### ISSUE TITLE
Question about changing language

### ISSUE THREAD

**Issue by freemail624** [opensourcepos/opensourcepos#1032]
If you have more users with different languages so every one of them want to use his language.
but the ospos support only one language to be the default for all users regardless of their languages.
So what about adding language to the employee table and allow every user to set and use the ospos with his language ?

**Comment by jekkos** [comment]
Sounds like a good idea. In that case we need to bind the language parameter to an employee record.

**Comment by jekkos** [comment]
We might need to do some more discussion on this design if you want this implemented. I currently don't need the feature so feel free to contribute.

**Comment by freemail624** [comment]
Yes this need more discussion. So I asked my to know the best way to do this.

**Comment by daN4cat** [comment]
This was implemented by @objecttothis
