### ISSUE TITLE
Receiving quantity & price

### ISSUE THREAD

**Issue by WebShells** [opensourcepos/opensourcepos#1190]
Dears,

When you receive a specific order from supplier, the cost price doesn't update in case it was changed by supplier and what if i got the same item for less price or higher price ? how it will be calculated in stock and which price it will take ? 
Can anyone advise regarding this ?

Thanks!

**Comment by daN4cat** [comment]
@WebShells Receiving has a number of issues, see #977, #943, #936, #544, #502, #404, #403 and #401.

It needs some love, somebody that takes full ownership of Receiving and makes all those changes.
I personally don't use it and therefore have not the time to make all the changes.

**Comment by jekkos** [comment]
Wow thanks for this elaborate issue list @daN4cat. Quite busy this week I have to make a deadline by friday, so not sure if I'll find the time to do code review on these new parts.

**Comment by daN4cat** [comment]
Don't tell me about deadlines I'm in a swamp at the moment. So much stuff and deadlines with my new job. Too much....

**Comment by odiea** [comment]
Have you enabled Calculate Average Price (Receiving) in Store Config.

**Comment by Talkyn** [comment]
I have been fiddling with 3.1.1 for days, and despite going over the config settings several times did not notice there was a "Calculate Average Price (Receiving)" option under "General."

I was here to submit that function as a feature request, but now I know it is already there!

Maybe someone (like me?) that can't be of any use on the coding side should help with documentation.

**Comment by daN4cat** [comment]
Yes, help with documentation is welcomed!
