### ISSUE TITLE
Add New/Custom Customer Columns

### ISSUE THREAD

**Issue by pimpurmom08** [opensourcepos/opensourcepos#1193]
Hello is there anyway to add custom columns in the "Customers" tab? Such as "Balances", "Birthdates", etc.
I would like to import lists of my customers but i need these kinds of columns and more. Please advise. 
Thank you!

**Comment by SteveIreland** [comment]
I believe that @jekkos has plans to introduce a new feature to OSPOS that provides for defining custom properties to primary tables, but I don't know what the planned delivery date is for that.

**Comment by daN4cat** [comment]
That's for items not customers.

**Comment by SteveIreland** [comment]
Oops ... sorry .... but it does sound like an opportunity!

**Comment by daN4cat** [comment]
@SteveIreland we live in a land of opportunities but not the one with (free) "milk and honey"...

**Comment by mckaygerhard** [comment]
yes this is same as #1983

**Comment by jekkos** [comment]
duplicate of #3118
