### ISSUE TITLE
Show Tickets in opensourcepos

### ISSUE THREAD

**Issue by elhui2** [opensourcepos/opensourcepos#1196]
Hello:

I want fork this project to add a system for sales of show tickets in one theater in México.

I'm using 
https://github.com/mateuszmarkowski/jQuery-Seat-Charts

I don't want break any license but I don't like the tracking_lib ... But don't worry I don't want remove the footer.

I need know something to modify opensourcepos? If you want I can share the changes..

regards!

**Comment by daN4cat** [comment]
You can untick the statistics checkbox to avoid any stats collection.

The map view would be nice for features like Dinner table that was added recently, I suppose.
But I would add all of that as an additional module or alternative to the current register.
