### ISSUE TITLE
categories expenses and Expenses  

### ISSUE THREAD

**Issue by asadjaved63** [opensourcepos/opensourcepos#1235]
Hi
i'm working on expenses module .everything working .but i'm stack in reporting.daily  weekly,monthly, yearly report... and profit after expenses deduction . can anyone help me regarding this? i will share all code,,,
thanks

**Comment by daN4cat** [comment]
It's a bit wholly, step by step what is that it's fine of the report you created and what it is not?
Have you checked some existing report?

**Comment by asadjaved63** [comment]
my Report Controller
`function summary_expense_categories($start_date, $end_date, $sale_type, $export_excel=0)
	{
		$this->load->model('reports/Summary_expenses_categories');
		 $model = $this->Summary_expenses_categories;
		$tabular_data = array();
		$report_data = $model->getData(array(
			'start_date'=>$start_date,
			'end_date'=>$end_date,
			'sale_type' => $sale_type));
		
		
		foreach($report_data as $row)
		{
			$tabular_data[] = array(
			$row['category_name'],
			to_currency($row['amount'])
			);
		}
		$data = array(
		"title" => $this->lang->line('reports_expense_categories_summary_report'),
		"subtitle" => date('m/d/Y', strtotime($start_date)) .' - '.date('m/d/Y', strtotime($end_date)),
			"headers" => $model->getDataColumns(),
			"data" => $tabular_data,
			"summary_data" => $model->getSummaryData(array(
			'start_date'=>$start_date,
				'end_date'=>$end_date,
				'sale_type' => $sale_type)
			),
			"export_excel" => $export_excel
		);

		$this->load->view("reports/tabular",$data);
	}`
`Model`
`public function getData(array $inputs)
	{
		$this->db->select('category_name, DATE(date) as date, sum(amount) As amount,');
		$this->db->from('expenses');
		
		$this->db->join('people', 'people.person_id = expenses.employee_id', 'LEFT');
		$this->db->join('expense_categories', 'expense_categories.expense_category_id = expenses.expense_category_id', 'LEFT');
		 
		$this->db->where('date BETWEEN "'. $inputs['start_date']. '" and "'. $inputs['end_date'].'"');

		  $this->db->group_by('category_name');
		  $this->db->order_by('category_name');
//var_dump( $this->db->get()->result_array() );
		return $this->db->get()->result_array();		
	}`
 All time data showing perfectly but current date and yesterday data  not showing.. dont know why need your helps

**Comment by adeola9848** [comment]
Yes
On Apr 15, 2017 13:39, asadjaved63 <notifications@github.com> wrote:my Report Controller
`function summary_expense_categories($start_date, $end_date, $sale_type, $export_excel=0)
{
$this->load->model('reports/Summary_expenses_categories');
$model = $this->Summary_expenses_categories;
$tabular_data = array();
$report_data = $model->getData(array(
'start_date'=>$start_date,
'end_date'=>$end_date,
'sale_type' => $sale_type));
	foreach($report_data as $row)
	{
		$tabular_data[] = array(
		$row['category_name'],
		to_currency($row['amount'])
		);
	}
	$data = array(
	"title" => $this->lang->line('reports_expense_categories_summary_report'),
	"subtitle" => date('m/d/Y', strtotime($start_date)) .' - '.date('m/d/Y', strtotime($end_date)),
		"headers" => $model->getDataColumns(),
		"data" => $tabular_data,
		"summary_data" => $model->getSummaryData(array(
		'start_date'=>$start_date,
			'end_date'=>$end_date,
			'sale_type' => $sale_type)
		),
		"export_excel" => $export_excel
	);

	$this->load->view("reports/tabular",$data);
}`

Model
`public function getData(array $inputs)
{
$this->db->select('category_name, DATE(date) as date, sum(amount) As amount,');
$this->db->from('expenses');
	$this->db->join('people', 'people.person_id = expenses.employee_id', 'LEFT');
	$this->db->join('expense_categories', 'expense_categories.expense_category_id = expenses.expense_category_id', 'LEFT');
	 
	$this->db->where('date BETWEEN "'. $inputs['start_date']. '" and "'. $inputs['end_date'].'"');

	  $this->db->group_by('category_name');
	  $this->db->order_by('category_name');

//var_dump( $this->db->get()->result_array() );
return $this->db->get()->result_array();
}`
All time data showing perfectly but current date and yesterday data  not showing.. dont know why need your helps

**Comment by daN4cat** [comment]
Try in the model:

$this->db->where('DATE(sale_time) BETWEEN ' . $this->db->escape($inputs['start_date']) . ' AND ' . $this->db->escape($inputs['end_date']));

**Comment by WebShells** [comment]
Interested in the model, awaiting your sharing once done... ! 
Thanks!

**Comment by daN4cat** [comment]
OK, this feature is now supported and in master. It will be part of 3.2.0.
In office view a person can create an Expense Category and then add Expenses and tag under a selected category.

Expenses can be viewed according to the selected range, similar to the Transactions from Sale.

Reports show the amount by Category.

**Comment by daN4cat** [comment]
Special thanks to @odiea for pulling the rabbit out of an old hat (branch), polish it to get it to work with 3.2.0 and then I completed the job.

**Comment by daN4cat** [comment]
Probably the expense row needs to be extended.
Thinking on, there should be a Supplier, VAT, Tax and a Declaration period like Quarter or month.

**Comment by daN4cat** [comment]
I haven't heard complaints so I assume this is working fine and therefore I close.

**Comment by odiea** [comment]
@daN4cat . Has the original contributor (appears to be @asadjaved63) been given credit for this module?

**Comment by daN4cat** [comment]
You are right, I forgot to add them. I'll do next days when back from my trip to Scotland.

**Comment by odiea** [comment]
Have fun.

**Comment by daN4cat** [comment]
done
