### ISSUE TITLE
Employee Permissions Bug

### ISSUE THREAD

**Issue by corslayth001** [opensourcepos/opensourcepos#1268]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information

OSPOS: 3.1.0 - 4f5ad57
OS: Arch linux
PHP: 7.0.14-1
MySQL: (Mariadb: 10.1.21-1)

### Expected behaviour

I have four employees and three stock locations(1 Cellar and 2 stores) then in employees permissions I selected: Customers, Items(All employees have access to all stock locations) and Sales(two employees sale in one Store and the other two in the other Store).

### Actual behaviour
If I only select one stock location in Sales permissions then in the sale module the stock location is different from the one I select but if I select two stock locations in sales permissions they can choose the stock location in the sale module and the stock count is ok.

### Steps to reproduce the issue
Get one employee grant him permissions for customers, Items(All stock locations) and just One stock location for sale, then in the sale module the stock location is different from the one you choose before. (Sorry for my english, I'm Spanish)

Thanks in advance,

**Comment by HassanAlyousof** [comment]
You are right, i tried it many times but it did not work

Also, when you try to assign a stock (warehouse) to an employee, it will not work. In my opinion this is very critical thing, it is kind of enhancement bug!!

Thank you

**Comment by daN4cat** [comment]
@jekkos is this an issue that needs to be fixed for 3.2.0?

**Comment by mckaygerhard** [comment]
not its not fixed

**Comment by RapidKiller** [comment]
Hi guys I have the same issue, I import items to only 1 stock location (the default stock location 1) the quantity is fine but as soon as i create a new stock location and i go and view my items it shows quantity 0 and i cannot select the first stock location as a filter. I then also have an issue where i add a new employee and give him full rights but it will not save the stock location 1 in his permissions even though i checked the box. Every time i test i have to restore from backup because it revokes permissions for that stock location and i have no access to the inventory module now - so frustrating.

**Comment by daN4cat** [comment]
Version?

**Comment by RapidKiller** [comment]
Hi I'm sorry i ended up going through some old threads and found a solution that worked for me about 10 minutes ago. It was related to having spaces int he naming convention for stock locations - as soon as i took the spaces out it worked fine. However is there anyway i can donate some money to have a function written?
