### ISSUE TITLE
HHVM

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#1272]
I read something about Facebook virtual machine to execute programs written also in PHP: http://hhvm.com/

Checking this website about Drupal using HHVM I can see that the performance results are quite good: https://forumone.com/ideas/running-drupal-on-hhvm/

There is a CodeIgniter fork leveraging HHVM: https://github.com/djchen/CodeIgniter-HHVM but it's 4 years old.

Wonder if something could be done to run OSPOS on HHVM but I read it associated more with nginx than apache.

Anyone else has a view on this?

**Comment by daN4cat** [comment]
Something more here and more recent about CodeIgniter and HHVM: https://github.com/busseyl/MaterialHackIgniter

**Comment by corslayth001** [comment]
@daN4cat @jekkos Hi Guys, I need some custom enhancements for OSPOS, I can pay for it, I would like to talk to you in private. Thank's in advance! Sorry for posting here, I do not see the need to create a new post

**Comment by jekkos** [comment]
@corslayth001 you  can email me on my address.. so I can see if I can help in any way. jeroen dot peelaerts at gmail ..

**Comment by daN4cat** [comment]
Some configuration hints: https://gist.github.com/shivaas/9354045

**Comment by daN4cat** [comment]
Some performance benchmarking HHVM vs PHP7: https://kinsta.com/blog/the-definitive-php-7-final-version-hhvm-benchmark/
Something more here: https://kinsta.com/blog/hhvm-vs-php-7/
