### ISSUE TITLE
Item Kit Question

### ISSUE THREAD

**Issue by leominojr** [opensourcepos/opensourcepos#1334]
Hello Good Day,

Is it possible that the item kit can be tendered on quantity?

Example.

Item Kit Name: Christmas Pack 1 
Item Components:
1. Apple : 5PCS
2. Wine : 2 PCS
3. Spaghetti: 1
4. Spaghetti Sauce: 1

When you tendered Christmas Pack 1
The item components should not be seen in the register. By which only the christmas pack and the quantity.

if you put christmas pack 1 and quantity 2
The item components will automatically change its quantity to:
1. Apple : 10 PCs
2. Wine: 4 PCS
3. Spaghetti: 2 PCS
4. Spaghetti Sauce: 2 PCs

Thanks for Understanding

**Comment by SteveIreland** [comment]
That's not supported by the item kit process.  Once the items associated with the kit are added then it's unfortunately necessary to change the quantities on the individual components.

**Comment by leominojr** [comment]
I cannot change the quantity of how many kits the customer will purchase. Is it possible for future?

**Comment by SteveIreland** [comment]
Yes ... if @jekkos and @daN4cat haven't banned me before then ... whenever "then" is.  It was something I wanted to do, but I was my first change and I wasn't sure I wanted to bite off a non-trivial database change.

**Comment by leominojr** [comment]
Thank you

**Comment by RamkrishnaMondal** [comment]
It's doable.....if the customer wish to buy say,  2 nos of 'Christmas Pack 1', just enter the kit twice in sales register.
