### ISSUE TITLE
for Pharmacy Stores

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1337]
I am using this application for my small medical store. Sometimes customer ask for only 1-5 tablets from a Strip of 10 tablets. So how can i manage this kind of sale , also handling the quantity during sale.
As of now sale module adds quantity 1 as default.

**Comment by nvk1990** [comment]
@bill-goldberg 
Hi.. Did you try updating the "Quantity Decimals" under Store Config--> Localization to the desired value(Maybe 2?). Also, when you update the quantity, consider it in batches the tabs comes in.

For example, if paracetamol comes in strips of 10 and Insulin comes in multiples of 5, use item description like " paracetamol 10 tabs", "Insulin batch of 5" etc. When you perform a sale, enter the decimal quantity and you should be good. I have tested this on some sample data and it looks ok.

Cheers!

![image](https://user-images.githubusercontent.com/28540763/27006669-a6ca0fdc-4e57-11e7-8f80-6092ebb0a8db.png)

**Comment by bill-goldberg** [comment]
Thank you @nvk1990

**Comment by bill-goldberg** [comment]
Would you please like to give any suggestion regarding handling batch numbers for a same medicine.
How to track particular batch during sale , receive ?

**Comment by nvk1990** [comment]
@bill-goldberg you can use the custom fields available under store config->General to hold the batch details and modify the code to track it during sale, receive and reporting.

Cheers!
