### ISSUE TITLE
Customer tables slow to load

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#1356]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Xampp or ubuntu server

### Expected behaviour
Customer tables should load faster then Items tables

### Actual behaviour
Customer tables take a while to load.

### Steps to reproduce the issue
My customer db has 19 customers.
![2017-06-23 15_22_54-](https://user-images.githubusercontent.com/10962177/27501070-74e833d8-5828-11e7-9f51-794d27285d2f.png)
I test with 119 Items.
![2017-06-23 15_23_38-](https://user-images.githubusercontent.com/10962177/27501094-907fe582-5828-11e7-83ca-ab6ac7064776.png)

**Comment by daN4cat** [comment]
@odiea that's strange, I tested and the difference for me with large customer numbers and large number of items is of just 100ms.
It's true customer is slightly slower, but that's due to the lack of a dimensional table to contain customer name and stats.
Improving perfomance would require some time that I don't have right now.

**Comment by odiea** [comment]
I found the issue. I edited out this code and it's back to being fast again.
```
foreach($customers->result() as $person)
		{
			// retrieve the total amount the customer spent so far together with min, max and average values
			/*$stats = $this->Customer->get_stats($person->person_id);
			if(empty($stats))
			{
				//create object with empty properties.
				$stats = new stdClass;
				$stats->total = 0;
				$stats->min = 0;
				$stats->max = 0;
				$stats->average = 0;
				$stats->avg_discount = 0;
				$stats->quantity = 0;
			}*/

			$data_rows[] = get_customer_data_row($person, $stats, $this);
		}

**Comment by daN4cat** [comment]
you should get an error because $stats is not existing.
So the Customer->get_stats is slow. I would need to check that SQL query.

**Comment by odiea** [comment]
I just deleted the show empty stats.
```
public function search()
	{
		$search = $this->input->get('search');
		$limit  = $this->input->get('limit');
		$offset = $this->input->get('offset');
		$sort   = $this->input->get('sort');
		$order  = $this->input->get('order');

		$customers = $this->Customer->search($search, $limit, $offset, $sort, $order);
		$total_rows = $this->Customer->get_found_rows($search);

		$data_rows = array();
		foreach($customers->result() as $person)
		{	
			$data_rows[] = get_customer_data_row($person, $stats, $this);
		}

		$data_rows = $this->xss_clean($data_rows);

		echo json_encode(array('total' => $total_rows, 'rows' => $data_rows));
	}

**Comment by odiea** [comment]
I left public function get_row($row_id) alone and stats are showing fine and not showing errors.

**Comment by daN4cat** [comment]
it shows 0 to all customers for sure.

**Comment by daN4cat** [comment]
the stats should be saved in the customers database everytime there is a transaction so it's quick to fetch. How it's done at the moment it needs to calculate line by line checking all the historical and calculating.
Not efficient at all. Get_stats was initially created only for the modal, then I extended to the table forgetting about the simplistic design behind it.

**Comment by daN4cat** [comment]
Maybe I can make it optional for the table so people can have control. Later it needs to be redesigned for better performance.

**Comment by odiea** [comment]
This is what I edited out of search. Just wondering why in search it was necessary to create 0 stats?
			if(empty($stats))
			{
				//create object with empty properties.
				$stats = new stdClass;
				$stats->total = 0;
				$stats->min = 0;
				$stats->max = 0;
				$stats->average = 0;
				$stats->avg_discount = 0;
				$stats->quantity = 0;
			}
If I am the only one to notice this I would leave the present code alone.

**Comment by daN4cat** [comment]
You commented out even this:

`/*$stats = $this->Customer->get_stats($person->person_id);`

**Comment by odiea** [comment]
yes but that was an error on my part. It was just public function search that was giving me the issue.

**Comment by daN4cat** [comment]
So I'm lost now.... what did you change?

**Comment by odiea** [comment]
I removed the following from public function search
```
if(empty($stats))
			{
				//create object with empty properties.
				$stats = new stdClass;
				$stats->total = 0;
				$stats->min = 0;
				$stats->max = 0;
				$stats->average = 0;
				$stats->avg_discount = 0;
				$stats->quantity = 0;
			}
It now looks like the following
public function search()
	{
		$search = $this->input->get('search');
		$limit  = $this->input->get('limit');
		$offset = $this->input->get('offset');
		$sort   = $this->input->get('sort');
		$order  = $this->input->get('order');

		$customers = $this->Customer->search($search, $limit, $offset, $sort, $order);
		$total_rows = $this->Customer->get_found_rows($search);

		$data_rows = array();
		foreach($customers->result() as $person)
		{	
			$data_rows[] = get_customer_data_row($person, $stats, $this);
		}

		$data_rows = $this->xss_clean($data_rows);

		echo json_encode(array('total' => $total_rows, 'rows' => $data_rows));
	}

**Comment by daN4cat** [comment]
@odiea that cannot be right. `$stats` comes from `$stats = $this->Customer->get_stats($person->person_id);`

**Comment by odiea** [comment]
Yes this was not touched.
```
public function get_row($row_id)
	{
		$person = $this->Customer->get_info($row_id);
		// retrieve the total amount the customer spent so far together with min, max and average values
		$stats = $this->Customer->get_stats($person->person_id);
		if(empty($stats))
		{
			//create object with empty properties.
			$stats = new stdClass;
			$stats->total = 0;
			$stats->min = 0;
			$stats->max = 0;
			$stats->average = 0;
			$stats->avg_discount = 0;
			$stats->quantity = 0;
		}
		$data_row = $this->xss_clean(get_customer_data_row($person, $stats, $this));
		echo json_encode($data_row);
	}
So you are suggesting that if no stats are found search should create stats.

**Comment by odiea** [comment]
I will close this again.

**Comment by daN4cat** [comment]
I need to add the option to enable/disable it, so I leave it open, but again I don't believe the code you copied & pasted above is correct.
A proper fix will come with 3.2 or later when I find the time to fix database data model properly.

**Comment by odiea** [comment]
If you get a chance you could look at Application/Controllers/Customers.php > This is where I made my changes to only public function search().

**Comment by jekkos** [comment]
Same for this one, it pops up on my radar for 3.1, but for me this is more something we should tackle in a 3.1.1 release (as there will be other bug reports probably)

**Comment by odiea** [comment]
@daN4cat I just installed ospos 3.2 into a Ubuntu server with mysql instead of mariadb and the Customer tables load great. Must be a Mariadb issue

**Comment by mckaygerhard** [comment]
mariadb made a lookup dns name resolving.. u must disable that in my.conf... its not a mariadb issue

**Comment by odiea** [comment]
Thanks for the suggestion but it made no difference. Also it is just the Customer tables that load slowly.

**Comment by daN4cat** [comment]
Yep the way stats are retrieved needs optimisation. I know it's not the best solution at the moment.

**Comment by daN4cat** [comment]
I don't see finding the time to improve this by 3.3.0 so move to 3.4.0.

**Comment by daN4cat** [comment]
It looks fine to me and I have a test table with about 2000 rows.
Not sure how big this can get but it's acceptable.

I close.
