### ISSUE TITLE
Report Display & Print Formatting

### ISSUE THREAD

**Issue by dennis-in-pdx** [opensourcepos/opensourcepos#1361]
I recently did a rollout of version 3.1.0 - 4f5ad57 for a non-profit thrift shop.  Along the way, I found that most reports were excessively wide for our older monitors and also for landscape printing.  Similarly, sales and receivings receipts were too wide for portrait printing as was done by the prior desktop program which OSPOS replaced.  I wanted to use CSS styles to reduce widths for individual reports, but found it nearly impossible to specify the CSS selector because of the huge nesting level of .div.s below an available unique id or class.  My solution for this was to set a PHP variable $container_id in application/views/partial/header.php to assign as the id for the .div. having the container class, then setting that $data['container_id'] in every PHP file that called partial_header.  That allowed for CSS selectors that were much simpler. 

My questions: Is there any interest in this work I did?  If so, what's the best way to indicate those changes?  (I'm a newbie with Github.)

**Comment by daN4cat** [comment]
Have you created just one I'd covering both screen and print cases or are those separate?
For the receipts you could have created a different php and add it to the list of receipts.

**Comment by jekkos** [comment]
It would certainly be nice to have the screen more responsive and adapter to different screen and print sizes. Alas I'm no real UI expert so would be glad if someone else can contribute this to the project. I guess that some rework of the html might be needed to make it flexible enough.

**Comment by jekkos** [comment]
So div nesting is one thing, but I wouldn't want to pollute our serverside code with too much of a view logic. I know CSS3 supports quite some things that allows one to make responsive designs easily..
