### ISSUE TITLE
[New Feature/Issue] Search result variations

### ISSUE THREAD

**Issue by benchonaut** [opensourcepos/opensourcepos#1374]
@jekkos @daN4cat @SteveIreland 

Hello , 
in a recent Setup ( OSPOS 3.0.2, most recent MariaDB),

the user has the Problem of finding "too much" , 
because full text search returns SQL "LIKE" Results, 
so if you enter "OM" it will find any result containing "OM" , even in the Word ,
but does not return the items starting with "OM" or containing " OM " first (sorting btw).

Firstly i removed the "remove spaces"-function from search , so user can at least search for 
" INK " to find e.g. "Black Ink" instead of "Pink Pen"

I tracked down the SQL-Statements in the underlying CodeIgniter-database code ->
application/models/Item.php Line 137-197...

and now the question is if there is a proper variant to return results from multiple searches ,
e.g. 

first search for "WORD%"     ( $this->db->like('name', $search,'after'); ) (you can decide where the % comes in CodeIgniter like statements )
then search for "%WORD"    ( $this->db->like('name', $search,'before'); )
then search for "%WORD%" ( $this->db->like('name', $search,); )

and combine the results WITHOUT sorting them ( e.g. https://stackoverflow.com/questions/32535014/php-codeigniter-merging-query-results-before-foreach-loop -> and then merge the result objects from this->db->get() ).

I guess i am not the only one with this problem.

Regards

**Comment by daN4cat** [comment]
We discussed the possibility to have smarter ways to perform searches adding something in the search box, but that will require time that we don't have.
So at the moment it is what it is and until now we got no major complaints.
