### ISSUE TITLE
Discount as value not as percentage

### ISSUE THREAD

**Issue by bmghandi** [opensourcepos/opensourcepos#1381]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add a x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   7.x
- MySQL or MariaDB version is:   MySQL 5.7
- OS and version is:   Ubuntu 16.4
- WebServer is:  Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   None

### Expected behaviour
OK

### Actual behaviour
OK

### Steps to reproduce the issue
None

Hi,

I searched the issues database and found that the issue of discount NOT as a percentage was discussed a few times, but there was no definite answer for those who wish to have it not as a percentage. One such discussion for example is on this link:  #261, #286 and #302.

This is a very important issue for me because in my store, discount is hardly given as a percentage.  Rather, a certain amount is occasionally deducted to customers. An ideal UI will allow the user to choose which case applies, whether as a percentage or not using a say a radio button.  I suggest the developers should again re-consider this issue because giving discount amount (not as percentage) is fairly common especially is family/private/small scale businesses. 

While waiting for a formal solution on this issue, I have started to modify my installation to have a temporary solution, but I run into a problem for which I need some guidance please.

I updated the function **get_item_discount** inside the file: **ospos/application/libraries/Sale_lib.php** to simply return the discount as follows:
`	public function get_item_discount($quantity, $price, $discount_percentage)
	{
		// $total = bcmul($quantity, $price);
		// $discount_fraction = bcdiv($discount_percentage, 100);

		// return bcmul($total, $discount_fraction);
		return $discount_percentage;
	}
`
However, this has only partially solved my problem.  As you can see in the screenshot below, the payment section of the Sales screen is now correct, with $50 deducted as a discount for each of the two items, giving the correct net total of $850 (950-100 = 850).  But the left side of the screen where the items are listed is still interpreting the discount as a percentage (50% of the price instead of $50). The same problem also shows up in the receipt, where the total payment is correct but the cost of the individual items is wrong.

So my question is, which other file do I need to edit to have the discount treated as a value rather than as a percentage for each of the individual items in a transaction.

Thank you very much in advance for your support.
![salesscreen](https://user-images.githubusercontent.com/29827013/27852214-b8d8c338-610a-11e7-87c3-82bf3f5afc06.png)

**Comment by odiea** [comment]
@daN4cat @jekkos I got this figured out but I need an app config name for it. Currently Receipts, Takings, Detailed and Summary Reports are showing the same values. I plan on not showing the other discounts in Customer and Store config once this is enabled. Preferably something already in the language files.

**Comment by SteveIreland** [comment]
I don't think it is a simple as this.  My guess is that you have a significant queue of problems lined up for you.

**Comment by daN4cat** [comment]
Is the discount by item or against the total,?

**Comment by bmghandi** [comment]
It is by item.

**Comment by daN4cat** [comment]
And do you want fixed discount or % discount, or both at the same time?

Anyway to change all the discount logic from % to fix amount there are different parts to change, not only sale register but also receipts/invoices and all the database tables.
Quite some work....

Yet another example where things should be more a composition to items rather then being part of the cart item itself.
The cost of changing and adding feature is a sign of how the technical debt is now kicking in and slowing us down. A software engineering manual classic.... :-)

**Comment by bmghandi** [comment]
Many thanks for your kind responses.

I would love to have the option of choosing one or the other.  But if I had to choose one, I would prefer the fix amount rather than % as that is the most prevalent in my situation.

In pursuit of my temporary solution, while still hoping the developers will take a serious look at this issue, I have managed to now have the cost of items evaluated correctly by making the following changes, in addition to the change I made to the **get_item_discount** function as I showed in my earlier post:

1.  I updated **ospos/application/libraries/views/sales/register.php** by changing the line of code:
`<td><?php echo to_currency($item['price']*$item['quantity']-$item['price']*$item['quantity']*$item['discount']/100); ?></td>`

to

`<td><?php echo to_currency($item['price']*$item['quantity']-$item['discount']); ?></td>`

So the sales screen now looks OK at least for the "Sale" mode of the register.

2.  I updated **ospos/application/views/sales/receipt_default.php** to print the discount correctly, this involved making minor changes to the ospos/application/language/en/sales_lang.php so that % is not printed for the discount line in the receipt.  

So the receipt is also OK now.

The next problem I now have is with the "Return" mode of the register in the Sales screen.  If a previous transaction is returned, the discount amount is still subtracted from the cost which is already negative, thus making the total wrong.  It should have been -(cost - discount) instead of -cost-discount.  See the below screenshot for an example.
![salesscreen2](https://user-images.githubusercontent.com/29827013/27906386-d0f4fe60-61ef-11e7-8100-216a9e564ac5.png)

Any direction on which file to edit to solve this problem is much appreciated.

Thank you.

**Comment by njengam** [comment]
Hi bmghandi 

Did you manage to find a complete solution for all the issues you encountered if so please share with me. as am currently trying to setup the same

**Comment by ridlomfahmi** [comment]
Hi bmghandi

Have you solved your problem? i have same problem like you, i wish you can share your solution here. 

Thank you

**Comment by bmghandi** [comment]
Hi,

Unfortunately, I did not.  If you find a solution please share with me as
well.

Thanks.

**Comment by anasiqbalkhan** [comment]
Hello, I have solved the solution ... /libraries/Sale_lib.php line 947 function name public function return_entire_sale($receipt_sale_id) add minus sign before $row->discount_percent ... 
so it should be -$row->discount_percent just like -$row->quantity_purchased.

Check and let me know I am good or not

**Comment by odiea** [comment]
This feature is already in the unstable 3.3.0. You can use either or both on a Sale now.

**Comment by anasiqbalkhan** [comment]
> This feature is already in the unstable 3.3.0. You can use either or both on a Sale now.

Hi, from where i can get the setting ?

**Comment by odiea** [comment]
You will have to download the bintray most current version. It's is not a simple copy and paste. You will have to upgrade your current version.

**Comment by erastus** [comment]
@WebShells could close, this is resolved in version 3.3.0
