### ISSUE TITLE
Tax 1 and Tax 2 in New item form gets swapped while updating the item.

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1388]

**Comment by bill-goldberg** [comment]
![snapcrab_noname_2017-7-10_11-48-1_no-00](https://user-images.githubusercontent.com/23611136/28005108-811132b8-6566-11e7-9710-6f5fe78e4519.png)
![snapcrab_noname_2017-7-10_11-48-12_no-00](https://user-images.githubusercontent.com/23611136/28005107-810e72da-6566-11e7-9d4e-914badc364df.png)

**Comment by daN4cat** [comment]
@bill-goldberg what if you put a non-zero value in the default?

**Comment by bill-goldberg** [comment]
i don't want to assign any digit for tax by default except 0.
