### ISSUE TITLE
Call a Rest service when Completing a sale that has Credit Card payment method

### ISSUE THREAD

**Issue by morra2020** [opensourcepos/opensourcepos#1400]
### Installation information

- OSPOS version is: 3.1.0 
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   ( 7.1)
- MySQL or MariaDB version is:   (MySQL 5.7)
- OS and version is:   (Windows 10)
- WebServer is:   (Apache 2.4)
- (If applicable) Installation package for the LAMP/LEMP stack is:   ( XAMPP)

### Question

I am relatively new to PHP and i was wondering whether it would be possible to call a rest service that i will host (application/json) on another server to capture the sale id, payment_amount (specific to this sales_credit method only)

My service will respond with result : 0 or 1. When its 0 complete the sale, however when its 1 show an error message and not complete the sale. 

This must only happen if credit card is selected as one of the payment methods for the sale.

My service will manage the floor-limit on acceptable values for credit card payments via standalone.

**Comment by jekkos** [comment]
see also #864

**Comment by daN4cat** [comment]
@morra2020 of course it's possible, just a matter of finding some good soul to implement it OR you learn PHP and OSPOS and add the functionality.
I don't want to sound funny but that's the reality here.
