### ISSUE TITLE
Lookup field to search for more than the barcode or name

### ISSUE THREAD

**Issue by petercdee** [opensourcepos/opensourcepos#1404]
### New Feature / Enhancement

Multiple barcodes or plu/sku numbers

Would it be possible to lookup for products on fields other than the barcode and name? 

Items may have more than one barcode and even sometimes a PLU or SKU number. Sometimes the supplier changes packaging and you want to be able to add more barcodes for the item. Currently you can use a custom field to record the extra barcode but the Sale Screen lookup box can not lookup an item based on the stock items custom field. 

Thoughts?

Thx PD

**Comment by daN4cat** [comment]
I would create the item with the new PLU/SKU to make a distinction as even the cost price might be different.
How many products do you get with "multiple codes"?

**Comment by petercdee** [comment]
Ideally you don't want to keep creating a new stock item for a packaging change. Could create an excessively large stock table for any changes. The historical reporting is better if it is under the one code. Also the average cost price is better under the one code. 

Regarding how many "multiple codes", there are three main codes for any one stock item a shop keeper would use. The barcode on the packaging, the supplier code (this is the language the suppliers talk when you are ordering) and then an in house PLU number. If you could search for items on those three fields you would cover 90% of the cases.
