### ISSUE TITLE
Personnel check in / check out tracking 

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#141]
Have you ever thought about fixing timeclock-punchclock and integrating it into OSPOS  or at least get it working correctly for OSPOS users to use?

**Comment by jekkos** [comment]
You mean the 'real time' clock feature?

**Comment by daN4cat** [comment]
Is this to get a clock on the top right bar to show real time?

**Comment by odiea** [comment]
This is a company time clock  where employees clock-in or out to show how many hours they worked.  There is a more current version but it's quite buggy .http://timeclock.sourceforge.net/screenshots.php.
I had no problem locating real time clock code for ospos.

**Comment by daN4cat** [comment]
Gets complicated, figure out you have multiple shop assistants logging in and out. What time do you track?

That feature goes a bit beyond the stock management and cost / sales tracking story.

**Comment by jekkos** [comment]
This feature is something I'll be adding in scope of the multistore enhancements. I'll add an audit logging table in this case

**Comment by RyanfaeScotland** [comment]
@daN4cat I would think that it would be separate from the login / logout feature (or possibly yet another configurable to join the two). User logs at the start of their shift, hits the clock-in button, logs in and out throughout the day, logs in and the end of their shift and hits the clock-out button.

Could spice it up a bit with automatic checks so if the user logs in but hasn't clocked in it prompts them to do so, user logs out but hasn't clocked out it prompts them to do so (reckon the second one would be annoying but its just an idea).

**Comment by jlctmaster** [comment]
Hello I have seen this requirement and I was struck because it is a very required functionality in any POS system, for the control of opening and closing of cash per user, this way you can control what is the change of shift for ATMs , I am using this software a lot and therefore I am very interested in contributing.

**Comment by daN4cat** [comment]
Yes, it would be great and see even this #440.

If you want to work on this it would be a great contribution indeed.

**Comment by daN4cat** [comment]
And check #505 too...

**Comment by daN4cat** [comment]
And maybe #150 too

**Comment by WebShells** [comment]
Being Discussed in #2825
