### ISSUE TITLE
Reportico

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#1433]
### Question 

I have been tasked to generate some reports out of the system and a quick search of the issues database found that Reportico seemed to be the preferred reporting tool of choice, so I dove right in tonight, installed it and started generating reports.

My question is are there any firm or tentative plans to integrate Reportico with OSPOS?

**Comment by daN4cat** [comment]
Yes, I started working on it and an integration with Codeigniter and composer but I'm pending on Reportico guy to finish something is working as next step.

**Comment by daN4cat** [comment]
See https://github.com/daN4cat/codeigniter-reportico

**Comment by daN4cat** [comment]
This is the PR I'm pending on to sort out the composer dependency and tidy up of the architecture: https://github.com/reportico-web/reportico/pull/16

**Comment by daN4cat** [comment]
BTW, I just found this new library/project for CI that might be a better option for an integration: https://bitbucket.org/vikseriq/ciportico

@SteveIreland maybe you can give a try to that one?

**Comment by SteveIreland** [comment]
You're just trying to give me something to do so that I stay out of trouble.  But it won't work!

Yes, I'll give it a try.  Thanks!

**Comment by daN4cat** [comment]
Alternative is to wait for me to do something about that....

**Comment by daN4cat** [comment]
..... eventually

**Comment by daN4cat** [comment]
What I can also do is import that code in Github and wrap it in composer. Let see if I find the time.

**Comment by daN4cat** [comment]
I've imported Ciportico into a GitHub repo here: https://github.com/daN4cat/ciportico

**Comment by RamkrishnaMondal** [comment]
Hope, this Ciportico thing will also be useful in generating the reports, required for indian users.

**Comment by daN4cat** [comment]
@RamkrishnaMondal good to know, hope people from India (especially hackers planting their Copyright at the bottom of pages - not you -) will pay a beer for the work...

**Comment by SteveIreland** [comment]
I believe @daN4cat is waiting on a new branch of Reportico to become available before integrating it with OSPOS.  It should be coming soon based on the discussion surrounding it.  https://github.com/reportico-web/reportico/pull/16

**Comment by daN4cat** [comment]
Yes, indeed. Also I need to find the time to deal with this change.

**Comment by daN4cat** [comment]
This will be a bit of work.... I can already see it. Time for some fuuuuuuuuunnnnnnnnnnnnn :-)

**Comment by daN4cat** [comment]
I gave a try to ciportico yesterday but it's not ideal, there would be some work to get things done properly. I prefer to wait for the new reportico architecture with composer installation and then start from there.
I would double the work to fix ciportico and then move to new reportico architecture composer based.

**Comment by SteveIreland** [comment]
I can wait. Thanks for looking in to this

**Comment by SteveIreland** [comment]
3.3.0?   Oh my.  Didn't see that one coming.

**Comment by daN4cat** [comment]
I sense that we are close to release a 3.2.0 because there is not much more going on. Some extra fixes and a couple of language translations and we are good. It's probably better to have shorter release cycles.
Unless you are ready with the PO part?

**Comment by SteveIreland** [comment]
I've made progress on it but there is a lot left to do.

**Comment by daN4cat** [comment]
@SteveIreland do you prefer to move PO part to 3,3.0?

**Comment by SteveIreland** [comment]
I don't have a preference. If you move forward with publishing 3.2 then I will simply rebase my work. So far there haven't been any commits I've seen that will cause any conflicts

**Comment by guillermohaad** [comment]
Hi @SteveIreland , any progress to integrate Reportico?or Can someone give me some light? Thank you

**Comment by daN4cat** [comment]
No progress because the newer version of reportico using composer and etc. is close to release time. It doesn't make sense to work on an integration of something that is going through a massive rearchitecture.

**Comment by guillermohaad** [comment]
Hi @daN4cat , I agree with you
Thank you

**Comment by guillermohaad** [comment]
can someone give me a light at the end by inserting a menu option that takes me to an external URL but within OSPOS?
example: 
![image](https://user-images.githubusercontent.com/12921805/37120275-eb087f54-2227-11e8-8eb5-aa02d358c545.png)

**Comment by objecttothis** [comment]
@daN4cat it's been awhile on this.. Any update?  I think it would be nice for OSPOS to have a robust report builder.  My staff frequently ask me for reports that I have build by hand with MySQL, but with a robust enough report builder, would be easy for them to do themselves.  Like other things, I'd be glad to help, but I don't know what the status of things are.

**Comment by daN4cat** [comment]
No progress as I didn't have time.

You can always run Reportico outside OSPOS reading the same database.
Build the templates for your report and copy over later. But if you find the time you can try and integrate it in OSPOS.
I'll check over the weekend the branch and refresh it.

**Comment by daN4cat** [comment]
I don't think this integration will ever happen because there are security issues with reporting that don't seem to get closed.

Maybe some other solution could do instead.
