### ISSUE TITLE
Regular Database Backup

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1442]
I am a regular user of this OSPOS point of sale on my small grocery store.
And I also take database backup on a regular basis.
But I want that the backup should be from last backup time not the complete backup. As every week I have to take backup and it creates a backup from the beginning. I want it to create backup only for last 1 week... As for before that I  have already a backup.

**Comment by daN4cat** [comment]
@bill-goldberg we know you are regular OSPOS user :-) (judging by the number of requests you must be)

My thinking about this backup story is that you could consider backing up the whole MySQL database to a AWS S3 bucket.
In the case of my wife's business the whole VPS is backed up daily to AWS S3 overnight, with 4 weekly rolling backups.
The cost of storing this data on an AWS S3 bucket (many GBa) is 2 US$ a month!

So the cost of implementing a CDC (https://en.wikipedia.org/wiki/Change_data_capture) type of solution in OSPOS is high considering what I said above,

Now if you just want to have an OSPOS backup story being part of the code, maybe using something like this: https://github.com/psugand/CodeIgniter-S3 would allow you to take the zip and store it in your AWS S3.
Please be careful when you setup an S3 bucket and make sure you restrict access to in not only to your use user and key but also to you IP address only (or range if it's dynamic).

**Comment by jekkos** [comment]
I just use Cron and mysqldump on my nas to download a daily dump of the db.. use a sliding window of about a month to keep the data, works just fine.

Also have another failover instance that has the latest dump restored. During next restore there's a check to see whether the failover was used and so it knows that master data is in failover instance in that case

**Comment by daN4cat** [comment]
Oh good, you implemented a failover and automatic switch.
To be honest when I find the time I want to check the cost on AWS and see if using RDS or better Aurora is easier as full managed and elastic.

**Comment by jekkos** [comment]
If we really want to make it scalable I guess we need to look into Kubernetes, which is sort of defacto standard to make applications resilient and scalable these days. Docker cloud also seems to support horizontal scaling and can use AWS instances with docker daemon as backends.. plenty of options here

**Comment by SteveIreland** [comment]
Backups don't have a lot of value unless you can quickly restore them.  I have some experience with incremental backups and they aren't for the faint of heart in a recovery situation.  A full backup provides for simple recovery.  If you log the transactions since the last full backup then you could reapply the transactions after restoring from the last full backup and get pretty close to the point of failure.  But I don't see too many doing that.

https://dev.mysql.com/doc/refman/5.5/en/point-in-time-recovery.html

Is that what you're shooting for?

**Comment by DavidShoe** [comment]
I am running crashplan on my "server" box which is doing continuous backup.  I can recover things easily and go back a long way.  It costs a bit more but I am also backing up full machines with it.

**Comment by jekkos** [comment]
This is not something that should be tackled in OSPOS, but rather a sysadmin thing to setup.

**Comment by equinenigeria** [comment]
I will like to restore my ospoos backup. How I will I go about doing that. Thank you

**Comment by SteveIreland** [comment]
Try googling how to restore a mysql database.  It really isn't an OSPOS application issue.  However, I'll give you a tip that one of your steps should be to "SET FOREIGN_KEY_CHECKS=0;"   At least that has been my experience.  If you need more help please open up a new issue.   This ticket has been closed.
