### ISSUE TITLE
New OSPOS Starting Point for Office Apps

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#1490]
### New Feature / Enhancement

Since we are considering adding some additional modules for new features such as purchasing and  debt management/receivables it seems that we need a new starting point for these office functions.

"home" currently takes us to the primary OSPOS menu.  "office" should take us to the modules associated with the back office components of OSPOS.

If someone has already done this or has explored it I'd like to hear their thoughts about it.

I see OSPOS configuration, Taxes, Purchasing, Employees, messaging and Debt Management as being modules in the "office" application.

This will certainly require some tweaking to the underlying modules configuration it seems like the path of least resistance to drawing a separation of responsibilities between the customer facing components and the back office components.

**Comment by daN4cat** [comment]
You mean a distinction between till and back office capabilities.

If you have the same home canvas, you could have two groups and then the home is organised according to the groups. However I would leave flexibility in allowing people to add functionalities (modules) to one group or the other. For instance items can be used by both, as customers and etc.

**Comment by SteveIreland** [comment]
It's finally coming together.  It will be like walking in through the front door of the store.  Then those that know where the office door is and who have a key to it will be able to access the office modules.

In other words, logging in always takes you to the modules assigned to the home page.  Then you can go to the modules assigned to the office app.  The office link is manually entered (replacing "home" with "office") or is simply a link from favorites bar which is what I will be doing.

**Comment by SteveIreland** [comment]
I've started some documentation on the effort on the wiki at [Menus and Permissions](../wiki/Menu-and-Permissions)

**Comment by SteveIreland** [comment]
A pull request has been submitted for this change.  But it's primarily for testing and as a foundation for future development for additional modules such as purchasing, customer debt management, and vendor invoice reconciliation.  I don't expect it to be a 3.1 feature.

**Comment by daN4cat** [comment]
Maybe I can pull it in a feature branch

**Comment by daN4cat** [comment]
And thank you for the contribution

**Comment by daN4cat** [comment]
Covered by #1534.
