### ISSUE TITLE
$config['cookie_httponly']

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1498]
### New Feature / Enhancement
During my troubleshooting of CSRF and my server configuration I noticed that `$config['cookie_httponly']` is set to FALSE by default.  As far as I can tell the app is working fine with it enabled.  Is there a reason why it was set to false?  Setting it to true has the added benefit of the CSRF cookies (edited: and all other cookies) being appended with HttpOnly (see below)

`Set-Cookie | csrf_cookie_ospos_v3=EgKo_TvbI…ax-Age=7200; path=/; HttpOnly`

This is a good security measure to enable if we can as it mitigates many XSS attacks.

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MySQL 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP) FAMP 

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jekkos** [comment]
Think we'll need to do some regression testing as we rely on reading cookie data in javascript for some types of form submissions.. This might maybe break now so we'll need to verify first. Otherwise then I agree we should turn on this mitigation

**Comment by objecttothis** [comment]
@jekkos ok I wasn't aware that we were reading cookie data with JavaScript. I'm guessing it will break that, but regression testing should be able to quickly test that.

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by daN4cat** [comment]
XSS attack is another story, you can inject any js before reaching the user web browser and execute operations in the background on the user web browser.
See https://www.owasp.org/index.php/Types_of_Cross-Site_Scripting

CSRF uses an authenticated user browser to perform operations against the web server: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

They are different type of attack vectors.

**Comment by daN4cat** [comment]
BTW, we should set HttpOnly to true and test.

**Comment by objecttothis** [comment]
@daN4cat right. This is why the cookie_httponly flag is what I was suggesting turning on. I only came across it while troubleshooting the CSRF. I Didn't mean to imply they were defending the same attack vector.

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by daN4cat** [comment]
httponly cannot be true. As @jekkos explained js posts the cookie and at modal dialog time or any ajax call you get a failure because of CSRF protection.

**Comment by daN4cat** [comment]
So I would suggest to close this issue

**Comment by jekkos** [comment]
Or we find another way to send the csrf token using ajax

**Comment by daN4cat** [comment]
True... suggestions? But for 3.2

**Comment by objecttothis** [comment]
[https://stackoverflow.com/questions/28417781/jquery-add-csrf-token-to-all-post-requests-data](Check here) 
This guys is using ajaxPreFilter to do it.  I agree that it should be in the 3.2.0 milestone.

**Comment by daN4cat** [comment]
Moved to 3.3.0, not urgent.

**Comment by daN4cat** [comment]
Even if #1980 changes the way CSRF is managed, $config['cookie_httponly'] = TRUE doesn't work with Ajax calls.

**Comment by daN4cat** [comment]
@jekkos to confirm this is still an issue. I tested the other day.

**Comment by objecttothis** [comment]
@daN4cat perhaps this allows you to re-enable CSRF check on the login? #1535

**Comment by daN4cat** [comment]
This is fine now. I close.
