### ISSUE TITLE
Add multiple tax (4 nos) rate item wise, 

### ISSUE THREAD

**Issue by ajaykumarji** [opensourcepos/opensourcepos#1500]
Add multiple tax (4 nos) rate item wise or on total sale value

**Comment by daN4cat** [comment]
Not sure I understand, what do you mean with "4 nos"?

**Comment by ajaykumarji** [comment]
i mean, group of tax/ category of tax be one tax i.e.

1. Sales Tax State- Group
      Tax1  5%
      Tax2  5%
      Tax3  5%

2. Sales Tax Export- Group
      Tax1  6%
      Tax2  6%
      Tax3  6%

Like above, we can select any one for sales

Thanks

**Comment by daN4cat** [comment]
Have you checked what @SteveIreland added? Maybe you can see with him how to complete that work and get what you need.

**Comment by SteveIreland** [comment]
Is this a VAT tax situation?
