### ISSUE TITLE
Any one can give idea how to add Expenses module in menu separately like add customer

### ISSUE THREAD

**Issue by ajaykumarji** [opensourcepos/opensourcepos#1501]
Any one can give idea how to add Expenses module in menu separately like add customer and generate report date wise

**Comment by daN4cat** [comment]
Somebody gave source code for the expenses support, but it would need to be ported to latest 3.1.0 and polished.

We can make that code available only under the condition that you contribute it back and make it to work with 3.1.0.

**Comment by ajaykumarji** [comment]
yes definitely, i will contribute to introduce new module, idea so that OSPOS will be a not only POS but more then that like a small ERP based on double entry system of accounting.

**Comment by daN4cat** [comment]
@ajaykumarji ok, good. Here the branch containing that code based off 3.0.2: https://github.com/jekkos/opensourcepos/commits/feature/expenses

I never tested, just took it with the idea that one day we will add the feature.
So here you, first try to get it to work as it is based on 3.0.2 and then rebase it with 3.1.0.

Looking forward for you contribution, I guess you will have a bit of work to do so this will make 3.2.0 no earlier.

Many thanks for the help!

**Comment by jekkos** [comment]
Ok we'll have to check and see if it complies with our interface design standards..

**Comment by daN4cat** [comment]
Should be using the new js tables and etc. Of course we need to review the code and etc.

**Comment by daN4cat** [comment]
@ajaykumarji how are you getting on with this Expenses code and etc.? Some progress?

**Comment by odiea** [comment]
Looks like another misleading contributor.

**Comment by daN4cat** [comment]
well, as usual many just want, few really contribute.... :-1:

**Comment by mckaygerhard** [comment]
well @daN4cat contributing in a languaje that are not native to you its very tedious and dificult for people that have great ideas but not have the skills .. so let take more considerations right?

**Comment by mckaygerhard** [comment]
wee all have family, jobs and problems to pay attention.. that's are some important reason.. why some contributors let the work unfinished also poor motivation on code sharing
