### ISSUE TITLE
Barcode Number required to be unique

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1531]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MySQL 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Be able to add multiple items with the same barcode number.  For example if we have two of the same books in the store.  One is new and the other is used, so they are at different prices and two different wholesale amounts.

### Actual behaviour
I can't add an item if it has the same barcode number

### Steps to reproduce the issue
The database structure has ospos_items.item_number is an index but not required to be unique, which means this is not a database structure problem.  I believe the code just needs to be modified to not require Barcode Number to be unique.  I can submit the pull request but wanted to discuss the change here first to see if that was ok.  Is there a reason that barcode number must be unique?  For businesses like mine where it is acceptable to have multiple items with the same barcode, requiring it to be unique creates a problem.  In 2.0.2 this wasn't required, so it appears to have been introduced at some point along the way.

**Comment by SteveIreland** [comment]
And just to add my 2 cents to this discussion.  The item_id is our unique item identifier but that is automatically assigned by the system so it's not extremely useful as a business item identifier.  Not all items have barcodes so it's not useful as a consistent business item identifier.  In my world the distributor will have their item identifier and the vendor/manufacturer will have their item identifier.  What's usually printed on the package is the vendor/manufacturer item id and if available the UPC code will be included on the package.  So UPC might be scanned to find an item, but if the UPC isn't included on the package then we might enter the vendor item id.  And if that's not available we try to find the item by description.  The distributor item code usually isn't included on the package but is used for reordering.

**Comment by daN4cat** [comment]
I appreciate the problem but this will complicate the matter at till time because you'll get multiple with the same and it won't be one scan one item and straight process.

Also the risk is that people will reintroduce again and again the same item easily creating duplications. 

If you want to intrude such support it has to be optional otherwise it becomes a nightmare of sales assistant mistakes for others. I can already see it coming for my case. The less the best.

**Comment by objecttothis** [comment]
I'm ok with it being implemented as an option.  I can see that there are businesses that do it both ways. There are two things to note:
- Barcode scanners are programmed (through scanning specialized barcodes) to either hit enter after a scan or not inserting a newline after a scan.  Not inserting a newline after a scan allows the item to be scanned and then selected at till time.
- The second note is related to the first.   Currently search suggestions on the sales window currently only display the item name.  One of the customizations I had made for my fork of 2.0.2 was to to modify search suggestions to display item number | item name | and item price (see screenshot).  This is incredibly helpful because lets say a business is searching for a product by item name because the barcode won't scan.  Let's say there are multiple products with the same name but different barcodes and prices.  If the search suggestion results in the sales window only show the item name there is no way to differentiate and someone just has to guess.

**Comment by daN4cat** [comment]
The suggestion line format line is subjective, in my case I would need some attributes and not Barcode nor price.

**Comment by objecttothis** [comment]
So what if I implemented it in a way similar to the implementation of the barcode printer function where you can choose from three attributes to be displayed in the sales search suggestions?

**Comment by daN4cat** [comment]
Yes that would make sense, but it's better to wait for the attributes change to come in and then add this feature.

**Comment by objecttothis** [comment]
Sounds good
________________________________

**Comment by objecttothis** [comment]
@daN4cat what kind of timeline do we have on attributes changes?  I would like to move forward on customizable search suggestions, but if the attributes changes will make that code obsolete and the attributes changes will be somewhat soon I can wait.

**Comment by daN4cat** [comment]
@objecttothis we can close this, correct? WRT attributes, that is with @jekkos in terms of timeline and pushing to public OSPOS.
