### ISSUE TITLE
CSRF error at login time

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#1535]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 
- PHP version is: 7.1
- MySQL or MariaDB version is: MySQL 5.6
- OS and version is: CentOS 6.9
- WebServer is: Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:  N/A

### Expected behaviour

* Logout from OSPOS on day 1, login from same login page (no refresh) on day 2
* Enter user credentials into login page
* (ReCAPTCHA tick box ok)
* Enter OSPOS home page

### Actual behaviour

* Logout from OSPOS on day 1, login from same login page (no refresh) on day 2
* Enter user credentials into login page
* (ReCAPTCHA tick box ok)
* `403 Forbidden` Error due to invalid csrf token:
![image](https://user-images.githubusercontent.com/636048/29752543-0e4897d6-8b58-11e7-863e-ae16dcd6929d.png)

### Steps to reproduce the issue

* Use a HTTPS connection
* Logout from OSPOS on day 1, login from same login page (no refresh) on day 2
* Enter user credentials into login page
* (ReCAPTCHA tick box ok)

**Comment by daN4cat** [comment]
@jekkos the CSRF error at login time persists. I can systematically reproduce it now.
Probably 1 day is not necessary but try waiting few hours and I bet you can reproduce it.

**Comment by jekkos** [comment]
I understand that this is an annoying bug, but on the other hand I want to question a bit the urgency to have it fixed for 3.1. Is it really that much of a blocker ? Maybe we better postpone for a later bugfix release and invest time in getting 3.1 out of the door

**Comment by daN4cat** [comment]
@jekkos please look into this as it's bugging me every day I reopen my laptop because the login window was from the previous day. At Login time the token needs to be refreshed before posting it.

**Comment by jekkos** [comment]
Actually it's not a bug, but a feature.
Can you try setting in config.php the following.

`$config['csrf_expire'] = 0;`

**Comment by jekkos** [comment]
On the other hand if this resolves it, then I wonder why the token isn't expiring when using the application once logged in.

**Comment by daN4cat** [comment]
Probably it happens if you set the session timeout longer than csrf_expire. I will try that and let you know.

**Comment by jekkos** [comment]
Hmm ok I wonder whether we need csrf at login time.. I've done a quick google and there is still a recommendation to have it. Of course if the token expires after some time we'll be seeing this issue.

On the other hand you're right, it will never appear when logged in because session will probably timeout before. So technically the only way to tackle this would be doing a token refresh before the login actually happens, which might be a bit of a tedious solution.. or drop the csrf at login time completely, which I'm not really fond of either

**Comment by daN4cat** [comment]
I would say drop it from login page only. There is nothing to protect if you are not logged in or no?

**Comment by daN4cat** [comment]
Where is that they said it's better to retain?

**Comment by daN4cat** [comment]
Tricky story, but that means that probably it's better to refresh the token. I assume that if you put the session timeout to infinitive and csrf to a shorter time the user will get the login error in any web page.
So this is a general issue, not a login one only. I bet you said that already in your comment.

**Comment by jekkos** [comment]
Also interesting new solution : https://www.owasp.org/index.php/SameSite
We might want to implement it as external links to an ospos installation are rare

**Comment by daN4cat** [comment]
Agreed, but we should start with fixing this CSRF issue first...

**Comment by odiea** [comment]
Actually it's not a bug, but a feature.
Can you try setting in config.php the following.

$config['csrf_expire'] = 0; I tried this and it will not login. I set it to 86400 sec in a day and I will see what happens. Yes this if frustrating when you have to log in every 2 or 3 hrs if nothing is happening.

**Comment by daN4cat** [comment]
Indeed, it's annoying.

**Comment by odiea** [comment]
I left Firefox on the login screen and chrome on the Sales screen. Neither of them gave me any issues this am. Thats about 6 o r7 hours of idle time. I don't know what the security issues would be though.

**Comment by daN4cat** [comment]
It makes a difference as you can leave the sale window open forever without the need to log in.

**Comment by daN4cat** [comment]
I believe I fixed this and testing it, as it takes a long time to make sure it's working as expected.

**Comment by daN4cat** [comment]
Fixed and in master. I just excluded CSRF check from login page.
