### ISSUE TITLE
New Feature: Office Menu

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#1543]
### New Feature / Enhancement

To support  modules that might be considered to be part of "back office" functionality as opposed to "point of sale" functionality there needs to be a clear separation between storefront modules and back office modules.

Back office modules might be purchasing and vendor invoice reconciliation, debt management (a.k.a receivables).

More detail regarding the new menu system can be found on the wiki.

[Menu and Permissions](../wiki/Menu-and-Permissions)

**Comment by SteveIreland** [comment]
A pull request has been submitted for it and the wiki updated to reflect some of the last second changes.

**Comment by daN4cat** [comment]
Good and well done. Maybe I should import this into a feature branch. I assume this is the first part of the back office + purchase order story, correct? Maybe I can call the branch feature/backoffice

**Comment by SteveIreland** [comment]
Thanks, and yes this the purchase order system will be assumed to be located in the office menu.

My preference would be to go ahead and merge it in to master so that I don't need to rebase it every time the master branch changes.  I've found that activity quickly consumes a lot of my limited time - especially since I now need to spend a bit more time building out each of the sub-releases when I recreate the test environments.

I will also be submitting a pull request today for the work order feature which (because of conflicts in the configuration programs) I've based on the office menu (assuming it would soon be merged into master).

Technically neither work orders nor purchasing needs to be dependent on the office menu, but since I'll be deploying both to my production site this weekend it's more efficient in the use of my time to build and test one upon the other.  If you want them to be submitted as independent of each other then I'll need to cherry pick my work to build a special pull request.  But it doesn't look like I'll be able to find time to do that this weekend.

If at all possible please merge.  :-)

**Comment by daN4cat** [comment]
I merge to feature/backoffice and make that the 3.2.0. If nothing relevant pops up out of 3.1.0 requiring a 3.1.1 then I can move that to master. Anyway 3.1.1 should be minor fixes so rebasing will be easy. I'll try to keep up with that. OK?

**Comment by SteveIreland** [comment]
Okay.  Sounds like a plan.  Thanks.

**Comment by daN4cat** [comment]
Now in feature/backoffice. A bin tray build with the full zip should be ready within 30 min.

**Comment by SteveIreland** [comment]
A pull request has been submitted to correct a typo on the database.sql and tables.sql files.

**Comment by daN4cat** [comment]
In feature/backoffice branch

**Comment by daN4cat** [comment]
@SteveIreland I need to reopen this issue because there is some odd behaviour.
I removed the delete permission to a user for testing purposes and saved the user.
Result was that Gift Card was in Office and Employees disappeared from both views. Of course there was no means to reinstate Employees because I change the delete option to admin account. So I was forced to fix it in the database itself.
A similar thing happened yesterday, where I found an icon in Office instead of being in Home after I saved some configuration to my admin account user.

Can you please take an account change something save and do again few times that cycle and see if the change is consistent and nothing else disappear?
Not sure if it's a saving issue or lack of some default that it's not written in the database or else.

**Comment by daN4cat** [comment]
Other point, what should be the behaviour of the OSPOS on the left when you click on it and you are in Office view?

Currently it always switches to home. Should it be like that or should it go to Home or Office according to the current top bar context?

**Comment by daN4cat** [comment]
@SteveIreland I found how to create the problem, at least this happened twice to me.
Go to the user permission, uncheck Allow Delete and save. You get Gift Card in Office view and no Employees in either view anymore.

**Comment by SteveIreland** [comment]
I'll figure this out today. I had something similar happen to me while I was working on purchasing and I assumed I pushed something I shouldn't have. But now that you experienced the problem I have a pretty good idea of where the bug is

**Comment by SteveIreland** [comment]
A pull request has been submitted to fix this

**Comment by SteveIreland** [comment]
Regarding your earlier question I don't have a strong opinion but I would lean toward it retuning the user to the home page

**Comment by daN4cat** [comment]
Merge the PR, with regards to the second point let's leave it as it is then.

**Comment by daN4cat** [comment]
The commit fixed the issue. I close and thanks for the work done so far.

**Comment by objecttothis** [comment]
This is just an opinion but I think Reports should go in the Office menu.  What do you all think?

**Comment by daN4cat** [comment]
@objecttothis it depends, in the case of my wife they need access to reports from the till. I would say that it should probably go to both.
One day reportico will be only for the office view.
