### ISSUE TITLE
Currency Symbol Prepend or Postpend

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1564]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MySQL 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Currency symbol side would be automatically assigned based on locale information.

### Actual behaviour
Currency symbol always appears on the left side (prepended)

### Steps to reproduce the issue
This code starting on Line 17 of /helpers/locale_helper.php shows a method that I think is supposed to dictate the symbol and whether to prepend or postpend the symbol, but it only appears to set the symbol.

`function currency_side()
{
    $config = get_instance()->config;

    $fmt = new \NumberFormatter($config->item('number_locale'), \NumberFormatter::CURRENCY);
    $fmt->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, $config->item('currency_symbol'));

    return !preg_match('/^¤/', $fmt->getPattern());
}`

Does numberformatter actually give the information that dictates whether to prepend or postpend?

**Comment by daN4cat** [comment]
Try en_GB (£) and then Spain or France code to get (€). The former if prepend, the latter Postpend. If they work there is no general issue.

**Comment by objecttothis** [comment]
You're correct.  This means that the data that numberformatter is giving is incorrect.  I'll look into seeing what the deal is with ICU and why it's causing problems.

**Comment by daN4cat** [comment]
I already pointed you to a page where somebody from Colombia forced the currency to what they wanted. So it's a matter to try that trick and add it in the OSPOS configuration page.

**Comment by objecttothis** [comment]
Yes, and that would be a suitable workaround, but rather than code around bugs, I much prefer to correct the bugs.  If I'm unable to get the appropriate databases updated then I will go that route.

**Comment by daN4cat** [comment]
Sure, it was just a way to fix whilst waiting. So I put on pending this issue and assign to you.

**Comment by objecttothis** [comment]
I've submitted a ticket to the CLDR database which ICU uses for its localization formatting.  https://unicode.org/cldr/trac/ticket/10643

**Comment by daN4cat** [comment]
I would close this because it's not an OSPOS issue.

**Comment by objecttothis** [comment]
That's fine, we can close it.  I may end up needing to write code to work around it if they won't fix the database, but I can deal with it at that time.
