### ISSUE TITLE
Question about adding language line

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1566]
### Question

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

What is the procedure for adding a language string for new features?  Do I just submit a pull request with the language line added in each appropriate language file and an empty string, or is there a procedure by which this is done in weblate?

I'm working on the per-user language selection and need to add a string to employees_lang.php but didn't want to just submit a pull request for each language's employees_lang.php if that's not the way it should be done.

**Comment by jekkos** [comment]
Well it should be enough to add it in the source language (which is not en-US now) .. unless you have translations for other languages then it's ok to leave them empty and eventually I will sync the others using a script I have..

**Comment by daN4cat** [comment]
Question answered?

**Comment by jekkos** [comment]
Btw I'm upgrading to latest weblate version, migrating the whole thing on the way.. fingers crossed hope to have something up and running soon

**Comment by objecttothis** [comment]
@jekkos, you said the source language is not en-US now... did you mean that it IS en-US now? If I understand correctly I should add the string in the source language and then add the string in all other languages with an empty "". If that is right then we can close this as I understand everything.

**Comment by daN4cat** [comment]
He was referring to Weblate, not GitHub. But I assume he fixed that last night during the upgrade?

**Comment by objecttothis** [comment]
meaning I add the string in the source language on weblate and it propitiated to the other languages automatically?

**Comment by daN4cat** [comment]
So all languages in translation should be like en-GB, en-US, etc.

**Comment by daN4cat** [comment]
Weblate should show you an empty translation in your language when something is added to en-US.

The agreement is to use en-US as seed language. The rest of the group upgrades the other languages.
The annoying thing for me now is that to keep up to date en-GB I need to go through Weblate even if I develop my own feature.... and that bother me a bit :-(
