### ISSUE TITLE
Open source point of sale website

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1568]
This is just a thought but I would be glad to donate hosting space on my shared server if someone has or wants to pick up a domain name for open source POS. GitHub is fairly good so it's not a big deal, but having a domain name and server space would be attracting more users, which would attract more contributors and donations toward the project (paying for the domain, SSL cert if needed, etc), having a hosting space for weblate on that domain, having email specific to the domain. Other than that and the site could be fairly static so that we aren't spending a lot of time developing and maintaining. We could also have a demo install of ospos on that site.

Thoughts?

**Comment by daN4cat** [comment]
Not sure I fully follow the proposal.
Are you suggesting to host the code and a demo (+weblate and email)?
Or are you suggesting to have a server offering OSPOS as SaaS in multi tenant mode (e.g. selling the installation via subdomain to the main domain)?

The latter could be achieved deploying on AWS and I can work on the architecture for that as it won't be too difficult. Also if we go for RDS/Aurora we can have an high reliable and performant backend.
With autoscaling behind an application load balancer we can deploy and scale the business logic.

Again I can work on that if that's the idea. But whether that's a viable at least non-profit business it's a good question and requires a bit of work on the economics of the idea.

**Comment by objecttothis** [comment]
no, I was suggesting a simple face (website) to opensourcepos that allowed space for a demo, ospos specific email, weblate and links to github, donations, download, etc. I wasn't thinking to host the code as GitHub does great at that and SaaS would potentially be a lot of work. Also I think it might violate the ToS on the shared hosting I have.

**Comment by daN4cat** [comment]
SaaS solution would need an AWS (cloud) deployment. Not something for a shared hosting.
BTW, I would not recommend using a shared hosting for that.
I personally have a VPS for my wife's business to free from all the shared hosting nightmare (other tenants doing wrong things slowing down your node, etc.).
And having a demo running will face quite some hits impacting the rest of your applications.

**Comment by objecttothis** [comment]
Yeah, I don't think we should try to implement SaaS... We wouldn't necessarily need to have a demo running... it could just be a feature list and some screenshots.  It's just an offer to host it for free.  We would just need a domain name to point at it.

**Comment by daN4cat** [comment]
Fully appreciated, I just wanted to avoid loading your host. Let see what @jekkos thinks about it.
It's something we discussed in the past to have a domain and etc.

**Comment by jekkos** [comment]
Indeed I fully agree, a mini website with a quick overview of the features we have can make a huge difference and will indeed give the project more traction. I once planned to launch something that using simple jekyll templating and host it on github as you propose.

Also I've been thinking on this saas offering as well, one could easily scale using container orchestration with Kubernetes or Docker Swarm. Docker cloud supports this out of the box! One can also resuse the same database for different stores (using a minor tweak I have in mind) to make it more cost efficient. The only downside in my eyes is the support work. I'm already too busy with many other things so I don't really know if I will have enough motivation to do that. But I agree that it could be a nice additional service we could offer beside improving the software itself, that's also how most open source software companies run their business, they sell support and services aronud an OSS product. 

But first there is the website which might be quickly put together. As currently I receive some referral credit on DigitalOcean I could easily rollout a demo instance on the same host that has weblate setup (and that is financed by the DO referrals here)

**Comment by jekkos** [comment]
Also maybe I'd want to transfer the project on github to an organization name.. think that'll give a better overall impression on what we're doing here?

**Comment by daN4cat** [comment]
Setup a full K8 story takes time. And I would not recommend sharing the same database but having separate schema. You don't want to risk compromising the whole database for something wrong with one tenant.

Anyway, this is going to far. And indeed little time for this from my side too.

On having an org story for GitHub would probably make sense.

**Comment by jekkos** [comment]
Any opinions on which name for the organisation? Currenlty in we use ospos most of the time so maybe we can stick with that?
Same question for the domain name. 
Seems thats ospos.com and opensourcepos.com are already taken
I would suggest to use .net or .org, but then ospos or opensourcepos?

**Comment by SteveIreland** [comment]
Grab opensourcepos.net if you can.

**Comment by objecttothis** [comment]
I don't have strong feelings about which domain. I'll send the DNS server names to point it at.

**Comment by objecttothis** [comment]
NS1.ARVIXESHARED.COM

NS2.ARVIXESHARED.COM

those are the DNS servers. once I know the name of the name I will set it up and setup an SFTP login for whoever is needing it. I can also setup any email addresses needed and databases for weblate or whatnot

**Comment by daN4cat** [comment]
.org as it's an opensource and no profit

**Comment by daN4cat** [comment]
ospos.org is gone. opensourcepos.org might be free

**Comment by objecttothis** [comment]
agreed that .org is more representative of the type of project

**Comment by objecttothis** [comment]
I'm showing opensourcepos.org is available

**Comment by jekkos** [comment]
Ok will take that one then

**Comment by jekkos** [comment]
Ok domain registered, pointing to the nameservers you suggested, I'll try to see if I can make it refer to this repository

**Comment by objecttothis** [comment]
I created the addon domain opensourcepos.org and setup the ftp account as well as a webmaster email account.  I can also create any other emails and databases that are needed. I don't know who needs the ftp login information but I'd like to send that information by a more secure/private method than here.  Also @jekkos a whois lookup is showing me that the nameservers are not yet pointed at the nameservers I have above.  If you've already done it then it just might need time to propagate.  As far as I can tell, the following work needs to be done:
- Setup the basic static site with information about Opensourcepos, links to things (like github, downloads,etc), perhaps a knowledgebase, etc. 
- Weblate needs to get transferred and setup.  I could probably setup a subdomain if we want to do that... something like translate.opensourcepos.org
-  Setup any email accounts needed and if there are other DNS entries needed set those up.

In the interest of not suggesting something and then dumping the work off on someone else, I am willing to work on the static site but I think it would be good if the decisions about design, and backend were made by everyone.  I'd prefer to use a CMS for the site, but if there are strong opinions as to which, I'm fine.  I have experience with Joomla, and some wordpress, but for the most part CMS' are all the same and I don't mind learning a new one.  As to maintaining it, I don't know if it's best as a github project or just assign one or more maintainers, similar to weblate.

**Comment by daN4cat** [comment]
@objecttothis a static page is zero maintenance from a security perspective. Any CMS like Drupal, Joomla, Wordpress get constant security patches and they can be open to attacks.

Give the nature of what you probably want to add a 1 scrolling page could do. At least as a starting point. There are a number of free 1 scrolling pages.

**Comment by objecttothis** [comment]
Sounds good.  Am I right to assume that it would be best to match the "flatly" theme that ospos uses by default?

**Comment by jekkos** [comment]
Fine by me. I'd prefer to do a static site as well and use github and jekyll templates to have everything under version control.

Regarding DNS, maybe we are just fine pointing the main domain to the github page then for now? 
With regards to email, how should we setup MX records? I have a mailserver of my own and could add this domain to it, or maybe we use gmail which might be more reliable in the end?
Any ideas there?

**Comment by jekkos** [comment]
Project moved to new opensourcepos organization now

**Comment by objecttothis** [comment]
Yeah, for now setup the dns servers pointing at my shared server and we can setup an .htaccess file to redirect to the github page.  Once the page is live, we can take away the redirect.  Your idea of hosting the email on your mail server is a good one.  send me the details of the MX entry and I will set it up.  The only downside to using gmail is that unless you pay for google business, I think you'd have to use the gmail domain in the email, which is not as official.  It may be helpful to setup spf and dkim at some point, but that can be done later.

**Comment by SteveIreland** [comment]
:cry: I already miss jekkos/opensourcepos.

**Comment by guillermohaad** [comment]
Hi friends, I'm going to make my first donation; I live in Latin America and the payment is in Euros, I want to congratulate you and continue to lament this magnificent project.

The donation I must make in e button of Gitub:
Keep the Machine Running, If you like the project, and you are making money out of it on a daily basis, then consider buying me a coffee so I can keep ading features.

well deserved.Thanks

**Comment by objecttothis** [comment]
@SteveIreland haha... yeah it threw me for a loop at first, but it's sort of growing on me.  Not that I don't like jekkos ;)

**Comment by jekkos** [comment]
Ok I setup the DNS to point to gh-pages branch on the repository. Also weblate now has a separate A record as translate.weblate.org.

We could setup email addresses as well and then I'll have to configure my mail server to handle that.

**Comment by objecttothis** [comment]
did you mean translate.weblate.org or something else?  translate.weblate.org is returning a 404.  Just to be clear, do you want me to develop the 1 scrolling page static site and host it or no?  I'm fine either way.

**Comment by objecttothis** [comment]
it appears that github offers free hosting of jekyll pages, so I don't know that it would be necessary, however if we are wanting to host weblate on a server then we would need to have that hosted somewhere and just create a dns entry so that it's appearing on the opensourcepos.org domain

**Comment by jekkos** [comment]
ah yes indeed, that's what I did in the end. I made the static page here on github. You can edit it by checking out the gh-pages branch.
* opensourcepos.org
* translate.opensourcepos.org

the latter points to the DO weblate instance. I cover costs of that one with the referral fees. I could also add a demo instance to that host so people can peek around without installing first (which is always nice).

If you feel like adding some content to the gh-pages branch then go ahead!
I was planning to give everyone push access and ability to create project branches. For master I'd like to keep PR process as it's a useful thing for keeping code quality and discussions going

**Comment by objecttothis** [comment]
Super!  I'll take down the addon domain then on my shared host.  Let me know if in the future that is needed.  Weblate now gives me a different error message when I attempt to access the ospos translation
![weblate](https://user-images.githubusercontent.com/17935339/30309917-ea1d1d7a-979e-11e7-81cb-c63b8d73fa6e.JPG)
If possible I'd like to get my staff working on the Russian and azerbaijani translations tomorrow, so when you resolve it if you could also resolve the account I created for them as well that would be super helpful

**Comment by objecttothis** [comment]
Super!  I'll take down the addon domain then on my shared host.  Let me know if in the future that is needed.  Weblate now gives me a different error message when I attempt to access the ospos translation
![weblate](https://user-images.githubusercontent.com/17935339/30309917-ea1d1d7a-979e-11e7-81cb-c63b8d73fa6e.JPG)
If possible I'd like to get my staff working on the Russian and azerbaijani translations tomorrow, so when you resolve it if you could also resolve the account I created for them as well that would be super helpful

**Comment by objecttothis** [comment]
@jekkos I just thought I'd point out that www.opensourcepos.org routes correctly but opensourcepos.org does not.  You might want to fix the dns entry so that it routes correctly

**Comment by jekkos** [comment]
Ah ok indeed I'll make a wildcard dns entry instead

**Comment by objecttothis** [comment]
@jekkos I noticed that the gitter instance refers to jekkos/opensourcepos. Do you want to change that also to match opensourcepos/opensourcepos or just leave it the same?

**Comment by jekkos** [comment]
Hm ok dns wildcard should be fine. @objecttothis can you check weblate access? I've added you again to users list, something went wrong after upgrading django social plugin

**Comment by objecttothis** [comment]
same error. it says the project doesn't exist or is inaccessible to the public

**Comment by jekkos** [comment]
Ok think it as an issue with changed ACL on the project after upgrade. I checked again while logged in and it's visible now.

**Comment by jekkos** [comment]
Also you should be able to change/add translations as a user

**Comment by objecttothis** [comment]
Yes, it's working now in both my account and the account my staff will be using for translation.  After merging #1597 can you resync az-AZ, ru and en-US from github to weblate?  I believe the most accurate progress of translations for those three are on github and need to get to weblate.

**Comment by daN4cat** [comment]
Commit to master done.

**Comment by objecttothis** [comment]
@jekkos, any chance you could take the Azerbaijani and Russian Translations that daN4cat committed to the master and upload them to weblate?  That's the last thing I need to get my staff to finish the translations of Russian and Azerbaijani.

**Comment by objecttothis** [comment]
@jekkos, since there is only one change to the Russian, don't worry about that one.  I will make the change on Weblate and you can pull that down as per normal.  The Azerbaijani does need to be pulled from github to weblate though.

**Comment by objecttothis** [comment]
@daN4cat I'm not sure but I think the Azerbaijani translation in weblate is setup as az_AZ and github is setup as az-AZ.  I would recommend reworking the naming conventions in all the languages on weblate to match github.  Even if it isn't what's causing problems, it's nice for continuity.  I also noted that a recent commit you made created an az_AZ folder under languages.  Was that on purpose?

**Comment by daN4cat** [comment]
No that was not on purpose, I attempted to do a couple of things from Weblate but unsuccessfully. That should be removed as per my comment on @jekkos commit.

**Comment by daN4cat** [comment]
@jekkos we need to make Weblate open otherwise you become a bottleneck in the process. Just a factual deduction nothing personal to be clear.

**Comment by objecttothis** [comment]
Is anyone else experiencing problems with weblate timing out and not responding when updating translations?  My staff and I are attempting to work on the Russian translation but when submitting a translation change the browser just spins it's wheels and often doesn't load the next phrase

**Comment by jekkos** [comment]
I rebased the from the latest github version two days ago. Not sure but I'll try to rerun the indexation again.
@daN4cat I added you as weblate admin so now you can help troubleshooting in case of issues? Let me know if this works for you.

**Comment by jekkos** [comment]
@objecttothis indeed seems to be hanging on saving translations, looking into that now.

**Comment by jekkos** [comment]
Some translations still seem to refer to the old source files.. looks like this folder rename was not without impact..

**Comment by daN4cat** [comment]
I close this, there is no more to discuss.

**Comment by jekkos** [comment]
@mckaygerhard @daN4cat I think once wiki is organized, we should move it to gh-pages (jekyll) and embed it in the website. In that case we'd just be working on another git branch which is then the actual website

I don't know if there's anything existing that can port jekyll but it might be worth looking into.

**Comment by mckaygerhard** [comment]
hi @jekkos good idea, the wiki can build automatically using gh-pages, there's a "opensourcepos.github.io" that has garbage, really the project need better administration like those i manage take a shoot at https://github.com/MoonLightDE, was abandoned but the pages, the README's all the info are in need way to take in and follow.. i cannot said the same for opensource pos

but, @jekkos  the behaviour that you proposed seems too complicated, why not just use the docs directory so then normal human users can clone documentation alongside with clone the repository, not at all have "deep" knowledge..

when user visit the "future" pages, will seee the install, development etc etc pages and follow, and users clone the repository all the references are only online, the 70% of the users in the planet are not connected to the network men! inclusivelly me! i have a very limited internet connection and i manage by bytes, very xpensive! in some countries only USB-like devices are the only way to connected!
you guys thing that all the people in the work are just have the 4-thousand cores laptop with 4-thousand gigas of ram, but that not the real!
and that the really reason why some systems like M$ windows are most used, the piracy and these people that i mention found on those software the ways that cannot be found here!

**Comment by mckaygerhard** [comment]
hi @jekkos good idea, **the wiki can build automatically using gh-pages, there's a "opensourcepos.github.io" that has garbage**, really the project need better administration like those i manage take a shoot at https://github.com/MoonLightDE, was abandoned but the pages, the README's all the info are in need way to take in and follow.. **i cannot said the same for opensource pos**

but, @jekkos  the behaviour that you proposed seems too complicated, why not just use the docs directory (github pages can build from that event from a branch) so then normal human users can clone documentation alongside with clone the repository, not at all have "deep" knowledge..

when user visit the "future" pages, will seee the install, development etc etc pages and follow, and users clone the repository all the references are only online, the 70% of the users in the planet are not connected to the network men! inclusivelly me! i have a very limited internet connection and i manage by bytes, very xpensive! in some countries only USB-like devices are the only way to connected!
you guys thing that all the people in the work are just have the 4-thousand cores laptop with 4-thousand gigas of ram, but that not the real!
and that the really reason why some systems like M$ windows are most used, the piracy and these people that i mention found on those software the ways that cannot be found here!

**Comment by jekkos** [comment]
well my point was that also the website can be something to which each can contribute. Wiki is nice but if people start looking for a solution, a simple but nice landing page looks better and will inform non devs indeed about what ospos has to offer.

**Comment by jekkos** [comment]
Currently README.md is now visible on opensourcepos.org frontpage. Found an easy way to include it in a jekyll template. Found some [instructions](https://medium.com/@webprolific/using-github-pages-the-easy-way-bb7acc46f45b) to update the page on the gh-pages branch using [release-it](https://github.com/webpro/release-it).

**Comment by mckaygerhard** [comment]
well the README it's not the best choice to promote it to frond page! i think that we all can be made something similar to the already done in the wiki page!
