### ISSUE TITLE
Receipt not limiting description

### ISSUE THREAD

**Issue by waynebr76** [opensourcepos/opensourcepos#1579]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections "New Feature / Enhancement" and "Issue / Question / Bug".
2. Remove just the one of the two sections you don't need 
3. Remove this section as it's just a guideline
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [xx] I'm reporting an issue of an unmodified OSPOS installation
- [] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- x[] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
On previous versions the receipt would limit the description so all information could fit on the print out, I have looked in this version and the latest master and cannot see anywhere that limits the description characters on the receipt 

### Actual behaviour
The receipt does not print pricing etc on receipts where the description is too long

### Steps to reproduce the issue
Make a sale with an item with a long description - print receipt on receipt printer

**Comment by SteveIreland** [comment]
The default receipt only prints the item name and ignores the item description and alternate item description.

I sort of like the full name to appear so that there isn't a question about what is being purchased.  How about if we wrap it rather than losing information?

**Comment by waynebr76** [comment]
Hi wrapping it would be great, it must be the name its printing but I find quite alot of my name have many characters and then it does not print all of the info on the receipt

**Comment by guillermohaad** [comment]
hi @waynebr76 
some time ago I had a similar problem, look at this issues
 printing to sale the font comes out very small # 1634

**Comment by waynebr76** [comment]
Thanks will take a look

**Comment by SteveIreland** [comment]
I just retested this in the current version and it is wrapping the text (at least in the print preview).  I'll retest it when I'm near a real printer (later this evening),but it appears to be working in the current release.

![image](https://user-images.githubusercontent.com/23066623/33241435-3aae9cc6-d293-11e7-83fe-b9e989f28694.png)

**Comment by waynebr76** [comment]
Hi Steve, Version 3.1.0 wraps on the screen but not on the print, it will great if it now works. Let me know how the test goes.

**Comment by daN4cat** [comment]
CSS for the printing is different from the screen one. It needs to be verified.

**Comment by SteveIreland** [comment]
Thanks for the reminder on this.  I finally found time to locate the print css and remove the superfluous rule-set.  A pull request has been submitted for the change.

**Comment by waynebr76** [comment]
Thanks

**Comment by waynebr76** [comment]
HI Steve, is it just the 1 file that needs changing? I just amended my file with your changes to test and using the default layout it still does not wrap.

**Comment by odiea** [comment]
No css changes will take effect until after the program has been recompiled or what ever they use to change it in the master.

**Comment by SteveIreland** [comment]
Yes.   Just like @odiea pointed out.

I made a note on the pull request that the compressed version of the style sheet will need to be recreated after the change is made.  

You can work around that by going directly to the compressed version and locating and searching opensourcepos.min.css for #receipt_items td{white-space:nowrap} and removing it.

You need to be careful but it is doable.

Save the change and restart the server.  You might need to refresh the browser cache.

**Comment by waynebr76** [comment]
Thanks

**Comment by daN4cat** [comment]
I'll merge it later...

**Comment by daN4cat** [comment]
Merged and in master. Take the latest traybin file to get the change

**Comment by waynebr76** [comment]
Thanks that's great

**Comment by SteveIreland** [comment]
Is this complete?

**Comment by waynebr76** [comment]
I have not tested the new download but applied the file as a patch to my current installation and it works.

**Comment by waynebr76** [comment]
Hi Guys I am testing the new master and the receipts are not wrapping was this request pulled through?

**Comment by daN4cat** [comment]
Looks fine to me: https://github.com/opensourcepos/opensourcepos/blob/master/public/css/ospos_print.css

Are you sure you are not using a cashed or ol version of min.css?
Download the file from bintray, please read the README.

**Comment by waynebr76** [comment]
Thanks, maybe I picked up the min.css from an earlier version while uploading the test - Sorry

**Comment by daN4cat** [comment]
No problem
