### ISSUE TITLE
Cost applied on Kit Only related items in an Item Kit

### ISSUE THREAD

**Issue by Alaa-23** [opensourcepos/opensourcepos#1580]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] I'm reporting an issue of an unmodified OSPOS installation
- [X] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [X] I read the README, WHATS_NEW and UPGRADE
- [X] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [X] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [X] I'm aware the latest master could be a development version and therefore not stable
- [X] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: Authentic
- PHP version is: 5.5  
- MySQL or MariaDB version is:  MySQL 5.5
- OS and version is:   Ubuntu 14.04
- WebServer is:   Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:  LAMP

### Expected behaviour

In Item Kits, when creating a new item with the pricing option (Kit Only), option value (1), It is expected that when I **connect Kit Item** that I made previously with a certain price AND cost in items **and** add normal items to the same Item Kit, as the components of that Item Kit when selling that item kit, it is expected that:

- The price is overridden by the price of the Kit Item in Items.
- The  Items included in the Item Kit are discounted from the inventory.
- When I see a detailed Sale report, there is no cost applied on items inside the Item Kit, only the Kit Item that I priced previously in Items.

### Actual behaviour
Cost is applied on items inside the Item Kit, regardless I used the price option: Kit Only.
Which affects the profit (outcome without income) and causes negative profit values in reports (reference to screenshots).

**For the record:**
I tried the option (Kit and Stock), while choosing (Non Stock) for the inside items, just for trial purpose, **_same effect_**.
**-- What I am trying to do is to sell each of these items (T-shirt and Shorts) separately, as well as selling them with a different price (NOT A DISCOUNT). **While dis-counting all (items and kit item) from the inventory.** 

### Steps to reproduce the issue
Posting this matter here..

![1](https://user-images.githubusercontent.com/14993988/30295624-858bde94-9741-11e7-89b8-a6db1446fe3a.png)
![2](https://user-images.githubusercontent.com/14993988/30295623-858b4312-9741-11e7-83ff-c2e546af1a1e.png)
![3](https://user-images.githubusercontent.com/14993988/30295625-85918b14-9741-11e7-8c5f-b963af7ba80d.png)

**Comment by SteveIreland** [comment]
I'm working on this.  It's not a quick fix so it might take another day or two.

Thanks for catching this.   It's not a commonly used feature.

**Comment by Alaa-23** [comment]
@SteveIreland Many thanks!

It's widely used here in Egypt as some stores sell wholesale products and by the piece..

I'm waiting for your fix :relaxed:

**Comment by Alaa-23** [comment]
@SteveIreland Any updates? :)

**Comment by SteveIreland** [comment]
Yep, it's coded up and I've been trying to test it.  But the target keeps moving.   :-)

I was doing well when @jekkos and @daN4cat were too busy to change things.  But now they seem to have freed up some time and with @objecttothis my tiny world changes daily.  I'm still trying to figure out how to adapt. 

I just installed the latest release and for some reason the drop-down for selecting items and customers isn't working so even though my change probably didn't break it and probably won't fix it I won't be submitting a pull request until I figure out why and what's needed to fix it.

**Comment by SteveIreland** [comment]
Actually it's just the "Find or Scan Item" that isn't working in the release I've pulled.  The customer search works fine.

**Comment by SteveIreland** [comment]
Okay, I believe I stumbled across the issue.  I'm testing on PHP 5.6 and a PHP 7 only variation of a statement was introduced.  So I made the statement PHP 5.6 compatable and the drop down started working.

I'll submit that change with this.

**Comment by SteveIreland** [comment]
I still have a bit of testing to do since I felt compelled to clean up and simplify the logic.

In the meantime if anyone needs to know what needs to be fixed in Item.php if they are running on PHP 5.6 it is the following.

```
function get_search_suggestion_format(string $seed = NULL)
```
needs to be changed to (dropping the data type statement "string"
```
function get_search_suggestion_format($seed = NULL)
```

**Comment by daN4cat** [comment]
Ok, I missed that during the code review, I'll pay more attention next time.

**Comment by Alaa-23** [comment]
@SteveIreland This is still not related to my issue, isn't it?

**Comment by daN4cat** [comment]
I removed the string in the function line, it's in master now. Wait for the bintray zip to be available in 5 or 10 min after the automated build is completed.

@SteveIreland more improvements can be part of a PR.

**Comment by Alaa-23** [comment]
@SteveIreland Any updates? I have work depending on this that's postponed =D

**Comment by daN4cat** [comment]
The way to speed up things in the open source world is to fix it by yourself and contribute it back to avoid the cost of maintaining it. That's how it works...

**Comment by SteveIreland** [comment]
Sorry.  I'm going as fast as I my limited time permits and I'm not going to submit it until I'm comfortable that it has a reasonable chance of success. 

At this point it's looking pretty good, but I have a few more use cases that I need to test through and that simply takes time.  I'll definitely submit a pull request for it tomorrow.

**Comment by Alaa-23** [comment]
@SteveIreland Thank you, sir!

**Comment by SteveIreland** [comment]
A pull request has been submitted for this

**Comment by daN4cat** [comment]
In master

**Comment by Alaa-23** [comment]
So how do I use the new fix in my current 3.1.1 code? Should I just download master and then merge and replace?

**Comment by daN4cat** [comment]
@SteveIreland adding a kit with items to the register adds the items with price 0. Not sure that's correct.

**Comment by SteveIreland** [comment]
Nope ... not correct.  That's not what happened during my pre-pull testing.  So I'll take a look.  I'll rebuild from the master and take a look.

**Comment by SteveIreland** [comment]
@daN4cat I should have qualified my response.  It depends on how you have the kit flagged for pricing.  If you have it flagged as "Kit" then only the kit item will show a price and cost.   If you have it flagged for "Kit and Stock" pricing then only the Kit pricing and the kit items that are flagged as stocked items will be priced. (the pricing for services are assumed to be rolled up in to the kit item).   Then if you have if flagged as "Kit and Components" then all items that have a price are priced.

Are you seeing a different behavior?

**Comment by SteveIreland** [comment]
Maybe a better question is "am I missing something"?

**Comment by SteveIreland** [comment]
@Alaa-23 I checked out the 3.1.1 branch and looked at the differences in just the Sales.php controller since 3.1.1 and there have been a lot.  So it would be a delicate operation but certainly doable if you have some time to spare.  Unfortunately I've spent it all I had to spare just putting this together (although I personally think it was well worth it so I appreciate that you brought it to our attention).

**Comment by Alaa-23** [comment]
@steveirelnd I tried it and it worked! But after dropping the database and importing master's.
I appreciate your work and spending time fixing this. Thanks again, I'll make sure I post any errors in the future.

**Comment by daN4cat** [comment]
@SteveIreland price option is Kit Only. But then where do you input the prices? Not sure I get this feature and it might well be my lack of reading up a bit more....

**Comment by SteveIreland** [comment]
There is an item type of kit that will typically be added as a non-stock item. That is where the price is set for the kit if we are pricing at a kit level

**Comment by daN4cat** [comment]
I trust you tested this and everything is fine. I don't need this feature, I just gave a try out of curiosity. Surely community testing will spot any issue if any :-)

**Comment by SteveIreland** [comment]
Soon after 3.2 is released no doubt!

**Comment by SteveIreland** [comment]
I believe this can be flagged as complete.

**Comment by D3v1Lz** [comment]
Hello Guys, am facing same issue in item kit print options and pricing... Print option always show all items on receipt and on sale module..
1 more question can i show the kit name on report ? 
Awaiting reply...
