### ISSUE TITLE
DO NOT print receipts jsPrint

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1581]
Hi
Install jsPrint but when I print the receipt does nothing?
I have Firefoz 55.0.3 (64-bit) on Windows 10
version OSPOS 3.1.1
Can somebody help me?

**Comment by odiea** [comment]
Enable jsprint settings in Firefox. Set as needed for security.
Go to Store config and reselect the printers then press submit and see if that fixes it.

**Comment by odiea** [comment]
Occasionally I had to select a different printer. Submit. Then go back and select the correct printer. Then submit.

**Comment by guillermohaad** [comment]
Thank you friend  @odiea ,  change Receipt format and I did what you say and I worked perfect. Things that 
happen....

**Comment by lkwetter** [comment]
I am having this issue only in the PC's Non-Admin account (Widnows 7). I do the things above to get it working again, but as soon as the PC is shut down for the night and restarted the next day, it happens again. If I clear out the PC browser sessions and cookies and reload the Point of Sale, it will happen, also. So, it seems to be permissions and sessions related. We have multiple volunteer retiree cashiers using this and I can't come in every day to fix it and they are not computer literate.  If they were, they'd be dangerous. Sometimes, not always, the cashiers will get a message asking them to allow a program (jsprint setup) to change printer settings. They ignore/don't see it or think it's malicious. If they give permission receipts will print for them.

I can print the receipts with no problem from other browsers, but it runs out miles of empty paper. In Chrome the print dialog thinks there is 4 sheets of paper to print in the receipt. It would be nice if I could do something to make printing dependable for the cashiers.

**Comment by odiea** [comment]
I assume this is a localhost setup. Try changing your jsprint options.
![2017-09-30 04_47_12-add-ons manager](https://user-images.githubusercontent.com/10962177/31045163-af6d34bc-a59a-11e7-9f00-d2a2cb31d02e.png)

**Comment by lkwetter** [comment]
Thank you. After playing around with it for a while, it seems now to be working now. I'm not sure what I did, but the last thing I tried was to disable jsprint and then enable it again.  I like this POS and and the cashiers find it generally easy to use and nice looking.
