### ISSUE TITLE
Barcode with product code-price

### ISSUE THREAD

**Issue by pmuruaga** [opensourcepos/opensourcepos#1586]
Is there a way to read a barcode, configure a product with the barcode, that is variable, depending on the weight. It's for a butcher shop each peace of meat has a barcode that has a code of product plus a final price, so I can get the weight to based on the price of the product. Thanks.

**Comment by daN4cat** [comment]
Search other issue as it was already discussed.

**Comment by daN4cat** [comment]
Duplicate of #1243

**Comment by daN4cat** [comment]
Actually it's already implemented, see the ticket I mentioned above.
