### ISSUE TITLE
/ospos/public/ spits out 500 internal error ( and I have edited the .htaccess file )

### ISSUE THREAD

**Issue by aleifuu** [opensourcepos/opensourcepos#1587]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] I'm reporting an issue of an unmodified OSPOS installation
- [] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [] I read the README, WHATS_NEW and UPGRADE
- [] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [] I'm aware the latest master could be a development version and therefore not stable
- [] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: opensourcepos.20170909085348.3.1.1.76a002.zip 
- OSPOS git commit hash is: 
- PHP version is:   5.6
- MySQL or MariaDB version is:   MySQL 5.6
- OS and version is:   raspbian jessie
- WebServer is:   Apache 2.2
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
To a login screen, so that I can continue installation

### Actual behaviour
Internal error 500
and tail error.log doesn't log or tell what went wrong

### Steps to reproduce the issue
just go to ip_address/ospos/public/

Hi everyone, It seems I've bumped across something common that ospos beginner bumped into. I have read some of closed issues and faq. and they all suggest to edit .htaccess file of public/ to rewrite accordingly ( on subdir, instead of web root ) 

I have edited application/config/database.php with necessary information too 
( in fact whether I have or have not, hitting ip_address/public will just spit 500 error for no reason )

I did that, but none seems to effect. hitting ip_address/ospos/public will just give me 500 internal error. Strangely apache2 error log doesn't give anything useful and I have been reading some of past issues but could not get past this 

*Note : I have other applications running on same host, same apache2 but no problems for them even I encounter 500 on this specific ospos installation 

Many thanks,

**Comment by daN4cat** [comment]
Checked ownership and permissions?

**Comment by aleifuu** [comment]
This is what I did so far:

sudo chown www-data:www-data /var/www/html/ospos
sudo chmod -Rv 755 cache* /var/www/html/ospos

**Comment by aleifuu** [comment]
could be a php error. tried to turn on the php reporting directives like error_log, display_error on php.ini
seems no effect yet

**Comment by daN4cat** [comment]
Have you read the wiki with the instructions to install on Rasperry Pi? Also Nginx, Php7 and MariaDB are better choices performance wise.

**Comment by aleifuu** [comment]
@daN4cat , yes. I am following the steps as outlined in the raspberry pi wiki section. I'm looking at it every now and then, see if there's misstep or something

Yes, I heard Ngix / MariaDB is superior choice than Apache/MySQL. But that's what I have right now and where I'm more comfortable setting. not too experienced with Ngix / MariaDB yet

**Comment by aleifuu** [comment]
had some fiddling around with the code a bit, may focus it down to database connection 

I just commented the following section 

```
$db['default'] = array(
        'dsn'   => '',
        'hostname' => !empty(getenv('MYSQL_HOST_NAME')) ? getenv('MYSQL_HOST_NAME') : 'localhost',
        'username' => !empty(getenv('MYSQL_USERNAME')) ? getenv('MYSQL_USERNAME') : 'admin',
        'password' => !empty(getenv('MYSQL_PASSWORD')) ? getenv('MYSQL_PASSWORD') : 'pointofsale',
        'database' => !empty(getenv('MYSQL_DB_NAME')) ? getenv('MYSQL_DB_NAME') : 'ospos',
        'dbdriver' => 'mysqli',
        'dbprefix' => 'ospos_',
        'pconnect' => FALSE,
        'db_debug' => (ENVIRONMENT !== 'production'),
        'cache_on' => FALSE,
        'cachedir' => '',
        'char_set' => 'utf8',
        'dbcollat' => 'utf8_general_ci',
        'swap_pre' => '',
        'encrypt' => FALSE,
        'compress' => FALSE,
        'stricton' => FALSE,
        'failover' => array(),
        'save_queries' => TRUE
);

```

**Comment by daN4cat** [comment]
Of course, wrong config leads to malfunctioning... it's an obvious. So was that the issue?

**Comment by aleifuu** [comment]
Ok. We can close this issue 

What causing internal 500 this time was not .htaccess rewrite. As it turned out, it's much simpler. It's because the 'admin' user was not created yet, hence no access and the 500 error. ( Still I'd wish the system could have caught them, log something useful and display what the error was ). This happens 
to be a super simple error. Could be a CodeIgniter issue ?

I thought the user is automatically created when you run database.sql but I was wrong 

Ok. I'm closing this issue

Thanks everyone and @daN4cat

**Comment by daN4cat** [comment]
OSPOS admin user is created by database.sql script. Where did you see differently?

**Comment by aleifuu** [comment]
yes, OSPOS admin user is created by database.sql 

I thought the script also created the MySQL user 'admin' as well with the same credential all in one go too. It just created the OSPOS admin right ?

You'd still have to either use your current MySQL user or create new one

**Comment by daN4cat** [comment]
That's on you as sysadmin not something OSPOS can solve. MySQL admin privileges needs to be protected from external access. It's a basic security requirement.

**Comment by maya-tsedeke** [comment]
Please solve the following error , in OSPOS after first installation , 
A PHP Error was encountered

Severity: Warning

Message: session_destroy(): Session object destruction failed

Filename: Session/Session.php

Line Number: 702

Backtrace:
File: /var/www/ethiomecan.com/application/hooks/load_config.php
Line: 13
Function: sess_destroy

File: /var/www/ethiomecan.com/public_html/index.php
Line: 315
Function: require_once


An uncaught Exception was encountered

Type: Error

Message: Call to a member function result() on bool

Filename: /var/www/ethiomecan.com/application/hooks/load_config.php

Line Number: 16

Backtrace:

File: /var/www/ethiomecan.com/public_html/index.php
Line: 315
Function: require_once

**Comment by SteveIreland** [comment]
@maya-tsedeke This is a closed ticket.  Please open up a new ticket providing the information about your environment, version, etc. that's requested.  Thanks.

**Comment by daN4cat** [comment]
I bet that code doesn't come from the official release zip files but from GitHub master directly.
