### ISSUE TITLE
Rounding Bug

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1590]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is:  4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MySQL 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
With Currency Decimals set at 2, cash decimals set at 1 and "Round Up" Selected, prices should be rounded up to the nearest 0.10.  For example 2.23 should round to 2.30.

### Actual behaviour
Instead it rounds to 3.00.  With half-up selected 2.26 rounds properly to 2.30, but not properly when round up is selected.

If no one else wants to own this, it can be assigned to me and I will look into it.  I first wanted to confirm that it is indeed a bug, but I thought perhaps I'm not understanding round up correctly.

**Comment by odiea** [comment]
You might want to converse with @SteveIreland  about this issue.

**Comment by objecttothis** [comment]
@SteveIreland come on down!  You're the next contestant on The Rounding is Right!

**Comment by SteveIreland** [comment]
I didn't have time to test it but I looked at the code and it seems okay.  The only hole that I thought might be possible is if the config for currency decimal didn't actually exist in the config file.  But no doubt there  are other possibilities that I'm overlooking.

If you want to dive in there please do so.  I don't use the cash rounding feature myself but I volunteered to do so (it seems like eons ago) but never received any feedback.

So enjoy!

**Comment by daN4cat** [comment]
I believe this is now fixed, so I close.
