### ISSUE TITLE
Feature request - item count in sales module

### ISSUE THREAD

**Issue by nashtm** [opensourcepos/opensourcepos#1595]
### New Feature / Enhancement

I use Ospos for my business. I think it is useful to have a counter on the Sales module to indicate the number (sum) of items that have been rung up.  Visibility could be controlled via Store config module.

**Comment by odiea** [comment]
Have you tried using the Sales Summary Report.

**Comment by SteveIreland** [comment]
I could see where the number of items in the cart could be useful information if you need to verify that all items in the bag were included in the sale.  In the totals area if we change the Total label to say (instead of simply "Total" to be "Total of x Items" would that satisfy the requirement?

**Comment by nashtm** [comment]
Steve, that is exactly what I used it for iny previous pos. Sometimes people being a last minute item or two and the total of items helps verify that I have included them.  I think your suggestion to add to total line  is great and would not need any further configuration.

**Comment by RamkrishnaMondal** [comment]
It's easy to implement.

use      `echo array_sum(array_column($cart, 'quantity'));`

check it here: http://www.tradingmaster.esy.es/public

**Comment by odiea** [comment]
Here is what I came up with. Application/views/sales/register. Line 350
```
<table class="sales_table_100" id="sale_totals">
			<tr>
			    <th style="width: 55%;"> <?php echo $this->lang->line("sales_quantity"); ?></th>
				<th style="width: 45%; text-align:right; "> <?php echo array_sum(array_column($cart, 'quantity'));?></th>
			</tr>
			<tr>
			<th style="width: 55%;"><?php echo $this->lang->line('sales_sub_total'); ?></th>
				<th style="width: 45%; text-align: right;"><?php echo to_currency($subtotal); ?></th>
			</tr>

**Comment by RamkrishnaMondal** [comment]
@odiea 
You can also use in your receipt / invoice.

**Comment by odiea** [comment]
Nice looking site.

**Comment by SteveIreland** [comment]
Interesting.   If I bought 24 of one product and 113 of another product I would have set the item count to 2.  I would have assumed that the quantity of each item was properly reflected at the line item before it went into the bag.  I interpreted what was being asked was that the count of the different products in the bag was what was needed.

Would it make sense to have an additional line as @odiea  does?  I would also only count stocked items.  It certainly wouldn't make sense to include service items.

I too would include the following line right above the Subtotal line.
 
[ Quantity of 2 Items       137 ]

**Comment by odiea** [comment]
Here is the result I get. I am sure a real programmer can embellish it.
![2017-09-15 06_57_32-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/30483220-576d9594-99e3-11e7-801f-8bb35ab91d47.png)

**Comment by SteveIreland** [comment]
I don't know if it's better or not.  It might actually confuse things ... so that is why I ask.

But I'm glad to see we're not the only ones selling things we don't have in stock.  :wink:

**Comment by odiea** [comment]
The preventing of out of stock Items being sold has been hashed out a couple of times. I figured if someone brought the Item to the Register but the Inventory says no items I will sell it. Bad Inventory input!

**Comment by RamkrishnaMondal** [comment]
What about this? @odiea @SteveIreland 

![screenshot at 2017-09-15 19 34 10](https://user-images.githubusercontent.com/14151032/30486038-fb292a0e-9a4c-11e7-9231-f60646fcea6c.png)

**Comment by SteveIreland** [comment]
@RamkrishnaMondal so your vote is just for the total quantity and not the total number of items?  So you don't see any value for the total number of items?

**Comment by nashtm** [comment]
For me the total quantity is most important but having the breakdown is a plus.

**Comment by RamkrishnaMondal** [comment]
To tally the quantity in the bag with quantity in the receipt, is more important. 

Best solution should be, as you mentioned 

> [ Quantity of 2 Items 137 ]

**Comment by odiea** [comment]
Here is a copy of the receipt with the quantity in 2 locations. Which location is best?
![2017-09-15 10_24_51-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/30493142-4be52d32-9a00-11e7-93fc-24624262f5fc.png)

**Comment by odiea** [comment]
Here is a modified receipt using the set font size +2 in bold
![2017-09-15 10_53_38-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/30494195-61429508-9a04-11e7-8d49-0cad13379485.png)

**Comment by RamkrishnaMondal** [comment]
This location is the best.  LOL!

![screenshot from 2017-09-16 03 33 45](https://user-images.githubusercontent.com/14151032/30505034-e56fa06a-9a8f-11e7-8e27-1881a629194b.png)

**Comment by SteveIreland** [comment]
Support for this being included in the register has been added to the latest pull request. I did not touch the reports since I ran out of time. I'll wait for feedback on this change

**Comment by daN4cat** [comment]
In master

**Comment by SteveIreland** [comment]
Many thanks!.

**Comment by daN4cat** [comment]
@SteveIreland there is a problem, the receipt prints under quantity column the overall total on each line.
Let say I bought 4 different items I read 4 on each item line instead of 1.

**Comment by daN4cat** [comment]
It looks like it's saved wrongly because opening an old sale the quantity per line is correct.

Also the total per line is wrong as multiplied by 4.

**Comment by odiea** [comment]
Here is what i see after a new sale. Using php 7 and Mariadb. What are you using?

![2017-09-16 15_12_44-](https://user-images.githubusercontent.com/10962177/30516075-c9338f9e-9af1-11e7-9176-dbfb749ecc83.png)

**Comment by daN4cat** [comment]
I will look into this later. I didn't have more time yesterday (need to tidy up the garden as autumn is approaching).

**Comment by daN4cat** [comment]
Disregard my comment above, everything seems to be working fine with regards to quantity.
I close
