### ISSUE TITLE
Can someone help me rid two php ospos files of malware?

### ISSUE THREAD

**Issue by esbyrt** [opensourcepos/opensourcepos#1596]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 7.0.23
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 10.0.32
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Windows 10
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4.27
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Actual behaviour
I am running ospos on a subdomain and two of the ospos php files were infected. The host site blocked access to the domain. I replaced them with files from github with the same name but they are substantially different and reports come up blank. I am barely familiar with php and I'm not sure what else might be malfunctioning. The two bad files were common.lib.php and sqlparser.lib.php. Can someone help me out by finding and removing the malware in the two original files I backed up? I'd be willing to pay for your time (to a point - I don't make much on this). I would appreciate any help!!!!!

Thanks!
PS - I don't want to upgrade to 3.1 until I know everything is functioning properly. I know that could turn into a nightmare.

**Comment by jekkos** [comment]
I don't think any of these files are supposed to be in an ospos installation..

**Comment by jekkos** [comment]
So I wonder where did you find their replacements? At least they are not in our repository nor in the vendor installed code

**Comment by RamkrishnaMondal** [comment]
I think the files he mentioned are part of phpmyadmin installation.

**Comment by esbyrt** [comment]
The files were in the ospos folders. 
/home/ritzyrag/public_html/sales/protected/extensions/sqlquery/libraries/sqlparser.lib.php
{CAV}Atomicorp
/home/ritzyrag/public_html/sales/protected/extensions/sqlquery/libraries/sqlparser.lib.php
I found the replacement file here https://github.com/appfog/af-php-myadmin/blob/master/libraries/sqlparser.lib.php which I see now wasn't an OSPOS related page. 

My reports all come up like this now, with false all across the top and no data.
![sales](https://user-images.githubusercontent.com/28318020/30496751-a5076454-9a0d-11e7-8171-f1918ec084fa.JPG)

Obviously I need to put the original files back but I need to get the malware out of them first. Can anyone help me? Or point me to an antivirus that can remove malware from php?

**Comment by daN4cat** [comment]
Stop your server and Search for a php scan utility that deletes the files. You can Google it. But that has nothing to do with OSPOS.

**Comment by esbyrt** [comment]
Ok daN4cat, I put the original files back (still looking for a scanner but that's besides the point) and my reports still come up blank. What would be causing that?

**Comment by daN4cat** [comment]
I bet you switched to MySQL 5.7

**Comment by esbyrt** [comment]
You nailed it! Yes I did switch to PHP 7. When the site first went down I made some changes to try to fix it. That was before I contacted the hosting company and discovered they had blocked the site due to infected files. I simply lost track of the changes/fixes I had made along the way. Thanks for your help. When I changed it back to 5.5 everything is working again. Lesson learned.
