### ISSUE TITLE
sales_receipt not change

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1598]
Hi, Friends
I have fo version 3.1.1 fo 09-09-20117
when creating a return and print the receipt the title always says:
Sales Reciept
Same happens for Receiving
Thank you all for contributing and I hope you can help.
attached evidence

![image](https://user-images.githubusercontent.com/12921805/30498029-cd477f3c-9a1a-11e7-9105-adff5ba82ae1.png)

**Comment by odiea** [comment]
This may not be the answer that you are looking for but this has always been that way.

**Comment by daN4cat** [comment]
Receiving indeed should not be sale. It's a bug and needs to be fixed

**Comment by odiea** [comment]
I believe he is stating that Receivings also does not show "Return" on the receipt when it is a return..

**Comment by guillermohaad** [comment]
I agree with @odiea.

**Comment by guillermohaad** [comment]
@daN4cat , Is there a place where you can change the titles of the reports?

**Comment by daN4cat** [comment]
Right return, not receiving.

**Comment by daN4cat** [comment]
This is not a bug, just a detail. So I put up for some brave person to take and go.
As far as I'm concerned this is really a detail.
