### ISSUE TITLE
Return of sale

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1599]
on return of sale the receipt says POS # should not say Return #?
Could someone explain the return on sales?
in the report of return the same thing happens, says sales report

Thank you
attached evidence

![image](https://user-images.githubusercontent.com/12921805/30500879-e1aed33e-9a25-11e7-8b03-3374505a7bdf.png)
![image](https://user-images.githubusercontent.com/12921805/30504212-13f7d752-9a33-11e7-9751-c530abf90fa0.png)

**Comment by odiea** [comment]
This may not be the answer that you are looking for but this has always been that way.

**Comment by daN4cat** [comment]
I would say no, the Barcode relates to the sale. The fact you identify a sale to perform a return is a different action and story.

**Comment by daN4cat** [comment]
The report is sales and returns. It's more a statement of transactions. Could be even renamed to be Transactions log or simply Transactions.

**Comment by guillermohaad** [comment]
I agree with daN4cat, the report should say returns transactions and the sales transactions sales to be able to differentiate

Thank you

**Comment by daN4cat** [comment]
It will be simpler to rename it Transactions, that's it.

@jekkos @odiea @SteveIreland @objecttothis  any view on this?

**Comment by odiea** [comment]
Ya. Detailed Transactions Report sounds ok.

**Comment by objecttothis** [comment]
Agreed on renaming to Transaction Report and Transactions

**Comment by SteveIreland** [comment]
That makes sense to me.

**Comment by odiea** [comment]
Sales Summary Reports and Sales Graphical Reports so we all know it only pertains to Sales.

**Comment by jekkos** [comment]
+1

**Comment by guillermohaad** [comment]
@odiea  how to differentiate the sales report and the return report?
thank you.

**Comment by odiea** [comment]
Returns are already filtered in the Detailed Sales Report. After the report is run you will see the transaction type column.
![2017-09-20 06_51_06-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/30644645-44c5ee82-9dd0-11e7-8d0c-7bbf151baeb8.png)

**Comment by guillermohaad** [comment]
@odiea I have installed version 3.2.0, should I update the master files?
thank you

**Comment by odiea** [comment]
If you installed 3.2.0 then you have all the necessary files. If you are just testing you might consider creating a new db with database.sql if in production use the upgrade db if necessary 3.1.1 to 3.2.0.

**Comment by guillermohaad** [comment]
@odiea thanks you are a bacan as we say here in my country.

**Comment by daN4cat** [comment]
In master now with Transactions instead of Sales
