### ISSUE TITLE
Upgrade from version 3.1.1 to 3.2.0 and note that they eliminated quotes and invoices?

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1600]
Upgrade from version 3.1.1 to 3.2.0 and note that they eliminated quotes and invoices? and button migrate

![image](https://user-images.githubusercontent.com/12921805/30502916-d1c74d40-9a2d-11e7-85ef-5f575d980079.png)

![image](https://user-images.githubusercontent.com/12921805/30503588-6bd30bf2-9a30-11e7-8eed-e0038a87e5d7.png)

**Comment by SteveIreland** [comment]
Configuration. Enable invoices

**Comment by guillermohaad** [comment]
Thanks friend @SteveIreland, corrected, and the migrate button should appear after upgrade?

**Comment by SteveIreland** [comment]
I'm not sure about the Migrate stuff.  That was tweaked after I worked on it and I was busy at the time and wasn't paying attention to what was changed.  But I think the intent was that it wouldn't appear unless it was necessary.

**Comment by daN4cat** [comment]
Yes it's like that. If not required it disappears automatically

**Comment by guillermohaad** [comment]
Thank you @SteveIreland  and @daN4cat
