### ISSUE TITLE
Items not showing after CSV import in OSPOS 3.0.2

### ISSUE THREAD

**Issue by jsoftwares** [opensourcepos/opensourcepos#1603]
Hi Support,

I uploaded items using a CSV file and the upload went successful, but when I click ITEMS menu, I can't find any item. But I can see them when I search for an item through SALES menu or scan the bar code.

Also When I click any option in DETAILED REPORT i get continuously:
This page isn’t working
178.62.43.178 is currently unable to handle this request.
HTTP ERROR 500.

Please assist me to resolve this.

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 
- PHP version is:    7.0
- MySQL 5.0.12
- OS and version is:   16.4,
- WebServer is:   (e.g. Apache 2.2

**Comment by daN4cat** [comment]
You said you read the README for 3.0.2. However I'm under the impression that you didn't pay attention to the fact that 3.0.2 does not support PHP7 nor MySQL 5.0.12 nor 5.7 but 5.5 or 5.6.
