### ISSUE TITLE
Question - cant run live and dev instances together (WAMP)

### ISSUE THREAD

**Issue by nashtm** [opensourcepos/opensourcepos#1604]
I cant get two versions running together in same WAMP installation. I get this error:
PHP Fatal error:  session_start(): Failed to initialize storage module: user (path: sessions) in C:\\xampp\\htdocs\\ospos\\vendor\\codeigniter\\framework\\system\\libraries\\Session\\Session.php on line 143

I have searched but can find the the answer - I would think this is a common issue so maybe I missed it.

**Comment by daN4cat** [comment]
I assume you are pointing to two different directories with different databases, right? Maybe you should also name the cookies differently in the configuration file just keep things separate from each other.

**Comment by nashtm** [comment]
My error  - I left the angled brackets around <OSPOS path> when editing htaccess file. Late night problem!
