### ISSUE TITLE
Sales Data Import facility in Excel or CSV Format

### ISSUE THREAD

**Issue by bharatthakkar** [opensourcepos/opensourcepos#1605]
### New Feature / Enhancement

I need to import last 3 months sales data from my old package (old package is developed in COBOL and data can be exported from the package in CSV format)

Is there any possibility to import Excel or CSV file for Sales data (like Item data and Customer Data)

Thanks

**Comment by daN4cat** [comment]
Currently it's not supported and it will be tricky because each sale needs to link to items in the database. So you would need to make sure sale contains a valid foreign key to your items. It's the id.

In short you would need to develop the importing feature looking up items and adding the sale.

**Comment by daN4cat** [comment]
Probably you can import your csv file to a temp table and then with SQL upload ospos with the sales. You can give a try from myPhpAdmin

**Comment by bharatthakkar** [comment]
Thankyou for your positive reaction..

Yeah, I m working on it.. I have already wrote an engine in php and SQL to transfer from old package CSV to ospos MySQL Data Tables... Testing it.. and hope I will transfer it successfully...
