### ISSUE TITLE
Floating header and table headers

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1610]
### New Feature / Enhancement

Currently when scrolling on pages, the entire page scrolls.  There are two features I would like to propose

1- The main header stays at the top of the page while scrolling.  This would include from the time/date at the top down to and including the module icons.
[COMPLETED] 2- Sub-headers and table headings stay at the top of the page while scrolling.  This would include, for example, the headings in the store config as well as all table headings.  With tables being able to alway see the table heads greatly assists analyzing the data... this is especially helpful in long reports.

There are likely several ways to implement this and I don't mind doing the work on it, but wanted community assessment and decision.  These ideas can be separated too if people like one but not the other. Thoughts?

**Comment by odiea** [comment]
As my buddy @daN4cat  says. Make it a config item. But it sounds good to me.

**Comment by daN4cat** [comment]
In this case I would say make the change without optional story. I agree on the better user experience, however the table would to be studied as there is a lot of js to crunch to get to the change you want.

**Comment by jekkos** [comment]
think it's a lot of work to make it look good in most situations.

**Comment by objecttothis** [comment]
@jekkos, if it can be made to look good in most or all situations and is not a significant performance hit do you feel ok with it? it isn't extremely high on my priority list so I wouldn't get to it right away, but I would like to give it a shot if there aren't objections.

**Comment by jekkos** [comment]
Sure go ahead some eye candy is always nice to have

**Comment by daN4cat** [comment]
I added the table floating header feature, called sticky header in bootstrap tables terminology.

When the top bar becomes floating, the sticky header needs an additional value to be set `stickyHeaderOffsetY` so the table sticky header stays under the topbar floating one.
See: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/sticky-header

**Comment by SteveIreland** [comment]
I will download and run a quick build and test.  A snapshot I rebuilt about an hour ago had issues with finding jQuery.  It might be something I did wrong on my end, but hopefully that issue will go away with a 2nd attempt.

**Comment by SteveIreland** [comment]
I think I missed a step  Just ignore me.

**Comment by objecttothis** [comment]
@daN4cat me likey! I'm looking forward to rejoining the fun once my sabbatical is over mid-January.

**Comment by daN4cat** [comment]
I close this because I don't think we need anything more than what already implemented.
