### ISSUE TITLE
not a problem, just a process query

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1611]
Hi Friends,
I have versión 3.2.0 
I am new here and I want to know how is the process of returning an item from a sale? I am attaching an example if you can lend me a hand ..

![return](https://user-images.githubusercontent.com/12921805/30552848-05807966-9c65-11e7-8ad5-7a350f4e4d95.png)

the exercise is as follows:

I want to return 2 units of article "12345"

Thank you

**Comment by daN4cat** [comment]
That's correct. You say how you return the money with a negative payment and issue a receipt. Job done

**Comment by odiea** [comment]
If you do not want to return the first item just delete it from the list then in 12345 change the -10 to -2.

**Comment by daN4cat** [comment]
Ah... the detail. ... correct as per @odiea description

**Comment by guillermohaad** [comment]
thanks to the friends @daN4cat @odiea  for the explanation, it is clear.
