### ISSUE TITLE
New Feature: Language per user

### ISSUE THREAD

**Issue by HotFireyDeath** [opensourcepos/opensourcepos#1612]
### New Feature / Enhancement

I expect the community to implement, as I have no idea on how the software work internally as of right now. My idea for a new feature is actually a feature implemented on our current POS system for our restaurant. As the title states, this allows a custom language setting for the user instead of global. I don't see this implemented into the POS as of now, and it'll be cool to see.

**Comment by daN4cat** [comment]
There is by employee and system. However not by customer.

**Comment by HotFireyDeath** [comment]
Oh ok. Thanks, I just needed it for employees.

**Comment by daN4cat** [comment]
It's in the latest master code that will be released as 3.2.0 at certain point.
