### ISSUE TITLE
Suppliers Report is not working

### ISSUE THREAD

**Issue by saruban** [opensourcepos/opensourcepos#1615]
My ospos version : 3.1.1

I have 2 suppliers and receive goods from both suppliers.  I need to view the goods total value received from my suppliers.  
In Reports, supplier report module is not work like as it.  

To recreate the follow the steps here ;

Add 2 or 3 items and 2 or 3 suppliers.  After that, go to receiving section and receive goods from suppliers.  
Then go to report > suppliers. You can't see all suppliers report there.  

Thanka

**Comment by daN4cat** [comment]
What about the template information?

**Comment by saruban** [comment]
Means?

**Comment by saruban** [comment]
Can you please look into this issue.  It's really big issue

**Comment by daN4cat** [comment]
Next time you create an issue don't scrap everything and read what's in front of you answering the questions.
In that way you get help or it might be that you could find the answer by yourself.

**Comment by SteveIreland** [comment]
Also (and I don't use the report myself) the Supplier Report appears to be a summary sales by supplier and not a Receivings by supplier report.  This area is going to receive a little boost in functionality in the 3.2 release.

**Comment by saruban** [comment]
### New Feature / Enhancement

*For New Features or Enhancements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.*


### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- x[] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is:   versi4f5ad57
- PHP version is: 5.6.31
- MySQL or MariaDB version is:  10.0.32-MariaDB
- OS and version is:  linux
- WebServer is:  Apache 2.4

### Expected behaviour
The supplier report has to show the summary of goods receiving from every supplier. 

### Actual behaviour

The supplier report doesn't show any details. 

### Steps to reproduce the issue
Add 2 or 3 items and 2 or 3 suppliers. After that, go to receiving section and receive goods from suppliers.
Then go to report > suppliers. You can't see all suppliers report there.

**Comment by odiea** [comment]
I believe there may be a filter issue going on here. Here are a few receivings.
![2017-09-19 09_26_34-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/30600570-0d66648e-9d1d-11e7-910c-1ecf0897f2e4.png)

Here is the suppliers report.
![2017-09-19 09_27_00-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/30600606-2904b646-9d1d-11e7-95a7-2a7bee17e178.png)

**Comment by saruban** [comment]
Yes. @odiea . There are some issues to fix.  Thanks for understanding it. Please reopen it to fix this asap.

**Comment by odiea** [comment]
This will have to be reopened by @daN4cat or @jekkos if they believe it is necessary.

**Comment by daN4cat** [comment]
@saruban help in fixing issues is appreciated. I won't have time for this issue.

**Comment by daN4cat** [comment]
Also the supplier report is about sales and returns not receivings. It has always been like that since the beginning.

**Comment by saruban** [comment]
I can understand that you are too busy with other works.  If you hve any idea about the solution  share here and try to fix this by myself or with othere help

**Comment by saruban** [comment]
In here, Supplier is a company which give goods to our store. So we need to know the goods and it's cost given by every supplier.

**Comment by odiea** [comment]
Sorry my misunderstanding. Yes it works properly with Sales.

**Comment by jekkos** [comment]
@saruban so in fact it's an enhancement you ask for, not a bugfix..

**Comment by jekkos** [comment]
You can use detailed orders report, eventually add supplier field to the preselection or create your own report for viewing orders.
