### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1616]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MySQL 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
When entering an incorrect format in the price column on the sales register to manually adjust the price of an item ospos would pop up a toast notification explaining that the format of the number entered is incorrect.

### Actual behaviour
When entering a number with incorrect format it gives me a blank screen and the log produces the line:
`ERROR - 2017-09-19 15:47:05 --> Severity: error --> Exception: Number parsing failed /usr/local/www/public_html/pos_alpha/application/helpers/locale_helper.php 192`

### Steps to reproduce the issue
This can very easily happen if your localization settings are expecting a comma but you give it a period.

**Comment by jekkos** [comment]
Maybe we can add try - catch clause there and then handle appropriately once something goes wrong?

**Comment by objecttothis** [comment]
yeah, go ahead and assign it to me and I'll work on it.

**Comment by daN4cat** [comment]
@objecttothis any chance to close this issue?

**Comment by objecttothis** [comment]
I need to fix it first.  I'm hoping to work on it Monday morning.

**Comment by objecttothis** [comment]
I'll get working on this in the morning (Tuesday GMT+4).  I'm glad to finally get back to having more time to work on the code again.
