### ISSUE TITLE
New instalation not working on xampp localhost

### ISSUE THREAD

**Issue by abdulrehman6** [opensourcepos/opensourcepos#1619]
Hi, Friends
I have fo version 3.1.1 fo 09-09-20117
1. I have past all codes to pos folder created in htdocs 
2. created new database name ops and imported database.sql in phpmyadmin
3. then set localhost database username as root and password as empty and database name ops in config/database.php.
now when i access it show error see the screen shot below.
I hope someone will help me what i missing anything?
![pos](https://user-images.githubusercontent.com/32044325/30616397-8a81f134-9dab-11e7-9875-38a6d22bcbe8.png)

**Comment by odiea** [comment]
Read the wiki on xampp to enable needed php extensions.

**Comment by abdulrehman6** [comment]
Thanks for reply i did not found any solution yet.
can anyone help
thank you in advance

**Comment by abdulrehman6** [comment]
xampp/php.ini
i enabled these extensions but same error.
extension=php_bz2.dll
extension=php_curl.dll
extension=php_fileinfo.dll
;extension=php_ftp.dll
extension=php_gd2.dll
extension=php_gettext.dll
extension=php_gmp.dll
extension=php_intl.dll

**Comment by odiea** [comment]
extension=php_sockets.dll
