### ISSUE TITLE
Can't apply return to gift card - Bug or feature request?

### ISSUE THREAD

**Issue by esbyrt** [opensourcepos/opensourcepos#1620]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 7.1
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 10.0 .32
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
When a customer buys something on a gift card and then returns that item the store should be able to put that credit back on the gift card. When I try to make a return to a gift card number that already exists for the customer I get a "Gift Card 11 remaining value is %2.00!" displaying above register mode and the return payment won't apply. 

If I create a new gift card number (not entered under gift cards just one that hasn't been used yet) I get the message "Gift Card 2000 cannot be used for this sale: invalid Customer."

Also the store that I set up OSPOS for does returns for store credit only. So a return to gift card that could be done right in the return window would save a fair amount of time.

Not sure if this is a bug or a feature that hasn't been asked for yet.
Thanks!

**Comment by odiea** [comment]
In gift cards create a new gift card with the customer name and a credit of .01 and see if that works for you. Gift cards with a 0 balance will not accept a credit.

**Comment by esbyrt** [comment]
Thank you! Yes that works. I think I'll set up a range of gift card numbers with the .01 balance on them to use for returns. That will speed things up at the till.

**Comment by daN4cat** [comment]
Mmmh on a return the credit should be loaded no matter. This is a bug.

**Comment by esbyrt** [comment]
Hi. I did a little more experimenting. When the purchase is made on a gift card the return can be put back on the SAME gift card with no issues. So that part is not a bug, it is working properly. It's just a problem trying to put a credit on a new gift card with a zero balance.

**Comment by daN4cat** [comment]
@esbyrt I fixed the return to Giftcard with 0 balance. Please check the latest master, test and let me know if fine. Also check any other case you may come up as I didn't test this so extensively.

**Comment by odiea** [comment]
Working fine now. I did a Sale to deduct money also a Return to a Gift card with a 0 balance. You got it.

**Comment by esbyrt** [comment]
Works great now. Thanks!
