### ISSUE TITLE
Report Calculations logic

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1622]
![screenshot 22](https://user-images.githubusercontent.com/23611136/30634569-2f2b3e0a-9e0d-11e7-9f3e-4c4b30e98377.png)

**Comment by bill-goldberg** [comment]
can anybody explain that how this calculation is performed... as it is not the sum of subtotal or total column.

**Comment by SteveIreland** [comment]
What version of the software are you running this report from?  And if it's 3.1 or later did you successfully run the migration?

**Comment by SteveIreland** [comment]
I ran a quick test in 3.2.0 - 4f5ad57 and it seems to be working as expected there in a Sales tax scenario.  Additional tests, if necessary, will need to be done later.

**Comment by odiea** [comment]
@bill-goldberg your feedback for issues would be much more valuable if you would fill out the template.

**Comment by bill-goldberg** [comment]
yes i am using the latest build...but unable to understand the logic behind this calculation

**Comment by bill-goldberg** [comment]
i am seeing the same summary in all summary reports...what is the logic behind calculation in summary reports? what is the purpose of summary reports.. any idea will help me getting not to be confused...

**Comment by daN4cat** [comment]
Is this wrong in 3.2.0 or an issue about what you want to understand? I can't get @bill-goldberg ....

**Comment by bill-goldberg** [comment]
i cannot understand properly that is this was an issue in prior versions and improved in the latest version..
as i cannot successfully setup the latest version on my localhost... please read this wiki page..."Installing "opensourcepos" in windows and localhost" added by me... and check the steps are correct or not...because i have successfully runned that all 3 commands but still i getting a blank white page instead of login page...

**Comment by daN4cat** [comment]
But that has nothing to do with the calculation issue here.... you lost me.

**Comment by bill-goldberg** [comment]
ok .. i have setup 3.2 successfully just few minutes ago let me check this issue in latest then i will reply here.

**Comment by bill-goldberg** [comment]
Ok i got this... it was an issue in the older version but now fixed in the latest version... i checked it in 3.2

You can close this issue.. 
but give me your review about the wiki page.
