### ISSUE TITLE
need to change discount percentage to discount value in detail report

### ISSUE THREAD

**Issue by jabasinfo** [opensourcepos/opensourcepos#1623]
HI i need to change discount percentage to discount value in detailed sale report page, kindly guide me for this change

**Comment by SteveIreland** [comment]
My thought is to replace the discount percent with a discount code that can be specified on the item and or the customer and then add a discount table where each code represents a discount type that is either by percent or by amount.    We could also add a quantity and second discount percent/amount to be applied if the quantity sold meets or exceeds that quantity.

The discount code could be overridden at the point of sale.

Just adding my design suggestions if you are going to contribute a change.

.

**Comment by SteveIreland** [comment]
But you are just referring to the report.  So that shouldn't be too complicated.

**Comment by daN4cat** [comment]
Indeed....

**Comment by jabasinfo** [comment]
actually i have made some changes in pos saleto take the discount_percentage as a discount value, so thats not the problem. in reports also i have made some changes in code to calculate discount value, but only in detailed sale report page its showing as discount percentage. so i need know where u r getting discount percentage from database and making the calculation

**Comment by daN4cat** [comment]
Well the obvious answer would be somewhere in the code :-)

Do a search across the files for discount and you should get all the touch points.

**Comment by jabasinfo** [comment]
i have checked the code but i cant get it can u tell me here

**Comment by odiea** [comment]
Looks like a closed issue to me.
