### ISSUE TITLE
Office Module Icon Position

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1624]
### New Feature / Enhancement

I think the Office Module Icon should appear as the rightmost icon.  I think the reason that it's current position feels a little funny is the following:
- The app config icon formerly appeared on the right end.  
- Since most languages are left to right reading the first thing that people will look at on the top bar is the office icon whereas I don't think that's the first thing we want to draw people's attention to.

Thoughts?

**Comment by SteveIreland** [comment]
That's fine with me.  We only need to change the sort value in the modules table.

**Comment by SteveIreland** [comment]
And there might be a simple code change required in the configuration since I think sort value 1 might be hard-coded.

We would just need to change that to 999

**Comment by SteveIreland** [comment]
I sort value of 0 means that it wlll not display in the menu.  I thought I better point that out.

**Comment by objecttothis** [comment]
ok if no one objects I'll submit the pull request

**Comment by SteveIreland** [comment]
none from me.

**Comment by daN4cat** [comment]
Fine with me

**Comment by daN4cat** [comment]
@objecttothis any plans to work on this?

**Comment by objecttothis** [comment]
Monday morning. My ISP put me behind a NAT so I had to sort that out. it's a quick fix.

**Comment by objecttothis** [comment]
#1671 pull request ready to merge
