### ISSUE TITLE
Jetbrains license support

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#1625]
Just to let people in the team know that I have a little surprise (as like last year). Don't know how many of you use JetBrains IDE for development but I've gotten a couple of licenses for the work we're doing on this project. Just ping me if you're interested, they're one year valid and work for most of their products.

Specifically for PHP I use PHPStorm which works pretty well IMHO

**Comment by SteveIreland** [comment]
I've been using PHPStorm from the beginning so I'm good with licensing, but thanks for the offer.

**Comment by guillermohaad** [comment]
Hi @jekkos I'm interested
thank you

**Comment by daN4cat** [comment]
@guillermohaad I'm afraid that offer applies to people that are real and active contributors.

**Comment by guillermohaad** [comment]
@daN4cat I understand, well later when the contribution of mine is reflected we will get it, thanks

**Comment by jekkos** [comment]
All licenses have been issued. Will close this one

**Comment by jekkos** [comment]
All, I have gotten a renewal for jetbrains licenses (all of them). Contact me throu

**Comment by jekkos** [comment]
Hi Guys, I have two licenses in spare for PHPStorm / Intellij (contributors only).

Anyone interested in getting one (renewed)? Let me know!

**Comment by WebShells** [comment]
@jekkos if no one would need it, I'd like to renew mine. Otherwise i usually use sublime...

**Comment by WebShells** [comment]
@jekkos License Extended, Thanks !
