### ISSUE TITLE
Permission to open/edit branch in the master

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1627]
@jekkos is there any way to give @SteveIreland and i permission to create a branch from the master and edit that branch?  I ask because it's becoming a bit of a headache to rebase a fork of the project, create a branch of that and then submit a pull request from that branch back to the master.

**Comment by jekkos** [comment]
I just checked and I'm not sure if that's directly feasible without giving push access to all the project's branches. Not that I don't trust you guys but I think that it's good practice to keep reviewing each other's code using pull requests.

On the other hand I don't directy understand the added benefit of creating  branches directly in the repository. How does it differ from doing it in a fork? Git was designed to do just that, distributed vcs and there actually shouldn't be any extra overhead in making pull requests?

Maybe you mean that you often need to cherry pick just those changes you want to get merged, beside progressing on other stuff, while the base from where you begun keeps moving forward (in this case the master in this repo?)

**Comment by objecttothis** [comment]
@jekkos I completely agree on the need for a review system and code management rather than free-for-all style of commits.  This might just be an issue of me being new to git and github, but overhead that's happening is that my fork of the project is constantly out of date.  At least on github, I need to create a pull to pull in all the changes from the opensourcepos master to my master and if I wait too long to do that, then it won't automatically merge and I have to manually resolve the conflicts and merge it, before creating a branch on my fork.  

@daN4cat also mentioned that when he merges my pull requests there are some sort of inconvenience caused on his end by the branch being created from my fork instead of the base, but I'll have to have him elaborate.

If there is a better way for me to do it, please let me know.  One potential would be to grant the access to collaborators, but have a standing rule that you don't directly merge your branch to the master, but instead you and @daN4cat still review the code through the pull request and sign off on it.

**Comment by objecttothis** [comment]
The stupid thing that I am finding it seems is that pull requests are specific to github.  I just got egit in Eclipse setup with the opensourcepos repository and there does not seem to be the option of creating a pull request.  Instead I have to push to my fork and then open up github and create the pull request there.  I was hoping for an all-in-one solution in eclipse since it's my pet IDE, but I guess not...

As for your thoughts, can you clarify if you are referring to:
- Rebase my fork with the origin->create a branch in my fork->make code edits in the branch->submit the pull request?

Or is there a different order/steps I'm missing?

**Comment by objecttothis** [comment]
As a side note, are you able/want to give us access to assign, close, label, etc issues?

**Comment by jekkos** [comment]
Ok apparantly you need write access for that. So now @objecttothis and @SteveIreland both have access to label issues and also to push to branches. Use it wisely.

**Comment by SteveIreland** [comment]
To mangle a quote of a wise Native American from an old Clint Eastwood move ...  "I shall endeavor to persevere to be wise."  I can't promise I'll actually be wise.

**Comment by daN4cat** [comment]
@jekkos can you grant @odiea rights to close issues? It seems he lost those.

**Comment by odiea** [comment]
@daN4cat @jekkos Thanks. I got my powers back.

**Comment by odiea** [comment]
Shall we close this now?

**Comment by jekkos** [comment]
Go ahead @odiea
