### ISSUE TITLE
Error Adding and Updating Item

### ISSUE THREAD

**Issue by esbyrt** [opensourcepos/opensourcepos#1629]
Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

 I'm reporting an issue of an unmodified OSPOS installation
Installation information

OSPOS version is: 3.1.1
OSPOS git commit hash is:
PHP version is: (e.g. 5.5, 5.6, 7.0, 7.1) 7.1
MySQL or MariaDB version is: (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 10.0 .32
OS and version is: (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Windows 10/Windows 8
WebServer is: (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4.27

### Issue / Question / Bug

Since doing the update to 3.1.1 everything appeared to be working on my end. But my clients couldn't enter inventory on either of their computers in the store. They would get "error adding and updating dress" when trying to add a new dress item. Troubleshooting over the phone with them I discovered they don't see Stock Type or Item Type in the New Item screen - which led me to the employee permission screen. They both had permission to add/update/delete items but not for Item Kits as the store doesn't use them. I enabled kits for both of them and now they can enter inventory. Not a big deal having that enabled but I think that must be a bug otherwise it doesn't make sense having two separate permissions.

**Comment by SteveIreland** [comment]
Nice catch.  I thought this one had been put to bed months ago, but apparently it woke up again.  I'll take care of this one this weekend.

**Comment by daN4cat** [comment]
@esbyrt hope your business can pay a beer to us. See readme page for a contribution button ☺

**Comment by esbyrt** [comment]
Absolutely I will buy you a beer (or two). The work you are all doing here is 100% appreciated! I would like to add I'm not making a penny on this myself. I'm a bookkeeper and my clients are a small clothing store that was keeping inventory in notebooks and struggling to keep the lights on. A free solution was the only possibility for them. Without ospos they would still be scribbling lol!

**Comment by daN4cat** [comment]
Fix in master. Pleas @esbyrt test and confirm it's fine.

**Comment by esbyrt** [comment]
Tested and confirmed fixed. Thank you.
