### ISSUE TITLE
New Feature / Enhancement - Shortcut Keys in Sales module

### ISSUE THREAD

**Issue by nashtm** [opensourcepos/opensourcepos#1630]
### New Feature / Enhancement

Can Shortcut Keys be implemented in the Sales module for Payment Type , Add Payment and Complete buttons to speed up sales processing?  I think it will be a benefit.
thanks Tim

**Comment by daN4cat** [comment]
Search closed issues, this was discussed.

**Comment by nvk1990** [comment]
Tagging old issues so that somebody may find it handy: #425, #1083 

I use the below in script section of register.php

// numeric values available at https://css-tricks.com/snippets/javascript/javascript-keycodes/
$(document).keydown(function(e){
   if (e.which == 119) { //focus on customer search
$('#customer').focus();
}

    else if(e.which == 121) { //simulates add payment button click
      $('#add_payment_form').submit();
    }
});

these are simple ones I use and can be customised based on the usage.

Cheers!

**Comment by nashtm** [comment]
thanks - will add js code as needed.  Tim

**Comment by guillermohaad** [comment]
@nvk1990 thank you

**Comment by izeblood** [comment]
> Tagging old issues so that somebody may find it handy: #425, #1083
> 
> I use the below in script section of register.php
> 
> `$(document).keydown(function(e){ if (e.which == 119) { //focus on customer search $('#customer').focus(); } else if(e.which == 121) { //simulates add payment button click $('#add_payment_form').submit(); } });`
> 
> ** Numeric values available at https://css-tricks.com/snippets/javascript/javascript-keycodes/
> these are simple ones I use and can be customised based on the usage.
> 
> Cheers!
@nvk1990 
how about to complete the sale? $('#finish_sale_form ').submit();  is no effect...

**Comment by izeblood** [comment]
@daN4cat @SteveIreland @jekkos @odiea any idea to this?
@nvk1990  
I try this and it is really works....
$(document).keydown(function(e){ if (e.which == 119) { //focus on customer search $('#customer').focus(); } else if(e.which == 121) { //simulates add payment button click $('#add_payment_form').submit(); } });

But.... how about the quantity? the Complete button? and the Delete amount? please response....

**Comment by dlwiindi** [comment]
still struggling with calling the finish_sale_form submission function. nothing happens.
