### ISSUE TITLE
Item add to Sale failed

### ISSUE THREAD

**Issue by lutfiajib** [opensourcepos/opensourcepos#1632]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.11
- OSPOS git commit hash is: 76a0026
- PHP version is:   5.5
- MySQL or MariaDB version is:   MySQL 5.5
- OS and version is:  Ubuntu 14.04
- WebServer is:  Apache 2.4

### Actual behaviour
After upgrade database from "2.4 to 3.0" then "3.00 to 3.11" without problem. Then I can use almost one day without found any problem. Except... there is some items on stock it can not add to sales screen. Weird.. stock not empty and other items can add to sales screen.

**Comment by jekkos** [comment]
see #1629

**Comment by daN4cat** [comment]
@lutfiajib can you please #1629, take the latest code from master and see if it fixed your issue?

**Comment by arikb** [comment]
I have the problem described.

I upgraded to 3.2.0 ad1e63f. Logs show migration was successful. Problem was not resolved.

My setup:

OSPOS: 3.2.0
Commit: ad1e63f
PHP 7.0
MySQL 5.7.20
OS: Ubuntu server 16.04.3 LTS
Web server: Apache 2.4.18

**Comment by daN4cat** [comment]
Yes. Also upgrade from which version?

**Comment by arikb** [comment]
From 3.1.1. I'll open a new issue. Thanks.

**Comment by arikb** [comment]
Thanks for your help @daN4cat - I opened issue #1747. I'll be around to answer questions / provide more information / provide access.

**Comment by SteveIreland** [comment]
Are you able to change line 56 in index.php to "development" and then repeat the test to see if can tell you if there is a PHP related error that is being triggered?

```
	define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
```

**Comment by daN4cat** [comment]
@SteveIreland I don't think it's necessary. See #1747.
