### ISSUE TITLE
Inventory summar Export to An option does not work

### ISSUE THREAD

**Issue by ishtiaquesarwar** [opensourcepos/opensourcepos#1633]
Hi
I am using OSPOS 3.0 where in inventory summary i was trying to export the report in xls format and other format but unfortunately its not working. see the report > http://prntscr.com/gnv0rm

How to fix it ? any help or guidance would be highly appreciated

thanks
ishtiaque

**Comment by odiea** [comment]
Here is what I see using 3.2.0 on Exporting Inventory summary report. Unfortunately it will only export the visible tables. I have mine set at 25.
![2017-09-21 08_44_05-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/30702093-381e33ae-9ea9-11e7-8890-75e335df6721.png)

**Comment by ishtiaquesarwar** [comment]
Isn't it possible to do the same using version 3.0?

**Comment by odiea** [comment]
Sorry I currently do not have that version available to me.

**Comment by ishtiaquesarwar** [comment]
any other way to get it fixed ?


Regards,

<http://www.softbd.com>

A.M.Ishtiaque Sarwar / Managing Director
8801711-272324 / ceo@softbd.com

Soft Tech Innovation Ltd. *Office*: 880-1611-272324
Sector:14, Road:15, House:92, Uttara, Dhaka. 1230
http://www.softbd.com
*Consultant:*
Azadi Technologies, Chittagong.

*Skype*: softbd | *GTalk*: ishtiaque.sarwar | *Linked In*: ishtiaquesarwar
<https://bd.linkedin.com/in/ishtiaquesarwar>

*Business Concerns*: *MUTHOFUN <http://www.muthofun.com/> |  aamarPay
<https://www.aamarpay.com/> | Soft Tech Innovation Limited
<http://www.softbd.com>*

[image: Facebook] <http://www.facebook.com/ishtiaque.sarwar> [image:
Twitter] <http://www.twitter.com/ishtiaquesarwar> [image: Google Plus]
<https://plus.google.com/116320436752203524696> [image: Linkedin]
<https://bd.linkedin.com/in/ishtiaquesarwar> [image: Skype]
<http://htmlsig.com/softbd>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by odiea** [comment]
Backup your db and get the current version and do all the db updates would be my only guess..

**Comment by odiea** [comment]
I found a copy of 3.0 and I am having no issues with exporting.
![2017-09-22 11_30_15-wedidit _ powered by ospos 3 0 0](https://user-images.githubusercontent.com/10962177/30756921-d1a12b68-9f89-11e7-980b-7ece5073edfe.png)

**Comment by ishtiaquesarwar** [comment]
I can't get it to work. Is it JavaScript related issue? How to make it
work!

**Comment by odiea** [comment]
All I can suggest is go to https://github.com/opensourcepos/opensourcepos and you will see there are 12 releases. Click on Releases and You can scroll down and re-download 3.0 and see if that works for you. All I did was download it and set up database config and it worked fine for me. If you upgraded from a previous release you may have to do db updates and enable more php extensions.

**Comment by jekkos** [comment]
@ishtiaquesarwar seeing some weird things in your screenshot like duplicated item numbers. This wasn't even possible before 3.2 so you must be using a custom version. 

If you're having other people do this work for you then maybe ask them to solve these issues instead of relying on our goodwill to help you out.

**Comment by ishtiaquesarwar** [comment]
@jekkos we did few customizing but that was done by you back in 2015 end,
no one else. Nor you or anyone else touched on the thing that you have
mentioned here from screenshot reference. So your assumption is not right
at all.

**Comment by SteveIreland** [comment]
Something similar has happened to me many times before.  I look at code and say to myself "Who wrote this piece of crap?".  I then look at the change history log to learn that I wrote it years ago.   It's a very humbling experience.  Only once did I look at code that I didn't recognize and think "What an elegant way of doing that".  Once ... probably 25  years ago.

Is Reportico an option for you?  With Reportico you wouldn't be  limited to extracting a page at a time.
