### ISSUE TITLE
printing a sale the font comes out very small

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1634]
Hi, 
I have version 3.2.0  printer EPSON TM-T20II Receipt
printing a sale the font comes out very small

attached evidence

![endosurgical](https://user-images.githubusercontent.com/12921805/30718146-a4f9497e-9ee4-11e7-8362-82274fac2278.jpg)

**Comment by odiea** [comment]
![2017-09-21 14_58_04-](https://user-images.githubusercontent.com/10962177/30718507-5fed78ca-9edd-11e7-9c49-f1353a99479d.png)

**Comment by guillermohaad** [comment]
@odiea that's how I'm configured

![image](https://user-images.githubusercontent.com/12921805/30719221-4462526e-9ee8-11e7-941c-aea84b8debc4.png)

**Comment by odiea** [comment]
Then try a higher number.

**Comment by guillermohaad** [comment]
@odiea  Do you talk about increasing font size? I already did and it increases the font of the screen.
I'm working with JS Print Setup for Firefox will have something to do?

Than you

**Comment by odiea** [comment]
The printed size changes just fine on my full size printer when I adjust the font size. Maybe one of the programmers can help. I do not have a receipt printer to test it with.

**Comment by guillermohaad** [comment]
thank you @odiea  hope if any good soul can help us,

**Comment by odiea** [comment]
All I can suggest is change the font size (submit) then go to takings and reprint a receipt with different saved font size settings.

**Comment by guillermohaad** [comment]
thank you @odiea 
I'll try and tell you how it was

**Comment by daN4cat** [comment]
@guillermohaad sorted? Can we close?

**Comment by guillermohaad** [comment]
@daN4cat for more that enlarges, only increases the font of the screen but the impression does not?
thank you

**Comment by daN4cat** [comment]
Ok, I'll need to check on a printer...

**Comment by guillermohaad** [comment]
@daN4cat , Thank you

**Comment by sanubari97** [comment]
![img_20170926_103931](https://user-images.githubusercontent.com/30258590/30840454-f127c5b4-a2a9-11e7-8e6f-d6a63969de88.jpg)

I wish we could have this kind of clear view of the fonts

**Comment by guillermohaad** [comment]
@sanubari97 Do you print this ticket from OSPOS or another system?

**Comment by guillermohaad** [comment]
@daN4cat you could change the font type as it says @sanubari97 ? that example is very clear.
thank you

**Comment by guillermohaad** [comment]
friends I found it and the problem was in the type of bar code:
I had code39 set up and I changed it for EAN13 and everything came out very well.
Thank you @daN4cat 

![image](https://user-images.githubusercontent.com/12921805/30934089-1030bd74-a392-11e7-874e-1de03e870868.png)

**Comment by odiea** [comment]
If this is happening should the barcode be excluded from the font adjustment?
```
</div> " end of font div".
	<div id="barcode" style="text-align:center;" >
		<img src='data:image/png;base64,<?php echo $barcode; ?>' /><br>
		<?php echo $sale_id; ?>
	</div>

**Comment by guillermohaad** [comment]
@odiea,  this should be an improvement? because my head wanted to explode  jajaja
thank you good soul

**Comment by daN4cat** [comment]
Not sure I fully get. Is the barcode affecting the font size on the receipt printer?

**Comment by odiea** [comment]
That is my understanding of this situation.

**Comment by guillermohaad** [comment]
I'm not sure what the solution was:
or could be understood as the name of the article was very large?
There should be a limit to the name of the article.

if it was for the bar code we should take the improvement of @odiea 

anyway i am a new man  Thank you Friends...

**Comment by odiea** [comment]
Maybe someone can test this on a pos receipt printer to duplicate this problem.

**Comment by guillermohaad** [comment]
I agree with   @odiea , we need to try.

**Comment by odiea** [comment]
You could start by changing the barcode back to the original one you used and see if that changes it or try your longer item name and see if that does it.

**Comment by guillermohaad** [comment]
I'm going to try what you say and I'm informing you of the exact problem.

**Comment by sanubari97** [comment]
@guillermohaad no it from another store. Mine is the same as you.

**Comment by guillermohaad** [comment]
@sanubari97 , ok I get it.
I did the tests and definitely when the name of the article is very long, this novelty is reported, should we limit it?

**Comment by ravindug** [comment]
I'm too have this problem with earlier version when product description too long it goes to next line without shrinking font size , I'm asking here anyone figure out to solve this issue.
![print](https://user-images.githubusercontent.com/6562505/36145153-7e5c90e6-10d6-11e8-9f7a-98cea4a5cbf6.JPG)

**Comment by guillermohaad** [comment]
hi@ravindug ,  as there is still no solution to limit the field, there was no way out except to change the size of the description of each item and problem fixed.

**Comment by guillermohaad** [comment]
@ravindug  Could you fix this problem? or someone else can I correct it?
Was this problem corrected in the new version?

**Comment by mckaygerhard** [comment]
i'm afraid still happened, but only with thermal printers..

**Comment by guillermohaad** [comment]
@mckaygerhard  I mean include it in development as you say?

**Comment by guillermohaad** [comment]
@mckaygerhard in version 3.2.0 this was not corrected?

**Comment by mckaygerhard** [comment]
nop, for thermal printers.. i have enought devices to test and it's not working! the product description must be cut, here in my country we cut the product description before printing, some thermal printers automatically scale the font unless we send some commands

my fork has a brand that manages that but its paid! at gitlab

**Comment by guillermohaad** [comment]
attached evidence of what happens, besides the cut of the paper does it well down ??
![image](https://user-images.githubusercontent.com/12921805/39200630-4b79886a-47b2-11e8-950e-c537597df1ed.png)

**Comment by mckaygerhard** [comment]
kakaka exactly as you attached the iamge,

explanation to @odiea @daN4cat @jekkos and @SteveIreland the developers of ospos due i can see that no have enought hardware to test:  **size of fonts are resized but the paper still "think" that font are in the original size**, so the amount of apper forward like if the font was not resized! taht can be viewed in some printersdebuggin and some others projects

**quick workaround its cut the item/product description**

**Comment by nerv55** [comment]
@guillermohaad adjust your browser printing option, remove all margins, head and footer

**Comment by mckaygerhard** [comment]
ah but the issue was closed ! as resolved? lest try the @nerv55 solution and report feedback @guillermohaad

**Comment by guillermohaad** [comment]
thank you 
I'm going to try what my friend @nerv55  , says and inform them if this is the solution

**Comment by mckaygerhard** [comment]
umm i now remenber @guillermohaad that i write something in the wiki about it: https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-for-OSPOS-Printing please check due the info that @nerv55 i think already are here

**Comment by guillermohaad** [comment]
eureka, this is the solution, thanks to @nerv55  and @mckaygerhard 

![image](https://user-images.githubusercontent.com/12921805/39201866-f0448cf2-47b5-11e8-8d61-3e1bc4d3ed37.png)

**Comment by mckaygerhard** [comment]
so the wiki information are correct now!

**Comment by nerv55** [comment]
@guillermohaad make the same, and be sure to save the configuration, also must scale document.

**Comment by mckaygerhard** [comment]
of course, was pointed in the wiki! there's a mobile appp in development that solves that, but of course only for bluetooh devices..

**Comment by nerv55** [comment]
@guillermohaad  here more info https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-for-OSPOS-Printing please check

**Comment by guillermohaad** [comment]
thank you @nerv55  and @mckaygerhard I'm going to check and tell them how it was

**Comment by guillermohaad** [comment]
@nerv55 , Thanks for your help, I am solved, you are a great friend.
thank to @mckaygerhard

**Comment by Saiuke** [comment]
The links aren't working anymore. I need the solution to the same problem
