### ISSUE TITLE
view of page is broken on installation of latest version 3.2

### ISSUE THREAD

**Issue by abdulrehman6** [opensourcepos/opensourcepos#1636]
Hi i have installed new version and after login home page not showing correct.
please help on this issue. here is the screen shot. thanks
![issue](https://user-images.githubusercontent.com/32044325/30765364-d36bbb50-a008-11e7-8949-dcb8670d8a80.png)

**Comment by daN4cat** [comment]
Check readme and download files from bintray not github.

**Comment by abdulrehman6** [comment]
thanks for reply. i have download from bintray version 3.1.1.
 on index page its showing a massage "Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php"

**Comment by daN4cat** [comment]
Point to public dir

**Comment by abdulrehman6** [comment]
in public folder i have index.php file there please tell what to edit in this file?

**Comment by odiea** [comment]
opensourcepos.20170909085348.3.1.1.76a002.zip Is the file you need to download. Not the source code .zip
