### ISSUE TITLE
composer install showing error for gd extension

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1637]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections "New Feature / Enhancement" and "Issue / Question / Bug".
2. Remove just the one of the two sections you don't need 
3. Remove this section as it's just a guideline
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhancement

*For New Features or Enhancements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.*

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information
- OSPOS version is: latest
- OSPOS git commit hash is: 
- PHP version is:   5.5
- MySQL version is: 5.6
- OS and version is:   Windows 10 x64
- WebServer is:   Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:  WAMP

**Comment by bill-goldberg** [comment]
just few minutes ago i downloaded the latest master zip and tried to install it...using the commands
composer install
npm install
grunt --force

but the composer install command is showing an error about enabling gd extension which is already enabled in my php configuration...

**Comment by bill-goldberg** [comment]
![screenshot 38](https://user-images.githubusercontent.com/23611136/30771591-f45960dc-a068-11e7-8eb4-fb2cf17a5abb.png)

**Comment by bill-goldberg** [comment]
![screenshot 38](https://user-images.githubusercontent.com/23611136/30771595-1b643b16-a069-11e7-8318-e68146d23205.png)

**Comment by bill-goldberg** [comment]
![screenshot 39](https://user-images.githubusercontent.com/23611136/30771604-3c11bb40-a069-11e7-90b9-ac338fdbb88d.png)

**Comment by bill-goldberg** [comment]
and please try to create an article in the wiki section for installing opensourcepos on windows machine step by step for latest 3mb zip files...

**Comment by daN4cat** [comment]
I'm pretty sure @bill-goldberg that you can help us with that, wiki editing is open. Also there are already wiki pages with windows installation guides, so it's a matter of updating them or tidy them up.

**Comment by daN4cat** [comment]
Please note that composer is asking the Php7 version of gd and you stated in the template php 5.5. Check that point as first thing...

**Comment by bill-goldberg** [comment]
please confirm once more... in the screenshot i uploaded ... i think its the version for dompdf v0.7...where did you see php7 version
