### ISSUE TITLE
Custome Invoice Number Not SAVED

### ISSUE THREAD

**Issue by arrazka** [opensourcepos/opensourcepos#1638]
OPSPOS : 4f5ad57
Register Mode : Sales Receipt. 

Create Invoice = Chechked  and insert my custom invoice nuber ex: INV82828
click Complete
viewing invoice page 
Invoice # 1 <--- this should be INV82828

I try another sales but still have problem :
Invoice #2 <--- not my custom invoice

**Comment by odiea** [comment]
You will now need to add a customer. Then choose Invoice from the dropdown list.

**Comment by arrazka** [comment]
I have adding customer, but still no saved.. 
 when register as Sales Mode we cant create custom invoice number. showing in the bottom print after sale.. I chechked Create Invoice and insert my custom invoice number .. but not saved...

**Comment by odiea** [comment]
Have you read the wiki about Sales. That explains the type of Invoicing numbering that is Available.
I believe what you are seeing is just the available template that is currently set for your selected Invoicing and not a location to place an Invoice number. You can try to locate issues about Invoicing.

**Comment by arrazka** [comment]
Sorry sir if I am wrong in explaining the question, 
in the config I check **Enable Invoicing**.
so in the register mode : Sales Receipt , Quote, Invoie and Return..

I choose **Sales Receipt Mode**.. 
adding item to cart
adding customer
adding payment
than **Create Invoice Form** appear in the bottom. 
I chechked Create Invoice than insert Invoice Number. that mean $keep_custom = TRUE) 
I click Complete -- > $this->load->view('sales/invoice', $data);
Invoice # 9 ( 9 is auto generate same like as invoice mode / custom invoice not working )

**Comment by odiea** [comment]
You will have to give me the version you are using. I am on 3.2.0 and the invoice number at the bottom of the sales screen no longer shows.

**Comment by arrazka** [comment]
$config['application_version'] = '3.2.0';
<?php echo $this->config->item('application_version'); ?> - <?php echo substr('$Id: 4f5ad5761503bbc94152cbf16afa76439ca155b8 $', 5, 7); ?></strong>.

**Comment by arrazka** [comment]
$Id: 4f5ad5761503bbc94152cbf16afa76439ca155b8 $', 5, 7); ?>

**Comment by SteveIreland** [comment]
I left some of the legacy behavior in the system such that even in Sales Register mode if the user checks the "Create Invoice" button then the system will save it as an invoice (even though it was created in Sales Register mode.")   In a test I performed just a few minutes ago  if the user allows the system to auto-assign the invoice number then all is good.  However, if the user tries to enter a manual invoice number the manual invoice number is not saved.

This is a bug.  I know at one point I had this working but it probably go lost in one of the many code merges I did. 

My preference would be to not allow manual invoice number entry.  It just doesn't make sense to me, but there may be a justifiable need for it ... so I'll try to resolve that this weekend (or next).

**Comment by arrazka** [comment]
Hi Mr.SteveIreland, Thank you for your attention, hopefully this problem can be solved immediately

**Comment by odiea** [comment]
I forgot and removed the check invoice box  from my test version.

**Comment by daN4cat** [comment]
Fix in master

**Comment by odiea** [comment]
Works now. No issue saving custom invoice.
