### ISSUE TITLE
Problem in INSTALL

### ISSUE THREAD

**Issue by ahmednassr** [opensourcepos/opensourcepos#1640]
hello i want setup opensourcepos

show this message

![555556666](https://user-images.githubusercontent.com/13977631/30780889-12836c64-a11e-11e7-8fa0-4af8d922d7b5.PNG)

**Comment by odiea** [comment]
https://github.com/opensourcepos/opensourcepos/releases is the current stable version

**Comment by simonaogstino** [comment]
Include public folder in the root.

**Comment by ahmednassr** [comment]
![8888](https://user-images.githubusercontent.com/13977631/30781216-9922bc2a-a123-11e7-908e-005c0bb39b02.PNG)
this messgae show also

**Comment by simonaogstino** [comment]
fix .htaccess file in public folder.
 like this

# if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
RewriteRule ^(.*)$ /<OSPOS path>/public/index.php?/$1 [L]

Regards
Simon

**Comment by daN4cat** [comment]
@ahmednassr read the error_log in public dir, what is it saying?

**Comment by ahmednassr** [comment]
![image](https://user-images.githubusercontent.com/13977631/30797509-fd9ea68a-a1de-11e7-9999-5d233b05b51e.png)

**Comment by ahmednassr** [comment]
this error showing me /

**Comment by ahmednassr** [comment]
any one here for solve this problem please

**Comment by odiea** [comment]
Yes read the wiki.

**Comment by ahmednassr** [comment]
i am make all true configuration is true and not open also show this message http error 500

**Comment by bill-goldberg** [comment]
for this error "http error 500" check your apache config file and enable rewrite module... may be it will solve your problem...

**Comment by ahmednassr** [comment]
this message showing on my site online not localhost and i active rewrite mode in localhost it's work on localhost but showing this message
![image](https://user-images.githubusercontent.com/13977631/30852276-ea4408ca-a2b3-11e7-9799-db87cc77f1cb.png)

**Comment by bill-goldberg** [comment]
please check that all the required php extensions are enabled. its showing the php.ini file in the error.. it could be the extensions issue...

**Comment by hussain4996** [comment]
I am facing the same issue. The problem in beta version is that it doesn't have the vendor folder which is system directory so I was getting the same error your system folder path doesn't appear to set correctly. 
After using the stable version I am getting Installation is not correct I checked error log and extensions are installed but still getting error PHP requires extension 
`[Thu Sep 28 04:05:24.997383 2017] [:error] [pid 4164:tid 1724] [client ::1:64252] PHP installed extensions: Core, bcmath, calendar, ctype, date, ereg, filter, ftp, hash, iconv, json, mcrypt, SPL, odbc, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, wddx, xml, xmlreader, xmlwriter, apache2handler, openssl, curl, fileinfo, gd, gettext, intl, mbstring, exif, mysql, mysqli, pdo_mysql, pdo_sqlite, Phar, mhash, referer: http://localhost/ospos/public/login
[Thu Sep 28 04:05:24.997383 2017] [:error] [pid 4164:tid 1724] [client ::1:64252] PHP required extensions: bcmath, intl, gd, sockets, mcrypt, referer: http://localhost/ospos/public/login
`

**Comment by odiea** [comment]
You will have to go in and enable the extensions that are not enabled. It appears you are missing sockets.

**Comment by hussain4996** [comment]
@odiea  Thank you so much for taking out some time to reply the question. 
Yes you right. But if you see I already enabled the bcmath, intl extension but still I am getting the error (Php required extensions) its a little strange.
 Also I have gd2 installed is it fine? And lastly I do not have mcrypt in ext folder. Can you tell me from where I can download the missing extension?

**Comment by odiea** [comment]
You should see it in your php.ini file.

**Comment by hussain4996** [comment]
Thank you @odiea . I really appreciate that how you managed some time from your precious time to help out. Its working now. Its really a great open source pos application for small business.

**Comment by MrMegamind** [comment]
I went to PHP version in cPanel and activated intl extension and it all worked. So the issue with "php.ini" is definitely connected to missing extensions

**Comment by mujahid15** [comment]
> 
> 
> hello i want setup opensourcepos
> 
> show this message
> 
> ![555556666](https://user-images.githubusercontent.com/13977631/30780889-12836c64-a11e-11e7-8fa0-4af8d922d7b5.PNG)

add vendor folder in this project  main directory
then edit php.ini file intl line, then restart xampp

**Comment by odiea** [comment]
Read the entire issue!!

**Comment by khnRzk** [comment]
These error comes because your PHP required extensions: bcmath, intl, gd, openssl, mbstring, curl
