### ISSUE TITLE
Question when lost internet

### ISSUE THREAD

**Issue by waynebr76** [opensourcepos/opensourcepos#1642]
### IMPORTANT IMPORTANT IMPORTANT

###Question 

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- x[] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- []x I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is:  4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) Mysql
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Ubuntu 14.04
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Actual behaviour
Today I lost internet connection for the whole day due to a network outage, for some reason OSPOS crawled and was unusable for most of the time even though it is hosted on a local server and I could access VestaCP and also webmin and these worked as normal. Is there any reason why Ospos would have difficulties and can I do anything to prevent this happening next time?

**Comment by odiea** [comment]
Store config/general disable send statistics should help

**Comment by waynebr76** [comment]
Thanks I will try that

**Comment by waynebr76** [comment]
Hi I have done what you said but it is still unslow without an internet connection to the point that it is unusable. What else could I try

**Comment by waynebr76** [comment]
After closing the browser and 're opening it appears faster. I will see how it goes tomorrow

**Comment by waynebr76** [comment]
Hi just an update on this, I still have no internet today and OSPOS is still runing at a speed that makes in unusable. Not sure what I can do to make this stable when in offline mode
