### ISSUE TITLE
Print Unpaid Receipt

### ISSUE THREAD

**Issue by sanubari97** [opensourcepos/opensourcepos#1644]
can we print the receipt even the customer haven't pay it yet ?
 Sometimes neighbours take the item first and pay later, so we need to print the receipt and make the neighbour sign as a prove.

**Comment by SteveIreland** [comment]
That behavior is what involces is for

**Comment by sanubari97** [comment]
yes but u cant print it out unless u input the amount tendered. The amount tendered must be 0.

**Comment by daN4cat** [comment]
Use due payment for the sell on credit

**Comment by SteveIreland** [comment]
Invoices can be printed without any payment transactions having been entered if you enable invoice mode and put the register in "Sales by Invoice" mode.

**Comment by sanubari97** [comment]
owh and u have to input the customer name too to be able printed it.
ok got it, thank you.
