### ISSUE TITLE
Employees date_of_birth or age attribute should be added.

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1645]
Please give an option for date_of_birth or age for new_employees. This is a required field . But it is not present untill now...

**Comment by daN4cat** [comment]
I would say no, from a security point of view adding even the date of birth when it's not really necessary is a bad idea. If a leak happens, as employee you might be exposed to higher liability cost.

Therefore I'm not going to implement that and discourage the implementation.
