### ISSUE TITLE
Weblate Azerbaijani problems

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1646]
### Issue / Question / Bug
Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

@jekkos @daN4cat The weblate update of Azerbaijani from github worked, however I'm getting errors when I try to make changes to the translation.  In Zen Mode the ajax spinner just spins without showing the green checkbox and when I try to make a change in the standard mode I get the error:

> 
>     Internal Server Error 
> 
> Server Error
> 
> The server had serious problems while serving your request. We've just sent our trained monkeys to fix the issue.

**Comment by objecttothis** [comment]
I forgot to mention that changing the Russian translation is now working perfectly.  Thank you to whoever fixed that.

**Comment by daN4cat** [comment]
Didn't know OSPOS has now a Zen mode. @SteveIreland is that a hidden feature you enabled with some secret sequence of function keys?

**Comment by SteveIreland** [comment]
I'm innocent.

**Comment by objecttothis** [comment]
yeah it's up,down,up,down,b,a,b,a,select,start while saying "make me one with everything". ;). just kidding, it's Zen mode in weblate

**Comment by jekkos** [comment]
Hm yes @objecttothis indeed I've been getting quite some error logs in my mail due to this.. seems to be some permission problem I'll check once I find the time.
Also need to check if changes are propagated correctly to the git after save

**Comment by objecttothis** [comment]
@jekkos thank you.  You rock.

**Comment by jekkos** [comment]
@objecttothis should work now

**Comment by objecttothis** [comment]
@jekkos, yes and no.  It does work in that it is now saving translation changes, but no in that all the translations are mixed up.  I think that what may have happened is that when the Azerbaijani was transposed from github onto weblate the columns got shifted.  For example, in giftcards the Azerbaijani translation for "Inventory to add or subtract." is actually the translation for "Could not delete selected Gift Card(s), one or more of the selected Gift Cards has sales." and the translation that is in that one is the translation for "Category"... I don't know if it's consistent but it appears to be shifted down five phrases.

**Comment by objecttothis** [comment]
@jekkos, after looking into it more, it appears that this was a problem I caused.  Somehow in the commits on github the translations were shifted.  I will fix it in weblate and then we should be good.
