### ISSUE TITLE
This Page is Not Working HTTP 500 Error

### ISSUE THREAD

**Issue by rkdaredevil** [opensourcepos/opensourcepos#1648]
http://localhost/opensourcepos/public/
This page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500

I'm running xampp on windows 
Clone latest Git Repo
Composer install
bower install
package.json install
but still getting this error

**Comment by odiea** [comment]
https://github.com/opensourcepos/opensourcepos/releases is the current stable version

**Comment by obink** [comment]
sorry to interrupt, i just faced the same problem. and maybe i am the Ignorant here...


i think @rkdaredevil didn't read about the install.MD

there say "6. Modify application/config/config.php encryption key with your own"
and you can find it on specific peculiar "config.php" file about 
> $config['encryption_key'] = getenv('ENCRYPTION_KEY') ? getenv('ENCRYPTION_KEY') : '';

this is something we need to be done before starting the index file.

am i right @odiea ?

**Comment by odiea** [comment]
It is an option to use either your key or the programs key.
