### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by nsk123456** [opensourcepos/opensourcepos#1650]
![untitled](https://user-images.githubusercontent.com/11977139/30945898-60b78952-a433-11e7-8186-bbd4349785ab.png)

**Comment by odiea** [comment]
Read the current and closed issues. This has been asked now more times then I can Count.

**Comment by nsk123456** [comment]
i try all the solutions... is there way i can directly get the modified code??? coz im not that much tech savvy.. can pay if want...
