### ISSUE TITLE
transaction number on receipts

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1652]
how to search for a particular receipt in reports or sales takings ? there is no way to search for a particular receipt. and the transaction number is a good option for this... please try to add the transaction number on receipt both in sales and receivings

**Comment by odiea** [comment]
pos or POS then transaction number pos 129 POS(space)129.

**Comment by bill-goldberg** [comment]
how to search this  instantly in reports or takings etc?

**Comment by odiea** [comment]
In takings set the date to all time and you can search for a receipt. Reports does not have a search by pos feature.
