### ISSUE TITLE
just to confirm- this invioce or sale page  can print good on thermal printer as a reciepts?

### ISSUE THREAD

**Issue by abdulrehman6** [opensourcepos/opensourcepos#1656]

**Comment by SteveIreland** [comment]
The original and current invoice was designed for full size paper.  It never occurred to me that it might also need to print on a thermal printer so I don't know what it would look like on a thermal printer, but I don't think it will be pretty.

**Comment by abdulrehman6** [comment]
Once i print on thermal printer the sale receipt printer dont stop to release paper untill i switch off

**Comment by hprafa** [comment]
@abdulrehman6  yes you can print on a Thermal Printer, you just need to isntall de drivers for your printer. I'm actually using an Epson TM-T58, the only thing you need to do if you use Chrome, is Ctrl-P select your printer and then adjust the scale.

**Comment by abdulrehman6** [comment]
@hprafa thanks for your reply. I have test it using chrome and adjusted scale receipt is okay but print dont stop at the end of recepit its continue printing blank paper and dont cut the paper

**Comment by sanubari97** [comment]
try to experiment with your printer's "printing preferences"
