### ISSUE TITLE
setup directory size

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1657]
i have installed the latest opensourcepos-master with composer, npm, grunt etc and the final size of the directory is about 170 mb or more... after making its zip it is still about 70mb..which is much more than previous setups

Please guide me for removing unnecessary directories from the final install directory...
here is the screenshot of final install directory...

**Comment by bill-goldberg** [comment]
![screenshot 54](https://user-images.githubusercontent.com/23611136/30975516-1c100dd0-a490-11e7-8848-c6c2cf9c53d7.png)

**Comment by daN4cat** [comment]
Not sure I understand, why are you installing the development environment if you don't know what to do about that?

There is the bintray file with everything in it for production environment. Just check the readme and use that. Leave all the composer and grunt stuff behind.

**Comment by bill-goldberg** [comment]
ok...but will i get the latest build on bintray?

**Comment by odiea** [comment]
Yes. That appears to show 10 min to 1 hr after the commit.

**Comment by bill-goldberg** [comment]
ok

**Comment by bill-goldberg** [comment]
opensourcepos.20170924192539.master.b1b630.zip 
is this the latest stable build?
uploaded 4 days ago

**Comment by daN4cat** [comment]
Looks the latest because there were no submission in the past few days
