### ISSUE TITLE
Store Config HTTP ERROR 500 + 

### ISSUE THREAD

**Issue by arrazka** [opensourcepos/opensourcepos#1658]
using Open Source Point Of Sale version 3.2.0 - 4f5ad57.
a few minutes ago before I wrote this issue, I downloaded the master file, then did the installation, http: // localhost / ospos / public /. login page appears,
after login, click -> office -> store config -> blank page
"
This page is not working

localhost is currently unable to handle this request.
HTTP ERROR 500
"
click -> employees -> new employess -> no form appears
so when click new item, new taxes code, and other form does not appear.

**Comment by daN4cat** [comment]
Check old cases this was covered again and again and again and ....
