### ISSUE TITLE
Swedish language 

### ISSUE THREAD

**Issue by caston79** [opensourcepos/opensourcepos#1659]
Question

I've translates OSPOS to swedish a few days ago in Weblate.
How long will it take before Swedish is included in the code ?

I need to check e few items since for example table can be translated in to 2 words.
Bord = dinner table and tabell=database table.

/mats

**Comment by jekkos** [comment]
Hi I can see your changes in weblate indeed. Thanks for that! However still for some reason it does not directly propagate to the git repository. I'lll need to check first why.

**Comment by caston79** [comment]
Hi hope you get some time to look at it :-) 
/mats

**Comment by daN4cat** [comment]
@jekkos any progress?

**Comment by daN4cat** [comment]
Not sure what happened but after rebasing Weblate with the latest from master here, Gift Card and Reports don't look translated anymore.

**Comment by caston79** [comment]
Shall I translate  Gift Card and Reports again or is there a backup ?
Seems weblate hadn't transferred the translations to the code...

**Comment by daN4cat** [comment]
@caston79 I was expecting a Weblate rebase without impacts but apparently it wasn't the case for Swedish and those two files. Not sure @jekkos is able to recover some old file, alternative is to re-translate (I know a pain in the a**, sorry about that).
Besides, I couldn't push Swedish translation to master here using Weblate UI, @jekkos any idea?

**Comment by jekkos** [comment]
Been off for a couple of days, I'll try to catch up tonight. Anyway was looking into weblate issues last week. Saw that it might be due to a php translation toolkit bug (which has some fixes in latest weblate master) so I tried to fetch the latest images..

**Comment by jekkos** [comment]
But will need to verify if this resolves the issues as it occurs only for certain languages

**Comment by caston79** [comment]
Hi
ok, let me know if I shall retranslate it again o if you can restore it from some kind of backup.

/caston79

**Comment by jekkos** [comment]
Ok I checked weblate again and the swedish translation is there (at least if you download the .po files for the application components). Except if you download php strings (which we actually need) then it just shows empty strings.

**Comment by jekkos** [comment]
I suppose this PR could fix the issues here

https://github.com/translate/translate/pull/3697/files

I might want to patch the installation manually to see if it helps

**Comment by daN4cat** [comment]
Any news, @jekkos ?

**Comment by caston79** [comment]
Any news, @jekkos , @daN4cat ?

**Comment by jekkos** [comment]
Will need to check how to apply this PR to the docker container, as it's not under git afaik.

**Comment by daN4cat** [comment]
@jekkos any chance to give it a kick over the weekend?

**Comment by daN4cat** [comment]
@jekkos news?

**Comment by jekkos** [comment]
wiill try to have a look this week

**Comment by daN4cat** [comment]
@jekkos have you the chance to look into this?

**Comment by jekkos** [comment]
yesterday. I need to patch one of the django dependencies using what is in a PR somewhere on github, haven't directly found the needed file to do it. I have however seen it in another weblate docker setup

Although I did update to the latest weblate image but the php support is still problematic.

**Comment by daN4cat** [comment]
@jekkos what about this story?

**Comment by daN4cat** [comment]
I checked Weblate and most of the Swedish translations are gone... hmmmm

**Comment by daN4cat** [comment]
I'm afraid that the translations needs to be reapplied from scratch....

**Comment by caston79** [comment]
Ok. So timme for a retranslate it again

Will it work now?? Don’t want to do it again. ;-)

/caston79

**Comment by daN4cat** [comment]
@caston79 many have translated in other languages (e.g. Bulgarian, Italian, Vietnamese) and translations are now in the code.
So it should be fine this time, but @jekkos please confirm.

**Comment by caston79** [comment]
How long after I start retranslating can you tell if the new translation is correctly transfer to the master repository ?

**Comment by daN4cat** [comment]
You can translate one file and then @jekkos or I can commit to master so we can see if all is fine.

**Comment by daN4cat** [comment]
If you do it now, once do I can commit to master.

**Comment by daN4cat** [comment]
@caston79 yes, works fine, I just pushed some of your translation to master. Keep going and once all done let me know that I push the translations to master.

I assume it will take some time to go through all.

**Comment by daN4cat** [comment]
I close this because I saw you translated and committed and the translation went straight to GitHub master.
So now it's in your hands to finish the job.

Thanks again for the contribution and I'm sorry if it's a bit of a restart and some work went lost. I sense that somehow it want overridden during a pull/rebase and so went lost.
