### ISSUE TITLE
speed up proccessing payment

### ISSUE THREAD

**Issue by bigbossmaher** [opensourcepos/opensourcepos#1660]
hello ,
i think clicking on add payment then complete then going to sale register can take a long time 
can some one give a solution

**Comment by odiea** [comment]
Cashiers make mistakes. Management wants to know something about the sale. At this point in time the Sale can also be cancelled or Suspended.

![2017-09-30 15_36_59-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/31049685-429446ae-a5f5-11e7-94c2-ac20869bf990.png)

**Comment by daN4cat** [comment]
And I made even simpler compared to what used to be....

**Comment by bigbossmaher** [comment]
i want to use this script  in a supermarket , when the Cashier click on add payment then coplete then return to register .
i'm using onlu cash , so i don't  need any other options .
i want to make a button that resume all those steps . is that possible ?

**Comment by daN4cat** [comment]
yes, you can customise like you prefer for your needs.
