### ISSUE TITLE
blockUI issue when modifing footer.php

### ISSUE THREAD

**Issue by bigbossmaher** [opensourcepos/opensourcepos#1661]
hello ,
when i modified the views/partial/footer.php adding some jquery code in the button then restarting apache the home screen become blocked by blockuI
this is a fresh installaion , i only modified the footer.php to e like this
		</div>
	</div>

	<div id="footer">
		<div class="jumbotron push-spaces">
			<strong><?php echo $this->lang->line('common_you_are_using_ospos'); ?>
  			<?php echo $this->config->item('application_version'); ?> - <?php echo substr('$Id: 4f5ad5761503bbc94152cbf16afa76439ca155b8 $', 5, 7); ?></strong>.
			<?php echo $this->lang->line('common_please_visit_my'); ?>
			<a href="https://github.com/jekkos/opensourcepos" target="_blank"><?php echo $this->lang->line('common_website'); ?></a>
			<?php echo $this->lang->line('common_learn_about_project'); ?>
		</div>
	</div>
		

	<script type="text/javascript">

	$(document).ready(function(){
	//var keypressed ;
	
	$(document).bind('keyup', function(e) {
		if ( (e.which == 115) || (e.which == 118) ) {
	localStorage.setItem('keypressed', e.which);
    $('#add_payment_button').trigger('click');

		}
});
	
  	if ($( '#finish_sale_button' ).length){
		if (localStorage.getItem('keypressed') == 115){
	$( "#sales_print_after_sale" ).prop( "checked", false );	
    $('#finish_sale_button').trigger('click');
		}
		if (localStorage.getItem('keypressed') == 118){
		$( "#sales_print_after_sale" ).prop( "checked", true );	
    $('#finish_sale_button').trigger('click');
		}
};
  	if ($(location).attr('href') == "http://localhost/ospos1/public/sales/complete"){
		
    window.location = "http://localhost/ospos1/public/sales";   
};

	$(document).bind('keyup', function(e) {
		if ( e.which == 40 ) {
    $( "#register_wrapper tr:last" ).prev("tr").children("td").last().prev("td").prev("td").prev("td").find('input').select();

		}
		
});
});
	
		
	</script>
</body>
</html>

![capture1](https://user-images.githubusercontent.com/15154710/31095553-29620af0-a7b1-11e7-9fe3-f6755ac3a1e5.PNG)

**Comment by daN4cat** [comment]
That's the correct behaviour, especially when people don't read the license file.

**Comment by bigbossmaher** [comment]
it is not related to footer 
i'm getting also the same behaviour when modifying register.php

**Comment by daN4cat** [comment]
check if the english version gives you the same issue, if not the french translations where not right
