### ISSUE TITLE
Merging data from 2 stores

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1662]
i have this application installed on 2 laptops and there is lots of data in both setups... Now i am deciding to merge both database and continue all these on a single setup/desktop.

The application version and database structure are same... only the data like items list, sales and receivings history , customers and suppliers list are different.

any idea about this kind of scenario?

**Comment by daN4cat** [comment]
You would need to run SQL scripts to do the data migration. However you cannot expect the numbering of sales and receiving to be retained as the progress numbering will most likely overlap.
Also bear in mind that inventory tracking needs to regenerated taking into account new sales and receiving transactions. The best way to approach this is to create two sample databases with let say 10 transactions and do a merge.
Also I can see that you might have a problem with customer referencing as the import could require a different linking Id. 
Not a trivial task, but good luck with that.
