### ISSUE TITLE
Invoice export as PDF

### ISSUE THREAD

**Issue by simonaogstino** [opensourcepos/opensourcepos#1663]
I start using this system a month ago and looks very powerful, one of the clients asked to export the invoices as a PDF file to be able to send the invoices via email to his customers.

any kind solution ?

Regards
Simon

**Comment by odiea** [comment]
Yes. That feature is already included.

**Comment by simonaogstino** [comment]
Hello Odiea,

can you please tell me how can I export invoice to PDF.

Thanks

**Comment by odiea** [comment]
All I had to do was send the Invoice to the customer via email and it will show up as a pdf. Unless I am misunderstanding what you are requesting.

**Comment by odiea** [comment]
I did notice this issue with the emailed pdf because the language has not been created for it.
![2017-10-05 07_18_34-inbox - oagnew netscape net - mozilla thunderbird](https://user-images.githubusercontent.com/10962177/31229331-91eec7d2-a99d-11e7-94c6-67b862c595dc.png)

**Comment by daN4cat** [comment]
Ok, so there is a bug with the title of the pdf.

**Comment by daN4cat** [comment]
BTW what Simon is asking is different. What he could do is to use a pdf printer driver and print the invoice with that pdf printer.

**Comment by daN4cat** [comment]
@SteveIreland this is something you changed and I'm not sure what the correct fix should be, in controllers/Sales.php line 791 I read:

`$filename = sys_get_temp_dir() . '/' . $this->lang->line("sales_N") . '-' . str_replace('/', '-', $number) . '.pdf';`

There is no sales_N translation, should that be `sales_$type` like in the subject line?
That would sound a possible fix.

**Comment by odiea** [comment]
Looks good now using your suggested fix.

![2017-10-07 06_58_51-](https://user-images.githubusercontent.com/10962177/31308066-1ca2011a-ab2d-11e7-8742-2e6782739784.png)

**Comment by daN4cat** [comment]
Fixed with my suggestion, if any different @SteveIreland can change it. At least this solution is consistent with the email subject line.

**Comment by SteveIreland** [comment]
👍 That works for me if it works for everyone else.
