### ISSUE TITLE
Handling multiple pos in a single store

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1664]
i want to setup 2 copy/pos of this application in my 1 store to achieve faster transactions for large number of customers...
but i want to manage all the data in a single database...
Is there any solution to this problem? Please let me know...

**Comment by daN4cat** [comment]
Before jumping to solutions you should think about the (real) problem: what you are trying to solve and what business value will give you. Because based on that you can decide if it's worth investing time or money to do something.

**Comment by odiea** [comment]
The other option would be to point the other computer's browser to the ip address of the computer that contains the program and database.

**Comment by SteveIreland** [comment]
Interesting suggestion and theoretically possible, but it's obviously not part of the test scenario.  You would need to refresh pick one box as the master and if the confit changes then you would need to reboot the child app server. That's the first issue that comes to mind

**Comment by odiea** [comment]
So you are insinuating that this is not a multi-user networked program.

**Comment by SteveIreland** [comment]
If that question was directed at me then my response is "not at all".  It most definitely IS a multi-user networked application.

I was just pointing out that I haven't yet heard of anyone configured to run a single database servicing two PHP app servers and since CodeIgniter performs its own session management instead of delegating it to the PHP app server I don't know if CodeIgnier supports the suggested architecture.  I'm not saying that it doesn't ... I just don't know.

**Comment by daN4cat** [comment]
Going back to my point, what is the problem is trying to solve? Architecting complications is an expensive aim.

**Comment by SteveIreland** [comment]
I'm guessing that he is trying to implement some variation of a server farm in order to distribute the resource demand across multiple boxes in an effort to achieve nirvana.

Just guessing though.  😈

**Comment by daN4cat** [comment]
Cluster deployment is not a simple job, also what kind of load is he talking about and using what HW?
And then you have the point of the DB and Data Replication & Recovery. Having a cluster pointing to a common database needs to be made redundant to avoid single point of failure scenarios.... just to mention few things.

**Comment by Ibnumarjan** [comment]
@bill-goldberg : Should clearly describe what is actually trying to achieve.

Might be he is simply want a multiple cashiers running the same system. In this case @bill-goldberg, you need to setup simple network with a server, in server hardware you have to implement the system  (including database). then you can seetup multiple cashiers by accessing the pos through server ip. 

If you have no budget to setup separate server hardware, you can make one of the two cashier's PC as your server, though there will be perfomance issue.

**Comment by daN4cat** [comment]
No further, I close

**Comment by AlaaEldinMohamed** [comment]
@Ibnumarjan I think this is what he wanted to say, an outlet with several POS (like Supermarket with 3~4 checkout lane. now what you have proposed sounds like a working solution BUT how he could identify or distinguish each POS sales transactions ? knowing that at equivalent shops the users could do sales transactions on different checkout lane which means we can not only depend on user's transactions log if we would like to dig into each POS transactions.
for exe ( checkout lane for home appliance and another 2 for Grocery)
