### ISSUE TITLE
Cant edit amount tendered invoice

### ISSUE THREAD

**Issue by sanubari97** [opensourcepos/opensourcepos#1665]
![untitled](https://user-images.githubusercontent.com/30258590/31157490-fa3c329e-a8ed-11e7-8532-b38325dcbeb4.jpg)

![untitle22d](https://user-images.githubusercontent.com/30258590/31157875-9bfd91f2-a8f0-11e7-8d27-58bc7264c808.jpg)

The customer hasn't paid yet, but later he pays it, how do I manage the invoice to make it paid off ?

**Comment by odiea** [comment]
The intent of this update was just to be able to change the payment type. It is not a full bookkeeping system.

**Comment by sanubari97** [comment]
Ok, maybe next update ?

**Comment by daN4cat** [comment]
Authoring an invoice after you issued it can be considered a crime in certain countries. If you are unsure about the end invoice issue a pro-forma using Orders or what @SteveIreland implemented. Once it's finalised you issue the final invoice.

Therefore there will be no change outside the payment mode as it is at the moment.
