### ISSUE TITLE
Fails to add new customer or new supplier

### ISSUE THREAD

**Issue by rjobeirne** [opensourcepos/opensourcepos#1673]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is:    7.0
- MySQL or MariaDB version is:    MySQL 5.7
- OS and version is:    Ubuntu 16.4 Mate & Mint 18.2
- WebServer is:    Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP) N/A

### Expected behaviour
Adding New Customers, New Items and New Suppliers

### Actual behaviour
Adding New Items works fine.
When adding New Customers or New Suppliers the input form opens but the Submit button does nothing. A customer list can be imported from a csv file.
It fails to add New Employees as well.

Nothing reported in /var/log/apache2/error.log, /var/log/dmesg.
/var/log/apache2/access.log reports
`127.0.0.1 - - [11/Oct/2017:13:16:03 +1100] "POST /customers/save/ HTTP/1.1" 500 554 "http://localhost/customers" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0`

### Steps to reproduce the issue
I checked that php-gd, php-bcmath, php-intl, php-sockets, php-mcrypt and php-curl are all installed and enabled.

**Comment by SteveIreland** [comment]
Since we've had so many language issues may I ask what language is involved?

Have you tried setting your index.php file to development mode to see if it is suppressing a PHP error?

**Comment by rjobeirne** [comment]
It is set up for english with localisation code set to en-AU (Australian). I tried US as well with no change.

I switched the /var/www/html/public/index.php from production to development mode but am not seeing any errors. Where should they appear?

**Comment by SteveIreland** [comment]
The PHP errors usually appear on the page in areas related to areas in the code where the PHP error is triggered.  Since you're not seeing anything then I the problem is not likely a PHP errror.

**Comment by SteveIreland** [comment]
I downloaded the version you are reporting an issue with and ran a test with the same PHP version and MySQL version but could not replicate the issue.

You might want to try to re-install if you haven't already done so.

Also, if you made some configuration changes before testing, try to add a customer before making any configuration changes to see if the problem exists prior to the changes.

Steve

**Comment by jekkos** [comment]
Set the environment to 'development' in index.php so you'll see the actual error

**Comment by rjobeirne** [comment]
@SteveIreland - I have just completed a reinstall on a different system with a fresh OSPOS download. I tried adding a new customer before configuring the store - same result. The New Customer form comes up but absolutely no effect from the Submit button.

@jekkos - I am already using development mode (see posting above) but not getting any php errors.

**Comment by rjobeirne** [comment]
I tried again with a totally new operating system install (Ubuntu 16.04) and a fresh OSPOS install. The first thing I did on logging into OSPOS was try to add a new customer but had the same result, ie. no action from the Submit button. 
Maybe it's in my installation technique. Since the installation instructions given on the OSPOS site are geared toward a DigitalOcean server rather than a local one, I have documented my installation process to assist in my many tries. I attach a copy. Am I doing something wrong?
[Ospos_inst.pdf](https://github.com/opensourcepos/opensourcepos/files/1386271/Ospos_inst.pdf)

**Comment by rjobeirne** [comment]
I solved with the help of others. My problem was due to a missing dependency for php-mbstring. I suggest the installation instructions be updated to include 'php-mbstring' in the Server Requirements.

**Comment by daN4cat** [comment]
Very good @rjobeirne and thanks for the issue report. I'm adding that point in the notes.

**Comment by alarez** [comment]
Can I suggest you include this information in the installation instruction page.?http://www.opensourceposguide.com/guide/gettingstarted/installation

**Comment by shyamsunderindia** [comment]
Hi All, My name is Shyam, I am also having same problem. When I am adding New Customer there dialog box is opening but that is blank only submit button appear and nothing field to enter detail. Rest adding Item, whole seller etc . is working fine. Only facing problem in adding New Customer.

I tried this application in my local server using xamp there everything working fine there is no issue and I can add New Customer, But in shared hosting server I cannot add New customer.
I also check Mbstring in my hosting server that is enabled and set Auto by default.

Please anyone help me as soon as possible. I am using latest version of ospos opensourcepos.20190704173621.master.7da7c0

Here I am sharing screenshot of problem in Adding New Customer.
https://drive.google.com/open?id=1Uwbe1GrqFBhTq4_-qoeNR1y9KA84nUt5

Waiting eagerly for some working solutions.
Thanks ,
SHYAM SUNDER
Email: shyamsunder.india@gmail.com

**Comment by rovanxl** [comment]
> Hi All, My name is Shyam, I am also having same problem. When I am adding New Customer there dialog box is opening but that is blank only submit button appear and nothing field to enter detail. Rest adding Item, whole seller etc . is working fine. Only facing problem in adding New Customer.
> 
> I tried this application in my local server using xamp there everything working fine there is no issue and I can add New Customer, But in shared hosting server I cannot add New customer.
> I also check Mbstring in my hosting server that is enabled and set Auto by default.
> 
> Please anyone help me as soon as possible. I am using latest version of ospos opensourcepos.20190704173621.master.7da7c0
> 
> Here I am sharing screenshot of problem in Adding New Customer.
> https://drive.google.com/open?id=1Uwbe1GrqFBhTq4_-qoeNR1y9KA84nUt5
> 
> Waiting eagerly for some working solutions.
> Thanks ,
> SHYAM SUNDER
> Email: [shyamsunder.india@gmail.com](mailto:shyamsunder.india@gmail.com)

Did you ever get this resolved? I am having the same issue on a new install.

**Comment by daN4cat** [comment]
If you check config and system  status do you get some warning?

**Comment by rovanxl** [comment]
I'm running OSPOS Installation Info: 3.3.2 - bb309c / Language Code: en-US. There are no warnings. Everything is green.

I am able to import customers thru csv but they do not show up under the customers list. I am also unable to select a customer in sales. I get a 500 error
