### ISSUE TITLE
Question Docker installation

### ISSUE THREAD

**Issue by arnoldtkl** [opensourcepos/opensourcepos#1679]
Hello, I done the docker-compose build and docker-compose up.
But, when I enter http://localhost
It show "Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php" 

Anyone can help me this?

**Comment by daN4cat** [comment]
what about checking old issues as this was already discussed several times?

**Comment by mufasilfaizal** [comment]
Did you find the solution? I'm facing the same with Docker installation in Mac. I can't find the solution. Every solutions are for running using XAMP,WAMP/MAMP.

**Comment by daN4cat** [comment]
@mufasilfaizal you need to find the answer to your problem, nobody tested Docker installation on Mac I'm afraid. Keep us posted if you find a solution. Thanks
