### ISSUE TITLE
how to export report as PDF ?

### ISSUE THREAD

**Issue by arrazka** [opensourcepos/opensourcepos#1681]
How To export Report as PDF ? 

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

**Comment by jekkos** [comment]
Use bstables export functionality. I think PDF export is one option there

**Comment by odiea** [comment]
Unfortunately it does not appear in the export list.
![2017-10-23 05_08_44-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/31886181-847c5c1a-b7b0-11e7-8080-de885b3d5d8b.png)

**Comment by daN4cat** [comment]
That plug in needs to be enabled or similar....

**Comment by jekkos** [comment]
Ok I thought we had it enabled? I remember  having a dependency on PDF javascript thingy for enabling this. However I was looking into enabling it to export all but think that the dataExportType: All only applies if you're not using server side pagination. We should call some kind of hook to load all data, then disable pagination, export, and re-enable. Might want to dig into this code to get this fixed once and for all

**Comment by daN4cat** [comment]
Yes it sounds the issue reported in bstable git repo.

**Comment by daN4cat** [comment]
Added pdf and change is in master, part of 3.2.0

**Comment by daN4cat** [comment]
Has anyone counter tested this? @arrazka can you please check? Thanks

**Comment by arrazka** [comment]
Big Thanks to @jekkos  @odiea  @daN4cat PDF is working. but if we install fresh OSPOS from master we still have trouble " Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php "

**Comment by odiea** [comment]
https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files are the latest unstable versions. Do not use the github master.
