### ISSUE TITLE
App's View is Larger

### ISSUE THREAD

**Issue by sanubari97** [opensourcepos/opensourcepos#1683]
![untitled](https://user-images.githubusercontent.com/30258590/31652945-7329353e-b353-11e7-972f-abb2fd2f2a30.jpg)

Why is it changed like this, after I make changes to the "Export all reports records (#868)" files related ?

and what is this line for `<link rel="stylesheet" type="text/css" href="dist/opensourcepos.min.css?rel=9202eddfb2"/>` ? I try to change that yesterday and the view back to normal, and today in the morning it look good but then I refresh the in the noon, it turn out this big again ...

**Comment by daN4cat** [comment]
have you downloaded everything from bintray?

**Comment by sanubari97** [comment]
no. what is that ?

**Comment by odiea** [comment]
Local install

Dowload the latest stable release from github or unstable build from bintray
Create/locate a new mysql database to install open source point of sale into
Execute the file database/database.sql to create the tables needed
unzip and upload Open Source Point of Sale files to web server
Modify application/config/database.php and modify credentials if needed to connect to your database
Modify application/config/config.php encryption key with your own
Go to your point of sale install public dir via the browser
LOGIN using
username: admin
password: pointofsale
Enjoy

**Comment by sanubari97** [comment]
I try to install the new 3.1.1 and the I copy the "header.php" and "manage tables.js" from the master  and it look like this 

![untitled](https://user-images.githubusercontent.com/30258590/31698555-aee5f222-b3f0-11e7-9a86-89f5883217e1.jpg)

and the export all reports not working which was working before. I'm confused.

**Comment by daN4cat** [comment]
Take the bintray files in full, don't nit pick.

**Comment by sanubari97** [comment]
downloaded the master and copy everything,
everything looks normal again but the report still not  exported all

**Comment by daN4cat** [comment]
I've enabled the option to export all in bootstrap-table, however it doesn't look to be right indeed.
I have even updated bootstrap-table code to the latest in my test environment but it doesn't seem right.
However I can read that other people face the same issue: https://github.com/wenzhixin/bootstrap-table/issues/2508
Not sure what else can be done.

**Comment by daN4cat** [comment]
Reopened #868

**Comment by jekkos** [comment]
Probably debug the javascript to see what it's doing. If I'm not mistaken it should just call the server endpoint without any query string parameters... should dig into the bstables code and check then I guess
