### ISSUE TITLE
Taxes missing from reports

### ISSUE THREAD

**Issue by esbyrt** [opensourcepos/opensourcepos#1685]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 7.0.24
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 10.0.32-MariaDB
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Windows 8 and 10
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4.27
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Run a report on sales and see the tax amounts on it

### Actual behaviour
Taxes are missing from most sales details but the Amount Tendered shows the full amount. I have noticed that since the update two tax items may show on the sales register. What was Tax 1 at 5% is now GST at 5%. Even though they are both tax 1 on checkout they show as two different taxes. See picture below. 
![two tax rates](https://user-images.githubusercontent.com/28318020/31751475-b96f23ce-b442-11e7-8514-c444437c5b89.JPG)

### Steps to reproduce the issue
![missing taxes](https://user-images.githubusercontent.com/28318020/31751097-f21d48e2-b440-11e7-9a86-8e9ed4cc1e8b.JPG)
The detailed report is missing all tax amounts. A summary report shows some but

**Comment by odiea** [comment]
Could this possibly be related to your previous issue?

**Comment by esbyrt** [comment]
Possibly. The store users haven't kept me up to date very often. I believe all the day to day sales are going through ok. The one long sale that simply wouldn't complete  - I asked her to enter just five items at a time and she hadn't done it yet. Still waiting to hear how that goes.

Hm. Looking at the reports again today August showed no taxes on the detail sales report, September showed no taxes through the first week then the taxes show up again. It would be great to find the problem has resolved but it is a big concern on why it happened in the first place. Of the recent ones that calculated correctly both tax descriptions (tax 1 and gst) are included in the total tax.

I will keep exploring to see if I can find something that can be duplicated.

**Comment by daN4cat** [comment]
@SteveIreland have you noticed anything like that with your installations?

**Comment by daN4cat** [comment]
BTW, have you upgraded from an older version to a more recent one in the past months?

**Comment by esbyrt** [comment]
Yes this issue and #1635 with sales not completing and disappearing from the system both started after upgrading to 3.1.1.  The users report they are still having issues and I am going on site to check it out on Tuesday. I will report back with what's going on.

**Comment by daN4cat** [comment]
Have you upgraded the database running all the scripts and migration function properly?

**Comment by esbyrt** [comment]
I followed the update instructions and ran the 3.0.2 to 3.1.1 script. I hope that was all I needed to do. Is there a way to check that all the migrations are applied properly?

**Comment by odiea** [comment]
1. Check to make sure your Customers are set as taxable.
2. Check to see if your Items have the taxes included with them.
3. Place the proper taxes into the Tax amount.
4. Uncheck Use Customer tax support in Store Config.
![2017-10-23 11_43_52-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/31904254-f609d114-b7e7-11e7-945e-a03a7184a9a1.png)

**Comment by esbyrt** [comment]
All those settings were already set properly.

**Comment by odiea** [comment]
The only other thing I would check is pull up a receipt from The report that is not showing taxes and see if the receipt shows taxes. This is as much as I can help you out.

**Comment by daN4cat** [comment]
Also have you run the migration from OSPOS? There should be an icon in admin to support that. If you don't see check admin permissions to make sure it's enabled and visible to you.
Once it's visible run the script from that view. You only need to do it once.

**Comment by esbyrt** [comment]
Thanks odiea, yes the receipt shows the taxes properly.

**Comment by esbyrt** [comment]
daN4cat I honestly don't remember for sure if I ran the migration when I did the upgrade. I remember seeing that the migrate button would show up if it was needed so wouldn't have been too worried if it didn't. Anyway, I just backed up the database and ran migrate. Went to do an invoice with 7 random items and applied payment but clicking complete brings me to a blank screen instead of the invoice and the sale fails to enter into the system. I will update this over on my other issue as well. #1635

**Comment by esbyrt** [comment]
Solved!! When I went looking for Migrate I realized there was also a new Tax tab that I didn't have permissions for. Added that in and created a tax item under that tab. Taxes show up properly on all the reports now. I totally missed that one with taxes still configured under Store Config as well.  Now if I could find an answer for why my sales won't complete over on #1635 I'd be happy!

**Comment by daN4cat** [comment]
Ok, can closed.
