### ISSUE TITLE
User profiles logging other profiles 

### ISSUE THREAD

**Issue by alvintaffy** [opensourcepos/opensourcepos#1687]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections "New Feature / Enhancement" and "Issue / Question / Bug".
2. Remove just the one of the two sections you don't need 
3. Remove this section as it's just a guideline
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhancement

*For New Features or Enhancements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.*

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] I'm reporting an issue of an unmodified OSPOS installation

I have installed OSPOS from cpanel. I have created employees with different permissions but when user1 tries log in  using his credentials but logs into user2's profile. Sometimes it even logs into system administrator profile.

How do i fix this? your assistance will be greatly appreciated

**Comment by odiea** [comment]
Do the users have unique names and passwords? And what version?

**Comment by alvintaffy** [comment]
Hi 

Thanks for the quick response they do have unique names and passwords. Like shown below

Username: Thulak 
Password:Password@2017 (she still has to change it)

User 2

Username: Lebom


I am using version 3.1.1


⁣Regards
Alvin T Matewa
Chief Marketing Technologist
SIMBOTI TECH
44 Harry Galuan Street Midrand 1658 Johannesburg
(Office: +27 (0) 73 191 1813 |Mobile: +27 (0) 73 191 1813 | *  e-mail: alvin@simboti.co.za
Website: www.simboti.co.za

**Comment by odiea** [comment]
Are you using Firefox. If you do then you need to put it in a private window. I know fire fox will save the user names and passwords in a drop down list for a user to select their name from..

**Comment by daN4cat** [comment]
I bet it's what @odiea said... login credentials automatically stored in Web browsers and prompted everytime you access the Web page.

**Comment by alvintaffy** [comment]
Hi Guys 

I have tested with different browsers and I am still experiencing the same problem. One thing that I have noticed is that when using the same network I have this challenge. Right now the employees are at remote site and only person can login if the second person tries to login then user1 profile shows up instead user2. When I was onsite with them if I try log into user1 then my admin profile pops up.

**Comment by daN4cat** [comment]
Must be Halloween coming soon that is throwing some sorcery in it :-)

You haven't provided that much information about your setup, so how can somebody help you? We don't have any crystal ball to guess I'm afraid. Considered that?

**Comment by alvintaffy** [comment]
Hi @daN4cat I am not sure what more information you require. If possible send me your email address i will email the link and loging credentials. You can test from your side. I have installed the software from cpanel, do i need to do anything else ? maybe i missing something.

**Comment by SteveIreland** [comment]
If the issue isn't the more likely one suggested by @odiea then what you're describing can only be explained if your people and employee tables are corrupt.  Is this the first time you've tried to install the software?  Are you loading the database from scratch?  What database are you using and what version?  Is it compatible?

After confirming everything is supported then I'd try clearing the database and reloading the tables using the database.sql script and trying it again.

When you said you installed it from CPanel are you referring to an installation script someone created?  Or did you mean you installed it USING CPanel (which is what I do).   I don't think anyone here has experienced the issue you're reporting - so we're grasping at scarecrow straws here.

**Comment by daN4cat** [comment]
@alvintaffy when you created the issue there was a template, which you chose not to fill in in full. That's the information we are after.

**Comment by alvintaffy** [comment]
Hi guys

Below are the details from my hosting service provider. I am using ospos on windows

PHP 5.6.30
Distrib 5.6.33
Apache/2.4.23 (Unix)
nginx/1.13.3
===

**Comment by daN4cat** [comment]
And database version?
Also which one is: Apache web server or Nginx one?

**Comment by alvintaffy** [comment]
Hi guys Below is the respond from my service provider

>>And what is the database version?
As I mentioned in the previous update, MySQL version is Distrib 5.6.33.

>>Also which one is: Apache web server or Nginx one?
In our server we are having both Apache and Nginx web service. Nginx acts as reverse proxy, used to manage dynamic files and Apache is used to manage static files.

**Comment by daN4cat** [comment]
It's getting complicated I'm afraid.
If you cannot clearly understand yourself what the installation is, I suggest to seek professional support. I cannot help you and our time is limited, and when we have some we use it to develop OSPOS.

**Comment by alvintaffy** [comment]
Hi Francesco

 

I am not sure what is getting complicated, if possible can I Skype you ? I really need to your help, I am not that technical but I have provided with all the information.
