### ISSUE TITLE
Search and view invoice/receipts

### ISSUE THREAD

**Issue by livewirerules** [opensourcepos/opensourcepos#1690]
### New Feature / Enhancement

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes: 

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is:  4f5ad57
- PHP version is:   5.6
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
An option to view order invoices/receipts under the reports section and an option to search through orders. 
Currently through the reports i can see a summery list... But if i need to print an invoice or receipt again  or search orders there is no option

**Comment by odiea** [comment]
Apparently you have not noticed the update button on the right side of the row. The blue sale number will show the receipt.
![2017-10-26 06_28_11-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/32052974-05122e78-ba17-11e7-8dec-3996e70312c5.png)

**Comment by livewirerules** [comment]
Thanks.. I noticed now that the sales # is linked...

By the way, is it possible to change the Sales # format? something like 00001 or current year-00001 or something similar to that?

Currently is says POS 1, POS 1.... etc...

**Comment by daN4cat** [comment]
No
