### ISSUE TITLE
How to add and display the item/unit cost in the reports

### ISSUE THREAD

**Issue by pards124** [opensourcepos/opensourcepos#1692]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections "New Feature / Enhancement" and "Issue / Question / Bug".
2. Remove just the one of the two sections you don't need 
3. Remove this section as it's just a guideline
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhancement

**It would be better if we add the item/unit cost on all of the reports.
Let me know how to add and display the item/unit cost of all reports.**

**Comment by odiea** [comment]
More explanation needed. Which Reports?

**Comment by pards124** [comment]
Let say on the **Detailed Sales Report** just like in the photo below.
![capture](https://user-images.githubusercontent.com/33042543/31919664-a4f11b20-b896-11e7-8e8c-8571d7d1ed35.PNG)

**Comment by daN4cat** [comment]
Wholesale is unit cost price. That's for the American English. If you switch to British English you get the unit cost price.

**Comment by pards124** [comment]
Apologee for the confusion my term is incorrect.
I should say the **item price** w/c was log in the sales. it needs to display in the detailed sale report. 
Please suggest  what value do i need to put in the highlight to display the item price in the detailed sale report. 
I really appreciate your suggestion and recommendation

![image](https://user-images.githubusercontent.com/33042543/31928787-050abb3a-b8cc-11e7-8654-ecaf77968a5a.png)

**Comment by pards124** [comment]
Also related to case #738, but not yet solved
