### ISSUE TITLE
Incorrect Tax calculation

### ISSUE THREAD

**Issue by livewirerules** [opensourcepos/opensourcepos#1693]
### Issue / Question / Bug

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is:  4f5ad57
- PHP version is:   5.6
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
If i have a product for $10 and i charge 10% as tax, then the total should be $10 +  10%

### Actual behaviour
On my order the tax percentage is calculated inside the product. The tax is calculated on a way always it equals to to the product value

![Image](https://content.screencast.com/users/livewirerules/folders/Jing/media/e7b3c801-a871-4d6a-aa08-6921396b2e8f/2017-10-24_1234.png)

**Comment by marcellusmontilla** [comment]
Some users actually expect this behavior (matter of preference and/or convenience). Having the price tax-inclusive, makes the final price "rounded". This is usually more convenient for other stores.

**Comment by SteveIreland** [comment]
So this is not actually about an incorrect tax but more about how prices are to be entered in a VAT tax environment?  I didn’t know VAT taxers had a choice.

**Comment by marcellusmontilla** [comment]
The choice is not with taxing itself but with the pricing configuration, either tax-exclusive or tax-inclusive.

**Comment by daN4cat** [comment]
This sounds a special case, what do you expect us to do?
We spent already a lot of time fixing the taxation and I'm not willing to spend any more time for corner cases I'm afraid.

**Comment by SteveIreland** [comment]
@marcellusmontilla hopefully the relatively new Cash Rounding feature still works.  Of course, we won't know until someone uses it and reports back.

@daN4cat maybe @livewirerules will follow up and provide further details regarding the issue but unless I am missing something I don't see a problem here that needs correction,

**Comment by livewirerules** [comment]
Actually i was playing around with the functions and noted that its not a problem... 

On the configuration, i thought Include tax was meant to enable/ disable the tax. But actually it means to enable tax inclusive or exclusive for products

Thank guys... :)

**Comment by daN4cat** [comment]
Maybe the translation needs fixing? I'll check again the English one to make it's tax inclusive....
