### ISSUE TITLE
Not deleting sales_taxes records when deleting sales

### ISSUE THREAD

**Issue by marcellusmontilla** [opensourcepos/opensourcepos#1695]
### Issue / Question / Bug
- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information
- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 5.6
- MySQL or MariaDB version is:  MySQL 5.6
- OS and version is:  linux
- WebServer is:   Apache
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Deleting sale in "Daily Sales" tab under Sales Module should also delete corresponding rows in ospos_sales_taxes table.

### Actual behaviour
Deleting sale in "Daily Sales" tab under Sales Module DOES NOT delete corresponding rows in ospos_sales_taxes table.

### Steps to reproduce the issue
Delete a sale in "Daily Sales" tab under Sales Module

**Comment by daN4cat** [comment]
It should not be a physical hard delete but a soft one.
We changed that recently and therefore taxes stay in the table. The primary table of sales drives the visibility.

Therefore not an issue.

**Comment by marcellusmontilla** [comment]
Deleting sales (hard) deletes the records in the following tables:
- sales
- sales_items
- sales_items_taxes
- sales_payments
but not in:
- sales_taxes

I was assuming the action would be consistent in all sales_ tables. I was concerned it might affect the consistency of the reports (tax-wise).
