### ISSUE TITLE
Successful login takes me back to the login screen, no message or error

### ISSUE THREAD

**Issue by HeinB** [opensourcepos/opensourcepos#1697]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] I'm reporting an issue of an unmodified OSPOS installation
- [X] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [X] I read the README, WHATS_NEW and UPGRADE
- [X] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [X] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [X] I'm aware the latest master could be a development version and therefore not stable
- [X] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 2b2396521ca49d5f950977235b402fb9b3fd902a
- PHP version is:    7.7.10
- MySQL or MariaDB version is:  MariaDB 10.1.28 
- OS and version is:   Windows Server 2012
- WebServer is:   Apache 2.4.28
- (If applicable) Installation package for the LAMP/LEMP stack is:   XAMPP 7.1.10

### Expected behaviour
When I click on "Go" after supplying the correct username and password, it should log into the application.

### Actual behaviour
When I click on "Go" after typing in the correct username and password, the screen refreshes back to the login page with no errors or other messages.

### Steps to reproduce the issue
Type in admin as username
type in pointofsale as password
click on Go button

There are no errors in the Apache logs.

**Comment by daN4cat** [comment]
Php version 7.7 ? Is that correct?

**Comment by odiea** [comment]
No. This is the current version of Xampp.
Includes: Apache 2.4.28, MariaDB 10.1.28, PHP 7.1.10, phpMyAdmin 4.7.4, OpenSSL 1.0.2, XAMPP Control Panel 3.2.2, Webalizer 2.23-04, Mercury Mail Transport System 4.63, FileZilla FTP Server 0.9.41, Tomcat 7.0.56 (with mod_proxy_ajp as connector), Strawberry Perl 7.0.56 Portable

**Comment by HeinB** [comment]
Yes, sorry about the mistype.  PHP 7.1.10

**Comment by daN4cat** [comment]
Have you followed wiki page instructions?

**Comment by HeinB** [comment]
I believe I did.  I have a successful install on Raspberry Pi before, but need to move it to Windows.  I followed the installation instructions on windows and do not see any error in any of the log files. Any pointers to debug would be appreciated.

**Comment by daN4cat** [comment]
Check in public dir for any error_log file.
Also make sure you have the php extensions in place and database is fine.

**Comment by HeinB** [comment]
There is no error_log.  The DB is fine, if I log in with the incorrect credentials, it gives me an "Invalid username or password" error. I had issues before with extensions but enabled the missing ones and there are no errors now in the apache error log file.

**Comment by daN4cat** [comment]
Have you copied all the files, even application/migrations ones?
I want to make sure it's not related to that feature somehow.

**Comment by HeinB** [comment]
I downloaded and extracted the full github code.  I have an application/migration folder with a subfolder sqlscripts and 3 php files.

**Comment by HeinB** [comment]
I can give you remote access if you would like to see? (obviously privately...)

**Comment by daN4cat** [comment]
I'm afraid I don't have the time to debug for you. I'm giving you some hints but you need to find the way out by yourself. If it works on Raspberry PI there is no reason why it shouldn't on Windows too.

**Comment by HeinB** [comment]
I understand, thanks.  At this stage I am out of ideas, tried everything I can.

**Comment by daN4cat** [comment]
Which directory are you pointing with your web server? Is it public or else?

**Comment by HeinB** [comment]
XAMPP is installed, inside it is an htdocs folder. In htdocs I have a working phpmyadmin and extracted the github files into opensourcepos.  I access it through port 85 on the localhost using http://localhost:85/opensourcepos/public.  This brings up the longin page and gives correct response if I use an invalid username or password.

**Comment by daN4cat** [comment]
Right, and have you changed the .htaccess to:

> # if in web root
> # RewriteRule ^(.*)$ index.php?/$1 [L]
> 
> # if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
> RewriteRule ^(.*)$ /opensourcepos/public/index.php?/$1 [L]

**Comment by daN4cat** [comment]
The other thing you need to make sure is that your folders have the right access right to apache user and r & w.

**Comment by HeinB** [comment]
I tried the rewrite rule. but still get the same result.  I even changed my document root directory to the location and still get the same result.  Thank you for trying to help!

**Comment by daN4cat** [comment]
I assume you checked that the login credentials you use have the permission to access OSPOS, just to exclude that. Not sure you started completely from scratch or you used an old database.

**Comment by daN4cat** [comment]
Also please search old issues and see if something pops up somewhere.

**Comment by odiea** [comment]
I downloaded and extracted the full github code. I have an application/migration folder with a subfolder sqlscripts and 3 php files. You need to download the bintray files not the github download or clone.
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20171029075934.master.8b92d1.zip

**Comment by HeinB** [comment]
That's it!  Thank you, it is working as expected on XAMPP.  An update to the instructions would save so much time.
