### ISSUE TITLE
OSPOS client disconnection / delay in response

### ISSUE THREAD

**Issue by dvashisht** [opensourcepos/opensourcepos#1702]
### Issue

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) : 5.6.25
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) : MySQL 5.7.14
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) : Windows 10 Professional
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) : Apache 2.4.23
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP) : WAMP 3.0.6

### Expected behaviour

OSPOS client should not disconnect/delay the response from server (when server is on the same LAN) in case Internet is disconnected.
And client should work normally e.g. Sales -> 'Find/Scan Item OR Receipt' 

### Actual behaviour

In present production setup at store, POS workstations are on the same LAN as OSPOS server. But if Internet disconnects (due to any reason) then client also stops responding in 'Find/Scan Item OR Receipt' or there is a delay in response, until the DNS cache is cleared using command 'ipconfig /flushdns'. After clearing the DNS cache the client starts working normally after a few seconds.

**Comment by SteveIreland** [comment]
Do you have that flag for sending activity to Google turned on or off?  It might help with this issue if you turn it off

**Comment by odiea** [comment]
Store config-general-Send Statistics. Remove check mark if it is there.

**Comment by SteveIreland** [comment]
Yea ... what he said.

**Comment by dvashisht** [comment]
Stevelreland & Odiea,

After removing check mark from store config-general-send statistics, OSPOS client does not disconnect now, and there is no delay response when Internet disconnects.

The application performance is normal as expected. The issue stands resolved.

Thank you,
Dinesh

**Comment by odiea** [comment]
Thanks for the feedback.
