### ISSUE TITLE
Cannot log in when using Cloudflare

### ISSUE THREAD

**Issue by marcellusmontilla** [opensourcepos/opensourcepos#1704]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report
- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.6
- OS and version is: linux
- WebServer is: Apache
- (If applicable) Installation package for the LAMP/LEMP stack is: (e.g. WAMP, XAMPP)

### Question

I'm trying to use Cloudflare for this.

Problem:
Log-in page will load but when I log in it says:
"An Error Was Encountered" - "The action you have requested is not allowed."
When I'm already logged in when I activate Cloudflare, I can't log out (but other features are working).
![Error message](https://user-images.githubusercontent.com/25737631/32362012-bea3530a-c0a0-11e7-831a-45837ad2f712.jpg)

I've set up other sites in the same server without this problem. I've explored all options in Cloudflare and I'm kind of stumped. Is there anything in Secure_Controller.php that may have caused this?

**Comment by jekkos** [comment]
That's csrf kicking in.
Does cloudflare do any cookie filterign?

**Comment by marcellusmontilla** [comment]
I turned off SSL, and still can't log in. Will csrf work without SSL? Also, cloudflare works only up to the login page of ospos.<domain>.com but fully works in <domain>.com.

I don't know if cloudflare does any cookie filtering, can you suggest a way how to know this?

**Comment by marcellusmontilla** [comment]
I'm searching their wiki and found [this](https://support.cloudflare.com/hc/en-us/articles/200171806-Error-1010-The-owner-of-this-website-has-banned-your-access-based-on-your-browser-s-signature). From this, I could surmise they have their own "block pages". The error I've been getting though looks like it's generated from within OSPOS.

**Comment by daN4cat** [comment]
Csrf has nothing to do with SSL. The issue is related to cookies.

In the configuration file you can disable csrf and see if that's the issue. However changing configuration is not the correct solution because you compromise on security.

**Comment by marcellusmontilla** [comment]
Cloudflare has a feature called "[Web Application Firewall](https://www.cloudflare.com/waf/)" which is the only setting I know related to CSRF. I have not enabled it here.

**Comment by daN4cat** [comment]
I meant disable in OSPOS configuration file.

**Comment by marcellusmontilla** [comment]
According to Cloudflare support personnel, they are not doing any cookie filtering.

**Comment by daN4cat** [comment]
Is this solved? Have you found the reason why Cloudflare is causing problems?

**Comment by marcellusmontilla** [comment]
It's not yet resolved. I also have an unresolved ticket with Cloudflare. They have tested it (gave them  my web address with a test login credential) and encountered a 403 during one of their tests, hence mod_security was mentioned. Still, my ticket is not yet closed.

**Comment by daN4cat** [comment]
Let us know the solution when you get to an end.

**Comment by marcellusmontilla** [comment]
Ok. I got it to work. The problem was in my Cloudflare page rules, although I don't quite understand why. If anyone else is using Cloudflare and stumbles here, OSPOS 3.1.1 is compatible with Cloudflare. Try to remove/add page rules (in Cloudflare) one by one just so you know which ones work and which ones do not.

**Comment by daN4cat** [comment]
I'll add this to the FAQ
