### ISSUE TITLE
PHP Fatal error: session_start():

### ISSUE THREAD

**Issue by knichel** [opensourcepos/opensourcepos#1705]
I downloaded and did a fresh install of ospos.  When I use a browser to navigate to my install, I get a 500 error "This page isn't working" in google chrome.
I have tested the mysql credentials I entered in the database connector and they work.  I ran the databse sql setup and verified the tables exist.
When I check the apache2 error log, I see "**PHP Fatal error: session_start(): Failed to initialize storage module: user (path: sessions) in /var/www/html/opensourcepos/vendor/codeigniter/framework/system/libraries/Session/Session.php on line 143**"

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: Downloaded yesterday so current.
- OSPOS git commit hash is:  cannot get to load, so no info available as of yet.
- PHP version is:  PHP Version 7.0.22-0ubuntu0.16.04.1
- MySQL or MariaDB version is:   5.7.20-0ubuntu0.16.04.1
- OS and version is:   Ubuntu 16.04
- WebServer is:   Apache/2.4.18 (Ubuntu)
- (If applicable) Installation package for the LAMP/LEMP stack is:   LAMP

### Expected behaviour
I expect the index.php page to load, but it does not.

### Actual behaviour
I am getting an apache error : "PHP Fatal error: session_start(): Failed to initialize storage module: user (path: sessions) in /var/www/html/opensourcepos/vendor/codeigniter/framework/system/libraries/Session/Session.php on line 143"

### Steps to reproduce the issue
I installed this software using the same install method on a different Ubuntu box and same behavior

**Comment by daN4cat** [comment]
You most likely downloaded Github code, which is for developers.

**Comment by daN4cat** [comment]
Check the readme and download from bintray

**Comment by knichel** [comment]
The statement "Dowload the latest stable release from github or unstable build from bintray" suggests the opposite.  Bintray is unstable and would likely be for developers.

**Comment by odiea** [comment]
If you want a working version you will need to follow his advise.

**Comment by knichel** [comment]
I downloaded the unstable version and can get to the login page, but now after I enter the admin/pointofsale credentials, I get an error "The requested URL /ospos/public/login was not found on this server."  
I have changed the .htaccess file in /ospos/public to read 
"RewriteRule ^(.*)$ /ospos/public/index.php?/$1 [L]"
and commented out the other.  I have mod_rewrite enables, I checked.
