### ISSUE TITLE
Import Items Excel Template needs update

### ISSUE THREAD

**Issue by marcellusmontilla** [opensourcepos/opensourcepos#1709]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.6
- OS and version is: linux
- WebServer is: Apache

### Issue

Import Items Excel Template needs to be updated. Remove "Quantity" and "Location" columns.

**Comment by daN4cat** [comment]
I'm not sure I can follow, why are you saying that Quantity and Location need to be dropped?
If you do items are not allocated to the right stock location and you even don't know the quantity.

**Comment by marcellusmontilla** [comment]
There's a downloadable excel template (actually csv) when importing items. The template was in the previous format where there was only one stock location allowed. Location and quantity columns were placed somewhere in the middle of the table. Now that multiple stock locations are allowed, locations and corresponding quantities should be appended in the right-most columns.

**Comment by daN4cat** [comment]
And it looks like that with the file in master: https://github.com/opensourcepos/opensourcepos/blob/master/import_items.csv

or am I missing something?

**Comment by marcellusmontilla** [comment]
Oh. My bad. I was using an old import_items template in my downloads folder.
