### ISSUE TITLE
Import items by csv is_serialized column not read correctly

### ISSUE THREAD

**Issue by marcellusmontilla** [opensourcepos/opensourcepos#1711]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.6
- OS and version is: linux
- WebServer is: Apache
- (If applicable) Installation package for the LAMP/LEMP stack is: (e.g. WAMP, XAMPP)

### Expected behaviour
Items table is_serialized value is 0, when importing by csv with a column is_serialized = 0

### Actual behaviour
Items table is_serialized value is 1, when importing by csv with a column is_serialized = 0

### Steps to reproduce the issue
Import items by csv with is_serialized = 0

**Comment by marcellusmontilla** [comment]
I suspect that the ospos_items table is taking the is_serialized values from the "wrong" column in the CSV import template.

**Comment by SteveIreland** [comment]
What makes you suspect that?

The index / field mapping should be as follows
```
0 - barcode
1 - item name
2 - category
3 - supplier id
4 - cost
5 - price
6 - tax 1 name
7 - tax 1 rate
8 - tax 2 name
9 - tax 2 rate
10 - reorder level
11 - item description
12 - allow alt description flag
13 - is serialized flag
14 - custom 1
15 - custom 2
16 - custom 3
17 - custom 4
18 - custom 5
19 - custom 6
20 - custom 7
21 - custom 8
22 - custom 9
23 - custom 10
24 - item image
25 - location 1
25 - quantity 1
```

**Comment by marcellusmontilla** [comment]
Yes, that is the order of values that I used. I also tried importing with is_serialized = 1, hoping that the reverse happens with records getting is_serialized = 0, but still is_serialized = 1. So, any value I put: is_serialized = 0 or 1, records is_serialized = 1 in ospos_items.

There are only two columns in my csv with value = 1, Col10 (reorder level) and Col12 (alt desc flag). The import function could be getting the is_serialized value from either.

**Comment by SteveIreland** [comment]
I looked at the code here is the trick.  For those two flag fields if you put anything in it other than leaving it blank then the flag will be set to '1'.  Even if you put a '0' in it the flag field will be set to '1'.

**Comment by marcellusmontilla** [comment]
I will improve the wiki. :)

**Comment by daN4cat** [comment]
Ok, maybe set to 0 should be false anyway...
