### ISSUE TITLE
Error al cargar recibido de Ventas Precio Total y algunas adiciones que suenan geniales

### ISSUE THREAD

**Issue by cristhianlamy** [opensourcepos/opensourcepos#1714]
Hola a todos primero que todo esta genial la herramienta 

1. al instalarla en un cpanel en la ultima verion encontre que no se actualiza el precio total de ventas recibidas por lo cual no totaliza el recibo.
2. seria genial que el software adicionalmente manejara un estado de factura para recibido donde confirma el valor que pago el tipo de pago que realiza para manejar cuentas por pagar.
3. asi como deberia realizar cuentas por pagar para un pos normal debe tener cuentas por cobrar es decir podrías informar cuando "FIAS" asi es en mi pais jeje y cuando el cliente te debe y cuanto y ir haciendo adelantos al tema.
4. y finalizando todo negocio peque;o requiere de un modulo de gastos simple donde diga tipo de gasto valor y comentarios si es el caso agregar una foto para registrar los gastos que tuvo para tener una ganacia mas exacta.

quedo al tanto para saber porque tengo ese error y en que puedo ayudar

**Comment by cristhianlamy** [comment]
![image](https://user-images.githubusercontent.com/3495105/32689865-1753c72c-c6ba-11e7-8f02-2e509f3506c2.png)

mira aqui en la imagen se ve que no esta sumando la totalidad que puede ser mi version de php es 5.6 apache 2.2 estoy con la ultima version

**Comment by odiea** [comment]
English please. Google Translation.

Hello everyone, first of all, this tool is great

when installing it in a cpanel in the last verion I found that the total price of sales received is not updated, so it does not totalize the receipt.
It would be great if the software additionally handled an invoice status for receipt where it confirms the value I pay for the type of payment that is made to manage accounts payable.
as well as should perform accounts payable for a normal post must have accounts receivable that is, you could inform when "FIAS" so it is in my country hehe and when the client owes you and how much and go making progress on the subject.
and ending all small business, or requires a simple spending module where you say type of expense value and comments if it is the case add a photo to record the expenses you had to have a more accurate income.
I am aware to know why I have this error and how I can help

**Comment by cristhianlamy** [comment]
Hello
currently install the latest version of the software and works great except for the reception module that is not calculated the whole when loading the items as seen in the image that previously loaded what generates not cost correctly and does not report the total value of the loaded merchandise

**Comment by odiea** [comment]
Make sure receiving quantity at least has a 1 in it.
![2017-11-11 07_17_22-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/32690224-89707f44-c6b0-11e7-94c4-71989cd95c69.png)

**Comment by cristhianlamy** [comment]
perfect indeed eo thousand grace
Regarding the fact that I can help with the project they require in addition to financial support I know something about the framework and working on it I can be of help

**Comment by odiea** [comment]
Was this a new install or an upgrade from a previous version? That should have been placed automatically.

**Comment by cristhianlamy** [comment]
It was a new installation but it works for me changing what they mentioned to me but I want to support the project in that I can help them

**Comment by odiea** [comment]
Thanks for the help offer. Let us know what you can do for the project.

**Comment by mckaygerhard** [comment]
@odiea this means that ospos does not permit negative amount in the inventory?

i dont understant so much but if there is the case, how can permit negative amounts in inventory?

ospos still use webservice to update the inventory?

esto significa que ospos no permite ventas negativa o inventario negativo?
y si lo entendi bien, coo podria yo permitir ventas negativas?

@cristhianlamy es code realize adaptacion file de la novela de paly2 o es algo nuevo? (esta en la esquina de tu foto)

**Comment by daN4cat** [comment]
Inventory can go negative at sale time, you get a warning though.

**Comment by mckaygerhard** [comment]
oh then thanks @daN4cat so its like the phppos, i a phppos user and i just see today that ospos its the continuation of..

**Comment by daN4cat** [comment]
yes, it's the newer version of phppos. We took it and improved it changing all the look'n'feel, newer version of CodeIgniter, more security, more functionality and etc.
