### ISSUE TITLE
Adding Bulgarian language

### ISSUE THREAD

**Issue by wanewi** [opensourcepos/opensourcepos#1718]
Question 

Hello I just want to know how I can help to add Bulgarian language to my installation . I just want to try if the language gonna work and after that its gonna be awesome if we can add that to installation for everybody who want to use it . thank you .

**Comment by jekkos** [comment]
Hi, can you try to sign up on weblate? Check wiki for further instructions.

**Comment by jekkos** [comment]
I just need to find a way to import that patched translate toolkit dependency using pip an django.. so that the php strings conversoin hopefully works as it should

**Comment by daN4cat** [comment]
Anyway to at least force a manual push? We are stuck at the moment....

**Comment by wanewi** [comment]
I cant register at the translation platform.

**Comment by jekkos** [comment]
Ok emails arent working either, guess we'll have to stick to manual translation then for now

**Comment by daN4cat** [comment]
@jekkos so we are stuck with all the translations made that are in Weblate.... is there really no solution to this issue?

**Comment by jekkos** [comment]
I have just installed the patched translate toolkit, seems that changes can be committed to the repo now (see latest two commits in master).
Will check for those other translations whether I can recover them now

**Comment by daN4cat** [comment]
Oh good, so we can add these to 3.2.0 then.

**Comment by jekkos** [comment]
Hm it appears that new changes are now properly staged in the repo, however, still seeing this problem with the swedish translation some time ago, it's in the history but does not propagate to the repo

**Comment by odiea** [comment]
@jekkos while you are here can you also see why no new bintray files are showing?

**Comment by daN4cat** [comment]
Travis is somehow broken. There are errors not due to OSPOS per se if I see it right.

**Comment by jekkos** [comment]
I have been skimming through the logfile but can't see where it goes wrong. The build seems to exit with code 1 so one step has failed. @daN4cat did you spot the culprit ? Might be the upload itself I'll check further in a minute

**Comment by daN4cat** [comment]
I see failures at the beginning of the log with downloading of packages and similar. Check the initials steps.

**Comment by jekkos** [comment]
@wanewi I added bulgarian language now, it should be ready for translation. Did you manage to get a login on the server?

**Comment by jekkos** [comment]
Registration should work again, some issues with email configuration prevented the mails from being sent to Gmail. Tested and verified that it works now.

**Comment by jekkos** [comment]
@wanewi did you have time to look into these translations? Otherwise I postpone the milestone here.

**Comment by wanewi** [comment]
I will , later today.

**Comment by wanewi** [comment]
I translate something but i still need time for the rest . Can you tell me how you export this stuff so i can try translate to my own bild and see how is going . Thank you .

**Comment by daN4cat** [comment]
This should be done in the sense of support is available and just translations need to be synced when available.

@jekkos shall we close this one as many of the others?

**Comment by daN4cat** [comment]
@wanewi, please complete the translations so we can have everything in 3.2.0.
I close this issue as it's now an ongoing job to keep up with the translations.
