### ISSUE TITLE
sales mode ARE very hardcoded, ospos are not deployed in seveeral countries

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1721]
### New Feature / Enhancement

implement the opensourcepos are unuseless for countries where the fiscal rules are related to specific modes of sales... in ospos only are "sale", "sale with credit card", "quote" and "return"

some countries have "government sale" where the setings are not edited by the employee, like the tax.. and others like the taax may vary depending of the method that pay..

due in Sales.php model and Sales lib all de modes are very hardcodes this are impossible to implement without break original code..

Please this behaviour must be changed!

### Issue / Question / Bug

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [ ] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 8b92d1973255922738b1e282d2f5d681d81b1e1c 
- PHP version is:  5.5,
- MySQL or MariaDB version is:   MariaDB 10.1
- OS and version is:  Linux not winbuntu ok
- WebServer is:   Apache 2.4

### Expected behaviour

made a special payment ajust to the law's country

### Actual behaviour

sales modes are very hardcoded

### Steps to reproduce the issue

make a sale

**Comment by SteveIreland** [comment]
Sales modes are by necessity "hard coded" because there is code behind them to support the mode.  So to add a new sales mode you would need to add all of the code required to support the mode.  It makes no sense at all to have a user defined sales mode which would at best do nothing and at worst break everything else.

It sounds more like you have a unique taxing requirement and maybe some set of rules that need to be enforced based on a "sub-type of sale".  If you can specify in more detail what country(s) you are referring to and point us to where we can get more information on the local laws then we can start an informed discussion.

**Comment by daN4cat** [comment]
@mckaygerhard happy for you to change the code and contribute a more generic support for non "hard coded" sales mode.

**Comment by mckaygerhard** [comment]
now i try to understand how the ospos work with the modes, very complicated and too much js call , i'm not expert but all the parameters can be stored in the database and including the defines.. 

umm i living in a very law-less country u know? i'll implement the coe with a different license.. a more piracy license..

**Comment by odiea** [comment]
Good luck with that.
