### ISSUE TITLE
Excel Import in Customers Module NOT adding customers to the database

### ISSUE THREAD

**Issue by marcellusmontilla** [opensourcepos/opensourcepos#1722]
### Issue / Question / Bug
- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information
- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.6
- OS and version is: linux
- WebServer is: Apache

### Expected behaviour
Excel Import in Customers Module will add customers to the database

### Actual behaviour
Excel Import in Customers Module NOT adding customers to the database. Notification "Customer Import Successful" did show up but customers were not added.

### Steps to reproduce the issue
Use Excel Import button in Customers Module

**Comment by daN4cat** [comment]
@odiea do you have to verify this and confirm it's an issue?

**Comment by odiea** [comment]
I tried this in 3.2.0 and initially the new customers did not show . They did show after a table refresh.

**Comment by daN4cat** [comment]
Ok, thanks. So it's a refresh story issue.

**Comment by daN4cat** [comment]
@marcellusmontilla how can you claim customers are not added to the database when it's not the case?

**Comment by odiea** [comment]
I will down load the 3.1.1 and give it a try and let you know.

**Comment by daN4cat** [comment]
Right, it's an older version.

**Comment by odiea** [comment]
I get the same with ospos3.1.1
Import worked but names did not show until the tables were refreshed.
![2017-11-21 14_42_36-open source point of sale _ powered by ospos 3 1 1](https://user-images.githubusercontent.com/10962177/33098386-7aec92f6-ceca-11e7-964a-469afa7c5ca9.png)

**Comment by odiea** [comment]
This was with a newly created db, earlier test was with my current test db.

**Comment by odiea** [comment]
To confirm it still works I used the csv from 3.1.1 and all went well.

**Comment by odiea** [comment]
The only issue I did notice was the following.
OSPOS Import csv.
![2017-11-21 15_03_53-microsoft excel non-commercial use - import_customers csv](https://user-images.githubusercontent.com/10962177/33099270-8bd1a856-cecd-11e7-9ba7-88c9b7da71df.png)
And the following is the export from customers.
![2017-11-21 15_05_14-microsoft excel non-commercial use - customers csv read-only](https://user-images.githubusercontent.com/10962177/33099280-9e2c957e-cecd-11e7-9d2c-73b91b4b5614.png)

**Comment by marcellusmontilla** [comment]
Good to know that it's working from your end. I will have to check why it's not working on my install.

**Comment by daN4cat** [comment]
What happened in the recent past is that people uses old csv files and import them with recent versions of OSPOS.

**Comment by marcellusmontilla** [comment]
I suspect it's in the specific encoding of my csv file because when I upload using the untouched template file (previously downloaded from pos), it adds "Bob Smith". I'm still investigating.

**Comment by marcellusmontilla** [comment]
Here's what I tried but still did not work.
1. Opened the default import_customers.csv using Excel
2. Opened my not_importing_customers.csv also using Excel
3. Copy-pasted rows from not_importing_customers.csv to import_customers.csv (in Excel)
4. Save import_customers.csv as import_customers_2.csv
5. Use that import_customers_2.csv as import file
6. Notification "Customer Import Successful"
7. Refresh page
8. No customers added

**Comment by marcellusmontilla** [comment]
Here's another method which imported only 1 row out of thousands.
1. Opened the default import_customers.csv using TextEdit
2. Opened my not_importing_customers.csv also using TextEdit
3. Copy-pasted rows from not_importing_customers.csv to import_customers.csv (in TextEdit)
4. Save as is. No rename.
5. Used import_customers.csv as import file
6. Notification "Customer Import Successful"
7. Refreshed page
8. Only 1 customer added (more than 2k records in csv)

**Comment by marcellusmontilla** [comment]
Extended test using TextEdit.
9. Opened new import_customers.csv using TextEdit
10. Delete-then-Enter between succeeding records to "ensure row is separated"
11. Did it for 3 lines.
12. Save as is. No rename.
13. Used import_customers.csv as import file
14. Notification "Customer Import Successful"
15. Refreshed page
16. Only the <b>three</b> customer records added (more than 2k records in csv)

**Comment by marcellusmontilla** [comment]
I don't know why the csv parser is not recognizing the row records where an explicit "new line" was not added (Delete-then-Enter). My csv looks like this:

![screen shot 2017-11-23 at 1 09 12 pm](https://user-images.githubusercontent.com/25737631/33159690-88b71992-d050-11e7-9945-6a1f23c7013d.jpg)

Each new record is already a new line but csv parser only added records where I <b>re-inserted</b> a new line (Delete-then-Enter).

**Comment by daN4cat** [comment]
Thank you for testing, I will look into this over the weekend.

**Comment by daN4cat** [comment]
The import function uses this PHP function: http://php.net/manual/en/function.fgetcsv.php

Please note that there might be issues with end of lines added from Mac, read the note. Is that your case?
If yes you should try to add:

`ini_set('auto_detect_line_endings',TRUE);`

`ini_set('auto_detect_line_endings',FALSE);`

at the beginning and at the end of the `do_excel_import()` in `controllers/Customers.php`.

**Comment by daN4cat** [comment]
Give a try anyway even if not a Mac story and see what happens.

**Comment by marcellusmontilla** [comment]
I'm sorry I'm kind of confused because you mentioned true and false together, should I add both?

**Comment by marcellusmontilla** [comment]
Adding
```
ini_set('auto_detect_line_endings',TRUE);
```
worked. Maybe it should be made default. Thank you.

**Comment by daN4cat** [comment]
It was supposed to be TRUE at the beginning of that function and FALSE at the end.
Anyway, glad it solved the issue.
I'm not sure it's safe to add by default as it could have side effects to others. But I'll read more about it and see if it's better to add it.
