### ISSUE TITLE
Overlay after login

### ISSUE THREAD

**Issue by vimkaf** [opensourcepos/opensourcepos#1725]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is: 5.6.12
- MySQL or MariaDB version is:  MySQL 5.6.26
- OS and version is:  Windows 7 
- WebServer is:   Apache 2.4
- XAMPP 

### Expected behaviour
i am expecting to see the pages without the overlay

### Actual behaviour
all pages have the overlay 
### Steps to reproduce the issue
![issue](https://user-images.githubusercontent.com/2923113/33173048-e26a7cfc-d052-11e7-80e7-be1200f38dfd.png)
please @awriel and @daN4cat 
I am using a fresh installion of OSPOS i have not edited anything except config/database.php

**Comment by odiea** [comment]
Try installing the unstable version and see if when the login screen appears it states you have php issues.

**Comment by vimkaf** [comment]
it doesnt show me any issues, i have all the required extensions installed

**Comment by odiea** [comment]
Another screen image of the current version please

**Comment by vimkaf** [comment]
it is not more showing the overlay, i fixed it by removing the database and installing a new one, why is that? and what can i do to prevent any issues like this from recoccuring

**Comment by odiea** [comment]
which version is working now 3.1.1 or 3.2.0. Different versions have different databases. If you do not change any of the programs wording it may never be an issue for you again.

**Comment by vimkaf** [comment]
VERSION 3.11

**Comment by mckaygerhard** [comment]
@vimkaf try to hit F12 and see the console errors, maybe old data between cache browser and server, i can see you are using guindows so tht problem of overlay happened always .. 

the other its the DB layer, try to see in /var/lib/<server>/error.log if there any error when load the page, again seems realted to gu9ndows behavior..

**Comment by vimkaf** [comment]
@mckaygerhard I checked mozilla firefox console no errors, i think the question here  is how to modify without breaking the web application?

**Comment by odiea** [comment]
Read the licenses and the front page about modifying OSPOS.

**Comment by mckaygerhard** [comment]
@vimkaf as @odiea saids, you must read! i noted that in your case some extra steps must be made.. in fact wiki page and README are little outdated but its a common problem of windoze users only just "click click click"

modify the database are not enought on your case, you must revise the php settings and get sure all the required are loaded/filled.. also revise the htaccess.. pleas do that windoze users dont do, READ like linux users..
