### ISSUE TITLE
error Class 'Racecore\\GATracking\\GATracking' not found in Tracking_lib.php on line 43

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1726]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] **I read the wiki VERY OUTDATED!!!!!!!!!!**
- [ ] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: lasted from git
- OSPOS git commit hash is: fcab8e1fc98ead656275ceede47de913f8598d02
- PHP version is:  5.6
- MySQL or MariaDB version is:  10.1
- OS and version is:   Debian linux
- WebServer is:   Apache 2.2

### Expected behaviour

see the ospos store after login

### Actual behaviour

i got that error:
```
PHP Fatal error:  Class 'Racecore\\GATracking\\GATracking' not found 
in /home/remoto/Devel/opensourcepos/application/libraries/Tracking_lib.php 
on line 43
```

### Steps to reproduce the issue

i install fresh, from git clone
run the db script
set htaccess files as proper
login and got that error

**Comment by odiea** [comment]
You have just become a devbeloper. Now you are on your own.

**Comment by mckaygerhard** [comment]
developers need info for help or code! where its the need info, i search some around that problem, why the "bintray" version does not have this error?

i sustituye the complete vendor directory and runs, but i try to understant why i cannot use a non-minified versions of my js files etc etc

**Comment by odiea** [comment]
In the States we call this the school of hard knocks. Read Read Read.

**Comment by mckaygerhard** [comment]
jajaj ok read, but reading all info are outdated!

**Comment by mckaygerhard** [comment]
aloso the info that i find must have some level of relationship.. i try to take shor ways.. but no problem.. the firt crack i made ith the layer when @vimkaf try to alter, so ui help to other in shor way right?

**Comment by vimkaf** [comment]
@mckaygerhard i dont get you

**Comment by mckaygerhard** [comment]
@vimkaf do you modify something or change some db values? i now reproduce your problem..

**Comment by vimkaf** [comment]
@mckaygerhard i did not change any db values

**Comment by mckaygerhard** [comment]
jajaj well there's a implicit change in that shadow.. i change the footer, happened, i change the "vendor" directory, happened, any changes that not follow the wiki page for modify the ospos, happened your problem..

**Comment by vimkaf** [comment]
then it is not fully truly open source

**Comment by odiea** [comment]
Barriers have been added to protect this resource from dishonest people who want to re brand it as their own.  So I will close this issue as it has no real useful Information.

**Comment by daN4cat** [comment]
Read the license file

**Comment by daN4cat** [comment]
Open Source does not mean: I rebrand it as mine (other people's work) and sell it as mine so I make money (out of other people's work).

The License file is there to tell you that you can use it for free, but you respect the people that build it. And we don't want a penny but don't mind a beer....

**Comment by mckaygerhard** [comment]
ah ok, well i need them info, i try to read and understand the code but its very frustrating to a novice understand something that READING are outdated, maybe if there more help can we made something..

**Comment by mckaygerhard** [comment]
due i not have fully 24/7 network connection i want to use directly to test directly.. i cannot waith until the build happened.. due i'm offline do you understsand!?

**Comment by daN4cat** [comment]
Well, don't complain when I started there was 0 documentation and just code. I bang my head few times on the wall and two years later you have what you see thank with @jekkos if course. He is the custodian that made it possible to get here.

So the code is your documentation and the wiki gives you hints.

Also learn Codeigniter first because that's the boiler plate here.

**Comment by mckaygerhard** [comment]
i have this problem of Racecore, why by example? i not found good hints in google search only few non close related problems

**Comment by daN4cat** [comment]
composer install

**Comment by vimkaf** [comment]
forget the rebranding part, the software has no documentation 👎 ,the wiki is not much 👎 .OK you said do not edit the footer and licences 👍  and you would be alright i dont mind but what of creating new modules or editing existing modules ? I think you have made it pretty difficult to do so. Which shouldnt be so, if it is opens source.

**Comment by SteveIreland** [comment]
This is silly.  Having made some significant changes to existing modules and having added one and started working on another I can personally attest to the fact that it is simple to add additional modules ... if you are at least competent with the tools and the languages involved and are willing to do the work. 

If not, then there is a bit of self-education that first needs to be done.  But whining about it doesn't get the job done.  This project is not sponsored by a corporation so it will grow only by the contribution and/or encouragement of the community of users and volunteers. 

The hard part is meeting the  high bar set by the project owners for coding standards.  :wink:

**Comment by mckaygerhard** [comment]
incredible, i'm going to my home and by phne i see that! i answered until go "off line"

umm i noted that there's too complicated things for many task, by example generating the api doc in docs directory by a external system , why not so simple like markdown sintasx and then github rendering directly ! pufff

another, too many complicated things to running in developer mode, and only works with ngingx or apache2 .. apart of the thing that hijacked the complete root of the htdocs site.. puff

**Comment by daN4cat** [comment]
As said again and again, please take and write your own one.
