### ISSUE TITLE
JS Print Setup Not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1728]
Hi friends 
again me,
I work with the OSPOS 3.1.1 version on Windows with fiscal printer through the JS Print Setup addon and it's a surprise today that my firefox was updated to the QUANTUM version and when I go to print it does not find the printer, they disappeared and in the adddon it is off and says JS Print Setup Not compatible with Firefox Quantum ??

![image](https://user-images.githubusercontent.com/12921805/33215040-3fd049d6-d0fc-11e7-9ab8-509e49433c24.png)

How can we solve this problem??

Thank you

**Comment by odiea** [comment]
All we can do is hope that the author updates this fine extension.

**Comment by guillermohaad** [comment]
Hi friend @odiea , 
any solution to re-activate and print on the ticket printers?

**Comment by odiea** [comment]
You can wait and see what happens or download an earlier version of Firefox and then change the update settings

**Comment by guillermohaad** [comment]
thnak @odiea 

Friends, I share with you the author's response in case one of them happens the same:

For successful porting of jsPrintSetup as Web Extension there is a need to extend FF API.
We have made proposal for New API features with version of jsPrintSetup WE and we are waiting for mentor to continue with implementation.
https://github.com/edabg/jsprintsetup/issues/39

We will be happy when our implementation is landed in FF and launch new version of jsPrintSetup WE.

Temporary solution is to use Firefox ESR.


Regards,

Dimitar Angelov

EDA Ltd.
mailto: mitko@edabg.com
http://www.edabg.com

**Comment by odiea** [comment]
If you are a windows user you can use Pale Moon and add the jsprint addon to it.

**Comment by guillermohaad** [comment]
thank you @odiea I'm going to try and tell you my experience

**Comment by guillermohaad** [comment]
thanks to @odiea for this great contribution. Add-On JS Print Setup It was tested with Firefox ESR and Pale Moon and in both of them it worked successfully.

**Comment by Extremal1981** [comment]
Hello friends, I also use this most useful extension, now I switched from Firefox to Waterfox where everything works fine, the author will soon release a release on the quantum engine, with the support of xpcom. so there is an alternative! At least two distinct forks Waterfox and Pale Moon.

**Comment by SteveIreland** [comment]
And I had never heard of either before.  I'm going to need to come out of my fox hole more often.

**Comment by daN4cat** [comment]
Thanks for the input about this  topic, it sounds useful indeed.

With regards to the long printing, I had a similar issue when I set up the printer. It was due to the paper size and bottom margin. Play with those and see if something changes. I cannot remember from the top of my head what that was as it's a long time ago.

**Comment by guillermohaad** [comment]
thank you friend @daN4cat , I will follow your recommendations and comment,
happy weekend to all

**Comment by vimkaf** [comment]
@guillermohaad Did installing Firefox ESR solve the problem of re-activate and print on the ticket printers?

**Comment by guillermohaad** [comment]
friend @vimkaf, yes sr.

**Comment by guillermohaad** [comment]
ok @vimkaf , with previous versions not problem, this problem is with version Firefox Quamtun.

**Comment by mckaygerhard** [comment]
i write ho to workaround this in the wiki, see #1845 but my problem its different, sometimes work and sometimes does not!

**Comment by jekkos** [comment]
Chrome still works fine with Auto print. Check wiki on how to configure it

**Comment by mckaygerhard** [comment]
@jekkos seems do you not noted that the old original wiki are very VAGE in information.. i must improved in the weekend, he old wiki are only links and citations...

still are very vage due the instruction i provide are basic, but well much very much better rather original

**Comment by daN4cat** [comment]
Again, go back 5 years and tell me what / how was....

**Comment by jekkos** [comment]
I agree we need better install instructions (eg mini website) for non technical users.. main issue is currently lack of time so if @mckaygerhard you feel up to improving this, go ahead.

**Comment by mckaygerhard** [comment]
i'm working on! and the dependency on apache can be away if the hardoced rules about rewwriting can be optional, then the index file must return back.. this make user-friendly the complete ospos and webserver agnostic!

**Comment by daN4cat** [comment]
If you find a way to install OSPOS selecting the environment and place the correct files / config, go ahead.
But you have not to force regressions on others because of a point in making generic to everything. Read the index.php, not sure what the big deal is to touch one line of a .htaccess. Also people coming to GitHub should be prepared to config something manually and not expect commercial support.

**Comment by ravindug** [comment]
You can use latest browser then you have to configure printer properly in Printer configuration ,
Go to print preview and remove all margins and headers and footers
then go to device and printers and
change length of paper and edge after print then all will work,
use silent print of firefox in about.config to not to show print dialog afterwards

**Comment by mckaygerhard** [comment]
@ravindug lasted browser need lasted hardware, and i not will put my i7 8G ram laptop in the store due the employee can take away some day, ok? so i put a pemtiun4 with 512 RAM and firefox 38 where OSPOS works well..

about your printing setup, works in some cases, only with some devices but i using Linux and some printers dont wotk with your setup! thanks i use a Epson 220 that seems works but some other parners reported me that your setings not work always.. in conclusion dont assume all people can use "fashion lasted" in bussines always be used "the more cheap and available to situation"

**Comment by mckaygerhard** [comment]
hi @ravindug i also already added your suggestions to the wiki printing setup some time agos thanks, please see it here: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Printing#preparation-printing-for-firefoxpalemoon

**Comment by ravindug** [comment]
thank you for your recommendation, and I didn't suggest for high end device and I implemented for very bare minimum PC and cheap 58mm ĉhineese printer.

**Comment by yeffer2** [comment]
It works with: https://www.palemoon.org
all addons from firefox suport

**Comment by odiea** [comment]
It now appears that Pale Moon no longer supports JSPRINT.
