### ISSUE TITLE
Creating a new module

### ISSUE THREAD

**Issue by vimkaf** [opensourcepos/opensourcepos#1729]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:   5.6
- MySQL or MariaDB version is:   MySQL 5.6
- OS and version is:   Windows 7 
- WebServer is:  Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Steps to reproduce the issue

I tried creating a new module called accounting I succeded but in the homepage instead of getting Account as the module name I am getting module_accounts(TBD), how can this be solved

**Comment by odiea** [comment]
In your language. go to module language and add it there. Once you open it up you will see how it is done.

**Comment by vimkaf** [comment]
I did that already,but no change

**Comment by odiea** [comment]
$lang["module_accounts"] = "Accounts"; it should look similar to this.
then use this to call it if necessary
<?php echo $this->lang->line('module_accounts') ?> Then save it.

**Comment by odiea** [comment]
In your database it should look something like the following.
![2017-11-24 12_23_08-localhost _ 127 0 0 1 _ ospos1 _ ospos_modules _ phpmyadmin 4 5 1 - opera](https://user-images.githubusercontent.com/10962177/33222171-6c4482e6-d112-11e7-97ea-def7a83c742d.png)

**Comment by vimkaf** [comment]
i have done the database part and edited the module lang file but how do i call it?

**Comment by odiea** [comment]
$lang["module_config"] = "Store Config";
$lang["module_config_desc"] = "Change the store's configuration";
Do you have lang for both of them in the module lang?

**Comment by odiea** [comment]
In configs did you add the module to autoload .

**Comment by vimkaf** [comment]
![issue](https://user-images.githubusercontent.com/2923113/33222467-dbcd31a4-d157-11e7-8b9c-f5e66d296fb2.png)
also note i added a new permission in the database

**Comment by vimkaf** [comment]
The steps i took was 
1. Edit the module lang file added the module name and desc
2. Insert it in the ospos_modules table
3. Add a new permission in ospos_permissions table
4. Update the Admin user Permissions

**Comment by odiea** [comment]
This is not necessary. It will get the info from the autoload.
then use this to call it if necessary
lang->line('module_accounts') ?>

**Comment by vimkaf** [comment]
What is not necessary?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: odieaSent: Friday, 24 November 2017 9:04 PMTo: opensourcepos/opensourceposReply To: opensourcepos/opensourceposCc: Kay Adamolekun; AuthorSubject: Re: [opensourcepos/opensourcepos] Creating a new module (#1729)This is not necessary. It will get the info from the autoload.
then use this to call it if necessary
lang->line('module_accounts') ?>

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opensourcepos/opensourcepos","title":"opensourcepos/opensourcepos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opensourcepos/opensourcepos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@odiea in #1729: This is not necessary. It will get the info from the autoload.\r\nthen use this to call it if necessary\r\nlang-\u003eline('module_accounts') ?\u003e"}],"action":{"name":"View Issue","url":"https://github.com/opensourcepos/opensourcepos/issues/1729#issuecomment-346890230"}}}

**Comment by odiea** [comment]
then use this to call it if necessary
lang->line('module_accounts') ?>

**Comment by vimkaf** [comment]
How do I autoload the module                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: odieaSent: Friday, 24 November 2017 9:21 PMTo: opensourcepos/opensourceposReply To: opensourcepos/opensourceposCc: Kay Adamolekun; AuthorSubject: Re: [opensourcepos/opensourcepos] Creating a new module (#1729)then use this to call it if necessary
lang->line('module_accounts') ?>

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opensourcepos/opensourcepos","title":"opensourcepos/opensourcepos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opensourcepos/opensourcepos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@odiea in #1729: then use this to call it if necessary\r\nlang-\u003eline('module_accounts') ?\u003e"}],"action":{"name":"View Issue","url":"https://github.com/opensourcepos/opensourcepos/issues/1729#issuecomment-346891898"}}}

**Comment by odiea** [comment]
In config did you add the module to autoload . Bottom of the autoload.php file.

**Comment by vimkaf** [comment]
No I did not                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: odieaSent: Friday, 24 November 2017 9:36 PMTo: opensourcepos/opensourceposReply To: opensourcepos/opensourceposCc: Kay Adamolekun; AuthorSubject: Re: [opensourcepos/opensourcepos] Creating a new module (#1729)In config did you add the module to autoload . Bottom of the autoload.php file.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opensourcepos/opensourcepos","title":"opensourcepos/opensourcepos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opensourcepos/opensourcepos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@odiea in #1729: In config did you add the module to autoload . Bottom of the autoload.php file."}],"action":{"name":"View Issue","url":"https://github.com/opensourcepos/opensourcepos/issues/1729#issuecomment-346893311"}}}

**Comment by SteveIreland** [comment]
The bottom of the autoload is actually for the model, not the module.

**Comment by odiea** [comment]
Yes it loads the module from the model.

**Comment by vimkaf** [comment]
@odiea I have fixed the issue of the module name not displaying correctly, the mistake was from my part i was editing the wrong file instead of editing en-US i was editing en-GB. <I know silly me>

**Comment by odiea** [comment]
Glad you figured it out.

**Comment by daN4cat** [comment]
@vimkaf it happens
