### ISSUE TITLE
Trying to add expiry dates to items and reports on expiry items

### ISSUE THREAD

**Issue by tenkodoy** [opensourcepos/opensourcepos#1732]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections Enhancement

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhancement
I use the software at the pharmacy shop and periodically we have to flush out drugs that are expiring. if we could add expiry to items that are created and also find reports on items that are about to be expired or give warning just like how the low order mark does. 

### Installation information

- OSPOS version is: 3.0.1
- OSPOS git commit hash is: 
- PHP version is:  5.6
- MySQL or MariaDB version is:   MySQL 5.7
- OS and version is:  Windows 10
- WebServer is:   Apache 2.2
- (If applicable) Installation package for the LAMP/LEMP stack is:   XAMPP

**Comment by odiea** [comment]
adding custom field to sales register table #1137
