### ISSUE TITLE
CLARIFICATIONS ON SOME ISSUES

### ISSUE THREAD

**Issue by vimkaf** [opensourcepos/opensourcepos#1733]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:   7.1
- MySQL or MariaDB version is:   5.7
- OS and version is:  Windows 10
- WebServer is:   Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   XAMPP

### Steps to reproduce the issue
I need somethings clarified
1. I want to understand the difference between the register mode : sale and sale by invoice, for example if a customers buys an item on credit an invoice is generated so if the customers nows pays for the item bought a receipt should be printed. How can i acheive this using OSPOS?
2. How can i append to the receipt or invoice . like a gate pass
3. Has OSPOS been tested with a POS receipt printer ? If yes does it require any extra config or it just prints directly.
4. If OSPOS is deployed on a LAN, can it be configured?

**Comment by mckaygerhard** [comment]
the most important its the 3: for that u must implement the vendor printer program, in countries where a fiscal kit its used, you must made and proxy or man-in.the-middle program that receive the php commands and send to the kit-printer... for the rest just send to the printera text-based traductionof the sale.. i currently implemented in two cases but some issues may happened if the os its something stupid like win32 some implementatios are very unstable like happened in RD...

**Comment by vimkaf** [comment]
I have solved question 3 and kudos to the author and contributors they did a nice job. now i only have 1 question, consider the scenario i stated in question 1 if a customer buys an item on credit(he or she has not paid) an invoice is generated and the customer later pays for the items bought how do i update OSPOS to show that the customer has fully paid in OSPOS.

**Comment by daN4cat** [comment]
Add due payment to the transaction.
Later you can edit the transaction and change the payment to be what you want (cash, card, cheque).
From Sale view and transactions log you can select from the filter drop down box due payment, so you know what's pending.

**Comment by daN4cat** [comment]
To edit the transaction select the icon on the right of the row. It will pop up a form where you can edit the payment form.
No partial payments can be managed though.

**Comment by daN4cat** [comment]
Bear in mind that sale with invoices life cycle can be managed like pro-forma and then full invoice. So consider that option too.

**Comment by vimkaf** [comment]
@daN4cat the due payment feature is it available or i have to do it myself

**Comment by daN4cat** [comment]
Available, just select "due" in sale register as payment. Job done.

**Comment by odiea** [comment]
Is this available in 3.1.1?

**Comment by odiea** [comment]
Answered my own question. Yes it is.

**Comment by vimkaf** [comment]
@daN4cat the feature is available in 3.1.1 , i figured it out
