### ISSUE TITLE
Backup to FTP Server Feature Request

### ISSUE THREAD

**Issue by vimkaf** [opensourcepos/opensourcepos#1734]
### New Feature / Enhancement

*For New Features or Enhancements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.* 
It would be nice to backup to an FTP Server rather than downloading to local computer someone should implement it

**Comment by daN4cat** [comment]
Happy to merge it in, if you could contribute the feature.

**Comment by jekkos** [comment]
Think it's a bit out of scope as a a backup is probably just a database dump.
Things like that should be automated using cronjobs or other server infrastructure..

**Comment by daN4cat** [comment]
that's what I do.
