### ISSUE TITLE
RETURN feature for SALE BY INVOICE (without payment)

### ISSUE THREAD

**Issue by marcellusmontilla** [opensourcepos/opensourcepos#1735]
### Issue / Question / Bug
- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information
- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.6
- OS and version is: Linux
- WebServer is: Apache

### Expected behaviour
Reverse a SALE or SALE BY INVOICE (unpaid) transaction.

### Actual behaviour
Only SALE can be reversed correctly. Reversing a SALE BY INVOICE will require to add a "negative payment" for the "COMPLETE" button to show.

### Steps to reproduce the issue
1. Submit a SALE BY INVOICE (without payment), get the sale id "POS #";
2. Go back to sales register and select RETURN;
3. Input POS #;
4. COMPLETE button will never show unless you put a "negative payment"

This is incorrect since there was no payment made in the first place.

**Comment by marcellusmontilla** [comment]
Maybe I just don't understand how, but is the "DUE" payment method designed for this? :)

**Comment by daN4cat** [comment]
You use a negative due payment right?

There will be no enforcement for that. It is designed for people to use a bit their brains and not expect their own specific processes to be implemented in OSPOS. So it stays loose.
