### ISSUE TITLE
Adding Item Category to Sales Receipt

### ISSUE THREAD

**Issue by AhsenKh** [opensourcepos/opensourcepos#1740]
### Issue / Question / Bug

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

**- I have used Docker installation**
- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is: 7.1
- MySQL or MariaDB version is:   (MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is: Windows 10
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   XAMPP 7.1.11

** ************************************************** **

I want to display items' **category** along with other information, on sales receipt. For this, I tried to modify *receipt_default.php*. However, *$item* object received does not have category field attached to it.

I found that inside *Sales.php* controller, the following line is responsible for printing the receipt.

```
// Reload (sorted) and filter the cart line items for printing purposes
$data['cart'] = $this->get_filtered($this->sale_lib->get_cart_reordered($data['sale_id_num']));
```

Here, the method `get_cart_reordered` is available inside *Sale_lib.php* that further calls `get_sale_items_ordered` of *Sale.php* model.

Here, DB query does get category of the item. However, it is not passed to `add_item` method, available in *Sale_lib.php*. Now, I can add an extra argument for `add_item` method, but the problem is that it is being called at many other places. I don't want to make room for any glitch.

Is anyone up for discussing the issue?

**Comment by odiea** [comment]
In sale_lib around line 798 I added the following below description.
					'category' => $item_info->category,

**Comment by AhsenKh** [comment]
Works like a charm.

One more thing, I need my items to first be ordered by category, and then by name. Currently, I have added code for sorting, inside `receipt_default.php`. But then I saw this option being available inside `models/Sale.php` in following form.

```
// Group by Item Category
elseif($this->config->item('line_sequence') == '2')
{
	$this->db->order_by('category', 'asc');
	$this->db->order_by('sales_items.description', 'asc');
	$this->db->order_by('items.name', 'asc');
}
```

Do you have any idea, how do I set the value of `line_sequence` to 2?

**Comment by odiea** [comment]
This is as far as I can go with the receipt. This is based on 3.2.0. If your db is current then you should be able to extract the application folder and Rename your current application folder then paste this into the program
.https://github.com/odiea/opensourcepos
