### ISSUE TITLE
Allow sales by weight / New Feature - Enhancement

### ISSUE THREAD

**Issue by Saiuke** [opensourcepos/opensourcepos#1741]
I work with products that are sold by weight. So it would be great if the products could be fractionated in this way. I believe that simply allowing the quantity to be specified with decimal numbers would already help. I imagine that people who sell liquids also have this kind of problem. I sell thinner sometimes, to facilitate it, I have to divide my merchandise into bottles, but sometimes a customer wants only half a bottle. That complicates matters.

**Comment by daN4cat** [comment]
It's already implemented and you can even scan barcodes generated by scales containing the weight.

Search past issues and study the configuration of OSPOS.
