### ISSUE TITLE
add address

### ISSUE THREAD

**Issue by infomail** [opensourcepos/opensourcepos#1743]
Please, I need when the sale is made, print the customer's address on the tickets? How could I add it?

**Comment by odiea** [comment]
if you are using the current 3.2.0 you can download this version. Extract the application folder and replace the old one  with this one. https://github.com/odiea/opensourcepos. This is currently a test version.

**Comment by odiea** [comment]
Currently this is just using the en-Us language.

**Comment by infomail** [comment]
@odiea Thanks for the prompt response, in this new version how can I make the client's address on the ballot?

**Comment by odiea** [comment]
If you are referring to on the receipt then that is already built into it.

**Comment by infomail** [comment]
@odiea I am running version 3.1.1, the purchase address shows the address of the business, what I need is the customer's address

![image](https://user-images.githubusercontent.com/31284618/33641932-727ebbf6-da16-11e7-8830-33ff85017ada.png)

**Comment by odiea** [comment]
I do not know how well this will incorporate into 3.1.1. In store config you will need to select the enhanced receipt.

**Comment by odiea** [comment]
This is how the Enhanced receipt appears.
![2017-12-05 19_50_32-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/33642114-a6791940-d9f5-11e7-9585-9400008926c5.png)

**Comment by infomail** [comment]
When I install the files that send me in the link, it looks like this->

Your system folder path does not appear to be set correctly. Please open the following file and correct 
this: index.php

**Comment by odiea** [comment]
You will need to download the file. Extract it with zip. Then from the extracted file copy just the application folder into the current root directory.

**Comment by odiea** [comment]
What you may want to do then is download the current bintay version and replace that application folder with this application folder.

**Comment by infomail** [comment]
Sorry, Do you have any link to download it????

**Comment by mckaygerhard** [comment]
download from here https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files go to the end of the page grab the zip not the asc this are a 3.2.0 with lasted commit from master.. only unzip and sustituye the application DIRECTORY (not folder.. )

**Comment by SteveIreland** [comment]
@odiea If I may I'd like to ask what may turn out to be a stupid question.

Why is the customer address required on a POS receipt?  If the customer is walking out the door with a balance due then it seems to me that the document should be an invoice.

**Comment by SteveIreland** [comment]
Sorry, I thought you were using it in your shop.  I knew it would turn out to be a stupid question.

**Comment by odiea** [comment]
It was kinda a mashup for adding Category.
If it only contains  a return It will say Return and on an  Invoice the receipt will now say Invoice.
Yes my initial intension was just to use the Full name on an Invoice Receipt if the template was not used.
