### ISSUE TITLE
403 Error Forbidden - LEMP Installation

### ISSUE THREAD

**Issue by AhsenKh** [opensourcepos/opensourcepos#1746]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and **the problem still persists**.
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: latest-master
- OSPOS git commit hash is: ???
- PHP version is: 7.0.22
- MySQL or MariaDB version is: MySQL 15.1, MariaDB 10.0.31
- OS and version is: Ubuntu 16.04 LTS
- WebServer is: Nginx 1.10.3

### Issue

I have used [LEMP installation from this link](https://github.com/opensourcepos/opensourcepos/wiki/Local-Deployment-using-LEMP). I followed each and every step. However, when I go to *http://localhost/opensourcepos*, it gives me **403 Error Forbidden** *nginx/1.10.3 (Ubuntu)*.

Kindly discuss the issue.

**Comment by daN4cat** [comment]
Have you checked all the issues where Nginx is discussed?

**Comment by odiea** [comment]
Wouldn't he need the ip address of the ubuntu server and not localhost?

**Comment by mckaygerhard** [comment]
well apart of the very complicated setup, do you test it the part of phpinfo() ?
does phpinfo() returned right page?
i mean: this link https://github.com/opensourcepos/opensourcepos/wiki/Local-Deployment-using-LEMP#paste-the-following-php-code-into-the-file-and-save-it does result in expected php information?

next step i note the the hole link wiki there's no opensourcepos reference... only manual nginx winbuntu setup.. 

the 403 its due the source of the ospos are all from the user that clone the repo or untar or the user that download the sources, not the www-data user... 

get sure that the owner of the ospos sources in webroot are www-data .. also the ospos need a "hardcoded very complicated" (again) rewrite rule in root webserver

**Comment by daN4cat** [comment]
Ref #1130 

@RamkrishnaMondal can you please help?

**Comment by RamkrishnaMondal** [comment]
Just a few days ago i have installed LEMP on ubuntu 16.04.1(Elementary OS Loki) without any problem. Please re-check all the steps as per the wiki guide. Check the steps @mckaygerhard  commented above.

![screenshot from 2017-12-09 19 20 38](https://user-images.githubusercontent.com/14151032/33796214-343b4cb2-dd16-11e7-8bf1-eadba088c1b1.png)

**Comment by daN4cat** [comment]
Thanks @RamkrishnaMondal for the support.

**Comment by AhsenKh** [comment]
@mckaygerhard phpinfo() returns the right page, similar to @RamkrishnaMondal pasted.

However, I do not know how to perform the step you mentioned below,

> get sure that the owner of the ospos sources in webroot are www-data .. also the ospos need a "hardcoded very complicated" (again) rewrite rule in root webserver

**Comment by mckaygerhard** [comment]
chowm -R user:group /path/to/files

`chown -R www-data:www-data /var/www/html`

please try again whit the last command assuming your files are installing in /var/www/html take caution and please read  carefully seems do you need use more linux hosts and less winbutu.. too many clicks.. a quick google search gives you that command

please revise again:
1) php are working and give you phpinfo (now this passed)
2) mysql are working and you have access using user and pass by a hostname
3) the codeigniter ospos install are working 
4) the codeigniter ospos install can connect to database

The wiki and documentations lack of good support check procedure, the issue template are unuseless whitout that checks, of course due there's no way for mid-users to checks those...

the 3 and 4 steps to cheks are the most important and the most common problems here by users..

i dont understand why so complicated installation procedure, why not just install a normal php and apache2 with mysql in not so newer linux in a simple virtualbox virtual machine, with just 256Mb ram and a 2G of disk debian can server by just putting files of ospos in the www server root..
