### ISSUE TITLE
Item add to Sale failed - take 2

### ISSUE THREAD

**Issue by arikb** [opensourcepos/opensourcepos#1747]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported  - actually an identical issue has been closed assumed fixed. It's not. #1632 
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0 (unstable), upgraded from 3.1.1 stable in an attempt to fix this very issue
- OSPOS git commit hash is: ad1e63f
- PHP version is: 7.0
- MySQL or MariaDB version is: MySQL 5.7.20
- OS and version is:  Ubuntu 16.04.3 LTS up to date to now, Digital Ocean droplet
- WebServer is:  Apache 2.4.18

### Issue / Bug  / Question / New Feature

This is basically a duplicate of #1632 by @lutfiajib with the exception that I installed 3.1.1 from the zip and upgraded to 3.2.0 as an attempt to fix it.

Items added manually to the system (i.e. not through import through CSV). Some items can be added to a sale and some cannot eliciting the error message "Item add to Sale failed". Some items are added without an issue.

You can see in this screenshot the error message trying to add a second item - the first item was added successfully.
![screenshot-2017-12-10 vuurwerkt nl winkel powered by ospos 3 2 0 1](https://user-images.githubusercontent.com/1229613/33809351-c7cf6bcc-ddf5-11e7-9e3b-4e55bdafd763.png)

Nothing unusual in the logs, nothing unusual in the query log.

When an item is deleted and created, sometimes it can b added without a problem, other times it produces the same problem.

**Comment by daN4cat** [comment]
Have you taken this version from bintray: https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20171209171002.master.ad1e63.zip ?
If yes, which web browser are you using and how can I reproduce this as you say some items are fine and some not. I need to have one good and one NOT good.

**Comment by arikb** [comment]
The very one, yes.

**Comment by arikb** [comment]
Also, I turned on all the logging, I have those if you want.

**Comment by arikb** [comment]
@daN4cat actually when I think about it, I can even give you access to the machine if you send me an OpenSSH public key. It's not a production machine (yet).

**Comment by daN4cat** [comment]
I'm sorry but I don't have time to check other's people installations.
I just need all the data of the item that does not work.

**Comment by arikb** [comment]
Okay... item_number 907 (not item_id) has absolutely no problems, while item_number '44' fails every time.

```
mysql> select * from ospos_items where item_number in ('907', '44');
+--------------+-----------------------+-------------+-------------+-------------+------------+------------+---------------+--------------------+---------+--------------+-----------------------+---------------+------------+-----------+-----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+
| name         | category              | supplier_id | item_number | description | cost_price | unit_price | reorder_level | receiving_quantity | item_id | pic_filename | allow_alt_description | is_serialized | stock_type | item_type | tax_category_id | deleted | custom1 | custom2 | custom3 | custom4 | custom5 | custom6 | custom7 | custom8 | custom9 | custom10 |
+--------------+-----------------------+-------------+-------------+-------------+------------+------------+---------------+--------------------+---------+--------------+-----------------------+---------------+------------+-----------+-----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+
| Paris        | Cakes                 |        NULL | 44          |             |      40.00 |      40.00 |         1.000 |              1.000 |       6 | NULL         |                     0 |             0 |          0 |         0 |               0 |       0 |         |         |         |         |         |         |         |         |         |          |
| Aansteeklont | Veiligheids artikelen |        NULL | 907         |             |       0.25 |       0.25 |         1.000 |              1.000 |      22 | NULL         |                     0 |             0 |          0 |         0 |               0 |       0 |         |         |         |         |         |         |         |         |         |          |
+--------------+-----------------------+-------------+-------------+-------------+------------+------------+---------------+--------------------+---------+--------------+-----------------------+---------------+------------+-----------+-----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+
2 rows in set (0.00 sec)
```

**Comment by arikb** [comment]
Is there any other piece of information I can give you, @daN4cat ? It's still assigned to me with the pending label.

**Comment by arikb** [comment]
I also went through all the foreign keys to the table `ospos_items`, and besides the obvious differences (item Aansteeklont participated in sales so it has entries in sales items and item Paris didn't, differences in stock) I could find no other difference between them.

**Comment by daN4cat** [comment]
I assume the items are visible from Items view and you have inserted them using OSPOS not importing straight in the database. Right?

**Comment by arikb** [comment]
Correct. I haven't imported or made any manual changes to the database. They also come up in the search box when adding to the sale when I start typing either the "barcode" or the item name.

**Comment by daN4cat** [comment]
One thing comes to my mind, item_number should be a barcode not a number like that because OSPOS will clash between the number you set and item_id.
Most likely you have an item_id 44.
Please remove the item_number and if you want to generate some item_number for you based on the item_id go to Configuration >> Barcode >> Barcode Content and set Generate if empty.
Then from items view you selected the item and click barcodes. You'll get the barcode field filled in with a unique barcode generated out of item_id.

**Comment by arikb** [comment]
I will try it, although that defeats the purpose of the user. They have a catalogue number for each product which I encouraged them to use as the "barcode".

**Comment by arikb** [comment]
That didn't go well. I tried removing the barcode or replacing it with a long unique number. The configuration option didn't seem to make a difference, I don't see an automatically generated barcode.

I looked at another item that causes the error, this one:
```
mysql> select * from ospos_items where item_id = 7;
+-----------+----------+-------------+-------------+-------------+------------+------------+---------------+--------------------+---------+--------------+-----------------------+---------------+------------+-----------+-----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+
| name      | category | supplier_id | item_number | description | cost_price | unit_price | reorder_level | receiving_quantity | item_id | pic_filename | allow_alt_description | is_serialized | stock_type | item_type | tax_category_id | deleted | custom1 | custom2 | custom3 | custom4 | custom5 | custom6 | custom7 | custom8 | custom9 | custom10 |
+-----------+----------+-------------+-------------+-------------+------------+------------+---------------+--------------------+---------+--------------+-----------------------+---------------+------------+-----------+-----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+
| Marvelous | Cakes    |        NULL | 702         |             |      29.50 |      29.50 |         1.000 |              1.000 |       7 | NULL         |                     0 |             0 |          0 |         0 |               0 |       0 |         |         |         |         |         |         |         |         |         |          |
+-----------+----------+-------------+-------------+-------------+------------+------------+---------------+--------------------+---------+--------------+-----------------------+---------------+------------+-----------+-----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+
1 row in set (0.00 sec)
```

This one has a barcode (item_number) that is unique amongst the item_numbers and also doesn't clash with any item_id. It causes the same problem the Paris item causes.

**Comment by daN4cat** [comment]
For sure you have another clash. As said try to avoid using simple numbers like those as barcode.
If you search by Marvelous it will work, if you search using 7 it will work.
The message you see is simply saying that it cannot find the item simply using 702.
Barcodes follow dedicated formats and not sure why you need to number the item differently from item_id. In the long run you will get more and more issues because of clash of barcodes set manually.

As suggested go to Configuration >> Barcode >> Barcode Content and set "Generate if empty".
The from Items tick the boxes of the items with no barcode number and click the Barcode Generate button.
Refresh the items view and you will get barcodes generate according to the format you chose in Configuration.
I tend to use EAN8 to have a short barcode to put on small items.

**Comment by arikb** [comment]
I've been searching by the name or barcode and both produce this error message. I checked again and there is no clash. I can see the number 7 (item_id for this item) flash briefly in the search box before the error message shows up. I see the same (with different numbers of course) with successful items. If I understand that correctly it means it did find the correct item.

I generated an EAN8 barcode in the way you described for this item, and it still produces the same error message for this item.

Finally, I deleted all of the item_number, and generated a barcode for all of them. This seems to have done the trick somehow. Thank you for that!

For now I have my workaround, but it does look like a workaround to me, not a solution. If the item search in the UI returns a single item and it is selected, it should be already resolved to its ID and therefore unique, so a clash should not be an issue at this stage.

I don't really know PHP, but if I understand the logic in `Item->get_info_by_id_or_number()`:
```php
        public function get_info_by_id_or_number($item_id)
        {
                $this->db->from('items');
                if (ctype_digit($item_id))
                {
                        $this->db->group_start();
                                $this->db->where('item_id', (int) $item_id);
                                $this->db->or_where('items.item_number', $item_id);
                        $this->db->group_end();
                }
                else
                {
                        $this->db->where('item_number', $item_id);
                }
                $this->db->where('items.deleted', 0);
                $query = $this->db->get();
                if($query->num_rows() == 1)
                {
                        return $query->row();
                }
                return '';
        }
```

it seems flawed to me that the query looks for the `item_id` or the `item_number`, which could potentially return 2 rows (and with non-unique barcodes more rows) and then it limits the results to a single row or else returns FALSE.

Then the code in `sale_lib->add_item()` checks the result with `empty()` to determine failure, or maybe FALSE is also considered empty in PHP?

and eventually the controller ends up relying on that to return an error - all that after the view already resolved the item completely and uniquely.

Based on my limited understanding of this code, and the fact that this function still coerces the search term to integer when looking for item_id, I think the workaround will only work as long as the barcode interpreted as a number does not collide with an item_id. EAN8 barcodes seem to have a check digit, so that will reduce but not eliminate that likelihood.

Thanks for all your help!

**Comment by arikb** [comment]
So after reading the previous comment, I went looking for those collisions and found one:
```
mysql> select * from ospos_items where item_id in (5,55);
+----------+----------+-------------+-------------+-------------+------------+------------+---------------+--------------------+---------+--------------+-----------------------+---------------+------------+-----------+-----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+
| name     | category | supplier_id | item_number | description | cost_price | unit_price | reorder_level | receiving_quantity | item_id | pic_filename | allow_alt_description | is_serialized | stock_type | item_type | tax_category_id | deleted | custom1 | custom2 | custom3 | custom4 | custom5 | custom6 | custom7 | custom8 | custom9 | custom10 |
+----------+----------+-------------+-------------+-------------+------------+------------+---------------+--------------------+---------+--------------+-----------------------+---------------+------------+-----------+-----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+
| Ox       | Cakes    |        NULL | 00000055    |             |      40.00 |      40.00 |         1.000 |              1.000 |       5 | NULL         |                     0 |             0 |          0 |         0 |               0 |       0 |         |         |         |         |         |         |         |         |         |          |
| Splendid | Cakes    |        NULL | 00000550    |             |      32.50 |      32.50 |         1.000 |              1.000 |      55 | NULL         |                     0 |             0 |          0 |         0 |               0 |       0 |         |         |         |         |         |         |         |         |         |          |
+----------+----------+-------------+-------------+-------------+------------+------------+---------------+--------------------+---------+--------------+-----------------------+---------------+------------+-----------+-----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+
2 rows in set (0.00 sec)
```
Adding Splendid works fine, but adding Ox fails - I believe because Ox' `item_number` when coerced to integer is the same as Splendid's `item_id`.

**Comment by daN4cat** [comment]
You have a good point, I need to check that logic. Not sure that was touched or not in recent times or was already like that since a while.

Thanks for the report and debugging help.

**Comment by arikb** [comment]
Well, "Blame" shows it was last touched 11 months ago, by multiple people, including you...

**Comment by daN4cat** [comment]
Having touched the code from my side is a simple guess. The blame was not the point, I need to check if any change introduced a different behaviour.

**Comment by jekkos** [comment]
I do remember fixing something like this. Think I had to cast a variable as integer in a mysql query instead of just adding it as a string. Should be somewhere in Item model if I'm not mistaken.

**Comment by daN4cat** [comment]
Hmmm @jekkos actually there is a change made 1 year ago:

```
Author:		jekkos <removed>
Author date:	1 year ago (05/11/2016 19:44:55)
Commit date:	1 year ago (05/11/2016 19:49:08)
Commit hash:	49c89d1cecdfb6f6b427dd1ee1343ea0132b8b2c
Parent(s):	872aa7b829

Improve item search performance by casting to correct datatype (#924)
```

with the following:

	public function get_info_by_id_or_number($item_id)
	{
		$this->db->from('items');
-		$this->db->group_start();
-			$this->db->where('CAST(item_id AS CHAR) = ', $item_id);
-			$this->db->or_where('items.item_number', $item_id);
-		$this->db->group_end();
+
+        if (ctype_digit($item_id))
+        {
+            $this->db->group_start();
+                $this->db->where('item_id', (int) $item_id);
+                $this->db->or_where('items.item_number', $item_id);
+            $this->db->group_end();
+        }
+        else
+        {
+            $this->db->where('item_number', $item_id);
+        }

I probably need to test that and see if the 0's are removed and not left and treated as a string in the barcode.... thoughts?

**Comment by daN4cat** [comment]
@arikb if you find the time tomorrow, would you mind to give a try replacing the code marked with the + with the code marked with the - and test again?
Not the final fix, but just to check if that makes a difference.

I will then check more tomorrow or next days as it's now late.

**Comment by daN4cat** [comment]
Something we discussed in #666

**Comment by daN4cat** [comment]
Thinking on twice, I don't expect that to be the issue here. It's probably better to debug the code....

**Comment by arikb** [comment]
I'll try to get to it today, I asked my customer to check whether the workaround works so I can't touch the system until she gives me the okay.

**Comment by jekkos** [comment]
Just guessing: the zero might cause different weird behavior on ctype_digit? 

https://stackoverflow.com/questions/8557973/why-does-ctype-digit0-return-false

**Comment by jekkos** [comment]
think it's best to debug this step by step to understand what's going on

**Comment by daN4cat** [comment]
@arikb any feedback?

**Comment by daN4cat** [comment]
@SteveIreland @odiea do you think you have time to help with this?
I'm having a bit of difficulty to find the time before Christmas between my wife busy with her shop and me looking after our son...

**Comment by odiea** [comment]
Sorry I am in the same boat as you are. Got grand kids and my wifes Ugly Sweater Store going on till after Christmas. If I had a list of Items I could add that constantly gave issues I could play around with it.

**Comment by daN4cat** [comment]
Re-reading all this thread from the beginning because I really didn't pay the necessary attention.

@arikb has a point when he says that having two conditions in the where or_where could cause a failure because the expected result is 1. If item_id and item_number are the same you get one line (e.g. item_id value is set in item_number / barcode line). But if somebody enters an item_number as barcode in a different item then there is a clash.

I bet that's part of the "bug", but I need to think what to do in that case because two lines clashing between codes set in item_id and item_number doesn't sound right to me. Somehow we should probably just take the first line anyway.
Also what I should check is that if somebody adds 0s as barcode prefix those are not removed as it's a string, and that should be allowed to be considered different, and here ctype_digit might be the issue.

Going forward EAN8 codes that add item_id with a checksum will clash with item_ids that are equal to the same value. But EAN8 pads with 0 and therefore it should treated as string.

Maybe the old way was safer? 

```
		$this->db->group_start();
			$this->db->where('CAST(item_id AS CHAR) = ', $item_id);
			$this->db->or_where('items.item_number', $item_id);
		$this->db->group_end();
```

**Comment by daN4cat** [comment]
Here what ctype_digit considers numeric: https://stackoverflow.com/questions/236406/is-there-a-difference-between-is-int-and-ctype-digit#236411

0 prefix is considered number and the casting to (int) removes the 0 and makes the search of item_id be the first choice.

**Comment by odiea** [comment]
Sorry I can't help out much with this. I think it would be good to have a copy of his db to try to figure it out.

**Comment by arikb** [comment]
Sorry, I was pretty busy with this and other projects. I can get you a copy of the database before I erased the "barcodes" field from all items and created them as EAN8 barcodes if there are takers.

**Comment by daN4cat** [comment]
@arikb, zip the database dump and attach it here. Thanks.

**Comment by daN4cat** [comment]
Fixed and in master. barcodes starting with 0 are considered barcodes and never item_id.
There will be always at least 1 returned (first come first serve) in case of clashes between item_number (barcode) and item_id if simple numbers are used as barcodes.
The correct workaround is to prefix barcodes with 0 to avoid any clash.

**Comment by SteveIreland** [comment]
Sorry I didn't catch the earlier request.  I was discombobulated by some new work assignments and as a result was totally zoned out for a couple of weeks.

**Comment by daN4cat** [comment]
No worries, family and job come first.

**Comment by mckaygerhard** [comment]
WTF? start the barcodes with 0? seriously!? how do that for those scanners that dont allow modification?

great!

**Comment by daN4cat** [comment]
Not sure I explained properly. Any barcode is seen as barcode, however the barcodes starting with 0000 and thrn a short number were taken as a number matching item_id. So I made sure that those starting with a 0 are considered barcodes.

However if we look at the very big big picture in the long run in 10 years somebody might start having a clash between long barcodes and item_ids.
That's why we should probably consider removing the item_id search and just use barcodes and generate barcodes out of item_id automatically if the field is empty.

I would consider that approach.

**Comment by mckaygerhard** [comment]
umm i could provide a better solution: please read me a while: how maybe, barcodes are minimun 10 digits or more, well what happened when a barcode and a amount of items are same?

i mean: i have 1000010111 items created (erase, created etc and so one) and then now i scan a barcode just equal to that number! what happened? its not a "rare" case, its a very posible case

my solution its count the amount of the digits of the barcode, and change the item very common and scholar grade "autonumeric" to a special format in table.. that's the solution.. the format could be YYYYMMDDHHmmssdd using the time as code for the numbers

**Comment by daN4cat** [comment]
I'm afraid EAN8 is not 10 minimum.

**Comment by mckaygerhard** [comment]
of course ean8 its 8, and so one.. you guys cannot assume all people will have same limited resources as yours.. i try to test the barcode quality in the ospos and seems does not work!

**Comment by daN4cat** [comment]
Mixing up topics?

**Comment by daN4cat** [comment]
BTW I have suppliers that give us barcodes with 6 and starting with £ and then 5 digits.
You cannot assume anything about barcodes because there are several standards.

**Comment by mckaygerhard** [comment]
yeah that's right so hen a special format to the items may solve the problem then!

**Comment by daN4cat** [comment]
Item_id is the table id.

**Comment by daN4cat** [comment]
It would make sense to remove the search by item_id and generate barcodes instead when the field is empty. Job done.

**Comment by arikb** [comment]
I don't know if it will help at this stage, but here's the dump.

[ospos-before-patch.sql.gz](https://github.com/opensourcepos/opensourcepos/files/1612882/ospos-before-patch.sql.gz)

**Comment by daN4cat** [comment]
@arikb I closed this, it seems solved to me. Please test latest 3.2.0 and let me know if any more issue.

**Comment by daN4cat** [comment]
If it's deleted it's deleted, right?
