### ISSUE TITLE
Adding Icon / Link to Sales Manage Page

### ISSUE THREAD

**Issue by JackCameo** [opensourcepos/opensourcepos#1749]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: ad1e63fa3a64af385ebdb4782ea0368050f4aa7e
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.5
- OS and version is:      Ubuntu 16.4
- WebServer is:      (e.g. Apache 2.2
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

I am new to OSPOS, my development skills are a bit rusty but have been able to make small modification with success. This is probably a fairly easy fix but I seem to be having trouble with it. 
I have duplicated the invoice and created a packing slip, i added the necessary addition in various files and it is all working properly. The issue I am facing is adding an icon with a link to the manage sales page. The only place I am finding related to this is the function "get_sale_data_row" in the table_helper.php. I have added a custom row 

```
$row['packingslip'] = anchor($controller_name."/packingslip/$sale->sale_id", '<span class="glyphicon glyphicon-list-alt"></span>',
		array('title' => $CI->lang->line('sales_show_packinglsip'))
	);

```
yet it is still not displaying on the manage page for sales. I have of course added the sales_show_packinglsip to the sales_lang.php. 
Thank you for your time and clarification on the issue.

**Comment by daN4cat** [comment]
@JackCameo in `table_helper.php` you need to add something to `get_sales_manage_table_headers` too:

> 	$headers[] = array('packingslip' => '&nbsp', 'sortable' => FALSE);

Usually the 'edit' is left to the last position so add you icon before or after receipt or even the 'invoice' section.

**Comment by daN4cat** [comment]
Would be nice if you could share and contribute your work to the project....

**Comment by JackCameo** [comment]
Thank you, worked perfectly.

I don't mind to share and contribute however I don't believe my additions or modifications would fit properly into the theme of POS as I am using the POS to manage wholesale and retail, my code my not be written wonderfully and I don't know how to contribute on Github - I believe I would need to create a branch and push updates...If you want to share instructions I can give it a try and you can decide if my updates would fit.

**Comment by daN4cat** [comment]
Simply zip the files you changed and attach them here. 
Also add any change you made to the database tables structure.

**Comment by JackCameo** [comment]
I have made a few modifications, let me know if you want me to refactor anything. I have only added to the en-US language, I may add spanish to my modifications but was not intending others.
[application-12-17-17.zip](https://github.com/opensourcepos/opensourcepos/files/1566710/application-12-17-17.zip)

**Comment by JackCameo** [comment]
Is there a way to share privately?

**Comment by JackCameo** [comment]
[application-12-18-17.zip](https://github.com/opensourcepos/opensourcepos/files/1566726/application-12-18-17.zip)

**Comment by JackCameo** [comment]
[application-12-18-17.zip](https://github.com/opensourcepos/opensourcepos/files/1566727/application-12-18-17.zip)

**Comment by daN4cat** [comment]
Thanks, I will look into it later.

**Comment by mckaygerhard** [comment]
oh great @daN4cat you can also view my adaptations to fiscal kit printers and adapt to ospos please, and a soda too! thanks in advance! ¬_¬
