### ISSUE TITLE
Add overall discount

### ISSUE THREAD

**Issue by buddimasupun** [opensourcepos/opensourcepos#1751]
Hi,

Is there any way to add overall discount in sales and receiving window along with the individual discounts.
Adding that functionality will be a great addition to this system
Thanks

**Comment by mckaygerhard** [comment]
some of my clients need that feature, a manager wants to give a special discount to a particular client at the sale moment..

it's a feature very need it!

**Comment by nerv55** [comment]
same here ,it's a feature very need it and usefull to client!

**Comment by odiea** [comment]
Have you tried using the Customer discount then add additional Items discount as needed at POS.
![2017-12-17 11_46_42-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/34082705-588357f8-e320-11e7-8711-26676d515699.png)

**Comment by mckaygerhard** [comment]
@odiea its not the same, it means at the sale moment! a surprise discount based on the amount of sale by example some client that buy exactly 800 event 801

**Comment by odiea** [comment]
This feature has been requested 90+ times. Maybe someday someone will set it up for use in OSPOS.
https://github.com/opensourcepos/opensourcepos/search?q=discount&state=open&type=Issues&utf8=%E2%9C%93

**Comment by mckaygerhard** [comment]
umm i understand i can made it! but that's means many many stupid cuestions (due i hate jquery) @odiea i finished the specific country implementation based on fiscal kit... i'll made a pull request in some day..

**Comment by mckaygerhard** [comment]
by the way, the response was so funny

**Comment by mckaygerhard** [comment]
@buddimasupun the prevoulsy issue most closed to this its ·#911 please write here
