### ISSUE TITLE
Cannot complete invoices

### ISSUE THREAD

**Issue by buddimasupun** [opensourcepos/opensourcepos#1752]
Hi,
it is impossible to complete sales invoice in 3.2.0 since the Complete button is missing. Please Check.
Thanks

**Comment by mckaygerhard** [comment]
please fill the bug template, them answer all the questions, also seems this bug was fixed in lasted master. this bug issue will be close due that i posted to you

**Comment by odiea** [comment]
You must add a customer to the Sale before the Invoice option will work.
