### ISSUE TITLE
Barcode quality (question)

### ISSUE THREAD

**Issue by marcellusmontilla** [opensourcepos/opensourcepos#1753]
### Issue / Question / Bug
- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information
- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.6
- OS and version is: Linux
- WebServer is: Apache

### Question
What is barcode quality? I've tried playing with it in the config, tried setting it to 10 and then 100. There seems to be no difference. Just curious, is there?

**Comment by jekkos** [comment]
Think it just refers to the generated output image compression quality ratio

**Comment by marcellusmontilla** [comment]
Does anyone have an idea how to choose what value is best for what scenario? When to use barcode quality = 10 or 100?

**Comment by daN4cat** [comment]
Sorry no help from my side as I never used the barcode printing feature. I just use EAN8 generated ones and print the number with a handheld label printer. It's used to tag small sparse items. Most have already barcodes.

**Comment by mckaygerhard** [comment]
umm now i understand why not taking enought atention to the barcode and item add problem in issue #1747 all of you guys does not have enought hardware.. i have enought hardware and the answer to this:

the barcode quality its suppost is the margin of error for reading a printed label with a code that can be misread or confused with another bar code.. so two labels printed witha  EAN13 code can be equal with a larger margin and a poor quality..

in a industry the barcodes are the second most importan way to identify the items (products in the real life guys)

**Comment by marcellusmontilla** [comment]
umm, so when to use quality = 100 and when to use quality = 10? Or should everyone use quality = 100 every time? I assumed there must be cases where one is favored over the other since someone made it editable in the config.

**Comment by mckaygerhard** [comment]
i not see any change in ospos.. its nonsense, due php cannot interact with hardware.. so i cannot test due the generation of image need too many steps to see it! (config then that and that and then generate a barcode)

**Comment by daN4cat** [comment]
Barcode quality would work if the barcode image were a jpeg, but because it's a png there is no use of that parameter.

From BarcodeBase.php:

```
	/*
	 * Set Quality
	 * @param int q - jpeg quality 
	 * @return instance of \emberlabs\Barcode\BarcodeBase
	 */
	public function setQuality($q)
	{
		$this->jpgQuality = (int) $q;

		return $this;
	}
```

Here the type is defaulted to 'png'

```
	/*
	 * Output Image to the buffer
	 *
	 * @return void
	 */
	public function output($type = 'png')
	{
		switch($type)
		{
			case 'jpg':
			case 'jpeg':
				imagejpeg($this->img, null, $this->jpgQuality);
			break;

			case 'gif':
				imagegif($this->img);
			break;

			case 'png':
			default:
				imagepng($this->img);
			break;
		}
	}
```

The base64 convertion the output has no parameter so it stays a png

```
	/*
	 * Base64 Encoded 
	 * For ouput in-page
	 * @return void
	 */
	public function base64()
	{
		ob_start();
		$this->output();

		return base64_encode(ob_get_clean());
	}

```

It will probably make sense to remove the Quality parameter from Configuration as png images are lossless and zip compressed.

**Comment by mckaygerhard** [comment]
so in conclusion, the removal its the obvious.. 

due the code in php does not make any sense or follows the barcode quality standards and confused to real uses that know about inventary rules and usage of stores

**Comment by daN4cat** [comment]
done already and in master. Removed.

**Comment by mckaygerhard** [comment]
also remenber that must set internally the jpg to 100 if jpg its used, the better to sizes (large stores need light files in invetory)

**Comment by daN4cat** [comment]
jpeg is not used as I said, please read my comment above.

**Comment by mckaygerhard** [comment]
done! i write after that commend.. catch it!

**Comment by mckaygerhard** [comment]
but i noted jpeg produce more light files! why not used with 100 in ?
