### ISSUE TITLE
error on edit report sales, model seems does not return valid rows for get_info of sales

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1754]
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:lasted master
- OSPOS git commit hash is: 
- PHP version is:    5.6
- MySQL or MariaDB version is: MariaDB 10.0
- OS and version is:  VenenuX massenkoh Linux
- WebServer is:    Apache 2.4

### Issue / Bug  / Question / New Feature

i go to the reports, then made a report of transactions, sales on the day all sales all stock

then click on a sale to edit and popupwindows shows empty

server output says: 
` PHP Fatal error:  Call to a member function row_array() on boolean in /usr/share/html/opensourcepos/application/controllers/Sales.php on line 1132, referer: http://127.0.0.1/opensourcepos/public/index.php/reports/detailed_sales/2017-12-18/2017-12-18/complete/all`

i revised the controller, the call was:
`$sale_info = $this-xss_clean($this->Sale-get_info($sale_id)-row_array())`

in the Sale model i does not get clear the query, last command was `$this->db->get` but returns `TRUE` event a clear info from db, seems the select does not return valid rows!

**Comment by mckaygerhard** [comment]
now returns always FALSE

**Comment by odiea** [comment]
Are you still having this issue? If not I will close it.

**Comment by mckaygerhard** [comment]
hi @odiea , of course yes, there's no commit related! i monitoring the code changes and i cannot see any work in this.. i put the line where and why.. as anybody can see i track any changes from this repository every day

**Comment by odiea** [comment]
Latest Github Master or Bintray? None of my test servers show this issue.

**Comment by daN4cat** [comment]
Latest master in controller Sales line 1132 there is nothing like that. 
See here: https://github.com/opensourcepos/opensourcepos/blob/master/application/controllers/Sales.php#L1131
and it's now line 1131 because I removed one line with latest commit.

Nevertheless, I tested and I don't get the issue.

Are you sure you have the correct files? Or are you reporting something of a modified code? I suspect the latter....

**Comment by mckaygerhard** [comment]
that's change was minutes ago.. now you can say re-test again.. so let me test and report feedback again

**Comment by mckaygerhard** [comment]
oh i must waith for bintray .. when done i re-test and report feedback in some hours

**Comment by daN4cat** [comment]
My change has nothing to do with the issue you reported, and that file has just one line changed.
I'd suggest to check the modifications you made to the code as I can see you made some.

We tested and we cannot reproduce, therefore I close this issue.

**Comment by daN4cat** [comment]
Of course if you manage to report a test case that can allow us to reproduce it systematically, then we'll reopen the issue.

**Comment by mckaygerhard** [comment]
umm said that its my "modification" ok lets configure a clean install... i'll post later feedback

**Comment by mckaygerhard** [comment]
still have the issue, said "reopen" but i cannot reopen, seems here there are some "dictadura"

**Comment by mckaygerhard** [comment]
still have the issue, said "reopen" but i cannot reopen, seems here there are some "dictadura", 

seems the problem are the apache2 version worker, there's no take the htaccess i noted, i try later with a more older apache2 and different db (will use mysql more older too)

**Comment by daN4cat** [comment]
I can reopen but you need to understand what's wrong as I couldn't reproduce and @odiea  too.

**Comment by mckaygerhard** [comment]
i noted that some issues here never could reproduce unless pay attention to one thing: all of you thinking that apache lasted with php lasted are the only configuration for people.. well as i posted now the hardcoded htaccess and the very specific configurtion and the very close apache preference its a common in the list of opened and close issues here... its so hard to see the evidence?

**Comment by daN4cat** [comment]
We use apache 2.4, php5.6 and mariaDB but we cannot reproduce the problem.
If you can the best for you is to debug the issue and find a fix.

**Comment by mckaygerhard** [comment]
quite strange in one of my installations OS in that particular OS does not work, i'll not close yet and try again why i have this error to documented if happened to another people..

**Comment by daN4cat** [comment]
When you have a fix please submit a PR.

**Comment by daN4cat** [comment]
Any news?

**Comment by mckaygerhard** [comment]
or i not got enought skills or i got something wrong in wheeze with php 5.6, i'm currently in that for sporadic moments of "inspirations", please be patient for a day more and you can close it (i already know you like it close issues)

**Comment by daN4cat** [comment]
I bet this is yet another non-issue but a personal issue/customisation/installation... I'm not here to fix those.

**Comment by mckaygerhard** [comment]
its not personal customization, i see in log files and seems others have similar issues like me but notes have not tecnnical words to express the issues.. if we have some stadisticall tool can we see an obvious commons inside all the issues

**Comment by daN4cat** [comment]
And who else is reporting this issue?

**Comment by mckaygerhard** [comment]
i removed the OS instalation, never found the reason, comparing the code the only difference was a extra column in sales table, but inclusivelly removing that change the error still hapened, 

cannot reproduce in other OS installation .. so i'll must close this issue as unknow reason and unresolved

**Comment by daN4cat** [comment]
So we know that `VenenuX massenkoh Linux` is not supported. RIP

**Comment by mckaygerhard** [comment]
last problem was in Debian wheeze/jeesie, the error in venenux massenkoh linux was gone dais ago

**Comment by daN4cat** [comment]
People installed on Raspberry PI with Debian and no issues... instructions in the wiki.
