### ISSUE TITLE
error installation force usage of network connection on reports

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1755]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- []x Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted
- OSPOS git commit hash is: 
- PHP version is:    5.6
- MySQL or MariaDB version is: MariaDB 10.0
- OS and version is:    Venenux massenkoh Linux
- WebServer is:    Apache 2.4

### Issue / Bug  / Question / New Feature

try to use the sales report sumary `summary_sales` so go to Reports->Summary->Transactions and click

take too much time to display.. reason: stupid usage of network external resources

webserver log said:

`[Mon Dec 18 10:04:43.651441 2017] [:error] [pid 15482] [client 127.0.0.1:46360] Analytics Host not reachable! Error: Connection refused, referer: http://127.0.0.1/opensourcepos/public/index.php/reports`

as the real problem its at the log

**Comment by odiea** [comment]
Do you have Send Statistics unchecked in General config?

**Comment by mckaygerhard** [comment]
umm interesting, this configuration must be automatically configured based on ping status.. there's easy way to do so in php due unixes does not need permisions to made pings..

**by default this settings must be off.. confuse so much to the user impelmentation when other errors are present and not have enought knolegd**

**Comment by mckaygerhard** [comment]
@daN4cat for sure only see the "close" button in github interface, i read the readme files and related wiki pages and i do not have any reference documentation to this setting **clarelly** .. its a bug that must be resolved better thant with a simple response
