### ISSUE TITLE
Missing Employee permissions for Expenses Reports. Current 3.2.0

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#1756]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: Current 3.2.0
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) 7
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) Maria 
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Xampp or Ubuntu Server
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Expenses Reports permission no longer available in Employee grants.
![2017-12-20 06_24_13-wedidit _ powered by ospos 3 2 0 - opera](https://user-images.githubusercontent.com/10962177/34209373-12eb8afe-e54f-11e7-93e7-3dc44d0b27ea.png)

**Comment by odiea** [comment]
Showed properly after manually adding the grants.

**Comment by mckaygerhard** [comment]
where its the query to added to my personal database.sql file?
or how can we extrac the protper query to set this by default to admin employee!?

**Comment by mckaygerhard** [comment]
ok ok sorry its added by default in lasted master..

**Comment by daN4cat** [comment]
Every new addition is managed with an automatic upgrade the first time you login. Only once.

**Comment by odiea** [comment]
In my case I had upgraded the db before the Reports were installed.
