### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#1760]
Thanks to @jekkos,@dan4cat ( doing all the grunt work this year), @Steveireland and everyone else who contributed to keep OSPOS alive and well.
Merry Christmas and Happy new year to all.

**Comment by daN4cat** [comment]
Merry Christmas and Happy New Year too, @odiea

**Comment by jekkos** [comment]
Thanks to all you guys for continuing the effort to keep this project going! Although I found myself not being able to invest a lot of time I think it's still great to see a project like evolving and being thrived by the community around it. Happy holidays.

**Comment by marcellusmontilla** [comment]
I haven't contributed because I don't really code, but I appreciate the quality of OSPOS and the work of core collaborators. Sincerely, THANK YOU.
