### ISSUE TITLE
Run OSPOS on AWS Lambda

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#1761]
Would be interesting to run OSPOS completely on AWS Lambda using RDS Mysql as backend.

PHP on Lambda: https://www.lambdaphp.host/

In this way you just pay per click and operation in a completely serverless mode.

**Comment by daN4cat** [comment]
More here: https://aws.amazon.com/blogs/compute/scripting-languages-for-aws-lambda-running-php-ruby-and-go/

**Comment by mckaygerhard** [comment]
it's a great idea but currently i think are other needs uncomplmeted like a good documentation and a isntaller checks that oriented what are wrong in more specific way..

**Comment by daN4cat** [comment]
Setup AWS API Gateway with Lambda using PHP: http://cwhite.me/hosting-a-laravel-application-on-aws-lambda/

**Comment by daN4cat** [comment]
Issue is file writing, that cannot be done as there is not file system (e.g. save images). We would need to use S3 instead or everything stored in MySQL.

**Comment by jekkos** [comment]
https://hackernoon.com/how-did-i-hack-aws-lambda-to-run-docker-containers-7184dc47c09b

**Comment by daN4cat** [comment]
Before doing anything with this we would need to remove any local file reading/writing and store everything in a database or mount an S3 bucket.
I don't see this happening any time soon... just a nice thought. Maybe one day...

**Comment by daN4cat** [comment]
I close, I don't think we will ever find the time for this and could have a major impact.
Better rely on docker containers and deploy OSPOS web app to AWS Fargate or Azure Container.
Some could even dare to go for Kubernetes if they wish, but it's more for scaled solutions.
