### ISSUE TITLE
strange redirection after install

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1762]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted master from bintray
- OSPOS git commit hash is: 
- PHP version is:      5.6
- MySQL or MariaDB version is:  MariaDB 10.1
- OS and version is: Debian jeesie
- WebServer is:     Apache 2.4

### Issue / Bug  / Question / New Feature

setup install normally and in htaccess set rewrite rule to the path as wiki and comment said

after login redirect to login controller and no feedback in error.log

log of apache access:

```
192.168.1.106 - - [24/Dec/2017:21:31:42 -0400] "GET /ospos/public/ HTTP/1.1" 200 1317 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.9) Gecko/20100101 Goanna/3.2 Firefox/45.9 PaleMoon/27.3.0"
192.168.1.106 - - [24/Dec/2017:21:31:51 -0400] "POST /ospos/public/login HTTP/1.1" 404 512 "http://192.168.1.105/ospos/public/" "Mozilla/5.0 (X11; Linux x86_64; rv:45.9) Gecko/20100101 Goanna/3.2 Firefox/45.9 PaleMoon/27.3.0"
192.168.1.106 - - [24/Dec/2017:21:31:59 -0400] "GET /ospos/public/index.php HTTP/1.1" 200 1317 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.9) Gecko/20100101 Goanna/3.2 Firefox/45.9 PaleMoon/27.3.0"
```

**Comment by mckaygerhard** [comment]
as can noted in the las log, hardcoding "index.php" in the url bar get access but fails after sucessfull login, so then remove those very complicated non-working specific rare rewrite rules seems solve the problem but need to put the name of the index "index.php" in config.php

unless pay attention to one thing: all of you thinking that apache lasted with php lasted are the only configuration for people..

**Comment by daN4cat** [comment]
You forked OSPOS, right? Customise as you like it to fit your needs. Nobody prevents you from doing that.
Just to be clear, I'm not sure what you expect us to do for you? Just take and change as you like.

**Comment by mckaygerhard** [comment]
i'm afraid i'm taking about fresh install from jenkis, do you read the information provided?

**Comment by daN4cat** [comment]
And where it's written that we support Jenkins?

**Comment by mckaygerhard** [comment]
sorry i write bad .. i mean bintray, i just i also working in another proyect and get confusing

**Comment by mckaygerhard** [comment]
wow! closed! i dont see the commit that solved that!??¡P?

**Comment by daN4cat** [comment]
And what should I fix? Your personal problem, installation, customisation?

**Comment by mckaygerhard** [comment]
i try it but i not have enought time as i can noted, many issues seems related to the very hardcoded developers "think" customizations.. due the isues are closed very quickly

**Comment by daN4cat** [comment]
What you are "blaming" is CI installation leveraging composer in a secure way.
The fact that you want some special for your installation is for you to sort out.
Maybe you should make a distinction between what is your special requirement and what is standard off-the-shelf on offer. I'm afraid I don't have time to fix special needs.

**Comment by mckaygerhard** [comment]
solution for this problem are really the #1608 but its delayed to 4.0.0 (was for 3.2.0 but no made it)
as in #1608 are posted, the .htaccess file have hardcodes routes and its only suppoert by apache2..

**Comment by jekkos** [comment]
@mckaygerhard feel free to propose any improvements on this part..

**Comment by mckaygerhard** [comment]
i have a almost done solution but will require "index.php" must be present in all the url's, will work with all webservers

**Comment by daN4cat** [comment]
I don't like having index.php in my URL path, why would I need that @mckaygerhard because you want?

**Comment by mckaygerhard** [comment]
hi @daN4cat and @jekkos , maybe dont you like it, but one of the indicators of the most mayority of the issues reportes are due that "forced" and "hardcoded" ambiguous "apache2 only" rewrite rules

some of the disadvantages of the current behaviour:
* only support officially apache2 the most slowly webserver (well apart of IIS or whatever named)
* due that its very complicated write an oficial documentation, in fact there's no clear neither structured documentation in the wiki
* does not permit aliasing the professional way of any no-hacking chrootkit installation

we have only in the wiki an amount of 5 page for install process and those pages are very generic without structure due are really user contributed notes.. 

also i tested a modified no-htaccess ospost in hiawatta (the most secure http web server) and in the very famoust "lighttpd" (that server wikipedia and youtube as a fact) and works of course by purgein those "bill gates" htaccess depends files

i converted and try to detect those rewrite rules using index.php files and the php SERVER array, i dont are a developer either an expert but by now i have only many test.. due my limited knowledg and time i not post a pull  also due i have pending how to addeed new strings to spanish languaje.. in the weblate there's no way to do?
