### ISSUE TITLE
How can i add expenses system in this software

### ISSUE THREAD

**Issue by shamiul72** [opensourcepos/opensourcepos#1763]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

I need to know how can i add expenses system in ospos.Kindly provide me the working code or suggest me that how can i achieve this thing.Thanks

**Comment by daN4cat** [comment]
It's already implemented in 3.2.0 soon to be released.

**Comment by mckaygerhard** [comment]
please can ilustrate or give some way to see this feature in curren jenkys? i mean **you are very great to close issues** but please give **more info rather than just only "already implemented in somewhere here in next"**, thanks in advance

**Comment by shamiul72** [comment]
mckaygerhard is right....Kindly give us more information please

**Comment by daN4cat** [comment]
Search open/close issues and read the threads. That's what the template invites to do to avoid repetitions.

**Comment by mckaygerhard** [comment]
i searching i found some but not all the people are expert in code, please give a break to anothers...

@shamiul72  expenses are a module like other, appears in upgrades after run property the scripts if ospos are lower than 3.1 and the user have right permission (some ilogic due if i not have permission how can i added permissions to me itselft)

so if module does not appears must added permissions to the user and will see one icom more, also must enabled for the others modules

@daN4cat its true that a search give some light but not all the people have idea where or what search due there's a barrier called "language"

**Comment by shamiul72** [comment]
@daN4cat @mckaygerhard I have noticed that the expenses system is added to the software 30 days ago...Can anyone tell me how to use it....here is the screen that captured
![capture](https://user-images.githubusercontent.com/33060445/34585436-7bd49cee-f1c1-11e7-8182-da3eebdb1aab.PNG)

**Comment by odiea** [comment]
Yes it is in version 3.2.0. so go to local install on the ft page and download the unstable build from bintray.

**Comment by shamiul72** [comment]
@odiea ok....Thank

**Comment by mckaygerhard** [comment]
currently i must post first in google translator to explain to you, i currently experimenting with that new feature

**Comment by shamiul72** [comment]
@mckaygerhard Do whatever you want to do...I have just asked a simple question...

**Comment by mckaygerhard** [comment]
i said due i not write very well english, i want not said to you some thing wrong.. so i still testing the new features that will be release in 3.2

**Comment by shamiul72** [comment]
@mckaygerhard Ohhh Sorry for misunderstanding
