### ISSUE TITLE
TAX settings (shipping / freight cost)

### ISSUE THREAD

**Issue by kaslak** [opensourcepos/opensourcepos#1764]
Hi there,

there has been a lot of discussion about taxes - and how to handle them.
Since 3.1 there has been a lot of changes about this.

Could anyone tell how to handle all these new options... like tax-type etc.
You're changing issues - but how will I find out how to use it - if not involved in the process?
Maybe there's an issue about it - please help me find it. WIKI?? Ha! I'm lost in the dark :(

**Comment by daN4cat** [comment]
There is the standard tax with VAT system or US system as it always used to be, and there is the Customer tax: https://github.com/opensourcepos/opensourcepos/wiki/Sales-Tax-by-Customer

**Comment by daN4cat** [comment]
What do you need exactly?

**Comment by kaslak** [comment]
Thanks, mate. Couldn't find that on the wiki - reading for now... :)

**Comment by kaslak** [comment]
No way to get a cascading Taxing...
I re-read the wiki at least 3 times, tried for hours - no result.
I want 2% on the Item , then subtotal, then VAT ... I'm puzzled.
Reading the wiki, this should be possible, but putting it in practice, can't find a way.

**Comment by daN4cat** [comment]
Are you talking about GST and Tax system in India?

**Comment by kaslak** [comment]
No, Europe...
We deal in textile wholesale and add a 2% freight (not really a tax, more a surcharge) before adding 19% VAT

**Comment by daN4cat** [comment]
OK, so that's not a tax but an additional cost.

**Comment by kaslak** [comment]
yes, but how I understand the cascading system one can add a tax on an item and the the VAT.
I just can't figure out where to determine that it's cascading.
In DB sales_items_taxes we have a columns "cascade_tax" and "cascade_sequence" (values are all zero) ... what is it for?

**Comment by daN4cat** [comment]
The shipping cost was discussed here #872.

Applying the tax as way of adding a charge with double tax could be an option but it follows the US system. You need to read about that or wait for @SteveIreland to reply.
I use simple VAT 20% included. And that does for me.
