### ISSUE TITLE
I want to know if there is a way to print the total price value into float value after points

### ISSUE THREAD

**Issue by shamiul72** [opensourcepos/opensourcepos#1765]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

I want to know if there is a way to print the total price value into float value after points.Kindly suggest men any code or procdure to do it.Thanks

**Comment by SteveIreland** [comment]
Is this for a school project?

Floating point calculations are generally bad for general  business purposes because of rounding issues.

If you just want to render it with the exponent then the following link includes examples (particularly in the comments) that will provide you with code examples.

http://php.net/manual/en/language.types.float.php

**Comment by shamiul72** [comment]
@SteveIreland No, this is for a sweet shop in which we use kg,s for measurement like 1.5 2.5 kgs etc

**Comment by daN4cat** [comment]
In configuration you can set up to two decimals for quantity and totals, and up to three  decimals for taxes. I'm going by memory but it should be something like that.
So Kg can be supported in the quantity.

**Comment by mckaygerhard** [comment]
@shamiul72 the correct way to do that its enable float amunt for cuantities in stock/items, so 1.2 kg will be 1,2 items amount.. but seems ospos does not support that, its the correct way where must be done

**Comment by mckaygerhard** [comment]
ah @daN4cat does respond the way to do..

**Comment by shamiul72** [comment]
@mckaygerhard I have just noticed that if change the quantity to 1.5 or something in float, the system put its price as its quantity (1.5) to the payment section...The problem is only in the quantity field and the print section remains 1 or 2 but not in points

**Comment by daN4cat** [comment]
With print you mean receipt or invoice?

**Comment by shamiul72** [comment]
@daN4cat Receipt and invoice

**Comment by daN4cat** [comment]
So your issue is that quantity with decimals is not printed in receipts and invoices.
Just that?

**Comment by shamiul72** [comment]
Ya

**Comment by daN4cat** [comment]
It's working:

![image](https://user-images.githubusercontent.com/636048/34361296-ad612cae-ea60-11e7-88c7-dfc126de4441.png)

**Comment by shamiul72** [comment]
How...?

**Comment by daN4cat** [comment]
Simply setting 2 decimals for quantity in Store Config (COnfiguration) under Locale tab.

Have you checked that before asking here?

**Comment by shamiul72** [comment]
Oh God....Thanks @daN4cat

**Comment by daN4cat** [comment]
I read that you didn't..... I close.
