### ISSUE TITLE
Installation of OSPOS 3.1.1

### ISSUE THREAD

**Issue by linuxaddd** [opensourcepos/opensourcepos#1768]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

The installation is not correct, check your php.ini file.
<img width="1093" alt="screen shot 2018-01-03 at 9 36 55 am" src="https://user-images.githubusercontent.com/35039787/34515313-7b783584-f069-11e7-9e81-96a9f233fb5e.png">

**Comment by daN4cat** [comment]
I'm sorry but I need to close this issue because you chose to ignore the check list that would explain you what to do.

**Comment by tawl** [comment]
Hello every one,

Since 2 months, i'm working with ospos 3.1.1 after updating from 3.0.2.

But, monday morning, i find this error "**The installation is not correct, check your php.ini file**"
![20180110_071903](https://user-images.githubusercontent.com/11440694/34880076-2cce69d6-f7a7-11e7-9f5f-bb546855c7c3.jpg)

Please Help. I need to re-starting my work.

Regards

**Comment by odiea** [comment]
Check the php.ini file and make sure ll the following are enabled.
'bcmath', 'intl', 'gd', 'sockets', 'openssl', 'mbstring', 'curl'

**Comment by tawl** [comment]
OK, I will verify.

I will let u know if it works.

Thanks.

**Comment by hjoab** [comment]
Hi.

I recently discovered this project and I would like to collaborate in it,
BUT.... I need help in understanding it.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

*Holger José Otto ANDRÉ B.*
Skype: hjoab1

Mobile/Whatsapp : +(506) 8883-9645

Website: https://cr.linkedin.com/in/hjoab

San José, Costa Rica, Central America.

2018-01-12 9:18 GMT-06:00 tawl <notifications@github.com>:

**Comment by odiea** [comment]
You should download and install the unstable version. Play with it for a while then inspect the code to see how it works.

**Comment by daN4cat** [comment]
@tawl in 3.1.1 also mcrypt php extension.

**Comment by tawl** [comment]
I verified the log and extensions of PHP.
![20180113_065209](https://user-images.githubusercontent.com/11440694/34905150-11155d04-f84b-11e7-9042-95f76198ffee.jpg)
![Uploading 20180113_065152.jpg…]()
But i don't know what happened. It works for me for a more than 1 month.
How can i install the other extensions

**Comment by daN4cat** [comment]
@tawl something must have changed, either you touch PHP code (in any form, even altering some header or footer), or you updated the server and the php extension is not fine anymore.
Also make sure you didn't update to PHP 7.2 because 3.1.1 does not work with PHP 7.2. You need 3.2.0 for PHP 7.2.

**Comment by tawl** [comment]
![20180113_065152](https://user-images.githubusercontent.com/11440694/34905296-b249363a-f84d-11e7-8e84-b24df9808693.jpg)
The prix which not uploaded.

I tried To install a new version of 3.1.1 with new databasa, but always thé same errorerror.

**Comment by odiea** [comment]
Have you followed these instructions for the needed files?
https://github.com/opensourcepos/opensourcepos/wiki/Local-Deployment-using-MAMP-for-Windows

**Comment by daN4cat** [comment]
@tawl which version of PHP are you using?

**Comment by tawl** [comment]
php5.5.12

**Comment by tawl** [comment]
Apache/2.4.9 (Win32) PHP/5.5.12

**Comment by daN4cat** [comment]
and have you changed anything of the OSPOS php code?

**Comment by tawl** [comment]
I think so , i changed something in the footer but it's for a month (not a Big thing ),  after it work fine. But i tried with a new folders of ospos and new database the same error.
I remember i see  the problem for the first time after connecting to internet (it was the first i connect this pc to internet ).

**Comment by daN4cat** [comment]
Try with the original code (with no changes at all) and see if it works fine. I bet it will.

**Comment by mckaygerhard** [comment]
yeah all changes are permited until the ospos get some internet external check also... as exampel the footer.. for that change must desminified and rework the checks in both the js and php libs of ospos

**Comment by daN4cat** [comment]
@mckaygerhard you must respect the software license terms. If not remove OSPOS from your machines and use another software.
Please confirm here that you follow the license terms and conditions.
