### ISSUE TITLE
Installation OSPOS 3.1.1

### ISSUE THREAD

**Issue by linuxaddd** [opensourcepos/opensourcepos#1769]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is: 5.6     (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:  MariaDB 10.1    (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is: OS X     (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:  Apache 2.4    (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:  XAMPP    (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I'm doing a new installation, did as instructed but when i open the login page and try to login, i get this error - The installation is not correct, check your php.ini file. below is an image.

<img width="1093" alt="screen shot 2018-01-03 at 9 36 55 am" src="https://user-images.githubusercontent.com/35039787/34517197-f611a41c-f071-11e7-88ef-cc1c860da100.png">

**Comment by mckaygerhard** [comment]
a very popular issue.. maybe we need a better documentation or a better behaviour for the hardcoded ospos web root path, why nobody can see that?

**Comment by mckaygerhard** [comment]
first of all: what error log are referending the ospos installer? PLEASE BICHT! be clear!

second all the documentation are very out of sync from the hardcoded assumed ¿environment of the ospos code

**for most unixes and linuxes if are reference as error web serve log from php/web call, must be in `/var/log/<webserversoftwarename>/error.log` its a standar, event if we use a abberration like XAMP in that case will be in `<pathofxamp>/apache/log/error.log`**

the bad hardcoded rewrite rules, the need of and check installer and a good documentation are very need changes for a new year!

**Comment by linuxaddd** [comment]
The error log is empty, i'm thinking the php.ini is not correct, please can i have a copy of a working php.ini.

**Comment by mckaygerhard** [comment]
your php.ini canot be empty due you are using a vendor OS php installed, and for most easy, just re-run:

`apt-get --fix-broken --reinstall install php5-common`

to regenerate php ini fi8les, if not just remove all with "purge" and install again..

for php right check make a phpinfo.php file in webroot and visit from your browser, the contents of the php file must be `<?php phpinfo(); ?>`

**Comment by linuxaddd** [comment]
I said error log is empty, not php.ini

**Comment by mckaygerhard** [comment]
quite strange are emtpy.. so then some extension of the php are not installed/enabled please do you install all the required packages/extensions?

**Comment by daN4cat** [comment]
See comment in #1770

**Comment by mckaygerhard** [comment]
@linuxaddd in OSX see the error log of XAMP again after reinstall , at the <pathofxamp>/apache/log/error.log , must be opened with the editor not in the browser, try to use the php.ini provided by their installation not by other due may differ significativelly

**Comment by daN4cat** [comment]
Please note that you have PHP 5.6 so you don't have the MCrypt problem as per discussion in #1770, look for XAMPP php extensions help in StackOverflow.com
