### ISSUE TITLE
[suport] can be cut&paste in portable xamp

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1771]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:      7.0
- MySQL or MariaDB version is:    MariaDB 10.1
- OS and version is:  Guindows
- WebServer is: Xamp
- (If applicable) Installation package for the LAMP/LEMP stack is:    XAMPP

**NOTE: using a portable XAMP isntalation**

### Issue / Bug  / Question / New Feature

i not have this error, i'ts a friend of my but not have enought skills to report here and i helping

he installed PERFECTLY ospos, then tests etc,, everything are good, 

later he take the installation (due are xamp portable) and zipped to go in another machine.. works..

afeter some usage try to return to another machine from that install and ospos now dont work, it renders a shadown mask.. 

source code was not altered, only the copy paste from machine to machie, that previously works

any suggestions?

**Comment by nerv55** [comment]
same happens to me, how can I fix it?

**Comment by mckaygerhard** [comment]
as always, guindows are a waste of time.. close it
