### ISSUE TITLE
Unable to login to OSPOS

### ISSUE THREAD

**Issue by narayant** [opensourcepos/opensourcepos#1772]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is:    5.6  (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:5.7      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   Windows10   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   2.4   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:  WAMP    (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Am unable to navigate to the home page and the PHP error is as follows 

[05-Jan-2018 17:22:20 UTC] PHP Fatal error:  require(): Failed opening required 'C:\wamp\www\master\vendor\composer/../tamtamchik/namecase/src/functions.php' (include_path='.;C:\php\pear') in C:\wamp\www\master\vendor\composer\autoload_real.php on line 66

[05-Jan-2018 17:22:20 UTC] PHP Stack trace:

[05-Jan-2018 17:22:20 UTC] PHP   1. {main}() C:\wamp\www\master\public\index.php:0

[05-Jan-2018 17:22:20 UTC] PHP   2. require_once() C:\wamp\www\master\public\index.php:315

[05-Jan-2018 17:22:20 UTC] PHP   3. require_once() C:\wamp\www\master\vendor\codeigniter\framework\system\core\CodeIgniter.php:178

[05-Jan-2018 17:22:20 UTC] PHP   4. ComposerAutoloaderInit7c32d909724326970501f1087a9d5944::getLoader() C:\wamp\www\master\vendor\autoload.php:7

[05-Jan-2018 17:22:20 UTC] PHP   5. composerRequire7c32d909724326970501f1087a9d5944() C:\wamp\www\master\vendor\composer\autoload_real.php:56

**Comment by odiea** [comment]
Read the wamp wiki and also in php.ini maybe remove the the ; in front of (include_path='.;C:\php\pear')

**Comment by daN4cat** [comment]
The problem is different, you downloaded the code from master, which is a development version. Please check the README

**Comment by narayant** [comment]
Thanks. I downloaded the latest version again "opensourcepos.20170909085348.3.1.1.76a002" and am able to see the login screen. But when I login I am getting 404 error message "public/login". I have checked the httaccess file at public and it doesn't require changes I suppose 
"RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
 #RewriteRule ^(.*)$ /POS64/public/index.php?/$1 [L]"
correct me if I am wrong.

Also I changed the error logging threshold to 4 and the log file extract is provided below

INFO - 2018-01-07 19:21:21 --> Config Class Initialized
INFO - 2018-01-07 19:21:21 --> Hooks Class Initialized
DEBUG - 2018-01-07 19:21:21 --> UTF-8 Support Enabled
INFO - 2018-01-07 19:21:21 --> Utf8 Class Initialized
INFO - 2018-01-07 19:21:21 --> URI Class Initialized
DEBUG - 2018-01-07 19:21:21 --> No URI present. Default controller set.
INFO - 2018-01-07 19:21:21 --> Router Class Initialized
INFO - 2018-01-07 19:21:21 --> Output Class Initialized
INFO - 2018-01-07 19:21:21 --> Security Class Initialized
DEBUG - 2018-01-07 19:21:21 --> Global POST, GET and COOKIE data sanitized
INFO - 2018-01-07 19:21:21 --> CSRF cookie sent
INFO - 2018-01-07 19:21:21 --> Input Class Initialized
INFO - 2018-01-07 19:21:21 --> Language Class Initialized
INFO - 2018-01-07 19:21:21 --> Loader Class Initialized
INFO - 2018-01-07 19:21:21 --> Helper loaded: form_helper
INFO - 2018-01-07 19:21:21 --> Helper loaded: url_helper
INFO - 2018-01-07 19:21:21 --> Helper loaded: table_helper
INFO - 2018-01-07 19:21:21 --> Helper loaded: text_helper
INFO - 2018-01-07 19:21:21 --> Helper loaded: locale_helper
INFO - 2018-01-07 19:21:21 --> Helper loaded: html_helper
INFO - 2018-01-07 19:21:21 --> Helper loaded: download_helper
INFO - 2018-01-07 19:21:21 --> Helper loaded: directory_helper
INFO - 2018-01-07 19:21:21 --> Database Driver Class Initialized
INFO - 2018-01-07 19:21:22 --> Form Validation Class Initialized
INFO - 2018-01-07 19:21:22 --> Session: Class initialized using 'database' driver.
INFO - 2018-01-07 19:21:22 --> User Agent Class Initialized
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/pagination_lang.php
INFO - 2018-01-07 19:21:22 --> Pagination Class Initialized
DEBUG - 2018-01-07 19:21:22 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2018-01-07 19:21:22 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2018-01-07 19:21:22 --> Encryption Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Model Class Initialized
INFO - 2018-01-07 19:21:22 --> Controller Class Initialized
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/calendar_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/date_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/db_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/email_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/form_validation_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/ftp_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/imglib_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/migration_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/number_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/profiler_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/unit_test_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/english/upload_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/bootstrap_tables_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/common_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/config_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/customers_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/datepicker_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/employees_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/enum_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/error_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/form_validation_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/giftcards_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/items_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/item_kits_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/login_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/messages_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/migrate_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/module_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/receivings_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/reports_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/sales_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/suppliers_lang.php
INFO - 2018-01-07 19:21:22 --> Language file loaded: language/en-US/taxes_lang.php
INFO - 2018-01-07 14:21:22 --> File loaded: C:\wamp\www\POS64\application\views\login.php
INFO - 2018-01-07 14:21:22 --> Final output sent to browser
DEBUG - 2018-01-07 14:21:22 --> Total execution time: 0.1225
INFO - 2018-01-07 19:21:36 --> Config Class Initialized
INFO - 2018-01-07 19:21:36 --> Hooks Class Initialized
DEBUG - 2018-01-07 19:21:36 --> UTF-8 Support Enabled
INFO - 2018-01-07 19:21:36 --> Utf8 Class Initialized
INFO - 2018-01-07 19:21:36 --> URI Class Initialized
INFO - 2018-01-07 19:21:36 --> Router Class Initialized
INFO - 2018-01-07 19:21:36 --> Output Class Initialized
INFO - 2018-01-07 19:21:36 --> Security Class Initialized
DEBUG - 2018-01-07 19:21:36 --> Global POST, GET and COOKIE data sanitized
INFO - 2018-01-07 19:21:36 --> CSRF cookie sent
INFO - 2018-01-07 19:21:36 --> CSRF token verified
INFO - 2018-01-07 19:21:36 --> Input Class Initialized
INFO - 2018-01-07 19:21:36 --> Language Class Initialized
ERROR - 2018-01-07 19:21:36 --> 404 Page Not Found: Pos64/public

**Comment by daN4cat** [comment]
You need to change the .htaccess because your dir is Pos64, that's why it cannot find the page...

**Comment by daN4cat** [comment]
So do this:
```
# RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
RewriteRule ^(.*)$ /Pos64/public/index.php?/$1 [L]
```

**Comment by narayant** [comment]
Thanks for the quick response. I tried that as well, still the same error.

#RewriteRule ^(.*)$ index.php?/$1 [L]

**# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path**
RewriteRule ^(.*)$ /POS64/public/index.php?/$1 [L]

 INFO - 2018-01-07 14:44:26 --> File loaded: C:\wamp\www\POS64\application\views\login.php
INFO - 2018-01-07 14:44:26 --> Final output sent to browser
DEBUG - 2018-01-07 14:44:26 --> Total execution time: 0.0701
INFO - 2018-01-07 19:44:31 --> Config Class Initialized
INFO - 2018-01-07 19:44:31 --> Hooks Class Initialized
DEBUG - 2018-01-07 19:44:31 --> UTF-8 Support Enabled
INFO - 2018-01-07 19:44:31 --> Utf8 Class Initialized
INFO - 2018-01-07 19:44:31 --> URI Class Initialized
INFO - 2018-01-07 19:44:31 --> Router Class Initialized
INFO - 2018-01-07 19:44:31 --> Output Class Initialized
INFO - 2018-01-07 19:44:31 --> Security Class Initialized
DEBUG - 2018-01-07 19:44:31 --> Global POST, GET and COOKIE data sanitized
INFO - 2018-01-07 19:44:31 --> CSRF cookie sent
INFO - 2018-01-07 19:44:31 --> CSRF token verified
INFO - 2018-01-07 19:44:31 --> Input Class Initialized
INFO - 2018-01-07 19:44:31 --> Language Class Initialized
ERROR - 2018-01-07 19:44:31 --> 404 Page Not Found: Pos64/public

**Comment by daN4cat** [comment]
I wrote Pos64 not POS64!

**Comment by narayant** [comment]
Silly me. In fact it shouold be pos64 not even Pos64. Thanks a lot.
