### ISSUE TITLE
Missing US language lines in Reports

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#1773]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0 unstable
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) 7
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) Mariadb
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Win 10
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) XAMPP
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
ERROR - 2018-01-05 13:08:06 --> Could not find the language line "reports_confirm_delete (TBD)"
ERROR - 2018-01-05 13:08:06 --> Could not find the language line "reports_confirm_restore (TBD)"
ERROR - 2018-01-05 13:08:39 --> Could not find the language line "reports_confirm_delete (TBD)"
ERROR - 2018-01-05 13:08:39 --> Could not find the language line "reports_confirm_restore (TBD)"
 With Error reporting enabled I saw this.

**Comment by SteveIreland** [comment]
Another good catch.   MINE!  I could use an easy one.  :wink:

**Comment by SteveIreland** [comment]
Pull request submitted.

**Comment by odiea** [comment]
@SteveIreland . I found a couple more.
ERROR - 2018-01-05 13:46:22 --> Could not find the language line "items_confirm_restore (TBD)"
ERROR - 2018-01-05 13:46:26 --> Could not find the language line "items_tax_percent_number (TBD)"

**Comment by SteveIreland** [comment]
lol

**Comment by SteveIreland** [comment]
I knew it was too easy.

**Comment by odiea** [comment]
I guess you should not have showed me how to enable the normal errors.

**Comment by SteveIreland** [comment]
:-)   Nope, that was nothing but good.  You've definitely stumbled across a couple of my copy and paste errors.  Sorry about that.

**Comment by odiea** [comment]
No problem. I try to catch as many issues as i can. Now I have a new tool to work with. Thanks

**Comment by odiea** [comment]
If you get a chance can you go to www.ospos.25u.com and see if is secure enough to be a demo server?

**Comment by SteveIreland** [comment]
Absolutely not.  My webroot security tool flagged it immediately as a high risk and malicious site.

**Comment by SteveIreland** [comment]
I meant I did go there and that's when the security tool kicked it and told me to stay out!  :-)

**Comment by odiea** [comment]
I don't know why that is. It is just a Ubuntu server without a certificate. Oh well I gave it a try. Thanks

**Comment by daN4cat** [comment]
Yes I had the same issue. My ISP blocked the access to that domain flagging it like a place with virus.

**Comment by daN4cat** [comment]
Fixed and in master

**Comment by daN4cat** [comment]
Please check everything is fine

**Comment by odiea** [comment]
Looks good. Thanks

**Comment by odiea** [comment]
I downloaded the latest and tried to check all modules. Found the following errors. English US.
ERROR - 2018-01-07 04:54:02 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 04:54:09 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 04:54:17 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 04:54:34 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 04:54:42 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 04:54:59 --> Could not find the language line "giftcards_confirm_restore (TBD)"
ERROR - 2018-01-07 04:55:07 --> Could not find the language line "suppliers_confirm_restore (TBD)"
ERROR - 2018-01-07 04:55:25 --> Could not find the language line "item_kits_confirm_restore (TBD)"
ERROR - 2018-01-07 04:56:08 --> Could not find the language line "customers_confirm_restore (TBD)"
ERROR - 2018-01-07 04:56:39 --> Could not find the language line "config_lines_per_page_number (TBD)"
ERROR - 2018-01-07 04:56:40 --> Could not find the language line "config_tax_category_duplicate (TBD)"
ERROR - 2018-01-07 04:56:40 --> Could not find the language line "config_tax_category_invalid_chars (TBD)"
ERROR - 2018-01-07 04:56:40 --> Could not find the language line "config_tax_category_required (TBD)"
ERROR - 2018-01-07 04:56:40 --> Could not find the language line "config_tax_category_required (TBD)"
ERROR - 2018-01-07 04:56:40 --> Could not find the language line "config_tax_category_required (TBD)"
ERROR - 2018-01-07 04:57:12 --> Could not find the language line "expenses_categories_confirm_restore (TBD)"
ERROR - 2018-01-07 04:57:23 --> Could not find the language line "expenses_confirm_restore (TBD)"
ERROR - 2018-01-07 04:57:33 --> Could not find the language line "taxes_confirm_restore (TBD)"
ERROR - 2018-01-07 04:57:40 --> Could not find the language line "employees_confirm_restore (TBD)"
ERROR - 2018-01-07 04:57:45 --> Could not find the language line "reports_expenses (TBD)"
ERROR - 2018-01-07 04:57:45 --> Could not find the language line "receivings_stock (TBD)"
ERROR - 2018-01-07 04:57:52 --> Could not find the language line "reports_expenses (TBD)"
ERROR - 2018-01-07 04:57:52 --> Could not find the language line "receivings_stock (TBD)"

**Comment by odiea** [comment]
Here are the issues when I switched over lang to English(Great Britain)

ERROR - 2018-01-07 06:21:45 --> Could not find the language line "config_lines_per_page_number (TBD)"
ERROR - 2018-01-07 06:21:45 --> Could not find the language line "config_tax_category_duplicate (TBD)"
ERROR - 2018-01-07 06:21:45 --> Could not find the language line "config_tax_category_invalid_chars (TBD)"
ERROR - 2018-01-07 06:21:45 --> Could not find the language line "config_tax_category_required (TBD)"
ERROR - 2018-01-07 06:21:45 --> Could not find the language line "config_tax_category_required (TBD)"
ERROR - 2018-01-07 06:21:45 --> Could not find the language line "config_tax_category_required (TBD)"
ERROR - 2018-01-07 06:22:10 --> Could not find the language line "expenses_categories_confirm_restore (TBD)"
ERROR - 2018-01-07 06:22:10 --> Severity: Notice --> Undefined variable: filters C:\xampp\htdocs\ospos1718\application\views\expenses_categories\manage.php 37
ERROR - 2018-01-07 06:22:21 --> Could not find the language line "expenses_confirm_restore (TBD)"
ERROR - 2018-01-07 06:22:29 --> Could not find the language line "taxes_confirm_restore (TBD)"
ERROR - 2018-01-07 06:22:36 --> Could not find the language line "employees_confirm_restore (TBD)"
ERROR - 2018-01-07 06:22:41 --> Could not find the language line "reports_expenses (TBD)"
ERROR - 2018-01-07 06:22:41 --> Could not find the language line "receivings_stock (TBD)"
ERROR - 2018-01-07 06:22:50 --> Could not find the language line "reports_expenses (TBD)"
ERROR - 2018-01-07 06:22:50 --> Could not find the language line "receivings_stock (TBD)"
ERROR - 2018-01-07 06:23:27 --> Severity: Notice --> Undefined index: sale_status C:\xampp\htdocs\ospos1718\application\controllers\Reports.php 1096
ERROR - 2018-01-07 06:23:30 --> Could not find the language line "customers_confirm_restore (TBD)"
ERROR - 2018-01-07 06:24:11 --> Could not find the language line "item_kits_confirm_restore (TBD)"
ERROR - 2018-01-07 06:24:22 --> Could not find the language line "suppliers_confirm_restore (TBD)"
ERROR - 2018-01-07 06:24:36 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 06:24:41 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 06:24:44 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 06:24:46 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 06:24:50 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 06:24:56 --> Could not find the language line "payment_options_order (TBD)"
ERROR - 2018-01-07 06:25:17 --> Could not find the language line "giftcards_confirm_restore (TBD)"
ERROR - 2018-01-07 06:28:03 --> Could not find the language line "config_lines_per_page_number (TBD)"
ERROR - 2018-01-07 06:28:03 --> Could not find the language line "config_tax_category_duplicate (TBD)"
ERROR - 2018-01-07 06:28:03 --> Could not find the language line "config_tax_category_invalid_chars (TBD)"
ERROR - 2018-01-07 06:28:03 --> Could not find the language line "config_tax_category_required (TBD)"
ERROR - 2018-01-07 06:28:03 --> Could not find the language line "config_tax_category_required (TBD)"
ERROR - 2018-01-07 06:28:03 --> Could not find the language line "config_tax_category_required (TBD)"

**Comment by SteveIreland** [comment]
A gift that keeps giving.

**Comment by SteveIreland** [comment]
The "payment_options_order" error is due to a bug in the reset_cash_flags() in Sale_lib.php.  I'll be including a fix for that.

**Comment by daN4cat** [comment]
@odiea the following don't make sense to me:

```
ERROR - 2018-01-07 06:22:10 --> Severity: Notice --> Undefined variable: filters C:\xampp\htdocs\ospos1718\application\views\expenses_categories\manage.php 37
```
That line is commented out in master code. Uh?

```
ERROR - 2018-01-07 06:23:27 --> Severity: Notice --> Undefined index: sale_status C:\xampp\htdocs\ospos1718\application\controllers\Reports.php 1096
```
I don't get how come that this is an issue in GB and not US English. Uh?

**Comment by odiea** [comment]
I may not have tested the en-us as much as I should have.
Line 37 is this possible filter code that was left in. 	
```
	<!--<?php echo form_multiselect('filters[]', $filters, '', array('id'=>'filters', 'class'=>'selectpicker show-menu-arrow', 'data-selected-text-format'=>'count > 1', 'data-style'=>'btn-default btn-sm', 'data-width'=>'fit')); ?>-->
```
 I will restest again after the newest commit.

**Comment by daN4cat** [comment]
That needs a fix indeed. But I don't have time now and I'll be travelling the coming week, so if somebody wants to fix all the issues here is welcome otherwise we need to wait next weekend, I'm afraid.

**Comment by SteveIreland** [comment]
A pull request has been submitted. for the missing en-US entries.  Aren't the en-GB tags automatically generated once Weblate is involved?  Admittedly I'm not as familiar with the process as I should be.

**Comment by odiea** [comment]
I think @daN4cat is the automatic translator for en-GB.

**Comment by SteveIreland** [comment]
I rebuilt the pull request to include an attempt to fix the two issues that @daN4cat highlighted from your comment.  I overlooked them since I was focused on the missing language elements.

**Comment by SteveIreland** [comment]
I made a small (but critical) correction to my correction to my correction to the Detailed_sales.php

No .... I am not stuttering.

**Comment by daN4cat** [comment]
Fixed en_GB
