### ISSUE TITLE
Ospos with expense system release

### ISSUE THREAD

**Issue by dareelijah** [opensourcepos/opensourcepos#1778]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:3.1
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

I have searched in open close issues to find the answer but can't find the answer.I just want to update my ospos to the version that support expenses system. I have a pharmacy which is managed by a servant 
.ThatswhyI need that module to track all earning on it.I know that the new version of this module in releasing.So, could you guys please tell when this version is releasing. Or you have released it stable or unstable version.Thanks

**Comment by odiea** [comment]
If you look in the local install and select the unstable version. This version is really close to being released. The following is the most current unstable version. If you decide to upgrade to this release it will automatically update the database so the login page may be a little slow to open until it is fully updated.
 https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180106164332.master.ba5fa3.zip

**Comment by odiea** [comment]
It would be best if you can try it out on a local install to find any issues that may show. More php.ini ext's may need to be enabled.

**Comment by dareelijah** [comment]
Thanks @odiea I am going to try offline.
