### ISSUE TITLE
Italian language and help on manual language change

### ISSUE THREAD

**Issue by lucailvec** [opensourcepos/opensourcepos#1779]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue 

1. The link on the wiki page about the weblate page of ospos (https://github.com/opensourcepos/opensourcepos/wiki/Adding-translations) **is break** (it points at an old link on opensourcepos.org). 

2. Then the italian language can be added on http://weblate.jpeelaer.net/  ? currently i'm traslating the en_US string with the italian ones... but nothing change (i checked the language setting on localization in the setup menù) in the interface.

I modified only the language definition!

Thank you

**Comment by jekkos** [comment]
Before you can use the language a minor code change needs to be done. Did you manage to create the language itself in weblate? Last time I needed to init the files manually after the language was added as the docker setup is far from ideal to keep this server running

Installing it natively on the VPS is still on my TODO list howevre

**Comment by lucailvec** [comment]
I wish to use weblate but the italian is not listed.
If you suggest me another way i will do or i wait your modify ? (But the modify on the docker file is on weblate site docker correct ?)

**Comment by jekkos** [comment]
@lucailvec I addd italian now. Should be ready for translation. Can you let us know when done so we can consider whether this can go with 3.2 or not

**Comment by lucailvec** [comment]
@jekkos i think on sunday the translate will be completed. After your check it's possible to see the change in the head or in unstable branch or something else ?

**Comment by daN4cat** [comment]
Added Italian language in config drop down.

By the way, I doubt you can use OSPOS in Italy due to the strict fiscal rules around cash registers. But it could be that they changed the law.

**Comment by lucailvec** [comment]
There is another way to use the printer... today there are 2 printer, the first the fiscal bill and the other for the courtesy bill. With the management we can print the courtesy and then on the cash refigter the fiscal bill.
 Thank you 4 all !!

**Comment by jekkos** [comment]
@lucailvec Added your work to the repository. Can you check with latest unstable if it works fine for italian?

**Comment by daN4cat** [comment]
checked but there are many string still not translated. More work to do @lucailvec

**Comment by lucailvec** [comment]
@daN4cat OK, all words translated but few must be checked ( i'm not sure that are correct). 

Will i only `docker-compose build` to pull the update with docker and load the translation?

**Comment by mckaygerhard** [comment]
hi @jekkos  i see this issue that have similar problem like me and that's why i posted here!, i used the weblate and translated all spanish, but now see how to added missing string translations from weblate.. i cannot do it from github? due the wiki are very unclear about that and i search enought but maybe with not most exact tips for!

**Comment by lucailvec** [comment]
I think because:
- some translate are flagged with an error or "must review".
- travis failed the build
