### ISSUE TITLE
Menu display formatting issue

### ISSUE THREAD

**Issue by sqvquilter** [opensourcepos/opensourcepos#1780]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1 
- OSPOS git commit hash is:  4f5ad57
- PHP version is:  7.1.9    
- MySQL or MariaDB version is:   Mariadb 10.28   
- OS and version is:   windows 10, Linuxmint 17.3   
- WebServer is:  Apache 2.4.27    
- (If applicable) Docker installation: 
- wampserver 3.1.0

### Issue / Bug  / Question / New Feature

Menu display vertically instead of horizontal 
![image](https://user-images.githubusercontent.com/35180289/34783623-eb51b1ce-f5e0-11e7-9c5f-d98cd235b68e.png)

selecting menu item causes info to be displayed at the bottom of the screen
I am seeing this on both Linux and windows install .  Code is installed in web root 
unmodified except for encryption key value.  Result is the same in firefox and chrome browsers.
Did I miss something?
Sandy

**Comment by mckaygerhard** [comment]
its a obvios feature, all  the monitors now are widescreen and this its logically bets choice to reodering menu..

**Comment by mckaygerhard** [comment]
by the other way, when the menu are displaying in ospos vertically and some text are not formated, its a install issue. do you verified the downloaded files? follow property the install process?

**Comment by odiea** [comment]
Did you download it from the following link. If not try this one.
https://github.com/opensourcepos/opensourcepos/releases/download/3.1.1/opensourcepos.20170909085348.3.1.1.76a002.zip

**Comment by sqvquilter** [comment]
I re-downloaded from the above link and re-installed.  Now it is working.  Thank you for such a quick response.

**Comment by sqvquilter** [comment]
Thankyou
