### ISSUE TITLE
Logo dimension

### ISSUE THREAD

**Issue by dlusignan** [opensourcepos/opensourcepos#1782]
### Installation information
- OSPOS version is: 3.1.1
- OSPOS git commit hash is: no idea
- PHP version is:      7.1
- MySQL or MariaDB version is: MySQL 5.7
- OS and version is:   OS X Sierra
- WebServer is: Apache 2.4

### Question

What is the Company Logo acceptable dimension ? Can't upload my logo.

Thank you

**Comment by SteveIreland** [comment]
A quick look shows ....
max_size = 1,024K
max_width = 800px
max_height = 600px

**Comment by dlusignan** [comment]
A quick look where ?

Thank you.

**Comment by SteveIreland** [comment]
Logo constraints are set in application/controllers/Config.php.
