### ISSUE TITLE
Localization layout change in french

### ISSUE THREAD

**Issue by dlusignan** [opensourcepos/opensourcepos#1783]
### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: no idea
- PHP version is:      7.1
- MySQL or MariaDB version is:     MySQL 5.7
- OS and version is: Mac OS X Sierra
- WebServer is: Apache 2.4
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue

When in french the layout change. Is this a bug or expected behavior ?
See SC for exemple please.

T
<img width="1440" alt="home_en" src="https://user-images.githubusercontent.com/3680574/34877674-fc6e15fc-f774-11e7-9ca9-0156b765f52d.png">
<img width="1440" alt="home_fr" src="https://user-images.githubusercontent.com/3680574/34877675-fc7bdea8-f774-11e7-8f77-b97ab6c1fe5b.png">
<img width="1440" alt="tax_en" src="https://user-images.githubusercontent.com/3680574/34877676-fc86f1f8-f774-11e7-9f53-8e09881711ef.png">
<img width="1440" alt="tax_fr" src="https://user-images.githubusercontent.com/3680574/34877677-fc924f76-f774-11e7-8d56-44634b478043.png">

hank you

**Comment by odiea** [comment]
We see that the French language has not been updated lately. If you would like to help out you can read the wiki about submitting a language change.

**Comment by daN4cat** [comment]
Yes, you need to update the French translations to fit the layout.

Go to Weblate to update the translations: http://weblate.jpeelaer.net/

**Comment by daN4cat** [comment]
I see this is ongoing so I assume French translation is currently being taken care and close this.
