### ISSUE TITLE
Check Email Receipt by Default

### ISSUE THREAD

**Issue by waynebr76** [opensourcepos/opensourcepos#1784]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is:  3.1.0 - 4f5ad57
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) 7.1
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MYSQL 5.7
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Ubuntu 16.04
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Question 

Question: in the sales register when I add a payment for a customer the check boxes appear below as expected. How would I check the Email Receipt by default as i'm finding the users are forgetting to tick the box.

**Comment by odiea** [comment]
You can try editing or commenting out the following in application/libraries/sale lib.php around line 900 or higher.
```
public function clear_all()
	{
		$this->CI->session->set_userdata('sale_id', -1);
		$this->set_invoice_number_enabled(FALSE);
		$this->clear_table();
		$this->empty_cart();
		$this->clear_comment();
		//$this->clear_email_receipt();
		$this->clear_invoice_number();
		$this->clear_quote_number();
		$this->clear_sale_type();
		$this->clear_giftcard_remainder();
		$this->empty_payments();
		$this->remove_customer();
		$this->clear_cash_flags();
	}

**Comment by waynebr76** [comment]
Thanks for the quick response, this does not check it at default, it does remember the last setting but if a user uncheck's the option as a customer has asked to not be sent a receipt then the box remains unchecked.

**Comment by daN4cat** [comment]
I believe there should be a config option to decide what should be by default for printing and email: if always checked, always unchecked or remember the previous.
I will look into this because it will be useful for me too. I can see the issues coming....

**Comment by waynebr76** [comment]
Thats great thanks

**Comment by jekkos** [comment]
Still planned for 3.2 this one?

**Comment by daN4cat** [comment]
Yes, but I bumped into an issue with bower. A chartist plugin got the version renumbered in npm, so now the reference is gone and the version dependency broken. I need to find the right version again, not sure what they have done. I bet the build is broken now they changed this story about 10 days ago.

**Comment by daN4cat** [comment]
Implemented and in master.
Under Receipt tab in configuration you can set the default behaviour of the email and print check boxes in sale register.

This was indeed a required feature because an admin can prevent cashiers from unchecking the box and call you because they can't print a receipt!!

**Comment by daN4cat** [comment]
@waynebr76 please test and confirm it's fine.

**Comment by waynebr76** [comment]
Thanks I have tested this and it appears to be working
