### ISSUE TITLE
dist folder is missing

### ISSUE THREAD

**Issue by umair1191** [opensourcepos/opensourcepos#1785]
dist folder is missing from public directory. can you please upload

**Comment by odiea** [comment]
The Github version is for developers only. You need to go to local install and download either of those versions.

**Comment by mckaygerhard** [comment]
hi @umair1191 the github development model of ospos are veryt (unnecesary) complicated.. 

to solve your issue download the bintray file and the all the required files take it from.. i mean if you not want to use those "on-line" dependencies due in your stations like me there's no networking due not anybody in the planet has money to pay constant network internet, just download the github and then download the bintray file.. all of you need take it from the bintray file. here: https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files

ah, in a cybercafe a normal user cannot install git commands or any due its a "common use" machine.. so its not easy .. and no taking about mac/win related, must download more files...

**Comment by jekkos** [comment]
Question answered, will close
