### ISSUE TITLE
System folder path incorrect

### ISSUE THREAD

**Issue by CyberLynx** [opensourcepos/opensourcepos#1786]
I clone the code and upload fresh opensourcepos to my hosting, put it under subfolder named "pos". when accessing opos first time "hostname/pos/public/" i get these error message  "Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php"
I modified public/.htaccess already. but still getting the same error message.

**Comment by jekkos** [comment]
Please read the FAQ, readme first.
You should download an unstable build if you want everything to work out of the box
