### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Syedwaheed** [opensourcepos/opensourcepos#1787]
hi,
I have downloaded this system and run composer install through cmd. the application is working showing the login page but in console i m getting the above error. 
Any Assistance in this regard is highly appreciated. 
Thanks

**Comment by HassanAlyousof** [comment]
What is the error that is showing?

**Comment by HassanAlyousof** [comment]
You have to 
1 - install composer 
2 - install npm (node.js)
3 - install grunt

it may help you and i am sorry if i did not understand you

**Comment by Syedwaheed** [comment]
I have used two of the above statements first i used install composer and then install npm. I have changed the database file and everything but when i access it from localhost it gives me following error:
![capturepos](https://user-images.githubusercontent.com/14071753/34985525-08f83c1c-fad6-11e7-905d-3bf13797008d.JPG)
Thanks for your reply.

**Comment by daN4cat** [comment]
You need to run the grunt command otherwise assets are not generated.

**Comment by Syedwaheed** [comment]
But still i m facing the same issue even though i run the grunt command

**Comment by odiea** [comment]
From local install down load the current unstable zip and you won't have to deal with all this.

**Comment by daN4cat** [comment]
Run bower

**Comment by Syedwaheed** [comment]
@odiea unstable version is working fine. But stable version is having problem even though the i have run the following commands one after the other on window's cmd:
1. composer install.
2. npm install.
3.npm install grunt.
4. npm install bower.
If i enter npm run bower command i m getting following errors on command prompt.
![capture-](https://user-images.githubusercontent.com/14071753/35034362-b6aec04c-fb8f-11e7-818d-2fde5d527906.JPG)
Is it anything else should i do to make it work? Thanks for your response.

**Comment by odiea** [comment]
Under local host install are 2 versions. Stable 3.1.1 and unstable or current 3.2.0. The Github version is the current 3.2.0 if you want to jump thru all the processes you are doing now. I just opt to use the current zip.

**Comment by Syedwaheed** [comment]
@odiea  Thank you i m now using the unstable version. Its working fine but i wanted to print out the selling item on the DESKTOP receipt printer. Now its printing the receipt bill on A4 size paper. Can i change the printing options to DESKTOP receipt printer?  Thanks

**Comment by odiea** [comment]
I have no issues using an old Brother laser printer. You will need to reset the printer settings.

**Comment by Syedwaheed** [comment]
Do i have to change the printer settings configuration or i have to change the Receipt page in setting config option in menu?

**Comment by Syedwaheed** [comment]
3 options i.e module_expense,module_expenses_category,module_office are not working it gives error when user clicks on it "404 Page Not Found" Do i have to change something in controller?

**Comment by odiea** [comment]
It sounds like you have installation issues. I would suggest a clean install.

**Comment by Syedwaheed** [comment]
I have followed this link:
https://github.com/opensourcepos/opensourcepos#local-install
Anything that you want to add i m missing in unstable version. I haven't run any commands in this version. All i have done is to change the config/database.php file and put my credientials. And i havent change the encryption key. I m okay with one by default.

**Comment by daN4cat** [comment]
Check your PATH, make sure the tools are visible from command line.

**Comment by Syedwaheed** [comment]
Can you please explain about the what you mean by PATH? are you talking about environment variable and if you do . Do i have to setup path to project directory or something else?

**Comment by mckaygerhard** [comment]
PATH its the real complete place in the filesystem.. but also there's relative "PATHS" in the very hardcoded/complicated rulez in ".htaccess" files.. check it out and edited (puff) as your needs

**Comment by daN4cat** [comment]
@Syedwaheed yes environment variables. The error you had could be due to that too.

**Comment by daN4cat** [comment]
Is this sorted now?

**Comment by Syedwaheed** [comment]
I have downloaded the second last unstable file from top and i see it isnt
having those 4 option thats aint working in new unstable version. So i
decided to stick with this unstable version.
