### ISSUE TITLE
Editing bulk of items

### ISSUE THREAD

**Issue by HassanAlyousof** [opensourcepos/opensourcepos#1788]
Editing bulk of items using tax 1 is working, but once you finish it

It will not update automatically. So, you need to refresh the page and if you did not refresh the page and you clicked on edit an item the pop up model will not be good shape with a white page.

When you editing a bulk of items, you can not remove Tax 1 or Tax 2 values.

OSPOS 3.2.0

Thanks a lot

**Comment by Syedwaheed** [comment]
@HassanAlyousof Can you please tell me where m i going wrong in installation #1787.

**Comment by daN4cat** [comment]
Thanks for the issue report, however you didn't state OSPOS version.

**Comment by HassanAlyousof** [comment]
I am sorry 

OSPOS 3.2.0

**Comment by daN4cat** [comment]
Yes, I confirm that you cannot remove the tax in bulk updates. You can just change it.
How critical is this issue? Not sure... why would you remove a tax when it was allocated?

To be honest to touch I would spend time that I don't have, so if somebody else wants to help here they are welcome.

**Comment by daN4cat** [comment]
Looking into it better, this is actually the behaviour in general. Setting an empty field means no change.
It works the same for all the fields.

Therefore this is actually not a bug but a design decision, so any change needs to be applied to all the fields in the same way.

**Comment by jekkos** [comment]
This is a bug that has been there since some time. It's more of a design problem indeed and not trivial to fix.

My suggestion would be that we should prevent the user from bulk editing tax2 only by showing a warning or disabling the field if he does not want to edit field 1.
