### ISSUE TITLE
(bug) racecore problem when install in hosting provider

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1790]
### Background information
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!) Similar found but no solution provided!
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:       5.6, 7.0 (tested both)
- MySQL or MariaDB version is:    MySQL 5.5
- OS and version is:    Oracle enterprise linux el6
- WebServer is:       Apache 2.2

### Issue / Bug  / Question / New Feature

puff another problem using stable version, why if i have all requirements? i edited the very tedious htaccess files but still not get right installation now

uploading the    rquired fiels are very slow not all he people have great networling

```
INFO - 2018-01-18 19:26:22 --> Controller Class Initialized
ERROR - 2018-01-18 19:26:22 --> Severity: Error --> Call to undefined function Racecore\GATracking\Client\Adapter\socket_create() /home/vol3_7/epizy.com/epiz_20744912/htdocs/ospos/vendor/ins0/google-measurement-php-client/src/Racecore/GATracking/Client/Adapter/Socket.php 26
```

**Comment by mckaygerhard** [comment]
if provier dont enable the socket module how we can install ospos, 

why not deactivate the unnecesary tracking library.. 

its no so hard, if not socket module then deacivate the statics

**Comment by nerv55** [comment]
Confirmed.

I install OSPOS in hosting provider fare more chip that VPS.

this is log entry error:

INFO - 2018-01-18 19:26:22 --> Controller Class Initialized
ERROR - 2018-01-18 19:26:22 --> Severity: Error --> Call to undefined function Racecore\GATracking\Client\Adapter\socket_create() /home/vol3_7/epizy.com/epiz_20744912/htdocs/ospos/vendor/ins0/google-measurement-php-client/src/Racecore/GATracking/Client/Adapter/Socket.php 26

How can i solve this?

**Comment by daN4cat** [comment]
@mckaygerhard, well fix it.

**Comment by mckaygerhard** [comment]
hi @daN4cat i solved but implicts removal of tracker process and make optionally the captcha,

assuming that original project dont will do that.. close this issue, and people that wants that @nerv55  must only removed the tracker(implicts statics disable), checks(you knnow what i taking about) and captcha(curl) process in ospos..

with that i can install in hosting providers, but as README said its better use a VPS, docker or the ocean's recommendation..

so this issue can be closed or well as developers prefers, reopened and impelments
