### ISSUE TITLE
[ask] how to added a extra column to sales table and display in the reports transaction

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1791]
### Background information

- [ ] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!) **NOTE:** not same as custom columns i mean a colum in sales to select easyle by the fiscal printer in each country!
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)

### Issue / Bug  / Question / New Feature

due to fiscal possible implementation on each sale id, will be easile to have a extra column in the sales table.. 

why in sales table and not in relational extra column? due local printer implementation on each country are closelly related to the unique id of the sale.. its more easy to other see it as its.. 

also some law in specific countrys need that impementations as its.. 

**so the question its: how to show this extra column in the transactions reports?**

**Comment by januaryramadhan** [comment]
I think there is a bug. when i used php 7.1 on my server. and I have a
problem when i deploy it to heroku.

**Comment by mckaygerhard** [comment]
hi @daN4cat why the commet of @januaryramadhan was deleted? 

i implemented this extra column (for now only columns, but later i'll doit for dinamically any amount of) but the code are not in good shape, for a pull WIP code can be merged or must be all the code in good shape of quality?

**Comment by mckaygerhard** [comment]
i try to follow the https://github.com/opensourcepos/opensourcepos/wiki/Add-a-custom-field-to-the-Sales-Register wiki but are very unclear..  so made my own code.. but i still have some problems.. the code implicts a extra parameter in the save of the sales model and parse it in the sale lib in each implementation of savin the sale

still i dont know why the comment of @januaryramadhan was deleted

**Comment by daN4cat** [comment]
It was off topic

**Comment by dvidic** [comment]
I need to add item_name to receivings, tried in receivings.php, but no luck, I get extra column, but without any data in it....

**Comment by mckaygerhard** [comment]
see in the views/sales files.. i dont remenber but i think its in receipt.php or something similar

**Comment by mckaygerhard** [comment]
currently i worked this i must prepared a pull request but the code must be good to the others

**Comment by dvidic** [comment]
receipt.php is not for Receivings. receivings.php is the file. I tried items_item_name but it gives me blank data...tried item_name, same thing. It doesn't pull data from database for barcode for items on receivings...

**Comment by januaryramadhan** [comment]
It was off the topic.

**Comment by dvidic** [comment]
@mckaygerhard tnx, I solved my problem...I totally forgot about Receiving library

**Comment by mckaygerhard** [comment]
seems now the report of transactions are good for me too, but i'll not close yet due i still must merge last changes in my personal repo, so next week i'll test and made a pull

**Comment by dvidic** [comment]
Hm, barcode shows up in receivings, but after adding quantity to item, receivings crashes....

**Comment by mckaygerhard** [comment]
i was in similar problem with reports... was spagetty code , code again from start and clean and problems gone

**Comment by daN4cat** [comment]
@mckaygerhard you are breaking the LICENSE terms, you are not supposed to re-brand OSPOS software as you are doing here: https://github.com/codeigniterpower/osposweb/tree/osposweb-oficial

Stop that now or I will request GitHub to act as you are breaching the license agreement.

This is an official warning, you cannot call it VenenuX WebOsPOS. You must understand that point.

**Comment by daN4cat** [comment]
And I will write the same to GitLab.

**Comment by mckaygerhard** [comment]
umm ok i'll deleted the gitlab brand, but the problem its the disorder in this repo, users come here and get lost in the ocena of issues, just right now i discovered problems printing due lack of information..

i folk in gitlab due here other users show me more options to make ospos work in fiscal printing for other countries, also help printing.. helo here are only "read wiki" (a very out of wync wiki) or then "read README" ( a very out of date liks and "gerenric" info) .. 

so the information must be more clear.. if does not want other "perform better" that

**Comment by mckaygerhard** [comment]
@daN4cat dou you can explain me what its the specific "break" of the licensed i not rebranding nothing .. change the repo name are not rebranding due gitlab still said "fork" and i just have a "extra column" implementation in progress, all the files reamin unaltered of course .. 

so if you can explain me when have enought time.. due its very dificult to my make myselft the required changes ito my store.. in my country we have real costs.. every are calculated due the crisis..
