### ISSUE TITLE
[bug] spanish languaje have serious missing/unstranslated strings

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1793]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [ ] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [s] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted master
- OSPOS git commit hash is: 
- PHP version is:      5.6, 7.0
- MySQL or MariaDB version is:     MariaDB 10.2
- OS and version is:      VenenuX Massenkoh Linux
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)

### Issue / Bug  / Question / New Feature

theres many string un stranslated in spanish cases.. realted to newer modules (xpenses) some string in sales (quantity items) and strings in localiation

**Comment by mckaygerhard** [comment]
ah the LICENSE files have some typos too, i can help with spanish if need..

**Comment by jekkos** [comment]
OK feel free to use weblate to update translations.

**Comment by mckaygerhard** [comment]
trying all of my night but interface dont let me put any word!

**Comment by mckaygerhard** [comment]
finish spanish, please when the string will be uploaded to the source code? the weblate tool its a crap.. urls are not correct.. by example: http://*/accounts/... have an "*" ... also other things..

**Comment by mckaygerhard** [comment]
i still have to revise some strings, in practice.. but i think now its better.. now tonight i'll translate the russian missing strings.. later i'll ask for help a friend of my for greek (i only read the alphabet)

**Comment by mckaygerhard** [comment]
hi @jekkos i used the weblate and translated all spanish, but now see how to added missing string translations from weblate.. i cannot do it from github? **due the wiki are very unclear about that and i search enought** but maybe with not most exact tips for!

**Comment by daN4cat** [comment]
I see Spanish translations are submitted to Weblate and master, so all looks proceeding fine. I close.

**Comment by mckaygerhard** [comment]
the spanish translation **in weblate are compelted but in practice in the ospos are incomplete!**

i mean that in github master there's more string rather thant in weblate, same for russian ! 

**So seriusly ! you can see that string "sales_quantity_of_items " are missing in spanish files, so weblate said 100% but when go to ospos usage there's more than 30% of strings missing!!!!**

there's more than "close issue", !please!

**Comment by jekkos** [comment]
Ok so I guess new strings were added to english afterwards that are not copied to spanish or other languages. Looks like an annoying issue here as there should be some way to sync them from the base language.

**Comment by jekkos** [comment]
Ok again this seems to go back to the other problem. The string is present in weblate but not in the git repository file.

**Comment by mckaygerhard** [comment]
@jekkos if the problem its still present and its very importnat, wjhy this issue are close so lightly? puff
