### ISSUE TITLE
[bug] russian languaje serious missing/unstranslated strings more thant 60%

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1794]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [ ] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [s] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted master
- OSPOS git commit hash is: 
- PHP version is:      5.6, 7.0
- MySQL or MariaDB version is:     MariaDB 10.2
- OS and version is:      VenenuX Massenkoh Linux
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)

### Issue / Bug  / Question / New Feature

theres many string unstranslated in russian cases.. more thant 60%, 

i'm not expert but have person that can revise me.. russian native, but i need made it by pull request the weblate stupid tool want upgrade my browser that definitivelly that person will not do! (neither me)

**Comment by mckaygerhard** [comment]
i have worked in sales specially in the invoice words, in russian there's no invoice at all, so each string must be translated to context equivalent.. the rest will be remained until i check some other lectures about sales that i cannnot remember by now..

**Comment by mckaygerhard** [comment]
as happened in #1808 russian translation need to resync, there's many missing strings

**Comment by daN4cat** [comment]
Russian translations taken care.

**Comment by mckaygerhard** [comment]
this its no only to "take care", there's more strings in master rather thant in weblate! the russian interface are only 60% available to translate.. also i not speak russian but i can read and i dont undeerstant respect the farewell usage!

i mean that in github master there's more string rather thant in weblate, same for russian ! 

that's why i put "bug" here, close an issue its not just "shot" the close button!

**Comment by jekkos** [comment]
Ok yes we need a global resync of all languages. I'll try to look into that asap.

**Comment by mckaygerhard** [comment]
thanks, @jekkos and please, stopt the sensible trigering "close" button

**Comment by mckaygerhard** [comment]
hi @objecttothis, i installed the russian updates directly from weblate, but there's many strings "out of context".. still need some work? i take the work and do some corrections by my selft due i need that updates in hurry for some family friends, seems i read and understand enough russian, in any way you can revised later

**Comment by objecttothis** [comment]
@mckaygerhard I agree that there are missing translations and errors to correct.  I appreciate your work to help on the translations, but if you are not a native speaker of Russian, please don't make changes to the weblate translation.  Instead submit them as suggestions and then change the translation for your family friend on the local instance.  I have native speakers working on the Russian and Azerbaijani translation in weblate now and they will fix the problems.  If you make changes at the same time to the Russian they will need to go back and review those changes and it slows the work.  Suggestions are easier to spot and confirm or reject.

**Comment by mckaygerhard** [comment]
i put many suggestion and comments in the translations.. well not so much, only 18 strings due obviously that you said.. 

about me, not native speaking but read very well respect the context.. my friend are native and russian citicent traveling many times and confirmed my strings as i suspect

**Comment by daN4cat** [comment]
@objecttothis good luck...

**Comment by mckaygerhard** [comment]
still some translation in "wrong" context.. for russian.. especially in printing

**Comment by objecttothis** [comment]
Understood. My staff are working on it. I've asked them to finish the translation by the end of February.

**Comment by objecttothis** [comment]
@mckaygerhard please mark the strings that are wrong by checking the "needs review" checkbox without changing the translation and then clicking save. I will go over those translations with my staff to make sure they understand the context.

**Comment by mckaygerhard** [comment]
pufff.. ok ok, let me do that in the weeekend, with the person in from of the monitor, i mark not only suggestion also put some reason why he suggested.. count with that!

**Comment by mckaygerhard** [comment]
$lang["taxes_tax_code_cannot_be_deleted"] = "Сбой в удалении Налогового Кода."
i read literally and must be код налога ,   не может быть удален
не может быть 
are not aplly to things, so paste suggestion its a double working way.. waste of time, i'll ask to him to help me or make itselft the translation right?
