### ISSUE TITLE
[ask] how to remove import exquel or only import CSV or ODT files

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1796]
in many modules are the button to import from a file, how can i change to import from a odt file or CSV file? but with own separator! i mean..

**Comment by jekkos** [comment]
CSV import is standard. You'll have to start from the template anyway so why bother changing separators?

**Comment by mckaygerhard** [comment]
the problem its that if i ofert te stupid "excel" will neveer let to use that thing.. the idea its to migrate to something cheap and free of usage

**Comment by daN4cat** [comment]
CSV is free to use and any open office supports it. I don't understand the problem here....

**Comment by daN4cat** [comment]
CSV is the format we support and open standard.
