### ISSUE TITLE
[curl] make curl not error if not present, so capchat only available if present

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1797]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted
- OSPOS git commit hash is: 
- PHP version is:      5.6
- MySQL or MariaDB version is:   MariaDB 10.2
- OS and version is:    VenenuX Massenkoh linux
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)

### Issue / Bug  / Question / New Feature

now with 3.2.0 curl are need, the usage its only for capcha and sms sending.. 

we can make this requisite optional if these options are only available if are curl present and not forcing installer to do..  and made an optinal popup info when cursor are over that items with info about it

this due some hosting does not offers that.. more specifically free hostings

**Comment by jekkos** [comment]
Feel free to contribute this improvement at any time.

**Comment by mckaygerhard** [comment]
i'm working on.. dont worry

**Comment by mckaygerhard** [comment]
hi, the module checking are done in the Login class, but i note something about duplication of loading of configuration keys, so i ask in `#1872#issuecomment-370199299` https://github.com/opensourcepos/opensourcepos/issues/1872#issuecomment-370199299 about it... to autodetect modules and try to save in the db if some are availabe or not (feature)

**Comment by daN4cat** [comment]
1 year and 3 months later.... nothing happened. I close.
