### ISSUE TITLE
Multiple VAT?

### ISSUE THREAD

**Issue by klodoma** [opensourcepos/opensourcepos#1798]
Can one explain me in 2 lines how to add 2 VATs 20% and 10%, 20% being default? 

I looked at this and I am more confused than before.
https://github.com/opensourcepos/opensourcepos/wiki/Sales-Tax-by-Customer

![image](https://user-images.githubusercontent.com/944350/35189329-5ce7d290-fe48-11e7-914a-8bf42b9daad4.png)
![image](https://user-images.githubusercontent.com/944350/35189332-64df04b4-fe48-11e7-9027-06d83f8acae3.png)

**Comment by daN4cat** [comment]
The sale by Customer is only required for cases where you tax based on the customer residency. It's relevant for the US for instance.
If you have standard VAT with two rates, just untick the Customer Sale Tax support and use Tax 1 Rate and Tax 2 Rate. Also don't use the tax view from the second picture, you don't need that.
