### ISSUE TITLE
Blank screen once i log in

### ISSUE THREAD

**Issue by Jyotie** [opensourcepos/opensourcepos#1801]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.2
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) : 7.2.1
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) : 10.1.30
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)    : windows 7
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)  :  Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.1
--

- (If applicable) Docker installation:   No 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP) : XAMPP V3.2.2

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hello Sir,

I am new to this, I downloaded latest fresh copy and installed. Followed all steps mentioned in README file.
Because my db name is 'opensourcepos' and it has 'root' user, I made only this changes till now.
And then in browser i logged in. But after that a blank screen coming.
So I set 'display_errors' to 1 in index.php.

So I saw the message,

**An uncaught Exception was encountered
Type: Error
Message: Class 'Racecore\GATracking\GATracking' not found**

I gone through old issues and wiki too.
But i didnt get what is the fix for this.

Can you please help?
Thank you.

**Comment by daN4cat** [comment]
You didn't tick all the check boxes, especially one that tells you to download the code from bintray.
Go up in thos isdur and click the link and download the latest code from bintray.

The checklist is there to do not be ignored.

**Comment by Jyotie** [comment]
Okay. I will do.

**Comment by mckaygerhard** [comment]
the mayority of people ignore the checkboxes, i have a pull request that will sove that, with a more friendly template..
