### ISSUE TITLE
blockUI added to the page after login to the ospos

### ISSUE THREAD

**Issue by faruqimuneeb** [opensourcepos/opensourcepos#1803]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [yes] Reporting an issue of an unmodified OSPOS installation
- [yes] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [yes] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [yes] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [no] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [no] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [yes] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is:   5.5.9
- MySQL or MariaDB version is:    MySQL 5.5
- OS and version is:     Ubuntu 14.04 LTS
- WebServer is:   nginx   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature
I am facing the issue for my fresh installation, the problem is that after login, the page become ir-responsive and some div tags are added that block the ui, I am pasting the code of div's below.

--------------------------------------------------------------Auto added divs--------------------------------------------------
<div class="blockUI" style="display:none"></div>
<div class="blockUI blockOverlay" style="z-index: 1000; border: none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(0, 0, 0); opacity: 0.6; cursor: wait; position: fixed;"></div>
<div class="blockUI blockMsg blockPage" style="z-index:1011;display:none;position:fixed"></div>

looking for response. Thanks in advance

**Comment by mckaygerhard** [comment]
again user dont fill the checkboxes..  i have a pull request that may sove this problem that users dont fill and make "respnsive" issues!

@faruqimuneeb please edited the issue and fill the chekboxes, if not, will be closed, please read ! read!

**Comment by faruqimuneeb** [comment]
@mckaygerhard filled in the checkboxes as per your advice, I am sorry, I missed it in a hurry, sorry again for that.

**Comment by odiea** [comment]
Update to unstable 3.2.0.

**Comment by daN4cat** [comment]
... and you get what you are after.

**Comment by mckaygerhard** [comment]
hi @januaryramadhan ok well to not populate this issue, please answer me directly by email, can you extracted from my profile due answering this issue by email does not give to me your email address..

i think its not hard, i not still see it, but maybe only added a entry in the database and a icon.. we can see it later.. **i still testing the expenses related and translatiing russian** (there's many differences between russian and some concepts in ospos)

**Comment by mckaygerhard** [comment]
hey @januaryramadhan seems the 3.2.0 already have some of your requested features! as said odiea  please upgrade/install the 3.2.0 from bintray (see the README at install/requirements)

**Comment by daN4cat** [comment]
That's what we already said making less noise...

**Comment by nerv55** [comment]
** @daN4cat ** I want some modification, of course, I want to discuss with you the Hour rate and how much will be the cost. if you can send me your email to send you details of What I need. leonardosalazar@mail.ru

**Comment by daN4cat** [comment]
@nerv55 I'm afraid I don't have time at the moment.
Not sure @jekkos has time either, but up to him to answer.
Maybe @SteveIreland or @objecttothis can help? Or @odiea if he's up for the challenge?

**Comment by odiea** [comment]
@daN4cat Currently I am not up to that skill level. Nothing I can copy and paste.

**Comment by odiea** [comment]
This appears to have multiple questions or issues from different participants. I will close it.
