### ISSUE TITLE
Logging out - unintentional

### ISSUE THREAD

**Issue by marcellusmontilla** [opensourcepos/opensourcepos#1804]
### Background information
- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information
- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.6
- OS and version is: Linux
- WebServer is: Apache

### Issue / Bug  / Question / New Feature
After logging in, user is logged out after a short time. It does not happen all the time, but it does happen and sometimes in succession. There were instances I had to log-in 3 to 5 times because I was logged out after clicking a module or some button.

**Just wanted to ask what potential settings or configuration could help avoid this?**

We have made a few modifications already and we're not really sure if we changed something we shouldn't. A hint to the right direction would be much appreciated.

**Comment by daN4cat** [comment]
Try to install the original and see if you can reproduce. If not focus on your changes. Without seeing/knowing what you have customised it's difficult to say.

**Comment by daN4cat** [comment]
No news, I assume this is not relevant anymore and therefore close.
