### ISSUE TITLE
[ask] Packaging / delivery costs

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1805]
Hello.
In warehouse there's a often situation on receiving items that you get invoice from supplier and there are on the invoice item and shipping/packaging costs. These costs are equaly dispersed on all items on invoice. When the items are received I need to add them in plus add shipping/costs that are on original invoice. 
For example: I buy 10 HDD's (100$ each) from supplier. Supplier gives me invoice with 10 HDD and adds 20$ for packaging/shipping on invoice. This 20$ is dispersed equaly on all HDD's, so they cost me 102$ each, as these costs add value to HDD on items received. 
Is there a possibilty to do this in OSPOS?

Many tnx.

**Comment by HassanAlyousof** [comment]
I think for the main time, you can add it as expenses or you can change the calculate average price in configuration module

**Comment by dvidic** [comment]
Where can I add expenses?

**Comment by odiea** [comment]
In local install download the unstable bintray version. It contains the Expenses module.

**Comment by odiea** [comment]
Have you checked employee permissions to see if it is available in there?

**Comment by mckaygerhard** [comment]
no i confirmed there's no expense module, i double check again later, i have some sources in another machien that have it! but are not same as master.. i dont remenber where i take it

**Comment by dvidic** [comment]
I tried clean install 3.2.0 now and now I  have "The installation is not correct, check your php.ini file." error. 
Where is newest version (unstable) available?

**Comment by odiea** [comment]
$keys = array('bcmath', 'intl', 'gd', 'sockets', 'openssl', 'mbstring', 'curl'); are the ext that are now needed.

**Comment by odiea** [comment]
PHP version 5.6 or newer is recommended (PHP 7.x is supported). Please note that PHP needs to have php-gd, php-bcmath, php-intl, php-sockets, php-openssl, php-mbstring and php-curl installed and enabled. Under server requirements.

**Comment by odiea** [comment]
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180119115347.master.02f873.zip
Is the latest but you will probably get the same php errors on Login.

**Comment by dvidic** [comment]
TNX I solved installation error, openssl was the issue. Now I have expenses, but it is still unclear how to add expenses on receiving items and disperse that expense equaly on all received items?

**Comment by odiea** [comment]
Ya. That will not fix the issue you are having. It will jut show that as an Expense.

**Comment by dvidic** [comment]
Is there a way to add an item which will add value to other items in receiving invoice? Fo example:
item 1 value: 10 (new value with calculated expense: 10+30/3)
item 2 value: 10 (new value with calculated expense: 10+30/3)
item 3 value : 10 (new value with calculated expense: 10+30/3)
expense item: 30 (new value with calculated expense: 10+30/3)
total sum: 60

**Comment by odiea** [comment]
Currently in OSPOS if you chose Calculate average price it will update your entire stock not just the new Items. So it does not have the feature you are asking for.

**Comment by dvidic** [comment]
That's quiet a problem. Everyone who has warehouse/stock must enter receiving items with calculated expenses added to item values. Delivery/packing adds final value to item. There should be default value named Packaging costs which is only for receiving items and works as I wrote. Without this, accounting is not correct.

**Comment by daN4cat** [comment]
@dvidic OSPOS is not an accounting system, it cannot possibly contemplate all the use cases of this world unless people contribute the feature.
I can think of other cases like shopping bag cost, shipping cost, delivery man fee, handling fee, etc.
How many more that I am not aware of?

And for your case what would you do with the cost if today the shipping cost is 30 but in two weeks time you restock but the agent delivers it passing by at 0 cost or less cost? What would you do?
You see, many possibilities.

The best is to keep it simple at the moment until we find a generic way to deal with cost additions and sale additions. Maybe in a new future version, I hope somebody will help.

**Comment by dvidic** [comment]
This feature I'm talking about is marginal cost and it is normal behavior when you receive items in stock...delivery/packing cost adds value to items according to their net value. 
I'm aware what OSPOS is, and it's not suppose to do accounting, but item receiving is useless for most of us in EU without this.
Please, don't be mad at me, I'm just suggesting. I looked at the code, and cannot find how to add just this one field named "incoming cost" which would add value to all items at receiving....

**Comment by mckaygerhard** [comment]
hi i have an idea, we can take two type of costs, incoming inversions costs and resto so normal dayly costs.. only the second are expenses at all, so we can provide based on that flag two types of reports and emulated a mini accounting

**Comment by mckaygerhard** [comment]
we added to the table a new field, type, and well for now choose for cost the type 1 and for expenses the type 2, then in the reports, only will afected by the type 1 in the amounts

i made a rudimentary expense application for a friend of my.. working as i said
