### ISSUE TITLE
Error 500 in Store Config after upgrading to Code Igniter 3.1.7

### ISSUE THREAD

**Issue by briantan1979** [opensourcepos/opensourcepos#1806]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is:  
- PHP version is:  7.1
- MySQL or MariaDB version is: mysql V 14.14 Distrib 5.7.21
- OS and version is:  Ubuntu 16.04 LTS
- WebServer is: Apache 2.4.18 (Ubuntu)
- (If applicable) Docker installation:  N.A.
- (If applicable) Installation package for the LAMP/LEMP stack is:  LAMP

### Issue / Bug  / Question / New Feature

Manually installed using the release zip file. Unzipped, installed and everything works fine.
However, when I download the default composer.json into the application folder and did a composer update, the CodeIgniter version is upgraded to V 3.1.7 from V 3.1.5 previously.

Everything else still works fine except for the Store Config module which would end up reporting an error 500 when navigated to.

Downgrading CodeIgniter back to 3.1.5 would fix the problem, however, please either update the composer.json to restrict CodeIgniter to v 3.1.5 or fix any compatibility issue with v 3.1.7.

Thanks in advance.

**Comment by daN4cat** [comment]
Use 3.2.0 because we fixed that issue with the latest release (hopefully soon to be released).
We won't fix it in 3.1.1 so please stick to CI 3.1.5.
