### ISSUE TITLE
Installing OSPOS on a sub-domain 

### ISSUE THREAD

**Issue by ebenezery4** [opensourcepos/opensourcepos#1807]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 
- PHP version is:  5.6    (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:  mysql     (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:  ubuntu    (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:  apache 2.4    (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Hello i try to install OSPOS on a live server though am very familiar with the installation on a local server but this time i want to deploy it on a live server. Though am deploying it on a sub domain and i dont know if am missing a configuration .

Here is what i did:
I set up a sub domain .........retail.getpaid4learn.com
i set up a directory on the sub domain which i named invoice and i uploaded the OSPOS files into the directory 
i point my sub domain to the url to retail.getpaid4learn.com/public

and i made all the configuration on the database.php

and i try to access the app via the url but all i got is internal server error

Kindly point me  to the right direction if am missing out

**Comment by mckaygerhard** [comment]
try6 tofind out in your hosting cpanel or whatever, the error log, this its a very famous common problem due the rewrite rules (you are in a subdirectory) and base url setup, without that error log we cannot do or recommend any.. also its recommended that the directory application/log of the ospos are writable and see if there any log file there..

**Comment by ebenezery4** [comment]
@mckaygerhard Thanks for the response i check the application/log i could not find any thing there rather than the index.html fileand also i check the error log file on my cpanel and there were no error associated to OSPOS at all. that is where i got confused and dont know what else to do

**Comment by mckaygerhard** [comment]
well i have some maybe bad new .. due the error "500 internal server" its only see in the webserver log files, umm i dont remenber how but there's a way or some way to enable the log error in hosting cpanel try to ask to provider support.., about the application/log check permission and re-run

**Comment by mckaygerhard** [comment]
more bad news ..also i advertise to you, i try to setup ospos in many web hostings and mayority does not have enought requeriments to deploy ospos.. specially due mcrypt and soxket enabled in php..  

the error "500 internal server" its only see in the webserver log files, umm i dont remenber how but there's a way or some way to enable the log error in hosting cpanel try to ask to provider support.., about the application/log check permission and re-run

**Comment by ebenezery4** [comment]
ok let me run more check on that... thaks

**Comment by ebenezery4** [comment]
Wao! even the hosting company don't know what to do (ipage).....Should i conclude that the application can't run on a live server or there is a misconfiguration some where.....

**Comment by mckaygerhard** [comment]
yeah, i noted in many hosting, the socket php module are "suprimed" from users configuration.. as many others.. due "security" implications.. 

that's why in the README ospos developers recomended ocean's.. sorry but you must use a VPS even a hosting,, where you can deploy in docker or in virtual machine container

so this issue can be closed...

**Comment by mckaygerhard** [comment]
see #1790 issue, are happened to me .. @ebenezery4  yeah, i noted in many hosting, the socket php module are "suprimed" from users configuration.. as many others.. due "security" implications..

that's why in the README ospos developers recomended ocean's.. sorry but you must use a VPS even a hosting,, where you can deploy in docker or in virtual machine container

so this issue can be closed...

**Comment by ebenezery4** [comment]
but before the issue got closed i want to try it like this but dont know
how it will turned out but i want to give it a try i will install the
application on a local server and put the database in a remote server if
that can work though i dont know if i will get any issue with that.

**Comment by mckaygerhard** [comment]
that's can be done, easy as configure the database with remote credentials..
