### ISSUE TITLE
Azerbaijani Translation in Weblate not in Master

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1808]
### Background information
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: Latest Master files
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature
It appears that the data in the Master is stale for the Azerbaijani translation.  I haven't pulled that down from Weblate before and am not even sure I have permissions to do so.  If the latest Russian in Weblate could also be pulled down that would be helpful for 3.2.0.

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by mckaygerhard** [comment]
yeah, the russian translation of ospos are very bad state, many translations are incorrect, i try to do some work but its very hard to make some equivalent due by example, a invoice have not equivalent in russain behaviour..

**Comment by objecttothis** [comment]
@mckaygerhard yes, Russian needs updating.  I have a native speaker working on it.  Forgive me if you are a native Russian speaker, but please be careful about making changes to Weblate if you are not a native speaker of the language.  Invoice in Russian is фактура in the context that it gets used in ospos.

**Comment by mckaygerhard** [comment]
i update some strings but i do thanks to help of someone else, that's correct me, but i notes that i cannot insert new missing strings on russian either spanish, 

i have an idea, if you dessire, i can let in check and make comments in those that i not have clarelly the conext and you only pay attention those most difficults

i'm native reader only, no i'm not native rusain speaker, i not speak well either write (its very confusing the specific russian alphabet respect the others cirilic derivates)

**Comment by mckaygerhard** [comment]
hey "фактура" , that's all, very plain?

**Comment by mckaygerhard** [comment]
umm фактура sounds like spanish "factura" are you sure?

**Comment by objecttothis** [comment]
yes, very sure.  We use it every day in our bookstore here.  Yes, it is the same root word as many other languages.

**Comment by mckaygerhard** [comment]
umm so i guest so then i'm over in this section.. i think you are more correct sorry i htinks that russian was abandoned.. so that's why i post some translations in last week

**Comment by objecttothis** [comment]
no problem.  My recommendation is that when you see a problem with a language that isn't your first language make the change by using the suggestion feature in weblate and it can then be reviewed by a native speaker.   Thank you for your contributions to the translations.

**Comment by mckaygerhard** [comment]
yeah, done some comments and suggestions based on russian xperience.. (well i was thinking was abandoned)

but still i have a problem with missing spanish strings.. how i can do with it?

**Comment by jekkos** [comment]
@objecttothis so you mean that weblate has more data then what is in git?

**Comment by objecttothis** [comment]
@jekkos correct.  For example if you look at the bootstrap table in weblate for AZ and then look at it on the master you'll see that it's populated in weblate but empty in the master.  Are languages automatically populated from weblate or do they need to be manually brought down?

**Comment by objecttothis** [comment]
Also the naming for the translation in weblate is set to "az_AZ (generated)" but the convention we have been using means that it should be listed as "Azerbaijani (North)".  The same with "Arabic (ar_EG)" which by convention should be "Arabic (Egypt)"

**Comment by objecttothis** [comment]
In case you are curious, there is a South Azerbaijani spoken in Iran using Persian script and with some differences in vocabulary.

**Comment by daN4cat** [comment]
Is this still an issue or the latest drops from Weblate fixed it?

**Comment by objecttothis** [comment]
Yup, still an issue.  If you look at the bootstrap table in the master for Azerbaijani, you'll see that all the translations are just empty quotes, but weblate shows them as populated.  Question:  The readme.md has the translate site at http://weblate.jpeelaer.net/ but my understanding is that we are using translate.opensourcepos.org so are these two different instances of weblate or is it the same instance with a DNS entry alias?  If they are two instances, this could potentially be what's causing the problem.

**Comment by daN4cat** [comment]
Same.

**Comment by jekkos** [comment]
Yep it's the same instance.. it's a weblate sync issue. I guess I'll need to dive into the code to have it resolved once and for all.

**Comment by mckaygerhard** [comment]
i still have problems with "that" weblate tool, as on #1794  and #1793 i clone fresh ospos and use it, and still have many string missing, but in weblate the project in spanish said 100% translated.. but see that the "close" button have a very sensible trigger...

**Comment by jekkos** [comment]
@objecttothis some missing strings are available for translation now..

**Comment by daN4cat** [comment]
@objecttothis, please complete the translations so we can have everything in 3.2.0.
I close this issue as it's now an ongoing job to keep up with the translations.

**Comment by objecttothis** [comment]
Super, my staff have been told to finish by the end of February.
