### ISSUE TITLE
Please add Vietnamese translation

### ISSUE THREAD

**Issue by vnwildman** [opensourcepos/opensourcepos#1809]
I can't see Vietnamese language in Weblate. Please add it.
Thanks,

**Comment by jekkos** [comment]
@vnwildman should be done. Let me know when translation is there.

**Comment by jekkos** [comment]
@vnwildman I saw you already started to translate a couple of components. However the files weren't properly created yet. They are now.

You should go through these again and click revert + save to get the work back, as it couldn't be saved yet properly.

**Comment by jekkos** [comment]
I have started doing this for reports already, not sure which others you were working on?

**Comment by vnwildman** [comment]
Still missing module_lang.php in Weblate.

**Comment by jekkos** [comment]
@vnwildman good point. I added the module in all languages. Can you check?

**Comment by daN4cat** [comment]
I guess after the last resync more translations are available.
However my last commit, odiea's one and the forthcoming from Steve will introduce more strings to be translated.

Maybe we can close this issue now?

**Comment by vnwildman** [comment]
I've just updated. You maybe close this issue now?

**Comment by daN4cat** [comment]
Good, I close as I see the translation workflow to work fine.
Thanks for the contribution.
