### ISSUE TITLE
The installation is not ..... check php.ini file AND Custom field

### ISSUE THREAD

**Issue by lucailvec** [opensourcepos/opensourcepos#1812]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)

## 1 Issue

The build and run are doesn't give me any error but when sign in on localhost:80 or anyone else ip the browser give me the famous "The installation is not correct, check your php.ini file".

### Step to reproduce issue 1

-  Docker installation: Docker-compose build; docker-compose up 
-  All file from latest commit on master branch of git

## 2 Issue
From modified version of ospos 3.2.0 when i follow the [wiki](https://github.com/opensourcepos/opensourcepos/wiki/Add-a-custom-field-to-the-Sales-Register) the browse interface work properly except i cannot enter in the config menù because HTTP ERROR 500. I add 3 new custom fields so the sales register and Items menù show me the updated header.

### Step to reproduce issue 2

-  Docker installation: Docker-compose build; docker-compose up are from [Issue](https://github.com/opensourcepos/opensourcepos/issues/1592) and use the dockerfile from the opensourcepos.20170909085348.3.1.1.76a002 and the application and other folder of the 
-  All file from latest commit on master branch of git

How can i solve those problem ? 
Look that the issue 2 had required that i solve issue 1.

**Comment by mckaygerhard** [comment]
yeah very famous, its very strange that a very famouos error does not have solved

please enable write permission on application/log directory and then up the level log to 4 in the application/config/config.php file and later see the php file under log directory to see what are the errors.. also please see the webserver error log file

**Comment by lucailvec** [comment]
Tomorrow i will try to connect to the container and enable log... or modify the container/dockerfile setting to reproduce the chmod.

For the second issue any suggest @mckaygerhard ?

**Comment by mckaygerhard** [comment]
same process, we need to see the 500 cause of error, only availabel inthe webserver log.. in a normal instalation (due i hate dockers, but praised that are very usefully) those causes could be in the /var/log/apache2/error.log as example if use apache2

**Comment by daN4cat** [comment]
@lucailvec have you sorted out with your issue?

**Comment by jekkos** [comment]
Did you use the bintray version for this? Otherwise you need more steps to do a full build first.

**Comment by mckaygerhard** [comment]
well its not easy triyin to understang that "very generic" message, i studi the code, i'm not expert in development but i see the line with and array that check modules, 

please if i check each modulo at least provide the message that what module are fail..

also some modules only are for non-ospos functionality related like curl..  and socket

**Comment by daN4cat** [comment]
Read the error log file under dist or public  (sorry can't remember from the top of my head) and the error message there will tell you that info.

**Comment by daN4cat** [comment]
I don't want to print anything at login page because it will expose detail of your web setup. It's a security point.

**Comment by mckaygerhard** [comment]
umm ok you have right , but then if there a first installation it makes sense! i mean, post a semaphore flag in db that tell to system its not complete in production mode, while are under this, all need information will show to front end.. until this flag are out and set "installed"

i think this its not so hard to do.. not know how right now.. due i learning about ospos php files and i dont know nothing about jquery (i hate it)

**Comment by daN4cat** [comment]
No news from the submitter. I close.
