### ISSUE TITLE
Calc avg. Price (Receiving) - wrong calculation

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1813]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is:     7.1
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:     Windows 10
- WebServer is:     Apache 2.4
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

It looks like **Calc avg. Price (Receiving)** is not working properly. I had 16 items with cost price 151.37, and then received 6 more with cost price 205.59. OSPOS is now giving cost price 166 instead od 178.78. How this function actually works or I'm missing something?

**Comment by odiea** [comment]
The following is the method I found to use from the Internet. The calculation appears to be correct.

151.37  
16 ×
--------------------------
2,421.92 =
 
205.59  
6 ×
--------------------------
1,233.54 =
 
1,233.54  
2,421.92 +
--------------------------
3,655.46 =
 
22 ÷
--------------------------
166.157272727272727 =

**Comment by dvidic** [comment]
Yes, you're right, I used wrong method for arithmetic mean. TNX!

**Comment by dvidic** [comment]
I solved my own proposition->
Just add <th style="width: 10%;"><?php echo $this->lang->line('items_cost_price'); ?></th>  to register.php and of course: <td><?php echo form_input(array('name'=>'items_cost_price', 'class'=>'form-control input-sm', 'value'=>to_currency_no_money($item['cost_price']), 'tabindex'=>++$tabindex));?></td>
