### ISSUE TITLE
The for attribute in the label for emailing a receipt at checkout has a dash instead of a underscore

### ISSUE THREAD

**Issue by TazTheManiac** [opensourcepos/opensourcepos#1814]
### Background information
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: a3bf1d7

### Issue
As the title says.  
The for attribute in the label for emailing a receipt at checkout has a dash instead of a underscore, making it so that you can't click the label to check the box.  
```<label for="email-receipt" class="control-label checkbox">```.

**Comment by odiea** [comment]
Did you change it from a dash to an underscore? Did this correct your issue?

**Comment by TazTheManiac** [comment]
@odiea Changing to an underscore works. But the issue is still there in the code you pasted, in the label opening tag, the for attribute still has a dash.

**Comment by odiea** [comment]
Thanks for the tip. If one of the developers thinks this is an issue They would probably change it. Currently I have no issues with the dash and not the underscore being used.

**Comment by TazTheManiac** [comment]
No it is not an issue that brakes the system, i just figured it would be a little QOL improvement.

**Comment by daN4cat** [comment]
Good catch!

**Comment by daN4cat** [comment]
Fixed and in master. Thank you for spotting this issue.

**Comment by TazTheManiac** [comment]
No problem, keep up the good work!
