### ISSUE TITLE
No receipt display on non-taxable sale

### ISSUE THREAD

**Issue by sqvquilter** [opensourcepos/opensourcepos#1829]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1 and 3.2.0
- OSPOS git commit hash is: 4f5ad57 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) mysql 5.7.19
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) windows 10
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) apache 2.4.27
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP) wamp64

### Issue / Bug  / Question / New Feature

When item sold is not taxable pressing the complete button  yields blank screen - no sales receipt is displayed.
Expected behavior would be to show sales receipt.
Attached are expected and actual results.
![expectedsale](https://user-images.githubusercontent.com/35180289/36105333-33058cfa-0fc9-11e8-8a07-502a228561b2.JPG)
![expectedcomplete](https://user-images.githubusercontent.com/35180289/36105335-3519b336-0fc9-11e8-9c03-7a269729c603.JPG)
![errorsale](https://user-images.githubusercontent.com/35180289/36105338-36f79dbc-0fc9-11e8-80ad-dcc9ba121fec.JPG)
![errorcomplete](https://user-images.githubusercontent.com/35180289/36105342-38f8bf38-0fc9-11e8-8051-217b21afc7d2.JPG)

**Comment by odiea** [comment]
I do not think I have ever seen the ? after sales tax but under normal conditions I can not reproduce this issue.

![2018-02-12 08_56_46-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/36105943-1d8d87d8-0fd3-11e8-99b8-4d406792a662.png)

**Comment by sqvquilter** [comment]
I was actually not inquiring about the ?.  When I have item on the sale that has no tax I do not get the receipt when I press the complete button.  In California Labor is not taxable.  Adding this to sale causes  completion to fail.

**Comment by odiea** [comment]
That may be what is causing your issue.

**Comment by odiea** [comment]
This appears to be a modified version with issues I will close.

**Comment by mckaygerhard** [comment]
@odiea if ospos will never fit all the countries requeriments and must be modified for ? WHERE WE CAN ASK OR REPORTS ABOUT THE FITS?

i mean with respect, obviously ospos do not fit all the users requeriments, if there a opensource proyect and users NEED to modify to fit their requeriments, who we can do that if there's no place for that?

its a great software and made great work, but by example In California Labor its not taxable, and In venezuela there's 3 types of tax, and that depends of the final amount of sale..

all of this make obvious the ospos must be ajust to fit the usage of...

**Comment by odiea** [comment]
Yes but if the modifications are creating issues we can not be responsible for that.

**Comment by sqvquilter** [comment]
This code was not modified.  I have re- installed and re-tested.  I will post the results in a new item since this one has been closed.

**Comment by odiea** [comment]
I reopened it. Let us know how it turns out. I believe the ? is giving the no print issue. Try removing it and see what happens in register and receipt.
