### ISSUE TITLE
Item search / adding by name

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1833]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is:      7.1
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      Windows 10
- WebServer is:      Apache 2.4

###  Bug 

Search items by name in sale register don't work, at least for me. It shows deleted items only when I try search by name. Adding by item# works, but not by name, only if item is deleted, but then it cannot be added ...

**Comment by odiea** [comment]
Again no issues here.
1. Deleted Items will not show in the Register. Unless you modified the code.
2. If you search by Item id  it will fail to add to the sale if it was deleted. Unless you modified the code.
3. In name search from Register you need to select the Item you need from the drop down list. Unless you modified the code.

**Comment by dvidic** [comment]
Weird. Where's the code which controls this feature located?

**Comment by odiea** [comment]
My suggestion would be to download the current unstable version. Attach your current database to it and see if you are still getting this issue.
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180212074123.master.9caf22.zip

**Comment by daN4cat** [comment]
So why do you delete them then? If you can restock don't delete. As simple as that...
