### ISSUE TITLE
Item receiving

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1835]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      Windows 10
- WebServer is:    Apache 2.4
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug
Am I missing something how receiving works or is this a bug.

I have item 200 of "Brtve SP" already in stock 

![receiving1](https://user-images.githubusercontent.com/35903927/36207657-e56bb5c6-1196-11e8-9ad3-8f75d731b0ab.png)

and I receive another 100 pieces and OSPOS gives me this number...

![receiving2](https://user-images.githubusercontent.com/35903927/36207664-ea9ae328-1196-11e8-930a-d092cde403b9.png)

**Comment by odiea** [comment]
I don't see any math problems here.

![2018-02-14 07_14_20-inbox - oagnew netscape net - mozilla thunderbird](https://user-images.githubusercontent.com/10962177/36208713-f3b944b2-1156-11e8-9aa9-e9a9c25d4426.png)

**Comment by dvidic** [comment]
Thank You for replying.
Let's do this one more time...
I have **200 pieces** of item with price **37,62 per item** on stock. That gives me total of **7524 money**.
Then I **add** another **100** items with the same price of **37,62** to stock. Thet will be total of **11286 money.** 
Math: **200*37,62+100*37,62**. Receiving is _ADDING_, not multiplying. 
If You divide 752400 with 300 you now get 2508 per item. So, this is wrong. Or there's some other way to add items to stock aka receiving I don't know about.

TNX

**Comment by odiea** [comment]
Receivings does not use your current Inventory. When you input Inventory into receivings it is just updating the current inventory that you currently entered. Your 200 is a multiplier. If you choose to use that as a single item then replace the 200 with 1.

**Comment by odiea** [comment]
You sell a 6 pack of soda. You would enter the cost and receiving qty as 1
You sell the cans separately divide the cost by the qty. Then you would put 6 in the receivings qty.

**Comment by dvidic** [comment]
I have to apologize for this one....I did'nt realize that receiving quantity was the same as stock value, that's why OSPOS multiplied it.... My BAD and once again, I apologize for this.

Also, I noticed that on receivings printout, there's no item number, only item name. Is it possible to add item number/barcode?

TNX
