### ISSUE TITLE
No receipt on non-taxable sale  Item #1829

### ISSUE THREAD

**Issue by sqvquilter** [opensourcepos/opensourcepos#1837]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) 7.1.9
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)  MySQL 5.7.19
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Windows 10
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4.27
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

This is the same as item #1829.  That issue was closed with a comment about modified code.  The code has not been modified.  I reinstalled a clean version and got the same results. 
I generally like what I see with OSPOS and would like to use unmodified code.  Modifying the code would complicate taking advantage of any future enhancements that are made, so I would prefer to not modify the code.  That said many businesses need to use both taxable and non-taxable items.  The only way I have been able to make this work is to put the sales tax on each individual item.  While this works it is not as desirable as being able to set the sales tax in one place. Setting the sales tax for each item is asking for data entry errors and thus tax issues.  Please reconsider this issue as the code  is unmodified.

When item sold is not taxable pressing the complete button yields blank screen - no sales receipt is displayed. Configurations for taxes is 
![taxcode](https://user-images.githubusercontent.com/35180289/36225484-ae22a8ac-117f-11e8-875f-294f2298834d.JPG)
![taxconfig](https://user-images.githubusercontent.com/35180289/36225491-b2d473d0-117f-11e8-9c8c-11d3198db58a.JPG)
 Taxable item setup
![taxitem](https://user-images.githubusercontent.com/35180289/36225524-c9c7033c-117f-11e8-9f39-c3c969c7e9ce.JPG)
Non taxable item is
![nontaxitem](https://user-images.githubusercontent.com/35180289/36225538-dcca3e86-117f-11e8-8d5f-0cf6461f700a.JPG)

Expected behavior would be to show sales receipt like taxable sale.
![expectedsale](https://user-images.githubusercontent.com/35180289/36226102-b3bfaf38-1181-11e8-8e4c-12167b17d583.JPG)
![expectedcomplete](https://user-images.githubusercontent.com/35180289/36226105-b7c4479c-1181-11e8-96bb-575f5782b21c.JPG)
Actual result  No receipt displayed and sale is not complete.
![errorsale](https://user-images.githubusercontent.com/35180289/36226125-ca8bf29e-1181-11e8-814c-8fdffde1a04d.JPG)
![errorcomplete](https://user-images.githubusercontent.com/35180289/36226130-cd9eb980-1181-11e8-9de7-51d3e939e779.JPG)

**Comment by odiea** [comment]
Thank's for clarifying this issue. @SteveIreland got any ideas?

**Comment by odiea** [comment]
Try the following to see if it changes anything.

![2018-02-15 10_51_15-open source point of sale _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/36272362-9327abc8-123e-11e8-8f55-1c7c169283a1.png)

and just have a separate tax.

![2018-02-15 10_51_47-open source point of sale _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/36272428-be466c22-123e-11e8-8876-244fe5af1cdc.png)

**Comment by daN4cat** [comment]
This is a pure US case, no help from my side I'm afraid.

I hope @odiea suggestion helps, if not @SteveIreland needs to look into this.

**Comment by sqvquilter** [comment]
This issue has been resolved.  It was a set-up issue - Thank you for your assistance
