### ISSUE TITLE
Distorted Icons and Homepage

### ISSUE THREAD

**Issue by gfo2007** [opensourcepos/opensourcepos#1839]
Hi,
I just installed opensourcepos and after logging in, my icons and homepage looks totally distorted. The Google chrome developer tools shows the following error.
![ospos error 4](https://user-images.githubusercontent.com/14317420/36254346-b87b8774-1242-11e8-8a72-22f15a0b25ca.PNG)
![ospos error 5](https://user-images.githubusercontent.com/14317420/36254347-b8afb51c-1242-11e8-94a3-e5812ff3061f.PNG)

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by mckaygerhard** [comment]
...and the issue list will grow up always of many many similar isssues until the proposed changes by me are not filledm what changes, well i reponse same : search the issues..

@gfo2007 must checks following:
1. do you installed a downloaded github repository of from bintray redist?
2. what wiki or instruction do you follow? to install?

**Comment by gfo2007** [comment]
Hi,
1. I installed from a downloaded github repository.
2. I followed the wiki instruction for installing opensourcepos on wamp on windows.

**Comment by mckaygerhard** [comment]
that's the problem, for sure you are a guindows user that never read.. the things that are usefully are not just "click click" please, always read the files first..

i'll explain to you, the github repo does not have "as is" the dist files so all the 404 are not found

if you want something "lasted" close to the github source use the bintray, please READ the README and follow the instruction, of course i understand there0s no clear instructions but you can claim that ..

umm i think i'll will take the iniciative to made a alternate wiki for most novice users so developers in guthub of ospos doe snot disturb with minor issues and novice users will be happy with clean instructions.. due all of us are novice in some point of life

**Comment by mckaygerhard** [comment]
https://github.com/opensourcepos/opensourcepos/wiki here there's some procedures to install in some flavors like WAMP (guindows), LAMP(ubuntu with nginx) and Dockers or raberryPI, and if you use apache there's no dificult way.. just put in root htdocs and populate the db

**Comment by gfo2007** [comment]
Thanks. I have tried the bintray one and it's working perfectly. Thanks for your time.
