### ISSUE TITLE
[bug] spanish languaje have serious missing/unstranslated string

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1841]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [ ] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted master
- OSPOS git commit hash is: 
- PHP version is:      5.6, 7.0
- MySQL or MariaDB version is:     MariaDB 10.2
- OS and version is:      VenenuX Massenkoh Linux
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)

### Issue / Bug  / Question / New Feature

theres many string un stranslated in spanish cases.. realted to newer modules (xpenses) some string in sales (quantity items) and strings in localiation

i used the weblate and translated all spanish,the wiki does not said nothing about and the strings STILL ARE MISSING!

**i open new issue due the #1793 was closed in a random shot, but the ospos interface still have many missing untranslated strings, but the weblate said 100% translated!**

**Comment by jekkos** [comment]
Ok indeed I need to do a round trip adding non existant translation strings to other languages again. Let me check that one

**Comment by jekkos** [comment]
@mckaygerhard missing strings are present now. Can you add the translations so I can integrate?

**Comment by mckaygerhard** [comment]
ok please do not TRIGGER THE "CLOSE" button arbirtrary until i confirmed fixed right?

**Comment by mckaygerhard** [comment]
the translation are 100% done now i must tests if there still missing strings.. russianhave many unstranslted and now empty strings..

when tests donne i'll close or post feedback here

**Comment by mckaygerhard** [comment]
@jekkos  i have a problem i dont understand how/what its the correct work for "order" format in the config printing option, there's two options "Default" and "Order", what that means? a "order format" will be a completed sale and receipt¡?

**Comment by daN4cat** [comment]
We can close this soon because all the translations are pushed to GitHub when needed.
Probably @jekkos will need to do a refresh again this week to make sure all the strings are in WebLate.
But that's business as usual now and applies to all the languages.

**Comment by daN4cat** [comment]
I've just checked, the new translations added today are visible in Weblate.
We can close this.
