### ISSUE TITLE
Item Return showing error "Item add to Receivings failed"

### ISSUE THREAD

**Issue by VJ141** [opensourcepos/opensourcepos#1843]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1 
- OSPOS git commit hash is:  4f5ad57
- PHP version is:   7.0   (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:   MySQL 5.7.21    (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is: LAMP on 16.04  Ubuntu app. Digital Ocean     (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is: Apache 2.4.18     (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:LAMP      (e.g. WAMP, XAMPP)
![image](https://user-images.githubusercontent.com/35817279/36328301-9c111110-132f-11e8-8de6-bcb6bf268490.png)

### Issue / Bug  / Question / New Feature

Hi 
When I try to scan a receipt for return it doesn't list the items sold on that receipt and throws an error saying that " item add to receivings failed". I checked the issue OSPOS Sale Return #253 but it doesn't really say anything about what to do  if the receipt is scanned and the items or not listed. 
When i try to manually enter the item to be returned it updates the wrong quantity to the system in multiples of 10 even if a single item is returned.
I installed the system just the way it was specified in the installation guide to install on digital ocean. Can you please help me solve this?

Thank you!

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by daN4cat** [comment]
Have you tried the latest version 3.2.0 in its "beta form"?
Just go here: https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files and download the latest version.

Try again and see if it's fixed or not. Thanks.

**Comment by WebShells** [comment]
@daN4cat should be closed ?
