### ISSUE TITLE
Quote -> Invoice <- Return

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1844]
### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is:     7.1
- MySQL or MariaDB version is:     MySQL 5.6
- OS and version is:      Windows 10
- WebServer is:     Apache 2.4

### Issue / Bug  / Question / New Feature

Sending quote via mail sends invoice instead of quote to customer... (tried with latest commit files, it's the same). 
Is it possible to add "PDF" button next to Print to enable PDF file download?
Also, how to make invoice based on the quote? I make a qoute today, customers pays for it three days later and I want to make him a invoice based on that quote....

Another one, customer does not like an item he purchased and he wants to give it back. How to make return? Item given back shold have cost price, not price when received back, and invoice fot it should have minus (-) next to item price....

**Comment by mckaygerhard** [comment]
i like this feature/request .. maybe the interface looks more "lot of things" in screen but its great do not limit the pdf downloading when the printer are already configured!

about the return problem i think must be open a new issue.. its a big problem when prices changes

**Comment by odiea** [comment]
Also, how to make invoice based on the quote? I make a qoute today, customers pays for it three days later and I want to make him a invoice based on that quote....
In the Register mode drop down select Invoice and it will be changed to an Invoice. As far as the cost price changing that appears to be an issue you have to deal with. If he paid 5.00 then he should get his 5.00 back.

**Comment by truchosky** [comment]
at the moment, cant quote be recovered after confirm it ?, will be a nice feature even for dinner table option

**Comment by odiea** [comment]
Unless you discard the quote it will show under suspended in sales.

**Comment by truchosky** [comment]
but if you "confirm" the quote and print/send it to customer then quote cant be recovered, a suspend quote is not a quote, how do you print suspend quote to customer ?

**Comment by odiea** [comment]
Unsuspend the quote. Under payment select Quote again. Then after the quote appears on the screen select Print then select Sales Register and the Quote will suspend again.
![2018-02-18 07_44_54-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/36353169-ee670bda-147f-11e8-9ac8-20fe5e1a1e62.png)

**Comment by truchosky** [comment]
my bad, If you descard it then quote disapears, but if you return to sales register then is there, suspended, thx you

**Comment by daN4cat** [comment]
@odiea is it true that an invoice is sent over email instead of a quote?

**Comment by odiea** [comment]
It was but not now with the quote commit.

**Comment by daN4cat** [comment]
ok, so the problem here is solved right?

**Comment by dvidic** [comment]
@odiea _In the Register mode drop down select Invoice and it will be changed to an Invoice. ._

My question was: how to make an invoice BASED on a issued quote?   You make a quote for a customer, he pays based on it, and you need to make him a invoice.

**Comment by odiea** [comment]
Unsuspend the quote when it shows in the register select Invoice from the drop down. The select the Invoice button under payments. It is that easy.

**Comment by dvidic** [comment]
@odiea Hm, figure it out, thank you. I think that this should be done different... Finished quotes should have separate button such as "Issued quotes". Suspended quotes are every quotes that has been finished and not finished too. This is confusing...
It's just my opinion, trying to help to make this piece of software best there is...

**Comment by daN4cat** [comment]
@SteveIreland, any opinion on the quote / invoice process?

WRT PDF, just use a pdf printer and job done, you save it locally. No need to go that far...

**Comment by SteveIreland** [comment]
My opinion on the quote => work order =>invoice process is that the process, in order to keep things easy to develop and maintain,  was adapted to the existing database ... in fact the database was a bit simplified because we eliminated the set of "suspended sales" tables. 

Depending on the needs of the OSPOS site an invoice can be prepared directly from a quote.  If the shop uses work orders then a work order can be prepared directly from a quote, and then when the work is done then an invoice can be prepared directly from the work order.

Database wise it's the same document simply transitioning through various stages of development.

No doubt there are improvements that can be made (a couple were subsequently made after the first phase of development), but the goal for this iteration was to keep it simple yet functional.
