### ISSUE TITLE
[bug] improved and explained printing due does not work always

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1845]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki) **wiki has very ambigous info** only cited issues that also are deprecated
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1 also tried with lasted
- OSPOS git commit hash is: 
- PHP version is:  irrelevant
- MySQL or MariaDB version is: irrelevant
- OS and version is:   tried guindows, linux mac also
- WebServer is:  irrelevant
- **WEBBROSER** triyed: palemoon 25, firefox 45

### Issue / Bug  / Question / New Feature

printing from ospos are now complicated, jsprint plgins are deprecated and its not working as denoted in the issue #431 must be used https://addons.mozilla.org/es/firefox/addon/seamless-print/

I CANNOT PRINT NOW, i recently spent in a new printer, due legal issue i must done that, now i cannot print, OS print perfectly.. so CUPS are not the problem..

the wiki are very out of date also unuseless cited use an info that are out of sync and redirect to read the issues thatr already also have out of date info..

**i can write instruction or update the wiki but i need mor info** as the screens shots show my printing are listed but no printing happened

what are the fu***gn right way to be able, please without citations unuseless and out-of.-sync infos the printer are START TSP 100

![ospos-jsdialog](https://user-images.githubusercontent.com/1571724/36348630-0a238eb6-146c-11e8-9ab3-126ea4905532.jpg)

**Comment by mckaygerhard** [comment]
after many friustrating investigations due "excelente documentation" in the ospos code and wiki i found a proposal

1.  Type about:config at Firefox’s location bar and hit Enter.
2.  Right click at anywhere on the page and select New > Boolean
3.  Enter the preference name as print.always_print_silent and click OK. Then set the boolean value to true.
4. Restart firefox

So with this, OSPOS will not depend of an plugin that will be always out of date, out of sync etc etc, but the configuration settings must be changed, by example a new "Format" (ug ah?) aparte of Default and Order can be named "Assumed" that asumed will print directly bypassing the browser (firefox) configuration. This works to firefox and palemoon.

**Comment by mckaygerhard** [comment]
i write in the wiki the very poor and very ilogic information, now i must wait tomorrow to test the store printer and report feedback, with the virtual printer here works, but need to test with the real printer.. 

https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Printing

after tests and see results i close or let open this issue

**Comment by odiea** [comment]
Font size is under Receipt and I still can not find the format setting. Also Seamless print has been deprecated in Quantum. Format in Invoice is how to display the Invoice numbers.

**Comment by daN4cat** [comment]
1. No swearing, I can't stand to it.
2. Firefox issue was already covered in #1728, so this is a duplicate.

I use Chromium and works fine for my needs, so I don't know what we could do for that issue with Firefox.

**Comment by mckaygerhard** [comment]
corretions mafe, err @odiea , so what's the difference between "Deault" and "order"? default does not means nothing! 

also i found a way to autoprint in quantum, i post in the new printing wiki, i posted that for quantum there's an altternative way in the wiki that i updated..

**Comment by mckaygerhard** [comment]
hi @daN4cat for sure works for you but not for others, the original wiki was very POOR AND BAD EXPLAINEd, the issue search are not USER FRIENDLY, and the issue template said if user "read the wiki" so there some point to "organize" here..

as the issue said, the changes must be "altered" to reload the config and printer go bask work.. take all the night due in the "ocean of issues" there's no explanation of that..

**Comment by odiea** [comment]
If you are referring to receipt and this is what you are talking about.
![2018-02-18 10_44_05-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/36354930-c33ea10c-1498-11e8-8b0b-a4eb2b2ecbdb.png)
Then the default receipt shows more info than the short receipt.

**Comment by daN4cat** [comment]
For any Quantum solution please post it to #1728

**Comment by daN4cat** [comment]
Also the search issue feature is difficult or not user friendly?
I see you are not happy even with GitHub. Well I'm afraid I can't fix that, take it with GitHub.
Firefox JsPrint is something that was already there since version 2.x, so not that much I can say about as I don't use it.

**Comment by mckaygerhard** [comment]
thanks for the hint @odiea updated the wiki ! i dont understant why here has wiki if all the "solutions" are in comments as @daN4cat said! sorry i mean the "ocean of issues"

@daN4cat i posted now, posted the link to the updated wiki, seems works but in some "rare" situations doe s not, make changes as said in the other issue and return to work, i also explained in the wiki too, now close this issue "with the trigger"
