### ISSUE TITLE
Font characters in mailed/printed documents

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1846]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 136093b8abff3c0105640a8456dedf8daba0914f
- PHP version is:      7.1
- MySQL or MariaDB version is: MySQL 5.6)
- OS and version is:     Windows 10
- WebServer is:     Apache 2.4

### Issue 

Quotes/Receipts/Invoices look good in Chrome/FF etc., but documets sent to customers mail and or printed don't show characters : _š, č, ć, ž, đ_.

How to enable it?

**Comment by daN4cat** [comment]
With documents you mean the pdf in attachment?

**Comment by dvidic** [comment]
Printed quotes/invoices/receipts and mailed quotes/invoices/receipts. They look OK in browser, but when printed or mailer, they have missing characters like a wrote above

**Comment by jekkos** [comment]
Could be an encoding issue? Never tried this really

**Comment by daN4cat** [comment]
Pdf I could understand but the printer issue is strange as that's sorted by browser and printer driver. The only change is a css to format the printout, but that should not change the string format.
This would require some testing but I have no time for this at the moment.

**Comment by jekkos** [comment]
Indeed the printer case sounds weird. The email however could be different as it's sent using text/html mime type (and probably some other headers). If someone can confirm this is a bug then let's label it's as such and maybe investigate later.

**Comment by mckaygerhard** [comment]
its a miscconfiguration in printer, due the OS, i cannot reproduce in a complete POSIX OS like MAC or freebsd, rthe localization of the OS must be in sync with the printer config and the webbrowser

**Comment by mckaygerhard** [comment]
its a misc-configuration in printer, due the OS, i cannot reproduce in a complete POSIX OS like MAC or freebsd, rthe localization of the OS must be in sync with the printer config and the web browser, as always, M$ dont disappoint users with breaking-standars

**Comment by dvidic** [comment]
Will try on different OS and language settings....

**Comment by daN4cat** [comment]
The setup is down to the user we cannot expect full coverage here.

**Comment by dvidic** [comment]
Guys, just tested on different OS and all characters are shown. So it's obviously down to OS setup and not OSPOS related.
TNX

**Comment by mckaygerhard** [comment]
as always a Guiwdows problem.. idont understand why this thing it's till used
