### ISSUE TITLE
Customer information on documents

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1848]
### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: df2a76b4cf360586f98334470eeebb9d999d119b
- PHP version is:      7.1
- MySQL or MariaDB version is:     MySQL 5.6
- OS and version is:      Windows 10
- WebServer is:      Apache 2.4

### Question

Can anyone please tell me how to add more customer info on quotes/invoices? I need _company name, VAT number, full address (address1, address2, zip, city, country, mail and phone number._ 
Those informations are needed because invoices are sent via post, and VAT number is crucial info for accounting, it's more important data than company name in EU.

Also, VAT for suppliers and customers needs to be *required data and company name should be shown on customers list...

**Comment by jekkos** [comment]
Shouldn't be too hard, just adapt the templates (check the views folder how it's done)
