### ISSUE TITLE
Return Issue with Invoicing enabled.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#1849]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: All 
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

When creating a single or multiple item return It appears to show a random Item number.
This is not a @SteveIreland issue but one that has always plagued me.
Images to follow. Does not give issue if Invoicing is disabled. Currently I have the same issue in Receivings returns unless I edit out the Invoice->Reference search.

**Comment by odiea** [comment]
This is the item input. You can see in the register view that this was the number selected.
![2018-02-20 13_29_42-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/36448921-616dc336-1646-11e8-8b6e-711f1295bfed.png)
This is the Item that showed on the form.
![2018-02-20 13_29_16-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/36448932-687d48a4-1646-11e8-8607-46d50e9e6aac.png)
![2018-02-20 13_27_58-](https://user-images.githubusercontent.com/10962177/36448937-6cb837bc-1646-11e8-9e8d-d6d148e98e36.png)

**Comment by mckaygerhard** [comment]
umm dou you revised the web-browser cache issues? are you testing that in Guiwdows "thing"?

**Comment by mckaygerhard** [comment]
umm dou you revised the web-browser cache issues? are you testing that in Guiwdows "thing"?

due i  noted that do you not fill the OS and the stack of server in the issue template. there's some issues with browser cache when using most modern versions specially in guindwos.. and when webprojects use the infamous jquery/ajax request

so please confirm em that this does not happened in other browsers using a real OS, maybe try a very older (but working) version of firefox like 32, or using palemoon fresh install

**Comment by odiea** [comment]
Yes Windows 10. Yes Firefox ,Palemoon ,Google chrome all show the same issue. And please quit blaming Windows for all your issues.

**Comment by odiea** [comment]
And the following is using Lubuntu to a Ubuntu Linux server. The Item number entered was 1.

![2018-02-20 17_04_17-open source point of sale _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/36456103-7d9fd124-1660-11e8-91de-f56406691a99.png)

**Comment by mckaygerhard** [comment]
i using very older firefox 16 with very older debian linux 2.6.32 never that problem, its a cache problem, your F12 show the stack of the id 1 but browser show the stack of the item incorrect..  in the network tab refresh and see the requests and the respose of the item search and see what are hapened when perform the request for the item

about guindows, do you see the 79% of the issues are in that os and related incompatible problems..

**Comment by mckaygerhard** [comment]
umm the "vinbuntu" are uner the virtual machine so the webserver are in guindows, please do you can try all on linux fres install but manually added the item and reproduce all the process?

**Comment by mckaygerhard** [comment]
its not ospos problem, hit F12 in the browser, go to the network tab, then go to the webserver and stop it, erase the webbrowser cache and start again, then in the browser clear the cache too (due you are using firefox and chromium most modern) and with the F12 network tab refresh/redone the process and see the request made in the network tab.. here are the debugging p¿of the problem..

if are ospos problem in the database are the problem in the data of the items, but its very improbable as i noted
