### ISSUE TITLE
[bug] normalization in the language respect the locales

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1850]
i'll explaint the situation respect the comments in commit  028f38784e8531ed387278208e902d2b90483b5f#commitcomment-27673788

ok, @jekkos i'll explain and in some way @daN4cat have right in some way but not totally, 

i'll explain, codeigniter does not support per locale language files, so for all the `es_<XX>` locales we must setup a only "Spanish" directory/language translation.. 

1. so the correct way its a very neutral translation in the weblate work and the name of the language must be "Spanish" not "Spanish (Spain)" that's all, rest of the translation i currently revised, so @jekkos rename for now the name of the language in weblate, 
2. same for Russian due in Russian we have 3 king of locale: ru_RU, ru_UA an the KOI8 variations, also Serbian and other that can be confused, as i discussed with @nerv55

**IMPORTANT** as recommendation, weblate does not permit make the work in context due the translator does not have the ospos interface in action.. so must always be in two steps , first translation of strings, then later second see that first translations in action by the usage of the ospos interface.. due the context language...

**NOTES** for now i only take that respect the Spanish and Russian due those are the only i have knowledge, but same situation are in others

**Comment by daN4cat** [comment]
Not sure I follow everything here, but we can support languages with locale. For instance Arabian translation is the one from Egypt and so it's marked with ar_eg. It's true that code igniter core does not make a distinction but OSPOS does and we use two language codes.

**Comment by daN4cat** [comment]
Therefore it's probably better to mark the translations with the correct locale code.

**Comment by daN4cat** [comment]
And we followed the same with en_US and en_GB because of:
- s vs z (summarise vs summarize)
- re vs er (centre vs center) 
- que vs ck (cheque vs check)
- ou vs o (colour vs color)

**Comment by daN4cat** [comment]
The language code definitions for Spanish are:

es	Spanish
es-AR	Spanish (Argentina)
es-BO	Spanish (Bolivia)
es-CL	Spanish (Chile)
es-CO	Spanish (Colombia)
es-CR	Spanish (Costa Rica)
es-DO	Spanish (Dominican Republic)
es-EC	Spanish (Ecuador)
es-ES	Spanish (Castilian)
es-ES	Spanish (Spain)
es-GT	Spanish (Guatemala)
es-HN	Spanish (Honduras)
es-MX	Spanish (Mexico)
es-NI	Spanish (Nicaragua)
es-PA	Spanish (Panama)
es-PE	Spanish (Peru)
es-PR	Spanish (Puerto Rico)
es-PY	Spanish (Paraguay)
es-SV	Spanish (El Salvador)
es-UY	Spanish (Uruguay)
es-VE	Spanish (Venezuela)

**Comment by mckaygerhard** [comment]
well if you see the locale interface, those list are unnecesary for translation, due a user can set the localization to ru_RU and use Spanish as interface languaje, so a "es" for translation its the right choice..  that's i try to explain that in the languaje directory a es_ES its unnecesary so "SPain" or "Spanish (Spain)" its not a "name"..

**but! currently due the localization module in config are totally broken..**  due #1858
