### ISSUE TITLE
Resetting admin password from within mysql

### ISSUE THREAD

**Issue by HeinB** [opensourcepos/opensourcepos#1851]
I cannot log into my system after changing my own password and the admin password was changed as well - I can get into mysql.  Can you let me know if it is possible to reset the admin password from mysql?

Thanks

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by mckaygerhard** [comment]
pleasse be specific, its admin mysql DBMS password or ospos admin user password, due for the fisrt its not a ospos issue, search for "reseting mysql root passoword" of course the search give you only unix related due in xamp there's no password

again the github template its not usefully, we must admint that for people its tedious fill that template,  i propose two times some changes more resumed and usefully

**Comment by HeinB** [comment]
Apologies, this is the admin user to access the application.  I tried resetting the password by copying the password from the database.sql file and updating the ospos_employees table where username='admin', but I still get invalid password when I try to log in to the application using admin/pointofsale.

OSPOS Version: 3.2.0
PHP version: 7.1.10
MariaDB version 10.1.28
Windows Server 2012
Apache 2.4

Thanks!

**Comment by mckaygerhard** [comment]
the password its hashed so its not as easy as you did it, umm better its convertinf other user as admin user, try that first...its more easyle

**Comment by daN4cat** [comment]
database.sql password should be the hased version of _pointofsale_. Have you tried that?

**Comment by HeinB** [comment]
I used the hashed password in database.sql, but I still get an error (invalid username or password) when I try to log in.  I don't know how to convert another user to admin if I cannot log in as an administrator.

**Comment by mckaygerhard** [comment]
the suggestion made by me its use another user already in the system, i cannot do credit to the process due you are using guindows: or you have a problem in the update hash or you are a problem with the mysql/mariadb db..

1. find that another user in the `<PREFIX>_employees` table apart of the admin user, remenber the id of
2. go to the `<PREFIX>_grants` table, added same permission to the user that will be new admin

**IMPORTANT** the trick are due you already known the password of the other user, **and not  altered yet** in the doub OS software installed

this its the alternate way if there's no way to manage the admin password.. if your installation are bad, you must reinstall or change to a good POSIX operatiin system software

**Comment by shiftcm** [comment]
This is very easy just thinking  try to search  hash password version 2 in gg then go to https://www.php.net/manual/en/function.password-hash.php
and scroll down to sample password with hash copy hash code (long charactor) and put it in to your DB of your OSPOS in employee table, Go to your site refresh and login with sample password in link above GOTHA! you can login and go to change to your pass again 

FINISH... :) Hope can help a lot of ppl
