### ISSUE TITLE
Amazon EC2 instance database connectivity

### ISSUE THREAD

**Issue by loneknight16** [opensourcepos/opensourcepos#1860]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: Current v3.1.1
- OSPOS git commit hash is:  
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) - 7.0
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) - 5.7
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) - Ubunto 16.04 Amazon EC2 Instance
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) - Apache 2.4.18 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: LAMP stack followed instructions from here - https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04

### Issue / Bug  / Question / New Feature

I get the below error when I opened the main page:
database.php file has the following:

getenv('MYSQL_HOST_NAME') : 'ip_addresss' - so in place of ip_address, i've tried the EC2 instance private IP, public IP, localhost and 127.0.0.1. I've also added a host name in the hosts file for localhost 127.0.0.1 

I've also edited the security group to allow  inbound connectivity from anywhere on port 3306 - i know this is not required but I'm getting desperate as I've spent several hours to get this to work.

I've tripled checked all PHP modules are installed and can post a phpinfo file here if required. Can someone kindly please help! Thank you!!!

A PHP Error was encountered
Severity: Warning
Message: mysqli::real_connect(): (HY000/2002): Connection refused
Filename: mysqli/mysqli_driver.php
Line Number: 201
Backtrace:
File: /var/www/html/public/index.php
Line: 315
Function: require_once

A Database Error Occurred
Unable to connect to your database server using the provided settings.
Filename: core/CodeIgniter.php
Line Number: 518

**Comment by daN4cat** [comment]
This is OSPOS not AWS support.

**Comment by mckaygerhard** [comment]
please @daN4cat.. its a OSPOS problem due the line has a if-else implicit @loneknight16  try by remove all the line the getenv and just put directly the ip.. that's the problem with those developers that think all are like their env

**Comment by jekkos** [comment]
Probably just a mysql setup issue.

1. Are you sure the port is open and that it's reachable from the host running php?
2. Maybe mysql is not configured to accept tcp/ip connections but only works through a socket on the machine
3. try to reach it with a standard client first to see if it actually works

**Comment by mckaygerhard** [comment]
please give me a break! lñest see some facts:

1. muysql are obviously running, if not duplicate message running does not happened!
2 the firts are enought to the second
3. the second and firts reach too that!

**Comment by mckaygerhard** [comment]
please give me a break! lñest see some facts: @jekkos 

1. mysql are obviously running a connect are happened!, if not duplicate message running does not happened!
2. the firts are enought to the second
3. the second and firts reach too that!

**Comment by daN4cat** [comment]
@mckaygerhard I assume you are an expert of AWS, aren't you?

**Comment by daN4cat** [comment]
If you don't define .env nothing of that stuff is used. So getenv part can be ignored and it uses 'localhost'.
99% of the people will be fine with that if not you need to set the IP of your mysql/mariadb instead of 'localhost'.
However on AWS you design your VPC, subnets, security groups and etc. And you need to make sure your nat rules allow you to connect from EC2 instance to the db.
Also I don't know what kind of database deployment was selected. It could be that MySql id installed on a EC2 instance or using RDS.

And when somebody goes for AWS deployment it means they are after something scalable and etc.

I'm not going to give for free AWS consultancy.

**Comment by daN4cat** [comment]
So next time @mckaygerhard try to avoid misleading people and also avoid your useless remarks.

**Comment by loneknight16** [comment]
@daN4cat - it actually worked without the getenv and the actually issue was to do with credentials. 

FYI, localhost worked just fine as the server name. Apologies to have wasted everyyone's time here.

Anyone using the EC2 Ubuntu 16.04 instance and LAMP stack - please make sure all your modules are installed - make sure you go through each one sudo apt-get install php-xxx (module name) as noted in this thread [https://github.com/opensourcepos/opensourcepos/issues/1607](url) 

For some strange reason I had to sudo phpdismod and sudo phpenmod some modules to get ride of some errors.

**Comment by daN4cat** [comment]
Glad it was solved. Maybe next time you can use Docker deployment.

**Comment by mckaygerhard** [comment]
@daN4cat tht's why i tell to him to remove that and put "hardcoded" username and passwd! XD

umm by the way, why your comments and responses dont arrive me as mail notifications! very rare... when you made some responses or comments i cannot see it arrived in my mail!

**Comment by mckaygerhard** [comment]
@loneknight16 the sudo problem its due your using winbuntu, due some scalable issues about security must paerform that task with more privilegies.. later then give to www-data the respective access permissions

**Comment by daN4cat** [comment]
@mckaygerhard you are missing the point. Case closed, move on.

**Comment by mckaygerhard** [comment]
ah ok @loneknight16 now i understand.. umm some module maybe was missing amonth the needs
