### ISSUE TITLE
[feat] focus and pre-select ready to change amount item/tendered for easy of use

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1863]
### Issue / Bug  / Question / New Feature

in the amount_tendered the employee must quickly put the amount, but due currently first need to erase the predefined  and input the client's amount.. that little action to erase the predefined amount take a precious time (must move the mouse, hit the erase key)

please @jekkos , @odiea , @objecttothis  or @daN4cat its a very usefully change, if a pull request will be acepted i'll made it, but at the moment if not, it's here!

this improvement are based on the experience of usage in employees.. 

### 1) at the items amount number in  `register.php` of `application/views/sales`

``` diff
172c172
-echo form_input(array('name'=>'quantity', 'class'=>'form-control input-sm', 'value'=>to_quantity_decimals($item['quantity']), 'tabindex'=>++$tabindex));
436c436
---
+echo form_input(array('name'=>'quantity', 'class'=>'form-control input-sm', 'value'=>to_quantity_decimals($item['quantity']), 'tabindex'=>++$tabindex, 'onClick'=>"this.select();"));
```

### 2 at the amount tendered of the payment

``` diff
436c436
- 									<?php echo form_input(array('name'=>'amount_tendered', 'id'=>'amount_tendered', 'class'=>'form-control input-sm disabled', 'disabled'=>'disabled', 'value'=>'0', 'size'=>'5', 'tabindex'=>++$tabindex)); ?>
---
+ 									<?php echo form_input(array('name'=>'amount_tendered', 'id'=>'amount_tendered', 'class'=>'form-control input-sm disabled', 'disabled'=>'disabled', 'value'=>'0', 'size'=>'5', 'tabindex'=>++$tabindex, 'onClick'=>"this.select();")); ?>
480c480
- 									<?php echo form_input(array('name'=>'amount_tendered', 'id'=>'amount_tendered', 'class'=>'form-control input-sm non-giftcard-input', 'value'=>to_currency_no_money($amount_due), 'size'=>'5', 'tabindex'=>++$tabindex)); ?>
+ 									<?php echo form_input(array('name'=>'amount_tendered', 'id'=>'amount_tendered', 'class'=>'form-control input-sm giftcard-input', 'disabled' => true, 'value'=>to_currency_no_money($amount_due), 'size'=>'5', 'tabindex'=>++$tabindex, 'onClick'=>"this.select()")); ?>

```

**Comment by dvidic** [comment]
My employees have issues in register because of delay when entering quantity/price....Register refreshes everytime you enter a value. And when you enter for example quantity, move to price, register refreshes in the meantime and deletes value in price... Is there a way to shorten that delay?

**Comment by mckaygerhard** [comment]
@dvidic that its due the non-sense "send statis" in office->configuration->general, deactivate and test again to see if helps

**Comment by daN4cat** [comment]
@mckaygerhard make me understand your suggestion: when you click the textbox the complete number is automatically selected and you can directly type the new value. Is that the aim?

If yes, I'll test and apply the change as it makes sense.

**Comment by daN4cat** [comment]
@dvidic the register design is old, it should be redone completely using more javascript avoiding a complete refresh of the view.
But it's a lot of work and not sure when we will ever find the time to do that.

**Comment by odiea** [comment]
@daN4cat Yes that is the way it works. It would be nice to add the on-click to Price too.

**Comment by mckaygerhard** [comment]
hi @daN4cat yes, as you said, and for register,

also as @odiea said, i do not recomended redone using complete javascript, **of course take some time but its more secure respect the browser cache**, that make many headache problems... 

also **in terms of manteneance its a very complex work, we must take carefully in consideration the time to mantain that changes in the future**

**Comment by dvidic** [comment]
@mckaygerhard after applying your code changes to register.php I get "Amount tendered must be a number" error and cannot finish receipt...
I reverted to old register.php and it works fine....

**Comment by odiea** [comment]
Compare the last 2 lines and you will see he left out something very important.

**Comment by dvidic** [comment]
I looked in commit, it seems that there's no errors in code.

**Comment by odiea** [comment]
I had no issues with the code in his pull request. He did update the Amount tendered problem.

**Comment by dvidic** [comment]
Yep, pull requst has correct code. Thanks for the hint!

**Comment by mckaygerhard** [comment]
umm @dvidic i made that pull in fly, maybe i made some misctake.. lest see that again and i posted here feedback..

interesting, but notifications about many of the comments dont arrives at my mail..

**Comment by mckaygerhard** [comment]
ah @dvidic and @odiea .. now i can see that you said..yes i do not see the rest of messages..

**Comment by daN4cat** [comment]
Done and in master.
