### ISSUE TITLE
Enable https in base_url without set ssl in docker image

### ISSUE THREAD

**Issue by ElGranLoky** [opensourcepos/opensourcepos#1867]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: -
- PHP version is:    7.1
- MySQL or MariaDB version is: MariaDB 10.2
- OS and version is:  Docker
- WebServer is:  Docker
- Docker installation: jekkos/opensourcepos:master

### Question 

¿How to force change the base_url to https without edit? ¿can set with a docker enviroment variable?

**Comment by mckaygerhard** [comment]
easile, just go to the application/config and edit the config.php then here change the http to https only, that's all

please close this when done.. help to mantain organized our project

**Comment by mckaygerhard** [comment]
@ElGranLoky when editing application/config and edit the config.php then here change the http to https only, take care of the change:

original wil be:

``` php
$config['base_url'] = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https' : 'http';
$config['base_url'] .= '://' . $_SERVER['HTTP_HOST'];
$config['base_url'] .= str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME']);
```

you must change to

``` php
$config['base_url'] = 'https';
$config['base_url'] .= '://' . $_SERVER['HTTP_HOST'];
$config['base_url'] .= str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME']);
```
**please close this when done.. help to mantain organized our project**

**Comment by daN4cat** [comment]
Easy like that, just reapply to docker and life will be easy peasy.

**Comment by ElGranLoky** [comment]
Thank you very much, I had my doubts but I imagined that this was the change that would have to be made.

The question is if you are thinking about enabling it directly from a docker variable so that you do not have to make the change each time the official docker image is downloaded

**Comment by daN4cat** [comment]
@mckaygerhard please clarify how to do it in dockers as I'm sure it's an easy walk for you...

**Comment by jekkos** [comment]
Guess it's just a matter of adding an environment variable in the compose file and read it out in PHP?

**Comment by ElGranLoky** [comment]
I [create PR](https://github.com/opensourcepos/opensourcepos/pull/1874) with the changes for enable https with a docker variable.

**Comment by mckaygerhard** [comment]
i commented on your pull request, change the code to property merged:

better put:

``` php
if (isset($_ENV['FORCE_HTTPS']))
$_SERVER['HTTPS']  = 'on'
```

that's all

**Comment by ElGranLoky** [comment]
Thanks

**Comment by mckaygerhard** [comment]
umm i'll make a special specific wiki page for those variables or changes.. fiiiuu, the wiki it's also a git repository so can working on this at same time
