### ISSUE TITLE
[feat] new credit sale mode, sale by a credit

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1869]
### Issue / Bug  / Question / New Feature

New sale mode for partial payments, that is, new credit sale mode.

we can take the quote mode, duplicate the behaviour and make it as a sale mode that receive payments.. the only difference its that will print a receipt that quote does not.

its easy, but i tried to made it and have some problems too many javascripts and jquery stuff that i dont understand

**Comment by WebShells** [comment]
Refer to #1428 & #24, already discussed and planning to support partial payments...

**Comment by mckaygerhard** [comment]
WOW, a lot to read, thanks, i put on .. i close due this its duplicated!

**Comment by mckaygerhard** [comment]
solved partially in https://github.com/opensourcepos/opensourcepos/issues/1427#issuecomment-371530881

**Comment by mckaygerhard** [comment]
i develop(well i not a developer) my own credit sale mode, for those that need some point directions how to solve it, may help that code: https://github.com/codeigniterpower/osposweb/tree/osposweb-cxcteipado

of course its not an avanced accounting, an there's no Acount payable, but at leas have an accounting about the amounts added to a credit sale amount made!

**Comment by mckaygerhard** [comment]
only related but not similar/specific work: see #2080 (will be related to xpenses)
