### ISSUE TITLE
Deselecting employee grant module does not delete child grants

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#1870]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: latest master
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is: Ubuntu     (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: yes
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

###  Bug

Found one regression in the employee form You previously weren't enabled to remove grants from a module without having the grants that site below it deselected.

![schermafdruk van 2018-02-28 23-47-49](https://user-images.githubusercontent.com/576234/36817563-d7d3d0fa-1ce1-11e8-8d02-d57cc4b0378e.png)

**Comment by daN4cat** [comment]
@jekkos do you plan to fix this by 3.2.0 release?

**Comment by jekkos** [comment]
Think this code went out after the home / office modules were added. I have to check first 
1. Whether it is still there but broken for some reason
2. Then add it back or adapt to make it work again

Quite some fiddly javascript if I remember well. Will try to have a look somewhere this week.

**Comment by jekkos** [comment]
Ok should be fixed in latest master

**Comment by daN4cat** [comment]
@odiea can you please test and confirm it's fine?

**Comment by odiea** [comment]
I tried this yesterday and it worked fine for me. It did remove all the check marks.

**Comment by daN4cat** [comment]
Thanks, I close.
