### ISSUE TITLE
Invoice elements missing

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1871]
### Installation information

- OSPOS version is: 3.2.0

### Issue 

My accountant told me today that OSPOS invoice/receipt are legally not usable. They have only date on them and it should have these:
**Invoice date
Date of items delivery
Payment due date**

All these dates can be the same, but they have to be on printed invoice/receipt. Also, on every invoice there should be name of employee who made invoice....
Without those elements invoice should not be given to customer.

**Comment by SteveIreland** [comment]
I don't recall anyone reporting that it wasn't legally usable.  What country is this?  
There really isn't anything in OSPOS that a payment due date can be calculated from.  You could include a payment terms description in the invoice footer or the sale comment.  Also, payment terms can be different by customer or customer type so that would need to be factored in to the effort.

Maybe another post 3.2 initiative?

**Comment by dvidic** [comment]
Country is Croatia.
These three dates can be the same, but must be printed on invoice.

**Comment by WebShells** [comment]
@dvidic dvidic, will take a look over that... you know that you can manually edit the invoice final form right ?

**Comment by dvidic** [comment]
@WebShells thru html or I missed some other invoice customization method?

**Comment by odiea** [comment]
You will need to edit the application/views/sales/invoice.php. Like the rest of us you will learn how to customize for your needs.

**Comment by WebShells** [comment]
@dvidic, as odiea mentioned in invoice.php file, or you can customize before printing by double clicking the section you would like to edit...

**Comment by daN4cat** [comment]
This is a custom requirement, @dvidic you cannot make your specific local issues a generic thing here. You need to get someone to customise OSPOS for your needs. We need to draw a line here.

**Comment by dvidic** [comment]
OK, I'll change invoice php html elements myself. I was under impression that Croatia is not only country with that kind of invoice form requirement.
@daN4cat I can admit that this is mine local issues, but this is only specific local issue so far, all other issues/bugs I reported are general requirements and improvements for all users. I'm trying to make the best of it

**Comment by dvidic** [comment]
@WebShells @daN4cat @odiea I added elements that were missing, but one thing I cannot add: **TIME**. 
I need time (HH:MM format) on invoice. Tried with 	`<?php echo $sale_time; ?>` but it gives me nothing. 
Can anyone please help me.

**Comment by mckaygerhard** [comment]
hi @dvidic maybe if on sale_lib the sale time will be added, and then in the controller must be added to the data of the views? i'm based on CI workflow of MVC..

**Comment by WebShells** [comment]
Sale date and time already shows on invoice... No?

**Comment by mckaygerhard** [comment]
my country need too, i not see this requeriment, but in my country we need that also.. i was planning do that but time, time...

**Comment by dvidic** [comment]
@WebShells No, I have only date on invoice

**Comment by dvidic** [comment]
Found it: `<?php echo $transaction_time ?>`

**Comment by daN4cat** [comment]
@dvidic since OSPOS in Croatian is missing translations, I'm pretty sure you have time to help and complete the them: http://weblate.jpeelaer.net/projects/ospos/#languages
