### ISSUE TITLE
Code Documentation needed

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1872]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) 5.6
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MySQL 5.7
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.1
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Currently there is very little documentation of the code.  It would be a lot of work to manually document all methods and classes.  What if we use something like PHPDoc2 https://github.com/phpDocumentor/phpDocumentor2 which has become sort of a de facto standard with documentation to automatically document functions and classes in the master code?

**Comment by jekkos** [comment]
I think @daN4cat did something in this direction a while ago. Was mainly generating documentation from the existing code.

I'd try to make the code as self explanatory as possible, however this is not always trivial.

**Comment by mckaygerhard** [comment]
well i can documented some in the wiki, as you can see @jekkos , i started to separate end-user documentation from developer-technician related in the wiki...

i understand some the code in general terms but in advanced terms not, specially this not help due the very complicated (and convenient of course related to the footer part) development tools

so i'll try to make this weekend some general explanation based on my experience (make new report, make a extra column for sales, make a extra changes in a input or label without css regeneration)

**Comment by jekkos** [comment]
Ok all contributions welcome on that part

**Comment by mckaygerhard** [comment]
hi @odiea, @jekkos  i have a **important code question, about loading config keys**: i see that the model are autoloading and in that array are loading the appconfig model, als too i can see that there's a hook that also load the configs key from database as a array of the CI configuration array..

there's two loading of configurations.. so when i want to check a config key, agains i must check? agains the config array CI or agains the autoloaded model? and what load first?

**Comment by daN4cat** [comment]
@objecttothis there is a script under bin/ called gendocs.sh and uses ApiGen.
The original issue was #1278, please read that case.

You can find the latest generated doc in my mirror of ospos: https://dan4cat.github.io/opensourcepos/
It's up to date to today's code version.

I've tried to add a bit of documentation here and there, but it's a slow progress task.
At the moment I don't have that much time to dedicate to improve this point.

**Comment by mckaygerhard** [comment]
hi @daN4cat, that api gen it great, why dont pull to the git wiki? the wiki of the proyect can be cloned and push riles,, can be this or are not convenient?
or well put in some way to other can read?

in last, can i source and link your repository in the wiki? for developer documentation?

**Comment by mckaygerhard** [comment]
hi @jekkos and @objecttothis i added some code tips to the wiki that help to start code, this in combination with the @daN4cat API documentation should be enought to make features and new pieces of code to the project.. chek it and hope will be usefully
PD: still need some reorganization but i'm working on.. in a parallel wiki and put later

**Comment by mckaygerhard** [comment]
links: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#tech-architecture

**Comment by mckaygerhard** [comment]
ah, also i try to ilustrate the translations better here too: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#always-use-translations-event-hardcoded-strings

**Comment by mckaygerhard** [comment]
hi @all, @jekkos, i'm just improved the error log guide in the wiki, https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-DEVEL:-Error-Logging-in-OSPOS with a screenshots of each case, i split in two main cases, at client side and at server side..  please hope will be usefully, later i'll link and organize the proper way to go here. for users will do a different guite to error log..

error log maybe will be better to the reporting issues, amny project ask or those files when a issue are posted

**Comment by mckaygerhard** [comment]
hi @all  and @jekkos i added how to gen the code api documentation and proper links in the development wiki page index at https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#development-code-tips-and-help hope it helps

**Comment by mckaygerhard** [comment]
the code api documentation that points by you @daN4cat are not accesible right now! we need some other links!
