### ISSUE TITLE
It is unethical and potentially illegal to disable someone's install.

### ISSUE THREAD

**Issue by jimktrains** [opensourcepos/opensourcepos#1875]
https://github.com/opensourcepos/opensourcepos/blob/32074771acad1fa66af34e629f8668a83e9fdc98/application/controllers/Login.php#L114

Additionally, this check is faulty.  I added some additional information to the footer (the current register and shop) and trigger this along with an issue with blockUI. I am entirely compliant with the license as I have not touched the text originally present.

**Comment by mckaygerhard** [comment]
yeah the license said MIT.. well lest analize, ospos make you cheap some money.. and you claim that its ilegal.. 

well both parts have right, you want freedom and those developers guys want reconicion of their work.. so lets declare this a null result okey

so due both parts have right both part must be by own

**Comment by daN4cat** [comment]
It's not illegal and the license terms are clear. No claim of ownership, copyright and all that stuff as many are doing behind the scenes not having moved a finger. Also the name is Open Source Point Of Sale.

**Comment by jimktrains** [comment]
Obviously you didn't read my message. I didn't change the message about what we're using in the footer. I added another piece of information telling the end user which register is currently being used (we have multiple registers).

Your message was left intact. I'm not complaining about your addendum to the MIT license. I'm complaining about preventing an install from working even when the terms of your license are kept in it's entirety. (Moreover, it's a silly check, it literally took only a few minutes to remove.)

Also, the personal attacks are uncalled for. We're using ospos internally and not selling it or hiding what it is based on. Additionally, if you'd check other issues, I'm working on some larger features that we plan on committing back, so the vitrol is entirely uncalled for.

**Comment by odiea** [comment]
Would that not be more informative if that was shown in the top navbar instead of the footer? Just wondering.

**Comment by jimktrains** [comment]
I wanted it to be unobtrusive as it's not always needed. A small chance as such shouldn't wreck an install.

**Comment by jimktrains** [comment]
Wreck an install by design*

**Comment by daN4cat** [comment]
It's a silly check on purpose, to stop the ones that really want a free meal without neither using their brain.

**Comment by daN4cat** [comment]
And there was no personal attack. I explained why.

**Comment by marcellusmontilla** [comment]
@jimktrains Just curious, who disabled whose install?

**Comment by mckaygerhard** [comment]
@jimktrains i found a solution for you, just dont touch the div's that are related to the footer, so them make a new css or incrush a code css in the header, then in the foother before the div's related put your code..  of course you must made all css related with new labes/names to do not conflict the leyr shadow that happened, that its just a message but empty je je

**Comment by mckaygerhard** [comment]
also i agree with @daN4cat  to stop the ones that really **want a free meal without neither using their brain.** (most windozers users are like)

**Comment by jimktrains** [comment]
@daN4cat I was refering to when @mckaygerhard said "yeah the license said MIT.. well lest analize, ospos make you cheap some money.. and you claim that its ilegal.." not specifically anything in your message. (It's also not an MIT license. It's based on the MIT license, but that's neither here nor there right now as I'm not objecting to the change.)

@marcellusmontilla A stock part of the software disabled the rest of the software because I made a change that is compliant with the license.  The license says 

> The footer signature "You are using Open Source Point Of Sale" with version, hash and link to the original distribution of the code MUST BE RETAINED, MUST BE VISIBLE IN EVERY PAGE and CANNOT BE MODIFIED.

I retained this information with no modifications to the div that contains it, just an addition to the <div id="footer">. Not, I didn't even edit the div that directly contains the message in question, just the one tagged as the footer.

@mckaygerhard every single one of your solutions is a non-obvious solution to a problem that shouldn't exist. i.e.

1) I don't want them in the header, so why would I think to put them there. (No technical basis is present to point to this as a good/better option.)
2) I wanted the message of what software is being used to show first, so why would I think to put it above said message. (No technical basis is present to point to this as a good/better option.)

3) I didn't add any CSS, so I'm not sure what's conflicting.

4) I have no idea what you mean, but yes, an empty overlay and no console message or visible message is extremely frustrating.

Moreover, these are all options _after_ I find out that the code disables itself when anything is added to the footer (after the OSPOS message?).  Sure, I have options, but I also have the option of removing all of these silly checks, which I did so that they don't randomly bite us in the butt.  Luckily I went to test my stuff a little more before showing it to our brass (problems only manifest after logging in and not while I had an active session.) Otherwise our brass would have seen software that "self destructs" when you change it and would have unanimously thumbs down me doing any more work with it.

This is not the message you want to send. If someone wants to remove the attribution line they will and can. Perhaps add a comment above the div reminding the user that the terms of the license prohibit modifying the following div. An honest person will abide. A dishonest person won't. A dishonest person will also just disable your checks when it fails.  I happen to be an honest person bit by an edge-case in your opensource-anti-piracy code and had to disable said checks anyway.

> also i agree with @daN4cat to stop the ones that really want a free meal without neither using their brain. (most windozers users are like)

To be honest, that's a risk you take with open source software. Being actively user-hostile (even when they're compliant with the license!) is not a good approach. Even if you had a better license, like the GPL, you still can't stop anyone with even a quarter brain from doing what they wish with the software.

It's also very insulting and annoying to read "windoze" and makes you come across as childish.

**Comment by mckaygerhard** [comment]
@jimktrains i agree with you in some aspects, ixected @all here read carefully i read carefully your position, i'll take the most two impotants aspects, i read (and i spected developers too) the par that said: _" every single one of your solutions is a non-obvious solution to a problem that shouldn't exist. i.e."_: and my problem i must cited its that i have problem to write, but my documentations are very well write when i done:

1 - you are right, the README are not clear in that, must said "mantain all the footer class/div unchanged" or some thing like, but also i give you the solution too, of course now i exptected some developer take more care about the text at README's, wiki pages, are not so simple like putting words, and by the way, do you read the solution i posted? dont touch the div and that's made the deal for you.. if needsome directions or specific commands let's do it! i write for you! to linux of course ! i dont use guindows... of course about the unclear license and footer lest see next:

2 - conributions vs "hostile": of course if there are a ostile behavior or frustrating and complicated development env the overall of contributors are few.. i posted that few time here.. and currently i made some important changes like made a better wiki BUT: change the code its for developers, not for normal end-users, if a end-user wants to mae some tihing like, must read . and in this part must read the code, to contribute to a less-painfull reading i currently improve the wiki right now..

3 -  but try to understand that by example in some countries there's too many people that are "vivos" as said colloquially in my country! Because working in contribution is not the same as working for others without anything in return, umm sounds like "socialism" but that's the problem in a community, some guys are not working only consuming

4 - the shadow div are "empty" as logicall, if there's some message here will be easy to hack/crack for many right? XD, umm but other are illogicall like "dont expose install information at login page" pufff please, end-users are not administrator, if this are not take wth care by administrator! please!, ah of course a end-user are not an administrator, this only happened in a win environment..

**Comment by jimktrains** [comment]
> umm sounds like "socialism" but that's the problem in a community, some guys are not working only consuming, here are people spend time to make this work!

You're not special in this regard. Look at how the bad and Linux kernel handle this.

> to here developer some other are illogical like "dont expose install information at login page" 

I never said that so I'm not sure what you're talking about. I only said the issue didn't arise until I logged in again.

> ah of course a end-user are not an administrator, this only happened in a win environment..

Again, I have no idea what you're talking about. Plenty of Linux and bad systems are administered by their end user.

**Comment by mckaygerhard** [comment]
wow, you read so fast!.. do you test the poposed solution yet?

> You're not special in this regard. Look at how the bad and Linux kernel handle this.

Linux kernel receibe money, not only donnations.. a great difference..

>I never said that so I'm not sure what you're talking about. I only said the issue didn't arise until I logged in again.

that part its not for you, dont worry... that part give to you the reason that some information its necesari¿y at installation runtime

> Again, I have no idea what you're talking about. Plenty of Linux and bad systems are administered by their end user.

maybe this are the reason why our work of developer are so bad paid! now everybody nay person are develper too? wow! universitu to the garbage! well i'm not developer in any way!

**Comment by mckaygerhard** [comment]
> Again, I have no idea what you're talking about. Plenty of Linux and bad systems are administered by their end user.

ah important: good system are not administrating by those! definitelly!

**Comment by nerv55** [comment]
free for the word not for beer, the developers are in their right to protect their effort.

**Comment by nerv55** [comment]
clear warnings should also be given in the readme that changes to the message in the footer will disable the system

**Comment by jimktrains** [comment]
@nerv55 I didn't change the message in the footer. I added information about the current location below it.

Also, are they really "protecting" anything when their check is so faulty that compliance with the license still causes the application to stop working?

@mckaygerhard you can't really believe that someone is incapable of admining their own computer. What does an admin do with their own. I don't know what high horse you think you're on, but you sound very bad.

Also, what's with this?

>  maybe this are the reason why our work of developer are so bad paid!

I'm a salaried developer who is being paid to work on ospos with the intent of committing what we can back. Please stop with the hyperbole.

**Comment by mckaygerhard** [comment]
@jimktrains  umm i like your idea, maybe will be better merged in #1792 **do you want to do that for improve support for your clients?**

about that:
> I'm a salaried developer who is being paid to work on ospos with the intent of committing what we can back. Please stop with the hyperbole.

the world are not like yours: many "salarymen" (as called in japan) are not enought payed! in some countreies , are remote paid and are only 50$, of course when changed in local money sound like much money! please take a more expanded vision of the things

**Comment by nerv55** [comment]
@jimktrains, i'm not arguing with you, even if you did not change the original text in the footer, you add something to the string, this change the contented and the length of it. but I'm sure if you read  in readme file, something like "Be aware if you modify in any way the footer, deleting, adding, text. the system will stop working", you can take measure to avoid this "bite you in the butt". 
Yes is not the best way to protect software but at least keep away the persons that try to re-brand the thing without take the effort to at least read the readme.

**Comment by jimktrains** [comment]
@mckaygerhard I prefer to keep all discuss public.

>  simple: when you buy a refrigerator only USE IT, not REAPAIR IT!, the TECHNICIAN its whow repair and administrate the functionality of the refrigerator, you only be able to use the AVAILABLE FUNCTIONS! RIGHT? 

No, by and large I perform my own maintenance to the extent my tools can take me.

> 
only countryes like EEUU, CANADA, SWISERLAND or GERMANY exist a profession called "Developer", in the rest there a frustrating due users thingks can be administrator, also think can be developers..

I'm not sure what you mean for the first portion, but the second portion sounds extremely elitist and just as incorrect.

@nerv55 sure if it were called out as such. However, the current readme only talks about 

> The footer signature "You are using Open Source Point Of Sale" with version, hash and link to the original distribution of the code MUST BE RETAINED, MUST BE VISIBLE IN EVERY PAGE and CANNOT BE MODIFIED.

And 

> Authoring the footer notice replacing it with your own or even worse claiming the copyright is absolutely prohibited

Currently it talks about not wanting you to modify the footer notice. So, sure, while extra documentation in the readme and in the footer file will save others from being bit, I still find it to be a poorly thought-out anti-feature.

**Comment by mckaygerhard** [comment]
@jimktrains about the readme and footer, we are working in better documentation, and in future we will perform better the advertising

@jimktrains about the issue per se, try only added a new div section.. that's make the trick

>  No, by and large I perform my own maintenance to the extent my tools can take me.

well that's incorrect, in normal way, **that's the job of the technician, not yours**, but in other words, of course if you do that, and there's a advertising that said "tond touch if are nto qualified"...

**Comment by jimktrains** [comment]
@mckaygerhard

> well that's incorrect, in normal way, that's the job of the technician, not yours

No, it's not.

**Comment by marcellusmontilla** [comment]
@jimktrains I don't know what the issue is, it is your installation after all; hence, everything is under your control. How can you even hint at someone being unethical or doing something illegal when that someone is you? Is this because you almost got humiliated in front of your brass (thanks to your prudent testing, you didn't)?

**Comment by jimktrains** [comment]
@marcellusmontilla The issue is that the code contains booby traps, which are unethical at the very least, and could potentially be a legal liability. It is my installation, and I removed this round of booby traps and am a bit worried there are others.

> thanks to your prudent testing, you didn't

The issue only happened _after_ login in, hence the change happened quite a while before the issue it caused. Please stop the vitriol. More over, it wouldn't have been my humiliation, it would have been an instant "no" to continuing work with OSPOS.

To be honest, I find the booby traps childish and a very good way to turn away other organizations from contributing to it. I know there is concern about people selling hosting of your code and calling it their own, but this is not an effective means of preventing people from doing that. It only serves to make the project look foolish.

**Comment by mckaygerhard** [comment]
this threat its so funny, right @marcellusmontilla and @nerv55 , lest analize a little:

> No, it's not. It's insulting and elitist to think so.
 
pardon me! if i were a lawyer, you are not the right person to said if something are legal or not,  agains my profession, you are only a "zealot"


pardon me! if i were a tecnician, you are not the right person to said if refrigerator are broken or not,  agains my profession, you are only a "zealot"

inconclusion, **if you are the best , so be by your own and dont call the experts**. that's why are so many OS instalation broken? not, its just many "experst"

**Comment by jimktrains** [comment]
@mckaygerhard First, I do not have clients. I am an employee.  Second, unfortunately #1792 is not a feature we require. #477 is what I'm currently working on with a goal of being able to commit back the feature. I also have a handful of other little things I'll have to collect and separate into Issues and PRs at some point.

**Comment by jimktrains** [comment]
@mckaygerhard in https://github.com/opensourcepos/opensourcepos/issues/1875#issuecomment-370197099 I quite literally have no idea what you're talking about. Are you implying that it's not possible for a non-expert to do anything? Do you really call a repair man every time there is a problem in your house?

**Comment by mckaygerhard** [comment]
umm ok lest get working on that so? or continue writing?

**Comment by jimktrains** [comment]
> umm ok lest get working on that so? or continue writing?

@mckaygerhard, excuse me. What?

**Comment by mckaygerhard** [comment]
umm ok lest get working on that so? or continue writing? well if a normal user dont follow the instruction must take care of their changes and errors right?

i'm taking care of the wiki and i try to do the best in the future about the shadow, the usage and instalation of the ospos.. based on your suggeestions

**Comment by jimktrains** [comment]
@mckaygerhard  Thanks.

And please don't get me wrong, I completely understand the developers' concerns over people rebranding OSPOS and selling it. I don't think it's silly. I don't think it's stuck-up. It's really frustrating when other people take credit for the work you've done.

I just don't think that this is an effective means of alleviating that concern. I think that it has the potential of turning off potential contributors, including corporate ones.

So what do you do? Well I don't believe there is very much that can be directly done, unfortunately. Indirectly, however, I do believe that there are things that could be done. For instance, what are these people who you're worried about doing? They're selling hosting for modified versions of OSPOS (if I understand this all correctly.) Can we sell hosted versions? That's right up my alley, feel free to contact me out-of-band about it if it's something you're interested in.

Additionally, selling support and custom service work could be another option. Again, feel free to contact me out-of-band if that's something you'd like to discuss.

Just because you've graciously made the software open source doesn't mean you can't or shouldn't profit from it in other ways.

In the end though, yeah, it's very frustrating when people claim credit for your work. I think the solution is to make those people less relevant, not to put up mere speed bumps in an attempt to stop them (while also making you look bad).

**Comment by odiea** [comment]
Would u 2 quit this stupid pissing match and do something productive for OSPOS

**Comment by mckaygerhard** [comment]
o7 yes captain! right now!

**Comment by daN4cat** [comment]
This whole discussion saddened me a lot, and I must be frank that since somebody moved to this forum the tone of the discussions in many threads changed. And I don't like it at all.

But I cannot stop trolls, they come and don't leave anymore. It's a fact of life in the internet/digital world. Their only mission in life is to disrupt, take anything they find and shed a lot of frustration / negativity.

I cannot change that.

Therefore I removed all the "crap" that bothers so many for a reason or another since a while.
Do what you want, as long as the tone of the discussions here turns to be more constructive as it used to be a couple of years ago.

It's not my intention to read so much unhappiness.
