### ISSUE TITLE
Cannot add new customer/error 500 when adding a db customer to sales invoice

### ISSUE THREAD

**Issue by tledowl** [opensourcepos/opensourcepos#1876]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: Open Source Point Of Sale version 3.1.1
- OSPOS git commit hash is:  4f5ad57
- PHP version is:   7.1.9
- MySQL or MariaDB version is:   MySQL 5.7.19   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:  Windows 10    (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:     Apache 2.4.27 (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  

Hi,

I am currently having trouble with adding a new customer to OPSOS. When I click 'New Customer', i get the pop up box but wit no options to add any information:

![image](https://user-images.githubusercontent.com/37003258/36923355-f8a4c8de-1e62-11e8-8d0f-c0111677a4f0.png)

I can succesfully add a new customer using a csv file, however if I add them to a sales invoice, I get the error 500 page. This is a fresh install, following the instructions on the wiki page. I have not ammended any of the configuration, and it is 'straight out of the box'. I have all of the necessary .dll files on my system, but still no luck. I downloaded the stable version of OPSOS.

If anyone could help that would be great!

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by WebShells** [comment]
@tledowl have a look @ apache and php bin files...

**Comment by tledowl** [comment]
@WebShells I would love to - but what exactly am I looking for? Apologies for being the noob...

**Comment by mckaygerhard** [comment]
seems duplicate of #1873 well @tledowl  you are guindow user, must read a few , i must assume that in your system the log files are under `apache2/log` or under `log` directly of the instalation.. maybe the README files of the apache2 instalation on your case could help.. the issue template does not said nothing about either the readme but must know these things to report a problem on instalation

also must activate the log of ospos, go to application/config/config.php and see log level, change from 0 to 4 and see the result in the application/log directory as <date>.php

those two files have the trace of the problem must parse here in markdown format, please read about too. ok.. ah of course for all must read

**Comment by tledowl** [comment]
Thank you; the issue was with the database connection strangely. Everything else was working with the db, so unsure why this was throwing up errors. Changed the dB info the admin details and hey presto, customers and sales receipts and now working. Thank you everyone for your help!
