### ISSUE TITLE
Print Inventory Count Details

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1877]
Hi Friends again me, I'm sorry,
How can we print the Inventory Count Details query?
some help?

![image](https://user-images.githubusercontent.com/12921805/36936009-6afd75ba-1ecd-11e8-8704-899a49d73ec7.png)

**Comment by mckaygerhard** [comment]
right click ooen in new windo then print with cups-pdf, there's no direct button for that in ospos edit windo

**Comment by guillermohaad** [comment]
Thank @mckaygerhard , I did what you say but show this

![image](https://user-images.githubusercontent.com/12921805/36936315-be17eb96-1ed1-11e8-908b-fae836ef6b7d.png)

**Comment by mckaygerhard** [comment]
no no, i refers only the item part, richt click over the windo js and opene in new

**Comment by guillermohaad** [comment]
@mckaygerhard , ufff I'm sorry I do not understand what you say? Could you give me a clue with a picture?
Thank you

**Comment by mckaygerhard** [comment]
sorry @guillermohaad i dont use the apache2 install, also i modified the paths of css.. i just also load again the same css in the item deatils.. but donjt remenber how right now, but its for sure if the css of item inventory are also loadin in that view wil print smoothy

umm sorry, lest be opened this issue, i dont remenber right now but i can write later in few days

**Comment by guillermohaad** [comment]
@mckaygerhard Thanks for your interest in my problem. There should be a report of this query that is very important for the business.

**Comment by mckaygerhard** [comment]
@guillermohaad i remenber now, you want the inventory specific history my solution dont give you that! only give to you the details of the inventory.. this its right?

**Comment by guillermohaad** [comment]
@mckaygerhard this its right, thank.

**Comment by mckaygerhard** [comment]
hi i working now with this, some one that work with printjs can work with this issue, i mean printjs can select a region and print if a button can be configured in the details view!

**Comment by mckaygerhard** [comment]
ok i'll try to added a button in th report that invokes same popup windows but with new tab, parse all css needs and lauch print() process.. currently i can print with blues bar transparency.. i'll update this later with more progress

**Comment by guillermohaad** [comment]
@mckaygerhard  , It would be a great advance because many of us have the need to have the inventory movement as support for surveillance and control.

Thanks for your work time, you will be rewarded.

**Comment by mckaygerhard** [comment]
lo he logrado.. pero no tengo organizado los archivo probe con otra cosa, 
aqui la solucion: 

https://stackoverflow.com/questions/20101409/how-can-i-insert-a-print-button-that-prints-a-form-in-a-webpage

es decir agrega un boton que diga imprimir area y define esa area.. yo voy hacer un pull request para todos los detalles que sirva.. mientras experimenta tu.. 

yo lo hice con algo mas sencillo con el reporte de vetas detalladas.. manana adiciona el pull request

**Comment by guillermohaad** [comment]
Great, @mckaygerhard we are waiting for the pull request
Thank you

**Comment by guillermohaad** [comment]
ufff unexpected result ...attached evidence
![printdetails](https://user-images.githubusercontent.com/12921805/37297765-7665ed8a-25ec-11e8-810e-c95e98a9e1c9.png)

**Comment by daN4cat** [comment]
For any type of reporting or advanced reporting I would suggest to consider reportico so you can build the reports you want against OSPOS database. And you can export them to pdf and print as you like.

**Comment by mckaygerhard** [comment]
hi @guillermohaad i said that the view loaded for the detail must include the header partial view too, so that can load the required CSS and JS files... alter you can included the js to print..

hi @daN4cat i tried reportico, but seems very complicated and inject many more depends.. and i dont like more "autoload" stuff, there's another way to? 

its better **"phpreport"** must think in end-users (taht will use that reports)i suggest! more easy to implement and use .. 

why? just use normal odt/xls files as templates, so end-mortal-users can easyle implement their own reports customized..

**Comment by guillermohaad** [comment]
Thank you @mckaygerhard 
in my humble opinion I agree with @ daN4cat to include Report as part of the opensourcepos core. We hope that in the next version already exists.

**Comment by mckaygerhard** [comment]
@guillermohaad pleas copy the same view, but in new file, load tha view when load the detail to print, but removing the lines of the menus.. 

about reportico, i means that  it's more simple the phpreports, end-users dont have to sufers of a pain again an API, just manage simple sheets files.. 

the realibility of a project resides in their easy to use of their users and ALSO DEVELOPMENT

**Comment by guillermohaad** [comment]
@mckaygerhard I'm sorry, I do not understand what you want to say, if you can send an example I appreciate the humanitarian aid. Thank you

**Comment by guillermohaad** [comment]
ok thank you @mckaygerhard

**Comment by daN4cat** [comment]
@mckaygerhard for you I suggest to use a paper notebook and a pen. It's easy to use and you can do everything.

**Comment by mckaygerhard** [comment]
a quick search demostrate what means "complicated things" https://github.com/opensourcepos/opensourcepos/issues?q=is%3Aissue+system+path+error+is%3Aclosed

my intention it's not make a hard discussion here @daN4cat but facts talks by it selft!,,, 

in any case was only a suggestion.. seems the work with reportico are on the way right? let's analize, if something like you with your skills started parallel to make the same but with phpreports (the older not the newer folk) will finish before 3.2.0 release! and tha's a fact!

**Comment by mckaygerhard** [comment]
umm about this issue how can i added a icon aside of the edit icon in each line, i added by concat the anchor aside of the edit link anchor but icon just put in new lijne..

**Comment by mckaygerhard** [comment]
hi @guillermohaad i make some thing related with this and i want to make this contribution to be release in 3.2 but i dont know how to put aside a icon print alogside with the icon that popup the details modal window.. no one of the developers here seems to help so much! maybe you can make some pressure

**Comment by guillermohaad** [comment]
Hi @mckaygerhard , I'm sure our friend @daN4cat  can give us a hand in this regard, thank you for your perseverance.

**Comment by mckaygerhard** [comment]
any progress on this?
