### ISSUE TITLE
Can I sell the quantity in stock only or show the stock at the time of the sale?

### ISSUE THREAD

**Issue by maxdo200** [opensourcepos/opensourcepos#1879]

**Comment by WebShells** [comment]
@maxdo200 stock quantity is already displayed below item name once you scan or enter an item into the sales register....

**Comment by maxdo200** [comment]
Thanks for the answer Thank you Is it possible to sell the same quantity
for example
I have a quantity of 200 when selling does not exceed the quantity stored
Thanks

**Comment by dvidic** [comment]
You can sell all the quantity you have on stock

**Comment by WebShells** [comment]
@Dvidic he means don't sell negative stock items... Once 0 is reached he won't be able to complete the sale...

**Comment by odiea** [comment]
The warnings were placed there in case you had an inventory miscount. Say the inventory states you only have 10 items yet the customer brings 15 items. Are you going to not sell him the other 5 items?

**Comment by daN4cat** [comment]
Just to be clear, there is no block on negative stock, just a warning. You can keep selling with negative stock.
It's mainky a tracking tool, logging what you are doing not blocking you.
