### ISSUE TITLE
Reporting Question/Issue

### ISSUE THREAD

**Issue by loneknight16** [opensourcepos/opensourcepos#1881]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- x[] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) - 7.0
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) - 5.7
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) - Ubuntu 16.4
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) - Apache 2.4
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP) - LAMP

*** Question:

My questions are about the 'Detailed Sales' Report:

1) Is it possible to customize this report to display the item_name next in the main row instead of having displayed as a drop_down row triggered by clicking on the '+' icon? I figured it is done this way to display multiple sale items in one transaction but wondering if it is possible to list in the same row or otherwise when exporting the xls can we change the default export option to dump everything including the dropdown row? at present you need to expand the dropdown rows for the export to include the item details.

I did try playing up the code by adding the 'name' field in the SQL query which then gets added to the 'Summary' array however this did not work. 

2) Can you include the total sales figure, report title(Detailed Sales Report) and the report date period when the report is exported in XLS? 

3) In the Total Sales figure, can you breakdown the figure to show the payment type - how many paid via cash/card etc and also have this included in the XLS export?

Also, there is an issue with exporting the report as XLS when the drop_down rows are activated. XLS file has Loading please wait... and then appended by the field names.

Appreciate your help.

Thank you

**Comment by daN4cat** [comment]
For advanced reporting I would suggest Reportico. You access OSPOS database and build the reports you want with that tool.
