### ISSUE TITLE
how to edit customer name from sales module?

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#1884]
@daN4cat 
hi to all developer/contributor of OSPOS... After a good time of hard work, commitment and diligence, You have reached a great height. Congratulations OSPOS developers/contributors!
...BTW
IMPORTANT: as an admin, you can assign cashier with limited privileges, if some customer names are misspelled, cashier can easily modify some changes..even without admin's permission...

**Comment by daN4cat** [comment]
It sounds a good idea and feature. I need to think about the UX design. Maybe an edit icon next to the customer name to open the edit form?
Let me think about...

**Comment by jekkos** [comment]
There used to be an option of adding a customer directly from the register? But ok up to now we can't edit a name directly.

Easy thing would be to add some kind of input field and show selected customer in it. If it's clicked then it gets rid of the readonly flag and name can be edited. Enter will then save/update it.

**Comment by jekkos** [comment]
Or in case of the bootstrap tables, I think you can make cells editable, so we might just leverage that and then link the action to a backend call..

**Comment by jekkos** [comment]
Check http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/editable.html for a UI example. Looks pretty neat. Also I'll update bstables to latest version as the fix you did for them has been released since three days

**Comment by daN4cat** [comment]
Not sure I follow. The point is to have the ability to edit a Name from the sales register. Why bstables?

**Comment by jekkos** [comment]
Ok there's both options, either edit it from the register or edit it from takings view. Initial question wasn't really clear but the second case looks like something I'd like to have myself.

**Comment by izeblood** [comment]
thanks for all your replies... this feature solve the duplication of customer names in case the're misspelled. @daN4cat can you add this as official feature for next modification of OSPOS?

**Comment by daN4cat** [comment]
I implemented this feature. The name of the customer is highlighted as a link, you click on it and the Customer edit form pops up. Edit the information and then submit. The page refreshes with the customer new information.

This will do.

Please be aware that if an Employee has no right to access Customers, no customers can be added nor edited. That's always been the case and I'm not changing that behaviour.

**Comment by odiea** [comment]
Works great. Thanks

**Comment by daN4cat** [comment]
@izeblood please test too, but I think I can close this now.

**Comment by izeblood** [comment]
ok @daN4cat i will test it... thanks....

**Comment by izeblood** [comment]
@daN4cat... i tested it already.. and it works great..thanks....case close....
