### ISSUE TITLE
About guide requirement

### ISSUE THREAD

**Issue by martadinata666** [opensourcepos/opensourcepos#1885]
### Installation information

- OSPOS version is: 3.1.1
- PHP version is:  7.1)
- MySQL or MariaDB version is:  MariaDB 10.1
- OS and version is:  Debian 9.2
- WebServer is:  Apache 2.4

### Issue / Bug  / Question / New Feature

Add php-mcrypt to the installation guide, i saw it missing after tried to install ospos today.

![screenshot_20180315_080544](https://user-images.githubusercontent.com/2433562/37472034-4f2e2dc0-2828-11e8-9e30-92de9c922aea.png)

**Comment by mckaygerhard** [comment]
the php-mcrypt its only if php << 7.1, for php  >> 7.0 the needed module its openssl

**Comment by daN4cat** [comment]
It's in the README.
