### ISSUE TITLE
Sales Takings Summary still shows deleted or cancelled amounts.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#1886]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: current Master
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) 7
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MariaDB
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Windows 10
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP) XAMPP

### Issue / Bug  / Question / New Feature

I finally got around to testing the deleted or cancelled Sales. I found in Takings summary the  deleted amounts were still being shown. It appears that Sale.php summary payments does not have a where clause for deleted or cancelled. I added the following and the cancelled or deleted payments do not show now.
```
public function get_payments_summary($search, $filters)
	{
		// get payment summary
		
		$this->db->select('payment_type, count(*) AS count, SUM(payment_amount) AS payment_amount');
		$this->db->from('sales AS sales');
		$this->db->join('sales_payments', 'sales_payments.sale_id = sales.sale_id');
		$this->db->join('people AS customer_p', 'sales.customer_id = customer_p.person_id', 'LEFT');
		$this->db->join('customers AS customer', 'sales.customer_id = customer.person_id', 'LEFT');
        $this->db->where('sales.sale_status = 0');

**Comment by mckaygerhard** [comment]
i triyed more carefully and seems something wrong with your installation. the sales are already filtered, at leas in the report, where from that module are you made it?:

``` sql
db:ospos SELECT 
`sale_id`, 
MAX(CASE WHEN sale_type = 0 && sale_status = 0 THEN 'reports_code_pos (TBD)' WHEN sale_type = 1 && sale_status = 0 THEN 'INV' WHEN sale_type = 2 && sale_status = 1 THEN 'OdT' WHEN sale_type = 3 && sale_status = 1 THEN 'Q' WHEN sale_type = 4 && sale_status = 0 THEN 'RET' WHEN sale_status = 2 THEN 'CNL' ELSE '' END) AS type_code, 
MAX(sale_status) as sale_status, 
MAX(sale_date) AS sale_date, SUM(quantity_purchased) AS items_purchased, MAX(employee_name) AS employee_name, 
MAX(customer_name) AS customer_name, SUM(subtotal) AS subtotal, SUM(tax) AS tax, SUM(total) AS total, 
SUM(cost) AS cost, 
SUM(profit) AS profit, 
MAX(payment_type) AS payment_type, 
MAX(comment) AS comment 
FROM `ospos_sales_items_temp` 
WHERE `sale_status` =0 AND ( `sale_type` =0 OR `sale_type` = 1 OR `sale_type` = 4 ) GROUP BY `sale_id` ORDER BY MAX(sale_date)
```

**Comment by daN4cat** [comment]
@odiea please wait for the bintray build and test it to see if it's fixed.

**Comment by odiea** [comment]
I copied  and pasted and this resolved my issue. Thanks. Who knows when Bintray will work again.

**Comment by jekkos** [comment]
Looking at it.. will try to change API keys see if that resolves the issue here. For some reason the build is not being pushed.

**Comment by jekkos** [comment]
@odiea had some fun debugging the bintray issue! So apparantly it seems that the current release version of dpl (deployment tool used by travis-ci) is broken for bintray. Went through a couple of hoops and found myself

* writing a custom curl request with my api key to bintray endpoint to see whether used credentials actually work (they do)
* reproduced the issue on a local machine
* adding a http proxy to ruby runtime that then sent all request to a SOCKS interceptor (burp suite)
* tried to circumvent SSL by having ruby ignore certificate validation, after adding burp suite CA certificate chain to the ruby env
* then finally saw raw http request/responses from the tool in burpsuite
* realised that the BASIC http header wasn't filled with the parameters I gave it

but it seems that all this is already fixed in their master branch (just no binary ruby release yet) and found the option to use bleeding edge code for dpl instead.. let's hope that this works.

**Comment by odiea** [comment]
I see it currently has new releases. Keep up the good work.

**Comment by jekkos** [comment]
yes bintray builds are back.. phew

**Comment by daN4cat** [comment]
Yes, let's get Weblate up and running so we can release 3.2.0. I can't wait to close with that story...
