### ISSUE TITLE
Weblate down ?

### ISSUE THREAD

**Issue by caston79** [opensourcepos/opensourcepos#1888]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [NA] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [NA] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: NA
- OSPOS git commit hash is: NA
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

Does anyone know what has happen to weblate ?
http://translate.opensourcepos.org/ is down and http://weblate.jpeelaer.net/engage/ospos to.

/caston

**Comment by daN4cat** [comment]
Yes, @jekkos is aware and hopefully fixing the issue.

**Comment by jekkos** [comment]
Ok I've managed to migrate postgres data to a native install, seems the python env is more or less OK. Last thing to do now is setup nginx as a reverse proxy to wsgi with proper ssl support..

**Comment by daN4cat** [comment]
Sounds good.

**Comment by jekkos** [comment]
OK it's running again on HTTP temporarily,will need to check if all data is fine now

**Comment by caston79** [comment]
👍

**Comment by jekkos** [comment]
Getting closer, got https setup now, just can't commit to repo for some reason

**Comment by jekkos** [comment]
I'm able to enter translations again, however, commit is not working (due to a non existant table). Despite that I executed all the migration (on bleeding edge weblate) now, will check that further when I find time.

**Comment by jekkos** [comment]
Ok this newer version has some shiny new features

* github oauth integration
* google oauth integration
* google translate integration
* should be able to sync language file (just read this from the docs)
* performance seems better with the nginx frontend now (which serves the static files)
* easier to maintain

**Comment by mckaygerhard** [comment]
WoW umm but the "older not-fashion" previous version was working good! why?

**Comment by daN4cat** [comment]
@jekkos somehow the commit is stuck again. I wanted to rebase but got stuck, sorry.

**Comment by jekkos** [comment]
Ok my bad, permission problem on the server

**Comment by jekkos** [comment]
Now the branch is 225 commit ahead?

**Comment by daN4cat** [comment]
It was already like that before I rebased. That's why I rebased. I don't understand why it's like that.

**Comment by jekkos** [comment]
Ok I'll check to see whether these commits are already integrated, but I think they are

**Comment by daN4cat** [comment]
@jekkos I cannot do that much anymore. If I rebase I get an error, if I commit I get and error and etc. :-(

**Comment by daN4cat** [comment]
Weblate seems to work now. I close this issue.

**Comment by tekkeur** [comment]
Still down 😏
