### ISSUE TITLE
system path error

### ISSUE THREAD

**Issue by hdr105** [opensourcepos/opensourcepos#1889]
I am getting this error

"Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php"

error might be there at public/index.php

	$system_path = '../vendor/codeigniter/framework/system';

But I didn't find any vendor folder 

Can you help ?

**Comment by WebShells** [comment]
Please download latest stable released version...

**Comment by mckaygerhard** [comment]
@hdr105 seems do you download the github repository and NOT READ THE README OR THE WIKI!

a rule in linux word its always reading enought before making something.. to have a remote idea what to do

please read the README and when download the proper file use something like 3.1.1 or one month ago..

this issue whould be closed! but there's many problems with that, so i propose make a ready to use (i do myselft) ISO IMAGE LIVE DISK to test and usage of OSPOS

**Comment by daN4cat** [comment]
@hdr105 download the full image from bintray: https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files/ (as indicated in the README).
