### ISSUE TITLE
[fix] provide a ready to use iso image for ospos

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1890]
### Issue / Bug  / Question / New Feature

i noted as a simpel search produce: https://github.com/opensourcepos/opensourcepos/issues?q=is%3Aissue+system+path+error+is%3Aclosed

that install ospos its very dificult .. so due i have very experience with iso live disk i'll provide a ready to use iso download for ospos..

this will solve many issues reported always here again and again and again.. 

features to include:
* complete ospos 3.2.0 (well until the last date)
* complete wiki link offline (inside disk) well english only for now
* devel: php 5.6, mariadb 10.1, mysqlworkbench, 
* webserver maybe will change, but unless apache i'll provide specific docs.. lighty vs apache2
* ide: geany(not i not include eclipse or blob-massive space ide)
* desktop : i choose MATE due are more light rather cinnamon and look are familiar with those from older desktops
* UEFI support? well seems wil be not possible by now, due ospos must run in older environment, my machine of the store its a pentium4 with 512 ram, i not will use my laptop to that ok?

currently i only run ospos with apache2 but when i susessfully able to run in lighty and documented well , i'll only release with lighty.. that's why i not upload yet the new changes in the git wiki here..

**Comment by jekkos** [comment]
Just use docker?

**Comment by jekkos** [comment]
Doesn't really make sense to do this using iso images, docker is exactly made to handle this kind of situation. It should just be a matter of typing `docker-compose up` in the project folder.

**Comment by mckaygerhard** [comment]
umm @jekkos why users send too many issues with install problems if docker are so easy to use? its just another fact! but dont worry was only an idea, 

i ask, can i provide a isos for human people that dont understand and dont have those "docker thins"?

**Comment by jekkos** [comment]
There is the cloud install that leverages docker, right? It's quite easy to go through as that was supposed to be a 'one click' install. Ever tried that one?

**Comment by mckaygerhard** [comment]
when i deploy that cloud install in a stored that no have internet? tell me? and another, in my store i have only a p4 with 512 ram, here lasted firefox dont run so i install debian wheeze with a not so older firefox and ospos runs!

**Comment by daN4cat** [comment]
Feel free to do it in your GitHub repo, create the image for a full installation as you like.

**Comment by mckaygerhard** [comment]
i read the wiki for docker related but there's (apart of ocean's) any other place or to made by itselft a docker and manteneance.. we need better for those also, due as i said: i have some older machines and newers, but i use those newers machines for see HD movies (obviously) and olders for work (due for that we not need powerfull cpu or GPU), that why i ask and point about and iso .. 

i try to made a better wiki for docker installation, but how can i move a already installed docker to a offline machine? @jekkos , @daN4cat?

**Comment by WebShells** [comment]
Mmmm don't know how that would help... Or what advantages it might add...
