### ISSUE TITLE
Migrate away from bower

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#1891]
### Issue / Bug  
 
I have been seeing warnings about bower usage in the build logs lately. Apparantly it's not maintained anymore and to ensure build stability we'll have to migrate to some other dependency management tool.

Different options to consider
* Move to Yarn [(might be fastest but maybe less future proof)](https://bower.io/blog/2017/how-to-migrate-away-from-bower/)
* Move to [npm and webpack](https://medium.com/netscape/bye-bye-bower-or-how-to-migrate-from-bower-to-npm-and-webpack-4eb2e1121a50) (which is my preference)

**Comment by daN4cat** [comment]
One of the next versions....

**Comment by daN4cat** [comment]
https://medium.com/netscape/bye-bye-bower-or-how-to-migrate-from-bower-to-npm-and-webpack-4eb2e1121a50

**Comment by mckaygerhard** [comment]
npm, bower, docker-cloud all "fashioned" way of doint something that must be do the package manager of the distribution... we need something that the os manage not that a guy mantain.. something in witch can trush.. i prefer the package manager , inclusivelly if only has olders versions of the software

**Comment by SteveIreland** [comment]
I'm good with npm and wepack.

**Comment by daN4cat** [comment]
This will replace #975, and yes we discussed back in 2016 that we should move on.... but requires volunteers to take and switch to the new paradigm.

We should switch to npm and webpack indeed. @SteveIreland keen to take this challenge on for 3.3.0?

**Comment by SteveIreland** [comment]
Sure ... sounds like a fun project.  :-)

**Comment by jekkos** [comment]
Think we should combine this one with 
* switching to ES6
* use babel to transpile to ES5
* webpack for minififcation
* npm instead of grunt and bower for the build

**Comment by jekkos** [comment]
Was recently playing around with es6 and I kind of like the new features in there, it could make a lot of code more concise. But maybe we should focus on moving the build itself first.

https://github.com/nefe/You-Dont-Need-jQuery

**Comment by jekkos** [comment]
As demonstrated in #3190 we can keep Grunt for the minifaction and use npm to download the frontend dependencies if they are not available on bower.
