### ISSUE TITLE
session_sha1 is not defined since commit 33cc7e3f

### ISSUE THREAD

**Issue by i92guboj** [opensourcepos/opensourcepos#1893]
I am stuck in commit 395ac217, because the cleanup right after that one is breaking the sales window completely. Concretely, search on write doesn't work at all, and the cursor is not moving into the input field either. Looking as the js console I can see this:

```
opensourcepos.min.js?rel=a3f7c802fe:46 Uncaught ReferenceError: session_sha1 is not defined
    at HTMLDocument.<anonymous> (opensourcepos.min.js?rel=a3f7c802fe:46)
    at k (opensourcepos.min.js?rel=a3f7c802fe:4)
    at Object.fireWith [as resolveWith] (opensourcepos.min.js?rel=a3f7c802fe:4)
    at Function.ready (opensourcepos.min.js?rel=a3f7c802fe:4)
    at HTMLDocument.g (opensourcepos.min.js?rel=a3f7c802fe:2)
(anonymous) @ opensourcepos.min.js?rel=a3f7c802fe:46
k @ opensourcepos.min.js?rel=a3f7c802fe:4
fireWith @ opensourcepos.min.js?rel=a3f7c802fe:4
ready @ opensourcepos.min.js?rel=a3f7c802fe:4
g @ opensourcepos.min.js?rel=a3f7c802fe:2
```

So, please, review 33cc7e3f and do whatever needs to be done or revert it until it's fixed. I can see many changes regarding sha1 in that commit, and in any case reverting to the previous commit fixes it, so there's clearly some problem with that commit.

Maybe the users using barcode scanners didn't notice the problem.

**Comment by mckaygerhard** [comment]
hi @i92guboj do yo sync with lasted master? seems its a really that you not follow lasted changes! or your installation has a cache problem.. 

i cannot reproduce your issue. maybe you are in guindow or do no empty the apache2 cache

**Comment by i92guboj** [comment]
I do the following to update:

`git fetch upstream
git diff master..upstream/master
git merge upstream master`

Then I see this:

`$ git log --oneline
3b411bbe (HEAD -> master, upstream/master) Skip cleanup after deploy
4d8006da Use bleeding edge (dpl) for deploys
a5c797b6 Add API key as travis environment variable
b9bc7583 Change bintray API ke
b84d9d89 Fix Summary Takings including not completed transactions (#1886)
63d9fd21 Revert Giftcard broken fix (#1694)
ddb0e756 Update encrypted travis API key
a24a55f8 Update bstables to 1.12.1 (#1884)
a353068c Fix locale support to Giftcard with decimals (#1694)
442b64d1 Add locale support to Giftcard with decimals (#1694)
8547c3b0 Fix employee form grants regression (#1870)
bf30652a Fix config view tabs errors
7525c650 Total Inv. Retail Price & Quantity
f2ccebc8 Enable https for proxy offloading
5edfed5b Enable https for proxy offloading
8c60d6cd Select full input line on click (#1863)
33cc7e3f Remove the "crap" (#1875)
395ac217 Translated using Weblate (Arabic)`

I am in Gentoo Linux and I have no idea if it could be some kind of cache issue. I suppose I can try a clean copy...

**Comment by mckaygerhard** [comment]
umm ok try those two things:

1. if you use apache2 please clean cache, (i dont know whow that i not use apache2 its slow, either nginx, same problem with cache)
2. try clean copy clone of the git first, then later try the update merge.. but with the "1" first!

report feedback!

**Comment by daN4cat** [comment]
@i92guboj take the latest from bintray and test again.

**Comment by mckaygerhard** [comment]
@i92guboj he has right, if you are using the git source code, must regenerate all the js and css stuff's, if not please use buntray, if the search input dont work, its due you dont have in sync the opensourcepos.min.js file in right sync or generated!

**Comment by i92guboj** [comment]
That makes sense. And. .. how would I go about sync'ing the js stuff? I tried a clean copy and it works indeed. But I'd prefer to keep my old repo because of all the branches and stuff I have there.

**Comment by jekkos** [comment]
I wonder, how do you develop when (saying you have a lot of branches) not knowing how to run a build?
Just curiosity. Otherwise it's just running bower install which will run grunt afterwards.

**Comment by mckaygerhard** [comment]
umm, old repo dont work! quite strange! clean copy work, so maybe the merge conserves some of your changes, try made a repo comparison.  i easyle use meld to compare hole directory...

but, do yo uregenerate again the files as the documentation wiki points? https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#2---how-to-start-develop

about the js's files, i dont have those coplicated things.. i use a hacked direct "made unminified, use forever", when i need some change not able to do by myselft i download the bintray and use the files from the compresed in bintray

**Comment by jekkos** [comment]
@mckaygerhard it's not about making things complicated, it's just the way you setup a build environment  that also makes development easier. You shouldn't commit binary, minified or compilated code to a VCS. This actually relieves you from having to go through merge conflicts in minified files over and over again

**Comment by mckaygerhard** [comment]
yeah, in that part you have right in some way, but some proyects have better way to do so.. 

in any case the wiki explain the part need for that, i hope do that well, if any error are in that let me know to improve it: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#2---how-to-start-develop

**Comment by i92guboj** [comment]
Knowing how to use git has not much to do with knowing a thing about web development, or any development at all. I am a C/C++ guy and I've done a fair amount of coding using these languages, I know some other languages as well, but I don't know a thing about web applications besides some html, css, php and js notions. And I -absolutely- have no idea about codeigniter, grunt, bower or whatever other frameworks and libs you use in opensourcepos. I could learn as I could learn how to handle a helicopter, but I lack the time and interest to do so currently. That might change in the future, but I am quite busy with real life right now.

I use my branches only to do some trivial changes or adjustments on the receipts layouts and stuff like that, or some translation fixes from time to time. Even a donkey like me can do that. I also set up the git repo to be able to make PRs as you suggested me in some other issue I opened time ago.

Anyway, thanks for pointing that out. bower install indeed fixed the issues I were having so we can close this. Sorry for all the noise. I will take note and try to

**Comment by mckaygerhard** [comment]
@i92guboj take easy, i feel just like you.. it's a pain for me more thant you .. that's hwy i write (and i'll improve) the wiki: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#2---how-to-start-develop here there are a link about developmen specific index that you must to read carefully that "easy", i mean try to make it to understand the development here

**Comment by daN4cat** [comment]
so @i92guboj it's better if you download the bintray code for the time being.

Both of you, there is no point to complaint a lot because the more you complaint the less you learn.
Front end development is like that, and we are not even using the latest technologies like Webpack.

Any company doing serious front end development minimises css and js, it's a standard thing.

So instead of writing comments about how much you don't like, spend the time to learn about just googling.

**Comment by mckaygerhard** [comment]
with the issue #1951 users like @i92guboj can made changes and contributions more easyle..
