### ISSUE TITLE
Change Password for Employees

### ISSUE THREAD

**Issue by shifasiddeqque** [opensourcepos/opensourcepos#1894]
i need to create a small functionality where in every employee can change their own passwords without requesting admin to change their passwords.
I tried to create a button with class "modal-dlg pull-left" on the top navigation menu besides Logout Button, However i am unable to click this button from Home Module,
The button works fine when i am in employee module however i don't want to give employees the employee module permission,Please help me
Thanking you in advance
![changepassword](https://user-images.githubusercontent.com/14173981/37638781-904a7b50-2c34-11e8-84de-1ee0edf10674.png)

**Comment by mckaygerhard** [comment]
what so complicated, why not just concatenated to the OSPOS string and set tup individual style ?

**Comment by daN4cat** [comment]
The feature is already implemented, click your name on the top right and the form to change the password pops up.

**Comment by marcellusmontilla** [comment]
Yes it is but as of OSPOS 3.1.1, you need to have access to the employee module to change password. Only the admin can change his password this way, other users can not.

**Comment by daN4cat** [comment]
I need to check this but it should not be restricted.

**Comment by mckaygerhard** [comment]
i confirmed the bug in ospos 3.2.0 @daN4cat see picture

> Yes it is but as of OSPOS 3.1.1, you need to have access to the employee module to change password. Only the admin can change his password this way, other users can not.

i'm afraid that @marcellusmontilla has right i cannot cahnge the password if i not give to user full access to employee module

![cambioclave](https://user-images.githubusercontent.com/1571724/37647967-002b1a28-2c04-11e8-8951-b0a52b456425.png)

**Comment by shifasiddeqque** [comment]
yes that is the problem, we cannot give Employee Module permission to everyone, i just want to create a new Password Functionality where in Employee can change their Passwords.
What i have created works fine from Employee/Sales/Receivings module but i am unable to open Pop up when clicking from Home /Reports/Messages/Storeconfig screens etc
just sharing a
![changepassword](https://user-images.githubusercontent.com/14173981/37655206-a7c0a17a-2c6a-11e8-9476-a51d63ebe4cb.png)
 screenshots

**Comment by daN4cat** [comment]
The solution is not creating something, the solution is fixing the permission. We'll look into this.

**Comment by shifasiddeqque** [comment]
My issue is all together a different issue, Can anybody please help me in doing so

**Comment by daN4cat** [comment]
I meant to say that the password change feature should not require the Employee module permission. That needs to be fixed.

**Comment by shifasiddeqque** [comment]
Yes indeed,Please help me
Thank you

**Comment by odiea** [comment]
When I try this the current password is pre-filled in. Can this be removed.
![2018-03-21 07_51_22-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/37713543-dcf7ec46-2cdc-11e8-9ed3-49c448bf0184.png)

**Comment by jekkos** [comment]
That probably just a matter of disabling browser autofill for that field, rather easy to fix

**Comment by odiea** [comment]
Yes it is. My other browsers do not show that. I think I need to test in private mode. Thanks

**Comment by shifasiddeqque** [comment]
@jekkos Please help me setting up a Employee change password functionality..i cant click the buttton from Home Module.However if i remove the "**modal-dlg**" class from the button,i can click but i need to open it in a bootstrap modal box.it does not show me any error too.

**Comment by daN4cat** [comment]
Fixed and in master. There is no permission allocated, a person should be allowed to change the password whenever they want from everywhere.

Please test and close if fine.

**Comment by daN4cat** [comment]
@shifasiddeqque I don't know why you need to make it so complicated but try my fix and that would do.

**Comment by daN4cat** [comment]
@odiea do you have time to counter check this and confirm it's fine? Thanks.

**Comment by mckaygerhard** [comment]
i can chek too this.. give some time and report feedback

**Comment by odiea** [comment]
I downloaded the latest. It doesn't work for me unless I give the employee employee permission.

**Comment by odiea** [comment]
The following is not related to this commit but how the heck do I get rid of this issue. It only happens when I try to change permissions for certain employees.
![2018-03-25 08_03_52-wedidit _ powered by ospos 3 2 0](https://user-images.githubusercontent.com/10962177/37876004-0fed78a8-3004-11e8-87a1-58864bf8987e.png)

**Comment by mckaygerhard** [comment]
hi @odiea please double chek it's working for me, see:
![changepassword](https://user-images.githubusercontent.com/1571724/37876044-4ab3ae42-3015-11e8-834d-4e62b767aa45.png)

**Comment by mckaygerhard** [comment]
maybe must clean cache webserver, 
**important** please noted the "hardcoded" Submit text for the modal dialog button are not translated.. for future issues, in the link/anchor at the partil/home view

**Comment by daN4cat** [comment]
Right, I forgot the translation. Fixing it.

**Comment by daN4cat** [comment]
Fixed the Submit translation, it was an issue already there but never spotted as I simply copied and pasted the code.

**Comment by odiea** [comment]
Here is what I get after deleting history and in incognito mode when trying to change the password.

![2018-03-25 09_12_35-](https://user-images.githubusercontent.com/10962177/37876646-da82d3da-300c-11e8-8bc4-bb0fbf820b4d.png)

**Comment by mckaygerhard** [comment]
yeah @odiea now it's working for you, in my case work at first time due i not using the horrible apache2 or nginx web serbvers

this issue are resolved and double checked!

**Comment by odiea** [comment]
@mckaygerhard The modal has never failed to work. If you read the lower right you can see that it is not currently working unless employee is granted access to employees.

**Comment by mckaygerhard** [comment]
oh men you have right! i can see the "network" tab.. @odiea , @daN4cat its solved partially.. still need the part when submit the values! the save process are still in the employee controller @daN4cat.. i think if that save process are also in home can mannage the problem?

**Comment by daN4cat** [comment]
hmmmm got it. Never too easy :-(

**Comment by mckaygerhard** [comment]
i have a idea, maybe it's easy:

@daN4cat in the save method of the employee pass a second parameter, that indicates comes from home module, then in the chek of the module permissions of the save method in employee controller, check only if the module are "home" (controller) and wants to chek passowrd only.. with this avoid to duplicate the function in home controller and reuse the code..

seems the problems only happened when fisrt password change ! that's why you have problems @odiea only in your new employees that never changed the password

so the problem are in the checking of modules in the save function of Employees controller, just check if comes from home and that's all

**Comment by odiea** [comment]
seems the problems only happened when fisrt password change ! that's why you have problems @odiea only in your new employees that never changed the password. 
This is not correct. The password has been changed multiple times

**Comment by mckaygerhard** [comment]
ummm @odiea that the only part that check for module permissions in the code.. well i'm done here .. i dont know .. no mre ideas

**Comment by daN4cat** [comment]
Fixing, don't worry.

**Comment by daN4cat** [comment]
OK, it should be fixed now.

**Comment by odiea** [comment]
Works great now. Thanks

**Comment by daN4cat** [comment]
Good, I close.

**Comment by shifasiddeqque** [comment]
@daN4cat Thank you for your kind help!!
i got it working now
