### ISSUE TITLE
[bug] (feat) permit added existing clients are ilogic

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1898]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted 3.2.0
- OSPOS git commit hash is: master
- PHP version is:     5.6
- MySQL or MariaDB version is: MariaDB 10.2)
- OS and version is:    Linux obvously, i used only the better
- WebServer is:     i not used anymore the apachepuach
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

i note an ilogic behavoir, appart of the "change passowrd bug" recently reported:

create new employee and give only two permissions:
* acces to Sales .. due can sel 
* access to sales reports AND CLIENT REPORTS

now that's the funny, i give only access to clients reports.. but no to clients module.. so he cannot manange clients. 

BUT IN THE SALE SCREEN HE CANNOT ADDED A CLIENT! but can access to reports of clients!

i mean that the behaviour of the permission are ilogic due he need search the clients in the sales screen to make invoices... but not necesary this need access to client module!

**Comment by daN4cat** [comment]
The logic is: people to use their brains and allocate permissions in sensible ways.

**Comment by mckaygerhard** [comment]
@daN4cat maybe it not easy to understand, or i not explain clarelly, maybe was like the password employee that cannot cahnge their own passowrd.. but how knows.. until other comes and tell the same!

i mean, in other words, if i dont give permissions to "see" clients, why in reports are showed all the clients names and sales!? who knows maybe "i'm too smart and the earth are spherical"

but well it's working right untils some one report the same as me! as always XD
