### ISSUE TITLE
show costumer email

### ISSUE THREAD

**Issue by sazwan09** [opensourcepos/opensourcepos#1900]
How can i put costumer email / phone on receipt....??

**Comment by daN4cat** [comment]
No sure I get the purpose of this, is for the customer to remember their email and phone number?

**Comment by sazwan09** [comment]
easier for the employee to track or call customer when their is a mistake or for survey....

**Comment by daN4cat** [comment]
But the transaction has the customer name already. This request does not make sense to me.

**Comment by daN4cat** [comment]
BTW, under application/views/sales you can find the receipts, you need to add the customer details there.
Of course the controller/sales.php needs to pass the information but if you check the invoice one probably you can find what of the customer you can access.
