### ISSUE TITLE
Question, how get information for quote?

### ISSUE THREAD

**Issue by josaal17** [opensourcepos/opensourcepos#1902]
### Issue / Bug  / Question / New Feature

I make an invoice for sale on credit, for example with an amount of $ 1500, and in cash I receive $ 500. How can I get the information of that sale for when the client wants to give me a quote?

**Comment by SteveIreland** [comment]
What kind of sales transactions are the problem that you are discussing?  Quotes are technically not something that you should be taking money against.  However, Work Orders which are effectively a promise to do work that is not yet totally defined and which allows money to be collected against it.  I  believe you might be able to record a payment against a quote (although I haven't tested that).  You definitely can against work orders (which are essentially pre-sale documents).  There should be a place for to enter the amount of the payment and the type of the payment.  Then when you are ready to finalize the quote or work order you simply change the type to invoice.

Does that help?

**Comment by josaal17** [comment]
Hi,

The type of transactions I am referring to are, for example, when your business wants to "sponsor" its customers through a loan. A more concrete example, I will sell you 500 packs of rice and have a cost of $ 3000, that amount I can give to you on credit, you pay me initially $ 500 and I give a credit to you for $ 2500 that You can cancel in monthly payments.

Does this system have it or should it be implemented?

**Comment by SteveIreland** [comment]
That sure sounds like a typical invoice accounts receivable scenario, but OSPOS doesn't have an accounts receivable component yet.  All it can do is record the deposit and prepare an invoice for the customer.  (Unless someone has slipped in a post sale payment entry and tracking while I was asleep.)

**Comment by mckaygerhard** [comment]
@josaal17 i implemented a very basic invoice accounts in my fork, very basic and not using the "due" WIP feature , if you have some programming skills maybe it helps and possible complete by you.. for now it prints and employee can see partial payments made to, of course as inteligent this kind of payments cannot be changed

![todolisto](https://user-images.githubusercontent.com/1571724/38355854-13aee306-388c-11e8-8b88-7f23bb56072c.png)

**Comment by mutasaleo1** [comment]
@josaal17 is trying to say how do you enter the remaining $2500 if its going to be paid over more than a months i hope i got that right. I also asked the same question
