### ISSUE TITLE
[bug](integr) weblate auth broken, disable auth integrations

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1903]
### Issue / Bug  / Question / New Feature

the weblate auth has some integration, **the ospos weblate auth are totally broen due two reasons:**

case 1: but unless you do not have a session cookie of some other weblate auth already loaded, will break
case 2: choose "auth with github" and getw again the auth problem broken

**Comment by jekkos** [comment]
Duplicate issue, will close
