### ISSUE TITLE
Email configured as SMTP is not working as expected

### ISSUE THREAD

**Issue by ctorix** [opensourcepos/opensourcepos#1910]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.1.1
- OSPOS git commit hash is:  76a0026
- PHP version is:  7.0
- MySQL or MariaDB version is:  MariaDB 10.1
- OS and version is:  Debian Stretch
- WebServer is:  Apache 2.4
- (If applicable) Docker installation:  N/A
- (If applicable) Installation package for the LAMP/LEMP stack is:  N/A

### Issue / Bug  / Question / New Feature

In ****Store Config > Email**** I set the following email configuration parameters:
****Protocol:****  SMTP
****SMTP Server:****  mail.mydomain.com (tested with my email server)  smtp.gmail.com (tested with my gmail account.
****SMTP Port:****  587 (my server)  465 (gmail)  587 (gmail)
****SMTP Encryption:****  TLS (when using port 587)  SSL (when using port 465)
****SMTP Username:****  my_user_name
****SMTP Password:****  my_password

When I have our company email in ****Store Config > Information > Email**** and I send the customer receipt to one of our company email addresses I get a bounced email on my email server of the following error:
"(reason: 554 5.7.1 <recipient email address>: Recipient address rejected: SMTP Auth is required, or it is a spam with forged sender domain)".

If I leave ****Store Config > Information > Email**** empty and email the receipt to one of our company email addresses I get the email and the headers are:
User Agent OSPOS
Return-Path <ospos.mydomain.com>
Delivered-To company.email@mydomain.com
Received from mail.mydomain.com (localhost.localdomain [127.0.0.1]) by mail.mydomain.com (Postfix) with ESMTP id 87EFE3F0AA for <company.email@mydomain.com>; Wed, 28 Mar 2018 17:49:33 -0600 (MDT)
X-PHP-Originating-Script 33:Email.php
X-Mailer OSPOS
X-Priority 3 (Normal)

When I email the customer receipt/invoice to my gmail account it goes straight to SPAM because it fails SPF, DKIM and DMARC checks.

It does not appear that it's actually sending mail by logging into my email server and sending it from there.  It looks like it's sending mail straight from the OSPOS server to the recipient.

**Comment by ctorix** [comment]
One more piece of information.  When I send it to my gmail account I only receive the email (and as spam) if the Store Config > Information > Email is blank.  If I have the company email in Store Config > Information >Email I never receive the email in my gmail.

**Comment by daN4cat** [comment]
Where is your server running?

**Comment by ctorix** [comment]
It's running on a Linode

**Comment by mckaygerhard** [comment]
your information its no so clear.. there's two possible situations here:

**1** the smtp server of the receip need auth and close configured in bad, so not compatible way:
>When I have our company email in Store Config > Information > Email and I send the customer receipt to one of our company email addresses I get a bounced email on my email server of the following error:
"(reason: 554 5.7.1 : Recipient address rejected: SMTP Auth is required, or it is a spam with forged sender domain)".

this means that your company smtp server needs a expert are not compatible to world welcome.. maybe a paranoic windoser configure it, smtp must be not auth complety.. only for server side senders

**2** in the case of your gmail, you are sending with a differen header so obviously all checks are fail, due for other it's like a spam.. you must paid to gmail to make that and do not rejected, the free solution its own server.. of course experts only

**Comment by ctorix** [comment]
I think I need to clarify my comment about emailing to Gmail.

1) Setup a new customer with a valid Gmail account
2) Complete a sale for that new customer and select to email them the receipt
3) Receipt email goes straight to the Gmail customer's SPAM, if it's received at all, folder because all checks fail

This is while the Store Config > Email is configured to use SMTP and all of the settings for our email server.  If I tail the mail log on the email server I never see an attempted connection from OSPOS to our email server when emailing the receipt to this Gmail customer.

When OSPOS is configured to use SMTP settings for a specific server, is that server not the system used for emailing from OSPOS?  If that's the case, I'm confused why this is an option under Store Config > Email.

**Comment by ctorix** [comment]
I adjusted our SPF record and added in:  a:ospos.mydomain.com

The SPF check now passes, but because it's not actually trying to send the email from our server DKIM and DMARC checks are not applicable.  The receipt emails still go to Gmail's SPAM folder

If I remove our company email from Store Config > Information > Email the Return Path of the email is:  www-data@ospos.mydomain.com

And the email is received directly from my OSPOS server.  Received block of the email header:  Received from ospos.mydomain.com (ospos.mydomain.com. [IP of my OSPOS server] by mx.google.com...

Again, even though I have configured OSPOS to use our email server, it's not attempting that at all and sending straight from the OSPOS server to the customer's email.

**Comment by daN4cat** [comment]
WRT server, I'm trying to understand if it's a machine you run at home/office or it's hosted somewhere. Because the source IP could be blacklisted.
However let me look into this more and come back.
I remember in the past somebody had a problem.

**Comment by WebShells** [comment]
@daN4cat it's something normal I guess if the domain isn't verified... Emails will be received as spam until the domain's risk meter gets low due to people marking email as not spam... Unless if as you mentioned the ip is blacklisted...

**Comment by daN4cat** [comment]
@ctorix please read issue #519. @RamkrishnaMondal got it to work and check the URL he provided.

Also read this and see if it can be of any help: https://www.formget.com/codeigniter-gmail-smtp/

**Comment by daN4cat** [comment]
Also please check your Linode IP is not blacklisted using: https://mxtoolbox.com/blacklists.aspx

It could happen that if it's a shared host another tenant used the IP to spam and therefore your IP is blacklisted.

**Comment by ctorix** [comment]
Thank you.  I checked my server's IP on mxtoolbox and it's not blacklisted.  My day is just getting started and I won't be able to try the other suggestions until later this afternoon or tomorrow.  I'll get back to everyone with the results.  Thank you again for all of the information.

**Comment by mckaygerhard** [comment]
hi @WebShells @daN4cat @ctorix as you said, checks will always fail as i explain, a way to make it work its tell to gmail to "send from another account", go to settings of gmail and in accounts tab configure a alternate mail account.. gmail send a code to your server and later you must accept.. of course you must have a smtp server ...

or a domian to "link" to your gmail account that last its only with paid service

**Comment by ctorix** [comment]
@daN4cat I was able to use the link posted in #519 and email is working as expected now.  Thank you again.
