### ISSUE TITLE
Stock Location name displayed wrong in Employee Form page

### ISSUE THREAD

**Issue by streetlife** [opensourcepos/opensourcepos#1913]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is:    5.6
- MySQL or MariaDB version is:  MySQL 5.5
- OS and version is:  Cent OS
- WebServer is: Apache 2.4
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

After defining multiple stock locations in store config, during employee creation, the default location displays as stock instead of the custom name defined.

![ebunrose limited powered by ospos 3 1 1 1](https://user-images.githubusercontent.com/279971/38129957-1b3435fa-33f9-11e8-8d1e-7606cb8e5360.png)
![ebunrose limited powered by ospos 3 1 1](https://user-images.githubusercontent.com/279971/38129958-1b5b21ec-33f9-11e8-9d1a-795209ffb6a1.png)

**Comment by daN4cat** [comment]
Stock was fixed in 3.2.0 (soon to be released).
