### ISSUE TITLE
please improve README due HUGE AMBIGUOS info

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1915]
hi @jekkos and @daN4cat i proposet a changeset to README file, due as many other issues reported are very large and vage.. so due now wiki pages are more improved i propose a pull request that can be reviewed at https://github.com/opensourcepos/opensourcepos/pull/1914:

the file will look as: https://github.com/mckaygerhard/opensourcepos/blob/e129787064fb5b8223c742be2a69cdc8742cc5c2/README.md

take in consideration that i made those changes:
*  Improve the README and update link, to more seriusly
* points to a complete feature datasheet
* update link of bintray due lasted buntray modifications for proper sort files
* remove **very infantile marks about "chase up"**  (where are the lawyers and police?)
* improve the LICENSE points and limitations
* links to the documentations and installations
* simplified the README due are very large and too ambiguous see opensourcepos#1875 (comment)
* prepare for explain difference between bintray and release

i hope other users like @objecttothis @SteveIreland and @odiea reviewed and disscuss that changes specially those like "remove **very infantile marks about "chase up"**  (where are the lawyers and police?)" and the "simplified the README due are very large and too ambiguous see opensourcepos#1875 (comment)" changes...

**Comment by mckaygerhard** [comment]
issues #1921 , #1922 , #1923 are due a very ambigous readme file, **extremedy larrgeee with very basic information about install ...**  for a so large file no?

**Comment by daN4cat** [comment]
Improved
