### ISSUE TITLE
Breaking news: Amazon to buy OSPOS code

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#1916]
After many months of negotiations with Amazon, we are pleased to announce that Amazon put forward an offer to buy Open Source Point Of Sale code.

After having analysed several commercial POS software on the market, Amazon recognised the impressive innovation OSPOS solution brought to the market, and they want to roll out the software to their high street shops.

@jekkos, @daN4cat, @odiea, @SteveIreland and @objecttothis will receive 10000 chocolate eggs each in compensation.

Impressions from odiea in his own words: "This is fantastic news, I can now retire and go on holidays in central America with my chocolate eggs and relax after years of testing. I already bought 10 fridges from Amazon to store all the eggs in my private resort".

Comment from jekkos: "It was a hard negotiation because Amazon wanted to give us Swiss chocolate and I couldn't accept it. In the end they agreed to give us 100% Belgian chocolate eggs".

Comment from daN4cat: "I was expecting crypto choco currency but given the recent drop in value of crypto currencies I'm happy with the deal".

SteveIreland and objecttothis were unavailable for a comment, the last news was that they were seeking medical advise after the excesses of a choco party last night.

**Comment by odiea** [comment]
Thanks for the holiday wishes.

**Comment by odiea** [comment]
I did a short sell on my egg stock and was able to purchase the following property.
![img-20150520-wa0004](https://user-images.githubusercontent.com/10962177/38171063-fb9a0c5e-354e-11e8-9172-6720e96c012f.jpg)

**Comment by objecttothis** [comment]
Happy Easter/April fool's to you too buddy. Make sure you cut me in ;)

**Comment by jekkos** [comment]
You caught me there on the issue title ;) Plenty of chocolates here indeed. Happy easters!

**Comment by dvidic** [comment]
Can objecttothis object to this?

**Comment by objecttothis** [comment]
Touche. ;)
