### ISSUE TITLE
Remove some unused language files

### ISSUE THREAD

**Issue by vnwildman** [opensourcepos/opensourcepos#1918]
Following files seem aren't used by new version (3.2.0) of OSPOS:

- enum_lang.php
- form_validation_lang.php

If this is true, please remove them. If not please add them to weblate.

**Comment by mckaygerhard** [comment]
i think the files will be deleted depending of the vendors and the dependency needs.. seems by example "form_validation_lang.php" are part of the codeigniter framework.. so this issue probably will be closed

**Comment by jekkos** [comment]
OK let's check if it's present in english first..
