### ISSUE TITLE
Docker post-install (local, not digitalocean): Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

### ISSUE THREAD

**Issue by AlpNek** [opensourcepos/opensourcepos#1921]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: Latest on github
- OSPOS git commit hash is: 4d46da7
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) 7.0.15-apache (from Dockerfile)
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 10.1.21 (from docker-compose.yml)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Ubuntu bionic
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) apache2
- (If applicable) Docker installation: Docker version 17.03.2-ce, build f5ec1e2
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

After docker-compose build and docker-compose up, cannot load the login page. Tried various URLs: localhost, localhost/public etc but I get the following error:

Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

I have installed codeinsighter as well and changed $system_path variable in public/index.php accordingly to point to "system" directory of codeinsighter.

**Comment by mckaygerhard** [comment]
please what install process or how to (with link please) do you follow?

seems the "vendor" directory of codeigniter does not have filled!

**Comment by jekkos** [comment]
Did you start the container from a bintray build? If not then you'll need to build the project first.

**Comment by AlpNek** [comment]
Thank you for quick replies.

I used the install instructions on GitHub on how to use with Docker.

Basically, I cloned the repo, ran docker-compose build and then
docker-compose up. There are no further instructions on GitHub project page
after that. Am I missing something that I didn't read?

Thanks.

**Comment by mckaygerhard** [comment]
please @AlpNek what exact github page do you follow as instructions!? to try to follow same instructions and try to reproduce your problem, so then i try also to make a better install wiki page!  and i repeat README file must be reorganized as i proposed in #1914 

as i described in pull #1914 @jekkos the README links, points to a "ambigous" instructions in wiki page, also the remaining "docker" instructions need improvements at the wiki, i try to improve the build deploy at my linux install but i'm not so much interested in overhead already existing process (httpd and mysql)

i made a index install wiki (WIP) but the docker instalations need furter details.. not only "tips" as the "mantain a docker" wiki suggest

**Comment by jekkos** [comment]
Ok indeed it might not be very clear that currently the github repo is not building except through travis. If you want to build using docker you can check .travis.yml for the exact sequence of commands.

Or easier would be to download a prebuilt zip from bintray and then launch docker-compose from that folder which should work right away.

**Comment by AlpNek** [comment]
Thanks, I'll try that.

**Comment by jekkos** [comment]
Added the build instructions in the readme now.

**Comment by mckaygerhard** [comment]
the README need organization! its pretty large, the projects always have a SEPARATE INSTALL file! do you know?

**Comment by jekkos** [comment]
Ok might make sense to move some information to an INSTALL.md indeed.

**Comment by mckaygerhard** [comment]
@jekkos take in consideration i noted the very limited capacity to see users by you guys, i can made a base pull request with a distro agnostic INSTALL file usefull for any OS/php combination, due i have some skill to understand the user position, i noted that you guys do not understand the very specific environment need by ospos that users don't understand..

**Comment by daN4cat** [comment]
Ha ha ha, such a bozo.

**Comment by mckaygerhard** [comment]
interesting @jekkos seems @daN4cat don like my "facts" ancl close, locket and silence my pull abour readme file... well no problem @daN4cat the project are openclose right? i 'm patiente, very..

i have very respect, due many "information" are "out" due that kind of movement but dont worry men! i not that kind of person! good for you i'll always collaborate...

**Comment by WebShells** [comment]
@mckaygerhard we are all here trying to help... @daN4cat as everyone can see had done alot to this project... Please stop mis-leading childish replies and lets work as a team...

**Comment by mckaygerhard** [comment]
until the last problem with migration was not "childish" well i try to do myselft sometingh but i not the only "unhappy here" but the only with voice (still)...

**Comment by jekkos** [comment]
Maybe next file to add is code of conduct for this project.. just a matter of getting contributors aligned on do's and donts

**Comment by WebShells** [comment]
I Agree, will take care of that file ;p !

**Comment by mckaygerhard** [comment]
so then @WebShells : "who watches the wachmens?" very funny a "guideline" file! for who's?

**Comment by daN4cat** [comment]
@mckaygerhard guess who?
