### ISSUE TITLE
Error: Too Many redirects

### ISSUE THREAD

**Issue by rfmperkins** [opensourcepos/opensourcepos#1922]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:    5.6.35
- MySQL or MariaDB version is:     MySQL 5.6.38
- OS and version is:   CentOS 7.4 / cPanel 68 Build 36
- WebServer is:   Apache 2.4.33
- (If applicable) Docker installation: N/A
- (If applicable) Installation package for the LAMP/LEMP stack is:   N/A

### Issue / Bug  / Question / New Feature

Firefox, Chrome, and Safari are giving an error about to many page redirects, This is the link in the address bar:   Domain.TLD/ospos/public/index.phppublic/?/index.phppublic/

**Comment by mckaygerhard** [comment]
what how to or installation rules do you follow? seems do you not proper configurre the "very complicated" htaccess rewrite rules

**Comment by rfmperkins** [comment]
This was installed by softaculous in December 2017 and has been working until today with zero changes to the software.

**Comment by mckaygerhard** [comment]
oh men please! ovbously the problem it not ospos! give a break!

**Comment by rfmperkins** [comment]
except it just happened on a fresh install also, if you do not want to be helpful mind your own business you do not have to reply

**Comment by mckaygerhard** [comment]
wel @rfmperkins  as you said, until some days ago iwas always working, and if always install same verion working and suddeendly not working the problem obvious it's with someting in your hosting provider

**Comment by rfmperkins** [comment]
@mckaygerhard Nothing has changed on the server I own the and control all of it, so please move along

**Comment by mckaygerhard** [comment]
with the most respectfully intentions , well @rfmperkins  as you said, until some days ago i was always working, and if always install same version working and suddenly not working the problem obvious it's with something in your hosting provider

taking in considerations tht ospos version that you used/install/use do not change! the problem it's not in that piece!

**Comment by daN4cat** [comment]
Wait for 3.2.0 to be released by this weekend and see if the issue goes away.
BTW how did you use softacolous to install OSPOS? Do they provide OSPOS as part of their library?

**Comment by WebShells** [comment]
@daN4cat yes it is part of softaculous library provided with instant setup... That might help alot of users I guess...

**Comment by daN4cat** [comment]
Ok but we don't support that. I will look into it as it's the second report but those guys should sort it out.

**Comment by WebShells** [comment]
@daN4cat was discussing with @jekkos regarding this point... Trying to find suitable solution that might be helpful for some....

**Comment by WebShells** [comment]
@rfmperkins check if cpanel issued any updates and forced it to your box... Maybe or it's related to that :)...

**Comment by mckaygerhard** [comment]
yeah @WebShells as i suggests!

**Comment by daN4cat** [comment]
Well softacolous is a paid service, it also lists as support website for OSPOS another web site: https://www.softaculous.com/apps/ecommerce/Open_Source_Point_of_Sale

I would say, @rfmperkins get in touch with those guys since you pay for their service. They need to sort this out.
