### ISSUE TITLE
The installation is not correct, check your php.ini file.

### ISSUE THREAD

**Issue by nipponsan** [opensourcepos/opensourcepos#1923]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: 
- PHP version is:      7.0
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

### Issue / Bug  / Question / New Feature

hello.. I have installed OSPOS using Softaculous in ifastnet free hosting.. its all done until I cant login and it said " The installation is not correct, check your php.ini file. "

what I know that I need to enable the sockets extension and its not been allowed in free hosting.. and support said I need tu use "fsockopen" function.. how can I enable it?

**Comment by daN4cat** [comment]
Wait for 3.2.0 version to be released, it should by the weekend.

**Comment by mckaygerhard** [comment]
@daN4cat this will not be solved by "removing the mcrypt" only, need further more advanced, @nipponsan this problem it's due vendors in free hosting have many php version to choose, so a better explain must be done for users right? due there's many changes with php 5.X respect php 7.X that due the requirements in ospos does not fit well as i explain in #1921 and n #1914 right?

**Comment by mckaygerhard** [comment]
i forgotten to added that on all free hosting except those very olders sockets and curl are not available any more!

**Comment by daN4cat** [comment]
softaculous is a paid service that has nothing to do with us.

@nipponsan I'm afraid you need to get in touch with softaculous and ask them to sort your issue out.

**Comment by thearafat** [comment]
open source pos not login see this massage 'The installation is not correct, check your php.ini file.' please all friends help me????
