### ISSUE TITLE
(bug) migration errors bad redirect in login process

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1927]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted (7 hours ago from this point, bintray)
- OSPOS git commit hash is: 
- PHP version is:     5.6
- MySQL or MariaDB version is:     10.2
- OS and version is:     Linux debian 8 or debian 9 or docker
- WebServer is:    apache 2.4

### Issue / Bug  / Question / New Feature

The firts login will failt due lasted migration code, seems also related to issues #1922 , due the login process staled or try to redirect again, here the error log:

```
[Thu Apr 05 10:29:12.509978 2018] [:error] [pid 7836] [client 127.0.0.1:58525] PHP Fatal error:  
Cannot redeclare class Migration_Upgrade_To_3_2_0 in /var/www/html/application/migrations/20180225100000_upgrade_to_3_2_0.php on line 0, 
referer: http://127.0.0.1/public/index.php/login
[Thu Apr 05 11:20:05.151847 2018] [:error] [pid 7056] [client 127.0.0.1:58946] PHP Fatal error:  
Call to undefined function execute_script() in /var/www/html/application/migrations/20170501150000_upgrade_to_3_1_1.php on line 12, 
referer: http://127.0.0.1/public/index.php?
```

**Comment by mckaygerhard** [comment]
hi @jekkos there's another error happened in some veruy specific situations, but i not paste here due i not have still the log to investigate it

**thanks to take attention @jekkos some guys here do not have a child like actitude!**

**Comment by mckaygerhard** [comment]
the commit 1b0eb0d936d6f08d5560aeaadb8dc54f2e331939 solvet the redeclaration class problem, but still need about the  undefined function execute_script(), some instance problem i think!

**Comment by mckaygerhard** [comment]
@jekkos  no! its the helper autoload, you loaded the library only, still need the helper!

**Comment by mckaygerhard** [comment]
now working!

**Comment by mckaygerhard** [comment]
need to instanciate the $CI object and do not use directly the $this in the migration from 3.1.1 to 3.2.0 sorry for the noise but i was testing hurry due i'm at work!

that is the new error now due taht:

```
[Thu Apr 05 12:07:03.251035 2018] [:error] [pid 8466] [client 127.0.0.1:59136] Migrating to 3.1.1, referer: http://127.0.0.1/public/index.php?
[Thu Apr 05 12:07:03.251164 2018] [:error] [pid 8466] [client 127.0.0.1:59136] PHP Fatal error:  
Using $this when not in object context in /var/www/html/application/helpers/migration_helper.php 
on line 22, referer: http://127.0.0.1/public/index.php?

```
due need the $CI  be instanciated and then later use the db-simplequery with $CI->db (i think)

**Comment by daN4cat** [comment]
$this / $CI issue solved

**Comment by mckaygerhard** [comment]
now works! thanks @daN4cat see that i try to contribute too!
