### ISSUE TITLE
minor duplicate SQL errors with PK with lasted migration fixed

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1928]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: lasted with migration fixes
- OSPOS git commit hash is: lasted
- PHP version is:   5.6
- MySQL or MariaDB version is: 10.2)
- OS and version is:    obvious is linux
- WebServer is:     apache 2.4

### Issue / Bug  / Question / New Feature

seems ther's a little problems now with migration fixed, database show some problems with insertions/updates, see error log (not pasted compelte, too many):

```
[Thu Apr 05 13:03:59.442291 2018] [:error] [pid 8467] [client 127.0.0.1:59217] 
error: Duplicate entry 'quote_default_comments' for key 'PRIMARY', 
referer: http://127.0.0.1/public/index.php/login
[Thu Apr 05 13:03:59.442300 2018] [:error] [pid 8467] [client 127.0.0.1:59217] 
Migrated to 3.2.0, 
referer: http://127.0.0.1/public/index.php/login
```

seems the issue reported in #1861 are not invalid.. but i dont found any reason why this are happened

**Comment by SteveIreland** [comment]
The quote_default_comments is a configuration value that the migration script is trying to add, but the error occurs because it already exists.  I would normally ignore it unless there is reason to believe that the migration script isn't completing.

If the migration script isn't completing (and as a result keeps trying to rerun) then there are two choices.  First, maybe the migration script has already run and needs to be removed or secondly, if it hasn't run then you might try deleting the "quote_default_comments" from the config file and letting it try again.

**Comment by daN4cat** [comment]
Just ignore they are no harm and neither relevant to you.

**Comment by mckaygerhard** [comment]
??¡¡¡ "not harm and neither relevant to you" ??? what that's means? @daN4cat ?

@SteveIreland thanks for suggestions, i remove the PK conflicts some tries ago, and still are produced! i mean, i manually do that you suggest and still i have that problem in each login!
