### ISSUE TITLE
Link to selected customer does not show name

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#1929]
No idea why exactly this shows when a customer is selected. I guess it should be the name instead of the edit link URL

![schermafdruk van 2018-04-06 09-28-41](https://user-images.githubusercontent.com/576234/38408256-0fe7073e-397d-11e8-9d1e-10005d31d7ef.png)

**Comment by daN4cat** [comment]
Works fine for me and other people tested at the time and confirmed it's fine.

Is there any unusual with that Customer name? Have you merged something?

**Comment by marcellusmontilla** [comment]
Maybe the url is really the "name" in the database. That would be funny. :)

**Comment by daN4cat** [comment]
The code looks fine to me:

```
			<?php
			if(isset($customer))
			{
			?>
				<table class="sales_table_100">
					<tr>
						<th style='width: 55%;'><?php echo $this->lang->line("sales_customer"); ?></th>
						<th style="width: 45%; text-align: right;"><?php echo anchor('customers/view/'.$customer_id, $customer, array('class' => 'modal-dlg', 'data-btn-submit' => $this->lang->line('common_submit'), 'title' => $this->lang->line('customers_update'))); ?></th>
					</tr>
```

**Comment by daN4cat** [comment]
The only option is for the Sales controller to set the wrong string, here the code:

```
			if(isset($customer_info->company_name))
			{
				$data['customer'] = $customer_info->company_name;
			}
			else
			{
				$data['customer'] = $customer_info->first_name . ' ' . $customer_info->last_name;
			}
```

I would say that somehow in company_name there is a URL instead of empty or else.

**Comment by jekkos** [comment]
Ok should be fixed now.
