### ISSUE TITLE
system directory missing

### ISSUE THREAD

**Issue by ChandhruSekar** [opensourcepos/opensourcepos#1930]
$system_path = '../vendor/codeigniter/framework/system'; 
vendor folder is missing...

**Comment by jekkos** [comment]
Please read INSTALL readme properly. Either download bintray or latest zip release.

**Comment by jekkos** [comment]
I've added this to first point in FAQ (as it is I think by now top 1 in the FAQ indeed). So hopefully this will reduce this kind of issues created here.

**Comment by mckaygerhard** [comment]
hi @jekkos i dont thinks so.. the install instruction are so ambiguos, the time will give me the reason!

**Comment by mckaygerhard** [comment]
documente distro agnostic as possible now in the wiki for docker, local and cloud flavors.. 
https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-Getting-Started-installations
