### ISSUE TITLE
uncomplete russian translations, we can help due there's many strings emtpy, but lasted session others "are working"

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1932]
seems @nerv55 have knowledge of russian, me have limited but i can read,  @jekkos seems too but are busy, release of 3.2 will be and still people like those can made something (last session other people was working but.. still some strings are missing or need in russian)

**Comment by mckaygerhard** [comment]
seems #1759 dont kwon about it

**Comment by nerv55** [comment]
@mckaygerhard I have tried  weblate, man does not work, Can I just submit File to Main Repo With the Russian Strings.

**Comment by daN4cat** [comment]
Russian is being translated as we speak, no need to create more tickets and noise.
@objecttothis is taking care of this part.

**Comment by daN4cat** [comment]
@nerv55 I checked Weblate and works with no issues. You can contribute to the translations if you are a native speaker.

**Comment by nerv55** [comment]
@daN4cat  thanks, I have just tried now but no luck so far.

![weblate](https://user-images.githubusercontent.com/26050096/38515848-6f8b36dc-3c03-11e8-8587-0d1c0e0e82ae.png)

**Comment by mckaygerhard** [comment]
O.o imo! monkeys!? be carefull, "it's working", please men, we just try to contribute!

**Comment by daN4cat** [comment]
Works for me, not sure which way you are trying to login but I don't use GitHub connector:

![image](https://user-images.githubusercontent.com/636048/38517269-48f8fd0a-3c31-11e8-8211-5924e231f409.png)

**Comment by nerv55** [comment]
@daN4cat  yes that must be, I'm using git connect, thanks for clarifying that.

**Comment by mckaygerhard** [comment]
umm maybe it' better remove those buttons?, last try output a lot of sensible information @daN4cat , well it's just a suggestion only.

**Comment by nerv55** [comment]
@daN4cat  I'm in at last

**Comment by jekkos** [comment]
oauth connectors arent working for the time being.. just use regular login

**Comment by nerv55** [comment]
russian translations are complete

**Comment by mckaygerhard** [comment]
i can see the commits, seems the context are correct now! i 'll test in live demo at my side and report feedback
