### ISSUE TITLE
(bug) in sales the involved table dont get back after a un-suspend

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1934]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

as discuss in comment https://github.com/opensourcepos/opensourcepos/issues/1933#issuecomment-379501678 in sales the involved table dont get back after a un-suspend

**Comment by daN4cat** [comment]
I tested with 3.2.0 and works fine.

**Comment by mckaygerhard** [comment]
There's no bug: @daN4cat describe the right process in that comment: https://github.com/opensourcepos/opensourcepos/issues/1933#issuecomment-379550108 thanks

**Comment by mckaygerhard** [comment]
if you put more tables like I did, they just disappear, if you can try it with 6 tables and you will see it. another issue closed in hurry! see https://github.com/opensourcepos/opensourcepos/issues/1933#issuecomment-379600903
