### ISSUE TITLE
Sub categories in sales 

### ISSUE THREAD

**Issue by GurlWhoCodesAlot** [opensourcepos/opensourcepos#1936]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS version is: 3.1.1

OSPOS git commit hash is: dont know, softacolous installed it

PHP version is: 7.0.28

MySQL or MariaDB version is: 5.6.38

OS and version is: linux

WebServer is: apache

Selected language is: ENGLISH

(If applicable) Docker installation:

(If applicable) Installation package for the LAMP/LEMP stack is:
### Issue / Bug  / Question / New Feature
Question:
I want to organize items on category and sub categories so when I go to sales model, a drop down of categories pop up and when I select the category all its child pop up leading my to the item finally. Can we do this in current implementation? 
Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by WebShells** [comment]
@nisaanwaar do you count this as a filled in form :/?

"Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:"

Please read before submitting issues randomly...
Thanks

**Comment by nisaanwaar** [comment]
@WebShells  Apologies, somehow while submitting my browser was refreshed and just submitted unedited form. Question updated now

**Comment by mckaygerhard** [comment]
well @WebShells i think the template its complet unfriendly! its natural the many issues comes without that chekboxes unfilled right @GurlWhoCodesAlot ?

**Comment by WebShells** [comment]
@GurlWhoCodesAlot please check #1859 as a reference, this issue was already discussed... I guess this thread should be closed... 
@mckaygerhard i guess lazy people are just skipping the template... and its clear they doesnt even take a look on the already solved or being discussed issues... 
The template helps us alot in trouble shooting...

**Comment by daN4cat** [comment]
Close as duplicate.

**Comment by mckaygerhard** [comment]
@WebShells i understand the part of lazy people, but think about it! must be bidirectional, as any of the ospos developers have important time, users already have important time! do  you think a normal use will debug and find the error reported on restaurant tables? (that suppost to are "fine"?), no! users only said "dont work" due its just "users", so those epople that comes and make a great effors to report, with your actitude make getting away! slowly of course!

**Comment by mckaygerhard** [comment]
@WebShells i understand the part of lazy people, but think about it! must be bidirectional, as any of the ospos developers have important time, users already have important time! do you think a normal use will debug and find the error reported on restaurant tables? (that suppost to are "fine"?), no! users only said "dont work" due its just "users", so those epople that comes and make a great effors to report, with your actitude make getting away! slowly of course!

there's a lof of more complex project in github that the issue templates get more friendly , also README, i put examples in recent commits.. 

right @GurlWhoCodesAlot ?

**Comment by GurlWhoCodesAlot** [comment]
Well clearly @WebShells  you have got a problem in talking directly. 
To your surprise i did a search for keywords of "displaying items in sale" and "categories list in sales" and found nothing. 
and to top it off, the blank template was posted because of normal "HUMAN ERROR" and my phone's sudden browser refresh (which i suppose you are not, otherwise you would got my point earlier. )
Now that you have referenced a similar issue, can you please tell my how can i show a dropdown list (with sub categories as nested list and items in the end) of categories ?
i cant really wait for nxt release!
