### ISSUE TITLE
Nested Dropdowns

### ISSUE THREAD

**Issue by GurlWhoCodesAlot** [opensourcepos/opensourcepos#1938]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

Installation information
OSPOS version is: 3.1.1

OSPOS git commit hash is: dont know, softacolous installed it

PHP version is: 7.0.28

MySQL or MariaDB version is: 5.6.38

OS and version is: linux

WebServer is: apache

Selected language is: ENGLISH

(If applicable) Docker installation:

(If applicable) Installation package for the LAMP/LEMP stack is:
### / Question 
I have a list of categories and items which fall in that category, my question is how can i display the categories first and on hover over a specif category show items of that category? 
I basically want to know how can i use/implement nested drop downs in ospos. 
Can i include bootstrap plugin of dropdown?
Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by WebShells** [comment]
@daN4cat shall we close this :D ?

**Comment by mckaygerhard** [comment]
@WebShells no more jokes, the template its terrific complex! and the question are good formulated, do waht you wnat guys, but seems there's no professional "answers" here!

**Comment by daN4cat** [comment]
I'm tempted to add a checkbox in the template: if you are not a monkey tick this checkbox. Let see what happens :-)

**Comment by daN4cat** [comment]
To answer the question, maybe you can have a look into the detailed sales/transaction report. You can adopt the same approach, list the categories as main parent entry and clicking the + you open the second level with all the items listed.
However I would not take the report code as it stands because paging is not managed server side, so you end up pre loading a lot.

**Comment by GurlWhoCodesAlot** [comment]
@webShells I am wondering where do you see incomplete form..since I filled what I know and I have no idea about docker and lemp. So please take some time and clarify what effort it takes into simply replying to questions and not farguing over petty issue like a teenage girl. 
@dan4cat I hope you wouldnt lock this one too, since this is plain bullying by other member.

**Comment by GurlWhoCodesAlot** [comment]
@dan4cat  also I would suggest you to conver these into an 'When posting I agree to below clauses' rather than having people check on every line. I just read that I am supposed to individually check all those clauses -_-

**Comment by GurlWhoCodesAlot** [comment]
referring to your answer, @dan4cat I made some changes in register.css to add dropdowns and bootstrap dropdown..they aint reflected. is there anything I am missing?

**Comment by mckaygerhard** [comment]
@GurlWhoCodesAlot there's many suggestions on the template issue, but none comes here alive! many git proyect have less complicated issue templates and inclusive made more complex projects rather thant this!

**Comment by daN4cat** [comment]
@mckaygerhard well it will stay and get on with that, also cut the constant ranting because it's really too much and does not bear any fruit.

**Comment by daN4cat** [comment]
Change css to add dropdowns? Maybe you should start from adding the code for that before getting to css?

**Comment by WebShells** [comment]
@daN4cat I had the same thoughts... Ddnt want to get myself into another bla bla conversation..

**Comment by GurlWhoCodesAlot** [comment]
@webshells were you the first one to start this bla bla here?

**Comment by GurlWhoCodesAlot** [comment]
@dan4cat I have added the code obviously! I am changing register.php and added new stylle classes in register.css the style changes haven't reflected! 
I dont know this forum is for help or criticizing others who ask questions!

**Comment by daN4cat** [comment]
Have you checked current instances of dropdowns in the code to take inspiration?
They don't use css and those use a bootstrap js plugin.
Assuming you want to go for that approach, but to be honest I struggle to understand what you are trying to achieve because in your original question you wanted to hover over the category and get a list of items.
There is a tooltip feature available, maybe that could do instead it you list the items in it?

**Comment by GurlWhoCodesAlot** [comment]
I qant to remove the search of items from sales and instead add a dropdown of categories which will have their items nested in them so user doesnt have to search by item name and can track the items by categories. 
I tried using form_dropdown and it display nested items as multiselect and didnt show nested objects either.
Are you talking about some other dropdown instance I dont know of?

**Comment by daN4cat** [comment]
Check the sales register code, dropdowns are used there. Good luck with your feature implementation.

**Comment by mckaygerhard** [comment]
@GurlWhoCodesAlot that idea sound great! why not a popup modal dilg ? and when selects finish, off and show the register sale complety fill with the items?

**Comment by GurlWhoCodesAlot** [comment]
@dan4cat I have already checked it, those are simple dropdowns and I need multilevel dropdowns.. when passing nested json to the current dropdown functions it shows them are multiselect in one level dropdown..all I am asking is what could be the reaaon of my css change not being reflected?

**Comment by GurlWhoCodesAlot** [comment]
@mckaygerhad thought of it before..that seemed like a longer implementation than dropdowns. Do we have any popups already being used this way?

**Comment by mckaygerhard** [comment]
well at the reports controllers there's a lot, and i try to explin how to make dlg link here: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#how-to-invoke-a-function-with-anchor-as-a-modal-dialog maybe it helps, umm now, how to take the items selected and return to the sale register object may need use the $CI session object manipulation and the sales lib functions..

**Comment by mckaygerhard** [comment]
about multilevel selects box, with those dlg still will need, so then maybe (due i assume ospos used jquery that i hate) you @GurlWhoCodesAlot must see some at the jquery documentation

**Comment by mckaygerhard** [comment]
another solution its use the https://github.com/Symphony9/pickathing for those

**Comment by odiea** [comment]
I am asking is what could be the reason of my css change not being reflected? I believe you must make your css changes to master then run composer to set your new css changes. The way to change them in the bintray zip file. 1 create a style.css in the public/css. Then go to sales/views/partial/ header and give the location for the style.css file. I have found that this was the easiest way to add or change .css files. Copy the contents of the register.css to style.css and your changes should now show.

**Comment by GurlWhoCodesAlot** [comment]
@odiea thats the issue, i dont know how to build/run composer. 
i am going to try adding new css and in header and that should reflect my changes without build..right?

**Comment by mckaygerhard** [comment]
yes @GurlWhoCodesAlot  and it's very less complicated

**Comment by WebShells** [comment]
Done the job? It's true what he is requesting is based on jquery...

**Comment by daN4cat** [comment]
@GurlWhoCodesAlot, we use this bootstrap js plug in for the dropdows: https://silviomoreto.github.io/bootstrap-select/

There is no the multiple drop downs (like the menu) type of functionality.
I guess you want something like this: https://jsfiddle.net/chirayu45/YXkUT/16/

If you really read the wiki you could have spotted this: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Environment-Development

In order to add a js plugin and add your changes to css, and to get all bundled in the .min forms you need to add the js plug in to bower.json and run bower install, then run grunt and etc.

This is because OSPOS uses at the moment bower and grunt. Maybe one day we switch to webpack and it will easier/different.

**Comment by daN4cat** [comment]
I close this because you have all the info you need. It's a matter of playing and reading online documentation now.

**Comment by mckaygerhard** [comment]
Good information @daN4cat thanks..

**Comment by mckaygerhard** [comment]
with issue #1951 maybe future contributions could be more easyle, due css and js edition can be on the fly,so i refers here due as every noted event use the wiki for docs development the issues are using always
