### ISSUE TITLE
how to install: php-gd,php-bcmath,php-intl,php-sockets,php-mcryptand php-curl on windows

### ISSUE THREAD

**Issue by Alrawi221** [opensourcepos/opensourcepos#1944]
Please tell me detail how to install and enable: php-gd,php-bcmath,php-intl,php-sockets,php-mcryptand php-curl on windows

**Comment by SteveIreland** [comment]
http://php.net/manual/fa/install.windows.extensions.php

**Comment by daN4cat** [comment]
Please use StackOverflow you'll find answers to your questions more easily than posting here.

**Comment by Alrawi221** [comment]
thank you so much..

2018-04-13 20:56 GMT+03:00 FrancescoUK <notifications@github.com>:
