### ISSUE TITLE
OSPOS latest version

### ISSUE THREAD

**Issue by StanlySimon** [opensourcepos/opensourcepos#1945]
Is the latest version released in softaculous ?

**Comment by mckaygerhard** [comment]
obviusly not, take some time and softaculus are not supported, use the wiki instructions and a supported environment

**Comment by mckaygerhard** [comment]
wiki was improvement and have better documentation and not vage references please read them, installation steps are in: https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-Getting-Started-installations take in consideration that

**Comment by StanlySimon** [comment]
Ok will do that

**Comment by daN4cat** [comment]
Just to be clear, we have nothing to do with softaculous.

**Comment by mckaygerhard** [comment]
i pointing that in the response.. and umm maybe i must also point that in the wiki.. i'll do !
