### ISSUE TITLE
IMPORTANT: To all EU area OSPOS users, please be aware of GDPR (25/05/2018)

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#1949]
This applies to EU area users mainly, any other company storing EU citizens information should be aware of this too.

As you know OSPOS offers a Customers CRM capability, a means to store data about your customers.

OSPOS does not enforce any privacy policy, which means that data entered in OSPOS is assumed to be collected and managed according to any privacy law covering your country.

In case of GDPR, it's required the explicit consent of the customer in order to allow you to capture and store their data. That means before you enter your Customer data in OSPOS you need to have their consent and the explicit consent record needs to be retained. That's not something OSPOS can do for you.

GDPR also requires that if a Customer asks to be removed all the data needs to be removed.
Currently OSPOS just soft deletes the Customer to retain the information of who you sold to in past receipts.

There is even the part related to Mailchimp connector, but you need to read Mailchimp information about GDPR on their web site.

It's a tricky matter and please get informed and decide by yourself whether the Customer feature of OSPOS is fine for your GDPR needs or not.

As OSPOS developers we don't bear any responsibility and neither liability on the matter, we cannot make any promise of compliancy.

**Comment by daN4cat** [comment]
One option to improve the matter with regards to GPDR would be to add a checkbox in the Customer view (and spreadsheet import) confirming that the user gave consent to store their data. That would match a Mailchimp field (if my memory is right).

Also I could probably add the feature of scrambling the user details when deleted to avoid any issue.
That could be an optional thing to add to the configuration under a "better privacy" or something like that.

**Comment by daN4cat** [comment]
GDPR topic covered by Mailchimp blog.

**Comment by daN4cat** [comment]
Other thing I should probably add is a Customer registration date and the Employee name that registered the Customer.

**Comment by SteveIreland** [comment]
This is an interesting law and certainly well intended but doesn't seem well thought out.  Isn't the requirement to "be able to be forgotten" at odds with laws that require a company to be able to prove sales to particular individuals?  If I sold someone a bad product and then they wanted us to "forget about them" and then they come back and declare they were made sick by something we sold them ... what defense would the company have since they now have no record of the sale to the particular individual because they were required to be forgotten?

How about gun sales?  Can I buy a gun from a dealer and then ask them to forget about me so that there is no record of the sale?

Just a bit confusing to me based on the summary info from Mail Chimp but there are probably clarifications regarding exceptions stipulated in the law.

**Comment by daN4cat** [comment]
Gun sale are highly regulated in the EU. It's not like in th US, somebody needs a license and I'm sure selling a riffle requires registration and data retention.
It's not a blanket law that removes everything, that's my understanding.

And I assume that if someone wants to be forgotten cannot make a claim without a piece of evidence. But this is more food for lawyers.

**Comment by jekkos** [comment]
@daN4cat thanks for sorting this out and adding the required functionality. Regarding the 'right to be forgotten', I read something that customers should be able to also view their data and modify it at any time.  Do you know of any such requirement for GPDR?

**Comment by jekkos** [comment]
I'll try to test / review this functionality tomorrow

**Comment by daN4cat** [comment]
You can extract by customer all the transactions under their name if they want know what you store about them.
The right to be forgotten is what I implemented with the delete removing any data of the customer and any Mailchimp entry. That was already there.
Anonymising the entry is legally fine, so we don't break dependencies.

**Comment by jekkos** [comment]
@daN4cat was just testing the new functionality on the demo site. It seems that I'm no longer to import any customers through the standard import file. The required checkbox works fine at first sight, I need to check it before i can add a new customer.

**Comment by daN4cat** [comment]
I'll test the customer import this eve and fix. Thanks

**Comment by daN4cat** [comment]
Fixed the import issue as another one with delete.

**Comment by daN4cat** [comment]
Any test or comment?

Shall I close?

**Comment by jekkos** [comment]
Seems fine in latest demo version now

**Comment by SteveIreland** [comment]
So are we effectively forcing these EU rules on OSPOS users in the US?  There doesn't appear to be an "opt out" option here.

**Comment by WebShells** [comment]
Same to my region 🤔

**Comment by daN4cat** [comment]
It's enforced if you tick the checkbox in the config.
The rest is good practice for audit trailing (e.g log date and employee at registration time).  The consent checkbox is something you can find on Mailchimp too no matter where you live.
So not unusual and just good practices I would say.
