### ISSUE TITLE
"Item Kit Items" printing on receipts regardless of "Kit Only" print option enabled.

### ISSUE THREAD

**Issue by JigoloPete21** [opensourcepos/opensourcepos#1950]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.20
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.0.28
- MySQL or MariaDB version is: 5.7.17
- OS and version is: Ubuntu 16.04.1
- WebServer is: Apache 2.4.18
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

1) I have the following options selected for a test Item Kit I created:

**Price Option:** Kit Only
**Print Option:** Priced Only

2) The Item kit is comprised of 2 Item Kit Items:

First Test Item
Second Test Item

3) The item kit also has the "Kit Item" field populated with the following item name "Oakley Test Item Kit"

When pulling up the item kit in the sales register, "Oakley Test Item Kit" appears with its correct pricing and "First Test Item" and "Second Test Item" appear with $0 for their pricing, as expected due to the 'Kit Only' price option.

However, when completing the sale and viewing the receipt, all 3 line items appear on the receipt instead of just the item kit, regardless of whether the 'Priced Only' or 'Kit Only' print option is selected prior to making the sale.  I have tried creating multiple different kit items with every possible combination of Price and Print options to no avail.  From the documentation online, the expected behavior would be to see only the Item Kit listed on the receipt, however, these doesn't appear to be the case.  Can you please recreate the issue on your end to confirm if my findings are accurate?

Let me know if you need screenshots or database entry info in order to further clarify the issue.

Thanks!

**Comment by WebShells** [comment]
@SteveIreland actually I noticed that when I first tested,  but I thought am missing something... But yeah even final reporting if we can list the selected item kit name in place of items name itself in it...

**Comment by JigoloPete21** [comment]
@SteveIreland This feature is a godsend to us because we frequently sell customized sunglasses (Frames + Lenses) and had no way of reliably tracking our inventory automatically, until now!  By tracking the sunglass inventory at the "frame + lense" level and selling at the completed "kit" level, everything is unbelievably smooth and error-free.  Thank you for developing this.

**Comment by daN4cat** [comment]
Thanks @SteveIreland for the help.

**Comment by SteveIreland** [comment]
No problem.  You'll see more than a couple of lines of code changed.  When testing I kept stumbling into one issue after another that I had to resolve before I could start testing my fix for the reported issue.  Almost done.

**Comment by SteveIreland** [comment]
The problem not only existed in receipts but also in invoices, quotes, and work orders and in the email version of the listed documents.  I also fixed a surprising issue I found in kit maintenance, for some reason the item kit selection wasn't listing item kits, so that needed to be repaired.  Let me know if you find any other issues related to the use and maintenance of kits and I'll jump on it this week.

A pull request has been submitted.

**Comment by daN4cat** [comment]
Code in master.

@JigoloPete21 please go to Bintray (see README) and test the new code.

**Comment by SteveIreland** [comment]
Thanks @daN4cat for catching and removing the debug code.  I'm apparently a bit rusty.  :-)

**Comment by SteveIreland** [comment]
I just upgraded to the latest version of PHPStorm and it seems to be doing a much better job of keeping my usually code formatting mistakes out of the code.

**Comment by JigoloPete21** [comment]
I created a fresh install of OSPOS 3.2.1 and can confirm that the **Item Kit** is now the only line item printed on a receipt when the **Print Options** "Kits Only" and "Priced Only" (when the other line items are $0) are selected for the **Item Kit**.  The only instance in which this doesn't appear to work is when the **Price Option** "Kit and Components" and "Kit and Stock" are selected with the **Print option** "Kits Only"; in this instance all line items are still printed, which certainly makes sense since the line items are all priced, but is a bit unintuitive since the **Print Option** explicitly says "Kits Only". Not sure if this is expected behavior or not, but wanted to make a note of it.  Regardless, thank you for the prompt fix.  Very much appreciated!

**Comment by JigoloPete21** [comment]
I should also note that I tested returns as well and can confirm that all items relating to the Item Kit get returned to inventory as expected.

**Comment by SteveIreland** [comment]
I would have answered earlier, but my electricity and internet connection was out of commission for awhile.  I'm thinking that I'll make a change simply to not allow that combination of options because the alternative would be to try to compute a price on the fly (which seems ripe with problems to me).

Thanks for checking this out.

**Comment by JigoloPete21** [comment]
I found another small bug.  When viewing a receipt via the "Transactions" report or by using "Daily Sales", it still shows all items associated with an Item Kit, rather than just the Item Kit on its own.  So just to recap, the receipts print correctly directly after the sale, but not when recalling it later it appears.

**Comment by SteveIreland** [comment]
I encountered that during my testing but I thought I fixed it.  Were you looking at a sale that was created prior to the fix being applied or after?  Whether or not it should be included in the print when reprinting from the Daily Sales panel is already established by the print option flag on the sales item table.  So it is not recalculated if you change the kit definition after the sale.

I'll retest it this coming week.

**Comment by JigoloPete21** [comment]
I tested after the fix being applied.

**Comment by SteveIreland** [comment]
I've started testing this and I haven't found a problem .... yet.   So let me break down somethings here.

>"When viewing a receipt via the "Transactions" report or by using "Daily Sales", it still shows all items associated with an Item Kit, rather than just the Item Kit on its own."

That's the way the transaction reports work.  It will still show the details because the details are used to reduce inventory for stocked items.

> "So just to recap, the receipts print correctly directly after the sale, but not when recalling it later it appears."

This is the issue that I'm not having much luck recreating, but there are many possible permutations so over the next week or two I'll keep trying various combinations.  So far, when I've gone to daily sales to reprint an invoice it looks just like it did when it originally printed.

**Comment by daN4cat** [comment]
Are we good to close this?

**Comment by JigoloPete21** [comment]
I think so. Go for it. I tested again and didnt run into the issue.

**Comment by daN4cat** [comment]
Good. Thanks for the confirmation, I close.
