### ISSUE TITLE
improve minification using ci-minify can be possible?

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1951]
in many issue we have been see it that deploy ospos are not easy and the development setup are not easy either..

i found this: https://github.com/slav123/CodeIgniter-minify and i ask if can be used event the complicated minification system.

i understand that its a "on-the-fly" mechanics but can be combined with ci-cache and makes life better for users..

some opinions @jekkos @objecttothis @WebShells @nerv55 ?

**Comment by nerv55** [comment]
If, we implement this, I can make android client responsive very quick.

**Comment by mckaygerhard** [comment]
some issues as examples that will not happened if this are implemented: 
* https://github.com/opensourcepos/opensourcepos/issues/1866#issuecomment-370199504 need css modifications but normal users cannot contribute due the very complicated process as happened here
* https://github.com/opensourcepos/opensourcepos/issues/1938#issuecomment-380206204 a great feature to give to items classifications, but not easy to do, obviously words from the issue author that neeed edit the css but in principie does not understand the complicated build/devel environment
* https://github.com/opensourcepos/opensourcepos/issues/1875 was a very popular issue that was "closed and locked" due the true of the problems that a build environment comes was revealed! with the on the fly css and js minification maybe those problems not happened
* https://github.com/opensourcepos/opensourcepos/issues/1863 this feature the "focus" inpiuts on sales modules could be made more easyle for normal users event waith until a project developer commit the changes property..
* https://github.com/opensourcepos/opensourcepos/issues/408 : this also can avoid some cache problems with proper configurations like #1357#issuecomment-310834755 and like , but **in counter part** the CDN possible files must be taken from the manually minified produced from library

there's many more issues that can be avoid and users contribution benefics... right @simonaogstino @GurlWhoCodesAlot ?

**Comment by jekkos** [comment]
You can run with full css / js by adding ?debug=true to your URL. Maybe add a rewrite rule in apache to do that for you and you'll have full sources everytime

**Comment by mckaygerhard** [comment]
err i mean this issue its to not use those "onlyne build tools" and can make only clone the repo and just run on the fly ! do you read the original issue ?

**Comment by mckaygerhard** [comment]
also apache its the most slowes web server of all... by the way maybe due that youtube and wikipedia does not use it!

**Comment by mckaygerhard** [comment]
err i mean this issue its to not use those "onlyne build tools" and can make only clone the repo and just run on the fly ! do you read the original issue ?

**Comment by mckaygerhard** [comment]
sorry i dont see the response of you @daN4ct due any of the notifications from you arrived to me.. 

so close this so the resopnse its always negative event if are improvement for other users
