### ISSUE TITLE
travis.yml.

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#1954]
I resync'd today with the ospos repository and it pulled in a version of travis.yml that has a trailing period.  Windows doesn't support file names that end with a period, so this caused me a bit of trouble trying to figure out how to deal with it.  It looked like it was pending a commit on a delete for the file but unfortunately I caught it in the "in between" stage.  I had to commit it to master on one of the branches I'm working on so that I could continue work (otherwise it wouldn't let me rebase my branch on the jekkos master).

Hopefully it will just go away but I thought I'd mention it so that if it pops up in a future pull request then there is a record of it.

**Comment by mckaygerhard** [comment]
git, docker and so tools are nativelly linux-unix related, and those kind of files are common men, so i'm afraid that in the future more of those files will be on, that's one more reason to not use window only for gamming

**Comment by daN4cat** [comment]
@jekkos was that on purpose? There are two files now one with final dot and one without. Weird.

**Comment by SteveIreland** [comment]
@mckaygerhard I'm quite happy with the platforms I'm working with.  I stopped paying attention to platform rants a couple of decades ago and I have still always managed to get the job done.

**Comment by mckaygerhard** [comment]
umm i not taking about ranks, well the M$ platforms are not preciselly the most indicated to make services.. in any case, i not found info about files with a dot at the end, only the hiddeen unix normal with a dot at the beggining.. i dont remenber that travis-ci do support for the M$ platform nativelly, only using cywing.. inclusivelly i remenber the issue 216 of travis-ci that does not end with guindow suport, only for osx and linux... due those platforms are made to do works.. the rest for gamming or something else..

i mean: maybe now its not working any more..

**Comment by daN4cat** [comment]
Duplication removed. I closr.
