### ISSUE TITLE
expense module - amount, tax field getting empty during edit

### ISSUE THREAD

**Issue by StanlySimon** [opensourcepos/opensourcepos#1955]
OSPOS 3.2.0
When editing an existing record in expense module, Amount and Tax fields value disappear and display as 1.00

**Comment by daN4cat** [comment]
Thanks, I'll test this in the evening. Any special way to reproduce this?
Is this a new installation or an upgrade?

**Comment by StanlySimon** [comment]
Its a new installation.
To reproduce this error, create an expense entry with all details and then edit it, automatically amount and tax field values disappear and set as 1.00

**Comment by SteveIreland** [comment]
We now have an expense module?!?!?  Geesh, I take a nap and WHAM there is a whole new world.  Searched for expense in the wiki and found nothing.  Is it a secret?   :-)

**Comment by odiea** [comment]
It's a fairly simple module so we thought it would be self explanatory.

**Comment by mckaygerhard** [comment]
@SteveIreland the wiki it's still under construction.. that's why expense its not documented, but due the bad actitude i'll fork the wiki and started with spanish only.. in any case i contribute enought for all here

**Comment by daN4cat** [comment]
@StanlySimon I tested and works fine.
Anything else that we should know but you didn't say because you removed the issue template?

**Comment by odiea** [comment]
I also had no issues with Expenses

**Comment by mckaygerhard** [comment]
i revised the wiki, and the expense module are pointed:
here: https://github.com/opensourcepos/opensourcepos/wiki#introduction -> "expense module integrated"
here: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-complete-feature-datasheet#complete-list-of-features -> almost at the end of the complete list

of course a detailed expense wiki page still are not happened.. due the work in progress

**Comment by StanlySimon** [comment]
Still having issue with expense module.
If you enter an amount with more than three digit (ex: 123123.00) and when you edit this, you will get 123.00
I'm not sure if this issue occurring due to any incorrect settings in Store Config.
Can someone test this module by entering more than 3 digit amount and try edit

![image](https://user-images.githubusercontent.com/38244786/39165614-f3a5c586-47a2-11e8-8775-89dd952bd678.png)

**Comment by StanlySimon** [comment]
It is working fine with 3 digit amount. So I suspect issue is something with thousand separator.
Again, I may be wrong as these are my finding while doing testing on this module.

**Comment by daN4cat** [comment]
Ok, I'll test it with bigger amounts. I suspect it could be locale setting related.
Could you tell me exactly what you configured in your locale? Just take a screen snapshop so you'll be quicker.

**Comment by daN4cat** [comment]
BTW a total of 123,123.00 doesn't look right either. Something more to check and fix.

**Comment by daN4cat** [comment]
I tested inputting 100,000.00 and works fine.

Please take a snapshot of your locale config so I can check what's different.

**Comment by daN4cat** [comment]
OK, I've got now. It only happens if you input both sum and tax with more than 3 digits.

**Comment by StanlySimon** [comment]
My locale config is below

![image](https://user-images.githubusercontent.com/38244786/39171494-a17f1e82-47bc-11e8-91b7-a5a4dcfd93eb.png)

**Comment by daN4cat** [comment]
The issue is fixed.

Please @StanlySimon test the latest code from bintray (read the README to get where to find the code).

**Comment by StanlySimon** [comment]
Thanks @daN4cat 
Now expense module is working perfectly and the issue has fixed

**Comment by daN4cat** [comment]
Great, thank you for the bug report and testing.
