### ISSUE TITLE
Demo Web Site

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#1956]
Just curious ... I see we have a https://translate.opensourcepos.org.  Does anyone know what would it take to set up https://demo.opensourcepos.org as a demo site that we can use to demonstrate what is in the latest development release?

**Comment by mckaygerhard** [comment]
well this implicts a audo earsing account like happened with myroundcube demo: once the user logout all the related data erased!

**Comment by SteveIreland** [comment]
Auto erasing is not what we would want here.  If I go into it I would expect to see the test data that someone else created.  It might be nice, though, to have a way to reinitialize the test data just in case we want to set up the data in a particular manner in order to show off a new feature to the OSPOS community.

**Comment by mckaygerhard** [comment]
right @SteveIreland well you explain better that i talking about: an account that after logout all data go to the original test data..

**Comment by jekkos** [comment]
Ok found a simple script that will allow me to have such a setup w/o docker cloud. Docker hub can be configured to trigger some http endpoint once it receives a new push. When that happens, I need to pull the newest image and reinit and restart the container.

https://github.com/schickling/docker-hook

**Comment by jekkos** [comment]
Might be easy for everyone to test and checkout new features without having to install latest themselves

**Comment by SteveIreland** [comment]
I totally agree!   This is going to be awesome.  Thank you @jekkos

**Comment by WebShells** [comment]
@jekkos is there anything I can help with related to this? 🤔

**Comment by jekkos** [comment]
Ok I setup a demo instance at https://demo.opensourcepos.org

a web hook is configured in docker hub that will trigger a redeploy once a push is done to master.

**Comment by daN4cat** [comment]
@jekkos I tried the demo website but I cannot login.

**Comment by odiea** [comment]
I tried yesterday with no issue. Must have been changed by a user.

**Comment by daN4cat** [comment]
It's fine now. Weird....

**Comment by odiea** [comment]
He might consider removing the employee module or make it not writable.

**Comment by mckaygerhard** [comment]
of course there's is no "full features test" of some modules are removed, as i suggested once user logout all data must be reset to original demo data

**Comment by SteveIreland** [comment]
Interesting.  

As I said earlier, if the original demo data is cleared by logging off then that would defeat one of the goals of trying to showcase a new feature.

Obviously someone with a dark heart can make things difficult for the community.  Hopefully that won't be the case but if it does then after the the build someone just needs to go in to the admin, add themselves as another admin with a secure password and change the admin profile to be unable to administrate employees and security.

This might actually motivate one of us to add some additional power and flexibility to the employee security module.

We would also need to coordinate on the configuration because switching tax configurations can make reports look a bit odd.

**Comment by mckaygerhard** [comment]
umm now sounds like a lot of work to do event a simple demo feature component.. 

and also someone in some issue requested that feature of employee security, but as always was closed "quickly"... very quickly as always..

**Comment by SteveIreland** [comment]
With 174 open issues your false claim that issues are closed too quickly is simply unwarranted. Issues are closed that are either completed, duplicated, don’t make sense, or don’t reflect the direction that the architects of OSPOS want to take it.

**Comment by mckaygerhard** [comment]
there¿s many issues due the wrong point direction of a simple file: README

**Comment by nerv55** [comment]
is this demo only for community o I can show it to potential users?

**Comment by nerv55** [comment]
@SteveIreland   I can provide android APK pointed to this site if anyone wants test scaled mobile view.

**Comment by daN4cat** [comment]
Can I setup a stand before the demo entrance to sell beer and popcorns? We might make a bit of money in that way this time....

**Comment by WebShells** [comment]
@daN4cat or we can advertise ;p ! just entering the same num of bucks that we might get out of popcorn and beer ;p

**Comment by daN4cat** [comment]
Ok, I believe we can close.

**Comment by mckaygerhard** [comment]
hi @SteveIreland @jekkos @WebShells @odiea @daN4cat i play a little in the demo website, and notes that users can configure languaje and many other modules..

last 5 minutes i see in some arabic languaje with other country conbination, data items fdont care but was hard to find the interface due the moduel icon do not show due missing fonts in my device

1. see that any user can make changes and let the demo in "own" state with thier languaje and country setting
2. if we limited that, so then users cannot will test all the funtionalliuty

so with many respect i ask if we can made something respect that situation..
