### ISSUE TITLE
Customer identification

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1957]
a good Samaritan to help me?
I have version 3.1.1. and how can I include in the customer file the identification number since it does not come with it?

attached example

![image](https://user-images.githubusercontent.com/12921805/39190103-83d844f8-4799-11e8-96ac-03572fde4481.png)

**Comment by mckaygerhard** [comment]
do you want to make a new field? and stored in the database? if there's you must explain better ok next time!

**Comment by guillermohaad** [comment]
Hi friend @mckaygerhard , 
Thanks friend, I was asking why I should have this field and it does not come by default?

**Comment by mckaygerhard** [comment]
@guillermohaad  the problem its that you not have read the development wiki: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index , alfter read it umm there's two ways for sure to made it

and also of course the very ambigous README and INSTALL files in the ospos package right?

if still are too complicated please fill me a issue in my fork and i can made it for you, but first try the wiki reading ok

**Comment by guillermohaad** [comment]
@mckaygerhard , I'm going to check and if this is complicated for me, I'm going to bother you, thank you

**Comment by SteveIreland** [comment]
Are you asking if the customer id from the table can be displayed, or are you asking for a new user defined identifier for the customer?

The customer identifier would never be displayed on the new customer form (as you are requesting in your example) because it isn't yet known.

**Comment by mckaygerhard** [comment]
that's the first and most easy way, by displaying the customer id from ospos tables.. the second and more harded are making a new/custom column in the table and parsing/displaying in the form and customer model/object

**Comment by guillermohaad** [comment]
Hi friend @SteveIreland , I require a new user defined identifier for the customer.
thank you.

**Comment by mckaygerhard** [comment]
as i guess!, well as i proposed first read the development wiki,  https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index , alfter read it if are too dificult for you i can made it by fill a issue to my fork

and also of course that demostrate the very ambigous README and INSTALL files in the ospos package right?

**Comment by guillermohaad** [comment]
@mckaygerhard  and @mckaygerhard 
In my country the identification number or social security number is important for any kind of document and it would be convenient in the new versions to include it.

**Comment by mckaygerhard** [comment]
@guillermohaad in my country too, here there its the "cedula identidad" that's why i understand your request.. i'm afraid here someone more else will understand

**Comment by guillermohaad** [comment]
@mckaygerhard 
So I need the cedula, but I still do not understand how to do it because I read but it's a little complicated, could you help me?

Thank you

**Comment by mckaygerhard** [comment]
@guillermohaad you must understand firts as marked in development index the codeigniter concept, its not MVC complety but const of a model (Customer) that represent the database data to access, the Controller (here are various) that take these data and manipulate it to render the Views (in the appliction/view directory)

in al lof this, model are already made, so the only you must do it in controllers, added the already mapped id field of the model... 

if you do not code php in codeigniter you will expends almost 5 days to learn.. 

in other hand by some buck i can made it

**Comment by SteveIreland** [comment]
Is the account number field that is already there not suitable for your purposes?

**Comment by mckaygerhard** [comment]
@SteveIreland of course not! as i said and @guillermohaad said! its a proper number to each people in the country! like the passport but internally!

the problem here its that the developers thinks that theirs needs are the only needs!

**Comment by guillermohaad** [comment]
@SteveIreland It could serve but it does not show it to me when printing the invoice.

attached evidencie

![image](https://user-images.githubusercontent.com/12921805/39198563-ff3a6bc2-47ac-11e8-8861-f3cc1819df9e.png)

**Comment by mckaygerhard** [comment]
in that case @guillermohaad you must manyally exposed the field!

**Comment by guillermohaad** [comment]
@mckaygerhard  I mean include it in development as you say?

**Comment by mckaygerhard** [comment]
nop, the printing "facrtura" its like a custom view that implements the pdf library exporting, of course if a field are n ot coded will not show!

**Comment by SteveIreland** [comment]
I'm surprised that it's not being included in the invoice when printed ... it should be if it's not blank.  I'll check in to that for the current release.  It will be a simple change.

**Comment by mckaygerhard** [comment]
thanks @steveireland please refers that issue in the commit if you do something

**Comment by guillermohaad** [comment]
I'm sorry, and as my friend @SteveIreland says , it should be if it's blank, I put it on and it showed on the invoice. This solution could work but I agree with my friend @mckaygerhard 

![image](https://user-images.githubusercontent.com/12921805/39199522-4b9e32bc-47af-11e8-938a-0982123258ba.png)

thank you

**Comment by guillermohaad** [comment]
@mckaygerhard  and @SteveIreland 
I take this opportunity to ask how I can remove the columns highlighted in red from the print of the invoice so that it only shows description quantity and price?

![image](https://user-images.githubusercontent.com/12921805/39199975-694ece24-47b0-11e8-98ea-dbc099e4288e.png)

**Comment by mckaygerhard** [comment]
to remove must see in the vies pointed by the respective report controller invoked, see the network tab by using this: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-DEVEL-for-Error-Logging-in-OSPOS
umm seems panama right @guillermohaad ?

**Comment by SteveIreland** [comment]
Closing this issue since it's been resolved.

**Comment by guillermohaad** [comment]
@mckaygerhard  great thanks
