### ISSUE TITLE
#1924 Needs to be reopened

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#1958]
I was trying to test an invoice and found that the invoice was broken as a result of a change made for #1924.

I have an idea as to how to accomplish the same objective but I'll do that later this week.

**Comment by daN4cat** [comment]
@jekkos to comment

**Comment by jekkos** [comment]
@SteveIreland what exactly is broken then? Only thing I added is show discount whether we applied it or not.

**Comment by odiea** [comment]
Should the columns have some kind of filler or column size change so the displayed columns stay to the right right ?

**Comment by SteveIreland** [comment]
Good question, we don't specify column widths so the table will either be narrower or the other columns will be automatically expanded to fit the width.  The later usually happens when the width is set to or inherited as 100%.  I'm not yet sure what it is, but I'll check on it when I'm testing it later this evening.

What would be your preference?

**Comment by odiea** [comment]
None really . I would like to see the invoice before and after the item[discount] issue is fixed. Like you stated no other adjustments may be necessary

**Comment by odiea** [comment]
@SteveIreland here is the original issue #1824

**Comment by SteveIreland** [comment]
Thanks @odiea I see what's going on now.   Hopefully I can submit a fix for it tonight.

**Comment by SteveIreland** [comment]
If there is no discount on the sale then the discounted unit price column will not be rendered..

**Comment by daN4cat** [comment]
@SteveIreland have you checked if quote and work order have the same issue/behaviour?

**Comment by SteveIreland** [comment]
I have now.  The  revised pull request includes a fix for quotes.  Work orders did not need it.  In most small shops the owner does not want the prices included on the work orders.

**Comment by daN4cat** [comment]
In master

**Comment by jekkos** [comment]
@SteveIreland thanks for ironing this out.
