### ISSUE TITLE
IMPORTANT: To all US area OSPOS users, please be aware of CLOUD ACT vs GDPR

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1960]
This applies to USA area users mainly, any other company storing US citizens information should be aware of this too.

As you know OSPOS offers a Customers CRM capability, a means to store data about your customers.

With US Congress passing the CLOUD Act and the implementation of the new General Data Protection Regulation (GDPR) on May 25, 2018, the regulatory challenges for organizations in regards to data privacy are drastically increasing.

This are related **to GDPR, but as counter part, the CLOUD act not required the explicit consent of the customer in order to FBI allow capture and store data from your customers, and  MAY IMPLICT you in legal issues.** That means before you enter your Customer data in OSPOS you need to have their consent and the explicit consent record needs to be retained. That's not something OSPOS can do for you.

So it's not only to EU area as issue #1949 said! I opened here this, if will close it please then renamed the tittle of the issue #1949 to point its also for USA.

**Comment by SteveIreland** [comment]
Yes, thanks for bringing the Cloud Act to my attention.  I will now start lobbying our Senator (Chris Coons) who is one of those responsible for this illegal monstrosity. 

However, it appears (on first glance) to be the opposite of the GDPR in that it requires companies to retain private information and release it to any EU law enforcement agency that asks for it without the normal due process of law.  At least that is the general opinion of the privacy protection organizations around here.

Interesting stuff.

**Comment by mckaygerhard** [comment]
here are very strange things: 

* both startes at same time and are in sync to apply
* both are oposite, very oposite!
* the EEUU case can "implant" info on your account due the nature of the act
* the EU case make more dificult to developers make things, but easy to enterprices

i mean, its very easy to a great enterprise that have many employees make proces and define to the GDPR act the needs.. but for little projects like us, of course its very difficult

... wheantime in the EEUU case, its more direct, goes directly to your data, "implant" the false information adn get of you in a palm...

both acts are bad in any case, of course the EEUU case its a very very bad extreme.. 

in Venezuela in the old days police man "implants" drugs... today its a "yanky" official/enterprise that "implants" information and make of you a terrorist!

in spanish: "antes te sembraban drogan unos policias, hoy te siembran informacion empresas gigantes"...

**Comment by WebShells** [comment]
Google already updated their policy as well...

**Comment by nerv55** [comment]
Here http://data.consilium.europa.eu/doc/document/ST-5419-2016-INIT/en/pdf link to GDPR law

**Comment by mckaygerhard** [comment]
umm that's true.. https://www.congress.gov/bill/115th-congress/house-bill/4943/text was only introduced again? or not?

**Comment by mckaygerhard** [comment]
https://www.fsf.org/blogs/community/strengthen-free-software-by-telling-congress-to-reject-the-stronger-patents-act 

in 2017 was the first try.. now in july was reintroduced! 
https://www.fsf.org/blogs/community/strengthen-free-software-by-telling-congress-to-reject-the-stronger-patents-act 

in 2017 was the first try.. now in july was reintroduced! July 10 reintroduced the Support Technology and Research for Our Nation’s Growth and Economic Resilience Patents Act (STRONGER Patents Act, S. 2082, H.R. 3666). will hijacked all the intents to make free implementations of any standart so all the software ideas wil be based only in "draft"s

**Comment by SteveIreland** [comment]
Wow.  My own Senator Chris Coons is the sponsor of this abomination.  He will be hearing from me.  Thanks @mckaygerhard for the update.

Fortunately it only has a 34% chance of being enacted into law  (per https://www.govtrack.us/congress/bills/116/s2082).

But still ...
