### ISSUE TITLE
Checkbox in settings for skipping Sales Complete page

### ISSUE THREAD

**Issue by kosimoff** [opensourcepos/opensourcepos#1966]
Please somebody add checkbox in setting for skipping Sales Complete page
![capture](https://user-images.githubusercontent.com/14353101/39392606-4c52dd5e-4ad2-11e8-82a3-42f905c6c686.PNG)

**Comment by daN4cat** [comment]
FIY that's the page you print, not sure how you could skip.

**Comment by daN4cat** [comment]
FIY that's the page you print, not sure how you could skip.

**Comment by WebShells** [comment]
Well I wasn't sure how could I reply to that lol... Jeeeeeesssss!

**Comment by kosimoff** [comment]
Right after print command is sent to printer, go to Sales Register page again, instead of staying in Sales Complete page.

**Comment by WebShells** [comment]
Or set windows header :x

**Comment by daN4cat** [comment]
@kosimoff feel free to contribute the feature.

**Comment by kosimoff** [comment]
If I were a programmer

**Comment by daN4cat** [comment]
If we had all the time of this world :-)

**Comment by WebShells** [comment]
@daN4cat we can simply add header or windows location on receipt page :/

**Comment by daN4cat** [comment]
Not sure I get what you mean... today I'm sleepy and slow so bear with me.

**Comment by mckaygerhard** [comment]
must take in consideration most scenarios, not only those wehre "windows.locations" works..

**Comment by WebShells** [comment]
@mckaygerhard in what cases it might not work :) ? if you can inform me please...

**Comment by WebShells** [comment]
@daN4cat i meant, cant we add windows.location and point it to sales, so once printing page reached if "Print after sale automatically is selected" after reaching print page for Kiosk or non-kiosk users will press enter ( to print ) or escape ( to not ) and the header will redirect the user to sales again.

**Comment by daN4cat** [comment]
I remember having looked in to something like that but I had an issue. I can't remember what was.
But I should look into this option again. Also there is the receipt re-print option to sort out.

**Comment by mckaygerhard** [comment]
umm i doub will work in mostly cases, seems for mobiles will cause some problems, i try to develop a mobile agnostic client app that uses webview and seemms here are not know waht i taking about.. 

webview embebs the client rendering and take output (talking in easy words) and the window location may cause confusions.. for mobile printers..

mobile rpinting are a great fetaure that will be lost if not work, and i not have today a mobile device to test, i must waith until July for that (i not living in a country that today can wastes resources )

**Comment by daN4cat** [comment]
Implemented with a settable delay before the return to sale page in the configuration.

**Comment by daN4cat** [comment]
Shall I close? Anybody else tested this?

**Comment by odiea** [comment]
I don't have a printer here so the only problem I see is setting the seconds to 0 or 1. The page always shows.

**Comment by daN4cat** [comment]
Yes the page shows because you need it to print. Once printed it flips back to sale.
The automatic flip happens only if you selected print after sale.

**Comment by odiea** [comment]
I think I can't hit cancel fast enough.

**Comment by mckaygerhard** [comment]
so then limit the list from 3 to 5 ... in any case this for sure wil cause other troubles
