### ISSUE TITLE
Select category from dropdown list when adding/editing item

### ISSUE THREAD

**Issue by kosimoff** [opensourcepos/opensourcepos#1967]
Now we can search for category and select. No dropdown list. It would be more convenient to directly select from dropdown list. Dropdown list with suggestions while typing.

![capture2](https://user-images.githubusercontent.com/14353101/39392736-b1a507b6-4ad4-11e8-976c-ad49746ca4cb.PNG)

**Comment by mckaygerhard** [comment]
This its no possible and not convenient, due if we have too many the list will not obviously fit, user will not understandt that there are more ...

**Comment by daN4cat** [comment]
I see what you mean, something like this example: https://select2.github.io/select2-bootstrap-theme/

The js plugin would be this one https://github.com/select2/select2-bootstrap-theme

I can give a try and see if it's difficult to setup.

**Comment by daN4cat** [comment]
Mhhh, the problem with that js plugin is that you cannot add a new category as it is at the moment, it just selects what available.

**Comment by kosimoff** [comment]
Somebody pls implement this

**Comment by objecttothis** [comment]
This is sort of a duplicate of #2368.  I will be implementing this.
