### ISSUE TITLE
check you php.ini file

### ISSUE THREAD

**Issue by Alteno** [opensourcepos/opensourcepos#1969]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I'm a first time linux user, and i'm trying to set up a ospos server through digital ocean. I've followed http://www.opensourceposguide.com/guide/gettingstarted/installation and https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-Getting-Started-installations#cloud-deploy-installation pretty much verbatim. 

I'm now getting "The installation is not correct, check you php.ini file' when I try to log in through a browser. I've been going through the old posts here and the FAQ and the installation guides, but I can't find any information on where to find the error log or how to open it. It seems to be in different places based on the setup. There's mention of it being in the 'public folder', but no instructions on where this folder is or how to access it.
I'm a beginner just trying to get this thing set up. I'm not sure if a docker install would be better?

Any help would be greatly appreciated.

Thanks

**Comment by WebShells** [comment]
Please consider searching the issues before requesting help...

**Comment by WebShells** [comment]
Well, #1969 #1952 #1923 #1856 #1838 #1812 ... need more ? :)

**Comment by Alteno** [comment]
Alright, so the problem was that it needed the mbstring php module to be installed. You might want to change the wiki or the installation guide to include that with the installation of the other php modules.

Also, None of those articles helped in this case. They were either ambiguous or were for other types of servers. I had to get a friend who was proficient in Ubuntu and php to help me.

Thanks anyways.

**Comment by mckaygerhard** [comment]
hi @Alteno thanks for corrections. i not see this issue at time!

of course none of these issue help any of the information here help, and of course the README and INSTALL files are ambiguos..

the wiki pages are minimal still, need improvements, talk to me to improve and make the right directions to improve the documentation..

**Comment by mckaygerhard** [comment]
umm @Alteno i can see also that you join recently just today to github, also no have any identification or information.. in this ways not help so much to you be a comlete uknow user...

**Comment by daN4cat** [comment]
The INSTALL in the first statement says....

PHP version 5.6 to 7.2 is recommended. Please note that PHP needs to have **php-gd**, **php-bcmath**, **php-intl**, **php-openssl**, **php-mbstring** and **php-curl** installed and enabled.

**Comment by daN4cat** [comment]
I don't see ambiguity, it's pretty clear @mckaygerhard
