### ISSUE TITLE
Stock name with spaces invalidates grants

### ISSUE THREAD

**Issue by isheraz** [opensourcepos/opensourcepos#1970]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [*] Reporting an issue of an unmodified OSPOS installation
- [*] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [*] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [*] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [*] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [*] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [*] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.2.1
- OSPOS git commit hash is: none
- PHP version is: 7.1.9
- MySQL or MariaDB version is: 5.4
- OS and version is: Windows 10 Home
- WebServer is: WAMP
- Selected language is: English 
- (If applicable) Docker installation: NONE
- (If applicable) Installation package for the LAMP/LEMP stack is: NONE.

### Issue / Bug  / Question / New Feature

I needed to use this for a personal venture. The system invalidates my grants whenever I name Stock Location in the configuration with spaces. I Then had to mannually change the grant in the database I tried to change the code for it but it would make an overlay appear on my browser window and I am unable to click even after removal of BlockUI divs.

Please see the image below for clarification of the location of stockname

![image](https://user-images.githubusercontent.com/12581068/39649487-61fad36e-4fff-11e8-8e9a-4b3efb424782.png)

**Comment by odiea** [comment]
Try the current demo version. It appears 3.2.0 does not have this issue.

**Comment by mckaygerhard** [comment]
@odiea the screen said "3.2.1" ! so i dont know.. seems still are a bug in 3.2.0, also seems this problem are on guindows?

**Comment by daN4cat** [comment]
It cannot be 3.2.1 as blockui is gone.
Probably they meant to say 3.1.1.

Check again with the latest.

**Comment by isheraz** [comment]
BlockUI isn't the main issue, Grants are. Whenever I am adding a stock name with spaces e.g. "Stock Lahore" it then doesn't generate a grant in database and user does not have the access to it. 

I will do a fresh clone of the latest repo and configure the project again to confirm about the BlockUI.

**Comment by mckaygerhard** [comment]
dont clone it! @isheraz : download from bintray link in INSTALL.md file! if not you must read and configure it as said in wiki development index

**Comment by mckaygerhard** [comment]
dont clone it! @isheraz : download from bintray link in INSTALL.md file! if not you must read and configure it as said in wiki development index, as i cant see, you are a guiwdows user and the developer setup here are for unix related ok

**Comment by daN4cat** [comment]
@isheraz please test with the demo https://demo.opensourcepos.org/ and confirm you can reproduce the issue.

**Comment by isheraz** [comment]
@daN4cat I tested the bug on [demo](https://demo.opensourcepos.org/). It works fine over there. I built the files using grunt because I didn't have dockers, could this have been an issue?

**Comment by daN4cat** [comment]
@isheraz download 3.2.0 version from here: https://github.com/opensourcepos/opensourcepos/releases
Use: opensourcepos.20180414135600.3.2.0.4bab3f.zip
