### ISSUE TITLE
weblate error and again lot of info about server pytnhon etc docker

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#1974]
well: weblate error and again lot of info about server pytnhon etc docker

i do not paste the trace here.. can confuse and think i hacking the server/instance XD

two days ago i made translations and today due rare do not see that in git, i login,, and see what you of course got last time with the traceback

**Comment by jekkos** [comment]
latest translations should be in master now.

**Comment by jekkos** [comment]
I was upgrading the server, tried to add google translate support using an API key in the latest, but something went wrong during migration.

**Comment by jekkos** [comment]
![schermafdruk van 2018-05-05 16-07-51](https://user-images.githubusercontent.com/576234/39664101-8590e82a-507e-11e8-9318-e89a1744d418.png)

**Comment by jekkos** [comment]
So now there is the section 'Machine translation' enabled that queries google translate for a suggestion

**Comment by jekkos** [comment]
Also I think I have github oAuth working now (can someone verify)?

**Comment by mckaygerhard** [comment]
im able to log in now, but some files now give me reading errors...

**Comment by mckaygerhard** [comment]
![errorweblate](https://user-images.githubusercontent.com/1571724/39664307-c22af66c-5070-11e8-8be5-457643e3838e.png)

auth with github falis, but well, now not show lot of info to crackers... 
> Authentication has failed, probably due to expired token or connection error.

@jekkos stop the upgrades and upgrades, just let something that works and when works dont touch.. there-s a said that said>
> if are working let it be! and dont touch iiiit

**Comment by mckaygerhard** [comment]
now tried again, same results for files and for github oauth:
>                        Failed to complete your registration! This authentication, email or username are already associated with another account!

**Comment by jekkos** [comment]
Ok but that's because you already have an account with same email.

**Comment by jekkos** [comment]
Ok you're not able to view translations without being logged in. This is due to a migration that got stuck during the upgrade, I'll look into resolving that later. Should be functional once logged in now.

**Comment by mckaygerhard** [comment]
now i-m loggedin and cannoot still view the files.. this situations are like mocosfot behaviour.. new things comes with new problems..

but now im able to log in.. ..

**Comment by daN4cat** [comment]
works fine for me, but I don't use GitHub OAuth to login.

**Comment by mckaygerhard** [comment]
i dont use oauth neither, and still are give me error when try to access files..

**Comment by mckaygerhard** [comment]
interesting the error message tell something about monkeys well trained! amazing!

**Comment by jekkos** [comment]
Ok managed to run the last migrations after doing some python hacks.. should be running fine now, no more error messages in my mailbox for now. Will keep a further eye on this coming week.

**Comment by mckaygerhard** [comment]
i remenber the old linux era, install one time, run forever, but today install fashion and expect to fashion..

X-D
