### ISSUE TITLE
Web Installation Issue

### ISSUE THREAD

**Issue by ebenezery4** [opensourcepos/opensourcepos#1977]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2
- OSPOS git commit hash is: 
- PHP version is: 7.1
- MySQL or MariaDB version is: mysql
- OS and version is: linux
- WebServer is: apache 2.0
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue 
I try to install the latest version of ospos on a subdomain having check and enable all the php extensions
but am getting an error which says Page not found
retail.truebusiness.tech is currently unable to handle this request which is on uc browser so i try it on another browser (mozila) to cross check but i got a blank page so i go through the error log file to see the error messages and i got 
PHP Fatal error:  session_start(): Failed to initialize storage module: user (path: sessions) in /home/truenozy/retail.truebusiness.tech/vendor/codeigniter/framework/system/libraries/Session/Session.php on line 143

so i dont know what may have caused the issue.

**Comment by mckaygerhard** [comment]
you have two problems:
1. database are not configured
2. subdomain require extra (again complicated) step due the rewrite (again complicated) behaviour

for the first, please configure it at the `application/config/database.php` file
for the second please read at the `public/.htaccess` file

if you wish can ask in particular in my folk

**Comment by ebenezery4** [comment]
thanks for the response
which part of the public/.htaccess should i touch i already do the database configuration

**Comment by mckaygerhard** [comment]
oh men, in that point the files are selft explanatory! are fully of comments about each case! in your case a custom domain..  but that domain are the root of the virtual site, so can also be the case of the entire web root too both applied

**Comment by ebenezery4** [comment]
I try to edit the .htaccess in the public directory and here is the edited code
# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
 RewriteCond %{HTTP_HOST} ^retail.truebusiness.tech\.truebusiness\.tech$ [OR]
 RewriteCond %{HTTP_HOST} ^www\.retail.truebusniness.tech>\.<my web domain>\.com$
 RewriteRule ^/?$ "https\:\/\/www\.retail.truebusiness\.tech\/<OSPOS path>" [R=301,L]

# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
# RewriteCond %{HTTPS} !=on
# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
# RewriteCond %{HTTP_HOST} (.+)$ [NC]
# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
# RewriteRule ^(.*)$ /<OSPOS path>/public/index.php?/$1 [L]
but am getting the following error on the browser...
Internal Server Error
Error 500
This could be due to one of the following reasons:

.htaccess file was misconfigured

**Comment by mckaygerhard** [comment]
i cannot read the code due your code are re-interpreted as markdown by the issue editor.. please must use the markdown sintax to "escape" your code ... see the help of the github flavored markdown, so i can view clear the .htaccess file in right way!

ufff another complicated issue due the complicatd behaviour..

**Comment by ebenezery4** [comment]
Ok here is the code againi commented it so that you can read


# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
# RewriteCond %{HTTP_HOST} ^retail.truebusiness.tech\.truebusiness\.tech$ [OR]
# RewriteCond %{HTTP_HOST} ^www\.retail.truebusniness.tech>\.<my web domain>\.com$
 #RewriteRule ^/?$ "https\:\/\/www\.retail.truebusiness\.tech\/<OSPOS path>" [R=301,L]

**Comment by ebenezery4** [comment]
here is the code again i was trying to use the git markdown to escape the code sorry

```# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
 RewriteCond %{HTTP_HOST} ^retail.truebusiness.tech\.truebusiness\.tech$ [OR]
 RewriteCond %{HTTP_HOST} ^www\.retail.truebusniness.tech>\.<my web domain>\.com$
 RewriteRule ^/?$ "https\:\/\/www\.retail.truebusiness\.tech\/<OSPOS path>" [R=301,L]

# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
# RewriteCond %{HTTPS} !=on
# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
# RewriteCond %{HTTP_HOST} (.+)$ [NC]
# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
# RewriteRule ^(.*)$ /<OSPOS path>/public/index.php?/$1 [L]```

**Comment by mckaygerhard** [comment]
please men, do you  noted the line:
`RewriteCond %{HTTP_HOST} ^www\.retail.truebusniness.tech>\.<my web domain>\.com$`
what do you think are "my web domain"

and now, i assume yo have "truebussine.tech" and ospos must have in subdomain as "retail.truebussine.tech" right? (i deliberate write bad the domain to mantain some non-rast from web)
so remove the unnecesary lines please and that's all..
you must read and inteprete always, read its the most important part.. 
NOTE: this all taking in consideration that the subdomain will redirect automatically to the virtual root and all the virtual root are hijacket by the ospos install.. yes, so complicated from this guys..

for now, i recomended firt install in a very simple way in apart environment, make some experiments and later go to final target.. to gain some familiar with the environment...

**Comment by ebenezery4** [comment]
wao thanks a lot i play around with the file a bit and after this is the issue am left with 
``````
# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
#RewriteCond %{HTTP_HOST} ^retail.truebusiness.tech$ [OR]
RewriteCond %{HTTP_HOST} ^www.retail.truebusniness.tech
#RewriteRule ^/?$ "https\:\/\/www\.retail.truebusiness\.tech" [R=301,L]

my web address looks like this with the above configuration

https://www.retail.truebusiness.tech/%3COSPOS%20path%3Epublic/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/``````````````

**Comment by mckaygerhard** [comment]
umm taking the last comment and comparing with the .htaccess file in the ospos git, it's clear are lot confussing.. and (again) complicated..

what a messs..

so then @ebenezery4  please close this issue ...

**Comment by mckaygerhard** [comment]
the last line are happned due the rewrite condition are infinitelly happened due some part of you line now have missing the final domain..

its more easy fogott the "www" mess and use only the normal domain

also your rewirte has missiing the last part the domain.. please take a look of the original line and compare it!
