### ISSUE TITLE
Italian translation errors

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#1978]
This is in the 3.2 development branch  It seems like just popped up within the last couple of days.  PhpStorm flagged it.  It's in the taxes_lang file.
```php
$lang["taxes_round_half_even"] = "Arrotonda \\"Half Even\\"";
$lang["taxes_round_half_odd"] = "Arrotonda \\"Half Odd\\"";
```
If I change it to the following then the error goes away.
```php
$lang["taxes_round_half_even"] = "Arrotonda \"Half Even\"";
$lang["taxes_round_half_odd"] = "Arrotonda \"Half Odd\"";
```
But Italian translation isn't my specialty and I haven't ever had to touch Weblate. So I will defer to someone more knowledgeable.

**Comment by daN4cat** [comment]
I manually fixed this because Weblate doesn't work on the commit side.
@jekkos please check...
