### ISSUE TITLE
Add button to print Sales Summary Report in receipt template.. as per sales receipt.

### ISSUE THREAD

**Issue by ram666smkdk** [opensourcepos/opensourcepos#1979]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.1.1
- OSPOS git commit hash is: none
- PHP version is:  7.1.9
- MySQL or MariaDB version is: 5.4
- OS and version is: Windows 10 Home
- WebServer is: WAMP
- Selected language is: english
- (If applicable) Docker installation: n/a
- (If applicable) Installation package for the LAMP/LEMP stack is:  n/a

### Question / New Feature

Hi can somebody give me an idea, i tried so hard but no luck..huh : - )
appreciate if somebody can guide me to introduce 1 more button at page "Report Input" which is located on page "Reports >Summary Reports >sales". 

![view as receipt](https://user-images.githubusercontent.com/39026625/39675020-98932a6e-5187-11e8-961c-d28c1ef45454.png)

There is an existing 'submit' button in there. But i want to create one more button(as per picture above) to cater the same input for printing purpose. that button will be open "receipt default template". the purpose is to be able to print it to receipt printer (as implemented in sales receipt). 

 After clicking the button, it's should load the "receipt default template" and show the data & the content should be like below but in receipt template (as implemented in sales receipt) :

![content](https://user-images.githubusercontent.com/39026625/39675348-6de50990-518c-11e8-95fa-5e15a6200cae.png)

I have try to follow the sales receipt coding but no luck.

it's just the same way as we click the 'complete' button in "sales register"

![complete button](https://user-images.githubusercontent.com/39026625/39675392-1bd817ae-518d-11e8-8856-e17d867e0056.jpg)

and then go to receipt template & have print button.

![2](https://user-images.githubusercontent.com/39026625/39675403-539a281c-518d-11e8-9c13-7bbeea54f4f7.png)

appreciate if someone could help me.

TQ

**Comment by SteveIreland** [comment]
The receipt is designed for a specific sale so it cannot be generated from summary data so putting that button there doesn't seem appropriate (and actually isn't possible without making some inappropriate assumptions about the customer, sale id, payments due, etc.)

What is the purpose of generating the report in receipt format?

If you just need a different report format I would recommend using Reportico.

**Comment by ram666smkdk** [comment]
thank you for your feedback..the purpose is to be able to print the report in receipt printer(like thermal printer)..the content of the data just the same as per picture 2..

**Comment by mckaygerhard** [comment]
hi @SteveIreland i will use the fotos of this issue to populate the wiki sales part, due in this way, will be not necesary upload binary files again.. @jekkos  and @daN4cat if there any issue with taht please write feedback

**Comment by jekkos** [comment]
If I'm not mistaken we added some basic printing support for this table in 2.4. But if you want the layout to fit on a 80mm small receipt than that's another problem.

**Comment by daN4cat** [comment]
We added the printing support to Transactions under Sale Register. Try that one and see if it's fine for your needs.

**Comment by ram666smkdk** [comment]
webshells..tq its what i needs...tq very much..very easy one..👍👍👍

**Comment by WebShells** [comment]
You're welcome... This issue will be closed by the suggested solution... Maybe we can add end of day report removing specific columns from the table to be printed on 80mm receipt...
