### ISSUE TITLE
Quotation items not being shown correctly

### ISSUE THREAD

**Issue by Saiuke** [opensourcepos/opensourcepos#1985]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

Installation information

  -  OSPOS version is: 3.2.0
  -  OSPOS git commit hash is: 4f5ad57
  - PHP version is: 7.2
  -  MySQL or MariaDB version is: 5.7.14
  -  OS and version is: Windows 10
  -  WebServer is: Apache 2.4.23
  -  Selected language is: Spanish
  -  (If applicable) Docker installation:
  -  (If applicable) Installation package for the LAMP/LEMP stack is:

- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug

When doing a quotation that includes a item with a large name, in this case the item was "Adaptador hembra de presíon 3/4" Tigre", the complete item's name doesn't appear in the quotation, as you can see below:

![screenshot-2018-5-13 ferreteria lopes camacho potenciado por ospos 3 2 0](https://user-images.githubusercontent.com/19313767/39967992-689e1fc2-568b-11e8-92ec-f0b5aa611534.png)

Would be nice if the quotation format was similar to the courrent receipt format, considering that, most of the time, we use these thermal printers with very narrow papers where it cannot be seen properly.
Below you can check how the receipts are printed:

![capturar](https://user-images.githubusercontent.com/19313767/39968065-90bdea18-568c-11e8-8ae5-259408dde767.PNG)

Here you have my quotation printed:

![capturaree](https://user-images.githubusercontent.com/19313767/39968107-74f3ae2a-568d-11e8-9b81-26209e09b35f.PNG)

Anyway, I think  would be better to have some setup related  to the  quotations or printing as a whole. Something like the kind of printer (or paper) you use thermal or laser...

I couldn't post this without congratulating the developers and collaborators about the amazing project being developed here. Good work. I hope to be able to contribute in the near future, I still have some learning to do.

**Comment by mckaygerhard** [comment]
maybe could be some escaped strings respect database calls?

**Comment by Saiuke** [comment]
Even if the is this, the quotation, in its actual format, doesn't fit in the paper used by these thermal printers.

**Comment by mckaygerhard** [comment]
if the string are too large, there's no actual solution.. for the rest you must configure better the printer, see the pinter specific tips in the wiki

**Comment by Saiuke** [comment]
Right, but check my string >> "Adaptador hembra de presíon 3/4" Tigre", that's not large. It appears correctly in the receipt, even larger ones are shown correctly.

**Comment by mckaygerhard** [comment]
in that case, the `"` double coutes are managed confusin by the php.. as i said in some place there's bad scape rule.. must be investigate but right now i 'm busy..

**Comment by odiea** [comment]
You can try this and see how it works on a printer. Application/views/sales/quote.php. line 132 change both textarea to text.

**Comment by mckaygerhard** [comment]
um i dont know if that will work! i think is a problem of parsing data

**Comment by mckaygerhard** [comment]
sorry @odiea pardom me, i refers to the problem of quotation! not about fit into the invoice print
