### ISSUE TITLE
Invoice numbers

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1986]
### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is:  W10
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue /  Question / New Feature

When making an invoice, and an error occurs during making it, if operator goes back in browser he can't undo changes. That's fine. But if operator deleted that particular invoice, he cannot make another one with the same number. That is quite a problem, because skipping invoice numbers is not legal in my country, all invoice number must be sequential once issued. 

So, it would be OK to enable some kind of "timing" in which operator can delete/change invoice.

**Comment by SteveIreland** [comment]
The system is intentionally designed to not allow invoices to be deleted or altered because that would introduce criminal opportunities. However, all things can be hacked if you need it bad enough but you'll need to do it manually.

However, if the system failed to create the invoice the opportunity to reassign an unused invoice depends on how you are assigning the invoice numbers.  If it's using the built in counter then you could actually go in and change the next number to be used via configuration.

**Comment by daN4cat** [comment]
This reminds me of a guy a couple of years ago who was adamant in his request and justifications of altering invoices.
I explained the same, we don't implement bad behaviours...

**Comment by dvidic** [comment]
@SteveIreland No, I use custom invoice number format...
I understand legal aspect of invoice alternation, that's why I wrote about some kind of timing in which operator can change invoice, and after that period invoice is locked. It's very common to make a mistake in invoicing. In my country if you have invoices 1, 2, 3, 4, 5 is skipped, 6...etc., you have to make a document what happened to a invoice number 5.

**Comment by mckaygerhard** [comment]
@dvidic this its a not possible to implement due legal issues, you must made by your own! and maybe its no so difficult.. see the code in the SAle library php file to start

**Comment by WebShells** [comment]
Things are clear now... will close this issue.

**Comment by mckaygerhard** [comment]
i'll post in my personal a powered fork a complete process and each query made in the item create, sale process and also customer create so each user that wants to made those modifications can doit by it selft

check at https://osposweb.github.io/osposweb/ospos-5-DEVEL-2-procs-min-sqls-es#4-consultas-de-ventas
