### ISSUE TITLE
Add "Default Discount" as an Item Option.

### ISSUE THREAD

**Issue by JigoloPete21** [opensourcepos/opensourcepos#1989]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

While having a global "Default Sales Discount" can be useful in some cases, allowing a user to specify automatic default discounts to specific items (or categories of items) allows greater flexibility and fits more use cases.  Even though users can currently apply discounts 'on the fly' during a transaction, it would save time and reduce errors if automatic item discounts were an option.  Example: A store owner decides to put a specific range of goods on clearance and now needs to either manually apply discounts to each clearance item prior to completing the transaction, or reduce the retail price for all clearance items (which doesn't show the customers their discount savings on the receipt).  Adding a "Default Discount" field in the item page or something similar would be a great solution for this.

**Comment by JigoloPete21** [comment]
Correct.  I am not sure how much effort it takes to create a new column on the item page, however I figured it wouldn't be too difficult since you can add discounts to each individual item on the Sales page prior to completing a transaction.

**Comment by mckaygerhard** [comment]
i mean: create  new column and make some operation with "hard coded sources" are easy,, but a standar custom field that will affect all the items implicates touch already coded operations over taxes, prices and others over the items, that's why its not so easy @JigoloPete21 

if you need that you can made a default value when each item will be inserted/input in the store/inventary by hardcoded the input value of some of the already made filets.. 

to start develiop please read the wiki that has not so vage information as README

**Comment by SteveIreland** [comment]
I assume most handle item level discounts by reducing the price. A solution that seems more in line with your objectives is to associate a discount with a category and all items in that category would have that discount applied

**Comment by JigoloPete21** [comment]
Category discounts are indeed a good solution as well.  Not sure what it would take to develop such a feature, but figured I'd address it.  If no one wants to pick up this task then feel free to close it.
