### ISSUE TITLE
Deposit amount to generate new bill.

### ISSUE THREAD

**Issue by w002qaa** [opensourcepos/opensourcepos#1991]
Hello

I am using ospos version 3.1.1 
In my business; customer request service from me. I can not do their request without min deposit based on the total amount. 
I want to generate bill or receipt  if the customer pay at less minimum deposit, when the customer come to pick his order must pay the rest the amount with new update for the bill

**Comment by SteveIreland** [comment]
You can post a deposit against a work order.  The work order can be printed but I do not recall if payments are included but I’ll check in to that. If so would that satisfy your requirements s?

**Comment by w002qaa** [comment]
Hi SteveIreland
What do you mean by work order? Is it a module in the ospos? I could not see it. I think that what I am looking for.

**Comment by WebShells** [comment]
Hello @w002qaa the work order feature wasn't available in 3.1.1 I guess... @SteveIreland?

**Comment by SteveIreland** [comment]
@WebShells is absolutely correct.  It just seems (to me) like it's been there forever.  I added that for a service oriented shop.  Originally we were using a flavor of quotes for that purpose, but there were numerous problems with that approach, so support for work orders was added.  Looks like you'll need to upgrade to 3.2 to take advantage of it.  Sorry.

**Comment by mckaygerhard** [comment]
an explanation of how work the Work Orders in ospos would be grat, but an explanation to post in the wiki.. please..

**Comment by jekkos** [comment]
@mckaygerhard thanks btw for the extensive work on improving the wiki. I think currently the detail and quality superseeds what is in the INSTALL.md. Maybe we should consider cleaning up the  older parts and integrate it in the structure that you created. ALso +1 for the cloud native install method. Think I should also remove  the Docker cloud  as  leaving it there will make it confusing for most users.

**Comment by jekkos** [comment]
MIght be better to codense everything in one place and thus refer to the wiki for installation instructions

**Comment by jekkos** [comment]
Maybe we should agree on adding documentation as being part of the development process of the app here.

Like every time a new feature is added, some docs about how to use need to be added to the wiki. Any thoughts?

**Comment by mckaygerhard** [comment]
@jekkos i do not agree at all! you are thinking as due you are always connected to the network.. 

in nomadays i download a software and everything i need to install and use it was inside the tar ball..  today in very few countris all people are connected to the network, but in mayority people do not have good connections to the network and are very very expensive!

@jekkos that's why ther's too many duplicate issues, ther's why too many duplicate work

i improved the wiki due that wiki can be cloned and put as git submodule in a git repository, and i distribute alongside in my derived "less complicated" fork!

this project are ver very bad organized compared with other where i in!

**Comment by jekkos** [comment]
@mckaygerhard Not a good attitude to complain about this, better is to improve and then make it better so we can stop complaining, which is also my aim here.
I think you misunderstood my first answer as everyone should decide how he wants to setup the app himself. If you wanna go cloud we just have a 'recommended' way and that's it.

**Comment by SteveIreland** [comment]
To borrow from the great Homer Simpson .. "Ummmm ... whiskey,"

(I think he preferred donuts and I am okay with that too.)

**Comment by WebShells** [comment]
Will close... Updating to the latest version will do the job for @w002qaa ...
