### ISSUE TITLE
setting and employee not visible

### ISSUE THREAD

**Issue by nejoomst** [opensourcepos/opensourcepos#1992]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I have setting up ospos, all of sudden the employee and setup icons are not visible and could not find. can you help me?

**Comment by daN4cat** [comment]
Please fill in the template.

**Comment by SteveIreland** [comment]
Also, did you click on the office icon to see if those options are available in the office submenu?

**Comment by nejoomst** [comment]
i could not see the office icon in the panel.
![image](https://user-images.githubusercontent.com/39548248/40419344-1e815770-5e96-11e8-9903-19698fa0b771.png)

**Comment by WebShells** [comment]
@nejoomst please fill in the issues template so we can help you with your request...

**Comment by SteveIreland** [comment]
On a clean new install the office icon will be available and you'll be able to click on it and see the option for Employees and Configuration.  

If you are upgrading from an older database (possibly trying to skip intermediate releases) then it looks like you will need to do something special to populate the necessary permissions, modules, and grants tables and there are probably other issues waiting for you to stumble over.

**Comment by SteveIreland** [comment]
@jekkos did you classify this as a bug because you were able to replicate this issue?

**Comment by yatinkanekarinfipre** [comment]
Is this Issue Solved? Or Do we have any ETA to solve this issue?

**Comment by SteveIreland** [comment]
Try typing in your domain with /office at the end.  You might have accidentally flipped the switch to hide the office icon from the home page

**Comment by SteveIreland** [comment]
From the wiki ...

The Office menu option which appears on the Home menu group can be removed from the Home menu group via a configuration option on the General configuration tab. The result of this option is that the user must click on a link or type in the URL in order to access the office menu. This isolates it a bit from the home page so that no one will try to go into the office menu unless they are authorized and know what the URL is for it.

**Comment by mckaygerhard** [comment]
https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-Configuration

**Comment by jekkos** [comment]
AFAIK the module setup works for fresh installs (and for upgrades), so not clear how to reproduce this issue. @nejoomst were you able to resolve this after all? If yes what was the issue?
