### ISSUE TITLE
Receiving Report Issue on DB migration from 3.1.0 to 3.2.0 

### ISSUE THREAD

**Issue by nathanzky** [opensourcepos/opensourcepos#1996]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is:  4f5ad57
- PHP version is: 7.0.21
- MySQL or MariaDB version is: 5.7.18
- OS and version is: RHEL7.0
- WebServer is: Apache2
- Selected language is: en_US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 7.0.21

### Issue / Bug  / Question / New Feature

I have issue on issuing the detailed receiving report the total cost is set to zero "0" after DB import. I attached the report captured from 3.1.0 and 3.2.0.
Is there any extra step to makes sure that the DB are properly migrated?

![rcv_3 1](https://user-images.githubusercontent.com/26484936/40471765-abd233f8-5f48-11e8-9f67-7ad14dde24d7.JPG)
![rcv_3 2](https://user-images.githubusercontent.com/26484936/40471767-abff7f7a-5f48-11e8-8468-82f7c1c8c075.JPG)

**Comment by nathanzky** [comment]
here is the attached log.. hope this will help..

[log-2018-05-28.log](https://github.com/opensourcepos/opensourcepos/files/2044172/log-2018-05-28.log)
[Query-log-2018-05-28.log](https://github.com/opensourcepos/opensourcepos/files/2044173/Query-log-2018-05-28.log)

**Comment by SteveIreland** [comment]
I don't know what @mckaygerhard is looking for, but I didn't find the logs helpful. However, I would first be interested to know what is causing the total cost to be zero.  

I looked at the 3.1 to 3.2 migration script and there isn't anything "obvious" there that would impact the receivings report. 

When you expand the receiving summary for one of those items that have a zero total do the details look correct or are the totals at the line level also zero?

Not all of the receivings have a zero total, so can you provide some information about what might be different about the items on the receivings with a zero total than the items on the receivings that are correct?

Also, do you have the ability to use PHPAdmin or something equivalent to look at the individual records in your migrated database to see what columns of information might not look right compared to the others?  I'm interested in which column in the receivings_items table is zero that shouldn't be.  

For example.

![image](https://user-images.githubusercontent.com/23066623/40619607-bc92d364-6263-11e8-9b9a-ad80f34b1f4e.png)

There IS an SQL statement in the 3.02 to 3.1.1 migration script that could explain the issue if you never ran that script.

`UPDATE ospos_items SET receiving_quantity = 1 WHERE receiving_quantity = 0;`

You can safely use PHPMyAdmin to run that statement to see if that fixes the problem.

**Comment by SteveIreland** [comment]
If you are actually upgrading from a 3.02 database instead of a 3.1.0 database there there are probably other issues on the near horizon for you.

**Comment by SteveIreland** [comment]
Neither migration script actually touches the `receiving_quantity` field on the `receivings_items` table which I think might be the problem.  I don't believe that field should ever be zero. 

If you think it is appropriate then you might want to try running the following to to fix it.

`UPDATE ospos_receivings_items SET receiving_quantity = 1 WHERE receiving_quantity = 0;`

After fixing the database rerun the report to see if that improves the situation.  If it does then I'll add that to the 3.2.0 to 3.2.1 migration script.

**Comment by mckaygerhard** [comment]
i revised the logs for some inserts and then revised for make each query step by step but i not have same results.. maybe i not make property each query (yeah sound very tedious task but..)

**Comment by nathanzky** [comment]
Is there some steps or scripts I have to run after importing the DB.sql.
What I undestand is that it should be automatic DB upgrade at first login.
Maybe I miss something?

**Comment by daN4cat** [comment]
From 3 onwards yes, but if it's before 3.0.0 you need to manually upgrade the database running the upgrade script.

**Comment by SteveIreland** [comment]
The requirement that the receiving quantity on the receivings_items tables be something other than zero was introduced back in a commit on 6/24/2017 - making it introduced in the 3.1.0 release.  That makes total sense to me, but I can't find where there was a migration added to insure that the receiving quantity is 1 or greater.

@daN4cat Do you want me to add that fix statement to the 3.2.0 to 3.2.1 migration script?

**Comment by daN4cat** [comment]
@SteveIreland yes please fix the script.

**Comment by daN4cat** [comment]
So I can finally release 3.2.1

**Comment by SteveIreland** [comment]
The pull request has been submitted.  Merge and publish!

**Comment by daN4cat** [comment]
Done and thanks.
