### ISSUE TITLE
File index OSPOS 3.2 is only show code

### ISSUE THREAD

**Issue by whoami1904** [opensourcepos/opensourcepos#1997]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is: 7.0 
- MySQL or MariaDB version is: 5.7
- OS and version is: Ubunt 16.04
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi,
- I am facing a poblem, when i access web interface ospos it is on show code not interface. I had follow instruction "http://www.opensourceposguide.com/guide/gettingstarted/installation".
![1](https://user-images.githubusercontent.com/39585711/40476450-3ec8a8d4-5f6e-11e8-88de-27fb8de2cab2.png)

**Comment by WebShells** [comment]
Hello @whoami1904, please fill in issue template or else this issue will be closed.

**Comment by whoami1904** [comment]
I still don't understand. Pls show me. where can i fill?

**Comment by WebShells** [comment]
Filled, much better... Are you redirecting in a way or another? Since the main login page loads in public directory..

**Comment by mckaygerhard** [comment]
use the wiki instructions, seems your php instalation are not working that's why are show in the source event interpreted the php code!

**Comment by whoami1904** [comment]
- After i had install phpmyadmin, i no longer above error any more. But i get error: 
Forbidden
You don't have permission to access / on this server.
- And then i edit file "/etc/apache2/sites-available/000-default.conf 

![000-default-config](https://user-images.githubusercontent.com/39585711/40498331-f0c7ec54-5fa8-11e8-9f11-0aee75bd53c3.JPG)

i get error:
![error](https://user-images.githubusercontent.com/39585711/40498236-a8ce9664-5fa8-11e8-9b3f-48045bced188.JPG)
These files that i had edit:
![apache2-config](https://user-images.githubusercontent.com/39585711/40498262-bcefed5a-5fa8-11e8-8509-1a446022e52c.JPG)

![database-php](https://user-images.githubusercontent.com/39585711/40498272-c32f6af6-5fa8-11e8-8e0c-5b60d05da2a5.JPG)

![htaccess](https://user-images.githubusercontent.com/39585711/40498278-c9b3293a-5fa8-11e8-8f3f-5d5e8ef490ed.JPG)

**Comment by mckaygerhard** [comment]
document root are bad! please read the instruction wiki, of course if you point at the public only the rest of the installation will be not available for all the ospos application!

also dont paste images, use gnu linux terminal copy paste and mardown gtthub format! i hard to waith render images!

**Comment by whoami1904** [comment]
- May you show me where i am missing? or give me link that is instruction full installation on fresh ubuntu. I am really stack at here. :(

**Comment by mckaygerhard** [comment]
https://github.com/opensourcepos/opensourcepos/wiki#documentation

**Comment by WebShells** [comment]
@mckaygerhard @whoami1904 was this solved ? shall we close ?

**Comment by mckaygerhard** [comment]
@webshells please close it, solution was provided and also wiki procedure for install was not uses, if @whoami1904 need furter help will post more comments, so please close it!

**Comment by mckaygerhard** [comment]
@WebShells please close it, solution was provided and also wiki procedure for install was not used, inteface are from ruindows maycrosoft and proper installation are not used, so if @whoami1904 need furter help will post more comments, so please close it!

**Comment by WebShells** [comment]
Thanks @mckaygerhard...

**Comment by whoami1904** [comment]
@WebShells <https://github.com/WebShells> please close it ,I had solved. 
Thank you for your support.

I will post installation completely, show and fix problem that i facing 
while installed.

*Hang Vinh Nam* | IT Staff | *The Annam Group*
322 Dien Bien Phu, W22, Binh Thanh District, Ho Chi Minh City , Vietnam
T: +848 3512 6400 | F: +848 3512 6401 | M: +84 (0)9 090 70 842
www.annam-group.com <http://www.annam-group.com/>
