### ISSUE TITLE
item requisites

### ISSUE THREAD

**Issue by nejoomst** [opensourcepos/opensourcepos#2000]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

dear, if we place a requisition, how the other store get notified? is the email will go to the particular store/ ware house? can you please clarify.

**Comment by SteveIreland** [comment]
Are you referring to the requisition as documented in the Wiki or something else?  What's in the wiki is a design proposal. I have actually done some work on it, but I've been waiting on @jekkos to complete the item attributes project so that I could take advantage of it.

To answer your specific question, I was going to follow the pattern of the rest of the system by providing the ability to print the requisition, however, the requisition is an internal document that would be used for purposes of soliciting approval to purchase what is "requisitioned".  Then the buyer would consolidate into or build a purchase order from the requisitions.  It can then be printed and mailed, or emailed to the vendor.

**Comment by nejoomst** [comment]
even when we are requesting goods from where house to store or one store to another store, how other person will notified? nothing is there. any sort of message or email should go to the other store, then only they can move the goods from one store / warehouse to other store.

**Comment by SteveIreland** [comment]
OSPOS does not yet support multiple stores.  

There is work in progress on it in support of ticket #150 but it's not available to try out yet.

You can try to use the location feature but it is going to be severely limited in what it can do.

**Comment by SteveIreland** [comment]
I was playing around with this today and was wondering how companies are currently using OSPOS to transfer inventory between one locations.  There are three options that I can find. 

1. Item maintenance can be used to adjust inventory to reflect any transfers.

2. The receiving function can be used to manually adjust inventory, but similar to sales and returns it would need to be two separate documents.  In this cause you would want to set up the store as the supplier.

3. Sales and returns can also be used to transfer stock between locations.  For this it seems like you would want to set up the store as a customer to insure that sales and return values net out to zero.

**Comment by SteveIreland** [comment]
If there isn't any followup soon I think this can be closed.

**Comment by WebShells** [comment]
@SteveIreland I don't think this is planned anytime soon... Although multi shop feature is something good to consider in the project...

**Comment by jekkos** [comment]
I do have a docker build of this multi store on docker hub..

**Comment by WebShells** [comment]
@jekkos will you have anytime soon to recheck it? Or shall we close this one?
