### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Ezyweb-uk** [opensourcepos/opensourcepos#2001]
demo.opensourcepos.org gives 502 Bad Gateway

**Comment by SteveIreland** [comment]
This is a demonstration of how to properly render a 502 Bad Gateway error.

I'm glad to see it works.  :-)

**Comment by WebShells** [comment]
May we share this moment ? LOL Steve...

**Comment by mckaygerhard** [comment]
well @Ezyweb-uk since som specific commit demo still now work, will be back later dont worry, i dont remember the exact commit but was some weeks ago.. due ospos developers still have working on something for 3.2.1 release

**Comment by jekkos** [comment]
Demo is back in the air. I recreated the deploy script and enabled a swapfile on the server (MySQL wouldn't boot due to that)

**Comment by Ezyweb-uk** [comment]
Great, but I can't see the login credentials, am I missing something?

**Comment by odiea** [comment]
Current Demo. Create an expense and an expense Category and both Descriptions display the following.
csrf_ospos_v3 = 963032a802987fdc5ad86954c9e73e24. Also no Office Icon in demo.

**Comment by mckaygerhard** [comment]
confirmed

**Comment by daN4cat** [comment]
Fixing as part of #2009 and issuing a Release 3.2.2

**Comment by SteveIreland** [comment]
Okay, I finally see why you had to revert the csrf change.

**Comment by mckaygerhard** [comment]
about DEMO SITE cannot confirmed working due credentials are not working, admin and password are not work, maybe some guy changed !

maybe @daN4cat do you applied  2e7e9ce a direc git revert over past commit or manually by coding? maybe some code might be missing?

**Comment by odiea** [comment]
Demo site still down

**Comment by daN4cat** [comment]
Works for me.

**Comment by odiea** [comment]
This is all I have seen for the last few days.

![2018-06-09 05_38_11-window](https://user-images.githubusercontent.com/10962177/41191096-83055f66-6ba7-11e8-8562-53766deff9a5.png)

**Comment by daN4cat** [comment]
Right, the usual "funny chap" that believes to be really funny blocking out people and setting language to be Spanish.

**Comment by SteveIreland** [comment]
Is it possible to trigger the refresh of the demo site without doing a merge and affecting the commit history?

**Comment by daN4cat** [comment]
Just committing a change to GitHub triggers the CI/CD and the demo is reset.
I touched the README and now it's fine.

**Comment by SteveIreland** [comment]
Sounds good ... thanks.

**Comment by odiea** [comment]
Demo server not accepting user name or password. Good luck with this.

**Comment by daN4cat** [comment]
I'm going to commit something that will reset everything.

**Comment by WebShells** [comment]
Well... @daN4cat 502 Bad Gateway now...

**Comment by SteveIreland** [comment]
Ditto on the bad gateway for demo. 

I just pulled the latest commit and built a test environment from it and it starts up fine as it always does.

**Comment by WebShells** [comment]
Am not sure what caused this... did a demo reset and unable to show it again :x

**Comment by mckaygerhard** [comment]
hi @jekkos demo site are still not working! still (or again) bad gateway

**Comment by WebShells** [comment]
Will do a refresh... Thanks!

**Comment by daN4cat** [comment]
@WebShells BatW the js script issue in the form is something I fixed and in master now.

**Comment by WebShells** [comment]
It needs maybe 10 to 15 mins to refresh, right?

**Comment by jekkos** [comment]
Disk full again, need to check why exactly, but I kicked it and it's running again

**Comment by mckaygerhard** [comment]
too late! i opened in #2047 i mantain open until reason for disk full are find or a considerable time are passed

**Comment by odiea** [comment]
Demo down again. This time with a different language.

**Comment by WebShells** [comment]
Resetting...

**Comment by mckaygerhard** [comment]
maybe this problem it's due something wrong that the configuration have?

**Comment by daN4cat** [comment]
works fine now
