### ISSUE TITLE
please explain registration consent for doc and users

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2003]
in ospos 3.2.X master there's the chcke for registration consent.. i was thinking that with "checked" user was acept and ok but if not checked? i noted that in any case the new customer are inserted and present in the database?

so what exactly are the behaviour of that?

**Comment by WebShells** [comment]
@mckaygerhard its for replacing clients firstname and lastname with his ID for data privacy... In both cases customer will be inserted into database but it will be depending on the config ( Enforce privacy ) selected in configuration or if the box is checked or not.... GPPR regulations i guess... Not applicable in my region :x

**Comment by mckaygerhard** [comment]
ok thanks, now i'll put that info in the wiki page for clafiry. and added CPPR feature complain to the feature data sheet of the wiki page
