### ISSUE TITLE
Item avatar in Sales

### ISSUE THREAD

**Issue by julianishaqi** [opensourcepos/opensourcepos#2004]
- [x] Reporting an issue of an unmodified OSPOS installation
-  [x]  Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
-  [x]  Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
-  [x]  Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
-  [x]  Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x]  Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
-  [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is: PHP 7.0 
- MySQL or MariaDB version is: MySQL 5.6 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
Hello

I need to get item avatar in the ""Sales". Is there any easy way to modify the sales page and get the images of each items?

![image](https://user-images.githubusercontent.com/11313777/40655059-6de7dcb8-6340-11e8-8cbc-9de806017c9c.png)

**Comment by WebShells** [comment]
Well yeah it can be done, yet it wont be visible due to table size... And might take some more time to load..

**Comment by julianishaqi** [comment]
It is critical for me to see the image of item in the sales, is it the file Sale.php in application/models which i should edit?

**Comment by SteveIreland** [comment]
You would need to add the name of the image to the item array in Sale_lib.php and then add it to sales/register.php view.

**Comment by daN4cat** [comment]
It will slow down the register as it reloads the page every time you add an item. I wouldn't add that with the current UI design.

**Comment by WebShells** [comment]
Yeah exactly as I mentioned... It will slow down the whole page

**Comment by mckaygerhard** [comment]
well @daN4cat have right only if ospos are using with slow OS, 

but dont are so slow or at leas no more that traking user or retrieve on each request all the icons and css image data from google api!

if you want to do by selft @julianishaqi must read those pages:

1. https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#code-and-api-documentation
2. https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-DEVEL-Add-a-custom-field-to-the-Sales-Register
3. https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-DEVEL-for-Error-Logging-in-OSPOS
4. https://github.com/osposweb/osposweb/blob/gh-pages/ospos-5-DEVEL-2-procs-min-sqls-es.md this make idea of the data retrieve from the sales lib

sales lib make the magic, but take the current sale suspended or new into the session object ...

also there's an issue that modifiy directly the view of the sale, there, after extrat (taken from sale lib) the field/colum/arraykey of the image and retrieve from the item array, you must put in the view by modified the css/html respectivelly

**Comment by daN4cat** [comment]
@mckaygerhard you keep missing the point, I'm afraid I can't help.

**Comment by SteveIreland** [comment]
Good luck @julianishaqi.  If you're successful I sure would like to see the finished product.

**Comment by mckaygerhard** [comment]
i understand @daN4cat but locally there's no sense of those mechanis to cheap bandwicht, all runs locally..

umm maybe i can make a flag configuration in near future that load image in resized fit and send a pull request..  i'll studi tha this weekend and send feedback here

**Comment by jekkos** [comment]
Feature request not accepted (as discussed) so will close. Adding avatars to sales register will overload the screen as it is now.

**Comment by cmthai** [comment]
![Untitled5](https://user-images.githubusercontent.com/119729029/207753074-31c6b6a3-d87e-487b-acc1-1b5e1d02e5ce.jpg)
