### ISSUE TITLE
How can I make suspended sales to affect the inventory?

### ISSUE THREAD

**Issue by Saiuke** [opensourcepos/opensourcepos#2005]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

    OSPOS version is: 3.2.0
    OSPOS git commit hash is: 4f5ad57
    PHP version is: 7.2
    MySQL or MariaDB version is: 5.7.14
    OS and version is: Windows 10
    WebServer is: Apache 2.4.23
    Selected language is: Spanish
    (If applicable) Docker installation:
    (If applicable) Installation package for the LAMP/LEMP stack is:

### Question

I use the "Suspend Sale" feature to manage unpaid sales from my customers. For that purpose, would be better if such sales affected the item's inventory, even if being only suspended and not completed. How can I do this? And, out of curiosity, how do you use to manage the unpaid sales?

PS - I've read some issues concerning this, and the developers come to the conclusion that suspended sales should not affect the inventory. In my case, I belive that the oposit suits me.

**Comment by SteveIreland** [comment]
You are correct, suspended sales should not be used to track unpaid sales.  That is the domain of an accounts receivable (a.k.a. debt management) application.

I'm pretty sure  you will be on your own with this one and it will be a delicate operation.

No one would want to lose the ability to suspend a sale. The invoice feature is designed for unpaid sales and it would be far simpler to add the ability to add payments to a completed invoice.

**Comment by Saiuke** [comment]
It's a good idea. Really. But, how can I track, in a fast and simple way, the receipts with pending payments?

**Comment by Saiuke** [comment]
Well, thanks, I'll look into it. I tought that there was a simpler way. Like, when I clicked "Supend sale" it would trigger the database update.

**Comment by mckaygerhard** [comment]
if you are taking of a one paymet only can manage with the due feature of the ospos, but the sale will be marked as completed..  suspended sale may help with both scenarios are for one payment only, my brand if o track many payments.. it's not so simple so you are taking about a "due" but of a uncomplete sale..  the desing of the sale process cannot apply due the uncomplete sale are not a sale per se as i can see until are completed, its like ruindows maycosoft.. not desined to be usefully... or are a completed sale or not, so a modification are mandatory!

**Comment by mutasaleo1** [comment]
i think the guy is trying to say "how do u manage your payments in case your clients are doing part payments"  Lets say your client pays $100 and he/she is suppose to pay $200, after a week how do you add the other $100 in case he comes to pay it off? there should be a way to edit a sale so that we can add some money to it on a different date. As is stands the sales module is useful when your clients pay in full.

**Comment by daN4cat** [comment]
Use due payment for the credit. Later when paid pick up the sale and convert the due to what used to pay (e.g. cash). You can edit a sale to change form of payment.

**Comment by daN4cat** [comment]
@mutasaleo1 a deferred payment is supported.

**Comment by mutasaleo1** [comment]
@daN4cat  thanks bro im sure its also clear for everyone...my question is "how do you convert a quote into an invoice" if i quote a client today and he/she comes after a week and i want to turn that quote into a sale without redoing the items on my quote.

**Comment by SteveIreland** [comment]
A quote is in effect a suspended sale.  To convert a a quote to a sale simply set the register mode to Invoice and retrieve the quote and and click on the Invoice button.

**Comment by mutasaleo1** [comment]
@SteveIreland yes it does all that but i think in future if we can have them saved so that we can revert back using quote # or scrolling up or down. The other thing is we can make due payments, but it only allows one month due. Clients cant pay over 2 months or more than that. Some clients want to pay over more than a months. If we can have a facility where we can add payments and it keeps deducting from the total due it will be great.

**Comment by tekkeur** [comment]
> 
> 
> Use due payment for the credit. Later when paid, pick up the sale and convert the due to what's used for the payment (e.g. cash). You can edit a sale to change form of payment.

@daN4cat How edit a sale to change form of payment?

**Comment by WebShells** [comment]
@tekkeur you can edit it from the takings section (its now called daily sales), set the date of transaction and search for client name or you can select to filter due payments alone.
Update, change due to cash. That means fully paid.
