### ISSUE TITLE
invoice title with dual language 

### ISSUE THREAD

**Issue by tomchom** [opensourcepos/opensourcepos#2007]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is: 5.6.35
- MySQL or MariaDB version is: 5.7.21 / 10.2.14
- OS and version is: Windows 10
- WebServer is: Wampp local Server 3.1.3 
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

hello,  I want to change the different invoice title to an another language [i,e Arabic] along with English. please help me to do this. 
Please see the attached image i pictured where i want the changes. 

thanks for the Help

![dnp7aqb](https://user-images.githubusercontent.com/39748973/40695623-cff3192e-63e3-11e8-8771-9717ba99330b.png)

**Comment by mckaygerhard** [comment]
err i thnk that are not possible, many fields are stored in database "as is" so some sale attributes are stores as the languaje spelled!

so i guess, due i canot see any attached image from your issue,  the only solution its to hardcoded in specific languaje..

**Comment by tomchom** [comment]
sorry, I've updated the post with image. please check again.
