### ISSUE TITLE
Cant get to work please help redirected you too many times

### ISSUE THREAD

**Issue by thelowlow** [opensourcepos/opensourcepos#2008]
i have installed the lastest files to install and i get to the log in page and then enter the login and get a error message that says ' 

This page isn’t working
thelowlow.dx.am redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS'

CAN YOU PLEASE OFFER ANY ADVICE TO WHY THIS IS DOING THIS PLEASE HELP THANK YOU 

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by mckaygerhard** [comment]
the issue template information filed does not help in any thing!

please provide:
* what process (link exactly) do you follw to install the system
* from where do you download the ospos software

i dont understand why the ospos developers stil have this very vage template and the very vage INSTALL and README files, puff

**Comment by thelowlow** [comment]
https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=desc#files and installed via readme and install files via FTP

**Comment by mckaygerhard** [comment]
the readme file are very vage and poor informative,  please use the wiki pages, https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-Getting-Started-installations download again from same bintray and repeat the process and then post feedback here
