### ISSUE TITLE
many 500 error on any instalation

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2009]
i-ll cheap all the template and said the spoecific commit that work:

b13ac8d4f01867cb549ab89ba28c69a1eeec7b23

until the next code changes there's only translattions commits, so i dont know, i guess something in csrf simplifications .. i cannot find any more..

**Comment by SteveIreland** [comment]
I just now installed 3.2.1 and run a quick run through. So far I haven't seen any 500 errors.

**Comment by mckaygerhard** [comment]
all in updates cases!.. i cannot make the log for SQL operations. when i enable it! got 500 errors! so i cannot log the sql errors, i pretty sure there-s in updates, on fresh install seems fine

**Comment by mckaygerhard** [comment]
directory log premission are right etc etc (remenber i wrote the wiki log instructions very detailed)

also some errors when update employees information

**Comment by daN4cat** [comment]
Is the demo website working fine?

**Comment by odiea** [comment]
I don't know if all is ok. I did a pull this morning now the Office Icon does not show on my local version

**Comment by daN4cat** [comment]
demo seems to work fine

**Comment by mckaygerhard** [comment]
demo has problems, as seems reported,

-  icon office are not showing, Current Demo. 
- Create an expense and an expense Category and both Descriptions display the following.
csrf_ospos_v3 = 963032a802987fdc5ad86954c9e73e24.
- some 500 errors
- sql errors are only happened to me (due i cannot see the demo log)

**Comment by nerv55** [comment]
Tested and I  have errors too randomlly and icon office does not show

**Comment by daN4cat** [comment]
The csrf change is no good. I said not to merge it....
I'll revert it and issue a 3.2.2 release.

**Comment by mckaygerhard** [comment]
um please @daN4cat waith i said maybe csrf but maybe can be other change. i not investigate well, the commit i put to refer only are about the 500 errors, the rest of the problems i reporte are n the demo site, and the sql errors are before that commit

**Comment by daN4cat** [comment]
Release 3.2.2 with the revert of CSRF change

**Comment by jekkos** [comment]
Indeeed I thought there was an approval on the pr before merge. The fact that some fields show the token points to another security issue, namely an insecure direct object reference. Meaning that any field in post or get is rendered by a view, sounds fishy to me.

**Comment by jekkos** [comment]
Failing csrf should yield status 4xx not 500 imho

**Comment by daN4cat** [comment]
Yes not related to 500 but behind different issues reported.
As far as I remember I said not in 3.2.1. Anyway it's past.

**Comment by mckaygerhard** [comment]
hi guys and @daN4cat do you applied 2e7e9cecd8d7d38ca394692d43f1b0200b950f8b with revetion fo CSRF i still get 500 but only at firts login, after manually set the url with index.php hardcoded got everything right..

do you applied 2e7e9cecd8d7d38ca394692d43f1b0200b950f8b a direc git revert over past commit or manually by coding? maybe some code might be missing?

**Comment by mckaygerhard** [comment]
hi guys and @daN4cat do you applied 2e7e9cecd8d7d38ca394692d43f1b0200b950f8b with revetion fo CSRF i still get 500 but only at firts login, after manually set the url with index.php hardcoded got everything right..

do you applied 2e7e9cecd8d7d38ca394692d43f1b0200b950f8b a direc git revert over past commit or manually by coding? maybe some code might be missing?

@jekkos and @SteveIreland the 4xx status only got one time but i not give imnportance, so then now i know certanlly was due the csrf related, but now as i said got some problems..

about **DEMO SITE** cannot confirmed working due credentials are not working, admin and password are not work, maybe some guy changed !

**Comment by jekkos** [comment]
Correct can't login to it either. Let me refresh

**Comment by mckaygerhard** [comment]
thanks @jekkos i'll test deeply in some coupe of hours and reports feedback later ...

**Comment by jekkos** [comment]
Ok refresh done

**Comment by jekkos** [comment]
Well actually I did test csrf change thoroughly, maybe not the expense part, but that might be due to another side effect. Will have a look once I am back home

**Comment by daN4cat** [comment]
One guy reported a fix as comment to a commit. Look into that.

**Comment by jekkos** [comment]
Yes saw that comment. Will make a new build somewhere this weekend with that suggestion.

**Comment by mckaygerhard** [comment]
the comment fix: https://github.com/opensourcepos/opensourcepos/commit/c9a50cdeaf82c675507cea4e617fde16efe38cb6#commitcomment-29294019

**Comment by daN4cat** [comment]
Restored the CSRF change with the fix suggested in the comment (add & otherwise the param is concatenated with the previous param).
