### ISSUE TITLE
Edit Lines In Existing Sales

### ISSUE THREAD

**Issue by satanogo** [opensourcepos/opensourcepos#2010]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is: Version 5.6.30 & 7.1.1 (AppServ Information)
- MySQL or MariaDB version is: 5.7
- OS and version is: Windows 7 64 bits
- WebServer is: AppServ
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Question/New Feature

Hi OSPOS Community, Im been working for a while with the OSPOS and i liked it so much, But i have a question to ask, I want To know how i can edit the lines of an existing sale or invoice, sometimes the sellers make some mistakes so i wanna know how i can edit this sales and invoices

Another question i have, is there an IDE to use with this project to include new features to this software, or how can i include new features to this software?

**Comment by mckaygerhard** [comment]
> sometimes the sellers make some mistakes so i wanna know how i can edit this sales and invoices

must depend of the misctake! be more specific!

>is there an IDE to use with this project to include new features to this software, 

NOp! use leafpad, mousepad, any source editor, that-s all

> or how can i include new features to this software?

https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index

**Comment by SteveIreland** [comment]
When a sale is complete it cannot be changed. The proper way is to issue a full credit for the sale and then create a new sale.  That way you have a proper audit trail.  It makes the certified public accountants happier.  There have been numerous requests to allow changes after a sale is complete.  That's not going to happen because it would provide a way for others to make a sale, collect the cash, pocket some of the change, and adjust the sale for what was pocketed.

I use JetBrains PHPStorm as my IDE of choice.  You can use whatever your comfortable with.

**Comment by satanogo** [comment]
Yes I get it Steve is a hard procedure and a "illegal" one, i think im going to leave it just like this and see if i can teach the correct procedure to administrators.

Sounds good i think im going to try the JetBrains and the PHPStorm to make some changes to the Project

**Comment by satanogo** [comment]
@SteveIreland I Would like to know more about how to include the project to the IDE and start to work with it, cuz  i want to make some changes, maybe these changes could help someone (instead of me), So i'll Be waiting Your Answer

Thanks in Advance

**Comment by SteveIreland** [comment]
The correct way is to first fork the project in GitHub and then from PHPStorm you checkout your fork  from GitHub which clones the repository to your IDE.

You'll then add an upstream connection to the original opensourcepos repository so that you can stay syn'd with it.

There are numerous tutorials on the process so have fun and good luck..
