### ISSUE TITLE
Register sales from my Android App

### ISSUE THREAD

**Issue by lexcorp** [opensourcepos/opensourcepos#2012]
New Feature:

I want register sales to opensourcepos from my Android App, It's possible? Maybe web service?

**Comment by WebShells** [comment]
Please check other issues before opening a new one...

**Comment by mckaygerhard** [comment]
there-s no other issue like this @WebShells  a client app it's not same as a register sale only.. 

**we have a similar app that work offline**, @lexcorp you can open a issue at my fork in gitlab, from https://gitlab.com/osposweb/osposos, of course you need a gitlab account and we can disscuss that
