### ISSUE TITLE
Cash and Credit in Payment Summary Report 

### ISSUE THREAD

**Issue by whoami1904** [opensourcepos/opensourcepos#2013]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2
- OSPOS git commit hash is: 
- PHP version is: 5.7
- MySQL or MariaDB version is: 5.7
- OS and version is:  Ubuntu
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
How can i get summary payment report cash and credit seperate. I just only add column "total" but can not get amount of total. Amount of Tendered is not right. As i know "Amount of Tendered" is show amount of money that customer give you not price items.

![payment_summary_report](https://user-images.githubusercontent.com/39585711/41028815-6bab4150-69a4-11e8-88e8-3eb9a9f9908e.JPG)

I had add line in /reports/Summary_payment.php 
![summary_payments](https://user-images.githubusercontent.com/39585711/41028972-bdf1bbe2-69a4-11e8-94c5-4260ff59192c.JPG)
 
and /controllers/Reports.php -- line 370 
![reports](https://user-images.githubusercontent.com/39585711/41029106-0dc84898-69a5-11e8-8fc4-849f48126f75.JPG)

I reference /reports/Summary_sales.php. But it did not show amount of total cash and credit seperate as i am waiting :(
Pls, help me.

**Comment by SteveIreland** [comment]
In the example you provided above it shows cash and credit payments received and it shows them separately.  So I'm not clear on what you are trying to accomplish

Your question "How can i get summary payment report cash and credit seperate." doesn't make sense to me because that is what the Payments Summary Report is designed to do.  

If you're trying to add a total to reflect sales for which payment hasn't been received then that's a different topic.

**Comment by whoami1904** [comment]
As you see image attach, I sale 2 bill, price of item is 200,000$. On POS 12, customer pay by cash and they give me 1,000,000$ i must 800,000$ change to customer, and on POS 15 customer pay by credit. So in my cash drawer have only 200,000$, right? But on Summary report show cash is 1,000,000$, because end of shift, i will check summary report and get money from cashier. Do you understand me?

![receipt](https://user-images.githubusercontent.com/39585711/41076834-c44f8084-6a3d-11e8-9e89-d7fffd6e9880.JPG)

![payment_summary_report_1](https://user-images.githubusercontent.com/39585711/41076759-6303722c-6a3d-11e8-95d6-faf28bb982ef.JPG)

**Comment by daN4cat** [comment]
Please use the latest release 3.2.2 and test it again as some changes went in for this report.

**Comment by whoami1904** [comment]
Thank you.
![payment_summary_report_2](https://user-images.githubusercontent.com/39585711/41082163-9081048e-6a57-11e8-87ac-6f582145d79a.JPG)

**Comment by SteveIreland** [comment]
I understand the issue now
