### ISSUE TITLE
Question: KoolReport

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2015]
I was looking to see what the current state of PHP based reporting systems is and stumbled across Kool Report which is also hosted on GitHub.

https://github.com/koolphp/koolreport

It seems to be far more active as far as commit activity than Reportico,  Does anyone have any experience with it?

Instructions for integrating it with CodeIgniter is found at https://github.com/koolphp/koolreport/issues/4

**Comment by daN4cat** [comment]
I looked into that and asked few questions to the team.
However the tool is part free, you need to pay a fee for additional features.

**Comment by mckaygerhard** [comment]
not! @daN4cat, **only paid additional "features" as plugins, the core and system are total free**, by example iterate cross column sql as report its a paid plugin and that's can be done manually

koolreport it's far more easy and far more secure
