### ISSUE TITLE
bug: decimals are not interpreted correctly at expenses module

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2018]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  demo
- OSPOS git commit hash is: demo
- PHP version is:  ??? please!
- MySQL or MariaDB version is:  ??? please!
- OS and version is:  ??? please!
- WebServer is:  well must be apache2 for sure
- Selected language is: en-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

set localte in en-US and let all with default i demo site, then logout and login, then register a expense and said that amount must be set to number, see picture 1, 

so then in picture 2 i register 30000 but when submit picture 3 show register 0!

![ospos-error-locale-decimals](https://user-images.githubusercontent.com/1571724/41160721-919dbf2c-6afe-11e8-9ad4-f1986478c2bb.png)

![ospos-error-locale-decimals2](https://user-images.githubusercontent.com/1571724/41160743-9bc8d932-6afe-11e8-88b2-fc5178c02229.png)

![ospos-error-locale-decimals1](https://user-images.githubusercontent.com/1571724/41160758-a2a27074-6afe-11e8-8694-8da58422b721.png)

**Comment by jekkos** [comment]
Hm I wonder whether it leverages  the backend's locale parsing correctly here, will have a look maybe tonight

**Comment by mckaygerhard** [comment]
also remenber that at demo site any expense when register , the amount registered are alway set ot "0" as aditional detail!

**Comment by daN4cat** [comment]
Fixed and in master.
