### ISSUE TITLE
Release 3.2.3 still with mayor error bugs at expenses

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2020]
seems related with #2018 but error gives now at DB level with related tables, some refers incorrect?

i download a 3.2.2 stable build for test some of the old reportes bugs> https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180606204534.3.2.2.c5632a.zip

installed with defaults and full DB and apache2 access.. here the error SQL log:

```
ERROR - 2018-06-11 09:58:18 --> Query error: Cannot add or update a child row: 
a foreign key constraint fails (`ospos`.`ospos_expenses`, CONSTRAINT `ospos_expenses_ibfk_1` FOREIGN KEY (`expense_category_id`) 
REFERENCES `ospos_expense_categories` (`expense_category_id`)) - 
Invalid query: 
INSERT INTO `ospos_expenses` (`date`, `supplier_name`, `supplier_tax_code`, `amount`, `tax_amount`, `payment_type`, `expense_category_id`, `description`, `employee_id`, `deleted`) 
VALUES ('2018-06-11 09:58:04', 'ASA', 'AsAS', 10, 10, 'Efectivo', '0', '', '1', 0)
INFO - 2018-06-11 09:58:18 --> Final output sent to browser
DEBUG - 2018-06-11 09:58:18 --> Total execution time: 0.2809
```

**Comment by mckaygerhard** [comment]
i found the problem! expense category are empty on ospos at first install so then i try to register a expense, will fail due category are empty..

this are due the 0015bdffcf67816ff5a136758544200a7c093874 commit that remove the example, this are good but need to left a default category! or at leas alert users that category could not be empty!

umm i noted that if some one does not comment or if a issue does not have more that one person involucrated are not take seriusly!

**Comment by jekkos** [comment]
Ok thanks for pointing that out. If we're allowed to delete the last category, then we should also get a proper error message no?

**Comment by SteveIreland** [comment]
Agreed.

**Comment by mckaygerhard** [comment]
umm @jekkos and @SteveIreland why a release has too many bug and git now are too away of the release? a new release will nedd a complete revert of the last commits or a new branch in the git! pufff

**Comment by daN4cat** [comment]
Works fine for me.

**Comment by jekkos** [comment]
I can reproduce it.. the frontend validation is not flexible enough here and refuses to accept a formatted decimal.

**Comment by daN4cat** [comment]
Fixed and in master.
