### ISSUE TITLE
 Release 3.2.2 still with mayor csrf error 403 at register items

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2021]
seems related with #1990 cannot registyer a items, produces **403 invalid access errors, reproducible until git 9796d6cfc33714ff0b9d554e5c879b9719e573a3 commit only with BARCODE input field..**

i download a 3.2.2 stable build for test some of the old reportes bugs> https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180606204534.3.2.2.c5632a.zip

installed with defaults and full DB and apache2 access.. THE PICTURE ILUSTRATE TE PROBLEM

![osposerror-csfr-items](https://user-images.githubusercontent.com/1571724/41242545-d6b9b8ce-6d6d-11e8-8a7d-8b60cc8b256e.png)

**Comment by mckaygerhard** [comment]
same as #2024

**Comment by jekkos** [comment]
might not have been reverted properly, will have a look tonight

**Comment by mckaygerhard** [comment]
the PR send by you only solved agains 3.3.0 i reviewed, but 3.2.2 sitll will suffer due the csfr are after commit 9796d6c that are totally different and need other rewriting of the fix

**Comment by nerv55** [comment]
Bug confirmed I have tested yesterday.

**Comment by SteveIreland** [comment]
I'm not an expert by any means in the area of cross domain scripting errors but noticed that you are using an IP address instead of a domain name.  Since I am not encountering these errors in my tests could your use of an IP address be triggering this?

I've created a virtual domain on my local host to more closely simulate a production setup.  Maybe that is the difference?

**Comment by mckaygerhard** [comment]
umm maybne you send comment afeter recents, but @SteveIreland do you read that this only happened in 3.2.2 and today the lasted has a csfr commit unrelated to 3.2.2 and that-s why are unreproducible? also do you read i not the only with this error and other have it? do you read that only happened in 3.2.2 that means before commit 9796d6c ? maybe that's why you write that

**Comment by mckaygerhard** [comment]
but there's something strange here @jekkos and @SteveIreland the fix in PR at #2025 seems does not affect the 3.3.0 due at demo side everything works good! but i review the code and seems are need! 

i dont understand that's must be reproducible the error at athe demo side and at the git recent but seems works.. only reproducible with 3.2.2 ...

that's due i just tested the PR #2025 agains 3.2.2 and seems fixed the problem: see the picture i dont understand!

![seems-fixed png](https://user-images.githubusercontent.com/1571724/41293664-e7f0c3d8-6e23-11e8-8874-12057c7718bb.png)

**Comment by mckaygerhard** [comment]
#2024 was merged i'll close that but seems solved #2024 too so then thanks @jekkos  and please review the others bug issues too.. please

**Comment by daN4cat** [comment]
In master and I'm going to release it as part of 3.2.3
