### ISSUE TITLE
Suppliers info at Sales Summary Reports

### ISSUE THREAD

**Issue by saruban** [opensourcepos/opensourcepos#2023]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is:  7
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: Apache
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question / New Feature
How can I add Suppliers details in Sales Summary Report. 
There are ;
Date | Quantity | Subtotal | Tax | Total | Wholesale | Profit in Sales summary report.
I am looking for add one more option that is Supplier name . We can easily find out the supplier of sold product.

I can add this feature if anyone assists here,
Thanks.

**Comment by odiea** [comment]
Use the Supplier Summary Report.

**Comment by mckaygerhard** [comment]
Reports > summary reports column square> Suppliers > select date and sales

**Comment by saruban** [comment]
Hi, Thanks for the response. but in that way, we can't see the detailed reports. 
Supplier Summary Report does n't show the items that related to suppliers. I would like to display the supplier info along with their items in reports.
Then we can easily find out the sold products and their supplier in one place. 

I hope now you all understand and help me.

**Comment by daN4cat** [comment]
Install Reportico and build your reports.
We won't implement all possible reports in OSPOS.
That's what I did for my case ad I needed more advanced reports.

**Comment by drbeanz** [comment]
I also need a layawy feature im willing to pay if needs be

**Comment by drbeanz** [comment]
customer history and supplier history is so much necessary. I love this appliacation overall

**Comment by daN4cat** [comment]
Customer history is implemented. Supplier based transactions history is coming with 3.3.2.
Not sure what else you need.

**Comment by drbeanz** [comment]
I already have the 3.3.2 and the supplier report is for goods sold from
supplier's stock

**Comment by drbeanz** [comment]
What is needed is when I receive goods from supplier in recieving that is
stored and payments being made to that account partly or wholly with a
history of how much payments being made on multiple date n time...
