### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [opensourcepos/opensourcepos#2026]
Good day, about the enhancement of the project. I am willing to submit my design for logo and icon.

**Comment by WebShells** [comment]
Hello @loydjayme25 contributions are welcome as long as the rest of the members agree about the newly designed interface... I don't think any would reject the idea...

**Comment by loydjayme25** [comment]
@WebShells if that's the case. i will finish my design as fast as i can :) have a good day !

**Comment by jekkos** [comment]
Sure! new logo ideas are welcomed

**Comment by daN4cat** [comment]
Sounds good.

**Comment by loydjayme25** [comment]
any suggestions or comments ? 

![proposal](https://user-images.githubusercontent.com/37318022/41325712-5c9625e6-6eee-11e8-8dbc-0be178ff7f3c.png)

**Comment by jekkos** [comment]
I think the style is probably more modern from what we have now (it seems the OSS projects always tend to have bad UX design anyway), but still maybe we should have the full abbreviation in the logo (as it is now?)

Any thoughts?

**Comment by WebShells** [comment]
@jekkos i agree for the poor design... For the abbreviation thing its not necessary to be fully mentioned in logo... Yet the new logo should reflect OSPOS identity... 
@loydjayme25 any other samples you can provide ?

**Comment by loydjayme25** [comment]
i make other samples @WebShells

**Comment by daN4cat** [comment]
OSPOS only at the bottom would do.
I'll ask an opinion to the "art directors" (my OSPOS install user team).

**Comment by jekkos** [comment]
@daN4cat agree ospos suffices, it's shorter and up til now what we use in logo / shorthands

**Comment by loydjayme25** [comment]
@daN4cat 

![2](https://user-images.githubusercontent.com/37318022/41389309-a472b60c-6fc2-11e8-9959-38c81a68408d.png)

**Comment by jekkos** [comment]
I would say top or middle one?

**Comment by WebShells** [comment]
Top one reflects my company's colors and identity... Yowww I'll sue you 😎 :p ! 
Well definitely not the lower ones... I'll try to see if I can provide a sample from our designing department too...

**Comment by daN4cat** [comment]
If you read once OSP and roll back and read again up to the second letter OS..... you get OSPOS.

That's how logo designers sees the world and they are right.

We are boring engineers mate.

**Comment by daN4cat** [comment]
If it were a fully palindrome like OSPSO it would have been a yoyo reading.

**Comment by loydjayme25** [comment]
@SteveIreland  you mean the word Open must be on the top of POS while the source will be at the bottom ? In my opinion, if we do that using small px size, the combination of words will not be seen. But i will try it, ill give my best for the project .

**Comment by SteveIreland** [comment]
@loydjayme25 Don't bother.  @daN4cat has already dismissed my concerns as invalid.

I'll find a corner to crawl into ... I'll be okay in a few days.

**Comment by loydjayme25** [comment]
So what would be the final decision/suggestion for the logo so that i can make some adjustments on it.

**Comment by SteveIreland** [comment]
Top-left-green-black OPS with OSPOS works for me..  We'll see @WebShells in court.

**Comment by loydjayme25** [comment]
and also the sizes you needed for finalization.

**Comment by daN4cat** [comment]
Any chance to have a blue version to match the current logo colour and login page?

I'd prefer a bit of colour matching if possible.

**Comment by daN4cat** [comment]
Yet another request....

**Comment by SteveIreland** [comment]
@daN4cat Are you requesting a boring blue color?  Engineers are so drawn to blue.  Unbelievable!  :wink:

**Comment by WebShells** [comment]
@daN4cat see you at court too... Next to Steve and jekkos ull see 😒🤨🤣

**Comment by daN4cat** [comment]
@SteveIreland true and it's not even Monday to feel... the blues.

**Comment by WebShells** [comment]
Well, thats one of the options that feels straight & neat too... @jekkos @daN4cat @SteveIreland ? Colors to be changed to fit the project's theme...

![ospos](https://user-images.githubusercontent.com/26513147/41543455-810057dc-731f-11e8-9f9d-d297c336bbe3.jpeg)

Will re-upload other samples once done...

**Comment by mckaygerhard** [comment]
maybe a Something that has bilateral symmetry it's better in terms of portability and commercial spicollycally fit into minds! Egipts statues and icons are very beautifull due that!

**Comment by jekkos** [comment]
@WebShells also like that one. Maybe we should do some voting on what is proposed or how shall we proceed here?

**Comment by WebShells** [comment]
Great then... As mentioned color is changeable depending on the final scheme... Icons will be redesigned to fit logo selection

**Comment by debpedrano** [comment]
Greetings everyone , about this certain issue. Can I also submit my design ?

**Comment by WebShells** [comment]
@debpedrano sure... Lets see

**Comment by jekkos** [comment]
Ospos logo design contest.. seems to have more success than expected

**Comment by WebShells** [comment]
@jekkos still waiting for the votes to know which one will be officially using... @daN4cat @SteveIreland any thoughts ?

**Comment by odiea** [comment]
Yes. This one would look nice in blue.
![2018-06-25 15_04_34-wedidit _ ospos 3 3 0 _ login](https://user-images.githubusercontent.com/10962177/41875814-432d0526-7889-11e8-927e-115f838d4703.png)

**Comment by WebShells** [comment]
Holaaa @odiea

**Comment by Saiuke** [comment]
I'll try something and send soon.

**Comment by justinstories** [comment]
@WebShells, Os as wheels is such a great idea and fits with our theme/purpose.

Can you make the kart bit smaller? Too big as of now, in my opinion (may be even half size?).
Also did you try changing the letter O (wheels) regular and letters SPS italics? That might work better.

**Comment by WebShells** [comment]
Hello @justinstories, thanks for your comment... Maybe we should try that one too and compare the result with what i already submitted... Still waiting what other members decide 👍

**Comment by radik4li** [comment]
![ospos](https://user-images.githubusercontent.com/40339396/43187196-178c229c-8ff1-11e8-9692-4b5cc7f9feac.jpg)
Hello, i thought to see it in a diffrent way, more rounded and with more weight

**Comment by daN4cat** [comment]
I like it!

**Comment by WebShells** [comment]
Looks somehow related to old school designs... Doesnt look modern... Thats my thoughts o.O

**Comment by radik4li** [comment]
Its not very modern, but neither it is old schhool, but It dont have to be modern in my opinion since the interface is not highly modern and it would contrast.  I would also suggest to change the middle of the old logo to make it more full and to resemble more the open source if for the moment there is no change. Right now it looks like an power off button. Here i put some drafts

![ospos2](https://user-images.githubusercontent.com/40339396/43258261-85bc1ee8-90d2-11e8-8dd8-ba632d637b86.jpg)
![ospo1s](https://user-images.githubusercontent.com/40339396/43258262-85dae774-90d2-11e8-9e42-a651cedda03e.jpg)
![opspos3](https://user-images.githubusercontent.com/40339396/43258360-d4ec5078-90d2-11e8-807f-bf4d44be0e30.JPG)

**Comment by daN4cat** [comment]
Now the one in the middle matches the colours, looks better.
The current logo is what I could find for free... we are not graphic designers and therefore not emotionally attached to it.

**Comment by daN4cat** [comment]
Would be nice one day have all the menu icons drawn to better match the feature.

**Comment by jekkos** [comment]
The big logo is nice, however we probably need a simpler and more concise version as well? At this moment the logo is only shown on the login page if not mistaken. But if we have smaller versions wr might add it to the header/footer (like as a default company logo eg)

**Comment by januaryramadhan** [comment]
may we use the ospos, aka open source pos. to sell it into martket. but you
know we forbid to sell an open source software then how about the
installation ? can we get some bucks from that ?

**Comment by SteveIreland** [comment]
I would hate to think that someone would pay to use your services when you don’t even know how to post an issue or question on github. This comment is way off topic. Please search for where it has been answered before (it has) and if you can’t find it then please open a new issue.

**Comment by mckaygerhard** [comment]
@januaryramadhan seems makes sense if vendor know waht are doin but it's no so easy, as example client always ask for modifications, and if you cannot do will go to other provider!

**Comment by daN4cat** [comment]
Where are we with this logo story?

**Comment by WebShells** [comment]
@daN4cat maybe we should exclude some of the options given so we can take decision regarding the above... Which 3 do you prefer ?

**Comment by objecttothis** [comment]
Sorry for the late entry.  I'm not a graphics guy, but I am partial to the blue that we currently have or a similar blue.  I also like the charcoal.  I'm not as big of a fan of the green. So something like this is more preferrable to me:
![41389309-a472b60c-6fc2-11e8-9959-38c81a68408d](https://user-images.githubusercontent.com/17935339/45597888-d52cd500-b9e3-11e8-91ff-d7ff3349f29b.png)

**Comment by WebShells** [comment]
Hello @objecttothis for sure the colors to fit ospos current theme... I was waiting until we agree so i change the colors...

**Comment by SteveIreland** [comment]
As long as they are not the wobbly broken wheels on almost every cart I get then I'm okay with the logo.

**Comment by xykoarteiro** [comment]
hahah

**Comment by daN4cat** [comment]
I know we had different opinions, but I wanted to draw a line and change the logo in order to release 3.3.0 with something new.
I kept the blue colour reusing @loydjayme25 design, so many thanks to him and for his contribution.

**Comment by objecttothis** [comment]
I'm not sure but I think current practice is to use a vector format (svg) because it scales better than bitmap (tif, jpg). My recommendation is to use a single svg and scale it.

**Comment by daN4cat** [comment]
All the icons are png, I don't see how changing one would do better.

**Comment by objecttothis** [comment]
That's fine, but png is bitmap so it won't scale like vector will.

**Comment by daN4cat** [comment]
Yep, I know but I don't have any better.

**Comment by objecttothis** [comment]
@loydjayme25 could you upload the original hires image for the logo?  essentially we will to use the logo you created but the background color needs to be #3399cc to match the color of the buttons in the application.  The lettering should be white, with the background transparent.  Ideal would be to provide an original layered file (in whatever format you did it in) a favicon and an SVG vector file, but if you don't have time you can just provide the original hires layered file and I can make the changes.

Pretty Please :)

> ![2](https://user-images.githubusercontent.com/37318022/41389309-a472b60c-6fc2-11e8-9959-38c81a68408d.png)

**Comment by daN4cat** [comment]
@objecttothis I was under the impression we wanted to change button colour not the other way round.

**Comment by objecttothis** [comment]
@daN4cat oops, I misread your response. Ok, that's an easier change to make. Nonetheless I still think it's a good idea if we get the hires versions from the author.  I'll make the button color change to the logo color and regenerate the favicon then.

**Comment by objecttothis** [comment]
@loydjayme25 can you send the hires versions with the current background color? #1071b9

**Comment by daN4cat** [comment]
Agreed about the hires.
