### ISSUE TITLE
Is OSPOS GoBD Compliant?

### ISSUE THREAD

**Issue by maccer28** [opensourcepos/opensourcepos#2034]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

This is just a general question, I have everything up and running and happy with how it works. 
I am running this in a fruit shop in Germany, and i was looking up legislation for VAT on fruit and i came across "GoBD" and was wondering if OSPOS was compliant.  
https://de.wikipedia.org/wiki/Grunds%C3%A4tze_zur_ordnungsm%C3%A4%C3%9Figen_F%C3%BChrung_und_Aufbewahrung_von_B%C3%BCchern,_Aufzeichnungen_und_Unterlagen_in_elektronischer_Form_sowie_zum_Datenzugriff

Sorry about this link to another project but some good info.
https://github.com/invoiceninja/invoiceninja/issues/1487

Thanks

**Comment by mckaygerhard** [comment]
the second link was very more usefully rather the wikidepdia german specific info.. and currently there's not GoDB compilant from ospos "per se"

currently many of the GoDB compilant are already included and provided in ospos, but not pointed as.. lest see:

a. mantain a copy of the current database usage are a administration specific, not a ospos realted, so the rules 2, 6, 7 and 8 are not related to the application in true!

b. ospos and any software make a electronic (own made of course) storage of the invoices,.so rules 1, 2, and 5 and specially the 6 are already made by any POS software.. 

c. the rule 8, 10, 11 and 12 are manage with a good documentation and that are reading the code and the very little but well enought wiki made by me (yeah) at https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#code-and-api-documentation the part that explin the sales proces i also explainet in recent issue i dont remenber where but i can added later to the wiki..

d. and lasted: rest of the rules of that regulation are ilogical in some degree due are implicit in a software pos system, it's just way's to access and order the data and process, in conclusion any software must be well made like a system software project with a rule target and history well planed, resulting in a well documented product.. of course in this ospos will faild always...

**Comment by maccer28** [comment]
So its a grey area, so you will probably get away with it. Thanks for the quick reply and info. i suppose if your good enough you can defraud anything.

**Comment by mckaygerhard** [comment]
i'm not final word about this issue, but my point of view that law its a effor to makin a hard standar to control how the development are deployed in the EU, dont be strange if that law will be general for all european countries

**Comment by maccer28** [comment]
I think all they are trying to do is stop cash businesses messing with the books/data. 

Im just putting these links up in case this every becomes an issue. 

https://lexology.com/library/detail.aspx?g=19c9005b-3c4f-4a48-b585-90fa69c758c9
https://www.hks-systeme.de/uploads/media/GoBD-Export-HKS-Systeme-GmbH.PDF
https://deloitte-tax-news.de/german-tax-legal-news/new-guidance-issued-on-electronic-archiving-of-accounting-and-tax-information-and-electronic-data-access-by-the-tax-authorities.html

**Comment by mckaygerhard** [comment]
you said in less complicated words, today the books/data are software databases, i'm think its a good law in general terms.. but the problem its not that in fact.. 

a bussiness man really do not know what are happened inside the buyed software, that's the problem..  companies like mocosoft made huge systems like AX that have internals process and the regulations do not control how the data are manipulated!

**Comment by maccer28** [comment]
Is this another use case for a blockchain?

**Comment by maccer28** [comment]
OSPOSCOIN

**Comment by mckaygerhard** [comment]
O.o ->  i dont think so.. not so far..

**Comment by SteveIreland** [comment]
Definitely not.  Wow ... are there systems that actually ,meet all of those requirements?

Just the first one would require an image capturing system to save the original version of the invoice so that it can be reprinted exactly as it was 10 years later.

**Comment by maccer28** [comment]
Expensive for a startup with 1 person,

**Comment by SteveIreland** [comment]
One of the largest software companies in the world is SAP which is based in Germany.  It sounds like this law was created to insure that any startups must contract with SAP.  I have no doubt that SAP has already invested the hundreds of thousands of dollars to satisfy these legal requirements.

**Comment by daN4cat** [comment]
@SteveIreland same applies to Microsoft, IBM, Google, Amazon... you name it, all play the same game
