### ISSUE TITLE
Module Unexpected Error

### ISSUE THREAD

**Issue by leoladoudou** [opensourcepos/opensourcepos#2035]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3 // 3.0
- OSPOS git commit hash is: sorry, can't acces this information at the moment, and won't for days.
- PHP version is: 5.6.31
- MySQL or MariaDB version is: 5.6.36
- OS and version is: Windows 10, all updates done.
- WebServer is: Wamp
- Selected language is:  english
- (If applicable) Docker installation: --
- (If applicable) Installation package for the LAMP/LEMP stack is:-- 

### Issue 

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Upgrading from pointofsale 2.2.1 : I got ospos 3.2.3 working with a test database (empty one provided by database.sql). After running all the upgrade scripts in the right order, I can acces the login screen of ospos. If I ener wrongs ID, there's no problem : just saying the IDs are bad. If I enter good ones, I got a blank screen sayiing I do not have the permission to access the module named Unexpected Error. If I use ospos version 3.0, I get the exact message except it's named Unknown. In the browser, url tab, I got something like : localhost/ospos/public//no-access. I've already been able to upgrade a database in the past from the same version, but this time it just won't work. Thank you for your work.

**Comment by SteveIreland** [comment]
Wow .. 2.2.1 to 3.2.3 is quite a leap.  It seems that you just need a final tweak to hand permissions for your particular installation.  Can you check your PHP log file to see if tells us what module is not auhorized?

**Comment by leoladoudou** [comment]
I know haha, I can't acces the machine right now, but I do have the database with the problem so I might just install it on my laptop and see if I get the same error... Only problem : I do not have ID for the point of sale. Can I manually add one directly into ospos_employees? I'm wondering too if that no-access might not be because a module was added between 2.2.1 and 3.2.3 and since no users got permissions on it (because created before) lead to this error? If it doesn't work I'll provide PHP log next week.

**Comment by leoladoudou** [comment]
Got the same thing going on on my machine and PHP log just says:
[23-Jun-2018 18:55:32 UTC] No error - Only to create the file
[23-Jun-2018 15:55:03 America/New_York] Migrating to 3.1.1

[23-Jun-2018 15:55:08 America/New_York] Migrated to 3.1.1

[23-Jun-2018 15:55:08 America/New_York] Migrating sales tax history.  The number of sales that will be migrated is 3661

[23-Jun-2018 15:55:30 America/New_York] Migrating sales tax history.  The number of sales that will be migrated is finished.

[23-Jun-2018 15:55:30 America/New_York] Migrating to 3.2.0

[23-Jun-2018 15:55:31 America/New_York] Migrated to 3.2.0

[23-Jun-2018 15:55:31 America/New_York] Migrating to 3.2.1

[23-Jun-2018 15:55:31 America/New_York] Migrated to 3.2.1

**Comment by daN4cat** [comment]
That means upgrade to latest version through all the upgrades since 3.0.0 went well.
Did you manually run all the scripts between 2.1.1 to 3.0.0 before using OSPOS for the first time?

**Comment by leoladoudou** [comment]
Yes, I've run all of the 2.XX - 2.XX scripts in the sql console of phpmyadmin before trying to connect to the database with ospos.

**Comment by mckaygerhard** [comment]
i have this problem now.. after some months working without problem got "do not have the permission to access the module named Unknown"

**Comment by mckaygerhard** [comment]
i resolved the problem .. very rare in my case was that the user that i used to manage users seems unexpectly not have any entries in the `ospos_grants` table.. after insert those sql all comes to normal, and fix the others users.. i paste example with id 1 here:

```
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('customers', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('employees', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('expenses', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('expenses_categories', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('home', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('items', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('items_FERRETERIA', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('item_kits', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('office', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('receivings', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('receivings_FERRETERIA', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_categories', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_customers', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_discounts', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_employees', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_expenses_categories', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_inventory', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_items', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_payments', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_receivings', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_sales', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_suppliers', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('reports_taxes', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('sales', '1', 'home');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('sales_delete', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('sales_FERRETERIA', '1', 'home');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('suppliers', '1', 'both');
REPLACE INTO `ferreterotesting`.`ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES ('taxes', '1', 'both');
```
