### ISSUE TITLE
Item Kits Issue

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2037]
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- x[] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Issue / Bug  / Question / New Feature
This is also in the current Master.
When mode is set to development No rows show in the Item Kits Table.

opensourcepos.20180626184851.amount_validations.5537e9.zip
ERROR - 2018-06-28 08:28:29 --> Severity: Warning --> A non-numeric value encountered C:\xampp\htdocs\newmaster\application\controllers\Item_kits.php 34

**Comment by mckaygerhard** [comment]
well i dont think so development mode are for guindows.. al lthe developer and tools used in ospos are focused and made for linux !
> "C:\xampp..."

**Comment by SteveIreland** [comment]
@odiea this looks like the same issue that @daN4cat was having.

So you were just listing items in an Item Kit? I looked at the code and saw something which prompts a question.

Do all of  your item kits reference an active item (as a parent item)?  If not then then that is a definite clue.

I'm thinking that the statement on line 20 might be setting the total_unit_price to null and that might be causing the failure.

`$item_kit->total_unit_price = $kit_item_info->unit_price;`

**Comment by odiea** [comment]
All I had to do was click on the Item Kits Module and no kits showed.

**Comment by SteveIreland** [comment]
I ran a test before and after this change and that was definitely the cause.  Pull request on the way.

**Comment by odiea** [comment]
The row now shows with no errors. The following is trying to create a barcode and the barcode shows correctly.
A PHP Error was encountered
Severity: Notice
Message: Undefined property: stdClass::$item_id
Filename: controllers/Item_kits.php
Line Number: 17
Backtrace:
File: C:\xampp\htdocs\newmaster\application\controllers\Item_kits.php
Line: 17
Function: _error_handler
File: C:\xampp\htdocs\newmaster\application\controllers\Item_kits.php
Line: 214
Function: _add_totals_to_item_kit
File: C:\xampp\htdocs\newmaster\public\index.php
Line: 315
Function: require_once
And the following is from trying to update the kit.
![2018-06-28 18_33_56-wedidit _ powered by ospos 3 3 0](https://user-images.githubusercontent.com/10962177/42067140-f31cc2d0-7b01-11e8-9eb3-8007a4da0f2e.png)

**Comment by SteveIreland** [comment]
Is this all because of PHP  7?  PHP 6 was doing so much more for us.  :-)

I have been able to replicate the bar code generating error and will take a look at it as soon as I get back from the grocery store.

**Comment by odiea** [comment]
Yes I did recently update to 7.1 but I do not think that was the issue??

**Comment by SteveIreland** [comment]
Well, the first issue seems related to me because PHP 6 must have been making that empty string to numeric zero conversion automatically otherwise this would have shown up a year ago.  I don't know about the barcode issue yet, but the gremlins seem to be running rampant.

**Comment by SteveIreland** [comment]
Okay, the barcode issue must be a long term bug that was never stumbled across.  I can't blame PHP 7 for this one and it will require  more than a change to a single line of code.  I'll need to be careful.

**Comment by daN4cat** [comment]
Garbage at the end of the form fixed and in master.

**Comment by SteveIreland** [comment]
Garbage?  So harsh, but thanks.

**Comment by daN4cat** [comment]
O'right.... unnecessary printing of javascript on item_kits form removed and restored proper functionality.
Does it sound better? :-)
