### ISSUE TITLE
Duplicate Item Search Results

### ISSUE THREAD

**Issue by JigoloPete21** [opensourcepos/opensourcepos#2038]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.1
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: MS Windows 10 Pro 64bit
- WebServer is: Apache
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hello,

I noticed that I get duplicate Item Search results in the "Sales" section on certain items.  It doesn't happen with all items, only some.  I'm not sure what the determining factor is that causes certain items to be listed twice when they are only in entered into inventory once with a unique barcode.  Attached are some screenshots illustrating the issue.  Any idea what the issue could be?

Let me know what other info you need from me.

Thanks!

![ospos_duplicate_search_results](https://user-images.githubusercontent.com/13972098/42124773-ec2e5354-7c36-11e8-8f26-e38920fc2ccb.png)
![ospos_inventory_listing](https://user-images.githubusercontent.com/13972098/42124774-ec3e71c6-7c36-11e8-93d9-ed6b1ec7ce0f.png)

**Comment by jekkos** [comment]
I guess it's your items matching both the name and first part of the barcode. This probably won't happen if you use regular UPC or EAN8 instead.

**Comment by jekkos** [comment]
But you're right, a simple filter at the end of this method could fix this issue easily

**Comment by daN4cat** [comment]
@jekkos is this fixed?

**Comment by daN4cat** [comment]
I see that a PR covered this issue, I assume it's sorted.
