### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Jyotie** [opensourcepos/opensourcepos#2042]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: opensourcepos.20180613210031.3.2.3.f1cf3d.zip
- OSPOS git commit hash is: 
- PHP version is: 5.6.31
- MySQL or MariaDB version is: 5.6.39
- OS and version is: Linux
- WebServer is: Apache 2.4.27
- Selected language is: English (havent run any installation yet)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Issue:
I am trying to set this on live server. my live server config is : 
Apache Version	2.4.27
PHP Version	5.6.31
MySQL Version	5.6.39
All extenions are enables as per the requirement.

I have uploaded the latest zip : opensourcepos.20180613210031.3.2.3.f1cf3d.zip
I extracted it under my domain's 'public_html/PROJECTS/' folder.
And now trying to access login page. But I get error

**Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@mydomain to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.**

I checked in issues, but i did not get solution. Please help.

**Comment by Jyotie** [comment]
I found its folder permission issues on public folder. Fixed. Closing

**Comment by WebShells** [comment]
Good to hear that... One of few who tries to solve problems there self...

**Comment by daN4cat** [comment]
and minds to come back explaining how they solved so next time somebody can search old cases and finds a solution.

**Comment by Jyotie** [comment]
thank you so much. :)

**Comment by mckaygerhard** [comment]
umm @Jyotie noted that wiki does not point about the per-user directory installs.. dorry for that...

**Comment by Jyotie** [comment]
Not an issue! :)
