### ISSUE TITLE
Reporting Customers need help

### ISSUE THREAD

**Issue by mclaos** [opensourcepos/opensourcepos#2043]
### Background information

Searching for a customer in Reporting Customers is very difficult since it is a "drop list" when the number of customers increased I have to scroll down to search for a customer. Can you change the "drop list" into "search able list" instead. Thank you in advance.

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by WebShells** [comment]
Hello @mclaos, please fill in the issue template in your future issue submission in order for us to be able to point out your problems...

For the issue you are facing, you can tyoe first 3 or 4 letters or you can even type client name in the selection drop down list... For example client name is "WebShells"
You can simply click on drop down arrow and start typing "Web" you'll see webshells will appear.

**Comment by mclaos** [comment]
![image](https://user-images.githubusercontent.com/34768439/42411828-1c035966-822d-11e8-817f-42ead0224998.png)

in this section I cannot type any customer name to search for the right one, thank you for your reply

**Comment by odiea** [comment]
These are very basic reports . All you can do is select a customer from the dropdown list.

**Comment by mclaos** [comment]
yes, but can It be changed to "search-able-list" instead?

**Comment by odiea** [comment]
If you would like to implement that feature and give it back to us that would be great.

**Comment by mclaos** [comment]
Thank you for your reply Odiea, I don't think I have a knowledge in php script or relevant to fix this problem. Only thing I could do is to provide some idea about what happen when using the application in practically.

**Comment by odiea** [comment]
Ok. Thanks for the feedback.

**Comment by SteveIreland** [comment]
I agree with @mclaos. It certainly should be a searchable list.

**Comment by odiea** [comment]
Indeed. That's why I gave it those labels.

**Comment by WebShells** [comment]
Guys... It's already searchable... 
Am i mistaken here ? Click on drop down then try typing first 3 letters of client name the whole name will appear... Unless if you'd like to change the layout or to apply search form... @daN4cat @odiea ?

**Comment by odiea** [comment]
That must have been a feature you added to your branch. The drop down does accept any input but what is selected from the list.

**Comment by odiea** [comment]
@WebShells You are correct but you have to rapidly input the name else it jumps to the first letter of the next name. Learn something new every day. Thanks

**Comment by odiea** [comment]
I never learned to type properly. The hunt and peck is what I use. LOL

**Comment by WebShells** [comment]
@odiea I doubted myself lol... Yeah thats true, you should type it fast or else it will jump to another client name's first letter... At least, its there and does what @mclaos asked for...  
Maybe @SteveIreland would like to transform it into a regular input search form with auto complete from db?

**Comment by mclaos** [comment]
@odiea and @WebShells, I know when we put the first letter of the "first-name" it will jump out to the name start with that letter, but it won't work with "last-name" or telephone number.

**Comment by WebShells** [comment]
Added through #2384

**Comment by daN4cat** [comment]
Merged and in master.
