### ISSUE TITLE
Login Off

### ISSUE THREAD

**Issue by infomail** [opensourcepos/opensourcepos#2046]
Recently I have installed version 3.2 and I happen to close the session when I browse, this usually happens to me on Android devices, my iPhone did not happen, now it started on the laptop, someone knows what can happen, why it closes the session in less than a minute even deleting the cookies?

Thank you very much

**Comment by mckaygerhard** [comment]
do you fill and READ!!! the issue template before posting the issue? @infomail ? just answer me that simple question!

**Comment by mckaygerhard** [comment]
https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-why-my-issue-was-closed

**Comment by mckaygerhard** [comment]
hi @jekkos , @daN4cat, @WebShells and @SteveIreland  and any other i forget to mention related to developer team.. i place a wiki info about filling a issue to ospos here https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-why-my-issue-was-closed

i take liberty to link my fork for those user that require "more patient" feel free to remove it.. also i improve the wiki index aside.. also feel free to altered too!

important noted that some links are too older or unrelated.. wo i move it to lasted after FAQ section until we updated property..

**Comment by SteveIreland** [comment]
Gee, and I thought @daN4cat  was harsh.  Compared to @mckaygerhard he is Mother Teresa.

**Comment by mckaygerhard** [comment]
no no @SteveIreland that first wiki related page are to start.. of course maybe must be modified and "downgrade" level of advertise! 

sound too rude that content? i thinking was "soft" but now i dont know how to make started user feel and take care of the reading contents, also the template dont help so much either.. 

i'll change the https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-why-my-issue-was-closed now to more "soft" and hope are understandable!

**Comment by WebShells** [comment]
LOOOOL @SteveIreland

**Comment by WebShells** [comment]
@SteveIreland to me and with all respect to @mckaygerhard, I somehow disagree for that wiki page :x... You ?

**Comment by mckaygerhard** [comment]
i just altered but as i said @SteveIreland maybe was too hard, well @WebShells the idea almost was redirect to users the reason why was closed the issue.. i currently downgrade the idea of the original text and please review now to see if are better..

**Comment by daN4cat** [comment]
The problem is that people don't read and find it easier to open an issue and get an answer. Like ordering a take away....

**Comment by mckaygerhard** [comment]
i understand that you said @daN4cat well that's why i made that wiki page.. and well that people its that make rich to Bill right?
