### ISSUE TITLE
bug: demo 502 Bad Gateway error so not working 

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2047]
gives 502 Bad Gateway error, currently seems there's two possible reasons:

1. code related, js problems or something
2. reverse proxy related depends on the service

**Comment by mckaygerhard** [comment]
maybe not for others but 30G are a lot of space for server and a simple software (respect others with hundres of users at same time) how that space could be fill as is? well new rules let's see!

**Comment by mckaygerhard** [comment]
umm maybea posibility to delete user settings for a "demo mode" as new feature?

**Comment by mckaygerhard** [comment]
umm maybe a posibility to delete user settings at logout for a "demo mode" as new feature?

**Comment by odiea** [comment]
Or remove all access to the employee module.

**Comment by WebShells** [comment]
Ill try to refresh it... Try in couple of minutes please...

**Comment by WebShells** [comment]
I guess its not something related to the build itself... Its something related to domain controller ? 
Still same issue even after a reset... Does it give bad gateway or domain cashparking issue ?

**Comment by odiea** [comment]
Currently it is showing 502 gateway error.

**Comment by odiea** [comment]
Yes that would be a good Idea. In public index.php add demo mode then in logout have it drop and reinstall the employee database or something like that.

**Comment by mckaygerhard** [comment]
well @odiea it's not the first time i said that "idea" ..

i reopen the issue due this is a nginx problem, puff so famous apache2 and nginx and also so famous that 503 gateway problem, many hosting services give same problem sometimes..

**Comment by jekkos** [comment]
@odiea Good idea on 'demo' mode.. Will add something like this and then prevent pwd change for any user

**Comment by jekkos** [comment]
should be fixed now

**Comment by mckaygerhard** [comment]
so slowly but working! thanks, close it!
