### ISSUE TITLE
Time incorrect on client make lost bill on OSPOS

### ISSUE THREAD

**Issue by whoami1904** [opensourcepos/opensourcepos#2050]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- x[] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 5.7
- MySQL or MariaDB version is: 
- OS and version is:  ubuntu server 16.04
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
- I am facing big problem. I had install ospos on ubuntu server 16.04 into virtual box oracle
- On physical computer open virtualbox oracle and start ospos (ubuntu 16.04). And time is correct on my physical computer. And then i open web of ospos for sell, everything ok. EX: Yesterday i had sell 10 POSs on my physical (from POS 1 to POS 10)
- Today, i had also sell on my physical computer from 10:00am to 15:00pm and sold from POS 11 to POS 20. After that i had closed web of ospos but ubuntu server (that is instal ospos) on my physical still open. And then i open web of ospos on another laptop and time' s this laptop incorrect. It's time on laptop is 3:00am while present is 15:00pm (same day) but i don't know. I had sold 3 POSs (if right, POS will from POS 21 to POS 23) on this laptop to 22:00pm and . In end of day when i go to web for check, i just see 3 POSs, from POS 11 to POS 13 (time on that POSs is 3:00am) that is sold on laptop. POSs that i had sold from 10:00am to 15:00pm dissapear. I think 3 POSs that i sold on laptop override POSs that i sold on my physical.
- I don't know why time' s laptop can effect to time' s ospos (time' s ubuntu server). I think time's ospos (time' s ubuntu server) must be apply from my physical. I had also go to webmin and i see time is changed to same time' s laptop :(
- How can i fix time on ospos. Because i need to open web of ospos on many device, if that device can effect to ospos when it open web of ospos, It is very difficult to control it.

**Comment by WebShells** [comment]
Man... Seriously? Its there in configuration where you set timezone and format... If i got your question right! 
Am not sure anyone will read all of this :/

**Comment by SteveIreland** [comment]
The behavior sounds more like two instances of OSPOS are installed that are sharing the same database

What database are you using?

**Comment by whoami1904** [comment]
@SteveIreland, you right.
- This is my configuration.
![timezone](https://user-images.githubusercontent.com/39585711/42751963-a9ae78b4-8916-11e8-9900-78d03d5aab66.JPG)

**Comment by mckaygerhard** [comment]
XD seems phisicall are different OS and consecuent different php configuration.. for sure a kind of guindows..  no matter if database are shared

**Comment by whoami1904** [comment]
I will continue follow. thanks all :)
