### ISSUE TITLE
Item name on transaction report

### ISSUE THREAD

**Issue by saif3909** [opensourcepos/opensourcepos#2053]
### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.5.11
- MySQL or MariaDB version is: MySQL 5.0.11
- OS and version is: OSX Yosemite 10.10.5
- WebServer is: XAMPP on Mac
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hello,

I would like to thank you first for your continuous effort on making OSPOS a great free POS software. It meets all my requirements except one and that is ITEM NAME on downloaded detailed transaction reports. I know the items are displayed when I'm clicking the + sign on the detailed transaction report page but it would be more convenient for me if I can see which customer has purchased which item and sort them accordingly. So please consider adding this on future updates and if possible please suggest me how can I do it myself now. Thanks again for your great software.

**Comment by mckaygerhard** [comment]
duplicate report behaviour of sales or clients with item filter.. 

for statirng development read here: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#code-and-api-documentation, of course you will need a complete development environment for that read here first https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Environment-Development specifically the "Basic Tool installation" section, of course must search those tools for mac event for linux, due are UNIX related OS's will work as spected (not like the stpudi guindows does) maybe will not be fast a good reading are https://treehouse.github.io/installation-guides/mac/node-mac.html (its a github repo too) take care of howbrew path..

in other hand if you dont want to mess with all the very complicated development environment, download a lasted bintray version of ospos and then start from that decompresed code! more easy and faster ... of course..

**Comment by odiea** [comment]
Have you looked at the Detailed Customer Report or the Summary Item Report.

**Comment by mridul611** [comment]
I have looked into Detailed Transactions Report. The purchased item name comes up after clicking the + plus sign there but not showing if I download as CSV, TXT, PDF or any other format. Actually I want to see which customer has purchased which item in a single sheet/file.

**Comment by WebShells** [comment]
@mridul611 i guess you should do that by yourself... It needs some customization in order to reach the results needed...

**Comment by mclaos** [comment]
@mridul611 , I agree with you, in reports need more filters for example in "Category Report" needs filter by "Customer" and "Employee" and also in "Items Report" as well. Cheers

**Comment by mckaygerhard** [comment]
i dont remenber if @odiea , @daN4cat or @SteveIreland was the guy that said , that more avanced and detailes reports comes in a report engine and are a little away of the ospos target..

**the best solutions for that are separate the reports from the ospos program
in those cases we need a specific project apart of the ospos:**

- **a new project under the opensourcepos group of github namen openposreports**
- **this project only receive the absolute path to the ospos installation**
- **due under that path are "application" it search for configuration database files**
- **the rest are "cube"s build due all the structure of the ospos DB are know**
- the reports are build by user now with any filters and any tables (cube's)

of course and obviously we can construct that under a base of any report engine..
