### ISSUE TITLE
suspended menu

### ISSUE THREAD

**Issue by nathanzky** [opensourcepos/opensourcepos#2055]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.0.21
- MySQL or MariaDB version is: 5.7.18
- OS and version is: RHEL7
- WebServer is: Apache
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

 New Feature

Can we have a feature for suspended sale to see who's employee made the suspended sale?
This is helpful if the customer came back next day  where new employee is login to complete the sale.

![suspended](https://user-images.githubusercontent.com/26484936/42883231-0cc09306-8aac-11e8-89ee-508594620342.JPG)

**Comment by jekkos** [comment]
@nathanzky what would be really nice as well is a delete button next to the unsuspend..

**Comment by WebShells** [comment]
Ill give that a try at night...

**Comment by SteveIreland** [comment]
If the suspended order is a work order or quote please do not enable the delete button.  I'd like to continue to have it as a two step process to delete.  It should be reviewed first to make sure that they are canceling the correct order.

**Comment by erastus91** [comment]
at the time of elimination. that a text box appears to write a comment the reason for the elimination

**Comment by nathanzky** [comment]
@WebShells do you have any update with regards to this feature?

**Comment by odiea** [comment]
Is this sufficient for the employee name in suspended sales or should it be the full name. I don't plan on adding a delete button because of mistakes that can be made.
![2018-09-16 12_48_30-window](https://user-images.githubusercontent.com/10962177/45599776-f7f0c680-b9ae-11e8-8294-571d61ab4f15.png)

**Comment by odiea** [comment]
Unfortunately it is still the current logged in employee. I will wait and see if this issue #2093 gets more attention.

**Comment by odiea** [comment]
In controller/sales public function complete the following line of code needs to be changed so that it will pickup the sale_lib employee to get this to work properly.
		$employee_id = $this->Employee->get_logged_in_employee_info()->person_id;
I do not have the experience to change this to work properly.

**Comment by erastus** [comment]
this feature is already in ospos 3.2.3
$this->set_employee($this->CI->Sale->get_employee($sale_id)->person_id);

**Comment by erastus** [comment]
in the file sale_lib

``public function copy_entire_sale($sale_id)
	{
		$this->empty_cart();
		$this->remove_customer();
		foreach($this->CI->Sale->get_sale_items_ordered($sale_id)->result() as $row)
		{
			$this->add_item($row->item_id, $row->quantity_purchased, $row->item_location, $row->discount_percent, PRICE_MODE_STANDARD, NULL, NULL, $row->item_unit_price, $row->description, $row->serialnumber, TRUE, $row->print_option);
		}
		foreach($this->CI->Sale->get_sale_payments($sale_id)->result() as $row)
		{
			$this->add_payment($row->payment_type, $row->payment_amount);
		}
		$this->set_customer($this->CI->Sale->get_customer($sale_id)->person_id);
		$this->set_employee($this->CI->Sale->get_employee($sale_id)->person_id);
		$this->set_quote_number($this->CI->Sale->get_quote_number($sale_id));
		$this->set_work_order_number($this->CI->Sale->get_work_order_number($sale_id));
		$this->set_sale_type($this->CI->Sale->get_sale_type($sale_id));
		$this->set_comment($this->CI->Sale->get_comment($sale_id));
		$this->set_dinner_table($this->CI->Sale->get_dinner_table($sale_id));
		$this->CI->session->set_userdata('sale_id', $sale_id);
	}

**Comment by odiea** [comment]
I know but when the sale is completed the other line of code is what sets the employee_id. On reprint that line of codes does what it is suppose to do.

**Comment by erastus** [comment]
in the controller sales function complete {$ data ['employee_id'] = $ this-> sale_lib-> get_employee ();}

**Comment by erastus** [comment]
$employee_id = $ this-> sale_lib-> get_employee()

**Comment by odiea** [comment]
Then it throws a db issue where person_id is not present.

**Comment by erastus** [comment]
$employee_id =  $ this->sale_lib-> get_employee();
$employee_info = $this->Employee->get_info($employee_id);

must not mark error in db

**Comment by odiea** [comment]
I tried that no db issue but no employee name shows on the receipt.

**Comment by erastus** [comment]
and when there is no customer?

**Comment by odiea** [comment]
Employee id is showing a -1

**Comment by erastus** [comment]
if the field of employee_id is null or not exist. creates an empty object, you can verify it in the model person

**Comment by odiea** [comment]
![2018-09-17 19_42_46-window](https://user-images.githubusercontent.com/10962177/45659464-ecd28f00-bab1-11e8-9379-ccceb0117889.png)

**Comment by odiea** [comment]
in application/models/sale.php about line 1239 and 1244 add $employee_id
```
public function get_all_suspended($customer_id = NULL)
	{
		if($customer_id == -1)
		{
			$query = $this->db->query("select sale_id, case when sale_type = '".SALE_TYPE_QUOTE."' then quote_number when sale_type = '".SALE_TYPE_WORK_ORDER."' then work_order_number else sale_id end as doc_id, sale_id as suspended_sale_id, sale_status, sale_time, dinner_table_id, customer_id, employee_id, comment from "
				. $this->db->dbprefix('sales') . ' where sale_status = ' . SUSPENDED);
		}
		else
		{
			$query = $this->db->query("select sale_id, case when sale_type = '".SALE_TYPE_QUOTE."' then quote_number when sale_type = '".SALE_TYPE_WORK_ORDER."' then work_order_number else sale_id end as doc_id, sale_status, sale_time, dinner_table_id, customer_id, employee_id, comment from "
				. $this->db->dbprefix('sales') . ' where sale_status = '. SUSPENDED .' AND customer_id = ' . $customer_id);
		}

		return $query->result_array();

	}
```
In application/views/sales/suspended.php
About line 14 if you have not changed anything. About line 36 add
```
<th><?php echo $this->lang->line('sales_employee'); ?></th>
About line 36
<td>
<?php
	
$employee_info = $this->Employee->get_info($suspended_sale['employee_id']);
		 echo $data['employee'] = $employee_info->first_name . ' ' . mb_substr($employee_info->last_name, 0, 1);
?>
</td>

**Comment by nathanzky** [comment]
@odiea Thank you.. :-)
