### ISSUE TITLE
Intallation Error:  'wget' step error

### ISSUE THREAD

**Issue by Karumaj** [opensourcepos/opensourcepos#2056]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is:  not sure??? (not downloaded/ installed yet)
- PHP version is: 7.2
- MySQL or MariaDB version is: 5.7.22
- OS and version is: Ubuntu 18.04 LTS
- WebServer is: LAMP-server (Local install on ubuntu desktop)
- Selected language is:  English
- (If applicable) Docker installation:  N/A
- (If applicable) Installation package for the LAMP/LEMP stack is: LAMP

### Issue / Bug  / Question / New Feature
I have tried to follow the Local Deploy Install instructions from:  [Git OSPOS Wiki](https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-Getting-Started-installations#local-install)  and I had done all prerequisite LAMP install and configurations including phpmyadmin install. 

I am getting issues with the critical `wget` step of downloading the install files: `wget https://github.com/opensourcepos/opensourcepos/archive/lasted.tar.gz -O osposlastedstable.tar.gz`. I had figured that "lasted.tar.gz" was not available at the address and had tried to replace with "3.2.3.tar.gz". Both cases didn't work. BTW I had to use sudo because without it I got permission denied

**This is from my terminal::::::**
**Without sudo**
off_comp_1@Econ-1:/var/www/html$ wget https://github.com/opensourcepos/opensourcepos/archive/3.2.3.tar.gz -O osposlastedstable.tar.gz
osposlastedstable.tar.gz: Permission denied

**Error with 3.2.3.tar.gz:::::::**
off_comp_1@Econ-1:/var/www/html$ sudo wget https://github.com/opensourcepos/opensourcepos/archive/3.2.3.tar.gz -O osposlastedstable.tar.gz
--2018-07-20 12:25:17--  https://github.com/opensourcepos/opensourcepos/archive/3.2.3.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
Unable to establish SSL connection.

**Error with lasted.tar.gz::::::**
off_comp_1@Econ-1:/var/www/html$ sudo wget https://github.com/opensourcepos/opensourcepos/archive/lasted.tar.gz -O osposlastedstable.tar.gz
[sudo] password for off_comp_1: 
--2018-07-20 12:51:01--  https://github.com/opensourcepos/opensourcepos/archive/lasted.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/opensourcepos/opensourcepos/tar.gz/lasted [following]
--2018-07-20 12:51:04--  https://codeload.github.com/opensourcepos/opensourcepos/tar.gz/lasted
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-20 12:51:08 ERROR 404: Not Found.

Please assist.

**Comment by mckaygerhard** [comment]
i'm glad to congratulate you @Karumaj  due this its the only issue well filled in many many months..

but sorry i not have good news for you, seems all are "windo-like" errors, i'll explain clarelly (guindows like users seems need):

1) 
> osposlastedstable.tar.gz: Permission denied

winbuntu permission problems, due the terminal are with "$" normal users cannot write it!

2) 
> Unable to establish SSL connection.

another winbutu problem away from ospos or github

3) 
> 2018-07-20 12:51:08 ERROR 404: Not Found.

OK, first valid error, wiki page has a bad incongruence, i'll fix the wiki page link and there's the right link:
- for stable: https://github.com/opensourcepos/opensourcepos/releases/download/3.2.3/opensourcepos.20180613210031.3.2.3.f1cf3d.zip
- for unstable sync with github: https://bintray.com/package/files/jekkos/opensourcepos/opensourcepos?order=desc&sort=fileLastModified&basePath=&tab=files

**Comment by mckaygerhard** [comment]
i'm glad to congratulate you @Karumaj  due this its the only issue well filled in many many months..

but sorry i not have good news for you, seems all are "windo-like" errors, i'll explain clarelly (guindows like users seems need):

1) 
> osposlastedstable.tar.gz: Permission denied

winbuntu problem, must be in www-data group, using root account to permit to a normal users do that, due the terminal are with "$" normal users cannot write it!

2) 
> Unable to establish SSL connection.

another winbutu problem away from ospos or github, no  comments i dont use winbuntu

3) 
> 2018-07-20 12:51:08 ERROR 404: Not Found.

OK, first valid error, buit also a windo-like error _due if you read it can notice the invalild redaction_: wiki page has a bad incongruence, i'll fix the wiki page link and there's the right link:
- for stable: https://github.com/opensourcepos/opensourcepos/releases/download/3.2.3/opensourcepos.20180613210031.3.2.3.f1cf3d.zip
- for unstable sync with github: https://bintray.com/package/files/jekkos/opensourcepos/opensourcepos?order=desc&sort=fileLastModified&basePath=&tab=files

**Comment by odiea** [comment]
@mckaygerhard So in your mind Ubuntu is a different flavor of Windows. You need help or a long vacation.

**Comment by mckaygerhard** [comment]
ja ja  ja well @odiea winbuntu i just the standar choose to windo-like users? casuality?

i fix the wiki page, change to link to stable an d put unzip command event the tar command

umm noted that bintray can sort files in right way for users to find lasted as first file listed, please you can change the link in the install.md file ? that seems works: https://bintray.com/package/files/jekkos/opensourcepos/opensourcepos?order=desc&sort=fileLastModified&basePath=&tab=files noted the sort=desc in the get parameters...

**Comment by Karumaj** [comment]
Thanks so much for the prompt reply

**Comment by mckaygerhard** [comment]
@Karumaj  thanks to you for reading and fill property the issue template (without care about ambigous)

if you found more errors please report it, and close this issue, now are fixed

**Comment by WebShells** [comment]
Fixed as mentioned... Thanks @mckaygerhard

**Comment by Karumaj** [comment]
Thanks but before we really close this, I wish we could rewrite the
steps/walkthrough (even if just providing the information here). For
instance, if we are going to replace tar, which options and switches should
we use for the unzip command in the next steps?. I'm relatively new to the
terminal.

**Comment by mckaygerhard** [comment]
hi @Karumaj you pointed that are new to terminal, so please there's a "for impatinets section" in the wiki that have a iso with all the things need.. why you dont use that with a virtualbox machine?

also for rewriting please go ahead and post here all your steps, i also change the tar file by the zip file and commands

**Comment by Karumaj** [comment]
Thanks for all your helpful answers so far.
One more thing - I have tried many searches but haven't seen any mention on uninstalling. So, suppose I wished to completely remove ospos and re-install, is there anything else I need to do apart from removing its directories and files in var/www/html ? I have uninstalled LAMP but ospos is still there intact!

**Comment by Karumaj** [comment]
Hi, can I finish all my issues here?
**An error for step 6: (Database creation):**

root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';CREATE DATABASE ospos;GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'ospos'; database exists

I was trying to to reinstall ospos. had uninstalled LAMP and deleted html ( rm -r  /var/www/html)

**Comment by Karumaj** [comment]
Hi @mckaygerhard,  @WebShells  any help here?

**Comment by Karumaj** [comment]
A real headache in database creation:
1. ERROR 1007 (HY000) at line 1: Can't create database 'ospos'; database exists
Then I change database name from ospos
2. ERROR 1819 (HY000) at line 1: Your password does not satisfy the current policy requirements
Then I change database name again and password (to include numbers and special xters)
3. ERROR 1007 (HY000) at line 1: Can't create database 'pmospos'; database exists
Then I change database name again (tries to create new)
4. ERROR 1007 (HY000) at line 1: Can't create database 'pmospos2'; database exists

**Full terminal output::::**
**root@PM-Termnl:/var/www/html#** mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';CREATE DATABASE ospos;GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'ospos'; database exists
**root@PM-Termnl:/var/www/html#** mysql -u root -e "CREATE SCHEMA pmospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';CREATE DATABASE pmospos;GRANT ALL PRIVILEGES ON pmospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1819 (HY000) at line 1: Your password does not satisfy the current policy requirements
**root@PM-Termnl:/var/www/html#** mysql -u root -e "CREATE SCHEMA pmospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%';CREATE DATABASE pmospos;GRANT ALL PRIVILEGES ON pmospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'pmospos'; database exists
**root@PM-Termnl:/var/www/html#** mysql -u root -e "CREATE SCHEMA pmospos2;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%';CREATE DATABASE pmospos2;GRANT ALL PRIVILEGES ON pmospos2 . * TO 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'pmospos2'; database exists

**Comment by odiea** [comment]
As a novice Ubuntu server user I have always used Webmin and Phpmyadmin and not the command line

**Comment by Karumaj** [comment]
Was trying to play by the script. Let me try phpmyadmin before I complain
more. Tx for the tip

**Comment by SteveIreland** [comment]
If the database already exist be sure to include

DROP PMOSPOS2 IF EXISTS;

**Comment by mckaygerhard** [comment]
sorry for late.. now reading.. from up..

**Comment by mckaygerhard** [comment]
## **puff please all are LOGICALL errors i'll explain now:**

> root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';CREATE DATABASE ospos;GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'ospos'; database exists

obviously if you have an already made similar name DB must be previously erased and/or droped!

>     ERROR 1007 (HY000) at line 1: Can't create database 'ospos'; database exists

prevous installed db still exist obviously must be sure there's no previous database exist! droped or erase it! that's all

>   ERROR 1819 (HY000) at line 1: Your password does not satisfy the current policy requirements

winbuntu related...


>    ERROR 1007 (HY000) at line 1: Can't create database 'pmospos'; database exists

the problem of linux its that forces the users to think, and currently the user need to do the task hurry to cheap time, i understand that but i expose something about it: "without investments there is never any profit"  so drop windows and start to use a real os

>    ERROR 1007 (HY000) at line 1: Can't create database 'pmospos2'; database exists

this was happened due created the db name in a batch command event try by separate it, due the command in the wiki are bash commands but in batch process, as i said, "without investments there is never any profit"  so drop windows and start to use a real os

## **Lest explain more detailed now the errors:**

> root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';CREATE DATABASE ospos;GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'ospos'; database exists
root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA pmospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';CREATE DATABASE pmospos;GRANT ALL PRIVILEGES ON pmospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1819 (HY000) at line 1: Your password does not satisfy the current policy requirements

you run a several commands, do you nothed, and not all commands executed complete, if the error are related to "password" its obviously that `CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';` or `... * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WI... ` was the command problem..

also here maybe be a new bug due newer db administratuive policies need better password, not! due the error are related to distro specific. i can added extra steps to avoid that problem but Mysql changes too much so i assumed a Mariadb isntallation and will point notes on the wiki!

at last: here are two similar commands: first `CREATE SCHEMA pmospos2`  and lateer `CREATE DATABASE pmospos2` so its the same command, i must revise the wiki for check that not was a miscpelled!

> root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA pmospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%';CREATE DATABASE pmospos;GRANT ALL PRIVILEGES ON pmospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'pmospos'; database exists

now you try to RE-RUN same command, pointed that you just think that administrative task are just re-click? not, admin it not same as user, if you dont know about administrator form of work, it's recomended try some days to lear some comands and then find that re-run the same command will result in databse already created due the previous batch of commands, some of those just executed susessfully, so we can deduced that the commmand related to DB creation was susessfully!

> root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA pmospos2;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%';CREATE DATABASE pmospos2;GRANT ALL PRIVILEGES ON pmospos2 . * TO 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'pmospos2'; database exists

similar to previus, of course dont noted, but here are two similar commands: first `CREATE SCHEMA pmospos2`  and lateer `CREATE DATABASE pmospos2` so its the same command, i revised the wiki to check if are correct the wiki steps or may have errors..

## a special note:

this are not a linux related or command un familiar related, must think about it, some.. i noted that if those command were run on guindows by guindows cmd users only said "i solved easyle was here the error" but due was on linux..  i like that linux policy that said "adminis must already know what are doing", and take with easy, without investments there is never any profit, so i recomended some practice and i'll now check again the wiki for best results..

**Comment by mckaygerhard** [comment]
## **puff please all are LOGICALL errors i'll explain now:**

here are two similar commands: first `CREATE SCHEMA ...`  and lateer `CREATE DATABASE ...` so its the same command, i must revise the wiki for check that not was a miscpelled! BUT you as asdministrator must think a little:

> root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';CREATE DATABASE ospos;GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'ospos'; database exists

obviously if you have an already made similar name DB must be previously erased and/or droped! do you see the commands running in bach?

>     ERROR 1007 (HY000) at line 1: Can't create database 'ospos'; database exists

prevous installed db still exist obviously must be sure there's no previous database exist! droped or erase it! that's all, OR REVISE THE COMMAND IFF THERE SOME ERROR, copy paste are nto the best way to do something...

>   ERROR 1819 (HY000) at line 1: Your password does not satisfy the current policy requirements

winbuntu related...


>    ERROR 1007 (HY000) at line 1: Can't create database 'pmospos'; database exists
>    ERROR 1007 (HY000) at line 1: Can't create database 'pmospos2'; database exists

this was happened due created the db name in a batch command event try by separate it, the wiki have **some miscpelled error but that not are a problem due DB are created and can continue to install,** 

the problem of linux its that forces the users to think, and currently the user need to do the task hurry to cheap time, i understand that but i expose something about it: "without investments there is never any profit"  so drop windows and start to use a real os

## **Lest explain more detailed now the errors:**

> root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';CREATE DATABASE ospos;GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'ospos'; database exists
root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA pmospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';CREATE DATABASE pmospos;GRANT ALL PRIVILEGES ON pmospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1819 (HY000) at line 1: Your password does not satisfy the current policy requirements

you run a several commands, do you noted?, not all commands executed complete, if the error are related to "password" its obviously that `CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';` or `... * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WI... ` was the problem  command ...

also here maybe be a new bug due newer db administrative policies need better password, not! due that error are related to distro specific. i can added extra steps to avoid that problem but Mysql changes too much so i assumed a Mariadb isntallation and will point notes on the wiki!

at last: here are two similar commands: first `CREATE SCHEMA pmospos2`  and later `CREATE DATABASE pmospos2` so its in fact the same command, i must revise the wiki, was a miscpelled! BUT THAT ARE NOT A PROBLEN FOR CONTINUE THE INSTALL PROCESS!!

> root@PM-Termnl:/var/www/html# mysql -u root -e "CREATE SCHEMA pmospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%';CREATE DATABASE pmospos;GRANT ALL PRIVILEGES ON pmospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsaleC0d3%' WITH GRANT OPTION;FLUSH PRIVILEGES;"
ERROR 1007 (HY000) at line 1: Can't create database 'pmospos'; database exists

now you try to RE-RUN same command, pointed that you just think that administrative task are just re-click? not, admin it not same as user, if you dont know about administrator form of work, it's recommended try some days to learn

## a special note:

this are not a linux related or command un familiar related, must think about it, some.. i noted that if those command were run on guindows by guindows cmd users only said "i solved easyle was here the error" but due was on linux..  i like that linux policy that said "adminis must already know what are doing", and take with easy, without investments there is never any profit, so i recomended some practice and i'll now check again the wiki for best results..

**Comment by Karumaj** [comment]
Thanks for all the answers. Many others must be benefiting too

I'm stuck in the last step before login. 
1. But first the encryption key: php7.2 could not install openssl and mcrypt __(no installation candidate, could be obsolete and other related messages on the terminal_ )._ Does this mean we don't need the encryption key?
2. index.php in /var/www/html/public/   : http://localhost/public/index.php on the browser shows blank and after trying to edit system directory path it says :  " .. system path ...not configured properly...."
have tried: 
               $system_path = '../vendor/codeigniter/framework/system';
                                   = '..var/www/html//vendor/codeigniter/framework/system';
with and without trailing slashes.. 

Apache & msql are running ok and have confirmed ospos database and tables are in place

Please assist

**Comment by mckaygerhard** [comment]
again another related to fmailiarize with the real os, a linux:

> no installation candidate, could be obsolete and other related messages on the terminal 

on php7 those modules where included build in and changed to openssl module, search at your linux distribution

> index.php in /var/www ..

different issue please open a new issue and reclaim "ambigous htaccess not property configured" i posted a solution on my fork

put a idex.php fiel with redirection to public more easy rather complicated htaccess files.

**Comment by Karumaj** [comment]
@mckaygerhard Please elaborate on this:
 put a idex.php fiel with redirection to public more easy rather complicated htaccess files.

**Where** do I create index.php file **and how do I redirect** to public. Thanks

**Comment by mckaygerhard** [comment]
see :  https://github.com/osposweb/osposweb/commit/ac3a4d742ba7f8994185f3379473457032b94ab6

i recommend do not use manual made thinsk and download my iso an easy option that can be downloaded with all needed components included and software ready to use at https://sourceforge.net/projects/vegnuli/files/VenenuX-1.0/venenux-1.0-osposweb/debian-venenux-8-osposweb-i386.hybrid.iso/download and can later boot in a virtualBox machine by example.

**Comment by Karumaj** [comment]
Hello all good people?
At my my current stage I don't know whether to say "hooray!" or "still in the dark!" because I have a rather interestingly disturbing scenario. @mckaygerhard  I avoided to download the iso because i figured that I had to further learn about virtualboxes -- which i will do sometime. So, instead I followed the old Local Deploy walkthrough that all of you previous contributers did great to update. 
 
Now here is my case: I followed this [Git ospos wiki install guide - _Own local deploy_](https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-Getting-Started-installations#local-install) and did the necessary edits of database.php to change to my chosen password. Now, after typing http:localhost/public on the browser I encountered a common (on discussion threads) error: Invalid Username or Password

![invallid username or password](https://user-images.githubusercontent.com/6235797/43541149-5453420a-95d2-11e8-807f-c450b371cea0.png)

Please note: my username and password were the same as entered during "CREATE DATABASE " step. 

Now the big surprise was: --- the ospos defaults (admin & pointofsale) are working on the localhost/public prompt. It was just a curious trial and then, alas, I was logged in! 
Just how?

![logged-in-now](https://user-images.githubusercontent.com/6235797/43541285-b2ffe8d0-95d2-11e8-9d1c-f5609c9f6ded.png)

My environment:
--  ubuntu 18.04 and latest apache2 mariadb php
--  latest ospos from bintray: https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180729104548.master.76c63f.zip

My checks:
--  I have confirmed from the terminal that my ospos database with my own password was created and have actually viewed even the tables! [ mysql -u admin -p MyOwnPass ]
--  Confirmed from the terminal that there is no database with the default credentials (admin & pointofsale)

`MariaDB [ospos]> DESCRIBE ospos_tax_codes;
+---------------+--------------+------+-----+---------+-------+
| Field         | Type         | Null | Key | Default | Extra |
+---------------+--------------+------+-----+---------+-------+
| tax_code      | varchar(32)  | NO   | PRI | NULL    |       |
| tax_code_name | varchar(255) | NO   |     |         |       |
| tax_code_type | tinyint(2)   | NO   |     | 0       |       |
| city          | varchar(255) | NO   |     |         |       |
| state         | varchar(255) | NO   |     |         |       |
+---------------+--------------+------+-----+---------+-------+
5 rows in set (0.00 sec)

MariaDB [ospos]> quit
Bye
root@PM-Comp:~# mysql -uadmin -ppointofsale
ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: YES)
root@PM-Comp:~# mysql -u admin -p pointofsale
Enter password: 
ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: YES)
root@PM-Comp:~# 
`
The first table is viewed from my login credentials used in creating the database. The last two are unsuccessful attempts using ospos defaults

NOW: I think its unwise to use the 'fake login' that ushers me in as "John Doe' ! Could it be a slight issue that can be fixed from my end? What are my options now ?

To you good people...

**Comment by mckaygerhard** [comment]
hi @Karumaj lest see now:

**Comment by mckaygerhard** [comment]
hi @Karumaj seems you are very VERY confused:

> I avoided to download the iso because i figured that I had to further learn about virtualboxes -- 

so install it! no virtualboxes (that i hate it and winbuntu are no a real linux jajaja) and no windoze rules, you must made more read realted to DBMS administation and real OS's rather assumen some points, i explain now:

> Now here is my case: I followed this Git ospos wiki install guide - Local deploy install 

so then as i guess i'll still need to improved it!

> and did the necessary edits of database.php to change to my chosen password. Now, after typing http:localhost/public on the browser I encountered a common (on discussion threads) error: Invalid Username or Password

hey! warning, the username and password here are admin adn pointofsale there's no relation to those using in the database access!

> Please note: my username and password were the same as entered during "CREATE DATABASE " step.
> Now the big surprise was: --- the ospos db login defaults (admin & pointofsale) are working on the localhost/public prompt. It was just a curious trial and then, alas, I was logged in! Just how?

i will assume that "admin" and "pointofsale" are **in casuality same in DB ACESS as in the LOGIN ACCESS screen** right! BUT I REPEAT NOTHING RELATED TO!

> NOW: I think its unwise to use the 'fake login' that ushers me in as "John Doe' ! Could it be a slight issue that can be fixed from my end? What are my options now ? @jekkos great work first! what's your take here?

it's a initial login by default, i suppost that at first login that user (noted that it's the ID 1 in the DB) will be pasword changed! by "you"

**Comment by Karumaj** [comment]
Thanks @mckaygerhard  for shedding the (much needed) light. I forgive myself because I'm still a linux/mysql newbie! 

I am now on "Getting started" pages. See you on other issues...

Bye good pple.

**Comment by Karumaj** [comment]
Hello good peoples?
I wish to reuse this thread so that you can quickly connect with my issue.
It's simple: Where can I get the installation steps that are now missing from the web? @mckaygerhard @WebShells . ..

This is what I'm talking about: [DOCs Users](https://github.com/opensourcepos/opensourcepos/wiki) . The "DOCS USERS Getting Started installations" page content is no longer there. Can you give me the steps here please?

**Comment by SteveIreland** [comment]
I think the page you want is now found at https://github.com/opensourcepos/opensourcepos/wiki/Getting-Started-installations

**Comment by Karumaj** [comment]
Thanks
