### ISSUE TITLE
Make 2 sales in different tabs of the same browser.

### ISSUE THREAD

**Issue by erastus91** [opensourcepos/opensourcepos#2059]
I want to make 2 or more sales in the same browser. since my employees open more tabs to make sales and this gives me mistakes when printing, because they load articles from the other tab.

**Comment by WebShells** [comment]
Mmmm that should be using several employees each on his own login, or else it will load same sale...

**Comment by erastus91** [comment]
There are only 2 machines and they make sales at the same time. without rows, it is a departmental store. They do not use the suspension function.

**Comment by erastus91** [comment]
I'm willing to pay for the show. to be able to make more sales in different tabs with the same employee session

**Comment by SteveIreland** [comment]
One sale per session is "baked into" OSPOS.  My opinion is that this would require a major architectural change.  Is there any way that you can just use two separate browsers instead of two tabs in the same browser?

I haven't tried it, but I stumbled across a browser calling itself Ghost browser. It claims to support multiple sessions but since I haven't used it myself so I cannot say anything what issues  you might encounter,

**Comment by SteveIreland** [comment]
I don't understand the question.  Can you elaborate (or maybe someone else has better insight)?

**Comment by erastus91** [comment]
how to restrict that is used in a single window as the whatsapp application does

serviceworker ??

![whatsapp](https://user-images.githubusercontent.com/6712397/43083847-0cee5b2e-8e5d-11e8-9030-56bc6bedd699.png)

**Comment by mckaygerhard** [comment]
umm i afraid that you misunderstand the behaviour @erastus91

**Comment by erastus91** [comment]
I do not understand English, I speak Spanish, maybe that's the problem

**Comment by mckaygerhard** [comment]
@erastus91 SERA MEJOR USES MUCHO EL TRANSLATOR,  quieren hacer dos ventas distintas en el misma sesion, con el msimo usuario, esto es muy distinto a hacer dos llamadas "guasoh" distintas con el mismo usuario, la venta en sesio usa un unicdo id el -1

now for all, the main problem its that current sale are temporally loaded with id -1 at the session of the user..  from here we have:
1) the storage of the session its very limited, i guess was 2K or 2M i dont remenber but please we will charge amount of sales (more than one) in the user session storage?
2) the current sale are temporally store with a "well knowed id" currently the id "-1" so more that one will need a "well knowed id formats to identify" respect each users (the employee)
3) for users that dont understand ples before populate this issue with ilogical quiestions read before: https://github.com/osposweb/osposweb/blob/gh-pages/ospos-5-DEVEL-2-procs-min-sqls-es.md sorry only in spanish but use translator, i try to explain the workflow of the sale process and user/employee

**Comment by erastus91** [comment]
Gracias @mckaygerhard. Entiendo que la venta solo puede ser por un solo usuario (empleado), ¿cómo puedo limitarme a usar solo una pestaña para evitar problemas?
Google translate.
Thanks @mckaygerhard. I understand that the sale can only be for a single user (employee), how can I limit myself to using only one tab to avoid problems?

**Comment by mckaygerhard** [comment]
umm i dont undeerstand "como puedo limitarme ... para evitar problemas" please explain more in spanish to property i translate the problem in english and help also others

**Comment by erastus91** [comment]
si, como lo hace la aplicación web.whatsapp.com no me deja estar en dos pestañas

**Comment by erastus91** [comment]
así se obliga al empleado a trabajar en una sola pestaña, y no abrir otra pestaña

**Comment by mckaygerhard** [comment]
rename issue to "avoid open new tab" and i premonite response: it's impossible, youmust need smart people forced! so dont use window like ... 

you cannot avoid to open new tab, user will try to do as possible by any misctake.. 

maybe the only way its open a very limited window by javascript after employee login sucess!

**Comment by jekkos** [comment]
Such things are never handled by webapplications themselves. A browser will always use the same session across different tabs. I see two options here

* it could work if you open a new window (or tab) as 'icognito'
* another option could be using multiple domains for the same server, which would then use a different cookie for each tab. Easiest would be to create a wildcard dns record so that you can use an unlimited number of domains and thus tabs
