### ISSUE TITLE
export data not all

### ISSUE THREAD

**Issue by bocado47** [opensourcepos/opensourcepos#2063]
(FOR ITEMS) 
my  exportDataType: "basic " already set at exportDataType: "ALL", but  when i do export   only first page of my data are exported ? 

my opensourcepos.min.js is this  "public/dist/opensourcepos.min.js?rel=c206fd4a9f"

 a.extend(a.fn.bootstrapTable.defaults, {
            showExport: !1,
            exportDataType: "ALL",
            exportTypes: ["json", "xml", "csv", "txt", "sql", "excel"],
            exportOptions: {}
        }),

somebody help me. ? Thanks

**Comment by WebShells** [comment]
You are editing the wrong file... You should edit manage_tables.js ... Located under public - js - directory... Then you should provide the table header needed to full export with additional Params....
Shall we close?

**Comment by bocado47** [comment]
already edited. but still not all data catch on export

**Comment by bocado47** [comment]
![image](https://user-images.githubusercontent.com/29650349/43252295-b62e64e2-90f4-11e8-9c8a-bb20c0a58923.png)

**Comment by jekkos** [comment]
think this was already covered in #868

**Comment by daN4cat** [comment]
Yep, this was fixed. Which version are we talking about here?

**Comment by bocado47** [comment]
3.0.0 - 3.0.2 I think  .

**Comment by daN4cat** [comment]
Ok, so this is fixed in recent versions.
