### ISSUE TITLE
how to insert footerCallBack in bootstraptable like this, Help please :) 

### ISSUE THREAD

**Issue by bocado47** [opensourcepos/opensourcepos#2065]
"footerCallback": function ( tfoot, data, start, end, display ) {
        var api = this.api(), data;

// Remove the formatting to get integer data for summation
        var intVal = function ( i ) {
        return typeof i === 'string' ?
            i.replace(/[\₱,]/g, '')*1 :
            typeof i === 'number' ?
            i : 0;
        };

        total = api
          .column( 11 )
          .data()
          .reduce( function (a, b) {
                return intVal(a) + intVal(b);
            }, 0 );
        pageTotal = api
                .column( 11, { page: 'current'} )
                .data()
                .reduce( function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0 );
                
        totals = api
          .column( 12 )
          .data()
          .reduce( function (a, b) {
                return intVal(a) + intVal(b);
            }, 0 );
        pageTotals = api
                .column( 12, { page: 'current'} )
                .data()
                .reduce( function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0 );
            var numFormat = $.fn.dataTable.render.number( '\,', '.', 2, '₱' ).display;
            $( api.column( 9 ).footer() ).html('Total Sales: '+numFormat(pageTotal)+' ( '+numFormat(total)+' ) <br>Total Other Income: '+numFormat(pageTotals)+' ( '+numFormat(totals)+' )');
    // $( api.column( 8 ).footer() ).html('Total Other Income: '+numFormat(totals));    
},

**Comment by odiea** [comment]
No template info. Does not pertain to OSPOS. Closed
