### ISSUE TITLE
Make sale of a quantity in fraction

### ISSUE THREAD

**Issue by developerfranso** [opensourcepos/opensourcepos#2067]
Hi House,
i have been wondering is it possible with OPOS to sell quantities like 0.5 (Half) , 1/4 ( a quarter) of the Quantity, 1.5 and so on .  anytime i try to sell 0.5 it rounds up to zero and does not subtract, any help, please?

**Comment by WebShells** [comment]
Hello @developerfranso, yes it is possible in our project... Just you have to set quantity decimals to 2 or more..

**Comment by WebShells** [comment]
Closing this one...

**Comment by developerfranso** [comment]
Thanks for the response .  what if  you have 50kg of a certain commodity and u wish to sell in quantities of  1/4 kg and so on. @WebShells

**Comment by WebShells** [comment]
@developerfranso in this case you should have to divide your stock into portions and sell them or you should use weight based barcode

**Comment by AlaaEldinMohamed** [comment]
> 
> 
> Hello @developerfranso, yes it is possible in our project... Just you have to set quantity decimals to 2 or more..

@WebShells , Hello WebShells could you please elaborate more on how to set quantity decimals 2 or more ? because i have tried to sell half item (for exe 0.5) and it will not accept ?

**Comment by WebShells** [comment]
@AlaaEldinMohamed in configuration under locale section, set the quantity decimals to 2 or 3 depending on your needs.
0.500 is 0.500 grams 1 is as 1 KG.
