### ISSUE TITLE
Docker-build database.sql missing

### ISSUE THREAD

**Issue by jknight2014** [opensourcepos/opensourcepos#2070]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [New Install] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: Latest
- OSPOS git commit hash is: 76c63f6
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: Ubuntu 16.04
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: docker-compose from source
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Running docker compose build turns up the following error:

    server@Server:/opt/OSPOS$ sudo docker-compose build
    Building sqlscript
    Step 1/4 : FROM debian:jessie
     ---> 79f4bda91989
    Step 2/4 : MAINTAINER jekkos
     ---> Using cache
     ---> 146065462154
     Step 3/4 : ADD database.sql /docker-entrypoint-initdb.d/database.sql
    ERROR: Service 'sqlscript' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder905081789/database.sql: no such file or directory

dockerfile in the database directory references the database.sql but no file with that name exists. There is a tables.sql

**Comment by odiea** [comment]
For some reason that was removed on June 10th.

**Comment by jknight2014** [comment]
I read through the commits and missed that somehow. I pulled that from an older commit and build is progressing now. Is there an intention to change how the database is built?

**Comment by mckaygerhard** [comment]
errr ok so then so now ? maybe build form the others (like the final
release zip?)

Lenz McKAY Gerardo (PICCORO)
http://qgqlochekone.blogspot.com

2018-08-03 9:59 GMT-04:00 odiea <notifications@github.com>:

**Comment by jknight2014** [comment]
OK, I did not realize bintray was a name. I was thinking it was mistranslated for repo. Reatarted using the latest release file from "Bintray" and it built great. Now though all the resources are attempting to pull from SSL with no TLS server present.

**Comment by mckaygerhard** [comment]
hi @jknight2014 plesae can you revised if the wiki procedure for install are correct now?

**Comment by jknight2014** [comment]
@mckaygerhard When you say dont use github directly do you mean dont use the `git clone` command? Your docker method of using seperate containers may be a little over complex for what your trying to acomplish. I would think making your own custom image with all the necessary dependencies preconfigured. Initial startup can pull your latest stable image for the project. Docker setup in one simple command. Mind you, I am no developer, just an Admin.

**Comment by mckaygerhard** [comment]
i think similar like you @jknight2014 and yes, dont use github commands and as almost all here, seems now are pretty ambiguous, that commands where extracted from the amount of disorderly notes found, then i try to reproduce an custom install in a older debian and write initial wiki steps for docker, i'm not particular avocate to that method, **and from that moment today obvously some things are changed now!**

in fact using docker it's more easy to developer but **complicated for admins to setup**, developers may found a consistent and homogeneous environment so, then, debug or find solutions are more easy, but admins may found a headhache of problems due the build&retrieve cases, **why? simple: the resources that docker will retrieve/download, depends of the very very changing "network"**

so then my directions over that problem are two:
1. erase the docker option and let only for experts, so commands are close to the environment
2. help here @jknight2014  to improve the wiki and provide more detailes commands/howto

so if you choose the second i can also help to improve the wiki, i put the firts option too **due the idea its provide easy ways to do something, that's why i put in the beggining of the wiki page for install the iso ready to use link!** of course only debian not winbuntu.

**Comment by jknight2014** [comment]
The problem I am encountering now is trying to map ports. Since I am not dedicating a server to this app I would like to run OSPOS on an alternate port. The problem is your build is only forwarding port 80. When your app references HTTPS urls the server connection resets because port 443 is conflicting.

**Comment by daN4cat** [comment]
Open source is made of doers, people who walk the talk and make it happen.

**Comment by mckaygerhard** [comment]
i cant' see this here, but i can answered:

> The problem I am encountering now is trying to map ports. Since I am not dedicating a server to this app I would like to run OSPOS on an alternate port. The problem is your build is only forwarding port 80. When your app references HTTPS urls the server connection resets because port 443 is conflicting.

well that point it's beyond of the wiki, that its a custom setup, in that point it's a administrator zone! that's why i not like docker, too complicated!

it's only forwarding that port due it's the default's ..

**Comment by mckaygerhard** [comment]
i cant' see this here, but i can answered:

> The problem I am encountering now is trying to map ports. Since I am not dedicating a server to this app I would like to run OSPOS on an alternate port. The problem is your build is only forwarding port 80. When your app references HTTPS urls the server connection resets because port 443 is conflicting.

well that point it's beyond of the wiki, that its a custom setup, in that point it's a administrator zone! that's why i not like docker, too complicated!

it's only forwarding that port due it's the default's .. https://www.digitalocean.com/community/questions/how-to-bind-multiple-domains-ports-80-and-443-to-docker-contained-applications maybe that link can help to you

**Comment by jknight2014** [comment]
I will take some time and work through the wiki and get my install working. If I can keep up maybe I will maintain the docker image so you can focus on the app itself. 

I know what you mean, using separate images in your development makes it easier. I will get a single docker image, the idea is to simplify the deployment. If everything is contained things like custom ports become incredibly easy. And you can utilize socket connections rather then TCP connections through the docker network. I will see what I can get together tonight.

**Comment by mckaygerhard** [comment]
well seems do you are not understand here! -> `If everything is contained` If everything is contained so security updates over production environment must be doen over all the "combo" and not only over the specific service, that's why softw depends in OS are not good when "a project" will provide it!

**Comment by jknight2014** [comment]
Persistent data is stored outside the container. Security updates are easy, pull new application layers and build the container. Approx 10 seconds.

**Comment by jknight2014** [comment]
Where is the best location for the most current stable build? Your Wiki lists github but your readme lists the other site. Just want to be sure I am pulling the preferred version.

**Comment by jekkos** [comment]
currently we only promote 'releases' as stable and feature complete versions. However I feel that what is in master is also stable enough for daily use.

**Comment by jekkos** [comment]
I guess that you'll need to build the project before building the dockerfile now, or at least run the grunt build so it assembles the database.sql file. The bintray builds should be fine for that purpose though.

**Comment by mckaygerhard** [comment]
> Persistent data is stored outside the container. Security updates are easy, pull new application layers and build the container. Approx 10 seconds.

stic stic stic, always assuming hav network right? also always assumed wrong place, let's see @jknight2014 , ospos bundled a CI3 versin on the release, if debian distributed also CI and discovered a important hole? i must waith until ospos (and ospos ntil CI team) published the fix? as i know debian publish security fix almost inmediatelly, it's listed at number one of the most secure os and have a compatible CVE news list!

> Where is the best location for the most current stable build? Your Wiki lists github but your readme lists the other site. Just want to be sure I am pulling the preferred version.

what do you think about the README and about the wiki redaction? i think README are so ambigous, and wiki are so complicated, i wish to merge in a best made but well i'm just only a user here! developers have the rules!

as @jekkos said, if you used github download/clone must build the project (very complicated) and that process are (i suffer made that) xplained in the wiki also..

for more ready to use, there's two places as wiki said, stable release are the direct link in the wiki, i not mention bintray due it's obvious are not stable sure! recents bugs (and "hurry releases") in decimals corroborates that!
