### ISSUE TITLE
New Install in Xamp - database.sql is missing in Database Folder

### ISSUE THREAD

**Issue by anasiqbalkhan** [opensourcepos/opensourcepos#2071]
Hi there,

I want to install opensourcepos in xamp and I download the package from Github but database.sql is missing in Database Folder.

Please help me to Make a new install in xamp.

Regard

**Comment by SteveIreland** [comment]
See issue #2070 for instructions

**Comment by binahmad0419** [comment]
I can't find database.sql help me please
