### ISSUE TITLE
Demo username and password are not working

### ISSUE THREAD

**Issue by aokby** [opensourcepos/opensourcepos#2073]
Demo username and password are not working 
and default language is not english
https://demo.opensourcepos.org/
username: admin
password: pointofsale

![screenshot from 2018-08-07 15-21-10](https://user-images.githubusercontent.com/20846673/43779323-6c692aaa-9a58-11e8-87cc-d8ca71ee720c.png)

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information
- demo https://demo.opensourcepos.org/

###  Question 

Demo LOGIN is not Working using
username: admin
password: pointofsale
https://demo.opensourcepos.org/

**Comment by mckaygerhard** [comment]
many "isuess ago" i pointed that demo must setup a user that in logout erase all the made configurations and usage! 

due was mention by me was ignored! now seems are very need it feature! a speciall rule athat after 3 logins will earase all the data! that's could easy to do for developers experts!

**Comment by SteveIreland** [comment]
It was understood by all  that there would be piss-ants that were going to abuse the demo.  Since we refresh it fairly often it was decided that there wasn't a need to add a new security feature just for the demo.

There are more important features that we need to be spending our time on thank you very much.

**Comment by odiea** [comment]
It works now so I will close this issue. @aokby Thanks for reporting it.

**Comment by jekkos** [comment]
Ok have refreshed it indeed

**Comment by odiea** [comment]
@jekkos have you had a chance to see what is happening with this? Is it corruption or a bad user changing the admin password?

**Comment by daN4cat** [comment]
I bet on the latter @SteveIreland 's whiskey
