### ISSUE TITLE
Android or ios use

### ISSUE THREAD

**Issue by Mana53** [opensourcepos/opensourcepos#2074]
Is it possible to use it in android or ios tablets for getting an order from costumes?

**Comment by Mana53** [comment]
Honestly, I am an ordinary user and I don't know how should install this program on my laptop anybody can help me for a simple installation?

**Comment by mckaygerhard** [comment]
if you no have enought knowledge pay a symbolic amount of bucks for the job!

i have a fork that are modify for capable to use into androit/ios (tech details: using webview)

**Comment by Mana53** [comment]
@mckaygerhard let me know the cost?

**Comment by daN4cat** [comment]
@Mana53 I would be careful about the quality of you'd get, the guy is here to make easy talks all the time and misleading people too at times, and he has not contribute to the code in any form so far but some translations and convoluted wiki pages. Just after easy rides.....

**Comment by SteveIreland** [comment]
@Mana53 what OS are you running on  your laptop?

**Comment by mckaygerhard** [comment]
well as @dan4cat said, lest' make something, here can be other that can be made the work, but i'll sure be more thatn 10 bucks jeje, i do only for simbolic price, not for get money, what do you think agains that @dan4cat and @SteveIreland ?

so then @Mana53 lest taking in my fork or lest waith two days if something offers do the job!?

**Comment by mckaygerhard** [comment]
umm interesting someone have a work that use my fork!? Well, I don't have any apk demo yet, but I can do the job but if you @Mana53 decide compromise with me... I can do it for about 4 dollars, the price is symbolic.

**Comment by Mana53** [comment]
@nerv55 can you send the demo for the test, please?

**Comment by nerv55** [comment]
Yes, I will post the link to apk file here

**Comment by nerv55** [comment]
@Mana53  here link to demo 
https://wetransfer.com/downloads/682bbf9a37e5e7a5d0a0da05bd9030a620180817115526/c16e52db1cb8146b9c24d900ba51c92920180817115526/ebc7b9

to login you can use the default credentials for ospos

**Comment by Mana53** [comment]
@nerv55 I don't know how should use this file.

**Comment by nerv55** [comment]
@Mana53 , Sorry for the delay, here is the information https://www.wikihow.tech/Install-APK-Files-on-Android   <--- in this link you can read what you must do to install de APK, is the same process for tablets.

**Comment by haicoi311** [comment]
@nerv55 Can I get an apk file to test the software? and how this app connect to my ospos database?

**Comment by nerv55** [comment]
@haicoi311 , yes you can, find my fork of opensourcepos and post me from there, I will give you the link to apk file.

**Comment by haicoi311** [comment]
@nerv55 The link above has expired. Can you send me a new one?

**Comment by januaryramadhan** [comment]
Yeah, that link above is expired. there are any mirror ?

**Comment by nerv55** [comment]
@haicoi311 , @januaryramadhan : there is no mirrors, please find my fork of this repository, post me from there and I will send you the link to apk file.

**Comment by mckaygerhard** [comment]
hi @haicoi311  and @januaryramadhan : please go to the @nerv55 profile in guthub and here onece, search for a nerv55 ospos proyect and post there! NOT HERE! to mantanin distance and keep in issue! it's not a thing of other world do that ok?

> @haicoi311 , yes you can, find my fork of opensourcepos and post me from there, I will give you the link to apk file.

do you guys noted and READ THE CITED TEXT that @nerv55 dsaid! please any one can READ!? before paste or write to any part on internet!?

now i understand the point about issues in ospos, respect  @daN4cat closing any issue that he see! puff this are very frustrating!

**Comment by haicoi311** [comment]
Come down man. Sorry for making you guys get upset. Actually I do not fully understand what @nerv55 said above. I have tried to open nerve55 profile to find any where to pos my request for the file. But all the link forward to this project. One more time. Could you give me the link where I can post the request to him?

**Comment by nerv55** [comment]
@haicoi311  here is my fork of this project nerv55/opensourcepos, please post there, and will answer you as soon as I can.

**Comment by mckaygerhard** [comment]
ok i noted her fork dont allow issues, but plesase! for the mother of god! aliens and odin! do you make a fork to ospos from the nerv55 repo0? PLEEESSAAASEEEEEE KIILL HIM! before make childs!

take a breack @haicoi311 please can you READ some of the github work flow? you must make an issue not a pull request!!!!!!

if you cannot post a issue in other fork, that's not means you make a pull! try to search or open a issue in other repos of the same author, not here !pufff

**Comment by nerv55** [comment]
@mckaygerhard, @haicoi311  it's enable the issue request please make you post there

**Comment by akjanith** [comment]
Hey Guys, I have followed these instructions [https://naatlyrics.net/how-to-convert-any-website-into-an-android-app-free-using-android-studio/](url) by **"naatlyrics11"** & managed to create an android apk successfully. Herewith I'm attaching android studio project files for your convenience. Open this project with android studio. I used Android Studio Arctic Fox 2020.03 Version.

What you have to do is edit the url address in MainActivity.java according to your address. My OSPOS was deployed in a local network server so my address look like as following screenshot.
![ospos ss](https://user-images.githubusercontent.com/74984654/133949397-9f10515c-a1f3-4da0-899c-2ae2a23863f2.jpg)

Please download the project file folder from following link and move this folder to (In Windows)
'/Userfolder/AndroidStudioProjects/' and open this directory with android studio. Then change the above mentioned url address according to yours and build the project and see if it works.
[https://drive.google.com/file/d/1iMQUt4LmuYDNusDRPh3_bZzmDnKoHMM9/view?usp=sharing](url)

**Comment by molomixx** [comment]
Podrías apóyarme más detallado cómo lo has hecho..

**Comment by akjanith** [comment]
> Podrías apóyarme más detallado cómo lo has hecho..

Espero que ya haya instalado pos de código abierto y que ya esté funcionando bien. Entonces debes tener Android Studio instalado en tu computadora. Luego descargue el archivo anterior desde el enlace que le he dado y extraiga esa carpeta. Luego abra esa carpeta de proyecto desde su estudio de Android. Busque el archivo relevante según mi captura de pantalla y cambie la URL de acuerdo con su instalación. Luego puedes construir la apk e instalarla en tu Android. Tenga en cuenta que esto no funcionará en ios.
