### ISSUE TITLE
Payment Summary Report

### ISSUE THREAD

**Issue by AubieBTiger** [opensourcepos/opensourcepos#2075]
**Please forgive me it this topic has been talked about!  I'm VERY NEW to Github and have a hard time seeing**

On the payment summary reports, the total Cash is coming up as amt. tendered.  I am looking for a way to change this for total of cash sales.  (Credit Cards are correct)  I run firework stand and it totalling monies recieved before making change for cash sales????/

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
no template info

**Comment by AubieBTiger** [comment]
I am sorry if I missed up, but why was it closed?

**Comment by odiea** [comment]
no template info

**Comment by SteveIreland** [comment]
It's impossible to give an accurate answer to  your question if we don't at least know what version of the system you are trying to use and it's always helpful to provide additional info.  With more info we will be able to provide a higher quality answer.  If you provide the info then we'll reopen the issue

**Comment by odiea** [comment]
The Template states the following. Maybe we should make it larger or make it blink in red.
**IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.**

**Comment by mckaygerhard** [comment]
@odiea  and @SteveIreland I say this without bad intentions, the current template and readme are somewhat ambiguous, need to be more consensual and simple, so by example:

1. just ask for php, link/docu that used for installation already provides yet many more info of installation and what configured, if the link is not official is when you need more info
2) just ask for OS gives info about the type of user, example if it comes from linux arch or alpine is sure that we can talk to it in a more advanced way, not same form others
3) asking it to look for another issue or read the README is illogical when these are also ambiguous, but if you place a friendly README without so many external links to the sources to download, it is different, so by example copy and paste the wiki INSTALL page as a install file make more sense.. 
4) make the git wiki a git-submodule as documentation it's the right way to release the info, and paste instructions to clone a git with submodule

well @odiea the template are very complicated to fill to "novice" and "windo-like click click clik" users, do you noted?
