### ISSUE TITLE
Should we celebrate the 200 open issue mark (or should we cry)?

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2076]
I choose to celebrate with a shot of Kentucky's finest Knob Creek.  :-)

**Comment by mckaygerhard** [comment]
WOW, well mayority are due we need a better readme ? i guilty about taht wiki still need some work

**Comment by daN4cat** [comment]
Ha ha ha

**Comment by WebShells** [comment]
Lol
