### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by arteiro** [opensourcepos/opensourcepos#2077]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Já a algum tempo estou tentando instalar a versão atual do OSPOS mas não estou conseguindo, estou seguindo todos os passos indicados mas não obtive sucesso.
Qual seria o problema?
Mensagem:
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php
Estou utilizando XAMPP.
Obrigado 
Xyko

**Comment by arteiro** [comment]
Already for some time I am trying to install the current version of OSPOS but I am not getting it, I am following all the indicated steps but I did not succeed.
What would be the problem?
Message:
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php
I am using XAMPP.
Thank you
Xyko

**Comment by arteiro** [comment]
Already for some time I am trying to install the current version of OSPOS but I am not getting it, I am following all the indicated steps but I did not succeed.
What would be the problem?
Message:
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php
I am using XAMPP.
Thank you
Xyko

**Comment by odiea** [comment]
You did not read the install.md. Use the following https://github.com/opensourcepos/opensourcepos/releases/download/3.2.3/opensourcepos.20180613210031.3.2.3.f1cf3d.zip

**Comment by arteiro** [comment]
Hello Odiea,
Thank you it worked.
But I read everything the site says, but I did not find any error in my procedure.
Even if it is not inconvenient, what was the mistake I made, for me to pay more attention to the next one.
Thank you
Xyko

**Comment by daN4cat** [comment]
@arteiro have you fixed the issue or no?

**Comment by arteiro** [comment]
daN4cat
"have you fixed the issue or not?"
I simply overwritten my files and it worked, but I wonder where I went wrong. Well just like that to learn.
Sorry for the inconvenience.
Thank you
XYKO

**Comment by SteveIreland** [comment]
@arteiro I'll point out that "...I am trying to install the current version of OSPOS..." doesn't really tell us what version you are installing.  It could be the current "released" version, or the current master branch, or some current feature branch.  I'm surprised someone didn't automatically close the issue.

To answer your question you didn't install a "prepared branch" .. instead you tried to install a development branch that requires a few magical incantations to transform it into installable build.

**Comment by daN4cat** [comment]
@arteiro used to help in the past with translations and some debug if my memory is right.

**Comment by arteiro** [comment]
SteveIreland - Realment was trying the wrong version, because I used to do this before, but I was out for some time and did not notice the changes; Thank you, I'll pay more attention.
daN4cat - Yes - I even completed what was missing in the translation now.
Hugs to friends.
Xyko
