### ISSUE TITLE
Vanish Items on Sales register when adding items or edit

### ISSUE THREAD

**Issue by nipunahasanka** [opensourcepos/opensourcepos#2078]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.1.1
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 5.6.37
- MySQL or MariaDB version is: 10.1.34-MariaDB
- OS and version is:  CentOS 7
- WebServer is: Apache 2.2
- Selected language is:  English
- (If applicable) Docker installation: No
- (If applicable) Installation package for the LAMP/LEMP stack is:  No

### Issue / Bug  / Question / New Feature

When adding many items to invoice or quotation (on sale register) and then if i go to other tab ( customers/supplier or etc...) or wait few minutes to  add another items or after that if edit an item suddenly vanish all added items on sales register. What is the reason for this. I have extended php session life time from 2 hours to 12 hours but there was not an effect. item vanish on sales register will happen few times on hour. Help me.
Thanks.

**Comment by daN4cat** [comment]
Have you tried the latest official release and see if that happens?

**Comment by nipunahasanka** [comment]
@SteveIreland May be as my mind. I will check that. Whats the wrong with Multiple tabs. Can we solve this a way?

**Comment by SteveIreland** [comment]
There is only one session managed per browser.  Flipping between tabs in the same browser is sort of like having one cash register and trying to have two people using the same cash register at the same time.  It's generally safe to use a second tab for researching but  doing two different transactions in the same browser is likely to result in the system losing track of where it's at

**Comment by daN4cat** [comment]
For sure you can't do two transactions in parallel from the same browser because the session is per browser and there is just the concept of one transaction per session.
