### ISSUE TITLE
Upgrading to PHP 7.2 breaks ApiGen

### ISSUE THREAD

**Issue by e18r** [opensourcepos/opensourcepos#2079]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Read the [OSPOS Environment Development](https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Environment-Development) and the [OSPOS Development Index](https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index)

### Installation information

- **PHP 7.2**
- commit hash 76c63f6a6070e075457500e7cd2394250b91c4a2
- Arch Linux

### Improvement proposal

In order to upgrade to PHP 7.2, ApiGen has to be replaced with another doc generator.

After cloning the git repository for development, the script `devinstall.sh` fails at the command `grunt gendocs`:

    $ grunt gendocs
    (node:19983) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
    Running "apigen:generate" (apigen) task
    >> The 'apigen -version' command returned the error code '255' !
    >> Please check if you have Apigen installed.
    Error: Command failed: vendor/bin/apigen --version
    ERROR: application encountered an error and can not continue. Unable to log error.

    ERROR: application encountered an error and can not continue. Unable to log error.

    Warning: Task "apigen:generate" failed. Use --force to continue.

    Aborted due to warnings.

Grunt fails when it tries to run the command `vendor/bin/apigen --version`:

    $ vendor/bin/apigen --version --debug
    
    Fatal error: Cannot use 'Object' as class name as it is reserved in /[path]/opensourcepos/vendor/latte/latte/src/Latte/Object.php on line 14
    ErrorException: Cannot use 'Object' as class name as it is reserved in /[path]/opensourcepos/vendor/latte/latte/src/Latte/Object.php:14
    Stack trace:
    #0 [internal function]: Tracy\Debugger::shutdownHandler()
    #1 {main}
    Unable to log error: Logging directory is not specified.

This is an ApiGen issue already reported here: https://github.com/ApiGen/ApiGen/issues/1039. Though this was reported back in March 2018, it is still open as of August 2018. It seems PHPMyAdmin [was facing the same issue](https://github.com/phpmyadmin/scripts/issues/11) and decided to switch to [SAMI](https://github.com/FriendsOfPHP/Sami).

**Comment by mckaygerhard** [comment]
hi, as i xpected from a real linux user, a complete filled issue, so then now :+1: +1: 

SAMI its backguard compatible? NO, it's php 7 only, so the solution are two options:

1. the devinstall script must parse the php version and choose the apigen for the docs (noted not used so much he he)
2. removed the generation of documentartion and choose a markdown generator like: https://github.com/victorjonsson/PHP-Markdown-Documentation-Generator

i think the second are more flexible and wiki/git compatible https://github.com/victorjonsson/PHP-Markdown-Documentation-Generator making less depend of VERY COMPLICATED TOOLS

**take in consideration do not choose a tool that in future can cause breaks!** that's why i proposed the https://github.com/victorjonsson/PHP-Markdown-Documentation-Generator

**Comment by daN4cat** [comment]
So when Latte fixes this we should be good?

**Comment by mopsyd** [comment]
It appears that they have an open upstream issue in Composer to address the platform declarations, however `Nette\Latte` devs indicated that dependent packages (apigen) should [upgrade to 2.4.x](https://github.com/nette/latte/issues/183#issuecomment-445728523). Perhaps prompting Apigen to do so would move this along.
