### ISSUE TITLE
Can I change SUM gift card amount & total amount and how to change it?  Thanks All!

### ISSUE THREAD

**Issue by Davidavid88** [opensourcepos/opensourcepos#2081]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.1
- OSPOS git commit hash is: 
- PHP version is: 5.5
- MySQL or MariaDB version is: 5.7
- OS and version is: window 10
- WebServer is: xampp
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
If you just want to change the name being used go to application/language select your language and the module you want to change then change those to your hearts content.

**Comment by Davidavid88** [comment]
![screenshot_2018-08-13 hgd](https://user-images.githubusercontent.com/30363407/44061603-1d0869f4-9f7f-11e8-8f96-bb80e73f9db2.png)

In the screenshot, If I added GiftCard auto deduct GiftCard amount and Total amount and Amount Tendered show deduct amount. I would like to change add GiftCard auto SUM GiftCard amount and Total amount in Amount Tendered result show sum amount.

**Comment by SteveIreland** [comment]
I'm not understanding what you are asking.  Looking at your example the amount due is 76,000 and you've applied a gift card amount of 400 which leaves a balance due of 75,600.

That all looks correct to me.

Could be a translation issue but I don't know what "add GiftCard auto SUM GiftCard amount" is.

Are you asking that the single Payment Totals row be split into totals by payment type?

**Comment by Davidavid88** [comment]
Normal is  subtract Gif Card amounts. I would like to change SUM Gif Card amounts.

**Comment by SteveIreland** [comment]
Oh, are you selling gift cards?

**Comment by Davidavid88** [comment]
No, not selling gift card. I would like to use Customer's previous due amount in gift card.  Please!
