### ISSUE TITLE
Where i can insert data from item to my table in database ?

### ISSUE THREAD

**Issue by sunsophearoth** [opensourcepos/opensourcepos#2082]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by mckaygerhard** [comment]
hi @sunsophearoth noted you are new to giuthub and to ospos, i'll take my time to explain why you pend and make garbage of the time of the people that here work very hard:

1) you seems do not read the "amount of letters" when try to open this issue right! that's the first and main reason!
2) as mayority of windoze users do not like read and just click .. please open a new issue and property fill most relevant part of, as minimun if you installed the software, the page/wiki/link used to dome that and of not, whell property explain what do you want, so see you!

**Comment by SteveIreland** [comment]
@mckaygerhard I see you are taking time again to  start with insulting Windows users.  Is it simply not possible for you to provide any assistance without denigrating someone?

In this case the ticket was closed because the question doesn't make sense in the context of OSPOS support.  Adding additional information is unnecessary.  Here it seems like a language translation issue might be the most likely problem so rewording and expanding on the question would be a better start.

But if the question is still about how to extract data from OSPOS into one of his database tables then he probably still won't get an answer.   For that he should try Google.

**Comment by mckaygerhard** [comment]
relly can be made, with a controller code that extract and put, but of course it's a ad-hoc solution @SteveIreland

**Comment by daN4cat** [comment]
@mckaygerhard any chance for you to go out for a bit and do something else? I'm pretty sure that things will be better if you take a break and focus on something not related to Internet, computer and similar.
