### ISSUE TITLE
Should Expenses and  Expense Categories be an Office Application?

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2083]
The operations menu bar is generally for sales and receiving and the office menu bar is generally for back office applications.

Should the expenses and expense category options be moved to the office menu so that is where they will be for new installations?  Obviously they can be relocated easily enough.

Does anyone other than myself care?  :-)  I just believe that it would help the main menu look a little cleaner.

**Comment by odiea** [comment]
I can see how the expense category should be placed in the back office but we expected our employees to be responsible for the money in the till. I would say keep expenses on the home menu. Just my 2 cents.

**Comment by SteveIreland** [comment]
Makes sense. Thanks

**Comment by WebShells** [comment]
Yes, that's how i use it... Categories in back office, and placements in regular menu 👍
