### ISSUE TITLE
Thousands separator interpreted as malformed number in New Expense form

### ISSUE THREAD

**Issue by emi-silva** [opensourcepos/opensourcepos#2085]
### Background information

- [x] Reporting an issue reproducible in OSPOS demo
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported.
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)

### Installation information

- OSPOS live demo at https://demo.opensourcepos.org/
- Firefox Developer Edition v. 62.0b11

### Bug

The New Expense form issues a "Amount must be a number" error when entering amounts with thousands separators. This would't be a problem, except that thousands separators are added automatically when you type. Furthermore, the amount entered is deleted when the error message appears. This might be related to https://github.com/opensourcepos/opensourcepos/issues/2018, except that in this case, it is entirely a front-end issue; the form validation mechanism in the back-end is not affected.

## Steps to reproduce

1. Log in to https://demo.opensourcepos.org/.
2. Make sure that thousands separator is enabled: go to Configuration -> Localisation, check the "Thousands Separator" checkbox and hit Submit.
3. Go to the Expenses module and hit "New Expense".
4. In Amount, write `1000` and click away. The thousands separator should be inserted automatically. This can be a little tricky to reproduce. If it doesn't happen, try clicking in and out of the Amount field, writing more zeroes, deleting them, and clicking on other fields until the thousands separator kicks in.
5. At this point, the value in the amount field should be something like `1.000`. Click on it and add an extra zero.
6. The amount entered is deleted and an error message appears: "Amount must be a number" (see image)
![ospos_error](https://user-images.githubusercontent.com/16065447/44177088-0008ce00-a0b2-11e8-9e45-7471b3f53da8.png)

7. (optional) Repeat step 4 and hit Submit. The expense is created correctly.

**Comment by jekkos** [comment]
Ok checked this one and indeed, it fails to parse the number again once formatted. Will look for a solution here

**Comment by mckaygerhard** [comment]
hi @jekkos this bugs was not fixed some time ago?

**Comment by odiea** [comment]
I have also noticed that you may have to submit the localization form twice before there is a change in saving the separator setting.

**Comment by jekkos** [comment]
related to #1694

**Comment by daN4cat** [comment]
@jekkos is this fixed?

**Comment by daN4cat** [comment]
@odiea did you test this as I see you were active in the last week or so?
