### ISSUE TITLE
Demo server down again. 

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2095]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by mckaygerhard** [comment]
wow @odiea seems was not the property solution, 

i guess we need to activated verbose loggin and have a more detailed monitoring, maybe someone that checks constantly

**Comment by WebShells** [comment]
Resetting...

**Comment by mckaygerhard** [comment]
we need to put some monitoring on, there's any posibility to be more verbose in the loggin, some commits to "discover what are happened"?

this behaviour it's like windos : problem->reseting->problem->reseting only a donkey push the same load again and again

**Comment by yangciou** [comment]
Hi,

It still doesn't work. Any ideas of when it'll be up and running again?

**Comment by WebShells** [comment]
Mmm Seems someone messed up things again after resetting...

**Comment by daN4cat** [comment]
I bet on somebody having fun...

**Comment by mckaygerhard** [comment]
ok now password cannot be changed (for all employess) 

so maybe also we need to limit module changes!

**but!:**  we also need to be more log verbose to discover what are happened!

**Comment by odiea** [comment]
I will reopen this when the issue shows up again.

**Comment by yangciou** [comment]
I'm getting 502 Bad Gateway errors.
![screenshot_1](https://user-images.githubusercontent.com/35899715/44624405-abd4c980-a8bb-11e8-8fa0-06a97d9c90ca.png)

**Comment by mckaygerhard** [comment]
any one notice this behaviour it's like windos : problem->reseting->problem->reseting only a donkey push the same load again and again

it's clear there's TWO PROBLEMS:
1. there's a problem with server implementation that results in bad gateway response!
2. there's a problem with security, we must limit the user demo, or try reseting all after logout!

**Comment by jekkos** [comment]
Ok did a reset..

**Comment by Waqas-Ali-Azhar** [comment]
Bad Gateway
502 Bad Gateway
nginx/1.10.3 (Ubuntu)

**Comment by daN4cat** [comment]
I wouldn't that the change of mariadb in docker-compose caused this. I tested locally after I built it and it was fine. I can revert that change and see if it restarts.

**Comment by jekkos** [comment]
Still some issues indeed. I have to upgrade the compose file manually so it can't be that. However it does sound like a good idea to run from the git repo instead of just pulling from docker hub. It's up again now but I need to check why it got stuck in the first place.

**Comment by odiea** [comment]
Currently it is working. Thanks

**Comment by odiea** [comment]
Bad Gateway now showing.

**Comment by Waqas-Ali-Azhar** [comment]
where is it working , can you provide url ?

**Comment by odiea** [comment]
https://demo.opensourcepos.org/

**Comment by Waqas-Ali-Azhar** [comment]
Its giving 502 Bad Gateway

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by odiea** [comment]
Great. Hope you figure out what is going on with it.

**Comment by odiea** [comment]
It is currently working. Thanks

**Comment by Waqas-Ali-Azhar** [comment]
Thanks its working 👍

**Comment by odiea** [comment]
502 Bad Gateway
nginx/1.10.3 (Ubuntu)

**Comment by odiea** [comment]
502 Bad Gateway
nginx/1.10.3 (Ubuntu)

**Comment by daN4cat** [comment]
@jekkos what's the problem between the reverse proxy server and the docker container? (I assume you have something like that as setup).

**Comment by odiea** [comment]
Server is up and I unchecked the attribute permission for Admin.

**Comment by jekkos** [comment]
for some reason the php container stops after some time, tried to retrieve logs but found nothing suspicous. So it's not due to the reverse proxy, but my guess is that something does not work well when docker hub calls the curl hook. Maybe they changed formats or so, will need to check that further.

**Comment by odiea** [comment]
502 Bad Gateway
nginx/1.10.3 (Ubuntu)

**Comment by daN4cat** [comment]
@jekkos have you updated docker engine? Not that's the cause, just a thought.

**Comment by jekkos** [comment]
No maybe I have to try that, or try to see what request docker hub is actually sending, there might be something wrong there

**Comment by odiea** [comment]
502 Bad Gateway
nginx/1.10.3 (Ubuntu)

**Comment by jekkos** [comment]
ugh, I did adapt the deplooy script a bit today, didn't seem to help apparantly.

**Comment by odiea** [comment]
Did you do anything. It is working again.

**Comment by odiea** [comment]
Unknown column 'custom1' in 'field list'

This is the error that is returned when submitting a new item.

INSERT INTO `ospos_items` (`name`, `description`, `category`, `item_type`, `stock_type`, `supplier_id`, `item_number`, `cost_price`, `unit_price`, `reorder_level`, `receiving_quantity`, `allow_alt_description`, `is_serialized`, `qty_per_pack`, `pack_name`, `low_sell_item_id`, `deleted`, `custom1`, `custom2`, `custom3`, `custom4`, `custom5`, `custom6`, `custom7`, `custom8`, `custom9`, `custom10`, `tax_category_id`) VALUES ('test', '', 'misc', '0', '0', NULL, NULL, 10, 20, 1, 1, 0, 0, 1, 'Each', -1, 0, '', '', '', '', '', '', '', '', '', '', '')

Filename: models/Item.php

Line Number: 401

**Comment by jekkos** [comment]
Hm yes seems that for some reason the sqlscript container has the attributes version in it. In fact I need to rollback those changes done to tables.sql and use the migration script only. That's one last point to test (hope so tonight)

**Comment by daN4cat** [comment]
Demo seems working now. I close.

**Comment by WebShells** [comment]
Done, allow it 5 to 10 mins please until it's complete...

**Comment by WebShells** [comment]
Should be working fine now @odiea

**Comment by daN4cat** [comment]
I bet is the usual "funny troll"

**Comment by WebShells** [comment]
I totally agree @daN4cat :/

**Comment by odiea** [comment]
Invalid user name or password. 10/9/2018 8:33am mst.

**Comment by WebShells** [comment]
That's bad... I mean what's good and very heroic job in that? Changing password? Get the server down at least idiot... Do something 🤦‍♂️

**Comment by odiea** [comment]
I wonder what happened to the password fix that was suppose to be done.
