### ISSUE TITLE
Changing Tax Code doesn't update the Customers that are attached to it.

### ISSUE THREAD

**Issue by bullmike** [opensourcepos/opensourcepos#2096]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is:  7.0.31
- MySQL or MariaDB version is: 10.3.8
- OS and version is:  CentOS Linux release 7.5.1804
- WebServer is: Server version: Apache/2.4.6 (CentOS)
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

When changing the tax code in the tax screen, the associated records are not updated.

**Comment by bullmike** [comment]
Further to this, if the tax code is modified in the tax code screen, when you pull up the receipt from the manage sales screen an error is received:

A PHP Error was encountered
Severity: Warning

Message: round() expects parameter 3 to be integer, string given

Filename: enums/Rounding_mode.php

Line Number: 73

Backtrace:

File: /var/www/html/application/models/enums/Rounding_mode.php
Line: 73
Function: round

File: /var/www/html/application/libraries/Tax_lib.php
Line: 54
Function: round_number

File: /var/www/html/application/libraries/Tax_lib.php
Line: 227
Function: get_sales_tax_for_amount

File: /var/www/html/application/libraries/Sale_lib.php
Line: 1135
Function: apply_sales_tax

File: /var/www/html/application/controllers/Sales.php
Line: 913
Function: get_taxes

File: /var/www/html/application/controllers/Sales.php
Line: 1105
Function: _load_sale_data

File: /var/www/html/public/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: round() expects parameter 3 to be integer, string given

Filename: enums/Rounding_mode.php

Line Number: 73

Backtrace:

File: /var/www/html/application/models/enums/Rounding_mode.php
Line: 73
Function: round

File: /var/www/html/application/libraries/Tax_lib.php
Line: 54
Function: round_number

File: /var/www/html/application/libraries/Tax_lib.php
Line: 227
Function: get_sales_tax_for_amount

File: /var/www/html/application/libraries/Sale_lib.php
Line: 1135
Function: apply_sales_tax

File: /var/www/html/application/libraries/Sale_lib.php
Line: 468
Function: get_taxes

File: /var/www/html/application/controllers/Sales.php
Line: 920
Function: get_totals

File: /var/www/html/application/controllers/Sales.php
Line: 1105
Function: _load_sale_data

File: /var/www/html/public/index.php
Line: 315
Function: require_once

**Comment by SteveIreland** [comment]
I'll take a look at this tonight.  But to clarify, are you specifically assigning a tax code and subsequent sales are not picking up the new tax code or are you saying that that search rules for identifying a tax code to use is failing and the adjusted tax code is not being identified?

**Comment by bullmike** [comment]
Well, I went and set up a tax code and attached it to a customer. I make a sale and the receipt shows up without issue. If I modify the 'Tax Code' field on the 'Update Sales Category Tax' screen, the Customer Associations are lost. As a result of the loss of association, the error above is displayed when trying to a sales reciept.

For Example:

I have a tax code: TC-112211
I have a customer: John Doe who is configured to use the tax code: TC-112211

If at some point I realize that I mis-typed the tax code 'TC-112211' and I adjust the tax code to something else such as 'TC-112212', the association is lost between customer John Doe and the Updated Tax code. I'm sure you can imagine,  if you had 100's of users configured how cumbersome it would be to fix this issue without a SQL query.

As a result of the disassociation, when accessing an existing sales' receipt from /public/sales/manage via the '$' (show receipt) icon, i get the error message that was pasted into the comments. However, the receipt is still displayed below the error - i suppose the error message wouldn't be an issue in 'production' mode, however, the real issue is that the association is lost on modification. 

Thanks

**Comment by SteveIreland** [comment]
Wow, yes I see the issue and it wasn't what I had in mind when I defined the tax code table.  I was thinking small shop with a handful of tax codes.  In fact, most shops that deal only with walk-in's would only have one tax code.  In my rework for India GST I considered changing it so that you could change the tax code without the negative impact you are describing but even India GST would normally require one tax code unless the company ships out of state.

Each tax code represents a collection of taxing jurisdictions for a particular destination.  So you must ship to a lot of different taxing jurisdictions.    I'll go ahead and make the changes to the tax module as part of the India GST rewrite so that it has the ability to better support your scenario.

**Comment by SteveIreland** [comment]
I believe the PHP issue is the result of tightened data-type mapping introduced with PHP 7.

Apparently you are the first person to exercise this area of the code in the new version of PHP.

I will make it compatible in the work I am doing now.  Thanks for catching it but if you need version 3.2.3 of OSPOS to work for you now then I would revert back the latest version of PHP 6..

**Comment by SteveIreland** [comment]
This is resolved in #2155

**Comment by SteveIreland** [comment]
The changes to tax configuration for India GST addressed this issue.  The tax code is now identified by a surrogate, so the code itself can be changed without needing to make a corresponding change on the customers assigned to that tax code.
