### ISSUE TITLE
Login Credentials

### ISSUE THREAD

**Issue by JohnnKay** [opensourcepos/opensourcepos#2100]
user:admin
password: pointofsale

Can't login with these credentials! (Invalid username or password)

**Comment by daN4cat** [comment]
And what about the information in the issue template that you wiped out?

**Comment by Rizs820** [comment]
Same problem persists unable to login to demo instance by using given credentials.

**Comment by mrxcell** [comment]
Does anyone knows the default user for the Venenux/OsPos live-cd installation? I´ve tried admin and root and neither works.

**Comment by mckaygerhard** [comment]
the live cd install does uses a default passowrd, i just guess its "general" without quotes

in live mode the defualt password for live user are "live" and you can set a password for root as "sudo su" then "passwd root", also in same way for live user (in current session consol of course)
