### ISSUE TITLE
Venenux/OsPos Login Credentials

### ISSUE THREAD

**Issue by mrxcell** [opensourcepos/opensourcepos#2101]
I´ve tried several installations of a virtual machine with a Venenux/OsPos Live CD ISO, i have followed every single step on the installation with the step by step instructions but i haven´t been able to log in into the virtual machine with the password i´ve configured, ill appreciatte some help on finding out what the default user name is.

Tks in advance!!!

**Comment by nerv55** [comment]
Hello, try user:general password: general

**Comment by WebShells** [comment]
Hello @mrxcell, this forum isnt available to support any other modified versions of ospos.. Place your issue under the right project please... 
Thanks

**Comment by mrxcell** [comment]
Hi WebShells im new to GitHub and dont really know how this works, thanks for the info! :)

**Comment by mckaygerhard** [comment]
hi @mrxcell generally open source project support are shared, let it and apart help it's a windoze M$ practice.. ospos it's a great efforts made by few developers, i try to made a better wiki due this kind of situations where users dont know where to go..

so when if you dont know where to go it's a good practice to READ the respective wiki for information, or search for google for related words!

you can post and ask any help in any venenux related proyect at gitlab (that it's better rather github but the interface ui are too overrhead).

i dont remenber the username, i think its general and password if you dont defined at install, its general too, there's no sudo or i dont know.. due generally when i install linux i dont reinstall ... forever, due never get crash!

**Comment by mrxcell** [comment]
Hi @mckaygerhard i really appreciatte all this info on how to get started, thanks a lot!! 👍
