### ISSUE TITLE
error: links broken due moved wiki pages

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2106]
### Background information

not related.

### Issue / Bug  / Question / New Feature

recently due some moved pages in the wiki now many links seems are dead @daN4cat as https://github.com/opensourcepos/opensourcepos/issues/2056#issuecomment-416568706 mentioned

please we can return the original name of the wiki! of course with your changes

i'm ask first to do not said i'm unresponsive now that wiki has a decent face since my effors!

**Comment by SteveIreland** [comment]
Although I had nothing to do with it, I like the current cleaner look of the Wiki (without the structural artifacts in the name).

Obviously there is still more cleanup to do and it's unfortunate that the Wiki doesn't have an automatic redirect capability, but I vote for retaining the current page names.

Broken page links are just a temporary annoyance and anyone who wants can make a tiny effort to locate the page they want.

I can block off a little time each day to look for and fix broken links.

**Comment by daN4cat** [comment]
Indeed...
