### ISSUE TITLE
Demo module image missing

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2107]
Environment: DEMO  (as of a minute ago).

![image](https://user-images.githubusercontent.com/23066623/44737705-b90ed580-aac0-11e8-9c40-c5ff03e8fa06.png)

**Comment by jekkos** [comment]
Ok that's because the db wasn't reinitialized (volume removed) after switching branches..

**Comment by jekkos** [comment]
I might need to purge all volumes as well before restart. Also I found the php container crashing from time to time, quite annoying

**Comment by jekkos** [comment]
Ok added the volume prune to the script, doing some quick validations there.
