### ISSUE TITLE
Missing customer fields?

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2111]
In the 3.2.1 migration script I see the following.

```
ALTER TABLE `ospos_customers` 
  ADD COLUMN `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `employee_id` int(10) NOT NULL,
  ADD COLUMN `consent` int(1) NOT NULL DEFAULT '0';`
```
However these fields weren't actually included in the customers table.  I'm going to go ahead and add them to the customers table as part of the India GST project but I wanted to make sure there isn't some script gaming going on.  As it is now customer maintenance will crash if I simply run the database.sql script without following it up with a migration.  I believe the latest database.sql should build a complete database without any followup database fixes.

Other opinions?

**Comment by jekkos** [comment]
HI Steve, correct. I found the same thing for expenses. It does not seem to be present in the current database.sql? Still I wonder why these tables are there when starting a fresh docker build.

**Comment by jekkos** [comment]
Ok so in config the latest migration run will be set to before the first migration script?
I know most frameworks indeed work like this, so indeed there might be no point in maintaining the two things separately.

**Comment by SteveIreland** [comment]
Okay. So philosophically we have the tables and constraints that builds a 3.0.0 database.php that is used for installation.  And then the migration that runs the first time will alter the database to bring it up to the latest point release.

I can adapt to this approach but I am not a fan of no longer having a single SQL source member that describes the database.  Fotunately I can generate one from the resulting database so that I can sleep better at night. :wink:

Thanks for the insight.

**Comment by jekkos** [comment]
@SteveIreland In terms of overview, you're right, but we could also just dumip the final result back and use that as an input for a 'full initialization'. That way we don't need to maintain both.

What you think?

**Comment by jekkos** [comment]
@SteveIreland I would suggest to have that file generated by travis-ci.

**Comment by daN4cat** [comment]
Yes CI should do
