### ISSUE TITLE
can anyone tell me that how to add Category after ITEM NAME in receipt and also print the same on receipt? Thanks in advance.... 

### ISSUE THREAD

**Issue by jackraah** [opensourcepos/opensourcepos#2113]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by SteveIreland** [comment]
Only if you can tell us what version of the software you are running which is asked for on the template you chose to ignore

**Comment by WebShells** [comment]
Tired of repeating the same thing over and over :/ 😒

**Comment by mckaygerhard** [comment]
oh @WebShells that's normally, take a chance and test users, mostly those come from? 

for those i think it's better remove the template and designate a "aswer-man".. i guess (as windo are the most deployed to those users) will never read a end this behaviour!

**Comment by jekkos** [comment]
Question is easy and clear, and so is the answer. Just add the field to the array you pass to the view in the controller, then retrieve it there. Basic CI MVC pattern.

**Comment by SteveIreland** [comment]
LOL .... I was going to give him the line of code as soon as I knew what version he was running.  But you're right.

**Comment by jekkos** [comment]
You're too kind Steve, don't really like people opening issues like that, looks a bit unprofessional and it clutters the project's issue tracker ;)
