### ISSUE TITLE
HTTP/1.1 503 Service Unavailable.', TRUE, 503); echo 'The application environment is not set correctly.

### ISSUE THREAD

**Issue by Karumaj** [opensourcepos/opensourcepos#2117]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: not sure
- PHP version is:  7.2
- MySQL or MariaDB version is: Mariadb 10
- OS and version is: Ubuntu 18.04
- WebServer is: LAMP
- Selected language is: EN
- (If applicable) Docker installation: n/a
- (If applicable) Installation package for the LAMP/LEMP stack is: n/a

### Issue / Bug  / Question / New Feature
Hl,,
I have followed the install instructions on [Local deploy](https://github.com/opensourcepos/opensourcepos/wiki/Getting-Started-installations#professional-local-install) and used the latest build on bintray (as at the time of posting this issue). [This build from bintray](https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180902011132.master.7e8558.zip)

**The issue**: I get this page full of error messages {as pasted at the bottom of this issue.}

Now,
1. I have successfully installed ospos before on another machine and I don't know if this resulted from later builds.
2. All the same, what has never been clear is how to -  and the reason behind, editing the following files   -- which has brought confusion in the installation process [I can't even retrace the edits I made to the files in my last install]
-  .htacess
-  php.ini
- config.php
- apache2.conf
----I think for database.php it's clear that I only change the file if I use another password / username

3. Suggestions for editing these files have always popped up from my solution searches on the net. There's therefore need to know the logic behind and how to do it SAFELY and EXACTLY which files ARE TO BE EDITED as we have SIMILAR file names in different folders

Please assist.

Thanks

****HTTP://LOCALHOST/PUBLIC   - OUTPUT**** 
`=')) { error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT & ~E_USER_NOTICE & ~E_USER_DEPRECATED); } else { error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_USER_NOTICE); } break; default: header('HTTP/1.1 503 Service Unavailable.', TRUE, 503); echo 'The application environment is not set correctly.'; exit(1); // EXIT_ERROR } /* *--------------------------------------------------------------- * SYSTEM DIRECTORY NAME *--------------------------------------------------------------- * * This variable must contain the name of your "system" directory. * Set the path if it is not in the same directory as this file. */ $system_path = '../vendor/codeigniter/framework/system'; /* *--------------------------------------------------------------- * APPLICATION DIRECTORY NAME *--------------------------------------------------------------- * * If you want this front controller to use a different "application" * directory than the default one you can set its name here. The directory * can also be renamed or relocated anywhere on your server. If you do, * use an absolute (full) server path. * For more info please see the user guide: * * https://codeigniter.com/user_guide/general/managing_apps.html * * NO TRAILING SLASH! */ $application_folder = '../application'; /* *--------------------------------------------------------------- * VIEW DIRECTORY NAME *--------------------------------------------------------------- * * If you want to move the view directory out of the application * directory, set the path to it here. The directory can be renamed * and relocated anywhere on your server. If blank, it will default * to the standard location inside your application directory. * If you do move this, use an absolute (full) server path. * * NO TRAILING SLASH! */ $view_folder = ''; /* * -------------------------------------------------------------------- * DEFAULT CONTROLLER * -------------------------------------------------------------------- * * Normally you will set your default controller in the routes.php file. * You can, however, force a custom routing by hard-coding a * specific controller class/function here. For most applications, you * WILL NOT set your routing here, but it's an option for those * special instances where you might want to override the standard * routing in a specific front controller that shares a common CI installation. * * IMPORTANT: If you set the routing here, NO OTHER controller will be * callable. In essence, this preference limits your application to ONE * specific controller. Leave the function name blank if you need * to call functions dynamically via the URI. * * Un-comment the $routing array below to use this feature */ // The directory name, relative to the "controllers" directory. Leave blank // if your controller is not in a sub-directory within the "controllers" one // $routing['directory'] = ''; // The controller class file name. Example: mycontroller // $routing['controller'] = ''; // The controller function you wish to be called. // $routing['function'] = ''; /* * ------------------------------------------------------------------- * CUSTOM CONFIG VALUES * ------------------------------------------------------------------- * * The $assign_to_config array below will be passed dynamically to the * config class when initialized. This allows you to set custom config * items or override any default config values found in the config.php file. * This can be handy as it permits you to share one application between * multiple front controller files, with each file containing different * config values. * * Un-comment the $assign_to_config array below to use this feature */ // $assign_to_config['name_of_config_item'] = 'value of config item'; // -------------------------------------------------------------------- // END OF USER CONFIGURABLE SETTINGS. DO NOT EDIT BELOW THIS LINE // -------------------------------------------------------------------- /* * --------------------------------------------------------------- * Resolve the system path for increased reliability * --------------------------------------------------------------- */ // Set the current directory correctly for CLI requests if (defined('STDIN')) { chdir(dirname(__FILE__)); } if (($_temp = realpath($system_path)) !== FALSE) { $system_path = $_temp.DIRECTORY_SEPARATOR; } else { // Ensure there's a trailing slash $system_path = strtr( rtrim($system_path, '/\\'), '/\\', DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR ).DIRECTORY_SEPARATOR; } // Is the system path correct? if ( ! is_dir($system_path)) { header('HTTP/1.1 503 Service Unavailable.', TRUE, 503); echo 'Your system folder path does not appear to be set correctly. Please open the following file and correct this: '.pathinfo(__FILE__, PATHINFO_BASENAME); exit(3); // EXIT_CONFIG } /* * ------------------------------------------------------------------- * Now that we know the path, set the main path constants * ------------------------------------------------------------------- */ // The name of THIS file define('SELF', pathinfo(__FILE__, PATHINFO_BASENAME)); // Path to the system directory define('BASEPATH', $system_path); // Path to the front controller (this file) directory define('FCPATH', dirname(__FILE__).DIRECTORY_SEPARATOR); // Name of the "system" directory define('SYSDIR', basename(BASEPATH)); // The path to the "application" directory if (is_dir($application_folder)) { if (($_temp = realpath($application_folder)) !== FALSE) { $application_folder = $_temp; } else { $application_folder = strtr( rtrim($application_folder, '/\\'), '/\\', DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR ); } } elseif (is_dir(BASEPATH.$application_folder.DIRECTORY_SEPARATOR)) { $application_folder = BASEPATH.strtr( trim($application_folder, '/\\'), '/\\', DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR ); } else { header('HTTP/1.1 503 Service Unavailable.', TRUE, 503); echo 'Your application folder path does not appear to be set correctly. Please open the following file and correct this: '.SELF; exit(3); // EXIT_CONFIG } define('APPPATH', $application_folder.DIRECTORY_SEPARATOR); // The path to the "views" directory if ( ! isset($view_folder[0]) && is_dir(APPPATH.'views'.DIRECTORY_SEPARATOR)) { $view_folder = APPPATH.'views'; } elseif (is_dir($view_folder)) { if (($_temp = realpath($view_folder)) !== FALSE) { $view_folder = $_temp; } else { $view_folder = strtr( rtrim($view_folder, '/\\'), '/\\', DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR ); } } elseif (is_dir(APPPATH.$view_folder.DIRECTORY_SEPARATOR)) { $view_folder = APPPATH.strtr( trim($view_folder, '/\\'), '/\\', DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR ); } else { header('HTTP/1.1 503 Service Unavailable.', TRUE, 503); echo 'Your view folder path does not appear to be set correctly. Please open the following file and correct this: '.SELF; exit(3); // EXIT_CONFIG } define('VIEWPATH', $view_folder.DIRECTORY_SEPARATOR); /* * -------------------------------------------------------------------- * LOAD THE BOOTSTRAP FILE * -------------------------------------------------------------------- * * And away we go... */ require_once BASEPATH.'core/CodeIgniter.php'; `

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by daN4cat** [comment]
Beside the fact that your config looks having something missing, which version are you using 3.2.3 or the one in development 3.3.0?
PHP 7.2 came out after 3.2.3 so not sure it's all fine. I know 3.3.0 is because I tested it.

**Comment by daN4cat** [comment]
WRT your question I'll reply later because it requires time that I don't have until this evening.

**Comment by jekkos** [comment]
From what I see here this is an apache config issue (it does not pick up .php file but just renders it to the browser). Maybe check howto set correct mimetype for .php files and fastcgi wrapper to execute the mimetype.

**Comment by Karumaj** [comment]
@daN4cat This is the version from bintray: https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180902011132.master.7e8558.zip . It's version 3.3.x. I'm waiting for your input

@jekkos This could definitely be the issue I am experiencing with the build. But honestly this is a bit too techy.. I will need to dig deep and maybe too long to get this right - although I will have to learn eventually. Please make it a bit simple now on how  need to "to set correct mimetype for .php files and fastcgi wrapper to execute the mimetype". Does this have to do with the editing of .htacess, php.ini, config.php and apache2.conf files as appearing in net searches? Please send some light on this too. Thanks

**Comment by jekkos** [comment]
@Karumaj what do you use to run php scripts? fastcgi or php_mod?
 Check https://stackoverflow.com/questions/2712825/what-is-mod-php for more info.

yes indeed I think in this case you will need to modify apache2.conf

**Comment by Karumaj** [comment]
I have tried with the latest release on bintray released about 11 hour ago but the issue persists.
Even `gedit  /etc/apache2/apache.conf` did not help. My change here was from this default:

`<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>`

where I had changed   third line to:   `AllowOverride All`

**Comment by jekkos** [comment]
It's funny because I was trying to setup an install using apache as well this saturday but failed with this same issue. Tried using fgcid but for some reason apache didn't pickup my config file changes (as I set a handler for php mimetype etc)

**Comment by jekkos** [comment]
can you try to enable phpinfo in some way? If that doesn't work then it's probably not working due to a wrong php installation and I would try to reinstall the packages .
Maybe start with that first in a document root
`<? php echo phpinfo(); ?> and then open that file see if it renders

**Comment by mckaygerhard** [comment]
hi all @jekkos  and @Karumaj seems in recent apache2 and linuxes some things have changed.. i could try a test at the weekend and report some feedback..

as note @jekkos if we do not use direct files in www-root we must use a aliasing.. seems you both does not use alliasing and does not defined a alias place..

**Comment by mckaygerhard** [comment]
hi all @jekkos and @Karumaj seems in recent apache2 and linuxes some things have changed.. i could try a test at the weekend and report some feedback..

as note @jekkos if we do not use direct files in www-root we must use a aliasing.. seems you both does not use alliasing and does not defined a alias place.., professional installation need a very detailes wiki page and due the recent "behaviour" of some member maybe never be, and we have a lot of issues again (do you noted that issues was low trafic since we have a decent wiki @jekkos ?)

**Comment by Karumaj** [comment]
Hi all, 
From various solution searches php installation has not been ok as info,php file could not bring anything on the browser. I tried this first step  from search on how to install php on Ubuntu 18.04
 `sudo apt install php libapache2-mod-php`
 and public/info.php and ospos worked !!

My environment before this step:
-Clean updated Ubuntu 18.04
-All other steps on ospos install "local deploy"
-build in wget step == latest bintray as at time of post

I think you can now tell where/why my installation had issues

Regards.

**Comment by mckaygerhard** [comment]
i dont use winbuntu but i think it's not your instalation.. mayority of cases are little mistakes, nobody are expert.. right now i'm very busy but i promise that i'll look and take a rst arount monday and write a good "professional install"

take in consideration reading about: rewrite, aliasing, permission and the www-data user and mysql.. meantime i do that..

@Karumaj  one of my targets are configure/code  and document a more easy way to do all of these things

**Comment by odiea** [comment]
@Karumaj  Thanks for the great tip.

**Comment by odiea** [comment]
It appears that you are trying to use the development version and not the following bintray version. Please try the following.
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20180909114915.master.d8cb0d.zip

**Comment by mckaygerhard** [comment]
thermal printers use raw format print.. you can discuss with me that due i susessfull work with termal printers..  obviously you should talk with people that have the devices, rest of people only will confuse!

so i give you that https://github.com/IntegersOfK/Hoin-POS-58-80

ah if you need further information can post at my repository too

**Comment by mckaygerhard** [comment]
@Karumaj  thermal printers use raw format print.. you can discuss with me that due i susessfull work with termal printers..  obviously you should talk with people that have the devices, rest of people only will confuse!

so i give you that https://github.com/IntegersOfK/Hoin-POS-58-80

ah if you need further information can post at my repository too

**Comment by Karumaj** [comment]
Thanks but the readme.md doest not give clear installation guide for github amateurs  like me

**Comment by mckaygerhard** [comment]
umm, seems you need more reading about cups. i not remenber how to setup property, but it's working i can ask if there's one at deposit and become testing with you, post at my repository

**Comment by Karumaj** [comment]
Hi @mckaygerhard , have really tried (many tries) to figure out how to post on your repo to no avail. I think the only relevant link is creating an issue which brings me back here. Found no way to create it from your repo. This could be trivial but I'm just learning.....

**Comment by mckaygerhard** [comment]
i not have repo in github (onoy a mirror), was on gitlab! ah cups must be lower than 2.X so recent linuxes seems do not work

**Comment by Karumaj** [comment]
What would be the best option in this case

**Comment by odiea** [comment]
As far as Linux goes this is all I have to offer. I am not a Linux user.
http://www.openprinting.org/drivers

**Comment by Karumaj** [comment]
Ok will try. What's the link for gitlab?

**Comment by mckaygerhard** [comment]
the openprinting link only have precompiled in their page and does not support that printer!, and the CUPS are not linux are MAC software ported to linux, @Karumaj recent cups seem does not work, i recently try to recompiled in alpine and debian 9 and does not work, my working printer+machine are a Debian 6 squeeze (10 yeasr working, i do not touch right now), maybe tomorrow i report some feedback at my gitlab repo, but you need lot of patiente..

**Comment by odiea** [comment]
Ah The trials and tribulations of a Linux only user.

**Comment by daN4cat** [comment]
Cups works on Ubuntu  (debian based) Linux. It's used tens of times a day to print receipts on my wife's shop.

**Comment by daN4cat** [comment]
And it's a thermal printer.

**Comment by odiea** [comment]
You mean WinBuntu?

**Comment by mckaygerhard** [comment]
no i refers that cups must be older to compile the filter, and due there's more expert here maybe thei can work on! maybe call->restart->try!

**Comment by daN4cat** [comment]
Man, here we provide support for OSPOS, not how to install linux from scratch. We were at the stage that neither php was installed....

Let's close and please search some linux forum about how to install printers.
