### ISSUE TITLE
Where is database.sql for a new install?

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2121]
Dowload the latest stable release from github or unstable build from bintray. A regular repository clone will not work unless you are brave enough to build the whole project!
    Create/locate a new mysql database to install open source point of sale into
    Execute the file database/database.sql to create the tables needed
    unzip and upload Open Source Point of Sale files to web server
    Modify application/config/database.php and modify credentials if needed to connect to your database
    Modify application/config/config.php encryption key with your own
    Go to your point of sale install public dir via the browser
    LOGIN using

    username: admin
    password: pointofsale

![2018-09-04 12_34_48-window](https://user-images.githubusercontent.com/10962177/45050622-ff26e480-b03e-11e8-8f33-9977399d7a57.png)

**Comment by SteveIreland** [comment]
database.sql is generated from combining tables.sql and constraints.sql.

It is built during the grunt execution step.

After grunt it will be found in the database folder.

**Comment by SteveIreland** [comment]
@daN4cat had to remove it from the repository because I kept wanting to change it,

**Comment by odiea** [comment]
I found I was looking in the master repository and not the bintray. I will close this issue. Thanks

**Comment by daN4cat** [comment]
@SteveIreland you are a busy man, I wanted to save your time and my time as well during the reviews :-)
