### ISSUE TITLE
Sell some items only

### ISSUE THREAD

**Issue by w002qaa** [opensourcepos/opensourcepos#2129]
Hello

I am going to install OSPOS on Customs Clearance office. I want to make the sales auto load the those few items, and the employee just enter the price for each item. 

I don't want the employee to search for the items

How I can do that?
^_^

**Comment by WebShells** [comment]
Hello, can be solved by item kits... Preload list of items and can edit quantities/prices...

**Comment by SteveIreland** [comment]
This person hasn't followed up with any clarification so I'm assuming this issue can be closed.

I would want to know how the items to be auto-loaded are identified.  I originally thought they would need to be imported from some external app.

**Comment by WebShells** [comment]
Agree... Until we get an answer...

**Comment by w002qaa** [comment]
Sorry @SteveIreland  
I did follow up with this issue. But I did not write any comment. I got @WebShells answer, and that what I was looking.

Thanks for your support ❤

**Comment by SteveIreland** [comment]
Good job @WebShells!  I was way off target in my guess at what was being requested.
