### ISSUE TITLE
OSPOS crashed SQLscript / weaveworks

### ISSUE THREAD

**Issue by crzdcarney** [opensourcepos/opensourcepos#2130]
OSPOS has crashed and I cannot get it back online.

When I check the dockers these 2 instantly crash:

`jekkos/opensourcepos:sqlscript          "bash"                   6 months ago        Exited (0) 25 seconds ago                            sqlscript-1.opensourcepos.2ee42b0d`

`weaveworks/weaveexec:1.6.2              "/bin/false"             14 months ago       Exited (1) 2 seconds ago                             weavevolumes-1.6.2`

I am not sure where to begin to troubleshoot this.  I am simply trying to recover some of the sales records.  Is there a way to dump the DB info so sift through it or do a reinstall or upgrade?

I am fairly new to linux.

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by SteveIreland** [comment]
Is there a reason you don't want to provide the version of OSPOS you are trying to install and the version you are trying to migrate from?

**Comment by jekkos** [comment]
@crzdcarney the docker cloud environment is end of life currently. You should login to your droplet and there you'll find the docker containers running (or stopped in this case). Problem is that now there is no frontend controlling it, so in case it goes down it stays down.

Also I changed the docker-compose to reflect this situation now (sqlscript had a separate container because of docker cloud).

The mysql data should be in a docker volume, best to extract it from there and then do a native cloud install (check the wiki for that one)

See also #1939

**Comment by crzdcarney** [comment]
Awesome, thank you.  I spun up a Ubuntu server VM.  I will migrate the data to that.

**Comment by crzdcarney** [comment]
Stupid question, how do i identify what DB version this is so it upgrades properly?

**Comment by daN4cat** [comment]
Do you see an ospos_migration table? If yes, what's the value you read from the only entry?

**Comment by crzdcarney** [comment]
20180217100000

That is he only entry.

**Comment by daN4cat** [comment]
OK, look like being vs 3.2.0.
You don't need to worry about database upgrades, that since vs 3.0.0.

**Comment by crzdcarney** [comment]
YAY i have OSPOS up and running again.  Should Istart a new thread for this next question:

I dumped all of the DB info, so I have SQL files and txt files for the tables.  How do i import all of the txt files into the tables?

**Comment by daN4cat** [comment]
What about reusing a copy of the old database with the new ospos installation?

**Comment by crzdcarney** [comment]
So I can go through the usual setup and just copy over the old database.sql file instead of the default?   If that is the case, I will try it today.

**Comment by jekkos** [comment]
yep that will be easiest, extract sql using mysqldump and load it into another db /schema

**Comment by jekkos** [comment]
No more activity here, will close.
