### ISSUE TITLE
Modal edit box does not work after visibility toggle

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2132]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: latest master
- PHP version is: 5.6
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: apache 2.4
- Selected language is: english
- (If applicable) Docker installation: YES

### Issue / Bug  / Question / New Feature
Toggle visibiliy of a column. Then click edit on any row. Seems that javascript is not working properly in that case.f

**Comment by daN4cat** [comment]
@jekkos is this fixed?

**Comment by jekkos** [comment]
No, just did a quick test and the issue is still there. Will need to find the time to look at it.

**Comment by jekkos** [comment]
Also observed: no table refresh after saving a bulk edit. Also modal is broken if no refresh.

**Comment by jekkos** [comment]
Ok seems that the bootstrap tables extension is reinitializing the whole table, this discards the click event handlers that are bound to the edit items..

**Comment by jekkos** [comment]
Did a fix for this one, can be validated.
