### ISSUE TITLE
Bintray downloads not working. Response is Forbidden

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2133]
With the flurry of today's commits all I get when trying to download the unstable builds is Forbidden

**Comment by jekkos** [comment]
Yes I have gotten a message from them yesterday saying that they temporarily disabled our account due to overuse. Checked some stats last week and it didn't seem all that excessive, on average 10 -14 downloads a day for our latest unstable build. Awaiting their reply now.

**Comment by daN4cat** [comment]
Time for a break.

**Comment by jekkos** [comment]
> Dear Jeroen,
> 
> 
> We would like to acknowledge that we have received your request and a ticket has been created with ticket ID - 89386.
> 
> A support representative will be reviewing your request and will send you a personal response.
> 
> 
> If your subscription does not include customer support services or a SLA-based response time, please anticipate a delayed respons

**Comment by odiea** [comment]
@jekkos Thanks for the update. Hope they can fix the issue.

**Comment by mckaygerhard** [comment]
> LOL ... the perils of open source.

it's not so bad! and it's logical! download service are for proyects and when clients download are out of limits, there's no more "open source", becomes to like to "bussiness" and that need be paid

**Comment by jekkos** [comment]
https://bintray.com/jekkos/opensourcepos/opensourcepos/3.3.0#statistics
https://bintray.com/jekkos/opensourcepos/opensourcepos/3.2.3#statistics

**Comment by SteveIreland** [comment]
Hopefully those are just "repeat users" that are testing each new merge.

If they are using 3.3 for production purposes then I hope they have a bit of understanding of SQL when they finally need to upgrade to a subsequent final release,

**Comment by SteveIreland** [comment]
The limits are 
* 1TB/m downloads
* 10GB/m storage

Is the problem with total storage because there isn't any way that we've hit a 1TB per month download.  (Or am I reading that wrong?)

**Comment by jekkos** [comment]
Yes it must be that.. maybe we can enable it by deleting older builds then

**Comment by jekkos** [comment]
Indeed bintray replied. We're using too much stolrage. I'll have to remove some older builds. But they did re enable our account for the time being.

**Comment by odiea** [comment]
Delete everything over 1 1/2 years old? Currently still not working.

**Comment by WebShells** [comment]
Is there any need for a full backup? Just for records? @jekkos

**Comment by SteveIreland** [comment]
I wouldn't think so since the change history is reflected in git.

I would think we would only need the zip for each published release although I would hate to ever need to help someone with a 2.x release.  My answer would be upgrade to the latest release and call me in the morning.

**Comment by daN4cat** [comment]
The release zip are saved in GitHub under each release already.

Flush bintray completely and bump GitHub master to produce the latest zip.
We don't need to go back in time.

**Comment by jekkos** [comment]
I removed quite some artifacts from it, however it's still rate limited. I'll send a message to bintray so they can enable it again

**Comment by odiea** [comment]
Still down 9/18.

**Comment by jekkos** [comment]
Pinged them again this morning, hope they will unblock soon.

**Comment by odiea** [comment]
Still down 9/20.

**Comment by jekkos** [comment]
For some reason they forwarded my request to a service manager internally. Seems like they want to sell some extra storage (instead of just unblocking the account)

**Comment by odiea** [comment]
9/21 SOS. Someday they will help out to fix this issue?

**Comment by jekkos** [comment]
OK sent another mail to ask them to disable the rate limitation. If that doesn't help I'll consider creating a new account and just update the api key

**Comment by jekkos** [comment]
Should be fixed now

**Comment by odiea** [comment]
Now we just need something worth down loading.

**Comment by odiea** [comment]
Works again this A.M.. Closing this issue.
