### ISSUE TITLE
Proposition 

### ISSUE THREAD

**Issue by tekkeur** [opensourcepos/opensourcepos#2134]
Hello, and congratulations for your project, it's TOP, really TOP.
I have a proposal of a feature interesting to integrate on this application.

Infact, I have a shop selling computer equipment (laptop, HDD, printer, ...) if our client is a company their payment method is sometimes 2 weeks, or 1 month after the purchase of the items and sometimes by transfer bank or by check. That is to say, the customer is given the items he buys with an invoice containing the amount to be paid even if the payment has not yet done, and the items sold will be deducted in the stock.

And that I propose to integrate on your application if it is possible.
A type of sale with a subsequent payment and with the possibility to see the lists of sales or invoices that are not yet paid,

Thenks

**Comment by daN4cat** [comment]
The payment is called due, and it's already implemented. Check the demo web site.

Some people suggested to add more on that and we are waiting for somebody to contribute those additions.

**Comment by SteveIreland** [comment]
Yes, there is already an invoice document type that allows the sale to be "complete" without payment or with only partial payment. A subsequent payment tracking mechanism would be nice - even if it's not a full receivables management system.

**Comment by tekkeur** [comment]
@mckaygerhard 
can I test yours?

**Comment by mckaygerhard** [comment]
i need your private mail so for find, propose a file change in my repo here: https://github.com/mckaygerhard/xmpp and when i clone i can see your mail, or if you have a better way to show your mail to me without paste public here, maybe at my linkedin or at my blog

**Comment by mckaygerhard** [comment]
hi @tekkeur i need your private mail so for find, propose a file change in my repo here: https://github.com/mckaygerhard/xmpp and when i clone i can see your mail, or if you have a better way to show your mail to me without paste public here, maybe at my linkedin or at my blog

**Comment by mckaygerhard** [comment]
i send to you a invitation to the repo, so then acept and then make  a file change, after that i can see your mail to send you a link in private

**Comment by tekkeur** [comment]
@mckaygerhard  
lova.tna@zoho.com

**Comment by odiea** [comment]
Disclaimer: Any branches from This member will not be supported by OSPOS. Use at your own risk.

**Comment by mckaygerhard** [comment]
@odiea i not have branched any, in only setup a private install at my home and share to other.. that are the sin here? puff! alfter that, others can take ideas and code something for opensourcepos.. open your mind right?

**Comment by WebShells** [comment]
@mckaygerhard i already mentioned before not to spam/invite to projects not related to OSPOS on the issues list... Hopefully it's the last... The last warning too...
