### ISSUE TITLE
CSS and JS not working when you installa inside subfolder

### ISSUE THREAD

**Issue by son1cman** [opensourcepos/opensourcepos#2136]
I know this is a .htaccess and base_url issue but honestly i cant make this thing work if i put inside of a sub folder, im trying to install here: scrltsolutions.com/z/pos/ i have changed everything and js and css still doesnt work...

**Comment by daN4cat** [comment]
Obvious question, which version and where did you downloaded it from?

Also where are you running this ospos? Local machine, webhost, linux, windows?

It's frustrating too to guess many things...

**Comment by mckaygerhard** [comment]
as i suggested previously, we need a more flexible and usable way of instalation, many hosting providers dont allow htaccess rules, resulting in a unnusable instalation.. try firts locally and if worked then move all the files to your host

**Comment by son1cman** [comment]
Its insane the ammount of tickets talking about this very topic!!! but it seems all got the same treatment..  it just doesnt work on production... and my ticket its close so good luck for me.

**Comment by mckaygerhard** [comment]
take care @son1cman for sure will someone said "there' no , there's a liar"

**Comment by odiea** [comment]
Maybe if he provided any information on his installation he might have gotten a little more help. I am no tech guy but it appears to be root/sub-directory/sub-directory. The first sub-directory appears to work.

**Comment by mckaygerhard** [comment]
well @odiea that sound better rather past comments!

**Comment by mckaygerhard** [comment]
well @odiea that sound better rather you past comments!, but not! with a simpel index.php redirect all problems gone

**Comment by son1cman** [comment]
i donwloaded from here: https://github.com/opensourcepos/opensourcepos/releases   version 3.2.3
1) the only .htaccess that i need to modify is the one inside public forlder right?
2) database connection its all set.

what kind of information do you need? full path: /home/son1cman/public_html/scrltsolutions.com/z/ps/public/index.php
but i only need to star from here: public_html/scrltsolutions.com/z/ps/public/index.php since all my other codeigniter projects needs only that
its business hosting on godaddy, htaccess and all permisions are set, this is the very first project im having this issue.

**Comment by mckaygerhard** [comment]
ok nly need to modify relative paths not absolute! full path are not necesary

**Comment by son1cman** [comment]
i know i was only trying to show my folder structure this is my .htaccess
# if in web root
# RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
 RewriteRule ^(.*)$ /z/ps/public/index.php?/$1 [L]

**Comment by mckaygerhard** [comment]
ok nly need to modify relative paths not absolute! full path are not necesary

> this is the very first project im having this issue.

all the others have directly "Application" directory exposed, this make some tricks to use "public" as entry point due "some security" behaviour.. just in hataccess see that the rewrite rule said somethign about "subgdirectory"

**Comment by mckaygerhard** [comment]
ok @son1cman i recomended use a index.php like that and put directly in your opensourcepost root : 

``` php

<?php 
header('Location: public/index.php', true, 301);
die();
?>
```

**Comment by odiea** [comment]
http://scrltsolutions.com/z/ps/public/home works just fine on my end.

**Comment by odiea** [comment]
This was your original post for the site. scrltsolutions.com/z/pos/

**Comment by son1cman** [comment]
nahhh but i speak spanish ... where you guys come from? btw... **IT WORK**!!! but let me check every module on the menu...

**Comment by odiea** [comment]
Why. It is working now?

**Comment by son1cman** [comment]
i cant add new costumer and item kit... the modal forms seems to be empty  
![image](https://user-images.githubusercontent.com/6058362/45435814-935fff80-b66e-11e8-9919-8ee691920d74.png)

other modules since to work fine.

**Comment by son1cman** [comment]
you can close this issues since its now working.. i think i will search for this modal form issue... the problem was my .htaccess and folder permisions for a new folder i just created.

**Comment by odiea** [comment]
Just make sure you are using the correct database.

**Comment by mckaygerhard** [comment]
hi @son1cman of course works, i done in my respository and works for spanish speking users, if you need furter beter assistenace go to that and we can speak in spanish

**Comment by mckaygerhard** [comment]
and @son1cman  the modal form has a problem solved in last dais.. that's why its not working in your setup

**Comment by son1cman** [comment]
@mckaygerhard how can i get the patch for this issue? since i not allow to just clone from master.... last stable version was released january 13...

**Comment by mckaygerhard** [comment]
unless the official ospos, my repository has all in the master.. so you can clone and setup easyle, use the production brand.. manny users do same but seems ospos developers dont noted it!

**Comment by odiea** [comment]
Recheck your database. Use tjhe one from 3.2.3. It should not be showing cashups. That was not introduced until recently 3.3.0.

**Comment by WebShells** [comment]
> hi @son1cman of course works, i done in my respository and works for spanish speking users, if you need furter beter assistenace go to that and we can speak in spanish

@mckaygerhard can you stop redirecting/inviting users please?

**Comment by odiea** [comment]
Change your database. Practice with it then wait for the bintray version to become available. The database will  automatically upgrade with the new version then you just have to replace the code with the bintray version.

**Comment by odiea** [comment]
I downloaded and installed 3.2.3. Had no issues using the supplied database. I will close this now

**Comment by daN4cat** [comment]
To be honest, with all these comments pointing to all the directions I'm not sure I got what the problem and how it got solved.
