### ISSUE TITLE
404 Not Found after entering login details

### ISSUE THREAD

**Issue by evadavevadave** [opensourcepos/opensourcepos#2137]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: PHP Version 7.2.7-0ubuntu0.18.04.2
- MySQL or MariaDB version is: MySQL 5.7.23-0ubuntu0.18.04.1 - (Ubuntu)
- OS and version is: ubuntu server 18.04.1 LTS
- WebServer is: https://recordcollectors.net/
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: Ubuntu, Apache 2, MySQL
- followed this tutorial when setting up LAMP: https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-ubuntu-18-04
- followed virtual hosts tutorial after setting up LAMP server: https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-16-04
- followed this tutorial to setup SSL: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-18-04
 

### Issue / Bug  / Question / New Feature

I am definitely missing something.  I have followed the installation and able to get to the login page.  It fails from there with a 404 error. 

I have modified .htaccess in the public folder. 

I have modified the home directory as per instructions
DocumentRoot /var/www/recordcollectors.net/html/public

edited .htaccess file in /public
RewriteEngine On

# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
# RewriteCond %{HTTP_HOST} ^<OSPOS subdomain>\.<my web domain>\.com$ [OR]
# RewriteCond %{HTTP_HOST} ^www\.<OSPOS subdomain>\.<my web domain>\.com$
# RewriteRule ^/?$ "https\:\/\/www\.<my web domain>\.com\/<OSPOS path>" [R=301,L]

# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
# RewriteCond %{HTTPS} !=on
# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
# RewriteCond %{HTTP_HOST} (.+)$ [NC]
# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# if in web root
# RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
RewriteRule ^(.*)$ /var/www/recordcollectors.net/html/public/index.php?/$1 [L]

- I can login to myphpadmin and able to upload db
- I have been able to use this server in its current form for the past few months and run two sites running, able to be accessed
- Any help will be appreciated.

Cheers

**Comment by odiea** [comment]
As per issue #920
I was having a similar issue after upgrading to ubuntu server 18.04 and the following fixed my issue.

    sudo a2enmod rewrite
    edit /etc/apache2/apache2.conf

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

    sudo systemctl restart apache2

**Comment by evadavevadave** [comment]
@odiea  Thank you for sending me back to the article. The amount of times I looked at that article and just kept missing  the AllowOverride info.  

Something else is broken but please close this ticket


> As per issue #920
> I was having a similar issue after upgrading to ubuntu server 18.04 and the following fixed my issue.
> 
> ```
> sudo a2enmod rewrite
> edit /etc/apache2/apache2.conf
> ```
> 
> <Directory /var/www/>
> Options Indexes FollowSymLinks
> AllowOverride All
> Require all granted
> 
> ```
> sudo systemctl restart apache2
> ```
