### ISSUE TITLE
Database.sql is missing from database folder

### ISSUE THREAD

**Issue by zegysukmawan** [opensourcepos/opensourcepos#2141]
As the local install tutorial said it was in database folder but i can't find it anywhere. Thanks

**Comment by daN4cat** [comment]
Please download the release version or for current development the one from bintray. Read the Install.md.
If you download from GitHub you get a development view that requires a build step.

**Comment by rmoff** [comment]
Just to +1 that I hit this issue, following the instructions at https://hub.docker.com/r/jekkos/opensourcepos/ "Local install". Maybe these instructions can point out to d/l a release version and not just close the repo?

**Comment by mckaygerhard** [comment]
wow, that instruction are very vage right?
