### ISSUE TITLE
question: how are the database develop process

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2145]
ok, i can see the scripts and see that the final database.sql file are build from those files.. 

but, how differents developers are made to take in considerations the others and join the tables does not conflict.. 

i mean: how you guys made the database develop process!? so other we can contribute and make better effors:

PD: i make this question so all other users and me included do not ask later or in middle of a issue/pull ok?

**Comment by SteveIreland** [comment]
You must become one with the conflicts.   Conflicts must be embraced as the single truth of life itself.

Only when this is accomplished can a developer truly be at peace with himself.

**Comment by mckaygerhard** [comment]
¬_¬ yeah yoda! but ok mysqlworkbech are not used for the git commits right?

**Comment by SteveIreland** [comment]
I think it's safe to say that everyone uses the tools they are comfortable with.  I use SQL Workbench professionally, but I do not use it for OSPOS support since PHPMyAdmin does everything I need it to do and it is convenient since it is installed and enabled by WAMP.

**Comment by mckaygerhard** [comment]
sorry i not explicit my question very well, i can see that (reading) the database.sql are build using other sql files.. how made that without confilcts, or all the sync are made only using the git issue and pull comments as those days?

**Comment by mckaygerhard** [comment]
or in other works, if i try to improve my contribution from my fork (i have a extra table that setuop fiscal printers) how integrate sql or database changes, whic started point, where are the files to touch first?

**Comment by daN4cat** [comment]
If you don't have control of what you changed or a means to spot the difference then it's not a problem of tools but a problem in the way you work.

**Comment by mckaygerhard** [comment]
@daN4cat do not read my last response, or in other works, if i try to improve my contribution from my fork (i have a extra table that setuop fiscal printers) how integrate sql or database changes, whic started point, where are the files to touch first? 

i mean where i shoudl start here if i want to work with database.. hey i ask to steps to start to work.. of course all of you as community must guide other to works as dessire, or do not want ?

can just said "i dont care" and issues with people asking things will come more obviously!

**Comment by mckaygerhard** [comment]
as example quiestions like #2147 are happened (and will happened forever) due i cannot complete the wiki information and the readme does not point to any information page! that's why i ask for official information. of course do what do you want guys but i make sense... thanks for nothing information!

**Comment by SteveIreland** [comment]
The database.sql (tables.sql + constraints.sql) defines the 3.0 version of the database.  Then the migration scripts upgrade it to the the current release.  So any database changes you make will need to be incorporated in the migration scripts.

Hmmm.   Apparently you decided to close this issue while I was typing this

**Comment by WebShells** [comment]
Lol !

**Comment by SteveIreland** [comment]
No comment.
Yes, 
Yes, 
You would include the new table definition in the migration script.  Yes, the quality of the table definition has to be approved by the development community.  Crap is not acceptable.

**Comment by mckaygerhard** [comment]
great! first issue answered for novices! very very thanks @SteveIreland glad to close it!

**Comment by daN4cat** [comment]
If you check what was submitted as PR for the discount % / amount you would have an answer.

That should guide you, just go back in Github history.
