### ISSUE TITLE
Missing language mapping hook

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2148]
I'm sure I'll be embarrassed about something I'm overlooking but I just extracted and rebuilt from the master code branch and for some reason I'm not getting the language mapping.  I'm going to chase this down, but if someone has a clue they can share with me I'd appreciate it.

This is after ...
* composer install
* npm install
* grunt --force

![image](https://user-images.githubusercontent.com/23066623/45788813-bc722880-bc4a-11e8-99d6-7ce93397c27d.png)

**Comment by SteveIreland** [comment]
I discovered the issue goes away when I navigate to config and change the language to english..  Very odd since I know the database.sql is setting the value to english.

**Comment by SteveIreland** [comment]
This is what I see when I go into locale config after a fresh install.  However, the language config setting is showing "english".  More research is needed.

![image](https://user-images.githubusercontent.com/23066623/45789656-c5fd8f80-bc4e-11e8-97ee-4eb9063b400c.png)

**Comment by SteveIreland** [comment]
Okay, the language_code system value is created with an default value of en-US in tables, but the deleted in a migration script 3.0.2_to_3.1.1.sql

That's the problem.

Does anyone know why?

**Comment by SteveIreland** [comment]
Did you intend `"%\_%"` instead of `"%_%"` ?

**Comment by daN4cat** [comment]
If it was deleted then the latest migration script needs to fix it.

**Comment by SteveIreland** [comment]
I don't think that would be the correct way to fix it since the addition of the delete statement to the earlier script appears (to me) to be randomly deleting records.  I would just correct the delete statement to do what was intended and I think the intent was to delete language codes that had an underscore instead of a hyphen.

**Comment by jekkos** [comment]
Intentional, in fact I had a similar issue when upgrading my dutch install, at a certain point language folders were renamed, and this was reflected in the scripts only by updating the english to en-US (so other languages weren't)
So I thought there was a default catch that if no language is defined, it would default to english, which seems not to be the case in your test here. So what I would suggest is to add some catch in the code to set to english if the language folder is not found..

**Comment by jekkos** [comment]
Ok correct the statement might be wrong, if I remember well we use hyphens on the filesystem and underscore in the app_config table. But indeed I missed that the query is probably deleting other records as well. So I'll revert that tonight and try to find a better solution.

**Comment by daN4cat** [comment]
Yes, the touching of the migration script caused the issue. I can see it when I start a docker image from scratch.

**Comment by jekkos** [comment]
Did a fix for this, the config hook now checks whether both config values are present first. If not, or if any settings is corrupt or wrong, it will default to english.
Also removed the delete statement in the migration script, but together with the code change, even if executed, we shouldn't be able to get into that state anymore.

**Comment by jekkos** [comment]
I guess this error is solved now? Then can we close?

**Comment by SteveIreland** [comment]
Sticking a fork in it ... it is dun!
