### ISSUE TITLE
Sales_items Database May be missing Discount update

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2149]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: Current
- OSPOS git commit hash is: 
- PHP version is: 7.1
- MySQL or MariaDB version is: mysql 5.7
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: WAMP

### Issue / Bug  / Question / New Feature
Tried to update an old database and I had to manually install sales_items discount. Am I missing something here?

**Comment by SteveIreland** [comment]
Yes, I see something similar in the test environment I built last night over the most recent branch.  It didn't rename the discount_percent field to discount.   However, an environment I built from the master a few days ago looks fine.

Gremlins.

**Comment by SteveIreland** [comment]
Correct ... if someone doesn't sort it out by tonight I'll take a look and see what's going on.

**Comment by odiea** [comment]
For some reason ospos_receivings_items is also not getting updated.

ALTER TABLE `ospos_receivings_items`
	CHANGE COLUMN `discount_percent` `discount` DECIMAL(15,2) NOT NULL DEFAULT 0 AFTER `item_unit_price`,
	ADD COLUMN `discount_type` TINYINT(2) NOT NULL DEFAULT '0' AFTER `discount`;

**Comment by SteveIreland** [comment]
I deleted the database, recreated it from database.php and then logged in so that the migration scripts were kicked off.

The `discount_percent` field was properly renamed to simply `discount`.  Nothing in the error log to indicate a failure with that statement (there are numerous other failures, but not related to the discount_percent,)

I can't say for sure that I finally logged in to update the tables in my test environment because I had rebuilt it several times while chasing down what was going on with the language_code config value.

Hopefully in your case you hadn't logged in yet .... maybe?

**Comment by SteveIreland** [comment]
I just rebased my India GST project over the current master branch and will be running some tests and will check to make sure that the discount_percent field is again renamed.

**Comment by odiea** [comment]
I had logged in ok but after I tried to complete a Sale is when the database error showed. I then went and located the sql file and noticed receivings also did not update.

**Comment by SteveIreland** [comment]
Odd.  Well, I just now tested my rebase over the latest master (Latest commit c3ba10f  2 days ago).  The migration scripts ran fine and the field names were changed.  The language_code value is still being deleted so the language values are not being mapped on startup.

**Comment by SteveIreland** [comment]
Did you encounter this problem over an upgraded database or a brand new installation?

I've only been doing a new installation.

I'm going to try to upgrade an existing database this weekend with the India GST changes so I might encounter the issue if you encountered it with an existing database.

**Comment by odiea** [comment]
I try to find my oldest db to upgrade. I was using the attributes version.

**Comment by odiea** [comment]
The upgrade worked fine on another db I had. Maybe some of the tables were already updated in the previous db's I was using.
