### ISSUE TITLE
Submit button not working

### ISSUE THREAD

**Issue by saurabh261187** [opensourcepos/opensourcepos#2150]
### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 5.6.25
- MySQL or MariaDB version is: MySQL 5.5.6
- OS and version is: Windows 10 Pro 64Bit
- WebServer is: LAMP stack with Virtualmin
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  

Hello,

I am using OSPOS from quite some time. Off late, when I am trying to submit new customer information, the form is not getting submitted or clicked even after repeated attempts. I have noticed this only from the last week, and cannot use OSPOS for my day to day activities because of this issue. Any help regarding this URGENT matter will be highly appreciated.

Thanks.

**Comment by saurabh261187** [comment]
Disclaimer : Sometimes the Submit button on New Customer entry form works, sometimes it doesnt.

**Comment by mckaygerhard** [comment]
i have same problem like you that have some causes.. in my case i made too many changes.. in fact remove any reference to esxternal resource (??? i dont understand why made request to something that in future will changed), specially in csss

i suggest to made debug of your problem, follos the wiki debugging your installation.. (sorry wiki was significative changed.. search by yourselft)

**Comment by SteveIreland** [comment]
If it was working without problems and then started having problems what might have changed that started causing problems?  If you made some changes to the code then obviously that would be the first thing to look at.  If there are no obvious clues then you are left with no other options other than to start debugging the process which means is described in the WIki under https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-DEVEL-for-Error-Logging-in-OSPOS

**Comment by mckaygerhard** [comment]
i not made changes BEFOR the problems.. and as the @saurabh261187 said either.. i discover the bug later... and made some improvements, reported here but as always dont take care..

**Comment by mckaygerhard** [comment]
what do you fear in the comments, the error was reported... and occurs without changing the sources

**Comment by SteveIreland** [comment]
Fear is not the appropriate term ... disgust is.  @mckaygerhard  as has been discussed with you numerous times we are trying to keep the issues forum about the discussion and  resolution of issues of the original poster and not about your negative feelings about the development team.  And here we are again talking about you instead of providing solutions - a painful waste of my limited resources.  These last two posts will self destruct in 30 minutes or less.

**Comment by mckaygerhard** [comment]
@SteveIreland same for you, see 

>" If you made some changes to the code then obviously that would be the first thing to look at"

if you see clear the problem are without change anythig.. and there's a lot of issues reported similar.. due happened in some cases with big delay in the network connection (not alwys of course)

@saurabh261187 do you debug your install? see the network tab, see the codes (3 numbers digit) and report something like 500 or 404 or paste a screenshot to see what are happened!

no matter if you delete or erase  my opinion, issue like that will be commig more and more, and more forever until change some things inside documentation and installation

**Comment by odiea** [comment]
Check to see if there is a check mark in Registration Consent. It won't submit if there is not one.
![2018-09-21 15_30_41-window](https://user-images.githubusercontent.com/10962177/45907000-800e0c00-bdb3-11e8-8af1-a33dd00add47.png)

**Comment by SteveIreland** [comment]
@saurabh261187 were you able to determine what was going on and resolve it?
