### ISSUE TITLE
The page isn’t redirecting properly

### ISSUE THREAD

**Issue by Knobblywobbly** [opensourcepos/opensourcepos#2151]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: no idea what you're talking about!
- PHP version is: 7.2.9
- MySQL or MariaDB version is: haven't a clue!
- OS and version is: Linux Mint 18.
- WebServer is: Apache/2.4.34 (Unix) OpenSSL/1.0.2p PHP/7.2.9 mod_perl/2.0.8-dev Perl/v5.16.3 (hope there's something in there to answer this question)
- Selected language is: 
- (If applicable) Docker installation: Huh?
- (If applicable) Installation package for the LAMP/LEMP stack is: Eh?

### Issue / Bug  / Question / New Feature

Right then (and "Hello to all"), I'm hoping someone can help me before I have a real tantrum ;-)
I have installed LAMP on my computer running Linux Mint 18.3 and everything seemed to go ok. I started Apache and MySQL and they're running. I installed Docker which went ok too. I thin tried to install OSPOS using Docker. Loads of stuff flashed across the screen but when I got to the end I had the following error:

"Successfully tagged ospos_php:latest
WARNING: Image for service php was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating ospos_sqlscript_1
Creating ospos_mysql_1

ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint ospos_mysql_1 (5c1fc348d506da0de7d49ece90fe07b97cf057d97c58d1193db8715b08f2aad4): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project."

As I have no idea what this means or what the cause was, and now that I had MySQL, Apache & PHP installed, I tried to follow the instructions to do a manual install. I created a database but when I go to "localhost/ospos/database/database.sql" I get the following error:

"The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies."

Also, the URL changes to "http://localhost/ospos/database/database.sqlpublic/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/"

It's doing my head in - can anyone help please? 
TIA

**Comment by mckaygerhard** [comment]
before i paste my opinion, i ask: sure your database are up inside dockert and ospos cn get into with supplied credentials?

redirection are a "very" common problem but as i can see you have two problems not one! firts get sure your mysql works and ospos can get into

**Comment by daN4cat** [comment]
First, if you use docker, switch off Apache and MySQL installations on your machine/VM otherwise you get a conflict.
Then run `docker-compose build` and then `docker-compose up -d`.

**Comment by Knobblywobbly** [comment]
Ok, I switched off Apache & MySQL and ran the commands, but had to put "sudo" in front otherwise I got an error.
After this I went to "localhost/ospos/" but received a 404 error. I switched on Apache & MySQL, the went to "localhost/ospos/" which changed to "localhost/ospos/public" but all I have is a blank white screen.

**Comment by Knobblywobbly** [comment]
Thanks. I'm getting closer I think.
Did the above and got a login screen. Typed in "admin" & "pointofsale", clicked "go" then got this error:
"Unable to connect
Firefox can’t establish a connection to the server at 127.0.0.1."

URL had changed to "https://127.0.0.1/login"

**Comment by mckaygerhard** [comment]
your problem was not db connection , now solve your problem are a complicated and very intrincated rewrite rule.. if you have setup in subdir.. better to use a index.php .. if not please search for recent discussion here: https://github.com/opensourcepos/opensourcepos/issues/1491  a very very common problem due the htaccess

if you not are using and have a hiyacked www-root please see into the htaccess and edit proper to your path..

if you are using a subdir o subdomain install see https://github.com/opensourcepos/opensourcepos/issues/1491 and good luck

if you want a simpel solution put a index.php in the root of proyect and see my fork in sme discussion

**Comment by daN4cat** [comment]
@mckaygerhard stop messing up, we are talking of docker installation and that's fine. I'll delete your post because as usual you mislead people.

**Comment by daN4cat** [comment]
@Knobblywobbly have you used the code from a release zip file?

**Comment by Knobblywobbly** [comment]
Yes, I downloaded the zip file for version 3.2.3

**Comment by daN4cat** [comment]
And you run the docker-composer commands as I said...

I need to check if there was any fix to docker since the version you use.
Because with the latest dev version works fine.

You can always give a try and just download the docker files from GitHub master and re run the commands. See what happens.
Those are independent from the ospos app code version.

**Comment by Knobblywobbly** [comment]
Yes I ran the docker commands as you said, in fact I've just done them again now but still have the same problem.
Once I have entered the username and password then clicked on "go", Firefox offers to remember the password, but for a blank username, not admin. I don't know if that is relevant at all.
I'll see if I can find the docker files you speak about, but all this is very new to me, including using github.

**Comment by daN4cat** [comment]
Have you by any chance changed the config files in your local machine before building the docker image?

**Comment by daN4cat** [comment]
In case you are not sure, take again the complete release zip file and uncompress it in a new forder.
Then just run the docker commands without touching anything.
Again make sure no local Apache and MySQL service is running.

**Comment by Knobblywobbly** [comment]
Ok, I have downloaded v3.2.3 again and extracted it into a new folder. I ran the docker commands but on running "sudo docker-compose up -d" I get the following error:

"sudo docker-compose up -d
Creating network "ospos323_default" with the default driver
Creating volume "ospos323_uploads" with local driver
Creating ospos323_sqlscript_1
Creating ospos323_mysql_1

ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint ospos323_mysql_1 (2bce250ef554391d1cf667e932fbfe8ec6d0cb85030b1b80c92eacce864415f1): Bind for 0.0.0.0:3306 failed: port is already allocated
ERROR: Encountered errors while bringing up the project."

I uninstalled XAMPP yesterday - how can I check if MySQL is still active/running?

**Comment by Knobblywobbly** [comment]
I rebooted my computer and started again.

I downloaded version 3.2.2 and unzipped it into a different folder. I ran the commands an here's the result:
pc-solutions@pcsolutions-Aspire-V3-731 ~/ospos322 $ sudo docker-compose build
[sudo] password for pc-solutions: 
Building sqlscript
Step 1/4 : FROM debian:jessie
 ---> 7f228954ce78
Step 2/4 : MAINTAINER jekkos
 ---> Using cache
 ---> 090f2541f104
Step 3/4 : ADD database.sql /docker-entrypoint-initdb.d/database.sql
 ---> Using cache
 ---> 46ff572aa2c8
Step 4/4 : VOLUME /docker-entrypoint-initdb.d
 ---> Using cache
 ---> eb3047b435e9
Successfully built eb3047b435e9
Successfully tagged ospos322_sqlscript:latest
mysql uses an image, skipping
Building php
Step 1/12 : FROM php:7.0.29-apache
 ---> 839c97e935c6
Step 2/12 : MAINTAINER jekkos
 ---> Using cache
 ---> 40c7cf92e88f
Step 3/12 : RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y     libicu-dev     libgd-dev     openssl
 ---> Using cache
 ---> 8a161bc5ebde
Step 4/12 : RUN a2enmod rewrite
 ---> Using cache
 ---> 9c11b9bf750b
Step 5/12 : RUN docker-php-ext-install mysqli bcmath intl gd
 ---> Using cache
 ---> 193548693e13
Step 6/12 : RUN echo "date.timezone = \"\${PHP_TIMEZONE}\"" > /usr/local/etc/php/conf.d/timezone.ini
 ---> Using cache
 ---> dcdea21e527e
Step 7/12 : RUN echo -e “$(hostname -i)\t$(hostname) $(hostname).localhost” >> /etc/hosts
 ---> Using cache
 ---> afddd1adc34c
Step 8/12 : WORKDIR /app
 ---> Using cache
 ---> f9639cf5b960
Step 9/12 : COPY . /app
 ---> a297d67f259e
Removing intermediate container 241a251c4e99
Step 10/12 : RUN ln -s /app/*[^public] /var/www && rm -rf /var/www/html && ln -nsf /app/public /var/www/html
 ---> Running in d20eebb1d9c5
 ---> 0434844706d3
Removing intermediate container d20eebb1d9c5
Step 11/12 : RUN chmod 755 /app/public/uploads && chown -R www-data:www-data /app/public /app/application
 ---> Running in 8d8471ccf8ea
 ---> 01c97f0150d5
Removing intermediate container 8d8471ccf8ea
Step 12/12 : RUN [ ! -f test/ospos.js ] || sed -i -e "s/\(localhost\)/web/g" test/ospos.js
 ---> Running in f534cf6b8efd
 ---> f07e96c1f84b
Removing intermediate container f534cf6b8efd
Successfully built f07e96c1f84b
Successfully tagged ospos322_php:latest
pc-solutions@pcsolutions-Aspire-V3-731 ~/ospos322 $ sudo docker-compose up -d
Creating network "ospos322_default" with the default driver
Creating volume "ospos322_uploads" with local driver
Creating ospos322_sqlscript_1
Creating ospos322_mysql_1
Creating ospos322_php_1
pc-solutions@pcsolutions-Aspire-V3-731 ~/ospos322 $ 

I then opened Firefox and typed in 127.0.0.1 and all I got was a blank screen. I then typed in 127.0.0.1/login and got the login screen. I entered the username and password but then received the "cannot connect" message.

**Comment by daN4cat** [comment]
are you using http and not https?
Also when you start the docker image you need to wait 5/10s before you can connect to the website.

Make sure all the old docker images are down (docker-composer down) because otherwise you get a mess of images contending for the same ports and etc.

**Comment by Knobblywobbly** [comment]
Thanks for all your help.

I have installed LAMPP and set it up without docker and it is now working properly.
Thanks again.
