### ISSUE TITLE
.htaccess: Option SymLinksIfOwnerMatch not allowed here

### ISSUE THREAD

**Issue by Knobblywobbly** [opensourcepos/opensourcepos#2154]
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 7.0.21
- MySQL or MariaDB version is: 5.5.52
- OS and version is: 
- WebServer is: Apache 2.4.6-45.el7.centos.4 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I'm trying to install ospos on my hosting server. I've created a database, etc. but when I try to run the program I get a 500 Internal Server Error.
Looking at the server logs the error is:

[Sun Sep 23 12:42:29.859118 2018] [core:alert] [pid 3879] [client 185.214.136.2:41416] /var/www/xxxxx/data/www/xxxxx.com/ospos323/.htaccess: Option SymLinksIfOwnerMatch not allowed here

Can anyone tell me what this means and how to fix it please?
Thanks

**Comment by daN4cat** [comment]
Replace that with `FollowSymLinks` and see if it's fine. `SymLinksIfOwnerMatch` is more restrictive and secure but if that's an issue use the one I suggested.

**Comment by daN4cat** [comment]
If you check from the browser inspector, what do you see?

**Comment by Knobblywobbly** [comment]
Errmm.... nothing! Attached a screenshot of the inspector.

[http://www.coastalradio.es/pic1.png](url)

**Comment by daN4cat** [comment]
I wonder if `SymLinksIfOwnerMatch` was right and the issue is actually the permission applied to the your folders?
Have you checked that?

**Comment by Knobblywobbly** [comment]
All the folders are 755. Is that correct?

**Comment by Knobblywobbly** [comment]
Yes it does - all files and directories have the same owner as the web server.

**Comment by daN4cat** [comment]
And is there anything in the Apache error log?

**Comment by Knobblywobbly** [comment]
No, nothing. If I put  SymLinksIfOwnerMatch back in then I get the following error, but otherwise nothing.

"[Thu Oct 04 09:36:38.710144 2018] [core:alert] [pid 22382] [client 85.204.140.117:40498] /var/www/coastal/data/www/mydomain.com/ospos323/.htaccess: Option SymLinksIfOwnerMatch not allowed here"

**Comment by daN4cat** [comment]
Have you compiled the apache server on centos by yourself?
Because something about symlinks might be disabled.
I use centos and I have set it up in secure way to follow symlinks only if matching the owner.

Do you have any other PHP app running on your web server?

**Comment by Knobblywobbly** [comment]
I didn't compile anything. I've installed ospos on a VPS, so the hosts sort all that out. I have lots of other stuff running on various domains on this VPS and everything else is fine.

**Comment by Knobblywobbly** [comment]
The hosts sorted the symlinks problem, but then I got a 404 error when trying to access the index.php. Spoke again to the hosts and they said it was generating other syntax errors, so I've given up!

**Comment by daN4cat** [comment]
I have a VPS on CentOS too and I'm in control of Apache configuration and recompilation.
Not sure what the setup is, but you need to be on top of your configuration to deploy securely applications.
That rule is even in Drupal if you want to run that CMS system.
