### ISSUE TITLE
Unabled to permanently delete item

### ISSUE THREAD

**Issue by ahmedkaballo** [opensourcepos/opensourcepos#2156]
Hello
When i delete an item from items, the item is deleted in the system but it's not deleted from database. so when i try to add new item with the same barcode number of the deleted item the system gives a message says that the barcode already exists in the database.
so how can i permanently delete item from system?

**Comment by WebShells** [comment]
Please fill in the issue template so we can provide better support... The items can't be totally removed from the db because of db relations, you can remove the barcode before deleting, or you can allow duplicate barcodes from system configuration.

**Comment by daN4cat** [comment]
@ahmedkaballo you need soft delete because items could be referenced in transactions and therefore deleting them could cause errors.
Hard delete will never happen.
