### ISSUE TITLE
Receiving price not updating in total and in right payment bar

### ISSUE THREAD

**Issue by moniruss** [opensourcepos/opensourcepos#2157]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: opensourcepos.20180613210031.3.2.3.f1cf3d.zip
- OSPOS git commit hash is: 
- PHP version is: 7.1.19
- MySQL or MariaDB version is: 
- OS and version is: windows 10 64bit
- WebServer is: xampp
- Selected language is: english 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
1. Have extracted opensourcepos.20180613210031.3.2.3.f1cf3d.zip file in htdocs, imported database and successfully accessed it. For now, what i am seeing  is whichever item i am adding with a price, at the receiving page, when I select one or add one, the price don't get added in total price. It always shows $0. Sales option seemed to be working though.
2. I have directly extracted files and imported database.sql, nothing else. Is there a need to install composer, node.js, grunt-cli? It's already running as it is, just not counting receiving prices.

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by moniruss** [comment]
Also, There's a slight different between demo and recent version which I have downloaded and checking like 'wholesale price' shows 'cost' while 'retail price' shows 'sale price' etc. Demo access ain't working anymore though suddenly. Check it please.

**Comment by odiea** [comment]
In Items add new item form you must add your wholesale and resale prices. This also applies to adding Items in New Item in Receivings.  Receivings form does not add a cost or retail price. 
Yes the newer version is just a name change.

**Comment by moniruss** [comment]
Hi, thanks for the info but I already know that and did accordingly. Afterwards, when in receiving page, when i add that item that price doesn't get calculated, that's what i am saying.

**Comment by WebShells** [comment]
Are you updating the fields by pressing on the circular update button on the right side?

**Comment by moniruss** [comment]
That's weird. I have downloaded the full version opensourcepos.20180613210031.3.2.3.f1cf3d.zip, extracted it in my xampp localhost, imported inside database/database.sql file. But in my case, total price ain't getting updated. Sales page is working fine on the other hand! :(

**Comment by odiea** [comment]
What do you see when you go to Reports Receivings. Is it showing the correct info?

**Comment by moniruss** [comment]
No, I tried that too. I have added 3 item costing $20..total showed 0. Finished it. Went to report, there it's also $0

**Comment by odiea** [comment]
A true mystery. You can enable  error logging in config and change production to development in public index.php and see if anything shows.

**Comment by moniruss** [comment]
Okay. I will do that later when am home and get back to you. Btw, have you also installed from opensourcepos.20180613210031.3.2.3.f1cf3d.zip and its inside database? Which php version have you worked on?

**Comment by odiea** [comment]
Php Version is 7.1.16 and yes that is the current stable release.

**Comment by odiea** [comment]
In the Items form the receiving quantity must be 1 or greater. It cannot be 0.

**Comment by moniruss** [comment]
Thanks, that's the issue! The receiving quantity in 'add item' refer to bulk amount every time I make purchase while in receiving quantity in receiving page refers to multiplier of that bulk amount! I thought both receiving quantity refers to simply 'quantity'! So when added new item, i kept it 0 initially , and only added quantity in receiving page, which happens to be just a multiplier and resulted into 0! Got confused but thankfully now sorted out! Thanks again! :D
