### ISSUE TITLE
Sorting Error in the Report Pages

### ISSUE THREAD

**Issue by haicoi311** [opensourcepos/opensourcepos#2159]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is: 7.0
- MySQL or MariaDB version is: 10.1.26-MariaDB-0+deb9u1
- OS and version is:  - Debian 9.1
- WebServer is: Apache/2.4.25 (Debian)
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

When I look for the **Office Customers Summary Report**, I hava e problem with the **sorting function**.
Ospos **do not work properly** when I try to **sort** the subtotal value from largest to smallest or smallest to largest. 
But it **only happen to the Subtotal; Total; Wholesale** only, t**he others (Profit, Quantity, and even Customer name) is ok.**
What is wrong here?
![1](https://user-images.githubusercontent.com/43383226/45989559-7253d180-c0a6-11e8-9eab-718046de90d3.png)
![2](https://user-images.githubusercontent.com/43383226/45989560-7253d180-c0a6-11e8-81e3-41fcbf073c8d.png)
![3](https://user-images.githubusercontent.com/43383226/45989561-72ec6800-c0a6-11e8-9d21-2427283a1bf7.png)
![4](https://user-images.githubusercontent.com/43383226/45989562-72ec6800-c0a6-11e8-95e0-b785aaaf2397.png)

**Comment by SteveIreland** [comment]
Still, it is an interesting issue.  Since the sort is an "internal array sort" and not something we specifically program for I would guess that there is some sort of language encoding issue in play here related to the third party tools.

**Comment by odiea** [comment]
in 3.2.3 this is part of the code . for application/models/reports/summary_customers and check his version to see if it looks similar. I don't know if the  'sorter' => 'number_sorter may or may not be in that version or if it really means anything.
```
protected function _get_data_columns()
	{
		return array(
			array('customer_name' => $this->lang->line('reports_customer')),
			array('quantity' => $this->lang->line('reports_quantity')),
			array('subtotal' => $this->lang->line('reports_subtotal'), 'sorter' => 'number_sorter'),
			array('tax' => $this->lang->line('reports_tax'), 'sorter' => 'number_sorter'),
			array('total' => $this->lang->line('reports_total'), 'sorter' => 'number_sorter'),
			array('cost' => $this->lang->line('reports_cost'), 'sorter' => 'number_sorter'),
			array('profit' => $this->lang->line('reports_profit'), 'sorter' => 'number_sorter'));
	}
``

**Comment by SteveIreland** [comment]
I checked and that hasn't changed in forever.  Maybe in that particular release the SQL used to generate the data used by the report created it as a alpha field and maybe that isn't being handled by number_sorter.  The number_sorter seems to be some JavaScript magic that is beyond me (without spending a lot of time in self education camp) so I won't be able to help out with this one.

**Comment by haicoi311** [comment]
> in 3.2.3 this is part of the code . for application/models/reports/summary_customers and check his version to see if it looks similar. I don't know if the 'sorter' => 'number_sorter may or may not be in that version or if it really means anything.
> 
> ```
> protected function _get_data_columns()
> 	{
> 		return array(
> 			array('customer_name' => $this->lang->line('reports_customer')),
> 			array('quantity' => $this->lang->line('reports_quantity')),
> 			array('subtotal' => $this->lang->line('reports_subtotal'), 'sorter' => 'number_sorter'),
> 			array('tax' => $this->lang->line('reports_tax'), 'sorter' => 'number_sorter'),
> 			array('total' => $this->lang->line('reports_total'), 'sorter' => 'number_sorter'),
> 			array('cost' => $this->lang->line('reports_cost'), 'sorter' => 'number_sorter'),
> 			array('profit' => $this->lang->line('reports_profit'), 'sorter' => 'number_sorter'));
> 	}
> ``
> ```

![image](https://user-images.githubusercontent.com/43383226/46054503-beb81380-c171-11e8-90cd-b2453aac151e.png)
It is the same in the version 3.2.0.

**Comment by haicoi311** [comment]
I realize that when sorting, it only change the order of the numbers which have less than 6 letters ( 1 to 999 000 only) while the higher value (have more than 6 letters do not sort: from 1 000 000 up).

Where does this bug come from?

**Comment by jekkos** [comment]
are you sure? it might be due to the currency formatting.. 
sorting is bootstrap tables functionality. One might need a special sorter for currency columns to make it work correctly.

**Comment by haicoi311** [comment]
Lets see the two first screenshots that I attached in the post. You can see the problem right there. There are some numbers that do not change position when sorting command is executed

**Comment by haicoi311** [comment]
> are you sure? it might be due to the currency formatting..
> sorting is bootstrap tables functionality. One might need a special sorter for currency columns to make it work correctly.

I changed the currency format back to the US format ( "," for thousand separator and "." for decimal separator) and it works. 

But, how can it works for other currency format? (for example in my languages,  "." for thousand separator and "," for decimal separator?)

**Comment by jekkos** [comment]
probably a matter of adapting the sorting function to ignore currency symbols

**Comment by daN4cat** [comment]
Yes we would need to add more sorting functions.

**Comment by jekkos** [comment]
I pushed a fix to master. @haicoi311 can you validate if this works for you?

**Comment by haicoi311** [comment]
> I pushed a fix to master. @haicoi311 can you validate if this works for you?

how can I validate the new fix?

**Comment by haicoi311** [comment]
@jekkos @daN4cat I have change the file public/js/manage_tables.js as follow:
replace:
	a = +a.replace(/[^\-0-9\.]+/g, '');
	b = +b.replace(/[^\-0-9\.]+/g, '');

With:
	a = +a.replace(/[^\-0-9]+/g, '');
	b = +b.replace(/[^\-0-9]+/g, '');

But it still problem. it does not work. 
It only sort the number which have more than 6 letter (> 999.999)
And it only occurs with the vietnamese number formating ("," as decimal seperator and "." as thousand separator)

**Comment by haicoi311** [comment]
@daN4cat ok fine. I have changed the opensourcepos.min.js already. And it works now actually!
