### ISSUE TITLE
Deleted items don't show up in receipt

### ISSUE THREAD

**Issue by bullmike** [opensourcepos/opensourcepos#2161]
version 3.2.3

If you sell an item and it is later flagged as deleted, the item no longer appears in the receipt.

      public function receipt($sale_id)
        {
 -->         $data = $this->_load_sale_data($sale_id);  <----
                $this->load->view('sales/receipt', $data);
                $this->sale_lib->clear_all();
        }

        private function _load_sale_data($sale_id)
        {
                $this->sale_lib->clear_all();
                $this->sale_lib->reset_cash_flags();
                $sale_info = $this->Sale->get_info($sale_id)->row_array(); 
---->        $this->sale_lib->copy_entire_sale($sale_id);   <----

        public function copy_entire_sale($sale_id)
        {
                $this->empty_cart();
                $this->remove_customer();

                foreach($this->CI->Sale->get_sale_items_ordered($sale_id)->result() as $row)
                {
-->                    $this->add_item($row->item_id, $row->quantity_purchased, $row->item_location, $row->discount_percent, PRICE_MODE_STANDARD, NULL, NULL, $row->item_unit_price, $row->description, $row->serialnumber, TRUE, $row->print_option);
                }

        public function add_item(&$item_id, $quantity = 1, $item_location, $discount = 0, $price_mode = PRICE_MODE_STANDARD, $kit_price_option = NULL, $kit_print_option = NULL, $price_override = NULL, $description = NULL, $serialnumber = NULL, $include_deleted = FALSE, $print_option = NULL )
        {
-->                $item_info = $this->CI->Item->get_info_by_id_or_number($item_id);

        /*
        Gets information about a particular item by item id or number
        */
        public function get_info_by_id_or_number($item_id)
        {
                $this->db->from('items');

                $this->db->group_start();

                $this->db->where('items.item_number', $item_id);

                // check if $item_id is a number and not a string starting with 0
                // because cases like 00012345 will be seen as a number where it is a barcode
                if(ctype_digit($item_id) && substr($item_id, 0, 1) != '0')
                {
                        $this->db->or_where('items.item_id', (int) $item_id);
                }

                $this->db->group_end();

-->          $this->db->where('items.deleted', 0);

                ^^^^^^^^^^^^^^
                 THE ISSUE IS HERE

Thanks
Mike

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
I thought that was changed with issue #904

**Comment by odiea** [comment]
And again the info for the version is not included.

**Comment by SteveIreland** [comment]
It wasn't filled out correctly, but he did mention this was in version 3.2.3.

And you have an amazing memory.  I'll need to check to see if it was broken somewhere along the line ... hopefully not by me but that is always a real possibility.

**Comment by odiea** [comment]
I vaguely remember the issues I have had to deal with. Plus I just enter the words in search and it pulls up the ones I have dealt with.

**Comment by SteveIreland** [comment]
Checked the code and found that I own this one,  :-(   A fix for 3.3 is on the way.

Resolved simply enough by those who want to apply a quick release on their own and not wait for the next release.

Just remove line 341 from `.../model/Item.php` in function `get_info_by_id_or_number($item_id)` which should be
`$this->db->where('items.deleted', 0);`
