### ISSUE TITLE
Service 'sqlscript' failed to build

### ISSUE THREAD

**Issue by tomatoe45** [opensourcepos/opensourcepos#2167]
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

- OSPOS version is:  3.2.3
- OSPOS git commit hash is: 
- PHP version is: 5.6.38
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: Xampp
- Selected language is: PHP
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

Hi.. i found this nice and good application for pos unfortunately i was having a hard time when trying to 
install it.. i clone this package and upon installing. i have this 

"ERROR: Service 'sqlscript' failed to build: no matching manifest for unknown in the manifest list entries"

. anyone has the same issue?

**Comment by daN4cat** [comment]
Please download the official release zip file, don't clone GitHub repository unless you want to develop some feature.

**Comment by daN4cat** [comment]
if you want to develop and start from the GitHub repo, please read the wiki for the development setup.
