### ISSUE TITLE
 106/5000 Problem with reports module, uploaded from my HP ProLiant ML30 G9 Server

### ISSUE THREAD

**Issue by rocklalo** [opensourcepos/opensourcepos#2168]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by rocklalo** [comment]
Good day, my friend I install openSourcePos in window server through the IIS and htdocs of xampp, it opens everything to me well but the reports module does not work and it is the only module that does not open.
Error
(Your connection to this website is not private)
Username
password

www.eddosweb.cl

**Comment by daN4cat** [comment]
It looks like it requires a login when it comes to go to reports as there is a pop up form.
You sure you don't have anything else running on that path? It might be a clash with some other application using the /reports URL path.

**Comment by daN4cat** [comment]
BTW, it looks like you haven't copied all the files, this one is missing: http://www.eddosweb.cl/dist/bootswatch/fonts/glyphicons-halflings-regular.woff2

**Comment by daN4cat** [comment]
the report error is not something I've ever seen.
If you stop ospos and try to go to www.eddosweb.cl/reports do you still see the same?

**Comment by daN4cat** [comment]
There is some clash in your server, as said try to remove ospos and check www.eddosweb.cl/reports and see what happens.

**Comment by rocklalo** [comment]
> Por cierto, parece que no ha copiado todos los archivos, esta falta: http://www.eddosweb.cl/dist/bootswatch/fonts/glyphicons-halflings-regular.woff2

What is the name of the folder I did not copy?

**Comment by SteveIreland** [comment]
Did you install directly from a release zip file, the development branch, or from a zip file downloaded from bintray?  If from the development branch did you run the following three commands in the root of the unzipped file?

* composer install
* npm install
* grunt --force

**Comment by rocklalo** [comment]
> ¿Lo instaló directamente desde un archivo zip de versión, la rama de desarrollo o desde un archivo comprimido descargado de bintray? Si desde la rama de desarrollo ejecutó los siguientes tres comandos en la raíz del archivo descomprimido
> 
> * instalación del compositor
> * npm instalar
> * grunt --force

Which of all those is downloaded, I downloaded opensourcepos.20180613210031.3.2.3.f1cf3d

**Comment by SteveIreland** [comment]
Okay, thanks for letting me know.  That's the 3.2.3 general release zip and that's been vetted thoroughly.

@daN4cat  was asking if you had any conflicts in regard to IIS rewrite because the path /reports seems to be taking you to somewhere else other than the OSPOS /reports folder.  Also, he was testing to see if one of the files could be directly accesses via a URL.  On the system I'm aware of that URL he gave you should start a download.  On your site it says it can't be found.  So it seems that your URL rewrite configuration isn't correct.

**Comment by daN4cat** [comment]
My feeling is that their server has something else for that reports path, which causes a conflict.
That dialog box is more an access issue at IIS level, nothing to do with OSPOS, unless some files or report folder/dir was marked differently from read access point of view?
I never used IIS server, so I can't help with the details of the configuration.

**Comment by rocklalo** [comment]
It will be possible if you can help me by team viewer?

**Comment by rocklalo** [comment]
This is how it is configured with Rewrite Url

.htacces

RewriteEngine On

# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
# RewriteCond %{HTTP_HOST} ^<OSPOS subdomain>\.<my web domain>\.com$ [OR]
# RewriteCond %{HTTP_HOST} ^www\.<OSPOS subdomain>\.<my web domain>\.com$
# RewriteRule ^/?$ "https\:\/\/www\.<my web domain>\.com\/<OSPOS path>" [R=301,L]

# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
# RewriteCond %{HTTPS} !=on
# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
# RewriteCond %{HTTP_HOST} (.+)$ [NC]
# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# if in web root
RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
# RewriteRule ^(.*)$ /<OSPOS path>/public/index.php?/$1 [L]

# disable directory browsing
# For security reasons, Option all cannot be overridden.
#Options All -Indexes
Options +ExecCGI +Includes +IncludesNOEXEC +SymLinksIfOwnerMatch -Indexes

# prevent folder listing
IndexIgnore *

# Apache 2.4
<IfModule authz_core_module>
  # secure htaccess file
  <Files .htaccess>
    Require all denied
  </Files>
  # prevent access to PHP error log
  <Files error_log>
    Require all denied
  </Files>
</IfModule>

# Apache 2.2
<IfModule !authz_core_module>
  # secure htaccess file
  <Files .htaccess>
    Order allow,deny
    Deny from all
    Satisfy all
  </Files>
  # prevent access to PHP error log
  <Files error_log>
    Order allow,deny
    Deny from all
    Satisfy all
  </Files>
</IfModule>

<IfModule mod_expires.c>
  <FilesMatch "\.(jpe?g|png|gif|js|css)$">
    ExpiresActive On
    ExpiresDefault "access plus 1 week"
  </FilesMatch>
</IfModule>

**Comment by rocklalo** [comment]
`RewriteEngine On

# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
# RewriteCond %{HTTP_HOST} ^<OSPOS subdomain>\.<my web domain>\.com$ [OR]
# RewriteCond %{HTTP_HOST} ^www\.<OSPOS subdomain>\.<my web domain>\.com$
# RewriteRule ^/?$ "https\:\/\/www\.<my web domain>\.com\/<OSPOS path>" [R=301,L]

# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
# RewriteCond %{HTTPS} !=on
# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
# RewriteCond %{HTTP_HOST} (.+)$ [NC]
# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# if in web root
RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
# RewriteRule ^(.*)$ /<OSPOS path>/public/index.php?/$1 [L]

# disable directory browsing
# For security reasons, Option all cannot be overridden.
#Options All -Indexes
Options +ExecCGI +Includes +IncludesNOEXEC +SymLinksIfOwnerMatch -Indexes

# prevent folder listing
IndexIgnore *

# Apache 2.4
<IfModule authz_core_module>
  # secure htaccess file
  <Files .htaccess>
    Require all denied
  </Files>
  # prevent access to PHP error log
  <Files error_log>
    Require all denied
  </Files>
</IfModule>

# Apache 2.2
<IfModule !authz_core_module>
  # secure htaccess file
  <Files .htaccess>
    Order allow,deny
    Deny from all
    Satisfy all
  </Files>
  # prevent access to PHP error log
  <Files error_log>
    Order allow,deny
    Deny from all
    Satisfy all
  </Files>
</IfModule>

<IfModule mod_expires.c>
  <FilesMatch "\.(jpe?g|png|gif|js|css)$">
    ExpiresActive On
    ExpiresDefault "access plus 1 week"
  </FilesMatch>
</IfModule>`

**Comment by rocklalo** [comment]
### This is how it is configured with Rewrite Url
.htacces
RewriteEngine On

# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
# RewriteCond %{HTTP_HOST} ^<OSPOS subdomain>\.<my web domain>\.com$ [OR]
# RewriteCond %{HTTP_HOST} ^www\.<OSPOS subdomain>\.<my web domain>\.com$
# RewriteRule ^/?$ "https\:\/\/www\.<my web domain>\.com\/<OSPOS path>" [R=301,L]

# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
# RewriteCond %{HTTPS} !=on
# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
# RewriteCond %{HTTP_HOST} (.+)$ [NC]
# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# if in web root
RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
# RewriteRule ^(.*)$ /<OSPOS path>/public/index.php?/$1 [L]

# disable directory browsing
# For security reasons, Option all cannot be overridden.
#Options All -Indexes
Options +ExecCGI +Includes +IncludesNOEXEC +SymLinksIfOwnerMatch -Indexes

# prevent folder listing
IndexIgnore *

# Apache 2.4
<IfModule authz_core_module>
  # secure htaccess file
  <Files .htaccess>
    Require all denied
  </Files>
  # prevent access to PHP error log
  <Files error_log>
    Require all denied
  </Files>
</IfModule>

# Apache 2.2
<IfModule !authz_core_module>
  # secure htaccess file
  <Files .htaccess>
    Order allow,deny
    Deny from all
    Satisfy all
  </Files>
  # prevent access to PHP error log
  <Files error_log>
    Order allow,deny
    Deny from all
    Satisfy all
  </Files>
</IfModule>

<IfModule mod_expires.c>
  <FilesMatch "\.(jpe?g|png|gif|js|css)$">
    ExpiresActive On
    ExpiresDefault "access plus 1 week"
  </FilesMatch>
</IfModule>

**Comment by rocklalo** [comment]
This is how it is configured with Rewrite Url 
htacces

•	RewriteEngine On

•	# To redirect a subdomain to a subdir because of https not supporting wildcards
•	# replace values between <> with your ones
•	# RewriteCond %{HTTP_HOST} ^<OSPOS subdomain>\.<my web domain>\.com$ [OR]
•	# RewriteCond %{HTTP_HOST} ^www\.<OSPOS subdomain>\.<my web domain>\.com$
•	# RewriteRule ^/?$ "https\:\/\/www\.<my web domain>\.com\/<OSPOS path>" [R=301,L]

•	# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
•	# RewriteCond %{HTTPS} !=on
•	# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
•	# RewriteCond %{HTTP_HOST} (.+)$ [NC]
•	# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
•	RewriteCond %{REQUEST_FILENAME} !-f
•	RewriteCond %{REQUEST_FILENAME} !-d
•	# if in web root
•	RewriteRule ^(.*)$ index.php?/$1 [L]

•	# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
•	# RewriteRule ^(.*)$ /<OSPOS path>/public/index.php?/$1 [L]

•	# disable directory browsing
•	# For security reasons, Option all cannot be overridden.
•	#Options All -Indexes
•	Options +ExecCGI +Includes +IncludesNOEXEC +SymLinksIfOwnerMatch -Indexes

•	# prevent folder listing
•	IndexIgnore *

•	# Apache 2.4
•	<IfModule authz_core_module>
•	# secure htaccess file
•	<Files .htaccess>
•	Require all denied
•	</Files>
•	# prevent access to PHP error log
•	<Files error_log>
•	Require all denied
•	</Files>
•	</IfModule>

•	# Apache 2.2
•	<IfModule !authz_core_module>
•	# secure htaccess file
•	<Files .htaccess>
•	Order allow,deny
•	Deny from all
•	Satisfy all
•	</Files>
•	# prevent access to PHP error log
•	<Files error_log>
•	Order allow,deny
•	Deny from all

**Comment by rocklalo** [comment]
> > Por cierto, parece que no ha copiado todos los archivos, esta falta: http://www.eddosweb.cl/dist/bootswatch/fonts/glyphicons-halflings-regular.woff2
> 
> What is the name of the folder I did not copy?

That folder if copied

**Comment by nerv55** [comment]
@rocklalo did you fix it?, if not tell me how to reproduce your installation to help you.

**Comment by rocklalo** [comment]
Hello, no, I could not fix it, could you help me?

**Comment by rocklalo** [comment]
> ¿Qué más se está ejecutando en su servidor IIS y sirve algo de una carpeta / informes?
> 
> Además, IIS tiene su propia configuración para la reescritura de URL. ¿Revisaste allí para ver si hay un conflicto?

Yes, use Rewtite URL of the IIS, since I had never worked with htacces and does it automatically.

**Comment by rocklalo** [comment]
> ¿Qué más se está ejecutando en su servidor IIS y sirve algo de una carpeta / informes?
> 
> Además, IIS tiene su propia configuración para la reescritura de URL. ¿Revisaste allí para ver si hay un conflicto?

I would like you to help me in this topic

**Comment by rocklalo** [comment]
> Hola, no, no pude arreglarlo, ¿podrías ayudarme?

I would like you to help me in this topic

**Comment by rocklalo** [comment]
> @rocklalo lo arreglaste ?, si no me dices cómo reproducir tu instalación para ayudarte.

I would like you to help me in this topic

**Comment by SteveIreland** [comment]
We're happy to help but you'll need to answer the questions we ask.  I understand there is a language issue here but so far you seem to be ignoring the question about the /reports conflict.  All indications suggest that you have a conflict somewhere caused by a URL rewrite (and it definitely won't be an issue caused by the .htaccess included with OSPOS).  So please check your IIS URL Rewrite configuration.

We also asked what else is being served up by IIS that might using the /reports path name in the URL.  That is most likely to be where the source of the problem is.

**Comment by rocklalo** [comment]
> Nos complace ayudarlo, pero tendrá que responder las preguntas que hacemos. Entiendo que hay un problema de idioma aquí, pero hasta ahora parece que estás ignorando la pregunta sobre el conflicto de / reports. Todas las indicaciones sugieren que tiene un conflicto en algún lugar causado por una reescritura de la URL (y definitivamente no será un problema causado por el .htaccess incluido con OSPOS). Así que por favor revise su configuración de IIS URL Rewrite
> 
> También preguntamos qué más le está sirviendo IIS que podría estar usando el nombre de ruta / reports en la URL. Eso es más probable que sea donde está la fuente del problema.

I am from Chile and I speak Spanish, it costs me a little English. We could solve it tomorrow by Team Viewer?

**Comment by SteveIreland** [comment]
I'm happy to offer free advice (when I have time) related to OSPOS but I definitely don't have the time for supporting custom installations.  Maybe @nerv55  does.

**Comment by akincikerem** [comment]
Dear All,

Could you please explain. how the problem was fixed.

When I click submit button on any report pages, I am getting HTTP 500 error. 
http://hostname/demo/public/reports/summary_items/2018-12-19/2018-12-19/complete/all

In my localhost host, I did not see this problem.  
If I install ospos on my  freehosting account, I am getting this error.

**Comment by akincikerem** [comment]
Fixed: My Log is below. And I talked the Hosting provider. They said that they do not to given permission to create  temprary tables for free hosting. 

So if you use free hosting account, reports module will not work. Please note that.
(ospos version 3.2.3)

ERROR - 2018-12-20 05:50:34 --> Query error: Access denied for user 'hp_xx'@'192.168.%' to database 'hp_xx_Data1' - Invalid query: CREATE TEMPORARY TABLE IF NOT EXISTS ospos_sales_items_taxes_temp (INDEX(sale_id), INDEX(item_id))

**Comment by SteveIreland** [comment]
Well I hadn’t heard that one before. 

Well need to add that to the list of prerequisites

**Comment by akincikerem** [comment]
Dear all,

I am just testing on free hosting. And you cannot trust free hosting. One morning, you can see everything has  gone.  :)

And this is my solition to work report system without temprary tables . :)

Regards.

\application\models\reports\Summary_report.php
change below codes

Delete this row: 
$this->db->query('CREATE TEMPORARY TABLE IF NOT EXISTS ' . $this->db->dbprefix('sales_items_taxes_temp') .

Add this row:
$this->db->query('DROP TABLE IF NOT EXISTS ' . $this->db->dbprefix('sales_items_taxes_temp'));
$this->db->query('CREATE TABLE IF NOT EXISTS ' . $this->db->dbprefix('sales_items_taxes_temp') .
