### ISSUE TITLE
New docker build - login fails as redirect to non-existent HTTPS 

### ISSUE THREAD

**Issue by rmoff** [opensourcepos/opensourcepos#2170]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [N/A] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: opensourcepos.20180613210031.3.2.3.f1cf3d.zip
- OSPOS git commit hash is: opensourcepos.20180613210031.3.2.3.f1cf3d.zip
- PHP version is: php:7.0.29-apache
- MySQL or MariaDB version is: mariadb:10.3.9
- OS and version is: Host OS is MacOS 10.13.6
- WebServer is: php:7.0.29-apache
- Selected language is: 
- (If applicable) Docker installation: Server Version: 18.06.1-ce
- (If applicable) Installation package for the LAMP/LEMP stack is: n/a

### Issue / Bug  / Question / New Feature

When logging in the `FORM` redirects to HTTPS, which doesn't work. 

1. Downloaded and unzipped `opensourcepos.20180613210031.3.2.3.f1cf3d.zip`
2. Ran `docker-compose build`
3. Ran `docker-compose up -d`
4. Everything up: 

        $ docker-compose ps
                        Name                                Command               State            Ports
        ----------------------------------------------------------------------------------------------------------
        opensourcepos20180613210031_mysql_1       docker-entrypoint.sh mysqld      Up       0.0.0.0:3306->3306/tcp
        opensourcepos20180613210031_php_1         docker-php-entrypoint apac ...   Up       0.0.0.0:80->80/tcp
        opensourcepos20180613210031_sqlscript_1   bash                             Exit 0
        $

5. Go to http://localhost/ and get login form. Enter creds admin/pointofsale, click Go. Browser throws "Unable to connect" and has switched to HTTPS (https://localhost/login)
6. Confirmed with `curl`, 

        $ curl -s http://localhost:80|grep action
                        <form action="https://localhost/login" method="post" accept-charset="utf-8">

        $ curl https://localhost/login
        curl: (7) Failed to connect to localhost port 443: Connection refused

        $ curl https://localhost:80/login
        curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by daN4cat** [comment]
Yes this is an issue solved in 3.3.0 under development.
Can you please copy the docker files from GitHub master and rebuild the image and run the container again?

**Comment by rmoff** [comment]
The two `Dockerfile` are identical in Github master and the 3.2.3 release zip I downloaded: 

```
$ git remote -v
origin  git@github.com:opensourcepos/opensourcepos.git (fetch)
origin  git@github.com:opensourcepos/opensourcepos.git (push)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ diff Dockerfile ~/Downloads/opensourcepos.20180613210031/Dockerfile
$ diff database/Dockerfile ~/Downloads/opensourcepos.20180613210031/database/Dockerfile
$
```

Is there a different file I should be rebuilding from? Thanks.

**Comment by rmoff** [comment]
```
$ diff docker-compose.yml ~/Downloads/opensourcepos.20180613210031/docker-compose.yml
6c6
<
---
>
12d11
<
32c31
<         image: mariadb:10.3.9
---
>         image: mariadb:10.1.21
42,53d40
<
< #    phpmyadmin:
< #        image: phpmyadmin/phpmyadmin
< #        restart: always
< #        ports:
< #           - "8000:80"
< #        links:
< #            - mysql:mysql
< #        environment:
< #            - MYSQL_USERNAME=admin
< #            - MYSQL_ROOT_PASSWORD=pointofsale
< #            - PMA_HOST=mysql
$
```

Tried starting it up anyway with the docker-compose.yml copied from `master`. Same problem.

**Comment by daN4cat** [comment]
That's strange, I need to check if something else is missing.
I use myself and there is no issue with latest master.

**Comment by daN4cat** [comment]
@rmoff can you please change this line in application/config/config.php to be:

$config['base_url'] = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') || (isset($_ENV['FORCE_HTTPS']) && $_ENV['FORCE_HTTPS'] == 'true')) ? 'https' : 'http';

**Comment by rmoff** [comment]
It has that exact code already.

**Comment by daN4cat** [comment]
That was changed a month ago, how can 3.2.3 have that? Something doesn't add up...

**Comment by daN4cat** [comment]
3.2.3 was released 4 months ago.

**Comment by daN4cat** [comment]
New Docker files in master and coming with 3.3.0 uses an nginx reverse proxy solving the https and offering a free certificated solution upgrading itself in automatic way.

I will need to do some writing to document what to do with that.
