### ISSUE TITLE
Please Help : common_$$$$$$ (TBD)

### ISSUE THREAD

**Issue by Ibnumarjan** [opensourcepos/opensourcepos#2171]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

(X)- [] Reporting an issue of an unmodified OSPOS installation
(X)- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
(X)- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
(X)- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
(X)- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
(X)- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
(X)- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.6.23
- MySQL or MariaDB version is: 10.1.13
- OS and version is: Windows 10 Pro 64 bit
- WebServer is: Apache 2.4.17
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: XAMP

### Issue / Bug  / Question / New Feature
when I login it comes with common_welcome_message (TBD) all buttons as module_customers (TBD) as example.
![login](https://user-images.githubusercontent.com/19687579/46461174-abddb880-c7db-11e8-86da-629d43a599dd.JPG)
![common](https://user-images.githubusercontent.com/19687579/46461175-ac764f00-c7db-11e8-9d9b-8c6e4a905dca.JPG)
![common](https://user-images.githubusercontent.com/19687579/46461211-bf891f00-c7db-11e8-9f2b-10ae8df47310.JPG)

**Comment by odiea** [comment]
What is your selected language and did you download it from bintray.

**Comment by SteveIreland** [comment]
Navigate to the localization tab of the configuration option and select your language then click on save.

Then log off and log back on and you should be back to normal

**Comment by Ibnumarjan** [comment]
Thanks SteaveIreland,  it works.

Thanks odiea, I downloaded from master.
