### ISSUE TITLE
try to install a branch from item-attributes (noob alert)

### ISSUE THREAD

**Issue by danersan** [opensourcepos/opensourcepos#2176]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: phpmyadmin 4.7.7
- OS and version is: 
- WebServer is: online hosting
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Im pretty new in github, but i'm interested to get this open source pos for my startup business
i already follow the instruction to download and install, its working great on my hosting, but it different with the demo ( especially for adding custom attribute)

Then i already searching for days to download the branch of the "item-attributes" (https://github.com/opensourcepos/opensourcepos/tree/item-attributes) 

Finally i can download it successfully with this code: 
git clone -b item-attributes https://github.com/opensourcepos/opensourcepos.git

But when i try to install the app in my hosting, it return as follow
"Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php"

please can you guys help me how to install exactly like the demo was?
or maybe i just got wrong step to download the file?
Please help me

Thank you

**Comment by jekkos** [comment]
Hi,

you can download a working version from bintray for this branch. Beware that it is under testing and thus might contain bugs. If you find any you can report back here ofcourse.

**Comment by jekkos** [comment]
Here a link to the latest build (8 hours ago)

https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20181010225006.item-attributes.8e2bcb.zip

**Comment by daN4cat** [comment]
Please help with the test
