### ISSUE TITLE
E Commerce / Licensing 

### ISSUE THREAD

**Issue by divescheduler** [opensourcepos/opensourcepos#2177]
###  New Feature

I am looking for a POS tool that I can integrate into our current scheduling tool.   I have 2 questions for you below.

1.	Can you make the items available in a public eCommerce tool?  Allow customers to search, select and pay for items?  We want customers to be able to embed the shopping into their existing HTML or WP websites.  If not for a donation could you add it to your POS?

2.	I see in the terms and conditions that the open source pos must stay on the pages.  Could we make a donation for modified terms that would allow us to remove it?

We are very supportive of open source communities but our primary product is managing Scuba Trips and Courses.  Our customer base is asking for POS as an add-on to the products.  We would like to figure out a way that this can work for both of us.  Please let me know your thoughts.

**Comment by jekkos** [comment]
To me it's not exactly clear what you want to accomplish.
1. integrate ospos in a wordpress site sounds a little weird. I think that would make sense if you eg would want to sell through a webshop then you'd better look at existing wordpress plugins like woocommerce or the like .Beside that I don't see any benefit in cramming the project into a wordpress environment

2. The license is what it is. People have asked this before and the answer is mostly negative/ Why would you want to claim this work to be your own? I don't think that would be fair wrt all the people and hard work that was put into it here

Beside that the license is very generous. The only real restriction is to keep the footer which is in my opinion an important one as it gives credit where credit is due.

**Comment by divescheduler** [comment]
I would like to find a web based pos that will also allow for e-commerce. I want customers to be able to go the the website and search and purchase some or all the items. I would like to be able to choose limit items that appear based on if item is in stock or out of stock as well as limit by category. 

We also need to be able to make the POS software multitenant. And maintain a single site that will be able to support multiple companies.

As for the license I agree that is is very generous licensing agreement. Many other software offer a freemium model. For the free there are advertising. Of there is a pay option that eliminates advertising I would be open to paying for a license and either an annual maintenance to get updates or a royalty for a percentage of pos revenue. 

Thanks,


Sent from my mobile device
 
Chris Higgins
DiveScheduler.com
608-571-3483

**Comment by SteveIreland** [comment]
Sounds like OSPOS isn't a good fit for your requirements ... not even close.

**Comment by daN4cat** [comment]
Indeed, OSPOS is not an ecommerce solution.

**Comment by SteveIreland** [comment]
I believe so.  They retained the OSPOS licensing info.  It's an interesting branch.
