### ISSUE TITLE
Wrong Chinese language code

### ISSUE THREAD

**Issue by landall** [opensourcepos/opensourcepos#2183]
### Background information
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: f1cf3d3c87c82c48e453b34e574570980cd394de
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: Chinese
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

The Chinese translation of OSPOS is not Chinese(zh) but Chinese T(zh-TW).
Most Chinese use zh-CN (the correct code is zh-Hans) and a little part use zh-TW (the correct code is zh-Hant). I think OSPOS should treat Chinese as two translations.

ref: https://www.w3.org/International/articles/language-tags/

**Comment by odiea** [comment]
Thanks for your input. If you would like to help out please scroll down to the following on the front page and sign up to include the proper language.
Language Translations
To help us with OSPOS translations please use Weblate website here and sign up. After registering you can subscribe to different languages and you will be notified once a new translation is added.
Please also read the wiki page here to find our Translations Guideline.
Only with the help of the community we can keep language translations up to date.
http://translate.opensourcepos.org/

**Comment by landall** [comment]
i am trying. is there any docs to define the concept and models? i cannot confirm how to translate some key words

**Comment by odiea** [comment]
I am hoping someone who has added or updated a language will assist. I have not had the pleasure of adding one.

**Comment by SteveIreland** [comment]
The language code definition file includes the following.  So I would assume that we could just copy  one of the existing folders over.  I'm not sure of what the impact is on Weblate.

- zh	Chinese
- zh-CN	Chinese (S)
- zh-HK	Chinese (Hong Kong)
- zh-MO	Chinese (Macau)
- zh-SG	Chinese (Singapore)
- zh-TW	Chinese (T)

The locale_help file only includes support for zh as shown  below, but it doesn't look like it would take much effort to throw in another translation.  The work is in the actual translation effort.

'zh:simplified-chinese' => 'Chinese'

**Comment by landall** [comment]
in fact there should not be a language file named zh which is a language family.
only zh-Hans and zh-Hant.
zh-Hans stands for zh-CN and zh-sg.
zh-Hant for zh-TW and zh-HK.

**Comment by SteveIreland** [comment]
I see that you forked the OSPOS repository.  Will you be contributing the change?

If not I'll be happy to replace zh with z-Hans and zh-Hant

A warning though ... I do not speak Chinese ... being from Texas I have enough trouble with the Yankee variant of NorthAmericanese.

**Comment by landall** [comment]
@SteveIreland. it is better to replace it by u. i used to subversion and need some time to learn how to pull request and rebase by git.

**Comment by landall** [comment]
> Thanks for your input. If you would like to help out please scroll down to the following on the front page and sign up to include the proper language.
> Language Translations
> To help us with OSPOS translations please use Weblate website here and sign up. After registering you can subscribe to different languages and you will be notified once a new translation is added.
> Please also read the wiki page here to find our Translations Guideline.
> Only with the help of the community we can keep language translations up to date.
> http://translate.opensourcepos.org/

I cannot login to weblate by oauth of Github.... :-(

Request URL: https://weblate.jpeelaer.net/accounts/complete/github/?redirect_state=6eNrTF5l7L1C00zyubCo6rTYHuDPUlxe&code=*****************
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 188.166.59.126:443
Referrer Policy: origin

**Comment by landall** [comment]
@SteveIreland @odiea Can you help me to add new language definition Chinese Simplified(zh_Hans) in admin panel of weblate? I want to start to add Chinese Simplified translation to weblate.

**Comment by SteveIreland** [comment]
I'll go ahead and submit a pull request for it tonight.   I'm guessing that it has to be merged into master before Weblate can do its thing with it.  

I tried to log in to Weblate a couple of days ago but was also getting system error and was unable to complete the login.   I believe that  @jekkos will need to advise on that issue.

**Comment by SteveIreland** [comment]
The depoyment zip for the pull request for this issue is found at
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20181031005606.chinese-lang.42a69e.zip

**Comment by SteveIreland** [comment]
I didn't include a migration for this.  If someone doesn't see what they are expecting for the language then they can go to Office > Config > Localization  and change the Language setting  to what they want.

I copied "zh" to "zh-Hans" and "zh-Hant"and then dropped the "zh" set.  So if it was set to "zh" that will no longer work.  It will be an invalid setting.

**Comment by jekkos** [comment]
Ok but what would happen in case you have an invalid config? I think it will now fallback to english

**Comment by SteveIreland** [comment]
I think that behavior should be fine.  SInce it is merged I'll go ahead and close.

**Comment by landall** [comment]
http://translate.opensourcepos.org/ is down again?
