### ISSUE TITLE
Git issue with LICENSE

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2186]
I'm trying to rebase the India GST branch over the master branch and the LICENSE folder is getting in the way.  I can't complete a rebase because of this and was wondering if someone could take a look at it.  I haven't made any changes to it, so it's definitely something coming in as a result of merging the master branch.

It acts like it's something that I've changed but it won't let me commit it, stash it, or revert it.  (It pretends it does but it magically reappears.)  

Any suggestions?

![image](https://user-images.githubusercontent.com/23066623/47057361-4354eb00-d18e-11e8-8e81-e815262ee2ff.png)

**Comment by SteveIreland** [comment]
I'm sure it's not related, but I thought it was interesting.  When I unzip the zip file downloaded from the master branch I get an error on the zip file.  Damned annoying license file.  :-)

![image](https://user-images.githubusercontent.com/23066623/47088321-32d35d80-d1ec-11e8-94cf-c4936afdfae4.png)

**Comment by odiea** [comment]
I believe this issue came with the Attributes merge.

**Comment by daN4cat** [comment]
That folder should not be there...

**Comment by SteveIreland** [comment]
Okay, it's gone now.
