### ISSUE TITLE
composer.json change for attributes

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2189]
In attribute.php the statement `const DEFINITION_TYPES = [GROUP, DROPDOWN, TEXT, DATETIME];` isn' t supported in PHP 5.5 so I had to change composer.json to start with version 5.6

Is that what was expected?  Hopefully there isn't a reason that we have to maintain support for 5.5.

`"php": "^5.6 || ^7.0",`

**Comment by SteveIreland** [comment]
This is included in the India GST project, so if you're not in a hurry we can just let it happen when this is finally merged.

**Comment by jekkos** [comment]
Changed this version in composer.json and in README and install instructions.
