### ISSUE TITLE
Error when adding a new item ... count method requires countable object.

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2190]
I'm out of time to chase this one down so I thought I'd go ahead and report it.
When adding an item I encountered the following error message.

Using PHP 7.2.4 and MariaDB 10.2.14

Message: count(): Parameter must be an array or an object that implements Countable
Filename: models/Attribute.php
Line Number: 130

Backtrace:

File: C:\vroots\ospos1\application\models\Attribute.php
Line: 130
Function: _error_handler

File: C:\vroots\ospos1\application\controllers\Items.php
Line: 419
Function: get_values_by_definitions

File: C:\vroots\ospos1\public\index.php
Line: 315
Function: require_once
Attribute Name

**Comment by odiea** [comment]
I found this on the web and it appears to work. Try it and see.
Line 130: if(count($definition_ids ? : []))

**Comment by SteveIreland** [comment]
Thanks @odiea. I think you nailed it because I haven’t added any attributes yet
