### ISSUE TITLE
Supplier none

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2192]
In the latest version of ospos there are two types of supplier category, Goods Supplier and Cost Supplier. But in item I can only add a supplier category, the Goods Supplier category. if i keep my supplier as a cost supplier, the supplier is not reflected in items.

**Comment by odiea** [comment]
This may change once the supplier merge is completed.

**Comment by odiea** [comment]
Also the goods supplier is for Items and the cost supplier is for the cost of doing business. Such as Utilities.

**Comment by daN4cat** [comment]
Cost suppliers are for expenses.
