### ISSUE TITLE
Issue with updating india-gstbranch

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2197]
Hi @jekkos I am trying to update the india-gst branch.  

git says the push was successful but when I check to confirm the update it appears to have been backed out.

So I thought I'd try to delete the branch and upload a fresh one - but I can't delete the branch because the pull request is still open.

So I go to close the pull request and for about 3 seconds it tells me the pull request is closed.  Then if I refresh the page it is miraculously open again.

Apparently I have the permission to add a new branch but I don't have permissions to update and delete.

Can you delete it so that I can upload  my changes?

Thanks!

**Comment by SteveIreland** [comment]
Ignore.  Turns out that github was having a crisis for a few hours

**Comment by SteveIreland** [comment]
Ignore

**Comment by jekkos** [comment]
ah ok sorry didn't see your last message, I went ahead and remove the branch? Can you push it again? sorry for the inconvenience

**Comment by SteveIreland** [comment]
No problem.  I need to rebase it over the latest updates to master anyway.  I was going to do that tonight or tomorrow night.  I felt like I was living in the twilight zone last night.  I would update something, see a confirmation, refresh the page and it was gone.

**Comment by SteveIreland** [comment]
They still haven't totally caught up so I'm still a bit paranoid about doing anything.
