### ISSUE TITLE
There are no Expenses to display. 

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2198]
With the last update of OSPOS that was edited about 14 hours ago, I have this problem. In the expenses section I have this message: There are no expenses to display. I did a test with a new db and everything works fine,
![deepinscreenshot_20181021224345](https://user-images.githubusercontent.com/29256343/47279320-56e8c300-d58d-11e8-8b74-d24ed936fe7b.png)
![deepinscreenshot_20181021224353](https://user-images.githubusercontent.com/29256343/47279308-459fb680-d58d-11e8-86af-800e286e0b29.png)

 the problem is in the db that already has expenses and does not show them on the screen nor does it allow to create other expenses.
![deepinscreenshot_20181021224313](https://user-images.githubusercontent.com/29256343/47279334-7253ce00-d58d-11e8-8d65-ab1c1ccca743.png)
![deepinscreenshot_20181021224320](https://user-images.githubusercontent.com/29256343/47279353-9fa07c00-d58d-11e8-87cb-8235a81693dc.png)

**Comment by odiea** [comment]
I think the migration may not be working properly to upgrade your old database. Please check your db and see if the following have been installed.
```
ALTER TABLE `ospos_expenses`
  ADD COLUMN `supplier_id` int(10) NULL;

-- Link suppliers

UPDATE `ospos_expenses`
  INNER JOIN `ospos_suppliers`
    ON `ospos_expenses`.`supplier_name` = `ospos_suppliers`.`company_name`
SET `ospos_expenses`.`supplier_id` = `ospos_suppliers`.`person_id`;

-- Save name in description for those expenses whose supplier isn't registered

UPDATE `ospos_expenses`
SET `description` = CONCAT(`description`, CONCAT('\nSupplier name: ', `supplier_name`))
WHERE `supplier_id` is NULL;

-- Add foreign key

ALTER TABLE `ospos_expenses`
ADD CONSTRAINT `ospos_expenses_ibfk_3` FOREIGN KEY (`supplier_id`) REFERENCES `ospos_suppliers` (`person_id`);

-- Delete supplier name

ALTER TABLE `ospos_expenses`
DROP COLUMN `supplier_name`;
```
