### ISSUE TITLE
Question for supended sales and partial payment

### ISSUE THREAD

**Issue by tekkeur** [opensourcepos/opensourcepos#2199]
Hello,
Have a qstion.
1 - Scenario, User1 suspended a sale, then User2 unsuspend, add payment and complete the sale.
My question, would it be possible or is there a way to have the username that suspended the sale and the one who complete it?

2 - Is this OSPOS able to make a partial payement? (payment facilitation, goes from 3 to 4 payment for an item)
Thanks

**Comment by odiea** [comment]
Please refer to #1811 #24 #1971 #1429 #68 #2103. Thanks @WebShells

**Comment by daN4cat** [comment]
Point 1 is not supported.

**Comment by nathanzky** [comment]
> It doesn't answer my question 1 but thanks anyway for the info, it's useful.

Maybe this reference can help #2055
