### ISSUE TITLE
How come the demo doesn't have Cashups and Attributes yet?

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2204]
Just wondering,  I thought demo always at least reflected what was in master.

**Comment by SteveIreland** [comment]
I see that master was rebuilt about 6 hours ago in bintray but demo doesn't look to me like it has caught up.  Must be failing somewhere.

**Comment by WebShells** [comment]
True Steve, noticed that period ago but thought its reflecting latest release... Maybe stuck somewhere as you said...

**Comment by jekkos** [comment]
Server disk was full, is fixed now.

**Comment by odiea** [comment]
Back to showing previous Master

**Comment by SteveIreland** [comment]
Wow ... it sure is.    It doesn't even include the Chinese language fix that was applied last night.

**Comment by jekkos** [comment]
If you want a specific branch on demo, just trigger again the build in travis-ci, which should then call the hook to redeploy

**Comment by SteveIreland** [comment]
Thank you.
