### ISSUE TITLE
CSV file format for item import

### ISSUE THREAD

**Issue by aldrenalin** [opensourcepos/opensourcepos#2205]
As a newbie here I'm stumbling on some apparent inconsistencies with the required csv file format.

At 
https://github.com/opensourcepos/opensourcepos/blob/master/import_items.csv
dated Oct 15, 2018, the format is given as 
Barcode	
Item 
Name
Category
Supplier ID
Cost
Price	
Unit Price
Tax 1 Name
Tax 1 Percent
Tax 2 Name
Tax 2 Percent
Reorder Level
Description
Allow Alt Description	
Item has Serial Number
item_image
location_id	
quantity

However, this is inconsistent with 
 https://github.com/opensourcepos/opensourcepos/wiki/Import-data-from-CSV-file#importing-items
 dated Sept 1, 2018, where the format is
 
 0 - barcode
1 - item name
2 - category
3 - supplier id
4 - cost
5 - price
6 - tax 1 name
7 - tax 1 rate
8 - tax 2 name
9 - tax 2 rate
10 - reorder level
11 - item description
12 - allow alt description flag (1 to allow, otherwise keep this blank/empty)
13 - is serialized flag (1 is serialized, otherwise keep this blank/empty)
14 - custom 1
15 - custom 2
16 - custom 3
17 - custom 4
18 - custom 5
19 - custom 6
20 - custom 7
21 - custom 8
22 - custom 9
23 - custom 10
24 - item image
25 - location 1
26 - quantity 1

This is also inconsistent with an Export to csv which gives
Barcode
Item Name
Category
Company Name
Wholesale Price
Retail Price
Quantity
Tax Category
Avatar

I'm trying basic examples to import items at the demo site, demo.opensourcepos.org
but cannot, for example even successfully import the example file
https://github.com/opensourcepos/opensourcepos/blob/master/import_items.csv

I'm brand new at looking at OSPOS, overall it looks terrific. :)

**Comment by SteveIreland** [comment]
It can change with each release. In fact, in the india-gst branch it will include a new column for HSN code.  The documentation doesn't "keep up" so you should always refer to the example CSV file to determine what is supported in a particular release.

The demo site a few hours ago was built from the india-gst branch (that could change tomorrow if someone merges something into master).

**Comment by aldrenalin** [comment]
Thanks for your reply.

At present the  demo site at https://demo.opensourcepos.org reports using version 3.3.0 - 4f5ad57.
It turns out that the relevant format for import_items.csv  is :

Barcode,Item Name,Category,Supplier ID,Cost Price,Unit Price,Tax 1 Name,Tax 1 Percent,
Tax 2 Name, Tax 2 Percent,Reorder Level,Description,Allow Alt Description,
Item has Serial Number,item_image,HSN,location_id,quantity

With say some csv data of
100001,box11,boxes,,1,2,,,,,1,,,,,,1,10
it will import successfully.

Pardon my newbieness, but after some googling there doesn't seem to be an easy way to find a specific commit, 4f5ad57 in this case, 
on the github website.
Is there?

**Comment by SteveIreland** [comment]
When I first started participating I tried to chase it down once but wasn't successful myself and determined it wasn't worth the effort to nail it it down. I rebase and squash a lot so some commits are lost in that effort since they are added to a new commit.  Someone else may be able to provide some insight into where it comes from.

**Comment by daN4cat** [comment]
Changed with #2431
