### ISSUE TITLE
Languages Sync

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2206]
I noticed someone is trying to use a Turkish flavor of OSPOS in the demo and the language values are a couple of releases behind. 

It looks rather bad when the user sees variable names instead of an actual label,

Is there some reason we don't want to pre-load those values with the English equivalent until someone has a chance to translate them?  Is that a Weblate option?

**Comment by SteveIreland** [comment]
Okay.  Thanks.

**Comment by jekkos** [comment]
You can easily change that behavior in the language hook

**Comment by daN4cat** [comment]
Maybe the demo site should stick to English?

**Comment by SteveIreland** [comment]
@jekkos, @daN4cat 

How would you like me to proceed on this?  I was going to write a small script to sync up the various language files so that there is a entry for all of them and there is a value of either that language or English, but if you don't think that's the correct solution just let me know.  I'm not sure what's mean by changing the language hook.   Can the system be configured for a primary language and a backup language?  If so does that work if the language element is defined but is an empty string?

**Comment by jekkos** [comment]
I do this  kind of sync by using the old translations scripts as follows
1. First I convert all existing langauge files to CSV by using the ci-language-tool project on my github
2. Next I generate language files from these. This will add non existing lines for every language and sort them alphabetically

I think that currently the TBD label will show if either the line is not present or if it has no content, however not sure about the latter.

**Comment by SteveIreland** [comment]
Thanks for the feedback.
