### ISSUE TITLE
Minor bug in changing CurrencySymbol in localization

### ISSUE THREAD

**Issue by allenftan** [opensourcepos/opensourcepos#2207]
- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  LATEST?? (TRIED on the Demo Server)

### Bug - MINOR
The first submit for localization configuration reverts the currency symbol to default

REPRODUCING
1. Navigate to Configuration -> Localization
2. Change value of Currency Symbol to anything other than the default value
3. Submit Changes

Expected behavior - should change the currency symbol to the desired symbol of the user on first attempt
Actual behavior - the default symbol will be used on the first attempt

**Comment by daN4cat** [comment]
Thank you and well done. It's probably the first time I see a newcomer writing a well written bug report like this. Thank you for that indeed.

**Comment by WebShells** [comment]
Are you sure its the latest? The demo server wasnt mirroring latest build... I think it wS solved a while ago...

**Comment by allenftan** [comment]
Im not really sure if its latest, 
im testing 3.2.3 at home and the demo

**Comment by mckaygerhard** [comment]
i think i report same issue before, this could be caused due a double send action (that was solved) but still the saved settings are not clear; and for that settings we need to change in two steps to complety set all..

.. and good for @allenftan thaqt in a newcomer position make a firts issue very good!
