### ISSUE TITLE
Suspended sale migration can cause inconsistencies

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2208]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 up unil 3.0.2 

### Bug description

I found an issue in the suspended sales table migration. It fails if you have multiple sales in the table during migration becaues the id's in suspended_sales are not guaranteed to migrate in a consistent way.

The statements for this first append the suspended sales to the sale table with the appropriate type column. Issue is that the sale_id itself cannot be copied as it might already be taken by a sale records, so the autoincrement functionality is used.

Then next step is the suspended_sale_item migration. This will then copy all records and keep the sale_id that references the old suspended sale, but not necessarily also the newly migrated record, leading to a possible constraint violation.

What should be done here instead is
.1. Migrate suspended sale records and use an offset for generating the new sale_id (so that it does't collide with an existing sale record-
2. Migrate payemnt and item records using this updated sale_id
3. If someone has other or better ideas then post them here

**Comment by SteveIreland** [comment]
I see the issue you are referring to.  The suspended sales table itself was migrated as you mentioned but the suspended sales items and suspended sales payments were not coded in a way to pick up the new sales id. I'm surprised at my capacity to overlook issues such as this and I'm even more surprised that no one has screamed about it before now.

I'll be happy to fix this.

**Comment by jekkos** [comment]
It's not such a big issue for me, most the sales that go through suspended only stay there for a short time.

**Comment by SteveIreland** [comment]
Agreed.  I think when I originally combined the suspended sales into the sales table I was thinking that one of the prep steps would be to clear the suspended sales data before performing the migration. But I see that an effort was added to actually migrate the data which is easy enough with a temporary cross reference table.

**Comment by jekkos** [comment]
Yes I agree I will clear it for now as that is what my users want

**Comment by daN4cat** [comment]
@jekkos is this sorted?

**Comment by jekkos** [comment]
I resolved this by clearing the table contents. However a workaround should be done in which the suspended_sale_id is incremented with the max(id) of the current sale_id table by using an intermedia.e variable or table. Might not have the time to look at this before end of year.

**Comment by daN4cat** [comment]
@jekkos this is more than a year old. Still valid or should we close it?

**Comment by jekkos** [comment]
I think that clearing the table would be an acceptable solution: sales that stick for longer than one day in the suspended list are in our case not very likely to be resumed again. Unless anyone uses this functionality otherwise?

**Comment by daN4cat** [comment]
I would close, I see no traction outside your experience.

**Comment by WebShells** [comment]
@Jekkos actually yes, keeping suspended sales on hold for a longer period is somehow useful in specific cases... Prefer to be kept as it is :/
