### ISSUE TITLE
Cannot login an account except admin in live demo

### ISSUE THREAD

**Issue by landall** [opensourcepos/opensourcepos#2211]
Country: China
Happened In Live Demo from 2018.10.15-2018.10.30

Reproduce:

1. Log in as admin
2. Create a new account, only fill the red fields. Check every access with both(home and office).
3. Logout
4. Input the account id and password

Result: Invalid Username or Password.

**Comment by odiea** [comment]
Yes that was put into place so that the site would not be hijacked by a bad user.

**Comment by odiea** [comment]
A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: core/CodeIgniter.php

Line Number: 518

**Comment by jekkos** [comment]
Weird, tried to figure out why all of a sudden the containers were not able to connect anymore. I guess it must have been the docker networking gone awry. Redeployed and should be all good now.

**Comment by SteveIreland** [comment]
Even weirder, when you redeployed it the deployed the version not only does not include the india-gst changes but it doesn't include the attribute changes.
