### ISSUE TITLE
I want to add show "custom field" in the items list but i dont know what file i need to edit

### ISSUE THREAD

**Issue by wmardain** [opensourcepos/opensourcepos#2218]
Dear All, 
I use ospos 2.2.1. 
I want to add custom field to show the "weight" for every items. 
And i want to display this on the items without clicking detail of each of item . I just want it to be displayed just like "price".

Could you please help me which files i need to edit?
i already see other can do this with sales register but for "items" i need to make sure i edit the correct files.

Thanks and Regards

**Comment by SteveIreland** [comment]
You have probably already figured it out by now, but here is something for you.

2.2.1 pre-dated me, but it most likely requires changes to two files:  .../helpers/tabular_helper.php and .../models/Item.php

**Comment by SteveIreland** [comment]
Obviously you need to change the view to add the column you want - but I figured you knew that.

**Comment by mridul611** [comment]
Here's the detailed instructions of adding custom field to items - https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-DEVEL-Add-a-custom-field-to-the-Sales-Register

**Comment by SteveIreland** [comment]
That is an answer to a different question.

**Comment by jekkos** [comment]
In 3.3 master there are the attributes that replace this functionality

**Comment by wmardain** [comment]
Hi..
Thanks for your response. 

> You have probably already figured it out by now, but here is something for you.
> 
> 2.2.1 pre-dated me, but it most likely requires changes to two files: .../helpers/tabular_helper.php and .../models/Item.php

No. I havent figured it out. So you suggest me to replace those files? or to change it.. which part? And if i have to change the file.. which ones i should copy and which one i need to append with these.. 
and if i replace these.. can it still work for my version? (compatible) ?

**Comment by wmardain** [comment]
> Obviously you need to change the view to add the column you want - but I figured you knew that.

i have no idea to do that. I already use it since 2014.. i have around 2500 items.. so i am so afraid if i make a mistake the system will crash and we have to do manually.. oh no.. i need help for clear explanation steps to do this.

**Comment by wmardain** [comment]
Should i upgrade the version first? or i can modify it ..

Rgds

**Comment by odiea** [comment]
I updated the wiki to better show how the Custom_name is added to the Items table. Hope this helps. In the Wiki it is toward the bottom after adding a custom field to the register view.

**Comment by odiea** [comment]
This is how the table appears after custom item is added to the table after Company Name.
![2018-11-03 09_50_02-window](https://user-images.githubusercontent.com/10962177/47954278-03dc1c00-df4e-11e8-89f4-7bc66c96744a.png)

**Comment by SteveIreland** [comment]
oh.   I had to read the WHOLE page.  Oops.   My bad.
