### ISSUE TITLE
Default Attributes Option

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2221]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 465a2c
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.7.2
- OS and version is: FreeBSD 11.0
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug
New attributes do not appear by default in the item and have to be added individually.  I've also noticed this with new items that by default have no attributes assigned to them.  For example, I created a DROPDOWN field and gave it selections, but in order to populate the items already in existence with this attribute I first need to edit the field, click the drop-down next to "Attribute Name" and click the attribute for each item before it will appear in the list of attributes below.  We have 15k items in our database, so the extra work involved with adding a single attribute that we want to apply to all items is a little unwieldy.

One way that we may be able to tackle this is to have a checkbox for each attribute to "Apply to all Items" which when checked automatically makes the attribute visible in all items.  I recognize that some will want some attributes to not appear in all items by default, but I'm guessing that 99.9% will want at least some attributes to appear in all items.

Thoughts.

**Comment by jekkos** [comment]
So in this case you want to link the definition to the item but without assigning a value to it?

**Comment by objecttothis** [comment]
Correct. Here is why: Let's say I'm going to add a product and in 90% of products 7 out of 10 of the same attributes always exist. Currently in order to create the item for each attribute you have two extra clicks and a dropdown navigation.  Even across 30 items being created this is a lot of extra work.  If the attribute definition had a checkbox to allow "default" attributes, that would allow the administrator to tell the attribute to appear for each item at item creation and avoid the extra work.  In short this translates as the same functionality that custom fields was providing with the advantage of having the option to make none or some of the attributes appear by default.

**Comment by jekkos** [comment]
Ok I see what you mean. How do you create a batch of new items exactly?
If I'm not mistaken then in new item there should be two buttons, new and submit. If you click the first then I would want to have the attribute selection stay where it was.

**Comment by objecttothis** [comment]
@jekkos your suggestion of a new and submit button makes sense, but it does still require a good amount of extra work for my staff since before when creating a new item it was "tab", enter data, "tab" enter data. With not having default attributes data entry involves a lot more switching between mouse and keyboard to create the same item.

What I'm suggesting is having a boolean in the attribute definition where TRUE makes it a "default item attribute" and therefore when new items are created appear by default.  Further we can reduce junk data in the database by having the logic that creates the attributes and links them to the items simply not create an attribute if the user leaves the field blank.  If we go the "default item attribute" flag route, I can implement it.

**Comment by objecttothis** [comment]
We could even put a tooltip on the checkbox for the attribute settings page that explains that when the "Default Item Attribute" setting is checked it will automatically appear at creation of a new item.

**Comment by jekkos** [comment]
Made a pull request that might solve your issue when adding new items in batch.

**Comment by objecttothis** [comment]
I'm testing it now.  My database is upgrading now, so I'll confirm that it is resolved as soon as that is done.

**Comment by objecttothis** [comment]
So, if I understand correctly what you committed, I click the New Item button, then add attributes and data.  If I click Submit, it will close the window and add the item.  If I click  New it will create the item, but not close the Window so that another item can be added.  If my understanding is correct then this works.

The option of a button allowing you to add an item then immediately add another product is handy and I think it should be kept regardless, but there are a couple of problems with this approach:
- When "New" is clicked the item gets added and the window left open but all the data remains from the previous item in the fields.  I think it would be better to clear each of the field values but leave the attributes in place.  This way there isn't risk of stale data in the next item when it gets created.
- There is still the problem of having to add each of the attributes the first time.  What I'm suggesting is having a database boolean in the attribute definition for whether it's a "default attribute" which would cause it to automatically appear in the item creation window and therefore reducing time needed to create a new item back to closer to what it was before the attributes migration.

One thing that likely should be in place is that during item creation in the database if an attribute field is NULL or "" then it doesn't get created in the database.

Feel free to assign all this to me if it make sense to you to do it.  The enabling of items as a "default attribute" would be set to false for default to accommodate those that don't want to use the feature, but checkable for those that do.

**Comment by WebShells** [comment]
I agree with @objecttothis for keeping attributes field selected and releasing all other data.
 Less time for data entry...

**Comment by objecttothis** [comment]
This is a duplicate of #2817
