### ISSUE TITLE
How to add attributes in Excel Item import?

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2223]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 465a2c
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.7.2
- OS and version is: FreeBSD 11.0
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question
So now that we have migrated to attributes from custom fields, how do we include these attributes when importing items using the CSV import feature?  With custom fields there was a column for each custom field which allowed custom fields to be optionally populated.  The current csv template has those removed and does not have any attributes columns in their place.  So can the user just add those columns by name and have them get imported and assigned?

**Comment by jekkos** [comment]
Good point, this system for import was not adapted for attributes. Basically what it should do is add an attribute for the last unmapped column name and then subsequently add the values as a text entry in the attribute_values table.

**Comment by jekkos** [comment]
so an idea here might be that we map to an attributes column if the column name is the same as an existing definition? In that case the user will have to define the definition names first.

**Comment by jekkos** [comment]
unless we make this generic and create attributes as soon as an unknown column name is present?

**Comment by jekkos** [comment]
Ok I got your point. In my case I migrated all the data using SQL, but that might not be feasible for an average user. Indeed I think it's probably best to have them configure the attributes upfront. Next we can generate a csv template based on that configuration.

Afterwards some minor validations can be done (like when you import dropdown values, you should use only those values that were configured).

**Comment by objecttothis** [comment]
@jekkos I would say that the users should create all attributes prior to doing a CSV import.  

- When an attribute is created the code should modify the CSV template file to append that attribute name onto the header list.  
- When an attribute is deleted the code should modify the CSV template file to delete that attribute from the header list.
- When a CSV import is performed, the import should match the header to the attribute and use that to 1. Check to see if the attribute_value exists and add it to the attribute_values table if it doesn't.  If the attribute_type is a DATETIME then the check should be to see if the attribute_datetime exists and add it if it doesn't
2. Create the row in the attribute_links table

I think that we should assume, for now, that the data in the CSV is properly formatted.  I think there is a separate issue that was created to address the question of what to do when data is not properly formatted.

**Comment by jekkos** [comment]
Ok agree on the requirements here. The column headers in the excel should match the definition name then. Personally I migrated all my attributes through SQL but that might not be very suitable for an average user.

**Comment by objecttothis** [comment]
Hi everyone.  I'm finished working on the functionality to add, remove and rename column names when attributes are added, removed and renamed.  GROUP type attributes are ignored since you won't ever import a GROUP.

There are two remaining aspects to deal with now.  One is the actual parsing of CSV files, which should be fairly straight forward.  The other I need some input on: 

- The attributes migration 20181015100000_attributes.php kicks off the sql which converts the custom fields to attributes.  At this same time php needs to run to create the same column titles in the import_items.csv or we will end up with up to 10 attributes without columns in the import_items.csv which isn't good.  Am I correct in my assumption that the php legwork to modify the import_items.csv for this attributes conversion needs to happen in the up() function of the 20181015100000_attributes.php?

@opensourcepos/org thoughts?  My current work is in the attributes_csv_import_integration branch.

**Comment by objecttothis** [comment]
OK, I've modified the 20181015100000_attributes.php to also add the custom field names to the import_items.csv just before the migration.  Don't worry, I didn't touch any pre-existing migration SQL scripts.  ;)

I've tested it and it ignores blank custom fields which is the same behavior that the SQL migration script is exhibiting.

Now I will start working on the last piece that imports attributes when they are included into the import_items.csv file.

**Comment by objecttothis** [comment]
@jekkos @daN4cat we need to discuss how to adjust the do_excel_import() function in the Item Controller to accommodate attributes importing.  
- One thing, is that we are currently assigning values based on column position.  Do we want to continue doing this or do we want to assign them based on column name.  The advantage of column name is that the order won't matter and there is a little bit more clarity in the code.  The disadvantage is that if the column name of an attribute is the same as the column name of a column in the items table, it could introduce problems.
- Currently the count of the number of columns is hard coded at 23.  I think this needs to be modified to be pulled from the database or from the file itself.  If we pull it from the database, then we are guaranteed to get a correct number of columns because the count will differ based on the number of attributes that are not of type GROUP.

**Comment by objecttothis** [comment]
In general the do_excel_import() function is a bit of a monstrosity.  Does anyone have problems with me refactoring several of the sections into smaller functions?

**Comment by objecttothis** [comment]
Since both the Attribute model and the Item Controller will be relying on some of the same functions and code to import or alter the csv files I am thinking about creating a custom helper csv_helper.php and including it in the autoload.php to consolidate code a little.  For example, both could use the get_csv_file() function that I created in the Attribute model and there will be likely a dozen or so functions that can easily get lumped into the helper with some of them potentially being used by multiple controllers/models.  Thoughts?

**Comment by objecttothis** [comment]
So, I'm starting to understand better the difference between a Controller and Model. Based on what I'm reading is that the Model is supposed to include functions that interact with the database.  With that in mind, the functions to do the import_items.csv manipulation either belong in a helper or in the Attributes Controller.  I'm a little confused about whether I should be calling controller methods from the model, or is my scope of the model too narrow when it should not just include database manipulation methods but data manipulation methods in general?  If that is the case then the csv file manipulation functions are fine in the model.

**Comment by daN4cat** [comment]
Models are not supposed to call Controllers. It goes Controllers -> Models

**Comment by daN4cat** [comment]
Models are about any data interfacing.

Just a thought, maybe excel is something to be encapsulated in a Model.
Model can call another Model.

**Comment by objecttothis** [comment]
Yes, then I was correct to place those functions in the model. So then the do_excel_import should not be in the Item Controller since that is data interfacing? Another question is whether I should create another custom helper since both item and attributes make use of the CSV manipulation functions.

**Comment by daN4cat** [comment]
Would make sense to have an helper for common functionality.

**Comment by jekkos** [comment]
well yes a helper or perhaps just a couple of external classes. The latter might be easier for testing even.

**Comment by jekkos** [comment]
basing the import on column name might make it more robust if new columns are added later on. Also the code will look better. So feel free to tackle this issue there. Also some basic unit tests would be nice if you split up in multiple function( but maybe I should provide an example on how to do that)

**Comment by objecttothis** [comment]
@jekkos @daN4cat OK, I am working on reworking the code so that it imports as an associative array and refactoring to clean up the code.  Here's something that needs to get decided.  Currently it appears that the rightmost columns the code is looking at to see columns in a location_id/quantity pair.  This creates a problem with attributes that get added and removed to the right columns after the location_id/quantity pairs.  Here is what I would like to propose:

- Me work into the stock_location code to have it add a single column to the item_import.csv titled location_[insert location name]. In that column you would then have the quantities at that stock location.
- In that same code when a stock location is deleted it would remove the column from the CSV file.

Doing this would provide a few advantages:
- It would reduce columns associated with a single stock location from 2 to 1.
- adding the prefix (location_) distinguishes it as a stock location and makes it easier for the user to know which one that is rather than needing to know the sock_location_id
- It eliminates incompatibility between varying numbers of stock locations and attributes in processing the items_import.

This actually should be fairly easy because I refactored the functions needed to do this into a custom helper.  In general I think we should make it so that users never need to manually add columns to the CSV import template.  They only need to use it as provided.

**Comment by objecttothis** [comment]
One other thing is that we need to do a one-time migration for existing stock locations to be added into the items_import.csv file.

**Comment by objecttothis** [comment]
We also need to work into the install instructions to not overwrite the items_import.csv during upgrades.  I'm not sure how best to do that.  @jekkos @daN4cat thoughts?

**Comment by jekkos** [comment]
your proposal for the rework sounds fine to me. Regarding install instructions, do you mean that we will want to generate the template based on what is in the database now then?

**Comment by objecttothis** [comment]
@ jekkos I was more referring to any wiki or readme with install instructions

**Comment by jekkos** [comment]
Ah yes, would be good to add a bit of documentation. That works the best way if we link to it directly from the application itself imo.

**Comment by objecttothis** [comment]
Yes.  I have dreams of an automatic updater.  I know that several of you use Docker, but it would be nice to have a standalone updater that would pull the latest stable release (on the user's request) and walk users through the update as its doing it... same with a standalone installer.

**Comment by objecttothis** [comment]
@jekkos @daN4cat OK, I've submitted my changes in a pull request #2431 so let me have you guys take a look at it.   This ended up being quite involved because it meant reworking the code to have not just attributes updated in the import_items.csv when changes were made in OSPOS but also to do the same thing for stock locations.  Stock locations now works in the import_items.csv a little bit differently than it did before.

Before there were two columns for each stock location.  One required the ID of the stock location and the other for the quantity at that stock location.  Now each stock location has a column with "location_[stock_location_name]" as its header and each row would contain the quantity at that stock location.

**Comment by jekkos** [comment]
This one was sorted (PR merged). Thanks @objecttothis for the contribution!
