### ISSUE TITLE
Attributes don't appear in items table column dropdown after migration from custom fields

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2224]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 465a2c
- PHP version is: 5.6
- MySQL or MariaDB version is: MySQL 5.7.2
- OS and version is: FreeBSD 11.0
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue

As per #1909 I'm creating a new issue for this one.  After the migration from custom fields to attributes if I go into items and then click the dropdown in the upper right corner to select which columns to appear in the table, none of these migrated attributes are listed to select.  New attributes that are created do get added to this list, so I think that something to do with the migration script is not doing whatever is necessary to make migrated custom fields appear in the list of columns to add.

**Comment by jekkos** [comment]
Did you check the flags on the migrated attribute definitions? Do they have items module enabled? I suppose that this behavior should change as it was like this before, we should show the field if there was a custom column defined for it before.

**Comment by objecttothis** [comment]
Flags are all set to zero.  What flags do what in this column?  I see a flag of 7 on newly created ones.  Is there documentation on the flags currently?

**Comment by objecttothis** [comment]
I manually set the flags on the migrated attributes to 7 and they become selectable in the column dropdown.  Without documentation, I don't know what the 7 flag represents, but I think we should set the migrated definition to visible by default in the items table.  

Also, I noticed a mild formatting issue that the "update inventory" and "inventory count details" icons get pushed to the middle when custom columns are selected (see screenshot).  Those, by default should probably always appear on the right next to the "update item" icon.

![itemstable](https://user-images.githubusercontent.com/17935339/48548628-e496a480-e8e6-11e8-9a15-6aa0ea6a52fe.jpg)

We might want to create a different issue for this because its related but not the same thing, but I think we should allow changes to the order of the columns somehow.

**Comment by jekkos** [comment]
Ok I changed the colunm sorting order for attributes (icons come last now). Indeed the flag visibility is 7 for show in all modules (ITEMS | SALES | RECEIVINGS) which is 1 | 2 | 3 or 111 binary which is 7.

**Comment by jekkos** [comment]
Migrated fields are by default only visible in items now

**Comment by jekkos** [comment]
@objecttothis can you check so we can close?

**Comment by objecttothis** [comment]
All fixed.  Attributes are, by default, flagged as 1 and appear in Items
