### ISSUE TITLE
How Can I Show Customer Mobile number in Invoice

### ISSUE THREAD

**Issue by Sajibekanti** [opensourcepos/opensourcepos#2225]
Hi 
How Can I Show Customer Mobile number with an address in an invoice 
I try with change inn code 

		<div id="customer-title">
			<?php
			if(isset($customer))
			{
			?>
				<textarea id="customer" rows="5" cols="6"><?php echo $customer_info ?></textarea>
				</td>
			<?php
			}
			?>
		</div>

But Not Work , need Your Help

**Comment by SteveIreland** [comment]
I'm not clear on what you said you attempted to change, but to change what is rendered via $customer_info you "should" change the `_load_customer_data()` function in Sales.php

**Comment by Sajibekanti** [comment]
I am Sorry For That, but I try to Visible Customer Mobile Number In Invoice ,

**Comment by Sajibekanti** [comment]
V3.30

**Comment by odiea** [comment]
application/controller/sales  private_function_load_customer_data() should look like this.
```
if($stats)
			{
				$cust_stats = $this->Customer->get_stats($customer_id);
				$data['customer_total'] = empty($cust_stats) ? 0 : $cust_stats->total;
			}

			$data['customer_info'] = implode("\n", array(
				$data['customer'],
				$data['customer_address'],
				$data['customer_location'],				
				$data['customer_account_number'],
				$data['phone_number']
			));
```

**Comment by Sajibekanti** [comment]
Thanks For Reply 
I Try It but Not Work, Look Invoice Image 
http://prntscr.com/lgm299 There is No Mobile Number below Address

**Comment by odiea** [comment]
Sorry I guess I had modified my version. Here is more info that should be added. Add the phone number in the same function.
```
if($customer_id != -1)
		{
			$customer_info = $this->Customer->get_info($customer_id);
			$data['customer_id'] = $customer_id;
			$data['company_name'] = $customer_info->company_name;
			$data['customer'] = $customer_info->first_name . ' ' . $customer_info->last_name;			
			$data['first_name'] = $customer_info->first_name;
			$data['last_name'] = $customer_info->last_name;
			$data['customer_email'] = $customer_info->email;
			$data['customer_address'] = $customer_info->address_1;
			$data['phone_number'] = $customer_info->phone_number;
			if(!empty($customer_info->zip) || !empty($customer_info->city))

**Comment by Sajibekanti** [comment]
Thanks, Dude 👍  I
