### ISSUE TITLE
OSPOS and other RDBMS

### ISSUE THREAD

**Issue by Yorgocom** [opensourcepos/opensourcepos#2227]
Hello again
Another question. 

Does OSPOS support any other RDBMS besides MySQL/Mariadb? I am thinking Oracle 12c for example...(this is to benefit from Oroacle's multitenancy cb features)
We would setup apache in multitenant mode (using VirtualHost) 

Background information
IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

[] Reporting an issue of an unmodified OSPOS installation
[] Checked open and closed issues and no similar issue was already reported (please make sure you searched!)
[] Read README, WHATS_NEW, INSTALL.md and UPGRADE
[] Read the FAQ for any known install and/or upgrade gotchas (in specific PHP extensions installed)
[] Read the wiki
[] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
[] Aware the installation code is in bintray (see README), and GitHub master is for developers only and therefore not complete nor stable
Installation information
OSPOS version is:
OSPOS git commit hash is:
PHP version is:
MySQL or MariaDB version is:
OS and version is:
WebServer is:
Selected language is:
(If applicable) Docker installation:
(If applicable) Installation package for the LAMP/LEMP stack is:
Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by daN4cat** [comment]
The simple and quick answer is no.

Models are coded with MySQL SQL queries, a db change requires rewriting of all the models.

If you want to have a multi tenant solution you can have one MySQL db schema per tenant and shard MySQL dbs on different nodes (maybe using Percona distro with cluster mode, if you don't want a manual mode).
Or you can go for AWS RDS/Aurora solution to have it all high available with DR e fully maintained.

**Comment by daN4cat** [comment]
Also the code is not really multitenant at the moment, it will require some management of routing from subdomains to pick up tenant config. There is more to do to get it to be a full SaaS solution.

**Comment by Yorgocom** [comment]
Great many thanks for the input. I started reading about Percona.

Looking at it from a high level perspective, I can setup Percona for MySQL  as my RDBMS platform and host the different OSPOS databases in it. 

I would then have a layer of OSPOS installations (each in its own folder) or distributed on multiple servers and give each physical store its own URL to login to its own installation (so to speak). 

we would then code APIs from OSPOS to update the Prestashop db whenever a sale is done in the shop. I guess we would need a two way synch mechanism. 

Its not a Purists definition of multitenant setup but its close I guess. Will still need to factor the overall cost to us using multiple servers.
