### ISSUE TITLE
Rounding Tax 

### ISSUE THREAD

**Issue by w002qaa** [opensourcepos/opensourcepos#2228]
Hello Everyone,

I am selling item with price 19.90 with tax 5%. The system is rounding the tax from 0.99 to 1.00
How I can prevent the system from rounding.

Thanks

**Comment by SteveIreland** [comment]
Need much more info. In addition to the version of the software you are using I would need to know what your tax decimals configuration setting is and what flavor of taxing you are using.

**Comment by w002qaa** [comment]
Hi @SteveIreland 

I am using 3.2.3

https://imgur.com/a/pIDBItL

**Comment by SteveIreland** [comment]
Okay, I finally had a chance to spend a little time on this.  

My calculator  says that 19.90 x .05 = .995

So if "half round" is applied to .995 then you get 1.00 and not .99

Using the base tax system "half round" is baked in to the system.

I see that  you aren't using the "tax included" option so you do have the option to use the destination based tax option which will allow you to select an alternative tax rounding method.

**Comment by w002qaa** [comment]
Okay @SteveIreland 

I will try using tax included option
