### ISSUE TITLE
System doesn't validate payment types

### ISSUE THREAD

**Issue by bullmike** [opensourcepos/opensourcepos#2229]
Hello,

bug or feature request? 

There is no validation on the payment methods during the add_payment post. if value is altered via the developer tools, the payment method is added without any error. Payment methods should be restricted to valid types.

thanks
mike

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- x[] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  v3.2.3
- OSPOS git commit hash is: 
- PHP version is: 7.0.32
- MySQL or MariaDB version is: 10.3.10
- OS and version is: centos 7
- WebServer is: httpd
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by bullmike** [comment]
`
        // Multiple Payments
        public function add_payment($payment_id, $payment_amount)
        {
                $payments = $this->get_payments();

                // should be checking if the submitted type is valid
                $payment_options = get_payment_options();
                if ( in_array($payment_id, $payment_options) ) {

                        if(isset($payments[$payment_id]))
                        {
                                //payment_method already exists, add to payment_amount
                                $payments[$payment_id]['payment_amount'] = bcadd($payments[$payment_id]['payment_amount'], $payment_amount);
                        }
                        else
                        {
                                //add to existing array
                                $payment = array($payment_id => array('payment_type' => $payment_id, 'payment_amount' => $payment_amount));

                                $payments += $payment;
                        }
                }
                $this->set_payments($payments);
        }
`

**Comment by odiea** [comment]
And what do you consider a valid Type?

**Comment by bullmike** [comment]
Whatever is displayed in the Payment Type field when the page is generated?
 eg.. Whatever is returned by: get_payment_options();

**Comment by odiea** [comment]
I don't believe this is an issue due to the Payment type is a drop down form. Yes you can add different payment types to suite your particular needs. Visa MC Discover and Amex can be added to it. If it was a Standard input field I believe that would present an Issue.
