### ISSUE TITLE
DATETIME item attribute type bugs

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2232]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 465a2c
- PHP version is: 5.6.38
- MySQL or MariaDB version is: 5.7.24
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug

There seem to be a few kinks to work out with the DATETIME attribute type:
- The formatting on screen does not follow the selected locale.
- Dates previous to 1/1/2010 are not allowed (in our case we want a "publication date" but many books were published before 2010).
- Manual entry of the date is not allowed.

![datetime](https://user-images.githubusercontent.com/17935339/48552398-ef0a6b80-e8f1-11e8-85c7-a858f6e547b0.jpg)

**Comment by jekkos** [comment]
You are totally right. I didn't find a proper way to do this formatting across the different places this other type is used.

Honestly I added the attribute type but it didn't get enough attention during testing (I won't need this type myself). I did realise that I will need to find a way to map internal date format to either mysql DATE_FORMAT function to have the date output in the result set in a correct manner (which would be the quickest).

**Comment by daN4cat** [comment]
@jekkos is this fixed?

**Comment by jekkos** [comment]
No not yet, I'll need to find some time to look into it. We could however disable DATE attributes and move it to the next release to unblock. What you think?

**Comment by jekkos** [comment]
I think I'll try to map the configured date and time formatter to DATE_FORMAT mysql. MIght be the cleanest so the dates will be formatted directly in the resultset.

**Comment by jekkos** [comment]
Fix is almost ready, just need to verify

**Comment by daN4cat** [comment]
Status?

**Comment by objecttothis** [comment]
@jekkos, what ended up being the fix for getting the Item table to display the datetime attributes correctly.  I'm experiencing the same behavior with the DECIMAL attribute type.  On first entry of a datetime or decimal it updates the database but does not display the datetime or decimal in the items table.  If I update it again or update a different datetime or decimal it will populate that one, but only after updating each one twice does it display in the table.

**Comment by jekkos** [comment]
@objecttothis I have tested my latest PR with text and date attributes, seems to be ok. Haven't verified with Decimal yet but I think it will need to be added in the search query explicitly (like I did for the other types).

**Comment by daN4cat** [comment]
Code merged. I close this and if any issue reopen it.

**Comment by jekkos** [comment]
Ok decimals don't show up in search results, this needs fixing.

**Comment by daN4cat** [comment]
Decimals are a different matter.

I need to submit some minor change, you can take from there.

**Comment by daN4cat** [comment]
I committed to master the few changes I made here and there.
I temporary fixed the cash_refund issue discussed in another thread.
