### ISSUE TITLE
Unable to load Demo after last update to india-gst

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2233]
I rebased the india-gst over the latest master and pushed it to the repository.

I don't know if this was a problem before the push but demo.opensourcepos.org is now returning the following

`A Database Error Occurred
Unable to connect to your database server using the provided settings.`

I downloaded the corresponding build from bintray and gave it a cursory test and did not encounter a similar problem.  It started up normally and I was able to log in and out without a problem.  So I don't think it is anything I did ... but if it is please let me know so that I can slap my hand and not do it again.

Thanks.

**Comment by odiea** [comment]
I just tried the demo and get the following error.
A Database Error Occurred
Unable to connect to your database server using the provided settings.
Filename: core/CodeIgniter.php
Line Number: 518

**Comment by SteveIreland** [comment]
I checked the demo after I pushed the latest fix to the india-gst branch and found that it was "operational" again but does NOT include the latest changes for either item attributes or India GST taxing.

**Comment by odiea** [comment]
Currently your version is online.

**Comment by SteveIreland** [comment]
Yep

**Comment by odiea** [comment]
Current Demo has upgrade issues when trying to add a New item. Is there a cure for this problem?

A Database Error Occurred
Error Number: 1054
Unknown column 'hsn_code' in 'field list'
INSERT INTO `ospos_items` (`name`, `description`, `category`, `item_type`, `stock_type`, `supplier_id`, `item_number`, `cost_price`, `unit_price`, `reorder_level`, `receiving_quantity`, `allow_alt_description`, `is_serialized`, `qty_per_pack`, `pack_name`, `low_sell_item_id`, `deleted`, `hsn_code`, `tax_category_id`) VALUES ('Test1', '', 'Test', '0', '0', NULL, NULL, 10, 20, 1, 1, 0, 0, 1, 'Each', -1, 0, '', '')
Filename: models/Item.php
Line Number: 401
