### ISSUE TITLE
Discount being zeroed out prematurely

### ISSUE THREAD

**Issue by bullmike** [opensourcepos/opensourcepos#2236]
Just wondering what the purpose of the following block of code is? Can this be removed, is there a reason why this block is included that I can't see?

version 3.2.3
Line 740: 
                if($price == 0.00)
                {
                        $discount = 0.00;
                }

**Comment by SteveIreland** [comment]
Looks like this is something I added back in January of 2017.  I vaguely recall that I made the change thinking that it didn't make sense to have a discount percent for an item with a zero price.  Based on your test results it appears that the change is not in the appropriate spot and the discount percent needs to be set to zero when the sale is completed.

Unless someone still sees an issue with that  I'll go ahead and relocate this tidbit of code.

**Comment by erastus** [comment]
I see the code well. if the customer is selected before or there is a general discount and the product has a value of 0.00. the discount would not apply.

**Comment by SteveIreland** [comment]
This has been "fixed".
