### ISSUE TITLE
No add item suggestions 

### ISSUE THREAD

**Issue by LarsGMortensen** [opensourcepos/opensourcepos#2239]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3 - 4f5ad57
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.2
- MySQL or MariaDB version is: 10.3.9-MariaDB-1:10.3.9+maria~bionic
- OS and version is: Windows 7 ... AND on hosted webserver
- WebServer is: Apache/2.4.34 (Win32)  ...and nginx/1.14.0
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

When I go to Sales, and start typing the name of one of my products: The system isn't showing any suggestions.

I have created 2 items in the stock.

But if I just type "2" and hit enter: It adds the product with id = 2  ... but again; if I start typing the name, it does not show me any suggestions.

The problem persists on both my localhost and on my shared hosting at one.com - same problem on both servers.

What am I doing wrong?

**Comment by LarsGMortensen** [comment]
It wont auto-suggest any customers either.

**Comment by LarsGMortensen** [comment]
@daN4cat @jekkos @SteveIreland is there any chance that you have a fix for this? This is kind of urgent to me, so I would REALLY appreciate your help here. Thanks! :o)

**Comment by LarsGMortensen** [comment]
Here is a screencast video of the issue: https://www.screencast.com/t/JZTERQ58LD

**Comment by odiea** [comment]
I just tested 3.2.3 with php 7.2.4 and Suggestions do not work with that version. Try a lower version . Works with 7.1.16

**Comment by LarsGMortensen** [comment]
Okay, thanks. This solves it for now, I guess. But soon PHP 7.1 will be fased out, I think.

**Comment by daN4cat** [comment]
3.3.0 supporta 7.2

**Comment by LarsGMortensen** [comment]
Hmm... I downloaded the stable release, as you directed in your installation-instructions.... I downloaded it the day before yesterday, and got version "3.2.3 - 4f5ad57" ... so if there is a newer version; then why are you not linking to THAT version in your official install-instructions?

...and more importantly: How do I upgrade to that version?

**Comment by odiea** [comment]
3.3.0 is still a work in progress. It is considered the unstable version. My suggestion would be to change your PHP version then upgrade later after 3.3.0 has been released.
