### ISSUE TITLE
Stock-name with spaces still a problem vs employee grants

### ISSUE THREAD

**Issue by LarsGMortensen** [opensourcepos/opensourcepos#2240]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3 - 4f5ad57
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.2.12
- MySQL or MariaDB version is: 10.3.9-MariaDB-1:10.3.9+maria~bionic
- OS and version is: x86_64-pc-linux-gnu
- WebServer is: nginx/1.14.0
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I renamed my stock to: Stock 29
Then changed the details of the employee (id = 1).
First it went fine when saving the details for the employee.
I then changed something else for the same employee - and was no longer able to save it, as it says "Add at least one grant for each module." numerous times.

**Comment by WebShells** [comment]
Mmmm... If you press submit again after getting the errors it will close the form, but it wont save the selection... @daN4cat @jekkos @SteveIreland any ideas ?

**Comment by WebShells** [comment]
Also i guess php 7.2 still isn't fully supported in v3.2...

**Comment by SteveIreland** [comment]
I'll run through a test scenario again, but the issue that I fixed awhile back was that the stock name is also used as an HTML attribute name and the embedded space needed to be replaced by a lowercase character.  It was working in my tests but apparently it wasn't a complete test.

Did you need PHP 7.2 to be supported in 3.2?  I think we are only going to support it in 3.3.

**Comment by SteveIreland** [comment]
@LarsGMortensen Can you add a screen print of the permissions page on which you are receiving that error?  I retested the scenario you describe and could not recreate the problem.  It would be helpful to see what you are looking at.

**Comment by SteveIreland** [comment]
Oh duh.  I forgot.   The fix I applied is only in the india-gst branch.

Details are in #1911

**Comment by LarsGMortensen** [comment]
Sure, here's a screecast video: https://www.screencast.com/t/pR13Z3Ve

**Comment by SteveIreland** [comment]
Hopefully you saw my last post about the info regarding the fix being in #1911.  I noticed that the code changes are still documented in the commit that survived the rebase.  Click on https://github.com/opensourcepos/opensourcepos/commit/ce5a75d6a408862ca721e8e98e55e427178f44c6
