### ISSUE TITLE
how can i download only the demo for test in local (without internet)

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#2242]
i want download only the demo like containerized demo https://demo.opensourcepos.org , or modifiy/config for reinitialize after a few days?

**Comment by WebShells** [comment]
Clear enough that you didn't even spent a second to look through the wiki or previous issues... Will close this thread.

**Comment by ekardian** [comment]
> Clear enough that you didn't even spent a second to look through the wiki or previous issues... Will close this thread.

thx for respond mr sith XD
