### ISSUE TITLE
Discount Decimals is NOT included in the Configuration module, localization settings! WHY?

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2243]
To Whom It May Concern:

As a result of my evaluation/testing of all the features of the OSPOS I found out that the discount decimal is not included in the Configuration,localization settings in order to add decimal point in the discount. As a result during the sales, discount will display like this: if you enter 2.5 the result is only 2, if you enter 2.6 the result is 3, but good to say that the actual percentage of the discount decimal value is CORRECT. 

adding the discount decimal can add simple improvements for the OSPOS.

**Comment by saanplus** [comment]
is there a solution to this yet?
