### ISSUE TITLE
Migration Script Error Handling

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2247]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.6.38
- MySQL or MariaDB version is: 5.7.24
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English

### New Feature
Currently it appears that even with db_log_enabled and log level set to 4 there is no reporting done when the migration scripts are run.  This is bad news for when the script encounters errors because it doesn't give the administrator any indication that something went wrong.  

I think at minimum we need to generate a log.  Better would be to also pop up a message when the script has run telling the user that the migration took place and to check the log to resolve problems.  Best would be to also roll back changes when a migration script fails so that the user doesn't have to restore a backup of their data and can fix problems before running the script again.

**Comment by jekkos** [comment]
There should be something in the logfiles in case it goes wrong. Check application/logs for any output during migration. It should certainly contain some statements on which migrations were ran.

But you're right that we should actually give this output to the user as well. Maybe a generic try catch during this process after which any of the errors are shown in a popup box.

**Comment by jekkos** [comment]
Well maybe we should stick to a minimum or maybe generic message and then refer to the log files in case something is wrong, as displaying all the detail might be a bit of a pain with the limited UI possibilities we have in the jquery popup thingy?

**Comment by objecttothis** [comment]
Yeah, I think a generic "check the log in ..." message would be fine.  One question though: do logs get generated regardless of the log_level setting and db_log_enabled setting or does it only generate a log with those turned on and set correctly?

**Comment by SteveIreland** [comment]
I’m always monitoring the php.log during the migration to catch unexpected errors. It nicely reports which step has started and when the step finishes and it reports most SQL errors.

**Comment by jekkos** [comment]
Ok I have now added a warning message on the login page when the migration is about to start. Also a user is logged out if a migration is about to happen.
