### ISSUE TITLE
Missing attribute values in search results

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2248]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.6.38
- MySQL or MariaDB version is: 5.7.24
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English

### Bug
If I am just browsing the items from the table I see the values of all the data:
![item listing](https://user-images.githubusercontent.com/17935339/49087462-7b147f80-f270-11e8-9861-45073b777a2e.jpg)

But if I do a search for a book, you'll notice that same book shows '-' instead of the relevant data even though I can edit the item and see all those attributes are there and defined properly.  I think this is probably a problem with the search.
![search results](https://user-images.githubusercontent.com/17935339/49087466-7ea80680-f270-11e8-926a-bbeea92a6639.jpg)

**Comment by objecttothis** [comment]
This is on a freshly migrated database, so attributes are in place.  I'm also noticing that none of the attributes are searchable, but that might be better in a different issue.

**Comment by jekkos** [comment]
to search you need to set the flag in the options dropdown. The values not showing is obviously a bug.

**Comment by objecttothis** [comment]
@jekkos OK, I found it.  Yes, the "Search Attributes" flag corrected the search not returning results based on attributes

**Comment by jekkos** [comment]
You're right, when you have a column visible in items it should also show values even when not searching on attributes themselves. This last commit should fix this.
