### ISSUE TITLE
Error on Sales screen if no stock permission

### ISSUE THREAD

**Issue by bullmike** [opensourcepos/opensourcepos#2249]
If user doesn't have a stock permission you get the following error when accessing the sales screen:

A PHP Error was encountered
Severity: Notice

Message: Trying to get property of non-object

Filename: models/Stock_location.php

Line Number: 83

Backtrace:

File: /var/www/html/application/models/Stock_location.php
Line: 83
Function: _error_handler

File: /var/www/html/application/libraries/Sale_lib.php
Line: 677
Function: get_default_location_id

File: /var/www/html/application/controllers/Sales.php
Line: 1728
Function: get_sale_location

File: /var/www/html/application/controllers/Sales.php
Line: 27
Function: _reload

File: /var/www/html/public/index.php
Line: 315
Function: require_once

        public function get_default_location_id()
        {
                $this->db->from('stock_locations');
                $this->db->join('permissions AS permissions', 'permissions.location_id = stock_locations.location_id');
                $this->db->join('grants AS grants', 'grants.permission_id = permissions.permission_id');
                $this->db->where('person_id', $this->session->userdata('person_id'));
                $this->db->where('deleted', 0);
                $this->db->limit(1);

                return $this->db->get()->row()->location_id;
        }

should be

        public function get_default_location_id()
        {
                $this->db->from('stock_locations');
                $this->db->join('permissions AS permissions', 'permissions.location_id = stock_locations.location_id');
                $this->db->join('grants AS grants', 'grants.permission_id = permissions.permission_id');
                $this->db->where('person_id', $this->session->userdata('person_id'));
                $this->db->where('deleted', 0);
                $this->db->limit(1);

                return (isset($this->db->get()->row()->location_id)) ?  $this->db->get()->row()->location_id : null;
        }

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.2.3
- OSPOS git commit hash is: 
- PHP version is: php 7.0.32
- MySQL or MariaDB version is: 5.5.60
- OS and version is:  CentOS 7.5.1804
- WebServer is: HTTPD
- Selected language is: en_US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by bullmike** [comment]
the suggested fix breaks other stuff. do not use.

**Comment by odiea** [comment]
How are they suppose to sell anything without giving them grants to a stock?

**Comment by daN4cat** [comment]
Which version?

**Comment by odiea** [comment]
And what did you do to bypass the grants for Sales? This is where you were getting the "at least 1 grant is needed" error.

**Comment by SteveIreland** [comment]
And what version of PHP are you running?  If it's not 7.1 then forgetaboutit.

**Comment by bullmike** [comment]
PHP 7.0.32 (cli) (built: Sep 11 2018 12:43:24) ( NTS )

forget about it?

**Comment by SteveIreland** [comment]
Nope.  I thought I had a clue with the get property of non-object.  I suppose I am clueless now.

**Comment by daN4cat** [comment]
The check list is in place to answer those questions.....

**Comment by odiea** [comment]
Yes but the programmed to use a stock location for Sales. So give permission for a stock location and see if the error goes away. Permission to Items is different then permission for Sales.

**Comment by bullmike** [comment]
I filled in the check list. daN4cat.

Odiea, to be honest I don't need the stock portion and can just enable it. However, it seems strange to include a checkbox for a permission that is required to process any sale. I was just letting you guys know..
