### ISSUE TITLE
System doesn't support CLI calls due to $config['base_url'] 

### ISSUE THREAD

**Issue by bullmike** [opensourcepos/opensourcepos#2250]
Version 3.2.3

application/config/config.php

This line breaks the CodeIgniter CLI:
$config['base_url'] .= '://' . $_SERVER['HTTP_HOST'];

should  be:

if ( ! is_cli() ) {
$config['base_url'] = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') || isset($_ENV['FORCE_HTTPS'])) ? 'https' : 'http';
$config['base_url'] .= '://' . $_SERVER['HTTP_HOST'];
$config['base_url'] .= str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME']);
}

**Comment by jekkos** [comment]
Ok fine, haven't used CI cli for anything yet, but feel free to send a PR to fix this issue.

**Comment by mckaygerhard** [comment]
its incomplete, must provide alternat base url if comes from cli plugin, in most cases a hardcoded path

**Comment by bullmike** [comment]
Works for me.  

Had to create a separate Secure_Controller <Secure_CLI_Controller > which handles the authentication / module access but, other than that...

**Comment by brainpascal** [comment]
> Works for me.
> 
> Had to create a separate Secure_Controller <Secure_CLI_Controller > which handles the authentication / module access but, other than that...
> 
> I suspect you aren't using the CLI functionality correctly as its all handled by CI in index.php

Could you show the code of the secure_cli_controller? I'm trying to use C.I. CLI with OSPOS but it needs login.
