### ISSUE TITLE
Remove deprecated lang code for custom fields

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2253]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.7.38
- MySQL or MariaDB version is: 5.7.24
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English

### Issue

I noticed that there are deprecated lines in the config_lang and potential other lang files regarding the custom fields that are being deprecated in favor of attributes.  Its an easy thing for me to remove, but I need to know if I need to go through all the languages and remove them or if i can just remove them in en_US and they will automatically get removed in the others once #2217 is resolved.

**Comment by jekkos** [comment]
@objecttothis feel free to do so now as weblate is back up and running.

**Comment by objecttothis** [comment]
I'm on it like flies on poop. :)

**Comment by jekkos** [comment]
Usually I handle this case by 'syncing' the translations using an old php script. Maybe this version of weblate supports it but I'm not quite certain there.

**Comment by jekkos** [comment]
One thing I can do is integrate this script to run from weblate 
https://github.com/WeblateOrg/weblate/issues/221

**Comment by jekkos** [comment]
I have synced language files, so I hope those deprecated fields are gone now (at least all other files should be aligned with english now)

**Comment by objecttothis** [comment]
They weren't gone because I had not created a pull request for the code change.  Created the pull request (#2262).  After it gets merged you'll need to sync language files again so that weblate no longer has those fields and all the other languages (besides en_US) no longer have those lines.

I also added to the migration script to remove the customX_name rows from ospos_config_app table in the database.

**Comment by objecttothis** [comment]
Just as an FYI, the addition of the default_item_columns addition is for another part of the code, but I forgot to redact it from the branch.  No change needed, because it will be used.
