### ISSUE TITLE
Client Demographics

### ISSUE THREAD

**Issue by data2base** [opensourcepos/opensourcepos#2254]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question / New Feature

Hi!

Is it possible to add client demographics to a sale where no client is selected. 
We do mostly cash sales, but would still like to record client demographics like, gender, race etc

Is it possible that we could add as a feature. 

I'm looking forward to the new release!

**Comment by WebShells** [comment]
Am not sure if there is a way or how much it will be useful to keep record of demographics as bulk... Since without adding client to database and assigning it to saleyou cant keep a track

**Comment by SteveIreland** [comment]
Can you set up a a few customers where the name encodes the demographics available in the customer definition?  I know that introduces a few permutations so it could grow and become unmanageable rather quickly, but if you are only interested in 2 or 3 properties then it might be doable.

**Comment by data2base** [comment]
That is a great idea, i'm only interested in 2 properties, :)
Thanks again.

**Comment by data2base** [comment]
Is it possible to change the customer field to required?

**Comment by SteveIreland** [comment]
It is required for invoice mode but not for receipt mode. 

There is no configuration option for making the customer required.

You would need to make a site specific customization
