### ISSUE TITLE
Getting Tax from wrong table

### ISSUE THREAD

**Issue by w002qaa** [opensourcepos/opensourcepos#2255]
Hello,

I am using OSPOS V3.2.3, and taxes are calculated from `ospos_items_taxes`. Where I am assuming it should be calculate from `ospos_sales_taxes`.  

Because I started taking taxes, and all old sales give me a wrong calculation on the total.

**Comment by daN4cat** [comment]
What about providing more information about your configuration? What you are saying it's not exhaustive.

**Comment by w002qaa** [comment]
Hello, I a back with same issue.

Now I am using OSPOS v3.3.1

I created two sales for demo. The first one was with 5% of VAT with Amount Due ($0.00). I changed the VAT value to 7%, and I did another sale with new VAT percent. 

If go back to check the receipt sale # 1, it show me Amount Due	($17.80). 


Here is photos to show the problem

https://ibb.co/yYGRS1x

https://ibb.co/WDQfGWQ
