### ISSUE TITLE
Updating files manually to added Cashups feature

### ISSUE THREAD

**Issue by mbajay** [opensourcepos/opensourcepos#2258]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by mbajay** [comment]
Lot of data at stake. this will help me understand the application better.

Also noted that the 'Expenses' form to add new expenses is showing similar behaviour.

What could be causing this issue?

**Comment by daN4cat** [comment]
Have you given a try updating in a test deployment to latest master?

**Comment by SteveIreland** [comment]
You will need to learn how to debug your changes to determination me what you are doing wrong.  This isn’t something we can help with. I believe there is some info on debugging in the Wiki

**Comment by mbajay** [comment]
> 
> 
> Have you given a try updating in a test deployment to latest master?

yes. This is the case while updating to the latest master.

**Comment by mbajay** [comment]
> 
> 
> You will need to learn how to debug your changes to determination what you are doing wrong. This isn’t something we can help with. I believe there is some info on debugging in the Wiki

Could you share a link?

**Comment by SteveIreland** [comment]
https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-DEVEL-for-Error-Logging-in-OSPOS

**Comment by mbajay** [comment]
> have you updated all the files to 3.3.0 or just some of them as you hinted above?

Just the files mentioned above. Solved all errors occurring due to updation of tabular_helper.php. The only thing that remains broken is the 'New Cashup'  form

**Comment by daN4cat** [comment]
Upgrade all the files and don't nitpick unless you are really familiar with the code.

**Comment by SteveIreland** [comment]
And what are the errors you are finding when you check the PHP log?   Did you change index.php to put the system in development mode?   You did read the instructions in the link I provided .... right?

**Comment by mbajay** [comment]
> 
> 
> And what are the errors you are finding when you check the PHP log? Did you change index.php to put the system in development mode? You did read the instructions in the link I provided .... right?

yes @SteveIreland . In debugging mode of the browser, I do get an 'internal server error'  

Request Header:
GET /pos/public/cashups/search?search=&order=asc&offset=0&limit=25&start_date=2018-12-03&end_date=2018-12-03&filters%5B%5D= HTTP/1.1
Host: mydomain.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://mydomain.com/pos/public/cashups
Content-Type: application/json
X-Requested-With: XMLHttpRequest
DNT: 1
Connection: keep-alive
Cookie: csrf_cookie_ospos_v3=a7427452e56014911e36621b9928aa77; glx_pp_9277_201813106={"loaded_time":1543855500,"click_num":1,"last_fired_time":1543855510,"last_fired_click_num":1,"pop_count":1,"unload_time":1543855510}; cpsession=ardagl%3ajsHajE6ZAShuj1Xs%2cb79c14781989c75a974db7ada7302a45; timezone=Asia/Kolkata; ospos_session=hb8uj865ke1q1khjrvjlb4ri9r4gtbi5

Response Header:
HTTP/1.1 500 Internal Server Error
Date: Mon, 03 Dec 2018 17:03:35 GMT
Server: Apache
X-Powered-By: PHP/5.6.38
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: csrf_cookie_ospos_v3=a7427452e56014911e36621b9928aa77; expires=Mon, 03-Dec-2018 19:03:35 GMT; Max-Age=7200; path=/
ospos_session=hb8uj865ke1q1khjrvjlb4ri9r4gtbi5; expires=Mon, 03-Dec-2018 19:03:36 GMT; Max-Age=7200; path=/; httponly
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

The Cashup feature seems to fail from this point onwards. What am I missing?
