### ISSUE TITLE
OSPOS installation failed on Cloud VPS

### ISSUE THREAD

**Issue by StanlySimon** [opensourcepos/opensourcepos#2259]
Hi,

I tried to deploy OSPOS 3.2.3 on Cloud VPS and got below error.
==
[Sat Dec 01 07:53:57.686530 2018] [:error] [pid 3940] [client 223.228.183.69:41083] PHP Fatal error:  Call to undefined function bcscale() in /var/www/html/ospos/application/hooks/load_config.php on line 39, referer: http://167.114.3.2:1987/ospos/
==

Server configuration is below:
==
PHP 5.6.38 (cli) (built: Oct 24 2018 12:50:38)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

mysql  Ver 8.0.13 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by daN4cat** [comment]
Sounds like you are missing some PHP module. Is bcmath included in your PHP setup?

**Comment by StanlySimon** [comment]
Yes bcmath is already installed on this server.

[root@vps ospos]# yum list installed | grep -i bcmath
php-bcmath.x86_64                  5.6.38-2.el7.remi                 @remi-php56
php56-php-bcmath.x86_64            5.6.38-2.el7.remi                 @remi-safe

**Comment by StanlySimon** [comment]
Please close this issue as it is resolved by restarting HTTP Server.
Now everything looks good.
