### ISSUE TITLE
OSPOS show variable name, help me please.

### ISSUE THREAD

**Issue by vb4win** [opensourcepos/opensourcepos#2260]
I installed OSPOS successfully. It shows the variable name instead of the word. Please suggest how to fix it. http://www.kelangnakorn.online/ospos

**Comment by odiea** [comment]
It appears that you are missing the language files.

**Comment by vb4win** [comment]
How do I fix it?

**Comment by SteveIreland** [comment]
Since the language elements are not being mapped then its a safe bet that you did NOT install OSPOS successfully. 

Did you install from bintray and if so which file did you install?  Also what server is hosting OSPOS and have you checked to make sure that all of the prerequisites have been met?

**Comment by WebShells** [comment]
Since no reply, will be closing this until reopened by user...
