### ISSUE TITLE
HELP! I can't run this OSPOS system. I'm using windows 10 and XAMPP.

### ISSUE THREAD

**Issue by norbeLsemaJ** [opensourcepos/opensourcepos#2263]
I downloaded the latest master file of the ospos as of today...but it can't run. please help admin

**Comment by norbeLsemaJ** [comment]
share me a link please

**Comment by daN4cat** [comment]
Read the wiki?

**Comment by norbeLsemaJ** [comment]
i follow all the instruction... i downloaded the latest .zip file then exctrat it and paste to my localhost address and install database using xampp.. but when i type localhost/ospos nothing happen...it says object not found. kindly help for this...

**Comment by norbeLsemaJ** [comment]
or should I donate first?

**Comment by norbeLsemaJ** [comment]
I'll try to review first...thanks

**Comment by norbeLsemaJ** [comment]
UH..UH...STILL WON'T WORK...

**Comment by odiea** [comment]
Try localhost/ospos/public.

**Comment by norbeLsemaJ** [comment]
yeah i try it...but still won't work... kindly send an official link that work..thanx..

**Comment by mckaygerhard** [comment]
all people her made wrong question (as always), first of all @norbeLsemaJ what wiki or install or readme file or tutorial are you using to make it run? please post links to see if are the correct!

second what specific steps do you made it!?
