### ISSUE TITLE
Not able to set up Local Deploy for Linux [noob question]

### ISSUE THREAD

**Issue by numa-drrey** [opensourcepos/opensourcepos#2272]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

_Not Sure about the last 2 check boxes I'm afraid..._

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: PHP 7.2.10-0ubuntu0.18.04.1 (cli)
- MySQL or MariaDB version is: mariadb  Ver 15.1 Distrib 10.1.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- OS and version is: Ubuntu 18.04.1 LTS
- WebServer is: 
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Short Disclaimer:
First of all: I'm a total php/mysql newb; sorry if the following is too trivial. I still would very much try out OSPOS. And indeed it says "you don't have to know how all these systems work to run OSPOS. You just need to install them" regarding LAMP on http://www.opensourceposguide.com/guide/gettingstarted/installation 

### Issue:
I've tried several times to do a local deploy install of OSPOS, following various install guides but never got it running. Not even arriving at the login-screen.

For example this happened on a freshly installed und updated Ubuntu 18.04 LTS system on Lenovo ThinkPad L540 following the instructions on 
https://github.com/opensourcepos/opensourcepos/wiki/Getting-Started-installations
at "Local Deploy install for Unix/Linux environments":

Step1:
`sudo su`

Step2:
```
apt-get install apache2 
apt-get install mariadb-server
apt-get install php 
apt-get install php-curl 
apt-get install php-mysql 
apt-get install php-gd 
apt-get install php-intl 
```

These dependencies are mentioned additionally in the "INSTALL.md" of the latest stable OSPOS release, so I included them to be safe (tried without them, too):
```
apt-get install php-bcmath
apt-get install php-dba 
apt-get install php-mbstring
```
```
a2enmod rewrite
systemctl restart apache2
```

Step 3:
`cd /var/www/html`

Step 4:
`wget https://github.com/opensourcepos/opensourcepos/releases/download/3.2.3/opensourcepos.20180613210031.3.2.3.f1cf3d.zip -O osposlastedstable.zip`

Step 5:
`unzip osposlastedstable.zip`

Step 6:
`mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"`

Step 7:
`mysql -u admin -ppointofsale -D ospos < /var/www/html/application/database/database.sql`

--> ERROR: "`bash: /var/www/html/application/database/database.sql: No such file or directory`"

Indeed this file does not exist. There exists var/www/html/database/database.sql though, but I couldn't do anything with this and not screw up the installation guide steps, because I'm not even sure what this Step does.

**What would be the correct thing to do at this point?** It's probably quite easy, but without knowledge about php/mysql it's quite difficult for me to get it. 

Also Step 8. ("Configure the OSPOS index page and encryption key this its by editing the config and htaccess files, can be bypassing but strong recommended set the encryption key at application/config/config.php with your owcurrently for security.") is quite cryptic and I do not understand what to do.

By the way, if that helps: At this point opening http://localhost/public only shows an excerpt of the code of index.php in that public folder. Opening http://localhost/ gives the Apache2 Ubuntu Default Page.

I hope I included enough information to be able to help me. Thank you.

**Comment by SteveIreland** [comment]
The path to the database.sql should be (...web-root)\database\database.sql
It appears that there is a typo in the wiki.

**Comment by SteveIreland** [comment]
Regarding the encryption key ....

I just go to https://randomkeygen.com/ and scroll down to the Codeigniter section and copy the encryption key that is generated there and then paste it into the appropriate spot in the conf.php file.

**Comment by jekkos** [comment]
This case will only work with a release zip, if you want to run an unstable zip you need to run the grunt build (check wiki for that)

**Comment by numa-drrey** [comment]
Thanks for your answers.

@SteveIreland:
Well yes, I thought so, too about the typo, so I went ahead and typed `mysql -u admin -ppointofsale -D ospos < /var/www/html/application/database/database.sql` without getting an error message.
But still: opening localhost/public only reveals index.php code like this
`=')) { error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT & ~E_USER_NOTICE & ~E_USER_DEPRECATED); } else { error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_USER_NOTICE); } break; default: header('HTTP/1.1 503 Service Unavailable.', TRUE, 503); echo 'The application environment is not set correctly.'; exit(1); // EXIT_ERROR } /* *--------------------------------------------------------------- * SYSTEM DIRECTORY NAME *--------------------------------------------------------------- * * This variable must contain the name of your "system" directory. * Set the path if it is not in the same directory as this file. */ $system_path = '../vendor/codeigniter/framework/system'; /* *------; `
and so on.

I guess I'm missing a crucial part of step 8, maybe the bit about the htaccess files? I haven't edited these yet.

@jekkos:
ahh, so I in fact was not "_Aware the installation code is in bintray (see README), and GitHub master is for developers only and therefore not complete nor stable_"?  (I do want a stable release one!)
So in Step 4 I instead wget another file, e.g. "https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20170805225340.zip", right?
Do I have to undo some of the steps I already did before trying anew with this? [If it's possible don't want to re-install OS again, already did a couple of times cause I didn't know how to undo steps...]

**Comment by jekkos** [comment]
ah no just get a zip from the release section here, this should have all the files you need.

**Comment by jekkos** [comment]
otheriwise if you are brave enough you can profit from some new features and try to build the latest bintray..
