### ISSUE TITLE
Unable to add new items or "New" button is not clickable

### ISSUE THREAD

**Issue by pards124** [opensourcepos/opensourcepos#2276]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

version 3.3.0

When i need to add new item, it is stuck in there.

**Comment by erastus** [comment]
active in config.php the log

**Comment by erastus** [comment]
Do you use the .env file for the connection to the database? or edit the database.php file

**Comment by pards124** [comment]
I got this error in logs

[Mon Dec 24 11:36:51.509136 2018] [:error] [pid 793] [client 210.213.84.202:60460] PHP Fatal error:  Call to a member function num_rows() on boolean in /var/www/html/ospos/application/models/Item.php on line 290, referer: http://ospos.example.com/public/items
[Mon Dec 24 11:36:51.509277 2018] [:error] [pid 793] [client 210.213.84.202:60460] PHP Stack trace:, referer: http://ospos.example.com/public/items
[Mon Dec 24 11:36:51.509326 2018] [:error] [pid 793] [client 210.213.84.202:60460] PHP   1. {main}() /var/www/html/ospos/public/index.php:0, referer: http://ospos.example.com/public/items
[Mon Dec 24 11:36:51.509393 2018] [:error] [pid 793] [client 210.213.84.202:60460] PHP   2. require_once() /var/www/html/ospos/public/index.php:315, referer: http://ospos.example.com/public/items
[Mon Dec 24 11:36:51.509453 2018] [:error] [pid 793] [client 210.213.84.202:60460] PHP   3. call_user_func_array:{/var/www/html/ospos/vendor/codeigniter/framework/system/core/CodeIgniter.php:532}() /var/www/html/ospos/vendor/codeigniter/framework/system/core/CodeIgniter.php:532, referer: http://ospos.example.com/public/items
[Mon Dec 24 11:36:51.509512 2018] [:error] [pid 793] [client 210.213.84.202:60460] PHP   4. Items->view() /var/www/html/ospos/vendor/codeigniter/framework/system/core/CodeIgniter.php:532, referer: http://ospos.example.com/public/items
[Mon Dec 24 11:36:51.509569 2018] [:error] [pid 793] [client 210.213.84.202:60460] PHP   5. Item->get_info() /var/www/html/ospos/application/controllers/Items.php:205, referer: http://ospos.example.com/public/items

**Comment by SteveIreland** [comment]
pards124 what version of PHP are you using?

**Comment by pards124** [comment]
Im using PHP 5.6.38 (cli) (built: Sep 13 2018 16:53:48)

**Comment by SteveIreland** [comment]
I tested with PHP 5.6.35 and it works fine.   Since you are installing from the unstable development branch I assume you are exploring the new features and know that you had to install from a build file deployed to bintray.

Can you tell me which zip file you installed from?

**Comment by odiea** [comment]
Any more info. If not I shall close this tomorrow.

**Comment by pards124** [comment]
In xampp it is working but in my linux box its not, all php modules installed and upgraded apache, mysql and php. I used this latest source file
opensourcepos.20190327000845.master.2c4114.zip

**Comment by pards124** [comment]
![Capture](https://user-images.githubusercontent.com/33042543/55299280-e495dc00-5464-11e9-98c5-48be6920c026.JPG)

Please help me what is the issue on this, form is not appearing when clicking the "New Item" button.

**Comment by SteveIreland** [comment]
Did you try the new system information page?  It might help provide a clue.

**Comment by pards124** [comment]
Hi Stevelreland,

Below are the system info 

OSPOS Installation Info: | 3.3.0 - 2c4114
-- | --
en-US
» GD: Enabled ✓» BC Math: Enabled ✓» INTL: Enabled ✓» OpenSSL: Enabled ✓» MBString: Enabled ✓» Curl: Enabled ✓

.Browser: Chrome.Server Software: Apache/2.4.37 () PHP/7.2.14.PHP Version: 7.2.14 .Server Port: 80.DB Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $.OS: Linux PTGTPD0B3KTJ 6.3 build 9600 #1 SMP Sat Mar 2 00:40:20 UTC 2019 x86_64

» [application/logs:] - 0777 \| Writable ✓ » [public/uploads:] - 0777 \| Writable ✓ » [public/uploads/item_pics:] - 0777 \| Writable ✓ » [import_items.csv:] - 0777 \| Writable ✓ » [import_customers.csv:] - 0777 \| Writable ✓

**Comment by daN4cat** [comment]
What about MySQL version 5.0.12-dev?
That looks old and probably deprecated.
We never tested with something older than MySQL 5.5 if my memory is right.
If you want performance use MariaDB latest version, see README.

**Comment by pards124** [comment]
Thanks for this info,it really helps, upgrade to mariadb will solve the issue
