### ISSUE TITLE
Item add to Sale failed

### ISSUE THREAD

**Issue by joe-zhang3** [opensourcepos/opensourcepos#2277]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I am pretty new to this project and thanks for all of your efforts to share this with everyone. 
I download the package from bintray and followed instructions to start up the project: 
docker-compose build
docker-compose up

I am able to do things like add a new item, add a new employee etc. However, when I try to sale an item, I got an error message says "Item add to Sale failed". 

Please let me know when I can grab some logs to give you more information.

**Comment by SteveIreland** [comment]
Also, I would be interested in which zip file you grabbed from bintray.  If it was the india-gst branch then I'd like to know a bit more about your configuration.

**Comment by joe-zhang3** [comment]
@SteveIreland , I am using the one `opensourcepos.20181215142948.master.e87c1d.zip`

**Comment by joe-zhang3** [comment]
Appreciated your reply. I will follow @WebShells 's comments to turn on debug info and see how it goes. thanks

**Comment by odiea** [comment]
No info for 21 days so I will close this.
