### ISSUE TITLE
barcode scanner don't work on sales button only

### ISSUE THREAD

**Issue by locik** [opensourcepos/opensourcepos#2279]
i need help. Please... My barcode scanner work on receivings button. I can add item there. but it don't work on sales button only. When i press my barcode scanner, i get the number but quickly it change with the text "start typing item name or scan barcode" so i can not add item with barcode scanner but i can add item with keyboard.
i use windows 10, ospos 3.2.3, xampp v3.2.2. 
here is screen recording of my problem https://youtu.be/7RZfYeuPYRs

**Comment by SteveIreland** [comment]
Having a screen recording is really helpful to understand the problem.

If you enter the item code manually and then press Enter do you have the same problem or does the problem only occur when using the scanner?

Like the other recent issue I might try putting the index.php in development mode just to see if it there might be a PHP error that is being swallowed.

**Comment by locik** [comment]
The problem occure only when i use scanner on sales button. There is no problem if i use the scanner on other button like receiving button and others.. and there is no problem if i add item or code item manually.

Oh, i confused and dont 
Understand how to do with php file but i will try

**Comment by locik** [comment]
I have tried but i found nothing. So what i've to do?

**Comment by mohsen8321** [comment]
I think there is no software problem
Only the solution will be in the barcode scanner setup


With Barcode Scanner there are some settings

**Comment by mohsen8321** [comment]
Example:
If you are using a barcode scanner, type symbol ls2208
You will find  QUICKSTARTGUIDE  
[https://www.zebra.com/content/dam/zebra_new_ia/en-us/manuals/barcode-scanners/MN000753A04ENa_ls2208-qsg-en.pdf](url)

In the first step, you can scan (Set Defaults Bar Code) in (page 3)

In the second step scan on
        (Enter Key Bar Code (Carriage Return / Line Feed (page 9)



After that you will find that the scanner works with you well

**Comment by locik** [comment]
oh, i forget to tell that i add this code ini php.ini as i found this from google. and now i still wait the answer causse i don't to understand php programming so i can't fix it myself

extension=php_bz2.dll
extension=php_curl.dll
extension=php_fileinfo.dll
extension=php_gd2.dll
extension=php_gettext.dll
extension=php_gmp.dll
extension=php_intl.dll
extension=php_imap.dll
extension=php_mbstring.dll
extension=php_exif.dll
extension=php_mysql.dll
extension=php_mysqli.dll
extension=php_pdo_mysql.dll
extension=php_pdo_sqlite.dll
