### ISSUE TITLE
Reports Sales Tax or Taxes

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2284]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: current master
- OSPOS git commit hash is: 
- PHP version is: 7.1
- MySQL or MariaDB version is: Mysql
- OS and version is: Win 10
- WebServer is: Wamp
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Reports are now showing 2 separate Tax Items as the Image shows. Should this be there?
The Sales Tax Report displays the Amounts only while the Taxes show Sales properly.
![2018-12-23 11_01_38-window](https://user-images.githubusercontent.com/10962177/50386415-1bf52f80-06a3-11e9-805a-b7141e3be30b.png)

**Comment by SteveIreland** [comment]
The new tax report breaks down taxes so that they can be reported by tax jurisdiction.  The other does not have that capability.

I kept the information on the report minimal until someone can tell me what else is needed for a "proper" tax report.

**Comment by odiea** [comment]
A Database Error Occurred

Error Number: 1054
Suddenly I started getting this error when trying to log in.
Unknown column 'fa.sales_tax_code' in 'where clause'

UPDATE ospos_customers AS fa SET fa.sales_tax_code_id = ( SELECT tax_code_id FROM ospos_tax_codes AS fb where fa.sales_tax_code = fb.tax_code)

Filename: C:/wamp64/www/newtax/vendor/codeigniter/framework/system/database/DB_driver.php

Line Number: 691

**Comment by odiea** [comment]
I had to delete the migration script and all started working correctly

**Comment by odiea** [comment]
The migration issue caused the tax jurisdiction table to be filled with 16 xtra entries and that was why the Report started working. The - sign next to the entry did nothing as far as removing the entries. I had to go into the database and delete the xtra entries. This was on an update of my current db.

**Comment by odiea** [comment]
A migrated database

**Comment by SteveIreland** [comment]
I'm going to run another upgrade an a populated data set just to make sure I didn't introduce a bug somewhere along the way.

**Comment by odiea** [comment]
Were you able to duplicate this issue?

**Comment by odiea** [comment]
From what I could see it wanted to run the script every time I logged in. I was using both a merge into my master and the current unstable build.

**Comment by odiea** [comment]
This is the error I get when I enable all errors in the config file. This is what I get when loggin on and the db is already upgraded.
INFO - 2018-12-24 17:31:34 --> Language file loaded: language/en-US/taxes_lang.php
INFO - 2018-12-24 10:31:34 --> Migrations Class Initialized
INFO - 2018-12-24 10:31:34 --> Database Forge Class Initialized
DEBUG - 2018-12-24 10:31:34 --> Migrating up from version 20181015100000 to version 20181203115700
ERROR - 2018-12-24 10:31:35 --> Query error: Unknown column 'fa.sales_tax_code' in 'where clause' - Invalid query: UPDATE ospos_customers AS  fa SET fa.sales_tax_code_id = (
			SELECT tax_code_id FROM ospos_tax_codes AS fb where fa.sales_tax_code = fb.tax_code)
ERROR - 2018-12-24 10:31:35 --> Query error: Can't DROP 'sales_tax_code'; check that column/key exists - Invalid query: ALTER TABLE ospos_customers DROP COLUMN sales_tax_code
ERROR - 2018-12-24 10:31:35 --> Query error: Table 'feature.ospos_tax_code_rates_backup' doesn't exist - Invalid query: SELECT COUNT(*) as count
FROM `ospos_tax_code_rates_backup`
ERROR - 2018-12-24 10:31:35 --> Severity: error --> Exception: Call to a member function row() on boolean C:\wamp64\www\my-master\application\migrations\20181203115700_indiagst.php 71

**Comment by odiea** [comment]
BTW: **Merry Christmas to all**.

**Comment by SteveIreland** [comment]
Merry Christmas and Happy Holidays to you too.

Once the migration script is successfully run I don't believe it should be trying to run again.

That is why I think the migration script completed successfully the first time it ran.  I'd be interested to know why it didn't complete the first time.

If you are unable to restart from scratch then I'll try to replicate it.  Do you run with basic tax and tax excluded?  Do you use two tax rates or just one?

**Comment by odiea** [comment]
Initially I started out with the old OSPOS tax code 1. I then changed to your new tax code 2. I will dig up an old database and see what happens. I don't use it for business purposes just testing for OSPOS. I would say this current version would be tax code #3.

**Comment by odiea** [comment]
This is the info I got with upgrading a different db with no login issues afterwards. Could have been a bad db? If there is something else I have to enable for db debugging let me know.
INFO - 2018-12-24 12:30:03 --> Migrations Class Initialized
INFO - 2018-12-24 12:30:03 --> Database Forge Class Initialized
DEBUG - 2018-12-24 12:30:03 --> Migrating up from version 20180610100000 to version 20181014170000
DEBUG - 2018-12-24 12:30:07 --> Migrating up from version 20181014170000 to version 20181015100000
DEBUG - 2018-12-24 12:30:08 --> Migrating up from version 20181015100000 to version 20181203115700
DEBUG - 2018-12-24 12:30:14 --> Finished migrating to 20181203115700

**Comment by odiea** [comment]
Here is some more fun for you.
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_rate_configuration (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_code_duplicate (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_code_invalid_chars (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_jurisdiction_duplicate (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_jurisdiction_invalid_chars (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_jurisdiction_required (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_category_duplicate (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_category_invalid_chars (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_category_required (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_category_required (TBD)"
ERROR - 2018-12-24 13:00:45 --> Could not find the language line "taxes_tax_category_required (TBD)"

**Comment by SteveIreland** [comment]
Thanks. Cleaning that up as well as the files themselves
