### ISSUE TITLE
Generate Same Barcode Multiple Times On Same Page

### ISSUE THREAD

**Issue by JigoloPete21** [opensourcepos/opensourcepos#2286]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.1
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: Apache
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hello,

This is more of a question than a feature request.  Is it possible to generate the same barcode multiple times on the same page?  The simple use case is we receive 10 (or sometimes 20) of the same product and we would like to print 10 (or sometimes 20) barcodes for this product on a single sheet of paper (for the obvious reason of saving paper).  My current workaround is to first generate the barcode, then save the .PNG of the barcode, and finally import the .PNG into an MS Word document, create 2 columns, then replicate the barcode throughout the document and print it.

While this workaround suffices for now, I was wondering what level of modification OSPOS would need to be able to support generating a single barcode multiple times on the same page within the application itself.

This previous issue may or may not be related to what I am asking:  https://github.com/opensourcepos/opensourcepos/issues/290

Thanks!
JP

**Comment by JigoloPete21** [comment]
This worked perfectly.  I replaced the file /application/views/barcodes/barcode_sheet.php with your modified version, added "Barcodes Per Page" into the Custom 10 field, and then tested 2 items by increasing their "Barcodes Per Page" value to 4, and it printed a total of 8 barcodes (4 per item).  This should definitely be a core feature of the application because it's so handy!  Thank you again for spending the time to add this feature.  I've attached screenshots of what I did in case anyone needs a visual of how it works.

![screen shot 2019-01-12 at 1 40 48 pm](https://user-images.githubusercontent.com/13972098/51078852-be844b00-1670-11e9-8d63-c9fcbfc71617.png)

![screen shot 2019-01-12 at 1 40 23 pm](https://user-images.githubusercontent.com/13972098/51078853-c17f3b80-1670-11e9-851f-906c8012dc8b.png)

![screen shot 2019-01-12 at 1 43 04 pm](https://user-images.githubusercontent.com/13972098/51078855-c6dc8600-1670-11e9-8670-fcaa8bedf9d2.png)

**Comment by odiea** [comment]
Glad it helped you out.

**Comment by Aravindalp** [comment]
What will be the solution after upgrading to 3.3.1. version? This method will not work for version 3.3.1. Please help

**Comment by bua2020** [comment]
Hello, I would like to ask, does this core feature works with continuous label paper? I have 4 stickers per row without cell-space. Please kindly suggest sir! Thank you very much in advance!
