### ISSUE TITLE
Increasing Session Timeouts Does Not Work

### ISSUE THREAD

**Issue by JigoloPete21** [opensourcepos/opensourcepos#2288]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.1
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: Ubuntu 16.04
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hello,

It appears that increasing the session expiration value within the file **/application/config/config.php** has no effect at all.  I've attempted to increase the value from the default 7200 seconds to 10800 or even 0 (to disable sessions timing out), however, sessions still seem to timeout after 7200 seconds of inactivity. 

To recreate the issue, simply increase the value of the following field to anything above 7200:

`$config['sess_expiration'] = 7200;`
Then reloaded Apache: `service apache2 reload`

It should be noted that decreasing this value DOES appear to work.  So changing it from 7200 to 30 will indeed timeout your session within 30 seconds of inactivity.  So I know the value is being fed into the application correctly in this instance.  Am I doing something wrong or is 7200 seconds simply a hard limit on session timeouts?

Thanks!
JP

**Comment by tajammalads** [comment]
I found the solution for this.

Just go to file
../application/config/config.php

then go to "Session Variables" Section
and find "ses_match_ip"
then change value from "TRUE" to "FALSE"

$config['sess_match_ip'] = FALSE;

That's it. :)

**Comment by jekkos** [comment]
Ok good to know, thanks for posting this back.
