### ISSUE TITLE
how to add past date sales

### ISSUE THREAD

**Issue by mdeora** [opensourcepos/opensourcepos#2291]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

Using latest stable release version with php 7.1

### Issue / Bug  / Question / New Feature

How do I add the sales of any of my past days or import sales from other system to this ?
There is no documentation on this.

**Comment by jekkos** [comment]
Only way is to import it using SQL.

**Comment by mdeora** [comment]
can you direct me to some documentation on this? with which fields to add data into ?
Is there any way to do that using adding a custom field in the sales section?

**Comment by jekkos** [comment]
I'm afraid the only documentation here is the code, as there is no feature whatsoever to support this usage. Don't know what you mean exactly with the second question.

**Comment by mdeora** [comment]
I mean, if there is a way to add a custom field in the sales entry?
To be able to change the date/time of sales entries seems to be a valid scenario/feature to me.

**Comment by nyenius** [comment]
Yes, I also need this feature. I think it's important for some on the first time they migrate to OSPOS.

**Comment by mdeora** [comment]
@nyenius I have found a way out for time being. Once you enter the sales record, go to daily sales and click on the edit icon along with the record. From there change the date/time to the desired date time.
For already added data or past imported data, you need to do it from mysql db.
Hope this helps.
