### ISSUE TITLE
Happy New Year! 

### ISSUE THREAD

**Issue by WebShells** [opensourcepos/opensourcepos#2292]
Happy new year everyone, wishing you a great year ahead full of more and more success...
We would like to thank all contributors, collaborators, and org members for keeping up the good work all through 2018 and the past years. 
Have a blessed 2019 from @opensourcepos/org 🎉🎈🍾🥂

**Comment by XYKOinfo** [comment]
Happy new year everyone!

**Comment by daN4cat** [comment]
Happy New Year

**Comment by SteveIreland** [comment]
My New Year's Resolution is to stay out of trouble and finally make @daN4cat happy with the first pull request.  Yes, I know it's a stretch goal.   ;-)

**Comment by WebShells** [comment]
@SteveIreland congrats, still struggling here 🤦‍♂️🤣

**Comment by ekardian** [comment]
same

**Comment by nathanzky** [comment]
Happy New Year Everyone...

**Comment by mckaygerhard** [comment]
:+1:
