### ISSUE TITLE
A suggestion/enhancement to show the cost and profit in the chart report

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#2293]
A suggestion to show the cost and profit in the chart report. see the image, im limited in the code, im learning, please add the idea for future releases. and blessing for all in this new year
[Capture imagen](https://prnt.sc/m1y27w)

**Comment by daN4cat** [comment]
This is not easily achievable without some rework of the pie visualisation tooltip.
At the moment it just reads the value used to compute the % of the total pie and add a currency symbol.
It might possible to have something done, but my recommendation is install Reportico and read OSPOS MySQL database and build your own reports with that tool.

**Comment by crazyfree** [comment]
let me do a pull request :p

**Comment by ekardian** [comment]
after 2 years, i installed reportico, my time its lava XD, not bad ( reportico, now i need learn mysql jaja

**Comment by daN4cat** [comment]
What's lava XD?

**Comment by ekardian** [comment]
> What's lava XD?

Lava mean No time, i said that because i installed after a few year after you told me about reportico for my reports, if a said my realashionship is lava mean i dont have girlfriends XD, 
if i write code, a very wordt code, so, my code is lava, and XD mean a big smile,
im trying to be a funny guy, im a funny guy in the real world, we need smile in bad times.
