### ISSUE TITLE
New Enhancement to update whole sale price

### ISSUE THREAD

**Issue by nathanzky** [opensourcepos/opensourcepos#2295]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.0.21
- MySQL or MariaDB version is: 5.0.18
- OS and version is: RHEL7
- WebServer is: Apache2
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 7.0.21

###  New Feature

I have a requirement to update the whole sale price if the cost is change when we receive the item.
![whosale](https://user-images.githubusercontent.com/26484936/50630460-69eb1c80-0f5a-11e9-90c5-42578595b941.JPG)

**Comment by jekkos** [comment]
This is already available in one way, check in the config section. You can average out the item price after receiving it in the orders. Feel free to extend as you like and contribute back.

**Comment by nathanzky** [comment]
thanks @jekkos, but would it be possible if the new price can reflect not as average?

**Comment by jekkos** [comment]
Yes that won't be a big change.. But I don't need it so no incentive to implement it.

**Comment by odiea** [comment]
Do this at your own risk.
With Notepad++ or some text editor try changing the following.
Application/models/item.php
around line 943 you should find.
public function change_cost_price($item_id, $items_received, $new_price, $old_price = NULL)
Replace $average_price with $new_price. 
$data = array('cost_price' => $average_price);
to
$data = array('cost_price' => $new_price);
Go to configuration and enable Calc avg. Price (Receiving)
This should give you what you are looking for.

**Comment by nathanzky** [comment]
@odiea Thank you.. this solves my issue..
