### ISSUE TITLE
[Sat Jan 05 07:37:14.043857 2019] [proxy_fcgi:error] [pid 2991:tid 139866666948352] [client 119.160.99.28:0] AH01071: Got error 'Primary script unknown\n'

### ISSUE THREAD

**Issue by MohsinAlii** [opensourcepos/opensourcepos#2298]
i;m facing that issue initially when deployed on server it works fine but after some time is shows file not found and apachi 
error log shows this error

**Comment by daN4cat** [comment]
This has nothing to do with OSPOS, use Stackoverflow or Google to search for a solution, for instance: https://stackoverflow.com/questions/44054617/mod-rewrite-in-2-4-25-triggering-fcgi-primary-script-unknown-error-in-php-fpm
