### ISSUE TITLE
jQuery Validation with Tax Configuration Maintenance

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2300]
The pull request for reworking tax configuration is now available.

Some technical points to note about tax configuration.

It takes advantage of the jQuery plugin.

The jQuery plugin, due to an unfortunate design decision, uses the "name" attribute to identify fields instead of the "id" attribute.  This means that the name attribute needs to be unique and that violates a basic html coding standard. That explains why the pattern that was in place for small table maintenance was used.  When I followed the same pattern I was asked to rewrite it - which is totally justified and I was and still am happy to do so (and despite the challenges I'm happy with the end result).

Fortunately the jQuery Validation plugin provides an alternate path to associate a rule with a field.  So I was able to use a method to locate a field by id and attach the rules to it.  That is the approach I've taken with the rework.

Through trial and error I've settled in on some conventions that work.  However, JavaScript and/or the validation plugin, being what they are, had one odd behavior that I felt I had to program for since I couldn't zero in on the cause(s).  It could be a bug in the plugin or it could simply be something I'm missing.

The use case scenario I was developing for is where there are data errors on the form (reported by the plugin) and the user chooses to ignore the errors and clicks on the Save button.   There are two ways to handle this ... first I could repeat the validations in PHP and ignore the save request if errors or found or secondly I could reject the save request on the client side if errors are found.  I chose the later approach because (at the time) it seemed cleaner and more straight forward.

~~The error is that the validation plugin submitHandler doesn't always seem to recognize that there is an invalid field in the form and therefore submits the form anyway.  I added invalidHander to the mix to see if it might shake things up enough that the behavior would be more consistent, but that didn't seem to improve the situation.  But it has worked in some of my tests but it seems in most cases it doesn't.~~

~~So I have code in there to handle both scenarios (where the error is detected and where it isn't detected).  So I apologize for what seems to be unnecessary code but it will take someone with some with more expertise than me in JavaScript and the jQuery Validation plugin to sort this one out.  Google search results were all over the place on this issue and didn't seem to me to provide a consistent answer.~~

So there it is.   I'll download the build and retest it to make sure I didn't fat finger something at the last second or blunder the merge.  But I'm hopeful that it is done and we can stick a fork in it.

**FOLLOWUP** --  *There was a fatal error in the approach I used to address what I identified as a bug.   So I removed the code used to interrupt the bug and even though I encountered the problem yesterday (several times) I have not been able to recreate it today.  Hopefully it was simply a case of self-induced misery.*

**Comment by SteveIreland** [comment]
This was more of an informational post than an issue.  So I expect to close it soon.

**Comment by jekkos** [comment]
Normally validation plugin should indeed cancel the submit if any of the fields become invalid. This is to my knowledge default behavior, so there might have been something that changed it?
Also regarding validators the class of an element can link to a validator name. This approach is used elsewhere in ospos and afaik should work.

**Comment by SteveIreland** [comment]
Yes.  I've seen that and have used the same pattern where it already exists  (i.e. the remove row icon).

However, my mother raised me to reserve the class names for CSS styling lest things start getting confused so I probably will NOT be the one to start that. :-)
