### ISSUE TITLE
Supplier update or add failed

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2309]
In the last update of ospos, when adding a new supplier I have the following error: Supplier update or add failed.
![captura de pantalla de 2019-01-12 01-19-38](https://user-images.githubusercontent.com/29256343/51070571-040d2d80-1609-11e9-9394-7486a18e9c7e.png)
![captura de pantalla de 2019-01-12 01-19-46](https://user-images.githubusercontent.com/29256343/51070577-14bda380-1609-11e9-8c8e-bc58192d1155.png)

**Comment by odiea** [comment]
Try scrolling down to the bottom of the form and put a number into Tax id and see if that helps.

**Comment by andriux1990** [comment]
thanks odiea.. it worked

**Comment by odiea** [comment]
When adding a new supplier the Id needs to be filled in because the id field does not accept a null value.

**Comment by jekkos** [comment]
Shouldn't it just be nullable then? @SteveIreland ?

**Comment by daN4cat** [comment]
If my memory is right I argued not to make this stuff mandatory. We should fix.

**Comment by odiea** [comment]
Yes would someone change that.

**Comment by emi-silva** [comment]
Was it me? Oh gosh, I'm sorry if it was. Unfortunately I'm in the middle of my trip through South America and unable to check this at the moment.

**Comment by jekkos** [comment]
Also seeing a status 500 when I don't select an expense category id. This case should be validated by the frontend first.

**Comment by jekkos** [comment]
Ok I changed this field to allow NULL values. However we there are other issues. Will make a new issue for that.
