### ISSUE TITLE
Bintray not showing current commits.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2312]
Here is the latest version shown on bintray. opensourcepos.20190107174727.master.acba94.zip. This is Dated 8 days ago according to bintray.

**Comment by jekkos** [comment]
Bintray account has been rate limited again. WIll do some cleanup and ask them to enable it.

**Comment by jekkos** [comment]
Cleaned up some older builds and deleted pre 3.3.0 versions. Will ask them to enable the account again.

**Comment by jekkos** [comment]
Got reply from jFrog, should be resolved now.

**Comment by odiea** [comment]
I will check it after you make the commits.

**Comment by jekkos** [comment]
Seems to be working again, last commit on bintray.
