### ISSUE TITLE
Preparing the way for Third Party Integration

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2315]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.6.3
- MySQL or MariaDB version is: 5.7
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### New Feature
** I renamed the issue because it's a bigger question than just the UI.

Is anyone against me renaming the Mailchimp tab in Config to "Third Party Integration" in order to make way for additional integration configurations such as the one I am working on for CCIDesq CMS? (#1680 )  

The idea is that each Third Party Integration configuration (API keys, etc) would be stacked vertically, but it requires making the name of the tab to be more generic than "Mailchimp".  If Third-Party Integration is too long then perhaps we could make it just "Integrations" or "3rd Party Integration".

We also need to create space in the database for Third Party Integration settings (API keys, etc).  Currently ospos_config is being used for it since its limited to just mailchimp, however with potentially dozens of different integrations I propose we add a table ospos_integrations with key and value columns which allows the database storage of the various settings needed.

**Comment by phantomgannon** [comment]
Thats a great idea. We're looking at integrating SendinBlue which is a cheaper Mailchimp alternative so that would work for us as well.

**Comment by objecttothis** [comment]
We are currently working out the best way to implement 3rd Party Integrations (See #1680) and this change is just the front end UI to provide the space for the settings of each integration.

**Comment by daN4cat** [comment]
Full support the initiative, it makes sense to me. Therefore go ahead.

**Comment by daN4cat** [comment]
Not sure you can make it for 3.3.0, let us know so I can tag it with right version.

**Comment by objecttothis** [comment]
No let's put it in the next release. 3.3.0 is already needing to come out soon.
________________________________

**Comment by objecttothis** [comment]
#2330 satisfies the code end of things for space to see and modify third party integrations.  I will create another branch now to migrate the mailchimp settings in app_config to a new table ospos_integrations and modify the code to look there for the mailchimp settings.  Then when new integrations get introduced they will need to use ospos_integrations to store settings for third party integrations.

**Comment by jekkos** [comment]
Don't directly see the benefits of moving these api keys to a new table. Won't it then have exactly the same structure as the existing config table, just a generic key-value store? 

Not sure also if the api keys are being hashed or encrypted in any way.

**Comment by objecttothis** [comment]
Yes, structurally I think the table would be the same. Organizationally there could end up being a dozen or more third party integrations each with anywhere between two and a dozen rows representing settings. This doesn't pose a problem for the speed of the application and other than it being not as fun for devs to look through in phpmyadmin it can stay a part of app_config. The only question is how far we want to go in saying what is ospos and what is not. If we just want to make that distinction in the code by using hooks to kick off extension code then the database can stay as is and use app_config. If we want to extend the structural separation to the database then create a separate key->value table. I don't feel strongly so just let me know what you want to do.

**Comment by objecttothis** [comment]
Currently I don't think they are but I may be mistaken. I believed GDRP would dictate that we should be.

**Comment by objecttothis** [comment]
@jekkos I take that back.  Mailchimp API keys and list ID's are being stored encrypted in the database.  That will need to be a requirement for all such settings.

Do you or @daN4cat have thoughts as to my comments a week ago about separating the integration settings or just keeping them in app_config?  I'm OK with either but think it would be better abstraction to have third party integration settings in their own table rather having 2-12 settings per integration cluttering up the app_config table.  Let me know what you guys decide and I'll implement it.  I'm working on the CLCdesq integration now, so it will affect how I implement the database storage.

**Comment by daN4cat** [comment]
Yes keys are encrypted as any other credentials for email and SMS features.

Let's keep all config in one key & value table. I don't see the value in complicating our lives. Semantically they are all config and there is little benefit going for separation of concerns.

**Comment by daN4cat** [comment]
Question: should we consider ReCaptcha config a Third party integration story, hence we move it to "integrations" tab? Thoughts?

**Comment by odiea** [comment]
That and maybe Message.

**Comment by daN4cat** [comment]
True, Message is an integration too.

**Comment by objecttothis** [comment]
These are all really good questions. It sounds like making Third Party Integrations well defined is going to be important. The thought was to provide a means for bringing in code that will interface with other systems to communicate data back and forth. So then what about all these other features in the code that rely on 3rd party software. Message feels to me like it fits well in integrations. Recaptcha feels more to me like a feature of ospos itself. Kind of like jQuery on the backend and bootstrap. Clear words escape me here but what if we differentiate between core features of ospos that happen to be 3rd party and very useful but nonetheless not core to ospos.  recaptcha login is a security thing so while not everyone uses it, it does support a major goal of ospos which is security of the app. message, Mailchimp, ccidesq, etc all are useful to some or most but are not central to the goal of the app and therefore qualify better in integrations. thoughts?

**Comment by daN4cat** [comment]
Yep, it becomes a bit of a philosophical debate. We could even argue that Nominat is an integration.

**Comment by objecttothis** [comment]
Right, but we have to draw the line somewhere. I believe that we talked about 3rd party integrations were to be implemented use post controller hooks. Perhaps that is a good place to draw the line of what is an integration? I don't feel too strongly other than I think it's important to have a clear definition.

**Comment by daN4cat** [comment]
It doesn't sound a good criteria. Let's leave it as it is.

**Comment by objecttothis** [comment]
> 
> 
> It doesn't sound a good criteria. Let's leave it as it is.

@daN4cat I think you're saying to leave current code in place.  I'm fine with that, but I do think it would be helpful to have some sort of a clear definition of what ospos considers a third party integration for future additions.  That way it's easy to determine whether stick the settings in integrations or some other place.

**Comment by objecttothis** [comment]
@jekkos @daN4cat We want to write the third party integrations code so that it's easily extendable to other integrations.  I think this is why we said that we would use post_controller hooks to kick off third_party integrations.  The problem is that the hook runs after the methods in the controller have already run so the hook won't have access to the data in the methods unless we are writing the changes to a file and pulling the changes in the file which then file maintenance becomes a bit of a pain.

What we really need is to be able to kick off an integrations method immediately after making the change to the data and passing the data that was changed to that method.

For example:
save() in the Item model would add a "hook" before the return called integration_save() which resides in an integration_helper and pass it the data regarding the changes.

I'm not entirely sure the best way to approach this, but I do know that the method of logging changes in a file and then pulling that file is really complicated because there is not only a file maintenance issue (how to keep the log from getting very large) and the issue of how does a hook track what changes have been already executed in the integration and which ones haven't.

**Comment by daN4cat** [comment]
Have you checked the hook logging the database requests?
You can enable that feature from config.
Probably it's not strictly what you want but could offer some inspiration?

The issue with the extensibility you are talking about is security.
Any rogue plugin becomes a backdoor for data leak.
So we need to think about this point.

 But I see the benefits of your idea. If I find the time I'll build a plug in to post to Google sheet some end the day transaction payload for logging and accounting purposes.

**Comment by objecttothis** [comment]
> Have you checked the hook logging the database requests?
> You can enable that feature from config.
> Probably it's not strictly what you want but could offer some inspiration?

Thanks for the tip.  I just found this: https://blog.onderweg.eu/2011/08/codeigniter-query-log-hook/
Potentially, we could have a post_system hook that
1- Logs the database requests (maybe JSON_encoded) in a 660 or 600 permission file.
2- Let's Third Party Integrations do their things.
3- Deletes the log file.

Unless the log file name was generated uniquely for that transaction we could face concurrency issues for users of CI with large operations.  For example if User A's browser kicks off the above at or very near to the same time as user B and the same log file is used for all transactions you could have a situation where user A's changes get logged to the third party integration of user B's action.  If each action gets its own log file that eliminates concurrency issues and as long as the file gets deleted at the end of the action you won't end up with a large folder of log files.

> The issue with the extensibility you are talking about is security.
> Any rogue plugin becomes a backdoor for data leak. Therefore we need to think about this point.

I think third party integrations should be stored in the repository and be subject to the same code checks and standards that the rest of the code is subject to.  That is the only way we can do third party integrations and still have code quality controls to prevent data leaks.

The extensibility I was referring to is writing the hooks to do the work of kicking off Third Party Integrations but requiring all Third Party Integration code be confined to the section of the code we allot for it.  This way there isn't a problem where we get someone submitting, even a really good, integration, but it's all over the place in the code and really muddies it up.  Depending on the integrations we may need to add future hook points, but at least there is some separation.

> But I see the benefits of your idea. If I find the time I'll build a plug in to post to Google sheet some end of the day transaction payload for logging and accounting purposes.
