### ISSUE TITLE
Change time zone

### ISSUE THREAD

**Issue by erastus** [opensourcepos/opensourcepos#2321]
### Bug
application/helpers/locale_helper.php

> 'America/Belize' => '(GMT-06:00) Saskatchewan, Central America',
'America/Cancun' => '(GMT-06:00) Guadalajara, Mexico City, Monterrey',
'Chile/EasterIsland' => '(GMT-06:00) Easter Island',

change time zone America / cancun by America / Mexico_City

> 'America/Belize' => '(GMT-06:00) Saskatchewan, Central America',
		'America/Mexico_City' => '(GMT-06:00) Guadalajara, Mexico City, Monterrey',
		'Chile/EasterIsland' => '(GMT-06:00) Easter Island',

**Comment by daN4cat** [comment]
Merged
