### ISSUE TITLE
Toast Notification on Item submit broken and "New Item" not working

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2323]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.6.38
- MySQL or MariaDB version is: 5.7.24
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue
I was having this issue with commit hash acba94 so I refreshed the code to commit hash a1b642 and refreshed the database with my production data.  On first login, the migration takes place and doesn't generate errors in the PHP logs.  

When I attempt to update an item by clicking the edit icon next to the item then clicking submit on the form the toast notification does not pop up but instead refreshes the screen with the message {"success":true,"message":"You have successfully updated item [name]","id":"[item_id]"} where entries in square brackets are the actual values.

it should be giving me a toast notification with this information, but isn't.

Also, the "New Item" and "Excel Import" buttons are broken (e.g., clicks do not respond).
![annotation 2019-01-28 152550](https://user-images.githubusercontent.com/17935339/51838619-454b5000-2320-11e9-8a01-a510e91fee19.jpg)

**Comment by objecttothis** [comment]
Also, the PHP or the OSPOS error log aren't giving me anything.

**Comment by jekkos** [comment]
Will have a look somewhere this week

**Comment by SteveIreland** [comment]
I just downloaded and installed the latest master ( commit level acba94) - added an item  - and then updated it without any odd behavior. 

This was over  a new database so migration was not involved.

When I tested the commit version you used I found that the database migration failed (on a new database build).  So something is out of sync with that branch.

I'll retest master tomorrow night using your specific configuration if your can provide some additional details about your configuration.  What flavor of tax configuration are you using?  Are you using the default tax system or destination based tax?  Are  you using any custom attributes?

Did you check to see if there were any JavaScript errors sent to the console log?

**Comment by objecttothis** [comment]
I'm running a FAMP server.  The version details are in the "Installation Information" section of the report.  This is indeed a migration from 3.2.0 where custom fields were heavily used.  This is commit has a1b642 and 675c6e that I was experiencing this issue with and both are post latest master.  They may be related to @jekkos fixes for datetime if the same issue isn't happening in the latest master.  I'll check for javascript errors in the console log.

**Comment by objecttothis** [comment]
@SteveIreland I just downloaded and installed the latest master (acba94) and I am experiencing all the same problems minus the table columns not appearing for migrated attributes.  @jekkos said he would take a look at it.  I did take a look at the demo (demo.opensourcepos.org) and while the new item button seems to work in that, the submit and New buttons don't work after opening the item creation view.

**Comment by jekkos** [comment]
Will try to take a look after I finish my fix for the refactor, otherwise I need to switch context (and branches) and so that might not be very efficient

**Comment by SteveIreland** [comment]
#2332 resolves a migration issue that could possibly be the issue here.

**Comment by objecttothis** [comment]
OK, test it once I get my pull requests fixed.

**Comment by jekkos** [comment]
Ok guess this was solved as users were able to create plenty of items on our demo server.

**Comment by objecttothis** [comment]
Something is wonky on my build then.  I'm using the same commit hash as the demo, but the new button doesn't function on my install.  What platform is the demo running?  Perhaps there is a compatibility issue with some server installations?  I am running a FAMP stack.

**Comment by objecttothis** [comment]
@jekkos do you have any idea why these problems would manifest on my server but not on the demo?  I'll try in the meantime to make an install on a shared hosting server I have access to and see if I get the same problem on that one.  The only differences that I think are in place between my server and the demo is potentially a different stack and the fact that my data is migrated.  Let me also try a clean database and see if that shows different behavior.

**Comment by jekkos** [comment]
You're database is probably also stuck and not running the migrations properly. Can you check the status 500 error log output?

**Comment by objecttothis** [comment]
I just tried the same build on a fresh database with no data to migrate and it had the same issue, so it doesn't seem to be due to migrated data.  I'll install a fresh database and software on this shared server which runs a LAMP stack and see if it has the same problem.  that will help narrow it down.

**Comment by jekkos** [comment]
But can you check the error in the http response ? Enable debug logging first and then you can see what is actually wrong.

**Comment by objecttothis** [comment]
@jekkos I had debug logging enabled in the config.php.  I increased the log level 4.  I also checked the server HTTPD error logs as well as the php error logs.  When I click the New Item or Import button nothing gets generated in any of the logs.  The Javascript console in Firefox did show me an error when the items page loads but I'm not sure if it's related.
![javascript error](https://user-images.githubusercontent.com/17935339/52620019-c7a94780-2ebc-11e9-90b0-a7680422d421.jpg)

I'm going to install a fresh copy on this shared server in the meantime and see if it gives me the same behavior since I'm not getting much out of logs.

**Comment by objecttothis** [comment]
Maybe that javascript error is related because I just checked the console on the demo site and that error doesn't come.

**Comment by objecttothis** [comment]
OK, I installed a clean database and the same commit hash on the shared server and it doesn't give this error, so it must be something with the way that my FAMP stack is interacting with the javascript.  Older commits are not exhibiting this problem on my stack, so let me see if I can figure out what the change is that's causing the problem.  It's possible that it's pretty unique to my configuration, but it's also possible that others running a FAMP stack may run into the same problem.  Let me see if I can figure it out.

**Comment by jekkos** [comment]
Thsi could be an issue in localStorage of the browser. Can you try to delete all it's contents for the site?

**Comment by objecttothis** [comment]
@jekkos I just installed 9e2f9f on the problem server and it works just fine.  Something changed between the 9e2f9f Master and 3b9bf5 that resolved the problem.

**Comment by jekkos** [comment]
Ok could have been a browser issue as well I guess.

**Comment by objecttothis** [comment]
Possibly, but Firefox is a fairly common browser. If it comes back then I will research it further, bit I'm under a deadline to get the CCIdesq integration done with ospos so it's not urgent for me.

**Comment by objecttothis** [comment]
The problem is back again.  On the same server and same browser commit hash efd4e9 is giving this message but commit hash 9e2f9f is working just fine.  The server logs don't generate any errors, ospos doesn't generate any errors, debug or info messages regarding this.
Here is the message
>{"success":true,"message":"You have successfully updated item [REDACTED]","id":"1"}

The error console gives me this prior to clicking submit in the view regardless of whether I have changed any values or not in the item view.
>TypeError: this.columns[a] is undefined[Learn More] opensourcepos.min.js:13:27060
>   toggleColumn https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:13
>  hideColumn https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:14
> m https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:39
>    each https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:2
>    m https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:39
>    n https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:39
>    <anonymous> https://[REDACTED]/public/items:394
>    k https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:3
>    fireWith https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:3
>    ready https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:3
>    g https://[REDACTED]/public/dist/opensourcepos.min.js?rel=f4e44a4ac7:2

I'm guessing from the error console that this is a jquery problem.

**Comment by objecttothis** [comment]
I should also note that the New Item button also doesn't work.  It's not just the toast notification.

**Comment by daN4cat** [comment]
You sure you are using the correct min.js and min.css?

**Comment by jekkos** [comment]
Can you try with debug flag enabled?

**Comment by objecttothis** [comment]
@jekkos sorry can you remind me how to do that?  I vaguely recall you telling me to add "debug=" or something like that to the URI.

**Comment by jekkos** [comment]
Add a trailing ?debug=true

**Comment by objecttothis** [comment]
OK, here is that result:
>TypeError: this.columns[index] is undefined[Learn More] bootstrap-table.js:2425:9
>    toggleColumn https://192.168.0.8/pos_dev/public/bower_components/bootstrap-table/src/bootstrap-table.js:2425
>    hideColumn https://192.168.0.8/pos_dev/public/bower_components/bootstrap-table/src/bootstrap-table.js:3009
>    toggle_column_visibility https://192.168.0.8/pos_dev/public/js/manage_tables.js:195
>    each jQuery
>    toggle_column_visibility https://192.168.0.8/pos_dev/public/js/manage_tables.js:194
    init https://192.168.0.8/pos_dev/public/js/manage_tables.js:253
>    <anonymous> https://192.168.0.8/pos_dev/public/items?debug=true:444
>    jQuery 4
>    fire
>    fireWith
>    ready
>    completed

**Comment by jekkos** [comment]
Looks like a browser cache issue again. Can you try to enter delete localStorage?

**Comment by objecttothis** [comment]
> Looks like a browser cache issue again. Can you try to enter delete localStorage?
I had serious doubts about it being a caching issue since in the same Browser one tab was working and a different install on the same server just a different tab was not working.  I cleared my cache in Firefox Developer Edition and then reloaded the problem page and it works fine now.
