### ISSUE TITLE
Builds are not updating the commit hash in the footer of the application

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2324]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: a1b642
- PHP version is: 5.6.38
- MySQL or MariaDB version is:  5.7.24
- OS and version is:  FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug
Each bintray build is not updating the commit hash displayed next to the version information in the footer of the application.  I'm not sure if this is hardcoded or stored somewhere else (didn't see it in app_config), but I would think that we would want to be updating it with each bintray build for better bug reporting.

**Comment by jekkos** [comment]
The issue in the past here was that we were committing grunt build output to git again. This prevented me from substituting the commit hash with the correct one as that would the add a new change to the git repo (which we would have to commit yet again).

But with the current workflow this might be easier to tackle if we agree that we only do this for packaged zips (in this case in the grunt build itself).

**Comment by jekkos** [comment]
I've done a fix for this. The commit hash is now substituted by travis before the packaging. So all bintray and official builds will have this variable filled in. I could enable the substitution on checkout as well but the we risk people checking in the config.php file as git would detect that it changed every time.

**Comment by jekkos** [comment]
Not quite right yet, need to double check

**Comment by jekkos** [comment]
Works now. Demo show the last commit hash in this repo now.
