### ISSUE TITLE
Adding max spend by month for the client (customization)

### ISSUE THREAD

**Issue by wd-code** [opensourcepos/opensourcepos#2326]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is:  f1cf3d3
- PHP version is: 7.0.33
- MariaDB version is: 10.1.37
- OS and version is: Debian 9.7 stretch
- WebServer is: Nginx
- Selected language is: French

### Question

*Disclamer: I'm French so I'm sorry if my English is bad*

I would like to know if your willing to help me: I'm in an association were poor student can come to buy some food at a very low price. However, there are limited in the spend amount in the store by month. Can we creat a new field *max spend by month* input in the creation of our "client" for this? If not we can specify a generic amount for everybody.
When the "client" exceeds this amount we want to disable the possibility to finish the sale (for exemple: an alert message instead of the button).
However, if a code is entered in the *Find or Scan Item or Receipt* input we can bypass the max amount system.
And by the way, can we disable to finish a sale when there is not client selected to?

At the moment it's a fresh install and the code have not been modified.

Thanks a lot if somebody can help us for that.
Have a great day.

**Comment by odiea** [comment]
You can try using the gift card feature.

**Comment by wd-code** [comment]
Hi,
Thanks for your reply and I've check the possibility to do that but it's too complicated to set up with the number of volunteers, and we've got too many students (more than one hundred) for the viability of the gift card solution.
However, I was thinking to add a custom JS script file in the code (this way I hope that after an update I've just to add the file again), but when I've tried to understand the code I'm not sure how to implement the file.
Do you think it's a possibility ?
Thank you very much anyway ;)

**Comment by jekkos** [comment]
Why would it be too complicated? You can just hand out the giftcards by number, so each student needs to get a number only once. Then you run a script that resets the amount on a montly basis after it was issued.

**Comment by odiea** [comment]
No further comments so I will close this one.
