### ISSUE TITLE
Receivings should be renamed to purchases

### ISSUE THREAD

**Issue by mdeora** [opensourcepos/opensourcepos#2328]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3 
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.1.3
- MySQL or MariaDB version is: 5.7
- OS and version is: Mac os mojave
- WebServer is:  apache web server 2.3
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Receivings is very confusing as a word, as some people relate it to the pending amounts to be received by customers. In my opinion it should be renamed as **Purchases** just likes **Sales** 

Thoughts?

**Comment by WebShells** [comment]
@mdeora right in a way, yet it cannot be considered yet as purchasing orders module... To me i have no problem about changing... @opensourcepos/org ?

**Comment by SteveIreland** [comment]
I would vote against the change.  When a purchasing component is incorporated then this would cause a LOT of confusion.

One word terms that can have multiple definitions can be confusing.  But if you don't like the term it is possible to change it for your site by tweaking the language files by either adding a qualifier or changing it to what you want to call it.

**Comment by objecttothis** [comment]
The problem with calling it purchases is that it is just as ambiguous because it doesn't define **who** is purchasing. The other thing about calling it purchases is that it implies there was an exchange such as money in exchange for the purchased product. While that is usually true, it isn't always true. For example when product is donated to a business it isn't purchased (paid for) so receiving is a better description. I do think that Product Receivings is better than Receivings but it's also longer.

**Comment by WebShells** [comment]
Thats what i meant when i said it cant be considered as purchasing orders... Thanks guys
