### ISSUE TITLE
Cannot add an Item in current Demo Server.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2329]
This is the error when hitting the submit button.
Error Number: 1054

Unknown column 'hsn_code' in 'field list'

INSERT INTO `ospos_items` (`name`, `description`, `category`, `item_type`, `stock_type`, `supplier_id`, `item_number`, `cost_price`, `unit_price`, `reorder_level`, `receiving_quantity`, `allow_alt_description`, `is_serialized`, `qty_per_pack`, `pack_name`, `low_sell_item_id`, `deleted`, `hsn_code`, `tax_category_id`) VALUES ('test', '', 'misc', '0', '0', NULL, NULL, 10, 20, 1, 1, 0, 0, 1, 'Each', -1, 0, '', '')

Filename: models/Item.php

Line Number: 401

**Comment by SteveIreland** [comment]
I noticed that the branch didn't reflect the latest database changes that are in master.

**Comment by odiea** [comment]
@SteveIreland I just created a new db. It gave me the upgrade warning when I logged on but the same issue shows as above.
I am using the current bintray version that is suppose to update the date as per @jekkos .

**Comment by odiea** [comment]
Current Demo still has this issue.

**Comment by SteveIreland** [comment]
Unfortunately the demo reflects the third party integrations branch which has not yet been rebased over the latest master.  So it is still running the migration scripts out of sequence.
