### ISSUE TITLE
Tax summary report shows double totals

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2335]
Opening this ticket before I forget to log it. When checking in 3.3 master I saw that the reported totals on that tax summary are twice the amount in other reports. Will check on latest to verify if this is still the case, but could be a SQL issue.

**Comment by SteveIreland** [comment]
Don't know why yet, but the migration didn't populate the sales_taxes table.  I need to fix that before I can test the "Sales Tax" summary report.  A ran a quick test of the "Tax Summary" report that is based over sales_items_taxes and didn't see any doubling of the numbers.  I compared it to the sales reports for the same period and it balanced.

**Comment by jekkos** [comment]
OK I'll double check on my side as soon as possible, but my version could have been out of date

**Comment by SteveIreland** [comment]
The latest pull request for IndiaGST contains a fix to the tax reports that resolves a problem I stumbled across during my tests.  It was picking up suspended sales and not just completed sales.  Hopefully this also resolves  your issue.

**Comment by SteveIreland** [comment]
@jekkos did the latest merge resolve the problem you saw?

**Comment by jekkos** [comment]
Ok updated to latest master and it's fixed now. thanks for taking care of this!
