### ISSUE TITLE
New Fresh Windows - The installation is not correct, check your php.ini file

### ISSUE THREAD

**Issue by fWd82** [opensourcepos/opensourcepos#2336]
### Installation information

- OSPOS version is: 3.2.3 - 4f5ad57
- OSPOS git commit hash is: 
- PHP version is: 7.2.5
- MySQL or MariaDB version is: 2.4.33 (Win32)
- OS and version is: Windows 10
- WebServer is: Apache 
- Selected language is: English

### Issue / Bug  / Question / New Feature
My windows is installed in **C drive** of my computer and I have installed my **XAMPP** in **E partition** of my computer. Yesterday Windows failed to start, I then **RESET** my windows _(Reset is option where Windows will rollback all changes and will not affect any personal files, but delete all installed softwares/apps on C)_. So my laptop successfully turned ON. But when I went to see if **localhost** is working, it went fine, even:
localhost/opensourcepos/public/
also run fine, but after submitting my login credentials _(username + password)_ I got this error:
**The installation is not correct, check your php.ini file.**
I remember I got this error before and I solved it by reading comments here #1607 and I fixed it by enabling/removing comments from certain plugins. But this is not working for me right now as my php.ini is as same as nothing is changed outside Partition C. 

I have tried adding PATH variable for php in System Environment but it still not working. 
Please if any one can help me. I have lot of data and I want to make it work. 
If you think I have posted in wrong place please remove this issue report but first I would love to have solution for said problem. 
Thank You, Waiting for reply.

**Comment by odiea** [comment]
These are the required 3.2.3 extensions. 'bcmath', 'intl', 'gd', 'openssl', 'mbstring', 'curl'

**Comment by fWd82** [comment]
@odiea Thank You very much for reply. 
Yes I have enable all these above extensions.
As I told before I have done nothing except removing apps/sofTwares from C Drive. All my PHP and OSPOS files are same as my previous successful 'version'.
I want to know what is changed after I have reset my C Windows.

**Comment by odiea** [comment]
My only suggestion would be to backup your database then reinstall xampp and ospos and see what happens. I can't remember if 3.2.3 will work with that high of php version. Good luck

**Comment by daN4cat** [comment]
No 7.2 was not supporter because cane out 3.2.3 release.

**Comment by fWd82** [comment]
Sorry, I have updated my question. In my question I have added correct version of OSPOS: **3.2.3 - 4f5ad57** I copied that version from my test machine.

**Comment by aristapribadi** [comment]
i have same problem

**Comment by EgyptianM** [comment]
Same problem here with a fresh installation.

**Comment by odiea** [comment]
Does not help not knowing the ospos version or the php version you are using.

**Comment by WebShells** [comment]
@odeia i think I should add the system info to be accessible outside the app folder... So we can request the info from the user by visiting a specific link...

**Comment by EgyptianM** [comment]
@odiea  for me I'm using php 7.2.4 and the latest stable version of OSPOS 3.2.3

**Comment by odiea** [comment]
As @daN4cat stated "PHP 7.2 was not supporter because came out 3.2.3 release." Try using an earlier version of PHP. Try 5.6 or 7.0 to see if that helps and make sure the extensions are enabled in your php.ini file.

**Comment by odiea** [comment]
@WebShells the only problem there would be you would then have to update 3.2.3 with the current sysinfo.

**Comment by daN4cat** [comment]
@odiea It looks like I need to go back to school, given the English of my quote....

**Comment by EgyptianM** [comment]
the issue still exists with php 5.6 and 7.1
ospos latest stable version and ampps 3.8 windows 7

**Comment by EgyptianM** [comment]
using php 5.6 solved it for me

**Comment by EgyptianM** [comment]
using PHP 7.1 results in this message: 
login_invalid_installation (TBD)
when trying to login.

**Comment by daN4cat** [comment]
Check the error_log and see if there is any message with regards to missing libraries.

**Comment by EgyptianM** [comment]
I couldn't find any error_log files.

So I removed it and re-installed again.
Made sure that all required plugins are enabled.
Worked fine on PHP 5.6
But on 7.1 it gives this error:

An uncaught Exception was encountered

I
Type: Error

Message: Call to undefined function mysqli_init()

Filename: C:\Ampps\www\ospos\vendor\codeigniter\framework\system\database\drivers\mysqli\mysqli_driver.php

Line Number: 135

Backtrace:

File: C:\Ampps\www\ospos\public\index.php
Line: 315
Function: require_once

Using Ammps 3.8 on windows 7 with php 7.1

**Comment by daN4cat** [comment]
It's a fundamental problem with your PHP7 installation. The libraries are not installed, you are even missing the mysql one.
Read the wiki and look for windows installation suggestions.
I close this issue as it's a non OSPOS one.

**Comment by EgyptianM** [comment]
All libraries are installed and mysql isn't missing I checked for it and other scripts works fine on the same machine.

**Comment by EgyptianM** [comment]
If this is the situation then it's a script problem because mysql is removed from php 7+ 
How can I install it on php 7+ when php 7+ doesn't support mysql commands?
You need to move to mysqli or pdo.

**Comment by daN4cat** [comment]
mysqli

**Comment by EgyptianM** [comment]
mysqli is installed and enabled I checked for it before writing my comment

**Comment by daN4cat** [comment]
Where have you downloaded OSPOS application code?
