### ISSUE TITLE
Add migration for tax_code field in Suppliers table

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2338]
As reported in #2309 there was an issue in creating or updating suppliers as no null values were allowed. In the last india migration script the `tax_code` column in customers table is migrated to `sales_tax_code_id`. 

- [ ] This column seems to refer to the `sales_tax_code` table without using any constraint
- [ ] The new `sales_tax_code_id` in `ospos_customers` does not have any constraint either
- [ ]  The `migrate_customer_tax_codes` uses the `fa.sales_tax_code` in it's where clause. I don't know if this column was ever present or whether it was mistaken with `tax_id` that is present next to `sales_tax_code_id`.

So I think this one was forgotten in the GST migration script. Next to `migrate_customer_tax_codes` we also need a `migrate_supplier_tax_codes`.

**Comment by daN4cat** [comment]
@SteveIreland is this something you plan to fix?

@jekkos shall we move this to 3.4.0?

**Comment by daN4cat** [comment]
Ping again, @jekkos @SteveIreland  see above comment.

**Comment by SteveIreland** [comment]
I assumed @jekkos fixed this with #2343, but since he hasn't yet responded here I'll go ahead and take a look to confirm. If this wasn't included in that pull request I'll do something about this.

**Comment by daN4cat** [comment]
Thanks, I really want to give a kick and close 3.3.0 end of the month.

**Comment by SteveIreland** [comment]
I've done a preliminary review and will follow up more closely when I have a larger slice of time.

But I believe there is some confusion.   The tax code (nor tax_code_id) is not the same as the tax_id.

There is not a foreign key to the tax code on the supplier table.  There is a tax id which is just reference information for those sites that need the information printed on a purchase order or some other document.

On the customer table there is both a tax_id and tax_code (the foreign key which is named tax_code_id)   Prior to this upgrade the id used to be the tax code itself, but post upgrade the key is the tax_code_id (again, not the same as tax_id which is simply a reference number to be used for the customer's tax license when the customer is not supposed to be charged taxes.   I presume that is a U.S. thing.

**Comment by SteveIreland** [comment]
I admit to not including constraints where applicable so I apologize for that..  Having worked for decades with a relational database that initially didn't support constraints (and not experiencing any crisis as a result) I tend to think that constraints are a solution in search of a problem.  Regarding constraints I'm definitely OLD school.  But I didn't exclude them deliberately ... I just overlooked it.

I'll also point out that when populating databases from backups constraints ARE the problem.  They need to be disabled until the restore is complete.  But I actually won't argue with anyone about their value.  Especially in a scenario when developers which don't understand the database start making changes.

So I'll submit a pull request to include them.

**Comment by jekkos** [comment]
OK thanks for the clarification and including the constraints in a PR. All of the other tables use it so let's stay consistent there.

I might have been confused on the tax_id field then, might not be the best name if it doesn't contain a technical database id then, so just renaming to `sales_tax_code` might be an option?

**Comment by daN4cat** [comment]
Happy with this? Shall we close or is there more to be done?
