### ISSUE TITLE
My Printer Zebra TLP-2844 and barcode 

### ISSUE THREAD

**Issue by xrootmaster** [opensourcepos/opensourcepos#2341]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by xrootmaster** [comment]
Salam, I am working in Saudi Arabia and I have installed the OSPOS script.
I have a problem with printing the barcode on the label correctly. 
I tried a lot but eventually the barcode does not print in the correct location on the label.
My printer is TLP2844 and I thought of using programs such as Bartender and Other but same problem.
So, is it a radical, correct and easy solution to the barcode printing problem?

Please guide and help me, thank you.

**Comment by odiea** [comment]
1. Use the correct Zebra driver.
2. Use the correct label size in the software.
3 Tweak the OSPOS barcode settings sizes as needed.
The Zebra lp2844 is what I am currently using to test barcodes and I am having no issues with it.

**Comment by odiea** [comment]
You may waste a few labels but make sure the Zebra is set correctly for the label size you are using.

**Comment by xrootmaster** [comment]
Hello nice to find someone using the same printer ..
Please indicate the settings you have worked on, my Labale size is 1 x 2 inches
Even after the label is calibrated and when 10 labels are printed, it begins to change at the fourth or fifth poster and does not print exactly on the label

Can you help? Thank you

**Comment by xrootmaster** [comment]
Yes I understand that thanks for your time.
I mean, it's ok if the service is paid in exchange for getting a valid result, is it a way to do it?


Thank you .

**Comment by odiea** [comment]
Sorry to me it sounds like a printer issue not an OSPOS issue.

**Comment by xrootmaster** [comment]
Yes, I expected that, but I have another accounting program on my computer with Bartender program working very well for years.

I tried repeatedly to change printer settings and change browsers but did not get the correct results

Overall thanks for your participation and I will still look for a solution to the problem.

My respect
