### ISSUE TITLE
A little question about printing

### ISSUE THREAD

**Issue by Yourii2** [opensourcepos/opensourcepos#2342]
I'm using OSPOS 3.2.3 Clean install on xampp windows 7 86bit 

for a Delivery Store

i'm using the tables as a delivery name 

all i want to do just to print 2 receipts ... the first one is the normal receipt for the customer

but the other one will be to the Delivery man and i don't know how to print 2 Receipts in the same time 

the second Receipt have the Delivery Name and the total amount and the items list not more 

how can i do this ? 

and about the category can't we make a category list ?? like a lot of other Applications ?  

i really love ospos and i would love to work on this application for every thing 

i will wait your replay 

thanks for your time

**Comment by WebShells** [comment]
Am worried about the 86bit thingy 😶... You can select to print 2 copies in advanced printer settings or during final print confirmation page, does it cover your needs?

**Comment by WebShells** [comment]
No reply... will close...
