### ISSUE TITLE
Attributes showing Date twice if item has Date and other Attributes.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2346]
I moved the Attributes in Register to Description because the Name was getting overfilled. The following issue happens in the current Demo and current master.
![2019-02-05 16_16_23-window](https://user-images.githubusercontent.com/10962177/52310779-cda1a480-2961-11e9-8c89-4156d4aca713.png)

**Comment by jekkos** [comment]
Yes I think I already fixed that bug in my open PR. The datetime was saved in both the attribute_value and attribute_datetime columns. That should not be the case anymore. Need to find the time to finish and fix the last issues there.

In some cases it's good enough to show the attributes appended to the name (like in my case I only use one value per item). So a couple of options / ideas

* Maybe we should add definition name + value in description by default Like Size: M, Color: Blue. However this would make the string already a lot longer and probably calls for placing it in the description field immediately
* Other option could be to place the value depending on the length in name or description field, so it's always displayed nicely. But that might feel a bit of fiddly and unpredictable in the end.

**Comment by odiea** [comment]
Are you going to enable an option so just the month day and year will be shown. I do not think the time would be needed?

**Comment by jekkos** [comment]
Ok maybe we need to limit showing only the date in sales and receivings? Might look better if that's acceptable.
