### ISSUE TITLE
check_numeric  function in Secure_Controller doesn't work correctly in php 7

### ISSUE THREAD

**Issue by bullmike** [opensourcepos/opensourcepos#2348]
Check_Numeric function called from Item and Tax config doesn't function correctly in php7.

check_numeric("test") returns 'true'

        public function check_numeric()
        {
                $result = TRUE;
                foreach($this->input->get() as $str)
                {
                        $result &= parse_decimals($str);
                }

                echo $result !== FALSE ? 'true' : 'false';
        }

Not sure why this function is doing a bitwise AND assignment.. '&=' .

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  v3.2.3
- OSPOS git commit hash is: 
- PHP version is: 7.0.33
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by jekkos** [comment]
Looks like something we could easily add a unit test for

**Comment by bullmike** [comment]
perhaps this should use the is_numeric() function ?

**Comment by jekkos** [comment]
well no not completely. Not sure how it would behave if we then try to parse some numbers formatted in a specific locale.

**Comment by jekkos** [comment]
Can you specify exactly where this function is not working? Was just trying it with PHP7 and it seems to behave as expected.

**Comment by jekkos** [comment]
Seems that the behavior of the intl formatter has changed then. Previously it would return `FALSE` if you would pass it a string that it can't parse. Now it seems to return `0`.

**Comment by daN4cat** [comment]
@odiea, have you ever experienced this with the latest version?

If it's not an issue with 3.3.0 I would close.

**Comment by odiea** [comment]
All appears to be working correctly for me. If there is a certain test that would be needed I would like to know what it is.

**Comment by daN4cat** [comment]
I close.
