### ISSUE TITLE
Invoice title change

### ISSUE THREAD

**Issue by bitflo** [opensourcepos/opensourcepos#2350]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by bitflo** [comment]
It should be very simple but I cannot find the file to change the title of the printed invoice. For tax purposes the invoice has to say "Tax Invoice" and not just "Invoice". I have looked at the view files but it seems that the title is pulled from another variable. Could you please point my to the correct file where I can change the title of the invoice from "Invoice" to "Tax Invoice"?

**Comment by SteveIreland** [comment]
Look for the line in application/views/sales/invoice.php and invoice_email.php that looks like the following (possibly around lines 47 and 18).
 
`<div id="header"><?php echo $this->lang->line('sales_invoice'); ?></div>`

Just change it to 

`<div id="header"><?php echo 'Tax Invoice'; ?></div>`

In the current development branch there will be a separate file for Tax Invoice.

**Comment by bitflo** [comment]
That worked thanks.

My language is set to en_ZA, under "Configuration > Localization" so I created an extra language file under "application/language/en-ZA" and edited the sales _lang.php file but with no success. 

I guess for time being I'll be using your solution. 

Thanks
