### ISSUE TITLE
Last digit of the commit hash not displaying

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2352]
### Background information
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information
Demo server
- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 3b9bf5
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug

The commit hash is written as 3b9bf in the code but the actual commit hash is 3b9bf5.  Something is truncating the last digit.

**Comment by jekkos** [comment]
Ok did a quick fix for this one, will check once deployed.

**Comment by jekkos** [comment]
Verified on demo and looks fine.

**Comment by objecttothis** [comment]
This seems to be still in issue in efd4e9a

**Comment by objecttothis** [comment]
![annotation 2019-02-26 181144](https://user-images.githubusercontent.com/17935339/53418830-17762b80-39f2-11e9-8c42-fe651a7c73b2.jpg)

**Comment by objecttothis** [comment]
Sorry this may not be an issue.  Both OSPOS and bintray are reporting 6 character commit hashes, but when you look at commit history in the master the commit hashes are all 7 character.  So is bintray/ospos correct or the commit history correct?

**Comment by jekkos** [comment]
You can make it 7 chars if you want. It's much longer even but I used a substring.

**Comment by objecttothis** [comment]
I didn't know that.  I don't really care all that much.  I just saw the inconsistency between commit history being 7 and OSPOS/bintray being 6.  We can leave it as is.
