### ISSUE TITLE
All Reports pages showing blank page after taking time to load

### ISSUE THREAD

**Issue by ebenezery4** [opensourcepos/opensourcepos#2353]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 5.6
- MySQL or MariaDB version is: mysql
- OS and version is: windows 7
- WebServer is: xamp
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue 
The issue am having is if i wanted to check summary report of my daily sales the system will take time to load for over 5mins and later show a black page and it ends

**Comment by WebShells** [comment]
Hello @ebenezery4,
In your case i guess its an issue with CI config, you should increase the execution session limit, since there is a huge data to retrieve in detailed transactions report.. Try to increase it and reopen this issue if its still exist.. This is based on what you said without checking or enabling error loging since you mentioned that over a specific period of time it goes blank...

**Comment by ebenezery4** [comment]
The issue still exist after increasing the execution time in php.ini to 10min and beside the data i want to retrieve is just a report of a single sale that i commit to test run the report page
