### ISSUE TITLE
Employee Cant access items after removing tax ability

### ISSUE THREAD

**Issue by farahota13** [opensourcepos/opensourcepos#2360]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3 - 4f5ad57
- OSPOS git commit hash is: idk
- PHP version is: 5.6
- MySQL or MariaDB version is: idk 
- OS and version is: windows 10 using Ubuntu Bash
- WebServer is: localhost
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: idk

### Issue / Bug  / Question / New Feature

I fully installed OSPOS yeserday its quite possible i messed something up, but it was stable thismorning, then i decided my users didnt need access to change taxes and employee information, so i removed thos features while leaving everything else checked. but now my employees get the error 
"You do not have permission to access the module named Items"

i have read through the previouly closed threads but havent found anything that fixes my issue, thanks in advance.

**Comment by odiea** [comment]
Make sure the employee has been granted permission for Items otherwise they can just sell current items in stock if you gave them permission in sales.

**Comment by farahota13** [comment]
So i keep adjusting the permissions, but it either fails to adjust or says successful but doesn't change anything, i would welcome a email address to connect directly with you so we may be able to show you the issue directly.

**Comment by farahota13** [comment]
we can close this, my issue was caused by spaces in the names of the stock locations, I received this information from a post made 2days ago on another thread, Thanks for all your help and keep up the good work.
