### ISSUE TITLE
Due Development Issue

### ISSUE THREAD

**Issue by tm-tomal** [opensourcepos/opensourcepos#2363]
Hello Dear Developers,
Actually i want to know how to development due options. because is there due has paid to once like admin can take money once and due payment cannot changes. 
basically i want to change some systems. and my big issue is DUE systems. 
if any developer can change it just knock me. 

CHANGE: due will take multi dates. like total due is 1000$.  and client can paid owner weekly 100$.
so real developers can contact me. 
![Uploading Screen Shot 2019-02-16 at 18.44.09.png…]()

**Comment by WebShells** [comment]
@tm-tomal we have discussed this issue already several of times and still no serious decision was taken about integrating with 3rd party ready to run interface where we can manage accounting part, or continue developing from where we started before... Please look into older issues.

**Comment by tm-tomal** [comment]
okay thank you

**Comment by WebShells** [comment]
Anytime... Will close
