### ISSUE TITLE
India GST migration leaving backup tables

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2367]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.6.38
- MySQL or MariaDB version is: MySQL 5.7
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug
Related to #2302 the /application/migrations/sqlscripts/3.3.0_indiagst.sql is creating backups of the ospos_sales_tax, ospos_tax_code_rates and ospos_tax_codes tables but then not dropping the tables after the migration is completed.  This leaves the tables in the database which will get stale over time.  Is there a reason not to drop the tables?  @SteveIreland perhaps you can help me understand the benefits of leaving the backups?

**Comment by SteveIreland** [comment]
There is already a pull request in place to address this issue

**Comment by objecttothis** [comment]
> 
> 
> There is already a pull request in place to address this issue

OK, I see #2343 now.  Thanks @SteveIreland

**Comment by SteveIreland** [comment]
But I'll be adding a "cleanup" step to the migration because the code that left the backup tables stranded has been in our "psuedo general release", so to follow recommended guidelines I need to add an "if exists then delete" to the pull request to do cleanup.

I WILL be assimilated.

**Comment by objecttothis** [comment]
@SteveIreland is the reason for the backups being created to make it possible to revert should the migration fail?

**Comment by SteveIreland** [comment]
no ... there was a structural change to the files so I make a copy of the original, create the new ones and then migrate the data from the old files to the new files.

**Comment by objecttothis** [comment]
That makes sense. In addition to whatever cleanup scripting you are doing for migrations I would add the lines right into indiagst SQL script to drop the tables at the end.

**Comment by SteveIreland** [comment]
#2343 was modified to include cleanup of the backup tables if the were left stranded.  (Which only happened during a brief period of time.)

**Comment by objecttothis** [comment]
Confirmed working.
