### ISSUE TITLE
Add ISO 4217 Currency code

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2369]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.6.38
- MySQL or MariaDB version is: MySQL 5.7
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### New Feature

Currently we have a row in app_config for the currency symbol that we are using for display in the application and on receipts.  Can we add in another row in app_config for the ISO 4217 Currency code as well (https://en.wikipedia.org/wiki/ISO_4217)?  

I think there are a few benefits to it.  One is that it's needed for the CLCdesq 3rd party integration that I'm working on.  Second, for users that don't know or want to use a currency symbol, the currency code (e.g., USD, EUR, RUB, etc) can be used in it's place.  This information can be pulled automatically under localization in the same way that we are pulling other localization information. The third benefit is that some currencies do not have a currency symbol, but all currencies have an ISO 4217 code.

I would think that if currency symbol is populated the app would use that, but if it's not the app would use the ISO currency code.

Thoughts?

**Comment by SteveIreland** [comment]
As I was working on the alternate currency for invoice I wanted to implement it but I ultimately decided that it was outside of the scope of my change.  However, I did make the currency symbol that I store in the database a three character field just in case future development transitioned over to 4217.

**Comment by objecttothis** [comment]
What table is that being stored in?

**Comment by SteveIreland** [comment]
I'll be storing the alternate currency language code, exchange rate, and currency symbol in the sales table.

**Comment by objecttothis** [comment]
#2394 is now in the master.

**Comment by SteveIreland** [comment]
@objecttothis For the configuration page, did you need to have the currency code set for integration to  CLCdesq to work?

If so then it's probably not a good idea to have it bound to the fomatting of the number.  If they want the currency code use in place of a currency symbol they can enter the currency code into the currency symbol field and get the result they want.

If the currency code and the currency symbol is provided then we want the currency symbol to be used.  The currency symbol is always provided.  If they blank it out then the system will determine the default currency symbol to be used and will drop it into the currency symbol field.
