### ISSUE TITLE
Current Demo down with following error.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2370]
A Database Error Occurred
Error Number: 1146

Table 'ospos.sessions' doesn't exist

SELECT `data` FROM `sessions` WHERE `id` = '68888f0416cc1c037582af5c002920ef291cc447' AND `ip_address` = '[REDACTED]'

Filename: libraries/Session/drivers/Session_database_driver.php

Line Number: 171

**Comment by odiea** [comment]
This page isn’t working demo.opensourcepos.org is currently unable to handle this request.
HTTP ERROR 500

**Comment by objecttothis** [comment]
This is because of the error in the attribute_lang for azerbaijani.  It has been corrected on weblate but there seems to be a problem merging it into the repository... At least it gives me an error when I try.

**Comment by jekkos** [comment]
Ok fixed it and waiting for the latest build now

**Comment by odiea** [comment]
An uncaught Exception was encountered
Type: ParseError

Message: syntax error, unexpected ':'

Filename: /app/application/language/az-AZ/attributes_lang.php

Line Number: 3

Backtrace:

File: /app/application/hooks/load_config.php
Line: 58
Function: load

File: /app/application/hooks/load_config.php
Line: 30
Function: _load_language_files

File: /app/public/index.php
Line: 315
Function: require_once

**Comment by jekkos** [comment]
Ok I fixed the file for now. Think this is more of a weblate issue as adding quotes kind of escapes content out of the PHP file, which I don't think we should allow from weblate itself.

**Comment by jekkos** [comment]
Maybe I should add a custom fixup to weblate to avoid this in the future. (Probably will do so if this happens again).

https://docs.weblate.org/en/latest/admin/checks.html

**Comment by objecttothis** [comment]
I agree that if " in the php from weblate translation breaks it then we should either escape the " properly or disallow " to be used in translations.  Right now I think it's escaping them with \\" but it really should be \" so it's failing.

**Comment by odiea** [comment]
A PHP Error was encountered
Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: hooks/load_config.php

Line Number: 54

Backtrace:

File: /app/application/hooks/load_config.php
Line: 54
Function: _error_handler

File: /app/application/hooks/load_config.php
Line: 29
Function: _load_language_files

File: /app/public/index.php
Line: 315
Function: require_once

**Comment by odiea** [comment]
Closed for now
