### ISSUE TITLE
Feature: Add DECIMAL attribute type

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2372]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 9e2f9f
- PHP version is: 5.6.38
- MySQL or MariaDB version is: 5.7
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### New Feature
We should add a DECIMAL attribute type.

In our particular case we have the weight of the item that we need to store as an attribute.  At this point the only option is to store it as type TEXT but that opens up errors being introduced into the data of having improperly formatted data and using the data (in third party integrations) is problematic.  Allowing a DECIMAL eliminates that problem.  I propose that adding this would add a column to the attribute_values table (type DECIMAL(7,3) DEFAULT NULL), adding the appropriate logic in the Attribute model/view to convert from TEXT to DECIMAL and back as well as adding the drop down in the view to select the type would be what is involved.

I don't think our case is unique, since it doesn't take much to think of all kinds of attributes that a decimal could help with (length, width, height, weight, Tare Weight, depth, etc.)

**Comment by objecttothis** [comment]
@jekkos @daN4cat can you guys think of any reason not to do this or considerations that need to be made?

**Comment by daN4cat** [comment]
Makes sense to me.

**Comment by objecttothis** [comment]
What is the procedure for creating a new migration script?  I see for each of the migrations there is a php in the /migrations/ folder with the format [numbers]_[name].php which points to an sql script in the /sqlscripts/ folder.  I know the SQL script needs to be 3.3.0_to_3.4.0.sql but the php file in /migrations/ is not as clear to me.  [number]_upgrade_to_3_4_0.php looks right but I don't know what numbers to put in there.  It looks to be a YYYYMMDD[more numbers] format but I don't know what to put for after the date.

**Comment by daN4cat** [comment]
YYYYMMDDHHMMSS set the latest date and time before committing to master.
I would say let's move away from release numbers and set date and time + name of feature.

**Comment by objecttothis** [comment]
Doesn't this mean more migration scripts then? For example between each release there may be 5-10 features in it.

**Comment by daN4cat** [comment]
Yes, but as said earlier we should aim at certain point to have a continuous release with incremental and small upgrades pulled automatically from GitHub or similar repo.

**Comment by jekkos** [comment]
sth like this

https://github.com/jimdoescode/CodeIgniter-GitHub-Updater/tree/master/libraries

Or we could turn ospos itself into a compose package and leverage that tool to keep it uptodate?

**Comment by daN4cat** [comment]
I saw that library and I had in mind to give it a try post 3.3.0.

Composer will require building a UI interface to it. Not sure it's that simple.

We could just create a OSPOS-release repo with everything in it to be pulled, something stable and just upgrade out of the stable master.

Just thinking loudly here...

**Comment by objecttothis** [comment]
@daN4cat by UI, I think you mean a GUI installer?  If that's accurate then it's on my wish list but not urgent for me at the moment.

Regarding the original conversations, I had understood what you had said to mean you wanted fewer releases which is why I was confused because small, incremental upgrades is sort of the opposite of that.  I think I understand now.  For now, I will name it YYYYMMDDHHMMSS_decimal_attribute_type.php since that seems to be what you are suggesting.

Regarding the idea of releasing out of a stable master, I like the idea, but what kicks out of our master right now is usually Beta and I wouldn't categorize them as guaranteed stable so I think we would need to differentiate stable master builds from master builds.

**Comment by jekkos** [comment]
@daN4cat or just a simple script that pulls the latest release zip and extracts it. Only thing to check would be whether the directory is writable for the PHP process.

**Comment by daN4cat** [comment]
Release from stable, not current unstable master.
We will need to change approach a bit.

**Comment by objecttothis** [comment]
OP resolved with #2393.  Closing
