### ISSUE TITLE
add units of measurements to locale

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2373]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 9e2f9f
- PHP version is: 5.6.38
- MySQL or MariaDB version is: 5.7
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### New Feature

In the Locale settings there is currently nothing that specifies units of measurement (length, mass) but this would be helpful information to have.  For example if we have an attribute that is the weight of an item (which becomes easier if #2372 gets implemented) then having a system setting that tells OSPOS what unit of measurement is being used in that attribute. 

This is beneficial for displaying in tables and reports what unit that attribute is in.  The values would be stored in app_config (cm, mm, g, kg, lb, in, etc) in two key->value pairs (unit_length, unit_mass) then the Attribute definition (and view) would be able to flag the attribute as a none, length or mass (0,1,2) respectively.  The logic would just need to be added to table generation to translate that flag into the proper display on the screen.

**Comment by SteveIreland** [comment]
I may not understand where you are headed with this ... but here are my thoughts.

The unit of measure depends on what's being measured.  So I don't see the value of adding this to the Locale settings.  For example, we recently added a feature where the quantity of an item can have a "unit of measure" associated with the quantity such as "case", "each", "carton", etc and it is user defined.  If you're measuring the volume of a particular item it could be in inches or meters, but it could also be in gallons or liters.  It is item specific so it has to be an attribute of an item.

**Comment by objecttothis** [comment]
@SteveIreland So if I understand what you are saying, is that unit of measurements are helpful but should be defined for each attribute, because a user could be wanting 2 or more different units of length or mass.  Is that accurate?

So then would having a column in the attribute_definition table labeled unit that a could be set when the user creates the attribute (or changed later) solve the problem?

Then there is no change to the app_config table and just one column added to the attribute_definition table. instead of a flag would be the actual unit of measurement.

**Comment by SteveIreland** [comment]
I believe that you can have as many "unit of measures" as you want (for an item) by simply adding a text attribute for each unit of measure  you want, giving it name that describes what you are measuring.

If you wanted to limit the values that a user can select for a unit of measure then just make it a drop-down box ... right?

**Comment by objecttothis** [comment]
@SteveIreland what you are suggesting (I think) is using Attributes to make an Attribute of an Attribute.  From a database/performance perspective that would be less efficient because you would be adding one field on one row if added to the attribute definition, but adding n rows in attribute_links where n is the number of items that have a unit of measure assigned to them.  

Yes, you are correct that units of measure could be limited to a dropdown if we go the Attribute of an Attribute route.

**Comment by SteveIreland** [comment]
That’s not quite what I meant.

**Comment by objecttothis** [comment]
Oh ok. Can you clarify so that I better understand what you mean?

**Comment by objecttothis** [comment]
Added to the DECIMAL attribute type in #2393. It can be extended later to other types of attributes but for now there is an optional unit of measure when the attribute type is DECIMAL.
