### ISSUE TITLE
OSPOS SMTP configuration not working in xampp

### ISSUE THREAD

**Issue by kaushalbjoshi** [opensourcepos/opensourcepos#2374]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: version 3.2.3
- OSPOS git commit hash is: 4f5ad57
- PHP version is: PHP Version 7.3.0
- MySQL or MariaDB version is: mysql
- OS and version is: win10
- WebServer is: Xampp
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

SMTP updated config file and try to send recipts from daily sales - clicking $ sign and send recipt to customer 
![image](https://user-images.githubusercontent.com/47893938/53249857-232ac080-3687-11e9-8cd2-cae575f65f1b.png)

**Comment by kaushalbjoshi** [comment]
[php_error.log](https://github.com/opensourcepos/opensourcepos/files/2894655/php_error.log)

**Comment by kaushalbjoshi** [comment]
its works after doing a change in php.ini and sendmail.ini - do not use the force sender in either file

**Comment by daN4cat** [comment]
Good and thank you for coming back to leave a solution to the problem.

**Comment by kaushalbjoshi** [comment]
in php.ini


[mail function]

sendmail_path = "\"C:\xampp\sendmail\sendmail.exe\" -t"


 in sendmail.ini 
[sendmail]
smtp_server=server address 
smtp_port=465
smtp_ssl=ssl
error_logfile=error.log
debug_logfile=debug.log
auth_username=your email
auth_password=your password
hostname=you smtp mail address

restart apache 

all done
