### ISSUE TITLE
does opensourcepos meet austrian legal requirements

### ISSUE THREAD

**Issue by u2mike** [opensourcepos/opensourcepos#2376]
simple question: 
does this opensourcepos system meet AUSTRIAN legal requirements?
maybe someone just use this opensource system in austria

greetings michael

**Comment by objecttothis** [comment]
I also should add that this is just the software itself.  If it gets installed on a server not meeting GDRP requirements (meaning not secured) that is a different story.

**Comment by objecttothis** [comment]
I believe it meets GDRP requirements, so unless Austria has additional requirements then it does.

**Comment by daN4cat** [comment]
I've added an option in config to enforce GDPR rules in form confirmation that consent to store personal data was given and in case a customer is deleted their personal details are removed.
History of what was captured about them can be a printout of customer transactions, should that be required.
Beside that, I don't know if Austria requires something special about receipts. But receipts are generated and numbered, no receipt can be deleted from the tool.
Of course database needs to be secured.

**Comment by WebShells** [comment]
Answered...
