### ISSUE TITLE
Weblate kicking server error on push/commit operations

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2378]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 5.6.38
- MySQL or MariaDB version is: 5.7.38
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue

Changes to the Azerbaijani translation are causing server errors.  In essence the line 
`$lang["attributes_attribute_value_invalid_chars"] = "Atribut dəyəri bu \\":\\" və ya \\"|\\" olmaz";`

Should be:
`$lang["attributes_attribute_value_invalid_chars"] = "Atribut dəyəri bu ':' və ya '|' olmaz";`

I corrected this in attribute_lang on weblate, but when I attempt to commit/push changes to the repository I get:

>  Internal Server Error 
>
>Server Error
>
>The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.

@jekkos  could this be a permissions problem on my account?

**Comment by jekkos** [comment]
yes I saw there was a parse issue with this file. Think it's solved now as the working directory is clean. The parser was not able to read those escape sequences indeed.

**Comment by jekkos** [comment]
Ok I've corrected this error in master now.
