### ISSUE TITLE
Update Items updates the database even when no changes are made

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2381]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: efd4e9
- PHP version is: 5.6.38
- MySQL or MariaDB version is: MySQL 5.7.24
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue

Current behavior when submit is pressed on the Item form view is an update is made to the database regardless of whether anything was changed in the form or not.  It also updates all fields and not just changed fields.

This behavior is resulting in unneeded (when nothing gets changed) or overly long database UPDATE calls (when just one field is changed it still includes everything about the item in the UPDATE)

If our hooks for Third Party Integration are going to be based on database queries this will result in a considerable number of unnecessary API calls for these third party integrations.

I propose that we put a check in the code to compare the item data used to populate the fields with the data in the fields on submit and only formulate the UPDATE to the database when there are changes and when the changes happen only include in the SET portion the actual changes instead of everything.  This will resolve the third party integrations issue and significantly reduce database hits.

**Comment by jekkos** [comment]
I don't really know whether there is a lot of overhead on the SQL side when no value is changed. At which level do you propose to check this condition exactly? And do we need to implement that for all models then? 
Can't we use the number of updated rows as a result to conditionally trigger the hook?

**Comment by objecttothis** [comment]
> I don't really know whether there is a lot of overhead on the SQL side when no value is changed, but I don't think so. 
There isn't much overhead.  As is, OSPOS is doing N+1 UPDATEs (where N is the number of attributes in the item).  For an item with 10 attributes this takes a little over 1ms, so not a lot of overhead.  The overhead will come with Third Party Integrations.  Each integration will do it's API calls based on what the hook gives it.  If, for example, a user has 3 integrations, we are forcing all of them to do their API calls and data processing when zero changes were made.

>At which level do you propose to check this condition exactly? 
I may be wrong, but I think the form level will be the easiest. OnSubmit could kick off a function that checks to see if the originally populated values match the values at the point of submitting the form.  Then minimally just not have it send anything to update if nothing changed, but even better would be to have the form only send data that has changed.

> And do we need to implement that for all models then?
At this point we would implement this at least for Item, Sale and maybe Item_kit models but if later we wanted to have integration hooks for people we could integrate it in Customer, People, Supplier, etc.

> Can't we use the number of updated rows as a result to conditionally trigger the hook?
The hook needs to get triggered one time for each time the form is submitted AND data actually gets updated in the database.  This means that if 5 UPDATES happen on one form submit then the hook only gets triggered once.  What I would like to happen is the hook not trigger 3rd party integrations if no UPDATE happens to prevent against unnecessary API calls.

**Comment by objecttothis** [comment]
One slight correction.  When a sale is made it will always update the item_quantities table with a new quantity so no check needs to get made here.  I'll look at what the code is doing and if it is also updating the items table we may have to get rid of that.  There is no reason for a sale to update Items
