### ISSUE TITLE
HTTP ERROR 500 WHEN COMPLETING SALE

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2383]
I have this same problem.500 error when completing sale · Issue # 387
![captura de pantalla de 2019-02-28 16-25-53](https://user-images.githubusercontent.com/29256343/53603106-25ed5000-3b76-11e9-9ceb-80a6c265ff1d.png)

When I finish the sale I have this error.

![captura de pantalla de 2019-02-28 16-25-58](https://user-images.githubusercontent.com/29256343/53603192-57feb200-3b76-11e9-9ea2-deedf205a3f4.png)
When I finish the sale I have this error.

I did the installation of sudo apt-get install php-gd.
Issue #387 was enough to install install the php5-gd package.

Currently I have PHP 7.2.15-0ubuntu0.18.04.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )

I have read all the problems related to this without any solution.

I can not add a new item or edit an item either
![captura de pantalla de 2019-02-28 16-40-55](https://user-images.githubusercontent.com/29256343/53603698-e32c7780-3b77-11e9-95bd-701f3226c859.png)
![captura de pantalla de 2019-02-28 16-40-59](https://user-images.githubusercontent.com/29256343/53603700-e32c7780-3b77-11e9-9415-2099de47d345.png)
![captura de pantalla de 2019-02-28 16-41-05](https://user-images.githubusercontent.com/29256343/53603701-e3c50e00-3b77-11e9-894d-fbd20314cb90.png)
I think this is also related
I do not know what I am doing wrong, if someone has gone through that, I would greatly appreciate your help. I am currently using the Ubuntu server 18.04.

**Comment by SteveIreland** [comment]
What version of OSPOS are you installing and where did you get the zip file from?

**Comment by andriux1990** [comment]
He downloads it from bintray. with wget opensourcepos.20190227220222.master.0f91fe.zip

**Comment by andriux1990** [comment]
También cargué versiones que funcionan perfectamente en el servidor local, y tengo los mismos problemas

**Comment by andriux1990** [comment]
I also uploaded versions to the server that work perfectly on the local server. but on the web server I have these problems

**Comment by jekkos** [comment]
Check your error logs to see what's going on there.

**Comment by andriux1990** [comment]
I'm not sure if the problem was due to a bad installation of PHP or MySQL. What I did to solve it was to uninstall MySQL and PHP, reinstall PHP. Also install mariadb instead of MySQL and now it works fine

**Comment by andriux1990** [comment]
thank you SteveIreland and jekkos..
I will close this issue.

**Comment by nira168** [comment]
@andriux1990 may I know how to config mariadb database as I also encounter this problem on Digitalocean. I tried to install mariadb instead of mysql but it show Invalid DB driver.

**Comment by daN4cat** [comment]
@andriux1990 the issue most likely was what's been found in #2538

**Comment by dwayneparchment** [comment]
I had the same error and removed the "ONLY_FULL_GROUP_BY" in my sqlmode and fix problem .
