### ISSUE TITLE
4,000 Commits

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2385]
Seems like there should be a celebration.   Congrats @WebShells for adding commit number 4,000.

**Comment by WebShells** [comment]
Champagne for everyone 🍷😎

**Comment by daN4cat** [comment]
A sign that either we are good (adding a lot of functionality) or crap (constantly fixing our mess) :-)

**Comment by objecttothis** [comment]
> 
> 
> A sign that either we are good (adding a lot of functionality) or crap (constantly fixing our mess) :-)

hehe, probably a little of both.

**Comment by daN4cat** [comment]
Hmmm probably @jekkos wanted the commit 4000 and that's why he forced the complete repush of master :-P
