### ISSUE TITLE
Terrible mistake

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2387]
@opensourcepos/org 

I just realized I accidentally force pushed to master (wanted to force push a bugfix branch instead). I have reverted to the latest commit I could find (which was 2 days ago on the weblate repo) but I'm not sure if this was the most recent one.

Can anyone that pulled recently check if there is stuff missing? 
Also I'll add a pre-receive hook after the fix to prevent these kind of mistakes in the future.

**Comment by WebShells** [comment]
I guess am the last, will check it once home...

**Comment by SteveIreland** [comment]
I was always worried that I would be the one that did that.  I once caught myself just about to press Enter on that.  I resolved to limit my drinking before I did a push.   :-)

**Comment by WebShells** [comment]
@SteveIreland i had the exact same feeling in every request 😂...

**Comment by objecttothis** [comment]
@jekkos the latest local copy of the master I have is from commit 0f91fee which is February 28th.  It appears that the latest commit on the master as it is now is @WebShells commit on the #2384 pull request.  Do we know what got lost/changed?

**Comment by objecttothis** [comment]
let me know if you want me to and I can force push it to the remote master.

**Comment by jekkos** [comment]
If you have a more recent version then go ahead.

**Comment by objecttothis** [comment]
OK, I pushed it.  @WebShells might want to check your code from #2384 and re-merge if needed.

**Comment by jekkos** [comment]
I rather have exactly the same commit hash as before.

**Comment by objecttothis** [comment]
@WebShells I readded your change from #2384

**Comment by objecttothis** [comment]
@jekkos I don't understand.  You mean that your commit hash is still the one you accidentally force merged?

**Comment by WebShells** [comment]
We could have just forced the pull request, i was the last to submit so I have the latest version  from 3/1/19... Not 27 or 28 February

**Comment by jekkos** [comment]
Ok so let's update to the version @webshells has and all should be fine then.

**Comment by objecttothis** [comment]
Sounds good to me

**Comment by WebShells** [comment]
Pushed back latest version to master... Will close.

**Comment by daN4cat** [comment]
I suppose there is a means in GitHub to block this force push of master. @jekkos can you please check?

**Comment by objecttothis** [comment]
I know GitHub can force a certain number of code reviews before merging a pull requests. That might be helpful to set that at 1 or 2. I don't know if that applies to merging directly to the master without a branch.

**Comment by objecttothis** [comment]
I think this is what you want @jekkos. https://help.github.com/en/articles/about-protected-branches

**Comment by jekkos** [comment]
Indeed will enable that protection now

**Comment by daN4cat** [comment]
Just to force push no other stuff otherwise urgent bug fixing straight in master gets delayed.

**Comment by objecttothis** [comment]
@dan4cat I think that you can make it so moderators and admins can merge branches without code review but people with non admin privileges have to have at least one code review.

**Comment by jekkos** [comment]
Force push on master should be disabled now. Also master cannot be deleted.

**Comment by WebShells** [comment]
Great, you won't cause us trouble anymore 😋

**Comment by objecttothis** [comment]
Yeah ya jerk :wink:
