### ISSUE TITLE
barcode scanner don't work on sales button only

### ISSUE THREAD

**Issue by locik** [opensourcepos/opensourcepos#2390]
### Question
i need help. Please... My barcode scanner work on receivings button. I can add item there. but it don't work on sales button only. When i press my barcode scanner, i get the number but quickly it change with the text "start typing item name or scan barcode" so i can not add item with barcode scanner but i can add item with keyboard.
i use windows 10, ospos 3.2.3, xampp v3.2.2. 
i add this code ini php.ini as i found this from google.
extension=php_bz2.dll
extension=php_curl.dll
extension=php_fileinfo.dll
extension=php_gd2.dll
extension=php_gettext.dll
extension=php_gmp.dll
extension=php_intl.dll
extension=php_imap.dll
extension=php_mbstring.dll
extension=php_exif.dll
extension=php_mysql.dll
extension=php_mysqli.dll
extension=php_pdo_mysql.dll
extension=php_pdo_sqlite.dll

here is screen recording of my problem https://youtu.be/7RZfYeuPYRs

**Comment by jekkos** [comment]
Can you try to configure your barcode scanner to send a return after reading the barcode? As from the first part of your video it looks like you need to hit the return key yourself. In sale there might be an issue that resets the field once the focus is gone.

**Comment by WebShells** [comment]
You're right, maybe the configuration of the scanner isn't set to auto submit after scanning...

**Comment by locik** [comment]
In the first video i try my scanner on receivings button and it's work. In the second try is in sales button and it's not work. And i dont understand how to configure my scanner so i let it in default configuration

**Comment by WebShells** [comment]
@locik that's the weird point... Scanners' configuration usually can be done through a booklet comes along with your barcode contains list of barcodes that you should scan to set.. Try resetting to default settings and retry...

**Comment by WebShells** [comment]
No updates... Will close
