### ISSUE TITLE
Developer needed to assist with custom report

### ISSUE THREAD

**Issue by data2base** [opensourcepos/opensourcepos#2392]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question 

Any developers available to assist in developing a custom report?
Thanks!

**Comment by nerv55** [comment]
Wich version did you use?, is linux or windows deploy?, what is the specifications of this custom report?

**Comment by data2base** [comment]
Hi! Current version is: 3.2.3 - 4f5ad57
Linux based. 

So basically all this will be linked to a specific category in the inventory during a specific period selected:

Stock opening balance
Selling Price
Cost price
Units sold
Stock closing balance
Current inventory value (Cost price x stock available)

Attached find sample excel report. 
![screenshot at mar 04 21-44-39](https://user-images.githubusercontent.com/37272312/53900721-d4e1ce00-4045-11e9-8b42-e2845e18df30.png)

**Comment by nerv55** [comment]
Stock opening and Stock closing exist in your database as fields or is calculated ?

**Comment by nerv55** [comment]
also, wich Mysql version do you have?

**Comment by data2base** [comment]
No extra fields in my database as it's the default ospos database. Can initial stock be pulled from items before any stock was sold? then items sold can be calculated. 

From an excel query i pull the sales per month per category and get the products per category sold.

**Comment by data2base** [comment]
MySQL 5.6

**Comment by nerv55** [comment]
Let's say you run the report form 15/02/2018 to 15/03/2018 (dd/mm/yyyy), wich method do you use to calculate initial Stock and closing stock?

**Comment by data2base** [comment]
Well thats what i cannot do currently. Or don't know how. I can only currently get, sales per month per category and a breakdown of sales per category. Through breakdown i can get quantity sold per item, cost price and selling price.

So on that specific date i can maybe get current stock left?

**Comment by data2base** [comment]
cant the Inventory Data Tracking help with this?

**Comment by nerv55** [comment]
do you have any rules implemented for inventory management?, for example FIFO, LIFO,  how often do you make inventory, cyclic inventory. for what reason I ask.
I work currently for retail company and we have our method, How and When analize stock rotation.
if you have something in your mind may be we can add it to you installation. to get the result that you need.

**Comment by data2base** [comment]
FIFO - Ok so this specific report is for consignment items, i would like to get a report on opening stock in the shop, sold for the month and payment due to the supplier.

**Comment by nerv55** [comment]
Ok, take the example from before 
Let's say you run the report form 15/02/2018 to 15/03/2018 (dd/mm/yyyy).
it will work for you if the report have this behavior:
calculate initial month stock= (no matter wich day you choose)[algebraic sum {sells,purchase,returns}] until day one selected month from the beginig of the year.
actual stock= will be pulled from database.
current sell= algebraic sum {sells,returns} between selected dates.
closing Stock=   algebraic sum {sells,returns,purchased} between selected dates.

**Comment by data2base** [comment]
Can you maybe assist with the query?

**Comment by nerv55** [comment]
yes, can you send me sample of your database ?

**Comment by data2base** [comment]
Sure, can it be sent privately some how?

**Comment by nerv55** [comment]
find my fork or this proyect and open issue there. we continue form there
