### ISSUE TITLE
Sale Register improvement for Sale Due

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2397]
OSPOS Installation Info | 3.3.0 - deven-US
-- | --
GD: Enabled ✓BC Math: Enabled ✓INTL: Enabled ✓OpenSSL: Enabled ✓MBString: Enabled ✓Curl: Enabled ✓
Browser: ChromeServer Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.1.16PHP Version: 7.1.16 Server Port: 80DB Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $OS: Windows NT PAVILION23 10.0 build 17134 (Windows 10) AMD64
Application/logs: Writable ✓Public/uploads: Writable ✓public/uploads/item_pics: Writable ✓import_items.csv: Writable ✓import_customers.csv: Writable ✓ CSV permissions were set to 0664

The Sale due payment currently is not restricted . A customer should be Entered before the Due payment 
is accepted.

**Comment by odiea** [comment]
I have tried this and it appears to work. If someone else could test it that would be great. application/views/sales/register under line 475. This is for the sales due payment needing a customer.
```
<?php
$payment_type = $this->input->post('payment_type');							
/ Only show this part if the payment cover the total and in sale or return mode
											
if($pos_mode == '1' && $payment_type != $this->lang->line('sales_due') && !isset($customer))
	{
	?>
<div class='btn btn-sm btn-success pull-right' id='finish_sale_button' tabindex="<?php echo ++$tabindex; ?>"><span class="glyphicon glyphicon-ok">&nbsp</span><?php echo $this->lang->line('sales_complete_sale'); ?></div>
<?php
}
?>
<?php
				
if($pos_mode == '1' && $payment_type = $this->lang->line('sales_due') && isset($customer))
{
?>
<div class='btn btn-sm btn-success pull-right' id='finish_sale_button'  tabindex="<?php echo ++$tabindex; ?>"><span class="glyphicon glyphicon-ok">&nbsp</span><?php echo $this->lang->line('sales_complete_sale'); ?></div>
<?php
}
?>

**Comment by nathanzky** [comment]
I test the function and it works, if payment type is due it needs to input customer detail to complete the transaction.. 👍 👍 👍

**Comment by odiea** [comment]
@nathanzky Thanks

**Comment by odiea** [comment]
It would be great if someone could add this with their commits. But please test it some more.

**Comment by WebShells** [comment]
I'll do it today along with some editions to system info...

**Comment by odiea** [comment]
The only issue I have seen is if the customer is added after the due payment is made they will not get their discount unless the due payment is removed then placed as a payment again.

**Comment by andriux1990** [comment]
I like it, good contribution.

**Comment by WebShells** [comment]
In master now.
