### ISSUE TITLE
Why is it sending request to  x-tags.net

### ISSUE THREAD

**Issue by nyenius** [opensourcepos/opensourcepos#2398]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [*] Reporting an issue of an unmodified OSPOS installation
- [*] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [*] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [*] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [*] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [*] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 7
- MySQL or MariaDB version is:  Mysql
- OS and version is: Linux
- WebServer is: Apache2
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Why is it sending request to  x-tags.net, the targetted url is down, and slowing down page loading. Especially for loading Register Mode and Stock Location dropdown.

This is 
`Request URL: http://x-tags.net/data/dmp/b?partner_id=1&csparams=dGNpZD1mOGExNTY4OGM0NGQ2MDU0NjNjYzQzYWIyNjQ3MTlhM2U5YzBkNDQ5&loc=http%3A%2F%2Fp01.notifa.info%2Fcampaign%2Flog.php&ref=http%3A%2F%2Fpos.tokozippo.com%2Fpublic%2Fsales

Request Method: GET

Status Code: 502 Bad Gateway

Remote Address: 13.228.245.212:80

Referrer Policy: no-referrer-when-downgrade
 `
While the page loading...... in the bottom left corner of chrome says: "Waiting for x-tags.net..."

**Comment by odiea** [comment]
Sounds like you need to get rid of that one and download it from here. No code like that shows up in OSPOS that I can find.

**Comment by nyenius** [comment]
Sorry, i found out it was bad script injection from my internet provider TELKOM 

Solved by this thread : [https://gist.github.com/abdilahrf/b63b6c0313d77fe2a51e18bfb4a8bb05](url), and it became lightning fast after that :)

**Comment by odiea** [comment]
Thanks for the feedback. Glad you got it worked out.

**Comment by nyenius** [comment]
Yes, everyone doesn't want it. It slows down website, and sometimes the scripts. It was ads from my ISP.
