### ISSUE TITLE
3.3 Migration Script Bug - 20170502221506_sales_tax_data.php

### ISSUE THREAD

**Issue by dtomlins** [opensourcepos/opensourcepos#2413]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- []x Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3 dev
- OSPOS git commit hash is: 
- PHP version is: 7.3
- MySQL or MariaDB version is: MairiaDB
- OS and version is: Ubuntu
- WebServer is: Apache 2.4
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

While re-running the full migration of data from 2.x the following error was encountered.

An uncaught Exception was encountered
Type: Error

Message: Call to undefined method Tax_lib::get_sales_tax_for_amount()

Filename: /opt/lampp/htdocs/pos3.3/application/migrations/20170502221506_sales_tax_data.php

Line Number: 60

Backtrace:

File: /opt/lampp/htdocs/pos3.3/application/migrations/20170502221506_sales_tax_data.php
Line: 24
Function: upgrade_tax_history_for_sale

File: /opt/lampp/htdocs/pos3.3/application/controllers/Login.php
Line: 50
Function: latest

File: /opt/lampp/htdocs/pos3.3/application/controllers/Login.php
Line: 24
Function: run

File: /opt/lampp/htdocs/pos3.3/public/index.php
Line: 315
Function: require_once

**@SteveIreland I assume    Should this call really be to "get_tax_for_amount()" instead?**

ALSO after changing that:  
An uncaught Exception was encountered
Type: Error

Message: Call to undefined method Tax_lib::update_sales_taxes()

Filename: /opt/lampp/htdocs/pos3.3/application/migrations/20170502221506_sales_tax_data.php

Line Number: 64

Backtrace:

File: /opt/lampp/htdocs/pos3.3/application/migrations/20170502221506_sales_tax_data.php
Line: 24
Function: upgrade_tax_history_for_sale

File: /opt/lampp/htdocs/pos3.3/application/controllers/Login.php
Line: 50
Function: latest

File: /opt/lampp/htdocs/pos3.3/application/controllers/Login.php
Line: 24
Function: run

File: /opt/lampp/htdocs/pos3.3/public/index.php
Line: 315
Function: require_once

**@SteveIreland I assume    Should this call really be to "update_taxes()" instead?**

Interesting that the migration table shows 20180501100000 - I didn't think it got that far!
Dan

**Comment by dtomlins** [comment]
AHA!  I think I see what is happening here now.

The migration script:  migration/20170502221506_sales_tax_data.php is using calculation and update statement code in the "current" downloaded - specifically  Tax_lib,  which has now been changed in name and function (for the above) which that code is dependant on table changes not made until  sqlscripts/3.3.0_indiagst.sql

**Comment by daN4cat** [comment]
Great, that's what I said in the past, don't fix the past (dependencies included) but just move forward.

@steveireland, it's better to decouple that migration script from the code at cost of duplication to avoid breaking backward compatibility.

**Comment by daN4cat** [comment]
@dtomlins please note that we haven't tested 3.3.0 with PHP 7.3 yet.
We support up to 7.2. So if you spot any issue bear that in mind.

We should probably test with PHP 7.3 before releasing 3.3.0.

**Comment by odiea** [comment]
The only thing I did not get to try was the migration script. But normal OSPOS works with no errors.
OSPOS Installation Info: 3.3.0 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: .Chrome
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
.PHP Version: 7.3.2 
.Server Port: 80
.DB Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
.OS: Windows NT PAVILION23 10.0 build 17134 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_items.csv:] - 0666 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓

**Comment by dtomlins** [comment]
I haven't seen any PHP issues yet either.

**Comment by daN4cat** [comment]
OK, good. That means OSPOS 3.3.0 is PHP 7.3 compatible.

**Comment by SteveIreland** [comment]
I'll be submitting the correction that @daN4cat suggested.  I've made the code changes but I don't have any 3.0.2 test data and will need to fabricate some and do some testing before I can submit the pull request.  Sorry it took so long to respond to this, but the last couple of weeks have been a bit rough with two different strains of virus which I most likely acquired from the earlier hospital visit.

**Comment by dtomlins** [comment]
Thanks Steve.  If helpful, I'm doing multiple migration tests on our data to see how far I can go to upgrade.
If they are contained, I can certainly do testing on them.  I'm validating each step, and change so when we do the upgrade from 2.1 we have minimal breakage.  I wonder about updating and what will break because each version needs new "config" information, especially for taxes.  I coded mine years ago.  But rates have changed, so "conversion of history" needs to keep what it was, not what it is ...  meanwhile, as the conversion happens before one can even get in to do the setup, it has to deal with "Facts not in evidence" to use a fitting phrase.

I'm interested in how your India GST works and if it is similar to Canada, but I can't see setup for it.
Products are classified as subject to HST (harmonized) 13%,  GST (federal only) 5%, or None.  
POS is in-store, so only one local rate for each applies.  When shipping is involved the destination is used to determine the rate.   Customers ALL pay it except for "Status Indians", who pay only the GST rate.   (effectively only)  Actually what is supposed to happen is that they get a "rebate" on checkout of the difference - showing both the charge and the rebate.  

Dan

**Comment by daN4cat** [comment]
@SteveIreland I can't remember if you submitted the changes to master in the end???
If yes, let's close this, thanks.

**Comment by SteveIreland** [comment]
This was corrected by pull request #2420
