### ISSUE TITLE
Weighted Barcode issue

### ISSUE THREAD

**Issue by MohamedMaghrby** [opensourcepos/opensourcepos#2417]
I followed the instructions but when I scan the barcode with wight char nothing found for the item

**Comment by WebShells** [comment]
What barcode format you are using ? Please fill in the issue template in order to support you in a better way...

**Comment by MohamedMaghrby** [comment]
I used this 02(\d{5})(\w{6}) as the documentation describes 2 char for department,  5 char for items and 6 char for weight

Is there any clear example of using weighted Barcodes produced by barcode scales 
So I can use with ospos to sell in portions

**Comment by WebShells** [comment]
@MohamedMaghrby that's the exact way it should be used... The barcode encoding now should take all products starting with 02 as weighted items, nothing more to be done. 
Please make sure that your printed barcode format is correct.

**Comment by MohamedMaghrby** [comment]
I did sir,

I defined the input format to 02(\d{5})(\w{6})

And set the barcode content to : Barcode

Then I set the Quantity Decimals in localization to 2

After that I created a new item called banana with barcode 0212345000000

Every time I do a scan it gives me Item add to sale failed

**Comment by WebShells** [comment]
Actually thats wrong... When you add a new item the UPC shouldn't be containing the prefix... So for example if your item's scale generated code is ( 02-10001-003500 ), the item code should be 10001 consisting of 5 digits, where the weight should be consisting of 6 digits as total.
In this way the barcode will be forced into register. 
Try it and let me know please

**Comment by MohamedMaghrby** [comment]
Yes sir, it works now
Thanks for your response

**Comment by WebShells** [comment]
Anytime... Glad it helped (Y)

**Comment by MohamedMaghrby** [comment]
Thanks

**Comment by truchosky** [comment]
how do you work with Kg and gr?, do you set the item price in gr, or is there any way to convert the gr (weight returns gr) to kg?
