### ISSUE TITLE
Question about registering OSPOS to national taxes of my country Bolivia

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#2418]
sorry for my english. In my country since this year 2019 changed to online billing, and Ospos is a very good option, I've been testing locally only for personal workshop inventory, my question is whether I can register ospos to national taxes where it enters a waiting phase for testing , by the time you have integrated the connection modules with the national tax servers of my country are tested for connection with them, and if you pass the tests, is enabled to work with the new national taxes in Bolivia.
Of course there are requirements and technical specifications for the development of electronic billing, for now I just need to know about my question about registering ospos to national taxes of my country. 

Some technical specifications in this link in another post I will expand

https://www.impuestos.gob.bo/page/341
https://www.impuestos.gob.bo/pdf/ANEXOS%20TECNICOS%20SFE.pdf

**Comment by mckaygerhard** [comment]
seems similar to was happening in Dominican republic and Venezuelan.. online for all ...

but i must daid to you taht seems it's more a problem on your side.. due ospos are opensource you must read the license.. 

se parece a lo que ocurre actualmente en Dominicana, Panama y Venezuela, todo en internet.. pero creo que la pregunta o no esta bien formulada o esta mas de tu lado analizarla.. te explico:
1) debes leer la licencia de ospos.. y canalizar tu mismo hasta donde aplica y hasta donde puedes aplicar..
2) una vez ali debes tu mismo leer los requerimientos, por ejemplo en Venezuela no importa que app sino que maquina envia la informacion, mientras que en Dominicana hay un caso especifica segun el tipo de facturacion realizar.. 

En ospos la unica experiencia que han tenido con maquinas y gestiones fiscales ha sido creo India GST o mejor dicho nisiquiera.. es decir no hay aqui quienes apliquen gestion fiscal directa.. yo aplique en Dominicana algo.. y ahora estoy tratando de hacerlo para otro pais..

**Comment by mckaygerhard** [comment]
seems similar to was happening in Dominican republic and Venezuelan.. online for all ...

but i must said to you that seems it's more a problem on your side.. so you must read the license of opensourcepos and later analize also your requirements.. due here there-s no so many that have experience with fiscal printing and online information to gubernamental institutions.... 

se parece a lo que ocurre actualmente en Dominicana, Panama y Venezuela, todo en internet.. pero creo que la pregunta o no esta bien formulada o esta mas de tu lado analizarla.. te explico:
1) debes leer la licencia de ospos.. y canalizar tu mismo hasta donde aplica y hasta donde puedes aplicar..
2) una vez ali debes tu mismo leer los requerimientos, por ejemplo en Venezuela no importa que app sino que maquina envia la informacion, mientras que en Dominicana hay un caso especifica segun el tipo de facturacion realizar.. 

Aqui en ospos la unica experiencia que han tenido con maquinas y gestiones fiscales ha sido creo India GST o mejor dicho nisiquiera.. es decir no hay aqui quienes apliquen gestion fiscal directa.. yo aplique en Dominicana algo.. y ahora estoy tratando de hacerlo para otro pais..

**Comment by SteveIreland** [comment]
Actually India GST is not automated either.   OSPOS licensing does not prevent anyone from adding the ability the ability to automate their billing, sales reporting, or taxing to their copy of the system.

**Comment by mckaygerhard** [comment]
hi @SteveIreland that sounds bit confusing.. if laws need many changes including rebranding?  some countries have very hard restrictions!

**Comment by SteveIreland** [comment]
Sorry it’s confusing. There was no discussion of rebranding. This request was about adapting OSPOS to be able to integrate with the tax services required by the Bolivian tax authorities.

However it didn’t take long for me to determine that the language challenges would make it impossible for me to attempt this effort.

**Comment by daN4cat** [comment]
As usual @mckaygerhard confuses the matter.
This has nothing to do with rebranding.
@ekardian needs to understand how OSPOS can interface the Bolivian taxing system and be approved.
It's beyond the scope of this project here.

**Comment by mckaygerhard** [comment]
as expected @ekardian, @daN4cat do not understand it and @SteveIreland is aware that the language are a challenge for all of them ...

.. currently the Latin American region is migrating to many changes respect fiscal recaudation and the online integration of the audit .. I am aware of what is happening in Bolivia, Dominican Republic, Venezuela (taking into account its crisis) and Panama .. but I will not be able to help you right away now.. but if you found more people maybe we can ajust.. but as you said some topic touch licensing issues

**Comment by daN4cat** [comment]
No follow up, I close.
