### ISSUE TITLE
Prevent Bootstrap Modal from disappearing when clicking outside or pressing escape?

### ISSUE THREAD

**Issue by AliSultanKhan** [opensourcepos/opensourcepos#2424]
Prevent Bootstrap Modal from disappearing when clicking outside or pressing escape?

**Comment by josh-tf** [comment]
I've tried to find a solution for this too - I'm not too familiar with how the modals are created but it looks like the changes we would need to make would be in the bootstrap js files themself which are part of the build

Keen to hear if anyone else has had any luck achieving this - we have 15 custom fields on our item form and sometimes an accidental click means we have to start again

**Comment by cristianjav** [comment]
In _public/js/manage_tables.js_ add this after line 78 and before _'message'_:
```
closeByBackdrop: false,
closeByKeyboard: false,
```
Then Grunt should be run to regenerate the js with the change made.

More info: https://nakupanda.github.io/bootstrap3-dialog/

**Comment by odiea** [comment]
I have found that if you add the following line after line 80 in application/views/partial/header.php that the js will also work. Great tip. Thanks @cristianjav .
<script type="text/javascript" src="js/manage_tables.js"></script>

**Comment by daN4cat** [comment]
@odiea it's not a good idea to suggest that workaround because the old and new is script will conflict.
Please follow the us change and grunt rebuild route.

**Comment by josh-tf** [comment]
Thanks @cristianjav !

**Comment by cristianjav** [comment]
You're welcome. I'm glad I was helpful. 👍

**Comment by odiea** [comment]
@cristianjav Thanks. I also like adding this new found modal dialog seen on your recommended page.
draggable: true, It helps getting the correct info from the page while editing the info.

**Comment by andriux1990** [comment]
Someone could help me here, it doesn't work for me.
thanks
