### ISSUE TITLE
Cost Price for Each Item & The Profit 

### ISSUE THREAD

**Issue by abdulhamid-ghannam** [opensourcepos/opensourcepos#2428]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

 #Question ;

Where can i add the cost price for each Item ?

and when i run the Item Report or Transaction report its didn't give me the Exactly profit , example :

The Red Marlboro its cost 6$ and the retail price is 8$ and plus tax its will be 9$ , so the profit will be 2$ .and the tax 1$ .
But the profit on the system 6$ .

how to fix it ?

and i have another question  : 

in the employee permission when i edit the permission and save it and says its saved , and go again to see if its saved , its not saved .
how to solve this and why its happen ?

Thank you very much , its great system .

**Comment by SteveIreland** [comment]
What version of OSPOS are  you testing with?  Also, what does your tax configuration look like?

**Comment by abdulhamid-ghannam** [comment]
Thank you for your reply  @SteveIreland 

The Version is  3.2.3 .

and the Tax conf. is :
Thanks 
![Screenshot (3)](https://user-images.githubusercontent.com/7567862/56484526-caa85180-6484-11e9-83bb-a5745af3e5f9.png)

**Comment by abdulhamid-ghannam** [comment]
any update?

**Comment by scottie01** [comment]
Hi abdulhamid-gha... I'm no expert or dev, just another user. I'm running 3.2.3 too. It seems you may be entering stock items from either the new item selection button on the sales module screen or in the Items module, without wholesale pricing?
