### ISSUE TITLE
Print Quote

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2432]
button print quote does not work.

**Comment by SteveIreland** [comment]
It works in the current development branch.

First question, did you select a customer to associate with the quote?

Second question, what version of OSPOS are you testing with?

Third question, where did you download the version you are testing from?

**Comment by andriux1990** [comment]
https://demo.opensourcepos.org/home

**Comment by andriux1990** [comment]
You can try it for yourself that the demo does not work either

**Comment by odiea** [comment]
@SteveIreland He is correct about the quote not printing. I had to enable the second print button for the quote to print. I downloaded from bintray the following unstable master.
opensourcepos.20190422231135.master.d35317.zip and my master also shows this issue.

```
<?php echo anchor("sales", '<span class="glyphicon glyphicon-print">&nbsp</span>' . $this->lang->line('common_print'), array('class'=>'btn btn-info btn-sm', 'id'=>'show_print_button', 'onclick'=>'window.print();')); ?>
	<?php if(isset($customer_email) && !empty($customer_email)): ?>
		<a href="javascript:void(0);"><div class="btn btn-info btn-sm", id="show_email_button"><?php echo '<span class="glyphicon glyphicon-envelope">&nbsp</span>' . $this->lang->line('sales_send_quote'); ?></div></a>
	<?php endif; ?>
```

**Comment by SteveIreland** [comment]
Sorry. I was reading too fast and missed the Print button.  I read it as the Quote button.   Thanks for clarifying

**Comment by SteveIreland** [comment]
This issue is that the quote.php file is missing the following statement around line 34. I will be including this fix in the changes I'm making for the fix for the pdf create issue.

`<?php $this->load->view('partial/print_receipt', array('print_after_sale'=>$print_after_sale, 'selected_printer'=>'invoice_printer')); ?>`

**Comment by SteveIreland** [comment]
I see @andriux1990 has closed this issue, but the fix is still coming.

**Comment by odiea** [comment]
I reopened it till further notice.
