### ISSUE TITLE
Adding Link to Customer in Daily Sales Page

### ISSUE THREAD

**Issue by tmn14** [opensourcepos/opensourcepos#2433]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: MariaDB 5.56
- OS and version is: centos
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I'm new to OSPOS, my knowledge of PHP and my development skills are only at first but I'm trying to make a small change (this is probably a fairly easy patch but I seem to have a problem with it)
I'm trying to link the customer name to the customer's card (customers / view / $ customer_id)
 I understand the place to add is in the function "get_sale_data_row" in table_helper.php. I've added a custom line :
empty($sale->customer_name) ? '' : anchor("customers/view/$person->person_id", $sale->customer_name, array('class'=>'modal-dlg', 'data-btn-submit' => $CI->lang->line('common_submit'), 'title'=>$CI->lang->line('sales_update'))),
But I do not get the client ID just empty ... What do I miss here?
Thanks!

**Comment by odiea** [comment]
I believe I have found your answer. I tested this and it worked in the current unstable master.
application/modes/sale.php add the following line around line 205
```
MAX(sales.customer_id) AS customer_id, 
```
in application/helpers/tabular_helper.php around line 110 add.
```
$row['customer_name'] = empty($sale->customer_name) ? '' : anchor("customers/view/$sale->customer_id", $sale->customer_name,
		array('class'=>'modal-dlg', 'data-btn-submit' => $CI->lang->line('common_submit'), 'title'=>$CI->lang->line('sales_update')));
```

**Comment by tmn14** [comment]
Hi @odiea,
Thank you for your answer :-) You found the solution
In tabular_helper.php I added '$ sale-> customer_id` and found the customer
