### ISSUE TITLE
Post Sale Payments

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2435]
### New Feature

A pull request was submitted to allow payments to be posted against a sale after the sale is complete.  This feature isn't supported for POS transactions since a sale cannot be completed unless payment is made.

So it's only available for Invoice sales.  For invoices deposits or a a partial payment can be entered at the point of time that the sale is completed which leaves a balance due for the invoice.

The intent of this change is to provide a way to enter the payment into OSPOS so that OSPOS will reflect the payment and reduce the balance due on the invoice.

The new payment is entered via the Update panel and the payment is written to the sales_payments table.   All of the sales reports (including the Daily Sales list from the Sales Register) will reflect the new balance due.

If the invoice is reprinted it will reflect the new payment.

**Comment by SteveIreland** [comment]
Pull request #2434 provides support for this feature.

This pull request introduces a structural change to the `sales_payments` table which will allow us to capture each individual payment with when and by who.

It also introduces a new table called `sales_stats` that will capture summary information about the sale that can be used to retrieve information that normally needs to be recalculated using SQL.  I use the table to track balance due without needing to recalculate the total same amount and total payment to date.

**Comment by SteveIreland** [comment]
The bintray download for this pull request can be downloaded via the following link by anyone interested in testing this out.  Please do not use it for a production site because there are still aspects of it that are being negotiated/discussed - and it DOES need more testing.

https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20190429004717.payment_update.30f03e.zip

**Comment by daN4cat** [comment]
@SteveIreland is any more work required here?

**Comment by SteveIreland** [comment]
Nope

**Comment by WebShells** [comment]
@SteveIreland can i know where i can see the payment report for a specific client in this PR ? 
I created a new sale partially paid, checked the edited form that now reflects due and cash and refund amnt etc, but i didn't find any report that shows the payment date and time of the payment.
