### ISSUE TITLE
Adding discounted price with each item individually?

### ISSUE THREAD

**Issue by mss30** [opensourcepos/opensourcepos#2436]
I'd installed and setup OSPOS recently and honestly it is a great contribution. I want to thanks to the OSPOS team for their effort. I have a small question as currently I don't know about OSPOS features very much. I had already looked into previous issues and didn't find the answer.

Anyways my question is that can I want to add a discounted price (along with retail price) with each item. Can I do so using the configurations page or any other settings? Or do I have to do this in the code myself?

**Comment by odiea** [comment]
The new 3.3.0 is moving away from the custom tables so you will have to do the code yourself.

**Comment by odiea** [comment]
If all of your items are going to have the same discount you could always use the default discount in Configuration. That will discount it at the POS.

**Comment by mss30** [comment]
Okay. Thanks for reply.
