### ISSUE TITLE
Round Final Total

### ISSUE THREAD

**Issue by w002qaa** [opensourcepos/opensourcepos#2437]
Hello,

Is any way to round the final total?
If the total between 12.01 to 12.49 -- I want round it to 12.00 
If the total between 12.50 to 12.99 -- I want round it to 13.00 

Thanks

**Comment by SteveIreland** [comment]
Have you checked out the cash rounding feature which provides that capability if you flag the payment type as cash?

**Comment by w002qaa** [comment]
Hi @SteveIreland ,

Where is this feature? I tried to change in the setting but nothing working.

**Comment by daN4cat** [comment]
@w002qaa which version are you using?

**Comment by SteveIreland** [comment]
If you are using a version that supports Cash Rounding you'll find it under Configuration > Localization

![image](https://user-images.githubusercontent.com/23066623/57195873-3c70a880-6f25-11e9-8513-2e197913fe3e.png)

**Comment by w002qaa** [comment]
@daN4cat 
I am using version 3.2.3

@SteveIreland 
I did the setup for this feature but is not working.

**Comment by odiea** [comment]
The tooltip for this feature states the following. Hope it helps.
"If Cash Decimals and Currency Decimals are the same then no cash rounding will take place.";

**Comment by SteveIreland** [comment]
I  haven't touched it in a long time so it's possible that it is no longer working.  But as @odiea noted, it doesn't make much sense for cash decimals to be the same as the currency decimals.  So what value do you have set for Cash Decimals?  Based on your first comment it should be set to 0.  And it only works if your payment type is equivalent to "Cash".

**Comment by SteveIreland** [comment]
I gave it a quick test and it appears to still be working (or at least doing something that looks like cash rounding).

**Comment by daN4cat** [comment]
No follow up, I close.
