### ISSUE TITLE
Update Error with invoices in development mode.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2438]
OSPOS Installation Info: 3.3.0 - cb0660
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
.PHP Version: 7.3.2 
.Server Port: 80
.DB Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
.OS: Windows NT PAVILION23 10.0 build 17763 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_items.csv:] - 0666 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓ 

The following error error shows in Sales Update Modal only in development mode.
$sale_info['amount_tendered'] appears to be the issue if no payment is entered.

A PHP Error was encountered
Severity: Warning
Message: A non-numeric value encountered
Filename: controllers/Sales.php
Line Number: 1171
Backtrace:

File: C:\wamp64\www\5219\application\controllers\Sales.php
Line: 1171
Function: _error_handler
File: C:\wamp64\www\5219\public\index.php
Line: 315
Function: require_once

**Comment by odiea** [comment]
Would you also add the following to the quote so that it works or prints.
```
<?php $this->load->view('partial/print_receipt', array('print_after_sale'=>$print_after_sale, 'selected_printer'=>'invoice_printer')); ?>
```

**Comment by SteveIreland** [comment]
Will do

**Comment by SteveIreland** [comment]
@odiea I'm having difficult recreating your issue.  I downloaded the latest master and set it up.  Then I upgraded my PHP to the same as yours, but are you really running version 5.0.12 of MySQL?  I don't believe that version is supported by OSPOS.   I'm running version 5.7.24
In your system info I'm seeing

.DB Version: mysqlnd **5.0.12-dev** - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

**Comment by SteveIreland** [comment]
Since I couldn't recreate the issue I proceeded with a fix to include that missing line of code in quote.php that you asked for.   That's in the master branch now.

**Comment by odiea** [comment]
According to xampp the DB Version: mysqlnd 5.0.12-dev  is different than the actual database version of 5.7.21

![2019-05-03 04_40_25-Window](https://user-images.githubusercontent.com/10962177/57132800-ef8ea580-6d5d-11e9-8752-f5bd8f1a9174.png)

**Comment by odiea** [comment]
The  program is now attached to a different db server.


OSPOS Installation Info: 3.3.0 - cb0660
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
.PHP Version: 7.3.2 
.Server Port: 80
.DB Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
.OS: Windows NT PAVILION23 10.0 build 17763 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_items.csv:] - 0666 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓

**Comment by odiea** [comment]
The following is the image from the db server.You can see that the listed DB version appears to be about the same.

![2019-05-03 05_17_12-Window](https://user-images.githubusercontent.com/10962177/57134313-0388d600-6d63-11e9-82c8-3b78c2350c5b.png)

**Comment by odiea** [comment]
I will ignore this issue then.

**Comment by SteveIreland** [comment]
Well THAT is interesting.  I just checked the demo site and it displays the same MySQL version.  Am I looking at this wrong?

**Comment by odiea** [comment]
The info is apparently the Library version and not the mysql version that is being used.

**Comment by daN4cat** [comment]
That 5.0.12-dev was reported in another issue where I said that looks strange.

**Comment by odiea** [comment]
OSPOS Installation Info: 3.3.0 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: .Chrome
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
.PHP Version: 7.3.2 
.Server Port: 80
.Mysql Version: 5.7.21 
.OS: Windows NT PAVILION23 10.0 build 17763 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_items.csv:] - 0666 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓ 

I found the following code that reports the mysql version correctly but someone with the knowledge will have to figure out how to get the info from database config or add inputs to the form.
```
<?php
				$link = mysqli_connect("localhost", "root", "", "ospos323");
				/* check connection */
				if (mysqli_connect_errno()) {
				printf("Connect failed: %s\n", mysqli_connect_error());
				exit();
				}
				 printf(".Mysql Version: %s\n", mysqli_get_server_info($link));
				mysqli_close($link);
				?><br>
```

**Comment by odiea** [comment]
And id someone knew how to use the getenv() function to use the variables that would be really slick. 'hostname' => !empty(getenv('MYSQL_HOST_NAME')) ? getenv('MYSQL_HOST_NAME') : '10.0.0.31',

**Comment by SteveIreland** [comment]
The following returns the version information.

`<?php echo mysqli_get_server_info($this->db->conn_id); ?>`

**Comment by daN4cat** [comment]
@webshells do you mind to fix this issue?

**Comment by WebShells** [comment]
@daN4cat not at all, I'll check it..
