### ISSUE TITLE
Datetime attribute

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2441]
First of all thanks to everyone for the incredible work they do in OSPOS.

Help with this problem:
I have created a datetime attribute with the name expiration date.
Then create 2 items, I save them with the datetime attribute (expiration date). and I only get this
![Screenshot_2019-05-05 Open Source Point of Sale Powered by OSPOS 3 3 0(1) png](https://user-images.githubusercontent.com/29256343/57198429-ea815000-6f2f-11e9-9dd8-a1ca44babca6.png)
In the  Receivings and Sales is working well
![Screenshot_2019-05-05 Open Source Point of Sale Powered by OSPOS 3 3 0(2) png](https://user-images.githubusercontent.com/29256343/57198518-089b8000-6f31-11e9-95a7-90ea2a451966.png)
but if I change the name of the item or add text, if I can see the expiration date
![Screenshot_2019-05-05 Open Source Point of Sale Powered by OSPOS 3 3 0(3) png](https://user-images.githubusercontent.com/29256343/57198798-61b8e300-6f34-11e9-8969-93472ef964cd.png)
The problem is that it does not happen in all cases. There are some elements that, even if I edit them, I never get the expiration date.
![Screenshot_2019-05-05 Open Source Point of Sale Powered by OSPOS 3 3 0(4)](https://user-images.githubusercontent.com/29256343/57198672-a8a5d900-6f32-11e9-907b-545c71bad6d0.png)
![Screenshot_2019-05-05 Open Source Point of Sale Powered by OSPOS 3 3 0(6)](https://user-images.githubusercontent.com/29256343/57198684-d1c66980-6f32-11e9-9916-13894c9c257b.png)
and the other problem is that in Receivings and Sales the date is shown duplicated
![Screenshot_2019-05-05 Open Source Point of Sale Powered by OSPOS 3 3 0(5) png](https://user-images.githubusercontent.com/29256343/57198720-56b18300-6f33-11e9-8717-ac585e08b838.png)
I do not know what to do to see the expiration date in the items module

**Comment by odiea** [comment]
Yes The fix for that is in the works. @jekkos will hopefully submit a fix soon.

**Comment by jekkos** [comment]
related to #2232 #2319

**Comment by daN4cat** [comment]
Please test latest master.

**Comment by andriux1990** [comment]
I like how it works now but when I look for the attribute, I do not have results.

**Comment by andriux1990** [comment]
I like how it works now but when I look for the attribute, I do not have results.

**Comment by daN4cat** [comment]
@andriux1990 what do you mean with no results?
I tested with the Demo website adding an expiry field with a date and it showed fine in Items.

**Comment by andriux1990** [comment]
Okay, I wanted to say when search for the attribute.
![IMG-20190617-WA0003](https://user-images.githubusercontent.com/29256343/59613111-8d0a2280-90db-11e9-9a91-f8d121783c8f.jpg)
![IMG-20190617-WA0002](https://user-images.githubusercontent.com/29256343/59613141-9c896b80-90db-11e9-9f62-b30fb814ad9b.jpg)
![IMG-20190617-WA0001](https://user-images.githubusercontent.com/29256343/59613158-a6ab6a00-90db-11e9-9200-8f4be1bd6d86.jpg)

**Comment by daN4cat** [comment]
Right, so it's a filter and search issue.

**Comment by odiea** [comment]
It appears to be on the date feature only.

**Comment by jekkos** [comment]
Hm ok was working on some improvements this Sunday but haven't finished yet. Will pick it up maybe tomorrow again.

**Comment by daN4cat** [comment]
@jekkos any update?

**Comment by jekkos** [comment]
I have added a change for this in master now. It should also search the other fields now (date and decimals)

**Comment by daN4cat** [comment]
@odiea confirmed it's working, therefore I close this.
