### ISSUE TITLE
Discount on items kit

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2442]
![Screenshot_2019-05-05 Open Source Point of Sale Powered by OSPOS 3 3 0](https://user-images.githubusercontent.com/29256343/57199162-240a8900-6f39-11e9-9d5f-aa84e6e12170.png)

I have this other problem. I made a kit of items (To sell the items per box, 10 in each box) with 2 discounts.
The costs of the individual item 2. the 10 would be 20 with 2 discount would be 18.
the problem is that when I add twice the box of items in sales only the 2 discount applies, likewise if I add three, four or five times more the box of articles always stays with the 2 discount.
![Captura de pantalla de 2019-05-05 13-13-47](https://user-images.githubusercontent.com/29256343/57199111-87e08200-6f38-11e9-9b05-983c539ed8f7.png)
![Captura de pantalla de 2019-05-05 13-21-38](https://user-images.githubusercontent.com/29256343/57199140-f6bddb00-6f38-11e9-9006-2adde969c865.png)
![Captura de pantalla de 2019-05-05 13-21-50](https://user-images.githubusercontent.com/29256343/57199143-fae9f880-6f38-11e9-9110-3ba8ace87f9a.png)
![Captura de pantalla de 2019-05-05 13-21-58](https://user-images.githubusercontent.com/29256343/57199151-0a694180-6f39-11e9-9e48-1649f745ab01.png)
![Captura de pantalla de 2019-05-05 13-23-01](https://user-images.githubusercontent.com/29256343/57199153-0f2df580-6f39-11e9-9225-8c96cc499630.png)

**Comment by odiea** [comment]
It appears that you might change it to a percentage discount. Your discount is a fixed 2.00 discount.

**Comment by andriux1990** [comment]
I'm sorry I overlooked this detail.
Thank you
