### ISSUE TITLE
Select customer given customer's account number

### ISSUE THREAD

**Issue by nira168** [opensourcepos/opensourcepos#2443]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
Hello,
How can I select customer by pressing Enter key when I input customer's account number? I tried input account number but when i press Enter or submit the account number is store as Customer's ID.
For example, 123456 is my customer's account number, but when i enter it return nothing as 123456 here will be customer ID.
Appreciate your help.
<img width="906" alt="Screenshot 2019-05-06 23 37 22" src="https://user-images.githubusercontent.com/17110407/57240209-1b5ca480-7058-11e9-8032-059f63ba2998.png">

**Comment by odiea** [comment]
In application/models/customer.php in the current master add $this->db->or_like('account_number', $search); beneath line 301 and see if that helps. It may have been left out at some time.

**Comment by odiea** [comment]
In application/models/customer.php you can replace line 308 with the following. It will show the customer acct number.
```
			$suggestions[] = array('value' => $row->person_id, 'label' => $row->first_name . ' ' . $row->last_name . (!empty($row->account_number) ? ' [' . $row->account_number . ']' : ''). (!empty($row->phone_number) ? ' [' . $row->phone_number . ']' : '' ). (!empty($row->company_name) ? ' [' . $row->company_name . ']' : ''));
```

**Comment by nira168** [comment]
Thanks @Odiea
In fact,  my purpose is to input customer's account number to the input field and pressing Enter Key then return customer. Example above I have customer account 123456, it already show suggestion David John[Customer account=123456][Phone Number=01234567890]. My problem is I filled 123456 in the input box then i press Enter, it's return nothing, but if i input customer's ID=2280 then press enter key, it will return customer. I want to return customer after i press enter key when i input customer account number

![test issue](https://user-images.githubusercontent.com/17110407/57307277-79e45a00-710e-11e9-8194-a7442ab22831.jpg)

Here's my software version code
public function get_search_suggestions($search, $unique = TRUE, $limit = 25)
	{
		$suggestions = array();

		$this->db->from('customers');
		$this->db->join('people', 'customers.person_id = people.person_id');
		$this->db->group_start();
		$this->db->like('first_name', $search);
		$this->db->or_like('last_name', $search);
		$this->db->or_like('CONCAT(first_name, " ", last_name)', $search);
		if($unique)
			{
				$this->db->or_like('email', $search);
				$this->db->or_like('phone_number', $search);
				$this->db->or_like('account_number', $search);
			}
		$this->db->group_end();
		$this->db->where('deleted', 0);
		$this->db->order_by('last_name', 'asc');
		foreach($this->db->get()->result() as $row)
		{
			$suggestions[] = array('value' => $row->person_id, 'label' => $row->first_name . ' ' . $row->last_name . (!empty($row->account_number) ? ' [' . $row->account_number . ']' : ''). (!empty($row->phone_number) ? ' [' . $row->phone_number . ']' : ''));
		}

		if(!$unique)
		{
			$this->db->from('customers');
			$this->db->join('people', 'customers.person_id = people.person_id');
			$this->db->where('deleted', 0);
			$this->db->like('email', $search);
			$this->db->order_by('email', 'asc');
			foreach($this->db->get()->result() as $row)
			{
				$suggestions[] = array('value' => $row->person_id, 'label' => $row->email);
			}

			$this->db->from('customers');
			$this->db->join('people', 'customers.person_id = people.person_id');
			$this->db->where('deleted', 0);
			$this->db->like('phone_number', $search);
			$this->db->order_by('phone_number', 'asc');
			foreach($this->db->get()->result() as $row)
			{
				$suggestions[] = array('value' => $row->person_id, 'label' => $row->phone_number);
			}

			$this->db->from('customers');
			$this->db->join('people', 'customers.person_id = people.person_id');
			$this->db->where('deleted', 0);
			$this->db->like('account_number', $search);
			$this->db->order_by('account_number', 'asc');
			foreach($this->db->get()->result() as $row)
			{
				$suggestions[] = array('value' => $row->person_id, 'label' => $row->account_number);
			}
			$this->db->from('customers');
			$this->db->join('people', 'customers.person_id = people.person_id');
			$this->db->where('deleted', 0);
			$this->db->like('account_number', $search);
			$this->db->order_by('account_number', 'asc');
			foreach($this->db->get()->result() as $row)
			{
				$suggestions[] = array('value' => $row->person_id, 'label' => $row->account_number);
			}
		}

		//only return $limit suggestions
		if(count($suggestions) > $limit)
		{
			$suggestions = array_slice($suggestions, 0, $limit);
		}

		return $suggestions;
	}

**Comment by nira168** [comment]
One more thing, I want to use Customer Card with barcode number. Because barcode scanner will auto submit after scanning like pressing Enter. If any way to disable auto submission after scanning, it's also a solution for me

**Comment by odiea** [comment]
If I understand correctly you would like the Customer Number to show the Customer the way entering an Item number shows the Item after pressing Enter?

**Comment by odiea** [comment]
If your primary goal is just to use Account number you can try the following. This will mess up the standard search results.
$this->db->group_end();
	$this->db->where('deleted', 0);
	$this->db->order_by('last_name', 'asc'); to 'account_number','asc' then in sales view in register add the auto focus in the customer auto complete and see if that gets you anywhere close.
.$("#customer").autocomplete(
	{
		source: "<?php echo site_url("customers/suggest"); ?>",
		minChars: 0,
		autoFocus: true,
		delay: 100,
		select: function (a, ui) {
			$(this).val(ui.item.value);
			$("#select_customer_form").submit();
		}
	});

**Comment by nira168** [comment]
Thanks @odiea I have added your code, but still no result after input account number and press enter. Here's my code
Customer 
public function get_search_suggestions($search, $unique = TRUE, $limit = 25)
	{
		$suggestions = array();

		$this->db->from('customers');
		$this->db->join('people', 'customers.person_id = people.person_id');
		$this->db->group_start();
		$this->db->like('first_name', $search);
		$this->db->or_like('last_name', $search);
		$this->db->or_like('CONCAT(first_name, " ", last_name)', $search);
		if($unique)
			{
				$this->db->or_like('email', $search);
				$this->db->or_like('phone_number', $search);
				$this->db->or_like('account_number', $search);
			}
			$this->db->group_end();
			$this->db->where('deleted', 0);
			$this->db->order_by('account_number', 'asc');
		/* $this->db->group_end();
		$this->db->where('deleted', 0);
		$this->db->order_by('last_name', 'asc'); */
		foreach($this->db->get()->result() as $row)
		{
			$suggestions[] = array('value' => $row->person_id, 'label' => $row->first_name . ' ' . $row->last_name . (!empty($row->account_number) ? ' [' . $row->account_number . ']' : ''). (!empty($row->phone_number) ? ' [' . $row->phone_number . ']' : ''));
		}
Register
/* $("#customer").autocomplete(
	{
		source: "",
		minChars: 0,
		delay: 10,
		select: function (a, ui) {
			$(this).val(ui.item.value);
			$("#select_customer_form").submit();
		}
	}); */
	$("#customer").autocomplete(
		{
	source: "",
	minChars: 0,
	autoFocus: true,
	delay: 100,
	select: function (a, ui) {
	$(this).val(ui.item.value);
	$("#select_customer_form").submit();
	}
	});
	$('#customer').keypress(function (e) {
		if(e.which == 13) {
			$('#select_customer_form').submit();
			return false;
		}
	});

**Comment by nira168** [comment]
Well it's work! I missed source site_url. Really thanks for your help

**Comment by nira168** [comment]
Hi Odiea,
The code your give me work with Enter key, but my scanner doesn't work with
it. Is there any way to fix this problem?

**Comment by odiea** [comment]
It works every time if you use the customer_id as the account number. I have had no luck using the account number to get the customer name to show.

**Comment by nira168** [comment]
It's okay, but is there any way to disable auto submit after scanning
barcode ?

**Comment by odiea** [comment]
Not that I am aware of.

**Comment by nira168** [comment]
Okay, Anyway thanks for your help
