### ISSUE TITLE
Search Suggestions Layout

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2444]
This is not an issues
I'm trying to show the name of the company in the sales search suggestions
I want to leave it as an option.
I was trying to add it in application/views/configs/general_config.php
![bitmap](https://user-images.githubusercontent.com/29256343/57436268-9959b080-71fc-11e9-9a24-89a8f613a2c9.png)
and I have not obtained results
If someone has any idea how to do it. I would appreciate your comment.

**Comment by andriux1990** [comment]
The reason I want to do it is that I have two items with the same name but from different manufacturers.
Thank you!

**Comment by cristianjav** [comment]
Hi, I've known OSPOS since recently so I tried to do what you need as a practice. I did it by making the following changes:
In _views/configs/general_config.php_ I added the **supplier_id** option for the suggestion columns.
In _models/item.php_ I modified the **append_label function**, I changed the line 546 to:
```
$supplier_info = $this->Supplier->get_info($item_info->$item_field_name);
$label .= $supplier_info->company_name;
```
and the line 558:
```
$supplier_info = $this->Supplier->get_info($item_info->$item_field_name);
$label .= NAME_SEPARATOR . $supplier_info->company_name;
```
I repeat to you that I have known OSPOS recently, I do not know if it will be the best way to achieve it. You should also try several searches to see if there are any errors.

**Comment by andriux1990** [comment]
Hello!. Thanks for taking the time
Poor what you did and you did not get results.
![image29](https://user-images.githubusercontent.com/29256343/57501349-6f5bc900-72a4-11e9-85f2-c06f880d5600.png)
![image18](https://user-images.githubusercontent.com/29256343/57501352-7387e680-72a4-11e9-8b8e-c8d32938bbb8.png)
![Screenshot_2019-05-09 Open Source Point of Sale Powered by OSPOS 3 3 0](https://user-images.githubusercontent.com/29256343/57501440-b47ffb00-72a4-11e9-808d-a3f1b283633b.png)
after selecting the supplier. In the search engine sales only shows me the id of the supplier. What I want is to see the name of the supplier when I'm doing a search.
![bitmap](https://user-images.githubusercontent.com/29256343/57501664-a1215f80-72a5-11e9-9365-142d7b5eb1f3.png)
![Screenshot_2019-05-09 Open Source Point of Sale Powered by OSPOS 3 3 0(1)](https://user-images.githubusercontent.com/29256343/57501674-abdbf480-72a5-11e9-8be3-c2021a142174.png)
![Screenshot_2019-05-09 Open Source Point of Sale Powered by OSPOS 3 3 0(1)](https://user-images.githubusercontent.com/29256343/57501733-daf26600-72a5-11e9-8275-56bf1171c980.png)
Muchas thank you @cristianjav

**Comment by cristianjav** [comment]
I didn't take into account that I have _multi_pack_ enabled. You have to make similar changes in the **get_search_suggestion_label** function. For example I made these changes and it worked:
```
if($label3 !== '')
{
  if($label3 == 'supplier_id')
  {
    $supplier_info = $this->Supplier->get_info($result_row->$label3);
    $label .= NAME_SEPARATOR . $supplier_info->company_name;
  }
  else
  {
    $label .= NAME_SEPARATOR . $result_row->$label3;
  }
}
```

**Comment by andriux1990** [comment]
Thank you. I am going to try

**Comment by andriux1990** [comment]
Thank you @cristianjav!. I did the tests and it works for me too.

**Comment by andriux1990** [comment]
> I didn't take into account that I have _multi_pack_ enabled. You have to make similar changes in the **get_search_suggestion_label** function. For example I made these changes and it worked:

How to use multi_pack, and for what? I was testing, adding packages to the item but without any results. I do not know if I'm using it in an incorrect way or its function is different. ?

**Comment by cristianjav** [comment]
Congratulations! I'm glad you made it. 

You can read about multi_pack at [wiki/items](https://github.com/opensourcepos/opensourcepos/wiki/Items) and in the comments at https://github.com/opensourcepos/opensourcepos/issues/1919

**Comment by andriux1990** [comment]
Okk. but I do not see any results.
I understand it this way: I have two articles, articles 1 are two boxes containing 10 bottles each, a total of 20. and the items 2 have the 20 bottles
![Screenshot_2019-05-12 Open Source Point of Sale Powered by OSPOS 3 3 0(1)](https://user-images.githubusercontent.com/29256343/57596550-771ba780-7508-11e9-8083-185a09c3e2f7.png)
to items 1, I mark Low sell item.
and in quantity per package I give 10.
Low sell item added BOTTLES COCA
![Screenshot_2019-05-12 Open Source Point of Sale Powered by OSPOS 3 3 0(2)](https://user-images.githubusercontent.com/29256343/57596871-20af6880-750a-11e9-9bd0-6e9545fd8055.png)
then in sales I sell a box of bottles.
and checking the stock only a box of bottles was sold but it is not discounted of the loose bottles
![Screenshot_2019-05-12 Open Source Point of Sale Powered by OSPOS 3 3 0(4)](https://user-images.githubusercontent.com/29256343/57597092-1f327000-750b-11e9-8bf2-3f0e64f191b8.png)
I do not understand why this is so.
Thank you!.

**Comment by cristianjav** [comment]
**I'm going to answer you but before I clarify that I can be wrong because I learned this by reading the information in the links I passed you and reviewing the code.**

They are two different items. Bottles | Each is to record the bottles you have out of boxes, Bottles | Box is to record the boxes of bottles.

In your example you have a total of 40 bottles:
 
- 20 bottles in 2 boxes of 10.
-  20 bottles out of a box.

Also, the stock is not automatic in case you run out of loose bottles (Bottles | Each) and need to open a box to replenish them. In this case you must register a purchase and put -1 Bottles | Box and 10 Bottles | Each. The transaction total should give you $0.

Items are connected to each other for better reporting. In case you're wondering.

It would be better to give the items the same name and change the name of the package. Then in Sales you will have Bottles | Each and Bottles | Box

**Comment by cristianjav** [comment]
Perhaps it would be better to close this issue. This no longer has anything to do with Search Suggestions Layout. Open another one in case you have more doubts.

**Comment by tmn14** [comment]
hi @andriux1990 
I suggest you to look into items kit that will resolve your inventory problem (just create the box as kit of 10 each bottels).
I agree with @cristianjav you can close this issue and open new one if you still doesn't find your answer

**Comment by andriux1990** [comment]
OK now I understand.
Thanks for your comments and for the help.

**Comment by mckaygerhard** [comment]
the proposed solutions here are the most slowers

**Comment by andriux1990** [comment]
already passing the thousand products the search of the products takes several seconds.
@mckaygerhard What do you think is the fastest way to do this?

**Comment by mckaygerhard** [comment]
umm.. WOW.. i have no idea.. ospos it's a inherint project so there's no real ID on some tables.. so that's the reason of that problem.. it's not intented to be a huge application.. for that tthere's more productive solutions (of course not odoo.. that it's a shit)

**Comment by WebShells** [comment]
@mckaygerhard That's how the project was build, you either like it or just leave kid... And keep your suggestions to yourself... Whoever is stikk using the app, am sure hes already satisfied...

**Comment by mckaygerhard** [comment]
> @mckaygerhard That's how the project was build, you either like it or just leave kid... And keep your suggestions to yourself... Whoever is still using the app, am sure hes already satisfied...

what's your problel.. do you read CAREFULLY the answer.. i suggest that:

* there's a solution: no? then leave the comment be free
* there's a solution: yes! ok so then where are the solution?

as i said.. opensourcepos are FAR BETTER THAT  oddo.. are simpel a great to use it! make this feature require some changes hard to develop i listed to you @WebShells  :

* make a better join with supplier customers table
* modifiy the model to make less slower the query
* do no use the CI framework Active Record to make subquerys (the problem reported in this iisue)

**Comment by mckaygerhard** [comment]
and @WebShells  he was talking with me  not with you so be clear!

**Comment by andriux1990** [comment]
at opensourcepos.org, as I understand it, they have customers with pharmacies.
![Screenshot_2020-01-09 OSPOS – Open Source Point of Sale](https://user-images.githubusercontent.com/29256343/72072950-8c71ed00-32b4-11ea-82f8-9c1464943f95.png)
In pharmacies, this is vital to see the provider or the laboratory. This is because there are products that have the same name, the same specifications, and when looking for the product you cannot know which of the two is the one that should be added to the shopping cart. I use it in the pharmacy to know which product I should select.

but after passing the 1000 products it takes about 7 seconds for the products to appear when searching for them. That is why I ask if there is a faster and easier way.

I also add the option to see the categories when I look for the product and that is very fast, I don't know why it takes 7 seconds with suppliers

**Comment by odiea** [comment]
If you are using Attributes disable them in the items module.

**Comment by andriux1990** [comment]
to see it this way
![Captura de pantalla](https://user-images.githubusercontent.com/29256343/72074086-deb40d80-32b6-11ea-9c63-414abff5bb15.png)

**Comment by mckaygerhard** [comment]
i belive that @andriux1990  have a pint here! web page said , they have customers with pharmacies but any DRUGSTORE (it called drugstore i guess) must see the provider customer! ... **it makes sense** @odiea  or web page does said only bloffs?

**Comment by andriux1990** [comment]
> If you are using Attributes disable them in the items module.

I could do it but in the attributes are the expiration dates of the medications

**Comment by andriux1990** [comment]
> If you are using Attributes disable them in the items module.

@odiea I just did what you told me and there was no change always the 7 seconds to show

**Comment by odiea** [comment]
I guess the question is where are you searching at? the Register or the Items module?

**Comment by andriux1990** [comment]
I just want to see if there is a way that is not difficult, and does not have to make so many changes in the code to be able to show the results without taking so much time.
I also believe that this is something that Ospos needs, it is a big step since many programs do not have

**Comment by andriux1990** [comment]
> I guess the question is where are you searching at? the Register or the Items module?

in the register, in the sales module

**Comment by odiea** [comment]
I guess that the search depends on what modifications you have made and what or how you are searching for the item

**Comment by daN4cat** [comment]
@andriux1990 I don't use attributes and customised the code to add the three specific things natively and I have 10 of 1000 items, search is far better it used to be in OSPOS 1.1!

The optimisation is with the database and not the php code.

**Comment by mckaygerhard** [comment]
> The optimisation is with the database and not the php code.

umm do you suggest some tune to the database? it makes sense but if you see the first post, he only added a new field to the framework, supplier.. that means a new sub.query.. so wheantime there's still a already made query (item) a new query i'ts starting (supplier) so that i guess was the slow reason..  (i guess)

**Comment by odiea** [comment]
Some optimization may be to try Mariadb instead of Mysql. Also try the highest php version that you can support.

**Comment by andriux1990** [comment]
I always use mariadb.
What solutions do you propose? I can upload the code as it is with the changes

**Comment by odiea** [comment]
I really have no idea. You can try disabling Attributes in the Sales module for a test and see if that helps any.

**Comment by andriux1990** [comment]
The search for Ospos is very good I think nobody can complain about this.
What I mention is because of these additional changes, which are 100% required in a pharmacy. have search suggestions - Item name | Category | Suppliers | price

**Comment by andriux1990** [comment]
> I really have no idea. You can try disabling Attributes in the Sales module for a test and see if that helps any.

I've already disabled everything and it really doesn't help

**Comment by andriux1990** [comment]
`$supplier_info = $this->Supplier->get_info($result_row->$label3);`

I have noticed that only this line is the one that delays the search

**Comment by odiea** [comment]
You can try the following and see if it changes anything.

```
if($label3 !== '')
			{
				if($label3 == 'supplier_id')
				{
					$supplier_info = $this->Supplier->get_info($result_row->$label3);
					$label .= NAME_SEPARATOR . $supplier_info->company_name;
				}
				else
				{
					$label .= NAME_SEPARATOR . $result_row->$label3;
				}
			}	
```

**Comment by andriux1990** [comment]
ok I'll do it now

**Comment by andriux1990** [comment]
> `$supplier_info = $this->Supplier->get_info($result_row->$label3);`
> 
> I have noticed that only this line is the one that delays the search

I think it is this line that puts the slow search

**Comment by andriux1990** [comment]
I managed to go from 7 seconds to 1.89 seconds

**Comment by odiea** [comment]
What did you do to achieve the new time?

**Comment by andriux1990** [comment]
just delete this `Supplier->`

**Comment by andriux1990** [comment]
I apologize for this mistake I thought I had it, but now I have it

**Comment by odiea** [comment]
What did you do to achieve the new time?

**Comment by andriux1990** [comment]
on models / Vendor on line 56, clone this function. change get_info to a different name and delete all the 'else'.

and in models / Item change get_info for the new name that I put.
And this worked for me. Now searches are fast enough as I hope

**Comment by andriux1990** [comment]
It is not the most appropriate but it worked.
if something is wrong please let me know

**Comment by andriux1990** [comment]
@odiea Any idea how to put these search suggestions with colors, to differentiate them better.
I tried but I couldn't do it
![busqueda](https://user-images.githubusercontent.com/29256343/72205522-b6104d00-3449-11ea-8062-2eae4546c642.png)

**Comment by daN4cat** [comment]
It light be that it's searching a non-indexed field, hence it's slow.

**Comment by odiea** [comment]
@andriux1990  All I can offer you is a color change. I could not find a way to alternate the colors.
```
#ui-id-1:nth-child(even){ font-size: 15px; font-weight:500; color: #04c; }
```

**Comment by andriux1990** [comment]
Well thanks, I guess it must be able to be done in some way

**Comment by andriux1990** [comment]
> @andriux1990 All I can offer you is a color change. I could not find a way to alternate the colors.
> 
> ```
> #ui-id-1:nth-child(even){ font-size: 15px; font-weight:500; color: #04c; }
> ```

Look @odiea I already did it
![WhatsApp Image 2020-02-23 at 9 01 51 AM](https://user-images.githubusercontent.com/29256343/75114514-1b945380-561c-11ea-9254-d9dfe8596b3f.jpeg)

**Comment by andriux1990** [comment]
If you are interested in the changes, I can send them to you. although I know that you are very intelligent and capable and that you probably already have this.

There is something I could not. If you have any suggestions, I would appreciate it.
is to be able to use the search suggestions to show me the quantity that I have in stock.
this is currently available but only when a product is added for sale

**Comment by odiea** [comment]
Sorry I do not have the knowledge to do that but it would be a nice added feature.

**Comment by andriux1990** [comment]
> Sorry I do not have the knowledge to do that but it would be a nice added feature.

if also, it would be very interesting, so we would not have to add the product to see if we have in stock, we would look at the quantity from the search suggestion.

at night I will try this again to see if I get it

**Comment by andriux1990** [comment]
> > Sorry I do not have the knowledge to do that but it would be a nice added feature.
> 
> if also, it would be very interesting, so we would not have to add the product to see if we have in stock, we would look at the quantity from the search suggestion.
> 
> at night I will try this again to see if I get it

I have not succeeded. makes it difficult for me when there are more stock locations :(

**Comment by MoiNKhulna** [comment]
> > @andriux1990 All I can offer you is a color change. I could not find a way to alternate the colors.
> > ```
> > #ui-id-1:nth-child(even){ font-size: 15px; font-weight:500; color: #04c; }
> > ```
> 
> Look @odiea I already did it
> ![WhatsApp Image 2020-02-23 at 9 01 51 AM](https://user-images.githubusercontent.com/29256343/75114514-1b945380-561c-11ea-9254-d9dfe8596b3f.jpeg)

please i need this  with stock quantity please help

**Comment by LuisPadilla** [comment]
Greetings @andriux1990 , I hope you are well, I need that function, would you be so kind to share it with me or tell me how to do it?
Thanks in advance.

**Comment by nira168** [comment]
@andriux1990 hello, i see your system can show item_pic in search suggestions. Could you share me the code how to do it? Thank you in advance, i really need this function.
