### ISSUE TITLE
Add Tagalog tl-PH to weblate

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2449]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 7.0
- MySQL or MariaDB version is: 5.7
- OS and version is: 
- WebServer is: 
- Selected language is: en-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### New Feature
For some reason I thought that this language was already translated, but it isn't.  I have a client that needs it and is willing to translate.  @jekkos can you add the language as soon as possible so that translation can be completed for a 3.4.0 release?

**Comment by jekkos** [comment]
Hi @objecttothis. You can add the language yourself by clicking 'add new translation' in any component you want to translate. The locale can be amended to the folder name once an initial set of files is committed in github.

**Comment by objecttothis** [comment]
Thanks.  Done.

**Comment by objecttothis** [comment]
It's a bummer that you have to go into each component to do create the translation.  OK, I've gotten the Tagalog (tl) translation.  A few things need to happen.

- The /languages/tl/ folder needs to be changed to /languages/tl-PH/ to make it consistent with our languages.
- The weblate interface needs to be adjusted to match /tl-PH/ and not /tl/
- It appears that the permissions are messed up for Receivings and Sales because it doesn't allow me to Start a New Translation.  I can only Request a New Translation

**Comment by objecttothis** [comment]
@jekkos I found the settings for Receivings and Sales that allows you to just automatically add the translation and fixed those two.  The other stuff is still needed and I'm not sure how to go about it.

**Comment by objecttothis** [comment]
I can see the language code at https://translate.opensourcepos.org/languages/tl/#information but it doesn't allow me to change it.

**Comment by jekkos** [comment]
Maybe you can try the other way around, add the language folder in git first and copy the english files, then commit to weblate? Might be more convenient?

**Comment by objecttothis** [comment]
I believe I fixed it by renaming the folder on the master and then pulling in weblate like you suggested.  Thank you @jekkos
