### ISSUE TITLE
Adding Customer Account Number to Customers Table View

### ISSUE THREAD

**Issue by Tbwan** [opensourcepos/opensourcepos#2451]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is:  4f5ad57
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: Ubuntu 18.04
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I'm attempting to display the existing "Customer Account Number" field in the table that displays in the Customers view, as well as some other locations. I thought the code location for table displays would be easy to find, but as a CodeIgniter newbie, I'm having trouble figuring out how the code works. Can someone help clarify how to do this?

**Comment by odiea** [comment]
To get the following in Customer table. Hope this helps you out.
![2019-05-21 15_42_55-Open Source Point of Sale _ Powered by OSPOS 3 2 3](https://user-images.githubusercontent.com/10962177/58132952-df8d1780-7bdf-11e9-8922-68cb290e2456.png)

In application/helpers/tabular_helpers.php
function get_customer_manage_table_headers() add the following lines below first name.
```
array('company_name' => $CI->lang->line('customers_company_name')),
array('account_number' => $CI->lang->line('customers_account_number')),
```
function get_customer_data_row($person, $stats) add the following lines below first name.
```
'company_name' => $person->company_name,
'account_number' => $person->account_number,
```

**Comment by Tbwan** [comment]
So that's where it is! Thanks so much, this is exactly what I needed.
