### ISSUE TITLE
Demo Server needs to be Reset

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2453]
Items are no longer showing in the demo Server. Possibly for issue #2452 or from someone adding 22 different stock locations.

**Comment by andriux1990** [comment]
It is because of the error #2452  But instead of resetting, there is a way to fix it without destroying the database

**Comment by WebShells** [comment]
Ill do a refresh

**Comment by odiea** [comment]
It is just a demo server. The database reset would be ok for the next person to screw up.

**Comment by jekkos** [comment]
Hmm something got stuck there, had to restart docker daemon.. should be fine again (also bumped the base image as I read about some serious security vulnerabilities in alpine base images)

**Comment by odiea** [comment]
Bad Gateway

**Comment by odiea** [comment]
Invalid user in a foreign language?

**Comment by jekkos** [comment]
I might have accidentally installed a version with mode set to production (and thus allowing users to change user / pwd). Should be fine again now (although the server disk is full which needs fixing)

**Comment by jekkos** [comment]
Ok demo has latest master now, will test a bit tomorrow.
