### ISSUE TITLE
Regarding missing files into current repository 

### ISSUE THREAD

**Issue by amitmagnatesage** [opensourcepos/opensourcepos#2455]
Hello,

I am currently trying to setup this project on my local system and i am using this repository code.But when i am trying to access and form like add employee,add customer they are not working fine.

I think i have issue with dist folder's file into current repository so can you please share those missing files,

Missing file : public/dist/opensourcepos.min.js?rel=aaf585bba7

Thank you.

**Comment by caloyregs** [comment]
same issue here.
