### ISSUE TITLE
Add new payment type as "Due paid" to calculate pending due

### ISSUE THREAD

**Issue by sky12ka4** [opensourcepos/opensourcepos#2456]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3/3.3.0 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

How can i add new payment type "due paid" so that i can calculate pending due.
lets take a case in which customer purchases product for INR 1000 and he pays only INR 700.
So to complete the sale cashier will add INR 700 as "cash" and INR 300 as "due".
Next time customer visits the store so pays INR 150 of his last time dues so here cashier should have some type of payment type ( eg "due paid" ) and in backend this will get subtracted from "due" so as to get remaining due of the customer.

eg:
due=INR 1000
due paid = 400
due remaing = due-due paid = 1000-400=600

please guide how this can be done!

**Comment by SteveIreland** [comment]
You should use an invoice to track the sale.  It will allow a sale to be "complete" even though there is a balance due.

Then when the customer comes in to pay the balance due then you simply locate the sale and edit it to add the additional payment.

The invoice has been there for awhile, the additional payment is a new feature with the 3.3 development effort.

**Comment by daN4cat** [comment]
Even without invoice the due payment is available.
You later edit the sale and you can add a payment or change what has been paid and what's due.

**Comment by sky12ka4** [comment]
@daN4cat unfortunately partial due payment is not available on edit sale page..we can just change the payment type from due to cash or any other but cannot change the amount ( this should be available for partial payment of due. eg due is 500,customer pays 400 so due pending is 100)

**Comment by daN4cat** [comment]
Hmmm I remember that partial payment was possible.
You can't edit past payment but add a partial payment. But let me try this even because it's a long time since I implemented this feature.

**Comment by WebShells** [comment]
@daN4cat it's possible in case he added 2 types of payments part due and other is cash, then he can set that to cash later on, but he cannot add a specific amount/payment to the invoice... That what steve was working on but 3.3 isn't ready yet...

**Comment by daN4cat** [comment]
Understood but there is no mention of invoice, unless I'm mistaken, in the original problem.

**Comment by mckaygerhard** [comment]
hi @sky12ka4 that's you search for are here: https://github.com/osposweb/osposweb/tree/osposweb-cxcteipado CAREFULLY THAT COMMITS ARE ONLY AS REFERENCES OF HOW TO DO THAT..

* added a new paidment method
* caculate tables for that 
* some extra calculation and ..
* extra column for in some reports

of course only for educational purposes, obviously there's some mistakes and not comments on code but the branch are special made with only related commits, by the way over a older release..

**Comment by SteveIreland** [comment]
Adding a partial or complete payment to a sale is included in the current master.  As far as I know it is still working.  Simply go to Daily Sales and locate the invoice and select it for editing.  The balance due is automatically defaulted into the new payment amount but you can override it to be a partial payment.  If there isn't a balance due then you cannot add a payment and the only change you can make to payments is to change the payment type.

I'll retest this feature over the weekend to make sure it is still working.  It doesn't sound like a lot of people have tried it out yet.

**Comment by SteveIreland** [comment]
@daN4cat "invoice" was mentioned as a solution to the problem.   Since POS sales should always be paid in full it seems to me the correct solution is to process the sale as a invoice so that it can be completed and the balance due tracked.

**Comment by izeblood** [comment]
Thank you @SteveIreland you are a troubleshooter... now I know how to pay multiple payments...

**Comment by WebShells** [comment]
@SteveIreland how too see payments history later? 🤔

**Comment by izeblood** [comment]
@SteveIreland but one thing that needs improvement a little just a little is the Payment Type [Select..]
In my own opinion, all remaining balances will include in the due like this:
![balances](https://user-images.githubusercontent.com/32444665/72863710-96f8a180-3d0c-11ea-97b9-61cc454bbef2.jpg)

**Comment by izeblood** [comment]
...If you select due to the last amount of payment the word [Select] will gone and the option now is to cash or due and it will stop the running balances. 
(I tested it many...many..times...)
