### ISSUE TITLE
Detailed Transaction Report not showing details

### ISSUE THREAD

**Issue by ugogoinfo** [opensourcepos/opensourcepos#2458]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 4f5ad57.
- PHP version is: 5.6.40
- MySQL or MariaDB version is: 10.1.40-MariaDB
- OS and version is: linux
- WebServer is: idshosting
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hi, please help.  Details of Detailed Transaction Report no longer displaying as from yesterday 30/5/2019.

It was showing before, no issues.  All details up to and including 29/5/2019 show up fine.

Yesdteray, I added a new Employee, set her permissions and logged into her account to test the permissions, and whilst logged into her account, processed some sales.

The Detailed Transaction Report worked fine.

After about half an hour I refreshed the report.  No transaction details showed up.

I logged into my own profile, and the same thing, no details.
![Tr Report](https://user-images.githubusercontent.com/4752733/58684530-e43c9300-8378-11e9-9f1b-9f3b7f730396.jpg)
![Tr Report Ok](https://user-images.githubusercontent.com/4752733/58684531-e4d52980-8378-11e9-864d-977e64b833fb.jpg)
![Tr Report Ok](https://user-images.githubusercontent.com/4752733/58684534-e6065680-8378-11e9-9431-776763922b66.jpg)
![Tr Report](https://user-images.githubusercontent.com/4752733/58684540-e7d01a00-8378-11e9-9c85-fe8872987045.jpg)

The only transactions processed for yesterday was one cash sale, one debit card sale; details showed up fine.  Then when I pulled the report again to review details of the sales, no further details were shown.

We are using OsPos in a live environment, and this is the busiest time of the month for us,  so you can understand the urgency of this being resolved.

We now have to record all sales manually until this is resolved.

If it would be quicker, I would like to know how to delete transactions of 30/5/2019  via PHPMyAdmin  and will remove the user and try again. 

If that is not possible, then  I have a database backup up to 28/5/2019.  I'm willing to empty the entire database and recover from the backup if it will be faster.

Any help would be appreciated.

Thank you

**Comment by ugogoinfo** [comment]
Hi does anyone have anything to help with this query?

I did a clean install and captured all the data again, and it worked well until today, and from today's date the exact same thing is happening.

Please help with anything, how to get the detail to show without having to go into PHPMyAdmin.

Thanks

**Comment by WebShells** [comment]
@ugogoinfo is there anything showing in error logs? And what is specifically happening before this issue appear?

**Comment by odiea** [comment]
Enable error reporting and see what's going on.

**Comment by ugogoinfo** [comment]
Thanks, do you mean php error reporting or is there some error reporting feature in OsPos?  I searched for how to enable error reporting in OsPos could not find anything so far.

**Comment by ugogoinfo** [comment]
@WShells - today a new user who had not logged in before at the same time that I was logged in, logged into view reports.  That is the only thing different today.

**Comment by odiea** [comment]
1, Change public/index.php to development
2. Application/config/config.php.
scroll down about half way and you should see error logging. Change the 0 to 1.
3 You will then be able to see the errors in the browser under inspect then network. This is in Google

**Comment by ugogoinfo** [comment]
@odiea  thanks

> 3 You will then be able to see the errors in the browser under inspect then network. This is in Google,

 I think you mean Google Chrome?

I don't have that browser installed, but I looked at Developer tools in Firefox and it reported a Syntax Error.

![SyntaxError-Transactions](https://user-images.githubusercontent.com/4752733/60344216-52936600-99b6-11e9-8c94-2927e597b763.jpg)

Please let me know if that is what you meant, thanks.

If not, I will have to figure out how to use the Google Chrome Developer.

**Comment by ugogoinfo** [comment]
> 
> 
> Enable error reporting and see what's going on.

Where is this error reporting?

**Comment by ugogoinfo** [comment]
> 
> 
> 1, Change public/index.php to development
> 2. Application/config/config.php.
> scroll down about half way and you should see error logging. Change the 0 to 1.
> 3 You will then be able to see the errors in the browser under inspect then network. This is in Google

Where do I do this?  I'm assuming cpanel?

**Comment by ugogoinfo** [comment]
> 
> 
> @ugogoinfo is there anything showing in error logs? And what is specifically happening before this issue appear?

Sorry, where are these error logs?

**Comment by odiea** [comment]
You may get to see the error better if you click on network then on the error.

**Comment by ugogoinfo** [comment]
> 
> 
> You may get to see the error better if you click on network then on the error.

Thanks.  I can't seem to find any error details under network tab.  I'm only seeing an error icon when I click the console tab as per previous screenshot. 

![NetworkReport](https://user-images.githubusercontent.com/4752733/60350215-68f3ee80-99c3-11e9-8a8f-d54c4ee973df.jpg)

**Comment by odiea** [comment]
Click on the 1st one that says get and that should expand it then cycle thru the tabs on the right.

**Comment by odiea** [comment]
This will show how it works. I have error logging enabled and index.php set to production. So you can ignore the upper part.
![2019-06-28 11_50_09-Window](https://user-images.githubusercontent.com/10962177/60361518-9e84e180-999b-11e9-88ec-cb0ecf2de13e.png)

**Comment by ugogoinfo** [comment]
@odiea   Thanks so much, I have a bigger screen at home, will do it this weekend.  This screen is really too tiny. I think I have isolated the exact transaction that caused the error in reporting. will report back over the weekend or Monday. God Bless.

**Comment by yusufbiyik** [comment]
![report](https://user-images.githubusercontent.com/10947957/60410052-f3f50480-9bce-11e9-9b0c-048a0d2c9e0c.JPG)
problem: end_date when not daterangepicker plugin ?
date does not go further than today's date.

**Comment by daN4cat** [comment]
Unless I'm mistaken OSPOS is not expected to have transactions in the future.
Or is this a different case?

**Comment by ugogoinfo** [comment]
@odiea Thanks, I finally got time to try that, but can't find any error message other than the one under Console.

![NetworkReport2](https://user-images.githubusercontent.com/4752733/60721264-a1e51380-9f2d-11e9-854e-23ac5298c71c.jpg)

**Comment by ugogoinfo** [comment]
Hi Everyone

Just to let you know we gave up on OsPos, we can't figure out why it stops showing reports.  Wishing you all the best on the development of this potentially awesome POS.
