### ISSUE TITLE
Need to deprecate check for import_items.csv in install statistics

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2460]
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 7.1.3
- MySQL or MariaDB version is: 5.7.34
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue

With the removal of import_items.csv from the root folder, this check needs to be removed from the installation statistics page.  @WebShells do you feel up to this?  Should be an easy base hit.

**Comment by WebShells** [comment]
@objecttothis for sure, i already have some modifications to be done related to stat page am just waiting for full recovery after lasik operation so i can get back to work 🤓...

**Comment by daN4cat** [comment]
@objecttothis true, I forgot to write about because I noticed that the other day.
Please fix that as part of 3.3.0, @WebShells can do any additional change later when fully recovered. Take it easy!

**Comment by objecttothis** [comment]
Sorry, I missed that memo. Here's to better eyesight! I'll take ownership of this then.

**Comment by WebShells** [comment]
@objecttothis @daN4cat thanks, i already missed my pc looooads, currently 404 error vision not found 😅. 
It's ok for 3.3.0, guess everyone is already excited for the release... 
Please do @objecttothis except if i had the chance to do it before... Thank you

**Comment by objecttothis** [comment]
Done.  It's in pull request #2462. If it looks good let's merge it.

**Comment by daN4cat** [comment]
Merged. Thanks.
