### ISSUE TITLE
Jfrog bintray

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2464]
This is just a query about
Where can I download the latest complication of ospos? 

bintray is still without packages.

![Screenshot_20190615-080303_Chrome](https://user-images.githubusercontent.com/29256343/59552496-f73c8f00-8f44-11e9-92d3-da1055bf92e4.png)

**Comment by odiea** [comment]
Yes @jekkos has been working on this issue.

**Comment by jekkos** [comment]
Very annoying that bintray is so unresponsive (emailed them again today)

I was going through the other options for deploying artifacts from the build and one of them is using github itself. So this means we could try to just push unstable builds to the releases, so it might be something to consider.

**Comment by jekkos** [comment]
Sent another message to them , no replies yet.

**Comment by jekkos** [comment]
27/06, still no reply. I have also contacted their sales dept.

**Comment by objecttothis** [comment]
I think we should look for an alternative to bintray. Just IMO

**Comment by daN4cat** [comment]
What could that be?

**Comment by jekkos** [comment]
Check this list of providers

https://github.com/travis-ci/dpl

**Comment by odiea** [comment]
Also found this site to see alternatives to Bintray.
https://stackshare.io/bintray/alternatives

**Comment by jekkos** [comment]
I tried to change the deploy plugin to use the gh-pages branch instead, so that those builds are just pushed to git instead. Currently still stuck at having the plugin push the zip file to the gh-pages branch on github (seems to be a config issue).

**Comment by jekkos** [comment]
Ok the push worked, the latest master zip is now in the gh-pages branch in this repo.

**Comment by jekkos** [comment]
So there's two options here, either I configure the deploy job to force push the latest build artifact to this branch, or I chose to do incremental commits. I think it might be handy still to have builds for different branches, but maybe only just the latest version there. Don't think this situation is configurable out of the box.

**Comment by odiea** [comment]
And how do we access these new builds.

**Comment by jekkos** [comment]
https://github.com/opensourcepos/opensourcepos/tree/downloads

**Comment by jekkos** [comment]
Or another option might be pushing it to the weblate server and then hosting from there.

**Comment by WebShells** [comment]
@jekkos if the second option pointing download.opensourcepos.org to a server auto generating the list of all build into a specific directory works without any limitations, I can host it either on web account or on another dedicated account...

**Comment by daN4cat** [comment]
We need to update the README with the new builds location.

**Comment by daN4cat** [comment]
And well done with the change.

**Comment by jekkos** [comment]
Yes correct. Storing it on github has the advantage that you know it was pushed by travis so there's no possibility that someone tampered with the contents. Still I think I should add a simple html page that adds links to the generated artifacts, something similar to a webserver's directory listing.

**Comment by objecttothis** [comment]
@jekkos well done.  Here is my recommendation:
- Setup automatic deletion of old builds so that we keep the repository of builds fairly clean without maintenance.
- Setup a directory structure in the downloads so that it becomes a one-stop-shop for all things downloads.  I recommend something like folders (releases, beta).  The beta folder would contain similar or the same as what we had on bintray and releases would be our current production releases (or a link to https://github.com/opensourcepos/opensourcepos/releases)

**Comment by WebShells** [comment]
We should list it on a specific page or link from website to increase traffic also and keep latest releases in sync...

**Comment by jekkos** [comment]
Pushing to the release page is also an option. But then we should indeed have the ability to distinguish between stable and unstable,

**Comment by daN4cat** [comment]
@jekkos if there is no option to structure it, it will get messy.

**Comment by jekkos** [comment]
I had a quick look and don't think there is one.

**Comment by objecttothis** [comment]
Then I think we should use that space as a straight replacement for bintray and use the current releases section for what it is now.

**Comment by jekkos** [comment]
It seems that the rate limitation was removed. I could also look into the bintray api to see how I can delete the oldest artifact after pushing another one.

**Comment by daN4cat** [comment]
I would stick to GitHub and end of the story. One environment would do.

**Comment by objecttothis** [comment]
Agreed. Bintray seems to have a problem with getting the account back up in timely manner when there is a problem.

**Comment by WebShells** [comment]
True, any would work if we don't face same problem again :/

**Comment by mckaygerhard** [comment]
the option of make tarball release are not so great conriderating the amount of commits here!

a note..  i understand that a specific and very configured platform for deploy are great, but why chose those options so complicated and limited integrated? why not gitlab with all needs? i dont understand why the human are the only live organish that likes complicated things, why not just keep in simple ? but well .. 

Well, it was just my opinion that agrees with those of the people who created a github account only to post and be forgotten... noting how complicated it is to generate the publishing artifacts in offline mode after cloning the repository.

**Comment by WebShells** [comment]
Brace yourselves lol :D

**Comment by jekkos** [comment]
Ok I think it's nicer to keep in github indeed, I'm only a bit worried that the repository size might grow too much. Once you fetch all remote branches there will be quite a lot to download if we push snapshots like this. 

But I could solve this by removing the date identifier in the filename and keep only the branch name in the filename and it then overwrite after every push. The date of the build will still be visible in git itself then.

**Comment by objecttothis** [comment]
I agree on keeping just one download for each branch.  The file should have a timestamp on it anyway.  If a commit needs to be reverted it won't be from these builds anyway, so other than being able to test older builds of a branch to see where bugs entered into the branch, there isn't much benefit to having more than one file per branch.

**Comment by SteveIreland** [comment]
I also vote to keep only the last build of a branch changed by a pull request.  I usually keep the last 2 or 3 builds of a branch I am working on in case I need to test "what was".  I have never had to pull an earlier version of a branch build (except, of course, the major releases).

**Comment by daN4cat** [comment]
If the concern is the binary size and github storage explosion, one could wonder why we don't keep the full code in place and you just click download as a zip button...
In that way you keep history and save on space storing just the code change.

**Comment by jekkos** [comment]
because then you'll be bothered having to merge minified files . Having build output under vcs is a nogo for me.

**Comment by daN4cat** [comment]
Unless we force an overwrite.

Anyway, let's move o  with what we have because I don't want to make it a sticky point.

**Comment by jekkos** [comment]
Bintray unlocked the account again, they added 2 more gigabytes to the repository. I will revert for now and probably add an api call to delete the oldest version after pushing a new one.

**Comment by jekkos** [comment]
Latest master can be found on [this link](https://bintray.com/beta/#/jekkos/opensourcepos/opensourcepos/3.3.0?tab=files)
