### ISSUE TITLE
demo site is showing blank page after login

### ISSUE THREAD

**Issue by gauravpolekar** [opensourcepos/opensourcepos#2473]
On demo site
https://demo.opensourcepos.org/ 

After login with admin / pointofsale

It is redirecting to blank page.

**Comment by daN4cat** [comment]
Right, it looks like there is a white page issue today...

**Comment by jekkos** [comment]
Will check tomorrow, no computer in my surroundings now

**Comment by odiea** [comment]
It works if after you login replace login with home on the address bar.

**Comment by odiea** [comment]
I changed the language to english us and it appears to be working properly now.
