### ISSUE TITLE
Supplier doesn't autofill in Expenses module

### ISSUE THREAD

**Issue by Tbwan** [opensourcepos/opensourcepos#2477]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.2.19
- MySQL or MariaDB version is: 5.7.26
- OS and version is: Ubuntu 18.04.01
- WebServer is: LAMP
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I think this was previously reported, (but not well) in issue #2459. It seems to me to be a bug. On a fresh install of OSPOS 3.2.3, I'm encountering an issue when creating a new Expense listing. The supplier field does not autofill. It also does not contain the text that it should, i.e. "Start typing Supplier's name..." 

It does work perfectly in the demo at https://demo.opensourcepos.org, but not on a fresh install on my machine. The demo is listed at 3.3.0 3f9b8c, but the most current stable release here appears to be 3.2.3 4f5ad57.

Can someone point me to where the autofill code should be for this field, and/or help fix this issue?

Thanks so much!

**Comment by odiea** [comment]
Unfortunately Bintray is down so the current master is not available. It does work in 3.3.0. You may have to wait until the Bintray issue is taken care of.

**Comment by odiea** [comment]
If you are brave you can try and cherry pic the following commit.
https://github.com/opensourcepos/opensourcepos/commit/e9c192f70b60a3a88bc84062119d29954abae73c

**Comment by Tbwan** [comment]
I looked into that commit, and have replaced the following files with no visible or functional change to the field:
application/controllers/Expenses.php
application/language/en-US/expenses_lang.php (the language it's set up in)
application/models/Expense.php
application/views/expenses/form.php
 public/css/bootstrap.autocomplete.css

I avoided using the migrations files but am looking at them.

**Comment by odiea** [comment]
You have to do the database files to get it to work. You can try installing them with phpmyadmin if you have it.

**Comment by Tbwan** [comment]
alas, it broke the database. I'll have to wait for bintray to be fixed I guess

**Comment by odiea** [comment]
The current unstable Master is now available for download. 
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20190704173621.master.7da7c0.zip

**Comment by jekkos** [comment]
This works in current master. Check out the bintray builds (they are back now). Will close for now.
