### ISSUE TITLE
receipt

### ISSUE THREAD

**Issue by jamrogers** [opensourcepos/opensourcepos#2478]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3 - 4f5ad57.
- OSPOS git commit hash is: 
- PHP version is: 
7.0.33-0+deb9u3
- MySQL version is: 
 5.0.12
- OS and version is: 
Raspbian 9.8 on armv7l
- WebServer is: 
Apache/2.4.25 (Raspbian)
- Selected language is: 
english

### Issue / Bug  

not sure if it is an issue or a bug....
when a user performs a sale - clicks add payment - clicks complete
the receipt fails to display and thus cant be printed unless the user has the sales-stock permission ticked in employee setup.
if the sales stock permission is ticked it displays and i can print ok.

im not sure if this is intended behaviour - but it seems that if you are allowed to process a sale you should be able to print a receipt?

im using chromium web browser Version 72.0.3626.121

**Comment by jamrogers** [comment]
I should mention that upon completing the sale the user is correctly redirected to public/sales/complete but it is shown as a blank page.

**Comment by jekkos** [comment]
Ok do you have any stacktrace for this issue? Blank page is mostly an indication that there was an error (but the details were hidden as you are probably in production mode).

**Comment by jekkos** [comment]
Also maybe try to make the issue title a bit more descriptive next time you create something.

**Comment by jamrogers** [comment]
Apologies, how do I do a stack trace?  I am usually work with asp.net, Do you mean the apache error log?

**Comment by jekkos** [comment]
like an error or sth. You should switch the setup to development mode to see why you get a blank page.

**Comment by daN4cat** [comment]
No follow up, I close.
