### ISSUE TITLE
Hi there! The employee management module is not working well: I am unable to create, update or delete an employee. Also, the default employee cannot access the items module. Please, help me settle these issues.

### ISSUE THREAD

**Issue by Yasaph** [opensourcepos/opensourcepos#2483]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
And the required info for the Issue template is where?

**Comment by Yasaph** [comment]
Here are the infos:

OSPOS version is: 3.2.3
PHP version is: Version 7.3.4
MySQL or MariaDB version is: MySQL
OS and version is: Windows 10 version 1803
WebServer is: Apache
Selected language is: french

Please,help me!

**Comment by odiea** [comment]
I do not believe that 3.2.3 would work propwerly with that high of php. Try php 5.6 and see if that changes anything.

**Comment by Yasaph** [comment]
Alright thanks!

**Comment by Yasaph** [comment]
Hi. Please, by the way, I want to be able to select the date for sales operations. How can I implement that?

**Comment by daN4cat** [comment]
Can you explain in more detail what you mean with that?

**Comment by Yasaph** [comment]
I mean the possibility to enter past sales into the application: in that case the employee will need to choose the date of those sales.

**Comment by daN4cat** [comment]
Gets very complicated because it has an impact on cashups. You can't fix the past of that part.

**Comment by Yasaph** [comment]
Ok. And by the way, I don't see the cashups module on dashboard for version 3.2.3.

**Comment by daN4cat** [comment]
That's in 3.3.0

**Comment by Yasaph** [comment]
Ok. Is it possible to integrate that module for that version?

**Comment by WebShells** [comment]
Adding it specifically would take you some time but updating the whole project can be done and db will be migrated to the new version, but 3.3.0 isnt officially released yet still in development phase...

**Comment by odiea** [comment]
The current unstable 3.3.0 Master is now available for download and it does contain the Cashup module..
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20190704173621.master.7da7c0.zip

**Comment by Yasaph** [comment]
Alright, thanks guy.

**Comment by Yasaph** [comment]
Hi there. Sorry for disturbing. All of a sudden, I am no more able to access the articles modules. It says 'I am no right to access the articles modules. Help, please; I am just a novice.
