### ISSUE TITLE
Restaurant tables

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2491]
I started using restaurant tables.

With 8 tables. I wanted to work in the following way.
Every time a table asks for something, just add it to the car and suspend the sale, because if they want to ask for more, I only restore the sale, add more to the car and suspend it again until the sale is completed.

I have the following problems, if I cancel the whole order of a table, I will clear the table number and I have not found a way to restore it again. I keep doing it in all the tables, I lose them all.

**Comment by andriux1990** [comment]
![Screenshot_20190712-110545_Chrome](https://user-images.githubusercontent.com/29256343/61145743-73b78480-a495-11e9-8b0f-d4b327815744.png)

![Screenshot_20190712-110715_Chrome](https://user-images.githubusercontent.com/29256343/61145761-7d40ec80-a495-11e9-81fe-fbe043b3870d.png)

**Comment by WebShells** [comment]
That's your problem i guess 😂

**Comment by andriux1990** [comment]
@WebShells Sure, it's a problem of mine, and I'm trying to solve it. But it is a limitation of ospos. You can see it in the ospos demo and therefore it concerns all

**Comment by daN4cat** [comment]
@andriux1990 do you sell drugs in your restaurant? I'm confused....

**Comment by andriux1990** [comment]
Oh my God!
I'm sorry for my bad translation, I express myself badly

**Comment by WebShells** [comment]
It's fine 😂 am still trying to find an issue for us to worry about... You can simply NOT cancel the table... Can you please rephrase your problem?

**Comment by daN4cat** [comment]
In one case you talk about drugs (gotas nasales), here table in a restaurant... 🤔

**Comment by andriux1990** [comment]
I do not have any restaurant, I just gave you an example that the function for restaurant tables is defective

**Comment by odiea** [comment]
He is correct on his issue. Enable dinner tables. Create a sale for a table. Suspend it. Unsuspend it. Then Cancel the Sale. It is not changing the Table status back to 0 in dinner_tables so that the Table can be used again.
![2019-07-12 12_22_16-localhost _ MySQL _ ospos3 _ ospos_dinner_tables _ phpMyAdmin 4 7 9](https://user-images.githubusercontent.com/10962177/61150074-c39b4900-a49f-11e9-95da-40d075069ea9.png)

**Comment by daN4cat** [comment]
Right... that feature was contributed a while back by somebody but never looked after properly.
I don't have personal motivation to spend time in this.
In my opinion there should be another view dedicated to restaurant needs.

**Comment by andriux1990** [comment]
![IMG-20190712-WA0003](https://user-images.githubusercontent.com/29256343/61150070-c1d18580-a49f-11e9-9719-f56cc499e71b.jpg)
I have 5 tables, but the problem is that tables T3 and T4 disappeared in the sales module
![IMG-20190712-WA0004](https://user-images.githubusercontent.com/29256343/61150353-7d92b500-a4a0-11e9-8c26-1873de48d220.jpg)

**Comment by daN4cat** [comment]
Time to dig out the bug guys...

**Comment by WebShells** [comment]
Alright got it now... Sorry for not getting you the right way... Personally never used restaurant tables, but i agree with @daN4cat more preferred to load a different view for restaurant including printing modules for different categories and other features, although i dont think it is what we are aiming for OSPOS...
Or else huge load of work is waiting for us... Recipes, ingredients, stock units...

**Comment by odiea** [comment]
I probably have this in the wrong place but it is working for me.
```
public function cancel()
	{
		$sale_id = $this->sale_lib->get_sale_id();
		$dinner_table_id = $this->sale_lib->get_dinner_table();
		if($sale_id != -1 && $sale_id != '')
		{
			$sale_type = $this->sale_lib->get_sale_type();
			if($sale_type == SALE_TYPE_WORK_ORDER)
			{
				$this->Sale->update_sale_status($sale_id, CANCELED);
			}
			else
			{							
				if($dinner_table_id > 0)
				{
					$this->db->update('dinner_tables', array('status' => 0));
				}
				$this->Sale->delete($sale_id, FALSE);
				$this->session->set_userdata('sale_id', -1);
			}
		}
		else
		{
			$this->sale_lib->remove_temp_items();
		}

		$this->sale_lib->clear_all();
		$this->_reload();
	}
```

**Comment by andriux1990** [comment]
thank you @odiea  also works for me

**Comment by odiea** [comment]
I removed it because it appeared to clear all the table statuses. So you may have to unsuspend  then re suspended the tables again so it shows the tables are not available.

**Comment by odiea** [comment]
This is a little more refined. It only changes the status on the sale that is being cancelled.
```
public function cancel()
	{
		$sale_id = $this->sale_lib->get_sale_id();
		$dinner_table_id = $this->sale_lib->get_dinner_table($sale_id);
		if($sale_id != -1 && $sale_id != '')
		{
			$sale_type = $this->sale_lib->get_sale_type();
			if($sale_type == SALE_TYPE_WORK_ORDER)
			{
				$this->Sale->update_sale_status($sale_id, CANCELED);
			}
			else
			{
				if($dinner_table_id > 0)
				{
				$this->Sale->delete_suspended_sale($sale_id);
				}
				$this->Sale->delete($sale_id, FALSE);
				$this->session->set_userdata('sale_id', -1);						
			}
		}
		else
		{
			$this->sale_lib->remove_temp_items();
		}

		$this->sale_lib->clear_all();
		$this->_reload();
	}
```

**Comment by andriux1990** [comment]
Thanks for your help. works very well

**Comment by andriux1990** [comment]
what can be done so that when a sale that has been suspended in table 4 is resumed, for example, it loads in table 4. since by default it always puts the first table

**Comment by odiea** [comment]
It does appear to load that table but the drop down just shows the First table after a reload.

**Comment by andriux1990** [comment]
It's true, but after so many times someone could get lost and not know which table is

**Comment by odiea** [comment]
I am not a programmer so the only thing I can offer is a bandaid for the register. In application/views/sales/Register.php after line 42 add the following. This will show the current table in use next to the drop down.
```
    <li class="pull-left">
    <label class="control-label"><?php echo $this->lang->line('sales_table'). ' '.$selected_table ; ?><label>
   </li>
```
![2019-07-13 10_45_57-Odies Test _ Powered by OSPOS 3 3 0](https://user-images.githubusercontent.com/10962177/61174304-79779d80-a55b-11e9-950e-4eece972bae0.png)

**Comment by andriux1990** [comment]
it works thank you @odiea

**Comment by daN4cat** [comment]
Is there any code to fix in 3.3.0 to get this to work fine? I see this got closed.

**Comment by odiea** [comment]
Only if you want to copy and paste the code I submitted for this.

**Comment by WebShells** [comment]
@odeia it will show current table being used and after suspension will it release the tables list back? 🤔 Or what

**Comment by odiea** [comment]
That is what it appeared to do. The main issue was trying to Cancel a suspended Table.

**Comment by SteveIreland** [comment]
I like easy ones .... especially if a solution is already available ... if no one jumps on this before I do then I'll be happy to permanentize the solution provided by @odiea.

**Comment by WebShells** [comment]
We go for it then if all seems ok with it 👍 Personally i have no problem...

**Comment by daN4cat** [comment]
Go for it and thanks for the help.

**Comment by SteveIreland** [comment]
Downloaded the latest master from bintray and noticed that the new items I set up were not being listed in the table. But since they were being created properly in the database I proceeded to work on this issue.

I wanted to confirm the issue still existed and did manage to confirm that there was a problem and I'm working on fixing that particular issue.  

As I understand the rules, the app should automatically flag the table as occupied when the first item that is added to the sale (the sale that the table is assigned to) .  When the sale is suspended the table remains occupied and it should remain flagged as occupied until either the sale is canceled or completed.  It appears that a third way that the table can become "empty" is if all of the items on the register are removed.

Like others I've never used this feature but those are the rules I will be implementing in this effort.  If I'm wrong on any of these points please let me know.

**Comment by SteveIreland** [comment]
A pull request has been submitted for this issue.

The selected table isn't flagged as occupied until the order is first suspended.

As noted in the previous post, the table stays occupied until  the sale is canceled or completed.

Cancelling or completing the sale will release the table.

I added the ability to swap tables which will release the previous table and flag the new one as occupied (although the swap only happens if a table has already been flagged as occupied (i.e. the sale had been suspended).

**Comment by odiea** [comment]
It would be best if someone else who uses this feature would download the dinner table fix in Bintray for more testing. Currently @SteveIreland has done a great job doing the necessary repairs on this feature.

**Comment by SteveIreland** [comment]
It's been merged.   If someone finds an issue please let me know.

**Comment by odiea** [comment]
@daN4cat . You mentioned tables should have it's own View. Would it be as simple as copying the current register then rename it dinner_table. Then remove Dinner tables from the current register view. Then adding the new view to the sales controller?

**Comment by SteveIreland** [comment]
I think the intent of the new view is to make it look a lot closer to what current restaurant POS systems have.  Item selection would be more "food menu" oriented and  stuff like that.
