### ISSUE TITLE
Having a New Module that acts the same as Cashup module, but for Customers Balance

### ISSUE THREAD

**Issue by engehab87** [opensourcepos/opensourcepos#2492]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 7
- MySQL or MariaDB version is: 4.7.4
- OS and version is: Windows
- WebServer is: Xampp
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

i want to create a New Module to be a similar as Cashup Module, but serving the Customers Balance. it will act the same as Cashup in adding each transaction the customer does since the invoice is issued under his name. the page will display all the customers with Balance and clicking on the customer, all the payments will show up along with the remaining for him or due on him.

i don't know how to do it in OSPOS, anyone could help ?

**Comment by engehab87** [comment]
i don't know how to do it in OSPOS, anyone could help ?

**Comment by WebShells** [comment]
Hello @engehab87 actually it's very different than what we are currently suggesting for the customer balance and spent amount... So you might either need to wait or try to apply the changes yourself 🤷‍♂️

**Comment by engehab87** [comment]
Actually I'm trying to do it myself, but I'm not able to do it. Been
working on it for a while but don't know where is the issue.

I will be waiting for the result then from what you are working on.
