### ISSUE TITLE
After Installing, to navigate to the app 

### ISSUE THREAD

**Issue by Akosile2000** [opensourcepos/opensourcepos#2494]
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

This is the error am getting

**Comment by odiea** [comment]
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20190714124155.master.fa71bc.zip

**Comment by Akosile2000** [comment]
I should download this right

**Comment by odiea** [comment]
Yes. This should work as expected.

**Comment by Akosile2000** [comment]
Okay
Have download it can you send the install procedures

**Comment by Akosile2000** [comment]
Sorry for disturbing...Just that this setup has been giving error since yesterday

**Comment by odiea** [comment]
https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md

**Comment by Akosile2000** [comment]
Modify application/config/config.php encryption key with your own

I dont understand this 
Can you explain please

**Comment by odiea** [comment]
Ignore it. It will create an encryption key for you.

**Comment by SteveIreland** [comment]
It will?  I didn't know that!  :-)

**Comment by Akosile2000** [comment]
The installation is not correct, check your php.ini file.
A database migration to 3.3.0 will start after login.

That's the error am getting now ...I cant login

**Comment by Akosile2000** [comment]
Please what can I do

**Comment by odiea** [comment]
Read

**Comment by Akosile2000** [comment]
Read what?

**Comment by Akosile2000** [comment]
The installation is not correct, check your php.ini file.
A database migration to 3.3.0 will start after login.

How do I resolve this

**Comment by Akosile2000** [comment]
Please are you there?

**Comment by WebShells** [comment]
@Akosile2000 that's normal at first login for migration to happen... Please go through previos issues...

**Comment by Akosile2000** [comment]
Sorry please which previous issues

**Comment by Akosile2000** [comment]
I can't locate  the php.ini file sef

**Comment by odiea** [comment]
Read the wiki and the issues. Plus you should have read the Issue template. It applies to everyone.

**Comment by Akosile2000** [comment]
Yeahhhhhh
But how can I solve it 
You should have a solution to the issue na

**Comment by Akosile2000** [comment]
Have tried reading through Wiki.... I can't see the solution

**Comment by daN4cat** [comment]
@Akosile2000 this is not an application that gets installed if you don't have prior knowledge of how to deal with your system and php based applications.
If you want the Google Play click and install experience I would suggest to consider buying a SaaS POS solution
OR
do a bit of homework and learn how to install php applications, deal with web server config and etc.

**Comment by daN4cat** [comment]
@SteveIreland yes, at the time I implemented a self key generation and save feature.
Due to the fact it's important to have one, if you don't know what to do and don't touch that entry in config.php OSPOS will do for you the first time.

**Comment by Akosile2000** [comment]
Okay
Nobody can help me further now

**Comment by odiea** [comment]
Not if you can't help yourself

**Comment by Akosile2000** [comment]
Okay 
Thanks man 
Have finally login

**Comment by WebShells** [comment]
Will close..

**Comment by daN4cat** [comment]
Good good, you found your way.
