### ISSUE TITLE
Current Demo is not displaying the Items Table.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2497]
OSPOS Installation Info: 3.3.0 - 0491c1
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache/2.4.25 (Debian)
.PHP Version: 7.2.18
.DB Version: 5.5.5-10.1.21-MariaDB-1~jessie
.Server Port: 80
.OS: Linux b3a59db8ede2 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64

File Permissions:
» [application/logs:] - 0775 | Writable ✓ 
» [public/uploads:] - 0755 | Writable ✓ 
» [public/uploads/item_pics:] - 0775 | Writable ✓ 
» [import_customers.csv:] - 0664 | Not Writable ✗

**Comment by odiea** [comment]
They will show after empty barcodes filter is selected

**Comment by SteveIreland** [comment]
What's the secret for displaying items with barcodes?

**Comment by odiea** [comment]
For some reason I think it may be relayed to the language or locale.

**Comment by SteveIreland** [comment]
I don't believe that language or locale has anything to do with it.

I took a cue from you and started playing with the filters.

When I select today's date or any date range the items started appearing again.

So it appears to be an issue with the initialization of the date filter.

**Comment by daN4cat** [comment]
The date filter was touched with the date attribute change. Worth checking if that introduced a regression.

**Comment by ronaldhuynen** [comment]
Hi, it seems I have an isssue related to this.

I'm using 3.3.0 - fa71bc with a database migrated from 3.2.3. Here too the item list is (partly) empty. New items are not displayed. Even when I switch the filter for empty barcodes on. I've tested all fillter settings (date ranges, locations, etc) without any result.

As soon as I create or update an item from within the Items module, the item will not be listed anymore in the items list. Also I get no confirmation popup and the create/update window does not close. It looks like if nothing happened, and when I close the new/update item window manually, the new entry is not listed (anymore) in the item list of the Item module. 

However the entry in the items and inventory table of the database is created and updated properly as soon as I hit the 'new' or 'update' button. Also this new/updated database entry looks 100% similar to other items that are listed ok within my item module. 

From the Sale module, everything works fine: all items can be searched and sold, new items can be created. The new items created from within the Sale module, are also shown correctly in the Items module. 

I need to note that SOMETIMES everything works ok in the Items module, and I still can't discover what the pattern is when it fails or works. Different browser makes no difference. 

To me it looks like the table filter of the items module has some problems.

**Comment by odiea** [comment]
Can anyone find when this build was committed. OSPOS Installation Info: 3.3.0 - 0491c1. I do not see it in bintray.

**Comment by daN4cat** [comment]
@ronaldhuynen how many stock locations do you have?

Have you manually created entries in the database in the past?

**Comment by daN4cat** [comment]
@odiea if you use a git client you should see an hash code for each commit. The final part is the code you see in OSPOS.

**Comment by odiea** [comment]
It appears this was committed on June 16 2019. With all the current changes I believe a newer branch should be put up for the demo.

**Comment by ronaldhuynen** [comment]
Sorry I'm new to Git and I'm also no developer - but happy to test.

@daN4cat, I have 3 stock locations. I did change some values manually in my database. But only simple vaue changes, no extra rows / columns / constrains etc. 

But now I've found probably the root of my issue. For testing I now also installed the latest master from Bintray ( 3.3.0 - ac6d5e, 2 days old ) and used a new and clean database. 

Then everything worked ok. I've succesfullyu created and updated 6 or more different items.  But after I created an Attribute Decimal type, the Item list module was completely empty. When switching off the visibility of this Attribute Decimal type for the Item module (by updating this attribute in the Attribute module). the Item lists module has all the items back again. The Sales and Receivings options can be set to visible without any problems. Also the reports will then show the attribute correctly. 

I never created an Attribute DATE type on my own fresh install.  Therefore I tried to switch off the visibility of the attributes of the Demo site: TEXT and DATE type. There's no DECIMAL (yet). However that did not solve the problem with the empty list of the Item module.

**Comment by andriux1990** [comment]
I also did tests and it is caused by the attributes in my case I have the text attributes

**Comment by daN4cat** [comment]
@ronaldhuynen have you tested with latest code in master, it appears to me that @jekkos fixed something about attribute query.

**Comment by jekkos** [comment]
@ronaldhuynen Is the issue resolved now? Could you do a check so we can close. Thx!

**Comment by ronaldhuynen** [comment]
@jekkos Yes your latest fix works on my setup. I installed 20190806222050.master.8bca8f from the bintray with a new database. Decimal and text attributes work fine now. See my comment on #2485.

**Comment by Hamzaqureshi401** [comment]
i also have the same problem i migrated 3.2.3 to 3.3.0 in item tables i could not see my items 
![image](https://user-images.githubusercontent.com/46222436/62822226-f1a4a380-bb99-11e9-8c15-0288d862dc7c.png)

**Comment by Hamzaqureshi401** [comment]
is anybody resolve it?

**Comment by jekkos** [comment]
I see you have multiple stock locations as well. I'll have to look into that.

**Comment by Hamzaqureshi401** [comment]
> I see you have multiple stock locations as well. I'll have to look into that.

yes i have and also selected different stock location but it shows nothing first of all i created new product the popup saya product generated but it is not shown 
![image](https://user-images.githubusercontent.com/46222436/62830839-cae47c80-bc2e-11e9-8eb8-5cd80e854dc1.png)

**Comment by odiea** [comment]
Looks like the Demo is ok today so I close this issue
