### ISSUE TITLE
Install ospos Windows

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2498]
I'm trying to install ospos on Windows
all separately as it is done in Linux, in Linux it is very easy just install apache2, PHP and its modules and mariadb and voila.
In Windows I want to do it in the same way without programs that already contain everything such as wampserver and xampp
because wampserver is very slow compared to Linux.
and I think it's more professional and practical because I would only install what I need.
If anyone knows how to do it, I would greatly appreciate it.

I have been able to install apache2, PHP and mariadb without any problem but I get it to boot ospos

**Comment by daN4cat** [comment]
I would say..... buy a Raspberry Pi and it will be faster and cheaper than a Windows laptop.

**Comment by andriux1990** [comment]
I have thought about that, in fact I want the raspberry pi 4 but it has problems, I also have a Windows computer and I want to do it to learn, I like to do it the hard way, since wampserver is easy. and I don't want to depend on such a program.

But I have tried for 3 days and I have not succeeded, so I ask for help.

**Comment by odiea** [comment]
Create a linux server virtual machine on your windows pc?

**Comment by daN4cat** [comment]
You can run on Raspberry Pi 3 no problem. It's all down to the speed of disk you use in the end when it comes to access the database.

**Comment by SteveIreland** [comment]
I use Windows and started off installing the individual components but then flipped over to WampServer simply because it provides a lot of flexibility regarding swapping out different versions of individual components.  I've never noticed any degradation in performance due to Wampserver.  All it does is install the necessary components.

**Comment by andriux1990** [comment]
Thanks for the suggestions and comments. In the end use the virtual machine.
