### ISSUE TITLE
[Question] why do we multiply 'quantity' and 'receiving_quantity on receiving model

### ISSUE THREAD

**Issue by waploaj** [opensourcepos/opensourcepos#2500]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 5.8
- OS and version is: linux ubuntu 19
- WebServer is: xammp
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hello; i would like to know on receiving model, when we update stock quantity  on model>receiving.php line 104

			[$items_received = $item['receiving_quantity'] != 0 ? $item['quantity'] * $item['receiving_quantity'] : $item['quantity'];](url)
why do we multiply purchased_quantity and receiving quantity also why is receiving quantity is = 1, on ospos_receiving table

**Comment by odiea** [comment]
Because when you multiply the receiving quantity by 0 you do not get the correct result.

**Comment by odiea** [comment]
Receiving qty was and may still be a multiplier

**Comment by waploaj** [comment]
so in a case of return an item we

> Because when you multiply the receiving quantity by 0 you do not get the correct result.

what am asking is if i change 
`
			$items_received = $item['receiving_quantity'] != 0 ? $item['quantity'] * $item['receiving_quantity'] : $item['quantity'];`
 to 
`
			$items_received = $item['receiving_quantity'] != 0 ? $item['quantity'] : $item['quantity'];`
is it the same thing?

**Comment by odiea** [comment]
All you can do is try it and see what happens.

**Comment by odiea** [comment]
Just check your inventory levels and see how the sales at the register look.

**Comment by SteveIreland** [comment]
The receiving quantity is reflects how many units of the received item is to be added to inventory.  If you change the system and try to put 0 in the receiving quantity then you've broken the system and it won't behave properly.  Receiving quantity cannot be zero.

**Comment by odiea** [comment]
They learn by their mistakes.
