### ISSUE TITLE
Error: Unable to load the requested file

### ISSUE THREAD

**Issue by w002qaa** [opensourcepos/opensourcepos#2503]
Hello Everyone,

I am using OSPOS v3.2.3. I did modified some line in the code. Suddenly, I got an error after I clicked the complete sale button. 

> An Error Was Encountered
> Unable to load the requested file: sales/.php

Is any way to debug the error?

**Comment by odiea** [comment]
What is the name of this mysterious .php that appears to be missing. It should say receipt.php or default_receipt.php

**Comment by w002qaa** [comment]
Hi @odiea 
I got the problem. In table _ospos_app_config_  the receipt_default was empty, and that cause the problem.

Thanks
