### ISSUE TITLE
[Question] What does column "line" in tables of sale_item and sales_items_taxes meaning

### ISSUE THREAD

**Issue by waploaj** [opensourcepos/opensourcepos#2504]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.2
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 5.8
- OS and version is: linux
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hello guys i would like to understand what is the purpose of the column "line" in sale_items and sales_items_taxes table, how it works

**Comment by SteveIreland** [comment]
Line is part of the composite key to uniquely identify an entry on the sales_item table.   If the same item is added multiple times to a sale then the line number is incremented.   An item can be added two or more times to an order if the item sale includes serial number tracking.

Hopefully I've provided a clue as to why the line number exists.  It could probably be better named, but that is what it does.

**Comment by daN4cat** [comment]
Is 3.2.2 really working with PHP 7.2?

**Comment by waploaj** [comment]
> Is 3.2.2 really working with PHP 7.2?
> 
> Also I assume MySQL 5.8 is MySQL 8 as they skipped from 5.7 to version 8.
> Again wondering if 3.2.2 works fine with MySQL 8 because we never tested it.

Yes but when i insert stock_location on db manually sometimes wont work well, sometimes even when i assign an employee permission it shows a message that "You have successfully updated employee" , but it does not give that permission on a user unless i insert on web stock_location one by one which is kind of annoying consider i have 42 stock_location.

**Comment by odiea** [comment]
Are you using your suppliers as a stock location.

**Comment by waploaj** [comment]
> Are you using your suppliers as a stock location.

no am not using suppliers as a stock location.
 English is not my mother tongue; please excuse any errors on my part.

**Comment by odiea** [comment]
It just appears to be an overwhelming amount of locations.

**Comment by waploaj** [comment]
> It just appears to be an overwhelming amount of locations.

so what is the limit of location

**Comment by odiea** [comment]
There is not any. But unless you manually edit out Items from each location it should have your full Inventory stored in each location. It just seems like a lot of overhead. But I may be wrong.
