### ISSUE TITLE
Please rekindle the proposed Purchase order development per #1479

### ISSUE THREAD

**Issue by scottie01** [opensourcepos/opensourcepos#2505]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: I don't know how to view this sorry
- PHP version is: 3.7.1
- MySQL or MariaDB version is: MySQL 5.7.24
- OS and version is: Window 10 64 viewing 
- WebServer is: DigitalOcean Droplet Ubuntu 18.04
- Selected language is: En US
- (If applicable) Docker installation: Unsure if I have Docker pre-installed on Droplet?
- (If applicable) Installation package for the LAMP/LEMP stack is:  LAMP as per installation instructions.

### Issue / Bug  / Question / New Feature

New Feature _Re-Kindle request_.

#SteveIreland has developed the existing workorder module which I am currently using with negative quantity and no pricing option to create purchase orders. Once my staff have created the purchase order in this manner I am able to authorise these by selecting Unsuspend from the suspended sales. This does give me some better insight into what stock my staff need and once I complete the negative sale it does update the stock level correctly like the receiving module. Unfortunately the are flaws though.... the sales (including negative) reports are in retail pricing so no markup is shown. Suppliers are not selectable from the workorder sales screen so either duplicate suppliers need to be added to the customer list or in my case I have no supplier list and just have the suppliers in the customer list with *Supplier* prepended to there name for searchablity. This inturn means none of the supplier reports can be populated.

#SteveIreland's wiki [https://github.com/opensourcepos/opensourcepos/wiki/Purchasing] Describes a much properly thought through solution which I believe would add great value and resolve all of the issues relating to miss-using the work order module to create purchase orders.
In my business (tyre shop) purchase orders are critical control documents. We cannot do business without them.

Kindest regards, and many many thanks for all your hard work developing such a great app.
Scott

**Comment by SteveIreland** [comment]
My focus at the moment is on learning Laravel but what I can do is use the purchasing system as a learning project.  So I will implement the purchasing system in Laravel and then you can decide if you want to use it.  I think that would make @jekkos happy because then he doesn't have another module to support in OSPOS should I have a heart attack.

I've just about finished my prep work and will be incorporating GraphQL (suggested by @daN4cat)
 and using Vue.js as the front end.  So I'm excited and motivated  which means that there is a good chance that I will actually complete the effort.

**Comment by scottie01** [comment]
Thankyou, I have to say pretty much all of what you said went over my head. Lol.
it sounds like you're going to work on a solution but it'll be outside OSPOS? Will it be seemless to the end user operable from within OSPOS? As a practicle measure I've standardised my markup so I can have my suppliers (In customers) with a pre defined discount back to cost pricing which seems to resolve my reporting issue where I wasn't able to access cost price supplies. I'm using the unsuspend to authorise and receive goods into stock from work/purchase orders. It's rude/ugly but it works.
Thanks heaps for your willingness to pick back up the purchasing system. I for one really appreciate it as we don't hold much stock so we're constantly making purchase orders to suppliers for pre sold work. Kindest regards, Scott
