### ISSUE TITLE
User log [Question]

### ISSUE THREAD

**Issue by esturniolo** [opensourcepos/opensourcepos#2506]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.2.19
- MySQL or MariaDB version is: mysql  Ver 14.14 Distrib 5.7.27
- OS and version is: Ubuntu 18.04 LTS
- WebServer is: Apache/2.4.29
- Selected language is: English
- (If applicable) Docker installation: N/A
- (If applicable) Installation package for the LAMP/LEMP stack is: N/A

### Question
Hi guys.
I searched into wiki and Issues and can´t find this.
There is a way to get a user log?
(i.e.) I have 50 pencils in stock and the user ABC made a sale for 10 pencils.
Then, the same user ABC modify manually the stock and set the new value in 30 pencils. 
So now I´ve lost 10 pencils...

There is a log for who made what in the modules?
Doesn´t matter if that log is stored somewhere in the server and not in the Web GUI.

Thanks for all your effort!!

**Comment by daN4cat** [comment]
Yes, in items select the icon on the right with inventory feature and you will get the transaction history.

**Comment by esturniolo** [comment]
Great!!!! I see it now!
Thanks @daN4cat
