### ISSUE TITLE
Custom report using custom attribute

### ISSUE THREAD

**Issue by ashkaps** [opensourcepos/opensourcepos#2511]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [y] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [y] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [y] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [y] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [na] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [y] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question

Is there an option in ospos to create custom report off of a custom attribute like a data field?
Ideally i am looking for alert on re-bill. My services required re-billing monthly and since all customers start at a different datetime, this feature would save a lot of time if it is already there.

**Comment by SteveIreland** [comment]
It’s not built in to OSPOS but I used Reportico for the custom reports I needed.  There are other tools

**Comment by ashkaps** [comment]
Appreciate your quick response. Thanks! So connect the db directly to a thirdparty tool? How can I achieve that? Is there a doc i can refer?

**Comment by jekkos** [comment]
I think you're mostly on your own here. You can just use plain SQL for any purpose, or connect it to other tools that allow you to visualize the data.

**Comment by ashkaps** [comment]
Sounds good. One last question. Is there an inbuilt dashboard I can use mysql on?
