### ISSUE TITLE
Question regarding the item kit behavior

### ISSUE THREAD

**Issue by Hamzaqureshi401** [opensourcepos/opensourcepos#2512]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by WebShells** [comment]
Please fill in issue template in future so we can provide the needed help. 
Those are ingredients and should have 
measurment units also... Alot of improvements on item kits were made by @SteveIreland in 3.2.3 one of them was the kit name and printing options...
To what i remember it's doable.. Didnt test it myself though..

**Comment by SteveIreland** [comment]
**Transferred from the description:**

Item kit loads all the products against kit i want when i enter kit name it should just load item kit example 1 cup contains items qty 3scoops 1 spoon and 1cup and kit name is "Big Cup" in sales it should load just "Big Cup" qty=1 is it possible?

**Comment by SteveIreland** [comment]
What you're asking for isn't supported by OSPOS. 

When selecting a kit all items are added to the order and based on the configuration of the kit, the item kit item will also be added.

Then based on the configuration of the item kit it's possible to only have the item kit item print on the sale and all of its components would NOT print (which is the behavior you want).

The item kit components appear on the order detail so that the inventory reductions for each individual component will take place.

**Comment by WebShells** [comment]
Yes, but he can still print only kit names... Although in reporting and detailed sales it shows the items list.

**Comment by SteveIreland** [comment]
I agree

**Comment by Hamzaqureshi401** [comment]
> Yes, but he can still print only kit names... Although in reporting and detailed sales it shows the items list.

**Comment by Hamzaqureshi401** [comment]
thanks for information
