### ISSUE TITLE
Search Client by account number, phone or email

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2513]
I have many clients with the same name, the only thing that is different is obviously your phone number, email, and account number
![Screenshot_2019-08-10 Open Source Point of Sale Powered by OSPOS 3 3 0](https://user-images.githubusercontent.com/29256343/62825927-dd987c00-bb70-11e9-9f45-51c4175b150e.png)
in the sales module to select a client, just write the name, if there is more than one with the same name, then I look for it by phone number or email and here it is allowed and I love it that way
![DeepinScreenshot_20190810130702](https://user-images.githubusercontent.com/29256343/62825964-55ff3d00-bb71-11e9-9350-3e7605ef4f6a.png)
The problem is in the Reports - Clients module, when I search for a client, I can only search by name. If I write the phone number or email I will not have any results. and when I wanted to see the specific information of a client I couldn't know because I have many clients with the same name
![Screenshot_2019-08-10 Open Source Point of Sale Powered by OSPOS 3 3 0(1)](https://user-images.githubusercontent.com/29256343/62826016-e89fdc00-bb71-11e9-9a36-750337bcff00.png)
![Screenshot_2019-08-10 Open Source Point of Sale Powered by OSPOS 3 3 0(2)](https://user-images.githubusercontent.com/29256343/62826018-ed649000-bb71-11e9-8f64-6781be4c1646.png)

A few months ago they improved the search engine by adding the field to type the name and I liked that.

I was trying to make this possible to search my clients by their account number, phone number and email but I didn't have good results.

I would appreciate the help if anyone knows how to do it. Thank you

**Comment by odiea** [comment]
In application/controllers/reports.php look around line 893. Look at the structure below and add $customer->phone_number and see if this helps you out any. It will not search for it but it should show the phone number.
```
if(isset($customer->company_name))
			{
				$customers[$customer->person_id] = $this->xss_clean($customer->first_name . ' ' . $customer->last_name. ' ' . ' [ '.$customer->company_name.' ] ');
			}
			else
			{
				$customers[$customer->person_id] = $this->xss_clean($customer->first_name . ' ' . $customer->last_name);
			}
```

**Comment by andriux1990** [comment]
thanks @odiea that's fine it works
