### ISSUE TITLE
"The page isn’t redirecting properly" error in firefox & "ERR_TOO_MANY_REDIRECTS" error in chromium

### ISSUE THREAD

**Issue by shankar58989** [opensourcepos/opensourcepos#2514]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: PHP 7.2.3-1ubuntu1 (cli)
- MySQL or MariaDB version is: mysql  Ver 15.1 Distrib 10.1.29-MariaDB
- OS and version is: Linux Mint 19.2
- WebServer is: apache2
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I followed the the steps in https://github.com/opensourcepos/opensourcepos/wiki/Getting-Started-installations#local-deploy-install.

Then I got "Not Found The requested URL /127.0.0.1/public/login was not found on this server" error. I followed the solution provided in "https://github.com/opensourcepos/opensourcepos/issues/920" this link.

Then I got the screen where it asks for username and password. When I enter the username and password I get the below error and i am stuck here.

The page isn’t redirecting properly - in firefox default window
 "ERR_TOO_MANY_REDIRECTS" error in chromium default window

**Comment by jekkos** [comment]
This sounds like an apache problem. Did you enable mod_rewrite ? Also do you have anything else setup except for ospos on the apache?

Maybe first double check if you can access a static file in your document root.

**Comment by shankar58989** [comment]
Hello jekkos, Thanks for the reply and apologies for the late reply. I managed to get it working installing it in the var/www/html folder. 

However I wanted to install it in var/www/html/myospos. The steps I did are. 
* I downloaded and extracted the zip file using the commands that you have in the installation steps. I just added the newly created folder to the download and extraction path. 
* After that I edited the DocumentRoot in the Websites available .config file in etc/apache2. 
* Then I edited the apache.config file also to under the /var/www from Deny to All.
* I edited the .htaccess file from the public folder. I uncommented the subdir and edited the path and I commented out the above root folder line.

After I do this I get this same above "redirect" error. As soon as i enter localhost/myospos/public in the webbrowser, it returns the above error and i can see that the url populates itself with endless /public/public/public....

I am supposing that apache is not reading the index.php file when it is in the sub directory, but is able to read when in the default root directory. is this right? if so your advise much appreciated. Thanks.

**Comment by shankar58989** [comment]
hello guys, 
requesting someone to confirm if my problem is because of apache or something else. it would be fantastic to figure out my problem and to install ospos into a sub directory. thanks.

**Comment by daN4cat** [comment]
Can you copy and paste your .htaccess from the public folder here?

**Comment by shankar58989** [comment]
Hello daN4cat, Thanks for your reply. please find the .htaccess file from the public folder below.
[htaccess.txt](https://github.com/opensourcepos/opensourcepos/files/3577358/htaccess.txt)

**Comment by mckaygerhard** [comment]
@shankar58989 this are due the **very specially complicated htaccess** delete it and make your own index.php redirect.. 

i reported previously in https://github.com/opensourcepos/opensourcepos/issues/1762 but developers assumed all the environments are like they have already... too much apache in fact

**Comment by mckaygerhard** [comment]
@shankar58989 this are due the very specially complicated htaccess delete it and make your own index.php redirect..

i reported previously in #1762 but developers assumed all the environments are like they have already... **too much apache in fact**

a modified no-htaccess ospos will work perfectly and works of course by purgein those "bill gates" windosers htaccess depends files, you must converted using index.php files and the php SERVER array

**Comment by daN4cat** [comment]
@shankar58989 I missed to answer this, is the mod_rewrite module installed on your server?

**Comment by shankar58989** [comment]
> @shankar58989 I missed to answer this, is the Apache mod_rewrite module installed on your server?

Hello daN4cat, Thanks for your reply. I thing you are referreding to the bolow commands

sudo a2enmod rewrite

and I have executed this and restarted the server

**Comment by daN4cat** [comment]
Is it working now?

**Comment by shankar58989** [comment]
hello daN4cat,
i still get the same error. below is the screenshot of the error when i try to have ospos in a sub directory
![Screenshot from 2019-10-12 22-38-24](https://user-images.githubusercontent.com/52268368/66705184-35a25900-ed41-11e9-8679-28af8f1932a4.png)

my install folder is var/www/html/myospos

my .htaccess file is below
[htaccess.txt](https://github.com/opensourcepos/opensourcepos/files/3720939/htaccess.txt)

my apache.conf files is below
[apache2.txt](https://github.com/opensourcepos/opensourcepos/files/3720940/apache2.txt)

sudo a2enmod rewrite 
is enabled

restarted apache2 with the command below
sudo systemctl restart apache2

**Comment by daN4cat** [comment]
@shankar58989 is that with a https connection or simply http?

**Comment by shankar58989** [comment]
> @shankar58989 is that with a https connection or simply http?

In Linux Mint 19.2 , Firefox 69.0.1
with http://localhost/public -  i get the error "The page isn't redirecting properly"
with https://localhost/public - i get the error "Unable to connect"

I installed apache in terminal using the command
sudo apt install apache2 

is there any configuration that I have to do in a particular way to apache or .htaccess file?

When the OSPOS is under the default folder var/www/html, it works alright.

**Comment by odiea** [comment]
Has it been extracted into that folder or do you have it in a folder. Localhost/ospos/public?

**Comment by shankar58989** [comment]
> Has it been extracted into that folder or do you have it in a folder. Localhost/ospos/public?

i followed the steps in the wiki installation guide in this link[https://github.com/opensourcepos/opensourcepos/wiki/Getting-Started-installations#local-deploy-install](url)

I created a new folder inside var/www/html called myospos
I downloaded and unzipped the contents of the folder inside the newly created "myospos" folder var/www/html/myospos.

**Comment by odiea** [comment]
and what happens when you use localhost/myospos/public?

**Comment by shankar58989** [comment]
> and what happens when you use localhost/myospos/public?

WOW, fantastic it solved the problem. It opens logs in and works fine. Thank you so much odiea. Thanks to dN4cat and jekkos too.
