### ISSUE TITLE
import_items.csv barcode not import

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2515]
The barcode for alphanumeric numbers is not imported to the database when importing a csv file.
Use all types of codes 39, 128, EAN 8 and EAN 13, from only 4 digit numbers etc, without any result.

All the data in the table are imported to Ospos without any problem, but the barcodes are not, and the maximum number of products that can be imported without generating problems is 150 or 200 maximum.

**Comment by WebShells** [comment]
@andriux1990 can you please copy the info from System info tab in the configuration section if available so we can help you in a better way ? or fill in the issue template please....

**Comment by andriux1990** [comment]
![Screenshot_2019-08-13 Tienda Gales Potenciado por NMP 3 3 0](https://user-images.githubusercontent.com/29256343/62985601-5871c900-bdf5-11e9-84b1-c5216721f1d1.png)
I am using this compilation opensourcepos.20190806222050.master.8bca8f.zip

**Comment by andriux1990** [comment]
also download the latest version of bintray opensourcepos.20190811152407.master.7ebae8.zip

I did tests on another operating system and I always had the same problem, no matter the bar codes

**Comment by WebShells** [comment]
Maybe there is a duplicate? Once it reaches this specific row it's interrupting the import process? Specifically you mentioned that you are having a problem inserting more than 150 or 100 item.

**Comment by andriux1990** [comment]
As I had that problem of duplicates what I did was create a new db and import 50 items for each import.
I currently have no duplicates, I have tried to import a single product with a barcode and the barcode does not matter.
I get all the data in the table except the barcode

**Comment by andriux1990** [comment]
I'm not a good programmer, in fact, I'm just learning

since it is very difficult for me to solve the problem of importing barcodes.
I created an attribute with the name codes, type of text. my intention to put the codes, since it allows me to import attributes.
The problem in this is that in the sales module, the search engine only looks for barcode and the names of the items, but does not look for a product by the name of the attribute.
I think that in order to search for the attribute from the register, something must be changed in models / Item.php but I still don't know exactly where.

**Comment by odiea** [comment]
Apparently the Barcode is not being read during the import. I inserted a column before Barcode and it finally saved the barcode. I had to name the column to get it to work.

**Comment by daN4cat** [comment]
The import was changed recently, the logic is different. There must be a keyword or mapping bug.

**Comment by izeblood** [comment]
Can we add the qr codes since the library of it is available?

**Comment by daN4cat** [comment]
We discussed the qr code issue already, there is no real use for it because it's not used as barcode.

**Comment by daN4cat** [comment]
@jekkos can you please give a kick? The controller csv import function looks fine but I don't have the time to test it now.

**Comment by mckaygerhard** [comment]
> maximum number of products that can be imported without generating problems is 150 or 200 maximum.

the problem it's due are using arrays for that .. so the in-arrays are too many.. the memory for php process must be raise to property managed and handle more data.. after made that i propety import more than 200 items products.. but only until 800 items... that's enought due ospos are not a large scalar POS system

changing to a object behaviour are hard to do and will cut off collaboration from mid-users... 

that must be made by cli command by an administrator using own api or database process

> The barcode for alphanumeric numbers is not imported to the database when importing a csv file.
> Use all types of codes 39, 128, EAN 8 and EAN 13, from only 4 digit numbers etc, without any result.

i do not have enought stills for that sorry

**Comment by jekkos** [comment]
When I checked it last time it seemd to pick up the barcode just fine, so I wasn't able to reproduce it immediately. I did download the template first (generate it).
@odiea which file did you use for import? was it an existing one or did you regenerate it from the UI?

**Comment by odiea** [comment]
@jekkos . I tried both. I ended up using Libre office spread sheet because 2007 excel just seemed to screw up the sheet.

**Comment by mckaygerhard** [comment]
make no sense using any ;M$ crap.. libreoffice, gnome-spread can able to make a sheet that can be use as a template to make the csv file to import.. but just dont work if have too many items (300 lines or/and more)

**Comment by jekkos** [comment]
Fix in master and validated by @odiea . Will Close.
