### ISSUE TITLE
Local Docker Deploy Install - stuck on Linux Mint 19.2

### ISSUE THREAD

**Issue by shankar58989** [opensourcepos/opensourcepos#2516]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: Linux Mint 19.2 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hello,

I am trying to install OSPOS on my desktop Linux Mint 19.2. Yesterday I tried "Own Local Deploy Install" but had problems and have raised an issue yesterday.

Today I tried to do a Local Docker Deploy Install on a fresh install of Linux Mint 19.2. after doing the initial updates. This install process appears much easier.

Everything goes fine until the very last command i think

After I enter "docker-compose up" command, the terminal is stuck at the below line. I am not so sure if the process is running or not

"php_1        | 172.18.0.1 - - [13/Aug/2019:13:08:41 +0000] "GET /favicon.ico HTTP/1.1" 404 1496 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

I did CTRL + C many times and again ran the command, it is the same, appears stuck. Help appreciated. Thanks.

**Comment by jekkos** [comment]
it seems to be running no? can you access the application through localhost?

**Comment by jekkos** [comment]
if you want to run in the background you can do so using ctrl-Z

**Comment by shankar58989** [comment]
Hello jekkos, Thank you for the reply and apologies for the late reply. I have managed to get the "Own Local Deploy Install" method working. I restored my OS and installed OSPOS fresh. 

But to understand, after entering the "docker-compose up" command, is the terminal supposed to be running for OSPOS to work?

I tried to load the login page and I got the contents of the index.php file inside the public folder displayed as plain text.

**Comment by shankar58989** [comment]
I have installed the OSPOS on my linux mint 19.2 through "own local deploy install".

Since I no longer have the docker deploy install of OSPOS and I cannot reproduce and test the solutions provided for this issue, i will close this topic, if I may. 

Once again thanks to Jekkos for the response as well as to the entire community for this fantastic software.
