### ISSUE TITLE
You do not have permission to access the module named Items and Receivings

### ISSUE THREAD

**Issue by terranoss** [opensourcepos/opensourcepos#2519]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: idk
- PHP version is: 
- MySQL or MariaDB version is: idk 
- OS and version is: 
- WebServer is: localhost
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Aftfer successfull installation on subdomain, I created a user and assigned the permission (ticked all). But when I logged into that user, I cannot access Items and Receivings. Anyone else having this problem? Can anyone help me?

Thank you
Deen

**Comment by odiea** [comment]
I could not recreate your issue. idk

**Comment by tariqsendi** [comment]
I'm having the same Issue.
<img width="434" alt="Screen Shot 2021-09-21 at 12 10 44 PM" src="https://user-images.githubusercontent.com/36600875/134144750-37d302e6-1cc5-4239-b917-82feccef9932.png">

**Comment by tariqsendi** [comment]
We only resolved the issue by returning to a snapshot and importing sales back in.
