### ISSUE TITLE
Foreign key constraint is incorrectly formed 

### ISSUE THREAD

**Issue by fWd82** [opensourcepos/opensourcepos#2520]
### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: opensourcepos.20180613210031.3.2.3.f1cf3d
- PHP version is: 7.3.5
- MySQL or MariaDB version is: 10.1.39 MariaDB
- OS and version is: Windows 8.1 64bit
- WebServer is: Apache/2.4.39
- Selected language is: 
 - Other info: On XAMPP

### Issue / Bug  / Question / New Feature
I have backup of ospos database sql file named: ospos-2019-08-19-14-50-58.zip and size is: 6MB. I have installed ospos to new laptop and I want to import that database to my new one. 
What is did was: 

1. I created new db and then import > ospos-2019-08-19-14-50-58.zip (Failed)
2. Tried on SSH Mysql shell. (Failed) 
3. Tried on Mysql Workbench (Failed) 

**ERROR 1005 (HY000) at line 140: Can't create table `my_db`.`ospos_customers` (errno: 150 "Foreign key constraint is incorrectly formed")**

Please be informed that my (current & previous) DB is `innoDB` and charset is `UTF-8 General CI`

What I need to do, please give advice. I have lot of data and transactions.

**Comment by jekkos** [comment]
Hi, I just checked on stackoverflow and [found the following. ](https://stackoverflow.com/questions/8434518/mysql-foreign-key-constraint-is-incorrectly-formed-error)
Do you have created your original tables in MyISAM? You might to migrate the tables to InnoDB.

```
ALTER TABLE ospos_customers ENGINE=InnoDB;
ALTER TABLE ospos_people ENGINE=InnoDB;
```

**Comment by daN4cat** [comment]
No follow up, I close.
