### ISSUE TITLE
Error: Folder path after fresh installation

### ISSUE THREAD

**Issue by sarzali07** [opensourcepos/opensourcepos#2524]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 5.6.13
- MySQL or MariaDB version is:  
- OS and version is: debian
- WebServer is: virtual
- Selected language is: english 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Issue: I have install on fresh virtual machine with IP of 192.168.100.40. I install apache2, php and mariaDB server. As per instruction I setup all. but when I access over localhost or from anywhere else by IP it gives me error "Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php"
Can anyone please let me know what is problem.

Regards

**Comment by odiea** [comment]
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20190811152407.master.7ebae8.zip is the file you need. Not the Dev version.

**Comment by sarzali07** [comment]
Hi Odia now it showing 
This page isn’t working 192.168.100.40 is currently unable to handle this request.
HTTP ERROR 500

**Comment by sarzali07** [comment]
After setting from Production to development it showing 

An uncaught Exception was encountered
Type: Error

Message: Call to undefined function mysqli_init()

Filename: /var/www/html/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php

Line Number: 135

Backtrace:

File: /var/www/html/public/index.php
Line: 315
Function: require_once

**Comment by sarzali07** [comment]
Thanks It works but after enter IP/public/login then 

Not Found
The requested URL /public/login was not found on this server.

it showing 500 error??

**Comment by daN4cat** [comment]
What is your web server root? And where did you install ospos? I mean in which folder?

**Comment by WebShells** [comment]
I guess we should make the server info section public? So users can make use of the installation data for issues? In the way i added it's not accessible without having ospos up and running... Shall we?

**Comment by sarzali07** [comment]
Hi any how I manage to display login screen. Now after entering username and password then it gives error

The installation is not correct, check your php.ini file.
A database migration to 3.3.0 will start after login.

**Comment by sarzali07** [comment]
> What is your web server root? And where did you install ospos? I mean in which folder?

Yes I setup in virtual machine and its on /var/www/html root

**Comment by andriux1990** [comment]
you already set up apache2.config

**Comment by andriux1990** [comment]
> Hi any how I manage to display login screen. Now after entering username and password then it gives error
> 
> The installation is not correct, check your php.ini file.
> A database migration to 3.3.0 will start after login.

https://github.com/opensourcepos/opensourcepos/issues/920#issuecomment-254451704
for php.ini you need a php extension

**Comment by andriux1990** [comment]
> https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20190811152407.master.7ebae8.zip is the file you need. Not the Dev version.

@odiea have you checked 
https://github.com/opensourcepos/opensourcepos/issues/2522#issue-486462410
the error in the detailed reports

**Comment by daN4cat** [comment]
No follow up, I close.
