### ISSUE TITLE
When company logo is uploaded, company name not appearing on invoice - Question

### ISSUE THREAD

**Issue by shankar58989** [opensourcepos/opensourcepos#2525]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3 
- OSPOS git commit hash is: 
- PHP version is: 7.2.19
- MySQL or MariaDB version is: 15.1
- OS and version is: linux mint 19.2
- WebServer is: apache2
- Selected language is: english
- (If applicable) Docker installation: no
- (If applicable) Installation package for the LAMP/LEMP stack is: 

Question

Question
I am not sure if this is a bug or and issue, so i have marked it as a question.

The company name is displayed on the invoice only when the logo is not uploaded. When the logo is uploaded only the logo is appearing on the invoice and the company name is not getting displayed.

This is not the case in the receipt. The name as well as the logo is getting displayed on the receipt.  
How do I get the name also to be displayed in the invoice along with the logo?

Requesting help on this issue. Thanks. 

I have attached the sample receipt file as well as sample invoice file below.
[sales invoice6.pdf](https://github.com/opensourcepos/opensourcepos/files/3560046/sales.invoice6.pdf)
[sales receipt14.pdf](https://github.com/opensourcepos/opensourcepos/files/3560048/sales.receipt14.pdf)

**Comment by shankar58989** [comment]
hello, 

should i change something in the sales invoice format {CO} to something else for the company name to appear along with the logo image in the sales invoice?

There is an option to check and uncheck the company name in the sales receipt. but i am unable to figure out how to do this in sales invoice.

hope someone can help me with this issue guys. thanks.

**Comment by odiea** [comment]
Try resizing your logo image. It's probably too large for an invoice.

**Comment by shankar58989** [comment]
hi odiea, thanks for your reply. I will try this solution and report back tomorrow.

**Comment by daN4cat** [comment]
Yes it's like that.

**Comment by odiea** [comment]
This code from Invoice to me appears to be the same as on the Receipt. So it should work the same.

```
<div id="logo">
			<?php
			if($this->Appconfig->get('company_logo') != '')
			{
			?>
				<img id="image" src="<?php echo base_url('uploads/' . $this->Appconfig->get('company_logo')); ?>" alt="company_logo" />
			<?php
			}
			?>
			<div>&nbsp</div>
			<?php
			if($this->Appconfig->get('receipt_show_company_name'))
			{
			?>
				<div id="company_name"><?php echo $this->config->item('company'); ?></div>
			<?php
			}
			?>
		</div>
```

**Comment by jekkos** [comment]
@odiea so invoice template also uses the receipt switch?

**Comment by odiea** [comment]
Yes it does for logo. The log does have to be a certain size for it to show in the Invoice.
![2019-09-11 05_44_34-Odies Test _ Powered by OSPOS 3 3 0](https://user-images.githubusercontent.com/10962177/64694670-6f88f280-d457-11e9-97eb-da2ece6d93f8.png)
And this is the Invoice.
![2019-09-11 05_45_00-Odies Test _ Powered by OSPOS 3 3 0](https://user-images.githubusercontent.com/10962177/64694690-816a9580-d457-11e9-9cfc-bab3805c777a.png)

**Comment by mckaygerhard** [comment]
> Try resizing your logo image. It's probably too large for an invoice.

the receitp musr rezise the logo.. to be in the invice also

**Comment by daN4cat** [comment]
Alright, I might have added that config switch some year ago...

**Comment by daN4cat** [comment]
I guess we can close here.
