### ISSUE TITLE
Inventory Summary

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2526]
I love the article module, it has almost everything. The problem is that when you have several locations. and I want to make a summary of the inventory of a certain location, and I look for my products by category, it shows me all the products including from the other locations.

The solution to this is in reports - Inventory summary. where I can search for location and quantities greater than 0.

All good so far, the problem here is that there is no Category tab, since I would like to search my products by categories and we do not have a search engine.

I think it would be super to include these changes in the ospos

**Comment by andriux1990** [comment]
![Screenshot_2019-09-01 Open Source Point of Sale Powered by OSPOS 3 3 0](https://user-images.githubusercontent.com/29256343/64082605-c3b10b80-ccce-11e9-8ad2-1e1d425da597.png)
![1](https://user-images.githubusercontent.com/29256343/64082581-687f1900-ccce-11e9-8eaf-ebf1e2713fe5.png)

**Comment by andriux1990** [comment]
I think here serious to add the column of categories
![image10](https://user-images.githubusercontent.com/29256343/64082703-5a31fc80-ccd0-11e9-8e06-b85713ff8709.png)
![DeepinScreenshot_20190901154525](https://user-images.githubusercontent.com/29256343/64082705-6918af00-ccd0-11e9-9258-cea33d4ef898.png)

**Comment by mckaygerhard** [comment]
> I love the article module, it has almost everything. The problem is that when you have several locations. and I want to make a summary of the inventory of a certain location, and I look for my products by category, it shows me all the products including from the other locations.
> 

i think you request for two different thing here.. first i see your picture in the previous last comment and seems quite very easy to made the addition of the categories to the summary inventory report.. 

but that:
>and I want to make a summary of the inventory of a certain location,

i recommend open a new issue and let this issue with only that:
> and I look for my products by category

that lasted request are just very easyle.. just in the model added the column and fit into the array, and lasted in the controller  requsted that data .. i'll made a pull request with those changes...

i'm afraik that ospos must remove all the reports modules and provide a new kind of report system.. all the POS system has a report module very advanced for..
