### ISSUE TITLE
albanianSQ translations folder

### ISSUE THREAD

**Issue by darknodi** [opensourcepos/opensourcepos#2527]
albanianSQ translations folder @awriel @yllumi @vnwildman @ratomi @pappastech

**Comment by SteveIreland** [comment]
I assume that someone knows what this issue is about because it is meaningless to me.

**Comment by daN4cat** [comment]
@darknodi please see https://github.com/opensourcepos/opensourcepos/wiki/Adding-translations (I don't know who deleted that guideline but I restored it)
