### ISSUE TITLE
improve attribute descriptions

### ISSUE THREAD

**Issue by diazvictor** [opensourcepos/opensourcepos#2529]
please added long text support to description attribute, Attribute type is stored in the database (attribute_values) as a VARCHAR(255) which is perfect for most attribute values. There is one category of Attribute in which this length is far too short. Descriptions. In the book industry publisher synopsis, table of contents, forewards, etc would all be far too long to fit here, i posted that feature request due the issue #2470

**Comment by mckaygerhard** [comment]
maybe no all the descriptions of the labels in the products will be necesary fit but in stores where many cristmas tools are sell we must include some hints about materials.. this will hep about that.. maybe with a inprovement search at the sale screen

**Comment by andriux1990** [comment]
This if I think it is very necessary, how can I do it, how difficult would it be?
that of increasing the attribute field

**Comment by jekkos** [comment]
@diazvictor Please don't open duplicate issues, let's track #2470 for progress on this one.

**Comment by mckaygerhard** [comment]
@jekkos the issue #2470 are locket so how contributions can post some advances? response that if you dont want duplilcate issues.. unlock that or open this! puff
