### ISSUE TITLE
Item Save - Language

### ISSUE THREAD

**Issue by blutme** [opensourcepos/opensourcepos#2533]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0 - ac6d5e
- OSPOS git commit hash is: 
- PHP version is:  5.6.40-0+deb8u5
- MySQL or MariaDB version is: 5.5-10.0.38-MariaDB-0+deb8u1
- OS and version is: Linux raspberrypi 4.9.35+ 1014 Fri Jun 30 14:34:49 BST 2017 armv6l
- WebServer is:  Apache/2.4.10 (Raspbian)
- Selected language is: en-US
- (If applicable) Docker installation: No
- (If applicable) Installation package for the LAMP/LEMP stack is: No

### Issue / Bug  / Question / New Feature

When I add a "new item"  with the default language en-US, it notifies (green pop-up notification) was added successfully, but when I change the language on (/public/config > Localization > Languaje "Spanish" 

- Logout an login for changes to be saved
- over console > service apache2 restart

Now in spanish languaje and try to add another article "nuevo articulo(new item)", then  notification window no longer appears, only a plain text message. 

Just like this: {"success":true,"message":"Has agregado satisfactoriamente un art\u00edculo bobadas2","id":13}

then when refresh "ip"/ospos_name/public/items > but the items if was added.

Then I try to Change the language to Portuguese (Brazil) and it works correctly here too.
Only spahish error. 

-over console > cd /var/www/html/ospos2/application/language
 do this:
 > mv en-US en-US.bk
 > mv es en-US
 > service apache2 restart

...to find out if there is an error in the "es" folder

But when login -> now is in spanish but the problem  persists.

Try with 4c80a9 but the error persisit.

Thanks for your help.

**Comment by jekkos** [comment]
OK thanks for the bug report, it could indeed be an error in one of the translated files. Can you check for error/warnings in the log files ?

**Comment by jekkos** [comment]
@blutme Can you try latest master? I fixed an escape sequence in the translations.

**Comment by mckaygerhard** [comment]
commit related: https://github.com/opensourcepos/opensourcepos/commit/9bdebc6bdda538b9423e4e11e67159ee9b610059

**Comment by blutme** [comment]
OK, THANK YOU. The problem was solved by changing the line that produced the bug. Now, I would like to know how I enable or where I cand find the file log/warnings for futures issues or bugs. 

Thanks.

**Comment by mckaygerhard** [comment]
@blutme i make a wiki page explaining that at https://github.com/osposweb/osposweb/blob/gh-pages/ospos-2-DEVEL-0-how-to-debug-CI-en.md with details..
