### ISSUE TITLE
item type disabled

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2537]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

![Captura de pantalla de 2019-09-12 10-40-56](https://user-images.githubusercontent.com/29256343/64803851-ebb03280-d54a-11e9-9f78-7bb97095bc98.png)

As of version 3.3.0 this is disabled.

For what reason?
when this is disabled In the item kit, this item section in the kit does not work

**Comment by SteveIreland** [comment]
There wasn't any follow-up on this so I'm assuming this can be closed.  If someone wants to discuss this further I'm happy to listen.

**Comment by klisle** [comment]
This is also happening to me. wondering why. Even when the user john doe has all privs the option is still disabled

**Comment by daN4cat** [comment]
What is the scenario to reproduce this issue?

**Comment by odiea** [comment]
@SteveIreland  He is correct. The only way I can get this to work is to comment out disabled in the Items form.  The form does not show a user has to have permission to get these to work.

**Comment by odiea** [comment]
This issue also shows on the current demo.

**Comment by daN4cat** [comment]
@SteveIreland this sounds a bug to fix a d release in 3.3.1. Can you please look into this?

**Comment by SteveIreland** [comment]
ok

**Comment by daN4cat** [comment]
@SteveIreland thanks

**Comment by andriux1990** [comment]
@klisle It really is not important that it is disabled, practically the item kit is nothing really special, if you are looking for something special in the kit, you will not find it.

**Comment by odiea** [comment]
@SteveIreland I assume the following code was to change the settings.
		$data['item_type_disabled'] = !$this->Employee->has_grant('item_kits', $this->Employee->get_logged_in_employee_info()->person_id);

**Comment by SteveIreland** [comment]
Thanks to @klisle for breathing life back into this and to @odiea for confirming the error.

**Comment by odiea** [comment]
Works great. Thanks for fixing this issue.

**Comment by daN4cat** [comment]
Ok I merge

**Comment by daN4cat** [comment]
Thanks @SteveIreland for the continuous support in this project.
