### ISSUE TITLE
Android app 

### ISSUE THREAD

**Issue by paverneuil** [opensourcepos/opensourcepos#2540]
hello,
 I wonder if there is an android application, or a method that would make it compatible printing receipt via a wireless thermal printer I just discovered your project and begins to interest me in the way it works.

**Comment by WebShells** [comment]
Hello @paverneuil, currently the project can run on Android devices, yet not fully responsive and printing to Bluetooth printer isn't supported. Need some customization in order to print directly from Chrome... Contributions are welcome 🤗 !

**Comment by paverneuil** [comment]
At first, I think that with Google Cloud Print, something would be possible with a rather simple integration.  the disadvantage would be connectivity. 😅

**Comment by WebShells** [comment]
True, google cloud printing cannot detect the Bluetooth printer... Thus it needs some tweaking to print raw data directly through js...

**Comment by andriux1990** [comment]
> hello,
> I wonder if there is an android application, or a method that would make it compatible printing receipt via a wireless thermal printer I just discovered your project and begins to interest me in the way it works.

Find the right Android application to connect to your bluetooth printer. Then you have to change the receip_defauld a bit and the printing works for you.

In fact, you can do this even from an Android webview app.

**Comment by WebShells** [comment]
@andriux1990 i think android web view app will print the receipt as an image... Some lines will be barely readable...

**Comment by andriux1990** [comment]
@WebShells To solve this, what is done is that by touching the print button there will be the application of the printer and then it will be printed.

the other thing that I did was next to the print button, create another button that I exported in PDF receipt and then open it and print

**Comment by WebShells** [comment]
@andriux1990 i believe the printed data should be sent as RAW data to the printer in order to print in text format... Or else it will print a low quality jpg image..
