### ISSUE TITLE
Barcode's 350 pixel width limit question

### ISSUE THREAD

**Issue by marcellusmontilla** [opensourcepos/opensourcepos#2541]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 5.6.40
- MySQL or MariaDB version is: 5.6.43
- OS and version is: linux
- WebServer is: Apache 2.4.41
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
Any reason why we have the 350 pixel width limit? I'm asking this because we sometimes encounter "**Caught exception: Not enough space on this barcode for this message, increase the width of the barcode**" but we can't increase beyond 350.

![image](https://user-images.githubusercontent.com/25737631/65035999-089a9a80-d97d-11e9-90f4-c99a4d861dea.png)

**Comment by daN4cat** [comment]
No idea why that limit.
Feel free to change, test and submit a PR with the change.

**Comment by WebShells** [comment]
The barcode will be readable only in a specific width i think...

**Comment by daN4cat** [comment]
Quite possibly

**Comment by WebShells** [comment]
And it depends on barcode type to set barcode width accordingly in order to be readable as correct formatted... Maybe this should stay unless we replace it by something which automatically input barcode width upon barcode selection.

**Comment by marcellusmontilla** [comment]
Not yet, but it's not really critical. Was just curious.
