### ISSUE TITLE
Add Visa , Master Cards in payment options Please 

### ISSUE THREAD

**Issue by norekluzt** [opensourcepos/opensourcepos#2542]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is:  Ver 14.14 Distrib 5.7.27
- OS and version is: 5.7.27 Ubuntu 18.04.1
- WebServer is:  using Digital Ocean
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

New Feature

Is there a way that we can add specific cards
eg. Master Cards,
      Visa Credit Cards

Reason why im asking is when making reports i would like the ability to distinguish between the type of payment made with cards as that is important when we reconcile with the banks.

I somewhat know a bit on how the system works but for the life of me i cannot figure out where exactly that is being taken as the database only has a field for {Sale_Type} but no where in the database you can add the different payment methods.

can one point me to what direction i can manually add the other payment methods? is it feasible to do it ?

![Payment Method](https://user-images.githubusercontent.com/44441986/65159084-c6ab3c00-d9f0-11e9-80f3-7bdd940d32bc.PNG)

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
Yes there is a way for this to happen. In your language find sales and add the following lines. Try this and see if it works for you.
```
$lang["sales_mc"] = "Master Card";
$lang["sales_visa"] = "Visa";
``` 
Then in application /helpers find locale_helper
Then add the following lines before or after line 250.
```
$payments[$lang->line('sales_mc')] = $lang->line('sales_mc');
$payments[$lang->line('sales_visa')] = $lang->line('sales_visa');
```

**Comment by norekluzt** [comment]
Amazing thank you so much !

________________________________
