### ISSUE TITLE
The upload destination folder does not appear to be writable.

### ISSUE THREAD

**Issue by norekluzt** [opensourcepos/opensourcepos#2543]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: Open Source Point Of Sale version 3.2.3
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: eng-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

ISSUE

I have my setup using digital ocean and i basically followed instructions to the Tee;

An issue i am having is that i can create items i cannot add images and the error
: The upload destination folder does not appear to be writable

it is possible that its just a folder permission issue but i would really like some one to take a look at this and assist me .. 

any assistance would be gladly appreciated

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by blutme** [comment]
I think you must enter to the module Access>Console Access on DigitalOcean and find path: /var/www/.... 

and enable permissions.

chmod 770 -R /var/www/html/[ospos name]/application/logs/
chmod 770 -R /var/www/html/[ospos name]/public/uploads/
chmod 770 -R /var/www/html/[ospos name]/public/uploads/item_pics/

I have performed this process on my local server and it worked for me.

**Comment by nira168** [comment]
@blutme what you mean by ospos name? I have installed all file in the /var/www/html/

**Comment by daN4cat** [comment]
@nira168 therefore the OSPOS name subfolder doesn't apply to you.
Check in the configuration tab and system info to make sure everything is setup correctly with writeable subfolders. With 3.3.0 there is that self checkup feature now.

**Comment by nira168** [comment]
@daN4cat thanks for your info, here is my system i
![issueospos](https://user-images.githubusercontent.com/17110407/66255892-25bfcd80-e7b3-11e9-849f-431471580e89.JPG)
nfo.

**Comment by nira168** [comment]
how to enable file permission?

**Comment by daN4cat** [comment]
Blutme post is explaining how, right? Just don't worry about the [ospos name]/ subfolder, remove that and apply the same command.

**Comment by nira168** [comment]
Thanks @daN4cat,  It works now with 777.

**Comment by daN4cat** [comment]
777 that doesn't sound good. Means everybody. How did you install Apache and the user?

**Comment by nira168** [comment]
I follow the installation guide via this https://www.opensourceposguide.com/guide/gettingstarted/installation

**Comment by daN4cat** [comment]
That site has nothing to do with us. Get in touch with them and ask support.

**Comment by dme1sc** [comment]
looking at this and looking at mine, I bet his file system is 'root' - it should probably be 'www-data' or similar.  
chown -R www-data: opensourcepos
then do those permissions at 770.

**Comment by SamPrinceFranklin** [comment]
If you encounter the error "The upload destination folder does not appear to be writable," you can follow these steps to resolve it.

### Solution

1. Open a terminal.

2. Navigate to the root of your project.

3. Run the following commands:

```bash
# Change ownership to the web server user (e.g., www-data for Apache)
sudo chown -R www-data:www-data uploads/

# Grant appropriate permissions (e.g., read and write for the owner)
sudo chmod -R 755 uploads/
