### ISSUE TITLE
/.../public  Plain text php code 

### ISSUE THREAD

**Issue by blutme** [opensourcepos/opensourcepos#2544]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 427432
- OSPOS git commit hash is: 
- PHP version is: PHP 7.2.22-1+0 debian9
- MySQL or MariaDB version is: Ver 15.1 Distrib 10.3.17-MariaDB
- OS and version is: Debian Buster
- WebServer is: Apache/2.4.38 (Debian)
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I installed OSPOS on debian jessie with php 5.2 and everything works correctly. Now I migrated to "debian buster" with php 7.2 and complements , but when access to ip/ospos/public/ only get a php file plain text code  * CodeIgniter.

[https://photos.app.goo.gl/WhFBE14jxKyha9jn8](url)

I configure the .httacces and apache files too. and review the issues: #920 #1331 #1357

What another configuration would be to do in this case? Thanks for your help!

**Comment by daN4cat** [comment]
Download the latest official Release 3.3.0 from [Github here](https://github.com/opensourcepos/opensourcepos/releases/tag/3.3.0), install and try again.
