### ISSUE TITLE
Navigation Menu 

### ISSUE THREAD

**Issue by rjiansevilla** [opensourcepos/opensourcepos#2552]
Is there a way I can disable some menu or the plat icons menu? navigation on the top and the home. thanks

**Comment by daN4cat** [comment]
Use the user permissions to control what's visible or not.

**Comment by rjiansevilla** [comment]
Thanks. is it possible to add menu or flat icon?

**Comment by daN4cat** [comment]
You can code what you like, as long as you respect the license.
