### ISSUE TITLE
UNABLE TO ADD NEW CUSTOMER, ON LOCAL HOST WORKING FINE, PROBLEM FACING IN SHARED HOSTING SERVER

### ISSUE THREAD

**Issue by shyamsunderindia** [opensourcepos/opensourcepos#2553]
Hi All, My name is Shyam, I am also having same problem. When I am adding New Customer there dialog box is opening but that is blank only submit button appear and nothing field to enter detail. Rest adding Item, whole seller etc . is working fine. Only facing problem in adding New Customer.

I tried this application in my local server using xamp there everything working fine there is no issue and I can add New Customer, But in shared hosting server I cannot add New customer.
I also check Mbstring in my hosting server that is enabled and set Auto by default.

Please anyone help me as soon as possible. I am using latest version of ospos opensourcepos.20190704173621.master.7da7c0

Here I am sharing screenshot of problem in Adding New Customer.
https://drive.google.com/open?id=1Uwbe1GrqFBhTq4_-qoeNR1y9KA84nUt5

Waiting eagerly for some working solutions.
Thanks ,
SHYAM SUNDER

**Comment by WebShells** [comment]
Hello Shyam, please we would like to know which version you are using? Installation? PHP? Etc... For this, please fill in the issue template so we can help in a better way, it might be related to php modules, not all are running as required.

**Comment by odiea** [comment]
opensourcepos.20190704173621.master.7da7c0
3 months ago

**Comment by shyamsunderindia** [comment]
Hi, WebShells and odiea, Thanks for giving fast reply and noticing my issue. Now I have some hope that my problem will be short out.  Here below is all detail about version etc. I all files are hosted on linux shared hosting. 

Details:
--------------------------------------------
OSPOS Installation Info:	3.3.0 - 7da7c0
Language Code:	en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache
.PHP Version: 7.3.6
.DB Version: 5.6.45-86.1
.Server Port: 80
.OS: Linux freeweb14-1.byetcluster.com 2.6.32-896.16.1.lve1.4.54.el6.x86_64 #1 SMP Wed May 2 07:43:19 EDT 2018 x86_64

File Permissions:
» [application/logs:] - 0755 | Writable ✓
» [public/uploads:] - 0755 | Writable ✓
» [public/uploads/item_pics:] - 0755 | Writable ✓
» [import_customers.csv:] - 0644 | Writable ✓
----------------------------------------------------

Thanks a lot

**Comment by odiea** [comment]
This is the current unstable 3.3.0 version. Try it out.
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20190925200927.master.d63eb4.zip

**Comment by shyamsunderindia** [comment]
@odiea  with given link by your side, if i install then will this work fine? Since the version which I am currently using is also working but in local server and same ospos version and files which uploaded on hosting server there is issue. If there will some issue in that version of ospos then that should not work even in my local host. But according to your suggestion let me to test the version which you given me.

Thanks a lot hoping and praying that now this will work.

**Comment by odiea** [comment]
We won't know until you try it.
1. Find a computer with 2 or more gigs of ram.
2. Put it on a battery backup and stick it in some lonesome place out of sight.
3. Install Wamp or xampp on it.
4. Install OSPOS on it.  
5. Get a dynamic dns provider if it really needs to be on the Internet.
Too many service providers are causing issues that we cannot diagnose.

**Comment by shyamsunderindia** [comment]
@odiea Ya you are right I am also thinking this is becoz of server hosting provider side, because that working fine on local host. By the way I am installing again those files which you provided to me. give me some time to check. If this will not work then I will migrate to any other hosting provider. 

If you can check faster than me on any shared hosting then please do and let me know. I am online here whole day and night today until my problem will not solve.

**Comment by shyamsunderindia** [comment]
@odiea Hi, I installed again on hosting server with those setup files which you shared with me, Still have same issue unable to add new customer. What to do next? Should I migrate to another hosting server? or there is some other solutions? please let me know.
Thanks for your kind help

**Comment by daN4cat** [comment]
@shyamsunderindia we need php logs to help you. For error logging enabling see this wiki page:https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-DEVEL-for-Error-Logging-in-OSPOS#error-log-on-client-side

**Comment by daN4cat** [comment]
BTW, the issue #2383 was about a similar issue and solution was fixing PHP and MySQL installation.

**Comment by daN4cat** [comment]
Another example pointing to a database issue #1876
