### ISSUE TITLE
Ubuntu Shell Access

### ISSUE THREAD

**Issue by WebShells** [opensourcepos/opensourcepos#2555]
Dear users, 

We're in need for a Ubuntu Shell access with elevated permissions to create all-in-one script for setting up nginx web server, install mariadb, install php, create nginx block files, and insall adminer... 
This will help in setting up OSPOS automatically on LEMP enviroment without any user effort other than few db related questions.

If anyone can offer comment down...
Much appreciate it!
@opensourcepos/org

**Comment by objecttothis** [comment]
@webshells, sorry I could give you a FreeBSD jail with elevated access, but I don't have access to Ubuntu.

**Comment by WebShells** [comment]
Thanks @objecttothis... What is the control panel you are using ? I guess the commands doesn't differ from CentOS to FreeBSD, if you have no problem please try the below and let me know if things ran smoothly... 

[OSPOS cPanel & SSH Auto Installer ](https://github.com/opensourcepos/opensourcepos/wiki/Getting-Started-installations#cpanel-ssh-install)
If you use something different than cPanel, i'd be glad to add several scenarios into installation script.

**Comment by objecttothis** [comment]
Sorry, I misunderstood. I didn't realize you were talking about a cpanel installer. I thought you were talking about a shell script or something similar. I'm not using cpanel on that server.  I do have a shared server that runs cpanel on it but I don't have, nor can I give, elevated access.

**Comment by objecttothis** [comment]
In November when I get back in the office at the beginning of November I can run it with just user access on cpanel.

**Comment by WebShells** [comment]
@objecttothis actually it's a shell installer but db creation is made through cpanel, if you can share access with regular permissions i can adjust to work on regular shells with no cPanel...

**Comment by daN4cat** [comment]
Sorry, only CentOS.
