### ISSUE TITLE
Error Graphical Reports payments

### ISSUE THREAD

**Issue by tuthanika** [opensourcepos/opensourcepos#2556]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 7.1.31
- MySQL or MariaDB version is: 10.3.17
- OS and version is: 
- WebServer is: localhost and share hosting
- Selected language is: All languages
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
![1](https://user-images.githubusercontent.com/22352264/65927585-75ee0700-e424-11e9-9de1-c5a5f06f5b19.png)
![2](https://user-images.githubusercontent.com/22352264/65927586-76869d80-e424-11e9-833c-c4f6e1e21a97.png)
![3](https://user-images.githubusercontent.com/22352264/65927587-76869d80-e424-11e9-997a-42d2a1ccf40a.png)

**Comment by WebShells** [comment]
This issue exist in 3.3.0, just tested... 

OSPOS Installation Info: 3.3.0 - 0b9a76
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache
.PHP Version: 5.6.40
.DB Version: 5.6.45
.Server Port: 80
.OS: Linux 2.6.32-696.16.1.el6.x86_64 #1 SMP Wed Nov 15 16:51:15 UTC 2017 x86_64

File Permissions:
» [application/logs:] - 0775 | Writable ✓ 
» [public/uploads:] - 0775 | Writable ✓ 
» [public/uploads/item_pics:] - 0775 | Writable ✓ 
» [import_customers.csv:] - 0664 | Writable ✓

**Comment by tuthanika** [comment]
I have fixed it successfully
application/controllers/Reports.php
replace line 853 to 855
 	public function graphical_summary_payments($start_date, $end_date, $sale_type)
	{
		$inputs = array('start_date' => $start_date, 'end_date' => $end_date, 'sale_type' => $sale_type);"
to
 	public function graphical_summary_payments($start_date, $end_date, $sale_type, $location_id = 'all')
	{
		$inputs = array('start_date' => $start_date, 'end_date' => $end_date, 'sale_type' => $sale_type, 'location_id' => $location_id);

**Comment by WebShells** [comment]
Fixed in master, will close... Thank you @tuthanika

**Comment by daN4cat** [comment]
Alright we need a 3.0.1 out soon. Let's wait a bit for more testing and feedback.
