### ISSUE TITLE
Delete of items or Bills 

### ISSUE THREAD

**Issue by faoziahmedtaher** [opensourcepos/opensourcepos#2558]
Hello 
i had POS 3.2.3 when i upgraded to 3.3.0 i cant delete any items or bills i cant delete any thing because the button delete not responding at all 
thx

**Comment by odiea** [comment]
Did you mark the items for deletion?

**Comment by faoziahmedtaher** [comment]
yes i select the item when i click delete it does not show any respond

**Comment by odiea** [comment]
You will have to submit the info from configuration/system info. It may help.

**Comment by faoziahmedtaher** [comment]
OSPOS Installation Info: | 3.3.0 - dev
-- | --
en-US
» GD: Enabled ✓» BC Math: Enabled ✓» INTL: Enabled ✓» OpenSSL: Enabled ✓» MBString: Enabled ✓» Curl: Enabled ✓
.Browser: Chrome.Server Software: Apache.PHP Version: 7.1.32.DB Version: 5.6.45.Server Port: 80.OS: Linux mocha3031.mochahost.com 3.10.0-962.3.2.lve1.5.24.8.el7.x86_64 #1 SMP Fri Jan 4 06:55:54 EST 2019 x86_64
» [application/logs:] - 0755 \| Writable ✓ » [public/uploads:] - 0755 \| Writable ✓ » [public/uploads/item_pics:] - 0755 \| Writable ✓ » [import_customers.csv:] - 0644 \| Writable ✓

**Comment by WebShells** [comment]
Please use copy info button to keep formatting...

**Comment by faoziahmedtaher** [comment]
معلومات التثبيت OSPOS: 3.3.0 - dev
Language Code: ar-LB

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache
.PHP Version: 7.1.32
.DB Version: 5.6.45
.Server Port: 80
.OS: Linux mocha3031.mochahost.com 3.10.0-962.3.2.lve1.5.24.8.el7.x86_64 #1 SMP Fri Jan 4 06:55:54 EST 2019 x86_64

File Permissions:
» [application/logs:] - 0755 | Writable ✓ 
» [public/uploads:] - 0755 | Writable ✓ 
» [public/uploads/item_pics:] - 0755 | Writable ✓ 
» [import_customers.csv:] - 0644 | Writable ✓

**Comment by odiea** [comment]
Your mysql is fairly old.  MySQL 5.6.4 (2011-12-20, Milestone 7). Don't know if that could be the issue. And maybe you could try the Bintray zip version instead of the dev version.

**Comment by faoziahmedtaher** [comment]
ok it's solved now thx
