### ISSUE TITLE
CSS Error & No Item Kits to display

### ISSUE THREAD

**Issue by messidiq** [opensourcepos/opensourcepos#2559]
![Screenshot_20191001_215705](https://user-images.githubusercontent.com/22187541/65975915-9015fc80-e499-11e9-9ece-37f7284aeca7.png)

Hi i found this issue when updating to version 3.3.0, Help me out

**Comment by odiea** [comment]
https://github.com/opensourcepos/opensourcepos/releases/download/3.3.0/opensourcepos.20190929181753.3.3.0.0b9a76.zip

**Comment by daN4cat** [comment]
Don;t use code from master but download the release as @odiea correctly pointed out.

**Comment by muhammadhanif** [comment]
> https://github.com/opensourcepos/opensourcepos/releases/download/3.3.0/opensourcepos.20190929181753.3.3.0.0b9a76.zip

I have installed this version. But, when I tried to add Items Kits, the page showed **No Item Kits to display**. I directly checked to the database, there are some items kits that i added previously.

![screenshot-toko local-2019 10 02-21_41_15](https://user-images.githubusercontent.com/12027149/66053437-86090200-e55c-11e9-8131-72216b46518a.png)
![screenshot-mysql local-2019 10 02-21_41_41](https://user-images.githubusercontent.com/12027149/66053441-899c8900-e55c-11e9-8b17-f746011c6707.png)

**Comment by odiea** [comment]
From your table it appears that you did not add any Items to the Item Kits

**Comment by muhammadhanif** [comment]
> From your table it appears that you did not add any Items to the Item Kits

I try to add item, the forms do not appear.
![pos-1](https://user-images.githubusercontent.com/12027149/66054378-13992180-e55e-11e9-8f08-455e8deec3bb.png)

**Comment by odiea** [comment]
What do you see when you click on 1 of the red views with error 500?

**Comment by daN4cat** [comment]
It's probably the same db error related to grouping

**Comment by odiea** [comment]
@daN4cat . Yes you are correct.

**Comment by daN4cat** [comment]
@muhammadhanif please see #2538

**Comment by muhammadhanif** [comment]
Thank you @odiea @daN4cat

**Comment by mckaygerhard** [comment]
again same bug...

**Comment by mckaygerhard** [comment]
again same bug, this are not same of #2538.. the problem it is maybe related to xss as i posted in  #2452 .. ... released a new version with a serious bug present.

**Comment by daN4cat** [comment]
@muhammadhanif can you please test with the latest code in master?

**Comment by daN4cat** [comment]
@muhammadhanif can you please test with the latest code in master?

**Comment by muhammadhanif** [comment]
@daN4cat the problems still exist

**Comment by daN4cat** [comment]
I believe this is a duplicate of #2538 and close this one.
