### ISSUE TITLE
NO TRANSACTION DETAILS to the day of transaction if DUE

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2563]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / 
Example: If customer had due amount of  $50 then after 5 days he want to pay it. if you view the transaction details in report module no payment being recieved or notice that he is paid. 
@odiea @jekkos @SteveIreland

**Comment by daN4cat** [comment]
Version please? Fill in the template to make sure we can help you.

**Comment by izeblood** [comment]
20190929181753.3.3.0.0b9a76

**Comment by SteveIreland** [comment]
Just noticed this and see that there is not a lot of activity on this.  

To be honest, I'm not clear on what the issue here.  If the customer hasn't made a payment then obviously the payment isn't going to be reflected in the transaction details report.  

For me this issue needs more explanation so I know what to look for.

**Comment by izeblood** [comment]
By exploring all the areas and modules of the OSPOS 3.3.0- 0b9a76, this issue has been solved.
It is the Issue of a certain transaction being due then, updated for coming days,months, to Cash but the problem is the date of transaction is NOT reflected in the receipt versus the date being paid.
![due](https://user-images.githubusercontent.com/32444665/67656258-3d433e00-f98e-11e9-96ae-428b97be98bb.jpg)

**Comment by izeblood** [comment]
I think, the sale date should NOT change..instead the date of payment in order to make and complete the transaction to become paid must be reflected also.

**Comment by izeblood** [comment]
![low sell](https://user-images.githubusercontent.com/32444665/67663828-4d184d80-f9a1-11e9-84da-18e36699a5a3.jpg)
@SteveIreland what is the uses of Low sell item?
