### ISSUE TITLE
[INFO] Nginx Content-Security-Policy (CSP)

### ISSUE THREAD

**Issue by wd-code** [opensourcepos/opensourcepos#2565]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 0b9a76
- PHP version is: 7.3
- MySQL or MariaDB version is: MarisDB 5.5
- OS and version is: Debian 9
- WebServer is: Nginx 1.14.1
- Selected language is: French / English

### Info

So I've wait so long for this update (and thank you all for that :kissing_heart:).
I was so impatient to test and run it. Everything goes well withe the install (even if I struggle a bit with the wiki).
But when I wanted to add a customer or items the screen was like this: 
![image](https://user-images.githubusercontent.com/6681481/66141637-4b5aa480-e604-11e9-9147-d6d104f4d099.png)

Actually it's my security conf in nginx wh does that. And to bypass this Ive just added a rule in "add_header Content-Security-Policy" were I wright another rule with my URL for "script-src" 'unsafe-inline' 'unsafe-eval'.

Hope it would help others with the same problem.

Ps: English is not my mother lang, feel free to modify this post or ask if it's unclear.

**Comment by wd-code** [comment]
I've forgot to say that I use Let'sencrypt certificats, and to config nginx I used [NginxConfig](https://nginxconfig.io/)

**Comment by wd-code** [comment]
Unfortunatly I can't use Docker on the server. And the issue was from a security policies that was with nginx conf on this server. It's just for those who might have the same security issue.

Yes, a lot missing translation actually, and I'm already working on it. Just finish the common section. And by the way how can I see the context of a string ? Sometimes I get stuck

**Comment by WebShells** [comment]
@wd-code please use weblate link for translations http://translate.opensourcepos.org it's much easier than setting up each string im php files.

**Comment by wd-code** [comment]
I using it but soemtimes I dont know how to translate like *cascade* in the taxes section

**Comment by daN4cat** [comment]
@wd-code thank you for sharing your issue and solution, somehow I was under the impression you had a problem which you couldn't solve.

**Comment by wd-code** [comment]
No I just wanted to share my solution for people who might have the same issue. The traduction trouble is irrelevant to this issue.
