### ISSUE TITLE
company address

### ISSUE THREAD

**Issue by data2base** [opensourcepos/opensourcepos#2568]
Hi!

Can the company address be changed as per stock location on the receipt that will be printed?
We have two shops with separated addresses and would like to include the address and contact number for the stock locations. 

Thanks

**Comment by WebShells** [comment]
Hello @data2base, ospos is currently supporting several stock locations, but it doesnt act as individual shops. 
This is a duplicate issue, please search in closed/opened issue for more information related to multi tenancy. 
1.
