### ISSUE TITLE
Help for better translation

### ISSUE THREAD

**Issue by wd-code** [opensourcepos/opensourcepos#2569]
# Need some info to complete some translation 

### A bit of background history: 
It's been a year, for a french non-profit organization, we install this software, wich is amazing by the way.
This organization help college student who struggle with their money. For the record we decide to not give some free food because it usualy difficult for there self esteeme. So we decided to just sell food or some other supplie 90% off than regular supermarket.

Now that the new 3.3.0 version is out, a lot of new feature was a big improvement for us to our routine, so I quickly install it. BUT ho god no, there so much missing translation :sob:. Well, we not all read (in this case) well english (me the first). So since a moment I knew this was comming, and I wanted to help to the project because it help us a lot I wanted to return the favor. So since reading english for me is a pain in my a** I'm gonna help to translate (in French).

BUT (again...):

### Some trouble to translate
So from time to time I'm stuck in the translation process because sometimes I dont understand.

For exemple yesterday I've struggle to understand some Taxes specifications (and found a minor bug in the process) and that was anwered [here](#2566)

Today I'm stuck with 2 others sequence to translate in the Suppliercomponnent:
When you create a new supplier there're a category with 'Cost Supplier' or 'Goods Supplier' and I really don't know what that's meens.

I've search a bit in the wiki or in the issues and I didn't found a place to ask the meanig of this or that for the help to understand for user or for the people who translate for a more accurate transltaion.

I don't know if there a better way to do this I'm a newbie in the github thing.

**Comment by jekkos** [comment]
Hi @wd-code . Cool to hear about your intentions to improve the french translations!

To be hones this distinction is not very clear to me either, I think @daN4cat is better suited to give you an answer here.

**Comment by daN4cat** [comment]
@wd-code I'll try to find the time today to help you. I understand and speak a bit French and hopefully I can translate it for you.

**Comment by daN4cat** [comment]
Sorry I've been too busy and couldn't really help...
