### ISSUE TITLE
Item list empty in demo

### ISSUE THREAD

**Issue by wd-code** [opensourcepos/opensourcepos#2571]
### Background information
The actual demo template

### Issue / Bug

I don't know if It's because of the messy conf of the demo or it's because it's nut up to date, but when you add a new item it dosen't shows up in the item list.

On my own install of the 3.3.0 release I dont have this issue

**Comment by odiea** [comment]
It appears to work ok after you choose the second stock location

**Comment by wd-code** [comment]
Ok. I may have not get a good look of the config my bad.

**Comment by odiea** [comment]
Who knows what someone did to the first stock location. A mystery. After all it is just a demo

**Comment by wd-code** [comment]
Yes of course. I don't really know when the demo is updated and with which version. But I'm steel feel a bit stupid to not verify if there was another stock location 😂😂

**Comment by odiea** [comment]
No problem. Have a good weekend.
