### ISSUE TITLE
Is OSPOS capable of buy and sell feature?

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2580]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by daN4cat** [comment]
What is a feature for you?
Can you please give some concrete  examples?

**Comment by izeblood** [comment]
Buy and Sell-->selling or buying items outright at a price agreed upon by the buyer and seller.
ex. you buy jewelry at $250 then after 2 months you sell that jewelry at $500. your have $250 profit on that jewelry.

**Comment by odiea** [comment]
You can purchase it thru the Receivings Module then sell it Later thru the Sales Module.

**Comment by SteveIreland** [comment]
It doesn't seem that this is what @izeblood is asking about, but one of the features to add that I had on my to-do list was for a "work order" I needed to be able to order products that would be used to service the work order, and then generate a purchase order for those items and then track the receipt of those items against the work order so that some notification could be generated that would let someone know that the products had been received and work could start on the work order.

That was obviously "out of scope" for OSPOS, but a similar use and probably closer to what this ticket is about would be to sell an item that needs to be ordered, order the item, receive it and somehow know that the received item is for a particular sale that needs to be completed.

**Comment by daN4cat** [comment]
What is different from the temporary item or something like that it was added?
You add the item at sale time with the sale in and sale out prices.

**Comment by SteveIreland** [comment]
@daN4cat you have a good memory.  I didn't even think of temporary items as a possibility here.   When I added that feature I was thinking in terms of items that were being built from other material and possibly other items found on site per the request or need of a customer and being sold as an item (so it was never ordered or stocked).

But I don't know of anything that would prevent it from being ordered.  It certainly should be explored as an option.

**Comment by daN4cat** [comment]
I sense that could do.

**Comment by daN4cat** [comment]
I close this because I believe there is a solution,
