### ISSUE TITLE
ERROR 1005 (HY000) at line 158: Can't create table `myospos`.`ospos_attribute_links` (errno: 150 "Foreign key constraint is incorrectly formed")

### ISSUE THREAD

**Issue by shankar58989** [opensourcepos/opensourcepos#2582]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 7.3.8-1
- MySQL or MariaDB version is: 10.3.17
- OS and version is: ubuntu 19.10
- WebServer is: apache2
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question

Hello Guys,

Previously I had backed up the database from the backup button in the ospos config menu. It gave me a .zip file inside which i got a ospos.sql file.

Today I reinstalled my os and did a fresh install of OSPOS. During the install process, I tried to import the backed up "ospos.sql" file 

I did this below command
mysql -u admin -p -D ospos < /home/myname/Documents/ospos.sql

instead of the below command mentioned in the wiki
mysql -u admin -ppointofsale -D ospos < /var/www/html/database/database.sql

Then I get the below error
ERROR 1005 (HY000) at line 158: Can't create table `myospos`.`ospos_attribute_links` (errno: 150 "Foreign key constraint is incorrectly formed").

Please let me know what I am doing wrong in trying to import a backed up .sql database file and help me with the correct steps.

Thanks

**Comment by daN4cat** [comment]
Are you trying to import an old file in the new database?

**Comment by odiea** [comment]
#2520 has a similar issue. You can follow the links from there. Or just try adding the following before and after you backup.
SET FOREIGN_KEY_CHECKS=OFF;
At top and bottom of the backup and see if it helps.
SET FOREIGN_KEY_CHECKS=ON;

**Comment by shankar58989** [comment]
> Are you trying to import an old file in the new database?

nope. I did a backup from OSPOS v3.3.0. And then reinstalled and tried to restore the backed up ospos.sql file

**Comment by shankar58989** [comment]
> #2520 has a similar issue. You can follow the links from there. Or just try adding the following before and after you backup.
> SET FOREIGN_KEY_CHECKS=OFF;
> At top and bottom of the backup and see if it helps.
> SET FOREIGN_KEY_CHECKS=ON;

will check it out and get back.

**Comment by daN4cat** [comment]
Open the ospos.sql file and write at the top of the file SET FOREIGN_KEY_CHECKS=OFF;
and then go to the end if the file and write SET FOREIGN_KEY_CHECKS=ON;

Rerun the database import has you have done before.

**Comment by shankar58989** [comment]
> Open the ospos.sql file and write at the top of the file SET FOREIGN_KEY_CHECKS=OFF;
> and then go to the end if the file and write SET FOREIGN_KEY_CHECKS=ON;
> 
> Rerun the database import has you have done before.

Thanks you so much. It worked, I got the data back.
Thank you odiea for supporting too.
I will continue to explore the software. Thumbs up.

**Comment by daN4cat** [comment]
Good news.
