### ISSUE TITLE
[Question] Big installation

### ISSUE THREAD

**Issue by encoretwo** [opensourcepos/opensourcepos#2584]
Hey,
I am right now looking into POS systems, and as I am a big proponent of open source, I would like to use opensourcepos, the only question I have, before first trying it out etc, does somebody have any experience with a lot of different of products? (I am looking for something that could take up to somewhere around 15 million products).

**Comment by WebShells** [comment]
Hello @encoretwo that depends on server specifications (memory and processor).

**Comment by SteveIreland** [comment]
I've heard reports that there are some sites using it that have a surprisingly large collection of items (but I don't recall those numbers being anywhere near 15 million).  

The focus of the OSPOS is small businesses, but if you decide to try it please consider sharing whatever changes you need to make for performance improvements.  That could only improve the product.

**Comment by encoretwo** [comment]
Thanks you two for the answers,
well I am a small business :/. It's just that we have a lot of different items.

Well I will share my experience for sure. :)

**Comment by daN4cat** [comment]
It's mainly about the database performance and the query we written.
We optimised where we could but it could be probably better.
See how items view loads and item search work.
That's what you need to test.

**Comment by daN4cat** [comment]
Also try to avoid attributes unless really necessary because that lookup could slow down queries if you feel it's too slow.

**Comment by encoretwo** [comment]
Thanks for the additional information
