### ISSUE TITLE
Error editing article - Serial Number

### ISSUE THREAD

**Issue by blutme** [opensourcepos/opensourcepos#2587]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 0b9a76
- PHP version is: 7.3
- MySQL or MariaDB version is: mariadb-server-core-10.3
- OS and version is: Linux debian Buster
- WebServer is: 
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hello, 
When adding a product on sale that has a serial number by default, an error message appears (red popup-
Error editing article) that does not allow you to add information in the serial code field.

How can fix that error? thanks.

[
![Captura de pantalla (25)](https://user-images.githubusercontent.com/29499149/67339308-8d368680-f4f0-11e9-9f78-8b1ea55e169a.png)
](url)

**Comment by odiea** [comment]
Cannot duplicate. Please red about error reporting.

**Comment by odiea** [comment]
No feedback so I will close this.
