### ISSUE TITLE
Add new user - Process/ Pointers :)

### ISSUE THREAD

**Issue by data2base** [opensourcepos/opensourcepos#2593]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information
.Browser: Chrome
.Server Software: Apache
.PHP Version: 7.0.33
.DB Version: 5.7.28-log
.Server Port: 443
.OS: Linux depro4.fcomet.com 2.6.32-954.3.5.lve1.4.71.el6.x86_64 #1 SMP Fri Sep 6 06:22:16 EDT 2019 x86_64

- OSPOS version is:  3.3.0 - 0b9a76
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

###  Question 

Hi! I'm struggling to add a new user with limits to different stock locations.
What is the procedure to add a new user? What is the minimum requirements for a user and from there i can set the required stock location.

Thanks.

**Comment by mckaygerhard** [comment]
if someone "wants" to property help it! please! due that info can be put in to the (now very broken links) wiki.. due seems the only info that fill in are complicated installation methods, rest are very out of date! please can some one give such detailed instructions? i'm interesting and i do not have enoutgh time for now...
