### ISSUE TITLE
Third Party Integration for store front

### ISSUE THREAD

**Issue by mandeepmavi** [opensourcepos/opensourcepos#2594]
Hi Friends,
I am new here, Want to know did someone tried to use OSPOS with any storefront like ZenCart.
or If OSPOS if able to handle its own online Store front. In the past I was able to use another POS with ZenCart.
I am willing to move to OSPOS.

Also please guide me if I posted this at wrong place.

Regards

**Comment by objecttothis** [comment]
@mandeepmavi We are working on developing code framework for implementing third-party integrations, but keep in mind that this only provides framework for third-party integrations to communicate and interact with OSPOS.  It doesn't change the base of what OSPOS is.  For example, it is not currently supported to turn OSPOS into a customer storefront, but with the 3.4.0 changes, you will be able to write a third-party integration to communicate data with an API for example.  This would accomplish the task, for example, of telling your online website about new inventory or a change in inventory when a new item sells.

For the security of data, all third-party integrations would be a part of the repository and subject to the same code reviews.  That is, if people want their third-party integrations available for everyone to use.

Please re-open if this doesn't answer your question.
