### ISSUE TITLE
OSPOS 3.3.0 HTTP ERROR 500

### ISSUE THREAD

**Issue by jcreen1977** [opensourcepos/opensourcepos#2595]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: ?
- PHP version is: 7.2
- MySQL or MariaDB version is: MySQL 5.7
- OS and version is: CentOS 7.5
- WebServer is: Apache/2.4.41
- Selected language is: English 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I initially installed Open Source POS Version 3.2.3 using Softaculous on my CPANEL VPS.  Version 3.3.0 became available on 9/29/2019 and I want to upgrade.  I performed a clone of the existing install and put into another directory.  I had Softaculous install version 3.3.0 into the initial directory and imported the backed up database using PHPMYADMIN into the new database.  Customers, Inventory, and Settings are displaying correctly.  However when I perform a sale, once I hit the green "complete" button, it displays a "This Page Isn't Working.  <Site Name> is currently unable to handle this request.  HTTP Error 500."  The cloned instance of Version 3.2.3 is fully functional.

**Comment by jekkos** [comment]
Can you enable error logging so you can see the actual problem?

In public/index.php change production with development

**Comment by jcreen1977** [comment]
![Error](https://user-images.githubusercontent.com/57203053/67920706-36c1eb80-fb73-11e9-8b30-a5257effc601.png)
This is the error that was returned.

**Comment by daN4cat** [comment]
Disable only_full_group_by. If you searched the open issues you would find how. I don't remember from the top of my head the issue number at the moment.

**Comment by daN4cat** [comment]
Probably the solution to this problem would be to do a group by item_id. I see if I can find the time over the weekend to give a try.
