### ISSUE TITLE
Last used Invoice Number

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2597]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

#############################################################################
https://demo.opensourcepos.org/config
![Screenshot_2019-10-31 Open Source Point of Sale Powered by NMP 3 3 1](https://user-images.githubusercontent.com/29256343/67951872-95a25780-fba9-11e9-9e54-161f26ef675d.png)

Invoice / Last invoice number used.
What is it for here? It is only to remind me that this was the last invoice number, or that when I start to invoice it will continue after this last number of invoices.

In some governments you cannot repeat or omit the invoice numbers, if you do this you can pay very large fines.
It would be useful for this to work in order to put this last invoice number and continue after this.

**Comment by SteveIreland** [comment]
The following is a snippet of documentation from the wiki.  If you are interested in using the "last number used" then you will want to focus on the {ISEQ} code.

**Sales Invoice Format** - This is how the invoice number will be formatted when it is assigned.  There are three codes that you can provide that will be translated to a particular value.  Normally only one is used.
- *$CO or {CO:9}* - This will be replaced with the number of sales records that have an invoice number.
- *$YCO or {YCO:9}* - This will be replaced with the number of sales records with rollover each year.
- *$SCO or {SCO:9}* - This is a count of the number of suspended sales records with an invoice number.
- *{ISEQ:9}* - This will use the "Last invoice number used" configuration value to build the invoice when the sale is complete.  When the sale is complete the value is incremented and replaces {ISEQ}.  If the invoice number should be a fixed number of digits then the number of digits to use can be indicated using the following format {ISEQ:9} with the single numeric digit after the colon representing the number of digits that should be returned.  It can be up to 9 digits long with 0 indicating that the number should be as long as necessary to hold the full value and {xxx:0} and {xxx} will be treated the same.
- *%y* -  The two digit year from the date of sale replaces the value %y.  In fact, there are numerous "%" tokens that are based on current system date and time.  They are listed at http://php.net/manual/en/function.strftime.php

For example, If the value "INV-%y{ISEQ:6}" will render the invoice number INV-17000032 if prior to generation the value of the last invoice number used is 31 and the year of the sale is 2017.
