### ISSUE TITLE
ngnix contrainer not starting

### ISSUE THREAD

**Issue by soulimane-mammar** [opensourcepos/opensourcepos#2598]
From the latest release I issued  `docker-compose build` then `docker-compose up` and unfortunately the ngnix contrainer fails to start with the error `envsubst: error while reading "standard input": Is a directory`

**Comment by daN4cat** [comment]
Have you read the instructions how to use it?

Use the install script under bin/ folder

**Comment by soulimane-mammar** [comment]
There is no bin folder in the release zip file!! am I missing something ??

**Comment by daN4cat** [comment]
Sorry my bad, I meant to say docker/ folder.

**Comment by daN4cat** [comment]
There install-local.sh and install-server.sh.

Try install-local.sh, however you need to install envsubst utility.

**Comment by soulimane-mammar** [comment]
Unfortunately in the release zip file the docker folder is empty perhaps I have to copy it from the git repo!!

**Comment by daN4cat** [comment]
Yes, copy it from GitHub master. I didn't realise it was empty in the release package file.

**Comment by soulimane-mammar** [comment]
still not working !! and this time it's because the url `https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf` is not valid the `option-ssl-ngnix.conf` file has moved to a new location `https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx.conf`

**Comment by soulimane-mammar** [comment]
One last thing... I had to create a dummy `error_log.log` file in the ngnix folder otherwise docker-compose will create a folder with the same name and ngnix will not be happy with that

**Comment by daN4cat** [comment]
Re last comment, that should be in GitHub too. I need to check how the release package is generated.

Thanks for the feedback and I'll check the other issue too.

**Comment by daN4cat** [comment]
By the way, have you managed to get it to work?

**Comment by soulimane-mammar** [comment]
Yes it's working now

**Comment by romuloslv** [comment]
@soulimane-mammar the path https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx.conf seems no longer on. I can't turn on the nginx container, what did you do to around?

**Comment by daN4cat** [comment]
I need to look into this and fix.

**Comment by daN4cat** [comment]
I fixed the path in the docker scripts
