### ISSUE TITLE
Sale error in form amount tendered

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2602]
this it's since 3.2.2 see picture, if the amount of the sale are complete why it's that label still present?

pufff! :1234: 

![Captura de pantalla de 2019-11-10 14-07-30](https://user-images.githubusercontent.com/1571724/68548472-cd887680-03c3-11ea-900b-02ec636650d0.png)

**Comment by odiea** [comment]
If the Cashier makes a mistake it can still be corrected. You can change your version as needed.

**Comment by mckaygerhard** [comment]
err seems you dont understand.. it said amount tendered and still show it! very funny @odiea

**Comment by odiea** [comment]
![2019-11-11 12_57_06-Window](https://user-images.githubusercontent.com/10962177/68616755-eb68e080-0482-11ea-944b-644534f77e3c.png)

**Comment by SteveIreland** [comment]
@odiea I cannot replicate the example that you  provided.  How did you make that happen?

In regard to the the original complaint, the label "Amount tendered" applies to the data entry field as well as the list of payment types found in the table.  Admittedly it could b a little more cosmetically pleasing, but I believe someone must have asked that the "Complete" button be added above the list of payments which makes it a little visually "off", but not a really big deal.

I don't believe anyone will be volunteering to fix this minor issue. But when this is rewritten it should be taken into consideration.

**Comment by odiea** [comment]
It is a bit annoying to see a hanging amount Tendered there. So to bypass the Register.css I changed line 471 in register.php to the following.
```
<?php echo form_input(array('name'=>'amount_tendered', 'class'=>'form-control input-sm disabled', 'disabled'=>'disabled', 'value'=>to_currency($payments_total), 'size'=>'5', 'tabindex'=>++$tabindex, 'onClick'=>'this.select();')); ?>
