### ISSUE TITLE
Bug: This page isn’t workinglocalhost is currently unable to handle this request. HTTP ERROR 500  when click Report->Detailed ->Transactions and select Transaction Range - All Time It can't load big data like 31173 transactions

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2604]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  
HTTP ERROR 500 will display when click Report->Detailed ->Transactions and select Transaction Range - All Time It can't load big data like 31173 transactions

**Comment by daN4cat** [comment]
It's a PHP timeout issue most likely. Can you please check the timeout set in your php.ini config

**Comment by daN4cat** [comment]
Anyway, the data loading should be paged. We know that we have that issue but it requires some work.

**Comment by izeblood** [comment]
> It's a PHP timeout issue most likely. Can you please check the timeout set in your php.ini config

the default_socket_timeout=is set to 30 and i change it to 9999 but still page isn't working...

**Comment by daN4cat** [comment]
Right, and what if you select a slight smaller time range?

Also it could be a memory issue on server side, or too much data to send over a HTTP response.

**Comment by izeblood** [comment]
its working when i tried smaller time range....

**Comment by jamrogers** [comment]
I fixed this by increasing max_execution_time to 120 (2 mins) in php.ini running apache2, you may have to experiment
