### ISSUE TITLE
Logo colors different from system button colors and favicon

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2607]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 452f2d
- PHP version is: 7.3.6
- MySQL or MariaDB version is: 5.7.26
- OS and version is: FreeBSD 11.2-U1
- WebServer is: Apache 2.4
- Selected language is:  English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug

- The color for the new logo blue is #1071b9 but the buttons are all #3399cc.  They should be the same blue.  The easier would be to change the logo, but IMO the more aesthetically appealing would be to change the buttons to #1071b9.
![color-difference](https://user-images.githubusercontent.com/17935339/68739229-c64eac00-0601-11ea-9023-a66fe2a9ef9b.jpg)

- The corners of the favicon file are not transparent so it renders white corners rather than transparent corners.  You can see in the image below that the green arrow logo is with transparency and the red arrow logo is without.

![favicon-transparency](https://user-images.githubusercontent.com/17935339/68739232-c9499c80-0601-11ea-8cf6-43d96a72ed21.jpg)

**Comment by daN4cat** [comment]
Go for the change of button colour fix.

Agreed about favicon transparency.

Can you make it for 3.3.1?

Thanks for the help as usual.

**Comment by objecttothis** [comment]
What is our 3.3.1 target release date?  Can you make available the original hi-res file?  That will be better for me to edit than the smaller logo.  I will generate the favicon from the fixed logo.

**Comment by objecttothis** [comment]
Also, I would like to generate the favicon logo without OSPOS since it isn't legible in the favicon.  Instead I would move the OP so that it's vertically centered.  Thoughts?

**Comment by daN4cat** [comment]
I don't have any hires version I'm afraid. I copied and pasted the image from the post related to the icon redesign.

**Comment by objecttothis** [comment]
@daN4cat did the favicon change somehow not make it into 3.3.1?  I just downloaded and installed 3.3.1 and it appears that the color correction on the login screen is in there, but the favicon is the one without transparency and OSPOS removed.

**Comment by objecttothis** [comment]
OK #2720 is ready for review and merger.

**Comment by daN4cat** [comment]
Merged. I close.
