### ISSUE TITLE
Discount using value not percentage

### ISSUE THREAD

**Issue by lutfiajib** [opensourcepos/opensourcepos#261]
Is possible give discount using value? not percentage like this

**Comment by daN4cat** [comment]
You can always type directly the discounted value and push edit button.
But that requires some mental calculation. Changing the purpose of the field will require a chnage in the configuration, I assume you want one or the other, or are you after both at the same time?

**Comment by lutfiajib** [comment]
i want value. but i'm sure, some people want percentage. 
What about save this discount type option on " Store Config"?
the default discount is percentage. we can change through this option

**Comment by daN4cat** [comment]
Yes, that was the point, but the issue is the mixed scenario where people want % and fixed value.
For your case it sounds like you just want fixed value.

This goes in the todo list, but not sure when this can be implemented.

**Comment by sgr1875** [comment]
I have modified the way i want i can post the screen shot and code if you guys interested.
![discount](https://cloud.githubusercontent.com/assets/17928628/13948835/61fce546-f048-11e5-9e6f-c88543066afa.png)

sorry if i am not suppose to reply on closed thread.

**Comment by ntkhan** [comment]
@sgr1875  I need this code , please if you can provide it to me.

**Comment by asadjaved63** [comment]
@sgr1875 i need this code please provide me

**Comment by daN4cat** [comment]
Somebody needs to work on this and contribute it to the project.

**Comment by ishtiaquesarwar** [comment]
There is no straight guideline or code snippet to fix this thing for version 3.0.0.

**Comment by daN4cat** [comment]
#302

**Comment by Ibnumarjan** [comment]
@sgr1875 I need this code please help me. Discount for total......

**Comment by erastus** [comment]
#2091  pull request discount on sales not percentage

**Comment by daN4cat** [comment]
Solved in #2061

**Comment by muhammadubaid001** [comment]
@sgr1875 hi, I need the code for Total discount.

Thank you.

**Comment by odiea** [comment]
There is no code unless you submit it.
