### ISSUE TITLE
 Scales and Scanners: Price Embedded Barcodes

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2612]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Question 

I need more clarification on the sale register and weighing barcode: 
1. what type of barcode should we use for both sales register and weighing ?
2. how to setup Price embedded barcodes?

**Comment by izeblood** [comment]
let me add... I already read the wiki about weighing scale using embedded barcode issue but I really don't know where and how the 2 characters for department? what this department for?

**Comment by WebShells** [comment]
@izeblood personally I've answered several issues related to weighing barcodes, please try to search different issues, department is to be set from scale, the printed barcode will have first 2 digits as department ( a scale option)
We set the default department in ospos to 02, so all barcodes starting with 02 are considered as weight barcodes and embed the quantity in quantity field. 
Let me know if you need more help, or close if you think it's fine...

**Comment by izeblood** [comment]
> @izeblood personally I've answered several issues related to weighing barcodes, please try to search different issues, department is to be set from scale, the printed barcode will have first 2 digits as department ( a scale option)
> We set the default department in ospos to 02, so all barcodes starting with 02 are considered as weight barcodes and embed the quantity in quantity field.
> Let me know if you need more help, or close if you think it's fine...

Thank you @WebShells for your concerned regarding this matter. all issue being raised is CLEAR of what weighing scale to be use; options to be configured in both sales modules and weighing scale... but I solved this issue already...
