### ISSUE TITLE
Possible to prevent complete of a sale until a payment type is selected

### ISSUE THREAD

**Issue by bricas** [opensourcepos/opensourcepos#2614]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 0b9a76
- PHP version is: 7.3.11
- MySQL or MariaDB version is: 5.7.28
- OS and version is: Alpine 3.10
- WebServer is: Nginx
- Selected language is: English
- (If applicable) Docker installation: Yes, custom.
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

On the sales screen, after you select an item to add, the complete button automatically appears. 

Generally our items are variable in cost, so we need to enter a price first. However, if the user puts in a price but doesn't shift focus OFF of the field, then they can press "complete" and it will register a transaction for the right amount, but without a payment type.

Perhaps I'm missing something, but I would like to force the user to have to put in a payment type before being able hit "complete."

Thanks in advance.

**Comment by odiea** [comment]
If the price stored in the Items is zero then yes it will show the sale as complete.

**Comment by bricas** [comment]
I guess that makes sense -- but, that also means I have to set a default retail price of 0.01 in order for the "complete" button to be hidden?

**Comment by odiea** [comment]
I would set a standard price then either give the customer a set or percent discount or discount it at the Register.

**Comment by odiea** [comment]
The other option that might work would be to go into Configuration and check the following Change Cost Price (Receiving) then update the Items in Receivings. See if that works. I believe it averages out the New cost.

**Comment by bricas** [comment]
I think the "0.01" base cost makes the most sense for us. Basically, all of our items are variable in cost (example: book replacement cost, dependent on the book) so this work-around allows us to force a payment type while keeping the cost "flexible."

Thanks.

**Comment by odiea** [comment]
This appears to be resolved so I will close this. Thanks
