### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Joy6969** [opensourcepos/opensourcepos#2616]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hi,

I came across your work via GitHub. I have bought a similar php application from someone who promised a lot and did not do anything. Took the money and conned me.

I need someone to help me validate the files I have and help me set it up on cpannel.

Looking at your work what you are doing free and for the community felt that I can seek help from you.

Please share your contact details so that we can discuss further and solve me issues.  If you are alright with it.

Looking forward to hearing from you

**Comment by WebShells** [comment]
Hello @Joy6969, please fill in the issue template or state the version of ospos you are using so we could help in a better way.
At first, try searching the solved issues in case any of your needs is covered or not, read installation instructions under cPanel section it might help you. .. 
For the help, it depends who is available or if anyone from the contributors/collaborators is willing to do what are you asking for.

**Comment by Joy6969** [comment]
Hi Team,

I have a similar no POS that I purchased from someone online and I was
conned. The person shared the files but didn't help me.setup I have minimal
technical background and need help in setup it up if it full php files. If
not I would like to use your services.

I am reai to share it you guys for further use and help the community use
that free of cost.

But I have paid a big amount for it and got cheated 😔.

Kindly help me.

**Comment by WebShells** [comment]
@Joy6969, please refer to [Installation instructions](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) under cPanel & SSH section for automated setup in case your technical background isn't enough for advanced setup. 
The mainly needed configuration are to be answered during the process.
If the installation didn't run or failed for any reason, please reopen this issue, will close...
