### ISSUE TITLE
Adding support for keyboard shortcuts and Function keys.

### ISSUE THREAD

**Issue by DeepRootedCoder** [opensourcepos/opensourcepos#2618]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

New Feature Request:
I really like OSPOS but one thing that I have noticed is that most people prefer to use a POS through a keyboard. Performing tasks with a keyboard are generally a lot faster and easier. 

I think that it would be really great if we could add some shortcuts like these in the sales register mode:

F12 : Complete Transaction.
F11 : Collect Payment.
F10 : Place Cursor At Search Item Bar.
Ctrl+P : Print Invoice.
F1 : Select Next Item.
F2 : Select Previous Item.
Ctrl+I : Increase Quantity of selected item.
Ctrl+D : Decrease Quantity of selected item.

**Comment by WebShells** [comment]
This is a duplicate of #1630 #1083 #1964 you can use the suggested solution by @nvk1990 in #1630 or try this library https://mattytemple.com/uncategorized/shortcut-js-add-keyboard-shortcuts-to-your-site/
Will Close...

**Comment by WebShells** [comment]
A final stable fix was applied to this issue through PR #4532
