### ISSUE TITLE
AdminLTE

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2620]

**Comment by WebShells** [comment]
@andriux1990 ?

**Comment by odiea** [comment]
Looks good. Are you going to offer to share this code?

**Comment by andriux1990** [comment]
Yes, but it's not ready yet. I'm missing the kit, which is super difficult because of the way it was done

**Comment by WebShells** [comment]
Why the topic was edited and closed? I mean what was the point of this thread if it wasn't a proposal, a suggestion for a change, or bug/help request ? 🤔

**Comment by izeblood** [comment]
I think this is a proposal @WebShells... OSPOS+AdminLTE to the next level

**Comment by WebShells** [comment]
@izeblood please repush the images in order to be displayed back or open a new issue with shots uploaded.

**Comment by izeblood** [comment]
![adminlte1](https://user-images.githubusercontent.com/32444665/73321189-acc21580-427c-11ea-805c-15a07bab6466.jpg)

**Comment by izeblood** [comment]
![adminlte2](https://user-images.githubusercontent.com/32444665/73322005-09263480-427f-11ea-8e8c-bd5a0b2e8dba.jpg)
