### ISSUE TITLE
UPI payment integration

### ISSUE THREAD

**Issue by javidmuhammed** [opensourcepos/opensourcepos#2621]
I would like to integrate UPI payments with the ospos.  The receipt should be printed only after the upi payment is completed. Is it possible to do with the existing code base, or new code has to be implemented?

**Comment by daN4cat** [comment]
New code has to be implemented

**Comment by javidmuhammed** [comment]
Right.... Is there any work going on for that. Any feature in progress. would like to pitch in..

**Comment by daN4cat** [comment]
I'm afraid you need to find somebody to work on this for you.

**Comment by javidmuhammed** [comment]
cool.. Thanks...
