### ISSUE TITLE
asking for a tutorial video or step by step directions. Index of / then a list of the files!

### ISSUE THREAD

**Issue by Mahiir-Nbo** [opensourcepos/opensourcepos#2623]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

First and foremost I would like to thank the github platform and the many guys and gals working for the community. Ive been at this source code for several weeks now and by that you can understand im a newbe lol!! ive read articles followed youtube video and I just cant seem to crack it! my question is simple and im sure everyone whos newbe and the following ones as well> If you can do a step by step tutorial (preferably for windows 64 bit & also preferably on video) the direction you have on here assumes that everyone is a professional programmer. and as much I like to think so i'm not. I have reached as far as "index of / then a list of all list of all the files below". Please & Thank you!!

**Comment by daN4cat** [comment]
Hi there, this is really a wide open question. What is that you need to know as first?

**Comment by Mahiir-Nbo** [comment]
@daN4cat  thank you so much for your quick response. Here are my question/issues.

4. unzip and upload Open Source Point of Sale files to web server (I have created an FTP page to upload it to but when i go to that page it gives **Index of / a list of the documents**
5. Modify application/config/database.php and modify credentials if needed to connect to your database (I have no idea what this means! I know how to modify it but how do i connect it to my database, and which database is that? Mysql or my pc's database?)
6. Modify application/config/config.php encryption key with your own (I dont have an encryption key, atleast i dont think i do. I also need assistance with this step)
7. Go to your point of sale install public dir via the browser (Does this mean I have to buy a domain name or can I use localhost? and if im interested in running this software in a different location with different employees what do i do?(

again i apologize im new to the game i want to thank you so much for your assistance!

**Comment by jekkos** [comment]
I think there is an issue in your webserver setup. The webserver is not calling php to render the index.php for some reason. Do you use a php enabled shared hosting ?

**Comment by jekkos** [comment]
How do you mean `run it in a different location`? You could try to use different stock locations and grant each employee access to only those she is active in.

**Comment by Mahiir-Nbo** [comment]
@jekkos I use Xampp which php is enabled. Ive watched a Linux based web tutorial even though im on windows. But that was the only youtube video i could find. I have provided the link at the bottom of this comment. Everything was clicking on all cylinders until he go to "Localsite.net" which is at the 8:00 minute mark.  2nd. I have a wonderful business idea that his software would work perfectly for. Im willing to pay more than just a cup of coffee :-). If i was to have few shops that I own. and lets say i have different employees working at those different shops. Can I have multiple users using this software independent of each shop. So shop 1 has three employees. One user name and password with different accesses for each user depending on their title. and shop 2. has three employees. one user name and password with different accesses for each user. My question is, can I have different shops utilize this software without intertwining their data. Because each shop is unique thus the data that comes out of that should be independent of the data that comes from the second shop. I dont know if im making sence??

**Comment by Mahiir-Nbo** [comment]
This is the link to the above comment.

https://www.youtube.com/watch?v=LNqvxH3Bx5o&t=14s

**Comment by jekkos** [comment]
If you want to keep the data separated then the stock location solution will probably suffice here.

Windows setup procedure might be very different from Linux. Maybe you can try to follow the cloud install procedure instead?

**Comment by SteveIreland** [comment]
That video is a couple of years old and is out of date and unfortunately will lead you to failure right out of the box.  The README is the place to start.

**Comment by WebShells** [comment]
I'll try to upload tutorials for usage maybe and couple of videos over the web and link them... But this will definitely take some time 🙆‍♂️

**Comment by Mahiir-Nbo** [comment]
@jekkos Will the cloud procedure require me to buy a doman and cloud service? I dont mind buying it I just would like to know if I take that route do I also have to buy a domain name? Id prefer videos to follow step by step because each step in unique and if I have visual video available I can see where I went wrong and fix it.
@SteveIreland  yeah believe me ive read the README  and every article i could find and video. I'm new to this and have zero experience in terms of a formal education in regards to computer science degree. I want to teach myself and grow slowly but surely. 
@WebShells looking forward to it. How long do think it might take you? Would be doing a windows installation? if so, assume the viewers are completely NEWBEES and let us learn from your expertise.

**Comment by odiea** [comment]
The quickest way to learn on Windows would be to download xxamp and install the Program into it.

**Comment by jekkos** [comment]
Yes you might also need a domain name in that case. You would need to point a dns record to the ip of your server 

You can also just access it directly by ip but that might not be very convenient.
