### ISSUE TITLE
Add boolean attribute type

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2625]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### New Feature

Currently we have DROPDOWN, GROUP, DECIMAL, TEXT and DATA Attribute types, but we have no BOOLEAN attribute type.  The idea is that the data behind the scenes would be TRUE or FALSE, but would be represented by a checkbox on the item GUI.

Example attributes that could benefit from this type of attribute: "Show on Website", "Will Reorder" and "High Request Item".  Essentially any attribute where the value possibilities are two would benefit from having a boolean type.

**Comment by jekkos** [comment]
Makes sense! I realize now i have such a 'custom field' already somewhere that I'd convert to this type.

**Comment by objecttothis** [comment]
I'm going to have to call the attribute type CHECKBOX because bool is a reserved word in both MySQL and PHP and boolean is a reserved work in Mysql.

**Comment by jekkos** [comment]
Yeah actually I tried to add this type of control, but it looked a little weird imho (having a label and then just a checkbox next to it).

Indeed name it checkbox would make more sense.

**Comment by objecttothis** [comment]
@opensourcepos/org We need to decide on how we want the CSV import to process certain values in OSPOS CHECKBOX attribute types.

0:
NULL: Do not create attribute.
FALSE:
"": Do not create attribute.
[spaces]: Do not create attribute.
1: Create attribute and mark it as checked.
TRUE: Create attribute and mark it as checked.
[All other values]: Create attribute and mark it as checked.

From the list above you can see that I have behaviors for most of the possibilities, but there are two questions that remain:

1. do "0" and FALSE values need to create the attribute and leave it as unchecked or should they not create the attribute at all?

2. Are there any possible values that I have forgotten?

**Comment by objecttothis** [comment]
@daN4cat @jekkos  thoughts on my above comment?

**Comment by objecttothis** [comment]
OK, I am submitting the pull request with 0 and FALSE creating a checkbox but setting it's value to unchecked (0).  If people feel strongly that we should do something else, then I will come back to it at that time.

**Comment by objecttothis** [comment]
Done and in the master.

**Comment by jekkos** [comment]
Ok just found the time to read this. You could maybe argue that a 0 would be decimal type (and false checkbox).

**Comment by objecttothis** [comment]
> 
> 
> Ok just found the time to read this. You could maybe argue that a 0 would be decimal type (and false checkbox).

Yes, I ended up parsing 0 and FALSE in a way that creates the attribute and marks it unchecked.  Is that what you mean?
