### ISSUE TITLE
Quantity fields are parsing decimals using currency decimals amount

### ISSUE THREAD

**Issue by nayerd** [opensourcepos/opensourcepos#2626]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: Latest
- PHP version is: 7.0.23
- MySQL or MariaDB version is: 5.7.19
- OS and version is: 
- WebServer is: WAMPSERVER 3.1.0
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

BUG: 

On file application/controllers/sales.php : line 477
The product quantity is calling the parse_decimals function wich is created to parse the decimals from currency fields and not from quantity fields. 

The bug limits the amount of decimals in the quantity field. It is limited by the currency decimal amount. In my case Euro (2 decimals) I can't sell items with more than 2 decimals. For example I can't sell a quantity expressed in grams as a part of a kilogram (0,001 kg).

Proposed solution: create a parse_decimals for general purposes with an editable field in the configuration. Maybe this issue is in more places I haven't cheked yet.

Than you so much for your effor.
Maybe is already solved in future releases.

**Comment by SteveIreland** [comment]
Good catch @nayerd. There appears to be several places where this coding error can be found. 

Unless someone else want's to take this earlier I'll take care of this during the coming weekend.

**Comment by odiea** [comment]
Thanks @SteveIreland . I was beginning to think that this was turning into abandon ware.

**Comment by SteveIreland** [comment]
A pull request has been submitted for this.

The installation zip is on bintray at https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20191222160607.decimal_parsing_fix.230d82.zip

**Comment by daN4cat** [comment]
Fixed and in master.
