### ISSUE TITLE
Current Demo has the following error.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2627]
A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: core/CodeIgniter.php

Line Number: 518

**Comment by daN4cat** [comment]
Is the database config fine?

**Comment by daN4cat** [comment]
Is the demo server fine?

**Comment by odiea** [comment]
No it is not. The error is the only thing that shows when trying to log on. No idea about the database config.

**Comment by daN4cat** [comment]
It could be that the database is down.

But this is the demo only.

**Comment by odiea** [comment]
Yes Demo only.

**Comment by peter279k** [comment]
I'm looking for the sale data management system.

When I want to visit the demo site, I also got the same error.

Please fix this and I can look at demo to decide whether this system is proper :).

**Comment by jekkos** [comment]
I redeployed from my phone. Can you check again?

**Comment by jekkos** [comment]
Seems fine again. I won't look into the root cause further add I'm still traveling in NZ atm. I will try to
Take a closer look Probably beginning next year.
