### ISSUE TITLE
Two BootsrapTables on One Page

### ISSUE THREAD

**Issue by musaddiq-pk** [opensourcepos/opensourcepos#2628]
Hi, I want to have data two tables on one page. E.g show sales and customers on one page.
As table is populated with _id_ so it's not loading data when I use other table. Required scenario is attached as snap.

Regards
![multi-tables](https://user-images.githubusercontent.com/11736070/71254415-ade25780-234c-11ea-9632-3bb002829788.png)

**Comment by jekkos** [comment]
Ok so what is the question? As you say you will need to work around that id issue.

**Comment by musaddiq-pk** [comment]
I was asking for a solution. But temporarily I managed by copy some code in opensourcepos.min.js.

**Comment by jekkos** [comment]
I won't recommend editing a minified file, it will be overwritten once you rerun the build. I think it'll pay off to try and setup the whole environment as it should to track your changes.

**Comment by musaddiq-pk** [comment]
Okay, so I will extract these changes in a view file.
