### ISSUE TITLE
delete sales button is not working

### ISSUE THREAD

**Issue by pedrobuck** [opensourcepos/opensourcepos#2630]
Hello, the delete sales button has stopped working after upgrading from OSPOS 3.2.3 to 3.3.1.

I can not delete any sale because I click the button, closes the window and nothing happens. What can it be?

**Comment by odiea** [comment]
Did the database get updated? If it did then you should be able to see in database ospos_sales-sale_status

**Comment by pedrobuck** [comment]
Yes, I ran the necessary update tables, after that the delete button stopped working.

**Comment by odiea** [comment]
Are you able to open your database and see if that is there?

**Comment by pedrobuck** [comment]
yes i have access to database and tables

**Comment by daN4cat** [comment]
@pedrobuck you need to grant the user permission to delete a sale. Check under Employee and Permissions tab, scroll down to sales and you'll see an "Allow delete". Check that to allow deletion of sales.

**Comment by pedrobuck** [comment]
Hello, the user already has delete permission. The problem is in the app. After the update it was no longer possible to delete sales.
