### ISSUE TITLE
Portuguese(Brazil) language and Demo server

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2632]
The Demo server always seems to mess up when this language is used. You have to enter Home or Office to get anything to show after login. If someone gets time could they try and figure this issue out. Thanks

**Comment by jekkos** [comment]
Hm probably a wrong escape sequence in the language files

**Comment by jekkos** [comment]
The language folder name in CI itself was changed, I have now changed our code to reflect that.
