### ISSUE TITLE
Importing Items CSV Issue

### ISSUE THREAD

**Issue by AlaaEldinMohamed** [opensourcepos/opensourcepos#2636]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 10.1.38-MariaDB
- OS and version is: Windows 7
- WebServer is: Apache (XAMPP Version: 7.3.2)
- Selected language is: ar_EG (Arabic)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I hope someone could help with importing items issue.

-I have downloaded the import_items.cvs template from within importing items pop-up menu (attached the downloaded template)
- now i filled the file with sample items to check the import function attached sample CSV file)
- but when i have tried to import items it always gives an error and items were not imported.
- i have checked documentations and issues and i don't see a consistent items import CSV template !
- i need to know how to import new items using import features.
(attached also the application error log for further investigation)

By the way i have just downloaded and installed OSPOS 3.3.1, Actually it was not an easy task and i was success after several trials and searching web and documentations, however i do like the application and i think it will have a great future with your support guys.

[Final.txt](https://github.com/opensourcepos/opensourcepos/files/3995152/Final.txt)

[log-2019-12-23.txt](https://github.com/opensourcepos/opensourcepos/files/3995159/log-2019-12-23.txt)

**Comment by WebShells** [comment]
@AlaaEldinMohamed thank you, so it's a fresh install or an upgrade from previous version?

**Comment by AlaaEldinMohamed** [comment]
@WebShells Thank you for your replay, it was a fresh installation.

What i just need a sample filled import_items.csv for release 3.3.1. this would help my trials to import items.

Thanks in advance and regards

**Comment by AlaaEldinMohamed** [comment]
@WebShells Hello Dear, after several investigations i discovered it was due notepad++ not saving at UTF-8 charset (I had to use Notepad++ to replace the Tab within text with Comma).  So now i managed to import some items after i converted imported items files to UTF-8 using normal notepad.
NOW another issues want to discuss OR raise, i can not delete fully items from the application to re-import them, OR update their stock level. could you please try to help with this issue ?

Thx & Regards

**Comment by WebShells** [comment]
Updating stock levels can be done only through items module one by one, or if you'd like a workaround is to use an sql query to update item_number rows in ospos_items where deleted = 1, set it to ''.
Then re-import the csv again.
I'll close, please reopen in case you need further assistance.
