### ISSUE TITLE
Setting a value in $config['cookie_prefix'] causes error 403 due to CSRF failing to be passed as param

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#2638]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1 
- OSPOS git commit hash is: 
- PHP version is: 7.2 and 7.3
- MySQL or MariaDB version is: MySQL 5.5 and MariadDB 10.3 
- OS and version is: CentOS and Ubuntu
- WebServer is: Apache
- Selected language is: English (GB)
- (If applicable) Docker installation: Tested with both
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

In application/config/config.php, setting the following:

$config['cookie_prefix'] = 'myprefix';

(where myprefix could be any), causes the CSRF to fail and not pass the CSRF token as param in HTTP POSTs.
The return error is a 403.

I believe this case should be managed, however for the time being do not set any value as follows $config['cookie_prefix'] = '';

**Comment by jekkos** [comment]
@daN4cat I have briefly tested this scenario by filling a cookie_prefix value. Form submissions work without any issue. I also tried this in a new fresh incognito tab.

On which request do you see the 403?

**Comment by jekkos** [comment]
Also the csrf cookie name itself can be configured in the `config.php` and exactly that value is used for fetching the token's value.

**Comment by daN4cat** [comment]
Try editing an item and save it and you get the failure with the form not closing.

I put in the config a value like  "ospos3". I also set the domain  but that doesn't seem to cause any issue.

**Comment by daN4cat** [comment]
@jekkos yes, that fixes it. Thanks.

**Comment by daN4cat** [comment]
Merged
