### ISSUE TITLE
NO NEW ITEM FORMA

### ISSUE THREAD

**Issue by buckbowl** [opensourcepos/opensourcepos#2640]
Sorry for asking again about this, I know there is an open topic, but no answer has helped me ... The box for new item does not appear .. please help, my server is on viewen.com and my website is https : //dcjeans.store/tienda

![no item](https://user-images.githubusercontent.com/59344753/71562943-76129880-2a4d-11ea-9207-76bacd5528e0.jpg)
![system](https://user-images.githubusercontent.com/59344753/71562944-76129880-2a4d-11ea-99d0-513217df4cdf.jpg)

**Comment by odiea** [comment]
If you see the item edit dialog box empty starting with version 3.3.0, please disable only_full_group_by option from MySQL/MariaDB. See issue #2538.

**Comment by buckbowl** [comment]
Thanks, I'm not very good with databases .... How do I do it ?? from cpannel ??
