### ISSUE TITLE
how to use weigh barcode in ospos

### ISSUE THREAD

**Issue by akhilnasi** [opensourcepos/opensourcepos#2642]
Hi,
I have gone through the weigh barcode issues. that i cannot use the ospos for vegetable and fruits.
I have already seen the same issue but i coudnot solve that using the previous solution that you have discussed that's why am opening one more issue.

Please if anyone can find me the solution for this it will be greatfull.
Thank you

**Comment by WebShells** [comment]
Hello @akhilnasi, 
Did you try checking our wiki ? Please check this page [Wiki Weighted Barcode Documents](https://github.com/opensourcepos/opensourcepos/wiki/Weighted-Barcodes) and let's know in case more explanation is needed.
Will close.
