### ISSUE TITLE
How to help translate on weblate ?

### ISSUE THREAD

**Issue by simobenso** [opensourcepos/opensourcepos#2643]
Hello, 

I'm trying to correct/add some missing strings on the french translation but I'm unable to do so, here the error that I get :

"This translation is currently locked for updates."

Can you help please ?

**Comment by WebShells** [comment]
Hello @simobenso , 
The translation is open for every user who'd like to contribute, just follow the below link:
https://translate.opensourcepos.org/
Login with your github account and add the language to your favorites. 
You'll be notified once new translations are available to cover.
Thanks for your contribution. 
Will close.

**Comment by simobenso** [comment]
That's what I was trying to do, when I try to add a missing translation here's what I get : 
![image](https://user-images.githubusercontent.com/1257993/71620030-d3325980-2bc7-11ea-9cfb-ea5d043612e3.png)

Plus, the save button is disabled.

**Comment by jekkos** [comment]
Weblate translations are unlocked now, you should be able to proceed.
