### ISSUE TITLE
Unsure of the exact process to use Due Payments

### ISSUE THREAD

**Issue by klisle** [opensourcepos/opensourcepos#2644]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
 

### Issue / Bug  / Question / New Feature

Hey guys,

Hope all is well. I am interested in understanding the Due payments feature but I am unsure of what the process/steps are supposed to be to use the feature correctly. I do not see any specific documentation and in the issues all I see is that the application supports part payments using Due Payments. I would also be interested in documenting the feature for layman users. Any assistance would be appreciated.

**Comment by WebShells** [comment]
Hello @klisle,
Due payments are currently supported as partial payments only. You can simply apply 2 payments ( 1 as cash, other as DUE ). Then in Daily sales windows you can edit the sale to update payment from DUE to Cash to list as fully paid. 
Daily sales filter contains DUE in order to list due invoices, same as reports filters.
The payments logging was contributed by @SteveIreland, me personally didn't had the chance to test... Will leave this part to him.

**Comment by Saiuke** [comment]
I'm building a sidekick system to deal with this problem. In this momment I'm studying Laravel, but, as soon as I finish my course I'll try to contribute to the OSPOS project.

**Comment by WebShells** [comment]
@Saiuke OSPOS is based on codeigniter.

**Comment by Saiuke** [comment]
I'm aware of that. Tha's why I'm starting to study CI after I finish the Laravel course.

**Comment by klisle** [comment]
> Hello @klisle,
> Due payments are currently supported as partial payments only. You can simply apply 2 payments ( 1 as cash, other as DUE ). Then in Daily sales windows you can edit the sale to update payment from DUE to Cash to list as fully paid.
> Daily sales filter contains DUE in order to list due invoices, same as reports filters.
> The payments logging was contributed by @SteveIreland , me personally didn't had the chance to test... Will leave this part to him.

Thanks for the reply. I also saw that an invoice could be made with no payments submitted. Then I am able to add more payments than two, reducing the balance each time. Is what you have told me the official way? What about supporting more than two installments? @WebShells

**Comment by mckaygerhard** [comment]
@klisle  and @Saiuke puff.. i will explain the "due" expectations:

*  ospos have a "due" payment to represent a "sell by credit but without credit card" and also to "avoid the accountant issues" of course.. very important that lasted
*  due the previous, ospos does not have any report that show that money that "are not really received" so we have here a "situation"! that's a due payment representation currently!

This "due payment" was and intent to avoid all the issues with "Accounts payable" problems.. but the true are that could complicated a bit the situation..

**Comment by mckaygerhard** [comment]
about your question @klisle  the right way it's that a "due payment" should not be altered! why! puff that money are not in the cash!...  so what about if i "debt" 10$ and later just modify the "due payment of 10$ to 1$" interesting right? i have a branch that solves that situation!

that' now to answer your question, there's no "right way" to make payments, opensourcepos has the free way to made payments in any order.. but with this "partial concept" that are (now again) a bit complicated...
