### ISSUE TITLE
 Close daily sales and cash count.

### ISSUE THREAD

**Issue by buckbowl** [opensourcepos/opensourcepos#2645]
Hello, is there any way to make a daily sales closing and cash count, and at the same time create a total sales report? 

And so start a new day with cash in the drawer?

Something similar to the image ...

![corte](https://user-images.githubusercontent.com/59344753/71603039-ac6d1800-2b20-11ea-9dee-ef48d24bf136.jpg)

**Comment by daN4cat** [comment]
There is a cashup feature, have you tried that?

You add on in the morning, saying hopw much cash you have. You update it in the evening and you will get the quantity of cash, card transactions and etc. based on the daily transactions.
Also if you had any petty cash expense using the expenses feature that will be accounted in the totals too.

Unfortunately there is not a closing of the day report that you can print. It's something we need to add.

**Comment by buckbowl** [comment]
It would be great if they did so and added to the application, and so get a daily cash closing report and be able to print it on the ticket printer

**Comment by nukerj** [comment]
Tengo está funcionalidad desarrollada.
I have that functionality developed

Contact vilchezjohnny82@gmail.com / Whatsapp +58412-6447407
El módulo de cierre se vee el contenido fuera del área cuando ingreso desde un teléfono pero en PC se vee bien

**Comment by nukerj** [comment]
![IMG_20210423_230619](https://user-images.githubusercontent.com/47283494/115945484-0f0ec380-a48a-11eb-98ad-eac97d3a3fd4.jpg)

**Comment by nukerj** [comment]
![IMG_20210423_231057](https://user-images.githubusercontent.com/47283494/115945524-31084600-a48a-11eb-914d-64c3776ac9ae.jpg)
![IMG_20210423_230812](https://user-images.githubusercontent.com/47283494/115945526-31a0dc80-a48a-11eb-884a-4bb4a29eae3d.jpg)

**Comment by nukerj** [comment]
![IMG_20210423_231008](https://user-images.githubusercontent.com/47283494/115945563-572de600-a48a-11eb-8831-47239ae16cd2.jpg)
![IMG_20210423_230715](https://user-images.githubusercontent.com/47283494/115945564-58f7a980-a48a-11eb-8d1b-755bb049b38d.jpg)
![IMG_20210423_230652](https://user-images.githubusercontent.com/47283494/115945565-58f7a980-a48a-11eb-9860-7580dccfe9c1.jpg)
