### ISSUE TITLE
Problem trying to migrate to the new version of OSPOS

### ISSUE THREAD

**Issue by Saiuke** [opensourcepos/opensourcepos#2647]
- [X] Reporting an issue of an unmodified OSPOS installation - The modification made is in the view only and don't interfere with data persistency.
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.0
- MySQL or MariaDB version is: 5.7.14
- OS and version is: Windows 10
- WebServer is: Apache 2.4.23
- Selected language is: Spanish

### Issue

I'm pretty familiar with OSPOS installations. I've installed it more than 10 times, both in GNU and Windows. I've done some updates too. I'm stating this so that you don't suggest that I check if the computer is on.

I'm able to run a clean installation of the new version. The problem occurs when I try to import the old data into the new system. I'm having some warnings from the PHPMyAdmin. The output is this:

21 errors were found during analysis.

    Unexpected character. (near "" at position 0)
    Unexpected character. (near " " at position 2)
    Unexpected character. (near "{" at position 3)
    Unexpected character. (near "{" at position 7)
    Unexpected character. (near "" at position 62)
    Unexpected beginning of statement. (near "" at position 0)
    Unexpected beginning of statement. (near "I" at position 1)
    Unexpected beginning of statement. (near " " at position 2)
    Unexpected beginning of statement. (near "{" at position 3)
    Unexpected beginning of statement. (near "" at position 4)
    Unexpected beginning of statement. (near "{" at position 7)
    Unexpected beginning of statement. (near "" at position 8)
    Unexpected beginning of statement. (near "" at position 10)
    Unexpected beginning of statement. (near "" at position 19)
    Unexpected beginning of statement. (near "" at position 24)
    Unexpected beginning of statement. (near "" at position 42)
    Unexpected beginning of statement. (near "" at position 47)
    Unexpected beginning of statement. (near "" at position 48)
    Unexpected beginning of statement. (near "" at position 58)
    Unexpected beginning of statement. (near "" at position 62)
    Unexpected beginning of statement. (near "" at position 63)

I tried to just ignore it and run the system, it worked until certain point. So far I noticed that:

Receipts aren't generated and sales aren't able to complete.
I'm not able to view detailed item info or (of course) edit items.

If someone is willing to try to replicate my problem I can send a copy of the sql file.
I disabled the option only_full_group_by, should I do anything else while importing the data?

EDIT: For some misterious reason the "Backup database" database in the old system isn't working anymore. I was thinking to try to run the old database in a clean installation of the 3.2.3 version and try it again, but I'm pretty sure that my database is broken somehow, I mean, there isn't another explanation. Would Excel imports cause this? I'm really lost here.

**Comment by daN4cat** [comment]
It's very difficult to help you with the information you provided.
Unfortunately I don't have time to check your .sql file.

**Comment by jekkos** [comment]
Regarding the error with receipts, do you see an error message that you can share?

**Comment by jekkos** [comment]
Can you go to configuration section to check which receipt template was selected?

**Comment by Saiuke** [comment]
The receipt format selected is the standart one. About the mesage errors, it shows "Server error somthing" and a lot of:

Notice in .\libraries\sql-parser\src\UtfString.php#134
Uninitialized string offset: 872

Backtrace

.\libraries\sql-parser\src\Lexer.php#772: SqlParser\UtfString->offsetGet(integer 369)
.\libraries\sql-parser\src\Lexer.php#258: SqlParser\Lexer->parseString()
.\libraries\sql-parser\src\Lexer.php#210: SqlParser\Lexer->lex()
.\libraries\Util.php#659: SqlParser\Lexer->__construct()
.\import.php#773: PMA\libraries\Util::mysqlDie(
string '#1064 - Você tem um erro de sintaxe no seu SQL próximo a \'?\' na linha 1',
string ,
boolean false,
string 'db_import.php?db=nospos&amp;token=3e79015f93fbd87ba3f78a50b3d2c92c',
boolean true,
)

**Comment by Saiuke** [comment]
I have a lot of items with double quotes. Something like Puntilla de 2".

**Comment by Saiuke** [comment]
I've tried again. This time I used the MySQL CLI. I got these errors in the very begining:

ERROR:
Unknown command '\U'.                                                                                                   ERROR:                                                                                                                  Unknown command '\e'.                                                                                                    ERROR:                                                                                                                  Unknown command '\D'.                                                                                                   ERROR:                                                                                                                  Unknown command '\n'.

Everything else did okay. Started the system, same problems. I'm not able to complete sales (blank screen) and not able to create or edit items.

Would this line cause any kind of error?

```
INSERT INTO `ospos_app_config` (`key`, `value`) VALUES
('address', 'Régimen simplificado\r\nNIT 1.121.829.547-6\r\nCalle Principal - Caribayona'),
```

**Comment by daN4cat** [comment]
@Saiuke sorry, where can I find the file `libraries\sql-parser\src\UtfString.php`? I don't see any in libraries from our OSPOS.

**Comment by Saiuke** [comment]
That's an error presented by PHPMyAdmin. Thinking that maybe my PHPMyAdmin was broken or something I tried doing the import using the MySQL terminal, there I got:

ERROR: Unknown command '\U'.
ERROR: Unknown command '\e'. 
ERROR: Unknown command '\D'. 
ERROR: Unknown command '\n'.

But the import followed on and I got the system running. But I'm still not able to complete sales (blank screen) and not able to create or edit items.
As I'm trying to import a OSPOS database from version 3.2.3 to 3.3.1 without any changes in the files or database structure. I guess there's some problem in my database, due to errors in the import process.

As I said, the 3.2.3 version (old one) is working pretty well, I'm keeping it until I'm able to update and make the import succesful. I got the 3.3.1 (new one) running without problems too, but with a blank database. I was thinking to write a PHP script to make the import and notify specific errors, but man, there must be a easy way.

**Comment by daN4cat** [comment]
@Saiuke I've completed yesterday a migration of OSPOS from version 1.1 to latest 3.3.1 and all went fine.
From 3.0.0 onwards is done automatically by the application the first time you login in, so not sure why you are using phpMyAdmin.

**Comment by jekkos** [comment]
Wow that's quite a leap @daN4cat . Happy to hear you managed to do that monster migration after all that time!

**Comment by daN4cat** [comment]
@jekkos yes it finally took place. I was stuck on an issue with duplicate customers and transactions. I spent a day reconciliation everything.
It's now live after all these years of work on OSPOS.

**Comment by daN4cat** [comment]
@Saiuke any update? Have you tried migrating a replica of the current database using 3.3.1 without phpMyAdmin?

**Comment by jekkos** [comment]
Indeed you might be better off running the script directly from the command line to avoid any escape or encoding issues that might arise when copy pasting and submitting in an html form.

**Comment by Saiuke** [comment]
What I just did was:

1. I created a copy of the courrent database using PHPMyAdmin.
2. In the new OSPOS installation, I changed the "database.php" info to point to the new database.
3. Then I simply login in the new installation. In the first login the migration is executed, then you have to login again.

In this new installation I experienced the problems listed below:

Can't complete sales. But I can view old receipts.
I'm not able to view detailed item info and create or edit items.

The clients module works fine, the same as everything else, so far I can tell.
I suspect that I have some kind of problem with my inventory.

I'll leave a copy of my database export file in the link below, if anyone can try to run it in a 3.3.1 install would be great. I'll delete it in a few hours.

[Database backup]("C:\Users\ezequ\Dropbox\Compartilhados\Database backup OSPOS FLYC.gz")

Login Ezequias
Pass midnight28

**Comment by WebShells** [comment]
DB link looks very online : p

**Comment by Saiuke** [comment]
Sorry XD

**Comment by Saiuke** [comment]
> 
> 
> Regarding the error with receipts, do you see an error message that you can share?

No, no errors. Just a blank page. Old receipts are just fine. I just can't complete new sales.

**Comment by Saiuke** [comment]
Turns out the error ocurred because I didn't deactivate the only_full_group_by, now that I have done it, it works.
