### ISSUE TITLE
Gift Card used for crediting a Return with error logging on the following error is shown. Any Ideas.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2648]
OSPOS Installation Info: 3.4.0 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
» Browser: Chrome
» Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.2.4
» PHP Version: 7.2.4
» DB Version: 5.7.21
» Server Port: 80
» OS: Windows NT PAVILION23 10.0 build 18363 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓ 

ERROR - 2019-12-31 09:04:37 --> Severity: Notice --> Only variables should be passed by reference C:\wamp64\www\my-master\application\libraries\Sale_lib.php 1264

**Comment by daN4cat** [comment]
@SteveIreland this looks to be a bug, because in Sale_lib.php the code is:
```
			foreach($this->CI->tax_lib->get_taxes($this->get_cart())[0] as $tax)
```
where 
```
	public function get_taxes(&$cart)
```
a function returns a temporary variable and cannot be passed by reference.

If my reading of the error and code is correct.

**Comment by daN4cat** [comment]
BTW, I cannot test that code because it's not executed if you have "Tax included" enabled.

**Comment by daN4cat** [comment]
@SteveIreland any chance you could look into this?

**Comment by odiea** [comment]
@SteveIreland This also happens when using Reward Points.

**Comment by daN4cat** [comment]
@SteveIreland it seems you went silent. Hope all is fine with you.

**Comment by daN4cat** [comment]
@odiea because you seem able to reproduce this bug, could you please change this line in 1261 from:

`foreach($this->CI->tax_lib->get_taxes($this->get_cart())[0] as $tax)`

to

```
$cart = $this->get_cart();
foreach($this->CI->tax_lib->get_taxes($cart)[0] as $tax)
```

and test again?

**Comment by odiea** [comment]
@daN4cat Yes I am receiving no errors now. The errors just showed when in development mode. I tried in the latest Master . I got the error before the fix but no error afterwards. Thanks

**Comment by daN4cat** [comment]
OK, I'll commit that change.

What is the error line using the Reward Points?

**Comment by odiea** [comment]
No errors in  giftcards or rewards now.

**Comment by daN4cat** [comment]
OK, I commit this fix then.

**Comment by SteveIreland** [comment]
Sorry ... I totally missed this ... glad you worked it out.
