### ISSUE TITLE
weigh barcode #Price embeded?#

### ISSUE THREAD

**Issue by akhilnasi** [opensourcepos/opensourcepos#2649]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 7
- MySQL or MariaDB version is: 
- OS and version is: win 10
- WebServer is: Xampp
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hi ,
I need one solution for the weigh barcode. for me instead of weight i need price.
for example:
02-department
05-item code
06-price

but instead of price it directly goes to quantity. I have already opened an issue regarding this and got an answer its not supported. Any one can help me regarding this.

Please i knidly request you to not to close this issue before i get the proper answer.

If there is no option for price could anyone can help to make this feature available in OSPOS.

**Comment by mckaygerhard** [comment]
please fill the template issue or remove it and make a feature request title property!

**Comment by jekkos** [comment]
@akhilnasi adding price from barcodes is not supported. You can only use quantity as it stands now.

Code needs to be changed to do this. So it's up to you to implement it or in another case ask someone to do it (maybe for a small fee)? Let me know what you think.

**Comment by akhilnasi** [comment]
yes .. i am ready to second condition

**Comment by WebShells** [comment]
@akhilnasi please sign up and submit a feature request through OSPOS website.
Https://opensourcepos.org
