### ISSUE TITLE
"Allow sales price change" for employees in sales

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2653]
So that an employee in ospos does not see the items in the item module but at the same time can create a product from the sales module, it is done in this way
![Captura el 2020-01-02 a las 07 06 28](https://user-images.githubusercontent.com/29256343/71668557-f9263e00-2d2e-11ea-9a17-6f3bf7471605.png)

But I have a problem here in sales. the employee can change the price of the item even if allow delete this unchecked

![Screenshot_2020-01-02 Hasba Systemsdfsdfds JEJEJE Powered by OSPOS 3 4 0](https://user-images.githubusercontent.com/29256343/71668743-b4e76d80-2d2f-11ea-9c07-cb7ac9fca343.png)
I think this "allow delete" should only be when the employee can see the item module.

I was trying if I could change this condition but I was not successful at the moment, if anyone has an idea I would appreciate it.

Thanks a lot

**Comment by daN4cat** [comment]
@andriux1990 "Allow delete" means allowing people to delete a transaction. You can see the delete button when you go to Sales/Transactions and you edit a Sale. The button is visible but you can't delete the Transaction is the check box is unchecked.

**Comment by andriux1990** [comment]
Well it's true, you're right. So what can be done so that this employee cannot change the original price of an item. because the discount is supposed to be for this

**Comment by daN4cat** [comment]
@andriux1990 what you can do? Train your employee. To tailor generic tools to specific business processes is a lot of work.
You'll end up having tons of switches and options and nobody understanding anymore what to configure. I mean, it's already complex now. Sometimes I can't even remember what a configuration switch is supposed to do.

**Comment by andriux1990** [comment]
I'm sorry, this is not what I was trying to say.

I meant that this field where the price is should not be editable. because employees can steal, charge less than the item costs and not be reflected in the discount details.

I will open a issue by expressing myself well

**Comment by odiea** [comment]
@andriux1990 . You can do that if you change the following from 'items' to'config' in application/controllers/sales. I believe it is line 1114. You would not want to give an employee that permission.
		$data['items_module_allowed'] = $this->Employee->has_grant('items', $this->Employee->get_logged_in_employee_info()->person_id);

**Comment by daN4cat** [comment]
@andriux1990 if the change is simple and just needs an extra permission, feel free to suggest a PR for that.

**Comment by andriux1990** [comment]
> @andriux1990 . You can do that if you change the following from 'items' to'config' in application/controllers/sales. I believe it is line 1114. You would not want to give an employee that permission.
> $data['items_module_allowed'] = $this->Employee->has_grant('items', $this->Employee->get_logged_in_employee_info()->person_id);

Thanks is just what I was looking for.

It is a simple but important detail and I think it should be in the teacher. I will suggest the change

**Comment by daN4cat** [comment]
@andriux1990 the correct change is to use something else than items, for sure not config.

`$data['items_module_allowed'] = $this->Employee->has_grant('sales_items_change', $this->Employee->get_logged_in_employee_info()->person_id);`

then you need to create a sql migration script to add the new permission in `ospos_permissions` table.

Something like:

```
INSERT INTO `ospos_permissions` (`permission_id`, `module_id`) VALUES
 ('items_change', 'sales_items_change');
```

**Comment by mckaygerhard** [comment]
1. @andriux1990  you must detail the title and fill the issue property with feature request type
2. @andriux1990 that you try to said, it's granular permissions for sales, once was make a sale!
3. @daN4cat the explanation are that:

in latin america (from where is andrux1990) there are no so much loyal people.. so ALL the POS systems have specific focus in already made sales, so **an employee with limited permission can only make a sale or alter very limited things from already made sales, but never changes items price in a sale, neither the amount of items.. that feature are not present in opensourcepos due seems opensourcepos assumes that owner of the store are aside with the employess in the store! of course are a small and fit application not like ospos or A2 soft!** i understand that due i also work with OASIS, A2 and others more ugly like that stupid thing name Oodo.

unfortunately opensourcepos are not so granular.. and @andriux1990 opensourcepos are a easy (very very easy) to use POS web system, and must be mantain and keep simple, if becomes more complicated will be hard to mantain..

**Comment by mckaygerhard** [comment]
unfortunatelly @jekkos  this feature as i xplained must be done.. witout that opensourepos are only a very small application ..

**Comment by andriux1990** [comment]
> @andriux1990 the correct change is to use something else than items, for sure not config.
> 
> `$data['items_module_allowed'] = $this->Employee->has_grant('sales_items_change', $this->Employee->get_logged_in_employee_info()->person_id);`
> 
> then you need to create a sql migration script to add the new permission in `ospos_permissions` table.
> 
> Something like:
> 
> ```
> INSERT INTO `ospos_permissions` (`permission_id`, `module_id`) VALUES
>  ('sales_items_change', 'sales');
> ```

Ok i will do this

**Comment by daN4cat** [comment]
@andriux1990 any update?

**Comment by odiea** [comment]
This give a little extra code but it works.
```
$employee_id = $this->Employee->get_logged_in_employee_info()->person_id;
$has_grant = $this->Employee->has_grant('sales_delete', $employee_id);
if($items_module_allowed & $has_grant)

**Comment by andriux1990** [comment]
Not yet, I've been doing other things to Ospos. I did the first thing @odiea  suggested and for the moment it's fine. but I know it must be done in a better way

**Comment by andriux1990** [comment]
I'll get to work on this tonight

**Comment by odiea** [comment]
I have always used  the currently available  code. If you don't want them to change the price then why would you give them the ability to delete the transaction. Sorry that's just the way I look at it.

**Comment by andriux1990** [comment]
It is simple, if the price changes, the employee could steal and from so many sales it is possible to ignore it.
When you delete a transaction, everything returns to the stock and the money from the sale disappears from the report, this is fine as well. It's like canceling an invoice, so to speak. They are two different things

**Comment by odiea** [comment]
If you have not got this yet the following appears to work in the current Master.
```
Database Update
INSERT INTO `ospos_permissions` (`permission_id`, `module_id`) VALUES
('sales_change_price', 'sales');

INSERT INTO `ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES
('sales_change_price', 1, '--');

Sales Lang update
$lang["sales_change_price"] = "Change Selling Price";

Sales Controller update
function_reload below 
$data['items_module_allowed'] = $this->Employee->has_grant('items', $this->Employee->get_logged_in_employee_info()->person_id);

$data['change_price'] = $this->Employee->has_grant('sales_change_price', $this->Employee->get_logged_in_employee_info()->person_id);

Register view update
if($items_module_allowed && $change_price)
```

**Comment by andriux1990** [comment]
> If you have not got this yet the following appears to work in the current Master.
> 
> ```
> Database Update
> INSERT INTO `ospos_permissions` (`permission_id`, `module_id`) VALUES
> ('sales_change_price', 'sales');
> 
> INSERT INTO `ospos_grants` (`permission_id`, `person_id`, `menu_group`) VALUES
> ('sales_change_price', 1, '--');
> 
> Sales Lang update
> $lang["sales_change_price"] = "Change Selling Price";
> 
> Sales Controller update
> function_reload below 
> $data['items_module_allowed'] = $this->Employee->has_grant('items', $this->Employee->get_logged_in_employee_info()->person_id);
> 
> $data['change_price'] = $this->Employee->has_grant('sales_change_price', $this->Employee->get_logged_in_employee_info()->person_id);
> 
> Register view update
> if($items_module_allowed && $change_price)
> ```

hey @odiea, I like this, because we don't add it to the master

**Comment by daN4cat** [comment]
Done and committed to master.

**Comment by daN4cat** [comment]
I tested and appears to work fine therefore I close. If you have any issue with the solution reopen the case.
