### ISSUE TITLE
Cannot return POS transaction if item is deleted

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#2659]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: MardaiDB 10.3
- OS and version is: Linux
- WebServer is: Apache
- Selected language is: British English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

In Sales register select as mode Return, enter a POS number containing an item that has been deleted and the POS transaction cannot be returned.
This didn't use to be the case in previous version of OSPOS.

**Comment by daN4cat** [comment]
I found the culprit, I've fixed and testing before committing.

**Comment by daN4cat** [comment]
Fixed and in master.

**Comment by odiea** [comment]
@daN4cat . It does now accept a transaction with a deleted item but not a deleted item for a return.

**Comment by daN4cat** [comment]
No it never did if my memory is right. The thinking is that you accept a return only if you have a receipt.
I remember we discussed that scenario a couple of years ago and we agreed that you want a receipt to accept something you don't have in stock anymore.
Also to avoid employees to return bogus item to cash some money.

**Comment by odiea** [comment]
Yes that was my point of view. Thanks for fixing this.
