### ISSUE TITLE
item doesnot display in item module but it displays in reports

### ISSUE THREAD

**Issue by akhilnasi** [opensourcepos/opensourcepos#2664]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7
- MySQL or MariaDB version is: 
- OS and version is: win10
- WebServer is: xampp
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

problem is i couldnot display my items in item module . but when i click the delete from the dropdown menu it shows the delete list of items in item module. I have inventory table also. and i can see my items in reports->items.
Can any one help me regarding this?

**Comment by daN4cat** [comment]
Have you imported items directly in MySQL and not via OSPOS?

**Comment by akhilnasi** [comment]
not directly via ospos... i have imported directly through ospos before and i did a backup and directly uploaded to ospos

**Comment by WebShells** [comment]
@akhilnasi sorry, but i can't find the answer in your reply... The items were imported through OSPOS items import csv form, or through phpmyadmin or any sql management service?

**Comment by akhilnasi** [comment]
i have done a backup of database and imported in another mysql. before i was using ospos 3.3.0 and i have migrated to ospos 3.3.1. Now items shows in report and when i select "deleted" from dropdown of item module it shows whole deleted . but it doesnot entire items in item module

**Comment by mckaygerhard** [comment]
@akhilnasi  you make a mysql dump of your database.. and later tem restore it! that are not well received due mysql will dump own setting for all the tables.. so ovbiously will break things.. 

i dont know if this are or not a bug in ospos.. due any king of dump must be supported! but for now you make the things in bad way.. try to dump in separate way and added proper parsing flags to your cron task

**Comment by odiea** [comment]
Try removing "ONLY_FULL_GROUP_BY" in sqlmode and see if that works.
