### ISSUE TITLE
Colon ':' symbol not allowed in attributes or item value on Item View

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2665]
### Background information

OSPOS Installation Info: | 3.3.1 - ae8450
-- | --
en-US
» GD: Enabled ✓» BC Math: Enabled ✓» INTL: Enabled ✓» OpenSSL: Enabled ✓» MBString: Enabled ✓» Curl: Enabled ✓
.Browser:  			Firefox  				.Server Software: Server 				.PHP Version: 7.3.6 				.DB Version: 5.7.26-log 				.Server Port: 80 				.OS: FreeBSD chiraq.chickenkiller.com 11.2-STABLE FreeBSD  11.2-STABLE #0 r325575+c9231c7d6bd(HEAD): Mon Nov 18 22:46:47 UTC 2019       root@nemesis:/freenas-releng/freenas/_BE/objs/freenas-releng/freenas/_BE/os/sys/FreeNAS.amd64  amd64
» [application/logs:] 				 -  0775 \|    Writable ✓  				» [public/uploads:] 				 -  0750 \|   Not Writable ✗  				» [public/uploads/item_pics:] 	 				 -  0750 \|   Not Writable ✗  				» [import_customers.csv:]  				 -  0640 \|   Not Writable ✗

### Bug

In attributes where values include a colon (':'), the error checking in the Items->New Item view is throwing an error.  Yet, this symbol should be allowed.  For example, anyone needing to record the Aspect Ratio of a movie (16:9, 4:3) or Book titles with colons ("Programmers Guide the Galaxy: How to Become a Better Programmer") can't.

Is there any reason why I shouldn't change the code to allow a colon?

**Comment by WebShells** [comment]
@objecttothis did you copy paste the issue template or the browser isn't rendering the code as expected? I see it's messed up

**Comment by objecttothis** [comment]
@WebShells I had to copy and paste it from the browser because the copy info link isn't working.
![Annotation 2020-01-06 171830](https://user-images.githubusercontent.com/17935339/71820480-a0e19a00-30a8-11ea-81f5-95169db521fd.jpg)

**Comment by WebShells** [comment]
@objecttothis clear man... That comment/question was before you opened the sys info related issue...

**Comment by jekkos** [comment]
I think there is a validation message that says you can't use the semicolon? It's used as a separator for aggregating the attribute value rows in the resultset. I could use another character ofcourse but I suppose the better way would be to read out the result from a data structure instead.

**Comment by objecttothis** [comment]
Actually, the validator message is "Attribute value cannot contain ':' or '|'" so it's not allowing a colon or pipe.  I can't forsee anyone using a pipe in an attribute value, but a colon, while not as common as 0-9a-zA-Z, it isn't uncommon.  You can see my examples above on how we use it.

**Comment by objecttothis** [comment]
> 
> 
> I think there is a validation message that says you can't use the semicolon? It's used as a separator for aggregating the attribute value rows in the resultset. I could use another character ofcourse but I suppose the better way would be to read out the result from a data structure instead.

@jekkos, Do you want me to do this one or do you want it?  We need to be able to use a colon in the attribute values, so it looks like either we are going to need to use a different character as a separator or we will need to read out the result from the data structure like you proposed.

**Comment by objecttothis** [comment]
@jekkos, I'm not seeing where we are using the colon (:) for delimiting.  If I remove "\:" from 
/views/attributes/form.php (140)
`        if ($("#definition_value").val().match(/(\||:)/g) != null)`

It passes all of the tests that I've thrown at it.
- Add a DROPDOWN attribute value containing a colon
- Add multiple DROPDOWN attribute values with one or more containing colons
- select an attribute dropdown value with a colon on an item.
- open an item containing an attribute dropdown value with a colon.
- remove said attribute.

Is there another place I'm not seeing that we are using the colon to do something that prevents us from allowing colon characters in the name of the dropdown value?

**Comment by jekkos** [comment]
@objecttothis indeed currently I think only underscores and pipes are not allowed. So I should update the code to validate on those tokens instead.
