### ISSUE TITLE
DATETIME attribute type problems

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2666]
### Bug

- When creating a new item, if you add an attribute that is of DATETIME type and change the value, the date reverts to 1.1.2010 as soon as that attribute loses focus.

- In the date selector 1.1.2010 is the earliest selectable date.  Dates prior to that are not selectable.  When dealing with publication dates, this is too restrictive since it's pretty common to come across book publication dates prior to 2010.

OSPOS Installation Info: | 3.3.1 - ae8450
-- | --
en-US
» GD: Enabled ✓» BC Math: Enabled ✓» INTL: Enabled ✓» OpenSSL: Enabled ✓» MBString: Enabled ✓» Curl: Enabled ✓
.Browser:  			Firefox  				.Server Software: Server 				.PHP Version: 7.3.6 				.DB Version: 5.7.26-log 				.Server Port: 80 				.OS: FreeBSD 11.2-STABLE FreeBSD  11.2-STABLE #0 r325575+c9231c7d6bd(HEAD): Mon Nov 18 22:46:47 UTC 2019       root@nemesis:/freenas-releng/freenas/_BE/objs/freenas-releng/freenas/_BE/os/sys/FreeNAS.amd64  amd64
» [application/logs:] 				 -  0775 \|    Writable ✓  				» [public/uploads:] 				 -  0750 \|   Not Writable ✗  				» [public/uploads/item_pics:] 	 				 -  0750 \|   Not Writable ✗  				» [import_customers.csv:]  				 -  0640 \|   Not Writable ✗

**Comment by jekkos** [comment]
I guess it would be better to have the default date set to today instead? Check my PR for that change.

**Comment by objecttothis** [comment]
Also, to clarify point 1 in the bug report.  It only reverts when losing focus to adding another attribute.  If I click another permanent field, it doesn't revert to 1.1.2010.

**Comment by jekkos** [comment]
Can you try my latest commit? I removed the startDate initializer in the widget.

**Comment by daN4cat** [comment]
That change will affect all the views and forms.

Can you please verify the effect on the other parts of the code using that default value in the search box?

**Comment by daN4cat** [comment]
I vaguely remember that there was a reason behind that change.

**Comment by objecttothis** [comment]
@jekkos, I just tried it on the demo.  Here are my results:
- The date selector is defaulting to todays date.
- With two or more attributes setup, If I create an item, add a date attribute, change the date, then add another attribute, the date reverts back to todays date.

**Comment by objecttothis** [comment]
Sorry, I forgot to mention.  I am also able to select dates before 1/1/2010, so that's fixed.

**Comment by odiea** [comment]
I receive the following error with logging on. Probably PHP version. Changing it to time did eliminate the error.
ERROR - 2020-01-10 12:18:39 --> Severity: 8192 --> mktime(): You should be using the time() function instead C:\wamp64\www\my-master\application\helpers\locale_helper.php 5

**Comment by jekkos** [comment]
Ah ok so that needs changing, thanks for pointing that out @odiea

**Comment by jekkos** [comment]
@daN4cat you might be right, I remember that we did that for some reason. I think we have 2010 because that is the project's inception date. So editing sales / items to have a date before 2010 does not make sense as the project didn't exist back then. I think that was the rationale behind that choice.

**Comment by objecttothis** [comment]
that makes sense, but now that we've added attributes, it is possible to have an item with an attribute needing to be dated pre 2010 (such a print date of a book).

**Comment by daN4cat** [comment]
@objecttothis fix is in master, please check if this is fine with you. @odiea would be good if you could do some more testing. I'll test a bit as weel in the coming days.

**Comment by odiea** [comment]
Adding an Item with a Date Attribute works with todays Date. I also removed the readonly so that I could change the date to anything I wanted.

**Comment by daN4cat** [comment]
This seems fine. I close.

**Comment by objecttothis** [comment]
I just downloaded and installed 3.3.1 to test with a copy of my production database before going live and there are still some issues with the date selector.
1- You cannot manually enter a date.  It requires you to use a selector. I would think it would be better to allow either the selector or manually entering the date with a formatting check to confirm that the date entered matches the localization.
2- The earliest year available in the selector is 2010.  Did @jekkos' changes not make it into 3.3.1?

**Comment by daN4cat** [comment]
They are in 3.3.2 bit we didn't release it yet.
Could you please latest master?
It's stable and I use it in production.
HOWEVER, if you use Tax included please let's talk before you update. I fixed few issues around that and fixes the database history.

**Comment by objecttothis** [comment]
I'll download the latest master then.  I saw the tax conversation but didn't pay attention to it entirely.  Our taxes is included into the price of the item, so I'm not sure if it applies to us or not, but it would be nice to be able to generate reporting showing net profit which would ideally remove the included tax.

**Comment by daN4cat** [comment]
Is this DATETIME attribute still a problem?

**Comment by objecttothis** [comment]
I'll check in the morning when I'm back in the office.

**Comment by objecttothis** [comment]
Tested and working.  The only way to enter a date is through the date selector, but that isn't a bug.  Perhaps down the road I'll create an issue with a datetime enhancement to either use the selector or manually type in the date.  Doing so would require some format checking to verify that the date is the correct format for the locale.
