### ISSUE TITLE
Problems with OSPOS installation info

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2667]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Installation Info: | 3.3.1 - ae8450
-- | --
en-US
» GD: Enabled ✓» BC Math: Enabled ✓» INTL: Enabled ✓» OpenSSL: Enabled ✓» MBString: Enabled ✓» Curl: Enabled ✓
.Browser:  			Firefox  				.Server Software: Server 				.PHP Version: 7.3.6 				.DB Version: 5.7.26-log 				.Server Port: 80 				.OS: FreeBSD [COMPUTER DOMAIN REDACTED] 11.2-STABLE FreeBSD  11.2-STABLE #0 r325575+c9231c7d6bd(HEAD): Mon Nov 18 22:46:47 UTC 2019       [USERNAME REDACTED]@nemesis:/freenas-releng/freenas/_BE/objs/freenas-releng/freenas/_BE/os/sys/FreeNAS.amd64  amd64
» [application/logs:] 				 -  0775 \|    Writable ✓  				» [public/uploads:] 				 -  0750 \|   Not Writable ✗  				» [public/uploads/item_pics:] 	 				 -  0750 \|   Not Writable ✗  				» [import_customers.csv:]  				 -  0640 \|   Not Writable ✗

### Issue 
The OS: field under user settings contains sensitive data.  When that data gets copied into an issue, that creates a security vulnerability for people creating tickets.  The two pieces of information that should not appear in the field are the domain of the computer and the username that the application is running as.  Really the only information that is needed is the OS and the version, so if that could somehow be extracted, that would be ideal.

### Bug
The "Copy Info" link is not working.  This is at least true in Firefox Developer Edition 72.0b11.  On mouseover the link decoration switches to underline but you can't click on it.  The Report an Issue link on that same browser does work.  Although, it doesn't do any auto-population of the issue text, which would be cool, were it possible.

**Comment by WebShells** [comment]
I noticed the format is messed since your last issue. Ill remove or replace the highlighted issues and will have a look at the formatting... I wonder why the copy link would stop functioning without any changes 😯

**Comment by objecttothis** [comment]
@WebShells see if you can duplicate the copy link issue on your end.  I'm not using the latest master, so I want to make sure that isn't the issue.  I didn't touch that section of code, so it shouldn't be related.  If you can't duplicate it, then I will download the latest master and see if it works on that.

**Comment by WebShells** [comment]
Check this kid, lol... And he calls himself a hacker ;p ! Gonna reset demo server and try it @objecttothis 
![image](https://user-images.githubusercontent.com/26513147/71820778-ded6c200-3098-11ea-83ce-e3a83c701345.png)

**Comment by objecttothis** [comment]
hehe.  How cute.  So hackers now include people who can change the company name in the settings.

**Comment by odiea** [comment]
I still get the following in both Chrome and Firefox.

OSPOS Installation Info: 3.3.2 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
» Browser: Chrome
» Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.2.4
» PHP Version: 7.2.4
» DB Version: 5.7.21
» Server Port: 80
» OS: Windows NT PAVILION23 10.0 build 18363 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓

**Comment by objecttothis** [comment]
@odiea is your copy info link working at the bottom?

**Comment by odiea** [comment]
Yes it is.

**Comment by WebShells** [comment]
> @odiea is your copy info link working at the bottom? in Firefox?

He used it man ;p or else it would have pasted messed up text... 
I'll double check this maybe tonight anyway... No worries...

**Comment by odiea** [comment]
I just checked the link to Issues in Firefox and that also works.

**Comment by odiea** [comment]
I lied. It is not working in Firefox. Sorry. I did not look to see what browser was copied until just now.

**Comment by odiea** [comment]
But It does work in Pale Moon a firefox clone?
	OSPOS Installation Info: 3.3.2 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
» Browser: Firefox
» Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.2.4
» PHP Version: 7.2.4
» DB Version: 5.7.21
» Server Port: 80
» OS: Windows NT PAVILION23 10.0 build 18363 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓
» [public/uploads:] - 0777 | Writable ✓
» [public/uploads/item_pics:] - 0777 | Writable ✓
» [import_customers.csv:] - 0666 | Writable ✓

**Comment by WebShells** [comment]
Just tested, with Mozilla FireFox the copy click is not functioning well... I'll handle it... 
Maybe i'll do a small research in order to pass info data directly to github issue... Can't promise about it, but not bad to give it a try... (Y)

**Comment by odiea** [comment]
Support for the Clipboard API's navigator.clipboard.writeText() method was added in Firefox 63.

**Comment by daN4cat** [comment]
@WebShells can we close this so I can release 3.3.2?

**Comment by WebShells** [comment]
@daN4cat sure, the deadline is by 31... Havin some issues with my pc, will try to submit before release date 👍

**Comment by daN4cat** [comment]
Thanks

**Comment by daN4cat** [comment]
@WebShells please fix this issue so we can close.

**Comment by WebShells** [comment]
![IMG_20200129_103336](https://user-images.githubusercontent.com/26513147/73340166-e564ed80-4282-11ea-9377-a19292f46e20.jpg)
@daN4cat i will 😅 hahaha

**Comment by WebShells** [comment]
That's happening now... I'll as soon as am done and installed my set of programs... Sorry for being late guys...

**Comment by WebShells** [comment]
It's a firefox issue.. 
For security reasons they blocked copying to users' clipboard through a web button... 
Shall we add clipboard library for this page ? or we release this update and keep for later releases ? @opensourcepos/org

**Comment by daN4cat** [comment]
I can see the security point, it makes full sense to me.
We should consider a manual way to offer wiki text to be copied and pasted in GitHub.

**Comment by daN4cat** [comment]
Right, where are we with this?

**Comment by WebShells** [comment]
@daN4cat i didn't proceed... Maybe i should add something that needs to allow permission to copy... Ill re look into this...

**Comment by jekkos** [comment]
@WebShells any chance of testing whether we can just select the text and copy it?

**Comment by WebShells** [comment]
Will find a workaround for this :/

**Comment by objecttothis** [comment]
@WebShells I would imagine that the quickest way to resolve this would be to have the link give you pre-formatted wiki-text to highlight, then copy/paste manually.  Then later we can look into a library to work around the issue without introducing vulnerabilities.

**Comment by WebShells** [comment]
Well, Guys... I had the chance yesterday to look over it... Copy and paste can be reworked through firefox using ClipboardJS... Any problem attaching it to our header ?... If no problem the only thing to worry about is reformatting the final paste results... Currently can paste as unformatted text.

**Comment by daN4cat** [comment]
Add the js only to that page not everywhere please.

**Comment by WebShells** [comment]
Updated system info directly to master please let me know  if there is still any problem with firefox... 
As suggested, ill try to add time comparison to check if server and local time are synced... Any ideas ? 
@odiea @objecttothis can you test it please ? Thanks for your time.

**Comment by odiea** [comment]
Works like a champ. 
Chrome, Firefox, Opera and IE returned the same info.

OSPOS Installation Info: 3.3.2 - dev
Language Code: en-US
Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Edge
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
.PHP Version: 7.3.2
.DB Version: 5.7.21
.Server Port: 80
.OS: Windows NT PAVILION23 10.0 build 18363 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓

**Comment by WebShells** [comment]
Will close this, moving to permissions and time sync issue...  Sorry for all the delay people <3
