### ISSUE TITLE
SALES REPORT for cashiers

### ISSUE THREAD

**Issue by buckbowl** [opensourcepos/opensourcepos#2669]
Información de la Instalación OSPOS: | 3.3.1 - c786d4
es
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓
.Browser: Chrome.Server Software: Apache.PHP Version: 7.3.11.DB Version: 5.7.28.Server Port: 80.OS: Linux phoenix.viewen.com 3.10.0-962.3.2.lve1.5.26.7.el7.x86_64 #1 SMP Wed Oct 2 07:53:12 EDT 2019 x86_64
» [application/logs:] - 0755 \| Writable ✓ 
» [public/uploads:] - 0755 \| Writable ✓ 
» [public/uploads/item_pics:] - 0755 \| Writable ✓ 
» [import_customers.csv:] - 0774 \| Writable ✓

**Hello, I want to see if it is possible and someone thinks the same to me ...
When creating an employee as a cashier you must be given permission for certain things. But I see that by creating a sales report under this cashier he can see what costs and profits are. I think this should be able to hide for them.**

![ganancia costo](https://user-images.githubusercontent.com/59344753/71921839-48b1a300-314f-11ea-983b-dc575a6f5b24.jpg)

**Comment by WebShells** [comment]
Giving a cashier report permission isn't a good idea... Yet... This is not the only thing related to cashier issues...
Try adding a new report removing profit and cost and summary data from the bottom of the page... This will solve your issue.
