### ISSUE TITLE
Clarification for Keyboard shortcuts... 

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2673]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

#Issue 
@daN4cat @SteveIreland @jekkos @odiea any idea to this?
@nvk1990
Tagging from #1630 issue
I try this and it is really works....
$(document).keydown(function(e){ if (e.which == 119) { //focus on customer search $('#customer').focus(); } else if(e.which == 121) { //simulates add payment button click $('#add_payment_form').submit(); } });

But.... how about the quantity? the Complete button? and the Delete amount? please response....

**Comment by izeblood** [comment]
I'll already try this $('#finish_sale_button').submit();  but it doesn't work...

**Comment by andriux1990** [comment]
> document.onkeyup=function(e){
  var e = e || window.event;
  if(e.which == 119) {
    $("#add_payment_button").click()
  }else if(e.which == 120){
    $("#finish_sale_button").click()
  }
//******************************************
  var a = a || window.event;
  if(e.which == 145) {
    $("#suspend_sale_button").click()
  }else if(e.which == 27){
    $("#cancel_sale_button").click()
  }

**Comment by izeblood** [comment]
@andriux1990 thanks man for contributing this....
I'm just want to add what are the variable handler for:
quantity? yes only quantity...hahaha...

**Comment by WebShells** [comment]
Shall you submit back a PR guys? Including shortcut keys list... Thanks for the work here..

**Comment by mckaygerhard** [comment]
@the developer process and code changing to test in opensourcepos are huge complicated.. also need more network connection (noted now that after clone the repository i had also download more more files due that shit of npm/nodejs/composer etc)

if you noted those guys @andriux1990 and @izeblood are windows guys that dont waste tiume in those complicated and tedious process.. 

**i guess liked that old way "download and that's all" but this repository are not like that! so that's why you @WebShells noted a PR are not happened! just those people paste the code here and that's all you get always**

**Comment by odiea** [comment]
@mckaygerhard . If you were smart you would download the files from Bintray.

**Comment by mckaygerhard** [comment]
@oidea .. me yes! but no those windoser users and you expected a PR please! be smart! **all the great project have great documentation.. but the only documentation in oopensourcepos are that make by me! Je!**

**Comment by izeblood** [comment]
@objecttothis @odiea @andriux1990 @jekkos @WebShells @daN4cat  @SteveIreland @er
![Untitled](https://user-images.githubusercontent.com/32444665/72305249-1ef7ff00-36ae-11ea-8bf1-05928703b714.jpg)

Can anybody help this to realize... when pressing arrow up (event.key==38) and arrow down (even.key==40) this highlight will be move and pressing delete key(46) can delete selected sale transaction.....

**Comment by andriux1990** [comment]
> @objecttothis @odiea @andriux1990 @jekkos @WebShells @daN4cat @SteveIreland
> ![Untitled](https://user-images.githubusercontent.com/32444665/72305249-1ef7ff00-36ae-11ea-8bf1-05928703b714.jpg)
> 
> Can anybody help this to realize... when pressing arrow up (event.key==38) and arrow down (even.key==40) this highlight will be move and pressing delete key(46) can delete selected sale transaction.....

The idea is fine, but there is a problem. The directional arrows are also used to scroll through the browser, if about 15 products are added, you must use the scroll with the directional arrows

**Comment by andriux1990** [comment]
> Shall you submit back a PR guys? Including shortcut keys list... Thanks for the work here..

I will do a PR of this.
There are two ways to do it. a separate js file and call it from the header or include these changes in the js script of register.php
which of the two?

**Comment by daN4cat** [comment]
If it's used in the register only, don't add it elsewhere.

**Comment by andriux1990** [comment]
> If it's used in the register only, don't add it elsewhere.

Mmm OK. I also wanted to use it for reception. but I will do it in each of the scripts

**Comment by Sufisoy** [comment]
> @andriux1990 thanks man for contributing this....
> I'm just want to add what are the variable handler for:
> quantity? yes only quantity... $("#quantity").focus() ?
> BUT... pressing tab is ok for me now...

where is to paste in register.php ?

**Comment by dlwiindi** [comment]
> > @andriux1990 thanks man for contributing this....
> > I'm just want to add what are the variable handler for:
> > quantity? yes only quantity... $("#quantity").focus() ?
> > BUT... pressing tab is ok for me now...
> 
> where is to paste in register.php ?

i have the same question too. did you eventually get to close this one out? you pasted in register.php?

**Comment by blutme** [comment]
> > document.onkeyup=function(e){
> > var e = e || window.event;
> > if(e.which == 119) {
> > $("#add_payment_button").click()
> > }else if(e.which == 120){
> > $("#finish_sale_button").click()
> > }
> > //******************************************
> > var a = a || window.event;
> > if(e.which == 145) {
> > $("#suspend_sale_button").click()
> > }else if(e.which == 27){
> > $("#cancel_sale_button").click()
> > }

thanks for your help. And if I wanted a shortcut to the main sales registration view, you know how would I implement it? I try implement this code but I think it is not the best solution...

`<a id="regiok" href="locahost/ospos/sales">↵</a>`

`$(document).keydown(function(e)
	{ 
		if (e.which == 119) 
		{ 
			$('#regiok').click(); 
			} `

Thanks for your help.
