### ISSUE TITLE
Just to know the use

### ISSUE THREAD

**Issue by akhilnasi** [opensourcepos/opensourcepos#2674]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7
- MySQL or MariaDB version is: 
- OS and version is: win 10
- WebServer is: xampp
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

hi,
i just wanted to know the use of $quantity = $matches[$qtyfirst ? 1 : 2]; in barcode_lib.
$qtyfirst = strpos('d', $barcode_format) - strpos('w', $barcode_format) < 0; 
Do you anyone can tell me about this ?
Any comments will be appreciated
thank you

**Comment by WebShells** [comment]
Hello @akhilnasi, this part of the code is used for the barcode encoding format of weighted products.... Considering w as quantity/weight.

**Comment by akhilnasi** [comment]
i need to use price instead of quantity. how can we define?

**Comment by akhilnasi** [comment]
@WebShells  could you please help me to get the price instead of quantity?

**Comment by WebShells** [comment]
@akhilnasi, sure... It will be a custom development request that will be paid based on hourly rates. In addition, it will be contributed back to the project so everyone can make use of it.
If you don't feel like paying any costs, you can simply set up your digital scale to print Weight encoded barcode in place of price encoded ones. 
A ticket regarding paid request was already created on the website, please follow up with the assigned member.
I will leave this open for opinions...

**Comment by akhilnasi** [comment]
@WebShells .. am ready to pay .. but i need urgently

**Comment by WebShells** [comment]
@akhilnasi please reopen the ticket at https://opensourcepos.org/support and you'll get staff help in order to proceed.
Usually it takes 24 up to 72 hours for custom development requests to be processed depending on availability.

**Comment by akhilnasi** [comment]
> 
> 
> Hello @akhilnasi, this part of the code is used for the barcode encoding format of weighted products.... Considering w as quantity/weight.

$qtyfirst = strpos('d', $barcode_format) - strpos('w', $barcode_format) < 0;
here is it previously defined 'w' and 'd' or just using strpos?

**Comment by akhilnasi** [comment]
@WebShells  could you please explain me what is this?
$quantity = $matches[$qtyfirst ? 1 : 2];

why that ratio?

**Comment by akhilnasi** [comment]
i tried to change the quantity to price but still its passing to quantity only .. can any one help me to change the weigh scale barcode(From quantity to price )
