### ISSUE TITLE
Module Title

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2677]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
![Screenshot_2020-01-11 pos Powered by OSPOS 3 3 2](https://user-images.githubusercontent.com/29256343/72214628-c406b200-34cb-11ea-8680-3f76854cf1c8.png)

Any idea so that right next to OSPOS the name of the module in which it is located appears. Some people agree that sales and registration is very similar, or other modules

**Comment by izeblood** [comment]
Kodus to all contributors of the OSPOS.. As OSPOS evolve its structural design using icons at the header is not essential because as this OSPOS go higher and higher I think there's a congestion of the icons plus the text that support the icons... 
What if we're going to use https://github.com/azouaoui-med/angular-pro-sidebar or https://github.com/azouaoui-med/lightning-admin-angular for the design since this is a responsive sidebar template with dropdown menu based on bootstrap 4 framework.

**Comment by andriux1990** [comment]
You have to do it yourself. I did it the first time is something difficult but then it will be easy. It takes me less than 10 minutes to put all my changes in the latest version of ospos. I have already done it

**Comment by daN4cat** [comment]
Maybe somebody could contribute those type of changes as @jekkos and I did the major overhaul from old OSPOS look'n'feel to new one.

**Comment by izeblood** [comment]
> You have to do it yourself. I did it the first time is something difficult but then it will be easy. It takes me less than 10 minutes to put all my changes in the latest version of ospos. I have already done it

@andriux1990  Please contribute it...
