### ISSUE TITLE
Adding Barcoding Formates including Price

### ISSUE THREAD

**Issue by akhilnasi** [opensourcepos/opensourcepos#2686]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7
- MySQL or MariaDB version is: 
- OS and version is: 10
- WebServer is: xampp
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hi,
Do any one know how to add price in barcode formats instead of weight.
for example:
02->dept
05->item
06->price

@WebShells i have already pulled a request but there were no proper response and taking lot of time to get response (more than two days)
Do any one can make for me this ?

**Comment by WebShells** [comment]
@akhilnasi ill handle that asap... The staff didn't receive their accounts yet for follow up, all the loads been hitting me and @jekkos on the web...
Please avoid creating duplicate issue, ill reset the ticket status.

**Comment by akhilnasi** [comment]
please i need urgently..

**Comment by WebShells** [comment]
@akhilnasi,
As i follow up i saw that @jekkos replied already since a long period of time, bur didnt get a reply from yourside.
Please don't blame any of the staff for not responding to a dead ticket :).

Thank you

**Comment by akhilnasi** [comment]
from first i told i cant pay 100 euros but i agreed with that weak ago..and opened a new ticket a weak ago

**Comment by WebShells** [comment]
@akhilnasi 
100 Euro is the hourly rate... The total amount will depend on how much time the requested feature needs until it gets done.
Thanks for understanding...

**Comment by akhilnasi** [comment]
but jekkos messaged me for 100 euros..  didnot tell for hourly basis.

**Comment by WebShells** [comment]
Then it takes less than an hour to be done :)... Simply!

**Comment by akhilnasi** [comment]
ok then please follow up this ..i will wait till tommarow. because its urgent..thank you @WebShells  ;)

**Comment by izeblood** [comment]
> Hi,
> Do any one know how to add price in barcode formats instead of weight.
> for example:
> 02->dept
> 05->item
> 06->price

I'm just want to ask why you include the price in embedded barcodes since as far as I know, weighed products already had their price base in per grams/kilos/pounds/etc. 
ex. In Item modules you declare those price per kilo and by the use of your digital weighing scale that prints price tag... it embeds product barcode and the quantity.. I already use this function and it works...

**Comment by WebShells** [comment]
@izeblood I tried explaining the same around 3 times so far...

**Comment by akhilnasi** [comment]
@WebShells @izeblood ...for example .. fish price always changes.. so we cannot alwys update the different kinds of fish..instead i would like to this

**Comment by WebShells** [comment]
Well this needs a specific development between the scale and OSPOS, should be generating a list of items labeled as scale items with TXT format, then pushed through a tool set to push data every specific period of time to the scale through network.
Then after you change the price of the item on the system, it automatically updates the scale PLU list... A bit long process but thats how it should be looking for.

**Comment by akhilnasi** [comment]
@WebShells     instead of  that just change to price..
i think it will be better just i wanted in price as i said before
