### ISSUE TITLE
supplier id import csv

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2687]
![DeepinScreenshot_20200116110304](https://user-images.githubusercontent.com/29256343/72546124-d415ed00-384f-11ea-87ae-15b81383e116.png)

How could we do so that the suppliers also matter? or if they are already in the database, when putting the names they refer to them.

Currently this field 'supplier id' does nothing special than just being there.
because no matter how much data is written in this supplier id columba, we will not have any changes at the time of import

**Comment by jekkos** [comment]
I suppose you need to add their database id's here in this case? So indeed you'll need to check you db to find that id and then fill in the correct one in the import file.

**Comment by andriux1990** [comment]
You're right. I did the test this way, writing only the id and it works fine
