### ISSUE TITLE
CASHUP FORM PRINTABLE  HELPME!!!!

### ISSUE THREAD

**Issue by buckbowl** [opensourcepos/opensourcepos#2688]
Información de la Instalación OSPOS: | 3.3.1 - c786d4
es
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓
.Browser: Chrome.Server Software: Apache.PHP Version: 7.3.11.DB Version: 5.7.28.Server Port: 80.OS: Linux phoenix.viewen.com 3.10.0-962.3.2.lve1.5.26.7.el7.x86_64 #1 SMP Wed Oct 2 07:53:12 EDT 2019 x86_64
» [application/logs:] - 0755 | Writable ✓
» [public/uploads:] - 0755 | Writable ✓
» [public/uploads/item_pics:] - 0755 | Writable ✓

Hello, hopefully and someone can help me. 
I want to be able to print (in tikets printer) the CASHUP form (the one with the red circle), could you tell me what lines I have to add so that a print button appears on it? and in what file does it have to be? Please help me, Thank you very much ...
![Imp CashUp](https://user-images.githubusercontent.com/59344753/72567397-726b7800-387b-11ea-97da-5714530aad9d.jpg)

**Comment by jekkos** [comment]
The form itself is not printable, but the overview is (thanks to bootstrap tables). You can export the data in different formats and print that export after.

**Comment by odiea** [comment]
1. Open app/views/cashups/manage and change the table div to the following.
```
<div class="print_hide" id="table_holder">
	<table id="table"></table>
</div>
```
The only problem is you won't be able to print the table view but it is not any good anyway.
Then load the modal and go to print preview and see how it appears. Firefox does not show much but Google shows the entire form. At least on Windows its doesIf it looks and prints good then copy the Print button over to the view/form and see if it prints ok.
The tables will show on the print form if you don't make them hidden. You can then remove the print button from the Manage view. Try it on a test app first.
