### ISSUE TITLE
Adding Extended Price using Attributes

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2689]
Is this possible to use attributes in order to add extended price or for example Price1, Price2, Price3?

aside from the default of pricing an item which is cost price (wholesale now..i don't know why it become wholesale in which this is a supplier's price.. ) and retail price it is important to consider the price adjustment factors for different scenario. Scenario #1: Supplier1 deliver a goods at cost price of 10, Supplier2 at cost price of 13 (all goods are the same except the price). what is the actual price to be use?
Scenario #2: supplier1 delivers a goods at the price of 20, after 5 days, supplier1 deliver a goods at the price of 25, (same product except the price). how your going to manage this...?
what if a certain store has a supplier of 5 or more?

So the question now... How we're going to solve this problem?

**Comment by jekkos** [comment]
You can fill in the price in receivings and it will be registered as such. There's even a functionality that adjusts the item price based on that.

**Comment by jekkos** [comment]
So in short you don't even need attributes for this.

**Comment by izeblood** [comment]
> So in short you don't even need attributes for this.

you mean Calc avg. Price (Receiving)? If this is what you mean... This is not What I mean... if not.. then guide me please @jekkos
