### ISSUE TITLE
How to manually translate it into another language instead of https://weblate.jpeelaer.net/

### ISSUE THREAD

**Issue by wak29** [opensourcepos/opensourcepos#2691]
I have tried to translate it into my native language which is RTL I translated config_lang.php, and common_lang.php pages inide the lang code folders but it is not showing any string I translated. everwhere where translated string should echo it displays 

"module_messages (TBD)
module_customers (TBD)
module_items (TBD)
module_item_kits (TBD)
module_suppliers (TBD)
module_reports (TBD)
module_receivings (TBD)
module_sales (TBD)
module_giftcards (TBD)
module_messages (TBD)
module_expenses (TBD)
module_expenses_categories (TBD)
module_cashups (TBD)
module_office (TBD)" and so on..

which file do I need to run to compile the translation and load it in to the system.?

**Comment by ekardian** [comment]
i did it from here http://translate.opensourcepos.org/

**Comment by wak29** [comment]
This is same as weblate think of it as I have translated manually and placed the translation in its folder now how to load the translation in ospos?

**Comment by jekkos** [comment]
Just download latest build after you commit changes in weblate. These should be visible in the changelog.

**Comment by wak29** [comment]
I didn't get and please excuse me for me not understanding, as I have translated all the strings of Lang files included in the folder locally not on weblate but in local copy in my pc so how can I commit changes in weblate and download latest built to see the translation visible/loaded in already installed ospos on localhost?

**Comment by daN4cat** [comment]
Zip all the files and add those here, we can add to master and sort it out.

**Comment by jekkos** [comment]
@wak29 any chance providing the files to us?

Maybe we should [configure a bot ](https://github.com/fastlane/issue-bot) that closes 'stale' issues after some time, as the tracker has so many that might not be relevant anymore..

**Comment by daN4cat** [comment]
The problem is that some are new feature requests.
