### ISSUE TITLE
Clarification of Low Sell Item 

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2692]
![updateitem](https://user-images.githubusercontent.com/32444665/72702184-bc5ea180-3b8c-11ea-897a-d59aaef22bdb.jpg)

@SteveIreland I'm just want to know, what this Low sell item for? and please educate me how to use this so this we can add this to the wiki...

**Comment by izeblood** [comment]
![updateitem](https://user-images.githubusercontent.com/32444665/72702337-49095f80-3b8d-11ea-9c99-bcfdfa95e56a.jpg)

**Comment by izeblood** [comment]
Updated: I'm trying to follow everything that wiki says on low sell item but, everytime i input id in low sell item nothing happen.

**Comment by SteveIreland** [comment]
I'll test it this weekend to see if something has been broken.  My first thought is that the low sell item might need to have a quantity per pack of 1.

**Comment by SteveIreland** [comment]
I ran a quick test and didn't encounter any problems with assigning a low sell item.

When you enter something in the low sell field it should be providing a "drop down" selection list of low sell items to select from.  Is there anything being provided?

The list of items provided to select from is only looking for items that are active and are flagged as stocked items.

**Comment by izeblood** [comment]
Yes it run well., but my concerned now is the relationship of the package vs each example:
 
![1](https://user-images.githubusercontent.com/32444665/73152528-37830300-410b-11ea-9270-cc599a9828d0.jpg)
![2](https://user-images.githubusercontent.com/32444665/73152554-508bb400-410b-11ea-8632-39a503456275.jpg)

Based on my presentation above, I assigned two sets of packages, cartoon and pcs. the pcs is for my retail and cartoon for wholesale, and I used low sell item for my product2 as wholesale as product1...
Question: What will happen to this? Is the number of item of product1 will be also deducted once I sale product2 as wholesale?

**Comment by SteveIreland** [comment]
The intent is to allow you to keep the same item in stock and allow you to track the number of cases that you have in stock and the number of pieces (broken cases).   So the total inventory for the item (in pieces) is the number of cases multiplied by the "quantity per"  plus the number of pieces from the cases that you've already broken down.

**Comment by izeblood** [comment]
Is my setup above is correct?

**Comment by izeblood** [comment]
When I sale product2 (product 1 and product2 are the same item, they only differ in packages) which is in carton pack and compose of 10 quantity per pack the only item quantity being deducted is the product2 but not in product1. 
In my own understanding this product1 and product2 has relationship that every time you choose to sale either of these products will take effect to each other quantity....right?

**Comment by CoinBR** [comment]
Sorry for bringing this back

So, the sell of a "pack" is not affecting the stock of the "each".
So how we benefit from this feature? How can we tear a "pack" apart into many "each"?
