### ISSUE TITLE
Detailed Reports - Suppliers

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2696]
It is I who I do not understand or the details of the suppliers do not work. I don't look for the reports and I don't get any results or there are others from dates before the current ones.

**Comment by andriux1990** [comment]
I've been testing this for 4 days. and the last one I did in the online demo of ospos

**Comment by daN4cat** [comment]
What kind of Supplier are you selecting? I mean the category you set in suppliers view.

**Comment by andriux1990** [comment]
> What kind of Supplier are you selecting? I mean the category you set in suppliers' view.

I have only supplier with category "Goods supplier"

**Comment by daN4cat** [comment]
@andriux1990 did you manage to debug this and understand why it doesn't work?

**Comment by andriux1990** [comment]
I would have liked to test this. but the last bintray ospos just doesn't start

**Comment by daN4cat** [comment]
Have you tried the demo site?

**Comment by andriux1990** [comment]
> Have you tried the demo site?

I just did it right now, and it doesn't work for me. @daN4cat  Tell me what I'm doing wrong, because I don't have any results in the supplier details
![Screenshot_2020-02-23 DIANE Powered by OSPOS 3 3 2](https://user-images.githubusercontent.com/29256343/75121379-11dd1100-5659-11ea-9ddb-0dd62c10cd97.png)

**Comment by odiea** [comment]
Di you make any Sales using that Supplier today?

**Comment by andriux1990** [comment]
make sales or purchases?
How can I make a sale using a supplier...

**Comment by odiea** [comment]
The suppliers name is attached to the Item that you Sell in the Register.

**Comment by andriux1990** [comment]
> ![2020-02-23 16_14_55-Window](https://user-images.githubusercontent.com/10962177/75122136-beb68e80-5657-11ea-8a70-98cf331fa058.png)
> The suppliers name is attached to the Item that you Sell in the Register.

Well, I did tests as you say and everything is fine. 
Thanks a lot

**Comment by daN4cat** [comment]
Yes, the detailed report by supplier is for the sales. Now I understand where you were coming from.
It doesn't represent any purchase from a supplier, which will be a bit tricky to create.

**Comment by andriux1990** [comment]
> Yes, the detailed report by supplier is for the sales. Now I understand where you were coming from.
> It doesn't represent any purchase from a supplier, which will be a bit tricky to create.

Many suppliers distribute the same product. What to do in this case?

**Comment by daN4cat** [comment]
Are those suppliers or agents?

**Comment by daN4cat** [comment]
In any case there is many to many relationship supported by OSPOS. It's one (supplier) to many (items).

**Comment by crevilla2050** [comment]
![image](https://user-images.githubusercontent.com/62775466/120131103-40fffd80-c18d-11eb-9722-311657c5fa78.png)
Well, I have this issue. When trying a detailed sales per supplier I get a blank page. Installed version is 3.3.4, unmodified.
Everything else seems to work fine.
How to resolve this? error log gives me nothing.
Thanks

**Comment by jekkos** [comment]
Are you using mysql or mariadb?
