### ISSUE TITLE
Location sales not selected

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2697]
In ospos demo (https://demo.opensourcepos.org) there are two locations.
In sales I give the user permission to sell only from one location, but this does not work properly because it takes the products from the location that is not selected.

This error is in both bintray and the ospos master.
You can check it in the ospos demo where there are two locations and you will see that it takes products from the stock location and not from the one currently selected.

**Comment by andriux1990** [comment]
that nobody else notices this error

**Comment by mckaygerhard** [comment]
maybe nobody noted due nobody uses complety the system, OR
maybe already noted but developer pass off the issue 
and the most possible are: 
**maybe reported several times but due almost all the people dont fill propeerty the issue template (that are xtreme complicated to windosers), those reports are pass off**

**Comment by daN4cat** [comment]
Simply I didn't find the time to test this.
I don't have this setup so the priority for me at the moment is to make sure the deployment I made on 1st Jan works fine with the shop.

Later I will look into other issues...

**Comment by andriux1990** [comment]
> Simply I didn't find the time to test this.
> I don't have this setup so the priority for me at the moment is to make sure the deployment I made on 1st Jan works fine with the shop.
> 
> Later I will look into other issues...

This is a serious mistake. Because Ospos is not taking the items from the selected locations. And this is happening. you can enter the demo of ospos and do the tests for yourself

**Comment by jekkos** [comment]
@andriux1990 you're doing a good job there bughunting. Interested in becoming an organisation member?

**Comment by jekkos** [comment]
@andriux1990 can you check my PR to verify if the fix works? Thanks!

**Comment by andriux1990** [comment]
> @andriux1990 can you check my PR to verify if the fix works? Thanks!

I did tests with firefox. and the problem apparently persists.
![Screenshot_2020-01-30 Neo Store Powered by OSPOS 3 3 2](https://user-images.githubusercontent.com/29256343/73450545-36302100-432b-11ea-96e3-f6a9d18fd7bc.png)
![Screenshot_2020-01-30 Neo Store Powered by OSPOS 3 3 2(1)](https://user-images.githubusercontent.com/29256343/73450546-36302100-432b-11ea-8b7d-783da091b325.png)
 then I tried more with another browser with opera and here I was looking for the products of the selected location. 
![DeepinScreenshot_20200130063435](https://user-images.githubusercontent.com/29256343/73450593-5233c280-432b-11ea-981e-114c6f8d4a89.png)

This will have to do with the browser cache.
This error also occurs when you have all permissions, with few permissions this does not happen

so that in firefox it works just log me out and then start again and here if it already works correctly

**Comment by andriux1990** [comment]
> @andriux1990 you're doing a good job there bughunting. Interested in becoming an organisation member?

Yes, of course I would like to, I would be happy to be it

**Comment by WebShells** [comment]
Welcome to the club @andriux1990 😎.

**Comment by andriux1990** [comment]
Thanks you @WebShells

**Comment by jekkos** [comment]
@andriux1990 I have sent you an invite. Indeed you might need to logout first to test this fix, as the browser might have the wrong location id set in the session. 
So but did it work after refreshing the session?

**Comment by andriux1990** [comment]
> @andriux1990 I have sent you an invite. Indeed you might need to logout first to test this fix, as the browser might have the wrong location id set in the session.
> 
> So but you confirm that it works when logging in with a fresh session (browser)?

Thank you. I received the email and accepted

**Comment by jekkos** [comment]
@andriux1990 can we merge this issue? Is it fixed?

**Comment by andriux1990** [comment]
> @andriux1990 can we merge this issue? Is it fixed?

yes @jekkos. no longer a problem now, thanks
it works fine you just have to restart session, but this is no problem doing it

**Comment by daN4cat** [comment]
It's in master now.
Thanks @jekkos for fixing this issue.
