### ISSUE TITLE
Enter key when adding a new product

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2699]
Adding a new product and pressing the Enter key activates the button new. and not the submit button as it did before, this can result in creating duplicate products by mistake if it is not pending, since when giving new with enter it leaves all the information and only eliminates the barcode

**Comment by jekkos** [comment]
That's not a bug, but a feature! We use it to enter items in bulk into our system. Most of the time the only difference between entries is price or just barcode, this makes it really easy.

**Comment by izeblood** [comment]
Now it's CLEARED...

**Comment by jekkos** [comment]
To make myself clear, you should use it from the sales or receivings register so that all new products are added to a ticket first. In case you have any good arguments on changing the behavior, let me know and we can consider adding a switch for this.

**Comment by andriux1990** [comment]
> To make myself clear, you should use it from the sales or receivings register so that all new products are added to a ticket first. In case you have any good arguments on changing the behavior, let me know and we can consider adding a switch for this.

An interuptor would be super. because I was using it in the item module and it happened more than once that I duplicated the products at least with the name. I was already used to pressing the enter key to save the product and close the modal.
but if the switch is created this would be applicable for both cases
