### ISSUE TITLE
serious error in Inventory Summary

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2702]
serious error in
Inventory Summary
![DeepinScreenshot_20200128162332](https://user-images.githubusercontent.com/29256343/73310827-a71bef80-41ea-11ea-8241-871816c1aaec.png)
https://demo.opensourcepos.org/reports/inventory_summary/all/more_than_zero

**Comment by jekkos** [comment]
Sorry but, what is the issue here?  I don't understand spanish well enough. Also try to adhere to the template.

**Comment by odiea** [comment]
He is correct. There are no amounts shown in the Summary Totals.
![2020-01-28 16_48_39-Window](https://user-images.githubusercontent.com/10962177/73315766-337be180-41ee-11ea-84c0-a196bf366006.png)

**Comment by odiea** [comment]
@jekkos If you get a chance to fix the above issue could you also fix Low Inventory so that it does not show any deleted locations. Thanks @odiea .

**Comment by odiea** [comment]
I figured it out. In Models Low_Inventory I added the following below AND item_quantities.quantity <= items.reorder_level.
AND stock_locations.deleted = 0  Now it just shows the current stock location.

**Comment by jekkos** [comment]
Thanks for that @odiea. I applied your fix + submitted a PR for this other issue, not sure why this was changed recently and will wait for the review before merge.

**Comment by odiea** [comment]
After applying your fix. Looks Good to me. Also no logged errors now.
![2020-01-29 15_43_06-Window](https://user-images.githubusercontent.com/10962177/73404216-5cfc4200-42ae-11ea-92e6-fb99dbe69f4f.png)

**Comment by andriux1990** [comment]
> I figured it out. In Models Low_Inventory I added the following below AND item_quantities.quantity <= items.reorder_level.
> AND stock_locations.deleted = 0 Now it just shows the current stock location.

this did not work for me

**Comment by andriux1990** [comment]
the problem is here. in controllers / Reports on line 1630
'summary_data' => $this->xss_clean($model->getSummaryData($inputs))
you just have to replace $inputs with "report_data

there are 3 lines 'summary_data' => $this->xss_clean($model->getSummaryData($inputs)) of these in reports

**Comment by daN4cat** [comment]
I need to check this over the weekend because it's not following the rest of the reports pattern somehow.

**Comment by daN4cat** [comment]
Merged the fix, I close this issue.
