### ISSUE TITLE
Page goes blank when completing a sale : key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales_items_taxes`

### ISSUE THREAD

**Issue by aromal** [opensourcepos/opensourcepos#2713]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1 - c786d4
- OSPOS git commit hash is: 
- PHP version is: 7.2.24-0ubuntu0.18.04.2
- MySQL or MariaDB version is:  5.7.29-0ubuntu0.18.04.1
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I'm getting a blank page when completing a sale after setting up the tax rates. The following error is from the log file. This happens when we complete a sale.

ERROR - 2020-02-03 21:01:26 --> Query error: Duplicate entry '9-1111-1-GST-2.5000' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales_items_taxes` (`sale_id`, `item_id`, `line`, `name`, `percent`, `tax_type`, `rounding_code`, `cascade_sequence`, `item_tax_amount`, `sales_tax_code_id`, `tax_category_id`, `jurisdiction_id`) VALUES (9, '1111', 1, 'GST', '2.5000', '1', '1', '0', 31.2, '1', '1', '2')

![ospos4](https://user-images.githubusercontent.com/625305/73668649-28ccbb00-46cc-11ea-9ca6-9a0d939f6d0f.png)
![ospos3](https://user-images.githubusercontent.com/625305/73668651-28ccbb00-46cc-11ea-86df-714f9967c723.png)
![ospos2](https://user-images.githubusercontent.com/625305/73668652-28ccbb00-46cc-11ea-8677-c3c94a8b0ec4.png)
![ospos1](https://user-images.githubusercontent.com/625305/73668654-29655180-46cc-11ea-8f7d-2cd85ba0e350.png)

**Comment by daN4cat** [comment]
Have you fiddled with MySQL database directly?

**Comment by aromal** [comment]
No.  This issue is easily reproducible if you configure the taxes as per
the screenshots attached and create a sale.
I just set up a fresh installation and set up the taxes in the same manner
and got the same error.

Thanks & Regards
Aromal

**Comment by daN4cat** [comment]
@steveireland this is for you to fix.

**Comment by jekkos** [comment]
The question is, is this a valid usecase? 
* If it is, then I think we need to change the constraint
* If it is not, then we handle this error gracefully in the UI and show a proper error message

**Comment by daN4cat** [comment]
This is more of an anomaly than a normal use case.

**Comment by jekkos** [comment]
The error looks weird in a way, that he has a duplicate entry for one sale, line 1 and linked to a specific item? It's not clear to me what he was doing in the register before seeing this error.

**Comment by SteveIreland** [comment]
Just saw this and it's a little late for me to dive into it.  I'll take a look at it tomorrow evening.

**Comment by aromal** [comment]
Hi,

I think it is a valid use case for Indian users. I'm not sure why nobody
reported yet.
Although the error shows like a duplicate entry for one sale, it is not the
case. It even happens with the first sale in a fresh installation.

Thanks & Regards
Aromal

**Comment by SteveIreland** [comment]
I don't believe that during development I was expect that the tax group code on the jurisdiction table would be anything other than unique for each tax jurisdiction. For tracking purposes it should be unique.

Before we add a constraint to insure that it is unique, is there reason that you would need them to be the same?  I'm curious as to why you configured it that way. 

The tax group is a way I adapt the destination based taxing to the existing tax system.  It's a compromise apparently it needs to be made a little more heavy duty.

**Comment by aromal** [comment]
Hi Steve,
There is no reason that the codes to be the same. I changed it and that error got disappeared. I didn't know the group code must be unique and that wasn't mentioned anywhere in the system. Also, the error I saw in the log was something different and hence it was difficult to track. Thanks for this. I think you should give a proper error message to be shown in that area. Thanks much!

**Comment by daN4cat** [comment]
@SteveIreland it's better to enforce a rule to avoid similar issue going forward.

**Comment by SteveIreland** [comment]
@daN4cat work and other stuff kept me busy this weekend so I didn't have a chance to work up anything for this.  So I'll try to slip it in during the week.  Is there a hard date on the 3.3.2 release?  Hopefully it wasn't this weekend.  :-(

**Comment by daN4cat** [comment]
@SteveIreland work comes first. Whenever you have time please fix this.

**Comment by daN4cat** [comment]
Fix in master. I close.
