### ISSUE TITLE
Demo server down with the following error

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2716]
An Error Was Encountered
Unable to load the requested language file: language/talong/form_validation_lang.php

**Comment by mckaygerhard** [comment]
the name are bad written.. of the filename and was refered badly in the code

**Comment by odiea** [comment]
Working now.

**Comment by WebShells** [comment]
Demo server facing issues again, not my fault this time guys ;p... Had some time wanted to check the installation info page... Please check demo, thanks <3

**Comment by jekkos** [comment]
Logged into it, seems fine?

**Comment by WebShells** [comment]
Yesterday it wasn't, the tables weren't displaying, the system info tab was redirecting to main home... Anyway working fine now ! Will close

**Comment by WebShells** [comment]
Demo bad gateway...

**Comment by odiea** [comment]
Working now.

**Comment by WebShells** [comment]
Demo: Unable to load the requested language file: language/lao/form_validation_lang.php

**Comment by odiea** [comment]
A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: core/CodeIgniter.php

Line Number: 518
