### ISSUE TITLE
Facing issue in Installing OpensourcePOS in Docker Compose.

### ISSUE THREAD

**Issue by V-Bhadauriya** [opensourcepos/opensourcepos#2717]
I followed the INSTALL.md for installing and configuring the OpensourcePOS latest in docker-compose.
Every dependent container is up and running fine, but when I am trying to access the UI getting below error.
_**“Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php”**_
  I checked the index.php file system path is:

**$system_path = '../vendor/codeigniter/framework/system';**

I checked in the container this folder doesn’t exist. 
Can any one help me on fixing this issue.

Thanks in advance.

**Comment by daN4cat** [comment]
What do you use to install docker?
Have you tried the docker/ scripts?
Also is that on a local laptop or hosted on the Internet?

**Comment by V-Bhadauriya** [comment]
@daN4cat , 
I have set up a VM of Ubuntu OS 16.x in my vcenter lab.
I have  install the docker with command:
**apt-get install docker docker-compose**

After cloning the OpensourcePOS repo, I have used below command to deploy the OpensourcePOS.

 **bash docker/install-local.sh** 

All containers all up and running.

**Comment by daN4cat** [comment]
Exactly, using the script will do for you.

Next time it would be good to read INSTALL.md 😉

**Comment by daN4cat** [comment]
I close this issue.
