### ISSUE TITLE
Error query at sales report details

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2721]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [ ] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [ ] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [ ] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: master
- OSPOS git commit hash is: 
- PHP version is: 7
- MySQL or MariaDB version is: 10
- OS and version is: Linux
- WebServer is: apache
- Selected language is: en

### Issue / Bug  / Question / New Feature

I got a recent problem:

here i get and error, working on a "Due account" feature, try to get sales 
details and got not working, so testin in a clean install and seems ospos 
have an problem, here are the log using log level 4 in config.php (was hard to find it)

```
ERROR - 2020-02-13 06:46:57 --> Query error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'osposweb_gales.ospos_sales_items_temp.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - Invalid query: SELECT `name`, `category`, `quantity_purchased`, `item_location`, `item_number`, `description`, `subtotal`, `tax`, `total`, `cost`, `profit`, `discount`, `discount_type`, `sale_status`, GROUP_CONCAT(DISTINCT CONCAT_WS('_', `definition_id`, attribute_value) ORDER BY definition_id SEPARATOR '|') AS attribute_values, GROUP_CONCAT(DISTINCT CONCAT_WS('_', `definition_id`, DATE_FORMAT(attribute_date, '%m/%d/%Y')) SEPARATOR '|') AS attribute_dtvalues, GROUP_CONCAT(DISTINCT CONCAT_WS('_', `definition_id`, attribute_decimal) SEPARATOR '|') AS attribute_dvalues
FROM `ospos_sales_items_temp`
LEFT JOIN `ospos_attribute_links` ON `ospos_attribute_links`.`item_id` = `ospos_sales_items_temp`.`item_id` AND `ospos_attribute_links`.`sale_id` = `ospos_sales_items_temp`.`sale_id` AND `definition_id` IN (1,2,3)
LEFT JOIN `ospos_attribute_values` ON `ospos_attribute_values`.`attribute_id` = `ospos_attribute_links`.`attribute_id`
WHERE `ospos_sales_items_temp`.`sale_id` = '1672'
GROUP BY `ospos_sales_items_temp`.`sale_id`, `ospos_sales_items_temp`.`item_id`
ERROR - 2020-02-13 06:46:57 --> Severity: Error --> Call to a member function result_array() on boolean /home/general/Devel/client-gales-ospos/application/models/reports/Detailed_sales.php 160
```

**Comment by daN4cat** [comment]
Version please....

**Comment by daN4cat** [comment]
That's the sql_mode=only_full_group_by issue

**Comment by andriux1990** [comment]
opensourcepos.20200205205545.master.ca2907

**Comment by daN4cat** [comment]
How to reproduce in OSPOS?

**Comment by daN4cat** [comment]
@jekkos this is another of the same issues. Could you please check and fix?

**Comment by daN4cat** [comment]
I'll check myself over the week end.

**Comment by mckaygerhard** [comment]
the proble are the excesive usage of GROUP CONCAT that are the famous _aggregate_ function that concatenates strings from a group into a single string_ but here are used to make cross-query with various options.

![imagen](https://user-images.githubusercontent.com/1571724/74537010-9ddf9200-4f0f-11ea-8c02-3c05a092229b.png)

it converts the vaues of rows as colums.. that can be made with php code.. and solves.. 

why cause problems?: well  MySQL are the kid's dabatase choice.. it makes life easy, group concat breaks standard SQL due does not follow the GROUP BY limitations as http://dev.cs.ovgu.de/db/sybase9/help/dbugen9/00000284.htm

where is the problem?: due implies an aggregate functions, so used with the GROUP BY clause to calculate an aggregate value for each group (remenber that this group are the colums value concatenated into a string separated by commas), the average value by the group or the sum of values in each group. of course due group by are in break, recent versions of mysql does now follow the standar and this are mandatory .. so the group by are not work anymore.. 

![imagen](https://user-images.githubusercontent.com/1571724/74540273-de420e80-4f15-11ea-9c6a-5cf10363d7aa.png)

solutions (from more easy to most difficult): 

* use older versions of mariadb/mysql very cheap one..  but some people here will said stupid things like "be secure" etc etc
* change the mysql mode as @daN4cat said _"That's the `sql_mode=only_full_group_by` issue_ but this are a break that will be missing in future versions, and as always does not source whre was "that" issue previously reported
* remade the code using php pure and iterate into results.. that's are less optimal but more compatible and proper to do.. due in future all will be mes and cloud computing are the future

justifications: people does not will install locally in business.. always will buy an cloud host and store there the install of opsos.. of course will not work and will be dischartd..  ok so then ospos are only for small vbery small bussiness.. ?

**Comment by mckaygerhard** [comment]
the problem are the excessive usage of GROUP CONCAT that are the famous _aggregate_ function that concatenates strings from a group into a single string_ but here are used to make cross-query with various options.

![imagen](https://user-images.githubusercontent.com/1571724/74537010-9ddf9200-4f0f-11ea-8c02-3c05a092229b.png)

it converts the vaues of rows as colums.. that can be made with php code.. and solves.. 

**why cause problems?**: well  MySQL are the kid's dabatase choice.. it makes life easy, group concat breaks standard SQL due does not follow the GROUP BY limitations as http://dev.cs.ovgu.de/db/sybase9/help/dbugen9/00000284.htm

**where is the problem?**: due implies an aggregate functions, so used with the GROUP BY clause to calculate an aggregate value for each group (remenber that this group are the colums value concatenated into a string separated by commas), the average value by the group or the sum of values in each group. of course due group by are in break, recent versions of mysql does now follow the standar and this are mandatory .. so the group by are not work anymore.. 

![imagen](https://user-images.githubusercontent.com/1571724/74540273-de420e80-4f15-11ea-9c6a-5cf10363d7aa.png)

**solutions** (from more easy to most difficult and right made it): 

* use older versions of mariadb/mysql very cheap one..  but some people here will said stupid things like "be secure" etc etc
* change the mysql mode as @daN4cat said _"That's the `sql_mode=only_full_group_by` issue_ but this are a break that will be missing in future versions, and as always does not source whre was "that" issue previously reported
* remade the code using php pure and iterate into results.. that's are less optimal but more compatible and proper to do.. due in future all will be mes and cloud computing are the future

**justifications**: people does not will install locally in business.. always will buy an cloud host and store there the install of opsos.. of course will not work and will be discharged..  ok so then ospos are only for small very small bussiness.. ? many people cannot ajust their php and/or mysql settings  @jekkos  and seems are a problem that only happened in recent mysql version due was fixed the "ambiguous" usage of group concat.. yes group concat are not completed until recent versions

**Comment by mckaygerhard** [comment]
the problem are the excessive usage of GROUP CONCAT that are the famous _aggregate_ function that concatenates strings from a group into a single string_ but here are used to make cross-query with various options.

![imagen](https://user-images.githubusercontent.com/1571724/74537010-9ddf9200-4f0f-11ea-8c02-3c05a092229b.png)

it converts the values of rows as columns.. that can be made with php code.. and solves.. 

**why cause problems?**: well  MySQL are the kid's database choice.. it makes life easy, group concat breaks standard SQL due does not follow the GROUP BY limitations as http://dev.cs.ovgu.de/db/sybase9/help/dbugen9/00000284.htm

**where is the problem?**: due implies an aggregate functions, so used with the GROUP BY clause to calculate an aggregate value for each group (remember that this group are the columns value concatenated into a string separated by commas), the average value by the group or the sum of values in each group. of course due group by are in break, recent versions of mysql does now follow the standard and this are mandatory .. so the group by are not work anymore.. 

![imagen](https://user-images.githubusercontent.com/1571724/74540273-de420e80-4f15-11ea-9c6a-5cf10363d7aa.png)

**solutions** (from more easy to most difficult and right made it): 

* use older versions of mariadb/mysql very cheap one..  but some people here will said stupid things like "be secure" etc etc
* change the mysql mode as @daN4cat said _"That's the `sql_mode=only_full_group_by` issue_ but this are a break that will be missing in future versions, and as always does not source whre was "that" issue previously reported
* remade the code using php pure and iterate into results.. that's are less optimal but more compatible and proper to do.. due in future all will be mes and cloud computing are the future

**justifications**: people does not will install locally in business.. always will buy an cloud host and store there the install of opsos.. of course will not work and will be discharged..  ok so then ospos are only for small very small bussiness.. ? many people cannot adjust their php and/or mysql settings , seems @jekkos  that this problem are a fix in recent versions of mysql due group concat have a ambiguous result

**Comment by andriux1990** [comment]
> I'll check myself over the week end.

thanks

**Comment by andriux1990** [comment]
> the problem are the excessive usage of GROUP CONCAT that are the famous _aggregate_ function that concatenates strings from a group into a single string_ but here are used to make cross-query with various options.
> 
> ![imagen](https://user-images.githubusercontent.com/1571724/74537010-9ddf9200-4f0f-11ea-8c02-3c05a092229b.png)
> 
> it converts the values of rows as columns.. that can be made with php code.. and solves..
> 
> **why cause problems?**: well MySQL are the kid's database choice.. it makes life easy, group concat breaks standard SQL due does not follow the GROUP BY limitations as http://dev.cs.ovgu.de/db/sybase9/help/dbugen9/00000284.htm
> 
> **where is the problem?**: due implies an aggregate functions, so used with the GROUP BY clause to calculate an aggregate value for each group (remember that this group are the columns value concatenated into a string separated by commas), the average value by the group or the sum of values in each group. of course due group by are in break, recent versions of mysql does now follow the standard and this are mandatory .. so the group by are not work anymore..
> 
> ![imagen](https://user-images.githubusercontent.com/1571724/74540273-de420e80-4f15-11ea-9c6a-5cf10363d7aa.png)
> 
> **solutions** (from more easy to most difficult and right made it):
> 
> * use older versions of mariadb/mysql very cheap one..  but some people here will said stupid things like "be secure" etc etc
> * change the mysql mode as @daN4cat said _"That's the `sql_mode=only_full_group_by` issue_ but this are a break that will be missing in future versions, and as always does not source whre was "that" issue previously reported
> * remade the code using php pure and iterate into results.. that's are less optimal but more compatible and proper to do.. due in future all will be mes and cloud computing are the future
> 
> **justifications**: people does not will install locally in business.. always will buy an cloud host and store there the install of opsos.. of course will not work and will be discharged.. ok so then ospos are only for small very small bussiness.. ? many people cannot adjust their php and/or mysql settings , seems @jekkos that this problem are a fix in recent versions of mysql due group concat have a ambiguous result

This could be a serious problem in the future. thanks

**Comment by daN4cat** [comment]
@andriux1990 please forget about he says. Keeps producing river of words and solve nothing, even miunderstanding what people say. Unfortunately....

**Comment by daN4cat** [comment]
@andriux1990 I commited a change to master. Wait for a new version to be packaged and made available in bintray and then test it.
If you get a similar error with another field, please repeat the fix I made in line 148 - MAX(name) AS name - to the next one that produces the error.

I can't test this properly because I don't have a setup with attributes and sql_mode=only_full_group_by  enabled to see if it's all fine.

**Comment by mckaygerhard** [comment]
interesting i dont care my commet was deleted a hole community was clear.. thanks for the RIGHT fix, all my comment always come in mail form also .. X-;

**Comment by daN4cat** [comment]
@andriux1990 travis build failed. I don't think it's my change but I don't have time to check the issue now. Pick up the files I changed and replace the ones you have with those.

**Comment by andriux1990** [comment]
OK. Where do you think the error may be?
The changes I had made was just adding a MAX and an AS.

it makes sense but it doesn't seem to be enough

**Comment by daN4cat** [comment]
@andriux1990 what is the new error log?

**Comment by daN4cat** [comment]
@andriux1990 any news?

**Comment by andriux1990** [comment]
It seems to be working fine, the registry log doesn't show me this problem now. Thank you @daN4cat

**Comment by daN4cat** [comment]
Was my fix enough or have you added more MAX and AS?

**Comment by andriux1990** [comment]
> Was my fix enough or have you added more MAX and AS?

Yes @daN4cat and thank you

**Comment by daN4cat** [comment]
Good, case closed.
