### ISSUE TITLE
Bug in items table with search in attributes selected

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2723]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: ca2907
- PHP version is: 7.3.6
- MySQL or MariaDB version is: 5.7.26
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug

In the latest master if I select the "Search in Attributes" option of the items view then search for a keyword the table does not display any information in any of the custom attributes except for matching cells for my search column.  For example, I have a text attribute called "Author" and with "search in attributes" selected if I type "Lewis" the table properly returns all items with "Lewis" in any attribute or name fields, but all the other columns are blank
![Annotation 2020-02-14 113249](https://user-images.githubusercontent.com/17935339/74510721-cc646980-4f1d-11ea-9c27-dcc6e7415ff0.jpg)

**Comment by jekkos** [comment]
Ouch, seems like a regression as I saw this working in the past

**Comment by objecttothis** [comment]
If you do a basic search without searching attributes it still works.  It's only when you search attributes that it has a problem.

**Comment by daN4cat** [comment]
@jekkos any chance to look into this?
