### ISSUE TITLE
Locations Kit

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2725]
When you have more than one location and products are added to a kit.
From which location are the products sold?

This is something that has not been taken into account

**Comment by mckaygerhard** [comment]
sounds complicated.. lest check:

i have a kit.. with two products, product1 from location1 and product2 from location2 so how we will xporess that in the kit?

**Comment by jekkos** [comment]
Not sure if the inventory level changes if you just configure the kit? Otherwise if you sell one, the currently selected location will be taken into account, no?

**Comment by mckaygerhard** [comment]
well as i explained.. of course.. but currently it happened as is? @jekkos ?
