### ISSUE TITLE
Stale issue bot configuration

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2726]
Just to inform all, I added an issue bot tracker to the project that willl

* Mark issues as 'stale' after 30 days
* Close issues with label 'stale' after 7 days

I just want to see that open questions are answered and closed and that only relevant tickets stay open.

Current configuration ignores issues with the 'enhancement' and 'needsowner' labels. I'll add 'bug' label as well.

First let's see if this works, otherwise If any suggestion to change the behavior then let's discuss here

**Comment by jekkos** [comment]
Ok the setup seems to work, first we have a notification that sends to the people involved. If they don't tag the issue properly or react to that then the issue is closed.

**Comment by daN4cat** [comment]
Yes, we should be careful in tagging the issues properly.
I reopened a couple of them that can be fixed easily since the author added the code (CLI mode).
