### ISSUE TITLE
No new BinTray builds?

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2729]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue

I'd like to rebase the event generator branch on master before fixing it, but I'm seeing that there are no new builds in BinTray for me to then download the rebased version for testing. @jekkos can you see if there is a problem on the bintray end?

**Comment by daN4cat** [comment]
I posted a comment the other day, I cannot get where Travis build is configured/controlled now.

**Comment by objecttothis** [comment]
I must have missed that comment.  Do we have a place for contributors can have these kinds of discussions without needing to open issues?  There is an opensourcepos/devroom in gitter that would suit that very well, but either we aren't all aware of it, or don't use it consistently.  Thoughts?

**Comment by daN4cat** [comment]
It was in Release 3.1.2 but this issue is the correct way to deal with this. So no worries.

I hope @jekkos can reply soon.

**Comment by objecttothis** [comment]
OK, sounds good.

**Comment by daN4cat** [comment]
I don't know why I couldn't see .travis.yml file the other day... I was probably too tired :-S

**Comment by daN4cat** [comment]
Let see if the run goes trough without errors.

**Comment by daN4cat** [comment]
I gave a try but fixed the composer docker issue to bump into another, which is the lack of gd extension.
No time now to check that....

**Comment by jekkos** [comment]
Looks like the composer image was changed for some reason. I might want to install gd manually then.

**Comment by daN4cat** [comment]
Yes composer/composer needed to change to be just composer.

However if you could amend the Travis script install gd hopefully we are good again.

**Comment by daN4cat** [comment]
I don't understand why they break backward compatibility with those docker image name changes. It's a maintenance nightmare to do that.

**Comment by objecttothis** [comment]
@daN4cat I assume that your working on this here is why bintray is empty now and there are no builds in it?  I wish we had a more reliable build repository that Bintray.

**Comment by objecttothis** [comment]
Are there instructions somewhere on how to manually build the whole project?  I looked at the install.md and it doesn't seem to point anywhere for that level of detail.

**Comment by jekkos** [comment]
It seems that one of our depencies needs gd installed and composer decided to strip most php extensions.

I went through their docs, they suggest to import composer into another docker image and run like this. So in this case we'd have to build a custom container that has both php and gd, and then also composer itself, unless we find something else that has these three things included.

**Comment by jekkos** [comment]
It seems that one of our depencies needs gd installed and composer decided to strip most php extensions.

I went through their docs, they suggest to import composer into another docker image and run like this. So in this case we'd have to build a custom container that has both php and gd, and then also composer itself, unless we find something else that has these three things included.

**Comment by daN4cat** [comment]
Or run the docker image php 7.x and install composer from run cmd line and then run the composer script.

**Comment by objecttothis** [comment]
Deleted duplicate comments

**Comment by jekkos** [comment]
Builds are back in bintray. I changed the travis setup a bit and have created my own 'buildbox' for the project. Cool thing is that this setup contains only the dependencies we need, and won't break as we I maintain it myself.

For the dockerfile, check out [github.com/jekkos/composer](github.com/jekkos/composer). 

Idea is to keep the required dependencies for building the project separate from the ones that are required to run it. In total there should be three docker setups

* One to install composer + package the zip, do some sanity checks
* One to run the application, this is the result of the build done by the previous step
* One to run the tests of the application. This is done by a separate container that is based on the previous one, but has extra dependencies in it like phpunit that are not required for running the app itself. The tests themselves are in the source code, but should also not be packaged in the final zip.
