### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by digitaloffensive** [opensourcepos/opensourcepos#2730]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: c786d4
- PHP version is: PHP 7.0.33
- MySQL or MariaDB version is:  10.0.38
- OS and version is: Ubuntu 16.04
- WebServer is: Apache
- Selected language is: English
- (If applicable) Docker installation: NA
- (If applicable) Installation package for the LAMP/LEMP stack is: NA

### Issue #####

Following some trouble shooting issues Iam seeing this error while trying to diagnose a 500 error
----------------------
An uncaught Exception was encountered
Type: ParseError

Message: syntax error, unexpected '=>' (T_DOUBLE_ARROW)

Filename: /var/www/html/application/config/database.php

Line Number: 77

Backtrace:

File: /var/www/html/public/index.php
Line: 315
Function: require_once
--------------------------------

Line 77 points to the dns line of the database.php and when you comment it out it just moves the error to next line.

Line 315 points to the codeignitor include once message.

Iam not sure how to fix this error. I have gone through multiple faq's and searching all 500 issues on the threads.

**Comment by objecttothis** [comment]
We need more background to understand the situation.  Is this a new install?  Fresh database? Did you read the install.md to confirm you have all of the required php modules installed?

PHP needs to have php-gd, php-bcmath, php-intl, php-openssl, php-mbstring and php-curl installed and enabled.
in the config file you should increase the log threshold and make sure that your log directory has proper permissions.  See if anything gets spat out there.  I'm guessing there won't be.

**Comment by digitaloffensive** [comment]
The install is new.

PHP installed modules:
apt install php libapache2-mod-php php-common php-mbstring php-xmlrpc php-soap php-gd php-xml php-intl php-mysql php-cli php-zip php-curl

apt install php php-bcmath php-openssl

OpenSSL support | enabled
cURL support | enabled
The whole list can be seen in the attached file
[phpinfo.txt](https://github.com/opensourcepos/opensourcepos/files/4226522/phpinfo.txt)
Just rename the file to .htm extension.

Log directory is 755 so the owner www-data should be able to write to the directory. I modified the config to be log level 4 and I see not data show up.

**Comment by digitaloffensive** [comment]
I have found one issue and corrected it though now I get a new error:

An uncaught Exception was encountered
Type: Error

Message: Call to undefined function bcscale()

Filename: /var/www/html/application/hooks/load_config.php

Line Number: 42

Backtrace:

File: /var/www/html/public/index.php
Line: 315
Function: require_once

The previous issue was I had a line commented out in the database.php

**Comment by daN4cat** [comment]
Usually that is due to rewrite module not being enable or similar issues.
If you found a solution already please add it here so other people facing the same issue know what to check when searching for past cases.
