### ISSUE TITLE
new item

### ISSUE THREAD

**Issue by bowenjnr** [opensourcepos/opensourcepos#2732]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- **[X]** Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1 - c786d4
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 5.7
- OS and version is: Ubuntu LAMP 18 Digital Ocean
- WebServer is: Apache2
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I have a new installation of the latest OSPOS version and now when am logged in I tried to add new item and the button "NEW" is inactive

**Comment by bowenjnr** [comment]
![image](https://user-images.githubusercontent.com/46376364/74906002-c27cb380-53c0-11ea-9a25-ffeedd037130.png)

the New button is inactive

**Comment by daN4cat** [comment]
Please fill in the issue template.

**Comment by bowenjnr** [comment]
Thanks. I have filled the issue template on the earlier on submitted issue by amending it.

**Comment by odiea** [comment]
Now please read the Issues and you will find the answer.

**Comment by bowenjnr** [comment]
Thanks I have read and found an answer

**Comment by daN4cat** [comment]
Was the answer the known issue about the database configuration with full group by?
