### ISSUE TITLE
Default permissions on logs directory

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2733]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug
Correct me if I'm wrong, but the default permissions given to the /application/logs/ directory is 755 or 775.  For security, shouldn't this be 750 or 770? I'm having a difficult time thinking of a scenario in which it's safe for world to have read access to the logs.

**Comment by jekkos** [comment]
OK sure feel free to adapt this, normally we run with the same user as the one that owns the actual files.

**Comment by daN4cat** [comment]
I need to check but I probably set 750 in my case.

**Comment by objecttothis** [comment]
The safest is 750. For those using shared hosting where they have no control over who else is in the group, 750 should be default. Everyone else can manually change it to what's needed...

**Comment by daN4cat** [comment]
I actually have 740.

**Comment by daN4cat** [comment]
So not sure I understand, what is that needs to be changed here?

**Comment by objecttothis** [comment]
Sorry, part of this was from my misunderstanding about the nature of zip files.  Zip files do not preserve permissions, so the permissions get set to whatever the OS sets them to when the unzip is performed.  

@WebShells did a great job on the installation info, but the check for logs (and probably other folders) should show red if the permissions for the folder are too high, thus posing a security risk.  

In short, if the webserver runs on the same account as the owner, the permissions shouldn't be higher than 700.  If the webserver runs in the same group as the owner then the permissions shouldn't be higher than 770... I think.  Thoughts?  Perhaps the install info should just check that there are no world permissions on that folder?

**Comment by WebShells** [comment]
Team i apologize for not being able to follow up lately... Been away for a while, will be back on track in a few... @opensourcepos/org

**Comment by objecttothis** [comment]
@WebShells No worries at all.  All of us are here in one way or another on a volunteer basis. Your help is appreciated.

**Comment by jekkos** [comment]
@WebShells Any chance you can look into this? So we can get the 3.3.2 out.

**Comment by WebShells** [comment]
![image](https://user-images.githubusercontent.com/26513147/79642290-61494480-81a5-11ea-80e5-7c55da5213d4.png)

@objecttothis @odiea @daN4cat @jekkos thoughts ? What color would best fit the warning in our case ? The setup could still be used because folders are written, but this is not secure so we should display a warning... So green should still be there since the software is usable with no issues...

**Comment by odiea** [comment]
@WebShells . For me it does not matter because I would use this in house only.

**Comment by jekkos** [comment]
You could argue and say that it"s a warning, ospos will work but it's not the ideal configuration in terms of security?

**Comment by objecttothis** [comment]
IMO Security warnings should be in red and more strongly worded. Something like "Security vulnerability warning: permissions higher than xxx leave this software vulnerable to attack." or something like that.

**Comment by objecttothis** [comment]
@jekkos anyone running this on a server that has no exposure to the WAN has little to be concerned about, however if ports 80, 443 and potentially others (sftp, ftp, ssh, etc) then this does need to be taken seriously from a tech security standpoint.

I believe we should make no assumption that people don't expose certain ports.  For our team, during this quarantine, everyone is working from home. I did server hardening some time ago, but, even with a hardened server, or shared hosting installs, creates directories and gives them 777 permissions then it's all moot.

I wouldn't go as far as not allowing the app to run, but I definitely would go as far as a strongly worded warning.

**Comment by WebShells** [comment]
![image](https://user-images.githubusercontent.com/26513147/79671452-fb73b180-81d2-11ea-84d1-3950417b5dcd.png)
Looks better ? @opensourcepos/org

**Comment by jekkos** [comment]
Ok good point @objecttothis . Maybe we should indeed rephrase the sentence to make a user aware of the potential risks involved.

**Comment by WebShells** [comment]
@jekkos lol we are commenting the exact same second ;p ! Hi man!

**Comment by jekkos** [comment]
Indeed. doing a great job there.

**Comment by WebShells** [comment]
Ok that's what i've reached... 
If all permissions were set correctly:
![image](https://user-images.githubusercontent.com/26513147/79676524-cd509a80-81ef-11ea-98b3-80e1bd310a68.png)

If permissions weren't set correctly / But no security risks
![image](https://user-images.githubusercontent.com/26513147/79676533-dd687a00-81ef-11ea-9eae-d0919790a600.png)

If permissions were set correctly but causing security issues
![image](https://user-images.githubusercontent.com/26513147/79676556-05f07400-81f0-11ea-885a-9cb87d03b59f.png)

@opensourcepos/org Let me know what you think so i can finalize this...

**Comment by objecttothis** [comment]
Looks good to me

**Comment by WebShells** [comment]
Good then, will apply few editions and submit a PR about it... I'll merge System Info tab with License Tab and do sub tabs for them to reduce the tabs from the menu...

**Comment by WebShells** [comment]
PR #2798 submitted, please let me know in case any more editions are needed.
