### ISSUE TITLE
Newly added items not displaying

### ISSUE THREAD

**Issue by bowenjnr** [opensourcepos/opensourcepos#2734]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: c786d4
- PHP version is: 7.2.24-0ubuntu0.18.04.3
- MySQL or MariaDB version is: 5.7.29-0ubuntu0.18.04.1
- OS and version is: Ubuntu 18
- WebServer is: Apache2
- Selected language is: en-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
I have added new items and they are not displaying
![items](https://user-images.githubusercontent.com/46376364/74935334-228f4c00-53f9-11ea-8a57-443129e98c38.PNG)

**Comment by daN4cat** [comment]
Have you added the item from the UI or directly in the database?

**Comment by bowenjnr** [comment]
I added from the UI

**Comment by odiea** [comment]
Can you enable error logging to see what shows?

**Comment by andriux1990** [comment]
#2452

**Comment by daN4cat** [comment]
Yep, good point. What is that you input in your item?

**Comment by izeblood** [comment]
The cause of not displaying all items right after you upload it using CSV import is the Timezone. Synchronize your OSPOS timezone and your computer timezone. that's it... I'll test it several times......

**Comment by izeblood** [comment]
there is no bug here...only the timezone must be sync between pc and ospos

**Comment by izeblood** [comment]
To whom it may concern. 
 I encourage everyone to please test it first all the possible way in order to solve problem so that we can simplify complex problem to minimize the STRESS of the developers.
:-)

**Comment by daN4cat** [comment]
Sometimes you don't really consider all the possible scenarios.
To be honest I'm not sure I understand the time implication between client and server with CSV import.
Can you please tell us how to recreate it?

**Comment by daN4cat** [comment]
CSV import is a red herring.
The problem is that the web browser time is used for the filtering where the items are indeed saved using the server time.

It's something to flag in the FAQ and installation procedure.

**Comment by daN4cat** [comment]
It will be an installation note, not a fix but we can probably highlight something in the System Info tab under Configuration.

@webshell can you please add the time sync check to that page?

**Comment by WebShells** [comment]
Sure will

**Comment by WebShells** [comment]
I missed this one :x

**Comment by WebShells** [comment]
OSPOS Installation Info: 3.3.1 - c786d4
Language Code: en-US

OSPOS Timezone is Different from your Local Timezone

Your Timezone:
Asia/Beirut

OSPOS Timezone:
Atlantic/Azores

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.23 (Win64) PHP/7.0.10
.PHP Version: 7.0.10
.DB Version: 5.7.14
.Server Port: 80
.OS: Windows NT 6.1

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable ✗
» [import_customers.csv:] - 0666 | Readable ✓ | Security Check Passed ✓

There are problems with file permissions please fix and reload this page.

Security Vulnerability Warning
Permissions higher than 750 leaves this software at risk.

» [application/logs:] is writable, but the permissions are higher than 750.
» [public/uploads:] is writable, but the permissions are higher than 750.
» [public/uploads/item_pics:] is writable, but the permissions are higher than 750.

**Comment by WebShells** [comment]
@opensourcepos/org 
Results as below, still having one issue and will submit a PR, does it look good ? Any changes ?

Timezone correctly set:

![image](https://user-images.githubusercontent.com/26513147/82595006-9504f900-9bad-11ea-80cb-f909f2508a4c.png)


Timezone not set:

![image](https://user-images.githubusercontent.com/26513147/82594877-6be46880-9bad-11ea-9727-7bd94e4be7b5.png)

**Comment by objecttothis** [comment]
@WebShells looks good to me.
