### ISSUE TITLE
Bug in Employee Update on Detailed Transaction Report

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2736]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: ca2907
- PHP version is: 7.3.36
- MySQL or MariaDB version is: 5.7.26
- OS and version is: FreeBSD 11.2-p15
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug
In Reports ->Detailed Reports ->Transactions with any date range that contains sales and any transaction type there is a problem updating the employee for any given transaction.  If I click the update icon then begin typing any characters, the search suggestions seem broken.  They only give me five employees which are a mix of employees with the delete flag set and those where the delete flag is not set.  This same functionality works properly in the Detailed Receiving report, but not in the detailed transaction report.

@daN4cat you said you recently did some rework on a few reports.  Is it possible changes didn't get made completely on this section?

**Comment by odiea** [comment]
Yes I see that detailed Receivings has a dropdown for the Employee while Detailed Transactions does not.

**Comment by odiea** [comment]
This is where it changed.
Change Employee input type in Sales edit form master
@daN4cat
daN4cat committed on Jan 19
1 parent b4eabd2 commit 5007410c1a37c14838c6e0545593eedb1b620b82

**Comment by daN4cat** [comment]
I need to test it again. The reason why I changed is because old sale where an employee was deleted showed the current employee where it should be a choice.
Also I replaced the dropdown with a suggest to hide old names and identities and avoid having big dropdown.
In the end if you want to replace an employee name you know the new name therefore should be quicker to select a new name.

**Comment by objecttothis** [comment]
It's OK with me if it's a suggest instead of a dropdown but it needs to only accept correctly spelled employee names.  Knowing some of my staff, if it doesn't, you will get all kinds of mis-spellings and employees that don't exist (deleted or otherwise).

In our use case, it's better if only non-deleted employees show up in the suggest or dropdown, but I can see a case where people might want to be able to select a deleted employee... for example if they are doing an audit of a fired employee.

Here, if the search suggestions were working correctly, it would be fine for it to include deleted employees, but no matter what gets typed, only the same five employees show up and I can't enter any other employees.

**Comment by daN4cat** [comment]
Agreed, I need to check and fix but not before the weekend. If an urgent matter please feel free to check and fix.

**Comment by daN4cat** [comment]
Fixed and in master. I close.
