### ISSUE TITLE
Question about updating attribute value logic

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2738]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.3.36
- MySQL or MariaDB version is:  5.7.26
- OS and version is: FreeBSD 11.2-R15
- WebServer is: Apache 2.4
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question

In my process of trying to add a boolean (CHECKBOX) attribute type I'm running into issues debugging.  I turned on the db logging and noticed that every time the submit button is clicked on the item manage view that ospos is deleting all the attribute links for that item and rewriting them one at a time.  This takes place even if none of the data is changed.  Can someone help me understand why that logic was taken rather than just updating the values that were changed, if any?  It seems like it could save significant numbers of queries as well as not inadvertently kick off 3rd party integrations that get triggered when an item is updated.

**Comment by jekkos** [comment]
@objecttothis Did my answer in the PR suffice on this one?

**Comment by objecttothis** [comment]
> 
> 
> @objecttothis Did my answer in the PR suffice on this one?

I'm not seeing which response was addressing the issue of attribute links being removed and then recreated each time.  Can you tell me which PR it was in?
