### ISSUE TITLE
Delete button at every page is not working

### ISSUE THREAD

**Issue by giftonian** [opensourcepos/opensourcepos#2743]
why Delete button at any page is not working? When I click, it does nothing

**Comment by odiea** [comment]
Closed until proper info is submitted. The issue form.

**Comment by giftonian** [comment]
I have installed version 3.3.2.
When I go to Customers or Items listing page, there is a Delete button at top left corner of the listing table. I select an item/customer and then press Delete button. Nothing happens, no message, no action, the selected record remains as it is.

**Comment by odiea** [comment]
IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.
