### ISSUE TITLE
Trying adding new items, form appears as blank box.

### ISSUE THREAD

**Issue by jitendrac** [opensourcepos/opensourcepos#2749]
https://github.com/opensourcepos/opensourcepos/blob/f4487947c5e5fc7c1d1ff09162bb9482459bcbee/application/views/items/manage.php#L66

I tried to find view,Debugger shows Internal Server Error at Ajax request to public/items/view
I also renamed form.php to form_view.php, Its still not working.  
/application/views/items/form.php seems to have some error.

**Comment by odiea** [comment]
IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.
