### ISSUE TITLE
Trying adding new items, form appears as blank box. 

### ISSUE THREAD

**Issue by jitendrac** [opensourcepos/opensourcepos#2750]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: Version 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL version is: 5.1.72
- OS and version is: Windows 10
- WebServer is: Apache
- Selected language is: US-en

### Issue / Bug  / Question / New Feature

at opensourcepos/application/views/items/manage.php
Line 66 in f448794
 <button class='btn btn-info btn-sm pull-right modal-dlg' data-btn-new='<?php echo $this->lang->line('common_new') ?>' data-btn-submit='<?php echo $this->lang->line('common_submit') ?>' data-href='<?php echo site_url($controller_name."/view"); ?>' 

I tried to find view,Debugger shows Internal Server Error at Ajax request to public/items/view
I also renamed form.php to form_view.php, Its still not working.
/application/views/items/form.php seems to have some error.

**Comment by odiea** [comment]
If you see the item edit dialog box empty starting with version 3.3.0, please disable only_full_group_by option from MySQL/MariaDB. See issue #2538.

**Comment by jitendrac** [comment]
Thanks, Disabling option made it works.
The default behavior of newer mysql versions will all raise same error, It should be marked as required change, and added to projects todo list.

**Comment by odiea** [comment]
It should also be read from the FAQS prior to Installing OSPOS.
