### ISSUE TITLE
Thanks Jekkos. The latest commits wiped out my Master.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2751]

**Comment by jekkos** [comment]
How do you mean?

**Comment by odiea** [comment]
After getting the commits all I see now is a small login on the upper left corner and nothing works.

**Comment by jekkos** [comment]
Ok are you on a git clone of the project?

**Comment by odiea** [comment]
Yes I am

**Comment by jekkos** [comment]
Ok I see the issue. Something wrong in the resource loading, lemme check.

**Comment by jekkos** [comment]
Ok pushed a fix for this.

**Comment by jekkos** [comment]
@odiea problem fixed or?

**Comment by odiea** [comment]
It appears to be so I will try and recover whats left after I get my grand kids

**Comment by jekkos** [comment]
It seems that docker hub images weren't build for quite some time, trying to fix that as well now.

**Comment by odiea** [comment]
Thanks. Worked as expected this morning.

**Comment by jekkos** [comment]
I've added a cronjob to the demo to refresh every hour, let's see if that helps for stability.

**Comment by jekkos** [comment]
Seems that the docker hub access token disappeared for unknown reasons. I regenerated the token now to get the autodeploy up and running again. Let's see if that works.

**Comment by odiea** [comment]
The only issue I have now is with the following screen overlay not disappearing. Any Ideas. I have tried replacing the Items Controller and Model with no luck. Not important just wondering.
![2020-03-08 08_17_15-Window](https://user-images.githubusercontent.com/10962177/76164564-9168e680-6115-11ea-8b26-054190fba49e.png)
