### ISSUE TITLE
Current bintray files displaying the following.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2756]
Cannot add an item to Receivings or Sales
ERROR - 2020-03-10 06:21:00 --> Severity: error --> Exception: Class 'Token_barcode_price' not found C:\wamp64\www\3112020\application\models\tokens\Token.php 30
ERROR - 2020-03-10 06:21:35 --> Severity: error --> Exception: Class 'Token_barcode_price' not found C:\wamp64\www\3112020\application\models\tokens\Token.php 30
ERROR - 2020-03-10 06:22:24 --> Severity: error --> Exception: Class 'Token_barcode_price' not found C:\wamp64\www\3112020\application\models\tokens\Token.php 30
ERROR - 2020-03-10 06:23:19 --> Severity: error --> Exception: Class 'Token' not found C:\wamp64\www\3112020\application\libraries\Barcode_lib.php 55
ERROR - 2020-03-10 06:23:36 --> Severity: error --> Exception: Class 'Token' not found C:\wamp64\www\3112020\application\libraries\Barcode_lib.php 55

**Comment by odiea** [comment]
I have also noticed that in Sales and Receivings there is no longer a default quantity of 1. What happened to that?

**Comment by jekkos** [comment]
Thanks for reporting this. This should be fixed. I have reverted this accidental commit until it is fully validated.
