### ISSUE TITLE
DROPDOWN values containing '&' added to existing attributes fail

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2758]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.2
- OSPOS git commit hash is: ffc50a
- PHP version is: 7.3
- MySQL or MariaDB version is: 5.7
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug
If you create a new DROPDOWN attribute and give it one or more values that contain '&' it will add the attribute.  But if you take an existing DROPDOWN attribute, then add one or more values that contain '&' upon clicking submit it will tell you that it added successfully, but reopening the attribute shows that it did not add the value.  an SQL query also shows that the attribute_value was never created.

The two bugs are that it's not creating the value if the dropdown attribute is pre-existing.  The second bug is that it's not erroring out when it fails to create the value.  This isn't a database limitation, because it creates the attribute_value containing '&' if the attribute is new.

This has been replicated on the current demo, 3.3.2 and 3.3.1

@jekkos, do you want to look into this, or do you want me to?

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by objecttothis** [comment]
In my debugging, I'm discovering that this likely has to do with the view.  It's unclear to me why, but when the attribute exists and you submit a new DROPDOWN value containing an '&' the post('definition_values') variable is null from the view.  If the definition doesn't exist or exists but the new value does not contain '&' then the variable is fine.

Here is the $_POST sent to Attributes->save_value()
`<b>array</b> <i>(size=6)</i>`
`  'definition_name' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Location'</font> <i>(length=8)</i>`
`  'definition_type' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'1'</font> <i>(length=1)</i>`
`  'definition_group' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>`
`  'definition_flags' <font color='#888a85'>=&gt;</font> `
`    <b>array</b> <i>(size=1)</i>`
`      0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'1'</font> <i>(length=1)</i>`
`  'definition_unit' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>`
`  'definition_value' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>`

Here is the $_POST of an additional DROPDOWN value in a new attribute
<b>array</b> <i>(size=7)</i>
  'definition_name' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Test Dropdown 5'</font> <i>(length=15)</i>
  'definition_type' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'1'</font> <i>(length=1)</i>
  'definition_group' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>
  'definition_flags' <font color='#888a85'>=&gt;</font> 
    <b>array</b> <i>(size=3)</i>
      0 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'1'</font> <i>(length=1)</i>
      1 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'2'</font> <i>(length=1)</i>
      2 <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'4'</font> <i>(length=1)</i>
  'definition_unit' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>
  'definition_value' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>
  'definition_values' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'[&quot;Tested Value is&quot;]'</font> <i>(length=19)</i>

**Comment by objecttothis** [comment]
The second example appears to be sending through a JSON encoded definition_value, but a pre-existing attribute doesn't send that through.

**Comment by daN4cat** [comment]
Checked with different browsers?

**Comment by objecttothis** [comment]
No, so I just checked it in IE and Edge.  Both have identical behavior to Firefox described above.

**Comment by objecttothis** [comment]
Curiously, jquery doesn't kick back an 'invalid character' error.  It just never gets JSON encoded and sent in that particular variable.

**Comment by objecttothis** [comment]
I'm getting closer

The offending code in the /views/attributes/form.php (145-162) is treating new attributes differently than existing.  When the attribute is new, it uses `values.push(value);`, but when the attribute definition is pre-existing, it sends the value, unescaped in the POST.  I'm guessing, based on the article below, that the unescaped & is breaking the POST, so nothing for that variable goes through.

`		if (is_event)
		{
			value = $('#definition_value').val();

			if (!value)
			{
				return;
			}

			if (is_new)
			{
				values.push(value);
			}
			else
			{
				$.post('<?php echo site_url("attributes/save_attribute_value/");?>' + value, {definition_id: definition_id});
			}
		}`

https://stackoverflow.com/questions/9102849/jquery-ajax-posting-data-with-symbols

**Comment by objecttothis** [comment]
OK, so by changing 
`			$.post('<?php echo site_url("attributes/save_attribute_value/");?>' + value, {definition_id: definition_id});`
to
`			$.post('<?php echo site_url("attributes/save_attribute_value/");?>' + escape(value), {definition_id: definition_id});`

The bug goes away.

**Comment by jekkos** [comment]
Thanks for solving this @objecttothis ! Indeed this sounds like a html entity escape issue.
