### ISSUE TITLE
Auto logout OSPOS

### ISSUE THREAD

**Issue by data2base** [opensourcepos/opensourcepos#2767]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Installation Info: | 3.3.0 - 0b9a76
-- | --
en-US
» GD: Enabled ✓» BC Math: Enabled ✓» INTL: Enabled ✓» OpenSSL: Enabled ✓» MBString: Enabled ✓» Curl: Enabled ✓
.Browser: Chrome.Server Software: Apache.PHP Version: 7.0.33.DB Version: 5.7.29-log.Server Port: 443.OS: Linux depro4.fcomet.com 2.6.32-954.3.5.lve1.4.71.el6.x86_64 #1 SMP Fri Sep 6 06:22:16 EDT 2019 x86_64
» [application/logs:] - 0775 \| Writable ✓» [public/uploads:] - 0775 \| Writable ✓» [public/uploads/item_pics:] - 0775 \| Writable ✓» [import_customers.csv:] - 0664 \| Writable ✓

### Issue / Bug  / Question / New Feature

Hi!

As of last month OSPOS constantly logs users out, only change was our internet connection. 
Any suggestions?

**Comment by daN4cat** [comment]
If tour internet connection change IP constantly that might cause the log out.
Check the config.php file and disable that option. But that reduces the security protection of your system.

**Comment by data2base** [comment]
Thanks, what should i remove from the config.php file?

**Comment by data2base** [comment]
An is it in applications/config/config.php?

**Comment by daN4cat** [comment]
That's the file but can't remember from the top of my head the correct line. Read the file through to find out.

**Comment by odiea** [comment]
Could it be this line?
$config['sess_match_ip'] = TRUE;

**Comment by daN4cat** [comment]
Yes

**Comment by data2base** [comment]
Thanks I've made the changes, ill advise later in the day.

**Comment by data2base** [comment]
Seems to be working! Thanks for the help. :)

**Comment by daN4cat** [comment]
Good but an ISP changing IP so often is unusual. I would check the reason for that because it might be due to some connectivity issues.
