### ISSUE TITLE
$item_id not added to $item_data on Item Update in Items->save Controller

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2770]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.3.15
- MySQL or MariaDB version is: 5.7.39
- OS and version is: FreeBSD 11.2
- WebServer is: Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question

In the save function of the Items controller, if the item is new, the item_id is being added to the $item_data array.
````
			if($item_id == -1)
			{
				$item_id = $item_data['item_id'];
				$new_item = TRUE;
			}
````

The problem I am having is that when someone updates an item (i.e., it's not new), then $item_id doesn't get added to $item_data and the event trigger for event_update (3rd party integrations) doesn't get the item_id when it gets passed $item_data.  Is there any reason why $item_id shouldn't be added to $item_data regardless of whether it's a new item or update?
````
			if($item_id == -1)
			{
				$new_item = TRUE;
			}
			$item_id = $item_data['item_id'];
````

**Comment by odiea** [comment]
The following is the error I received when I changed the way you suggested. Now the name and category has dissappeared.
success: false, message: "Error adding/updating item coke", id: null}
success: false
message: "Error adding/updating item coke"
id: null

**Comment by objecttothis** [comment]
yeah, it fails for me as well.  I need to investigate why, if the item_id is part of item data, the save function in the model fails. I can also assign the item_id to the item_data after it does the save but before the trigger call, but I want to understand the code better, so I don't just resort to a hack.

**Comment by objecttothis** [comment]
Sorry, it was failing because I was setting the item_id to null essentially.  The code should read 

````
			if($item_id == -1)
			{
				$item_id = $item_data['item_id'];
				$new_item = TRUE;
			}
			else
			{
				$item_data['item_id'] = $item_id;
			}
````
I'm testing it now, to see if it behaves.

**Comment by odiea** [comment]
Could this be part of the issue. I tried the new way and also get the null error.
PRIMARY KEY (`item_id`),
  KEY `item_number` (`item_number`),
  KEY `supplier_id` (`supplier_id`)

**Comment by odiea** [comment]
Yes that did the trick. I did not read very well on how you changed the $item_data['item_id'] = $item_id;

**Comment by objecttothis** [comment]
Yeah, it's easy to miss.  I missed it the first time too.

**Comment by objecttothis** [comment]
This issue has been resolved with the CLCdesq_API integration PR
