### ISSUE TITLE
Blank page issue  after migration from Localhost to Hosting - Point of Sale 

### ISSUE THREAD

**Issue by aliferozrupani** [opensourcepos/opensourcepos#2777]
Hello, 

Hope you all are in good health. I'm having a issue of blank page after migrating my POS from localhost to live. Script based on Laravel PHP. Would you guys have any solutions? I'm using Salepro POS script.

POS-script link:
https://codecanyon.net/item/lims-stock-manager-pro-with-pos/22256829

**Comment by odiea** [comment]
What does this have to do with OSPOS?
