### ISSUE TITLE
Item Module is very very slow

### ISSUE THREAD

**Issue by akhilnasi** [opensourcepos/opensourcepos#2781]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 
- OS and version is: win 10
- WebServer is: xamp
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

i have many items more than  9000. now item module is very slow .. it is not responding also 
and when i click the item module it stucks the entire program.
![image](https://user-images.githubusercontent.com/55619235/78544389-b7f86b00-7802-11ea-9913-2ec3091deb79.png)

**Comment by andriux1990** [comment]
I don't know exactly what it could be ... the same thing happened to me with windows, I switched to Linux and I don't have this problem.

I don't have that many products, I barely have 7000 because I never repeat the products ... but ospos is super super fast.

check that the rows are 25 lines and see if xss is not affecting you

**Comment by jekkos** [comment]
@akhilnasi were you able to solve this issue?

**Comment by akhilnasi** [comment]
no

**Comment by mckaygerhard** [comment]
@akhilnasi  you use windo shit in both sides.. it's a well know problems if you search at the issues code base here and check same behaviour with more than 5000 products codebase and 2G ram on stanar low end machines! .. use a real OS like linux
