### ISSUE TITLE
Receiving detailed report not showing all items

### ISSUE THREAD

**Issue by saydfuad** [opensourcepos/opensourcepos#2782]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.0
- MySQL or MariaDB version is:  5.6
- OS and version is: Linux
- WebServer is: Apache2
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

When Viewing receiving report there is + sign to view list of item received during that particular operation, but unfortunately it is showing only one item even if I did receive deference items in a cart. I have tried to simulate the issue on live demo here too: https://demo.opensourcepos.org/ 
see attached screenshot
![ospos_get](https://user-images.githubusercontent.com/8853402/78591857-c53a4780-784c-11ea-8673-3500c03b2a98.JPG)

3 item showed in red circle are of difference items not just WHEAT.

**Comment by odiea** [comment]
I am not able to replicate this issue.
![2020-04-06 13_29_53-Window](https://user-images.githubusercontent.com/10962177/78597512-e67a4400-780a-11ea-908f-b2ce7f7ba626.png)

**Comment by saydfuad** [comment]
@odiea  can you please try to replicate here : https://demo.opensourcepos.org/

**Comment by saydfuad** [comment]
@odiea  any idea how you make your version work? I need to implement this ASAP

**Comment by odiea** [comment]
Lucky I guess. Where did you download this version from? Stable or unstable?

**Comment by odiea** [comment]
Does the Detailed Transaction  Report show a similar result with a multiple Item Sale?

**Comment by saydfuad** [comment]
I downloaded from Stable and yes it shows a similar result with a multiple sales

**Comment by saydfuad** [comment]
After multiple checking and trying, I found out I was running unstable release, stable release working fine.
Please fix this in the master branch

**Comment by jekkos** [comment]
Thanks @odie and @saydfuad for reporting this bug. I'll have a look this weekend.

**Comment by WebShells** [comment]
@saydfuad was this resolved in the stable version ? can we close ?

**Comment by saydfuad** [comment]
@WebShells Yes, it was resolved in the stable version
