### ISSUE TITLE
Secondary barcodes

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2784]
Hello ... I hope all is well in these difficult times.

this is not a mistake, I just have a problem with a few products.
I keep the products with the code that the box brings, it turns out that sometimes these same products come in smaller boxes. (Obiameten with less quantity but it is the same product). and it is very annoying to me not to be able to use the bar code with this, because if I change it later I will have problems with the bigger boxes.

since the attributes have a great utility. I want to use these myself to create an attribute and put secondary barcodes. but I have not been able to add them for sale on register.

if anyone has any ideas i would really appreciate it

**Comment by odiea** [comment]
Have you tried using the allow duplicate barcodes under barcode in configs?

**Comment by andriux1990** [comment]
> Have you tried using the allow duplicate barcodes under barcode in configs?

Not because if I do it this way I would have to create more products of a single type.
I sell in units and these do not have barcodes, use the code to speed up the sale. (For example, if you sold pills, by units, they do not have barcodes)

**Comment by gaaytrimaa** [comment]
> Have you tried using the allow duplicate barcodes under barcode in configs?

After acitvating duplicate barcodes, the first item is selected by default when I use a barcode scanner in the sales window. 
Rather the desired output should be that a choice must be given for duplicate barcode items as to which one to select.
Another important thing to mention is that if I type the barcode manually then two options are shown for the same barcode products but this is not the case when I use a barcode scanner.
![Screenshot (2)](https://user-images.githubusercontent.com/38756022/79692510-23225280-8283-11ea-9df7-77fc11de70af.png)

**Comment by jekkos** [comment]
You can do a simple workaround here by configuring your scanner to stop sending a return after the number sequence.
