### ISSUE TITLE
Unable to send mail

### ISSUE THREAD

**Issue by tkintenn** [opensourcepos/opensourcepos#2790]
#2054 # Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: c786d4
- PHP version is: 7.2.29
- MySQL or MariaDB version is: 5.7
- OS and version is: Centos 7
- WebServer is: apache 2.4.6
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
3.3.1, centos 8, apache 2.4, mysql

No matter what option is chosen under Office > Configuration > Email, It won't send. 

Currently I have it set to Sendmail with a path of /usr/bin/msmtp 

The error logs indicate it is trying to use PHP mail regardless of what is chosen. 

Similar to #2704 and kind of similar to #2682 However #2704 has no resolution and is marked stale. This issue has followed me from 3.2.3 to 3.3.1. #2682 I had that exact problem, so I switched from smtp to sendmail, using msmtp, because i don't have time to troubleshoot the code myself. I also didn't quite understand what he adjusted.

**Comment by tkintenn** [comment]
@daN4cat  I see you labeled this as a bug. Is there a work around I can put in place until it's fixed in 3.4.0? Trying to be paperless if possible, so it would be awesome if we could email receipts. can the string values in Email_lib.php be manually filled in?

**Comment by jekkos** [comment]
I think you should be able to configure the email sending from the CI settings directly. Not sure how the email config works exactly (I haven't used it) but maybe on some systems it just can't be configured? (shared hosting eg)

**Comment by jekkos** [comment]
@tkintenn did you find a solution here?

**Comment by tkintenn** [comment]
Yes. I fixed the code issue myself. It essentially wasn't pulling what was saved in the DB for email or wasn't passing it, can't remember. Once I figured out CI structure it wasn't hard. We also implemented twilio and PayPal api's, so I don't remember exactly where we changed it.

**Comment by darkjedeye** [comment]
Hi There.. having tha sam issue here

**Comment by daN4cat** [comment]
@tkintenn would be nice to share the twilio and paypal integration code.
