### ISSUE TITLE
Kit Name not showing on Receipt if Items not shown

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2793]
OSPOS Installation Info: 3.3.2 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
» Browser: Chrome
» Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
» PHP Version: 7.3.2
» DB Version: 5.7.21
» Server Port: 80
» OS: Windows NT PAVILION23 10.0 build 18363 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓ 

@SteveIreland  I know you have done a lot of work for OSPOS. Is there a way to do this so that it shows the Kit name? Any help would be appreciated.
![2020-04-14 13_06_56-Window](https://user-images.githubusercontent.com/10962177/79265987-24ebb080-7e54-11ea-887c-f04c50623ade.png)

**Comment by SteveIreland** [comment]
@odiea I just saw this.  Did you figure it out or was there an oversight on my part?   Hopefully it was just a matter of nailing the configuration.

**Comment by odiea** [comment]
Yes I did. I had to add a no stock kit Item to the To the Item Name under the kit name. Never really thought about it until I starting experimenting with it. Thanks for your response.
