### ISSUE TITLE
Multiple Tax for each item  

### ISSUE THREAD

**Issue by abhiabhiab** [opensourcepos/opensourcepos#2794]
How to add multiple taxes and tax rate for each item? (by following GST-India)

**Comment by SteveIreland** [comment]
There is a section for Taxes in the Wiki that is a good starting point (if you start with Rules of Operation).

https://github.com/opensourcepos/opensourcepos/wiki/Taxes#rules-of-operation

I don't believe that it's so far out of date that it's useless.

But I definitely need to update the page.

**Comment by abhiabhiab** [comment]
Actually, I followed the steps mentioned in this doc.
https://github.com/opensourcepos/opensourcepos/wiki/India-GST

Added the various taxes and tax rates but i can assign only one tax for one item.

**Comment by SteveIreland** [comment]
Okay, that's odd.  I have a few questions.

Are you migrating an existing database from an earlier version?

What version are you trying to set up?  I need to know that before trying to replicate the issue.

How many tax jurisdictions have you added?  The tax rate maintenance program should allow you to add a separate tax rate for each tax jurisdiction for the same tax category.  If not then that would be a bug.

**Comment by abhiabhiab** [comment]
No. 
We started with version 3.3.0
Added 3 Tax Jurisdictions.

**Comment by SteveIreland** [comment]
Okay, I'll download and test the published  3.3.0 release tonight.

**Comment by SteveIreland** [comment]
I downloaded and tested 3.3.0 and didn't have a problem.  However, during the process I remembered an issue that has been fixed since 3.3.0 that might have something to do with this.

The tax jurisdiction group code needs to be unique as shown in the example below.  If you are using the same code for both tax jurisdictions then that could be a problem. 

![image](https://user-images.githubusercontent.com/23066623/79623649-88434000-80eb-11ea-9b24-83d9ed6ddc18.png)

**Comment by abhiabhiab** [comment]
Can you please share the tax rates screenshot ? 
How to assign this 2 tax for item ?

**Comment by SteveIreland** [comment]
Sure, the list is ...
![image](https://user-images.githubusercontent.com/23066623/79640832-ced38180-8161-11ea-8e0e-d26a5bd8a9de.png)

And the entry follows.  All that is necessary is to make sure that the drop downs reflect how the tax should should be configured.  In the example I'm adding a new state sales tax for items that are categorized as Alcohol products ...
![image](https://user-images.githubusercontent.com/23066623/79640863-10642c80-8162-11ea-81d2-266d5c372ad2.png)

**Comment by abhiabhiab** [comment]
Ok , then How to connect this with Items ?
