### ISSUE TITLE
allow option to use self signed certs for email

### ISSUE THREAD

**Issue by tkintenn** [opensourcepos/opensourcepos#2796]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

New Feature

Allow us the choice to allow self-signed certs for email, so an option we can change. By default PHP verify_peer is true for ssl/tls. I had to google like crazy to implement verify_peer = false for code igniter because I've never used the framework and host my own mail server.

**Comment by jekkos** [comment]
So that means you have a certificate installed that does not match the hostname of your mailserver? I wouldn't recommend such a setup and don't want to support disabling this verification as it's crucial in identifying that you are actually talking to the host you expect to talk to.

**Comment by jekkos** [comment]
So it feels like something you should fix on the mailserver side.

**Comment by tkintenn** [comment]
@jekkos you realize many smaller hosting companies use self-signed certs for postfix and there's a good chance that someone is hosting their POS software, they're probably using their own mail server. We use office365 and i'm not going to pay for each service account i need, so we use our own hosting server and a secondary domain for things like printers, apps, pos, etc. 

It wouldn't really be an issue if the mail features in ospos were fixed and we could use the sendmail option properly.

**Comment by jekkos** [comment]
The verify peer should not be an issue even if you are using a selfsigned cert on your mailserver.

If you choose to trust this provider's CA then at least they should install a certificate on the mailserver with a correct common name (CN). It's just a plain misconfiguration and using it this way  defeats the purpose of using SSL.
