### ISSUE TITLE
BUG: revert of barcode rework not complety done?

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2799]
Lasted commit over Sales controller has some errors:

@jekkos  in commit 4300f0a3c6968ae57136d9af58ad00af6094add9#diff-0e317d549720855158cc3e1741af5fbe erase the ´$price´ variable.. 

**but in revert of commit 4f60465fa02367748674f737d04cda9ff1843b6e#diff-0e317d549720855158cc3e1741af5fbe this variable does not return..**

i revised some problems in reports about filtering and noted that! i dont know if that affects my bug.. but reported as well

**Comment by andriux1990** [comment]
Hmm ... I'm going to try
