### ISSUE TITLE
Avoid double Submit

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2803]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

_____________________________________________________________

Sometimes when sending data, for example when I add quantities to the item, the server takes time to respond and the user presses the Submit button again, or the mouse occasionally double-clicks by mistake. This can generate duplicate records.

**Comment by mckaygerhard** [comment]
this are due you use huge databases! it takes a time to process .. so **the solution are that in each buton when are cllicked.. toggle blocked ui of the button .. in the ajax king we must made a extra script to detect the end of the process and re-enable the button!** thsi are not so easy to made!

**Comment by odiea** [comment]
The one thing I have done is to put the db on a separate server then use the local Terminal to access the db. Yes I have used a vm with a Ubuntu server as just a db server. This may or may not be the answer to your dilemma but it sure seemed to speed things up.

**Comment by WebShells** [comment]
The best thing in this case is to disable/block the submit button for 3 seconds after clicked... This will not cause any data duplicate or double entering stock locations, etc...

**Comment by mckaygerhard** [comment]
????  windosers users lost in the spaces? @odiea  **What do those have to do with a double submission of data? He's talking about resquest and response!**

and @WebShells  i just said that!

**Comment by odiea** [comment]
the server takes time to respond you dumb ass

**Comment by WebShells** [comment]
I wonder if he considered that harsh @odiea ;p lol

**Comment by odiea** [comment]
Mr Know it all is back here and I am already tired of his garbage. Thanks

**Comment by andriux1990** [comment]
> The best thing in this case is to disable/block the submit button for 3 seconds after clicked... This will not cause any data duplicate or double entering stock locations, etc...

This is reasonable. because anyone can do tests with two clicks and they will see that the products are duplicated

**Comment by andriux1990** [comment]
> the server takes time to respond you dumb ass

If it is true .. @odiea  .. mention the server to give an example .. but this always happens, that the mouse is somewhat defective .. or by accident two clicks are made

**Comment by ekardian** [comment]
JAJAJAJAJAJ change to this.. more practic xDDDDDDD
![imagen](https://user-images.githubusercontent.com/6296036/79935431-ebeaa780-8422-11ea-89e5-0b59bed1d0fe.png)

**Comment by andriux1990** [comment]
thanks for the suggestion. but this would be only for a computer team. I am rather seeing how to do it with javascript. if anyone has an idea?
thanks

**Comment by WebShells** [comment]
@andriux1990 try something like the below:

function submitPoll(){
	document.getElementById("idhere").disabled = true;
	setTimeout(function() {
		document.getElementById("idhere").disabled = false;
	}, 5000);
	
}
document.getElementById("idhere").addEventListener("click", submitPoll);

Let me know if that helped you...

**Comment by andriux1990** [comment]
> @andriux1990 try something like the below:
> 
> function submitPoll(){
> document.getElementById("idhere").disabled = true;
> setTimeout(function() {
> document.getElementById("idhere").disabled = false;
> }, 5000);
> 
> }
> document.getElementById("idhere").addEventListener("click", submitPoll);
> 
> Let me know if that helped you...

I did it ... I'm not sure if I did it right.
add the script in form_inventory.php.
then add an amount and quickly double-click the left mouse button and double the amount entered

**Comment by WebShells** [comment]
@andriux1990  did u set an id for the submit button ? and replaced "idhere" by the real id of the button ? 
I tried it on the copy info section, it worked without any issues and blocked the button for 5 seconds. 
Would you like me to add it to the PR to test it live ? 
Maybe you are assigning it incorrectly.

**Comment by andriux1990** [comment]
Really .. please and thank you.
a PR would be super

**Comment by jekkos** [comment]
It might be good to just disable the submit button after a submit until a change is done, so in this case until a user focuses on a new element. It makes sense to do it that way, as you probably never want to submit the same thing twice (so this is only done accidentally).

**Comment by daN4cat** [comment]
Agreed

**Comment by andriux1990** [comment]
> @andriux1990 try something like the below:
> 
> function submitPoll(){
> document.getElementById("idhere").disabled = true;
> setTimeout(function() {
> document.getElementById("idhere").disabled = false;
> }, 5000);
> 
> }
> document.getElementById("idhere").addEventListener("click", submitPoll);
> 
> Let me know if that helped you...

It works thanks a lot @WebShells
