### ISSUE TITLE
I erased an inventory but it's still in the reports (low report)

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#2807]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1 - c786d4
- OSPOS git commit hash is: 
- PHP version is: 7.2.29
- MySQL or MariaDB version is: 10.0.38-MariaDB-cll-lve
- OS and version is: Windows 10 1809
- WebServer is: Linux Apache
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

i create one more inventory named BIOS thinking i'd need one, note: i never modified the default inventory "Stock", so i erased the new inventory the next day, no problem all working good, but when i was creating an low report reappears the old inventory.

In Inventory summary do not appear the erased inventory.

i am missing something?
Thanks for the answers.

Report in low inventory
![imagen](https://user-images.githubusercontent.com/6296036/80042589-74258700-84cd-11ea-951f-02fe95d8c7ae.png)

Inventory summary that's ok

![imagen](https://user-images.githubusercontent.com/6296036/80043062-a08dd300-84ce-11ea-9ce1-63b9a3b3275c.png)

My inventory config

![imagen](https://user-images.githubusercontent.com/6296036/80042755-c797d500-84cd-11ea-8153-ca8f80ead033.png)

**Comment by odiea** [comment]
I believe the deleted filter was left out on that reports but has been repaired in the unstable branch
