### ISSUE TITLE
Kit Only Kit Only

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2808]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
____________________________________________________________
![Screenshot_2020-04-23 Teszt Powered by OSPOS 3 3 2(1)](https://user-images.githubusercontent.com/29256343/80110292-c0a7ab80-853b-11ea-8a68-585e32ee4d18.png)
Printing option: shows on the sales receipt only the kit-type product that has been added to the kit. (This is fine because it does what it says).

Price option: shows in the registry only the price of the product type kit and the other components without price. (This is fine because it does what it says).

We could change the latter, so that it is as it is now but with the difference that products without price do not appear.

**Comment by WebShells** [comment]
@andriux1990 @SteveIreland did a great job here, it was very basic until he added his touches to it... Maybe we should find a specific scenario for the printing and pricing option since it should also be reflected to the reports section "as selected"... Also currently there are no reports supporting kits also... Should be taken into consideration to covery basic kits reporting.
to what i believe Kit only must display the package name on the receipt and in the reporting without listing any other items under it, this can be helpful in menu items for restaurants also. 
Suggestions what best fits us here...

**Comment by andriux1990** [comment]
I think it would be good if we work on this characteristic

**Comment by andriux1990** [comment]
in reports we cannot see how many kits have been sold

**Comment by andriux1990** [comment]
@WebShells You are interested in the kit .. I have one. but it has only 2 errors.

**Comment by andriux1990** [comment]
Kit is complete now
