### ISSUE TITLE
Register no longer auto fills quantity to 1.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2809]
OSPOS Installation Info: 3.3.2 - dev

Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
.PHP Version: 7.3.2
.DB Version: 5.7.21
.Server Port: 80
.OS: Windows NT PAVILION23 10.0 build 18363 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓
» [public/uploads:] - 0777 | Writable ✓
» [public/uploads/item_pics:] - 0777 | Writable ✓
» [import_customers.csv:] - 0666 | Writable ✓

I just downloaded the current master from github. Used the proper way to do it. Initially I thought it was a problem I created but no. Please check this out and fix it.
![2020-04-25 05_50_09-Window](https://user-images.githubusercontent.com/10962177/80279221-469d3100-86b9-11ea-9598-c431b0e09478.png)

**Comment by WebShells** [comment]
@odiea have you checked if there is any barcode formats input in the configuration section ? 
I think this happened after the rework of Price embedded Barcode formatting...

**Comment by odiea** [comment]
No I sure don't have anything there

**Comment by odiea** [comment]
I looked in the db and it shows null.

**Comment by WebShells** [comment]
Maybe there is a specific string to be set in for the default EAN barcodes to be decoded... @jekkos @SteveIreland can you confirm that please ? Is there any format to be added to the configuration section in order for the barcode input to be considered as normal barcode without assigning it as price based or weight based ?
Thanks

**Comment by odiea** [comment]
@WebShells . Can you show me a valid string that I can place there and see if that string is needed?

**Comment by odiea** [comment]
I entered your format 02(\d{5})(\w{6}) into input format now the auto fill in Register is giving me 1 again.

**Comment by odiea** [comment]
Maybe we should add some kind of a default format so The rest of the system works.:)

**Comment by WebShells** [comment]
Yes, that's what i meant when i said default EAN decoding, without considering it a weight or price based barcode... 
Good to hear @odiea although we still need @jekkos and @SteveIreland to confirm if their functionality will work as expected and what should the user input be in that case.

**Comment by jekkos** [comment]
I think I fixed this one, so i'll close.
