### ISSUE TITLE
Unable to remove an avatar from the Items table. URI issue.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2810]
Current Demo.
Please try to remove an avatar from the Items Table. Somehting about uri issues
OSPOS Installation Info: 3.3.2 - 494b11

Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.38 (Debian)
.PHP Version: 7.3.17
.DB Version: 5.5.5-10.1.21-MariaDB-1~jessie
.Server Port: 80
.OS: Linux 768adacedfba 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64

File Permissions:
» [application/logs:] - 0775 | Writable ✓
» [public/uploads:] - 0755 | Writable ✓
» [public/uploads/item_pics:] - 0775 | Writable ✓
» [import_customers.csv:] - 0664 | Not Writable ✗

**Comment by odiea** [comment]
An Error Was Encountered
The URI you submitted has disallowed characters.

**Comment by objecttothis** [comment]
This is resolved with #2824 which will be included with 3.3.2
