### ISSUE TITLE
Tax included and Tax excluded For products.

### ISSUE THREAD

**Issue by abhiabhiab** [opensourcepos/opensourcepos#2811]
How to add tax included or tax excluded option for each items ?

**Comment by SteveIreland** [comment]
Is there still a need to answer this question?

For the basic tax system it is either all items are tax included or all items are tax excluded and is established in configuration.   For destination based taxes there is the capability for a single item to have some taxes as tax included and some items as tax excluded, but I can't say whether that makes sense in your tax scenario.  I'd be interested to hear if there is actually a practical application for it somewhere.

**Comment by SteveIreland** [comment]
Guess not.
