### ISSUE TITLE
Items Import template

### ISSUE THREAD

**Issue by danielcr100** [opensourcepos/opensourcepos#2812]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hi, i was triying to import a bunch of quantity of items, but the template.csv doesn't work, also I saw a lot of information and I tried as the information that you put in all forums and web pages and it still not working, I just wonder to know if you can have the same error and also if you have an example template as customers template. 
find attached an example template and It doens't work
regards 
![Captura de Pantalla 2020-04-28 a la(s) 09 53 07](https://user-images.githubusercontent.com/25063444/80509054-17472800-8936-11ea-876d-251569c550ff.png)

**Comment by odiea** [comment]
Have you tried using Open or Libre office?

**Comment by danielcr100** [comment]
> Have you tried using Open or Libre office?

yes, I tried whit both and neither work, do you have any solution or a template, maybe its my mistake

**Comment by danielcr100** [comment]
![Captura de Pantalla 2020-04-28 a la(s) 15 13 31](https://user-images.githubusercontent.com/25063444/80538372-e0d3d200-8962-11ea-8a56-55806c0256aa.png)

**Comment by odiea** [comment]
Did you use the Items Template?

**Comment by danielcr100** [comment]
> Did you use the Items Template?

Yes, I did use the template but It doesn't  work, I don't know if Im typing bad, but when I download and then I upload the template in blank it works, but when I type something dont work

**Comment by andriux1990** [comment]
I use libreoffice. and what you have in openoffice in the image above is wrong.

**Comment by danielcr100** [comment]
> I use libreoffice. and what you have in openoffice in the image above is wrong.

Do you have a template ??? It could help me tks

**Comment by danielcr100** [comment]
> a few days ago I was doing some imports and I was like an hour trying and always error. I did it with an older version and if it worked.
> 
> so possibly it's not your mistake

I was trying a lot of time and still not working

**Comment by andriux1990** [comment]
> > I use libreoffice. and what you have in openoffice in the image above is wrong.
> 
> Do you have a template ??? It could help me tks

https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20200307142254.master.7c3315.zip

try this version. this works for me. to import csv files
