### ISSUE TITLE
unknown error importing csv items

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2813]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
_____________________________________________________________________

unknown error importing csv items

**Comment by andriux1990** [comment]
[import_items(1).zip](https://github.com/opensourcepos/opensourcepos/files/4551935/import_items.1.zip)

**Comment by objecttothis** [comment]
@andriux1990 I need more context about the problem.  Did you make any modifications to the headers?  What program did you use to populate the CSV file?  What operating system were you using to do this?  I noticed all of your unit prices and cost prices are zero and your quantities are all zero.  It may be complaining about one of those.  Did you generate your csv template awhile ago, or use the one that it generates right there?  I ask because if you changed stock location names or attributes since then, this may cause problems.

**Comment by andriux1990** [comment]
@objecttothis I use libreoffice and I've done a lot of imports before .. so I know how to do it.

attach a file. You can do the tests by yourself and you will see that it will say an error

**Comment by objecttothis** [comment]
The demo and my setup do not have the same stock locations and attributes that yours does.  Please include a screenshot of the errors.  Please also answer the rest of my questions in my previous post.  I can't help you without more information.

**Comment by andriux1990** [comment]
> The demo and my setup do not have the same stock locations and attributes that yours does. Please include a screenshot of the errors. Please also answer the rest of my questions in my previous post. I can't help you without more information.

Good. I will test with the demo.
I have already done them before and it works but when you put more than one product it gives an error.

Later that I have the time I will send all this information.

Thanks a lot

**Comment by ekardian** [comment]
i dont know if was 2 year ago or the last year, i had a similar problem, and in one moment i changed, i dont know how, the codification to other unkown, i just opnened my csv with notepad and saved with UTF-8, worked for me, gg
