### ISSUE TITLE
Invoice number is not visible in sales register

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2820]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

test on latest master

### Issue / Bug  / Question / New Feature

When creating invoices, we used to have the invoice_number field in the view. For some reason it has disappeared and if a generated sequence clashes with one already in the db, then there is no way to correct it and complete the sale

**Comment by andriux1990** [comment]
@jekkos Also the latest versions of bintray, when you add products to the shopping cart .. it adds 0. no matter how much you add since registering, the quantity always remains at 0

**Comment by objecttothis** [comment]
> 
> 
> @jekkos Also the latest versions of bintray, when you add products to the shopping cart .. it adds 0. no matter how much you add since registering, the quantity always remains at 0

I'm using 3.3.2 - 9d2fd1 and not experiencing this behavior.  What steps are you taking to reproduce the problem?

I'm seeing
![quantity](https://user-images.githubusercontent.com/17935339/85521724-baa27980-b615-11ea-9d15-53c96f1302a6.jpg)

**Comment by objecttothis** [comment]
Regarding the invoice number not appearing in the sales register, is that because the invoice number is not generated until after the "invoice" button is pressed?  I see that the invoice number is appearing on the invoice generated after "invoice" is pressed in the sales register.  Perhaps this should be marked as an enhancement and get punted to 3.4.0 so that we can release 3.3.2?... unless I'm not understand the issue properly.

**Comment by jekkos** [comment]
I think there used to be a field that allowed you to edit the invoice number before completing the sale. And in some cases the autogeneration is off by one which then blocks sale completion, as you can't manually override the number anymore.

So not sure I need to check if the field is still in the view and why it's not shown in this case.

**Comment by objecttothis** [comment]
> 
> 
> I think there used to be a field that allowed you to edit the invoice number before completing the sale. And in some cases the autogeneration is off by one which then blocks sale completion, as you can't manually override the number anymore.
> 
> So not sure I need to check if the field is still in the view and why it's not shown in this case.

Understood.  Do we need to keep it as a 3.3.2 release or should it be punted to 3.4.0?  If we keep it in 3.3.2, when do you think you'll be able to get to it?  Sorry for any pressure.  I only ask because 3.3.2 is 5 months overdue and we are waiting to merge other PR's until after 3.3.2 gets released.

**Comment by jekkos** [comment]
Fixed and in master

**Comment by odiea** [comment]
@jekkos . Did this just change the Custom Invoice to show? Currently the standard Invoice Number just shows as the Invoice format.
