### ISSUE TITLE
Error when adding products and attributes in Turkish language

### ISSUE THREAD

**Issue by alieroglu06** [opensourcepos/opensourcepos#2822]
Hi,

It gives errors when adding products and attributes in Turkish language.

I couldn't find out why the problem was caused. Can you help me?

https://prnt.sc/sc5qqv
https://prnt.sc/sc5qu5

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by jekkos** [comment]
It might be due to special characters or a wrong escape sequence in the turkish translations. Can you check the application error log to see if there is something in there?
If not then check your javascript console and if any error messages post them here.

**Comment by alieroglu06** [comment]
Hello there,

I opened the application error log and did not receive any errors.
I saw an error in the javascript console.

https://prnt.sc/sce85t

**Comment by objecttothis** [comment]
@alieroglu06 please use the template and fill in the information about your build.  It's difficult to know what is causing the problem with the information you have provided. Also, go to Office->Settings->System Info and make sure that your permissions are set correctly.  You won't get any error logs unless your logs file has the correct permissions and log_level is set above 0 in config/config.php

**Comment by alieroglu06** [comment]
Sorry, I forgot to enter the information

OSPOS version is: 3.3.1 - c786d4

» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

Browser: Chrome
Server Software: Apache
PHP Version: 7.3.17
DB Version: 5.5.5-10.3.22-MariaDB
Server Port: 443
OS: Linux
Selected language is: Turkish

» [application/logs:] - 0775 | Writable ✓
» [public/uploads:] - 0775 | Writable ✓
» [public/uploads/item_pics:] - 0775 | Writable ✓
» [import_customers.csv:] - 0664 | Writable ✓

Error log is active. ($config['log_threshold'] = 1;)

**Comment by WebShells** [comment]
@opensourcepos/org i think we should add error log check and environment check to the system info ?

**Comment by alieroglu06** [comment]
application/logs folder is empty

Is the error log file written elsewhere?

**Comment by objecttothis** [comment]
> 
> 
> @opensourcepos/org i think we should add error log check and environment check to the system info ?

@WebShells this is a really good idea.  You could make it a scrolling textarea (similar to Settings->licenses but 100% width) and that way it wouldn't take up a lot of vertical space.

**Comment by objecttothis** [comment]
@jekkos we may want to add JSON_UNESCAPED_UNICODE mode to the json_encode() functions

`json_encode($message, JSON_UNESCAPED_UNICODE);`

That may resolve the problem that you see in the second screenshot.  It may still be an escaping issue, but I had to use the JSON_UNESCAPED_UNICODE mode with my CLCdesq integration so that json_encode wouldn't escape UTF-8 characters.

@alieroglu06 can you confirm that if you change the language to English or Azerbaijani (which you will likely still be able to read) that this issue doesn't happen.  I'll see if I can recreate it on my end.

**Comment by alieroglu06** [comment]
I changed the language to English and Azerbaijani and it didn't make any mistakes.

**Comment by objecttothis** [comment]
Yeah, there is definitely something about the way the Turkish translation is interacting with the app that is causing a problem.  I'm running a dev build of 3.3.2 and it won't even open the item/form.php view with Turkish turned on.  Azerbaijani and English are fine.  

@alieroglu06 I don't have time to look at this now.  Perhaps @jekkos can.  @alieroglu06 one way that you can help fix this problem without needing any programming skills is to create an account on translate.opensourcepos.org and check the Turkish translation for accuracy and incorrect characters.  I looked at Items and Common, but didn't see anything that was a clear winner.

**Comment by objecttothis** [comment]
@alieroglu06 maybe even easier, you could open up the different php files in /application/language/tr and look in the strings to see if there are characters that should not be in the translation.  Paste those strings here.

**Comment by alieroglu06** [comment]
Hi,
Thank you for your help.

I found the error in the file path below.
/application/language/tr/attributes_lang.php

wrong translate: 
$lang["attributes_attribute_value_invalid_chars"] = "Nitelik değeri \":\" ve ya \"|\" karakterlerini bulunduramaz";

correct translation:
$lang["attributes_attribute_value_invalid_chars"] = "Nitelik değeri ':' ve ya '|' karakterlerini bulunduramaz";

**Comment by WebShells** [comment]
I fixed it to master directly, will close this now...

**Comment by WebShells** [comment]
Thanks for this catch @alieroglu06

**Comment by objecttothis** [comment]
@WebShells I think it also needs to get fixed on weblate or it will get overwritten... Can you do that?

**Comment by jekkos** [comment]
> @opensourcepos/org i think we should add error log check and environment check to the system info ?

+1, this would be very useful. I think having it in dev mode deserves a warning on it's own.
