### ISSUE TITLE
Feature: Make Image upload restrictions customizable instead of hard-coded

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2823]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Installation Info: 3.3.2 - 9d2fd1

Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Firefox
.Server Software: Server
.PHP Version: 7.4.4
.DB Version: 5.7.29-log
.Server Port: 80
.OS: FreeBSD 11.3-RELEASE-p7

File Permissions:
» [application/logs:] - 0770 | Writable ✓
» [public/uploads:] - 0770 | Writable ✓
» [public/uploads/item_pics:] - 0774 | Writable ✓
» [import_customers.csv:] - 0640 | Not Writable ✗

### New Feature

This is related to #643. Currently our image upload restrictions are hardcoded.  I think that the original intent was because the image would be used as an avatar icon, but in no other place.  Now that I have 3rd-party integrations and an API connector almost out the door, we are needing to use these images in the API to populate product images and not just small avatars.

The dimensions are hardcoded in the Items controller

````
	private function _handle_image_upload()
	{
		/* Let files be uploaded with their original name */

		// load upload library
		$config = array('upload_path' => './uploads/item_pics/',
			'allowed_types' => 'gif|jpg|png',
			'max_size' => '100',
			'max_width' => '640',
			'max_height' => '480'
		);
		$this->load->library('upload', $config);
		$this->upload->do_upload('item_image');

		return strlen($this->upload->display_errors()) == 0 || !strcmp($this->upload->display_errors(), '<p>'.$this->lang->line('upload_no_file_selected').'</p>');
	}
````
I would like to add rows for each of these four variables into the config table and create dropdown options in Settings -> General for each of them with the allowed_types being a multiselect.  This would keep the same defaults as current, but then allow users who need to use images for more than just avatars to select higher values without having to modify the code.

@opensourcepos/org thoughts?

**Comment by odiea** [comment]
Sounds good. When you look into this can you find out why images in Items cannot be removed.

**Comment by objecttothis** [comment]
> 
> 
> Sounds good. When you look into this can you find out why images in Items cannot be removed.

I didn't know that was a thing.  I just tried to remove an image and it said that it was removed but then the image stayed.  I'll look into it.

**Comment by odiea** [comment]
I do not show anything in the error log but the browser inspector displays the following error.
An Error Was Encountered
The URI you submitted has disallowed characters.

**Comment by objecttothis** [comment]
@odiea have you tried it in multiple browsers?  I haven't had a chance to start troubleshooting it yet, but I thought I would ask if the behavior is limited to one browser or multiple.  I am using Firefox Developer Edition.

**Comment by andriux1990** [comment]
> ```
> 
> ```
> 
> 
> I would like to add rows for each of these four variables into the config table and create dropdown options in Settings -> General for each of them with the allowed_types being a multiselect.  This would keep the same defaults as current, but then allow users who need to use images for more than just avatars to select higher values without having to modify the code.
> 
> 
> @opensourcepos/org thoughts?

Mmmm

**Comment by andriux1990** [comment]
> Sounds good. When you look into this can you find out why images in Items cannot be removed.

This is true .. this happens with the images

**Comment by odiea** [comment]
Yes. Chrome,IE Edge Firefox and Opera.

**Comment by objecttothis** [comment]
OK, the demo is live with the changes until someone else makes a PR that overwrites the changes.  I'm going to start working on figuring out why images can't be removed and fix that.

**Comment by objecttothis** [comment]
Turned out to be easy to fix the bug with images on items not deleting.
The original code had " with ' inside:
url: "<?php echo site_url('$controller_name/remove_logo/$item_info->item_id'); ?>",
but needed to be reversed because PHP doesn't parse variable names inside of ' but will inside of "
url: '<?php echo site_url("$controller_name/remove_logo/$item_info->item_id"); ?>',

![a70485ef4384e77997b2fd9379544d77](https://user-images.githubusercontent.com/17935339/81407771-058f2d00-914d-11ea-8def-c91506693d82.gif)
