### ISSUE TITLE
Receiving Report did not show

### ISSUE THREAD

**Issue by dgddy** [opensourcepos/opensourcepos#2827]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7.0
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question 

When I clicked to detail report of Receiving and submited the input, it did not show anything but the blank page. Also how would I re-print the receipt?
And if the input qty is "0" in receiving, it goes to database error page. I suggest if there is an error signal with advice of the input in the same input page rather than goes to error page.

**Comment by fvillasenor19** [comment]
I agree with you, the problem in my case is when I quickly click twice on the button finish_sale_button or
finish_receiving_button

**Comment by fvillasenor19** [comment]
try to let it process the report or an option would be to disable the button when pressing it until it processes the report

**Comment by fvillasenor19** [comment]
the truth was that I was trying to disable the button in full action but I couldn't.
if you could help me it would be excellent

**Comment by daN4cat** [comment]
If my memory is right I fixed in 3.3.2. Hopefully that will be released soon.

**Comment by fvillasenor19** [comment]
Thanks  @daN4cat  when you add check in and check out time it seems like a good function

**Comment by WebShells** [comment]
@fvillasenor19 check in and out feature is being discussed on #2825 this is to be added to 3.4.0

**Comment by objecttothis** [comment]
I'll close this as 3.3.2 is being released with a fix
