### ISSUE TITLE
 add price in pull-left item inquiry in sales #question

### ISSUE THREAD

**Issue by fvillasenor19** [opensourcepos/opensourcepos#2832]
Información de la Instalación OSPOS: 3.3.1 - c786d4
Language Code: es

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.4
.PHP Version: 7.4.4
.DB Version: 5.5.5-10.4.11-MariaDB
.Server Port: 80
.OS: Windows NT TALLER-PC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓ 

help i have little programming knowledge.
I need to add the price to the name = "item" class="pull-left"  query in sales.

**Comment by andriux1990** [comment]
I don't understand what you want to do exactly

**Comment by fvillasenor19** [comment]
Search Suggestions Layout - Item Kit  andriux1990, open, 05/16/2020   very thanks
