### ISSUE TITLE
Latest commit Issue.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2835]
I am now getting the following error with error reporting enabled.
A PHP Error was encountered
Severity: Warning

Message: Use of undefined constant NO_DEFINITION_ID - assumed 'NO_DEFINITION_ID' (this will throw an Error in a future version of PHP)

Filename: models/Attribute.php

Line Number: 9

Backtrace:

File: C:\wamp64\www\my-master\application\models\Attribute.php
Line: 9
Function: _error_handler

File: C:\wamp64\www\my-master\public\index.php
Line: 315
Function: require_once

**Comment by daN4cat** [comment]
PHO version?

**Comment by odiea** [comment]
OSPOS Installation Info: 3.3.2 - dev

Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
.PHP Version: 7.3.2
.DB Version: 5.7.21
.Server Port: 80
.OS: Windows NT 10.0

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable ✗
» [import_customers.csv:] - 0666 | Readable ✓ | Security Check Passed ✓

There are problems with file permissions please fix and reload this page.

Security Vulnerability Warning
Permissions higher than 750 leaves this software at risk.

» [application/logs:] is writable, but the permissions are higher than 750.
» [public/uploads:] is writable, but the permissions are higher than 750.
» [public/uploads/item_pics:] is writable, but the permissions are higher than 750.

**Comment by odiea** [comment]
In Models/ Attribute I changed the following and it does not show me the issue any longer.
```
define('GROUP', 'GROUP');
define('DROPDOWN', 'DROPDOWN');
define('DECIMAL', 'DECIMAL');
define('DATE', 'DATE');
define('TEXT', 'TEXT');
define('CHECKBOX', 'CHECKBOX');
define('NO_DEFINITION_ID', '0');
define('CATEGORY_DEFINITION_ID', '-1');
```
