### ISSUE TITLE
Quantity Field is Disabled cant able to change quantity  Screen Shot added plz help me with issue

### ISSUE THREAD

**Issue by charan379** [opensourcepos/opensourcepos#2836]
OSPOS Installation Info: 3.3.1 - c786d4
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Edge
.Server Software: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.5
.PHP Version: 7.4.5
.DB Version: 5.5.5-10.4.11-MariaDB
.Server Port: 80
.OS: Windows NT MY-PC 10.0 build 18363 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓ 

Issue 👍 
Installed ospos today from this link [https://github.com/opensourcepos/opensourcepos/releases/download/3.3.1/opensourcepos.20191214181241.3.3.1.c786d4.zip](url) 

Quantity Field is Disabled cant able to change quantity as show in pic(ss)

![image](https://user-images.githubusercontent.com/37008444/82562084-32523400-9b92-11ea-88e5-9a7e9763d44b.png)

**Comment by odiea** [comment]
Yes. That is because you are using a Serial number.
