### ISSUE TITLE
Printing Receipt

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2837]
Can't print complete list of items (long list of items.... )

**Comment by izeblood** [comment]
Any idea ...maybe the setup of my printer?

**Comment by WebShells** [comment]
@izeblood if you meant sales with long items list is being cut not fully printed, it's something related to your printer configuration. You should add it up to 3276mm so the size of the paper will be 90(72.1) x 3276mm.
This will fix your issue, i'll close.

**Comment by izeblood** [comment]
thanks you @WebShells
