### ISSUE TITLE
New item modal is not loading

### ISSUE THREAD

**Issue by pasindu4u** [opensourcepos/opensourcepos#2839]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Installation Info: | 3.3.1 - c786d4
-- | --
en-US
» GD: Enabled ✓» BC Math: Enabled ✓» INTL: Enabled ✓» OpenSSL: Enabled ✓» MBString: Enabled ✓» Curl: Enabled ✓
.Browser: Chrome.Server Software: Apache/2.4.41 (Ubuntu).PHP Version: 7.4.3.DB Version: 8.0.20-0ubuntu0.20.04.1.Server Port: 80.OS: Linux ospos 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64
» [application/logs:] - 0777 \| Writable ✓» [public/uploads:] - 0777 \| Writable ✓» [public/uploads/item_pics:] - 0777 \| Writable ✓» [import_customers.csv:] - 0777 \| Writable ✓

 

### Issue / Bug  / Question / New Feature

Installed OSPOS on ubuntu 20.04 freshly for testing. Cannot get the item modal to working. All I get is a empty modal. However my friend who used this with XAMMP got this running smoothly. I'm a newbie to linux and my boss wants this done on linux. Please help me

**Comment by odiea** [comment]
Make attributes implementation compatible with only_full_group_by #2538

**Comment by odiea** [comment]
You should disable only_full_group_by in mysql and see if that fixes your issue.
