### ISSUE TITLE
Using a Cash Drawer (Suggestion: Add open cash drawer button without printing)

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2841]
Cash drawer will only open if the printer is done, then how can we check if the amount we gave for the change is correct if you NO longer look again for the sales.

**Comment by WebShells** [comment]
@izeblood you can set the cashdrawer to open AFTER printing, this can be done in printing preferences. After that you should set the delay for returning to sales page after printing for a period of 5 seconds or 10 seconds for the cashier to have enough time to double check.
This can solve your issue, maybe we should add open drawer button that prints 1 empty line; this will do the work

**Comment by izeblood** [comment]
I'll check it.. Thanks @WebShells

**Comment by izeblood** [comment]
I'll try this method..but it's not effective..
Maybe we this in order to open cash drawer independently with or without calling printer pulse.
![cash drawer](https://user-images.githubusercontent.com/32444665/85251898-23121f00-b48d-11ea-99bc-9148926b3b1b.jpg)

**Comment by andriux1990** [comment]
@izeblood I like how it looks .. how can I communicate with you?

**Comment by izeblood** [comment]
on

> @izeblood I like how it looks .. how can I communicate with you?

@andriux1990  Only here...

**Comment by izeblood** [comment]
or maybe the time that we add Amount Tendered, the cash drawer will open...

**Comment by andriux1990** [comment]
@izeblood do you have telegram?

**Comment by andriux1990** [comment]
> or maybe the time that we add Amount Tendered, the cash drawer will open...

The idea seems good to me .. I was thinking of using javascript ..

**Comment by izeblood** [comment]
yep. no db table involves its purely sdript directly to kick the cash drawer

**Comment by daN4cat** [comment]
This is something controlled via the printer driver, not sure it allows you to just open the cash drawer. Sending a dummy page break to open the cash drawer will risk to print a preconfigured header on the printer (some use that) wasting paper.

**Comment by bamkusniawan** [comment]
any solutions?
