### ISSUE TITLE
Cannot Change Receiving Date in Receiving Detailed Reports

### ISSUE THREAD

**Issue by robbytriadi** [opensourcepos/opensourcepos#2843]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [v] Reporting an issue of an unmodified OSPOS installation
- [v] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1 - c786d4
- OSPOS git commit hash is: 
- PHP version is: 7.1.33
- MySQL or MariaDB version is: 5.5.5-10.2.31-MariaDB
- OS and version is: Linux
- WebServer is: LiteSpeed
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Cannot change receiving date in receiving detailed report after choose the date. Cannot submit the change. The screenshot:

![image](https://user-images.githubusercontent.com/49820621/83359237-3a388200-a3a3-11ea-8a20-20652366f438.png)

There is an error message "Fields in red are required" but there is no field name in red

Thank you

**Comment by odiea** [comment]
Did you look at the Date on the Date picker? I don't think it can be changed. Should be a readonly input.

![2020-05-31 12_09_04-Glamour School Antalya WeB Tasarım KaliteliPanelci com _ Powered by OSPOS 3 3 2](https://user-images.githubusercontent.com/10962177/83359464-9fef2480-a337-11ea-91cb-5e89eca79eaf.png)

**Comment by robbytriadi** [comment]
> Did you look at the Date on the Date picker? I don't think it can be changed. Should be a readonly input.

If we change the date, the date format will be different with the previous.
Thank you

**Comment by jekkos** [comment]
@robbytriadi So you think that is the reason you can't change it? The dateformat is incorrect after you select another value? Do you see any exception in the dev console?

**Comment by odiea** [comment]
@jekkos Did you see the starting date on this datepicker. December 1899. What else is wrong with it. I replaced mine with the 1 from Expenses and had no issues after that.

**Comment by jekkos** [comment]
@odiea so you suggest to replace this picker with the one from expenses? Does that solve the 1899 issue? That one might be due to a wrong date format parse / evaluation

**Comment by odiea** [comment]
Or change it to a good Date picker. The expenses one worked for me.

**Comment by jekkos** [comment]
Fix is in master now.

**Comment by robbytriadi** [comment]
@jekkos thank you :)
