### ISSUE TITLE
Inventory Date Didn't Update when Update Sales Date

### ISSUE THREAD

**Issue by robbytriadi** [opensourcepos/opensourcepos#2844]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [v] Reporting an issue of an unmodified OSPOS installation
- [v] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1 - c786d4
- OSPOS git commit hash is: 
- PHP version is: 7.1.33
- MySQL or MariaDB version is: 5.5.5-10.2.31-MariaDB
- OS and version is: Linux
- WebServer is: LiteSpeed
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi All, I've found that inventory date did not update when update the sale date
Thank you

**Comment by andriux1990** [comment]
in version 3.3.2 - d5659b, which is from a few days ago, works perfectly

**Comment by robbytriadi** [comment]
> in version 3.3.2 - d5659b, which is from a few days ago, works perfectly

Please share the link to download 3.3.2. i've tried to install using git clone, but it can't running well 🙏🏼

Thank you

**Comment by andriux1990** [comment]
master should be fine .. I will review it.

links
https://bintray.com/jekkos/opensourcepos/opensourcepos#files

https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20200520100936.master.d5659b.zip

**Comment by robbytriadi** [comment]
> master should be fine .. I will review it.
> 
> link
> https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20200520100936.master.d5659b.zip

@andriux1990 ok, I'll try. Thank you

**Comment by robbytriadi** [comment]
I use version 3.2.3 - 4484a4. Inventory date doesn't update when sale or receiving date updated
![image](https://user-images.githubusercontent.com/49820621/100530708-ef030d00-3227-11eb-9fdb-69f17240d1e3.png)

Thank you

**Comment by jekkos** [comment]
@robbytriadi can you try latest master build? On my side this is working as it should.

![Screenshot from 2020-11-29 10-57-45](https://user-images.githubusercontent.com/576234/100538711-c253f300-3231-11eb-9e50-fa144654801c.png)

**Comment by robbytriadi** [comment]
@jekkos I've tried and its works. Thank you for fix this.
What I mean is if the date in receiving reports or sales (both report and daily sales are updated), the date in inventroy table isn't update

**Comment by jekkos** [comment]
how do you mean? the inventory table is updated every time a quantity changes.

**Comment by jekkos** [comment]
![Screenshot from 2020-11-30 23-05-09](https://user-images.githubusercontent.com/576234/100671286-88353f00-3360-11eb-9855-d19b377edbe1.png)

**Comment by robbytriadi** [comment]
@jekkos if you change the date of POS 1 in Daily sales or report (ex: transactions), the date of POS 1 in inventory table doesn't change. So, the date in sales report and inventory will be different

**Comment by jekkos** [comment]
Ok I see what you mean.

**Comment by jekkos** [comment]
@robbytriadi I did a fix for this, you can find a build on bintray soon.

**Comment by robbytriadi** [comment]
@jekkos thank you

**Comment by jekkos** [comment]
@robbytriadi in master now (for your convenience)

**Comment by robbytriadi** [comment]
@jekkos thank you. Is it the updated one? https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20201205004429.fix-default-register-mode.943856.zip

**Comment by jekkos** [comment]
You can download latest master branch instead @robbytriadi

**Comment by robbytriadi** [comment]
@jekkos its works! thanks a lot!
