### ISSUE TITLE
Changing Font Style for Receipt

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#2845]
How can i change the font style for the receipt? so that I can use Consolas as my font style. It is important for me so that I can differentiate the 0 and O. 

![receipt](https://user-images.githubusercontent.com/32444665/83376328-849e1b00-a404-11ea-9c16-24ac49768700.jpg)

**Comment by andriux1990** [comment]
Well I used to use something like this ...
@font-face{
    font-family:'Ticketing';
    src: url("Ticketing.woff");
}

#receipt_wrapper{
    font-family: 'Ticketing';
}

 to give an example.

but you want to do it from configuration.

**Comment by izeblood** [comment]
@andriux1990 can you please give the exact file for me to configure? thanks

**Comment by andriux1990** [comment]
> @andriux1990 can you please give the exact file for me to configure? thanks

to do it as you want from configuration you need to create a new table for the db.

I think it would be easier to create a custom receipt and be able to select it from the receipt template.

you have to create a css. and the css include the code that I copy above. then this css must have the exact address of the source (the source must be .woff)

**Comment by izeblood** [comment]
?????

**Comment by izeblood** [comment]
But what I did is add this to receipt_default     <div id="receipt_wrapper" style="font-family: Courier New" style="font-size:<?php echo $this->config->item('receipt_font_size');?>px">
