### ISSUE TITLE
After invoice creation, When i click on Sales Register previous sale data is still available 

### ISSUE THREAD

**Issue by spatil-InsightOps** [opensourcepos/opensourcepos#2846]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [YesYes] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0 - 0b9a76
- OSPOS git commit hash is: 
- PHP version is: 7.2.24-0ubuntu0.18.04.6
- MySQL or MariaDB version is:  5.7.30-0ubuntu0.18.04.1
- OS and version is: Linux ip-172-31-91-29 4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020 x86_64
- WebServer is: Apache/2.4.29 (Ubuntu)

### Issue / Bug  / Question / New Feature

In the Invoice register mode, I create a sale as shown below:
![image](https://user-images.githubusercontent.com/65078468/83390827-2e36d980-a410-11ea-814f-302b76bc3363.png)

After I click on invoice. the invoice appears.
Now when I go to the sales register it is expected that the previous sale should have automatically gone . But that does not happen. Can you please help me out with the same?

The pic below shows after the invoice generation when I click 'Sales Register'
![image](https://user-images.githubusercontent.com/65078468/83391140-a2717d00-a410-11ea-8491-bc1b2d73a0f0.png)

**Comment by odiea** [comment]
Does the Invoice receipt  show on the screen after you click on Invoice?

**Comment by tvpos** [comment]
i add new item for new invoice.
![image](https://user-images.githubusercontent.com/66126714/83413701-7d97fc80-a446-11ea-805b-30551a91f0c3.png)
then i click on image.
![image](https://user-images.githubusercontent.com/66126714/83413863-bc2db700-a446-11ea-8625-5a7afd265137.png)
but not finish
![image](https://user-images.githubusercontent.com/66126714/83413894-c6e84c00-a446-11ea-8bfe-8b3fe18f526b.png)
It 's old invoice. Some time button add payment hiden.

**Comment by odiea** [comment]
You need to add a customer to the Invoice or it will not work

**Comment by tvpos** [comment]
hi, i import csv but lose  quantity column, how to add column quantity ?
[image: image.png]

**Comment by spatil-InsightOps** [comment]
@odiea Yes, it does show the invoice receipt after I click the Invoice button.
But once I click the sale register I still find the same previous sale.

**Comment by odiea** [comment]
If it is not being sent then that may be the issue.
