### ISSUE TITLE
Your system folder path does not appear to be set correctly.  

### ISSUE THREAD

**Issue by dev-mu** [opensourcepos/opensourcepos#2858]
Who has managed to install and run Opensource pos successfully . each time I try to install I get this error >> Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php.  i have followed all online guides from reinstalling composers to changing permissions but none seem to work. I will appreciate all solutions to this. Thank you team

**Comment by odiea** [comment]
Please refrain from creating issues about installation problems before having read the FAQ and went through existing github issues. We have a build pipeline that checks the sanity of our latest repository commit and in case the application itself is broken then our build will be as well.

This application can be setup in many different ways and we only support the ones described in the INSTALL file linked below.

Read the INSTALL.md in our repository.

**Comment by dev-mu** [comment]
Hello Odiea, i have gone through the INSTALL.MD file and the approach described in there is not working.

**Comment by dev-mu** [comment]
i have managed to run the app successfully . thnk you Odiea
