### ISSUE TITLE
cash_refund disappears when changing payment type after sale

### ISSUE THREAD

**Issue by adamone19** [opensourcepos/opensourcepos#2861]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug

When I make the mistake of choosing "Debit Card" for a cash payment, item costs $6, $10 tendered, change due of $4. Two lines are generated in the table  ospos_sales_payments, one with the payment_amount with cash_refund of 0 and the other with the payment_amount of  0 and the cash_refund of $4. Then I realize my mistake and change the payment type to cash. This deletes the line with the cash_refund of $4 and end of day cashup is out by $4.
I have just tested this on the demo site and find the same problem.
This didn't happen when using 3.3.1
![image](https://user-images.githubusercontent.com/62197513/84353685-b341a000-ac13-11ea-8556-0169789e6cc9.png)
![image](https://user-images.githubusercontent.com/62197513/84353742-ceacab00-ac13-11ea-9ff5-6d52cb8ad540.png)

**Comment by mckaygerhard** [comment]
the implementation of payed amount in ospos are bad currently: a pay must be read only for DUE and for CREDIT CARD! becose those amounts are still not in the accountan of the store account!

sorry @adamone19 .. but those features are not accountant modes! you can still use my fork that have similar feaure right made!

**Comment by adamone19** [comment]
Hi, this wasn't a "question", just pointing out a bug.
Looks like there is no interest in fixing it but at least this post might save some time for someone else who encounters the same bug.

**Comment by hoststatic** [comment]
how you achieved adding multiple payments after sale @adamone19, I am trying to implement something similar

**Comment by adamone19** [comment]
Sale needs to be processed as an invoice, then you can go back into transactions/update and add payments to the transaction

**Comment by hoststatic** [comment]
Which version are you using?
How many payments could you add?

**Comment by adamone19** [comment]
3.3.8 But I have just seen your issue. I think the problem is that you are adding a "due" payment of the full amount. When it has been paid in full (even with a "due" payment) you can no longer add payments. You need to invoice without payment (or partial payment), then you can add as many payments as you like until it is paid in full.

**Comment by hoststatic** [comment]
It works thanks a bunch @adamone19

**Comment by adamone19** [comment]
Just glad to be able to help 😀Regards, Adam Craig (this was sent from my ***@***.*** 241 1246On 2022-12-13, at 20:45, hoststatic ***@***.***> wrote:﻿
It works thanks a bunch @adamone19
