### ISSUE TITLE
Add at least one grant for each module.

### ISSUE THREAD

**Issue by dev-mu** [opensourcepos/opensourcepos#2862]
Hey Guys, is it possible to create a user and grant him only one model?. for instance, I want to assign my employee-only access to the sales module and nothing else. every time I try to create an employee and assign them to a specific module I get a validation error "**Add at least one grant for each module**".

**Comment by andriux1990** [comment]
it's because you're doing it wrong. In addition to the module you must also assign a field, this is something very simple that I think you should not have problems
