### ISSUE TITLE
Demo Server down again.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2864]
A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: core/CodeIgniter.php

Line Number: 518

**Comment by odiea** [comment]
502 Bad Gateway
nginx/1.14.0 (Ubuntu)

**Comment by jekkos** [comment]
Ok installed some updates and running again.

**Comment by dpieski** [comment]
Im getting an HTTP ERROR 500 when testing "completing" a sale. Have reloaded, logged out / back in.

https://demo.opensourcepos.org/sales/complete

Should I make a new issue?

**Comment by odiea** [comment]
I just tested it and it appears to be completing a sale with no issues

**Comment by dpieski** [comment]
hmmm, thats odd. in the demo site, i unsuspended, add cash payment and complete and it keeps giving a 500. Ill try again later.

**Comment by odiea** [comment]
You are correct. It finishes a normal sale with no issue but it does give issues after unsuspending and then trying to complete the Sale

**Comment by odiea** [comment]
An Error Was Encountered
The URI you submitted has disallowed characters.

**Comment by jekkos** [comment]
where do you see this error exactly?

**Comment by odiea** [comment]
Apparently it got fixed. That was showing every time I tried to load any module

**Comment by jekkos** [comment]
OK great.

**Comment by andriux1990** [comment]
the error is present again

**Comment by odiea** [comment]
A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: core/CodeIgniter.php

Line Number: 518

**Comment by odiea** [comment]
A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: core/CodeIgniter.php

Line Number: 518

**Comment by jekkos** [comment]
Ok for some reason, the whole schema disappeared. Not sure how that happened but that is the reason why the error appears.?

I did see the mysql port was exposed on the host, so I disabled that already (as if eg it would allow an external user to connect with the default creds, then they might have been able to drop the db)

**Comment by daN4cat** [comment]
Uh oh... that was a bit of a security breach.

**Comment by jekkos** [comment]
Indeed. I double checked and the port is closed now to the public internet.

**Comment by jekkos** [comment]
I might also change the default creds in this docker compose just in case

**Comment by odiea** [comment]
Demo Server needs reset. No Items or Sales Tables are showing. Neither is the Date picker.

**Comment by jekkos** [comment]
This seems to be a js error. There is a quote missing in the darepicker code. No idea how that got in there

**Comment by odiea** [comment]
I downloaded and tried the current unstable master it it appears to be corrupted. Gives me the same issue.

**Comment by daN4cat** [comment]
@objecttothis is that missing quote related to your changes?

**Comment by objecttothis** [comment]
I can look tomorrow but my changes haven't been merged with the master. They are still in the branch.

**Comment by objecttothis** [comment]
I think the demo runs off whatever the last build was rather than the last master that was built. If it's an error in my branch I can fix it but perhaps the demo should be only the latest master?

**Comment by objecttothis** [comment]
Github is borked at the moment so I don’t know if even this will get through, but I did find the issue in a branch that I’m working on and have fixed it in that.  I checked out the master branch and the problem doesn’t exist there.  The reason that this happened on the demo is that the demo is whatever the last build is, not whatever the last master build is.  Since those builds are, by nature, a work it progress, this kind of thing will happen from time to time.  My recommendation is that the demo.opensourcepos.org is only the latest release version and then we have a separate demo that’s the latest release and a demo build for each PR or branch that has a build.  This allows us to keep the advantage of immediately being able to test branches that we are doing development on, but not cause problems with the demo that potential users will use to see if the software is something they want to deploy.

**Comment by jekkos** [comment]
Ok, I know you raised this before. I'll add a ticket to keep track of this. 

I'll edit the docker compose file to hosts two images: 

* last release (maybe by parsing a file in the repo itself)
* the last pushed commit on any branch in the repo

then I need to adapt the reverse proxy to map to the correct container

**Comment by jekkos** [comment]
I have deployed master again on the demo. The items are loading again.

**Comment by odiea** [comment]
502 Bad Gateway
nginx/1.14.0 (Ubuntu)

**Comment by jekkos** [comment]
Ok should be good
