### ISSUE TITLE
URI in invoice footer

### ISSUE THREAD

**Issue by haeckse** [opensourcepos/opensourcepos#2865]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: installed 3.3.1 release
- PHP version is: PHP 7.4
- MySQL or MariaDB version is: 5.7
- OS and version is: ?
- WebServer is: 1and1 webhost
- Selected language is: English / German

### Issue

The footer of the invoice shows on the left a module path like 'https://[host]/public/sales/complete'

This information shouldn't be visible on the printout. Maybe one could show https://ospos.wshells.org instead?

Is there a setting for hiding/replacing the URI or a workaround that is applicable to version 3.3.1 ?

**Comment by odiea** [comment]
That is normally a printer setting. Check and see if the header and footer are disabled in the printer

**Comment by haeckse** [comment]
In the printer settings, the checkboxes for header and footer are unchecked. The only setting that seems to work there is "show company name". All other settings, like 'set margins', 'show description', or 'show tax' don't change anything. 

And there is something odd when I send the changes: A blank page with the text `'{"success":true,"message":"Settings successfully stored."}` is invoked then. 
This doesn't happen with any other settings page. They work like expected, showing an overlay with the message "successfully stored" at the bottom of the regular page.

So maybe there is something broken in the setup module? Can it be reset somehow?

**Comment by odiea** [comment]
Not knowing what OS you are using try to set the header and Footer off when the print preview shows. Not from OSPOS but from your printer setup

**Comment by haeckse** [comment]
This was exactly the issue. It needs to be disabled in the OS-Printer dialog.

Thanks a lot for your help! :)
