### ISSUE TITLE
Blank screen when navigating to OSPOS.

### ISSUE THREAD

**Issue by BDub-Hay** [opensourcepos/opensourcepos#2866]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: **3.3.1**
- OSPOS git commit hash is: **Not exactly sure** 
- PHP version is: **7.2.24**
- MySQL or MariaDB version is: **MariaDB 10.1.44**
- OS and version is:  **Ubuntu 18.04**
- WebServer is:  **Apache**
- Selected language is:  **English**
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I am trying to get a fresh install of OSPOS up and running on a test system.  I installed mariadb, apache2, and php first along with all of the php modules then enabled the mod re-write.  
I downloaded the latest release, opensourcepos.20191214181241.3.3.1.c786d4.zip from github, and unziped it into my web root (/var/www/html/).  I created my database and database user, then populated the database with the .sql tables that came with the zip file (mysql -u admin -p ospos < database/database.sql).  I also granted all permissions on the ospos database to the database user.  I updated the database.php config file with the necessary database parameters (username, password and database name).  my last step was changing the owner and group of all files and folders under the /var/www/html directory.  I open up my favorite browser and enter localhost/public and i get a blank screen.  Any direction on how to fix my dilema would be greatly appreciated.  THank you.
Brian

**Comment by andriux1990** [comment]
It sounds like you will not write 'public' after the directory where it is ospos

**Comment by mckaygerhard** [comment]
bad installation.. @BDub-Hay  .. @odiea  put the label but no response.. nobody make a respnse for this kind of issues due are not an issue.. 

ironically always said here: "there is no support just issues" so you can contact me!

**Comment by objecttothis** [comment]
@BDub-Hay Please turn on your error log in the config.php to log_level 1 and post what logs get generated.  You should also look at your PHP error log.  blank screens usually are causes by configuration issues or missing prerequisite PHP components.

**Comment by WhatTheStack1** [comment]
Same issue

**Comment by gulbalee** [comment]
I'm getting the same issue, blank screen after entering login credentials. Any help?

ubuntu 20.04
ospos version 3.3.6


followed this tutorial for installation however used 3.3.6 files instead
https://www.opensourceposguide.com/guide/gettingstarted/installation


error log is as follows. 
```
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-03-15 14:46:25 --> Query error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ospos1.ospos_attribute_values.attribute_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - Invalid query: SELECT `attribute_decimal`, `attribute_id`
FROM `ospos_attribute_values`
GROUP BY `attribute_decimal`
HAVING COUNT(attribute_decimal) > 1
ERROR - 2022-03-15 14:46:25 --> Severity: error --> Exception: Call to a member function result_array() on bool /var/www/html/application/migrations/20210422000000_database_optimizations.php 85

```

chrome shows This page is currently unable to handle this request.
HTTP ERROR 500

**Comment by objecttothis** [comment]
> I'm getting the same issue, blank screen after entering login credentials. Any help?
> 
> ubuntu 20.04 ospos version 3.3.6
> 
> followed this tutorial for installation however used 3.3.6 files instead https://www.opensourceposguide.com/guide/gettingstarted/installation
> 
> error log is as follows.
> 
> ```
> <?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
> 
> ERROR - 2022-03-15 14:46:25 --> Query error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ospos1.ospos_attribute_values.attribute_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - Invalid query: SELECT `attribute_decimal`, `attribute_id`
> FROM `ospos_attribute_values`
> GROUP BY `attribute_decimal`
> HAVING COUNT(attribute_decimal) > 1
> ERROR - 2022-03-15 14:46:25 --> Severity: error --> Exception: Call to a member function result_array() on bool /var/www/html/application/migrations/20210422000000_database_optimizations.php 85
> ```
> 
> chrome shows This page is currently unable to handle this request. HTTP ERROR 500

turn off `sql_mode=only_full_group_by` in your SQL config and it will work.
