### ISSUE TITLE
New Item Details Menu Blank

### ISSUE THREAD

**Issue by wis2020** [opensourcepos/opensourcepos#2869]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Installation Info: 3.3.1 - c786d4
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache
.PHP Version: 7.1.33
.DB Version: 5.7.30
.Server Port: 80
.OS: Linux svr20.internet-webhosting.com 3.10.0-962.3.2.lve1.5.35.el7.x86_64 #1 SMP Tue Apr 14 15:56:28 EDT 2020 x86_64

File Permissions:
» [application/logs:] - 0755 | Writable ✓ 
» [public/uploads:] - 0755 | Writable ✓ 
» [public/uploads/item_pics:] - 0755 | Writable ✓ 
» [import_customers.csv:] - 0644 | Writable ✓ 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

The menu does not appeared when click "Add New Item".
Instead, try created 1 item by importing through CSV file.
However, tried to edit the item, by click the edit button right side of the item.
Also, nothing appeared in the item's detail menu. 
![New Item Error](https://user-images.githubusercontent.com/46512067/85918896-50017000-b899-11ea-93bc-4ae30579966c.png)

**Comment by odiea** [comment]
If you see the item edit dialog box empty starting with version 3.3.0, please disable only_full_group_by option from MySQL/MariaDB. See issue #2538.

**Comment by wis2020** [comment]
> If you see the item edit dialog box empty starting with version 3.3.0, please disable only_full_group_by option from MySQL/MariaDB. See issue #2538.

Hi,

Thank for the feedback. But, errrr I can't find it...
Guessed, can help to provide a
![New Item Error 2](https://user-images.githubusercontent.com/46512067/85921928-5b14ca00-b8b2-11ea-8652-938bf831b17d.png)
 little bit more info ?

**Comment by odiea** [comment]
Look in the php.ini file and see if it is there

**Comment by objecttothis** [comment]
In his case it will be my.cnf
