### ISSUE TITLE
After this mornings merge I receive the following. What's up?

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2872]
Error Number: 1111

Invalid use of group function

SELECT `sales`.`sale_id` AS `sale_id`, MAX(DATE(sales.sale_time)) AS sale_date, MAX(sales.sale_time) AS sale_time, MAX(sales.comment) AS comment, MAX(sales.sale_status) AS sale_status, MAX(sales.invoice_number) AS invoice_number, MAX(sales.quote_number) AS quote_number, MAX(sales.employee_id) AS employee_id, MAX(CONCAT(employee_p.first_name, " ", employee_p.last_name)) AS employee_name, MAX(employee_p.first_name) AS first_name, MAX(employee_p.last_name) AS last_name, MAX(sales.customer_id) AS customer_id, MAX(CONCAT(customer_p.first_name, " ", customer_p.last_name)) AS customer_name, MAX(customer_p.first_name) AS first_name, MAX(customer_p.last_name) AS last_name, MAX(customer_p.email) AS email, MAX(customer_p.comments) AS comments, MAX(ROUND(SUM(CASE WHEN sales_items.discount_type = 0 THEN sales_items.item_unit_price * sales_items.quantity_purchased * (1 - sales_items.discount / 100) ELSE sales_items.item_unit_price * sales_items.quantity_purchased - sales_items.discount END), 2) + ROUND(IFNULL(SUM(sales_items_taxes.sales_tax), 0), 2)) AS amount_due, IFNULL(MAX(payments.sale_payment_amount), 0) AS amount_tendered, IFNULL(MAX(payments.sale_payment_amount) - MAX(ROUND(SUM(CASE WHEN sales_items.discount_type = 0 THEN sales_items.item_unit_price * sales_items.quantity_purchased * (1 - sales_items.discount / 100) ELSE sales_items.item_unit_price * sales_items.quantity_purchased - sales_items.discount END), 2) + ROUND(IFNULL(SUM(sales_items_taxes.sales_tax), 0), 2)), 0) AS change_due, MAX(payments.payment_type) AS payment_type FROM `ospos_sales_items` AS `sales_items` INNER JOIN `ospos_sales` AS `sales` ON `sales_items`.`sale_id` = `sales`.`sale_id` LEFT JOIN `ospos_people` AS `customer_p` ON `sales`.`customer_id` = `customer_p`.`person_id` LEFT JOIN `ospos_customers` AS `customer` ON `sales`.`customer_id` = `customer`.`person_id` LEFT JOIN `ospos_people` AS `employee_p` ON `sales`.`employee_id` = `employee_p`.`person_id` LEFT JOIN `ospos_employees` AS `employee` ON `sales`.`employee_id` = `employee`.`person_id` LEFT OUTER JOIN `ospos_sales_payments_temp` AS `payments` ON `sales`.`sale_id` = `payments`.`sale_id` LEFT OUTER JOIN `ospos_sales_items_taxes_temp` AS `sales_items_taxes` ON `sales_items`.`sale_id` = `sales_items_taxes`.`sale_id` AND `sales_items`.`item_id` = `sales_items_taxes`.`item_id` AND `sales_items`.`line` = `sales_items_taxes`.`line` WHERE `sales`.`sale_id` = '3337' GROUP BY `sale_id` ORDER BY `sale_time` ASC

Filename: C:/wamp64/www/my-master/vendor/codeigniter/framework/system/database/DB_driver.php

Line Number: 691

**Comment by odiea** [comment]
This appears when I try to load or Edit a Sale  Receipt

**Comment by odiea** [comment]
Demo is showing this same error when trying to show the receipt in Takings

**Comment by odiea** [comment]
I removed the last commit so that is not the issue. It might be in a prior commit.

**Comment by odiea** [comment]
I reloaded a previous version pf models/sale.php and the issue is not present.

**Comment by odiea** [comment]
@SteveIreland Would you check out the demo to see whats going on with this. Go to Takings and try to edit or reprint a Receipt.

**Comment by objecttothis** [comment]
Models->Sale line 100 seems to be the culprit according to the error I get in the demo when I click show receipt in the list of sales.

**Comment by objecttothis** [comment]
Here is the pretty-print of the generated SQL.  It may shed some light on the situation.  I can confirm that the error isn't occuring on earlier commits

````
SELECT
    `sales`.`sale_id` AS `sale_id`,
    MAX(DATE(sales.sale_time)) AS sale_date,
    MAX(sales.sale_time) AS sale_time,
    MAX(sales.comment) AS COMMENT,
    MAX(sales.sale_status) AS sale_status,
    MAX(sales.invoice_number) AS invoice_number,
    MAX(sales.quote_number) AS quote_number,
    MAX(sales.employee_id) AS employee_id,
    MAX(sales.customer_id) AS customer_id,
    MAX(
        CONCAT(
            customer_p.first_name,
            " ",
            customer_p.last_name
        )
    ) AS customer_name,
    MAX(customer_p.first_name) AS first_name,
    MAX(customer_p.last_name) AS last_name,
    MAX(customer_p.email) AS email,
    MAX(customer_p.comments) AS comments,
    MAX(
        ROUND(
            SUM(
                CASE WHEN sales_items.discount_type = 0 THEN sales_items.item_unit_price * sales_items.quantity_purchased *(1 - sales_items.discount / 100) ELSE sales_items.item_unit_price * sales_items.quantity_purchased - sales_items.discount
            END
        ),
        2
    ) + ROUND(
        IFNULL(
            SUM(sales_items_taxes.sales_tax),
            0
        ),
        2
    )
) AS amount_due,
IFNULL(
    MAX(payments.sale_payment_amount),
    0
) AS amount_tendered,
IFNULL(
    MAX(payments.sale_payment_amount) - MAX(
        ROUND(
            SUM(
                CASE WHEN sales_items.discount_type = 0 THEN sales_items.item_unit_price * sales_items.quantity_purchased *(1 - sales_items.discount / 100) ELSE sales_items.item_unit_price * sales_items.quantity_purchased - sales_items.discount
            END
        ),
        2
    ) + ROUND(
        IFNULL(
            SUM(sales_items_taxes.sales_tax),
            0
        ),
        2
    )
),
0
) AS change_due,
MAX(payments.payment_type) AS payment_type
FROM
    `ospos_sales_items` AS `sales_items`
INNER JOIN `ospos_sales` AS `sales`
ON
    `sales_items`.`sale_id` = `sales`.`sale_id`
LEFT JOIN `ospos_people` AS `customer_p`
ON
    `sales`.`customer_id` = `customer_p`.`person_id`
LEFT JOIN `ospos_customers` AS `customer`
ON
    `sales`.`customer_id` = `customer`.`person_id`
LEFT OUTER JOIN `ospos_sales_payments_temp` AS `payments`
ON
    `sales`.`sale_id` = `payments`.`sale_id`
LEFT OUTER JOIN `ospos_sales_items_taxes_temp` AS `sales_items_taxes`
ON
    `sales_items`.`sale_id` = `sales_items_taxes`.`sale_id` AND `sales_items`.`item_id` = `sales_items_taxes`.`item_id` AND `sales_items`.`line` = `sales_items_taxes`.`line`
WHERE
    `sales`.`sale_id` = '1'
GROUP BY
    `sale_id`
ORDER BY
    `sale_time` ASC
````

**Comment by objecttothis** [comment]
@odiea can you post the hash for which bintray build it is working in?  I see from the demo that it is broken in a11f25.

**Comment by odiea** [comment]
Sorry. I just go back in the File History and use that one. commit a3fb05b is the one that I used to test it with.

**Comment by objecttothis** [comment]
@odiea I'm getting ready to go to bed, but could you do me a favor?  Could you change line 95 in the most recent master (that's broken) from `$this->db->where('sales.sale_id', $sale_id);` to `$this->db->having('sales.sale_id', $sale_id);` and tell me if that fixes the problem?

**Comment by objecttothis** [comment]
> 
> 
> Sorry. I just go back in the File History and use that one. commit [a3fb05b](https://github.com/opensourcepos/opensourcepos/commit/a3fb05b566ebe1683e540824f4a16c91410cc9f0) is the one that I used to test it with.


Meaning, it works in that commit, but not in a3fb05b?  Is that What you mean?

**Comment by jekkos** [comment]
was just cheking demo (which works) and locally with latest master, but nothing unusual there

**Comment by jekkos** [comment]
ok no too fast, now I have hit the problem

**Comment by objecttothis** [comment]
> 
> 
> was just cheking demo (which works) and locally with latest master, but nothing unusual there

When I tried it on the demo it was broken.

Sales --> Daily Sales button --> Click the dollar sign next to any of the sales "show receipt"

**Comment by objecttothis** [comment]
@jekkos This stack exchange article (https://stackoverflow.com/questions/2330840/mysql-invalid-use-of-group-function) was pointing this guy's issue to using where when he should have been using having.  That's why I asked @odiea to replace it.  Maybe you could try it too.

**Comment by odiea** [comment]
Meaning I took the Sale.php from the previous commit and replaced mine with it and it did not show the problem. Copy and Paste:)

**Comment by odiea** [comment]
I tried that and it did not change anything. I even tried in a different browser

**Comment by objecttothis** [comment]
> 
> 
> Meaning I took the Sale.php from the previous commit and replaced mine with it and it did not show the problem. Copy and Paste:)

OK, that helps.  @SteveIreland made some changes in that function to fix destination taxes.  I'm guessing that some of those changes caused something with the SQL to need to be different.  There are many places in the code where we are doing quite a bit in one single SQL query and it makes it a bit of a bear to troubleshoot things like this.

**Comment by objecttothis** [comment]
OK, I'm down for the night.  I think we are waiting on #2820 to release 3.3.2 anyway, so perhaps @SteveIreland can take a look at it... or @jekkos.

**Comment by jekkos** [comment]
OK I had a quick look and directly pinpoint the issue. Maybe @SteveIreland has an idea here, it has something to do with the changes in that query for the tax included fix. I can't directly see what is wrong here, but when reverting that method the receipt works again.

**Comment by SteveIreland** [comment]
I'll take a look at it tonight.

**Comment by SteveIreland** [comment]
I was able to replicate the issue this morning.   I don't see see why.  It doesn't feel like the displayed reason is the real reason.  But I'll have a fix tonight.  Sorry - definitely shoulda caught that.

**Comment by SteveIreland** [comment]
I'm going to do more testing this weekend.  What concerns me is when I posted the original pull request I had completed a thorough test and know I had tested the daily sales function (even though it looks like I never bothered).  When I made my last small rebase I didn't repeat the earlier tests.  I just made sure that the sales entry was still working as expected for base, destination based included tax and destination based excluded tax.

So I'm a little nervous about what else might not be working as expected.

So if you can please test in your scenario and I'll do a more thorough test this weekend in a variety of scenarios.

Thanks.

**Comment by objecttothis** [comment]
Yeah, having a good unit test suite will give us a lot more peace of mind. Getting phpunit running in my dev environment is first on my docket once I get two of these PRs into production.
