### ISSUE TITLE
Items in Kilogram, milligram and gram

### ISSUE THREAD

**Issue by muhammadubaid001** [opensourcepos/opensourcepos#2875]
Hi there, how can I add items that have some weight like in Kgs or grams and also sell the items in weight? And, when I want to add an item I will add the price of 1kg for that item.

**Comment by objecttothis** [comment]
Create an Attribute with DECIMAL type and then fill in the unit of measurement in the attribute form

**Comment by SteveIreland** [comment]
Just out of curiosity, isn't this already baked into the product.  Quantities can be decimal.   I know I set it up a site a couple of years ago to allow product to be sold by fractions of a gallon.  The price was "per gallon".  Was this feature somehow lost along the way?

**Comment by objecttothis** [comment]
@SteveIreland I think the OP is either referring to adding a unit of measure (pages, grams, dozen, etc) to attributes, or on second reading, perhaps the are interested in adding a unit of measure to the quantity field.  The former is already in place, although I'm planning to add the unit of measure to the views that show the attribute at some point.  Quantity is by default a decimal.  The precision can be adjusted in the configuration of OSPOS.  I think it's called quantity decimals.
