### ISSUE TITLE
opensourcepos premium version ?

### ISSUE THREAD

**Issue by syrakozz** [opensourcepos/opensourcepos#2882]
hello is there any premium version from this software , because i have a couple of feature i would like to request , or if some one can develop them for me

**Comment by izeblood** [comment]
Just elaborate your request with a simple and clear explanation. attachment will be appreciated.

**Comment by objecttothis** [comment]
At this point there is no premium version of the software.  You can hire a developer to make the changes for you and from there you have two options:
1. You can submit a pull request with the changes and if the changes are useful for the community as a whole, they can be merged into the master.
2. You can fork the repository and make the changes there.

The first option is better for you and the community.  The reason for this is that if you fork the project then you have to maintain that project separately which means any changes to this master that take place you will have to manually merge into your fork and resolve conflicts.  Choosing option 1 also benefits the community as a whole.

As @izeblood said, you should write what it is that you are wanting to do with the software and that is a good way to get the ball rolling.

**Comment by mckaygerhard** [comment]
tht's the problem, for us are easy those process but for those that only wants simpel responses.. just only responses with "pull request" and "fork" .. all of those words for developers .. 

i guess if i put and offers service for this person  @syrakozz  sure comment will be deleted..

**Comment by objecttothis** [comment]
@mckaygerhard you can offer to help the person.  You can even get paid for the work.  What you can't do is constantly criticize the work of other developers in your comments on issues.

**Comment by daN4cat** [comment]
If one comes to GitHub, they must have some notion of development, integration or application installation from basics...

**Comment by daN4cat** [comment]
By the way, I was under the impression that softacolous was offering a mean to install OSPOS from CPanel.

**Comment by objecttothis** [comment]
> 
> 
> By the way, I was under the impression that softacolous was offering a mean to install OSPOS from CPanel.

They do.  The current version I see on my shared host is 3.3.1 which is the latest released version.

**Comment by WebShells** [comment]
@daN4cat yes, was checking it. It's been a while since they are offering the setup. 
I think we should replace the content listed there with updated one.

**Comment by daN4cat** [comment]
Reason to release 3.3.2 do softacolous can move to that version.
