### ISSUE TITLE
Adding new items seem to be an issue on new install

### ISSUE THREAD

**Issue by darkjedeye** [opensourcepos/opensourcepos#2888]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- []x Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1 
- OSPOS git commit hash is: not sure
- PHP version is: 7.0.33
- MySQL or MariaDB version is: 5.7.30
- OS and version is: ubuntu 16.04 lts
- WebServer is: apche 2
- Selected language is: Englis
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
Hi Guiys.... have looked through the documentation, and had this issue before... but can't remember what i did to fix it, I can't seem to add items... get a small new item window with no space to do anything and submit and new buttons... can't remember if it was a css edit or a database issue....

Screen shot attached.

![add items](https://user-images.githubusercontent.com/29452733/87229483-90d4ab00-c3a8-11ea-9100-54e06ff95211.PNG)

**Comment by darkjedeye** [comment]
sorry, forgot, browser is chrome

**Comment by odiea** [comment]
If you see the item edit dialog box empty starting with version 3.3.0, please disable only_full_group_by option from MySQL/MariaDB. See issue #2538.

**Comment by darkjedeye** [comment]
sorry for duplicating... i seem to have missed that article... my most humble appologies... i will follow the directions and revert back.

**Comment by darkjedeye** [comment]
Thank you so much... you are epic... that solved it... and i should read more carefully.

**Comment by daN4cat** [comment]
Reason to release 3.3.2... where are we with that?
