### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Shaho87** [opensourcepos/opensourcepos#2899]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by Shaho87** [comment]
Dears,
Any documentation about this amazing POS ? if there is not any documentation then would you please tell me what is difference between sales type especially when i select a customer .?
![image](https://user-images.githubusercontent.com/15319401/88089462-b0cc5180-cb94-11ea-907e-f98c34ab3f24.png)

**Comment by andriux1990** [comment]
The receipt is proof of purchase of a product or service, through which your payment is credited. The receipt is issued by the provider always after the payment you receive in the transaction, as it is proof of it.

For its part, the invoice is a more complete document that proves that a commercial operation has been carried out and that it has tax purposes. 

so for the invoice it is mandatory that you bring a customer. while in receipt no

**Comment by Shaho87** [comment]
Dear Andriux,
Thanks a lot this part is somehow clear for me but when I select receipt in the customer section its written (Select Customer (Required for Due Payments)) which is not clear for me .
would you please tell me if I have select customer and select due payment what is meaning of that operation ?
Regards.

**Comment by WebShells** [comment]
@Shaho87 In this case you are proceeding with a sale without adding payments to the current operation. In this case you should select a customer name in order to add the due amount to his account. Hope this makes it clear!

**Comment by Shaho87** [comment]
@WebShells thanks a lot this is clear now . but if I want to payback for customer below is example
![image](https://user-images.githubusercontent.com/15319401/88109591-77efa500-cbb3-11ea-9dfc-fc18f277f42a.png)
how customer can payback this 58$ ?is there anyway ?

**Comment by WebShells** [comment]
Yes, you can go to the Daily Sales sales and search for customer name, edit the sale and set the payment as cash or you can go to Reports, Detailed Customers Report, select Due from filter, then edit the sale and set it as cash. You're welcome, glad it's clear.

**Comment by odiea** [comment]
Or you can Refund the amount in the Register

**Comment by odiea** [comment]
When you Refund the Sale the Inventory will be updated with the returned Items.

**Comment by Shaho87** [comment]
@WebShells  thanks for support but both mentioned ways are not working the amount from customer is not updated .

**Comment by Shaho87** [comment]
@odiea thanks but I want to do payment not return item .

**Comment by WebShells** [comment]
@Shaho87 you're looking into the wrong module, you should be looking in customer reports not customers total spent value.

**Comment by Shaho87** [comment]
@WebShells  I am afraid that we misunderstood let me let me ask my question in another way   
below customer has to pay back 58$ 
![image](https://user-images.githubusercontent.com/15319401/88192640-7373cc80-cc45-11ea-98b1-df93eed05482.png)
then if above 2 mentioned points by you is how to update money for customer then I have tried both but not succeed .
Please your support ....

**Comment by mckaygerhard** [comment]
> Dears,
> Any documentation about this amazing POS ? if there is not any documentation then would you please tell me what is difference between sales type especially when i select a customer .?
> ![image](https://user-images.githubusercontent.com/15319401/88089462-b0cc5180-cb94-11ea-907e-f98c34ab3f24.png)

the meanin was incomplete.. of course ospos does not are a accountan sistem so try to provide minimal one.. that's the trick.. if you need more info i have several one..
