### ISSUE TITLE
selling os pos 

### ISSUE THREAD

**Issue by Shaho87** [opensourcepos/opensourcepos#2902]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by Shaho87** [comment]
Dears ,
Can I modify os pos and sell it ?

**Comment by odiea** [comment]
No. That is not permitted.

**Comment by objecttothis** [comment]
Thank you for asking.  Please read the full license (https://github.com/opensourcepos/opensourcepos/blob/master/LICENSE)

Here is the relevant section. The short answer is yes you can, but you can't say it's your software and you can't remove OSPOS badging.  Many people sell the maintenance contract to maintain the software for them.

> Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

You cannot claim copyright or ownership of the Software.

Versions ≥ 3.3.2:

Footer signatures "© 2010 - 2020 · opensourcepos.org · 3.3.2 - 6909c8" 
In the format of: "© 2010 - Current Year · opensourcepos.org · Version - Commit"

and/or 

"· opensourcepos.org ·"

with version, hash and URL link to the official website of the project MUST BE RETAINED, 
MUST BE VISIBLE IN EVERY PAGE and CANNOT BE MODIFIED.

Versions < 3.3.2:

Footer signatures "You are using Open Source Point Of Sale" 

and/or 

"Open Source Point Of Sale"

with version, hash and URL link to the original distribution of the code MUST BE RETAINED, 
MUST BE VISIBLE IN EVERY PAGE and CANNOT BE MODIFIED.

**Comment by objecttothis** [comment]
> 
> 
> No. That is not permitted.

@odiea according to the license he can.  maybe I'm not reading it correctly.

**Comment by Shaho87** [comment]
@objecttothis  thanks a lot and that is very kind of you to response .
can you show me a way to have my own version of this OS POS ? like PHP POS (https://phppointofsale.com/) ..
I will take the source code and change everything and modify the code , change interface and add features .
so at least I spend about 700$-800$ .

**Comment by objecttothis** [comment]
You would need to fork the project.  Keep in mind that if you are going to hire developers to do that kind of work, it will likely cost significantly more than $700-$800.  You also need to understand that the license is very strict in that you can't claim the software is yours and you can't remove or modify the footer, even if you change the interface and add features.  My understanding of PHPPOS is that this project was a fork of PHPPOS when the original developer wanted to make the software a paid model.  This project has remained open source.

**Comment by Shaho87** [comment]
so You mean that OS POS is fork version of PHP POS not other way around ?then developer decide to close PHP POS ?

**Comment by odiea** [comment]
@objecttothis . It was always my understanding that a person could not sell OSPOS but could include it with the Sale of other Items.
Any person or company found breaching the license agreement will have a bunch of monkeys at the door ready to destroy their servers. As per the licencing agreement. But I may be wrong.

**Comment by Shaho87** [comment]
@odiea  please read the license part carefully 

https://github.com/opensourcepos/opensourcepos#license

**Comment by odiea** [comment]
If this is a problem then @jekkos can tell us what he thinks.

**Comment by Shaho87** [comment]
@odiea  Nice suggestion thanks .

**Comment by objecttothis** [comment]
@odiea It seems to me that if someone were to go on eBay and sell copies of OSPOS that this would be or should be a violation of the spirit of open source software, however, I was answering based on the text of the license. It seems like as long as you weren't claiming that the software was yours and you kept the footer and relevant badging in place that the license says someone could do just that. I don't think someone should be able to do that but I think we would need to change the license in order to enforce that.

**Comment by Shaho87** [comment]
I have seen many version of OS POS and people selling it without asking ....here I want to have permission or legal way to do business that is why I am here need your support .

**Comment by odiea** [comment]
https://github.com/opensourcepos/opensourcepos/blob/master/LICENSE states that it can be sold if all the license agreements are met. My misunderstanding then.

**Comment by odiea** [comment]
Have fun with it and hopefully you will commit something back to the original OSPOS.

**Comment by Shaho87** [comment]
@odiea  thanks a lot .....how is original developer of OS POS do you know please ?

**Comment by odiea** [comment]
I believe @jekkos took it over from  Copyright (c) 2012-2014 pappastech.

**Comment by Shaho87** [comment]
how can I contact him ? is there any way to contact @jekkos  ?

**Comment by odiea** [comment]
He will probably read the thread and may return your questions. His time zone is in Belgium so probably sleeping now.

**Comment by Shaho87** [comment]
I hope he respond to this thread ...

thank you so much for your time and @objecttothis  appreciate your support .

**Comment by Shaho87** [comment]
Dears,
which version doesn't have any license ?

**Comment by jekkos** [comment]
I think we have the license in place for quite some time now. It was indeed started from the original phppos source code (version 1.0) that might be around somewhere. That one looks very different from what we have now and will probably still have a regular MIT license in place.

**Comment by Shaho87** [comment]
@jekkos  thanks a lot. is there a way to get white label of this OS POS ?or how can I get full authority like PHP POS ?

**Comment by Shaho87** [comment]
Dear @jekkos  I have found a version which is V1.0.A with no license please find below link 
https://sourceforge.net/projects/poson/

**Comment by Shaho87** [comment]
the Application is not working but I will fix it and fork my version from it .
As I got some information OSPOS and PHP POS are different programs.  OSPOS is a forked version of PHP POS, but it split off years ago.
anyway I will not take your license app adn dont use it and in case I use it I will follow your license on version 3.3.1 .
but for the old version of PHP POS + OS POS there is no license .

**Comment by Shaho87** [comment]
and below is your original OS POS 

https://sourceforge.net/projects/opensourcepos/files/ 
 I will use POS On - OsPos instead of your OS POS and I will put my own license .
Have a good day and time .

**Comment by objecttothis** [comment]
> 
> 
> I have seen many version of OS POS and people selling it without asking ....here I want to have permission or legal way to do business that is why I am here need your support .

If you are aware of specific cases of people violating the license, please let us know the specific software so that we can pursue it.  Most of the contributors don't take kindly to other people profiting off  their work without recognition.

**Comment by Shaho87** [comment]
Here and there I have seen quite versions but dont remember exactly where was it .
I do care about license rights that is why I will not take OS POS even I take it to make business I will follow all license .
I will take above mention very OLD POS which is same in PHP but not related to OS POS and I will spend money on it then will put license like yours .

**Comment by daN4cat** [comment]
To be honest, the design of this application is old. It will require a massive redesign to bring it to a more modern and commercially acceptable form.
Also to make it a proper SaaS solution it should support integration with a proper IAM, have proper access control and being multitenant, multiuser and multisite. REST APIs, single page application front end, broken down in microservices, just to name few more.
Reporting left to an external tool accessible via Single Sign On.

It's a good old toy that does the job but we struggle to touch it without breaking something.

**Comment by daN4cat** [comment]
Having said that, we still love it.

**Comment by Shaho87** [comment]
Hello @daN4cat thanks I will build another POS from scratch because what you are saying is correct .

**Comment by mckaygerhard** [comment]
@Shaho87  i'm interesting in work togetter i have several improvement coded for opensourcepos also i know other have.. the last one that still work in improvement are @andriux1990  that providesd renew interface.. 

i also provides a androit compatible gui with responsibe desing too .. and mantain codebase almost up to date removing not usefully features..  as some people here said.. its a inherint app .. but some people (with private repos) have a newer aproach of.. 

phppos are the predecesor of.. but today i check and see many forks that tracks the opensourcepos work.. i guess if you @Shaho87  with your open mind work togetter with others can release a good project..
