### ISSUE TITLE
Will my Linux Distro be helpful for newbies?

### ISSUE THREAD

**Issue by asakpke** [opensourcepos/opensourcepos#2904]
### Background information
- [x] Reporting an issue of an unmodified (almost) OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: c786d4e0ab5c3d7e61cea1c7044b339917b86ce9
- PHP version is: 7.4.3
- MySQL version is: 8.0.20
- OS and version is: Linux Mint 20
- WebServer is: Apache
- Selected language is: English
- (If applicable) Docker installation: N/A
- (If applicable) Installation package for the LAMP/LEMP stack is: LAMP

### Question
I have created new distro (Linux Mint 20 based) with functional Open Source Point of Sale. My intention was to facilitate newbies. Will it help? What do you think?

(~~Currently I'm uploading files to SourceForge.net/u/asakpke, hopefully uploaded in few hours/days. I'll update link here when it's uploaded.~~) Here's the [ISO file](https://sourceforge.net/projects/roshantech-com-pos-os/files/POS-OS-2.0.1.iso/download) to download. [MD5 Sum](https://sourceforge.net/projects/roshantech-com-pos-os/files/POS-OS-2.0.1.iso.md5sum.txt/download). And necessary installation & basic help [doc](https://sourceforge.net/projects/roshantech-com-pos-os/files/Installation%20help.pdf/download). Use password below if asked anywhere

> esite.pk

#### RoshanTech POS OS 2 Screenshot
![RoshanTech POS OS 2 Screenshot](https://user-images.githubusercontent.com/7318102/88248327-3dbcfb00-ccba-11ea-931c-74d41ed3c9b1.png)

**Comment by asakpke** [comment]
Here's the [ISO file](https://sourceforge.net/projects/roshantech-com-pos-os/files/POS-OS-2.0.1.iso/download) to download. [MD5 Sum](https://sourceforge.net/projects/roshantech-com-pos-os/files/POS-OS-2.0.1.iso.md5sum.txt/download). And necessary installation & basic help [doc](https://sourceforge.net/projects/roshantech-com-pos-os/files/Installation%20help.pdf/download). Use password below if asked anywhere

> esite.pk

**Comment by odiea** [comment]
Thanks. I will try this out over the weekend.

**Comment by jekkos** [comment]
@asakpke how do you in fact create the iso file? Mostly the issue is that such images are quickly outdated. Security patches are rolled out every week / month.

But I guess it's fine for the purpose of running this in a virtual machine or the like. I think the docker cloud setup (one click deploy) at the time came sort of close to this one.

**Comment by odiea** [comment]
I tried to install it in vmware with no luck.

**Comment by asakpke** [comment]
> I tried to install it in vmware with no luck.

It's working in Virtual Box & I have tested it physically on laptop via USB & DVD both.

**Comment by asakpke** [comment]
> @asakpke how do you in fact create the iso file?

I used Systemback software for creating .ISO image. You can take the current images, install, improve it (i.e update OSPOS/etc) and create new one using the same tool (Systemback).

> Mostly the issue is that such images are quickly outdated. Security patches are rolled out every week / month.

Yes you are partially right. With the .ISO image, basic setup is done on the latest Linux Mint (v20) which will lost many years. And one can easily update OSPOS with commands or copy/paste new files. 

> But I guess it's fine for the purpose of running this in a virtual machine or the like.

Yes one can test it in VM but my intention was to use it on physical system.

> I think the docker cloud setup (one click deploy) at the time came sort of close to this one.

Docker are very good but difficult to setup & they are for technical peoples (mainly programmers or system admins). ISO images are very commonly in IT guys. Even in Windows world, which is dominating OS on the desktop. 

V1 (POS-OS-1.iso) was downloaded more then 4K around the world and I hope these new images (v1.3 & v2.0) will help many more (non-technical) peoples. I'm trying to create **one more image, RoshanTech ERP OS**, using ERPNext & Ubuntu 20.04.

**Comment by asakpke** [comment]
Do recommend my project on the DistroWatch if you liked it https://distrowatch.com/dwres.php?resource=submit#waiting
![DistroWatch_Recommend](https://user-images.githubusercontent.com/7318102/88446585-b64fc300-ce44-11ea-8a4d-4fbef0eb62da.png)
