### ISSUE TITLE
Docker deploy does not fetch the latest master correctly

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2907]
Yesterday I tried to validate latest master and observed the following behavior

The deploy was switched back to the master branch (as a push was done there which triggered the scripts). Despite this the version deployed did not seem to be the same hash as the last commit on master. 

* I removed the docker image for jekkos/opensourcepos to make sure nothing remained in cache. This is also what the deploy script does every time it is triggered.
* Forcing a pull on the jekkos/opensourcepos:master seems to yield the same digest as the one for master on docker hub
* Doing a `docker run -ti jekkos/opensourcepos:master` on demo then shows we are not dealing with that last commit
* Doing the same commands locally on my laptop do show me the correct results. The digest after the pull locally is the same as the one after the pull on the demo server. Files in the containers reflect those in the last commit on master.

I'm a bit baffled as I tried to clear all docker state on the server but the behavior persists. For some reason it keeps running an older image version for the master branch. If we push to feature branches then deploys seem to work fine.

**Comment by jekkos** [comment]
I'd like to have latest master on demo before I push the release button. If I can't find the root cause here I might push a tag named 3.3.2 and deploy that one instead.

**Comment by jekkos** [comment]
https://stackoverflow.com/questions/39352186/update-a-docker-image-in-registry

this could be a solution... gonna try quickly

**Comment by jekkos** [comment]
So let's see if `2324471e7ce3f24ced643d9dbaf231522c32d1e` is deployed on demo now

**Comment by odiea** [comment]
The demo server still shows that it is 5a638a

**Comment by jekkos** [comment]
Ok I have changed the deploy script to remove the container tagged with the branch name instead now.. I guess that might solve it (waiting for redeploy)

**Comment by jekkos** [comment]
@odiea I think that hash is fine as the last image probably was not pushed (due to the -f flag not existing on the command). I have reverted this and now it should deploy `b8bfe2239e336793d21dddecfb40362a9529d785`

**Comment by jekkos** [comment]
![Screenshot from 2020-09-02 09-42-45](https://user-images.githubusercontent.com/576234/91950581-b6bf6180-ed00-11ea-8d94-94139dcd732d.png)

**Comment by jekkos** [comment]
Looks good now to me...
