### ISSUE TITLE
Items Table in view not updated when attribute is deleted

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2911]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Installation Info: 3.3.2 - d9ec9c
Language Code: en-US

OSPOS Timezone is Different from your Local Timezone.

Local Timezone:
Asia/Baku

OSPOS Timezone:
America/New_York

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Firefox
.Server Software: Server
.PHP Version: 7.4.8
.DB Version: 8.0.21
.Server Port: 443
.OS: FreeBSD 11.3-RELEASE-p11

File Permissions:
» [application/logs:] - 0770 | Writable ✓ | Vulnerable ✗	
» [public/uploads:] - 0774 | Writable ✓ | Vulnerable ✗	
» [public/uploads/item_pics:] - 0774 | Writable ✓ | Vulnerable ✗	
» [import_customers.csv:] - 0640 | Readable ✓ | Security Check Passed ✓

There are problems with file permissions please fix and reload this page.

Security Vulnerability Warning
Permissions higher than 750 leaves this software at risk.

» [application/logs:] is writable, but the permissions are higher than 750.
» [public/uploads:] is writable, but the permissions are higher than 750.
» [public/uploads/item_pics:] is writable, but the permissions are higher than 750.	
Asia/Baku

### Bug

If you edit an item and delete an attribute, it successfully deletes but the attribute is still visible in the table until you refresh the screen, but if you simply modify or add an attribute that has Items visibility, it does get refreshed after clicking submit.

expected behavior is that deleting an attribute with Items visibility would update the table row without needing to hit F5 to refresh the page.  Doing this brings the behavior in consistent with adding and updating attributes.

**Comment by jekkos** [comment]
Ok I'm a bit surprised here.. does this happen after clicking submit? I'd think that hitting the delete button would unlink the attribute and then it should call get_row which will not see that link anymore..

**Comment by odiea** [comment]
The row changes like it was updating but does not remove the Attribute

**Comment by objecttothis** [comment]
> 
> 
> Ok I'm a bit surprised here.. does this happen after clicking submit? I'd think that hitting the delete button would unlink the attribute and then it should call get_row which will not see that link anymore..

It does indeed unlink the attribute, but doesn't refresh the row.  If you click edit again you see that the attribute isn't there.

**Comment by jekkos** [comment]
Had a look here but can't find the direct reason for this glitch. Will postpone this one for the time being.

**Comment by jekkos** [comment]
Should bne fixed now in master
