### ISSUE TITLE
Receipts not printing at all

### ISSUE THREAD

**Issue by alexmzirai** [opensourcepos/opensourcepos#2913]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: c786d4
- PHP version is: 7
- MySQL or MariaDB version is: 5
- OS and version is: Ubuntu 18.04
- WebServer is: Apache2
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue 
Hi guys, I am trying to print receipts from sales, and I have a thermal receipt printer (80mm E-POS 300 printer).

I also cannot access the Ticket Printer, Receipt Printer, and Invoice Printer settings, which are disabled.

When I print out a receipt, the paper is blank, and the receipt size is about one inch (length) by 80mm (width) in size.

When I test the printer on Windows it prints everything correctly, so I'm leaning on this being an issue with ospos.

Is this a margin issue in ospos? The client is accessing the installation via Chrome browser, which doesn't show anything on receipt printing. Microsoft Edge shows the error "unexpected configuration problem OX80040003."

Any advice will be appreciated, as it is an urgent installation.

![Screenshot (347)](https://user-images.githubusercontent.com/28978304/89448182-e27e1480-d75f-11ea-98e3-e6c0f1178248.png)
![Screenshot (348)](https://user-images.githubusercontent.com/28978304/89448195-e742c880-d75f-11ea-98ad-2b7544a70fe7.png)

**Comment by odiea** [comment]
JsPrint does not work anymore under mosr browsers. You can Try using Pale Moon and make changes with that browser and see if anything helps. Good Luck

**Comment by alexmzirai** [comment]
Will it allow me to edit the margins and ticket/receipt/invoice printing options?
Also, why wont Chrome display the receipt correctly in the preview window?

**Comment by alexmzirai** [comment]
In short, why cant I select the receipt printer option?

**Comment by odiea** [comment]
It uses JSPrint and chrome no longer supports it.

**Comment by alexmzirai** [comment]
Okay, so I should use Pale Moon....any guide for making the necessary changes in pale moon I can follow?

**Comment by odiea** [comment]
Firefox does not support it either. Just some Firefox clones still do like Palemoon
.

**Comment by odiea** [comment]
The allowed changes are in the Store config file I believe under Receipt.

**Comment by odiea** [comment]
Or check your printer support and maybe they have some suggestions

**Comment by alexmzirai** [comment]
Thanks. Yes the changes I need to make are in the Receipt tab...but they're grayed out...I cant access them.

**Comment by odiea** [comment]
Are you in Pale Moon?

**Comment by alexmzirai** [comment]
Installing it now...

**Comment by odiea** [comment]
Also check the previous issues those may help

**Comment by alexmzirai** [comment]
The previous issues with receipt printing and the receipt options not accessible were not answered sufficiently...they were closed abruptly.

**Comment by odiea** [comment]
Sorry. That's as much as I can help.

**Comment by odiea** [comment]
I also assume that you have the printer setup via its supplier software

**Comment by alexmzirai** [comment]
I understand that...i'm asking for a workaround to this problem. 
How are you guys running ospos? 
The installation is pretty useless if I cant print receipts.

**Comment by alexmzirai** [comment]
Yes the printer came with its driver and everything and it prints other things fine. But not OSPOS receipts.

**Comment by alexmzirai** [comment]
I've tried on palemoon and still cant access the receipt options that are grayed out

**Comment by odiea** [comment]
I am using Pale moon version 28.10 and I do not have any issues accessing the printer config page for Receipts.

**Comment by odiea** [comment]
Are you using the printer files for Linux?

**Comment by odiea** [comment]
On the supplied info it shows that you are using Ubuntu.

**Comment by alexmzirai** [comment]
No, I have installed the drivers on the windows client where the printer is connected. I have installed ospos on an Ubuntu VPS and access it via an IP.

**Comment by odiea** [comment]
And where are you trying to set this up? At the clients computer or the Ubuntu Server?

**Comment by alexmzirai** [comment]
The printer is connected to the client computer that I use to access the ospos installation. So since the printer is local, I only installed its drivers locally. Do i need to set up the drivers on the vps? I dont understand why that's necessary...

**Comment by odiea** [comment]
I have no idea. Does a standard printer work?

**Comment by alexmzirai** [comment]
I havent tried printing other docs from the vps. But this shouldnt be an issue since I only need to print receipts from ospos

**Comment by alexmzirai** [comment]
![Screenshot (349)](https://user-images.githubusercontent.com/28978304/89457336-e4e76b00-d76d-11ea-93b1-dfc30b2bb309.png)
this is the receipt tab options in Pale Moon 28.12. Still cant access the receipt options.

**Comment by odiea** [comment]
You will need to try Pale moon again and see if you can access the receipt config. I just tried on someone else server and my printer worked after resetting the selected printer

**Comment by odiea** [comment]
This is what I see. You can try ctrl f5 to refresh it 

![2020-08-05 13_54_43-Window](https://user-images.githubusercontent.com/10962177/89457871-5221de80-d723-11ea-9525-47bae0d54ddc.png)

**Comment by alexmzirai** [comment]
Yes I've refreshed the tab a number of times. I've run out of ideas on what could be the problem

**Comment by odiea** [comment]
As a last resort you could try installing the program on the local terminal and have the database set to your server.

**Comment by alexmzirai** [comment]
hmmm...I can try that....but that would mean that the client wouldn't be able to access the pos from anywhere...which is what he wants most.

**Comment by odiea** [comment]
Can you access it from your location and try to see if it does work?

**Comment by odiea** [comment]
It also may be a question that you can ask your vpn people

**Comment by odiea** [comment]
Is it set as the default printer? Can he print barcodes?

**Comment by alexmzirai** [comment]
Yes it  can print barcodes just fine. And I can access it from my lcoation too. The only problem is that it is not printing receipts.

**Comment by odiea** [comment]
Can you reprint a receipt from your location?

**Comment by odiea** [comment]
Can you access the site without going thru the VPN?

**Comment by alexmzirai** [comment]
I dont need to use a VPN to access the site...

**Comment by alexmzirai** [comment]
It's freely available via the vps IP

**Comment by odiea** [comment]
Sorry I thought it stated vpn not vps.

**Comment by alexmzirai** [comment]
No, I'm running Ubuntu in a VPS.

**Comment by odiea** [comment]
Does the windows print screen show after you press print? And then select the printer

**Comment by alexmzirai** [comment]
It does, and after I select the printer and click "print" all I get is an empty screen. The receipt is not displaying properly on the screen...forcing me to "fit-to-screen." After this, the printer generates an empty receipt about a quarter of the size of a regular receipt.

**Comment by odiea** [comment]
what happens if you don't fit-to-screen?

**Comment by alexmzirai** [comment]
Same output....empty receipt. I've wasted a large amount of receipt paper debugging this issue, lmao.
If I can't fix it by tomorrow I'll set up ERPNext on the VPS and apologize to the client for going past the deadline.

**Comment by odiea** [comment]
Sorry to hear that. The only other suggestion would be trying a different printer. Maybe a laser printer for testing

**Comment by odiea** [comment]
I have just never had it not print a receipt.

**Comment by alexmzirai** [comment]
Btw, is the E-POS 300 thermal printer compatible with os-pos?

**Comment by alexmzirai** [comment]
That's the printer I'm using for this setup

**Comment by odiea** [comment]
No idea. We do not get any feedback on printers unfortunately.

**Comment by odiea** [comment]
The following is from the WIKI.
Device Printing Support
The recommend receipt is the Star TSP 100 ECO using the Firefox or Chrome browsers, with this if there's no fiscal kit, we can print directly. Our recommended label printer is the Zebra LP 2824 Plus printer with 2 x 1 labels. Other customers have had success with other printers from companies. If you plan to purchase a different receipt printer than the recommend, try to get one that prints on paper that is 72 mm or greater.

Obviously prints depends of the browser, so must be first configure here, and then in ospos the printing configuration has some options, only enable with some changes over the browser. For the Zebra its recommended also search at https://www.peninsula-group.com/mac-thermal-printer-driver/ the CUPS interface for Unixes comes with basic enough support that works as its.

**Comment by WebShells** [comment]
@alexmzirai yes E-POS 300, class c copy of epson receipt pronters is compatible with OSPOS setup.
Mostly most of the receipt Printers are compatible yet we do recommend specific brands that will be listed on our website and ready to be shipped worldwide soon.

**Comment by odiea** [comment]
I see from some info that USB is optional. How is it installed.?
Technical Specifications
Printing method: Direct Thermal Printing
Printing Width: 72mm or 64mm
Print Resolution: 203dpi
Printing Speed: 300mm/s
Paper Speed Width: 79.5 0.5mm
Paper Loading: Easy paper loading
Printer Head: 100km
Auto Cutter: 2.5 Million Cuts
Interface: USB + Serial + Ethernet (Standard) Parallel + USB (Optional)
Compatible with EPSON ESC/POS command sets
Certificate: FCC, CE, 3C

**Comment by daN4cat** [comment]
The printer problem has nothing to do with ospos.

Trying printing to a pdf and see what you get. Printing to pdf is something will save you paper and understand how to configure your printer on your os and Web browser.

**Comment by odiea** [comment]
Must have moved on to a different program.
