### ISSUE TITLE
Weblate down for maintenance / upgrade

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2914]
Currently I'm in the process of upgrading weblate to the latest version. Bear with me.

**Comment by jekkos** [comment]
Ok I have version 4.1 running now. The database migration failed again so I had to start over with a fresh cleean database. Luckily I was able to recover some SQL from last time to migrate all users to the new schema. 

Following still needs to be done

* Enable github login again. Currently it sends a redirect_uri for example.com for some reason.
* Import the git project and then the translations

**Comment by daN4cat** [comment]
Redirect should be GitHub to website after the authentication is done by GitHub.
Is GitHub containing the correct return URL?

**Comment by jekkos** [comment]
Yes I think the issue is that the django server does not know what domain it should redirect oauth requests to (it's set to example.com now which obviously is not what is configured and authorized in github)

**Comment by daN4cat** [comment]
Just wondering, nothing to do with nginx reverse proxy, right? Like some x-forward or similar. I have vague memory that once for Grafana authentication running on Kubernetes I needed to enable something on nginx ingress.

**Comment by jekkos** [comment]
I think I have it figured now. Indeed some settings had to be done in the nginx reverse proxy (a reverse_pass and x-forwarded-for). But the issue was that the url generated used the wrong base domain. This setting was in the database (not in the settings file) and not obvious to find in the weblate docs. 

It's fixed now and the login works again. However I still need to migrate a couple of extra tables to finish the setup.. A bit of a pain but ok.

**Comment by daN4cat** [comment]
Weird setup. Worth reporting the bug so they fix and add it to a clear configuration setup.

**Comment by daN4cat** [comment]
Right, it's not a stable release. Unless it's really vital for a reason I would stay clear of unstable dev releases. But that's my personal view of course.

**Comment by jekkos** [comment]
You certanily have a point there. I guess it's a better idea to grab one of their stable releases instead.

**Comment by jekkos** [comment]
After a couple hours of work I decided to drop the initial users as it was too much of a pain to migrate. I did switch to the stable branch now so hopefully next time I can just run their migrations without further ado.

The latest 4.2.2 is live now and I pushed some translations in flemish that i have updated. I kind of like the way it works now, you can add your translation and have different kinds of context like nearby keys, translations in other languages, and more machinery to aid you to translate a string in the most accurate way possible.

So only downside now is that I don't have the original user table in there and all users will need to recreate their accounts. Luckily this is straightforward now if you use github oauth.

**Comment by jekkos** [comment]
Ok I have done some shell scripting and and sent a a 'call for translations' to all former weblate users. Let's wait a bit more and see if we can have some improved languages before releasing 3.3.3.
