### ISSUE TITLE
Not able to modify item quantity manually afer suspending sale

### ISSUE THREAD

**Issue by Saiuke** [opensourcepos/opensourcepos#2916]
### Background information

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Version is 3.3.1

.Browser: Firefox
.Server Software: Apache/2.4.23 (Win64) PHP/7.0.10
.PHP Version: 7.0.10
.DB Version: 5.7.14
.Server Port: 80
.OS: Windows Windows 10
.Running on local server Wamp

File Permissions:

» [application/logs:] - 0777 | Writable ✓
» [public/uploads:] - 0777 | Writable ✓
» [public/uploads/item_pics:] - 0777 | Writable ✓
» [import_customers.csv:] - 0666 | Writable ✓ 

- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

Bug

On the Sales panel, if I suspend a certain sale, then recover it (unsuspend) I'm not able to edit the Items quantity, when I try do do so I get an error "Error editando articulo" (Error while editing item). The same bug occurred even when the sale wasn't suspended before, but I could not reproduce the error with consistency.

I have admin privilegies and the item in question does not have Serial Number.
Before suspending the sale I can change the item quantity normally.
I just finished updateding the system and noticed this.
If I search for the cited item and then click on it I have one added to the quantity.
I'm getting a warning of low inventory even if the selling quantity is way below the actual inventory.

![Captura de tela 2020-08-10 15 36 13](https://user-images.githubusercontent.com/19313767/89828873-4bc6a480-db1f-11ea-918a-2e9b248b714c.png)

**Comment by SteveIreland** [comment]
3.3.1 has been out for awhile and I don't recall this issue being reported before.  Have you been running 3.3.1 and it just suddenly started happening or is this the first time you've ever unsuspended an order and then tried to modify it?  Also, did you happen to upgrade some component of wampserver about the same time the issue started.

I'll try to replicate it tonight.

**Comment by SteveIreland** [comment]
Sorry @Saiuke.   I installed 3.3.1 and was not able to replicate your issue.  I'll keep an eye out for a few days to see if you respond to any of my earlier questions.

**Comment by SteveIreland** [comment]
The complainant must have moved on.  Closing this issue.
