### ISSUE TITLE
Not able to backup database using option on Settings

### ISSUE THREAD

**Issue by Saiuke** [opensourcepos/opensourcepos#2917]
### Background information

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Version is 3.2 - 4f5ad57

.Browser: Firefox
.Server Software: Apache/2.4.23 (Win64) PHP/7.0.10
.PHP Version: 7.0.10
.DB Version: 5.7.14
.Server Port: 80
.OS: Windows Windows 10
.Running on local server Wamp

File Permissions:

» [application/logs:] - 0777 | Writable ✓
» [public/uploads:] - 0777 | Writable ✓
» [public/uploads/item_pics:] - 0777 | Writable ✓
» [import_customers.csv:] - 0666 | Writable ✓ 

- (If applicable) Installation package for the LAMP/LEMP stack is:  WAMP

Bug

The funcion database backup option in Settings -> General returned me this:

![Captura de tela 2020-08-10 18 53 10](https://user-images.githubusercontent.com/19313767/89842394-17f97800-db3b-11ea-8cac-d079fd9063fb.png)

I still did not tweak with the code trying to solve it.

**Comment by daN4cat** [comment]
You need to increase your php memory in php.ini
