### ISSUE TITLE
Cannot Delete Receiving if item has Attribute

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2918]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Installation Info: 3.3.2 - cb67b5
Language Code: en-US

OSPOS Timezone is Different from your Local Timezone.

Local Timezone:
Asia/Baku

OSPOS Timezone:
America/New_York

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Firefox
.Server Software: Server
.PHP Version: 7.4.8
.DB Version: 8.0.21
.Server Port: 443
.OS: FreeBSD 11.3-RELEASE-p11

File Permissions:
» [application/logs:] - 0770 | Writable ✓ | Vulnerable ✗	
» [public/uploads:] - 0774 | Writable ✓ | Vulnerable ✗	
» [public/uploads/item_pics:] - 0774 | Writable ✓ | Vulnerable ✗	
» [import_customers.csv:] - 0640 | Readable ✓ | Security Check Passed ✓

There are problems with file permissions please fix and reload this page.

Security Vulnerability Warning
Permissions higher than 750 for write and 660 for read leaves this software at risk.

» [application/logs:] is writable, but the permissions are higher than 750.
» [public/uploads:] is writable, but the permissions are higher than 750.
» [public/uploads/item_pics:] is writable, but the permissions are higher than 750.	
Asia/Baku

### Bug
If an item has one or more attributes defined and you do a receiving, that receiving cannot be deleted.

Steps to Reproduce:
- Create an item
- Add an attribute
- Complete a receiving for that attribute
- Go to Reports->Detailed Reports->Receivings
- Choose the default date range and click submit.
- Edit the receiving you just completed then click Delete and confirm.

Error: "Receiving(s) delete failed."
The error log reads: 
```
Query error: Cannot delete or update a parent row: a foreign key constraint fails (`pos_longtext`.`ospos_attribute_links`, CONSTRAINT `ospos_attribute_links_ibfk_4` FOREIGN KEY (`receiving_id`) REFERENCES `ospos_receivings` (`receiving_id`)) - Invalid query: DELETE FROM `ospos_receivings`
WHERE `receiving_id` = '2'
```

This is being caused by a foreign key constraint on the receiving_id.  The constraint is behaving as designed, however it seems unreasonable to not be able to delete a receiving if there is an attribute on an item.  I'm not sure I understand the purpose of having the sale_id and receiving_id columns in the attribute_links table.  Perhaps it's to keep a record of what attributes that item had at the time of sale or time of receiving?

If, however, there is a good reason for us not to be able to delete a receiving if an item in the receiving has an attribute assigned to it, then we should probably catch the error log error and return a toast notification with a more detailed error message that explained why the delete is unsuccessful.

@jekkos @daN4cat thoughts?  I can probably do the legwork if any changes need to be made, but I need to know how it ought to behave.

**Comment by jekkos** [comment]
Didn't I setup cascading deletes for the attribute link foreign key? If not then adding that will probably solve the issue. If we delete a receiving it can just delete everything linked to it in this case. 

Another option is to add a deleted flag to the receivings table and soft delete it instead. I guess it's probably more consistent and correct (as it's done for sales this way as well). Adding a deleted flag allows for a better tracability but will probably also introduce other bugs. So maybe we can fix this by adding the cascade and then add a story for the soft delete.

**Comment by objecttothis** [comment]
@jekkos yes, changing the foreign key constraint from ON DELETE RESTRICT to ON DELETE CASCADE resolves the problem, however you are correct that it makes the delete un-traceable and unrestorable.  However, I do not think that there currently is a mechanism to trace or restore attributes in receivings.  If I understand correctly, you've placed the receiving_id and sale_id columns in the attribute_links table precisely for tracing attached attribute_links rows to receivings and sales even if the current attribute_link is connected to a different attribute_id field.

My application doesn't have significant need for soft deletes in the attributes to preserve attribute - receiving/sale traceabillity, but I'm sure other's does.  My personal preference on this matter is that we write a patch migration script to change that foreign key to allow cascading deletes and then once someone wants to fully implement soft deleting we can turn it back on.  I can write the script, but I'll wait to hear what you want to do.

**Comment by jekkos** [comment]
Yes I agree, let's patch it this way for now, and then maybe we can add the soft deletes later on (however I'm not sure if it will be a lot of extra work, it might be a matter of changing the model queries only to take into account the deleted flag). I guess most of the complexity with soft delete is in the sales / items models where you have some constraints on invoice number generation that might break as the application is not seeing the deleted data..

**Comment by jekkos** [comment]
As this should be an easy fix I thought I'd add this one more before I (finally) press that release button.

**Comment by objecttothis** [comment]
#2927 submitted.  It needs a code review and merge.  Should be pretty straight forward.
