### ISSUE TITLE
Blank page after Local deploy in Manjaro

### ISSUE THREAD

**Issue by shankar58989** [opensourcepos/opensourcepos#2929]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0 (downloaded through local deploy wget command)
- OSPOS git commit hash is: 
- PHP version is: 7.4.9
- MySQL or MariaDB version is: 10.4.14-MariaDB
- OS and version is: Manjaro 20.1
- WebServer is: apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Question

Hello,
I am trying to install OSPOS on Manjaro using Local Deploy method. I have created a sub directory inside the root directory (srv/http/1).
* i have enabled rewrite mod in apache config file (etc/httpd/httpd.conf)
* i have un commented the sub directory in the .htaccess
I have attached both files for reference.

localhost/1/public results in a blank page. Please help me solve this issue. Thank you.

[httpd.conf.txt](https://github.com/opensourcepos/opensourcepos/files/5098795/httpd.conf.txt)
[htaccess.txt](https://github.com/opensourcepos/opensourcepos/files/5098797/htaccess.txt)

**Comment by daN4cat** [comment]
Not sure we ever tested with PHP 7.4.9.

**Comment by shankar58989** [comment]
> Not sure we ever tested with PHP 7.4.9.

please suggest which version of php shall i install and try. Also if possible please have a look at my httpd.conf and .htaccess files and let me know if i have made any mistakes there.

**Comment by jekkos** [comment]
seeing a blank page is probably a php error, try to enable error logging in the app to see what is going on. Could be just a wrong db config (but you won't know as it's not showing you anythin)

**Comment by shankar58989** [comment]
> seeing a blank page is probably a php error, try to enable error logging in the app to see what is going on. Could be just a wrong db config (but you won't know as it's not showing you anythin)

can you point me to where i should turn on error logging? should i turn all the error reporting stuff on in the php.ini file?

**Comment by shankar58989** [comment]
Please suggest me which version of php is recommended? i will try to reinstall the php. In the minimum requirements in wiki page it says 5.6+ so i thought installing the latest php would not be a problem.

**Comment by shankar58989** [comment]
I am thinking of giving the docker method a try. Is it possible to have multiple instances of OSPOS via the docker method like the sub folders in the LAMP stack method?

**Comment by odiea** [comment]
Try 7.2 php and see if that changes anything.

**Comment by odiea** [comment]
No feed back after 2 weeks so I will close this issue
