### ISSUE TITLE
Error 404 The request to url www.mysite.com/ospos/ redirects to www.mysite.com/public

### ISSUE THREAD

**Issue by van087** [opensourcepos/opensourcepos#2932]
### Installation information

- OSPOS version is: 3.3.1
- PHP version is: 7.3.13
- MySQL version is: 5.6.44-86.0
- OS and version is: CentOS 7
- WebServer is:  Apache 2.4

### Issue / Bug  / Question / New Feature

I state that I have read the post
https://github.com/opensourcepos/opensourcepos/issues/920
https://github.com/opensourcepos/opensourcepos/issues/1491

but i still couldn't figure out how to fix it.

I have a wordpress installation in the root of my server, so I have
copied all opensourcepos files into a new directory named "ospos"
If I try to access the link
www.mysite.com/ospos/
I am redirected to
www.mysite.com/public
with 404 error

To access the ospos installation I have to go to
www.mysite.com/ospos/public
only in this way everything works correctly.

Maybe there is some instruction in the htaccess.txt file of the ospos root folder
which does not redirect correctly.

attached the 3 .htacces files

[.htaccess.txt_wordpress.txt](https://github.com/opensourcepos/opensourcepos/files/5114163/default.htaccess.txt_wordpress.txt)
[.htaccess.txt_directory_ospos.txt](https://github.com/opensourcepos/opensourcepos/files/5114165/default.htaccess.txt_directory_ospos.txt)
[.htaccess.txt_directory_ospos_public.txt](https://github.com/opensourcepos/opensourcepos/files/5114166/default.htaccess.txt_directory_ospos_public.txt)

**Comment by daN4cat** [comment]
It should be .htaccess not .htaccess.txt, I assume you didn't change the file extension.

**Comment by van087** [comment]
The 3 files on the server are .htaccess

To understand the difference between the 3 I have attached them in .txt
