### ISSUE TITLE
Gift card value can be set as negative value

### ISSUE THREAD

**Issue by bobby-lin** [opensourcepos/opensourcepos#2935]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: Ubuntu
- WebServer is: nginx/1.14.0
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

There is a business logic issue where the Gift card value can be set as negative value.

First, add a new Gift card and enter negative value.
![image](https://user-images.githubusercontent.com/12782269/91653064-92307300-eacf-11ea-930b-7231dee06959.png)

After the gift card is added, we can see that the gift card contains negative value.
![image](https://user-images.githubusercontent.com/12782269/91653090-e6d3ee00-eacf-11ea-8797-34ad502841ff.png)

To fix the issue, the application will need to validate that Gift card value should not be negative.

**Comment by jekkos** [comment]
I suppose we should check / validate this, but I can't really imagine someone entering a negative amount by accident? 
And even then, you might not be able to pay with that giftcard after all( so no harm done there)?

**Comment by bobby-lin** [comment]
Hi @jekkos , I agree that the bug has low security impact. 

At some time, hope the team can fix the negative amount.

**Comment by jekkos** [comment]
Fix is now in master.
