### ISSUE TITLE
Travis-CI build failure

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#2937]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Issue
@jekkos, any ideas why Travis-CI build is failing?  According to the build history it's been failing for the last 5 days https://travis-ci.org/github/opensourcepos/opensourcepos/builds
```
Building ospos
Step 1/25 : FROM php:7.3-apache AS ospos
Service 'ospos' failed to build: Error parsing reference: "php:7.3-apache AS ospos" is not a valid repository/tag: invalid reference format
The command "docker-compose build" exited with 1.
11.12s$ docker-compose -f docker-compose.test.yml up --abort-on-container-exit
Creating network "opensourcepos_default" with the default driver
Pulling mysql (mariadb:10.3)...
10.3: Pulling from library/mariadb
Digest: sha256:3f823c604d029630ea04f46d7069ffad97fbf78f965ac44141c2e43185cb8303
Status: Downloaded newer image for mariadb:10.3
Building test
Step 1/25 : FROM php:7.3-apache AS ospos
Service 'test' failed to build: Error parsing reference: "php:7.3-apache AS ospos" is not a valid repository/tag: invalid reference format
The command "docker-compose -f docker-compose.test.yml up --abort-on-container-exit" exited with 1.
```

**Comment by jekkos** [comment]
It seems to be related to the travis setup. I removed the group tag and now it seems to be running with docker version 18 which should in fact support multistage builds.

**Comment by jekkos** [comment]
Ok it's green again. I'll close.
