### ISSUE TITLE
The latest Release is missing the compiled zips

### ISSUE THREAD

**Issue by JamesSwift** [opensourcepos/opensourcepos#2941]
https://github.com/opensourcepos/opensourcepos/releases/tag/3.3.2 references opensourcepos.20191214181241.3.3.1.c786d4.zip but it is not attached.

**Comment by JamesSwift** [comment]
Thank you kindly

**Comment by daN4cat** [comment]
@jekkos the release note contained a wrong file name. Not sure whether you fixed that too?

**Comment by daN4cat** [comment]
It seems fixed.
