### ISSUE TITLE
Bump version to 3.4.0

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2942]
If no blocking bug reports arrive, I'd bump versions to 3.4.0

(-) Bump composer file
(-) Bump package.json file
(-) Check Changelog if it contains all notes from the release page
(-) Bump bower file
(-) Bump deployment.json

**Comment by jekkos** [comment]
I forgot about deployment.json. @daN4cat also suggested to release a 3.3.3 with permission fix and perhaps the docker files included in the zip, so maybe I should do a minor bump first.

**Comment by SteveIreland** [comment]
It would be nice to include the tax calculation fix #2950 in 3.3.3 if possible.

**Comment by odiea** [comment]
@jekkos Please throw @SteveIreland a bone and include his fix. Thanks

**Comment by daN4cat** [comment]
There are a couple of things I should find the time to fix.
Not sure how they managed to do but in my wife's shop they messed up a couple of things requiring me to manually fix in the database. All my plan was to do not do that anymore... :-(

**Comment by jekkos** [comment]
Good to release 3.3.3? Any objections?

**Comment by jekkos** [comment]
Ok Let's wait for this one bugfix before I release this one.

**Comment by jekkos** [comment]
@daN4cat always funny to see an increased amount of bugreports after we do a release. I guess you can never catch 'em all but doing a second minor one after certainly makes sense.

**Comment by jekkos** [comment]
Not a lot of extra activity on weblate, despite my email campaign... So let's just try to tackle these incoming bug reports and then release 3.3.3 after fixing those. @daN4cat you spoke about some fixes you wanted to include? Is it relevant to have those for 3.3.3? Thanks!

**Comment by daN4cat** [comment]
Let me look into that over the weekend if I find the time.
If not release 3.3.3 and I'll contribute any additional fix in 3.4.0.
Also I want work on a replacement of Mailchimp with Shopify. 
Shopify integration would be handy also to control stock quantities between online and physical shop.
At the moment my wife's employees need to manually adjust quantities.

**Comment by daN4cat** [comment]
When I say Mailchimp replacement with Shopify is to use Shopify for email marketing campaigns now that they have that feature instead of Mailchimp. 
It's a cost reduction story.

**Comment by jekkos** [comment]
Ok so that increases the priority on fleshing out this eventsauce thingy and have @objecttothis work merged into 3.4 master first.

**Comment by objecttothis** [comment]
I recommend that we merge #2821 before #2619 (or the replacement for #2619 with eventsauce)

**Comment by jekkos** [comment]
OK let's first merge the two outstanding fixes I have done before 3.3.3

**Comment by jekkos** [comment]
@opensourcepos/org 
I wanted to bump to 3.4 but was wondering whether we should not make a more clear distinction between stable and unstable.

In this case I would propose to bump to either

* 3.4.0-dev 
* 3.4.0-unstable

until we release the actual version to make it clear that the version built is an unstable one. Any ideas or suggestions on this one? My preference goes with the first option here.

**Comment by SteveIreland** [comment]
Is anything in life truly stable?

I propose 3.4.0-reasonably-stable-but-check-issues-for-know-bugs.

**Comment by jekkos** [comment]
Well I'd take stable for no `known-bugs-for-this-milestone-at-the-time-it-was-released`

**Comment by objecttothis** [comment]
We could shorten it to 3.4.0-stable-ish

**Comment by objecttothis** [comment]
In all seriousness if I were doing it I would use -beta but I don't feel strongly about it. -dev is fine.

**Comment by jekkos** [comment]
Ok `-dev` it is
