### ISSUE TITLE
detailed_receivings report

### ISSUE THREAD

**Issue by blutme** [opensourcepos/opensourcepos#2947]
- OSPOS version is: 3.3.2
- OSPOS git commit hash is:  bb309c.
- PHP version is: 7.3
- MySQL or MariaDB version is: MariaDB
- OS and version is: Raspbian
- WebServer is: Nginx
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

I use “Receivings module” and received a single product and finish register then I review the detailed report I can see it without any problem. But when I do a reception on “Receivings module”  of several products and different quantities in a single entry record and finish the operation, then I review the detailed report it only shows me the first product that enters the reception but not the others. But I thing tha the Receivingn module is working ok because in the “inventory Count Detail” I can see the inventory data tracking like “RECV X” if it is ok. 

Example:

Receiving Mode: Receive | Stock source : PSDP
Find or Scan Item :
Delete	Item #	Item Name	Cost	Qty.	Ship Pack	Discount	Total	Update
	123	BREAD  [70 in PSDP] 	225 1		x1	4	$ 900	
	323	MEAT [10 in PSDP] 	225 1		x1	5	$ 1125	
	523	COFFE [30 in PSDP] 	225 1		x1	7	$ 1575

									DELETE 	√ FINISH
-----------------------------------------------------------------------------------------------------
Detailed Receivings Report
			             		09/09/2020 - 09/09/2020

Receiving ID	Date	Quantity	Received By	Supplied by	Total Payment Type….
- 1	09/09/2020	0	Blutme Pos		$ XXXX

Barcode	Name	Category	Quantity	Total	Discount
123	BREAD  [70 in PSDP] 	225 1		x1	4	$ 900

**Comment by odiea** [comment]
Please test this out using the online Demo Server and see if the same issue shows.

**Comment by blutme** [comment]
I did  that yesterday and in the demo it does not generate this problem.

**Comment by odiea** [comment]
You can look in the following issues to see if maybe yours is covered.
https://github.com/opensourcepos/opensourcepos/search?p=1&q=raspberry&type=Issues

**Comment by blutme** [comment]
I can't find any information related to my problem.
I carefully review the database but there is no alteration on it that prevents the query. Unfortunately I don't have much knowledge of PHP and it is difficult for me to identify how the query is performed.
maybe, Does it have something to do with the fact that the database is mariadb and not mysql? 
Thanks for your help.

**Comment by andriux1990** [comment]
Hello I use mariadb all the time..just reviewed and it works as it should
