### ISSUE TITLE
about Permission of files after upgraded from 3.3.1 to 3.3.2

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#2951]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.2.33
- MySQL or MariaDB version is: 10.0.38-MariaDB-cll-lve
- OS and version is: Linux 3.10.0-962.3.2.lve1.5.28.el7.x86_64
- WebServer is: Apache
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

i just ask, i changed the requirements of files perm. and all working, but i stilll receiving this msg, see the perm of my files.

![issues_v3 3 2_migration](https://user-images.githubusercontent.com/6296036/93043570-37932d00-f620-11ea-9345-ca0d31ad5cfc.jpg)

**Comment by jekkos** [comment]
I have spotted the same behavior indeed. @WebShells as discussed before (not sure if you know where the discussion is) there stil is some incosistency in how the permissions are evaluated (due to checking on decimal values instead of using the bitwise mask).

If you still have the reference to the original PR then maybe add it here.

**Comment by WebShells** [comment]
How can i regenerate the issue? Change permissions after upgrade?

**Comment by odiea** [comment]
The current Demo displays this also

**Comment by jekkos** [comment]
I think the discussion in #2885 describes the issue here.. we didn't create an issue for it but @ekardian has done this instead now.

**Comment by daN4cat** [comment]
Maybe there should be a quick 3.3.3 release before moving to 3.4.0?

**Comment by ekardian** [comment]
> 
> 
> How can i regenerate the issue? Change permissions after upgrade?

i changed with the suggested changes, like 750, 744, but reading the issues.. is like @jekkos said there in [#2885 ](url) , but all is working, sorry for my later answer, covid ********

**Comment by ekardian** [comment]
wellp guys.. i was changing the file perm, for generate other things , see the msg now
note. i was thinking? is not the language translation? u know? who know? XD

![issues_v3 3 2_migration_21](https://user-images.githubusercontent.com/6296036/93416907-c26c6580-f874-11ea-9b15-6ab9095ae79e.jpg)

**Comment by jekkos** [comment]
I know even if you have everything configured correctly there is some wrong reporting. It's kind of confusing and I think it should be fixed (as otherwise we'll get more worried users weighing in here). @WebShells any chance to take a look at this one?

**Comment by WebShells** [comment]
@jekkos will try to cover today, it shouldn't be an issue except if i want to change the way we are checking the file permissions.
Will try to get it done tonight.

**Comment by WebShells** [comment]
PR submitted pending revision and we are ready to go

**Comment by WebShells** [comment]
Merged into master

**Comment by jekkos** [comment]
Did a quick test today on latst

**Comment by daN4cat** [comment]
I noticed that the company logo will not display in the config and receipts if the folder is set as per suggestion. Is that only my deployment issue?

**Comment by jekkos** [comment]
I was checking this one as well today, I still see these warning even after setting all permissions correctly. But then I realized I'm not on the correct version. The logo seems fine here though.

**Comment by jekkos** [comment]
There might still be one unnecessary message in the green case. I do sort of like these self test features. 

![Screenshot from 2020-10-20 16-41-15](https://user-images.githubusercontent.com/576234/96602287-25796e00-12f3-11eb-
94d1-7f46f1d2ba06.png)

**Comment by ekardian** [comment]
> 
> 
> I noticed that the company logo will not display in the config and receipts if the folder is set as per suggestion. Is that only my deployment issue?

this happened to me in the first test

**Comment by daN4cat** [comment]
Thanks, I'm not the only one.

**Comment by jekkos** [comment]
Ok the messages do seem ok to me. I have done a quick test by uploading a logo on a correctly setup install (dockerized) and the uploaded files are readable after.

**Comment by jekkos** [comment]
@daN4cat can you check the process owner vs the file / folder permissions? In this case I guess the files inside the upload folder should be at least readable for the process owner.

**Comment by jekkos** [comment]
I think an easy way to see which user is currently running is to create a file in a temp folder then check the owner. Next to that the code here feels a little hard to maintain, I don't really think that it is nice to do these permission checks in the view here. 
Some refactoring might be needed to store the list of files to check in an array, filename as key and permissions as value.

Then you can just iterate over them and store the validation result in another array with same index. The view can then just loop over that result array and show the messages added in the validation.

I think it would make it easier to change as adding a check for the owner now requires a coder to make 5 changes while it could be done in one.
