### ISSUE TITLE
[Docker] Builded zip from bintray doesn't contain /docker folder

### ISSUE THREAD

**Issue by DrumSlayers** [opensourcepos/opensourcepos#2953]
##

- OSPOS version is: 3.3.2
- (If applicable) Docker installation:  yes

### Issue

Hi,
I try to configure open source pos via Docker but I'm facing a issue.
I want to follow the steps provided by install.md, but the /docker folder is missing from everywhere except git project, and your install.md mention not to use the git.
So I am stuck here :/

I also tried to use the docker-compose but .env is not provided and there isn't information about the env settings.

Can you help me?
Thank you!
DrumSlayer

**Comment by jekkos** [comment]
Hi @DrumSlayers you might be right, I have checked our build script and have now included the docker/ folder. The build should appear soon on bintray.

**Comment by jekkos** [comment]
@DrumSlayers The [following zip](https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20200917214347.master.301345.zip) should have all the files included. Let me know if you have any further questions.

**Comment by DrumSlayers** [comment]
It does work well, thank you!

**Comment by jekkos** [comment]
Ok indeed this file does not exist on the host before the container starts, so docker might create it as a folder then? 

You suggest that adding an empty file on that location then solves this issue?

**Comment by DrumSlayers** [comment]
> Ok indeed this file does not exist on the host before the container starts, so docker might create it as a folder then?
> 
> You suggest that adding an empty file on that location then solves this issue?

Exactly. i saw on some forums that this is a usual comportment of Docker when biding volumes., kinda weird because i have never seen that

**Comment by jekkos** [comment]
Ok I have added an empty error.log file to the data dir. This should resolve the issue.
