### ISSUE TITLE
Bulk item discount question

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#2956]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: bb309c
- PHP version is: 7.4.3
- MySQL or MariaDB version is: mariadb 15.1
- OS and version is: Ubuntu 20.04
- WebServer is: apache2 2.4.41
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Is there a way to select a bunch of items and give them a percentage discount?  I understand I can add a discount in the Sales module but I'd like the items to come up already discounted.  

Thanks

**Comment by chunter2** [comment]
Is this the right place for questions?  Just looking for any kind of help.  

Thanks

**Comment by odiea** [comment]
It is the correct place to ask but that feature is not available.

**Comment by chunter2** [comment]
Could this be something that's added in the future?  This is for a thrift store.  They tag items with different color tags and each week a different color is discounted to a different percentage to keep things moving through the store.  They have a 4 week cycle.  Maybe there's another way to do this that I don't know about.  I'm really new to this software.  

Thanks

**Comment by odiea** [comment]
It could be added but I would not hold your breath waiting for it. If you know a developer that could add it for you it would be a nice donation back to OSPOS. Yes my Wife also had a Thrift store so this does not have enough bells and whistles for that application.

**Comment by chunter2** [comment]
I'm guessing there's no discount column in the database for an item?  Maybe when I get some time I'll do some investigating.  What software did your wife end up using?  And what did she find was missing from OSPOS?  Just out of interest sake.

**Comment by odiea** [comment]
Discounting items by tag color Date or Category. Employee setup for secure logins and I assume much more. She ended up using Traxia she also had over 300000 items.
