### ISSUE TITLE
Https proxy setting in .htaccess

### ISSUE THREAD

**Issue by edwinhamers** [opensourcepos/opensourcepos#2957]
### Background information  & Issue

My hosting provider implemented a new loadbalancer setup that requires a "https" proxy configuration for Apache. They added 2 lines of code to the .htaccess:

```

# Vimexx Loadbalancer https proxy redirect...
RewriteCond %{HTTP:X-Forwarded-Proto} !https
SetEnvIf X-Forwarded-Proto "https" HTTPS=on
```

with these lines Opensourcepos won't work anymore. The returned error is "Not Found - 404".

I understand this really is a hoster specific issue and can be solved by removing the code. But the new https proxy loadbalancer config will be enabled by default and without it my website, and pos, won't work anymore. 

Are there any htaccess wizards that have a clue why it wont work ? It probably clashes with other htaccess code. Using the default one 

### Installation information

- [X] Did all the required checks....
- OSPOS version is: Latest
- WebServer is: Apache
- Selected language is: English

**Comment by edwinhamers** [comment]
I use this hoster on other domains (with WordPress installs for example) and the https proxy code does work. It uses the default wordpress redirects.

**Comment by edwinhamers** [comment]
In the meantime i solved the issue above by changing the redirect code to this:
```

# Vimexx https proxy redirect 
RewriteCond %{HTTP:X-Forwarded-Proto} !https
SetEnvIf X-Forwarded-Proto "https" HTTPS=on
RewriteCond %{SERVER_PORT} 80 
RewriteRule ^(.*)$ https://varsana.eu/$1 [R,L]
```

Maybe somebody can use this when encountering this issue... But remember that this will redirect all traffic to port 80 to port 443

**Comment by ekardian** [comment]
> 
> 
> In the meantime i solved the issue above by changing the redirect code to this:
> 
> ```
> 
> # Vimexx https proxy redirect 
> RewriteCond %{HTTP:X-Forwarded-Proto} !https
> SetEnvIf X-Forwarded-Proto "https" HTTPS=on
> RewriteCond %{SERVER_PORT} 80 
> RewriteRule ^(.*)$ https://varsana.eu/$1 [R,L]
> ```
> 
> Maybe somebody can use this when encountering this issue... But remember that this will redirect all traffic to port 80 to port 443

nice.. toma tu laik (take ur like XDDDDDDDDD)

**Comment by data2base** [comment]
Hi!

So i need to change the following code in order to load via https?

# redirect to public page
  <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^public$
    RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge [NC]
    RewriteRule "^(.*)$" "/public/" [R=301,L]
 
  </IfModule>

**Comment by data2base** [comment]
`# redirect to public page
  <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^public$
    RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge [NC]
    RewriteRule "^(.*)$" "/public/" [R=301,L]
 
  </IfModule>`
