### ISSUE TITLE
Barcode In ITEM KIT

### ISSUE THREAD

**Issue by akhilnasi** [opensourcepos/opensourcepos#2958]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 
- OS and version is: windows 10
- WebServer is: xampp
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
Hi !
i have a small problem in item kit !
As if now we can add the barcode in item module and generate the barcode from item module
But in Item Kit we cannot add the barcode , instead Auto incremented Kit Id is taken as barcode !. But i need a field to add a barcode in itemkit and that barcode should scanned in sale and receivings!

Do any one can fix this issue ! Thanks in Advance

**Comment by jekkos** [comment]
You mean that you would like to have the generate barcode button in item kits as well? I think this one needs a refresher in my case. You could just print barcodes for the kit id's you generate in this case?

**Comment by akhilnasi** [comment]
yes ! But it should be the same as in the item module. when we enter the
item from the item module it asks for the barcode also ! But in the Item
Kit module no field for Barcode . I need a Barcode input field in the item
kit and that barcode should be generated !

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jekkos** [comment]
Yes indeed or in this case an item number field in the item kit model. Doesn't sound like a very complex change.

**Comment by akhilnasi** [comment]
yes ! But could you help me to solve this ? or could you tell me where should i change the code ?

**Comment by jekkos** [comment]
I supose you will need to take a look in the Item_kits controller and the view associated with that.

**Comment by jekkos** [comment]
Feature is in master
