### ISSUE TITLE
The Receipt size

### ISSUE THREAD

**Issue by midsoft2010** [opensourcepos/opensourcepos#2960]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
Hello everyone? Is it possible to change the size of the receipt to 80mm? Or How to setup the Standard thermal printer to work with the pos?

**Comment by jekkos** [comment]
I think you can just adjust this in your page setup. If you have a receipt printer, change paper size to 80mm. Simple as that.

**Comment by midsoft2010** [comment]
It seems like i cant change these parameters ![Screenshot (23)](https://user-images.githubusercontent.com/29373167/95275818-37b6cf00-0852-11eb-9f93-54d29121a238.png)

**Comment by jekkos** [comment]
No change it in the page setup of your print dialog instead

**Comment by midsoft2010** [comment]
I got the receipt issue.. So how do you Make sales on credit and receive payments after the client or customer pays

**Comment by jekkos** [comment]
don't add any payments and add them later on?

**Comment by midsoft2010** [comment]
I only have 3 options i.e add payment, suspend and cancel, if i suspend i cant print the invoice content?

**Comment by jekkos** [comment]
OK you might not be able to complete the receipt without adding any payments indeed. Maybe you can add a 0 payment?

**Comment by midsoft2010** [comment]
This is where it is tricky since you cant track debtors! But thanks for your feedback. Maybe i will request for that feature

**Comment by mobinalhassan** [comment]
Does anyone know which thermal printer is best/compatible with Linux(Ubuntu 18.04.5 LTS)?

**Comment by midsoft2010** [comment]
Try epison or micros.. posiflex is fine but challenging to configure

**Comment by midsoft2010** [comment]
Hello there Jekkos!


Am trying to import the following attached csv file on version 3.3.3 and am
getting an error that  no rows were imported?

**Comment by midsoft2010** [comment]
Hi jekkos! I have some upgrade i want to ask for and how much it will cost!

1. Customer accounts:

      These are account receivables, where i can sell to a customer with
credit and they will be paying little by little.(here i can receive money
from a specific customer when they bring money without editing the sale
transaction)

2. Customer credit limit:

   This is where i set a limit for credit to a specific customer.

3. Suppliers import feature.

Please reply


Thank you
