### ISSUE TITLE
Databas.SQL is missing

### ISSUE THREAD

**Issue by Ahmad1Jaber** [opensourcepos/opensourcepos#2961]
Database.sql is missing

**Comment by odiea** [comment]
You need to download from the install.md and get a zip file.
https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md

**Comment by araneta** [comment]
there is no sql file on 
https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md

**Comment by Justotrev** [comment]
there is no sql file on kindly help on how to get the database.sql file
https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md

**Comment by SteveIreland** [comment]
If you're working on the master, you will need to read the BUILD.md file.  It tells you how to build the project, and one of the artifacts created by the build process is to create the database.sql file.

https://github.com/opensourcepos/opensourcepos/blob/master/BUILD.md

If this is your first time and you're new to this effort then just go slow and be patient.  It requires setting up a proper development environment.  All of the components (and the correct version of each component will need to be downloaded and/or installed.

Good luck.
