### ISSUE TITLE
How to install on docker?

### ISSUE THREAD

**Issue by 34t614t1254y** [opensourcepos/opensourcepos#2963]
Hi,

I have tried to install it on docker using Synology NAS.

But I have no idea how to install it.

Whatever I did, it shows '[mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully' and shut down.

Is there anyone help me with it?

**Comment by jekkos** [comment]
you might be better off asking on a synology forum in this case. I haven't tried their docker package yet, so I'm not sure on whether you will be able to start the compose from a UI. In any case you should be able to start it from the command line , once installed. But you might also need to install docker-compose then (and hence python) to run the full setup.

**Comment by 34t614t1254y** [comment]
Thank you for your replay.

I'm gonna ask there.
