### ISSUE TITLE
Serious inventory error when deleting a sale

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2964]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
_____________________________________________

If they sell a product in decimals, for example, a quantity of 0.5. and complete the sale .. after this in sales of the day. they erase the sale. this amount does not return to the item. there is only the message that he was deleted the sale.. this does not happen with products with whole quantities

![Screenshot_2020-10-12 Open Source Point of Sale Powered by OSPOS 3 3 2(2)](https://user-images.githubusercontent.com/29256343/95800581-f17bc880-0cb4-11eb-872e-e58359c976dc.png)
![Screenshot_2020-10-12 Open Source Point of Sale Powered by OSPOS 3 3 2](https://user-images.githubusercontent.com/29256343/95800591-f6407c80-0cb4-11eb-9a55-afd3e4c126c0.png)
![Screenshot_2020-10-12 Open Source Point of Sale Powered by OSPOS 3 3 2(1)](https://user-images.githubusercontent.com/29256343/95800596-f771a980-0cb4-11eb-847e-9a5f53cfc52d.png)

**Comment by jekkos** [comment]
At first sight it looks like item quantities table is not being updated. To be verified in the code.

**Comment by andriux1990** [comment]
> At first sight it looks like item quantities table is not being updated. To be verified in the code.

Thank you very much @jekkos  for seeing this error

**Comment by jekkos** [comment]
@andriux1990 Can you try latest version on dev server to see if this resolves your issue? Thanks

**Comment by andriux1990** [comment]
> @andriux1990 Can you try latest version on dev server to see if this resolves your issue? Thanks

Thanks @jekkos for solving the problem, now the quantities return to inventory

**Comment by jekkos** [comment]
The issue was only with decimal quantities (due to the `intval` cast in the sale correction).
