### ISSUE TITLE
Only full_group_by issue in detailed receivings report

### ISSUE THREAD

**Issue by saurabh261187** [opensourcepos/opensourcepos#2967]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2 , the last stable version released
- OSPOS git commit hash is: opensourcepos.20200903075833.3.3.2.bb309c.zip
- PHP version is: 7.2.24
- MySQL or MariaDB version is: 5.7.31-0ubuntu0.18.04.1
- OS and version is: Ubuntu Linux 18.04.4
- WebServer is: Apache 2.4.29
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: Virtualmin

### Issue / Bug  / Question / New Feature

Whenever I am trying to generate Receiving report, a HTTP 500 error is coming up. I ran the installation in development mode and this came up :

![image](https://user-images.githubusercontent.com/15091342/96087990-62ec8e80-0ee2-11eb-9393-6b9f8524406e.png)

I changed the MYSQL sql_mode to not use only_full_group_by , and removed it. Post that the receiving ran fine, but it may create dependencies on other softwares since I am using a shared server. Is there no way to run the installation out of the box without making any changesto sql_mode ?

**Comment by jekkos** [comment]
I'm surprised to see this issue popping up. You are using regular MySQL I supppose? I have just checked on demo and it does work fine on MariaDB. So it might be MySQL specific.

**Comment by saurabh261187** [comment]
Also, when you click on the + sign in Detailed Recievings report to see the details of a particular Recieving , it shows only one product name , to see the rest of it, you need to go into details and view. This is also functioning differently in the OSPOS Demo Server and on a MYSQL based server.

**Comment by jekkos** [comment]
Should be fixed in latest master. @saurabh261187 can you verify?

**Comment by saurabh261187** [comment]
I downloaded opensourcepos.20201028215111.master.625fb5 version from the unstable build releases. Now the receiving report works, however, as stated above, when you click on the + sign in Detailed Recievings report to see the details of a particular Recieving , it shows only one product name, even if you have received multiple , to see the rest of it, you need to go into details and view. But something is better than nothing :P 👍

**Comment by jekkos** [comment]
I have done another (untested) change and pushed it to a branch here. You can check the dev server in a couple of minutes to see if this resolves this last issue.

**Comment by saurabh261187** [comment]
By dev server, you mean the official demo at https://demo.opensourcepos.org/ ? I suppose you use MariaDB ther rite ? So it should work, let me know when I can download an unstable build from bintray and test it on my server. if possible, kindly mark the one I should use.

**Comment by saurabh261187** [comment]
This one ? opensourcepos.20201029084046.fix-detailed-receiving.1a9587.zip

**Comment by jekkos** [comment]
Yes correct. dev server is https://dev.opensourcepos.org

it has latest pushed commit normally, the demo runs the latest stable version

**Comment by saurabh261187** [comment]
> I downloaded opensourcepos.20201028215111.master.625fb5 version from the unstable build releases. Now the receiving report works, however, as stated above, when you click on the + sign in Detailed Recievings report to see the details of a particular Recieving , it shows only one product name, even if you have received multiple , to see the rest of it, you need to go into details and view. But something is better than nothing :P 👍

This issue still persists in opensourcepos.20201029084046.fix-detailed-receiving.1a9587.zip

**Comment by jekkos** [comment]
I have the impression that it does work when you use attributes. At least on my install it works. But even then it would be a valid bug.

**Comment by jekkos** [comment]
Ok did another commit to master, that should solve it. It'll be on dev server in a couple of minutes normally for you to verify. I checked locally and it seems fine (with and without attributes but on mariadb)

**Comment by saurabh261187** [comment]
The detailed receiving is sorted in opensourcepos.20201112184137.master.8571cd , in the unstable builds. However, now the Transaction Detailed sales report is not working. Same error HTTP 500. Kindly look into this.

**Comment by jekkos** [comment]
@saurabh261187 can you try latest unstable master in a couple of mins?

**Comment by jekkos** [comment]
Verified myself and was fine, will close again.

**Comment by saurabh261187** [comment]
This works. Thanks :D
