### ISSUE TITLE
Email CC or BCC

### ISSUE THREAD

**Issue by saurabh261187** [opensourcepos/opensourcepos#2968]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS version is: 3.3.2 , the last stable version released
OSPOS git commit hash is: opensourcepos.20200903075833.3.3.2.bb309c.zip
PHP version is: 7.2.24
MySQL version is: 5.7.31-0ubuntu0.18.04.1
OS and version is: Ubuntu Linux 18.04.4
WebServer is: Apache 2.4.29
Selected language is: English
(If applicable) Installation package for the LAMP/LEMP stack is: Virtualmin

### Issue / Bug  / Question / New Feature

Can anyone please elaborate how to send Invoices / Receipts as BCC or CC in this version of OSPOS ?

**Comment by jekkos** [comment]
to who would you want to send in cc? a fixed email? In that  case you can do a static configuration in CI itself I believe.

**Comment by jekkos** [comment]
you can change this in `application/config/email.php`. Fill in the `default_cc_address`

**Comment by jekkos** [comment]
Ok sorry no, this is file exists only in my private version. So it's not applicable to 3.3.2.

**Comment by saurabh261187** [comment]
So does the functionality exist or not ? Since it was available in the earlier versions ...

**Comment by jekkos** [comment]
As an admin user I follow most of the emails going out of my install (well in fact these are sent to an external 'admin' mailbox in this case). Quite good to have this as these days it has become rather hard to get good delivery rates.. I run my own mailserver and this has worked fine for quite some years, until recently especially microsoft started to block all traffic not originating from any other big company or mail platform.  .

**Comment by daN4cat** [comment]
You need to set SPF, DKIM and DMARC to your email and DNS entries. Those will increase the trust of your mail sender: https://www.csoonline.com/article/3254234/mastering-email-security-with-dmarc-spf-and-dkim.html
In that article they make it difficult but it is not that hard.

**Comment by jekkos** [comment]
Functionality in master, can be configured in email.php directly.
