### ISSUE TITLE
Create Customer from Customer view, recreating the same Customer from Sales allows duplication

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#2973]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3 (latest master)
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: MariaDB 10.3
- OS and version is: Cent OS
- WebServer is: Apache 2.4
- Selected language is: en_GB
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Create a Customer from Customer view.
Go to Sales.
Create the same Customer using New Customer button, a duplicate is allowed where in Customer view is not.

This is a mistake causing issues because email is unique.

**Comment by jekkos** [comment]
@daN4cat how do you know that a user is creating the same customer again? It can be well possible that two customers have a similar name?

**Comment by daN4cat** [comment]
The email is unique. I don't understand why in Customer the form at submit time flags the email duplication error but the same form in Sales doesn't.
This is one of the problems they are facing. Also messes up things with buying allocated  two the forcing a manual fix at database level.

**Comment by daN4cat** [comment]
I don't have time to look into this until next weekend. Not sure if you can find the time to test and fix?

**Comment by jekkos** [comment]
Hm no sorry I have other things on my hands now, maybe later on but wanted to get this stock location fix finished first.

**Comment by odiea** [comment]
I am not able to duplicate this issue. I created a new customer. Then I went into the Register and tried to duplicate this customer and I received the following.
![2020-10-19 13_38_39-Window](https://user-images.githubusercontent.com/10962177/96503515-9bf16f80-1210-11eb-9065-68934ff952c6.png)

**Comment by odiea** [comment]
Am I not testing correctly? I used the same customer with the same customer email.

**Comment by daN4cat** [comment]
Thanks odiea for the check. I need to retest on my side and verify the database table.
It might be that the table migration didn't change something.

**Comment by jekkos** [comment]
@daN4cat any new insights on this one?

**Comment by daN4cat** [comment]
Had no time to test further. Sorry.

**Comment by jekkos** [comment]
I briefly tried this one on demo and indeed, as @odiea confirms, we are not allowed to create a customer with same email address twice. Changed label to pending (until @daN4cat you find the time to have a further look).

**Comment by daN4cat** [comment]
Not sure how come I could reproduce this but not anymore, at the moment it's not an issue.

**Comment by daN4cat** [comment]
This was probably due to #3044 and #3045
