### ISSUE TITLE
Can use ip but not Domain name

### ISSUE THREAD

**Issue by darkjedeye** [opensourcepos/opensourcepos#2978]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation

 (yes)

- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!) 

(I did check, and maybe it's beed solved before, but i spent 2 days and only a vague reference to it)

- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)

(yes)

- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable
(yes to all above)
### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: bb309c
- PHP version is: PHP 7.0.33-0ubuntu0.16.04.16 (cli) ( NTS )
- MySQL or MariaDB version is: mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64) using  EditLine wrapper
- OS and version is: Ubuntu server 16.04 lts
- WebServer is: Apache 2 ver 
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2020-08-12T21:35:50

- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:  lamp

### Issue / Bug  / Question / New Feature

I'm not even realy sure it's an issue.... i can access the setup without any problems usin ip,
when i try wi url i get a recuring /public/public...
ie.
http://MYDOMAIN.ONNET/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/

I did try to edit .htaccess as was demonstarted in one of the threads i was reading, but that didn't work... happy to have one of the developers log into my vps and have a look.. as it is a test server, and nothing important on it.

**Comment by jekkos** [comment]
I think I have seen this one before. It might have something to do with the trailing slash. Which url do you enter exactly @darkjedeye ?

**Comment by jekkos** [comment]
We have a rewriteCond check in the .htaccess to check and [break the infinite](https://github.com/opensourcepos/opensourcepos/blob/c0ac4b34001b5dfbb4c1041ebb1c2e6aa49427e6/.htaccess#L4) loop in this case.

**Comment by jekkos** [comment]
To check if .htaccess works add following line on top of the file

```Deny from all```

Then check if you get a forbidden. If not then probably your apache setup is wrong.

**Comment by darkjedeye** [comment]
Managed to get it sorted... was my own stupidity... had it directed to port 82, and neglected to set the ports option in apache2
