### ISSUE TITLE
Upgrade to latest bower dependencies

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2979]
https://github.com/opensourcepos/opensourcepos/blob/3471c0f947593cd86ddece2942919e49c0d10964/bower.json#L36

Let's try and upgrade some libraries. Normally minor version bumps should not have any breaking changes and should update without too many issues. I'll run a `bower update` for this and then we can validate the build.

**Comment by daN4cat** [comment]
Anything new with the latest version?
