### ISSUE TITLE
Credit Card Filter Not Available in Transaction Listing

### ISSUE THREAD

**Issue by chrisvell88** [opensourcepos/opensourcepos#2983]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: Litespeed
- Selected language is: English UK
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
![CreditCardFilter](https://user-images.githubusercontent.com/49901801/96977919-0874b300-151e-11eb-9325-30f3bfc88ee2.png)

Hi Team, 

It seems that when you go to Sales -> Transactions and list transactions, there is no filter by credit cards. Can this be added please?

Moreover, how can you add additional payment types in the system such as bank transfer, etc?

Thanks,

**Comment by jekkos** [comment]
To add a new filter:
Not sure how this filter set is retrieved, but it should just read from the same array in which the payment types are defined. In that case all options should show. 

To add a payment type:
Shouldn't be too hard to add this. Payment types are found in the Sale.php model. It might just be a matter of adding a new constant in there (and some translation lines to get a proper label in each langauge).

**Comment by odiea** [comment]
I believe he needs to add this also to the filters at the top of  controller/Sales.php for it to show in the dropdown listings.

**Comment by chrisvell88** [comment]
Tried to add filter but not working. Can you direct me on how I can add payment type and the new filter please?

Thanks

**Comment by jekkos** [comment]
@chrisvell88 here a little gift from me. Can you try my branch and check if the filter works? I tried it locally and seemed fine.

**Comment by chrisvell88** [comment]
Thanks @jekkos  will try it out

**Comment by jekkos** [comment]
https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20201028214239.add-credit-filtering.0c67f3.zip

**Comment by jekkos** [comment]
If you confirm it works fine I'll merge it.

**Comment by chrisvell88** [comment]
Thanks for the link. From all those files, which files do need actual replacing? Will test out and let you know outcome today.

**Comment by odiea** [comment]
@jekkos I think he wants you to go to his house and change it for him.

**Comment by chrisvell88** [comment]
@odiea I think asking about something relatively simple and trivial im not asking too much. After all my contribution like all others are intended to help this product improving. Moreover, I think its better to just copy 1 or 2 files rather than replacing the whole file structure. So please I encourage you to avoid such frivolous comments.

**Comment by jekkos** [comment]
It's quite [a long list](https://github.com/opensourcepos/opensourcepos/commit/0c67f3a252ca9d3bea2ba76c9f00d5143193891e). But if you want I can deploy it on dev server so you can check there?

**Comment by jekkos** [comment]
Its on [dev server](https://dev.opensourcepos.org/home) now

**Comment by jekkos** [comment]
@chrisvell88 any feedback?

**Comment by chrisvell88** [comment]
@jekkos will give you feedback today

**Comment by chrisvell88** [comment]
Hi @jekkos  I have tried it on our environment but caused the reports not to run since updating those files you send me.

**Comment by jekkos** [comment]
Not sure I'm following. This change breaks your reports again?

**Comment by chrisvell88** [comment]
@jekkos  yes the filter is visible on the Sales -> Transaction Items Screen however when giving a date range to view report it does not show any data. Upon reverting to the original files all was back ok again so it based on the change.

**Comment by jekkos** [comment]
Ok so date filtering has stopped working on sales screen now then?

**Comment by chrisvell88** [comment]
Yes...after you created credit card filter, the transaction listing report does not work

**Comment by jekkos** [comment]
Ok but it does work in latest master, I'll merge and well see then if it's all good , and fix after if needed.

**Comment by chrisvell88** [comment]
I tested it on our environment. What are the credentials of the dev server link you provided so I can check from there as well?

**Comment by jekkos** [comment]
it's the same as in demo env admin/pointofsale

**Comment by odiea** [comment]
I downloaded and installed the latest unstable master and it appears to be just fine.

**Comment by jekkos** [comment]
Thanks for testing @odiea . In master now so I close.
