### ISSUE TITLE
How can you include Customer Details and Barcodes for serial numbers in receipt / invoice

### ISSUE THREAD

**Issue by chrisvell88** [opensourcepos/opensourcepos#2984]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: Litespeed
- Selected language is: English UK
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi, 

Is it possible to include Customer Details and Barcode Symbol for line item serial numbers on receipt / invoice? How can you do that?

Thanks,

**Comment by jekkos** [comment]
You can do this by editing the receipt templates in the view folder (`receipt.php`)

**Comment by chrisvell88** [comment]
Thanks 👍

**Comment by chrisvell88** [comment]
Can you guide me from where I can get customer paramters to display on receipt? Is there documentation available?

Thanks,

**Comment by jekkos** [comment]
I'm afraid that the only documentation here is the code. You can use any variable that is available in the view that loads the receipt. Check the Sale.php controllor `load_sale` method for any candidates there.

**Comment by chrisvell88** [comment]
Hi, 

That would be very difficult to find / guess the fields from where I need to get data to modify receipt then. Can you guide me which field returns the Line item serial number and the transaction customer details such as Name, Address, Tel, Email?

Thanks,

**Comment by andriux1990** [comment]
> Hi,
> 
> That would be very difficult to find / guess the fields from where I need to get data to modify receipt then. Can you guide me which field returns the Line item serial number and the transaction customer details such as Name, Address, Tel, Email?
> 
> Thanks,

You have to edit the receipt and add these additional fields to the controller so that the receipt can display them

**Comment by chrisvell88** [comment]
I have tried doing so but could not manage. Can anyone help on this please?
