### ISSUE TITLE
Custom Fields for Customers

### ISSUE THREAD

**Issue by chrisvell88** [opensourcepos/opensourcepos#2985]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.1
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: Litespeed
- Selected language is: English UK
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question 

Hi, 

Is it possible to add Custom fields to customer?

Thanks,

**Comment by jekkos** [comment]
At this moment it is not. We did have a plan to add and extend the attributes to be used from customers as well, but to my knowledge no one is working on this.

**Comment by chrisvell88** [comment]
Thanks for your reply, 

Can you maybe add a field to store the VAT / TAX number of the customer?

Thanks,

**Comment by jekkos** [comment]
I use the account_number field for that if I'm not mistaken. So this together with the company name could represent a business customer.

**Comment by chrisvell88** [comment]
we can use that yes. strongly recommend you add some custom fields to the customer table since it will bring more value to the product.

**Comment by jekkos** [comment]
Sure it will add value, but ospos is not a commercial product and I won't earn a penny adding it. I added most of the features at the time as I needed those as a user as well. So it's nice to be able to share this with others

**Comment by bfrosty1** [comment]
what if i offered to pay for it?  When import a csv to setup customers I need tohave membership info and expiration of membership in date form and type of memebership life ,individual, or family.

**Comment by DamianoSilverhand** [comment]
> what if i offered to pay for it? When import a csv to setup customers I need to have membership type and expiration of membership in date form (mm/dd/yyy) and type of membership life ,individual, or family. so 2 columns?

@bfrosty1 did you manage with this enhancement?

**Comment by jekkos** [comment]
PR in #3118

**Comment by jekkos** [comment]
Will close as we're tracking this in another ticket
