### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated in PHP 7.4

### ISSUE THREAD

**Issue by dedyf5** [opensourcepos/opensourcepos#2987]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: bb309c
- PHP version is: 7.4
- MySQL or MariaDB version is: 10.4.14-MariaDB
- OS and version is: Windows 10
- WebServer is: Apache 2.4.46
- Selected language is: Indonesia
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: XAMPP 7.4.11-0

### Issue / Bug  / Question / New Feature

Array and string offset access syntax with curly braces is deprecated in PHP 7.4.

Ref: [deprecate_curly_braces_array_access](https://wiki.php.net/rfc/deprecate_curly_braces_array_access)

![deprecate_curly_braces_array_access](https://user-images.githubusercontent.com/3234847/97083779-a9599000-163c-11eb-9efc-e1fb809b3c6f.png)

**Comment by daN4cat** [comment]
Fixed in 3.3.3
