### ISSUE TITLE
After updating to PHP Version: 7.4.9 I received the following error with error setting to 1 and going into configuration.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2988]
OSPOS Installation Info: 3.4.0 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Opera
.Server Software: Apache/2.4.46 (Win64) PHP/7.4.9
.PHP Version: 7.4.9
![2020-10-24 08_26_18-Window](https://user-images.githubusercontent.com/10962177/97084418-1a189200-15d4-11eb-9d75-7daa1d09b83f.png)

.DB Version: 8.0.21
.Server Port: 80
.OS: Windows NT 10.0

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable ✗
» [import_customers.csv:] - 0666 | Readable ✓ | Security Check Passed ✓

There are problems with file permissions please fix and reload this page.

Security Vulnerability Warning
Permissions higher than 750 for write and 660 for read leaves this software at risk.

» [application/logs:] is writable, but the permissions are higher than 750.
» [public/uploads:] is writable, but the permissions are higher than 750.
» [public/uploads/item_pics:] is writable, but the permissions are higher than 750.
» [import_customers.csv:] is readable, but the permissions are higher than 660.
America/Denver

**Comment by odiea** [comment]
Duplicate so I will close my issue

**Comment by daN4cat** [comment]
Latest master contains the fix to this issue.

**Comment by odiea** [comment]
I guess the current version on my server isn't the most current. Thanks for letting me know.
