### ISSUE TITLE
Amount Due calculation in Daily Sales report

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#2995]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Just a question about the amount due column in the daily sales report.  Is it calculated on the fly or taken from the database?  The reason I ask is I think it may be incorrectly calculated if there's discounts applied.  We have a customer called Volunteer that get a 20% discount.  In the sales module it seems to calculate the 20% on each item which is fine.  In the daily sales report it seems to calculate it on all the items combined.  These two values can be different based on rounding.  So then the amount due is different than the total on the receipt.  This then shows a negative value in the change due column even though they paid the full amount on the receipt.  Could this be a bug in the way the amount due column is calculated?  

Thanks

**Comment by jekkos** [comment]
Ok thanks for reporting this. Someone will need to take a look at the code to figure out if this works as expected.

**Comment by chunter2** [comment]
Just to update this, here are some screenshots.  This one is the Daily Sales report.  
![daily sales rounding](https://user-images.githubusercontent.com/531129/98468478-a1efc600-21a8-11eb-9bfc-3ce0e61d7452.jpg)
And this one is the receipt to go along with it.  
![receipt](https://user-images.githubusercontent.com/531129/98468493-b207a580-21a8-11eb-8962-1f5ab24549a3.jpg)
You'll see the total of the receipt is $30.40 but the Amount Due of the daily sales report is $30.41.  I believe this is because the discount is calculated on each item first on the receipt which I think is correct but calculated on the total in the daily sales report.  This is why the amount due is -$0.01.

**Comment by chunter2** [comment]
I just checked the Detailed Transaction Report and it looks correct as well.  
![rounding3](https://user-images.githubusercontent.com/531129/98686456-992cfa80-2336-11eb-8995-539bddb14ce8.jpg)
I can't seem to find where the Amount Due in the Daily Sales Report is calculated in the code.  Can someone point me in the right direction? 

Thanks

**Comment by chunter2** [comment]
@jekkos Could you point me in the right direction for this?  

Thanks

**Comment by jekkos** [comment]
I'll have a look tomorrow in the code.. it might be somewhere in the sale_lib in this case.

**Comment by chunter2** [comment]
@jekkos Did you have a chance to take a look at this?  And should this be marked as a bug?  

Thanks

**Comment by jekkos** [comment]
Not yet.. I'll try to have a look tonight.

**Comment by jekkos** [comment]
Check the sales model Sale.php, line 198. At first sight it uses the same value as the total there, which is as follows `'ROUND(SUM(' . $sale_price . '), ' . $decimals . ') + ' . $sales_tax`.

**Comment by jekkos** [comment]
But that is for the sale_due. There is also a change_due, check Sale.php, line 200. It's defined as follows

`(MAX(payments.sale_payment_amount) - ($sale_total)) AS change_due`

**Comment by jekkos** [comment]
While sale_payment_amount is the following
`SELECT payments.sale_id AS sale_id,
					IFNULL(SUM(payments.payment_amount), 0) AS sale_payment_amount,`

**Comment by jekkos** [comment]
Sop it seems that this change due is not rounded to `$decimals`, while initial sale_price is in fact rounded. Adding this might solve the issue here.

**Comment by chunter2** [comment]
@jekkos There may be a problem with the change due as well, I haven't had a chance to look yet but I still think the Amount Due is incorrect.  It should be $30.40 in my example above, not $30.41.  I think the amount due should be calculated the same way as the total on the sales receipt.

**Comment by chunter2** [comment]
@SteveIreland Could you possibly take a look at this too? I think it has to do with rounding like the issues you're working on.

Thanks

**Comment by daN4cat** [comment]
I'm lost here with the last few bugs, are all of these solved with Steve's PR?

**Comment by jekkos** [comment]
Yes I think @SteveIreland was looking into this. Last thing I heard was that he said the PR wasn't functionally 100% done yet. So not sure maybe we can go ahead and release 3.3.3, then do another minor one with his changes after (and address any additional feedback we will get in that one).

**Comment by objecttothis** [comment]
@SteveIreland How close are we to merging this?

**Comment by objecttothis** [comment]
@SteveIreland is this issue something already resolved in #3026?

**Comment by SteveIreland** [comment]
I think @jekkos identified and fixed the issue, but I'll retest it this week to see if there is still an issue.

**Comment by SteveIreland** [comment]
Just tested it and it appears to still be an issue.  I will work on it this weekend.

**Comment by SteveIreland** [comment]
Pull request #3107 has been submitted for this.

**Comment by SteveIreland** [comment]
This should now be fixed.   Let me know if I overlooked something.

**Comment by chunter2** [comment]
@SteveIreland Just getting to this.  Will your PR work on 3.3.2?  I haven't had a chance to upgrade yet but I tried your PR just to see and it still seems to be off; the receipt compared to the Daily Sales report.  I also checked the detailed transaction report and it's off as well.  If it's built off your cash rounding PR then I may have to test when I get things upgraded.  

Thanks

**Comment by SteveIreland** [comment]
I will rebuild the test from the latest master and rerun my tests this week, but my previous tests resulted in the same amounts printed on receipts as those on the daily sales report.    I tested it with percent discounts and discount amounts but no cash rounding (but cash rounding shouldn't make a difference.)

**Comment by chunter2** [comment]
@SteveIreland Just had a thought. Did you try with multiple items where it has to round the discount for each one? I think that's where it gets off by a few cents. I think the discount is applied to each item individually on the receipt but as a whole in the reports.

Also, I'm assuming this should fix old transactions since it's just a display thing?

**Comment by chunter2** [comment]
@SteveIreland I just tried on dev.opensourcepos.org and the Amount Due is still off in the Daily Sales report so I don't think it's an issue with me mixing PR's and versions.

**Comment by SteveIreland** [comment]
@chunter2 I just downloaded the latest copy of master from bintray installed it locally and ran a few tests. Everything still seems to be in balance.  I checked discounts by percent and discounts by amount.

**Comment by objecttothis** [comment]
@chunter2 can you send an exact step-by-step (and screenshots if possible) to how you are recreating this issue?  It might be that only in certain scenarios it's doing it and @SteveIreland isn't testing the same scenario.  @SteveIreland I noticed there is a screenshot above.  If you recreate the scenario in that screenshot does it show accurately?

**Comment by SteveIreland** [comment]
Earlier I noted that I was able to recreate the problem.  It is now fixed and I cannot recreate the problem.

**Comment by chunter2** [comment]
@SteveIreland Now that dev.opensourcepos.org is up to date I was able to test again and it looks like it's still not working all the time.  If you look at transaction Id = 2 you'll see the change due in the daily sales is still showing -$0.01 when it should be zero.  

Thanks

**Comment by SteveIreland** [comment]
Okay, I'll take a look tonight.

**Comment by SteveIreland** [comment]
Well, as luck would have it, someone installed a commit today that rebuilt the dev site, so your test data was not there.

So I created data exactly like what you posted on this thread earlier and could not find a problem with rounding.  However, a problem I DID see but couldn't explain was that the taxes that were calculated were totally different than any your example.

Instead of 5% GST computing 1.28 the current version is computing 1.44.

And instead of 13% HST computing .41 the current version is computing 3.73.  Maybe that issue is contributing so if you can fill me in on what's gong on I'd appreciate it.  How is your tax scenario configured?  Is it using the basic tax or is it using destination based taxing?  The amounts should be the same but maybe there is a bug there.

Also, if you can just provide a list of the items, prices, quantity, discount, and taxes you used in the dev test then I'll just replicate it in my local copy .... that way we don't need to worry about someone wiping it out.

**Comment by chunter2** [comment]
@SteveIreland I just checked dev.opensourcepos.org and my example is still there.  Here's a link.  https://dev.opensourcepos.org/sales/receipt/2
I'm just using normal taxes.  In my example above Kids Footwear and Books are 5% and the toy line is 13%.  The taxes are calculated on the discounted price.

**Comment by SteveIreland** [comment]
Okay, thanks.  I was able to replicate the issue locally and now that I understand how you have the taxes set up I now know that all is good with the taxes.

.99 * .50 = .495 which is truncated to .49 on the sale (rounding down) but is rounding up to .50 on the reports. 

So the method used in the sale itself doesn't do any rounding.  I think this should easy to resolve on the reports so I'll give that a shot tomorrow.  Thanks for being persistent.

**Comment by chunter2** [comment]
Glad you found it.  Thanks for continuing to look too.  :)  

One thing I was questioning myself is if say you have three items that all come to say 0.492 so they'd all round down to 0.49 but together they'd round up, is that taken into account?  It's like the Daily Sales calculation is calculated on a whole where the receipt is calculated on each item individually.  I think in looking at this so much I may have confused myself too.  :)

**Comment by SteveIreland** [comment]
Well, when I started making decisions as to what to change I found that what I thought was the issue actually wasn't.  The problem was that the rounding was taking place at the wrong spot.  I believe pull request #3113 should address the issue but docker is feeling abused so it's putting us in time-out.   Hopefully that will be sorted out soon.

**Comment by jekkos** [comment]
I have pushed a change for the docker setup.. Doing a login now before the build takes off, so that might fix the rate limitation issues for now.

**Comment by SteveIreland** [comment]
@daN4cat merged the pull request for this last change, so hopefully this is finally done!

**Comment by chunter2** [comment]
@SteveIreland Looks like it's working now on dev and in my 3.3.2 system with your patches applied.  Thank you for getting to the bottom of this for me.  Now I don't see any change due on debit/credit card transactions.

**Comment by jekkos** [comment]
Great news, so we're one step closer to do a 3.3.4 now. Thanks both.
