### ISSUE TITLE
Item name and Retail price in Items summary report

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#2999]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Would it be possible to get the Item name and Retail price in the Items summary report?  I've added Retail price in the search suggestions layout and it would be nice to have it in the report as well.  Our items are very generic and we distinguish them by price.  

Thanks

**Comment by jekkos** [comment]
Sure you can have that, you just need to adapt the code .. add the field in the SQL query, then add it in the report model, add the header and you should be good.

**Comment by chunter2** [comment]
I think I'm close with this.  I've added 
```			    'unit_price' => $row['unit_price'],```
to $tabular_data[] in the summary_items function of Reports.php and I've added
```		    array('unit_price' => $this->lang->line('reports_unit_price')),```
to the _get_data_columns() function of Summary_items.php as well as
```                MAX(items.unit_price) AS unit_price,```
to the _select function.  

The only issue I'm having is when you click on the "Retail Price" to sort it doesn't seem to sort properly.  I think it has to do with the _group_order() function but I'm not quite sure how that works.  

Thanks

**Comment by odiea** [comment]
Did you add this , 'sorter' => 'number_sorter'), after unit_price in the summary_items model report?

**Comment by chunter2** [comment]
That was it.  So the line becomes
```array('unit_price' => $this->lang->line('reports_unit_price'), 'sorter' => 'number_sorter'),```
Is the normal way to get things like this added a pull request?  I guess if they should be added at all?  

Thanks

**Comment by jekkos** [comment]
Yes indeed, you can proppose these changes in a pull request and then they can be included. Thanks.

**Comment by chunter2** [comment]
Just for completeness this is fixed with this commit.  https://github.com/opensourcepos/opensourcepos/commit/36b0b281090d4c7e134478acb96896b322e2a6e3

**Comment by jekkos** [comment]
Thanks and in master, will close.
