### ISSUE TITLE
Permisos para empleados y solución para lista de Artículos con existencia en 0

### ISSUE THREAD

**Issue by ozzylamberth** [opensourcepos/opensourcepos#3000]
Que tal amigos nuevamente por aqui. Se que los permisos se asignan a la DB en ospos_modules y ospos_permissions ya estoy claro en ello y se que los 
Action buttons de CRUD su funciones se encuentra en controllers/Items.php lines 336 y en tabular_helper.php en la linea 432 pero no logro decirle que usuario puede tener acceso a eso botones en el CRUD de inventario es decir que solo el administrador pueda ver esas opciones pero el vendedor no.

![11](https://user-images.githubusercontent.com/7409604/97793615-a1fa2f80-1bc4-11eb-91f6-7c563caa7251.jpg)

Con respecto a otro detalle sobre la lista de inventario la misma muestra toda la lista sin importar si tiene exixtencia en 0. Lo solucione de esta manera en la  aplication/models/item.php en la linea 224 hasta la linea 226

Este es el codigo original
if($filters['low_inventory'] != FALSE)
{
$this->db->where('quantity <=', 'reorder_level');

Este es el codigo que modifique para que solo me mostrara los articulos que tengan existencia unicamente en la lista.

if($filters['low_inventory'] != TRUE)
{
$this->db->where('quantity >', 'reorder_level');

Solo cambie la manera de realizar la peticion de <= a > y para ver todo el inventario completo solo cambie
if($filters['low_inventory'] != FALS) a if($filters['low_inventory'] != TRUE)

How about friends here again. The permissions are assigned to the DB in ospos_modules and ospos_permissions I am already clear on it and I know that the
CRUD Action buttons their functions are found in controllers / Items.php lines 336 and in tabular_helper.php on line 432 but I can't tell you which user can have access to those buttons in the inventory CRUD, that is, only the administrator can see those options but the seller doesn't.
![11](https://user-images.githubusercontent.com/7409604/97793624-d79f1880-1bc4-11eb-9419-b1ecc362aa4e.jpg)

With respect to another detail about the inventory list, it shows the entire list regardless of whether it has a 0 existence. I solved it this way in the application / models / item.php on line 224 to line 226
This is the original code
if ($ filters ['low_inventory']! = FALSE)
{
$ this-> db-> where ('quantity <=', 'reorder_level');

This is the code that I modified so that it would only show me the articles that only exist in the list.
if ($ filters ['low_inventory']! = TRUE)
{
$ this-> db-> where ('quantity>', 'reorder_level');

Just change the way you make the request from <= a> and to see all the complete inventory just change
if ($ filters ['low_inventory']! = FALS) to if ($ filters ['low_inventory']! = TRUE)

_Originally posted by @ozzylamberth in https://github.com/opensourcepos/opensourcepos/issues/2993#issuecomment-720014899_

**Comment by odiea** [comment]
Puedes probar esto. Vaya a application \ helpers\ tabular_helper y cambie la parte inferior de la función get_item_data_row por lo siguiente. Puede utilizar cualquier permiso que desee. Usé reports_taxes. Esto debería evitar que los iconos se muestren en la tabla de elementos.
You can try this. Go to application\helpers\tabular_helper and change the bottom of the function get_item_data_row to the following. You can use any permission you would like. I used reports_taxes. This should prevent the icons from showing in the Items table.
```
if($CI->Employee->has_grant('reports_taxes', $CI->session->userdata('person_id')))
		{
			return $columns + expand_attribute_values($definition_names, (array) $item) + $icons;
		}		
		else
		{
			return $columns + expand_attribute_values($definition_names, (array) $item);
		}
```
