### ISSUE TITLE
Limit number of digits in quantity box of Sales module

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3004]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Is there any way to limit the number of digits that can be entered in the quantity box for an item in the sales module?  I think what's happening is we're clicking on the quantity and entering a value and then scanning another barcode without hitting enter first or clicking outside the box.  The barcode gets entered in the quantity box with a carriage return and we don't notice.  It's so big a value it gets ignored in the calculations.  

Thanks

**Comment by chunter2** [comment]
Here's a screenshot of what's happening.  Would someone be able to point me in the direction of where I might be able to set the characteristics of the quantity box?  
![quantity](https://user-images.githubusercontent.com/531129/98386828-a9836380-201e-11eb-9f1c-88e2c0c747cf.jpg)
Thanks

**Comment by odiea** [comment]
I don't know if this would help you out. In application/views/Sales/Register.php locate and change the following line of code.
```
echo form_input(array('name'=>'quantity', 'class'=>'form-control input-sm', 'value'=>to_quantity_decimals($item['quantity']),'maxlength'=>2,'tabindex'=>++$tabindex, 'onClick'=>'this.select();'));
  ``` 
I just added the 'maxlength'=>2,to it.

**Comment by chunter2** [comment]
That works perfectly.  Thanks.  I'm guessing this is still a bug but maybe the maxlength sould be a feature to be added where maxlength is configurable from the GUI?

**Comment by jekkos** [comment]
Not sure how you would distinguish this type of input otherwise. The default focus of this screen is the item_number  so if you open the screen then anything you scan will go right into this box.

I believe that if you enter any quantity, the screen refreshes and if you scan a barcode after, it should go in the correct place.

**Comment by jekkos** [comment]
Also if you think it could be imrpoved otherwise, feel free to make any suggestions

**Comment by chunter2** [comment]
I think the focus on the item_number box is correct and more training needs to be done with our cashiers.  No problem there.  Adding the maxlength is just a work around so that the item can still be calculated.  Here's a screen shot of when the item quantity is less than what we're trying to sell but not huge.  You can see it calculates the total of the item anyways even though there's not enough.  I think the bug is for huge numbers the value isn't calculated and because of that not caught.  Maybe some coding type is being overflowed and a limit should be set somewhere?  
![quantity2](https://user-images.githubusercontent.com/531129/98455150-ca40db80-213a-11eb-8197-05480bf7c6b4.jpg)

**Comment by jekkos** [comment]
I think at least you'd see a warning that your stock quantity is insufficient? That might already ring a bell no?

**Comment by chunter2** [comment]
Yes, you get a warning but it doesn't calculate the total because the quantity must be overflowing something.  If you look at my first screenshot you'll see the second item has a huge quantity but a zero in the total for that item.  It basically skips it altogether.

**Comment by jekkos** [comment]
Ok it might not behave as expected then. I will have look.

**Comment by jekkos** [comment]
I just tried to reproduce this one and indeed, it seems to overflow if you enter more than 14 digits. This is exactly the default precision of a `[float in PHP](https://www.php.net/manual/en/language.types.float.php)`
f

**Comment by jekkos** [comment]
Also did a double check on what kind of precision that might be needed to make this work in regions with hyperinflation.. in Zimbabwe 1^22 currency units were exchanged for 1 dollar around 2009.. so we might need to review and do a proper fix in the future.

**Comment by jekkos** [comment]
Fixed and in master. Will close.
