### ISSUE TITLE
OSPOS goes back to login page when sales items reaches ~120-140

### ISSUE THREAD

**Issue by mgmamac** [opensourcepos/opensourcepos#3006]
Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

Installation information

- OSPOS version is: 3.3.2(release)
- OSPOS git commit hash is: bb309c2 (Is this it? I'm not sure.)
- PHP version is: 7.3.21
- MySQL or MariaDB version is: 5.7.31
- OS and version is: Windows 10 64bit 
- WebServer is: Wampserver 3.2.3 64bit
- Selected language is: 1909
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

Issue / Bug  / Question / New Feature

Hello! I'm not really knowledgeable in web and database stuff. I was able to make OSPOS work by following instructions from your documentation and youtube videos. I'm hoping that I can help a little by reporting the issue I encountered.

When inputting items on sales tab, once the number of items reaches somewhere ~120-140, the search bar won't show any product whatever you type in. When that happens, if you click any button on the webpage, it will take you back to login page. It happened without fail on 3 consecutive retries even after reboot. If I relogin, all my progress on inputting items on sales tab is gone. I was able to "bypass" the issue by breaking down the sale into 2 or 3 batch of receipts.

I'm using Firefox 92.0.2 64bit.

Thank you!

**Comment by jekkos** [comment]
@mgmamac kind of hard to help based on this information.. you'll need to post some kinf of error log first. Maybe check your chrome network console to see if there are any status 500 responses and then post the response body here.

**Comment by ozzylamberth** [comment]
I have entered a total of 350 articles in the sales module in both versions 3.2 and 3.3 and it works without problem except a little slow in the CRUD

Eh ingresado un total de 350 articulos en modulo de venta tanto en la version 3.2 como en la 3.3 y funciona sin problema salvo un poco de lentitud en el CRUD

**Comment by jekkos** [comment]
I don't think there is anything we can do here unless you provide more information.

**Comment by WebShells** [comment]
Issue confirmed

**Comment by WebShells** [comment]
ERROR --> Severity: Warning --> session_start(): Failed to decode session object. Session has been destroyed /maindir/vendor/codeigniter/framework/system/libraries/Session/Session.php 143

**Comment by WebShells** [comment]
I think it's related to session regeneration destroy  ?

**Comment by jekkos** [comment]
@WebShells were you able to reproduce this issue on your install then?

**Comment by jekkos** [comment]
Bump @WebShells ?

**Comment by WebShells** [comment]
@jekkos this happened after reaching a limit of 100 items in receivings ( 3 to 5 mins )

**Comment by jekkos** [comment]
@WebShells You are probably bumping into the 64 Kb limit of the blob session data column. It's already quite a lot and way more than the initial 4kb cookie limit.
We could increase the column size to MEDIUMBLOB (16MB) which should be enough for most usecases. But this might come with a performance hit.

**Comment by jekkos** [comment]
@ozzylamberth can you try the migration in my pull request, to see if this works and if performance is acceptable?

**Comment by objecttothis** [comment]
@jekkos is a longblob overkill here?  I think a mediumblob would be more efficient, but don't know for sure.

**Comment by jekkos** [comment]
I think it's mediumblob now (I might still have this message in the commit history, but I fixed the type afterwards).

**Comment by jekkos** [comment]
Closing this one for now. @ozzylamberth let me know if any issue otherwise.
