### ISSUE TITLE
Taxes to 0 on small sales

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#3008]
Hello .. This is not an error.
I am looking for a way to not apply taxes to small sales .. for example if I sell a Coke, do not apply taxes. in a way that from the sales module, taxes can be set to 0 .. 

thank you very much

**Comment by jekkos** [comment]
Maybe you can use the destination tax in some way here? Not sure if possible. @SteveIreland is our expert in these matters.

**Comment by andriux1990** [comment]
@jekkos if i've been trying to do this .. i'm still looking for a way to do it.
@SteveIreland If you have an idea or suggestion I would really appreciate it.

**Comment by jekkos** [comment]
I thought that maybe you can add a tax destination with 0 tax and then select that destination for this specific product.

**Comment by andriux1990** [comment]
I already tried it ... and it works, but if I have two taxes and I want to charge only one tax, this would not work, because it applies to both taxes

**Comment by SteveIreland** [comment]
I like the suggestion of setting up multiple "house customers", each with a different tax destination code configured for the various configurations you want to support.

**Comment by jekkos** [comment]
@andriux1990 can't you setup one destination with two taxes and then the other with one only, then switch destination according yo your usecase
