### ISSUE TITLE
Tax name in: Taxes Summary Report

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#3009]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

There are two fields to add taxes to a product:
Tax 1
Tax 2
![taxis](https://user-images.githubusercontent.com/29256343/98995586-27e87580-24f7-11eb-8279-8d8a10f97f27.png)

but to see the reports in Taxes Summary Report, it does not show the name of the tax .. it would be great if the name of the tax would appear .. in order to know with certainty which is which
![taxi](https://user-images.githubusercontent.com/29256343/98995842-90cfed80-24f7-11eb-8df9-d32e0336dcbd.png)

**Comment by jekkos** [comment]
Sure this one is not so hard to add, check the last addition by @chunter2 as example and try to add this yourself?

**Comment by andriux1990** [comment]
@jekkos Ok .. I'll do it

**Comment by jekkos** [comment]
@andriux1990 let me know if you need help.. would be good to have a PR for this. Thanks!
