### ISSUE TITLE
Panama Fiscal Printers

### ISSUE THREAD

**Issue by jadoux** [opensourcepos/opensourcepos#3010]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2 - bb309c
- OSPOS git commit hash is: 
- PHP version is: 7.4.12
- MySQL or MariaDB version is: 5.5.62
- OS and version is: ubuntu 14.04
- WebServer is: Apache/2.4.46 (Unix) 
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question / New Feature

Hi
I would like to hire someone familiar with Fiscal Printers in Panama, I can pay for this someone to help me integrate OSPOS with a fiscal printer (Bixolon SP-330II)

I have no idea what is required to make this work, so ask me the questions and I will try to find answers, but I am not a printing expert, and have no idea how this system works

Thanks in advance

**Comment by mckaygerhard** [comment]
i am at panama and i develop a integration with thos fiscal printers.. @jadoux

**Comment by jadoux** [comment]
@mckaygerhard thanks, you can get in touch at 69931111

**Comment by mckaygerhard** [comment]
@jadoux  use telegram i will send you message.. if you dont have installed will lost the contact
