### ISSUE TITLE
Search by Custom Attirbutes

### ISSUE THREAD

**Issue by chrisvell88** [opensourcepos/opensourcepos#3013]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue  Question 

Is it possible to make custom attributes searchable in the Items view?

Thanks,

**Comment by odiea** [comment]
It is already. Just use the dropdown and enable search attributes

**Comment by chrisvell88** [comment]
Hi odiea, 

Its not working well then. Please refer to attached screenshots. I have Brand selected to search. Typed HP in search and only got 2 results, one of which is not even branded HP. Moreover, in the last screenshot you can see the number of items containing brand HP and not being returned in search. 

Can you kindly advice?
![brand](https://user-images.githubusercontent.com/49901801/99297136-1d581400-2848-11eb-9768-56387e8e9c99.png)
![results](https://user-images.githubusercontent.com/49901801/99297138-1e894100-2848-11eb-9516-41f9639389ac.png)
![results2](https://user-images.githubusercontent.com/49901801/99297141-1f21d780-2848-11eb-9607-4aa4404e7982.png)

**Comment by odiea** [comment]
![2020-11-16 12_18_53-Window](https://user-images.githubusercontent.com/10962177/99297830-04c70a00-2806-11eb-9c68-4f19e582bf68.png)

**Comment by odiea** [comment]
What you showed was the dropdown for the columns to be displayed not the search.

**Comment by jekkos** [comment]
Maybe check #2764

**Comment by chrisvell88** [comment]
You have 3 screesnhots depicting all steps one by one @odiea

**Comment by odiea** [comment]
And you did not pay attention to what I stated or showed to you

**Comment by odiea** [comment]
1. Go to Items.
2. Click on Select then choose Search Attributes.
3. Add the attribute you are looking for in the search box.
Then the attribute you selected should show as expected.

**Comment by chunter2** [comment]
I wonder if maybe he wants to filter by attribute but still search that filtered list by item name.  Could that be the confusion?  I'm not sure that's possible but would be nice.

**Comment by odiea** [comment]
What I can see from the images is he never enabled Search Attributes in the Item Table. Yes it would be nice to have multiple searches available for the Items table.
