### ISSUE TITLE
Change in Email Bill format

### ISSUE THREAD

**Issue by saurabh261187** [opensourcepos/opensourcepos#3019]
### Installation information

OSPOS version : opensourcepos.org · 3.3.3 - 2393c2.
Server Software: Apache/2.4.29
PHP Version: 7.2.24-0ubuntu0.18.04.7
MYSQL DB Version: 5.7.32-0ubuntu0.18.04.1

### Issue / Bug  / Question / New Feature

Before updating my ospos version from 3.3.2 to the above version from the unstable build opensourcepos.20201115225224.master.2393c2 , the Email bills in PDF format sent to the customers looked like this :

![earlierpdfformat](https://user-images.githubusercontent.com/15091342/99664723-a1034200-2a8e-11eb-8d47-47202a91bfbb.png)

However, after the update, although all the settings are the same, it is looking like this :

![currentpdfformat](https://user-images.githubusercontent.com/15091342/99664783-baa48980-2a8e-11eb-83c7-dc1466fc126d.png)

Please guide me if I have done something wrong, or have gone wrong in some configuration.

**Comment by odiea** [comment]
It appears you are missing the invoice.css file.

**Comment by jekkos** [comment]
@odiea how did you conclude that?

**Comment by odiea** [comment]
It appears that there is no Invoice.css formatting.

**Comment by jekkos** [comment]
@saurabh261187 can you try master build and report back if this fixes the issue?

It might be that in certain setups the css file was not found (as I think that base_url did not include the public part in the URL). In fact if the css lookup happens relative to the current page it should be fine. It's also consistent with the CSS href's in the header.php now.

**Comment by jekkos** [comment]
I have done a quick test locally and PDF generation seems fine now. I close.
[Invoice.pdf](https://github.com/opensourcepos/opensourcepos/files/5694469/Invoice.pdf)

**Comment by odiea** [comment]
@jekkos I just tried sending an Invoice.pdf and it still appears to be an issue. I am using the current bower update branch. 
[Invoice-INV-20000599.pdf](https://github.com/opensourcepos/opensourcepos/files/5736600/Invoice-INV-20000599.pdf)

**Comment by jekkos** [comment]
Ok I'm no certain but think bower-update was branched some time ago.. so it might not contain this fix yet.

**Comment by jekkos** [comment]
Might be better to verify on master instead? At least I addded evidence after testing and closing.

**Comment by odiea** [comment]
@jekkos Did you try sending yourself an Invoice.

**Comment by jekkos** [comment]
Yes emails are not configured currently on dev server..

**Comment by jekkos** [comment]
I checked the generated pdf file in the tmp folder on the docker container instead. So that is the file that is attached to the email.

I did not check the email receipt yet though.

**Comment by daN4cat** [comment]
@odiea, @jekkos, shall we close this one? It's tagged 3.3.3.

**Comment by odiea** [comment]
@daN4cat I am still having issues with the way the pdf is looking after being sent. It appears not to have the invoice_email.css working.

**Comment by odiea** [comment]
This is the fix I now have to use for Invoice Emails to show properly. I don't know if they have changed their security setup?
In dompdf/dompdf/scr options I changed lines 160 and 182 to true.
In Invoice_email I had to revert back to the original css
```
	<link rel="stylesheet" type="text/css" href="<?php echo base_url() . 'css/invoice_email.css';?>"/>
```
 and then changed the logo to the receipt logo due to the logo not showing
```
<div id="company_name">
<img id="image" src="data:image/png;base64,<?php echo base64_encode(file_get_contents('uploads/' . $this->config->item('company_logo'))); ?>" alt="company_logo" />
</div>
```

**Comment by daN4cat** [comment]
@jekkos could you please fix this? I'm fixing an issue with sales register that I found testing this evening.

**Comment by jekkos** [comment]
@odiea thanks for the fix suggestion, great work. I've created a branch with those fixes.

**Comment by jekkos** [comment]
[Invoice1.pdf](https://github.com/opensourcepos/opensourcepos/files/5748820/Invoice1.pdf)

**Comment by jekkos** [comment]
The number box seems a bit off still

**Comment by jekkos** [comment]
@odiea good that you have the image back in there, I'll need to take a look to see how we can embed the correct image format.

**Comment by odiea** [comment]
The following also needs updated for the company logo to show.
```
<img id="image" src="data:image/png;base64,<?php echo base64_encode(file_get_contents('uploads/' . $this->config->item('company_logo'))); ?>" alt="company_logo" />
```

**Comment by odiea** [comment]
I tried this in a previous version and it works great.

**Comment by jekkos** [comment]
@odiea thanks for the tip, only concern I had is the mimetype, it can be different then png I suppose

**Comment by jekkos** [comment]
@odiea The mimetype should now be correctly set in this last commit. I have tested this with a local png upload.
[Invoice1.pdf](https://github.com/opensourcepos/opensourcepos/files/5750486/Invoice1.pdf)
