### ISSUE TITLE
demo is down

### ISSUE THREAD

**Issue by C0deGyver** [opensourcepos/opensourcepos#3020]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

okay... technically not about an install..... I tried to go to the demo to try this out but keep getting "502 Bad Gateway"

**Comment by C0deGyver** [comment]
it is now back up

**Comment by odiea** [comment]
A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: core/CodeIgniter.php

Line Number: 518

**Comment by jekkos** [comment]
OK thanks for bringing this to my attention @odiea . I checked the logs and saw that both databases had disappeared.. pretty weird. The logs seemed to indicate that the sql severs did crash and a recovery was needed.

I checked and the default user has rights to drop tables but also the whole db. I will enable some more logging now to investigate further if it happens again.

**Comment by odiea** [comment]
Demo and Dev Servers are down apparently with no warning messages sent.

**Comment by jekkos** [comment]
I did get some warnings and indeed the servers are [down](https://status.opensourcepos.org/).
Issues are automatically created in this [repo](https://github.com/opensourcepos/upptime/issues)

actually I was looking into this this morning but gave up after a while.

**Comment by jekkos** [comment]
Back up again.

**Comment by odiea** [comment]
502 Bad Gateway
nginx/1.18.0 (Ubuntu)

**Comment by jekkos** [comment]
Should be good now .

**Comment by odiea** [comment]
502 Bad Gateway
nginx/1.18.0 (Ubuntu)
