### ISSUE TITLE
instalación ospos 3.3.2 en subdominio

### ISSUE THREAD

**Issue by emmanuelff** [opensourcepos/opensourcepos#3023]
hi, i'm trying to install ospos in a subdomain, the provider is ipage, and i get the error 500 "Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log. "

when I check the log server on the server I don't see any files.

**Comment by rocky8roy** [comment]
hi
I can provide installation support for a fee!
if you are interested then you can contact me on rocky8roy@gmail.com

**Comment by andriux1990** [comment]
Your @emmanuelff .. you are violating the ospos license.
https://bagents.net/webba
https://nicapos.bagents.net/login

They are violating the license
