### ISSUE TITLE
OSPOS LOGOUT ISSUE

### ISSUE THREAD

**Issue by tm-tomal** [opensourcepos/opensourcepos#3025]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2 
- OSPOS git commit hash is: 
- PHP version is: 7.3
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: PHP
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi, 
Recently I update my OSPOS software, and last two days are in my software automatic logout within mins, I mean every minute are getting automaticlly logout.

**Comment by odiea** [comment]
You can try looking thru these to see if it helps.
https://github.com/opensourcepos/opensourcepos/search?q=auto+logout&type=issues

**Comment by jabad9999** [comment]
hi, is there any body can help me about logout issue. i uploaded ospos files as sub-domain -> ospos.mysite.com and everything working perfectly except logout, when i click logout its goes to home page why??? its suppose to go to login page but not!
