### ISSUE TITLE
SMS on sale complete module is available now for usd 99 only

### ISSUE THREAD

**Issue by rocky8roy** [opensourcepos/opensourcepos#3027]
Hi,
I have seen many people asking for this feature
I have implemented it and If anyone want it kindly contact me on rocky8roy@gmail.com to discuss further
I will implement it and integrate it in your ospos script for a fee.
thank you!

**Comment by odiea** [comment]
As a notice: @opensourcepos/org team doesn't hold any responsibility for any task or job assigned or accomplished by any third-party freelancers.
Please notice that the process isn't verified by any of the project developers nor team members thus you should do it at your own responsibility.
In case the job wasn't accomplished as agreed on @opensourcepos/org will not hold any responsibility about it.

**Comment by jekkos** [comment]
Sorry I close, our issue tracker is not a free advertisement channel
