### ISSUE TITLE
Third Party Freelancers Notice

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3028]
Thanks @WebShells 
As a notice: @opensourcepos/org team doesn't hold any responsibility for any task or job assigned or accomplished by any third-party freelancers.
Please notice that the process isn't verified by any of the project developers nor team members thus you should do it at your own responsibility.
In case the job wasn't accomplished as agreed on @opensourcepos/org will not hold any responsibility about it.

**Comment by jekkos** [comment]
Maybe this is something we should add to the README.md? Or Contributors file?

**Comment by odiea** [comment]
Currently this is a just a warning for people that want others to do their changes.

**Comment by WebShells** [comment]
I think we can pin it in the issues section. Maybe we should rephrase to cover several sections.

**Comment by odiea** [comment]
@WebShells I like your idea about pinning it.

**Comment by WebShells** [comment]
Lets fix a final statement that wouldn't put us in any responsibilities in case of any issues in any third party job. Will handle it

**Comment by jekkos** [comment]
OK I have pinnned the issue now it's clearly visible.
