### ISSUE TITLE
Can't Refund 

### ISSUE THREAD

**Issue by seanrs** [opensourcepos/opensourcepos#3031]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 
- PHP version is: 7.4.11
- MySQL or MariaDB version is: 10.4.14-MariaDB
- OS and version is: Windows 10 Pro 64bit, 2004
- WebServer is: XAMPP v3.2.4, Apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

For example, when you go to Sales, then select Invoice and then add items. Let say, you add 1 item, and it costs 10 USD, then on amount tendered type 5 USD and click add payment, then click on invoice. Go to Daily Sales and find that invoice, click on update and you will see refund type below the payment type. Now, i will choose another payment type and put 8 USD, which is 3 USD over, then click update. The refund is zero, Is it suppose to be that way?
However, if i go to sales, and then select invoice and add item for 35 USD, then choose payment as cash and on amount tendered type 20. Then, choose another cash and type 20, and click invoice. Go to daily sales, find that invoice and click update. You will see 40 USD for payment type cash and refund type cash of 5 USD.

====The problem is that after generate the invoice, and then try to add payment later, refund doesn't update its amount.====

**Comment by WebShells** [comment]
Please fill in issue template and describe the problem in details so we can better support you.

**Comment by seanrs** [comment]
Can't add refund in Invoice

**Comment by jekkos** [comment]
@seanrs How do you mean add a refund? Return the whole invoice?

**Comment by odiea** [comment]
It appears that hew would like to add more then 2 payments to his Invoices?

**Comment by seanrs** [comment]
> @seanrs How do you mean add a refund? Return the whole invoice?

For example, when you go to Sales, then select Invoice and then add items. Let say, you add 1 item, and it costs 10 USD, then on amount tendered type 5 USD and click add payment, then click on invoice. Go to Daily Sales and find that invoice, click on update and you will see refund type below the payment type. Now, i will choose another payment type and put 8 USD, which is 3 USD over, then click update. The refund is zero, Is it suppose to be that way? 
However, if i go to sales, and then select invoice and add item for 35 USD, then choose payment as cash and on amount tendered type 20. Then, choose another cash and type 20, and click invoice. Go to daily sales, find that invoice and click update. You will see 40 USD for payment type cash and refund type cash of 5 USD.

====The problem is that after generate the invoice, and then try to add payment later, refund doesn't update its amount.====

**Comment by odiea** [comment]
Now I understand. When an overpayment is done thru the update modal and an overpayment is made it is not updating the refunding amount where the Daily Sales table ,Invoice and Receipt are showing the Refund amount or Change due amount
,

**Comment by SteveIreland** [comment]
I'm working in this arena anyway, so I'll incorporate it.

**Comment by objecttothis** [comment]
> 
> 
> I'm working in this arena anyway, so I'll incorporate it.

@SteveIreland do I understand correctly that when #3026 gets merged, this issue will be resolved?

**Comment by SteveIreland** [comment]
Just tested this in the latest iteration of the #3026 pull request and it adds the over-payment and creates a cash refund transaction for the amount to be refunded.   So the answer is "I hope so."  :-)

**Comment by odiea** [comment]
Looks good here. Modal shows a refunded amount and so does the receipt. Great work @SteveIreland

**Comment by odiea** [comment]
It also appears to be correct with a Cash payment and a Credit card over payment.

![2021-02-07 14_15_50-Window](https://user-images.githubusercontent.com/10962177/107159740-3d7f0700-694f-11eb-959d-3028cdf3d5b0.png)

**Comment by jekkos** [comment]
Ok and I wonder how do we handle old data? I might have missed sth but saw in the migration that we have a cash_adjustment field now, but it might need to be backfilled?

**Comment by SteveIreland** [comment]
I considered it but felt there were too many unknowns that would need to be evaluated for each site.  I felt I would probably end up changing sales that didn't reflect what actually happened because the sale was done manually since the system didn't support what needed to happen.
