### ISSUE TITLE
Receivings return has inaccurate info.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3033]
I created a Receiving with 1 Item. You can see by the image what is happening when I try to Return that Receiving.  I believe this is also happening with earlier versions.

OSPOS Installation Info: 3.3.3 - e72dc7
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
.PHP Version: 7.3.2
.DB Version: 5.7.21
.Server Port: 80
.OS: Windows NT 10.0

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [import_customers.csv:] - 0666 | Readable ✓ | Vulnerable or Incorrect Permissions ✗

Security Vulnerability Warning
Incorrect permissions leaves this software at risk.

» [application/logs:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads/item_pics:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [import_customers.csv:] is readable, but the permissions are incorrectly set. Please set it to 640 or 660 and refresh.
America/Denver

![2020-11-25 11_23_50-Odies Test _ Powered by OSPOS 3 3 3](https://user-images.githubusercontent.com/10962177/100267538-d38ac000-2f10-11eb-9dc0-4b3ef16ae9b3.png)

**Comment by jekkos** [comment]
The total seems off ?

**Comment by odiea** [comment]
Yes it does. Sorry I should have noted that in the issue.

**Comment by jekkos** [comment]
Ok think I have found the culprit. Good find.

**Comment by jekkos** [comment]
Should be fixed in master now.
