### ISSUE TITLE
Unknown Change Due in Daily Sales or Takings after updating.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3041]
OSPOS Installation Info: 3.3.3 - e72dc7
Language Code: en-US

OSPOS Timezone is Different from your Local Timezone.

Local Timezone:
America/Denver

OSPOS Timezone:
America/New_York

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.2
.PHP Version: 7.3.2
.DB Version: 5.7.21
.Server Port: 80
.OS: Windows NT 10.0

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [import_customers.csv:] - 0666 | Readable ✓ | Vulnerable or Incorrect Permissions ✗

Security Vulnerability Warning
Incorrect permissions leaves this software at risk.

» [application/logs:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads/item_pics:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [import_customers.csv:] is readable, but the permissions are incorrectly set. Please set it to 640 or 660 and refresh.
America/Denver

This is the table view before using the update modal in Daily Sales.

![2020-12-09 13_01_29-Window](https://user-images.githubusercontent.com/10962177/101681156-f80d8e80-3a1e-11eb-9cd9-9b4e919c96be.png)

Here is the table view after submitting the update modal in Daily Sales. Any idea what might be going on. After refreshing the table view it looks like the first screen shot.

![2020-12-09 13_01_13-Window](https://user-images.githubusercontent.com/10962177/101681464-68b4ab00-3a1f-11eb-81f7-94b001cfd07e.png)

**Comment by SteveIreland** [comment]
I'll take a look at this one too.

**Comment by odiea** [comment]
I did not update anything I just clicked on Submit. Thanks for all you help.

**Comment by SteveIreland** [comment]
I was able to replicate the issue tonight and also confirmed that it is just a reporting issue and that the changes are not reflected in the database.  This looks like something I should be able to include in my cash rounding fix which, if there are no crises, should be in its final form this weekend.

**Comment by odiea** [comment]
@SteveIreland as a non programmer I resolved this issue by adding in Tabular_helper  $change_due = ($sale->amount_due - $sale->amount_tendered); in function get_sale_data_row($sale). You can probably come up with a better idea.

**Comment by mckaygerhard** [comment]
this #3041 needs attention: stale bot will close and is a confirmed bug

**Comment by SteveIreland** [comment]
Pull request #3026 includes the fix for this.

**Comment by odiea** [comment]
@SteveIreland thanks. I downloaded this commit and the issue is no longer there. Good work.
