### ISSUE TITLE
Add item, add payment, edit item discount, transaction is completed with an amount due

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#3042]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3.latest_master
- OSPOS git commit hash is: 
- PHP version is: 7.3
- MySQL or MariaDB version is: 10.3
- OS and version is: CentOs
- WebServer is: Apache
- Selected language is: en_GB
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Scenario:

- add item
- add debit card payment to match item price
- discount item 
- page is automatically refreshed
- an amount due is automatically added
- employee clicks complete (without paying attention)
- a cash amount due is added to match the overpayment with debt card
- a receipt is printed with cash to be returned to the customer

This scenario drove me mad, because they couldn't explain me and I couldn't figure out how they could have a weird payment until I realised that adding a discount later alters the due amount.

I wouldsay that if an item discount is touched after having entered the payments, payments are reset to avoid this mistake.

The worst part is that in order to edit the payment they were editing the transaction making the due cash disappear but leaving the wrong debit card payment in. End of the day report is wrong and that's why employees complained.

**Comment by jekkos** [comment]
@daN4cat in case you add a discount after payments are added, I would say that it would make sense to have an amount due only if they pay cash. 
If they are paying using 100% credit or debit card, I suppose it does not make sense to give them an amount due, unless a customer eg asks to have some cash on top of his payment. This latter case sometimes does happen as people find it easier or cheaper then going to an ATM to withdraw.

**Comment by daN4cat** [comment]
I prefer to reset the payments to none to avoid the issue.

**Comment by jekkos** [comment]
Not sure if that makes sense. Why don't they just remove the payment manually then? I think you can't really make too much assumptions here, the discount should have been applied before the payment addition.

If the payments are wrong after adding a discount they could also just remove the payments manually and add them again?

**Comment by SteveIreland** [comment]
So, the concept of change the price, discount, or quantity after the payment has been received wasn't something I ever expected.  My assumption has always been that the payment transactions would be cleared and re-added.  I definitely need for this to be the case for the way I'm currently handling cash rounding transaction.

I vote for automatically removing payments if there are any changes that cause a change in the sales amount.  If we don't then I need to redo how I'm handling that cash adjustment transaction because it depends on the total sales amount not changing after the cash payment is processed.  

So I will be watching for the final decision.

**Comment by chunter2** [comment]
I believe this is where I first ran into issues with @SteveIreland 's initial cash rounding to the nearest 5 cent commit.  I believe the complete button showed up even though amount due was negative.  And this may be part of his fix?

**Comment by daN4cat** [comment]
@jekkos the reality is that now with discounting full steam due covid-19 mess I see plenty of errors. There is no way to control it and it's better to reset  than figure out rules. It's also dangerous to emit a receipt stating an amount due because customers can come back and claim money they didn't receive. CCTV footage will be on their side because there was no cash handling.
It complicates the matter too much.

**Comment by daN4cat** [comment]
Also, sales assistants focus on customers during the transaction and expect few clicks to do it for them.
Alternative would be to block the editing of items with a payment set. But that constraints the matter.

**Comment by daN4cat** [comment]
I've committed the change to empty payments on item edit change.
Receivings doesn't have any similar behaviour so there is no reason to empty payments.
However, should we add a similar multipayment story we would need to add to Receivings too.

**Comment by jekkos** [comment]
@daN4cat the order of action still sounds a bit weird.. we would only ask a customer to pay after we know what the total amount is, and then ask for the payment method preference. 

But I agree we should limit the room for error.
* If we force them to clear payments manually, then intuitively they know they need to add the payment again after edit (as they removed it first)
* If we clear the payments then the user might be confused as she will notice that the complete button is greyed out. But you only have one extra click here to do

I'm ok with both, my intuition says that the second option might be less work..

**Comment by daN4cat** [comment]
That's the purpose, if it's greyed out pay attention to the new total.

I committed the reset. Believe me, as much as you can remind people, they will not follow the process you have in mind and it's better to follow them and prevent the mistakes.

Also @SteveIreland says that without this step his part won't work properly.

**Comment by chunter2** [comment]
I like this change but have another use-case I run into that I don't know how to fix.  In my case the cashiers don't click the complete button until they've processed the debit or credit through the payment terminal.  Once that's approved they click complete.  The problem is if the client doesn't want a receipt from ospos they forget to click complete.  Then they start scanning for the next client without looking at the screen.  What happened before this commit is it adds on to the previous customer and the cashier doesn't notice.  Now I'm not sure what they'll do in this case.  I'm not sure what the proper solution is but would it be an idea to disable the item box or pop up an message box saying to either complete the last sale or remove the payment?  Only for adding more items though?  I really don't know what I should do in this case.  

Thanks

**Comment by jekkos** [comment]
@chunter2 in this case you suggest that the first option would be better? 

That was also my first point, we can't make too much assumption on what a user is doing (or doing wrong). So it's probably more defensive to block the input.

**Comment by daN4cat** [comment]
To do not press the complete button has nothing to do with this change.
No matter previous or current, if you don't click complete you can keep adding as much as you like and still don't press complete.

**Comment by chunter2** [comment]
@jekkos Could we have both?  The problem is when the cashiers don't look at the screen.  So maybe keep this commit for everything but the item input box?  And for that box display an error/warning when something is entered to either complete the sale or remove the payment?

**Comment by daN4cat** [comment]
That doesn't solve the problem of not clicking complete.

**Comment by chunter2** [comment]
@daN4cat Yes, I agree we still need this commit.

**Comment by daN4cat** [comment]
@jekkos to answer your question, they sell one discounted item and process the payment reading the new price from the tag. That's why they mix up sequences. If we had one integrated pos and payment, we would not have this issue.

**Comment by chunter2** [comment]
Maybe I should be creating a new issue.  Basically I want the barcode scanner to stop working if a payment was entered.  And yes, one integrated pos and payment system would fix this.  :)

**Comment by daN4cat** [comment]
@chunter2 that's a different issue. Please create a new one for that request, however I must say that often there are last minute sales when they get to the desk. Usually small accessories and those can be easily added after they added the payment whilst talking with the customer.

**Comment by chunter2** [comment]
@daN4cat I'm not quite following your use case.  Do they then add a second payment to cover the item that was just added after the first payment was added?  If for example they choose debit on the first payment do they just choose debit again for the second payment?

**Comment by daN4cat** [comment]
@chunter2 yes, you get extra to add and if you add with the same payment method it adds up to the previous one. I don't see an issue here with this flow, I mean there is no potential for mistake unless, again, you don't click "complete". But that's anyway something you need to do.

**Comment by chunter2** [comment]
@daN4cat One inconsistency of this then is the following.  Say you scan item x, then add a payment and then change the quantity for item x.  The payment gets removed.  If you scan item x, then add a payment and then scan item x again to increase the quantity the payment doesn't get removed.

**Comment by daN4cat** [comment]
The original issue here was when you discount not add. However the edit item is one so you get the same effect no matter what you touch.
Having said that, people can do what they want, I'm just trying to minimise the obvious mistakes.
