### ISSUE TITLE
Click quickly twice submit button and entries are duplicated

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#3044]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3.latest_master
- OSPOS git commit hash is: 
- PHP version is: 7.3
- MySQL or MariaDB version is: 10.3
- OS and version is: CentOs
- WebServer is: Apache
- Selected language is: en_GB
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Scenario:

- add 1 customer with email address
- click the Submit button quickly twice
- dialog box closes
- two pop up notifications
- two customer accounts created with the same email address violating the email uniqueness

Submit button must be deactivate after the first click.

I now found out how they manage to create two customers with the same email in sequence.

**Comment by daN4cat** [comment]
We should disable the double click on Submit, they probably double click it causing the problem.

**Comment by daN4cat** [comment]
@jekkos I assigned this to you because you worked on the forms, I can't remember how they work and how we could avoid this double click.

**Comment by daN4cat** [comment]
Some hints: https://stackoverflow.com/questions/8165018/duplicate-data-insert-in-codeigniter/8165979#8165979

**Comment by jekkos** [comment]
I would expect the form to close when clicking submit. Only when you hit the new button it will stay open as a user is probably inserting a batch of new products.

**Comment by daN4cat** [comment]
It's not like that, try and double click submit button and see what happens.

**Comment by jekkos** [comment]
Do you have csrf enabled? I would expect this to block a double submit.

**Comment by jekkos** [comment]
![Screenshot from 2020-12-16 21-47-06](https://user-images.githubusercontent.com/576234/102404669-5078f900-3fe8-11eb-8f74-0748de7a0a07.png)

did a quick test on demo, and indeed, second request is blocked as the token is invalid..

**Comment by jekkos** [comment]
![Screenshot from 2020-12-16 21-53-07](https://user-images.githubusercontent.com/576234/102405256-26740680-3fe9-11eb-9908-b10fae795a05.png)
same behavior for customers

**Comment by daN4cat** [comment]
yes, csrf is enabled but I still get the issue.

**Comment by daN4cat** [comment]
The two submit in y case have different csrf values

**Comment by daN4cat** [comment]
I've just created a double entry in demo.opensourcepos.org:

![Screenshot from 2020-12-16 21-06-10](https://user-images.githubusercontent.com/636048/102406613-be222680-3fe2-11eb-8a8c-7876bfd12d6a.png)

**Comment by daN4cat** [comment]
I can reproduce exactly the same issue with demo. Just double click on submit.

**Comment by odiea** [comment]
Here is what I got testing. @daN4cat is correct with this being an issue.

![2020-12-16 14_11_32-Window](https://user-images.githubusercontent.com/10962177/102407082-c0678f00-3fa8-11eb-9cd8-b27bc5e4d9f1.png)
![2020-12-16 14_11_14-Window](https://user-images.githubusercontent.com/10962177/102407096-c6f60680-3fa8-11eb-98a7-928eae7c631e.png)

**Comment by daN4cat** [comment]
Got more about the issue, make sure the names are short like two letters.

**Comment by jekkos** [comment]
I tested on mozilla and couldn't create a duplicate... I tried to click really fast.. curious

**Comment by daN4cat** [comment]
just put 1 letter for name and surname

**Comment by jekkos** [comment]
I would try to add something in the manage_tables to check the dialog state so that it disables the second submit..

**Comment by daN4cat** [comment]
Yes please, this is causing issues. Thanks.

**Comment by jekkos** [comment]
@daN4cat check my PR I think that solves your issue.

**Comment by daN4cat** [comment]
Tested and works as expected. Brilliant! Thanks a lot, this now solves and explains the double entries.
I merged the PR and I'm going to close this.

**Comment by daN4cat** [comment]
@jekkos, there is an issue with this fix and here how it fails:

- go to customer, items or suppliers
- edit one entry
- now empty one of the mandatory boxes to cause an error
- click submit to cause the error notification to pop up
- click the X on the form on the top right to close the box (no change)
- reopen the same entry
- click submit as not changes
- the form will not close

**Comment by jekkos** [comment]
@daN4cat I have pushed a fix for this to master. Verified locally and looks fine on my end.

**Comment by daN4cat** [comment]
@jekkos still the same problem.

**Comment by jekkos** [comment]
Ok indeed the fix did not work.

It seems that the 'critical section' of this code also contained the jquery validation logic, apart from it's outcome. So even if the validation was wrong I think it flagged the form as submitted. I had a look inside the jquery validation code and am using some internal plugin flag to check if the form was already submitted. If a request is pending a subsequent one is cancelled.

**Comment by jekkos** [comment]
I tested this locally and for now was not able to do any double submit. Also the form still works if you edit something, try to save, close, open and then submit again.

**Comment by daN4cat** [comment]
OK, great. I initially posted a comment but wanted to test more bcause not 100% sure Ive uploaded the correct file for my test.
I now give a try to the new one.

**Comment by daN4cat** [comment]
Yes, it's now fine. Thanks

**Comment by jekkos** [comment]
Ok great to hear, it did took me a bit longer than expected. Glad to hear it's fixed.

**Comment by jekkos** [comment]
Can you approve? Otherwise i'll just merge.
