### ISSUE TITLE
OSPOS Version Upgrade  3.0.2 to 3.3.1

### ISSUE THREAD

**Issue by shifasiddeqque** [opensourcepos/opensourcepos#3050]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

While i am using OSPOS from some time now, I wanted to Upgrade my OSPOS version to the latest version, I have done the code changes,
Also i have created the required tables ( new ones), But while i try to login with my existing database ( which has around 100000 sales enteries), i am getting below Error)
Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in C:\wamp64\www\ospos-latest\vendor\codeigniter\framework\system\core\Exceptions.php on line 1

PHP upgrade works fine with the default db ( copied from database folder)

I changed the php memory_limit = 4096M from 128M, Also increased post_max_size = 20M in php.ini file but no luck
Could somebody help me How should i fix this error

Thanx in advance

**Comment by daN4cat** [comment]
Where did you get version 3.3.1?

**Comment by jekkos** [comment]
Are you certain you are editing the correct php.ini file? There might me mulitple depending on how you have PHP setup. Check the location in phpinfo to see if you got it right.

**Comment by shifasiddeqque** [comment]
thank you for the quick Response, Now that error is gone but i am still not able to login, the loader keeps on moving without any luck
![image](https://user-images.githubusercontent.com/14173981/102880630-a67af000-4471-11eb-9e96-23cfd3dd91a2.png)

**Comment by shifasiddeqque** [comment]
Please do needful, 
now i am getting 
Error Number: 1062

Duplicate entry '196901-0-2.5% Cgst' for key 'PRIMARY'

INSERT INTO `ospos_sales_taxes` (`sale_id`, `tax_type`, `tax_group`, `sale_tax_basis`, `sale_tax_amount`, `print_sequence`, `name`, `tax_rate`, `sales_tax_code`, `rounding_code`) VALUES ('196901', '0', '2.5% Cgst', '39.00000', 0.95, 8, 'Cgst', '2.500', '', 1)



 @jekkos @daN4cat 
Please help

**Comment by daN4cat** [comment]
@shifasiddeqque have you restarted from a copy of your database? Not sure whether trying twice the same operation caused that or not. It's better to restart from an original copy of the database and see if you reproduce.
If yes, it looks like you inserted twice the same item. No sure how but that error means that to me.

**Comment by shifasiddeqque** [comment]
@daN4cat Yes i have started from my existing Database.... But that db is working fine with old OSPOS(previous version), I have Updated Code only and retained the old db(added only new required tables and columns), and yes if i check in db , there are 2 enteries for same item ( but i have 1000's of such enteries which is working fine with old code base)......
i can't start from fresh db( which is working fine), Please help in this regard

**Comment by shifasiddeqque** [comment]
Actually i have 2 enteries one for CGST and 1 for Cgst (both are different) and i have added name to primary as well but no luck...
![image](https://user-images.githubusercontent.com/14173981/103064830-004af980-45db-11eb-87fe-2c16e994ed69.png)

**Comment by shifasiddeqque** [comment]
@daN4cat @jekkos @bricas @awriel 
Please help, Now getting 
Error Number: 1062

Duplicate entry '311778-0-6% cgst-24.0000' for key 'PRIMARY'

INSERT INTO `ospos_sales_taxes` (`sale_id`, `tax_type`, `tax_group`, `sale_tax_basis`, `sale_tax_amount`, `print_sequence`, `name`, `tax_rate`, `sales_tax_code`, `rounding_code`) VALUES ('311778', '0', '6% cgst', '24.00000', 1.36, 2, 'cgst', '6.000', '', 1)

Filename: C:/wamp64/www/ospos-latest/vendor/codeigniter/framework/system/database/DB_driver.php

Line Number: 691


![image](https://user-images.githubusercontent.com/14173981/103408437-7a095700-4b88-11eb-8437-77ae3cec110a.png)

This is a new table being created

PLease help

**Comment by daN4cat** [comment]
If it's a duplicted entry, how are we suppoed to help? You need to resolve that issue on your side I'm afraid.

**Comment by shifasiddeqque** [comment]
But as per my knowledge, this table doesn't exist in my current
database(ospos version 3.0.2) which i am trying to upgrade...
i don't know How this table gets it's records....


Please help in this regard as i am not able to move forward








Thanks & Regards
Shifa

**Comment by shifasiddeqque** [comment]
@jekkos @daN4cat @bricas @awriel 
please have a look into this, this is super urgent

**Comment by daN4cat** [comment]
@steveireland any hint to help here?

**Comment by jekkos** [comment]
@shifasiddeqque I'd say try to restore your backup and restart the upgrade from there? Do keep an eye on the logging in any case.

**Comment by shifasiddeqque** [comment]
I have compared code with the latest version of Ospos ( had done some customization so need to retain that),
I have deleted all my sales table enteries and it worked But for production i can't delete enteries

For Db Upgradation, am I missing anything??
How do i insert Necessary tables and table columns as per new Version??

DO I NEED TO RUN SCRIPTS LOCATED IN \application\migrations\sqlscripts

pLEASE HELP @jekkos @daN4cat

**Comment by objecttothis** [comment]
> 
> 
> I have compared code with the latest version of Ospos ( had done some customization so need to retain that),
> I have deleted all my sales table enteries and it worked But for production i can't delete enteries

There is a chance that your code customizations are not playing nice with the 3.3.1 version.  This can happen for example if the table is being generated with data that isn't what it was expecting, such as duplicates, when there wouldn't normally be duplicates so it can't create the row.  If the upgrade works on a stock setup, you'll need to likely first figure out from your error what data is duplicated, resolve that and then upgrade to 3.3.1.

If your customization is helpful for the software as a whole you can always submit a pull request to have it reviewed and then if it gets added to the software you don't need to keep up with code comparisons. 


> 
> For Db Upgradation, am I missing anything??
> How do i insert Necessary tables and table columns as per new Version??
> 
> DO I NEED TO RUN SCRIPTS LOCATED IN \application\migrations\sqlscripts
> 
> pLEASE HELP @jekkos @daN4cat

Those scripts are run automatically by the migration when you first log in.  I don't recommend running the scripts outside of the migration because PHP gets run alongside the SQL scripts with some of them and the SQL breaks without the accompanying PHP.
