### ISSUE TITLE
Sales register not working properly with due amount and missing customer

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#3055]
Before releasing 3.3.3 I need to fix this issue.

This code is two years old but it was not right, I'm fixing it. 

@jekkos bear with me.

**Comment by daN4cat** [comment]
I fixed this issue, however there is another one with mixed mode sale and return.
The payment disappear switching modes and it's set to complete.
This issue was before my change to clear the payment when changing mode, it was never right.
I'll see if I can fix tomorrow.

**Comment by midsoft2010** [comment]
i thought due was to work as if the customer has not paid? credit sale?. I think is good the requirement of a customer before completing due sale. if this was meant to act as a credit sale.

**Comment by daN4cat** [comment]
I fixed what was intended to be but didn't work properly, which is a due payment (credit) requires a customer.

**Comment by jekkos** [comment]
How do you do this mixed sale/return? You switch the mode during a sale then?

**Comment by daN4cat** [comment]
It's an exchange scenario, they return something and buy something else instead. Sometimes they need a refund for the remaining of other times they need to pay more for what they bought.
In switching between modes you can complete without adding any payment.

**Comment by daN4cat** [comment]
There is no easy fix for the mixed scenario, it would become awfully complicated to predict scenario and sequences. I decided to leave it as it is.
