### ISSUE TITLE
Search box in Customers, Items and etc. not working on mobile phones

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#3057]
Latest js plugins upgrade caused an issue with ospos on mobile phones, you cannot use the search box anymore

This needs to be fixed before we can release 3.3.3.

@jekkos I don't have that much time next couple of days, can you have a look?

**Comment by jekkos** [comment]
Ok any clue what might be wrong (error message or sth?)

**Comment by daN4cat** [comment]
What happens is that as soon as you press the search box, the keyboard pops up on the phone and disappears immediatly after with the table refreshing.

**Comment by jekkos** [comment]
Ok I have pushed something to dev server, let's check if the issues persists. Basically removed the resize trigger. I think it can of goes into a loop, keyboard pops up, resize is triggered that triggers the refresh, which in turn hides the keyboard again.

**Comment by daN4cat** [comment]
Ok, I'll test it later. Thanks

**Comment by daN4cat** [comment]
This is fixed, closing it.
