### ISSUE TITLE
Enhancement: Customer discount remains in Register Sale after the Customer is removed.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3059]
OSPOS Installation Info: 3.3.3 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.46 (Win64) PHP/7.2.4
.PHP Version: 7.2.4
.DB Version: 5.7.21
.Server Port: 80
.OS: Windows NT 10.0

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [import_customers.csv:] - 0666 | Readable ✓ | Vulnerable or Incorrect Permissions ✗

Security Vulnerability Warning
Incorrect permissions leaves this software at risk.

» [application/logs:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads/item_pics:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [import_customers.csv:] is readable, but the permissions are incorrectly set. Please set it to 640 or 660 and refresh.
America/Denver

Add a Customer with a discount. Add a few Items then remove the Customer. His discount still remains even if you add a different Customer.

**Comment by daN4cat** [comment]
This is tricky to address, what if they touched some discount items to increase it? What do you do in that case?
Maybe there should be a reset discount button to help with this but not implement something automatically unless we keep track of all the employee interactions to understand what they mean with something in a given point.... not in this lifetime :-)
