### ISSUE TITLE
Question regarding taxes and multi-currency sales

### ISSUE THREAD

**Issue by john-bonello** [opensourcepos/opensourcepos#3065]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 10.3.27-MariaDB
- OS and version is: 
- WebServer is: 
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi,

I have a few questions regarding taxes.

1. The taxes are not showing on my sales receipt. Maybe is it because most of the items I sell have a 0% VAT rate, but I would still like the VAT column to show that it's 0% and for the VAT row to be shown in the subtotal calculation. I have enabled "Show Taxes" and "Show Tax Indicator" but they still won't show.

2. Is there a way to backdate a sales receipt? I would like to have past invoices in the system as well but haven't figured out how to input them using dates in the past.

3. How can I invoice some people without VAT? For example in the case of cross-border sales across the EU, VAT should be zero rated. So far I noticed that if a product has tax added, it will show up even when invoicing. In the case of invoices, the tax specified in the Item's tax field doesn't always need to be collected. How can I choose not to calculate the tax in certain instances?

4. Similar to my previous question. How can I use different tax rates depending on the customer's location? I know I need to configure some tax settings, but I can't figure out the right process to do that.

5. Is there a way to collect X amount of tax more after a threshold is reached? For example, after selling €35,000 worth of goods in country X (invoices excluded), the VAT rate changes (goes up or down, depending on the product). This is to comply with the EU's distance selling regulations. The thresholds are different per country. So let's say after issuing €38,500 worth of sales receipts (not invoices) to customers in Poland, the tax rate for products should be the Polish rate. But if I haven't sold €35,000 worth of goods to Lithuania, VAT rate should still be that of my home country for Lithuanian customers.

6. How to enable multi currency invoices? I can't seem to find that option, even after following the documentation's instructions.

**Comment by daN4cat** [comment]
2. Edit a sale and click on the date field in the form, you can change the date.
However, be careful with the sequence numbering because certain countries fiscal regulations might not be happy  with certain fiddling. It's at your own risk.

**Comment by daN4cat** [comment]
4. You need to enable the different tax rates per location, @steveireland introduced it. Don't use VAT only anymore but setup the tax rates in configuration.

**Comment by daN4cat** [comment]
6. There was a suggested change to support multi currency but didn't get merge neither in 3.3.3.
Not sure what's the status of that, can't remember.

**Comment by daN4cat** [comment]
It looks like you have wholesaler requirements, not sure they are all supported because it's more retail system. Given UK is leaving tonight EU, I don't think I will ever need to deal with such cases if I were required to. Maybe @jekkos will?

**Comment by john-bonello** [comment]
> It looks like you have wholesaler requirements, not sure they are all supported because it's more a retail system. Given UK is leaving EU tonight, I don't think I will ever need to deal with such cases if I were required to. Maybe @jekkos will?

As it turns out these are the legal requirements I have to abide by, even to run a small retail business. In the UK and in Malta (where I'm based), sales receipts are accepted for VAT refund purposes and there would be no issue if my customers were based locally or in the UK; however this is not the case in a lot of CEE countries where I sell. If a customer requests an invoice, I'm obliged to provide a zero rated invoice and I think it would mess up the data if I had to do things manually.

May I propose the addition of one checkbox indicating the customer as a VAT registered business and therefore all tax will be eliminated in their invoices?

**Comment by daN4cat** [comment]
@john-bonello there is already a checkbox in customers to indicate if it's taxable or not. Have you scrolled down the Customer form? You can even assign Tax Id created with Tax view.
I never looked into this in detail but my feeling is that you can probably achieve what you need.

**Comment by daN4cat** [comment]
3. Use Customer, in Customer form unselect the Taxable.

**Comment by john-bonello** [comment]
> 1. You need to enable the different tax rates per location, @SteveIreland introduced it. Don't use VAT only anymore but setup the tax rates using the dedicated view and in configuration.

How does it work exactly? Any instructions? Because I can't figure it out to be honest. I can't understand how to assign a client to a tax jurisdiction -- or maybe I'm doing it wrong?

**Comment by john-bonello** [comment]
> 1. Use Customer, in Customer form unselect the Taxable. Make sure to assign a customer to your invoice (to state the obvious).
>    You can even create a new customer from sales register if it's completely new.

That works :) Thank you

**Comment by daN4cat** [comment]
BTW, the wiki can help you: https://github.com/opensourcepos/opensourcepos/wiki/Taxes
