### ISSUE TITLE
ERROR 404

### ISSUE THREAD

**Issue by ozzylamberth** [opensourcepos/opensourcepos#3070]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

OSPOS
VERSION 3.3.3
SERVIDOR WINDOWS -  CPANEL PLESK OBSIDIAN 18

QUIEN PUEDE AYUDARME A COMPRENDER EL .htaccess

```
# redirect to public page
  <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^public$
    RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge [NC]
    RewriteRule "^(.*)$" "/PruebaOSPOS/public/" [R=301,L]
  </IfModule>
```
En Servidores Linux me funciona bien pero lo estoy probando en Servidores Windows y me emite el error 404

Mi dominio va redirigido a una carpera llamada PruebaOSPOS por medio de un Index.php
```
<?php
header('Location: PruebaOSPOS/public/');
?>
```
Se redirige normalmente a inicio de sesion pero al ingresar las credenciales me dice
https://MiDominio.com/PruebaOSPOS/public/login

404: archivo o directorio no encontrado.
Puede que se haya quitado el recurso que está buscando, que se le haya cambiado el nombre o que no esté disponible temporalmente.

404 - File or directory not found.
The resource you are looking for may have been removed, renamed, or temporarily unavailable.

Mi pregunta es si este error es causado por .htaccess de la carpeta public o simplemente el sistema tiene dificultades para ejecutarse en Servidores Windows

CODIGO DE .htaccess DE LA CARPETA PUBLIC
```
RewriteEngine On

# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
# RewriteCond %{HTTP_HOST} ^<OSPOS subdomain>\.<my web domain>\.com$ [OR]
# RewriteCond %{HTTP_HOST} ^www\.<OSPOS subdomain>\.<my web domain>\.com$
# RewriteRule ^/?$ "https\:\/\/www\.<my web domain>\.com\/<OSPOS path>" [R=301,L]

# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
# RewriteCond %{HTTPS} !=on
# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
# RewriteCond %{HTTP_HOST} (.+)$ [NC]
# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# if in web root
RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
# RewriteRule ^(.*)$ /<OSPOS path>/public/index.php?/$1 [L]
```
NOTA: TODOS LOS PERMISOS ESTA ASIGNADOS, LA BASE DE DATOS CARGADA HAY CONEXION ENTRE EL SERVIDOR Y LA BASE DE DATOS EL SISTEMA BRINDA LA PRIMERA INTERFAZ GRAFICA DE OSPOS PERO EMITE EL ERROR 404 YA EH LEIDO TODOS LOS POST Y EH SEGUIDO CADA UNO DE ELLOS....

NOTA EN SERVIDORES BAJO LINUX NO TENGO PROBLEMAS PARA USAR EL REPOSITORIO

**Comment by daN4cat** [comment]
Your URL: https://MiDominio.com/PruebaOSPOS/

Try

```
# if in web root
# RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
RewriteRule ^(.*)$ /PruebaOSPOS/public/index.php?/$1 [L]
```
