### ISSUE TITLE
public function summary_expenses_categories should be summary_expenses

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3074]
OSPOS Installation Info: 3.3.3 - 4101ff
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.46 (Win64) PHP/7.4.13
.PHP Version: 7.4.13
.DB Version: 5.7.21
.Server Port: 80
.OS: Windows NT 10.0

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [import_customers.csv:] - 0666 | Readable ✓ | Vulnerable or Incorrect Permissions ✗

Security Vulnerability Warning
Incorrect permissions leaves this software at risk.

» [application/logs:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads/item_pics:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [import_customers.csv:] is readable, but the permissions are incorrectly set. Please set it to 640 or 660 and refresh.
America/Denver

In current Master in controller/Reports public function summary_expenses_categories should be summary_expenses because it is giving the error page not found.

**Comment by odiea** [comment]
Something changed somewhere. Neither the Demo or Dev server shows this issue. In the address it was showing summary expenses where the demo shows summary expenses categories.

**Comment by jekkos** [comment]
@odiea was this fixed in the end? Or it this a reverse proxy issue (rewrite rule adding url encoding)?

**Comment by odiea** [comment]
I do not know. I heard no response from anyone else so I closed it.

**Comment by daN4cat** [comment]
Better to verify this before closing.

**Comment by odiea** [comment]
So where does the Report name get called  from? Report. controller or some place else. I don't see it in the helper. I just want to figure out what is going on

**Comment by objecttothis** [comment]
@odiea build 4101ff is related to #3026.  I checked @SteveIreland commit log and he doesn't seem to touch anything related to that report.  I also can't replecate with ae52bd.  Can you try the be7d14 build and see if it is producing the same results for you.  I assume you are getting this when you navigate to Reports > Summary >Expenses then choose a date range and submit?

**Comment by odiea** [comment]
I just downloaded and installed  3.3.3 - be7d14. This also shows http://localhost/current/public/reports/summary_expenses/2021-01-28%2000:00:00/2021-01-28%2023:59:59/complete/all/0 in the address bar.

**Comment by objecttothis** [comment]
@odiea I want to make sure I understand properly. The demo and be7d14 do not have a problem but the branch in PR #3026 does have the issue? @steveireland can you look into this since it's affecting the branch you're working on?

**Comment by odiea** [comment]
Here is what I see when I click on the expenses Reports.  Neither report loads until I add categories. I guess what I am trying to fugure out is where the Report gets the name because Reports controller shows categories the way it should be.
![2021-01-28 06_07_24-Window](https://user-images.githubusercontent.com/10962177/106143089-8d7bf380-612f-11eb-8a52-c594bed5bb37.png)
![2021-01-28 06_07_46-Window](https://user-images.githubusercontent.com/10962177/106143112-9371d480-612f-11eb-812b-00729e172213.png)

**Comment by odiea** [comment]
I looked back into my previous merges and this is when the issue started showing for me.
![2021-01-28 06_48_49-Window](https://user-images.githubusercontent.com/10962177/106147474-206b5c80-6135-11eb-9eb3-fb9f601ea8dc.png)

**Comment by odiea** [comment]
I don't see what has changed possibly something I did years ago. If no one else has an Issue I would recommend closing this and not wasting time on it.

**Comment by odiea** [comment]
I created a new db and now in Permissions it shows summary_expenses_categories where I have summary_expenses. So I found the issue and will close this.

**Comment by jekkos** [comment]
Ah so you mean it was something on your end @odiea ?

**Comment by odiea** [comment]
I guess on a 5 yr old db anything can happen.LOL

**Comment by objecttothis** [comment]
> 
> 
> I guess on a 5 yr old db anything can happen.LOL

Happens to the best of us.  One thing you might do for future references when you're testing against a non-new database and run into something like this, is to make sure to try it against a fresh database and see if you get the same issue.  I keep a copy of a brand new db in phpmyadmin just for this purpose.
