### ISSUE TITLE
Search using a search filter by Category

### ISSUE THREAD

**Issue by ozzylamberth** [opensourcepos/opensourcepos#3086]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 
- OS and version is: Windows 10
- WebServer is: LOCALHOST/XAMPP
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
  
How about friends who have the time to guide me with a question in inventory. I would like to add a Multiselect that is related to category and filter the search. For example. If I have 1000 items in my inventory. With the multiselect I select the brand or category and in the text box filter the description, that is, I select the Tires Category and in the description Firestone 21/15 and in the DataTable Only that information is filtered

**Comment by jekkos** [comment]
Sure you can easily add more filters as a dropdown. There is already an example for the frontend in this case. Then you need to post that selection back to the server and apply it to the query.

**Comment by ozzylamberth** [comment]
How about this jekkos would you give me more information that I should interact to add more filters or where I can find the mentioned example .. Thanks for your help

**Comment by ozzylamberth** [comment]
How are you Jekkos? I hope you are well. I read all the problems on my question of how to add a category related dropdown, but all comments are directed to the attributes session that is assigned in the new items session.
In my case, I want to add a dropdown related to the category to filter. That is, when I go to inventory and I have the following options: 1 Delete - 2 Multiple edit - 3 Generate barcode - 4 Filtered by date and a drop down with different search filters and a search text box. what I want is to add a drop down that filters the search by category and in the text box what I want to search

As below, as the picture shows

From what I have read I think that all the components are grouped in which session I can locate myself to try to integrate the search filter

If you have an idea with the image in Category I have HYUNDAI
MITSUBISHI
FORD
KIA
So that you have an idea with the image in Category I have HYUNDAI
MITSUBISHI
FORD
KIA
Those brands should appear in the drop-down menu of categories, and when selecting, for example, KIA, all the elements that are related to KIA should appear and in the text box I search by code or description of the desired item


![capture-20210204-205528](https://user-images.githubusercontent.com/7409604/106974847-c6b5f400-672b-11eb-9a4a-2d5f3953e68c.png)

**Comment by ozzylamberth** [comment]
How about Jekkos and Odiea here again .... In advance it is an idea that I am developing the code, it may not be the ideal but the doubts I have.

models/item.php 
![capture-20210214-233825](https://user-images.githubusercontent.com/7409604/107903046-971e9d00-6f1e-11eb-9e64-be936185aa45.png)


This is the code to load the drop-down with the data from the Category column, in turn I call it Group and when selecting it for one of its records, you must load the drop-down 2 with the Brands related to that Category when selecting a Brand you must filter the with data from custom filters

al igual utilizo views\items.php

![capture-20210214-232847](https://user-images.githubusercontent.com/7409604/107903573-fb8e2c00-6f1f-11eb-814b-634036348746.png)


But a great question arises about how to relate the custom filters with the table of elements so that it generates the search or in its case filters the result.


If someone is interested in custom filters and wants to contribute ideas to implement it, welcome help

**Comment by ozzylamberth** [comment]
In the same way it occurs to me to manipulate the data table and generate the collapsible ones in the header of the same specifically the Group and Brand

**Comment by jekkos** [comment]
Question was answered in the other ticket you opened, gonna close this one.
