### ISSUE TITLE
New Issue Found: SALES limit it's number of items to be transacted...

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#3087]
I play around the OSPOS last month when I try to sale 100 different items in sales modules, it REJECTS in the 89 items and the system automatically logout and redirect to login menu... 
Does the system limits the number of items to be sold?
Please help me to solve this problem

**Comment by jekkos** [comment]
Hi can you try latest master branch and report back? It has a fix for this issue (larger blob datatype).

**Comment by izeblood** [comment]
> Hi can you try latest master branch and report back? It has a fix for this issue (larger blob datatype).

@jekkos yes.. I try to sale 178 different items and everything is okay....so far....

**Comment by izeblood** [comment]
I will continue to add more sales since i suspend the transaction to be able to continue adding more items...

**Comment by izeblood** [comment]
@jekkos can we include this minor fix to 3.3.3 version?

**Comment by daN4cat** [comment]
It will be in 3.3.4

**Comment by izeblood** [comment]
> It will be in 3.3.4

Okay...Thanks...
