### ISSUE TITLE
localhost/ospos/public displays blank page in browser

### ISSUE THREAD

**Issue by gedi-on** [opensourcepos/opensourcepos#3089]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by gedi-on** [comment]
OSPOS version is:3.3.3
OSPOS git commit hash is:
PHP version is:3.2.4
MySQL or MariaDB version is:
OS and version is:windows 10
WebServer is:xamp
Selected language is:PHP
(If applicable) Docker installation:
(If applicable) Installation package for the LAMP/LEMP stack is:

**Comment by jekkos** [comment]
PHP version is:3.2.4

Not sure if that makes sense.. Check your php error log you will probably have some missing modules.

**Comment by ekardian** [comment]
lol i have the same issue sometimes, but is for i install in diferents machines and linux version for test every 6 months XD

sometimes is your modules, look the requeriments(modules php)
php-gd, php-bcmath, php-intl, php-openssl, php-mbstring and php-curl

if your apache read .htaccess

if read php files

if read ... wait is windows 10... sorry gg i never installed in windows 10

RTM in https://github.com/opensourcepos/opensourcepos/wiki/Getting-Started-installations

and i hope not to see a php 8 there xDDD
