### ISSUE TITLE
WIKI pages and install.md are not up-to-date with correct installation proceedings

### ISSUE THREAD

**Issue by dulajdilshan** [opensourcepos/opensourcepos#3091]
### Background information
I have downloaded and correctly followed the steps. The steps seem to bit faulty. As an example 

> Populate database with that other command in same terminal mysql -u admin -ppointofsale -D ospos < /var/www/html/database/database.sql

Here, there is no such file called `database.sql`.
However, I have followed the correct procedure to set up the **opensourcepos**. But, I found that there is an error: giving Forbidden when accessing the `root` dir. and getting an internal server error when accessing `root/public`

* Here I have followed installing the stable release on digital ocean's LAMP droplet with MySQL

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
You need to install the current stable version from Install.md.

**Comment by jekkos** [comment]
I checked this file `https://github.com/opensourcepos/opensourcepos/releases/download/3.3.2/opensourcepos.20200903075833.3.3.2.bb309c.zip`, so the one in the wiki, and it does contain the database.sql file.

**Comment by jekkos** [comment]
@dulajdilshan If you can be a bit more specific otherwise we can update the docs . Currently I can't really reproduce.

**Comment by odiea** [comment]
@jekkos I assume that he had downloaded the code from the first page and did not build it.
