### ISSUE TITLE
Deployment guides needed for Heroku

### ISSUE THREAD

**Issue by MohammedMaaz** [opensourcepos/opensourcepos#3093]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: Heroku
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I'm not experienced in deploying LAMP based applications o cloud so please forgive if my question is naive and obvious.
I've been trying to deploy OSPOS app on Heroku, but I'm not sure which method should I use for the installation. Since heroku takes a github repo of an app and builds it by itself, so I tried to fork the original OSPOS repo to my account and connected it's master branch with my Heroku app. I also added a Heroku `Procfile` to the master branch of the forked repo. The contents of the Procfile are: `web vendor/bin/heroku-php-apache2 public/`. When I deploy the master branch on Heroku, it did build my app (showing build logs and displaying a success message at the end), but when I try to visit the url of my app it returned a 404 page (screenshot attached).
![image](https://user-images.githubusercontent.com/17180132/107160908-f3336f80-69ba-11eb-93f1-05cd680b7d15.png)

My question is what is the correct procedure of deploying this app to Heroku. I am aware of the fact that I should only use a stable release from bintray when deploying and not try to build the source code myself, but since Heroku forces you to connect a github repo and build the app by itself (I am not aware of any other method of deploying on Heroku), I was forced to opt this method, which did not work eventually.

**Comment by daN4cat** [comment]
Read the developer section in the wiki, you can't run from GitHub without installing libraries and etc.
Also check what travis script do.
