### ISSUE TITLE
Expenses is not showing my last register, help. (solved, after deleted % symbol from my description on db/table ospos_expenses>Description)

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#3094]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 8e52bd
- PHP version is: 7.2.33
- MySQL or MariaDB version is: 10.3.25-MariaDB-cll-lve
- OS and version is: Linux 3.10.0-962.3.2.lve1.5.28.el7.x86_64
- WebServer is: Apache
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

hey my bros, im in a problem :( i was like every day registering my expenses but from date 2021/2/8 is not showing in my filter, the expense figure in the database

from phpmyadmin/db i can see this
![imagen](https://user-images.githubusercontent.com/6296036/107309581-1153ab00-6a61-11eb-9905-8dd02ca78030.png)

but in my expenses module....
![imagen](https://user-images.githubusercontent.com/6296036/107310183-50cec700-6a62-11eb-8b6e-483568c33302.png)

if i filter a day ago i can see my last expense from yesterday like 2021/2/7
![imagen](https://user-images.githubusercontent.com/6296036/107310353-9f7c6100-6a62-11eb-9349-c6be26ea86d4.png)

if i filter in the range 2021/2/7 - 2021/2/8
i cant see nothing
![imagen](https://user-images.githubusercontent.com/6296036/107310801-84f6b780-6a63-11eb-8f79-57058e13cffc.png)

the last thing in my mind was.....in the comment,  its the first time i put the chararter $, i was testing in the demo server but its working there. thanks for your answers guys.

**Comment by ekardian** [comment]
i replayed the same error now in the demo server.... in the comment i put 100$us giro Elsa Núñez (siembra) + 7$us envío - 7.3% en agencia total comisión 8.3% del total del envío .... and i changed:
Location symbols and contry codes, i was testing and using for expenses in my house from 2015 i never see this issue from now, 
![imagen](https://user-images.githubusercontent.com/6296036/107311979-d142f700-6a65-11eb-9102-715e62f0daae.png)

**Comment by ekardian** [comment]
i tested with 1 expense (date 9/2/2021) in date and now i can the expense registered today, i gonna try again with that characters in the comment again for verified if i have the same issue with my expense from 8/2/2021
![imagen](https://user-images.githubusercontent.com/6296036/107407857-93cf7f80-6ae0-11eb-8cb0-fa21cc5cbe85.png)

**Comment by ekardian** [comment]
ok I was able to replicate the error, is with this character in the comment field, i saw something similar a few years ago here, but i dont remember where,,, i think lost in the limbo, something about CI filter some characters?
the text i wrote is:

> 100$us a Elsa Núñez (siembra) + costo envío 7$us, comisión de envío 7.3 + 1.0  total en agencia 8.3% del total enviado

and now all the expenses from 9/2/2021 are not shown
![imagen](https://user-images.githubusercontent.com/6296036/107409710-d72aed80-6ae2-11eb-9689-d8a00a055f8a.png)

**Comment by ekardian** [comment]
ok fixed, i just deleted the symbol "%" from my database, and now working.

![imagen](https://user-images.githubusercontent.com/6296036/107424657-5117a280-6af4-11eb-9e6d-e8a0571bae3b.png)

**Comment by odiea** [comment]
I believe that using the % sign is a CodeIgniter issue that has been mentioned here before.

**Comment by ekardian** [comment]
> I believe that using the % sign is a CodeIgniter issue that has been mentioned here before. If you really need to use it I believe it will work ok if you wrap it with quotation marks. '%' or "%".

yep, this issue has ben mentioned, but i lost the refrence in the limbo XD, for now i gonna try with the quotation, you have more work in others parts in the project, im just  a soul who scream out in the desert XDDDD.
