### ISSUE TITLE
ERROR 500

### ISSUE THREAD

**Issue by nelsondalida** [opensourcepos/opensourcepos#3096]
Good day, i have another problem, when i migrate it from localhost to hosting site for me to use in different device so i can monitor it in my personal pc or phone, all the functions are working but when i want to generate reports it goes "HTTP ERROR 500"

**Comment by ekardian** [comment]
welp, i migrated about 5 years in a ho$ting , i had same issues, so looking the .htacces
i commented this line

`#Options +ExecCGI +Includes +IncludesNOEXEC +SymLinksIfOwnerMatch -Indexes`

and i changed for this one, my hosting only perm that way. work but its a start

`Options -Indexes`

other

the permisions, sometimes the perm files was changed by your provider.

the best way is backup your database and download again the ospos with your version and githash

and install again again with your database copied and new db user from your host.

work for me in that years. Be happy all have a solution.
