### ISSUE TITLE
where tebular html code of report file is located?

### ISSUE THREAD

**Issue by Hamzaqureshi401** [opensourcepos/opensourcepos#3108]
![image](https://user-images.githubusercontent.com/46222436/107870704-80dff500-6ebc-11eb-8895-52b988f95213.png)
i want to know the location of this tebular file where its html is written like <td> and <tr> and this td and tr rendring reporst of employees

**Comment by SteveIreland** [comment]
It's automagically generated by JavaScript.

**Comment by andriux1990** [comment]
@Hamzaqureshi401 what do you want to do here?
