### ISSUE TITLE
Datatable column wise search filter in CodeIgniter

### ISSUE THREAD

**Issue by ozzylamberth** [opensourcepos/opensourcepos#3109]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 5.0
- OS and version is: Windows 10
- WebServer is: XAMPP
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

****Datatable column wise search filter in CodeIgniter****

What's up friends? I have a question about where can I manage the data tables in the item session.
Ie add filters as shown in this example
![capture-20210216-003302](https://user-images.githubusercontent.com/7409604/108018634-a9680c00-6fee-11eb-842d-d18b02fb40cb.png)
to achieve this
![capture-20210216-003501](https://user-images.githubusercontent.com/7409604/108018734-f3e98880-6fee-11eb-97ff-e4366c3d4ccf.png)
I have interacted with the files
Controller / item.php
Model / Items.php
View / item / manage.php
![capture-20210214-232847](https://user-images.githubusercontent.com/7409604/108018930-72dec100-6fef-11eb-966f-8421959c8696.png)
And I have not managed to make the adjustments

**Comment by jekkos** [comment]
Maybe try this plugin
https://bootstrap-table.com/docs/extensions/filter-control/

**Comment by jekkos** [comment]
You'll need to import in bower and then enable the plugin in javascript in manage_tables.js. If it works then might be nice if you report back. Thanks!

**Comment by ozzylamberth** [comment]
According to the information in the library.

Filter control

Use the plugin: bootstrap-table-filter-control to filter the fields in the table.

Under this code
<link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">

<script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

<table
  id="table"
  data-url="json/data1.json"
  data-filter-control="true"
  data-show-search-clear-button="true">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name" data-filter-control="input">Item Name</th>
      <th data-field="price" data-filter-control="select">Item Price</th>
    </tr>
  </thead>
</table>

<script>
  $(function() {
    $('#table').bootstrapTable()
  })
</script>

I have assigned this code to application \ views \ items \ manage.php
![capture-20210216-052152](https://user-images.githubusercontent.com/7409604/108043641-b64d2580-7017-11eb-9023-6720c117baeb.png)

but it still does not generate the desired filtering. I suppose that the code must be generated for each select and I still have a question with the manage_table.js file

**Comment by jekkos** [comment]
Sorry but you're not very clear on what you want to reach here. What code did you change here exactly? Might be better to ask in bootstrap tables project if you have any specific issue with their widgets.

**Comment by jekkos** [comment]
I guess you need to generate the table header with the correct attributes to have the widget you want. Check `[the bootstrap tables doc for that](https://examples.bootstrap-table.com/index.html#extensions/filter-control.html)`.

**Comment by daN4cat** [comment]
I guess what they mean is that you need to implement some backend functionality to support your filtering.

**Comment by ozzylamberth** [comment]
apparently that's what it takes to filter the columns with the library that Jekkos indicated to me. I managed to assign the select to the columns that I want to filter. Now I am trying to give the event to generate the filter

**Comment by ozzylamberth** [comment]
So far I'm still the same I have a little confusion
Filter Control
Use Plugin: bootstrap-table-filter-control to filter table fields.

I add the following extension to views/Item/manage.php
And I create a file called json/data1.json

<link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
<script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

<table
  id="table"
  data-url="json/data1.json"
  data-filter-control="true"
  data-show-search-clear-button="true">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="category" data-filter-control="select">Categoria</th>
      <th data-field="brand" data-filter-control="select">Marca</th>
    </tr>
  </thead>
</table>

<script>
  $(function() {
    $('#table').bootstrapTable()
  })
</script>

and I get the following result

![capture-20210217-001423](https://user-images.githubusercontent.com/7409604/108155519-69b82780-70b5-11eb-9ec4-712abc038e19.png)

So far so good the SELECTs are where I want to filter

BUT it does not generate the filter because I cannot perform the function that allows the SELECTs to perform the filtering


data-url="json/data1.json"

This line is calling a file called data1.json

And I generate it in the following way

$(function () {
  $('#table').bootstrapTable({
    filterControl: true,
    disableUnusedSelectOptions: true,
    data: data,
    columns: [
      {
        field: "category",
        title: "Categoria",
        filterControl: 'select',
        filterControlPlaceholder: "Placeholder",
        filterStrictSearch: false
      },{
        field:  "brand",
        title: "Marca",
        filterControl: 'select',
        filterStrictSearch: true
      }        
    ]

  });
});

But it still doesn't run the filter, can you tell me what the error is?

**Comment by jekkos** [comment]
right, you need to post the selected value from the frontend to the search method in the model and apply it to the query there.

**Comment by ozzylamberth** [comment]
unfortunately I can't make the filter here. I achieve it directly with php datatable but in bootstrap-table CI it is confusing I will keep reading

**Comment by ozzylamberth** [comment]
Okay. Looking at it from another point of view.
Working with:
Oh give me your opinion

Controller / Items
public function index () {

$ filter = $ this-> input-> post ('filter');
$ field = $ this-> input-> post ('field');
$ search = $ this-> input-> post ('search');
 if (isset ($ filter) &&! empty ($ search)) {$ this-> load-> model ('models / Item');
$ data ['Item'] = $ this-> Item-> getItemsWhereLike ($ field, $ search);
} else {$ this-> load-> model ('models / Item');
$ data ['Item'] = $ this-> Item-> getItems (); } $ data ['module'] = 'admin'; $ data ['view_file'] = 'Item / manage'; $ this-> load-> module ('templates'); $ this-> templates-> Item ($ data);
    }
Model / Item
public function getItemsWhereLike ($ field, $ search)
    {
        $ sql = "
            SELECT * FROM opsos_items
            WHERE $ field LIKE '% $ search%'
            ORDER BY `category` `registered_at`
        ";
        $ query = $ this-> db-> query ($ sql);
        return $ query-> result ();
    }

View / Item / manage
<form class = "form-inline" action = "<? php echo base_url (). 'Items';?>" method = "post">
        <select class = "form-control" name = "field">
            <option selected = "selected" disabled = "disabled" value = ""> Filtered by </option>
            <option value = "category"> Group </option>
            <option value = "brand"> Brand </option>
            <option value = "located"> Location </option>
        </select>
        <input class = "form-control" type = "text" name = "search" value = "" placeholder = "Search ...">
        <input class = "btn btn-default" type = "submit" name = "filter" value = "Go">
    </form>

![capture-20210220-183747](https://user-images.githubusercontent.com/7409604/108610857-6a9bd280-73af-11eb-81f8-5eef49d20be9.png)

**Comment by jekkos** [comment]
@ozzylamberth anything else you need help with? Can we close? Thanks.
