### ISSUE TITLE
BinTray Replacement

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3110]
### Issue

When it rains it poors, right?  In addition to needing to find a replacement for Travis-CI (#3063 and #2834) JFrog has announced that they are shutting down BinTray on May 1st (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

**Comment by objecttothis** [comment]
yay for DevOps fun!

**Comment by jekkos** [comment]
Yes ... I noticed already. Yesterday I have created a travis-ci.com account. It seems that we should be able to migrate to the new platform and hopefully we'll be able to stick with the free plan.

We're also often hitting rate limitation on docker hub now..

docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.

**Comment by jekkos** [comment]
Maybe github actions can also be used to host build artifacts.. It would be good to have everything integrated in one platform.

**Comment by jekkos** [comment]
https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by jekkos** [comment]
Maybe github actions can replace both travis and jfrog. In this case if we can run builds as a workflow and host the resulting artifact on github itself, then that would be great.

**Comment by daN4cat** [comment]
Yes, GitHub actions is quite promoted by Microsoft as the next. They are planning to migrate from Azure DevOps to GitHub.

**Comment by jekkos** [comment]
Bintray will shutdown completely 1st of may.

**Comment by SteveIreland** [comment]
Is that the day you are going to sell OSPOS and retire to a Swiss resort?

**Comment by jekkos** [comment]
Bintray had stopped working as expected

![Screenshot from 2021-05-26 10-20-55](https://user-images.githubusercontent.com/576234/119627290-58955a00-be0c-11eb-9334-cde0ee9867bd.png)

We could deploy to [github releases](https://github.com/travis-ci/dpl) instead using travis (dpl plugin)

**Comment by jekkos** [comment]
Seeing an issue with [OAuth setup now](https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token)

**Comment by jekkos** [comment]
It seems that some of the runs have deployed a zip to releases section here now..

**Comment by jekkos** [comment]
Ok the files do end up in github releases now. I had to find some workaround for the following

* Github release cannot exist without a tag
* Tagging a commit triggers another build, which caused the builds to trigger in a loop

So solution to the first point is to force and remove an old tag to the current commit. This means we will only have one prerelease for every branch, which I think is ok?

Second issue was solved by stopping the trigger for a commit that already has a tag.

**Comment by objecttothis** [comment]
> 
> 
> Ok the files do end up in github releases now. I had to find some workaround for the following
> 
>     * Github release cannot exist without a tag
> 
>     * Tagging a commit triggers another build, which caused the builds to trigger in a loop
> 
> 
> So solution to the first point is to force and remove an old tag to the current commit. This means we will only have one prerelease for every branch, which I think is ok?
> 
> Second issue was solved by stopping the trigger for a commit that already has a tag.

One prerelease for every branch is probably preferred in most cases.

**Comment by jekkos** [comment]
![Screenshot from 2021-06-09 08-51-36](https://user-images.githubusercontent.com/576234/121307150-ff472380-c8ff-11eb-9100-c741caecb901.png)

**Comment by jekkos** [comment]
So as long as I don't make the filename unique it won't stack the downloads in a branch prerelease. @opensourcepos/org fine like this or should we overwrite the previous zipfile? In that case I need to rename to opensourcepos.$branch.zip again.

**Comment by objecttothis** [comment]
I'm not sure but I think you're talking about whether we should be able to have multiple builds per branch or whether to overwrite the file each time a new build is made on that branch.  IMO, with bintray we had far too many builds and it caused the account to get frozen more than a couple times.  I think we ought to have at most two builds per branch.  We have a commit history, so if something gets borked in a branch we can revert commits and build again.  Perhaps I'm missing something that would be a good argument to have more than two builds per branch.

**Comment by jekkos** [comment]
Ok so maybe it's better to overwrite an uploaded zipfile with a newer one once the build triggers?

**Comment by objecttothis** [comment]
> 
> 
> Ok so maybe it's better to overwrite an uploaded zipfile with a newer one once the build triggers?

Yeah, but I don't feel too strongly about it, so if someone comes up with a super good reason to not do this, then you can decide.

**Comment by SteveIreland** [comment]
I'm also okay with overwriting it.  I don't ever recall going back to an earlier build.  I do, of course, often go back to earlier commits for research purposes.  If I did need it I could always rebuild it from an earlier commit.

**Comment by jekkos** [comment]
Ok perfect thanks for the input. The files are overwritten now. As a finishing touch I might want to include the app version in the file / tagname.

**Comment by jekkos** [comment]
![Screenshot from 2021-06-09 18-02-30](https://user-images.githubusercontent.com/576234/121389697-f761a080-c94c-11eb-90f9-0b926fc68866.png)

**Comment by jekkos** [comment]
So version string is extracted from config.php now. Then it tags the commit with branch-version and adds a prerelease for every unique combination of branch-version.
