### ISSUE TITLE
config_timezone_error (TBD)

### ISSUE THREAD

**Issue by awank2** [opensourcepos/opensourcepos#3116]
Info pemasangan OSPOS: 3.3.3 - 8e52bd
Language Code: id

config_timezone_error (TBD)

config_user_timezone (TBD)
Asia/Jakarta

config_os_timezone (TBD)
Asia/Bangkok

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Firefox
.Server Software: LiteSpeed
.PHP Version: 7.4.14
.DB Version: 5.5.5-10.3.27-MariaDB-cll-lve
.Server Port: 443
.OS: Linux 3.10.0-962.3.2.lve1.5.31.el7.x86_64

File Permissions:
» [application/logs:] - 0755 | Writable ✓ | Vulnerable or Incorrect Permissions ✗	
» [public/uploads:] - 0755 | Writable ✓ | Vulnerable or Incorrect Permissions ✗	
» [public/uploads/item_pics:] - 0755 | Writable ✓ | Vulnerable or Incorrect Permissions ✗	
» [import_customers.csv:] - 0644 | Readable ✓ | Vulnerable or Incorrect Permissions ✗	

Peringatan Kerentanan Keamanan
Izin yang lebih tinggi dari 750 membuat perangkat halus ini dalam risiko.

» [application/logs:] bisa ditulis, tetapi kode permisi lebih besar dari 750.
» [public/uploads:] bisa ditulis, tetapi kode permisi lebih besar dari 750.
» [public/uploads/item_pics:] bisa ditulis, tetapi kode permisi lebih besar dari 750.
» [import_customers.csv:] config_is_readable (TBD)	
Asia/Jakarta

**Comment by jekkos** [comment]
This TBD typically means that there is no translation for this string in your language. You can fix this using weblate, just log in using github account and look for the config component.
