### ISSUE TITLE
OSPOS with ElectronJS

### ISSUE THREAD

**Issue by bkrajendra** [opensourcepos/opensourcepos#3120]
Has anyone tried OSPOS with ElectronJS?
I am planning to add support for it along with standalone distribution for the server.
What are your experiences with this implementation, please share!
https://www.electronjs.org/

**Comment by SteveIreland** [comment]
Apparently not.  So many technologies ... so little time.

**Comment by jekkos** [comment]
@bkrajendra No haven't worked with it.. it looks nice though. What advantages do you see in comparison with using a browser?

**Comment by daN4cat** [comment]
Desktop App? That's ortogonal to SaaS idea.... if we had a REST API you could build your UI with whatever you wanted but we would need to manage the authentication with something external.

**Comment by bkrajendra** [comment]
@daN4cat , yes I understand the Desktop app is orthogonal to Saas, But what I am talking about here is the UI part, which can be made fast and modern by using Angular/React front ends.
Server-side installation of OSPOS can be kept separate part, which will remain as it is now, except handling REST part need to be added.
But my use case is mostly to distribute the entire system to clients/users, which will contain 
**Frontend App + Server + OSPOS server module.**
We can keep these three parts separate but at a later stage, we can have a single install script for all three.
This is a long road but we can at least open up a discussion about it to see the potential...!

**Comment by daN4cat** [comment]
On top of REST API, you need an Identity Provider based on OpenID Connect OAuth 2.0 protocols and have an access control story on the web service implementing the REST API. Quite some stuff to build and we are still stuck on an old style MVC application....
