### ISSUE TITLE
Correct Greyed out Submit button when clicking submit twice with validation errors

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3122]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
With the current master #3095 changes there is a bug where clicking submit when there are validation errors after you've clicked submit when there were validation errors causes the submit button to grey out.  The behavior should be that the submit button should never grey out if there are validation errors.  This is likely a logic error where the if statement is either looking at the wrong variable to decide whether to grey out the submit button, not looking at enough variables or the variables have values which are not expected.

**Comment by objecttothis** [comment]
@jekkos this is just the technical debt description.  I need to have a medical procedure done on 3 March, so I won't be able to fix this until 9 March.  Someone else can take this if the fix needs to be merged before then.

**Comment by jekkos** [comment]
I'll see if I can find the time and motivation to look into it. Thanks for letting us know. Good luck with the medical intervention.

**Comment by objecttothis** [comment]
@jekkos sorry I didn't take a look at this yesterday.  I have a hard deadline that came up to implement an online payment method on our website, so I've had to focus on that.  I may be able to find the time to fix this bug in the next few days, but if I don't we have a couple of options.  

- Someone else could fix it.
- We can wait for me to fix it before creating the bugfix release.
- We could release the bugfix and then put this fix in a later release.

**Comment by jekkos** [comment]
I went ahead and had a quick look. I think the issue was that calling is_valid before submit does not give a correct result as the form validation is only triggered after the call to submit()

Do you know if the submit is blocking in a way here? I mean, do I need to call validate() before submit or can we keep it like this? I was thinking that doing it in this order might beat the purpose if the submit blocks until a response is received.

**Comment by jekkos** [comment]
@objecttothis did you have any chance to validate my fix? Then we can close and do the release.

**Comment by objecttothis** [comment]
> @objecttothis did you have any chance to validate my fix? Then we can close and do the release.

Sorry. I'll do it first thing in the morning.

**Comment by objecttothis** [comment]
@jekkos Here's the problem:

```
			const form = $('form', dlog_ref.$modalBody).first();
			const validator = form.data('validator');
			const submitted = validator && validator.formSubmitted;
			const is_valid = !$.isEmptyObject(validator.invalid);
```
`console.log(validator.invalid);` on the first click with validation errors returns:

```
{}
```
which means that `const is_valid = !$.isEmptyObject(validator.invalid);` evaluates to false.  On the second click `console.log(validator.invalid);` returns:
```
{
  "name": true,
  "category": "Category is a required field.",
  "unit_price": false,
  "cost_price": false,
  "quantity_1": false,
  "reorder_level": false,
  "receiving_quantity": false
}
```
I apologize but because of this payment method deadline on our website, I don't have the time to investigate why the validator.invalid object is not being populated properly on the first click.  I think it should always populate the object with the invalid object details or we need to be looking at something else to determine if is_valid should be true.

in the console.log output of the validator doesn't seem to contain the data it should in the places that it should.

errorList and invalid don't look right to me because I think errorList should have a length of 2 not 1 because there are two validation errors.  Instead it's putting the first validation error details in errorList and the 2nd in invalid.

**Comment by objecttothis** [comment]
To clarify, I can tackle this on April 6th (before if I finish this online payment method early) or someone else can jump on it.  Sorry for the delays.

**Comment by jekkos** [comment]
@objecttothis did you see the fix that I did in master? I think the issue is that the validator is only triggered after you click the submit.

My question was whether we need to grey out the button before the submit is called? Was that the purpose of this story?

**Comment by objecttothis** [comment]
Oh sorry.  I did not see that fix.  I'll take a look.  The purposed was to grey out the submit and disable it on click except when there are validation errors.  The greying out (changing opacity) is just a visual identifier that the button has been pressed so that the user doesn't sit there wondering on a large import or long-running script whether the app registered the click.  That said, the two options for approaching this would be:

- Grey out on submit click but then re-enable if there are validation errors.
- Grey out only on successful validation.

The second is less complicated and given that validation doesn't take long is probably the desired result.

I'll go look at the master right now.

**Comment by objecttothis** [comment]
@jekkos the fix you merged with the database works on my system.
