### ISSUE TITLE
Directory access forbidden when trying to access configurations page.

### ISSUE THREAD

**Issue by dela-dels** [opensourcepos/opensourcepos#3123]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- PHP version is: 7.3
- OS and version is: 
- WebServer is: Apache on XAMPP
- Selected language is: English

### Issue 

So I have successfully installed OSPOS on a windows 10 desktop and everything works perfectly except the configuration screen. When I try to access that, I am told I do not have access to that directory. I have tried everything possible I know to fix it but I can't seem to go around it. This is my third installing OSPOS on a pc and I have never seen this error. Find attached image below:

![Screenshot 2021-03-02 115315](https://user-images.githubusercontent.com/12721695/109663889-7ed89000-7b64-11eb-8b5a-ec2eb8ca8927.png)

**Comment by jekkos** [comment]
This is something related to your setup. Maybe your webserver is intercepting the url due to some specific .htaccess configuration?

**Comment by dela-dels** [comment]
Maybe, can't tell since I didn't touch the .htaccess file. Just left everything as is and only followed installation instructions.

**Comment by jekkos** [comment]
maybe omit the public from the url? Does it work in that case?

**Comment by jekkos** [comment]
Could be a wrong rewrite rule

**Comment by daN4cat** [comment]
We should probably review the .htaccess. I sense some people might get issues with the follow symlink if owner.

**Comment by jekkos** [comment]
@dela-dels did you find a solution for this? Can you try latest master which has an updated .htaccess?

**Comment by dela-dels** [comment]
@jekkos No I did not. 
Okay sure, I will try the latest master then.

**Comment by jekkos** [comment]
Any update @dela-dels ?
