### ISSUE TITLE
Export product receipt invoice in Receiving Module

### ISSUE THREAD

**Issue by ozzylamberth** [opensourcepos/opensourcepos#3127]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 5.1
- OS and version is: W-10
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

How are you guys? I have a question for both Jekkos and daN4cat I think I have opened a thread on the subject, if so, you can cancel it and leave this one. My question is this. for the reception of products.

![capture-20210311-181726](https://user-images.githubusercontent.com/7409604/110863589-4721c480-8297-11eb-8855-e26ebe5afcac.png)

These are the files of my interest.
ospos_receivings.php
ospos_receivings_items.php
ospos_item_quantities.php
and finally ospos_inventory.php

I can export a file with an .xslx extension for each table, but they are related to whether there is another system or database file that interacts with that module. I expose the information since the product entry invoices exceed 100 items and loading them 1 x 1 is a very difficult task

How are you guys? I have a question for both Jekkos and daN4cat. I think I have opened a thread on the topic, if so, you can cancel it and leave this one. My question is this. for receiving products.

These are the files of my interest.
ospos_receivings.php
ospos_receivings_items.php
ospos_item_quantities.php
and finally ospos_inventory.php
I can export a file with an .xslx extension for each table, but they are related, I understand that the table ospos_item_quantities.php column quantity is in charge of adding the quantities of the product input with what are in stock there are other files in the system or of the database that interacts with that module.
I expose the information since the product entry invoices exceed 100 items and loading them 1 x 1 is a very difficult task and I am making a file export system that allows me with the INSERT INTO SELECT statement to interact with the database. In other words, I create a destro table from the ospos database and from archi I distribute to the four tables but I have problems in the export and I am solving if they have any information that I have not seen or some more practical idea

**Comment by jekkos** [comment]
I'm not really sure what the question is here .. do you still needf help?

**Comment by ozzylamberth** [comment]
How about Jekkos if I'm still at it what I need is to export a list of items instead of one by one invoices that arrive again inventory exceed 100 items and entering it one by one is a complicated task when you need the updated inventory. That's why I'm looking for ways to export the purchase invoice to the system globally while respecting all the steps of receiving

**Comment by jekkos** [comment]
you can use the receivings report for this? Or do you want to do a bulk inventory update? In that case you can use bulk edit but it depends on the action you want to do
