### ISSUE TITLE
gift card consumed in quote

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#3128]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

_______________________________________________________
Hello friends
I assigned a customer a gift card with a value.

I made a quote to this same customer and added a payment using the gift card number.

The sale was never completed ... it remains suspended. but the value paid with the gift card is consumed ... even without completing the sale.

**Comment by SteveIreland** [comment]
I also tested the scenario where a sale is entered and a payment is added using a gift card value of $5.  Then the sale is suspended.  Checked the gift card and the value was zero.  I then canceled the suspended sale and the gift card value remained zero.  I would have expected the gift card value to return to $5.

**Comment by SteveIreland** [comment]
I will need guidance on this.  A quote or work order is essentially a suspended sale.  So the issue regarding gift cards is the same.  The save method in the Sale.php model is used for all and it reduces the gift card amount at the point that it is saved.

I believe that the correct change is to condition the gift_card update to only reduce the gift card amount during save when the sales status goes to COMPLETED.

Does that sound like a good idea?

**Comment by odiea** [comment]
On a Quote I would suggest blocking any kind of payment. After all it is just a quote

**Comment by SteveIreland** [comment]
That makes sense to me.  :-)

**Comment by SteveIreland** [comment]
Unless somebody doth protest too much, the change I will make will be to somehow make it not possible to enter a payment against a quote.  @jekkos? - thoughts?

**Comment by jekkos** [comment]
Yes sounds good to me. We should not clobber the sale table with payment data for quotes.

Do your recall how the technical conversion works if a quote is converted to an actual sale? Do we copy the quote into a sale?
