### ISSUE TITLE
PDF character encoding issues in table export

### ISSUE THREAD

**Issue by Alakodi** [opensourcepos/opensourcepos#3132]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by Alakodi** [comment]
![Capture](https://user-images.githubusercontent.com/63294200/111315413-95c8b900-861f-11eb-8bc7-e4ae047eee60.JPG)

**Comment by Alakodi** [comment]
please help me to solve this problem

**Comment by Alakodi** [comment]
![Capture](https://user-images.githubusercontent.com/63294200/111316630-aa598100-8620-11eb-90c1-b5a13c6cffd2.JPG)

**Comment by jekkos** [comment]
That might be an encoding issue. Do the letter show properly outside of the report?

**Comment by Alakodi** [comment]
No problem was encountered before exporting the file. Character mixing process takes place after opening it with pdf

**Comment by jekkos** [comment]
Might be related to #649.

**Comment by jekkos** [comment]
you mean you had no issues in older versions?

**Comment by jekkos** [comment]
Very likely that this is a jsPdf issue. It seems that in order to support utf8 we might need to add a custom font to the PDF.

**Comment by jekkos** [comment]
From their documentation

```
The 14 standard fonts in PDF are limited to the ASCII-codepage. If you want to use UTF-8 you have to integrate a custom font, which provides the needed glyphs. jsPDF supports .ttf-files. So if you want to have for example Chinese text in your pdf, your font has to have the necessary Chinese glyphs. So, check if your font supports the wanted glyphs or else it will show garbled characters instead of the right text.
```

**Comment by Alakodi** [comment]
I am using Version 3.3.3 but I solve this by print button in reports page .This problem caused when export file as pdf and other files have no problem

**Comment by jekkos** [comment]
Ok but can you confirm that this export to pdf worked in older versions?

**Comment by Alakodi** [comment]
let me try the old version and can answer you

**Comment by Alakodi** [comment]
The same thing in old version

**Comment by jekkos** [comment]
Ok great (not great) thanks for the confirmation.

**Comment by Alakodi** [comment]
Thanks for this reply jekkos. I solved that using print button because all other programs have same issues when exported as pdf
.when I exported data as excel file this problem is not caused

**Comment by jekkos** [comment]
@Alakodi I read that the issues might be resolved with the latest jsPDF. I'm trying to make a build with that version now.

**Comment by jekkos** [comment]
I have checked a bit further, and it's not very straightforward to fix this.
tableExport describes a way which is using another pdf export lib, specifically for arabic / chinese. 
As you have a workaround for now, I'd prefer not to spend too much time on this.

https://github.com/hhurz/tableExport.jquery.plugin

**Comment by Alakodi** [comment]
Thanks for your time . I wish all the best #jekkos
