### ISSUE TITLE
Rewrite .htacces doesn't work

### ISSUE THREAD

**Issue by ffurxio** [opensourcepos/opensourcepos#3133]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 3b1f459
- PHP version is: 7.4.15
- MySQL or MariaDB version is: MariaDB 10.4.17 
- OS and version is: Windows 
- WebServer is: Apache 2.4.46
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 
All provided by Xampp 7.4.15
### Issue / Bug  / Question / New Feature

Good Day
I'm having this issue where i cant acces to the system because i always been redirect to 
localhost/public 
instead of 
localhost/ospos/public
Yes i have installed and enable the modules for php 
I already tried to fix, modify the .htacces in public whit the route of the subnomain and enable the rewrite rule on apache config
![image](https://user-images.githubusercontent.com/39169881/111414112-a9663500-869c-11eb-90db-a3e1e0bd3b34.png)

Yes i change the apache conf
![image](https://user-images.githubusercontent.com/39169881/111414721-afa8e100-869d-11eb-951e-c9952fc6e455.png)

I tried to use absolute paths but nothing change (one / or two also one \ or two )
![image](https://user-images.githubusercontent.com/39169881/111415247-c00d8b80-869e-11eb-884e-2287a458e118.png)

If i put the system files in the root folder all works fine but i prefered to have it in a subdomain (i'm a toc person)

if anyone can help i will be happy :3

**Comment by daN4cat** [comment]
Hi, the /ospos/public/index.php is the right thing.

What about this rule:

+SymLinksIfOwnerMatch

is that fine with your setup?
See if changing it with just +FollowSymLinks works or not.

If it does you need to fix your apache installation because the original option is the secure one.

**Comment by daN4cat** [comment]
I'm not a deep expert in Apache config, I never had the time to.
However, also check that the rule AllowOverride All is required in Directory / statement.
Again I'm not sure that's really required, do some homework please.

**Comment by daN4cat** [comment]
If nothing works, post on Stackoverflow the question under generic CodeIgniter 3 question and see if someone can help you.

**Comment by ffurxio** [comment]
@daN4cat Sadly nothing work, i remember that i had similar error long time ago with laravel so i think is something with the apache and the rewriterule but i can't remember what was the solution (didn't put attention to the professor), i'm gonna try to post on Stackoverflow and see if i can find the solution.
Also @ozzylamberth was able to install in a subdir on widows machine with xampp like me i'm gonna try to contact so maybe eh can explain what he does

**Comment by daN4cat** [comment]
Please write the solution here when you find one.

**Comment by jekkos** [comment]
@ffurxio any updates? did you get it working?

**Comment by jekkos** [comment]
Can you try to comment out line 11
`#Options +ExecCGI +Includes +IncludesNOEXEC +SymLinksIfOwnerMatch -Indexes`

**Comment by jekkos** [comment]
Do you have mod rewrite enabled in apache? 

`a2enmod rewrite`

**Comment by ffurxio** [comment]
@jekkos i made it work but not in the apropiate way because i modify the apache.conf to make the root dir a subfolder.
And yep i have already enable so i give up and leaved like that.
Maybe is just me so i'm gonna close the issue :c
