### ISSUE TITLE
Count column in Tax Summary Report seems incorrect

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3134]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I just noticed on the Tax Summary Report that the count column doesn't seem to take into account the quantity. If I make a sale of 2 of one item the count only shows up as one but if I make two sales of one item each the count shows up as two. Maybe this is what's intended but if so I'm not sure what the word count actually means. I think it should probably be total number of items which would mean the quantity would need to be included in the total, not just the number of lines.  I tested this on dev.

**Comment by odiea** [comment]
Count appears to be the number of Sales that included the Taxes.

**Comment by chunter2** [comment]
@odiea I think this is correct then.  Maybe Count should be renamed to Sales?

**Comment by chunter2** [comment]
@odiea Just looked at this again and I think it's the number of lines in the ospos_sales_items table with that tax.  So I think it should be either the number of unique sale_id with that tax from the ospos_sales_items table or the total item_id including quantity with that tax.  Does that make sense?  Basically right now I've got a count value between my total sales and my total items.

**Comment by odiea** [comment]
I just went into summary report for taxes and changed the count to array('report_count' => $this->lang->line('reports_completed_sales')), and now it shows Completed Sales which may be more informative then count.

**Comment by chunter2** [comment]
So this just changes the name of the column.  The values would be incorrect with that title.  Maybe an example will help.  For today we had 75 transactions and a quantity of 400 items sold taken from the Summary Transaction report.  In the Summary Taxes report we had a count of 212 at 13% and 51 at 5%.  These 212 and 51 numbers don't add up to 400 and they're more than 75.  They're just the individual lines of the ospos_sales_items table for each tax rate which isn't really useful information for me.  Hopefully this helps.

**Comment by jekkos** [comment]
Indeed this field is just the count (*) of the query as far as I can see. I have changed this to the sale_id. Currently I have no data to verify if it works as expected. Could you have a quick look @chunter2 ?

**Comment by odiea** [comment]
A Database Error Occurred
Error Number: 1054

Unknown column 'sale_id' in 'field list'

SELECT name, percent, count(sale_id) AS count, ROUND(SUM(subtotal), 2) AS subtotal, ROUND(SUM(tax), 2) AS tax, ROUND(SUM(total), 2) AS total FROM ( SELECT CONCAT(IFNULL(ROUND(percent, 2), 0), '%') AS percent, (CASE WHEN sales_items.discount_type = 0 THEN sales_items.quantity_purchased * sales_items.item_unit_price - ROUND(sales_items.quantity_purchased * sales_items.item_unit_price * sales_items.discount / 100, 2) ELSE sales_items.quantity_purchased * (sales_items.item_unit_price - sales_items.discount) END) AS subtotal, sales_items_taxes.name AS name, IFNULL(sales_items_taxes.item_tax_amount, 0) AS tax, IFNULL((CASE WHEN sales_items.discount_type = 0 THEN sales_items.quantity_purchased * sales_items.item_unit_price - ROUND(sales_items.quantity_purchased * sales_items.item_unit_price * sales_items.discount / 100, 2) ELSE sales_items.quantity_purchased * sales_items.item_unit_price - sales_items.discount END * (1 + (sales_items_taxes.percent / 100))), (CASE WHEN sales_items.discount_type = 0 THEN sales_items.quantity_purchased * sales_items.item_unit_price - ROUND(sales_items.quantity_purchased * sales_items.item_unit_price * sales_items.discount / 100, 2) ELSE sales_items.quantity_purchased * (sales_items.item_unit_price - sales_items.discount) END)) AS total FROM ospos_sales_items AS sales_items INNER JOIN ospos_sales AS sales ON sales_items.sale_id = sales.sale_id LEFT OUTER JOIN ospos_sales_items_taxes AS sales_items_taxes ON sales_items.sale_id = sales_items_taxes.sale_id AND sales_items.item_id = sales_items_taxes.item_id AND sales_items.line = sales_items_taxes.line WHERE sale_status = 0 AND sale_time BETWEEN '2021-03-25 00:00:00' AND '2021-03-31 23:59:59' ) AS temp_taxes GROUP BY percent

Filename: C:/wamp64/www/masterup/vendor/codeigniter/framework/system/database/DB_driver.php

Line Number: 691

**Comment by jekkos** [comment]
ouch ok, force pushed a new commit now.

**Comment by chunter2** [comment]
@jekkos I'm not noticing a change with your latest commit but I'm applying it to version 3.3.2 so that could be an issue.  I'm wondering if maybe there needs to be a DISTINCT in there?  I'm assuming if you're going with Sales for that column a sale should only count once.  With my data it looks like its counted however many lines in the ospos_sales_items table that tax rate occurs.

**Comment by jekkos** [comment]
Indeed, let's try `COUNT(DISTINCT(sale_id))`. Hopefully that will work?

**Comment by chunter2** [comment]
@jekkos That worked.  My totals are correct now.  Thanks.  My only other suggestion would be to rename the column header to Sales like @odiea suggested above and then I think this issue is fixed.

**Comment by jekkos** [comment]
I have adapted the column name in my latest commit @chunter2
