### ISSUE TITLE
Configuration Page

### ISSUE THREAD

**Issue by SwayerPT** [opensourcepos/opensourcepos#3135]
- OSPOS version is: 3.4.0 - 12d79b.
-
### Issue / Bug  / Question / New Feature

This bug happens when i oppen CONFIGURATION PAGE
==================================================
A PHP Error was encountered
Severity: 8192

Message: Array and string offset access syntax with curly braces is deprecated

Filename: barcodes/Ean8.php

Line Number: 115

Backtrace:

File: D:\xampp\htdocs\pos\application\libraries\Barcode_lib.php
Line: 8
Function: _error_handler

File: D:\xampp\htdocs\pos\application\libraries\Barcode_lib.php
Line: 8
Function: require

File: D:\xampp\htdocs\pos\application\controllers\Config.php
Line: 11
Function: library

File: D:\xampp\htdocs\pos\public\index.php
Line: 316
Function: require_once
==================================================

**Comment by SteveIreland** [comment]
We don't yet have a 3.4 release.  

There are unstable versions of OSPOS found in BinTray (which will be obsolete in a few days).

The latest build is https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20210317133526.master.6df9ac.zip

**Comment by SwayerPT** [comment]
Nice. You should Add a new thing for PORTUGAL.
Example: Contribution ID. Some clients ask to put in their fiscal discounts using Contribution ID number in the recipe, others not.

**Comment by SteveIreland** [comment]
To be honest only features that find widespread use are added to OSPOS. Requirements that would only be used in a single country would probably require that you fork OSPOS and add the feature to your own fork.  Based on your brief description of what you want I wouldn't understand enough to do any work.  If you want a good chance at having someone volunteer to add a new feature you should create a new issue for it and describe in great detail what you need, how it would impact the application and what reporting changes would be needed to support it (with links to any government or corporate related requirements that might help describe it.  Someone might be able to map it to an existing feature.   New features need to be approved by "The Deciders".  A new feature gets harder to sell if it is less broadly used or impacts the system in a way that makes an undesirable change to the architecture, or unacceptably complicates the UI.

**Comment by daN4cat** [comment]
Maybe the customer attributes feature could do if we allow them to be added to invoice and receipts.

**Comment by daN4cat** [comment]
BTW it's amazing how many rules people can come using OSPOS in different countries of this world.
All this development and experience built a database of requirements that it would be difficult for any people to build on their own.

**Comment by daN4cat** [comment]
I mean, only what you built @SteveIreland with all the taxation system is impressive. When I started with ospos predecessor there was only a notion of two taxes level.
For me there is only a fixed VAT rate. However, I reckon that Internet sales introduced a new set of problems and Steve, you did an amazing job in building all the flexibility required. Truly impressive and thanks a lot for all your hard and great work!
