### ISSUE TITLE
Add a Client Taxpayer Number

### ISSUE THREAD

**Issue by SwayerPT** [opensourcepos/opensourcepos#3136]
### Ideia
In Portugal every client have a taxpayer number that can be used in recipes or not. That will depend if the client asks for that.

### Making work
- Add a new column when creating a client with a name Taxpayer (in portuguese "Contribuinte") (not necessary to add)
- After making a sale in any mode the sale will add the taxpayer into the recipe with a field called "TaxID: XXXXX or depending the language".

In my opinion this is very necessary in any store outside US.

**Comment by odiea** [comment]
In receipt default you can change the customer line to the following and if they have a tax id it should show.
<div id="customer"><?php echo nl2br($customer_info) ?></div>. Try it and see if this works for you.

**Comment by SteveIreland** [comment]
When adding a customer, if you scroll down, there is a field labeled "Tax Id".  It seems that, based on the title of this issue, that should do the job.  The original design reason was that this is the number issued by the government to those who are exempt from taxes.  Not much is done with this field other than capturing it and printing it.  Looking at the code, I can see that there is an attempt to make the tax_id available and even display it using the technique that @odiea points out.  The tax id is displayed only if there is a value entered into the field.  That was the original design and should still be working.

**Comment by SteveIreland** [comment]
I believe the question may have been answered to the satisfaction of the original poster.  Unless I'm missing something I think this question can be closed.
