### ISSUE TITLE
Box Open & Box Close

### ISSUE THREAD

**Issue by SwayerPT** [opensourcepos/opensourcepos#3137]
### Box Open & Box Close

The POS should have a way to register the Cash In and Out from the box. 
Example… starting the morning openning the Box with “today date, amount in box”, then “final of the day close the Box with the amount in box”.
Every POS have this option, it’s obligatory

**Comment by odiea** [comment]
Cashup module is already there. Try using it

**Comment by SwayerPT** [comment]
Humm where is located to activate or what is the name? “Sorry for asking”.

**Comment by odiea** [comment]
I do not know what language you are using but here is a pic of the English lang modules.
![2021-03-20 17_11_59-Window](https://user-images.githubusercontent.com/10962177/111888151-9060cb00-899f-11eb-9451-3d51e448c05c.png)

**Comment by SwayerPT** [comment]
Wow ok. 
But to use that module it’s required to use the first and last date right now. And for cashup it should start by the first date and amounts (openning), then “update” with last date and amount. (Closing)

**Comment by janab381** [comment]
You can Update the Date Closed when entering the closing Cash and Selecting Today from Date Picker. It will auto select current data and time.
