### ISSUE TITLE
Cannot import item from excel - .xlsx or . csv file. 

### ISSUE THREAD

**Issue by bhojkamal** [opensourcepos/opensourcepos#3140]
### Importing Item Issue - importing item is not succeed. 

__Note.: I have to insert data one by one only__

Error - "There were 2 item import failure(s) on line(s): 2, 3. No rows were imported"

I tried to import items from  .csv file. But it could not be done. 

### Installation information

- OSPOS version is: 3.3.2 / 3.3.3
- OSPOS git commit hash is: 
- PHP version is: 7.3 & 7.4
- MySQL or MariaDB version is: 10.1 - 10.4
- OS and version is: Windows 10
- WebServer is: Apache 2.4.46

### Issue / Bug  / Question / New Feature

The error msg is - There were 2 item import failure(s) on line(s): 2, 3. No rows were imported
How can we fix this issue? 
We need .xlsx file to import items.

I hope this will be solved soon.

**Comment by jekkos** [comment]
@bhojkamal Maybe also post the excel or data that you tried to import. There is no way we can otherwise look in to this.

**Comment by emrebesir** [comment]
You can use this excel rows to import. Fill this excel than convert into csv and import.
[import_items.xlsx](https://github.com/opensourcepos/opensourcepos/files/6389771/import_items.xlsx)

**Comment by jekkos** [comment]
No reply or details. Will close

**Comment by nyenius** [comment]
I just have this issue right now. The failed data rows are items data that **retail price is 0 (zero)** and **duplicate** item name/barcode.

**Comment by bhojkamal** [comment]
I download the sample .csv file and filled the data  on it and it does not import. there is error as mention above.
