### ISSUE TITLE
Translation must be post processing

### ISSUE THREAD

**Issue by vnwildman** [opensourcepos/opensourcepos#3141]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information
https://demo.opensourcepos.org/

### Issue / Bug  / Question / New Feature
Vietnamese language:
![ảnh](https://user-images.githubusercontent.com/508758/113098948-628f4800-9223-11eb-9bab-e532a5910b3d.png)

Untranslation string will become empty, so key will be display. It should be origin English string instead.
I write php script to post processing this (put it in language dir). Please see the attachment, and rename it to php.
[post_process.txt](https://github.com/opensourcepos/opensourcepos/files/6234212/post_process.txt)

**Comment by vnwildman** [comment]
I mean you would apply my script when you release, not in git repo.
Thanks,

**Comment by jekkos** [comment]
Ok I see you are writing to a `_new` file, so we might have duplicates for every translation file then?

**Comment by jekkos** [comment]
Thanks for the translations btw

**Comment by ekardian** [comment]
at the end are 0 and 1 the caos

**Comment by jekkos** [comment]
@vnwildman if your translation is incomplete, then I'd suggest to translate it instead of using the english strings instead.
