### ISSUE TITLE
Sales Controller issues in current version.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3144]
OSPOS Installation Info: 3.3.3 - 616e8e

Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache
.PHP Version: 7.4.13
.DB Version: 5.7.21
.Server Port: 80
.OS: Windows NT 10.0

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [import_customers.csv:] - 0666 | Readable ✓ | Vulnerable or Incorrect Permissions ✗

Security Vulnerability Warning
Incorrect permissions leaves this software at risk.

» [application/logs:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads/item_pics:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [import_customers.csv:] is readable, but the permissions are incorrectly set. Please set it to 640 or 660 and refresh.

Is the controller/sales suppose to be reload() or _reload() it appears to have both also none of the right side buttons work now. Cannot complete a Sale or suspend a sale or add a new customer

**Comment by jekkos** [comment]
Thanks for reporting @odiea .

**Comment by odiea** [comment]
Also in the footer common_copryrights is misspelled.

**Comment by jekkos** [comment]
@objecttothis any idea if it could be something caused by the last merge?

**Comment by odiea** [comment]
It is all caused by the last merge. Try the dev demo.

**Comment by objecttothis** [comment]
I'll take a look

**Comment by objecttothis** [comment]
I submitted a patch, but I'll need to compare the Sales controller with my build that is working properly and see if I can't spot what got messed up.

**Comment by odiea** [comment]
I used the previous release of the Register and now it works properly

**Comment by odiea** [comment]
Also in config I am not able to add either of the 2 taxes.

**Comment by objecttothis** [comment]
@jekkos perhaps the best option here would be to roll back to the previous commit in the master.  That will give me a chance to figure out what happened in the rebase to bork the Sales controller.  It will also allow you to push the 3.3.4 release.  @SteveIreland won't have to rebase his changes on all the crazy then.  I don't think I have permission to roll back the master in the CLI.  Can you do it?

**Comment by jekkos** [comment]
Ok I'll force push the previous commit back now, I think that will be fastest for now.

**Comment by jekkos** [comment]
Ok I have done the rollback for now.

**Comment by objecttothis** [comment]
I'll close this then. I'll rebase again once I get a chance and slow down a bit then test the rebased version thoroughly to make sure the rebase didn't bork anything again. I'll also wait until 3.3.4 this time ;).

Sorry for the hassle guys.
