### ISSUE TITLE
New coding standard?  (don't like)

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3147]
I was progressing nicely through a manual merge (in an effort to both understand the new standards that are being implemented) but stumbled across a change I strongly disagree with and would like to pout about it a bit.

Here is what I like because it flows naturally with the SQL language.  I'm "selecting x from y where z".

		$this->db->from('sales');
		$this->db->where('invoice_number IS NOT NULL');
		return $this->db->count_all_results();

The apparent new standard appears to be..

		$this->db->where('invoice_number IS NOT NULL');
		return $this->db->count_all_results('sales');

Now I have to read it as I'm "select x where z from y".    That's invalid SQL language and my eyes have to drop down and search for what I'm selecting from before they can go back and fabricate what's happening.

Why is this standard changing?  Or IS this a new standard that I have to conform to?  I noticed that it's not being applied across the board but I see where that revision from the old to the new, for no other reason that I can see, is taking place in a significant part of the code.

**Comment by jekkos** [comment]
Hi, I don't feel strongly about either one here. I suppose the reason for using the 'new' style is that it's a bit shorter, but less readable as you say. We can vote here to agree on what we'll do otherwise?

**Comment by ekardian** [comment]
git creator give us this gift, you are now owner fromself, i cant undarstand, because i dont know write code but i can read something, nothing is easy for me, but if there are a better way for the functionality of scripts/programs... for me its ok.... COPIAD MALDITOS XDDDDD COPIADLO TODO

**Comment by andriux1990** [comment]
@ekardian Entiendo tu mensaje .. Ten más cuidado con tus palabras ofensivas

**Comment by ekardian** [comment]
> 
> 
> @ekardian Entiendo tu mensaje .. Ten más cuidado con tus palabras ofensivas

Creo que entendiste a que hace referencia esa parte de Copiad Malditos, como al creador de la GNU, recuerdas? es la esencia y la base del compartir el código XD

**Comment by objecttothis** [comment]
@SteveIreland this is changing with the CI4 upgrade.  The code will become:
```
	$builder = $this->db->table('sales');
	$builder->where('invoice_number IS NOT NULL');
	return $builder->countAllResults();
```

The code was changed by me for optimization because it got rid of an extra function call.  Some of these queries were appearing inside for loops and over a large dataset, even the single function call was reducing processing time.  It's moot now, since CI4 is changing it closer to what it was before.
