### ISSUE TITLE
Items Module Delay.

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#3153]
I tried to load 18,000 plus of different items... then I tried to transact it everyday for 2 months now... then I encountered delay of items module... for me the reason for this is the inventory count details...
My suggestion is to put an option to enable/disable this inventory count details so that it won't affect the delay of entire items module..

BTW, I'm using ospos3.3.3

**Comment by jekkos** [comment]
I think there's some performance improvements on the way in 3.4

**Comment by jekkos** [comment]
Feel free to give some feedback and test once @objecttothis merges some of his work. This will be soon as 3.3.4 is out now.

**Comment by objecttothis** [comment]
@izeblood If you are talking about the speed of importing large item files then it's on the way.  If you are talking about the speed of interacting with items then you might install and try out this build (https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.20210422093519.database_optimizations.dfdc45.zip) but please do it on a copy of your data.  Please report any problems that you find.

**Comment by izeblood** [comment]
I used version 3.3.4.. still I encounter delay of opening item module which I suspected inventory count details is the key....

**Comment by objecttothis** [comment]
@izeblood Can you explain what you mean by "Inventory Count Details"?  The database optimizations that I committed were only the tables touched by the Item model and more optimizations might be necessary for the Attributes and other tables. Can you share a screenshot of which page you experience the delay in loading?

**Comment by objecttothis** [comment]
Also, please share the details on the page found at Office --> Configuration --> Config & Setup

**Comment by izeblood** [comment]
> @izeblood Can you explain what you mean by "Inventory Count Details"? The database optimizations that I committed were only the tables touched by the Item model and more optimizations might be necessary for the Attributes and other tables. Can you share a screenshot of which page you experience the delay in loading?

Since, Inventory Count Details display all the transactions from the very beginning, I suggest to make an option to DISABLE/ENABLE this feature in order to minimize the load of the Items Module.

![icd2](https://user-images.githubusercontent.com/32444665/121861454-6a439080-cd2c-11eb-9b1a-c4fe0ee33ab3.jpg)


![icd](https://user-images.githubusercontent.com/32444665/121861188-31a3b700-cd2c-11eb-81a2-55fc3e819666.jpg)
