### ISSUE TITLE
How can I import my sales exported data (ospos.sql)

### ISSUE THREAD

**Issue by gazenferlucas** [opensourcepos/opensourcepos#3154]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 5.5 
- OS and version is: Windows 10 Pro and 20H2
- WebServer is: XAMPP
- Selected language is: english 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Dear,
I am using OSPOS 3.3.3 for my retail store for one month and I always back up the database. Today my old computer is broken and I install the OSPOS 3.3.3 into my new computer and it is ok the POS is open like new but I don't know how to import my back up database (ospos.sql) into newly installed OSPOS. Thank you very much for your kind help.

Best Regards,
Galau

**Comment by odiea** [comment]
You should be able to import it using Phpmyadmin in Xampp

**Comment by odiea** [comment]
In Phpmyadmin create a new db then import your old db to the new one you just created. Then in config database change the name of the db to the newly imported db.

**Comment by gazenferlucas** [comment]
Dear @odiea,

Thank you very much for your kind help. I missed to uncheck (foreign key .......) while importing the database. I'm able to import and using OSPOS again. 

Thanks and regards,
