### ISSUE TITLE
Cash totals at the bottom of reports

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3155]
There was an earlier attempt to report cash totals as net cash received minus the change due.

However, the last commit in this area now only reports the total cash received.  I'm not sure where the value in this is since the total cash received is actually cash received minus change given.  However, I'm not the user.  I saw where someone commented that this is what they were expecting but that comment may have been in respect to something else.

If someone can please let me know what's intended before I delete this support from my local code I would greatly appreciate it.   Thanks.

**Comment by odiea** [comment]
@SteveIreland What Total are you referring to?

**Comment by SteveIreland** [comment]
I'm rebasing over  the latest master and noted that the code to reduce cash payments was no longer in the tabular_helper.  That triggered the question, but I haven't yet checked to see if the code was relocated elsewhere.  That's what I'm about to do now.

**Comment by jekkos** [comment]
@SteveIreland a rework was done in the fix for #3138

**Comment by SteveIreland** [comment]
Yep, thanks ... I just now spotted it myself.  :-)

**Comment by jekkos** [comment]
So maybe I missed something? the idea was to substract the cash_refund directly in the query. I

**Comment by SteveIreland** [comment]
Nope, it's good.  I wanted to do that in my customer due tracking branch but was hesitant, so I'm glad you did it.  That simplifies things for me.

**Comment by jekkos** [comment]
Ok great thanks was double checking also on my side. The test I did looked good (see screencap also I took in #3138). I paid a sale of $20 with $40 (so $20 change) and checked that it showed $20 total cash.
