### ISSUE TITLE
OSPOS Report Headers appearing false false

### ISSUE THREAD

**Issue by shifasiddeqque** [opensourcepos/opensourcepos#3156]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

In every OSPOS report, my headers are not appearing giving False false , Could you Please help
attaching  screenshot
![reportError](https://user-images.githubusercontent.com/14173981/114380291-8fd6e100-9ba7-11eb-8315-21294bc0b38f.png)

@jekkos @daN4cat

**Comment by jekkos** [comment]
I suppose this does not happen in the actual master version?

**Comment by shifasiddeqque** [comment]
@odiea  this was running smoothly some days back, I made few changes to one of my reports and it appeared like above...
Even i reverted my changes, still headers are missing
Which form you are talking about????

@jekkos  this si master file only


when i tried to debug this issue, headers are appearing but once the view file is called, nothing actually shows up

**Comment by odiea** [comment]
The form you submitted to report your issue. Did you try to refresh your browser to see if the headers worked ok?

**Comment by shifasiddeqque** [comment]
Yes i do, so many times, i tried in incognito mode as well but no luck








Thanks & Regards
Shifa

**Comment by shifasiddeqque** [comment]
@jekkos @odiea 

After changing below line
$headers = $this->xss_clean($model->getDataColumns());
to
$headers =$model->getDataColumns();

Headers are appearing, Should i keep it as it is or look for another alternative??

**Comment by odiea** [comment]
If you are using it locally it should not be a problem.

**Comment by shifasiddeqque** [comment]
@odiea thanx for your reply 
but i will deploy it in my production that is hosted on aws
