### ISSUE TITLE
Open Modal on + sign OSPOS Report 

### ISSUE THREAD

**Issue by shifasiddeqque** [opensourcepos/opensourcepos#3158]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi Team,
i need to open a bootstrap modal on button click, but it's opening in next tab instead

![modalError](https://user-images.githubusercontent.com/14173981/114707896-5f7a7880-9d48-11eb-9b93-d1d85eb5597a.png)

Kindly help 
@jekkos @odiea @aelhofy

**Comment by jekkos** [comment]
You need to use the same path as used on the button, so that the js modal bootstrap is attached correctly.

**Comment by shifasiddeqque** [comment]
How to do achieve that if my button is application/controllers/Reports.php Pasting my whole method here
 
`**public function detailed_discrepancy($start_date, $end_date, $receiving_type, $location_id = 'all')
{
	$inputs = array('start_date' => $start_date, 'end_date' => $end_date, 'receiving_type' => $receiving_type, 'location_id' => $location_id);
	$this->load->model('reports/Detailed_discrepancy');
	$model = $this->Detailed_discrepancy;
	
	$model->create($inputs);

	//$headers = $this->xss_clean($model->getDataColumns());
    $headers = $model->getDataColumns();
	$report_data = $model->getData($inputs);
		

	$summary_data = array();
	$details_data = array();

	$show_locations = $this->xss_clean($this->Stock_location->multiple_locations());

	foreach($report_data['summary'] as $key => $row)
	{
		$get_employee_name = $this->Employee->get_info($row['completed_by']);
		if(!empty($get_employee_name->username)) {
			$completed_by = $get_employee_name->first_name.' '.$get_employee_name->last_name;
		} else {
			$completed_by = $row['completed_by'];
		}

		$summary_data[] = $this->xss_clean(array(
			'id' => $row['receiving_id'],
			'receiving_date' => $row['receiving_date'],
			'from_stock' => $row['source'],
			'to_stock' => $row['destination'],
			'quantity' => to_quantity_decimals($row['items_purchased']),
			'employee_name' => $row['employee_name'],
			'completed_by' => $completed_by,
			//'supplier_name' => $row['supplier_name'],
			'total' => to_currency($row['total']),
			'payment_type' => $row['payment_type'],
			'reference' => $row['reference'],
			'comment' => $row['comment'],
			'edit' => anchor('receivings/edit/' . $row['receiving_id'], '<span class="glyphicon glyphicon-edit"></span>',
				array('class' => 'modal-dlg print_hide', 'data-btn-delete' => $this->lang->line('common_delete'), 'data-btn-submit' => $this->lang->line('common_submit'), 'title' => $this->lang->line('receivings_update'))
			)
		));

		foreach($report_data['details'][$key] as $drow)
		{
			$quantity_purchased = $drow['receiving_quantity'] > 1 ? to_quantity_decimals($drow['quantity_purchased']) . ' x ' . to_quantity_decimals($drow['receiving_quantity']) : to_quantity_decimals($drow['quantity_purchased']);
			$final_quantity = $drow['final_quantity'];

			$emp = $this->Employee->get_info($drow['resolved_by']);
			$resolved_by = $emp->first_name.' '.$emp->last_name;
		
		
			if ($this->Employee->has_grant('report_resolveDiscrepancy', $this->session->userdata('person_id')))
			{
			
				if($drow['resolved_qty'] == 0)
				{
					$resolve_discrepancy =array(
						'resolve_discrepancy' => anchor('receivings/resolveDiscrepency/' . $row['receiving_id'].'/'.$quantity_purchased.'/'.$final_quantity.'/'.$drow['item_number'].'/'.$row['source'].'/'.$row['destination'], '<span id = "newID" class="btn btn-success btn-sm">Resolve Discrepancy</span>',
						array('class' => 'modal-dlg print_hide', 'data-btn-delete' => $this->lang->line('common_delete'), 'data-btn-submit' => $this->lang->line('common_submit'), 'title' => $this->lang->line('receivings_update'))
					));
				} 
				else
				{
						$resolve_discrepancy['resolve_discrepancy'] = 'Resolved<span class="glyphicon glyphicon-ok"></span>';
				}		 

			}
			if($quantity_purchased > 0){
			$details_data[$row['receiving_id']][] = $this->xss_clean(array($drow['item_number'], $drow['name'], $drow['category'], $quantity_purchased, $final_quantity, to_quantity_decimals($quantity_purchased - $drow['final_quantity']), $drow['resolved_qty'], $resolved_by,$resolve_discrepancy['resolve_discrepancy']));
			}
		}
	}

	$data = array(
		'title' => $this->lang->line('reports_detailed_discrepancy_report'),
		'subtitle' => date($this->config->item('dateformat'), strtotime($start_date)) . '-' . date($this->config->item('dateformat'), strtotime($end_date)),
		'headers' => $headers,
		'editable' => 'receivings',
		'summary_data' => $summary_data,
		'details_data' => $details_data,
		'overall_summary_data' => $this->xss_clean($model->getSummaryData($inputs))
	);

	$this->load->view('reports/tabular_details', $data);**`

**Comment by odiea** [comment]
Why don't you just add all of your changes into the current Receivings Report. Reports are a pain in the butt to deal with
