### ISSUE TITLE
Tamil Language unavailable in https://translate.opensourcepos.org/

### ISSUE THREAD

**Issue by kumaranar** [opensourcepos/opensourcepos#3162]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

###  Question 

I want to translate into Tamil language, i am unable to see this language in https://translate.opensourcepos.org/ could you kindly add or point me to any link to show how can I get tamil added to the list of translated languages

**Comment by jekkos** [comment]
Hi which tamil would you like me to add? I see two options, tamil and tamil (Sri Lanka).

**Comment by jekkos** [comment]
@kumaranar you can start translating, I have added your language now.

**Comment by kumaranar** [comment]
@jekkos Thank You, I will update once we complete it may be in a week or 2, Infact  my two kids are doing the translation, I will validate and upload it. I am encouraging my kids to take this as their summer project. Thanks for adding the language.

**Comment by kumaranar** [comment]
Please add Tamil India

**Comment by kumaranar** [comment]
@jekkos  , I see the folder is added in the code repository, but still the language is not available in https://translate.opensourcepos.org/ . Do you suggest me to wait for sometime (We will continue to do the offline translation strings ready till then)

**Comment by jekkos** [comment]
Great to hear @kumaranar , sounds like a good translation exercise. I think weblate does a good job there as it offers you some context on how the strings are translated in other languages. I have updated the platform and the language should be visible now.

**Comment by jekkos** [comment]
https://translate.opensourcepos.org/languages/ta/opensourcepos/
You can work both ways, translate the files directly or use weblate, or both.
If you have finished some files already maybe you can try weblate now.

**Comment by kumaranar** [comment]
@jekkos , Thank you. I am able to see the language listed in weblate and have started using it.

**Comment by jekkos** [comment]
Ok great, I see some of your contributions are already in the repo. If anything else let me know.
