### ISSUE TITLE
Cronjob with C.I. CLI shows OSPOS login page

### ISSUE THREAD

**Issue by brainpascal** [opensourcepos/opensourcepos#3163]
### Background information
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.3.3
- OSPOS git commit hash is: 
- PHP version is: 5.6
- MySQL or MariaDB version is: 10.1.41-MariaDB - MariaDB Server
- OS and version is: Linux 
- WebServer is: Apache
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I want to run a script located in the CLI controller (application/controllers/Cli.php) , so i have created a CPanel cronjob that runs this:

#cd URLTOTHEOSPOSINSTALL/public/; php index.php cli

The cronjob works fine, but the cronjob response email I receive shows that OSPOS returns the Login Page.

¿How can I run the CLI controller script?

Thanks!!

**Comment by daN4cat** [comment]
You need an authentication for security reasons and there is no authentication by key support at the moment.

**Comment by jekkos** [comment]
You'll need to login and fetch the cookie using curl in this case. I think there should be an easy option to store it as a file and send it with every request.
