### ISSUE TITLE
Version number not updated in 3.3.4 release zip package

### ISSUE THREAD

**Issue by prbt2016** [opensourcepos/opensourcepos#3165]
Hello @jekkos,

I was in the process of manual installation of OSPOS version 3.3.4 using this zip : 

https://github.com/opensourcepos/opensourcepos/releases/download/3.3.4/opensourcepos.20210418204911.master.080e8a.zip 

However noticed that the version number isn't updated to 3.3.4 in file /application/config/config.php on line number 11 i.e : 

`$config['application_version'] = '3.3.3';`

It's still 3.3.3. Could you please update the version number to 3.3.4 in the file.

Regards.

**Comment by jekkos** [comment]
Ok thanks for the headsup, I'm bumping the version now.

**Comment by jekkos** [comment]
Latest build is available for download now.
