### ISSUE TITLE
ospos wish list 2 things for next update

### ISSUE THREAD

**Issue by loejo** [opensourcepos/opensourcepos#3166]
### Installation information
- OSPOS version is: 3.3.3

### I / New Feature

hi all thnx for the wonderfull ospos 
i wish there is way to make
-// price level 
-//payment module withe due limit or credit limit

**Comment by loejo** [comment]
hi @jekkos any chance to make it !!!

**Comment by jekkos** [comment]
Sure if you want to pay my hourly rate.. which I don't think will happen :+1:
