### ISSUE TITLE
Multiple prices in an item

### ISSUE THREAD

**Issue by nmangones** [opensourcepos/opensourcepos#3169]
How can I configure Multiple prices in an item, example: handle Sales price 1, Sales price 2, Sales price 3, Sales price 4, these prices would be stipulated by the profit percentages.

**Comment by nukerj** [comment]
Puede hacerse de la siguiente forma:
En la sección de Productos se agregan los 3 input precio 1 precio 2 y precio 3 al igual que en la Base de datos se agregan los atributos precio1, precio2 , precio2  y tipoprecio (este para tener un control sobre el tipo de precio seleccionado .

Luego en la sección de ventas en la vista register hacemos un Select al lado de tipo factura y cuando se seleccione el tipo de precio este cambie en el formulario según sea 1, 2 o 3.

Este método lo he desarrollado pero con otros requerimientos como por ejemplo asignarle puntos a cada producto y luego el cliente pueda parar con sus puntos acumulados como un metodo de pago.

**Comment by loejo** [comment]
@nukerj 
where i can found it please

**Comment by loejo** [comment]
@WShells  any solution !!!

**Comment by nukerj** [comment]
@loejo estoy trabajando en una mejora de esta funcionalidad, emulando la funcionalidad de mesas de trabajo como Precios Vários, esto para el selector en ventas para cuando se seleccione el tipo de precio, este con una condición en la vista registers cambie al precio según este registrado en la tabla ítems

Para cuándo lo tenga listo si el Administrador de proyecto OSPOS desea implementarlo con gusto le entrego el código con los cambios. Mientras tanto...

Johnny Vilchez
vilchezjohnny82@gmail.com
Soporte Técnico iDevSofteare

**Comment by jekkos** [comment]
duplicate of #3121

**Comment by jekkos** [comment]
#1017
