### ISSUE TITLE
Navigating to /public results in ERROR 500 on cloud installation

### ISSUE THREAD

**Issue by Bossakabe** [opensourcepos/opensourcepos#3171]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 080e8ac20c2aa2b4677f996b13eacb6f71bdffa0
- PHP version is: 7.4
- MySQL or MariaDB version is: 10.3.25
- OS and version is: Ubuntu 20.04.1
- WebServer is: Apache
- Selected language is: en-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I keep getting error 500 whenever I navigate to web application, available at [http://165.227.191.97/public/](url) I am currently hosting on the cloud using digitalocean. I followed the step-by-step installation guide and everything went well. But I keep getting the aforementioned error. Sadly, the Apache Error log is empty and the PHP error log just shows debug information and nothing else. Both error logs leave me with nothing to work with!

**Comment by jekkos** [comment]
Hi can you open the index.php file and set 'production' to development on line 56? Then reload and check the errors.

**Comment by apalestrini** [comment]
Hola, qué tal! He leído todas las ayuda e Issues y no encuentro solución. 
Instalé la versión 3.3.2; 3.3.3 y 3.3.4 en docker corriendo en un windows 10 de 64 bits y siempre tengo el mismo error (500)
Reinstalé docker
reinicié el equipo
seguí todos los detalles de instalación
Cualquier aporte será bien recibido
Gracias

**Comment by jekkos** [comment]
It might be a db connection issue, but can't say for certain unless you enable error logging

**Comment by apalestrini** [comment]
> It might be a db connection issue, but can't say for certain unless you enable error logging

Hi! Thanks for answering. It was exactly that, a database problem. I rebooted the mysql image and it lifted. You're very kind!

**Comment by Bossakabe** [comment]
Hi,

Sorry for the belated response. I wasn't available for a couple of days.
Please find below the error I am getting

An uncaught Exception was encountered
Type: Error

Message: Call to undefined function bcscale()

Filename: /var/www/cyberose/application/hooks/load_config.php

Line Number: 42

Backtrace:

File: /var/www/cyberose/public/index.php
Line: 315
Function: require_once

**Comment by odiea** [comment]
It appears that you did not install all the required phps

**Comment by Bossakabe** [comment]
@odiea bcmath was the problem. Thanks

**Comment by Bossakabe** [comment]
@odiea Any suggestion on how to resolve the new issue:

_**`The installation is not correct, check your php.ini file.`**_

**Comment by odiea** [comment]
Yes run a phpinfo and see if all of the extensions I showed you above are working

**Comment by Bossakabe** [comment]
@odiea It worked, I didn't have `mbstring` installed although it was already enabled in `php.ini`. Thanks for the assist really appreciate it!

**Comment by sabetech** [comment]
> It appears that you did not install all the required phps. 'bcmath', 'intl', 'gd', 'openssl', 'mbstring', 'curl'

Quick Question: I have installed bcmath (sudo apt install php-bcmath) and restarted apache2 and I'm still seeing the error `Message: Call to undefined function bcscale()`. OS is ubuntu 16.04 LTS. 

What am I missing?
