### ISSUE TITLE
please add whatsapp integration to send invoice to customer ... thanks

### ISSUE THREAD

**Issue by hendysama** [opensourcepos/opensourcepos#3172]
## please  add button   in here 
button  ways  to link go to: https://api.whatsapp.com/send/?phone=6281808080&text=%2C+thank+you+this+is+invoice&app_absent=0

 6281808080 is mobile number customer registered in ospos customer.... 
your ospos is good... in my country whatsapp user are very much

thanks for attention

![Cuplikan layar dari 2021-04-25 19-47-11](https://user-images.githubusercontent.com/27440454/115993942-31761d80-a5ff-11eb-8e9e-0678924dc51f.png)

**Comment by jekkos** [comment]
I think this one is already somewhere deeply buried underneath the pile of other feature requests.

**Comment by jekkos** [comment]
#922

**Comment by hendysama** [comment]
I want to edit this page in which folder is this page located?
