### ISSUE TITLE
cannot issue new item. Already reached 200 item

### ISSUE THREAD

**Issue by yh-sourceforge** [opensourcepos/opensourcepos#3174]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 
- PHP version is: 4.9.5
- MySQL or MariaDB version is: 5.7.33
- OS and version is: Windows 10; 20H2
- WebServer is: MalaysiaHost-vip
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue: cannot issue new item. Already reached 200 item
We are a fashion retailer.
For the same design, we sell stock in small (3-6 pcs) quantity, hence the item's description will be by the cost & supplier's codes.
So we have a widespread of stocks, which is more than 200

**Comment by jekkos** [comment]
Your PHP version looks really old. You should upgrade to 7.2 as this version is not supported. Also upgrade to 3.3.4 if you can as it resizes the session blob storage.

**Comment by yh-sourceforge** [comment]
TQ! jekkos
