### ISSUE TITLE
php script on clic complete sale button.

### ISSUE THREAD

**Issue by blutme** [opensourcepos/opensourcepos#3176]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: bb309c.
- PHP version is:  7.3
- MySQL or MariaDB version is: MariaDB
- OS and version is: Raspbian
- WebServer is: Nginx
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

hello friends, i want to run a php script when i click the complete sale button.
I know how to program in Python but I'm not very expert in PHP.
The question is.
How can I implement a code that executes a php file?

when I try to see the source code I only find this line of code.
<div class = "btn btn-sm btn-success pull-right" id = "finish_sale_button" tabindex = "6"> <span class = "glyphicon glyphicon-ok"> & nbsp; </span> Complete </div>

or what code should I implement in
ospos \ application \ models \ sales.php 

Thanks for your help.

**Comment by blutme** [comment]
I try to edit this code and insert a line on   ...\application\views\sales\register.php
`        $("#finish_sale_button").click(function()
        {
                <?php  include '/home/blutme/holaok.php'; ?>
                $('#buttons_form').attr('action', "<?php echo site_url($controller_name."/complete"); ?>");
                $('#buttons_form').submit();
        });
`
But nothing happens...

how should be the code to insert to run a php script? Thanks

**Comment by jekkos** [comment]
You are including a php file from a view, that does not seem to be a very robust solution to me.

**Comment by jekkos** [comment]
Just create a script in the project itself? You'll need to read up on CodeIgniter a bit to know how. Check their documentation. You can find plenty of examples on the internet.
