### ISSUE TITLE
Undefined variable in the Items Controller

### ISSUE THREAD

**Issue by dantux** [opensourcepos/opensourcepos#3177]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4 - 392d92.
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Line 1097 in file /Controllers/Items.php has an undefined variable $col
I am not able to import items because of that.

**Comment by jekkos** [comment]
HI, does this occur in the master version? What is the fix you did? Thanks

**Comment by jekkos** [comment]
Ok this issue is present in our latest release then. It might be php treating warnings as errors in this case.

**Comment by dantux** [comment]
Unfortunately, the PHP is not throwing the error in the front end. I saw it under Developer tools at the ajax return data. I couldn't figure out what $col wanted to be, so I don't have a fix yet. I just copied the line 1089 replacing 1097 so I can continue with my import. 
Also, the import function must be tested more. I got a lot of issues with it when having more than 1 stock locations.

**Comment by jekkos** [comment]
Thanks for letting us know. I agree that we are probably missing some unit tests here. Beside this @objecttothis changed the import functionality quite a bit and we'll have his rework in the master branch pretty soon.

**Comment by objecttothis** [comment]
> Thanks for letting us know. I agree that we are probably missing some unit tests here. Beside this @objecttothis changed the import functionality quite a bit and we'll have his rework in the master branch pretty soon.

@jekkos, in my changes I did find a few unused variables and undefined variables. The items controller especially has quite a few changes and I'll make sure to address this when I break off that chunk into its own PR. I'll also add in unit tests as I go but I may need some assistance getting unit tests to run in my setup. I'm using phpstorm now so that should make it easier.

**Comment by objecttothis** [comment]
@dantux My changes have been merged with the master and this should not be an issue any longer.  You can download a pre-release here https://github.com/opensourcepos/opensourcepos/releases/tag/items_controller_patch.3.4.0-dev

Please keep in mind that this is a pre-release and there may be bugs in it, so please test in a non-production environment before moving it to production.  If it isn't fixed, please comment here and I will open the issue again.
