### ISSUE TITLE
Details User Mannual and sell price unit wise

### ISSUE THREAD

**Issue by SanjuMale** [opensourcepos/opensourcepos#3178]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 
- OS and version is: Linux
- WebServer is: Godaddy
- Selected language is: En_IN
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

1. Where I can get detail user manual field wise functionality.?

2. How to add category in item when it is pick list 

3. I am purchas ing tem in box wise in every item separate quantities are in boxes and in that can be sold single pc or full box how to do?

Example - I have purchase 1 pepsi cartage that price is 100 in that there is 10 bottels and when going to se ll , I can sell cartage wise or bottel wise 

And in Coca-Cola cartage may 20 bottles in one cartage and in the same I can sell cartage wise or bottel wise 

How to do ?

**Comment by odiea** [comment]
You can read the Wiki and see if the info is in there.

**Comment by SanjuMale** [comment]
Can you share the link for all three solutions

**Comment by jekkos** [comment]
* Not sure if I understand the question
* Use the item kits for your bottles of coke. 
* Enable the category as dropdown in the config
