### ISSUE TITLE
Chrome freezes when returning from blank screen in Windows 10

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3179]
In my setup we use two PCs for "cash".  They're running the latest version of Chrome with the sales module on the screen.  Windows 10 is set to blank the screen after 15 minutes of idle time.  When we go to use them again the tab is unresponsive.  Switching tabs or applications and switching back again will unfreeze it.  I could tell it was frozen because the clock in OSPOS was frozen too.  I found the following link that described the same issue.  

https://answers.microsoft.com/en-us/windows/forum/windows_10-power/chrome-freezes-after-my-screen-turns-off/0629b423-c81b-4e36-81a6-0087097e87c5

And the following in that link as a fix.  

Open new tab with: chrome://flags/
Search for 'occlusion'
Disable option 'Calculate window occlusion on Windows'
Relaunch Chrome

I tested it out and it seems to work.  Just posting here so I don't forget.

**Comment by odiea** [comment]
Thanks for the tip Facebook always gives me this issue. I will try and let you know
