### ISSUE TITLE
Amount Tender in receiving database field

### ISSUE THREAD

**Issue by SanjuMale** [opensourcepos/opensourcepos#3181]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 
- OS and version is: cpanel
- WebServer is: Linux
- Selected language is: en
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I have 5 queries

1. When I recieved the order , I want to make supplier  mandatory , how can I do it?
2. In receiving when entered amount tendered where it store in database?
3. Can we make provision in sale like receiving Pack?
4. Can I hide tax1 and tax2 from Item?

Thanks in advance.

**Comment by jekkos** [comment]
1. I guess you can but you'll need to change the code for this
2. the amounts are stored in receivings_items
3. what do you mean with provision?
4. Also only feasible if you adapt the code

**Comment by SanjuMale** [comment]
Thanks for your reply

1. Please guide in which file and what code I have to be changed?
2. I am asking about amount tendered not amount item wised.
3. Basically I want to sale item box wise or individual item wise like receiving.
4. Please guide in which file and what code I have to be changed?

**Comment by jekkos** [comment]
You can use quotes or suspended sales for provisioning.

Changing the code is up to you, try to find someone to figure it out. Don't ask me to do your work for free.
