### ISSUE TITLE
Search Suggestions Layout

### ISSUE THREAD

**Issue by NOTIOINNOVATION** [opensourcepos/opensourcepos#3183]
Viewing of Available stock can be a big help

**Comment by jekkos** [comment]
Is this a feature request? Maybe be a bit more specific

**Comment by NOTIOINNOVATION** [comment]
![image](https://user-images.githubusercontent.com/12730365/118400929-41c96780-b696-11eb-9e31-b6f6985a3598.png)

Its helpful as well if we can select Available Quantity to display in sales module when searching products/items

**Comment by andriux1990** [comment]
> Its helpful as well if we can select Available Quantity to display in sales module when searching products/items

I was able to do that ... there are many changes in the code, it was somewhat difficult hehehe

**Comment by NOTIOINNOVATION** [comment]
i hope they can include this feature :)

**Comment by jekkos** [comment]
> Its helpful as well if we can select Available Quantity to display in sales module when searching products/items

the amount in stock is shown next to each item once it's added to the register, no?

**Comment by NOTIOINNOVATION** [comment]
![image](https://user-images.githubusercontent.com/12730365/119057386-f77e1880-b9fe-11eb-89aa-647afcfbaad8.png)

when we search for a product in the sales module, as you can see in the image, the product name and price shown in auto suggest, and we suggest showing the item quantity.

**Comment by chunter2** [comment]
@jekkos I think what @NOTIOINNOVATION is looking for is like what I added in this commit https://github.com/opensourcepos/opensourcepos/commit/7b20e2c29c0246bd3965b62e227fef7fc0b0569f to add the option to select Cost Price.  I think the issue is that the Quantity is in another table so it may not be available the way the code is currently set up.
