### ISSUE TITLE
Need to Damage out items

### ISSUE THREAD

**Issue by stellarcheese** [opensourcepos/opensourcepos#3185]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 
- PHP version is: 7.3.27
- MySQL or MariaDB version is:  mysqlnd 5.0.12-dev - 20150407 - $Id:
- OS and version is: windows 10
- WebServer is: Xampp
- Selected language is: enlgish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I run a repair shop, and need a way to mark parts/ items as damaged out in the system, with a comment option for a description of why.

**Comment by jekkos** [comment]
You can add a text attribute called 'damaged' and fill in the field in the items in this case?

**Comment by stellarcheese** [comment]
> 
> 
> You can add a text attribute called 'damaged' and fill in the field in the items in this case?

I will give this a try, will it show on the report, that is what I need. I need to be able to show it as a loss, and item no longer available.

**Comment by jekkos** [comment]
I think it will show only in detailed sales reports, if you select sale module visibility.

**Comment by stellarcheese** [comment]
this will actually not work.
I need to damage out an individual item from the mul;tiple of this item in stock 
IE:

I have 3 iPhone 8 screens in stock
tech breaks one during installation
Need to go to system and damage out 1 of the screens so the report reflects the item gone at a lose for what was paid.

**Comment by jekkos** [comment]
But then you did not sell it in that case? Do you return damaged items or you just keep them in the stock and want to mark them as such?

**Comment by stellarcheese** [comment]
The item is thrown away

I deal in electronics repair, so if a part is damaged, the supplier will not take it back. I need to reflect that in the database that the item was taken out of inventory due to a loss. Then make a report of damaged items. 

so maybe even a section called damages that you can create a damage out ticket, and add each damaged item to

I'm new to ospos so I'm not familiar with the code enough to create myself

**Comment by daN4cat** [comment]
@stellarcheese this is custom implementation for your use case. You need to find someone to implement that feature for you.
