### ISSUE TITLE
how to edit receipt ospos

### ISSUE THREAD

**Issue by hujanoke** [opensourcepos/opensourcepos#3187]
### help

I have 2 stocks, then I want to display the location of the stock on the sales receipt, is it possible?

 <?php echo $this->lang->line('reports_stock_location'); ?> to call lang line stock, then the order calls the name of the stock location based on sales how?

**Comment by odiea** [comment]
You can try this to see if it works for you. This is in receipt default .
```
<td><?php echo ucfirst($item['name'] . ' ' .$item['stock_name']. ' ' .$item['attribute_values']); ?></td>
```
