### ISSUE TITLE
installation on MAC (XAMPP)

### ISSUE THREAD

**Issue by dlwiindi** [opensourcepos/opensourcepos#3189]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 10.4
- OS and version is: Mac OSX 11.2.3
- WebServer is: apache 2.4
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

attempt to access https://localhost/ospos/public/ returns the following errors:

A PHP Error was encountered

Severity: 8192

Message: Required parameter $lang_array follows optional parameter $load_system_language

Filename: helpers/locale_helper.php

Line Number: 98

Backtrace:

File: /Applications/XAMPP/xamppfiles/htdocs/ospos/public/index.php
Line: 315
Function: require_once

An uncaught Exception was encountered

Type: RuntimeException

Message: Class Attribute already exists and doesn't extend CI_Model

Filename: /Applications/XAMPP/xamppfiles/htdocs/ospos/vendor/codeigniter/framework/system/core/Loader.php

Line Number: 353

Backtrace:

File: /Applications/XAMPP/xamppfiles/htdocs/ospos/public/index.php
Line: 315
Function: require_once

**Comment by odiea** [comment]
Did you use the following stable release?
https://github.com/opensourcepos/opensourcepos/releases

**Comment by dlwiindi** [comment]
yes i did. i actually tried 2 other releases but same thing.

**Comment by odiea** [comment]
Are all of the following enabled in php? 'bcmath', 'intl', 'gd', 'openssl', 'mbstring', 'curl'

**Comment by dlwiindi** [comment]
i checked and all were enabled but it turns out XAMPP for MAC OSx does not
install the extensions and they have to bein stalled manually. i have left
it for now and will install on a windows machine

**Comment by odiea** [comment]
I dumped Xampp in favor of Wamp. A little harder to install but it's nice to be able to change php versions on the fly
