### ISSUE TITLE
mismatched function signatures

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3199]
@jekkos the Attributes controller has a call to get_attribute_definition_data_row() which is located in the tabular_helper.  
```
/**
 * Returns customer table data rows. This will be called with AJAX.
 */
public function search()
{
	$search = $this->input->get('search');
	$limit  = $this->input->get('limit');
	$offset = $this->input->get('offset');
	$sort   = $this->input->get('sort');
	$order  = $this->input->get('order');

	$attributes = $this->Attribute->search($search, $limit, $offset, $sort, $order);
	$total_rows = $this->Attribute->get_found_rows($search);

	$data_rows = array();
	foreach($attributes->result() as $attribute)
	{
		$attribute->definition_flags = $this->_get_attributes($attribute->definition_flags);
		$data_rows[] = get_attribute_definition_data_row($attribute, $this);
	}

	$data_rows = $this->xss_clean($data_rows);

	echo json_encode(array('total' => $total_rows, 'rows' => $data_rows));
}
```

The problem is that the signature for that function in the tabular helper is
`function get_attribute_definition_data_row($attribute)`

You can see that it doesn't include the input for $this, nor is it called.  When I did a git blame on the lines of code it looks like they haven't been touched since your initial commit of the attributes code.  Can you tell me whether I should just delete the reference to $this in the function call or if you intended to do something with the reference in the function?  The function currently isn't trying to reference anything in $this.

**Comment by jekkos** [comment]
you can remove this second param. The CI context is accessed through the CI variables so it looks like it's unused anyway.

**Comment by jekkos** [comment]
Closing as currently resolved in the code
