### ISSUE TITLE
Composer and language error

### ISSUE THREAD

**Issue by truchosky** [opensourcepos/opensourcepos#3201]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.4.4
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

pretty simple, I use ospos in spanish, just for testing purpose I installed a own package with composer, inmediatly after that ospos went down, at login I have this issue:
![image](https://user-images.githubusercontent.com/9977546/121085618-1b3baf80-c7b0-11eb-9ee1-4f6f0ff494aa.png)
Even after remove the package that I installed with composer the error remains, but the strange part is that If I change to english all work again

**Comment by jekkos** [comment]
It seems that you do not have language pack installed. This needs to be done using this command

``` docker run --rm -v $(pwd):/app jekkos/composer php bin/install.php translations develop```

**Comment by jekkos** [comment]
Or you can just call


```
php bin/install.php translations develop
```

but you will need to have the correct tooling configured.
