### ISSUE TITLE
Failing to run the solutionm

### ISSUE THREAD

**Issue by KelvinMasakadza** [opensourcepos/opensourcepos#3202]
Hello Guys... l m looking for your assisatance on running this solution.. Any quick ways that can be easy to use. thank you

**Comment by KelvinMasakadza** [comment]
l m using VS code please assist

**Comment by SteveIreland** [comment]
Someone will need to explain to me what VS code has to do with running a PHP application on a nix based or windows based Web server.

Other than that, I would recommend reading the README or the Wiki here.  That will help narrow your question
