### ISSUE TITLE
Moving from PHP strings to GNU gettext

### ISSUE THREAD

**Issue by BudsieBuds** [opensourcepos/opensourcepos#3205]
What do you guys think about moving away from PHP strings in favor of GNU gettext? There are a lot of advantages like the auto fallback to English if a language is only partially translated.

This is taken from the Weblate documentation:

Format | Linguality | Plurals | Comments | Context | Location | Flags | Additional states
-- | -- | -- | -- | -- | -- | -- | --
GNU gettext | bilingual | yes | yes | yes | yes | yes | needs editing
PHP strings | mono | no | yes | no | no | no | &nbsp;

Found this about using it with CodeIgniter:
https://forum.codeigniter.com/thread-42661.html

Is this feasible or a big no-no? If this has your approval, I'd love to help getting this started. But you'd have to point me in the right direction of where to start.

**Comment by jekkos** [comment]
I'm not completely sold on the gettext format, I know it has it's roots in GNU tooling, and probably has good support in PHP as well.

If the only argument is the fallback to english then that can be accomplished easily in our application itself. So if we need a fallback then I'd do that by loading the english translations and use those strings if the ones for the current language aren't present.

**Comment by BudsieBuds** [comment]
Plurals seem like a pretty good feature to have when implemented the right way, will probably make translations more consistent. Also, gettext has more info for people translating locally instead of through Weblate.

To me it seems more like - why not? What is it that you're not sold on?

**Comment by jekkos** [comment]
My first gut feeling is that it might be a lot of work for little gain. 

On the other hand, I do know that weblate has better support for it as you say and this might indeed increase the translation quality. 

There's also a bit of CI specific logic around this format in OSPOS, but maybe we can hide the fact that the translation file is a .po to avoid having to rewrite this language handling. Also I have some scripts that I sometimes use to sync and reorder the files once a translation is added (but maybe those won't be needed anymore).

So I guess a bit of investigation might be needed before we decide.

**Comment by BudsieBuds** [comment]
Maybe it's a good test to only update the `login_lang` together with PR #3190? I understand that there have to be more coding changes so it's not like *click* and test, but might be a good and smaller test environment. Don't think my coding skills are good enough to implement it at the moment, but I might give it a go.

**Comment by jekkos** [comment]
@BudsieBuds with updating login_lang you intend to add this translation in gnu text format? I need to check a bit on how the CI support works but if it manages to load the translations in memory as it does with the current php strings, then we might be able to do it without too much code changes.

**Comment by BudsieBuds** [comment]
Yes, we could try that after we manage to merge PR #3190.

**Comment by jekkos** [comment]
@BudsieBuds as we discussed in our call last week, I did a fix for the translations fallback.

**Comment by jekkos** [comment]
So not sure if we should then consider to move to gettext.

**Comment by BudsieBuds** [comment]
Nice work @jekkos! Personally, I think we should still consider it for the future. It's the main translation format these days and gives extra features like plurals. However, the priority just got way lower if you ask me.
