### ISSUE TITLE
Bug/feature in reCAPTCHA

### ISSUE THREAD

**Issue by BudsieBuds** [opensourcepos/opensourcepos#3207]
There seems to be a bug/feature when the reCAPTCHA is set, but not the keys. If I set it with wrong keys and try to login once, it gives an error. The second time it just logs in. This is great if it's designed like this, but can somebody test if this doesn't happen when the reCAPTCHA is set in the correct way?

I've asked this question in a PR and got this answer by @daN4cat.

> reCaptcha works fine with my setup. Now and then the picture selection challenge pops up and clearing the process confirms you are a human. I haven't tested fir a while the negative sequence making mistakes and see what happens. I'll do later.
> Also, never tested inputting wrong keys, that error scenario was not covered.
> 
> _Originally posted by @daN4cat in https://github.com/opensourcepos/opensourcepos/issues/3190#issuecomment-855222859_

To explain it better, here's a little gif:
![animation](https://user-images.githubusercontent.com/12870258/121419666-7dd9aa80-c96c-11eb-85f7-d795e6fdf84f.gif)

**Comment by nyenius** [comment]
I use recaptcha since ver 3.3.0 and now upgrading to 3.34 with no problem at all (before and after update).

fout voor site-eigenaar: ongeldige sitesleutel = site owner error: invalid site key

Try to follow the basic setup again. there might be a typo or misplaced code / key.

**Comment by nyenius** [comment]
Yep incidentaly i 'reproduce' your error when setting up a test instalation. 

That error is because you use 1 key in more than one domain/subdomain.

![image](https://user-images.githubusercontent.com/613132/124027459-1bc90e00-da1d-11eb-8da6-4ac93ff70ee5.png)

**Comment by BudsieBuds** [comment]
Hi @nyenius,

Thanks for your response! I think you misunderstood the problem but would be awesome if you could test it out.
My setup was also a test setup and I added the wrong keys on purpose. If you look at the GIF I added, you can see that if I click it twice it ignores the invalid reCAPTCHA. My question is if this also happens when the keys are valid? So could you try to login on a valid reCAPTCHA twice with it being invalid?

**Comment by daN4cat** [comment]
The solution is to check username, password and recaptcha result all together in the same form validation callback.
The fix is now in master.

**Comment by jekkos** [comment]
Great, thanks for the fix @daN4cat !
