### ISSUE TITLE
Upgrade travis buildbox to npm 6.x

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#3208]
As we want to use newer libraries that are often not supported by bower anymore, we need to have a way to update the tooling used in our build pipeline.

We already have a custom buildbox for composer under jekkos/composer. Now we also need node, grunt (1.3?) and bower on top of that.

So suggestion is to move all tools into one Dockerfile. Maybe we can start by cloning the one in jekkos/composer and then add the neccesary packages to it.

**Comment by BudsieBuds** [comment]
Might as well be NPM 7.x right?

**Comment by jekkos** [comment]
Yes I guess that should be fine. I don't expect that bump to cause a lot of issues as we're not really using npm as heavily as bower.

**Comment by jekkos** [comment]
also #1891

**Comment by jekkos** [comment]
@BudsieBuds It's node 10 now I think

**Comment by jekkos** [comment]
In latest master now.
