### ISSUE TITLE
Different prices by location

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#3215]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
_______________________________
Hello @jekkos @daN4cat @odiea @objecttothis @SteveIreland @WebShells @BudsieBuds.

This is not an error .. I wanted to do a PR about this, but since I have some pending fixes, I wanted to consult it with you if the idea seems good to you.

When we create a different location, the prices in OSPOS are maintained and shared across all locations.

@nukerj and I made these prices different by location, if we create a new location .. the prices are 0 and will be saved independently. This is of great help if we have a location where there are additional expenses and the cost should not be the same

**Comment by objecttothis** [comment]
@andriux1990 sorry I couldn't respond earlier.  Currently OSPOS doesn't have specific functionality for multiple external locations (physical stores).  It does however have functionality for multiple stock locations within the same physical location (back storage, aisle B, Front counter).  Some have chosen to use this feature as multiple external locations and technically it does work on a basic level for that, but doesn't track sales well by multiple external locations.

In order to implement what you are suggesting, we would need to first give OSPOS multiple-external location support and in that design discussion answer the question of allowing different pricing per external location.  In my usage I have more use for multiple external locations than I do multiple stock locations within a physical location, but if a business needed both (as many will) then both need to be implemented well.

@jekkos @daN4cat thoughts?

**Comment by andriux1990** [comment]
@objecttothis I already have these changes ... and I am using them

**Comment by objecttothis** [comment]
> @objecttothis I already have these changes ... and I am using them

That's great. Any chance you could create a PR so we could take a look and perhaps merge it into the master provided it fits well?

**Comment by objecttothis** [comment]
@andriux1990 are you willing to submit a PR for the multi-location capabilities?  It's a feature I will eventually need as well and figured I can write it myself, but if you already have it and are willing, then that's less work for me.

**Comment by andriux1990** [comment]
> @andriux1990 are you willing to submit a PR for the multi-location capabilities? It's a feature I will eventually need as well and figured I can write it myself, but if you already have it and are willing, then that's less work for me.

Hello friend .. I have spent full time .. tonight or tomorrow I do a PR .. of these changes .. I have to extract these changes from the code. because in the version that I use ospos I have other changes, so to do a PR I have to sit down

**Comment by objecttothis** [comment]
> 
> 
> > @andriux1990 are you willing to submit a PR for the multi-location capabilities? It's a feature I will eventually need as well and figured I can write it myself, but if you already have it and are willing, then that's less work for me.
> 
> Hello friend .. I have spent full time .. tonight or tomorrow I do a PR .. of these changes .. I have to extract these changes from the code. because in the version that I use ospos I have other changes, so to do a PR I have to sit down

OK super.  Let me know if you need help.  One we have the branch setup we can take a look and I can help with any tweaks if they are needed.

**Comment by andriux1990** [comment]
https://user-images.githubusercontent.com/29256343/128398959-1ee4b850-a87b-4738-86ee-d34a29fbf4d9.mp4

**Comment by andriux1990** [comment]
>  simplescreenrecorder-2021-08-05_12.00.44.mp4

it works this way

**Comment by objecttothis** [comment]
> 
> 
> > simplescreenrecorder-2021-08-05_12.00.44.mp4
> 
> it works this way

I like it!  I couldn't quite tell from the screen language.  Do you have quantity by location as well, or just price by location?  Also, we need to port your UI changes over, but that's a different animal!  :)

**Comment by jgbalam8402** [comment]
It will help me pass the code since I want to perform the same action on my system

**Comment by andriux1990** [comment]
> > > simplescreenrecorder-2021-08-05_12.00.44.mp4
> > 
> > 
> > it works this way
> 
> I like it! I couldn't quite tell from the screen language. Do you have quantity by location as well, or just price by location? Also, we need to port your UI changes over, but that's a different animal! :)

I just made a fork to have ospos clean .. I'll put the changes

**Comment by 0x10101** [comment]
> simplescreenrecorder-2021-08-05_12.00.44.mp4

Would you mind sharing your theme/css files. The look is so cool, I've tried before but not that rookie in css and web design overall

**Comment by joshbudu** [comment]
Any progress on the different prices by locations?

**Comment by nukerj** [comment]
> Any progress on the different prices by locations?
@joshbudu Not now. @andriux1990  and me have this same different prices by locations as a custom change is fully functional. But for OSPOS I don't know what is planned.

If you need this functionality you can contact my telegram profile @jvilchez that I have already published in other comments on this topic.
