### ISSUE TITLE
Discount using amount is bugged

### ISSUE THREAD

**Issue by minhazulOO7** [opensourcepos/opensourcepos#3224]
### Background information (Used https://demo.opensourcepos.org)

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information (Used https://demo.opensourcepos.org)

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug

Let's say a customer wanted X product 10 piece, price is 15$ per piece, so the total price will be 150$. Now when I want to give discount of 2$ IN AMOUNT NOT IN PERCENTAGE then it will be 148$. BUT there is a BUG which deduct that amount from the quantity of the product. That means this same X product 2$ discount will be 10 piece x 15$ - 20$ = 130$! This same thing happened to my ospos pos soft. 3.3.4. Thought demo version is ok but it seems this bug slipped the radar. I think this is due to this update -> Fix discount register parsing in some specific locales.

![osposd](https://user-images.githubusercontent.com/14863018/123834831-aaf4f980-d929-11eb-84ba-d6b03a41339b.jpg)

THIS IS INSANE! SO PLEASE CHECK THIS ISSUE ASAP! :(

**Comment by SteveIreland** [comment]
The discount amount is applied per item.  Not a bug.  It's "as expected" in standard environments.  Adjust your discount amount to $0.20 per item which is the discount per item required to provide a $2.00 total line item discount.

**Comment by minhazulOO7** [comment]
> The discount amount is applied per item. Not a bug. It's "as expected" in standard environments. Adjust your discount amount to $0.20 per item which is the discount per item required to provide a $2.00 total line item discount.

But previously it was just the amount I wrote was discounted 😔. So this will be the new coding? If you can please keep a option like "Discount per item", "Discount per item quantity".

**Comment by minhazulOO7** [comment]
@SteveIreland Forgot to tell! If I select percentage then the discount is applied on total item! Not per item discount! So then why it applies only to amount? 😔

**Comment by minhazulOO7** [comment]
@SteveIreland although if any of you guys can add "Discount on total bill" then this issue will be mitigated. Please consider this addition 😔
