### ISSUE TITLE
So, i ask, in view of a possible devaluation of the currency in my country

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#3225]
a few days in Boliiva there was a speculation of the devaluation, in what way you can change all prices to dollars?
and i was planing for firsth time to open my store in 1 week, and happen this :! , i have 2 types of  store in 1 OSPOS, i gonna migrate 1 to other clean OSPOS, no problem but, 

a idea how change all prices?

a enhancer?
mysql statement?
a currency switcher? XD cool

i ask before i start manually changing prices

God bless u guys, Apologies for the inconvenience

**Comment by nyenius** [comment]
is changing **Localization** in configuration doesn't help?

**Comment by SteveIreland** [comment]
The complexity will depend on the features you have enabled, but it will most likely require a combination of SQL and PHP similar to some of the earlier migration scripts.   You might be able to find one that is close enough to start with.

**Comment by ekardian** [comment]
> is changing **Localization** in configuration doesn't help?

nop, do not help in that way, but is like @SteveIreland said, welp, i have like 181 items, i dont have time, i gonna write every one again... cofee time XD

**Comment by ekardian** [comment]
> The complexity will depend on the features you have enabled, but it will most likely require a combination of SQL and PHP similar to some of the earlier migration scripts. You might be able to find one that is close enough to start with.

that feature might be great in the ospos v7.0 XD

**Comment by ekardian** [comment]
i imported the new csv, just a few rows, worki like a charm, but the id count grew, explained in this hilo [https://github.com/opensourcepos/opensourcepos/issues/3260#issue-957361326](https://github.com/opensourcepos/opensourcepos/issues/3260#issue-957361326)

**Comment by objecttothis** [comment]
@ekardian The current master now has the ability to import a CSV that updates items.  You only need the item_id and whatever fields you want to update.  Download the CSV Item Import Template and place the item_id in the Id field.  Then your place your wholesale/retail prices in dollars (without currency symbols).  You can download the release in https://github.com/opensourcepos/opensourcepos/releases/tag/items_controller_patch.3.4.0-dev but keep in mind that this is a development version and you should have a backup of your database.

**Comment by ekardian** [comment]
> @ekardian The current master now has the ability to import a CSV that updates items. You only need the item_id and whatever fields you want to update. Download the CSV Item Import Template and place the item_id in the Id field. Then your place your wholesale/retail prices in dollars (without currency symbols). You can download the release in https://github.com/opensourcepos/opensourcepos/releases/tag/items_controller_patch.3.4.0-dev but keep in mind that this is a development version and you should have a backup of your database.

thx objetivo, now thanks to ospos im a compulsive guy for backup all, just i need a backup of my backups and burn it in to a dvd, then to a usb, then to my nas server, and ftp server. syncing tool for all XD i gonna test this sunday, thx to the community, bless
