### ISSUE TITLE
Cannot setup multiple Application on a single server

### ISSUE THREAD

**Issue by akisoft21** [opensourcepos/opensourcepos#3226]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hello team, 
Please i am facing a very weird problem here.
i have a VPS on Google cloud (ubuntu 18.04)
i want to set up multiple ospos shop for 2 different companies with different urls, i have pointed both url to the VPS
i have successfully setup the first ospos shop for company A
but for company B after setup i am unable to lgoin, its redirecting back to login page.

**Comment by akisoft21** [comment]
@nyenius subdomains

**Comment by nyenius** [comment]
each subdomains has individual install?

**Comment by akisoft21** [comment]
@nyenius yes they do, but it's only the first installed that works, I have tried it on another VPS, I faced the same problem.
I used Apache as the server, and I created different virtual hosts for each subdomains pointed to each installation.

**Comment by ekardian** [comment]
> 
> 
> @nyenius yes they do, but it's only the first installed that works, I have tried it on another VPS, I faced the same problem.
> I used Apache as the server, and I created different virtual hosts for each subdomains pointed to each installation.

i see, i dont use vps, but u can watch ur .htaccess, look the redirection about of to where u can point ur subdomain, perm files too, requiriments on your php, maybe u have a direfrent instance for every subdomain? i dont know, full access to the database to that user db, that problem happens to me a lot, at the end in the .htaccess wast the last time, but who know, u can change the world with the free sowftware.. bless

**Comment by truchosky** [comment]
is an apache config, each subdomain should be pointed to each ospos installation

**Comment by jekkos** [comment]
This is question is not really related to ospos (how to setup a subdomain)? Check apache docs for this.
