### ISSUE TITLE
Employee add or update failed OSPOS

### ISSUE THREAD

**Issue by kizitox2** [opensourcepos/opensourcepos#3239]
### I installed ospos for managing inventory in a local store.At first everything was working fine until when I tried to add a new employee and I received error message **Employee add or update failed**. I am using ospos 3.3.4

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 
- PHP version is: 7.3.29
- MySQL or MariaDB version is: 5.7.23-23
- OS and version is:  Linux 4.19.150-76.ELK.el7.x86_64
- WebServer is: Apache
- Selected language is: English-GB
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
At first everything was working fine until when I tried to add a new employee and I received error message **Employee add or update failed**. I am using ospos 3.3.4

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
Check to see if there are any errors in the Login tab. You must also check the grants or permissions tab for errors

**Comment by kizitox2** [comment]
> Check to see if there are any errors in the Login tab. You must also check the grants or permissions tab for errors

Checked no error message. Where can find system errors logs in ospos?Thanks

**Comment by odiea** [comment]
In application/config/config line 251 $config['log_threshold'] = 1; // was 0. Then in application/logs you may see something showing in there.

**Comment by kizitox2** [comment]
> In application/config/config line 251 $config['log_threshold'] = 1; // was 0. Then in application/logs you may see something showing in there.

Thanks and appologies for the delay;
This is the text I receive in the log.
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-07-12 18:58:06 --> Could not find the language line "items_Kakola_Branch (TBD)"
ERROR - 2021-07-12 18:58:06 --> Could not find the language line "items_Masumbwe_Branch (TBD)"
ERROR - 2021-07-12 18:58:06 --> Could not find the language line "receivings_Kakola_Branch (TBD)"
ERROR - 2021-07-12 18:58:06 --> Could not find the language line "receivings_Masumbwe_Branch (TBD)"
ERROR - 2021-07-12 18:58:06 --> Could not find the language line "sales_Kakola_Branch (TBD)"
ERROR - 2021-07-12 18:58:06 --> Could not find the language line "sales_Masumbwe_Branch (TBD)"
ERROR - 2021-07-12 18:59:27 --> Query error: Duplicate entry 'Dickson' for key 'username' - Invalid query: INSERT INTO `ospos_employees` (`username`, `password`, `hash_version`, `language_code`, `language`, `person_id`) VALUES ('Dickson', '$2y$10$56n4uGpA9JJQRB5SZO/j..UUL6zZonC9FiwTiZ19IjgA9LEbQFkOi', 2, '', '', 393)

**Comment by odiea** [comment]
This may be the issue.
ERROR - 2021-07-12 18:59:27 --> Query error: Duplicate entry 'Dickson' for key 'username' - Invalid query: INSERT INTO ospos_employees (username, password, hash_version, language_code, language, person_id) VALUES ('Dickson', '$2y$10$56n4uGpA9JJQRB5SZO/j..UUL6zZonC9FiwTiZ19IjgA9LEbQFkOi', 2, '', '', 393)

**Comment by jekkos** [comment]
Good catch @odiea . We do not have any UI handling of this case.

**Comment by kizitox2** [comment]
> This may be the issue.
> ERROR - 2021-07-12 18:59:27 --> Query error: Duplicate entry 'Dickson' for key 'username' - Invalid query: INSERT INTO ospos_employees (username, password, hash_version, language_code, language, person_id) VALUES ('Dickson', '$2y$10$56n4uGpA9JJQRB5SZO/j..UUL6zZonC9FiwTiZ19IjgA9LEbQFkOi', 2, '', '', 393)

Ok,I have tried to go to the db but cannot find a duplicate.

**Comment by jekkos** [comment]
The db constraint has prevented you from adding that duplicate.

**Comment by jekkos** [comment]
So you should already have one user with this username in the db. Creating a second duplicate one is not allowed.

**Comment by kizitox2** [comment]
> So you should already have one user with this username in the db. Creating a second duplicate one is not allowed.

Thanks;
I have tried the solution of adding a different user name and it worked.I hope in the future edition we might have a way for the error message to the user to be more specific so as to help in taking a proper action.Thanks and all the best

**Comment by jekkos** [comment]
Yes I guess we should add aa callback that checks whether the username already exists before the save trigger.

**Comment by jekkos** [comment]
Just checked the code real quick. It's weird that this case is not handled gracefully as if the query fails we should at least show an error popup

**Comment by jekkos** [comment]
Just checked the code real quick. It's weird that this case is not handled gracefully as if the query fails we should at least show an error popup

**Comment by jekkos** [comment]
Ok I've added a simple check to verify whether a username exists before we try to save the employee.

**Comment by kizitox2** [comment]
@jekkos Thanks alot for the response and action taken so far.I believe to gether we can make OSPOS better.Will the fix be available in the next update or will I have to implement the fix in the current version?

**Comment by jekkos** [comment]
The fix is in master now, you can download the last build within half an hour.

**Comment by jekkos** [comment]
Fix in master.
