### ISSUE TITLE
accents converted "?" when enabled config_category_dropdown for atributes

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#3241]
### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 392d92
- PHP version is: 7.4.20
- MySQL or MariaDB version is: 10.3.29-MariaDB-cll-lve
- OS and version is: Linux 3.10.0-962.3.2.lve1.5.44.2.el7.x86_64
- WebServer is: LiteSpeed
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

HELP? i enabled config_category_dropdown (TBD) and i have issues with espanish characters, like SSD SOLID = Disco Sólido ===> Disco S?lido (wrong character)

![imagen](https://user-images.githubusercontent.com/6296036/125239095-29e91b00-e2b6-11eb-82f7-fc62e47ae732.png)

**Comment by jekkos** [comment]
Thanks for this bugreport @ekardian .

I have pushed a fix for this on the dev server. Can you check and confirm if the issue is fixed?

**Comment by ekardian** [comment]
@jekkos fixed
