### ISSUE TITLE
Buttons show but no action when clicked in Docker development environment

### ISSUE THREAD

**Issue by mcclone2001** [opensourcepos/opensourcepos#3242]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 080e8ac2
- PHP version is: 7.4
- MySQL or MariaDB version is: 
- OS and version is: WSL2 on Windows 10
- WebServer is: Apache
- Selected language is: default
- (If applicable) Docker installation: Docker version 20.10.5, build 55c4c88, docker-compose version 1.29.0, build 07737305
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I have tried this with both the most recent checkout in master and the 3.3.3 checkout 080e8ac2, both build ok with no errors but when I log in some buttons are clicked but no action is executed.

There is a closed similar issue here https://github.com/opensourcepos/opensourcepos/issues/3221, but no explanation is provided on how to solve this in a development environment.

There are some errors in the console but they appear on the page loading, clicking on the button generates no errors in the console nor network requests or logs in the backend.

![image](https://user-images.githubusercontent.com/15655540/125543169-bafb0ba6-ceaa-4cfd-bfd4-8c146c8b8811.png)

Thanks a lot for your help

**Comment by jekkos** [comment]
Can you pull latest master and rebuild all javascript? Maybe remove all downloaded files first

`rm -rf public/bower_components`
`rm -rf node_modules`

then run grunt again

**Comment by mcclone2001** [comment]
Tried with a clean installation with the latest commit in master (c3bdff6f), it worked flawlessly.
Sorry for the inconvenience
