### ISSUE TITLE
There are no Cashups to display

### ISSUE THREAD

**Issue by blutme** [opensourcepos/opensourcepos#3245]
### Installation information

- OSPOS version is: 3.3.3 and 3.3.4
- OSPOS git commit hash is: 
- PHP version is: 7.3
- MySQL or MariaDB version is: Mysql
- OS and version is: windows 10
- WebServer is: apache
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hello friends... 

I have ospos installed on both windows os and raspbian os, but when I try to create a cashup in windows os the cashup is created successfully because is notified then when I query by phpmyadmin the table ospos_cash_up I can see the cashups was created succesfully too... , when I make a backup of the database and transfer it to the raspberry pi and i see the cashups these if they appear in the visual register. The raspberry pi has MariaDB database... 

I do a clean installed of ospos  on windows both version 3.3.3 and 3.3.4 with the database clean but it still does not show the new created cashups.

what could be happening? has something to do with mysql and mariadb versions

the creation of a user, product and others work perfectly.

Thanks.

**Comment by odiea** [comment]
Enable error logging and see if anything shows

**Comment by daN4cat** [comment]
Version of MySQL or MariaDB? You missed to report that.

**Comment by blutme** [comment]
> Enable error logging and see if anything shows

Sorry, the error log is not show me anything. so I did was uninstall mysql client and server from windows and install mariadb and now I can see the records in the cashups.

**Comment by blutme** [comment]
> Version of MySQL or MariaDB? You missed to report that.

before MySQL, now I have MariaDB... I needed to solve quickly and the only thing that occurred to me was to install MariaDB and works for me.

**Comment by odiea** [comment]
Glad you got it working.
