### ISSUE TITLE
How to disable item box in sales module when payment added

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3247]
I'm looking for a way in code to disable the item box in the sales module when a payment is added.  I know this may not be something most people want but just looking for some help.  My use case is our cashiers scan items and then add a payment.  If the payment is debit/credit they manually enter the amount in a terminal.  The problem is they forget to "Complete" the sale in OSPOS.  Then they start scanning the next customer which added items to the first transaction.  They either have to remove the extra items to complete the sale or they don't realize what's happening and add the extra payment and complete the sale anyways.   Any ideas?  

Thanks

**Comment by odiea** [comment]
Retrain the Employees or start docking their pay checks.

**Comment by chunter2** [comment]
@odiea Normally I'd agree but they're all volunteers.  :)  Is there a "grey out" option for that box that could be enabled/disabled based on whether the Complete button was up?

**Comment by odiea** [comment]
I am not a programmer but maybe the following will help you out. Before```<?php echo form_open($controller_name."/add", array('id'=>'add_item_form', 'class'=>'form-horizontal panel panel-default')); ?>``` I added the following.
``` 
 <?php if(!count($payments) > 0)
				{
				?>
```
then after close form
```
<?php
}
?>
```

**Comment by chunter2** [comment]
@odiea That worked!  Thanks for the tip.  It seems to remove the item input line completely.  I'm wondering if there's a way to just grey out the box instead of removing the line.  Just for aesthetics.  Looks like the following is what creates the text input box.  

`<li class="pull-left">`
`<?php echo form_input(array('name'=>'item', 'id'=>'item', 'class'=>'form-control input-sm', 'size'=>'50', 'tabindex'=>++$tabindex)); ?>`
`<span class="ui-helper-hidden-accessible" role="status"></span>`
`</li>`
 
Maybe @jekkos knows how to grey it out and then use the if from above to enable or disable it?

**Comment by odiea** [comment]
I thought the way your employees were they would use the add item button then. Changing the location of the code will give you the following.
```
<?php if(!count($payments) > 0)
				{
				?>
				<li class="pull-left">
					<?php echo form_input(array('name'=>'item', 'id'=>'item', 'class'=>'form-control input-sm', 'size'=>'40', 'tabindex'=>++$tabindex)); ?>
					<span class="ui-helper-hidden-accessible" role="status"></span>
				</li>
				<?php
				}
				?>
```

![2021-08-06 03_55_27-Window](https://user-images.githubusercontent.com/10962177/128493425-1b0966e6-f7f0-4265-8b78-a13f9469f5fd.png)

**Comment by chunter2** [comment]
@odiea I'm not sure why I didn't think of putting the if only around the text field.  :)  I think this is a good workaround.  

The issue with our cashiers is they forget to hit complete to finish the previous sale and then don't look at the screen before using a scanner to scan items for the next customer.  When they do look and realize they've added to the previous sale they either cancel the sale completely and we don't get a record of that sale or they just add a payment and click complete which now has some extra items on it and has a total that doesn't match what they typed into the payment terminal.  Hopefully this cuts down on these issues.  

Thanks
