### ISSUE TITLE
![image](https://user-images.githubusercontent.com/3019836/106349494-40d71a80-62df-11eb-9882-f166a7b58d55.png)

### ISSUE THREAD

**Issue by Chris-ch41** [opensourcepos/opensourcepos#3250]
![image](https://user-images.githubusercontent.com/3019836/106349494-40d71a80-62df-11eb-9882-f166a7b58d55.png)

_Originally posted by @ayieye in https://github.com/opensourcepos/opensourcepos/issues/2989#issuecomment-770167669_

**Comment by Chris-ch41** [comment]
![Screenshot from 2021-07-27 19-57-49](https://user-images.githubusercontent.com/85863043/127235740-c2d0541d-a297-4402-ab5e-f2971b977d06.png)
![Screenshot from 2021-07-27 19-53-50](https://user-images.githubusercontent.com/85863043/127235749-19f3c91e-189d-4e2d-ac1b-ebd596741786.png)
![Screenshot from 2021-07-27 19-53-04](https://user-images.githubusercontent.com/85863043/127235756-d582447e-4d64-4911-b758-806de5689bbd.png)

Not work, im try in ver 3.4 and ver 3.3

**Comment by jekkos** [comment]
Why open a new issue for this?
