### ISSUE TITLE
Taxable Amount and Tax Amount is wrong both in OSPOS Demo and My Local System.

### ISSUE THREAD

**Issue by govardhan080** [opensourcepos/opensourcepos#3251]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4 - 392d92
- OSPOS git commit hash is: 080e8ac
- PHP version is: 7.4.16
- MySQL or MariaDB version is: 5.7.32
- OS and version is: MacOs Catalina 10.15.6 (19G2021)
- WebServer is: 2.4.46
- Selected language is: English (US)
- (If applicable) Docker installation: NA
- (If applicable) Installation package for the LAMP/LEMP stack is: MAMP

### Issue / Bug  / Question / New Feature

**Taxable Amount and Tax Amount is wrong both in OSPOS Demo and My Local System.**

**Configuration**
Tax Included : True
Tax 1(CGST): 2.5%
Tax 2(SGST): 2.5%

**Steps to reproduce Issue**
Step 1: Create an Item1 with Price as 10000 and set Tax1 & Tax 2 to 2.5% each.
Step 2: In Sales-> Add Item1, In the right block price summary shown below customer, 
            **The Subtotal and Tax Amount both are wrong. In this case Subtotal before tax is showing as 9512.2 instead of 9523.8**
           **The Tax1 (2.5%CGST) is showing as 243.9 instead of 238.1**
           **The Tax2 (2.5%SGST) is showing as 243.9 instead of 238.1**

This is a very serious issue in taxation, surprised to see that it exists even in Demo version hosted in https://demo.opensourcepos.org/ 
or if this is a configuration mistake from my end, please let me know how to fix it.
Thanks in advance.

![Screenshot 2021-07-28 at 12 57 41 PM](https://user-images.githubusercontent.com/88027749/127281895-1af28422-bb84-48e9-876a-befe25228b52.png)
![Screenshot 2021-07-28 at 12 42 22 PM](https://user-images.githubusercontent.com/88027749/127282134-e238c4f7-8d8f-4288-93dd-ba901bd387b9.png)

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
@SteveIreland  any Idea what might be going on here?

**Comment by SteveIreland** [comment]
@odiea I will check.

**Comment by jekkos** [comment]
How do you get to this 238.1?

for 2.5% tax included I find the following

10000 / 1.025 = 9756,09 so 243.9 tax which matches the screenshot.

**Comment by govardhan080** [comment]
@jekkos 
Tax is always calculated on **Taxable Amount** i.e **Price before Tax**, since the price set in item is inclusive of Tax, we have to reverse calculating **Price before tax**, to do that, considering there are two taxes (Tax 1 and Tax 2) set. i.e CGST = 2.5% and SGST = 2.5%, we have to sum both tax percent while arriving at "Price before tax" (Taxable Amount)

Here is how it is expected to behave.

To calculate **Price before Tax(Taxable Amount)** we have to first add all the tax percent 

Step 1: i.e 2.5% + 2.5% = 5%, i.e its 1.05 

Step 2: So Price before tax (taxable amount) = 10000 / 1.05 = 9523.8

Step 3: Now if we apply tax individually on **Price before Tax (Taxable Amount)** i.e 9523.8 * 2.5% = 238.1 for Tax 1 & Tax 2

Step 4: Now if we sum 9523.8 + 238.1 + 238.1  = 10000.

comparing this with current behaviour in system, where **Price before Tax** is 9512.2, if we apply 2.5% on it, we get 237.8 + 237.9 and will not add up to 10000 when summed.

i.e 9512.2 + (9512.2*2.5%) + (9512*2.5%) = 9987.8 != 10000

Hope this clarifies.

**Comment by jekkos** [comment]
Indeed you might be the first one to use multiple tax tiers together with a tax included scenario.

**Comment by odiea** [comment]
@govardhan080 it would be great if you would share your modified code with us. Thanks

**Comment by jekkos** [comment]
@govardhan080 for India GST specifically we have 'destination based' tax, which should support your case better.

Also indeed as @odiea any fixes for this are welcomed. If you submit them it will be easier for you to update in the future.

**Comment by SteveIreland** [comment]
Sorry.  Couldn't make time to explore this over the weekend because I ended up needing to work most of the weekend.  (Hadn't had to do that in a long time.)  But will try again this coming weekend.  Glad he was able to develop a work-around.
