### ISSUE TITLE
Cashups wrong sum

### ISSUE THREAD

**Issue by emilianocaro** [opensourcepos/opensourcepos#3253]
### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: ??
- PHP version is: 7.4.21
- MySQL or MariaDB version is: 10.4.20
- OS and version is: Windows

### Issue / Bug 

I'm having some trouble when using chash ups. If I make a second entry on a same day, isn't it supposed to sum up sales between that range of time? It sums everything again.
It should take into account the second "Open cash = 491" and data between that range of time.
Cause for a correct result I have to do: (Payments) $12126 - (Expenses) $12235 + (FIRST OPEN CASH) $584 = $475
The real equation I have on my papers are: 2nd OPEN $491 + Total cash payments (in that period of time) $2759 - (Expenses) $2775 = $475 (and not 382 = 491+12126-12235)->That's not the right way.
![36f749bd-2572-4e7f-b552-c9b3b3081e7c](https://user-images.githubusercontent.com/65317705/127379704-774f5ab5-9a3a-4156-8091-72361786b14f.jpg)
![dd158849-37ae-41d7-8272-ea112d58b9ef](https://user-images.githubusercontent.com/65317705/127379710-fb144bde-7c45-49fe-ba49-d795e3eb098d.jpg)
![d5512a6a-fc28-4b59-9130-e16339504a89](https://user-images.githubusercontent.com/65317705/127379714-c6cf542a-6af7-4d7e-821d-a06b721b4e2b.jpg)
![5b91076b-2d46-4912-9ec8-735fa5bb015f](https://user-images.githubusercontent.com/65317705/127379715-f39a3557-5f22-45a2-bc98-dfb082e5bd18.jpg)

**Comment by jekkos** [comment]
Not sure how if cashups were designed to work this way. Perhaps @daN4cat or @odiea can shed some light here.

**Comment by odiea** [comment]
It is a very basic Module. Start with setting the day and opening amount save then add the debits and credits at closing.

**Comment by daN4cat** [comment]
You open one at the beginning of the day and close it at the end of the day reporting any petty cash transaction and the rest are totals of the day pre filled.
Now I have no idea if something was changed somewhere else that changed the prefilled totals and produces some error.

To be honest I don't get the test scenario here.

**Comment by daN4cat** [comment]
There are no intermediate steps to add/remove something. It's just for the daily end of the day log.

**Comment by emilianocaro** [comment]
For those ones with the same problem I had. To be able to have more than one open-closed cashup on the same day, you need to activate "Date and Time Filter" on the config->Localization->Date and Time Filter
Otherwise "Closed cash" won't give you the right number as it would count the whole day transactions.

**Comment by daN4cat** [comment]
Who thought you anything?

We explained you the current design, which is no multiple cashups in a day.
That was my initial contribution, more than that probably happened by later contributions or by chance, I don't know to be honest.

Happy for you to contribute further improvements, it's open source for a reason 😉
