### ISSUE TITLE
Sales Filter Debit card missing

### ISSUE THREAD

**Issue by emilianocaro** [opensourcepos/opensourcepos#3254]
### Issue / Bug  / Question / New Feature

Module Sales->Takings->Filter "Debit card" is missing, also at lang file: $lang["sales_debit_filter"] = "Debit Card"; should be added.

**Comment by jekkos** [comment]
@emilianocaro could you make a PR to add this? Should be rather straightforward and a good learning exercise for contribution. Thanks!
