### ISSUE TITLE
Spanish translation updated Text

### ISSUE THREAD

**Issue by emilianocaro** [opensourcepos/opensourcepos#3255]
I don't know how to put this on pull request. I've updated Spanish translation. Some automatically translated text were wrong and completed some missing ones.
https://filebin.net/0wdr0kptpf8dneka

**Comment by jekkos** [comment]
@emilianocaro thanks for the files, I'll update them for you.

What you need to do in order
 

fork the repo on github
clone that forked repo to your local machine
edit the files or replace them with the ones in your zip
commit those changes to your local repo
push those changes to your forked github
create a pull request against this repo

**Comment by jekkos** [comment]
@emilianocaro can you check if the changes applied are fine?

**Comment by emilianocaro** [comment]
It's Ok, i'm still checking all lines and pulling request to merge as I go by
