### ISSUE TITLE
The site on https doesn't load properly! It works fine on port 80

### ISSUE THREAD

**Issue by dantux** [opensourcepos/opensourcepos#3256]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 10.5
- OS and version is: Alpine 3.5 (docker container)
- WebServer is: Nginx
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue 

I am running apache with PHP7.2 under docker container (alpine linux) for the OSPOS application with another docker running MariaDB database.
The docker apache is listening to port 80 and it outputs to external port 53080
On the Docker host physical server I have a NGINX reverse proxy that ensures the requests on port 80 for the name "inventory.imperiodelasunas.com" is served from the localhost 53080.
This works great, but I installed an SSL certificate managed by the NGINX server and now the OSPOS doesn't load properly when accessing https instead of http.
Please see the difference between:
http://inventory.imperiodelasunas.com/
and 
https://inventory.imperiodelasunas.com/

I have other servers with the same kind of setup, and they all work fine except OSPOS.
Any ideas?

**Comment by daN4cat** [comment]
There was an env variable FORCE_HTTPS, not sure it's still there but set it to true in your docker container and try again.

**Comment by dantux** [comment]
> There was an env variable FORCE_HTTPS, not sure it's still there but set it to true in your docker container and try again.

Thank you @daN4cat . I tried (sent that environemental variable inside the container): FORCE_HTTPS='1' but is still the same issue.
Does it make a difference that the server inside the container (apache2) is using http? The https (and the ssl) is on the outside reverse proxy server (NGINX)

**Comment by jekkos** [comment]
Your https site does seem to load, but it fails to load the css file for some reason. Might be a wrong rewrite rule or something?

**Comment by jekkos** [comment]
indeed it seems the setup is not outputting the links as https. Indeed @daN4cat this force variable is what you should use as the container cannot know whether there is a reverse proxy installed

```
$config['https_on'] = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') || (isset($_ENV['FORCE_HTTPS']) && $_ENV['FORCE_HTTPS'] == 'true');
```

**Comment by jekkos** [comment]
Can you set it to `true` instead of `1`?

**Comment by dantux** [comment]
Thank you @jekkos . I just change to `true` instead of `1` and the result is the same. Is very weird. 
This is how my docker-compose.yml file looks like (if it makes a difference):

![image](https://user-images.githubusercontent.com/3638646/127528686-c2fb2e99-eeb5-4399-ab67-4b35764bf62c.png)


And this is how the environment looks in that container:

![image](https://user-images.githubusercontent.com/3638646/127528329-d32eef14-f107-42b3-98ec-6a7c7d88d2fd.png)

**Comment by dantux** [comment]
> Your https site does seem to load, but it fails to load the css file for some reason. Might be a wrong rewrite rule or something?

Here are the rewrite rules I have in the `.htaccess` file:

![image](https://user-images.githubusercontent.com/3638646/127530916-6dd43077-1426-4c16-b222-46aff61d86f0.png)

**Comment by daN4cat** [comment]
What's the setup with nginx reverse proxy?

**Comment by dantux** [comment]
![image](https://user-images.githubusercontent.com/3638646/127551424-df5e62a6-a0e6-4896-a41f-8bfe3d30a67a.png)

**Comment by jekkos** [comment]
@dantux from your screencap it looks like you are not using the docker images from my docker hub.
Are you sure you have that line I posted earlier in config.php?

**Comment by dantux** [comment]
Is true, I'm not using your image (didn't know you have one). I'm using what I found to work best for all my servers.

But I'll check out your image and give it a try.

**Comment by dantux** [comment]
I just had a look at the Docker instructions you have for OSPOS. Seems a bit complicated where I just used a docker for a simple webserver to serve your app. 
I'll investigate and implement it when I get some time soon; I'm afraid it would conflict with my existing NGINX reverse proxy I have running several sites on that server, all served on port 80 and 443. But I'll look into it.

Thank you for the suggestion. I

**Comment by jekkos** [comment]
Why would it conflict? I think you should be able to replace the apache part with the one on docker hub.. there's no SSL configured in that one so it should play nicely with an external nginx.

I use a similar setup for the demo/dev setup.

**Comment by dantux** [comment]
I was reading "Nginx install using Docker" here: https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md
where it says it can install a reverse proxy.
I admit, I only had a quick look.

I'll give it a try tomorrow and let you know how it goes.

**Comment by dantux** [comment]
Hi Jekkos. Thank you for all your help!
I downloaded the latest 3.3.4 version, I created the Docker image, and now is working fine!
Not sure what had caused the issue before but thankfully is OK now. 

Have a great day and thank you so much for your assistance.

**Comment by jekkos** [comment]
I think this config line was changed a couple of months ago, so that might have been the issue. Good to hear you have it working now.

**Comment by lgwapnitsky** [comment]
Any recommendation on how to resolve this issue on an Apache2 installation running behind HAProxy?

**Comment by daN4cat** [comment]
Have you set the config param to true if using https?

**Comment by lgwapnitsky** [comment]
Which parameter is that

**Comment by daN4cat** [comment]
Read the thread from the beginning please.

**Comment by lgwapnitsky** [comment]
where is that set in a non-docker setup?

*Larry G. Wapnitsky*


*E: ***@***.****
*Web: Larry.Wapnitsky.com <http://larry.wapnitsky.com/>Twitter:
@LGWapnitsky*

**Comment by lgwapnitsky** [comment]
ok. i've created a conf file that sets the variable. I can load my front
page, with bad css (not what I want). tried to login, it goes back to HTTP

**Comment by lgwapnitsky** [comment]
[image: image.png]

**Comment by daN4cat** [comment]
Have you checked htaccess if set correctly with the path you have set your ospos too?

**Comment by lgwapnitsky** [comment]
Yes, I did. It is set exactly as it is written in the file. I made sure
that before I did the installation

**Comment by daN4cat** [comment]
Do you have a sub path in the url?

**Comment by lgwapnitsky** [comment]
No, I do not.

Here is my .htaccess file:

***@***.***:/var/www/html# cat .htaccess
# redirect to public page
  <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^public$
    RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge [NC]
    RewriteRule "^(.*)$" "/public/" [R=301,L]
  </IfModule>

# disable directory browsing
# For security reasons, Option all cannot be overridden.
Options +SymLinksIfOwnerMatch -Indexes

# prevent folder listing
IndexIgnore *

# Apache 2.4
<IfModule authz_core_module>
  # secure htaccess file
  <Files .htaccess>
    Require all denied
  </Files>

  # prevent access to PHP error log
  <Files error_log>
    Require all denied
  </Files>

  # prevent access to LICENSE
  <Files LICENSE>
    Require all denied
  </Files>

  # prevent access to csv, txt and md files
  <FilesMatch "\.(csv|txt|md|yml|json|lock)$">
    Require all denied
  </FilesMatch>
</IfModule>

# Apache 2.2
<IfModule !authz_core_module>
  # secure htaccess file
  <Files .htaccess>
    Order allow,deny
    Deny from all
    Satisfy all
  </Files>

  # prevent access to PHP error log
  <Files error_log>
    Order allow,deny
    Deny from all
    Satisfy all
  </Files>

  # prevent access to LICENSE
  <Files LICENSE>
    Order allow,deny
    Deny from all
    Satisfy all
  </Files>

  # prevent access to csv, txt and md files
  <FilesMatch "\.(csv|txt|md|yml|json|lock)$">
    Order allow,deny
    Deny from all
    Satisfy all
  </FilesMatch>
</IfModule>


And here is my directory structure...

***@***.***:/var/www/html# ls -al
total 100
drwxr-xr-x  7 www-data www-data  4096 Jan  5 08:56 .
drwxr-xr-x  3 root     root      4096 Jan  5 08:55 ..
-rwxrwxr-x  1 www-data www-data  1414 Apr 22  2021 .htaccess
-rw-rw-r--  1 www-data www-data  1780 Apr 22  2021 Dockerfile
-rw-rw-r--  1 www-data www-data  5469 Apr 22  2021 INSTALL.md
-rw-rw-r--  1 www-data www-data  2805 Apr 22  2021 LICENSE
-rw-rw-r--  1 www-data www-data  9635 Apr 22  2021 README.md
-rw-rw-r--  1 www-data www-data  1335 Apr 22  2021 UPGRADE.txt
-rw-rw-r--  1 www-data www-data 11464 Apr 22  2021 WHATS_NEW.txt
drwxrwxr-x 16 www-data www-data  4096 Apr 22  2021 application
drwxrwxr-x  2 www-data www-data  4096 Apr 22  2021 database
drwxrwxr-x  3 www-data www-data  4096 Apr 22  2021 docker
-rw-rw-r--  1 www-data www-data   950 Apr 22  2021 docker-compose.dev.yml
-rw-rw-r--  1 www-data www-data  2871 Apr 22  2021 docker-compose.nginx.yml
-rw-rw-r--  1 www-data www-data   886 Apr 22  2021 docker-compose.test.yml
-rw-rw-r--  1 www-data www-data  1185 Apr 22  2021 docker-compose.yml
-rw-rw-r--  1 www-data www-data   272 Apr 22  2021 import_customers.csv
drwxrwxr-x 10 www-data www-data  4096 Jan  5 09:56 public
-rw-rw-r--  1 www-data www-data    25 Apr 22  2021 robots.txt
drwxr-xr-x 24 www-data www-data  4096 Apr 22  2021 vendor
***@***.***:/var/www/html# tree -d -L 2
.
|-- application
|   |-- cache
|   |-- config
|   |-- controllers
|   |-- core
|   |-- helpers
|   |-- hooks
|   |-- language
|   |-- libraries
|   |-- logs
|   |-- migrations
|   |-- models
|   |-- tests
|   |-- third_party
|   `-- views
|-- database
|-- docker
|   `-- data
|-- public
|   |-- bower_components
|   |-- css
|   |-- dist
|   |-- fonts
|   |-- images
|   |-- js
|   |-- license
|   `-- uploads
`-- vendor
    |-- bin
    |-- codeigniter
    |-- composer
    |-- doctrine
    |-- dompdf
    |-- kenjis
    |-- mikey179
    |-- myclabs
    |-- nikic
    |-- paragonie
    |-- phar-io
    |-- phenx
    |-- phpdocumentor
    |-- phpspec
    |-- phpunit
    |-- sabberworm
    |-- sebastian
    |-- symfony
    |-- tamtamchik
    |-- theseer
    |-- vlucas
    `-- webmozart

50 directories
***@***.***:/var/www/html#
