### ISSUE TITLE
Migrations csv working, but ID COUNT grew after many failed attemps. fixed with a clean session and db backup

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#3260]
### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 392d92. 
- PHP version is: 7.4
- MySQL or MariaDB version is: 10.3.30-MariaDB-cll-lve
- OS and version is: Linux 3.10.0-962.3.2.lve1.5.44.2.el7.x86_64
- WebServer is:  LiteSpeed
- Selected language is: spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

all its ok, just the id count grow up after a fails imports from a csv. Note. At no time i do not closed the session. maybe was that?

welp i migrated a part of a db, i edited the numbers fields with "," with no commas for import without issues, only the:

Barcode, Item Name, Category, Supplier ID, Cost Price, Unit Price, Reorder Level, location_stock, working fine,

but after a lot of attemps importing to watch and fix the csv for a good import, i saw the ID COUNT, like the image, I had to reinstall the database backup for fix the count importing again the csv file, is not bad, that work, just a id started from 1 from 1000+ its to much XD

after a lot of tries importing with fails, maybe the id count was counting?
![bk 2](https://user-images.githubusercontent.com/6296036/127756522-72cf356f-b00e-4ea5-828e-6bf30856bdf5.png)

after deleting the db and importing again the backup and importing again a clean csv, the id look good

![bk1](https://user-images.githubusercontent.com/6296036/127756547-f620873c-8932-414a-a623-587b1a1cef74.png)

**Comment by objecttothis** [comment]
This happens because the database uses autoincrement to assign the Id.  with my recent merge into the master, this should be fixed so that it doesn't happen anymore.  This is because now, if there is an error in the CSV import it won't import any of them, so it doesn't increment the Id number.
