### ISSUE TITLE
Add an ability to capture photo through CCTV onvif/RSTP and save it along with transaction history

### ISSUE THREAD

**Issue by 833M0L3** [opensourcepos/opensourcepos#3261]
Hello, I have a CCTV camera in my shop right in front of the counter and I want this POS software to take a photo of the customer while making a Sales Receipt or selling things. The photo should be saved along with the transaction history so that later we can check the person's identification. Will it be possible? Since, camera supports both onvif and RSTP. Can we somehow capture the image right at that moment?

**Comment by daN4cat** [comment]
This is a POS application for stock management, daily journal keeping and receipt / invoice issuing. It also has limited reporting facilities.

It's not a multimedia application.
You need to figure out a solution outside this application.

Also, taking snapshot of people is a serious privacy breach issue.
Laws like GDPR come into play and you need to abide by them even from an application perspective.
