### ISSUE TITLE
Code fixes for reports

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3262]
Just found a couple code fixes for the items report and the taxes report.  

In application\models\reports\Summary_items.php the reports_quantity is missing the `, 'sorter' => 'number_sorter'` like the reports_unit_price
`array('unit_price' => $this->lang->line('reports_unit_price'), 'sorter' => 'number_sorter'),`
`array('quantity' => $this->lang->line('reports_quantity')),`

In application/models/reports/Summary_taxes.php the reports_sales is missing the `, 'sorter' => 'number_sorter'` like the reports_tax_percent
`array('tax_percent' => $this->lang->line('reports_tax_percent'), 'sorter' => 'number_sorter'),`
`array('report_count' => $this->lang->line('reports_sales')),`

@jekkos Could this be added?  

Also, is there a way to contact you directly?  I tried your opensourcepos.org email but not sure if you check that.  

Thanks

**Comment by jekkos** [comment]
@chunter2 Thanks for these changes. My opensourcepos email should work.

**Comment by chunter2** [comment]
@jekkos Just tried emailing again, hopefully it's not a spam thing.

**Comment by jekkos** [comment]
In master now.
