### ISSUE TITLE
THERMAL PRINTER INTEGRATION, PRINTING IS PAPER TOO LONG WHEN PRINTING

### ISSUE THREAD

**Issue by NOTIOINNOVATION** [opensourcepos/opensourcepos#3267]
![printer result](https://user-images.githubusercontent.com/12730365/128466733-013041bf-266c-4681-ac9e-af747e46b3fc.png)
THERMAL PRINTER RESULT. NEED HELP

**Comment by daN4cat** [comment]
More settings and set the custom margins.

**Comment by daN4cat** [comment]
Nothing to do with OSPOS, it's a printer and printer driver issue.

**Comment by chunter2** [comment]
@NOTIOINNOVATION I noticed this too on my thermal printer but when I actually print it doesn't spit out all the extra empty space.  I did turn off the headers and footers under the "More settings" option in Chromes print dialog.
