### ISSUE TITLE
Local Timezone and OSPOS Timezone did not same

### ISSUE THREAD

**Issue by rizaljanuari** [opensourcepos/opensourcepos#3268]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4 - 392d92
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hello good people, i want to ask if theres a problem and whats wrong with Local Timezone and OSPOS Timezone is not the same. i also post the screenshot and sorry if my english bad
![image](https://user-images.githubusercontent.com/20695677/128641387-630c04fc-7666-4ce1-904c-db6d7cd358fc.png)

**Comment by odiea** [comment]
What time does the clock show in the upper left hand corner. Is it your local time?

**Comment by rizaljanuari** [comment]
Yes is it, i confuse because the Timezone i set is same GMT+07:00 Bangkok, Hanoi, Jakarta. But why ospos only choose the Bangkok one and it can be different timezone

**Comment by odiea** [comment]
I guess it just uses the default GMT location.

**Comment by rizaljanuari** [comment]
So it cant be an issue right? Because actually i also get issue with importing items with csv. It said succesfully imported but it didnt show in items list also in the database. I read a threads about that and it said its because my Timezone is not correct. So here i am asking this question

**Comment by ekardian** [comment]
> So it cant be an issue right? Because actually i also get issue with importing items with csv. It said succesfully imported but it didnt show in items list also in the database. I read a threads about that and it said its because my Timezone is not correct. So here i am asking this question

nop, worked for me, in my case not working in the begining, after i saw a lot of mistakes for my bad config, like, currencies for example, i was importing with dots and commas, when i changed to other currencies, other for example, the suppliers, i had to put his ID0s and not his names, example id:2 = my supplier, i wrote 2 and not "my supplier" in the csv, i sed libreoofice and geany to watch if a bad character going wrong, one of the devs i dont remember is was @objecttothis in the master u can now update items and fixed a few things about the import, soon a wiki

**Comment by objecttothis** [comment]
> 
> 
> > So it cant be an issue right? Because actually i also get issue with importing items with csv. It said succesfully imported but it didnt show in items list also in the database. I read a threads about that and it said its because my Timezone is not correct. So here i am asking this question
> 
> nop, worked for me, in my case not working in the begining, after i saw a lot of mistakes for my bad config, like, currencies for example, i was importing with dots and commas, when i changed to other currencies, other for example, the suppliers, i had to put his ID0s and not his names, example id:2 = my supplier, i wrote 2 and not "my supplier" in the csv, i used libreoffice and geany to watch if a bad character going wrong, one of the devs i dont remember if was @objecttothis in the master u can now update items and fixed a few things about the import, soon a wiki

I suppose it's possible for the timezone difference to cause problems with the import, but I wouldn't think it would be likely because the import is running realtime rather than queuing the import to do more slowly.  As @ekardian put it, the import failing to add fields usually is caused by incorrectly formatted data in the CSV file.  Excel is often used to generate CSV files, but unless done properly, it can really mess the files up.  This is especially true with files that contain UTF-8 characters.  

The master does now have the ability to update existing items.  Please remember that the master is not a release build.  If you find any problems, please report them.  I did update the wiki with information about how to do the update.  At some point someone should put a CSV troubleshooting guide in the wiki as there are many common mistakes.  I will say that you should turn on error logging and check the log after running an import to see if there were errors generated and exactly what the problem is.

**Comment by rizaljanuari** [comment]
Whoaa, thank you. So much information i have from this thread. i think i suppose to try it all first, and noted the difference timezone above can't be an issue for my problem with importing item. i think i'll close this issue. thanks a lot!
