### ISSUE TITLE
about point rewards, should the last sale count as points? if the customer bought with his points

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#3272]
a customer won 10 points in sales, but in the last sale count as points? too? if he bought with his points

10 points i have - 10 points i gonna spent $$$ = 0 point .... i start again after i spent my points

but it doesn't matters

i was with gift cards if the customers buy 108$ in products for give him 12$, no problem here, just a little of work for search in the reports for watch if the customer have 108$ in consumption

just for illustrate the point he won after he paid with his last 10 points, for me no problem, just i tought that if he paid with his points, should not count
![imagen](https://user-images.githubusercontent.com/6296036/128953861-a284b261-1de9-4410-b949-94b294327c06.png)

**Comment by odiea** [comment]
This was the way the original developer designed it. If you would like to change the way it works feel free to.

**Comment by ekardian** [comment]
that is the way say a mandalorian guy 
![imagen](https://user-images.githubusercontent.com/6296036/130709489-bc9df07d-cc1d-409f-8224-6999494f6b5b.png)
![imagen](https://user-images.githubusercontent.com/6296036/130709556-d3d3913e-6fae-4a78-a779-0ed94a40f504.png)
