### ISSUE TITLE
can we upgrade this application to latest CodeIgniter 4.1

### ISSUE THREAD

**Issue by bhojkamal** [opensourcepos/opensourcepos#3273]
Hello, 

Can we upgrade this application to the latest version of CodeIgniter - 4.1.3, bootstrap 5, and latest jQuery?

**Comment by daN4cat** [comment]
And the question is: why?

**Comment by ekardian** [comment]
![imagen](https://user-images.githubusercontent.com/6296036/129143241-ff1f175c-fb5a-4ad0-b3e7-5cd6fe6152c9.png)

**Comment by ekardian** [comment]
> 
> 
> And the question is: why?

dude, github have more fun than fb XD

**Comment by objecttothis** [comment]
This is a duplicate of #842
