### ISSUE TITLE
How to import images in csv

### ISSUE THREAD

**Issue by moletelier** [opensourcepos/opensourcepos#3280]
### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 080e8a
- PHP version is: 7.3.29
- MySQL or MariaDB version is: 10.3.24-MariaDB
- OS and version is: Apache 2.4.46
- WebServer is: linux
- Selected language is: es_CL
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi, I would like to know if its possible to import items with an image while importing products because there's a column named "item_image". I know in csv that is no possible but maybe a weblink to an image of something like that is possible??

Thanks,

Manuel

**Comment by ekardian** [comment]
the devs need a rest, im a simple tester and lang things to spanish, but its free, u can try to insert the path images to the database with phpmyadmin with a sentence and uploads the images to your upload directory, i dont know how, but you can DO IT XD
items Table, pic_filename field
all my life was in this way, if i cant write code, i made my own way, its hard, but

![imagen](https://user-images.githubusercontent.com/6296036/130704839-91dddf72-157a-43c3-b1c1-a7d61bcebbd0.png)
