### ISSUE TITLE
Categories No Longer Working For Items (drop-down shows 'None', new Categories cannot be added)

### ISSUE THREAD

**Issue by pleatus** [opensourcepos/opensourcepos#3282]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation (minimal css changes to main page)
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.3.4 - 392d92
- OSPOS git commit hash is: 
- PHP version is: 7.3
- MySQL or MariaDB version is: 10.3.29-MariaDB
- OS and version is: Linux
- WebServer is: 
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hi I've deployed a clean installation of OSPOS to test. After putting in some test products (items) and fooling around with the system I am no longer able to change an items category, or create a new category in the add new/edit item modal.
The category displayed by the Modal category drop-down is "None".
The categories are still being displayed in the items table, and they still exist as entries in the items table inside pypmyadmin.
I'm fairly new to OSPOS so this could be something I've changed by mistake.
Categories were originally Test, Test2, and Test3. I changed them to Subscription, Service, and Product to see if using the word 'Test' was the issue.
I'm willing to provide any info necessary to diagnose this issue. Sorry for being vague, but like I said I'm new to OSPOS and not familiar with it's nuances yet. 
Any help would be appreciated. Thank you!

![items-page](https://user-images.githubusercontent.com/43357839/130662310-3e4bfffc-c31d-488f-be33-87acf0b085d7.jpg)
![edit-item-modal](https://user-images.githubusercontent.com/43357839/130662374-967ef89d-3f28-4742-94e9-5f0147a813ca.jpg)
![new-item-modal](https://user-images.githubusercontent.com/43357839/130662466-31f92fff-cfdb-418b-a8a3-27b8c28c97a8.png)
![ospos-items-phpmyadmin](https://user-images.githubusercontent.com/43357839/130662476-620c917f-8119-472d-816c-a08cf41d5d12.jpg)

**Comment by odiea** [comment]
In general config if you enabled use Category as a drop down then you will need to place Categories in the Categories Attributes. Otherwise uncheck it.

**Comment by pleatus** [comment]
Yes this did the trick. Thank you!
For future reference, would you be able to tell me where to find the Categories Attributes within the system?

**Comment by odiea** [comment]
I think that you should be able to enable it in Employees permissions. Then it should show in the Menu icons at the top

**Comment by pleatus** [comment]
Thanks again! Not sure I see it yet, but I'm sure I'll figure it out.

**Comment by odiea** [comment]
![2021-08-24 12_20_54-Window](https://user-images.githubusercontent.com/10962177/130669441-0b36e89e-5820-4b48-b1ec-1b6a7fe41eb2.png)

**Comment by odiea** [comment]
I was mistaken about needing the permissions. It is just under Attributes.

**Comment by pleatus** [comment]
This is great, thank! I was wondering about this as I have used some attributes for items already.
I don't see how I could use them as Categories however. I have a few different types of attributes added, as well as 3 attributes in a group.
Is there a special data-type that should be selected for the attribute so it's recognized as a category (for drop-down selection) or am I understanding this wrong?

**Comment by odiea** [comment]
Just like other Attributes. Click on the edit button to the right of ospos-category from there you can start adding your Categories

**Comment by odiea** [comment]
Just play around with it to see if it meets your needs.
