### ISSUE TITLE
Captcha security hole

### ISSUE THREAD

**Issue by fernadie** [opensourcepos/opensourcepos#3283]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: MySQL 5.7
- OS and version is: Ubuntu 20.04.3
- WebServer is: Apache 2.4
- Selected language is: Spanish
- (If applicable) Docker installation: -
- (If applicable) Installation package for the LAMP/LEMP stack is: -

### Issue / Bug  / Question / New Feature

After getting the expected error when trying to login without verifying captcha, if the button is pressed again immediately without filling in user/pass or verifying captcha it logs in with the previously entered credentials.

![image](https://user-images.githubusercontent.com/46056174/130888068-8a461cf3-2119-4097-b3ce-798f1c29feae.png)

**Comment by jekkos** [comment]
@daN4cat is this something you could have a look at?

**Comment by daN4cat** [comment]
I hardly have time at the moment. Sorry....

**Comment by ekardian** [comment]
same to me, but i am waiting to the 4.0 to post this issue too, dude a think can wait this issue, take your time and enjoy ospos, i have people dying with covid to close to me, so, patience, btw be strong devs

**Comment by jekkos** [comment]
Duplicate issue, can be closed
