### ISSUE TITLE
how to fix Automatic logout after 1 to 2 minutes ospos

### ISSUE THREAD

**Issue by mrtechhive** [opensourcepos/opensourcepos#3285]
Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: LiteSpeed
.PHP Version: 7.4.22
.DB Version: 5.7.35
.Server Port: 443
.OS: Linux 3.10.0-962.3.2.lve1.5.38.el7.x86_64

File Permissions:
» [application/logs:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads/item_pics:] - 0750 | Writable ✓ | Security Check Passed ✓
» [import_customers.csv:] - 0660 | Readable ✓ | Security Check Passed ✓

No security/vulnerability risks.

Asia/Dhaka

**Comment by sislinigeria** [comment]
Good day All,
I have OSPOS installed for 5 businesses, and all of them are having the same issue of automatic logout after 1 to 30 seconds.

**My Observation:**
1. This happens whenever they are using MTN Mobile Network Company (https://www.mtn.ng/) this is the most popular and used Internet provider in my country. The company has the most coverage area making them the preferred provider for individuals and businesses.

2. I suspect the MTN network provider uses dynamic IP, therefore anytime the Network IP changes, the OSPOS software logs out. And this happens in seconds.

**My Request:**
I believe there is something that can be done from the Software angle to stop the software from logging out anytime a network IP changes. You can effect this on subsequent updates and also list out a step-by-step process to resolve this for my clients who are currently facing this challenge.

I hope to hear from someone soon.

Sixtus Nnamdi
Email: sixtus.nnamdi@gmail.com

**Comment by tedyswaga** [comment]
$config['sess_match_ip'] = TRUE; change to $config['sess_match_ip'] = FALSE; 

The file is config.php
