### ISSUE TITLE
How to disable this?? 

### ISSUE THREAD

**Issue by Chris-ch41** [opensourcepos/opensourcepos#3290]
1. ![PhotoGrid_Plus_1630469214015](https://user-images.githubusercontent.com/85863043/131611209-eb4d5f1d-dac3-40f6-ac23-c34c8cd2e5fc.jpg)

2. Can i adjust line-height more closer?

**Comment by jekkos** [comment]
Just remove the image in the receipt.php file?

**Comment by Chris-ch41** [comment]
![Screenshot from 2021-09-01 15-46-36](https://user-images.githubusercontent.com/85863043/131642130-b96a008c-9c4d-4328-bc59-9760664c921c.png)

Remove code or what.?
If i remove this code, nothing happen..

**Comment by jekkos** [comment]
Can you check default_receipt.php ?

**Comment by Chris-ch41** [comment]
Thanks, if delete code in file receipt_short.Php

**Comment by Chris-ch41** [comment]
![PhotoGrid_Plus_1630483327197](https://user-images.githubusercontent.com/85863043/131656716-1276f514-9782-4ee5-bcb5-10933a2ef839.jpg)

Next question..
 How adjust more closer line_height?

**Comment by WebShells** [comment]
@Chris-ch41 if you adjust it for smaller padding it will affect displaying the discounts and discount values also. It's doable through setting the padding value in css files from 3 px to
 
#receipt_items td {
    padding: 0px;
}

Closing this
