### ISSUE TITLE
New product popup does not close when hitting enter

### ISSUE THREAD

**Issue by blutme** [opensourcepos/opensourcepos#3291]
### Installation information

- OSPOS version is: 3.3.5
- OSPOS git commit hash is: 
- PHP version is: 7.3
- MySQL or MariaDB version is: MariaDB
- OS and version is: Windows
- WebServer is: apache
- Selected language is: english 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

When I enter a new product, I enter UPC code, product name, category, purchase and sale price. If I press the enter key, the product is entered into the database (because the green pop-up message appears behind it) but the new product pop-up window does not close. On the other hand, if I register a new user and fill the fields and press the enter key, the customer's pop-up sale disappears and the green pop-up message appears. I believe that some users thought that the register was not made on new product pop-up window, since the pop-up window does not close automatically and can make you believe that the product has not yet been entered and can generate an error when trying to enter the product twice because like as if it were the same UPC.

Thanks for read and fix it.

**Comment by jekkos** [comment]
I think this works as designed, if you hit enter then the form will clear and allow you to add a new item after the one you have just added. You can change this yourself if you want by changing the action on return in this case.

**Comment by jekkos** [comment]
The item form behavior on enter is a bit different then the behavior for the customer form..
