### ISSUE TITLE
Very Slow in opening Item Module

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#3292]
When other people here talking about more development for OSPOS new version.... But My Problem is still a PROBLEM.. a serious problem...
![loading_slow](https://user-images.githubusercontent.com/32444665/131815356-140d7380-f41e-4d17-9a48-6881c15f5969.jpg)

It took me 5 minutes to open item modules...my suspect is due to a very large db which cause everyday transaction from 2017 up to present....

**Comment by jekkos** [comment]
Issue is fixed now?
