### ISSUE TITLE
After upgraded from 3.3.4 to 3.3.5 the item is not added but I can see it in the database

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#3295]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.5
- OSPOS git commit hash is: b4c48e5
- PHP version is: 7.4.22
- MySQL or MariaDB version is: 10.3.31-MariaDB-cll-lve
- OS and version is: Linux 3.10.0-962.3.2.lve1.5.44.2.el7.x86_64
- WebServer is: LiteSpeed
- Selected language is: Spanish
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

i upgraded from 3.3.4 and here we go.

i have a few errors

adding item

error 1.
if i do not delete the tax, i have this error, but is introduced to the database, and the item is not listed

![Screenshot_2021-09-03 Punto de Venta Open Source OSPOS Potenciado por OSPOS 3 3 5](https://user-images.githubusercontent.com/6296036/132076712-919f8846-c011-4e53-8428-39500dd4ea80.png)

and in the database its introduced

![Screenshot_2021-09-03 biosxtreme net localhost biosxtre_demopos ospos_items phpMyAdmin 4 9 7](https://user-images.githubusercontent.com/6296036/132076768-465547ad-9b84-436c-bcd1-dc9581005ec6.png)

error 2
if i delete the tax i have this error, but is introduced to the database, and the item is not listed too

![Screenshot_2021-09-03 Punto de Venta Open Source OSPOS Potenciado por OSPOS 3 3 5(1)](https://user-images.githubusercontent.com/6296036/132076837-cfef9ac0-a2a1-46a4-9173-dc455d20646a.png)

but in the database appear the item

![Screenshot_2021-09-03 biosxtreme net localhost biosxtre_demopos ospos_items phpMyAdmin 4 9 7(1)](https://user-images.githubusercontent.com/6296036/132076899-80cc5fd6-f2a5-4a27-b5eb-f490b7597ad7.png)

Now even deleting all taxes from config i have the same issue.

i love backup all so no problem, i am working in the v.3.3.4 again

**Comment by odiea** [comment]
You will need to enable error reporting so we can see what is going on

**Comment by odiea** [comment]
The issue has been located and a fix may be in the process. If you don't want to redownload the version again and can change the code we will let you know how.

**Comment by daN4cat** [comment]
Release 3.3.6?

**Comment by jekkos** [comment]
I'm off as announced so was hoping someone could pick this up. As discussed with @odiea the fix for this sqli vulnerability is the culprit. Reverting it will fix this issue but then will reintroduce the vuln.

It's probably best to enumerate the entity colums and check whether the sort column is in this list as a sanitization step.

**Comment by jekkos** [comment]
b4c48e5141fd04857def6cd141f96d27a5986a45

**Comment by jekkos** [comment]
Fix in master

**Comment by ekardian** [comment]
sorry guys, i was with family health problems, next week i gonna try again the new releases
