### ISSUE TITLE
Email Sending Problem on Receipt

### ISSUE THREAD

**Issue by mrtechhive** [opensourcepos/opensourcepos#3296]
General Info

User Setup

Permissions

OSPOS Installation Info: Version : 3.3.5
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: LiteSpeed
.PHP Version: 7.4.22
.DB Version: 5.7.35
.Server Port: 443
.OS: Linux 3.10.0-962.3.2.lve1.5.38.el7.x86_64

File Permissions:
» [application/logs:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads/item_pics:] - 0750 | Writable ✓ | Security Check Passed ✓
» [import_customers.csv:] - 0660 | Readable ✓ | Security Check Passed ✓

No security/vulnerability risks.

Asia/Dhaka
![Capture](https://user-images.githubusercontent.com/89564170/132086266-55f268d9-5f35-44c4-802b-6a0758b1648b.PNG)

**Comment by mrtechhive** [comment]
![Capture](https://user-images.githubusercontent.com/89564170/132086222-6eae667a-f1a8-44ec-892d-71cf1b771c10.PNG)

**Comment by odiea** [comment]
I believe you will need to edit both the sendmail.ini and php.ini to get it to send mail
