### ISSUE TITLE
Suppressing Credit Card and Debit Card

### ISSUE THREAD

**Issue by philippejd** [opensourcepos/opensourcepos#3297]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.5 
- OSPOS git commit hash is: fe7276
- PHP version is: 7.3.29
- MySQL or MariaDB version is: 15.1
- OS and version is: Raspbian GNU/Linux 10 (buster)
- WebServer is:   nginx/1.14.2
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I know I am going to get crucified over asking this but I have crawled through every issue request I can get my hands on but I cannot seem to find anything that explains how to suppress some payment options. I can get around code if I am shown what to remove or change but I'm not adventuristic enough to do it on my own out of fear I break something.  After hours of trying to get the PI instructions to work because they are so out of date I feel lucky to at least have a working copy using the instructions for PI 3 because the Orange instructions did not work at all as there is no longer a PHP 5 that would download. But here I am and its working as of now. Any help in suppressing Credit and Debit Cards would be great. The only issue I could find remotely close was this one: 

[https://github.com/opensourcepos/opensourcepos/issues/2898#issue-662659859](url)

However that one does not seem to address the issue in its entirety. Also it referenced another issue as the last reply and I could not find that original thread.

**Comment by jekkos** [comment]
Hi, good to read you took the time to go through the issue tracker. Its not something a lot of people do.

I think you should be able to remove the payment type in the dropdown in the register page. My guess is that they are loaded from an array in the sales controller.
If you change a file and are afraid to break things then just make a copy of it before you change it so you can restore it if something breaks.

**Comment by philippejd** [comment]
@jekkos,

I think I may have found the line I need to edit. I could not find the array to edit in the modles\Sales.php but in the Controllers\Sales.php I found an interesting note, however I am not sure how to edit this to indicate each payment type. Am I on the right track or is this off base? Thanks again.

[https://github.com/opensourcepos/opensourcepos/blob/a2e7c0a74bbdaed6a33fd80549d6e6117a32ecb3/application/controllers/Sales.php#L1213-L1216](url)

**Comment by odiea** [comment]
Look in application/helpers/locale_helper.php
