### ISSUE TITLE
OSPOS website: Contact Us is broken, has "ERROR for site owner: Invalid domain for site key" in recaptcha

### ISSUE THREAD

**Issue by bernd-wechner** [opensourcepos/opensourcepos#3299]
Subject says it all. Can't contact OSPOS at present because the form:

https://opensourcepos.org/contact-us/

is broken, the Contact Us button is disabled and the reCaptcha reports "ERROR for site owner: Invalid domain for site key".

**Comment by jekkos** [comment]
currently the website is not really maintained, I think it might be better to go for a static markdown version as @BudsieBuds also suggested.

**Comment by BudsieBuds** [comment]
Yeah, I'm working on some different things and have been experimenting with a static website. I'll discuss it with @jekkos when it's usable.

**Comment by bernd-wechner** [comment]
Drop Wordpress. I wouldn't touch that with a bargepole ;-). Ha, ha.
