### ISSUE TITLE
Backup failing from config page

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3301]
### Installation information

- OSPOS version is: 3.3.2

### Issue / Bug  / Question / New Feature

I'm getting an http 500 error when trying to do a backup from the config page.  I see the following errors in the /var/log/apache2/error.log

`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 35651616 bytes) in /var/www/html/ospos/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_utility.php on line 196`
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 63885968 bytes) in /var/www/html/ospos/vendor/codeigniter/framework/system/libraries/Zip.php on line 269`

It looks like I can maybe add a ini_set(“memory_limit”,”16M“); call (16M is just an example) to the top of those php files but I'm wondering if there's a proper solution for this.  This has been working fine but my guess is my database has grown past the memory limit.  

Thanks

**Comment by WebShells** [comment]
Hello @chunter2 this goes back for memory limit server side since your db grew bigger than the allowed allocated memory size. go to php.ini and try editing maximum memory limit from memory_limit = 128M to memory_limit = 256M or even more depending on how much memory your script needs to execute. 
Dont forget to return it back to the smallest size needed after you are done. 
Will close

**Comment by chunter2** [comment]
@WebShells Thanks for the tip.  It worked perfectly.  
Does this make sense to have to do this or should the database backup from the GUI be done a different way?  Or maybe there should be a note about this by the button.  

Thanks

**Comment by jekkos** [comment]
@chunter2 maybe we can raise this limit a bit in .htaccess.. ofcourse it depends on how large your database is.

**Comment by WebShells** [comment]
@chunter2 if you want to reach the same result editing .htaccess it can be done by adding the following line and replacing the XXX with the limit you'd like to set it to: php_value memory_limit xxxM.

**Comment by chunter2** [comment]
@jekkos @WebShells Would this be the ospos/public/.htaccess file?  I'm assuming this can't be done dynamically?  My database backup is growing at about 500k a month.  Also, there's no reason I need to do the backup from the GUI.  It's more that the button was there so I started using it.  :)  I figured an http 500 error wasn't good for the end user to see.
