### ISSUE TITLE
Same Item ID and UPC

### ISSUE THREAD

**Issue by blutme** [opensourcepos/opensourcepos#3305]
### Installation information

- OSPOS version is: 3.3.5
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: Mariadb
- OS and version is: Windows
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: XAMP

### Issue / Bug  / Question / New Feature

Hello Friends,

I have some UPC like 1020, 1140, 1820... Then when I search these on sales module, the suggest search always take the ítem ID number ( internal ID) because I have more of 2000 ítems. But not the UPC. 

How can modify the code programing or do for not suggest search the ítem ID.  Or should I put other longer codes?

Thanks for your help.

**Comment by WebShells** [comment]
@blutme in your case to resolve the conflict you can add leading zero to the item_number column in ospos_items table. This will definitely makes the printed barcodes unreadable, so you should configure your scanner to ignore barcode prefix for it to work again without any issues.
That's the easiest solution without messing around with the code.
Will close
