### ISSUE TITLE
Imprimir 58mm thermal printer

### ISSUE THREAD

**Issue by molomixx** [opensourcepos/opensourcepos#3309]
Buenas noches, podrían apóyarme como imprimir a 58mm thermal
 printer, ya que sale muy chico la letra y se desborda impresión...

**Comment by WebShells** [comment]
@molomixx try selecting short receipts template from configuration section this will help in decreasing the columns by 1 column, somehow it might fit on 58mm printer.

**Comment by molomixx** [comment]
En configuración se hizo igualmente se desborda.
