### ISSUE TITLE
Error on completing an un-suspended sale

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3314]
### Installation information

- OSPOS version is: 3.3.2

### Issue / Bug  / Question / New Feature

I've just noticed that I can't seem to complete an un-suspended sale.  A regular sale works fine.  When I hit the complete button I get a blank screen (white) in the browser.  I enabled debug logging and see the following errors when the complete button is pressed.  

```
ERROR` - 2021-09-24 08:35:07 --> Query error: Cannot delete or update a parent row: a foreign key constraint fails (`ospos`.`ospos_sales_items_taxes`, CONSTRAINT `ospos_sales_items_taxes_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `ospos_sales_items` (`item_id`)) - Invalid query: DELETE FROM `ospos_sales_items`

WHERE `sale_id` = '14257'
DEBUG - 2021-09-24 08:35:07 --> DB Transaction Failure
ERROR - 2021-09-24 08:35:07 --> Query error: Duplicate entry '14257-271-1' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales_items` (`sale_id`, `item_id`, `line`, `description`, `serialnumber`, `quantity_purchased`, `discount`, `discount_type`, `item_cost_price`, `item_unit_price`, `item_location`, `print_option`) VALUES ('14257', '271', 1, '', '', '1.000', '0.00', '0', '5.99', '4.49', '1', '0')
DEBUG - 2021-09-24 08:35:07 --> DB Transaction Failure
```

I can't seem to reproduce this on the demo and dev site so my guess is it's fixed in the latest release or I've broken something in my install.  I haven't had the time to upgrade yet but was just looking for some clarification on what's going on.  Any ideas?  

Thanks

**Comment by jekkos** [comment]
How did you try to reproduce this? Create a suspended sale, then finish another one and resume and complete the first?

**Comment by chunter2** [comment]
@jekkos I just tried creating a suspended sale and then brought it back up by un-suspending it and trying to complete it.  I've had reports of cashiers trying to use the suspend feature but it failing.  They were trying the method you suggested, completing another sale in between.

**Comment by chunter2** [comment]
@jekkos In looking at the database a bit it looks like the 14257 sale_id now has a sale_status of 2.  It doesn't show up in the daily sales report so I'm guessing a 2 means deleted?  I don't think I fully understand what the suspend feature does but I'm not quite sure why 
```
DELETE FROM `ospos_sales_items` WHERE `sale_id` = '14257'
```
is needed.  Is it trying to delete everything in the sales register before bringing back up the suspended sale?  

Thanks

**Comment by jekkos** [comment]
So it fails in case you add another sale in the mean time?
This is what the error seems to indicate.

**Comment by chunter2** [comment]
@jekkos I haven't tested the "sale in the mean time" method myself yet but indications are that both cases fail.  I'll test that method after end-of-day today.

**Comment by jekkos** [comment]
If i remember well then unsuspending a sale was a matter of changing the sale type value, so no new insert should be needed.

Your installation is a 3.3.2? I guess it's probably also present in 3.3.5 then.

**Comment by odiea** [comment]
@jekkos I have not had any issues with this.

**Comment by chunter2** [comment]
@jekkos I haven't been able to reproduce the issue on 3.3.5 on the demo and dev servers just like @odiea can't.  I tried the "sale in the mean time" method and it failed as well on my 3.3.2 version.  I know I need to upgrade but just haven't had the time.  I'm more interested in how the suspend works.  Not sure why it's trying to delete the entry instead of just changing the sale type back to "active" or something.  Is there a way to find out why there's a delete?

**Comment by jekkos** [comment]
I guess you'll need to peek in the code to understand why this happens then. Upgrading might be a bit of a burden..

**Comment by chunter2** [comment]
@jekkos @odiea I've been poking around in the code but can't seem to find a starting point.  Would either you be able to help me find where the 
```
DELETE FROM `ospos_sales_items` WHERE `sale_id` = '14257'
```
is called?  

Thanks

**Comment by odiea** [comment]
In models/Sale around line 1380.  public function clear_suspended_sale_detail($sale_id)

**Comment by odiea** [comment]
I am not a DB guy so my suggestion would be to create a test environment and try your backup db before you made the changes and see if the issue is still there.

**Comment by chunter2** [comment]
Would @objecttothis have any ideas on this?  Sounds like you're the database guy here.  

Thanks

**Comment by objecttothis** [comment]
> Would @objecttothis have any ideas on this? Sounds like you're the database guy here.
> 
> Thanks

Hehe. I'm learning as I go along too. @jekkos and @daN4cat  likely have a leg up on me in terms of database.  That said, I recommend setting up a fresh database and changing your db config to point to that database. Setup some dummy data and try to recreate on the same codebase that you currently experience the issues with. If the problem goes away then it isn't likely the code.

If you're running 3.3.2 you may want to update to the latest release build. If a fresh database fixes the issue and you did make changes in constraints, you should look at those first.

**Comment by objecttothis** [comment]
Also, enable the db log in config as well as the highest level of logs. Look for errors in both logs. Also try adding ?debug=true to the end of the url when recreating the issue.

**Comment by chunter2** [comment]
So I enabled db logging in the config but that didn't seem to show me any errors, just the database calls.  I tried removing the constraint that was causing the error and now the suspend is working properly.  All I can figure is when I removed and re-added the constraint a while ago with phpmyadmin it must not have added it back the same way as it gets added on the database creation.  I'm guessing it's not a good idea not to have the constraint but I'm not quite sure how to re-add it properly.

**Comment by objecttothis** [comment]
I'd go back to the migration script or db creation script where it is last modified or created and run that line to create it.

**Comment by chunter2** [comment]
Removing the constraints from phpmyadmin and then running this command
```
ALTER TABLE `ospos_sales_items_taxes`
  ADD CONSTRAINT `ospos_sales_items_taxes_ibfk_1` FOREIGN KEY (`sale_id`) REFERENCES `ospos_sales_items` (`sale_id`),
  ADD CONSTRAINT `ospos_sales_items_taxes_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `ospos_items` (`item_id`);
```
fixed things for me.  I'm still not sure what the GUI does differently but at least it's working now.  

Thanks for the help.
