### ISSUE TITLE
print using android no price.. if portrait product price = blank... if landscape= normal ok

### ISSUE THREAD

**Issue by hendysama** [opensourcepos/opensourcepos#3315]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 
- PHP version is: 7.3
- MySQL or MariaDB version is:  5.7.34
- OS and version is: ubuntu server 20.04
- WebServer is:  apache 2.4.46
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue 
Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

issue = if i print using android browser (chrome, firefox, soul) portrait position the price is blank.. if landscape all is OK ... temporary solution i always print landscape position.. but i got tired... i change paper size from a4, letter, 58mm POS , save as pdf  always blank if portait.. using PC /laptop is Ok
![Screenshot_2021-09-25-17-38-14](https://user-images.githubusercontent.com/27440454/134768993-8f42fa2c-dd14-494c-83a9-a52f1c1c21e4.png)
\
![Screenshot_2021-09-25-17-38-25](https://user-images.githubusercontent.com/27440454/134769012-9e6551d5-ba0f-4276-b707-c5b6f76c9882.png)
![Screenshot_2021-09-25-17-36-55](https://user-images.githubusercontent.com/27440454/134769029-3c2788b4-c874-4115-9ac2-b0b839fcb92f.png)

**Comment by Chris-ch41** [comment]
Om,  orang indonesia ya..  Gw pakai thermL 80 ok om
![Uploading PhotoGrid_Plus_1630469214015.jpg…]()

**Comment by Chris-ch41** [comment]
Coba cek ini om,
https://youtu.be/aRonqHxl_Ug

**Comment by majenun123** [comment]
sama bro coba font dikecilkan mgkn kertas 58 cukup bro
