### ISSUE TITLE
Items CSV Import - Supplier ID doesn't get saved

### ISSUE THREAD

**Issue by jevinsonlim** [opensourcepos/opensourcepos#3320]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.3.5
- OSPOS git commit hash is: b4c48e5141fd04857def6cd141f96d27a5986a45
- PHP version is: PHP 7.3.27
- MySQL or MariaDB version is: 10.4.18-MariaDB
- OS and version is: Windows 10
- WebServer is: XAMPP
- Selected language is: English United States
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

When importing Items with CSV Import, supplier/company name (based from Supplier ID provided) won't get recorded.

**Comment by nathanzky** [comment]
please check as well the items quantity after import. it is reflecting zero..

**Comment by jekkos** [comment]
@objecttothis any chance to validate this one?

**Comment by objecttothis** [comment]
> 
> 
> @objecttothis any chance to validate this one?

Yes, I'll take a look at it.  Likely it will be tomorrow when I'm working on OSPOS stuff.  

@nathanzky can you give me more details?  If you're willing, please upload an example of your csv import that is showing 0 quantity after the import. Also please enable the error logs and send the lines that are recorded during the import.  Finally, please confirm which OSPOS commit you are running and which version.  I'll need these things to narrow down what is causing the issue and replicate it.

**Comment by objecttothis** [comment]
@jevinsonlim nevermind, I see you submitted a fix for the issue already.

**Comment by daN4cat** [comment]
@objecttothis I believe the issue is what @nathanzky is talking about.

**Comment by objecttothis** [comment]
@daN4cat They are two separate issues.  @jevinsonlim reported supplier not saving and he submitted a fix for it already.  @nathanzky reported quantity being zero after import, but I need to see the information I requested from him first.  I don't think I modified the part of the code that imports/saves the quantities in this go-round, so I need to see that he isn't using an old template.  The quantities used to be imported differently than they are now, so if he's not using the auto-generated template, then that is likely the cause.

**Comment by objecttothis** [comment]
@nathanzky OK, that's the problem.  You're using an outdated template for your CSV.  This is because the code in 3.3.5 is looking for your location header as [location_name]_location.  So in your case it would be location1_location.  Since that doesn't exist in your header, it doesn't correctly import the quantity.  You will need to use the autogenerated CSV.  What about it isn't working?

**Comment by objecttothis** [comment]
This is what I see when I open that CSV file:
![image](https://user-images.githubusercontent.com/17935339/136852172-70be779f-f25a-4191-a859-7af8e42d5c5b.png)

It's missing quite a few headers in the autogenerated file.  If you go to dev.opensourcepos.org and login with the default username/password, then you will be able to click on Items > CSV Import > Download Import CSV Template (CSV) and you will see what it should look like.

Did you modify the headers after downloading it?  Are you working on an unmodified install of OSPOS?

**Comment by nathanzky** [comment]
@objecttothis thanks a lot the Download Import CSV Template (CSV) works fine, the old template works as well just modified the header name for stock location.

**Comment by objecttothis** [comment]
Super.  Glad it works.  I don't recommend using the old template.
