### ISSUE TITLE
Security: Wrong operator usage in password equals

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#3324]
@objecttothis this might be one [up your alley](https://github.com/opensourcepos/opensourcepos/blob/2f69841c95869c26d4413186dd0078e3a98dc461/application/models/Employee.php#L335). I did not know about this but a quick look on [stackoverflow](https://security.stackexchange.com/questions/238043/magic-hash-attack-in-javascript) confirms the report.

![Screenshot from 2021-09-30 21-35-59](https://user-images.githubusercontent.com/576234/135519561-69626dfc-1b75-4558-8f69-6fd3a98384eb.png)

**Comment by objecttothis** [comment]
Not surprising... but that's likely because all the other languages I use are strict typed.  I do like the flexibility that PHP offers, but this is a way that it can even cause a security vulnerability.

**Comment by objecttothis** [comment]
This should be an easy fix.  Employees.hash_version is a tinyint in the db and the password is a varchar which means the code could be changed to:
```
public function login($username, $password)
	{
		$query = $this->db->get_where('employees', array('username' => $username, 'deleted' => 0), 1);

		if($query->num_rows() === 1)
		{
			$row = $query->row();

			// compare passwords depending on the hash version
			if($row->hash_version === 1 && $row->password === md5($password))
			{
				$this->db->where('person_id', $row->person_id);
				$this->session->set_userdata('person_id', $row->person_id);
				$password_hash = password_hash($password, PASSWORD_DEFAULT);

				return $this->db->update('employees', array('hash_version' => 2, 'password' => $password_hash));
			}
			elseif($row->hash_version === 2 && password_verify($password, $row->password))
			{
				$this->session->set_userdata('person_id', $row->person_id);

				return TRUE;
			}

		}

		return FALSE;
	}
```
I would make the change but I'm going out of time and I don't have time to test the change.

**Comment by jekkos** [comment]
This one only affects users using the old MD5 scheme, which was deprecated a couple of years ago..

**Comment by jekkos** [comment]
I'll apply the change in a branch then test it quickly on the dev server.

**Comment by objecttothis** [comment]
num_rows() will always return an int, so that should be OK to go to ===.  hash_version is an int and md5() should return a string. so since $row->password is a string, those should be good.

**Comment by objecttothis** [comment]
> 
> 
> I'll apply the change in a branch then test it quickly on the dev server.

Thanks

**Comment by objecttothis** [comment]
Thanks for keeping up on these security items... I have noticed a number of complaints during build about outdated software going into builds that have vulnerabilities... we should look into those at some point.

**Comment by jekkos** [comment]
Yes I think most of those messages are from npm.. which we do not really use in the application itself, so it might have less impact.
