### ISSUE TITLE
Server Setup Issue

### ISSUE THREAD

**Issue by Prasad-Gandi** [opensourcepos/opensourcepos#3326]
Im getting the below error when hitting http://localhost:8084/public/    
Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404
localhost
Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.3.16

Steps what i did is 

1.  Downloaded sourcecode of OpensourcePos 3.3.5
2. Installed xampp and in placed extracted project in C:\xampp\htdocs\opensourcepos
3. Then runned this commands a.composer install
               b.npm install
c.grunt --force
4. set phpmysqladmin and created db for ospos 
5. edited database.php and added database details 
6. after started apache and mysql 
        
 Thanks In advance..........................

**Comment by jekkos** [comment]
Who is your webmaster? They say you should contact him

**Comment by jekkos** [comment]
You have probably put the files in the wrong dir

**Comment by Prasad-Gandi** [comment]
> You have probably put the files in the wrong dir

its worked now when iam acessing with localhost:8084/ospos/public
