### ISSUE TITLE
CSRF vulnerabilities in remove and delete forms

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#3332]
Some of the forms have CSRF vulnerabilities due to the fact that we allow a GET in the method handling. POST should be enforced everywhere as that would block an attacker into tricking a user with a valid session into triggering form actions on these specific methods.

One case was overlooked and an extra condition is added.

**Comment by daN4cat** [comment]
Despite all the work we have done years ago in improving security, there are still issues. It's a constant learning story.
