### ISSUE TITLE
Session error 

### ISSUE THREAD

**Issue by kaandenizbilkin** [opensourcepos/opensourcepos#3334]
### Question
Hello there. I log in to the system and after 3 - 5 seconds the log off, what could be the problem.

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [OK] Reporting an issue of an unmodified OSPOS installation
- [OK] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [OK] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [OK] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [OK] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [OK] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [OK] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.5
- OSPOS git commit hash is: ------
- PHP version is: 7.3
- MySQL or MariaDB version is: 5 MYSQL
- OS and version is: 
- WebServer is: birifix.com
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by jekkos** [comment]
Did you click the log out button?

**Comment by jekkos** [comment]
Do you use HTTPS or not? Which browser do you use? 

It might be an issue with the cookie not being picked up by javascript, I know there is some part that enables HTTPOnly flag in 
case you are on SSL.

**Comment by rizaljanuari** [comment]
> Do you use HTTPS or not? Which browser do you use?
> 
> It might be an issue with the cookie not being picked up by javascript, I know there is some part that enables HTTPOnly flag in case you are on SSL. 

Yes i've installed an SSL Certificate for this app. I try lot of browser like chrome, edge, Firefox etc but the issue still the same.

**Comment by jekkos** [comment]
@rizaljanuari was this solved in the end?

**Comment by tajammalads** [comment]
Same issue here.. any solution??

**Comment by tajammalads** [comment]
I found the solution for this.

Just go to file
../application/config/config.php

then go to "Session Variables" Section
and find "ses_match_ip"
then change value from "TRUE" to "FALSE"

$config['sess_match_ip'] = FALSE;

That's it. :)



> @rizaljanuari was this solved in the end?

**Comment by rizaljanuari** [comment]
> @rizaljanuari was this solved in the end?

not yet , but ill try the sollution above

**Comment by rizaljanuari** [comment]
> I found the solution for this.
> 
> Just go to file ../application/config/config.php
> 
> then go to "Session Variables" Section and find "ses_match_ip" then change value from "TRUE" to "FALSE"
> 
> $config['sess_match_ip'] = FALSE;
> 
> That's it. :)
> 
> > @rizaljanuari was this solved in the end?

Work like magic. Thanks :D
