### ISSUE TITLE
Adding New Item Major Issue/ Bug

### ISSUE THREAD

**Issue by minhazulOO7** [opensourcepos/opensourcepos#3340]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [?] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [?] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.5
- OSPOS git commit hash is: a2e7c0
- PHP version is: 7.2.24
- MySQL or MariaDB version is: 5.5.5-10.3.28-MariaDB
- OS and version is: Linux 4.18.0-305.19.1.el8_4.x86_64
- WebServer is: Apache/2.4.37 (AlmaLinux)
- Selected language is: en-US
- (If applicable) Docker installation: N/A
- (If applicable) Installation package for the LAMP/LEMP stack is: N/A

### Issue / Bug

When adding a new item, If I do not edit "**Receiving Quantity**", "**Reorder Level**" (there is already a value of 1 but it doesn't counts), submit it, it will say "**Error adding/updating item product**" and it will not show on items list. I have to go to sales, search for it and make a bill. After that it will show on items list. Currently I have to add a product by editing "**Receiving Quantity**", "**Reorder Level**" to any value then it works. That pre value 1 doesn't works. I have to manually enter 1 or any value then it works. **PLEASE CHECK IT BEFORE MANY USERS COMPLAIN ABOUT IT**.

**Comment by daN4cat** [comment]
I don't think you checked old cases because there is an answer to that. Please do.

**Comment by daN4cat** [comment]
which is fixed in 3.3.6. Hope that goes out soon / by end of the month.
