### ISSUE TITLE
Create Giftcard issue

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#3342]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: latest but I can reproduce with 3.3.4 using https://demo.opensourcepos.org/
- OSPOS git commit hash is: 
- PHP version is: 7.x
- MySQL or MariaDB version is: 10.x
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

- Go to GIftcards
- Create new Giftcard
- Select a Customer
- Set 1000.00 as value and leave the cursor in the text box (important!)
- Click with the mouse Submit
- The dialog box will not close and Submit is grayed out but no new Giftcard is created
- To exit from the dialog box click on the X on the top right

If you unselect the value text box or set something smaller than 1000 the Submit will succeed.

It took a while to understand why sometimes works and sometime no and that's the sequence to reproduce the issue.

**Comment by jekkos** [comment]
Might be related to the form validation that is not triggered? There is this greying out we did for the double submit issue. It might be related to that. The form might not be marked as valid as the field didn't blur yet.

**Comment by jekkos** [comment]
@daN4cat I can't imagine the form validation not being triggered once you submit the form? Are you sure it's due to the blur() event not being fired? We did add this double submit prevention some time ago so it could also be related to that. Perhaps if you have the time maybe revert that change and retest? Do you want to have a fix for this included in 3.3.6?

**Comment by daN4cat** [comment]
It's a minor because there is a workaround, which is to make sure the cursor leaves the text box before clicking submit.
We can move a fix to the next version so that we can release 3.3.6.

**Comment by jekkos** [comment]
Release is done now.
