### ISSUE TITLE
Composer validate warnings

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3350]
### Issue / Bug  / Question / New Feature

Composer validate gives the following results.  How should we resolve the warnings?

validate --no-interaction --ansi --verbose --no-check-publish --with-dependencies
 ./composer.json is valid but your composer.lock has some errors
 # Lock file errors
 - The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
 codeigniter4/framework is valid
 doctrine/instantiator is valid
 dompdf/dompdf is valid, but with a few warnings
 # General warnings
 - License "LGPL-2.1" is a deprecated SPDX license identifier, use "LGPL-2.1-only" or "LGPL-2.1-or-later" instead
 kenjis/ci-phpunit-test is valid
 kint-php/kint is valid
 laminas/laminas-escaper is valid
 laminas/laminas-zendframework-bridge is valid
 mikey179/vfsstream is invalid, the following errors/warnings were found:
 # General errors
 - name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$
 # General warnings
 - Deprecation warning: Your package name mikey179/vfsStream is invalid, it should not contain uppercase characters. We suggest using mikey179/vfs-stream instead. Make sure you fix this as Composer 2.0 will error.
 - License "BSD" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
 If the software is closed-source, you may use "proprietary" as license.
 # Publish warnings
 - Name "mikey179/vfsStream" does not match the best practice (e.g. lower-cased/with-dashes). We suggest using "mikey179/vfs-stream" instead. As such you will not be able to submit it to Packagist.
 myclabs/deep-copy is valid
 nikic/php-parser is valid
 paragonie/random_compat is valid
 phar-io/manifest is valid
 phar-io/version is valid
 phenx/php-font-lib is valid, but with a few warnings
 # General warnings
 - License "LGPL-3.0" is a deprecated SPDX license identifier, use "LGPL-3.0-only" or "LGPL-3.0-or-later" instead
 phenx/php-svg-lib is valid, but with a few warnings
 # General warnings
 - License "LGPL-3.0" is a deprecated SPDX license identifier, use "LGPL-3.0-only" or "LGPL-3.0-or-later" instead
 phpdocumentor/reflection-common is valid
 phpdocumentor/reflection-docblock is valid
 phpdocumentor/type-resolver is valid
 phpspec/prophecy is valid
 phpunit/php-code-coverage is valid
 phpunit/php-file-iterator is valid
 phpunit/php-text-template is valid
 phpunit/php-timer is valid
 phpunit/php-token-stream is valid
 phpunit/phpunit is valid
 psr/log is valid
 sabberworm/php-css-parser is valid
 sebastian/code-unit-reverse-lookup is valid
 sebastian/comparator is valid
 sebastian/diff is valid
 sebastian/environment is valid
 sebastian/exporter is valid
 sebastian/global-state is valid
 sebastian/object-enumerator is valid
 sebastian/object-reflector is valid
 sebastian/recursion-context is valid
 sebastian/resource-operations is valid
 sebastian/version is valid
 symfony/polyfill-ctype is valid
 tamtamchik/namecase is valid
 theseer/tokenizer is valid
 vlucas/phpdotenv is valid
 webmozart/assert is valid
 Composer found errors in ./composer.json.

**Comment by jekkos** [comment]
Might be good to run a composer update to see if the lock file is put in sync?

**Comment by objecttothis** [comment]
This has been resolved:

```
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
# General warnings
- require.codeigniter4/framework : exact version constraints (4.5.1) should be avoided if the package follows semantic versioning
- require.laminas/laminas-escaper : exact version constraints (2.13.0) should be avoided if the package follows semantic versioning
- require.psr/log : exact version constraints (3.0.0) should be avoided if the package follows semantic versioning
```
