### ISSUE TITLE
A PHP Error was encountered --- mysqli::real_connect(): (08004/1040): Too many connections

### ISSUE THREAD

**Issue by govardhan080** [opensourcepos/opensourcepos#3354]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 080e8ac
- PHP version is: 7.4.16
- MySQL or MariaDB version is: 5.7.32
- OS and version is: MacOs Catalina 10.15.6 (19G2021)
- WebServer is: 2.4.46
- Selected language is:  English (US)
- (If applicable) Docker installation: NO
- (If applicable) Installation package for the LAMP/LEMP stack is:

### Issue / Bug  

Hi, I am getting "mysqli::real_connect(): (08004/1040): Too many connections" randomly in middle of Invoicing.
Previously had got this once or twice in last 2 months, but from past few days, it is happening multiple times in a single day,. 

Only 2 users are using in 2 laptops at max, unable to understand why this error is occuring.
Please let me know if i have to change any settings to fix this issue. Refer screenshot for more information on the error.
Thanks in advance.
![Too_Many_Connection_Error](https://user-images.githubusercontent.com/88027749/140723842-df628227-f81d-4fbb-b5b0-4c53bc3a447c.png)

![Too_Many_Connection_Error](https://user-images.githubusercontent.com/88027749/140723785-b38f7ac1-ace9-40d9-a930-f9ed3f70cd7d.png)

**Comment by jekkos** [comment]
Are you using a local database? Do you have a max connection count set on the users?

**Comment by objecttothis** [comment]
Assuming that you aren't being hit by a slow loris or other DoS attack, @jekkos is right that you need to look at which processes are using the connections and what the max connections are set to.  How to do this will depend on the operating system of the server.

**Comment by objecttothis** [comment]
scratch that.  It isn't likely a DoS attack since it's MySQL that's complaining and not your server.

**Comment by govardhan080** [comment]
Actually, looks like the issue is fixed, 
I observed that my hosting provider (bluehost) had updated php version to 8.0, i reverted back to 7.4+ and since then i have not encountered the error. Probably PHP 8.0 was resulting in multiple open connections or something like that?

**Comment by daN4cat** [comment]
PHP 8.0 is not supported (yet).

**Comment by objecttothis** [comment]
> PHP 8.0 is not supported (yet).

The CodeIgniter 4 upgrade sets the stage for PHP 8 support but isn't the only player.
