### ISSUE TITLE
Error logging into the demo site

### ISSUE THREAD

**Issue by steveharman** [opensourcepos/opensourcepos#3356]
Trying to login to the demo system mentioned in the README results in:

![Screenshot_2021-11-13-15-15-19-387_com brave browser](https://user-images.githubusercontent.com/12557929/141649131-4394d952-26e3-4da9-b436-2cc65caaa9e8.jpg)

**Comment by jekkos** [comment]
It seems that a language file might be missing in malay. Perhaps someone switched to this language which then caused this error.

**Comment by jekkos** [comment]
This does not occur on dev, when I switch to malay, everything just works. So it might have been an issue in 3.3.4. Language files were synced after.
