### ISSUE TITLE
The installation is not correct, check your php.ini file

### ISSUE THREAD

**Issue by bhojkamal** [opensourcepos/opensourcepos#3358]
### Background
There is no problem with php version 7.3 before but when I change to php version to 7.4, I could not login to ospos. 
I have extensions php-gd, php-bcmath, php-intl, php-mbstring enabled, but I could not find php-openssl and php-curl on my server php extension on any php version. But there is no issue for php v7.3.

### Installation information

- OSPOS version is: 3.3.4
- OSPOS git commit hash is: 
- PHP version is: 7.4

### Issue 
When I try to login to ospos, it throws msg like this -> 
`The installation is not correct, check your php.ini file`

**Comment by odiea** [comment]
Check the prior open and closed issues.

**Comment by bhojkamal** [comment]
I didn't find the solutions on previous open and closed issues. 
However, I've seen the draft for ospos in codeigniter4 upgrade, hope, it will run on php 8.0 and 8.1 too. 
For now, I'm using PHP 7.3.

**Comment by jekkos** [comment]
I suppose this is due to your setup. The app works fine on 7.4 in docker with all dependencies installed (check the dev server).
