### ISSUE TITLE
An Error Was Encountered

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#3360]
Hello OSPOS Developers:
I upgraded my PHP from 5.6 to 7.4 and install OSPOS 3.3.4, It installs good and I try used the old database and it runs well... I can Open All the Modules.. but when I tried to sale its says and after hitting complete button nothing happens...and when i refresh the browser it says "An Error Was Encountered...it cannot complete the transactions.... 

I need clarification on this matter..Thank you and Godbless

**Comment by izeblood** [comment]
![Uploading 1.JPG…]()

![Uploading 2.JPG…]()

**Comment by izeblood** [comment]
![1](https://user-images.githubusercontent.com/32444665/141729085-49275120-17fc-4738-ab99-46c9f31add99.JPG)
![2](https://user-images.githubusercontent.com/32444665/141729093-00c4a598-029e-45d5-b033-3c408c8c8b15.JPG)

**Comment by odiea** [comment]
You will have to enable error logging and show what this error is

**Comment by izeblood** [comment]
I can't locate any logs file or any error logs in the application/logs folder...I already set my php.ini display_errors

**Comment by izeblood** [comment]
Can you suggest how to enable the error logging in ospos?

**Comment by izeblood** [comment]
when I refresh my browser it says"
An Error Was Encountered
The action you have requested is not allowed. "

**Comment by odiea** [comment]
application/config/config.php around line 261 change 0 to 1.
Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

**Comment by jekkos** [comment]
Can you try to upgrade to latest master @izeblood so we can release it ?

**Comment by izeblood** [comment]
okay I'll try it...

**Comment by izeblood** [comment]
> application/config/config.php around line 261 change 0 to 1.
> 
> Error Logging Threshold
> | | You can enable error logging by setting a threshold over zero. The | threshold determines what gets logged. Threshold options are: | | 0 = Disables logging, Error logging TURNED OFF | 1 = Error Messages (including PHP errors) | 2 = Debug Messages | 3 = Informational Messages | 4 = All Messages | | You can also pass an array with threshold levels to show individual error types | | array(2) = Debug Messages, without Error Messages | | For a live site you'll usually only enable Errors (1) to be logged otherwise | your log files will fill up very fast. | */ $config['log_threshold'] = 1;


<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-11-18 13:07:21 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales` (`sale_time`, `customer_id`, `employee_id`, `comment`, `sale_status`, `invoice_number`, `quote_number`, `work_order_number`, `dinner_table_id`, `sale_type`) VALUES ('2021-11-18 13:07:21', NULL, '1', '', 0, NULL, NULL, NULL, NULL, 0)
ERROR - 2021-11-18 13:07:21 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales_payments` (`sale_id`, `payment_type`, `payment_amount`, `cash_refund`, `cash_adjustment`, `employee_id`) VALUES (0, 'Cash', 1255, 0, 0, '1')
ERROR - 2021-11-18 13:07:21 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2021-11-18 13:07:21', '4363', '1', '1', 'POS 0', -1)
ERROR - 2021-11-18 13:07:21 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2021-11-18 13:07:21', '2432', '1', '1', 'POS 0', -1)

**Comment by izeblood** [comment]
ERROR - 2021-11-18 13:01:03 --> Severity: Warning --> Use of undefined constant IzeBlood - assumed 'IzeBlood' (this will throw an Error in a future version of PHP) C:\xampp\htdocs\pos3.3.4\application\views\login.php 6
ERROR - 2021-11-18 13:01:30 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales` (`sale_time`, `customer_id`, `employee_id`, `comment`, `sale_status`, `invoice_number`, `quote_number`, `work_order_number`, `dinner_table_id`, `sale_type`) VALUES ('2021-11-18 13:01:29', NULL, '1', '', 0, NULL, NULL, NULL, NULL, 0)
ERROR - 2021-11-18 13:01:30 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales_payments` (`sale_id`, `payment_type`, `payment_amount`, `cash_refund`, `cash_adjustment`, `employee_id`) VALUES (0, 'Cash', 777, 0, 0, '1')
ERROR - 2021-11-18 13:01:30 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2021-11-18 13:01:30', '934', '1', '1', 'POS 0', -1)
ERROR - 2021-11-18 13:01:30 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2021-11-18 13:01:30', '2432', '1', '1', 'POS 0', -1)
ERROR - 2021-11-18 13:08:24 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales` (`sale_time`, `customer_id`, `employee_id`, `comment`, `sale_status`, `invoice_number`, `quote_number`, `work_order_number`, `dinner_table_id`, `sale_type`) VALUES ('2021-11-18 13:08:24', NULL, '1', '', 0, NULL, NULL, NULL, NULL, 0)
ERROR - 2021-11-18 13:08:24 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales_payments` (`sale_id`, `payment_type`, `payment_amount`, `cash_refund`, `cash_adjustment`, `employee_id`) VALUES (0, 'Cash', 1255, 0, 0, '1')
ERROR - 2021-11-18 13:08:24 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2021-11-18 13:08:24', '4363', '1', '1', 'POS 0', -1)
ERROR - 2021-11-18 13:08:24 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2021-11-18 13:08:24', '2432', '1', '1', 'POS 0', -1)

**Comment by izeblood** [comment]
> n release i





> Can you try to upgrade to latest master @izeblood so we can release it ?

okay.... here's the result:
ERROR - 2021-11-18 13:41:58 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales` (`sale_time`, `customer_id`, `employee_id`, `comment`, `sale_status`, `invoice_number`, `quote_number`, `work_order_number`, `dinner_table_id`, `sale_type`) VALUES ('2021-11-18 13:41:58', NULL, '1', '', 0, NULL, NULL, NULL, NULL, 0)
ERROR - 2021-11-18 13:41:58 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_sales_payments` (`sale_id`, `payment_type`, `payment_amount`, `cash_refund`, `cash_adjustment`, `employee_id`) VALUES (0, 'Cash', 2629, 0, 0, '1')
ERROR - 2021-11-18 13:41:58 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2021-11-18 13:41:58', '4822', '1', '1', 'POS 0', -1)
ERROR - 2021-11-18 13:41:58 --> Query error: Duplicate entry '0' for key 'PRIMARY' - Invalid query: INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2021-11-18 13:41:58', '4538', '1', '1', 'POS 0', -1)

![ospos1](https://user-images.githubusercontent.com/32444665/142359047-cc116066-e4f9-41f0-bdff-f832b0d53f4f.JPG)
![ospos2](https://user-images.githubusercontent.com/32444665/142359058-368c45c6-6ef6-438e-b1a1-074f2882b250.JPG)
![ospos3](https://user-images.githubusercontent.com/32444665/142359067-65610b83-8e2b-42e5-b751-610da66ad6ee.JPG)

**Comment by izeblood** [comment]
I think the database that I importing is something wrong...
since I make a new database and it works well.

**Comment by izeblood** [comment]
Yes...I solved it already....Thank you OSPOS admins....
