### ISSUE TITLE
Getting Slow 

### ISSUE THREAD

**Issue by navasrahim89** [opensourcepos/opensourcepos#3361]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by daN4cat** [comment]
There is no information here, I close this issue.

**Comment by navasrahim89** [comment]
Slow processing

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by daN4cat** [comment]
Yeah, we are all slow processing this issue....

**Comment by navasrahim89** [comment]
No What am telling is Application is becoming slow when it is 3.3.6 version.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by daN4cat** [comment]
This is a bit of a guess game. You may have a point but ehat about explaining in more detail what is slow and under which conditions?
Also, is it slow in listing Items, searching for items, or Customers or something else?

There was no version mentioned before in the original post.

**Comment by navasrahim89** [comment]
Yes Actually  its getting slow while sale
Inserting items and more.
Version is latest  3.3.6

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by navasrahim89** [comment]
I tried with different browsers.
Still its same.
Quickly i can't insert items when its come to counter.
Among that all other is ok.
Good Apps.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by navasrahim89** [comment]
Dear Sir​ ,

This is the issue , that the email are not sending.
OSPOS Installation Info: 3.3.6 - dev
Language Code: en-US

OSPOS Timezone is Different from your Local Timezone.

Local Timezone:
Asia/Dubai

OSPOS Timezone:
America/New_York

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.48 (Win64) OpenSSL/1.1.1l PHP/7.4.23
.PHP Version: 7.4.23
.DB Version: 5.5.5-10.4.21-MariaDB
.Server Port: 80
.OS: Windows NT 10.0

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [import_customers.csv:] - 0666 | Readable ✓ | Vulnerable or Incorrect Permissions ✗

Security Vulnerability Warning
Incorrect permissions leaves this software at risk.

» [application/logs:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [public/uploads/item_pics:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [import_customers.csv:] is readable, but the permissions are incorrectly set. Please set it to 640 or 660 and refresh.
Asia/Dubai



________________________________
