### ISSUE TITLE
INSTALLATION ISSUE VIA XAMPP LOCALHOST

### ISSUE THREAD

**Issue by mykendoch** [opensourcepos/opensourcepos#3363]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- X[] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

AFTER FOLLOWING THE STEPS FOR XAMPP INSTALLATION, IM RECEIVING AN ERROR AFTER OPENIN LOCALHOST/SALES   THE WAY I HAVE CALLED IT. THE EERROR IS   Not Found
The requested URL was not found on this server.

Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/7.3.28 Server at localhost Port 80

**Comment by odiea** [comment]
localhost/opensource/public the the login should appear

**Comment by mykendoch** [comment]
Thankful for your feedback. I have tried all that the login is not
appearing I'm using Version 3.3.4 .
Can you be somewhere I connect you remotely for a fee ?

**Comment by odiea** [comment]
You will need to first set up the database then pint to the proper location of your setup

**Comment by mykendoch** [comment]
The database is well installed no problem there even the configurations for
the apache php.ini well done the issue is loading the login page or the
system

**Comment by hephitao** [comment]
I encountered the same error, you just have to enter the index.php through the path 

`http://localhost/{YOUR_PROYECT_NAME}/public/index.php`

**Comment by daN4cat** [comment]
That means the .htaccess file is not configured correctly with the subpath.

**Comment by mykendoch** [comment]
Yea the issue was about the .htaccess n it was sorted out Thankful very
much
