### ISSUE TITLE
EMAIL RECEIPT IS NOT WORKING,

### ISSUE THREAD

**Issue by navasrahim89** [opensourcepos/opensourcepos#3364]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by navasrahim89** [comment]
Email Function not working.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by daN4cat** [comment]
Thanks for the clarification but you seem to post quite cryptic issues.
You seem to disregard completely the issue template where it's clearly stated that if you don't fill it in the issue will be closed.
Not to be mean here, but it's extremely difficult to help you without a bit of context and explanation about what you are doing and trying to achieve.
Also, please search past issue as you may find some help there.

**Comment by navasrahim89** [comment]
Yes. Sure.i tried with old post .but still from xampp is giving error message.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by navasrahim89** [comment]
Please help me.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
