### ISSUE TITLE
Question: Barcode Format on Sales Form

### ISSUE THREAD

**Issue by medinagen** [opensourcepos/opensourcepos#3368]
Background information
IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

[] Reporting an issue of an unmodified OSPOS installation
[] Checked open and closed issues and no similar issue was already reported (please make sure you searched!)
[] Read README, WHATS_NEW, INSTALL.md and UPGRADE
[] Read the FAQ for any known install and/or upgrade gotchas (in specific PHP extensions installed)
[] Read the wiki
[] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
[] Aware the installation code is in bintray (see README), and GitHub master is for developers only and therefore not complete nor stable
Installation information
OSPOS version is: 3.3.5 - b92515
OSPOS git commit hash is:
PHP version is: 7.4.8
MySQL or MariaDB version is: 5.7.34-37
OS and version is: Linux 2.6.32-896.16.1.lve1.4.54.el6.x86_64
WebServer is: byethost22.com
Selected language is: en-US
(If applicable) Docker installation:
(If applicable) Installation package for the LAMP/LEMP stack is:

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Hi everyone. I would like to know if there is any way that the barcodes are printed with Code128 format in the printing of a quote or sale.
I need the barcode to be read by a barcode reader on a printed quote.
Thank you

**Comment by jekkos** [comment]
@medinagen You'll need to fix the code to make this work.
