### ISSUE TITLE
Undefined offset error in sales_lib when making sales with item_kits, it happens randomly

### ISSUE THREAD

**Issue by 0x10101** [opensourcepos/opensourcepos#3369]
![image](https://user-images.githubusercontent.com/49187932/143673551-c5341fb2-724f-43ee-825b-fd8b29490392.png)
Using : OSPOS Installation Info: 3.3.4 - 392d92

**Comment by jekkos** [comment]
the stack suggests that it happened during item deletion?

**Comment by daN4cat** [comment]
What's in line 1004 in Sale_lib.php?

**Comment by odiea** [comment]
```
public function delete_item($line)
	{
		$items = $this->get_cart();
	1004	$item_type = $items[$line]['item_type'];
		if($item_type == ITEM_TEMP)
		{
			$item_id = $items[$line]['item_id'];
			$this->CI->Item->delete($item_id);
		}
		unset($items[$line]);
		$this->set_cart($items);
	}
```

**Comment by jekkos** [comment]
Ok then we should look at how items in an item kit are added and whether they have the item_type set in the cart?

**Comment by odiea** [comment]
Are you possibly selling a Temp Item in one of your kits?

**Comment by daN4cat** [comment]
Good thought @odiea , well done.

**Comment by 0x10101** [comment]
I agree with @odiea well I was trying Price option (between kit only and kit and stock only). The item kit was changed by me several time to understand the behaviour.

**Comment by daN4cat** [comment]
Therefore, what is that is happening there?
