### ISSUE TITLE
need total quantity to be print on receipt

### ISSUE THREAD

**Issue by tallururevanth** [opensourcepos/opensourcepos#3373]
Hi..!!

I've modified my sale receipt as my requirements. But I have stucked at providing total sale quantity. can anyone please help me on this to get total quantity.
![Screenshot (8)](https://user-images.githubusercontent.com/22185585/145504087-e08457c8-0841-4b39-9032-71e410897ac0.jpg)

**Comment by odiea** [comment]
After you fill out the form correctly I will give you the answer.

**Comment by tallururevanth** [comment]
I don't know how to do it. thats why i asked for help.
