### ISSUE TITLE
Any one know how to reset the demo Servers. Been down  for awhile

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3374]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by jekkos** [comment]
Ah I was not aware. I think the disk ran full and I had to clean up some stuff, will try to restart now.

**Comment by Neustradamus** [comment]
@jekkos: Question: What is the username/password to test the demo?
There is no informations...
I think it is a big problem...

**Comment by SteveIreland** [comment]
Information about the demo is found on: 
https://github.com/opensourcepos/opensourcepos#-live-demo

**Comment by Neustradamus** [comment]
@SteveIreland: Thanks for your reply!

But when we are here, for example, https://opensourcepos.org/, we click on "Demo", there is a missing part...

**Comment by Neustradamus** [comment]
@SteveIreland: A remark, I think that the demo must be in English by default.
How it is possible to change it?
It must be easy to switch...

**Comment by SteveIreland** [comment]
The demo works fine for me when I go there from https://opensourcepos.org/ so I have no idea what the "missing part" is that you believe is missing.

The configuration options for demo appears to have been disabled.  I'm guessing that there were too many toddlers using configuration to disable the system ... so demo configuration had to be disabled.

My recommendation would be to install a local copy and play with it there.

**Comment by Neustradamus** [comment]
@SteveIreland: You have not understand me :/

The user/pass are not specified on https://opensourcepos.org/ or https://demo.opensourcepos.org/.

A guy who can test the demo, on homepage, click on "Demo" link no problem but no information about how to access.

People do not go on the README: https://github.com/opensourcepos/opensourcepos#-live-demo...

**Comment by SteveIreland** [comment]
I'm done.  

The user id and password IS on the page I provided a link to.  Since you are now advising others not to read the README I don't believe you actually want help.

Have a good year and I hope you get your issues resolved.

**Comment by odiea** [comment]
![2022-01-01 13_18_26-Window](https://user-images.githubusercontent.com/10962177/147859425-162b986b-46f8-4c97-9002-b95e63046c36.png)

**Comment by Neustradamus** [comment]
@SteveIreland, @odiea: The username/password is in the README.MD: https://github.com/opensourcepos/opensourcepos/blob/master/README.md

A guy does not see the username/password when he arrives on:
- The official website home page here: https://opensourcepos.org/ and he click on "Demo" link https://demo.opensourcepos.org/
- Directly on https://demo.opensourcepos.org/ via a crawler engine for example

The user must to KNOW that it is specified here: https://github.com/opensourcepos/opensourcepos or https://github.com/opensourcepos/opensourcepos/blob/master/README.md to know it.

Do you see the problem?

**Comment by jekkos** [comment]
@Neustradamus I guess you just want to have the credentials prefilled in this case? This should not be too hard to do.
@WebShells could you perhaps mention login password on the official website?
