### ISSUE TITLE
Add/adjust payment type of past sale

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3375]
I know I can adjust a past sales payment type by editing the sale from the daily sales report but is there any way to add a payment type?  As an example I have a sale marked as debit when it should be partial debit and partial cash.  I'm running OSPOS 3.3.2.  

Thanks

**Comment by odiea** [comment]
I believe you will need to add them to Locale helper and Sales controller.

**Comment by chunter2** [comment]
Sorry, I was asking to see if there was a way in the current version, not a way to change the code.  I know I can manually delete a row in the ospos_sales_payments table if I have two payment types for a sale but want to change it to just one.  I just can't go the other way since the payment_id's seem to be sequential.  And I'm not sure what would happen if I manually added one out of order.  Maybe @jekkos knows?  

Thanks

**Comment by jekkos** [comment]
The only way to know is to try it out I guess? You can add a new payment line in the db directly and update the old one for example.
