### ISSUE TITLE
blockUI blockOverlay OSPOS homepage issue

### ISSUE THREAD

**Issue by shifasiddeqque** [opensourcepos/opensourcepos#3378]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue /Bug

I am using OSPOS for quite sometime now, working flawlessly but  recently i tried to copy OSPOS folder  to a new laptop, i set up everything before i came across below problem after login. .Attaching Screenshot

![image](https://user-images.githubusercontent.com/14173981/146880035-65294233-8cc9-4cc1-80c3-6bc1f88c038e.png)

for now i am  using below script to hide it but i know this is not the right way 
<script type="text/javascript">
$(document).ready(function(){ 
	$.unblockUI();

});
</script>	 
i don't understand the issue, Could somebody help please
#php #osposISSUE #blockUI #homepage

@odiea  @jekkos

**Comment by daN4cat** [comment]
Which version?

**Comment by shifasiddeqque** [comment]
Open Source Point Of Sale 3.0.2

**Comment by daN4cat** [comment]
Upgrade to latest version

**Comment by shifasiddeqque** [comment]
Any Other solution(temporary) until i upgrade
