### ISSUE TITLE
Show Category is not working!!

### ISSUE THREAD

**Issue by navasrahim89** [opensourcepos/opensourcepos#3381]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is: 
- PHP version is: 
![Screenshot (22)](https://user-images.githubusercontent.com/47893394/147367260-9fd8c0a5-79eb-48a5-8370-4c2133255ffe.png)
![Screenshot (23)](https://user-images.githubusercontent.com/47893394/147367261-39b03531-e2eb-475b-acf9-985fb0968d2f.png)

- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
If you are using the show categories as a drop down then you will need to set up your Categories in Attributes

**Comment by navasrahim89** [comment]
Actually am using 3.3.6 Version
When i enable drop down list
It's not enabling.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by odiea** [comment]
Did you set up the Categories in Attributes? If not then it won't work.

**Comment by navasrahim89** [comment]
No Actually how to add the attribute. ?[Image]

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by navasrahim89** [comment]
Its not showing Category. [Image]

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by odiea** [comment]
![2021-12-24 13_14_38-Window](https://user-images.githubusercontent.com/10962177/147371268-040965ab-5938-4b7a-be85-86cb2ea56e74.png)

**Comment by navasrahim89** [comment]
See the Attachment picture
Category is not Showing
But Size and color Attribute is Showing.
[Image]
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by odiea** [comment]
You are correct this appears to be a bug. 
ERROR - 2021-12-24 13:39:25 --> Severity: error --> Exception: Call to undefined method Attribute::undelete_definition() C:\wamp64\www\willthiswork\application\models\Attribute.php 428

**Comment by navasrahim89** [comment]
Hopefully will be ok in next update?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by navasrahim89** [comment]
AActually Category is an important Module when it's come to multi products sales.
Please do the needful

Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by odiea** [comment]
The Category appears to work after you edit that line in the code. From undelete_definition()  to undelete.
Exception: Call to undefined method Attribute::undelete_definition() C:\wamp64\www\willthiswork\application\models\Attribute.php 428

**Comment by navasrahim89** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by navasrahim89** [comment]
Which line are you tellingabout? [Image] [Image]

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by odiea** [comment]
application\models\Attribute.php line 428 if you have not made any other changes.

**Comment by navasrahim89** [comment]
[Image][Image]
$success = $this  that line?
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by odiea** [comment]
Yes

**Comment by odiea** [comment]
$success = $this->undelete($definition_id);

**Comment by navasrahim89** [comment]
[Image]same . CATEGORY not showing

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by odiea** [comment]
Go back inti Configuration/general and make sure that the Show Category as a dropdown is checked and submit and you should see a green success

**Comment by navasrahim89** [comment]
Still same issue.
Not showing any items in category. [Image]

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by navasrahim89** [comment]
Een i check your demo.
Its same Category  is showing none .

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by odiea** [comment]
And how many Categories have you added to ospos_categories in Attributes?

**Comment by navasrahim89** [comment]
3 Category

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by navasrahim89** [comment]
Actually need a solution for that.
If Category is without Dropdown list.
Its is difficult to entry each time.
And chances for wrongentry also.
I hope it be ok  soon.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by odiea** [comment]
If dropdown is showing none then it appears to be working

**Comment by navasrahim89** [comment]
Sorry.
Actually how it's working?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by navasrahim89** [comment]
AActually i have different category of items.
Which means Beverages.
Cloth
Stationary
Electronics.etc

When i put this items in my inventory
I need to put this items in a category

For example :

Electronics

Under electronics i have variety of items.
So likee that any possibility?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by navasrahim89** [comment]
Now when i checked your demo
It's showing now test5 1 item in category [Image]

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by navasrahim89** [comment]
Thank you for your support.
I find the solution.[Image]

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by odiea** [comment]
@jekkos While you are fixing other stuff can you also fix this error?
ERROR - 2021-12-24 13:39:25 --> Severity: error --> Exception: Call to undefined method Attribute::undelete_definition() application\models\Attribute.php 428

**Comment by navasrahim89** [comment]
Fix Already

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jekkos** [comment]
> @jekkos While you are fixing other stuff can you also fix this error? ERROR - 2021-12-24 13:39:25 --> Severity: error --> Exception: Call to undefined method Attribute::undelete_definition() application\models\Attribute.php 428

I was checking for this code, think it should be good. Will close.

**Comment by navasrahim89** [comment]
Will get  list in attributes?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
