### ISSUE TITLE
Incorrect tax-calculation on Items Summary Report

### ISSUE THREAD

**Issue by LarsGMortensen** [opensourcepos/opensourcepos#3385]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: Newst version on your own demo-site (but the issues was also in older versions)
- OSPOS git commit hash is: Your own Demo site
- PHP version is: Your own demo site, so you tell me
- MySQL or MariaDB version is: Your own demo site, so you tell me
- OS and version is: Your own demo site, so you tell me
- WebServer is: Your own demo site, so you tell me
- Selected language is: Your own demo site, so you tell me
- (If applicable) Docker installation: Your own demo site, so you tell me
- (If applicable) Installation package for the LAMP/LEMP stack is: Your own demo site, so you tell me

### Issue / Bug  / Question / New Feature

Expected behavior: As a user, I would expect the tax-calculation on the Items Summary Report to be correct.

Current behavior: Tax-calculation on Items Summary Report is incorrect.

How to reproduce: 
1: Create an item with a VAT/Sales tax (I used 25% for my example, as that is the VAT-rate in my country, Denmark) 
2: Sell the item, and give a discount (in my example, I gave $50 dollar discount)
3: Check the Items Summary Report

![incorrect-tax-calc-items-report](https://user-images.githubusercontent.com/26773745/147744539-bfceb5ec-2275-4d22-877a-ec71342d518b.PNG)
![sales-tax-item-view](https://user-images.githubusercontent.com/26773745/147744540-cd634b62-c21c-4db4-9591-0f99cbcfa939.PNG)
![cash-discount-given](https://user-images.githubusercontent.com/26773745/147744695-1951e297-9c01-456f-9fde-82d3f85a2a51.PNG)

**Comment by SteveIreland** [comment]
It's been a few months since I've worked on this, but for the given item it looks like the tax is correct if the "tax included" checkbox isn't selected.   Can you include a screen shot of your tax configuration?  It is possible to configure three different tax scenarios ...  1. basic sales tax or 2. tax included  or 3. destination based sales tax.   Also, if you are just testing you should be aware that flipping between the different tax scenarios requires manual data cleanup (or preferably starting from scratch).  It isn't something that should be done.  Taxes will need to be configured correctly before entering any transactions.
