### ISSUE TITLE
Adding search field in reports

### ISSUE THREAD

**Issue by 0x10101** [opensourcepos/opensourcepos#3386]
I would like to add search field in certain reports,
Should I import the search function from /controllers/sales and add it to /controller/reports and add the add the search field in /views/reports?
Or is any other better way to do it?

Thanks in advance

**Comment by jekkos** [comment]
I think you can just enable the search functionality in bootstrap tables for the report. Basically all data should be in the frontend which will make it very easy to do.
There are two generic views you should touch in this case. You can check the js config for the other entities as an example.

**Comment by 0x10101** [comment]
thanks

**Comment by 0x10101** [comment]
> I think you can just enable the search functionality in bootstrap tables for the report. Basically all data should be in the frontend which will make it very easy to do. There are two generic views you should touch in this case. You can check the js config for the other entities as an example.

Which views should I change ?

**Comment by 0x10101** [comment]
so basically in view/reports/ the javascript part so 'partial/bootstrap_tables_locale' is loaded, I guess I have to look in other views that have table search enable and see their javascript config. Argghhh

**Comment by 0x10101** [comment]
Solved: What I did is added 'search: true' in bootstrapTable /views/report/tabular. Works like a charm
