### ISSUE TITLE
Json encode failure for specific data rendered in inventory report

### ISSUE THREAD

**Issue by rigzintsh** [opensourcepos/opensourcepos#3387]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.3
- OSPOS git commit hash is: 
- PHP version is: 7.4.26
- MySQL or MariaDB version is:  5.5.5-10.5.12-MariaDB-cll-lve
- OS and version is: Linux 4.18.0-305.19.1.lve.el7h.x86_64
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by rigzintsh** [comment]
![image](https://user-images.githubusercontent.com/80269899/147825196-a6263d2d-6403-40b8-ad9b-e24c93aca532.png)

**Comment by odiea** [comment]
Try upgrading to the current version.

**Comment by rigzintsh** [comment]
> Try upgrading to the current version.

Hi,
I tried but no luck 
[
![image](https://user-images.githubusercontent.com/80269899/147826846-36ee6fe8-98a3-437e-88cb-bcb39c75673f.png)
](url)

**Comment by rigzintsh** [comment]
![image](https://user-images.githubusercontent.com/80269899/147826883-4af12fdc-427f-4289-a80d-f3e0c8945f92.png)
I can only view "Zero and less" filter

**Comment by odiea** [comment]
Sorry but I can not replicate this issue you are describing.
![2021-12-31 07_06_05-Window](https://user-images.githubusercontent.com/10962177/147827339-8d73a40b-18f5-497b-8f74-1bd2c6eeeae2.png)

**Comment by odiea** [comment]
You can enable error reporting in application/config/config line 260 to see if any error shows in application/logs.

**Comment by rigzintsh** [comment]
no errors logged and more over I cannot view some item ( cannot view items in page 6)

![image](https://user-images.githubusercontent.com/80269899/147843511-0e679680-80aa-44f8-8b09-0736e6a7a254.png)

![image](https://user-images.githubusercontent.com/80269899/147843522-3fcf96c6-a2e5-4ff5-a9be-81cf48ac5f87.png)

I can view items on other pages except for page 6
![image](https://user-images.githubusercontent.com/80269899/147843527-ebe3b31a-6fc3-4f53-8c65-f17900de131b.png)

**Comment by rigzintsh** [comment]
> You can enable error reporting in application/config/config line 260 to see if any error shows in application/logs.

if you dont mind can you please have a look at the test server. 
https://demo.biecefs.org/
admin
passowrd: pointofsale

**Comment by daN4cat** [comment]
I confirm this is an issue. I experience that as well but really not using this report.
You get it with large number of items and I don't understand yet what's causing it.

**Comment by truchosky** [comment]
I noticed this issue not only in this kind of reports, this is present in inventory, sales report, expenses, etc, I think is because some items has special characters like %, ' and others, do you have items with this kind of characters? @rigzintsh

**Comment by daN4cat** [comment]
@truchosky I'll give a try disabling XSS filtering and see if that makes a difference.

**Comment by daN4cat** [comment]
@truchosky you can also test yourself, just set XSS filtering to FALSE in config.php

**Comment by jekkos** [comment]
Maybe because of the CSP headers or?

**Comment by daN4cat** [comment]
That was well before CSP, it's not that for sure.

**Comment by jekkos** [comment]
> > You can enable error reporting in application/config/config line 260 to see if any error shows in application/logs.
> 
> if you dont mind can you please have a look at the test server. https://demo.biecefs.org/ admin passowrd: pointofsale

I tried your login but it doesn't work. Is it still valid?

**Comment by rigzintsh** [comment]
> > > You can enable error reporting in application/config/config line 260 to see if any error shows in application/logs.
> > 
> > 
> > if you dont mind can you please have a look at the test server. https://demo.biecefs.org/ admin passowrd: pointofsale
> 
> @rigzintsh I tried your login but it doesn't work. Is it still valid? Also do you see any JS error when you open the browser console on the page 6?

Please try now. I have brought it up. I do not see any error as such.

**Comment by rigzintsh** [comment]
> > > > You can enable error reporting in application/config/config line 260 to see if any error shows in application/logs.
> > > 
> > > 
> > > if you dont mind can you please have a look at the test server. https://demo.biecefs.org/ admin passowrd: pointofsale
> > 
> > 
> > @rigzintsh I tried your login but it doesn't work. Is it still valid? Also do you see any JS error when you open the browser console on the page 6?
> 
> Please try now. I have brought it up. I do not see any error as such.

It happens at page 23 with 25 row per page.

**Comment by jekkos** [comment]
You probably need to allow error logging as I get a blank return, something went wrong on the server but I can't see what it is.

**Comment by rigzintsh** [comment]
@jekkos I couldnt find any error.
[log-2022-01-13.zip](https://github.com/opensourcepos/opensourcepos/files/7861202/log-2022-01-13.zip)

**Comment by jekkos** [comment]
@rigzintsh Maybe this is because the error logging was not enabled yet, you could set the app in development mode to see the error behind the white page.

**Comment by rigzintsh** [comment]
> @rigzintsh Maybe this is because the error logging was not enabled yet, you could set the app in development mode to see the error behind the white page.

Still no luck @jekkos . No error as such , i set it development mode and tried.

**Comment by jekkos** [comment]
Is your server still available? 
Could you check the developer console, network tab, then click the request that loads the data in the page. If you have enabled error logging you might see something in there.

**Comment by jekkos** [comment]
When I try on the demo server then it does seem to work.

**Comment by rigzintsh** [comment]
> When I try on the demo server then it does seem to work.

Hi @jekkos . The demo server is up. I couldn't find any errors in item list( Page 6 with 100 rows). Only found this error when generating inventory summary report 
![image](https://user-images.githubusercontent.com/80269899/151746898-0b986d50-1322-4946-aa9a-e11a891f3414.png)

I believe i set the app to development mode correctly
![image](https://user-images.githubusercontent.com/80269899/151747033-7c223d2e-67ed-4bba-a35f-a740a250a6c9.png)

Even tried SetEnv CI_ENV production in .htaccess.

**Comment by jekkos** [comment]
Ok that could be the issue @rigzintsh . Indeed the data section is just empty for that request. My hunch is that this might have something to do with XSS filtering. Could you try to disable the global xss filter in config.php ? 

```
$config['global_xss_filtering'] = FALSE
```

**Comment by rigzintsh** [comment]
> Ok that could be the issue @rigzintsh . Indeed the data section is just empty for that request. My hunch is that this might have something to do with XSS filtering. Could you try to disable the global xss filter in config.php ?
> 
> ```
> $config['global_xss_filtering'] = FALSE
> ```

It gives the same error @jekkos

**Comment by jekkos** [comment]
So the data variable is written into the view and json encoded. It's not even empty in this case, if it would be then I would expect to see an empty json array, but there is just no output at all, which is weird.
The weirdest thing is that it does work in your case if you use a different type of filter. The only thing I could think of is that some data fails to be json encoded and the echo does not succeed, for some reason, but then I would at least expect a PHP error or warning there.

I can't really come up with anything else for now. I think a 1-on-1 with a PHP debugger might shed some light on the issue. But for that I would need to get a hold of the data you are running the report for.

**Comment by daN4cat** [comment]
Yep, it's weird. I have exactly the same issue but no obvious reasons.
It's probably due to the amount of fetched data because with any filter works fine.

**Comment by rigzintsh** [comment]
@jekkos This is the data

**Comment by daN4cat** [comment]
It took a bit of time to come back to ths, even because I didn't have much time to debug it.

It turns out that adding % in the item name causes this for me, even in detailed transactions.
How to fix it, I'm not sure because I don't know exactly where this is flocked, not by XSS filer since I tried disabling it with no improvements.

To avoid the problem I've replaced on my side all the % with the word PCT, but that's just to stop the boss complaining about the issue.

**Comment by jekkos** [comment]
@daN4cat could this be an encoding issue? Perhaps we have to convert the data to html entities before we push it through json_encode?

**Comment by jekkos** [comment]
It seems indeed that the default behavior of json_encode is to return false if the encoding fails. There's a couple of flags we could enable to [narrow down the issue](https://www.php.net/manual/en/json.constants.php)

**Comment by jekkos** [comment]
@rigzintsh I made a PR for this issue. Could you perhaps give this a try to see if it resolves your issue?

**Comment by truchosky** [comment]
This is not an issue only in inventory, this happens in reports too, like daily sales, expensive list, summary or detailed reports

**Comment by jekkos** [comment]
I suppose it happens whereever json_encode is used. If you could validate if the fix works then we can apply it in those other places as well.

**Comment by daN4cat** [comment]
Confirm that it happens in any place where a % is returned.

**Comment by jekkos** [comment]
@truchosky did you have any chance to test the proposed solution?

**Comment by jekkos** [comment]
Related to #2452

**Comment by objecttothis** [comment]
Two thoughts:
- Yes, xss_clean is not in CI4 and has been replaced.
- IMO I would prefer that a dev spend the time needed to fix this in a pre-CI4 version to help get CI4 converted faster.  Long term that's a better investment because it both fixes this issue and gets CI4 converted faster.

That said, people can do what they want and I won't be offended either way.

**Comment by jekkos** [comment]
Ok I'll release 3.3.7 when i'm back home. Then we will focus on testing and finishing 3.4.

**Comment by truchosky** [comment]
sorry the late, I was on holidays, it didn't work for me, a really fast way to test this is in expenses module, add what ever expense with % character and that is all, does cover that change in tabular.php the expenses module?

**Comment by jekkos** [comment]
No the change suggested was for the report only. I think a more global fix is needed. We'll test this again in 3.4.

**Comment by objecttothis** [comment]
@rigzintsh 3.4.0 will release soon and this issue should be resolved in 3.4.0.  I will close for now, but reopen if the problem is not resolved.
