### ISSUE TITLE
ajax support instead http requests

### ISSUE THREAD

**Issue by 0x10101** [opensourcepos/opensourcepos#3394]
The web version its ok and does not have that big effect but using ospos on mobiles and devices with smaller screens its an struggle.
Adding single items its ok and could go with it but when adding more than 1 item the behaviour of http request that clears the windows, load the server response it's a headache.

Please consider adding support to ajax requests.

**Comment by jekkos** [comment]
I think the problem is more responsive design here, not ajax request perse. #593 #1959 #593

**Comment by jekkos** [comment]
@0x10101 Feel free to propose any improvements in this area.
