### ISSUE TITLE
Release 3.3.6 - Master file missing

### ISSUE THREAD

**Issue by brainpascal** [opensourcepos/opensourcepos#3395]
I´m looking for the Master zip file of the 3.3.6 release but it´s missing.
¿Where can I get it?
Thanks
![Captura](https://user-images.githubusercontent.com/58516016/148488692-fe40c1f1-305a-4009-9995-d81f3fc01628.PNG)

**Comment by jekkos** [comment]
I have added the latest zip file now. Enjoy!
