### ISSUE TITLE
Sort Customers by Total Spent 

### ISSUE THREAD

**Issue by DamianoSilverhand** [opensourcepos/opensourcepos#3400]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: bb309c
- PHP version is: 7.3.21
- MySQL or MariaDB version is: 5.7.30
- OS and version is: Darwin 19.6.0
- WebServer is: MAMP
- Selected language is: en_US
- (If applicable) Docker installation:
- (If applicable) Installation package for the LAMP/LEMP stack is:

### Issue / Bug  / Question / New Feature

I am trying to sort customers by their **Total Spent** (column), but noticed that column sorting is set to FALSE in the `get_customer_manage_table_headers()` of `tabular_helper.php` file, and it's a derived attribute from a temporal table. How do I go about making the sort work on the customer's "Total Spent"?
![Screenshot 2022-01-10 at 18 01 59](https://user-images.githubusercontent.com/35993666/148797545-9ef9f662-0b39-478a-ad36-5bc6228a0cfd.png)

**Comment by hoststatic** [comment]
maybe taking a look on the controller and the model of Customers. Also I'm looking for getting it working. Will let you updated

**Comment by jekkos** [comment]
Any contribution is welcomed @hoststatic
