### ISSUE TITLE
After upgrade from 3.3.4 to 3.3.6, deleted item cannot show anymore

### ISSUE THREAD

**Issue by lutfiajib** [opensourcepos/opensourcepos#3402]
On version 3.3.4, i can see all "deleted" item. But after upgrade, nothing show. Although all item still on MySql database.

You can also reproduces this from  https://dev.opensourcepos.org 
Login -> Item ->select "Deleted

---
![2022-01-11_05-50](https://user-images.githubusercontent.com/16447833/148851442-f7b1edb7-774f-4b73-9a93-9dc5e3cad4c7.jpg)
"

**Comment by jekkos** [comment]
Thanks for the bug report. You are right, I have verified this on the dev server. Items are not showing in case of deleted flag.

**Comment by jekkos** [comment]
It seems to trigger a 'method not allowed' in this case.

**Comment by jekkos** [comment]
Fix now in master.

**Comment by kayrahann** [comment]
Hello,
I don't do a local install. (Win10) 
![asdasdasdsdsdasddsdasdasasdasdasdasdasd](https://user-images.githubusercontent.com/102741343/161064988-3eec23aa-e26f-4e68-983b-176855dc534a.png)
