### ISSUE TITLE
Issue Importing Items using .CSV

### ISSUE THREAD

**Issue by joanne-nut** [opensourcepos/opensourcepos#3405]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- x[] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

OSPOS Installation Info: 3.3.6 - f3e41a
Language Code: en-GB

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache
.PHP Version: 7.2.34
.DB Version: 5.5.5-10.3.31-MariaDB
.Server Port: 443
.OS: Linux 3.10.0-1160.45.1.el7.x86_64

File Permissions:
» [application/logs:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads/item_pics:] - 0750 | Writable ✓ | Security Check Passed ✓
» [import_customers.csv:] - 0660 | Readable ✓ | Security Check Passed ✓

No security/vulnerability risks.

Europe/London

### Issue / Bug  / Question / New Feature

I am really hoping someone can help.  I have been trying, since Monday, to import a .CSV file of items into OSPOS, I have downloaded the .CSV template, added all the product info, and all I am getting is an error in a red box, which says it couldn't import it, and doesn't tell me why!  I really don't want to have to add over 600 products individually, as when our actual till goes live I will need to upload the items to the new till system using a .CSV. I am using Microsoft Office 2019 to create/edit the .CSV file.  

I can't take a screenshot of the error, as it does not stay on the screen long enough.  Please let me know if you need any other information.  Any help will be hugely appreciated.

**Comment by daN4cat** [comment]
Before importing 600 items, have you tried to import just one and see what happens?

**Comment by daN4cat** [comment]
There is no size limit but something might not be right in your file.
Chunking it will tell you which part is problematic.
Could be some character like %, which tends to be a problem.

**Comment by daN4cat** [comment]
Assume this is now sorted and hence closing it.

**Comment by izeblood** [comment]
I checked this already ..it works well... I uploaded 9181 different items...and it works ..using CSV import...make sure that your cost price and unit price is not equal to 0...

**Comment by izeblood** [comment]
but the only thing that makes me exhausted is the barcode column converting long numbers to scientific notation...
EX. 4.8E+12 instead of 4800180000000 because of a CSV file import...

**Comment by ProFiveCK** [comment]
I having trouble uploading items using the current template...any suggestions?

[import_items.csv](https://github.com/opensourcepos/opensourcepos/files/7895019/import_items.csv)

**Comment by izeblood** [comment]
> I am having trouble uploading items using the current template...any suggestions on what should go into each column to make it work? I use excel to populate the file.
> 
> @izeblood - can you share a sample of your CSV file?
> 
> [import_items.csv](https://github.com/opensourcepos/opensourcepos/files/7895019/import_items.csv)

[izeblood_sample_import.csv](https://github.com/opensourcepos/opensourcepos/files/7901817/izeblood_sample_import.csv)

**Comment by ProFiveCK** [comment]
Thanks, is it normal for the import to not show up in the items list after the import?

It takes some time for an import to show up on the items list, however you can see it in the sales register!

**Comment by joanne-nut** [comment]
@izeblood, I used the CSV template supplied (finally found it when trying to import a CSV file).  I discovered that my problem was a duplicate barcode (a supplier had the same barcode for two items in the same range!).

I do now have a new problem, where despite having the item qty on the CSV, all items are showing as 0 stock!

With regards to the barcode displaying incorrectly, I change the barcode column to number, and move the decimal point if it adds .00 at the end.

Sample .CSV below.

[import_items sample.csv](https://github.com/opensourcepos/opensourcepos/files/8040695/import_items.sample.csv)

**Comment by joanne-nut** [comment]
After successfully uploading the .csv file, I have had a couple of issues;

1. All item quantities are 0, despite the .csv having varying stock quantities
2. Some items that should be £6.99 for instance are showing up as £7.00 - I assume this can be resolved by having the price on the .csv at 3 decimal places?

I have two weeks to get this system live, so really want to iron out any glitches before then!  

TIA :)

**Comment by joanne-nut** [comment]
Did anyone find a solution to the qty issue?  I am days away from this thing going live, and I am just going around in circles now :(

Any help gratefully received!!

**Comment by daN4cat** [comment]
Is the stock location matching something you created in ospos before importing your csv?
