### ISSUE TITLE
Items duplicate in different tables in sales section.

### ISSUE THREAD

**Issue by AshishisLiquid** [opensourcepos/opensourcepos#3411]
### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is:  10.4.22-MariaDB
- OS and version is: Windows 10
- WebServer is: Local
- Selected language is: PHP
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug

I was exploring from Opensourcepos project. I come to find that, if you add any item in table 1 it gets duplicated in table 2. So it will mix the data of different tables.

Table 1 Image :

![Screenshot_11](https://user-images.githubusercontent.com/42866091/151344452-cc9710e4-1cf8-473d-8fbd-a4eb06302046.png)

Table 2 Image : 

![Screenshot_12](https://user-images.githubusercontent.com/42866091/151344508-6c189187-a842-457a-aa0b-233fa4c8ac78.png)

**Comment by odiea** [comment]
Are you suspending these sales during the transactions?

**Comment by AshishisLiquid** [comment]
> Are you suspending these sales during the transactions?

I want to show data as per table selection. I have come through this solution. But because of NO experience in codignator, i can't find resolution.

I was wondering if someone Guide me if we store data in session and get the session data to show.

@odiea I don't think we are suspending sales.

**Comment by odiea** [comment]
You will need to suspend the sales if you want to create more then 1 table transaction otherwise it will be the same sale.

**Comment by AshishisLiquid** [comment]
> You will need to suspend the sales if you want to create more then 1 table transaction otherwise it will be the same sale.

It does work thanks for your support
