### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Dhenshaw96** [opensourcepos/opensourcepos#3415]
I have installed ospos as the install file says to, I can get to the public area but once I login I get a error 4o4

This is the address is is trying to go to ((**************.com/ospos/public/login))

Please Help

### Installation information.

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by XiaoLuxtl** [comment]
I've struggled some hours with this too, the problem is that the rewrite engine wasn't working/configured properly.
In my case (Ubuntu) the problem was solved if I remember correctly enabling the rewrite engine on the directory

`vim /etc/apache2/apache2.conf`

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all **granted**
</Directory>

**Comment by jekkos** [comment]
Did that solve your issue @Dhenshaw96 ?
