### ISSUE TITLE
Is it possible to set a unit price per M2 (square meter) for special products like glass panels?

### ISSUE THREAD

**Issue by mouradsme** [opensourcepos/opensourcepos#3416]
Stores that deal in fabrics and glass panels for example set their unit price per square meter/foot. Now if a customer buys 4 glass panels of 2x3m, he would have to pay a price of 4 x 2 x 3 x UNIT PRICE (M2). And of course, those details should appear in the receipt he receives.
Is this option available in OSPOS? if not, how can it be implemented?
Thanks in advance 

-

**Comment by jekkos** [comment]
I have somewhere a really old branch that allowed you to define custom quantity units.. and relations between those. Alas again it was never merged or I did not take the time to upstream it.

I would just set unit price to be one m2 and then multiply with 24.

**Comment by mouradsme** [comment]
@jekkos The thing is my friend, who asked me for this feature won't budge, I tried telling him he could just set the unit price for M2 (like you suggested), but he says that he wants to be able to set the length and height as well as quantity when he sells to his customers, and that he'd like those values to show on the receipt. 
So for now, I'll try to add two input fields for length and height in the checkout form.

**Comment by mouradsme** [comment]
I managed to hard code the feature by editing the sales controller and view, and the sales library. Although now, all items have to have a "length and width" xD

**Comment by mouradsme** [comment]
@jekkos by the way, which controller function updates the stock quantity after a sale's been completed?
