### ISSUE TITLE
How to add new stock on existing product with new pricing

### ISSUE THREAD

**Issue by rkaombe** [opensourcepos/opensourcepos#3419]
I have **Product A** with the old price, now I have received the same **Product A** with the new price. How do I add that so that when selling this should reflect the new price?

**Comment by truchosky** [comment]
you cant

**Comment by rkaombe** [comment]
That doesn't sound good.

**Comment by odiea** [comment]
Go into Items and change the price. It is up to you what you r sell price is.

**Comment by truchosky** [comment]
I think he is refering to have new stock with new price(higher) and old
stock with older price, if not is like you said, a simple edit in article
module

**Comment by isbullaml** [comment]
Hi,
Have you found any solution to this?
