### ISSUE TITLE
help

### ISSUE THREAD

**Issue by akuwaee** [opensourcepos/opensourcepos#3421]
how to edit the number of Showing 1 to 2 of 2 rows rows per page which defaults to 10 to 100

in the item table

**Comment by akuwaee** [comment]
![image](https://user-images.githubusercontent.com/96807908/153700343-2d12f856-69b4-4a90-817a-a535502a900c.png)

like this how to set default to 100

**Comment by jekkos** [comment]
I think you can change the bstable configuration to have this as a default

**Comment by odiea** [comment]
In configuration general try changing line per page to 100 and see if this helps.

**Comment by akuwaee** [comment]
to change by default to 100 is it possible?

**Comment by akuwaee** [comment]
okeee thanks
