### ISSUE TITLE
Using OpenSourcePOS in pharmacy

### ISSUE THREAD

**Issue by Ippezrobert** [opensourcepos/opensourcepos#3429]
Great work I should say. I have just learned about this project. However I would like to know a few things:-

1. Can open-source pos be used in pharmacy business as a point of Sale? Pharmacies use batch numbers as opposed to barcodes to track items

2. Are item's Manufacture and Expiry dates captured since this is very necessary in tracking drugs?

3. Does the system support 80mm receipts?

4. Am using Windows 10, and I would like to build the system for deployment on production but instructions for development environment setup are not straightforward. How does one prepare a production package? any step by step for newbies 

Thanks and regards

**Comment by bhojkamal** [comment]
@Ippezrobert 
1. No but yes without batch or expiry 
2. NO.
3. yes
4. No.

**Comment by Ippezrobert** [comment]
@bhojkamal thanks for the info. can someone please guide me on installing opensourcepos on my laptop locally. am using windows 11
thanks

**Comment by LuisPadilla** [comment]
> @bhojkamal thanks for the info. can someone please guide me on installing opensourcepos on my laptop locally. am using windows 11 thanks

I can help!

**Comment by objecttothis** [comment]
1. Yes.
2. Create Attributes called Expiration Date (type DATE) and Manufacture Date (type DATE).  You can create a relatively unlimited number of Attributes for items.
3. Yes, we use them.
4. Unfortunately there is not yet an installer, but it sounds like @LuisPadilla is willing to help.

**Comment by Ippezrobert** [comment]
looking forward to the guidance @LuisPadilla to setup the system locally on my pc so that I can contribute back in all ways

**Comment by villenabassi** [comment]
do we support 58mm receipt printing for pharmacy ?

**Comment by Ippezrobert** [comment]
mostly people where i am use 80mm receipt printing

**Comment by bradl822** [comment]
I have used 58mm previously but I moved away from it as it felt very crammed. I had to adjust the receipt for to add data down rather then across the columns.
Also if you use palemoon(older version) you can still use automatic print. I have one register running palemoon that I use Auto print.
I don't remember what version of palemoon off the top of my head but u can check tomorrow.

**Comment by andriux1990** [comment]
> @bhojkamal thanks for the info. can someone please guide me on installing opensourcepos on my laptop locally. am using windows 11
> thanks

This sounds more like a drug distributor for pharmacies.

I understand that a pharmacy is mainly interested in knowing which medications are about to expire... and not in keeping detailed control by batch

**Comment by nathanzky** [comment]
This is interesting application for OSPOS, which version of OSPOS is recommended to use for pharmacy?

**Comment by WebShells** [comment]
> do we support 58mm receipt printing for pharmacy ?

Regarding 58mm Printers, you can use the short version of the receipt. 
Office -> Configuration -> Receipt -> Select Short in Place of Default. 

As @objecttothis mentioned, expiry and manufacturing date are controllable through attributes and can be filtered in the item table by selecting search attributes and typing in the expiry date.
Please reopen this issue if you need any help.
