### ISSUE TITLE
Integration with central inventory management system

### ISSUE THREAD

**Issue by Nirajpatel81** [opensourcepos/opensourcepos#3432]
Hello Everyone,

I’m new to this but looks like this a great POS system.  I have a question around integration with central inventory management system.   For example, let say if I have 4 retail stores and all four stores are running this POS system.  Can these four stores POS integrate with the single inventory management system in cloud and update the item sold information?  

Thank you!

NP

**Comment by jekkos** [comment]
You can create multiple stock locations in this case, so that should be feasible indeed.
