### ISSUE TITLE
Nothing after login page

### ISSUE THREAD

**Issue by gulbalee** [opensourcepos/opensourcepos#3438]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is: 
- PHP version is: 7.4.3
- MySQL or MariaDB version is: mysql  Ver 8.0.28-0ubuntu0.20.04.3
- OS and version is: ubuntu0.20.04.3
- WebServer is: Apache/2.4.41
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 
- _tutorial followed_: https://www.opensourceposguide.com/guide/gettingstarted/installation
- installation placed in: /var/www/html
-time spent on trying to get OSPOS running: more than a week. Tried it on Linux as well as Macbook, and docker, LAMP, MAMP, XAMPP. Only working instance was a softaculous one, however I do not have enough hosting resources and would like to install OSPOS on local computer. 

### Issue

I'm getting a blank screen on Safari after entering login credentials. 
Chrome shows This page is currently unable to handle this request HTTP ERROR 500.

Login page shows up but doesn't lead anywhere.
Any help?

error log is as follows.

```
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-03-15 14:46:25 --> Query error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ospos1.ospos_attribute_values.attribute_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - Invalid query: SELECT `attribute_decimal`, `attribute_id`
FROM `ospos_attribute_values`
GROUP BY `attribute_decimal`
HAVING COUNT(attribute_decimal) > 1
ERROR - 2022-03-15 14:46:25 --> Severity: error --> Exception: Call to a member function result_array() on bool /var/www/html/application/migrations/20210422000000_database_optimizations.php 85
ERROR - 2022-03-16 00:33:45 --> 404 Page Not Found: Public/login
ERROR - 2022-03-16 00:35:25 --> 404 Page Not Found: Public/login

```

Thank you for your time!!

**Comment by odiea** [comment]
Have you tried to disable sql_mode=only_full_group_by?

**Comment by ramirezlp** [comment]
> Have you tried to disable sql_mode=only_full_group_by?

I have the same issue and i tried that but it didn't work

**Comment by junb112706** [comment]
Try this mysql command:

SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
