### ISSUE TITLE
Hardware Integration

### ISSUE THREAD

**Issue by rjiansevilla** [opensourcepos/opensourcepos#3439]
Is there a guide here for hardware integration?
- Cash Register and Scanner

**Comment by bradl822** [comment]
[Wiki Link](https://github.com/opensourcepos/opensourcepos/wiki/Supported-hardware-datasheet) 

My old Epson receipt printer got damaged recently, I just bought a Hoin 80mm receipt printer on eBay. It worked perfectly with OSPOS. 
From what I can advise, any 80mm receipt printer with Auto cut and cash register port is ideal. The cash register port is nice as it will open the cash register drawer for you. As for a scanner I feel like nearly anything will work as they function similarly to any other input device. I have several brands floating around and never had an issue.

**Comment by odiea** [comment]
It is great to see users supplying information for others. Thanks

**Comment by rjiansevilla** [comment]
> [Wiki Link](https://github.com/opensourcepos/opensourcepos/wiki/Supported-hardware-datasheet)
> 
> My old Epson receipt printer got damaged recently, I just bought a Hoin 80mm receipt printer on eBay. It worked perfectly with OSPOS. From what I can advise, any 80mm receipt printer with Auto cut and cash register port is ideal. The cash register port is nice as it will open the cash register drawer for you. As for a scanner I feel like nearly anything will work as they function similarly to any other input device. I have several brands floating around and never had an issue.

Thanks for Sharing,
