### ISSUE TITLE
Incorrect tax calculation (tax included)

### ISSUE THREAD

**Issue by ThinkerNG** [opensourcepos/opensourcepos#3440]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is: b309b6
- PHP version is: 7.4.28
- MySQL or MariaDB version is:  5.5.5-10.3.32-MariaDB
- OS and version is: Linux 3.10.0-1160.49.1.el7.x86_64
- WebServer is: Apache
- Selected language is: de-CH
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Bug

If I set the Swiss tax (VAT) of 7.7% as inclusive. Unfortunately, the cash register (sale) calculates the tax incorrectly. If I sell a stock item worth 100 CHF, the 7.7% VAT should be displayed. However, instead of 7.70 CHF, 7.15 CHF is displayed and the return value calculation is also incorrect. The intermediate total is 92.85 CHF instead of the correct 92.30 CHF. If I change to tax exclusive, then the calculation is completely correct. However, I have to enter all items in the warehouse including the tax and it just has to show correctly on the receipt when I sell. It is not a rounding issue either, have tried all the setting options. I am really hoping for help as I would like to start in sales as soon as possible with this super POS project. But I can't do it this way, because I would be liable to prosecution with incorrectly reported tax.

![Sell tax exclusive OK](https://user-images.githubusercontent.com/59416613/159075920-83d86ace-e678-433e-832a-2409c881a21b.JPG)
![Sell tax inclusive false](https://user-images.githubusercontent.com/59416613/159075965-04374643-e025-4ca8-a69a-6743a58e4a26.JPG)
.

**Comment by bradl822** [comment]
I don't see the issue.. I'm on my phone so I apologise if I missed it but the calculations look correct.

First picture item is excluding tax.
CHF 100 + 7.7% (CHF 7.70) = CHF 107.70

Second picture item is inclusive of tax.
CHF 100 - (CHF 100 / 1.077 = 92.85 rounded) = Tax CHF 7.15

I don't know if that helps.

**Comment by ThinkerNG** [comment]
Thank you bradl822for your quick reply!
You are absolutely right, I made a big mistake in calculating the tax. Shame on me...

FALSE: Gross price - (Gross price * VAT rate) = Net Price
CORRECT: Gross price : (VAT rate + 1) = Net price

Everything is fine with the OSPOS tax calculation. Can be closed. Thanks a lot!
