### ISSUE TITLE
Docker compose up installation error

### ISSUE THREAD

**Issue by smontiu** [opensourcepos/opensourcepos#3441]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Issue 

When trying to install ospos using docker-compose I get an error regarding the manifest of jekkos.

docker-compose up

Creating network "opensourcepos_db_net" with the default driver
Creating network "opensourcepos_app_net" with the default driver
Creating volume "opensourcepos_uploads" with local driver
Creating volume "opensourcepos_logs" with local driver
Creating volume "opensourcepos_mysql" with local driver
Pulling mysql (mariadb:10.5)...
10.5: Pulling from library/mariadb
4d32b49e2995: Pull complete
03231033a668: Pull complete
5bf8bcd9a929: Pull complete
6c260950e90f: Pull complete
35baff4c5363: Pull complete
16cdd7e19187: Pull complete
813bfa8c4c6e: Pull complete
39d35769a106: Pull complete
dbdced1d466c: Pull complete
4ff170e7bd50: Pull complete
2a35ba3c0640: Pull complete
Digest: sha256:608b9e3c129f62efa7ebb93a5373c04784b91a89275d794ac2f2099fe1d6daa2
Status: Downloaded newer image for mariadb:10.5
Pulling ospos (jekkos/opensourcepos:3.3.7)...
**ERROR: manifest for jekkos/opensourcepos:3.3.7 not found: manifest unknown: manifest unknown**

**Comment by hoststatic** [comment]
I experienced same, have you tried downloading source from git and then run on docker ?

**Comment by bradl822** [comment]
I think you're using the tag 'latest' to pull a version that isn't released yet. Only 3.3.6 is out, your log shows 3.3.7

Maybe try using that specific tag 3.3.6 or like hoststatic said you could try directly downloading.

**Comment by smontiu** [comment]
Correct, I changed the tag to the previous one and worked correctly.

Thanks

**Comment by dgoadby** [comment]
I had this problem and 3.3.6 does load ok. The problem I now have is I cannot get the correct URL start the application it just seems to hang.

**Comment by bradl822** [comment]
> I had this problem and 3.3.6 does load ok. The problem I now have is I cannot get the correct URL start the application it just seems to hang.

I would recommend you open a new issue and fill in the template. We really have nothing to go on to know how to start to help with this.

**Comment by jekkos** [comment]
Indeed I bumped the version too rapidly. I have created a tag now and hope travis will now push the 3.3.7 tag

**Comment by jekkos** [comment]
I changed the CI config so now a container should be pushed and tagged properly once a git tag is added in the releases section. When this build is finished there should be a 3.3.7 tag in docker hub, which should solve the issue.
