### ISSUE TITLE
Format Sales ID

### ISSUE THREAD

**Issue by rjiansevilla** [opensourcepos/opensourcepos#3444]
How to format the SALES ID to ten digit number. exemple: SALES INVOICE -0000052102  
try to figure out this guide https://github.com/opensourcepos/opensourcepos/wiki/Sales but seems like I cannot configure it correctly. Thanks

**Comment by rjiansevilla** [comment]
> 

I see the number at the end refer to the digit.. is there a way to show the digit? I mean like the 00001 something like that? I've try using it but it shows the number directly. Thanks

**Comment by SteveIreland** [comment]
I will retest it tonight to make sure that it still works as I would expect it to work.  I haven't touched it in years.  I'm not sure what you mean by "is there a way to show the digit".

The :9 indicates that there should be 9 digits in the rendered token (i.e. the chosen number to be used for the invoice and then prepended with leading zeroes to achieve a 9 digit string to be used for the invoice number.  That is the value rendered by the token.  Then, of course, you can add text (alpha or numeric) in front of the rendered token or add text (alpha or numeric) behind the rendered token.  I believe you can also still combine tokens.

**Comment by SteveIreland** [comment]
In my test the format "9{ISEQ:9}" generated a 10 digit invoice number with an additional 9 as a prefix. So it still seems to be working as originally designed.

![image](https://user-images.githubusercontent.com/23066623/160957856-6e5dc038-7d35-41af-a84c-4ac49a0a48e5.png)

**Comment by rjiansevilla** [comment]
@SteveIreland thanks..
