### ISSUE TITLE
[Bug] In Detailed Sales report it shows only last row for items which have serial number

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3445]
For a sale witch have same item but different serial number, there is a bug on detailed transactions. Because it shows only the last row of sale and not the items (rows). 
The problem is in model application/models/detailed_sales.php and I believe its the getData() function
Everything works fine except the detailed transactions report.
In Sales

![1](https://user-images.githubusercontent.com/99489665/160579049-0e924c0a-150d-43e8-96b8-c890b9cc3260.PNG)

In receipt

![2](https://user-images.githubusercontent.com/99489665/160579135-5abc3e61-b20d-47e9-b560-1c71d9687173.PNG)

In Detailed Sales Report

![3](https://user-images.githubusercontent.com/99489665/160579211-57f1d928-6942-4e6e-b454-fb203e90c2fc.PNG)

So basically in the query of getData have to select item_serial or other solution if an item is inserted multiple times the detailed sales report (transactions) to show

**Comment by bradl822** [comment]
I have just run a quick test and can confirm I get the same result.

![image](https://user-images.githubusercontent.com/38707933/160928560-a5024145-9ef7-4b97-8d48-a1342e8534cd.png)

My details for a reference.
`
OSPOS Installation Info: 3.3.6 - f3e41a
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache
.PHP Version: 7.4.8
.DB Version: 5.5.5-10.3.27-MariaDB
.Server Port: 80
.OS: Linux 2.6.32-896.16.1.lve1.4.54.el6.x86_64

File Permissions:
» [application/logs:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads/item_pics:] - 0750 | Writable ✓ | Security Check Passed ✓
» [import_customers.csv:] - 0660 | Readable ✓ | Security Check Passed ✓

No security/vulnerability risks.

Australia/Sydney`

**Comment by jekkos** [comment]
I suppose this is an issue because the result list is grouped by item_id (which is the same for the two items). If aggregates are used in this case on the quantity, we should use a SUM and not MAX()

**Comment by hoststatic** [comment]
It does not seem to work for me, it sums all previous quantities and other fields that was changed from MAX to SUM for the item. I guess the problem is find a way to show all items that have same item_id even in new/line row would be perfect. 
Because that would match the receipt format.
Thanks in advance

**Comment by hoststatic** [comment]
something like group by item_id would work !?

**Comment by jekkos** [comment]
I changed the fix a bit, haven't tested it. Fingers crossed perhaps it works?

**Comment by bradl822** [comment]
I just tested on my end and it works. Nice One!!!
![image](https://user-images.githubusercontent.com/38707933/161150225-6954ce66-9e10-4852-8d30-392304281659.png)

**Comment by hoststatic** [comment]
works like a charm

**Comment by jekkos** [comment]
Ok thanks for the confirmation. Merged to master now.
