### ISSUE TITLE
How to Show Tax on Sales

### ISSUE THREAD

**Issue by rjiansevilla** [opensourcepos/opensourcepos#3446]
Hi, How to enable tax on the sales? Seems like I cannot able to show it. Screenshot provided Thanks 

https://prnt.sc/iVTdKbDQxfop
https://prnt.sc/VxbDI6HNm5GS

**Comment by rjiansevilla** [comment]
@bradl822 thanks it works.. one last question is there a way to remove the percent? I mean on printing it should be the term TAX not the percent something like that.

**Comment by bradl822** [comment]
You will need to modify your receipt templates.

The default output is the tax % then the tax term then the amount.
e.g. my test sale shows 10% GST $0.23

Find your receipt files in
**application/views/sales/**
If you check your configuration in OSPOS is will list what receipt template you are using so you can modify only the necessary file.

You are looking for a line similar to below.
`<td colspan="2" class="total-value"><?php echo (float)$tax['tax_rate'] . '% ' . $tax['tax_group']; ?>:</td>`
You just need to remove the reference to the tax rate. Similar to below.
`<td colspan="2" class="total-value"><?php echo $tax['tax_group']; ?>:</td>`
This would change my output to GST $0.23

**Comment by rjiansevilla** [comment]
@bradl822 Thank you.
