### ISSUE TITLE
CI4: Replace Database Backup Functionality

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3451]
### Issue / Bug  / Question / New Feature

CI4 no longer has the CI3 feature (https://codeigniter.com/userguide3/database/utilities.html#backup-your-database) to backup your database.

This needs to be replaced in the app\Controllers\Config.php backup_db() function.  Before this can be done we need to decide on how we want to do it. @opensourcepos/org

**Comment by jekkos** [comment]
I even don't know if this feature works properly if you have a larger db, eg. Will it hit the PHP memory limit because it tries to load the whole dump in memory before sending it to the user?

**Comment by jekkos** [comment]
If any objections please shoot @opensourcepos/org

**Comment by objecttothis** [comment]
> @jekkos @objecttothis I actually use this functionality but really only because it was there. I have hit the PHP memory limit and will probably keep hitting it as my database grows. The nice thing about the database backup is I can access it remotely and do a backup to a different machine which saves me having to do all that manually. I'm sure there's a better way but I just haven't taken the time to figure it out.

@chunter2 Thanks for letting me know. It will take some initial setup, but you could setup OpenVPN to remotely VPN into your network and then install something like phpmyadmin which gives you a gui interface.  Alternately SSH and use mysqldump in the CLI then FTP the backup.  As I mentioned before, the current implementation doesn't work, so it would need to be redone to use something like mysqldump anyway.

**Comment by objecttothis** [comment]
For reference, here is the current implementationn
```
	public function backup_db(): void //TODO:https://github.com/opensourcepos/opensourcepos/issues/3451
	{
		$employee_id = $this->employee->get_logged_in_employee_info()->person_id;
		if($this->employee->has_module_grant('config', $employee_id))
		{
			$this->load->dbutil();

			$prefs = ['format' => 'zip', 'filename' => 'ospos.sql'];
			$backup = $this->dbutil->backup($prefs);
			$file_name = 'ospos-' . date("Y-m-d-H-i-s") . '.zip';

			helper('download');
			while(ob_get_level())
			{
				ob_end_clean();
			}

			force_download($file_name, $backup);
		}
		else
		{
			redirect('no_access/config');
		}
	}
```

**Comment by chunter2** [comment]
@objecttothis I actually use ssh tunnels and phpmyadmin already.  Sounds like I just need to use the export function to duplicate the backup button.  Thanks for the info.

**Comment by jekkos** [comment]
I would say phpMyAdmin is the way to go here indeed.
