### ISSUE TITLE
CI4: Thumbnail creation needs to be rewritten

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3453]
### Issue / Bug  / Question / New Feature

Thumbnail creation needs to be brought up to date with CI4 styles in the pic_thumb() function found in the app/Controllers/Items controller.

https://codeigniter.com/user_guide/libraries/images.html

**Comment by jekkos** [comment]
It might indeed pay off to switch to a more actively maintained dependency. I would like to help out but not sure if I will find the time coming weeks.

**Comment by objecttothis** [comment]
@jekkos thanks for wanting to help. Anything you can provide is definitely appreciated, but I understand if you have too many other things going on.

**Comment by objecttothis** [comment]
> It might indeed pay off to switch to a more actively maintained dependency. I would like to help out but not sure if I will find the time coming weeks.

@jekkos did you mean this comment for #3455?

**Comment by jekkos** [comment]
Indeed I commented in the wrong place.

**Comment by ebentil** [comment]
Happy to help with this. I've already fixed and tested locally

**Comment by jekkos** [comment]
Ok great, I'll add you to the team. Can you try to apply changes to the ci4-upgrade branch?

**Comment by ebentil** [comment]
Alright I'll do

**Comment by ebentil** [comment]
I tried pushing directly to the branch but i dont have permission. I've created a PR towards ci4-upgrade instead. Let me know if its not ok

**Comment by objecttothis** [comment]
This code didn't work in CI4... I wonder if @ebentil 's code never got merged because the code was all CI3.  I fixed it.
