### ISSUE TITLE
CI4: Return of an undefined variable in Token_customer model class

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3454]
### Issue / Bug  / Question / New Feature
The get_value() function in app/Models/Tokens/Token_customer.php returns $value which is never defined in the function.

![image](https://user-images.githubusercontent.com/17935339/161233283-39eef6d1-6eee-416e-af34-038a27ba0b11.png)

**Comment by jekkos** [comment]
I wonder if the method is even used then?

**Comment by objecttothis** [comment]
> I wonder if the method is even used then?

It's an abstract public function that is declared in Token.php and implemented in each of the child classes including Token_customer.php

![image](https://user-images.githubusercontent.com/17935339/161492268-b814c1d2-c2ba-4b9e-aaf9-264c01c19468.png)

It's called in the replace_token() function in Token.php but replace_token is never called in the code.
It's called in the Token_lib parse() function
It's also called in the Token_lib resolve_token() function.

It only gets to that return statement (`return $value;`) in one of the below scenarios:
- There's no customer assigned at the time of function call
- customer_info is not empty
- Both

Seems to me that if the customer_info is not empty we should return that value. If the customer_id is -1 we should `return '';`
