### ISSUE TITLE
CI4: Emberlabs Barcode has been deprecated and not maintained for 11 years. Port or replace

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3455]
### Issue / Bug  / Question / New Feature

https://github.com/emberlabs/barcode

They have a deprecation notice and they recommend replacing with something like https://github.com/picqer/php-barcode-generator.  If the existing functionality can be ported to CI4 then we should do it then replace after.  If not, then we need to replace it in order for CI4 to work.

**Comment by jekkos** [comment]
Great work @objecttothis , thanks for the hard work.
