### ISSUE TITLE
CI4: Missing return statement in get_category_name() function of Supplier model

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3456]
### Issue / Bug  / Question / New Feature

Here is a bug in the code that PHP is complaining about and I need to resolve it to move forward with the CI4 conversion. The problem is that the code has a path that doesn't return anything. Seems like either switching the elseif to an else statement or switching the entire block to a switch statement and adding a default would be the logical options. Alternately if we wanted to go the route of throwing an exception we could do that as well, but it means wrapping the calling code in try/catch blocks and handling the exception. Thoughts?

#3271
![158175891-f5c7f9e8-4aa6-40a0-af58-7dc562758767](https://user-images.githubusercontent.com/17935339/161241109-ca6ea493-d5df-4660-8af8-447f1fa4e022.png)

**Comment by jekkos** [comment]
Maybe we can build the language key based on the constant value, so if a new one is added for some reason it will be rendererd as the key instead?

**Comment by objecttothis** [comment]
Currently the constants just represent an integer
![image](https://user-images.githubusercontent.com/17935339/161484602-88ee3e7c-65bd-4406-b54b-21f1d9e2f6ff.png)

I think you mean changing the code to read something like: `return lang('Suppliers.' . $id);` and probably refactor $id to something like $supplier_type, then in the language change the names from `'goods' => 'Goods Supplier',` to `'1' => 'Goods Supplier',`?  Can you confirm?

**Comment by objecttothis** [comment]
We might also be able to get away with `GOODS_SUPPLIER => 'Goods Supplier',` but I'm not sure if we'd have to cast that to a string or it would be fine as an integer and therefore a mixed associative array.

**Comment by jekkos** [comment]
> 



> I think you mean changing the code to read something like: `return lang('Suppliers.' . $id);` and probably refactor $id to something like $supplier_type, then in the language change the names from `'goods' => 'Goods Supplier',` to `'1' => 'Goods Supplier',`? Can you confirm?

Indeed that was my idea. If there is a string missing then it will be directly clear.

**Comment by objecttothis** [comment]
Fixed in #3271 but for now only in the en-US language.
