### ISSUE TITLE
CI4: get_info() function in Item model no longer contains location_id parameter

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3457]
### Issue / Bug  / Question / New Feature

The add_item() function in the Receiving_lib calls item->get_info() with two parameters, but item->get_info() has just one parameter.

![image](https://user-images.githubusercontent.com/17935339/161252136-cd0883f5-2a9e-4e13-9796-81937ac9f10f.png)

![image](https://user-images.githubusercontent.com/17935339/161252280-04e2170d-131e-41da-afa0-b5357a1318c3.png)

@jekkos You removed the 2nd parameter from the function back in 2014 (https://github.com/opensourcepos/opensourcepos/commit/97ff190ba5bd2315b9d7adec9d8e16eab73b64b4) when you were adding functionality to include stock locations. In that same commit you removed the parameter from a bunch of calls to get_info, but there is one call in Receiving_lib that still has the parameter.

![image](https://user-images.githubusercontent.com/17935339/161252234-3ce0079f-8925-4a28-b646-fe904485145f.png)

I need to know what to do with this?  I think it probably just needs to be removed, but wanted to check with you.

#3271

**Comment by jekkos** [comment]
Indeed it is probably an oversight, the param can be removed (as it is not used in get_info either).

**Comment by objecttothis** [comment]
Done
