### ISSUE TITLE
CI4: Fix recursiveCopy() and recursiveUnlink() functions in install.php

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3458]
### Issue / Bug  / Question / New Feature

These two functions have an issue with the RecursiveDirectoryIterator because getSubPathName doesn't exist in that class.  Alternately if install.php is stale and not used we should either remove it or repair it.

#3271

**Comment by jekkos** [comment]
The only thing in use is the translations install currently. This is used in the CI pipeline if I'm not mistaken. Beside this I think we do not use the script at all

**Comment by objecttothis** [comment]
Fixed in #3271
