### ISSUE TITLE
Have anyone tested performance in nginx/apache/litespeed webservers 

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3459]
I would like to know if anyone has tested performance website loads and everything in different web servers like apache/nginx/litespeed or others. 

Currently running on apache but know that running ospos on nginx could be as fast as 2-3 times on speed and performance.
Was there any performance boost? 
How was your experience in different web server software ?

**Comment by jekkos** [comment]
Php 7.3 offers a real speed improvement if I'm not mistaken. I think combined with mariaDb you get nice performance. Not sure if any difference between apache/nginx

**Comment by hoststatic** [comment]
What works for me it's caching static files like png, css, js for longer a month or so, huge boost.
Have never worked with nginx but apache could be configured easy and  have plenty of modules like modsecurity etc.
What I read on web that nginx or better litespeed (newer technologies) give you better performance,
Does this new web server software give better performance that is worthy to switch to them?
