### ISSUE TITLE
Reset product inventory to zero by Category

### ISSUE THREAD

**Issue by phantomgannon** [opensourcepos/opensourcepos#3463]
I need to be able to set the inventory of a particular category to zero so I can audit the quantities by scanning in via recieving to get an accurate stock count

**Comment by hoststatic** [comment]
Please explain in more detail, what you want to achieve and your idea. that could be done using an sql query and even creating a function that would call that query.

**Comment by phantomgannon** [comment]
Thanks. That looks really helpful. For our inventory control we set a category to zero. Then scan the items in. At the end we run a report of in stock items to get a stock count.
We have thousands of items so Do a category at a time so it's broken into mini-stock counts. 
Ideally I'd like the process to be done through a GUI . I'm happy to fund the development work if anyone is available.
