### ISSUE TITLE
[help] Array to string conversion error while creating new custom report

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3464]
I would like to create a report based on detailed_sales.php report and that would have an extra field "Items" as input.
Everything works fine except I couldn't get items input type working. In the input page it throws the error:

```

Severity: Notice

Message: Array to string conversion

Filename: helpers/form_helper.php

Line Number: 615
```

Copied date_input file to date_input_items.php and made the following changes 

```
	<?php
	if (isset($specific_input_name))
	{
	?>
				<?php echo form_label($specific_input_name, 'specific_input_name_label', array('class'=>'required control-label col-xs-2')); ?>
				<div class="col-xs-3">
					<?php echo form_dropdown('specific_input_name', $specific_input_name, '', 'id="specific_input_name" class="form-control selectpicker" data-live-search="true"'); ?>
				</div>
	<?php			
	}	
	?>
```

In controller added 
```
public function date_input_items()
	{
		$data = array();
		$stock_locations = $data = $this->xss_clean($this->Stock_location->get_allowed_locations('sales'));
		$stock_locations['all'] = $this->lang->line('reports_all');
		$data['stock_locations'] = array_reverse($stock_locations, TRUE);
		$data['mode'] = 'sale';
		$data['sale_type_options'] = $this->get_sale_type_options();
		$data['specific_input_name'] = $this->lang->line('reports_item');
		$items = array();
		foreach($this->Item->get_all()->result() as $item)
		{
			$items[$item->item_id] = $this->xss_clean($item->name);
		}
		$data['specific_input_name'] = $items;

		$this->load->view('reports/date_input', $data);
	}

```
In controller detailed_sales function changed
`$this->load->view('reports/date_input_items', $data);`

**Comment by bradl822** [comment]
Can you share what is line 615 in form_helper.php

**Comment by hoststatic** [comment]
fixed the form_helper in vendor was about the label and I was forming it wrong way
changed, I was passing array as title of the input lol
 
<?php echo form_label($specific_input_name, 'specific_input_name_label', array('class'=>'required control-label col-xs-2')); ?> 
to 
<?php echo form_label($this->lang->line('reports_items'), 'reports_items_label', array('class'=>'required control-label col-xs-2')); ?>

**Comment by hoststatic** [comment]
Well I'm creating a report based on detailed_sales and filter by item,

**Comment by hoststatic** [comment]
On the modified_version of detailed_sales reports/model

I made a change in the function
getData()

adding 
`$this->db->where('sales_items_temp.item_id', $inputs['item_id']);`
and in same function 
in
 ```
foreach($data['summary'] as $key=>$value)
		{ ... 
```
added same
`$this->db->where('sales_items_temp.item_id', $inputs['item_id']);`


But I get
 Undefined index: item_id

Any help would be appreciated

**Comment by hoststatic** [comment]
In create_temp_table on the Sale model added MAX(sales_items.item_id) AS item_id, but it does not seem to work. Any idea?

**Comment by bradl822** [comment]
I don't have time right now to look properly but I'm guessing it's something wrong with the sale model. 

This error is because there is no data being passed.

**Comment by hoststatic** [comment]
The report it takes data from Sale model the function create_temp_table, and the temporary table sales_item_temp. Ill upload in paatebin if that also helps you.
Thanks

**Comment by hoststatic** [comment]
https://pastebin.com/vY7fH3wy I've added the comments //added on changes.
Thanks in advance, if you'd like this kind of report with all changes let me know.
Thanks in advance

**Comment by odiea** [comment]
Enable your error log and see what it shows?

**Comment by hoststatic** [comment]
The item_id error dissapeared because I forgot to add as a parameter and in inputs but still it shows not data
tried it without inputs for certain item and it works but with inputs not and not getting any data.

I uploaded in a paste all changes that have been made
https://pastebin.com/CLaWF9DE

Thanks

**Comment by hoststatic** [comment]
What I would like to achieve is getting detailed_sales show for e certain item
Example Keyboard has item_id 100

so in detailed_sales model I've added line 94 and line 163
$this->db->where('sales_items_temp.item_id', 100);

And it shows what it should.
But getting it to work with item input failes to show data

**Comment by hoststatic** [comment]
Guy's I took another look the only problem is that the input does not pass as parameter,
Had a look of the query that happens and saw that item_id get an inappropriate value.

`WHERE `ospos_sales_items_temp`.`item_id` = 'complete`',

I tried changing on the value  date_input_items that is based on /views/reports/date_input/ and adding alternative value and it works
```
$("#generate_report").click(function()
    {       
        window.location = [window.location, start_date, end_date, $('#specific_input_data').val() ,  $("#input_type").val() || 0 ....

```
to  $('#specific_input_data').val() || 100 and it shows the result wanted.

**Comment by hoststatic** [comment]
Fixed. I had made a typo on the id of specific_input_data.
Anyways thanks guys.
If you'd like I'll share the new report

**Comment by odiea** [comment]
Glad you got it working.
