### ISSUE TITLE
First of all, if you're seeing the message `system folder missing` after launching your browser, that most likely means you have cloned the repository and have not built the project

### ISSUE THREAD

**Issue by dennistsc** [opensourcepos/opensourcepos#3475]
hi,

i'm install ospos version 3.3.6 and ubuntu 20.04 and i got Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php after i put 127.0.0.1

then i'm reading the install.md and i saw this message First of all, if you're seeing the message `system folder missing` after launching your browser, that most likely means you have cloned the repository and have not built the project

i'm not sure what is built the project. anyone can help me please. thx u 

this is what i got so far and i think i build it already 

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is:  not sure 
- PHP version is: 7.4.3
- MySQL or MariaDB version is: 8.0.28
- OS and version is: ubuntu 20.04
- WebServer is: apache2
- Selected language is: eng
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by daN4cat** [comment]
You don't need to build the project unless you want to setup the dev environment.

You just download the official release zip file.

**Comment by dennistsc** [comment]
thanks for your reply 
i unzip it and install PHP modules and i do the following

install PHP modules

my location
/var/www/html/ospos/opensourcepos-3.3.7/public

******sudo nano /etc/apache2/sites-available/000-default.conf
ServerAdmin webmaster@localhost
DocumentRoot /var/www/html/ospos/opensourcepos-3.3.7

******sudo nano /var/www/html/ospos/opensourcepos-3.3.7/public/.htaccess 
# if in web root
RewriteRule ^(.*)$ index.php?/$1 [L]

******sudo nano /var/www/html/ospos/opensourcepos-3.3.7/application/config/database.php
'username' => !empty(getenv('MYSQL_USERNAME')) ? getenv('MYSQL_USERNAME') : 'pos',
'password' => !empty(getenv('MYSQL_PASSWORD')) ? getenv('MYSQL_PASSWORD') : 'Ns*******',

******sudo nano /var/www/html/ospos/opensourcepos-3.3.7/application/config/config.php
$config['encryption_key'] = getenv('ENCRYPTION_KEY') ? getenv('ENCRYPTION_KEY') : 'I605*******';

of course , i setup the mysql database and import the ***.sql 

after all the setup, i put 127.0.0.1/public then i got this 
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php



> You don't need to build the project unless you want to setup the dev environment.
> 
> You just download the official release zip file.

**Comment by dennistsc** [comment]
![d](https://user-images.githubusercontent.com/60589279/163857495-e4419e6f-1c38-4429-949b-de0711d82018.JPG)

**Comment by dennistsc** [comment]
i will del the whole thing and do it again.... this is frustrating
