### ISSUE TITLE
using a andoird phone become a scanner 

### ISSUE THREAD

**Issue by dennistsc** [opensourcepos/opensourcepos#3476]
may i know anyone using the phone become a scanner on ospos?

**Comment by hoststatic** [comment]
use barcode scanner keyboard app on android also edit the sales/views/register and remove the "blur jquery function for the item" and also in form input for the item_number add on the class the "search input-group"

**Comment by hoststatic** [comment]
I have tried and it works like a charm, you hosting ospos locally or public?

**Comment by dennistsc** [comment]
> barcode scanner keyboard

could you give me the name of the apps from play store and IOS too? thanks you

**Comment by dennistsc** [comment]
> I have tried and it works like a charm, you hosting ospos locally or public?

locally but will public in the future

**Comment by hoststatic** [comment]
Sure https://play.google.com/store/apps/details?id=com.nikosoft.nikokeyboard
Here there are also premium apps with better support but this is free

**Comment by hoststatic** [comment]
Please don't forget to close the issue

**Comment by dennistsc** [comment]
> Please don't forget to close the issue

thanks for your help but i still didn't know how to do that. do you have some info i can read more? thanks for your help again

**Comment by hoststatic** [comment]
Close with comment when commenting here
