### ISSUE TITLE
ERR_CACHE_MISS on android devices using 3g sim network

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3477]
Hi guys,

I wish you doing well,
I am hosting opsos on an apache webserver and have enabled mod_cache extension.
Previously I had cached also js files because suspected that they may cause problems but sometimes still continues.
What measures should I take to fix this issues, there are times that the employee may take a time to enter items to register and many times it throws this error.

Have you experienced something like this?
I would like to know your thoughts

**Comment by hoststatic** [comment]
Mostly would like to stop caching Sales Register page

**Comment by hoststatic** [comment]
have set it to Sales Controller but still gives me ERR_CACHE_MISS and sometimes back me to login page, 
This happens when I use an scanner keyboard app, and works fine but after article 2-3 it shows this type of problem.
What could be reason of this happening?

**Comment by hoststatic** [comment]
I highly believe this has to do with form_input of searching name of item

**Comment by hoststatic** [comment]
wifi version works ok but when switching to mobile internet it reloads

**Comment by daN4cat** [comment]
Disable the same IP protection in config.php and try again

**Comment by hoststatic** [comment]
It works, but how what was the issue?

**Comment by hoststatic** [comment]
Still get some "Confirm Form Resubmission err_cache_miss" but not as before.
