### ISSUE TITLE
Selling kit as a whole kit, but not individual items

### ISSUE THREAD

**Issue by EHOTnOTACKYH** [opensourcepos/opensourcepos#3479]
Hi, guys!

I'm trying to use your POS for managing stock in a small cafe. So I have a number of ingredients as items. For example:
1. Bun
2. Cutlet
3. Letuce
4. Pickle
5. Cucumber

And I have some finished dishes as kits. For example:
1. Burger (including bun, cutlet, letuce and cucumber)
2. Burger with pickles (including bun, cutlet, letuce and pickles) 
3. Big burger (same as number one, but with two cutlets)

It is not useful for me to have just a list of items in the receipt when I add a dish as a kit. Also it's not useful to have individual items in the reports. But in the stock I still want to have separate items.

As there is no bills of materials or something like that, if I have ingredients as items, but sell the finished dish as a kit, that would solve my problem. Is that possible any way with OSPOS?

Also it would be cool if I can set individual price for kit, not only discount.

**Comment by SteveIreland** [comment]
I believe it is still possible to accomplish most of  your requirements with the kit structure.

However, the individual items are still included in most reports.  The invoice is certainly coded up to fit your requirements.  I do not remember if I applied the same logic to receipts but it would be easy enough to do if it's not already there.  The database supports it.
