### ISSUE TITLE
Import of stock quantity not possible with CSV file

### ISSUE THREAD

**Issue by Victor-Letens** [opensourcepos/opensourcepos#3481]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.7
- OSPOS git commit hash is:  6028bc
- PHP version is: 7.4.28
- MySQL or MariaDB version is: 5.5.5-10.5.15-MariaDB-1:10.5.15+maria~focal
- OS and version is: Linux 5.10.76-linuxkit
- WebServer is: Apache/2.4.53 (Debian)
- Selected language is:  English (Great Britain)
- (If applicable) Docker installation: 4.5.0 (74594)
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I can not import the current amount of stock (quantity) into the database with the template CSV file. I have tried to put it in the 26th field of the CSV file as described on the wiki page, but it does not succeed. I am not able to add custom fields either, which are described for making a book collection system as described on the wiki too

**Comment by hoststatic** [comment]
Have you tried downloading the model from Items and the using that model doc.
I had no issue in the past

**Comment by odiea** [comment]
Custom fields for Items were removed a few years ago. Attributes is now being used.

**Comment by GerardoRod** [comment]
Hello, sorry for jumping in I was trying to bulk update the items but it seems it is not working, I have downloaded the model and try several ways to update the file it did not work. 

Could you please help me to understand which should be the name for each row and what content we should insert in order to update the items.  I even try it in the demo app not working either 

```
ID,Barcode,Item Name,Category,Company Name,Wholesale Price,Retail Price,Quantity,Tax Percent(s),Avatar,,,
1,1,art1,cat,,0,0,5,'-,,"<span class=""glyphicon glyphicon-pushpin""></span>","<span class=""glyphicon glyphicon-list-alt""></span>","<span class=""glyphicon glyphicon-edit""></span>"
2,2,Samsung,Phone,xyz,0,0,3,'-,,"<span class=""glyphicon glyphicon-pushpin""></span>","<span class=""glyphicon glyphicon-list-alt""></span>","<span class=""glyphicon glyphicon-edit""></span>"
3,3,u,uui,,0,0,3,'-,,"<span class=""glyphicon glyphicon-pushpin""></span>","<span class=""glyphicon glyphicon-list-alt""></span>","<span class=""glyphicon glyphicon-edit""></span>"
4,4,erdf,dfsdf,,0,0,3,'-,,"<span class=""glyphicon glyphicon-pushpin""></span>","<span class=""glyphicon glyphicon-list-alt""></span>","<span class=""glyphicon glyphicon-edit""></span>"
5,5,asd,fsdgdfg,,0,0,3,'-,,"<span class=""glyphicon glyphicon-pushpin""></span>","<span class=""glyphicon glyphicon-list-alt""></span>","<span class=""glyphicon glyphicon-edit""></span>"
6,,asd2w,Fruta,,0,0,3,'-,,"<span class=""glyphicon glyphicon-pushpin""></span>","<span class=""glyphicon glyphicon-list-alt""></span>","<span class=""glyphicon glyphicon-edit""></span>"
7,,asde,cat,,0,0,5,'-,,"<span class=""glyphicon glyphicon-pushpin""></span>","<span class=""glyphicon glyphicon-list-alt""></span>","<span class=""glyphicon glyphicon-edit""></span>"
```


I read the wiki and I did all as suggested, not working =(

**Comment by jekkos** [comment]
@GerardoRod you should use the csv template for this instead. It is generated from the UI there should be a button to download it.

**Comment by GerardoRod** [comment]
@jekkos I did that, not working

**Comment by hoststatic** [comment]
check the MySQL table first, and check also if your data is formatted correctly in the CSV file.
It happened to me many times when for certain characters not being recognised in the name of product or similarly like single quotes

**Comment by hoststatic** [comment]
Set live query log and see what happens.
SET general_log = 1;

**Comment by bubblesqueak24** [comment]
same problem
