### ISSUE TITLE
Item Kit Fixed Discount Retail price is not appearing in the sales mode correctly

### ISSUE THREAD

**Issue by surprised-potato** [opensourcepos/opensourcepos#3482]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is:  3.3.6 [f3e41a]
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Item Kit Price fixed discount function is not working properly. In the Kit item section the price displays properly after discount is applied however when used in the sales section the fixed discount is not applied properly.

![Screenshot 2022-04-22 012848](https://user-images.githubusercontent.com/89435318/164518690-d0b7ae16-0f65-46a1-b5dd-2bd4d7debed0.png)
![Screenshot 2022-04-22 012946](https://user-images.githubusercontent.com/89435318/164518706-eeace3e9-7614-4058-aaff-477130ed7124.png)

**Comment by hoststatic** [comment]
You discount 100% of the price, are you trying to discount in % ?
If so make sure to check the % in the item kit because your discounting value which is 100% of the value of the price.
if you want to give free 1 from 12 items. you other calculation like 8.3%?

**Comment by surprised-potato** [comment]
Hi! yes that is the current workaround as fixed discount is applying to each individual item in the kit. Percent discount is working properly

**Comment by hoststatic** [comment]
I'm glad it worked, don't forget to close the issue
