### ISSUE TITLE
Error in clean installation 3.3.6

### ISSUE THREAD

**Issue by truchosky** [opensourcepos/opensourcepos#3483]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: 8
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

quite simple, I did a fresh/new ospos installation (latest version), I imported database.sql file and at login I get the message "A database migration to 3.3.6 will start after login." after that I get 500 http error and I cant login, if I refresh web I see again the login with database migration message, at this moment what ever person who install latest ospos will have this issue

![image](https://user-images.githubusercontent.com/9977546/164787349-bf08635e-cce3-4dec-96ee-4b913a51873e.png)

Error log shows:
`2022/04/22 20:20:12 [error] 2931901#2931901: *4793 FastCGI sent in stderr: "PHP message: Migrating to 3.1.1 (file: /home/runcloud/webapps/pos-336/pos/application/migrations/sqlscripts/3.0.2_to_3.1.1.sql)PHP message: error: 1060PHP message: error: Duplicate column name 'stock_type'PHP message: error: 1060PHP message: error: Duplicate column name 'item_id'PHP message: error: 1060PHP message: error: Duplicate column name 'kit_sequence'PHP message: error: 1060PHP message: error: Duplicate column name 'print_option'PHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended_items' doesn't existPHP message: error: 1054PHP message: error: Unknown column 'pic_id' in 'ospos_items'PHP message: error: 1062PHP message: error: Duplicate entry '1' for key 'ospos_dinner_tables.PRIMARY'PHP message: error: 1060PHP message: error: Duplicate column name 'dinner_table_id'PHP message: error: 1061PHP message: error: Duplicate key name 'dinner_table_id'PHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended' doesn't existPHP message: error: 1062PHP message: error: Duplicate entry 'date_or_time_format' for key 'ospos_app_config.PRIMARY'PHP message: error: 1062PHP message: error: Duplicate entry '1' for key 'ospos_customers_packages.PRIMARY'PHP message: error: 1060PHP message: error: Duplicate column name 'package_id'PHP message: error: 1062PHP message: error: Duplicate entry 'customer_reward_enable' for key 'ospos_app_config.PRIMARY'PHP message: error: 1050PHP message: error: Table 'ospos_sales_taxes' already existsPHP message: error: 1060PHP message: error: Duplicate column name 'quote_number'PHP message: error: 1060PHP message: error: Duplicate column name 'tax_type'PHP message: error: 1060PHP message: error: Duplicate column name 'sales_tax_code'PHP message: error: 1062PHP message: error: Duplicate entry 'cash_decimals' for key 'ospos_app_config.PRIMARY'PHP message: error: 1061PHP message: error: Duplicate key name 'email'PHP message: error: 1062PHP message: error: Duplicate entry 'financial_year' for key 'ospos_app_config.PRIMARY'PHP message: error: 1062PHP message: error: Duplicate entry 'giftcard_number' for key 'ospos_app_config.PRIMARY'PHP message: error: 1062PHP message: error: Duplicate entry 'receipt_show_company_name' for key 'ospos_app_config.PRIMARY'PHP message: error: 1062PHP message: error: Duplicate entry 'receipt_font_size' for key 'ospos_app_config.PRIMARY'PHP message: error: 1061PHP message: error: Duplicate key name 'person_id'PHP message: error: 1061PHP message: error: Duplicate key name 'sale_id'PHP message: error: 1061PHP message: error: Duplicate key name 'package_id'PHP message: error: 1062PHP message: error: Duplicate entry 'gcaptcha_enable' for key 'ospos_app_config.PRIMARY'PHP message: error: 1062PHP message: error: Duplicate entry 'barcode_formats' for key 'ospos_app_config.PRIMARY'PHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended_items' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended_payments' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended_items_taxes' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended_payments' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended_items_taxes' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended_items_taxes' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended_items' doesn't existPHP message: error: 1146PHP message: error: Table 'pos336demo.ospos_sales_suspended_items' doesn't existPHP message: error: 1146PHP message: error: Table 'pos`

`2022/04/22 20:20:13 [error] 2931901#2931901: *4793 FastCGI sent in stderr: "e/runcloud/webapps/pos-336/pos/application/migrations/sqlscripts/3.3.2_paymentdatefix.sql)PHP message: Migrated to paymentdatefixPHP message: Migrating to saleschangeprice (file: /home/runcloud/webapps/pos-336/pos/application/migrations/sqlscripts/3.3.2_saleschangeprice.sql)PHP message: Migrated to saleschangepricePHP message: Migrating modify_attr_links_constraintPHP message: Migrating to constraint (file: /home/runcloud/webapps/pos-336/pos/application/migrations/sqlscripts/3.3.2_modify_attr_links_constraint.sql)PHP message: Migrated to constraintPHP message: Migrating modify_attr_links_constraintPHP message: Migrating add_item_kit_numberPHP message: Migrating to number (file: /home/runcloud/webapps/pos-336/pos/application/migrations/sqlscripts/3.3.3_add_kits_item_number.sql)PHP message: Migrated to numberPHP message: Migrating add_item_kit_numberPHP message: Migrating modify_session_datatypePHP message: Migrating to datatype (file: /home/runcloud/webapps/pos-336/pos/application/migrations/sqlscripts/3.3.4_modify_session_datatype.sql)PHP message: Migrated to datatypePHP message: Migrating modify_session_datatypePHP message: Migrating database_optimizations" while reading response header from upstream, client: 201.188.86.44, server: app-pos-336.s8dygeqtxf-jqp3vjj5x350.p.runcloud.link, request: "POST /pos/public/login HTTP/1.1", upstream: "fastcgi://unix:/var/run/pos-336.sock:", host: "app-pos-336.s8dygeqtxf-jqp3vjj5x350.p.runcloud.link", referrer: "http://app-pos-336.s8dygeqtxf-jqp3vjj5x350.p.runcloud.link/pos/public/"`

**Comment by hoststatic** [comment]
Are you creating duplicate columns. Try to drop and create from beginning the database, I suspect I suspect error is linked with duplication of data on db

**Comment by truchosky** [comment]
I think the issue is MySQL 8

**Comment by hoststatic** [comment]
why not use mariadb, its same as mysql but better, just saying I have version 10.4.x and it works flawlesly

**Comment by jekkos** [comment]
MySQL 8 is not supported (or at least not really tested)

**Comment by jekkos** [comment]
I hope you were able to resolve this issue. But if you use a recommended version it should be fine.
