### ISSUE TITLE
Hi'I'm from Argentina, And I've just found the project....

### ISSUE THREAD

**Issue by ferchuchin** [opensourcepos/opensourcepos#3484]
How does the payment gateways work?
Do I need to manually state that the customer payed?
Is there any way to work with payment gateways API ? Here MercadoPago is one of the most used....
but what I want is to prevent any manual payment transaction....(well cash is obviously manual)

**Comment by hoststatic** [comment]
Like @truchosky mentioned try demo also read the wiki.
