### ISSUE TITLE
Ospos_sessions heavy impact and slow

### ISSUE THREAD

**Issue by truchosky** [opensourcepos/opensourcepos#3485]
I have ospos 3.3.0, no matter mysql version, php version or hardware.

Yesterday I noticed a really heavy impact in the general ospos performance, 1 year of use with 3 users, looking in detail I found ospos_sessions table with 450 mb of data, I empty the table and all worked really good again, what this table saves?

**Comment by hoststatic** [comment]
it logs the actions that employees does, like the ip date time, and describe the action that was done. (session, ip, permissions, sales, item properties, payments etc) 
It is very helpful in my opinion.
I have not noticed any performance issues what hardware are you running on?

**Comment by truchosky** [comment]
How much MB has your ospos_sessions table?, Mine has 450, Is un debían 9 with 8 GB RAM and 2 cpu, do droplet

**Comment by hoststatic** [comment]
dude 450mb its a lot of data, how much sales you made in a day?

**Comment by truchosky** [comment]
700-800

**Comment by hoststatic** [comment]
If ospos_sessions really affects the performance what I would do is dump the table every x time to a backup location and then clean it.
Perform a cron job so it does this automatically

**Comment by daN4cat** [comment]
Not sure why you have many sessions, do you login/logout constantly? Set a session to last a working day if it happens automatically. Also if your IP address changes constantly that will cause new sessions.

**Comment by truchosky** [comment]
I did some tests, first I dumped table, then only with 1 user I did some sales, checked a few reports and then I log out, all that in about 10 minutes, after that I checked tablet and it had like 6-7 rows of data, is that normal?, same ip, only 1 login

**Comment by daN4cat** [comment]
I will need to check when I have time but I don't remember something like that.

**Comment by izeblood** [comment]
Item Module won't open....i experience this for about 3 years of transaction ...

**Comment by daN4cat** [comment]
I have 10 years of transactions and works fine. Not sure why is different in my case.

**Comment by hoststatic** [comment]
@izeblood what size in Mb is your ospos_session table?
I have experienced something similar and the error it was same article was submitted twice with same item_number and one time with unescaped characters.
Fixing those items. made my list of item showing again,

**Comment by hoststatic** [comment]
Mine is ospos_sessions ~33Mb, ospos_sales 2.5Mb, ospos_inventory ~9.6Mb.

**Comment by hoststatic** [comment]
what about keeping data in microsoft sql server instead of mysql, also latest version runs also on linux machines and it offers better performance I guess
