### ISSUE TITLE
Feature Request: Search FIlter in Summary Reports Items and Suppliers

### ISSUE THREAD

**Issue by surprised-potato** [opensourcepos/opensourcepos#3491]
### New Feature
I'm loving OSPOS and I thank you all for your great work!

It would be nice if there was a search textbox inside Summary reports Items. It would be amazing if I could search for the items with their item names and filter by supplier.

**Comment by chunter2** [comment]
I think you just want the last comment of this issue https://github.com/opensourcepos/opensourcepos/issues/3386

@jekkos Any chance this could be added to the code?

**Comment by surprised-potato** [comment]
Thanks that what I was asking for. I got it to work as well.
