### ISSUE TITLE
Add Employee column to Daily Sales report

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3499]
I thought this would be something easy to add but it seems the daily sales report in the sales module is different than other reports.  Could someone point me in the right direction of where to look?  I see a search function in application/models/Sales.php but it doesn't seem to be obvious to me where I should add the code.  

Thanks

**Comment by odiea** [comment]
Took me a while to find out how I did this. In Tabular helper add the following lines.
array('employee_name' => $CI->lang->line('sales_employee')), around line 56
'employee_name' => $sale->employee_name, around line 97. Then add the following employee line from the following image You will need to add from select and the lower joins. Hope this helps.

![2022-05-04 15_22_28-C__wamp64_www_opensourcepos_application_models_Sale php - Notepad++](https://user-images.githubusercontent.com/10962177/166828024-2257d3fa-b6a7-453b-bf2e-11bbed2dbfd9.png)

**Comment by chunter2** [comment]
@odiea I tried this out and it works great.  Thanks for the help.  One thing I noticed is the search box doesn't seem to work for employees.  I tested it out on customers and that works fine.

**Comment by odiea** [comment]
You will have to add that info yourself.
