### ISSUE TITLE
Getting a blank page when accessing localhost/html/pos/public

### ISSUE THREAD

**Issue by MykelCipher** [opensourcepos/opensourcepos#3500]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is:  3.3.1
- OSPOS git commit hash is: c786d4
- PHP version is: 7.4.27
- MySQL or MariaDB version is: MariaDB 10.4.22
- OS and version is: Windows 10
- WebServer is: Apache/2.6.52
- Selected language is: English
- (If applicable) Docker installation: No
- (If applicable) Installation package for the LAMP/LEMP stack is: XAMPP

### Issue

I followed the installation guide on GitHub to enabled all needed PHP extensions and set up my database.
Whenever I try accessing the public dir on my browser (Firefox) I get a blank page. I saw some old issues saying it might be .htaccess file but none of them actually tell how to fix it.

My error log is 

ERROR - 2022-05-08 08:01:20 --> Severity: error --> Exception: Session: Configured driver 'database' was not found. Aborting.

Please I need a solution.

**Comment by odiea** [comment]
Try localhost/pos/public and see what you get plus that version is quite outdated.

**Comment by MykelCipher** [comment]
Localhost/pos/public is given an error message
NOT FOUND
The requested URL was not found on this server

**Comment by odiea** [comment]
Try the following version and see if there are any changes.
https://github.com/opensourcepos/opensourcepos/archive/refs/tags/3.3.7.zip

**Comment by MykelCipher** [comment]
Okay, I will.
