### ISSUE TITLE
How to show quantity is sales search bar in ospos

### ISSUE THREAD

**Issue by zaydmk** [opensourcepos/opensourcepos#3503]
Hi

How do I show items and quantities in a search bar (Sales Tab) at the same time?

<img width="551" alt="ospos" src="https://user-images.githubusercontent.com/105447252/168120604-5828f620-ac3b-4aac-9ba4-57861f0c4d32.PNG">

**Comment by nukerj** [comment]
@zaydmk i have this function. Contactame and i can help You witch this. Telegram @jvilchez

**Comment by WebShells** [comment]
Can we close this ?

**Comment by nukerj** [comment]
yes you can @WebShells 
a long time ago i helped @zaydmk with this

**Comment by nukerj** [comment]
Yes
