### ISSUE TITLE
database error on reporting

### ISSUE THREAD

**Issue by ChrysostomosPogiatzis** [opensourcepos/opensourcepos#3504]
![Screenshot from 2022-05-13 10-42-04](https://user-images.githubusercontent.com/33746884/168235508-3b824b85-4db3-425d-a6b0-fb5aeb0689e7.png)

**Comment by daN4cat** [comment]
It looks like you tampered your database dropping tables or renaming them.
Not sure if even renamed the database itself not updating ospos config file but there would be another message if it's the case.

When you go to Suppliers view, do you get an error?

**Comment by ChrysostomosPogiatzis** [comment]
Its from the website demo

**Comment by odiea** [comment]
Thanks for the Issue report. Demo is not working for Items.
