### ISSUE TITLE
No option to remove barcode from the receipt

### ISSUE THREAD

**Issue by MalinrRuwan** [opensourcepos/opensourcepos#3506]
Please add an option to remove the barcode from the receipt and please look into the bug where the user can't remove the company logo after it was added. When I click remove and submit it re-appers after a refresh. The same bug was identified in your demo site.

**Comment by hoststatic** [comment]
You could achieve that by editing the file receipt_short.php or receipt_default.php  on /application/views/sales/
and removing the barcode div


```
<div id="barcode">
		<img src='data:image/png;base64,<?php echo $barcode; ?>' /><br>
		<?php echo $sale_id; ?>
</div>
```

**Comment by MalinrRuwan** [comment]
Thank you so mucb
