### ISSUE TITLE
3.3.6 on Accuwebhosting shows page in blank after login

### ISSUE THREAD

**Issue by Arielako** [opensourcepos/opensourcepos#3507]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is: 
- PHP version is: 7.4.29
- MySQL or MariaDB version is: 8.0.27
- OS and version is: 
- WebServer is: accuwebhosting (linux server account)
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I've follow the installation instructions (INSTALL SCRIPT), After login application hows page in blank. I already followed the known issues setting up Apache and php recommendations, enabling all recommended modules (except curl which is not available for enable/disable - See the image). Also activate application and database logs to help me find out the issue.
![Screen Shot 2022-05-16 at 5 13 53](https://user-images.githubusercontent.com/30378224/168571099-10c7c2dd-1460-4db5-b9f2-f843502f1287.png)
![Screen Shot 2022-05-16 at 5 13 25](https://user-images.githubusercontent.com/30378224/168571162-e25ce2b0-34dd-44f1-bf9c-f5cf1892f080.png)

Let me show the logs
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

...
DEBUG - 2022-05-16 06:09:15 --> Migration class already loaded. Second attempt ignored.
DEBUG - 2022-05-16 06:09:15 --> Migrating up from version 20210103000000 to version 20210422000000
ERROR - 2022-05-16 06:09:15 --> Query error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pawiskid_pos.ospos_attribute_values.attribute_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - Invalid query: SELECT `attribute_decimal`, `attribute_id`
FROM `ospos_attribute_values`
GROUP BY `attribute_decimal`
HAVING COUNT(attribute_decimal) > 1
ERROR - 2022-05-16 06:09:15 --> Severity: error --> Exception: Call to a member function result_array() on bool /home/pawiskid/public_html/pos/application/migrations/20210422000000_database_optimizations.php 85

**Comment by odiea** [comment]
Try and disable sql_mode=only_full_group_by in mysql.

**Comment by Arielako** [comment]
that what they said, It is not possible to disable only_full_group_by in MySQL as you are using our shared hosting service. We do not offer the MariaDB database with our Linux shared hosting plan.

If you want to use the MariaDB database you can go with our Windows shared hosting plans.

Regards,

**Comment by Arielako** [comment]
so I'll try to upgrade my plan to windows shared hosting and switch to Mariadb, let me back when its done.

**Comment by Arielako** [comment]
They reply, if I move to this plan lost Apache and this will not work with this application.  Any other option do you recommends?

**Comment by Arielako** [comment]
Do you recommend another hosting who can work with this apps?  Hostinger or Hostgator could be an option?

**Comment by jekkos** [comment]
Digitalocean, check install instructions for that one

**Comment by Arielako** [comment]
ok, thnks for advice, let me have a look @jekkos.  As I briefly look they provide VMs, Kubernetes and PAAS.

**Comment by hoststatic** [comment]
don't forget to close the issue

**Comment by Arielako** [comment]
Still looking for options VPS plans are more expensive. Try to get share hosting option first.  I saw some share hosting providers who are support OSPOS, will determine this week what option and follow up the installation. Will keep open the incident, in case resolve I want to share the experience to help someone else with similar issue.

**Comment by Arielako** [comment]
I found a share hosting, low cost, a2hosting.com.  Already completed the process to install 3.3.6 in sub domain without any additional configuration more than what INSTALL file described.  Application worked without any problem.

Thnks so much for your follow ups, hopefully this can help any other with similar issue.  I'll start working and learning about this application, looks really complete!!!!
