### ISSUE TITLE
error at the very beginning of the installation in docker

### ISSUE THREAD

**Issue by privateer00** [opensourcepos/opensourcepos#3509]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.7
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation:  20.10.16
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi,
pretty new here. I'm trying to install ospos on my docker server. I downloaded last release from /releases, unzipped but when i run docker-compose build i get this:

 ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.mysql: 'volumes_from'

Andrea

**Comment by hoststatic** [comment]
there was something similar, but you should search the issues, also alternatively you could download it locally and deploy it.

**Comment by jekkos** [comment]
What version of docker do you use? The setup does work on CI so it's probably outdated

**Comment by privateer00** [comment]
was 20.10.16, maybe i can try tomorrow since it has been updated..

> What version of docker do you use? The setup does work on CI so it's probably outdated

**Comment by privateer00** [comment]
with updated version the contaner starts but then the interface isn't responding: at login i insert credentials and nothing happens, if i refresh the page i'm in but can't do anything
