### ISSUE TITLE
 Sales Payment Dates don't take Timezone into account

### ISSUE THREAD

**Issue by CoinBR** [opensourcepos/opensourcepos#3510]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is: 
- PHP version is:  The one on the official docker image
- MySQL or MariaDB version is: The one on the official docker image
- OS and version is: Debian 11
- WebServer is: The one on the official docker image
- Selected language is: 
- (If applicable) Docker installation: Yes
- (If applicable) Installation package for the LAMP/LEMP stack is: No

### Issue / Bug  / Question / New Feature
---

Hello =)

## sales payment dates don't take timezone into account
- I'm on the  GMT-3 timezone:
![image](https://user-images.githubusercontent.com/7809913/169622444-788f31a1-605d-4a2d-9e30-6a23ed7be5ac.png)

- My payments are always 3 hours ahead the related sale
![image](https://user-images.githubusercontent.com/7809913/169622544-f2d7a4c7-9320-4218-a412-f0859ad68a27.png)

So, this is probably due to the payment_module ignoring the timezone.
I could try and look at it myself, but I'm still trying to find time  to create an alternative way of handling multiple packages (we need all the stock to be held on the `min sale item`)

So, for now, I'll have to leave this issue here =/

**Comment by hoststatic** [comment]
I have no issues at all with this, have you checked your webserver date/time setup also take a look at the time on the client device (computer/mobile whatever) that you're logging in ospos

**Comment by CoinBR** [comment]
Sorry for the very late reply, I have been very overloaded.

In fact, the timezone on the server is different:
![image](https://user-images.githubusercontent.com/7809913/171495807-b16075b1-925b-49e6-9ade-d532dd3a3c50.png)

I cannot change it now, but I will do asap, and report here.

Still,  maybe is not ideal to have the sale and its payment on 2 different times, due to a timezone difference between the user computer and the server, or a difference between the project configuration and the actual server timezone.

**Comment by hoststatic** [comment]
I had similar issue, set both same and it works

**Comment by hoststatic** [comment]
Don't forget to close the issue if you save the problem

**Comment by hoststatic** [comment]
I'm glad you solved it @CoinBR

**Comment by CoinBR** [comment]
Sorry but I did not solve it. The problem persists.
When I find time, I may try to investigate the code and make to make the timezone more consistent on those 2 different actions.
But there are features (on this project) that are way more urgent for me to work on

**Comment by hoststatic** [comment]
change date/time on server,
check date/time on client that access the ospos 
That's what worked for me

**Comment by WebShells** [comment]
@CoinBR was your issue solved ?

**Comment by CoinBR** [comment]
As I mentioned, fixing the timezone both on server and client was not enough to fix the problem.
This don't actually impact me anymore, since I started grabbing just the right date, and ignore the wrong one.
If that's something the project maintainers think is not worth fixing, I'm fine closing the issue.
Just felt it would be valuable to keep track of the problem here

**Comment by jekkos** [comment]
@CoinBR What do you mean exactly with 'grabbing the right date'? 
In case the timezone settings on the browser system is different then the one on the php side, you might indeed see those differences.

**Comment by CoinBR** [comment]
Hey @jekkos ,

Let me explain the situation on the last tests I did:

- Timezones are the same (GMT-3) on:
  - Server OS
  - Client OS
  - OpensourcePOS configuration panel 
- After finishing a sale:
  - The sale datetime is registered on the database, using the `GMT-3` timezone
  - the **payment** datetime for this sale, uses the `GMT 0` timezone

In other words:
- We have 2 different datetimes related to the same operation. 
- One takes into account the timezone, and the other is not.
- Problem persists even after correctly configuring the timezones on client, server, and ospos

As I mentioned, this does not impact me anymore.I adjusted my SQL query to fix that discrepancy, so my manual report is just fine. I would be ok closing this ticket, if you find appropriate =)
