### ISSUE TITLE
Receive Report for suppliers

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3511]
This kind of report is helpful because it knows what supplies you have and from whom you bought them,
Some people who have big warehouses use suppliers in different ways to sell their stuff, but vice versa a report of this kind would be great.
What would work is to build something like this based on detailed_receivings

Something like
....
from ospos_receivings as recv
inner join ospos_suppliers as supp on recv.supplier_id = supp.person_id;

**Comment by hoststatic** [comment]
Created a custom report 
using ospos_receivings
joined ospos_suppliers, ospos_receivings_items and ospos_items. If you're interested let me know

**Comment by jekkos** [comment]
Sure PR is welcomed

**Comment by hoststatic** [comment]
@jekkos The reports work great, the only thing that is an issue is that Inner Join not working good or is not implemented well by me,
I would like to show data only for suppliers that are in the supplier's list (ospos_suppliers), but it's showing also requisition of the employees. How 
Any idea?


```
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');


class Inventory_supplier extends CI_Model 
{
	public function Columns()
	{
		return array(
			array('recv_time' => $this->lang->line('reports_date')),
			array('recv_name' => $this->lang->line('reports_item_name')),
			array('quantity' => $this->lang->line('reports_quantity_buy')),
			array('cost_price' => $this->lang->line('reports_unit_buy')),
			array('total' => $this->lang->line('reports_total')),
			//array('item_number' => $this->lang->line('reports_item_number')),
			//array('quantity' => $this->lang->line('reports_quantity')),
			array('company_name' => $this->lang->line('reports_supplier')));
			
			//array('reorder_level' => $this->lang->line('reports_reorder_level')),
			//array('location_name' => $this->lang->line('reports_stock_location')));
	}
	
	
	public function Total(array $inputs)
	{
		$this->db->select('recv.receiving_time as recv_time,
		items.name as recv_name,
		recv_items.quantity_purchased as quantity,
		recv_items.item_cost_price as cost_price,
		(recv_items.quantity_purchased * recv_items.item_cost_price) as total,
		supp.company_name as company_name');
		$this->db->from('receivings as recv');
		$this->db->join('suppliers as supp', 'recv.supplier_id = supp.person_id'                                                                                        );
		$this->db->join('receivings_items as recv_items', 'recv.receiving_id = recv_items.receiving_id', 'left');
		$this->db->join('items as items', 'recv_items.item_id = items.item_id', 'left');
		$this->db->where('recv_items.quantity_purchased >', '0');
		if(empty($this->config->item('date_or_time_format')))
		{
			$this->db->where('DATE(recv.receiving_time) BETWEEN ' . $this->db->escape($inputs['start_date']) . ' AND ' . $this->db->escape($inputs['end_date']));
		}
		else
		{
			$this->db->where('recv.receiving_time BETWEEN ' . $this->db->escape(rawurldecode($inputs['start_date'])) . ' AND ' . $this->db->escape(rawurldecode($inputs['end_date'])));
		}

		$this->db->order_by('recv_time','desc');
		//$this->db->group_by('supp.person_id');
		return $this->db->get()->result_array();
		
		

	}	

}
?>

```

**Comment by nyenius** [comment]
For me I created separate script that using Ospos database (incl. login) to generate more custom reports for my needs. I have two stock location: warehouse (Gudang) and Display.

This is receiving reports that I made:
![image](https://user-images.githubusercontent.com/613132/170709632-ddfebfe8-760a-454a-a1bb-924de1fd8138.png)

And this is stock report (2 warehouses in two columns side-by-side):
![image](https://user-images.githubusercontent.com/613132/170710267-df9afd82-6555-4634-947a-1efe62f83681.png)

**Comment by hoststatic** [comment]
It seems like when you do a requisition from stock_location a to b, 
if 
employee a has stock_location a
employee b has stock_location b
In ospos_suppliers they get registered with custom supplier_id different than (ospos_employee person_id)
So what I did is create an array with the supplier_id of employees and perform the query,
It works like a charm


$id_employee = array(11878, 11879, 11880, 11881, 11882, 11883, 12777);
$this->db->where_not_in('recv.supplier_id', $id_employee);


It would be great if you'd like to share the script
