### ISSUE TITLE
Hiding fields in sales / cart section 

### ISSUE THREAD

**Issue by moletelier** [opensourcepos/opensourcepos#3513]
### Question 

Hi, does anyone knows the route or file where it contains the structure of the items in cart? I already could hide some fields of the headers with the register.php file in views/sales, but I want to hide some fields of the item itself like the checkbook of type of discount, the price value, etc.

Thanks!!!

Here is a photo of the section I refer:

<img width="835" alt="Captura de Pantalla 2022-05-23 a la(s) 12 29 21" src="https://user-images.githubusercontent.com/62162604/169866047-526f69d4-6fc4-46a8-ac2a-a69e7ae60b98.png">

**Comment by hoststatic** [comment]
comment the interested fields you would like to hide on sales_table_100 in application/views/sale/register.php
