### ISSUE TITLE
Company Logo doesn't showing up

### ISSUE THREAD

**Issue by nyenius** [opensourcepos/opensourcepos#3515]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- x[] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is:  3.3.6
- OSPOS git commit hash is: f3e41a
- PHP version is: 7.4.29
- MySQL or MariaDB version is: 5.7.38-log - MySQL Community Server (GPL)
- OS and version is: Linux kernel 3.10.0-962.3.2.lve1.5.66.el7.x86_64
- WebServer is: Apache 2.4.53
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

![image](https://user-images.githubusercontent.com/613132/170684589-462d06de-7226-4f33-a065-0bcb9db5747c.png)

My company logo image didn't show up anywhere, after upgrade to 3.3.6. The above message are showing when I inspect in browser. Could some one help with solution?

**Comment by odiea** [comment]
Fill out the requested info.

**Comment by nyenius** [comment]
Very sorry, I've updated my info, please reopen the issue

**Comment by odiea** [comment]
You can try to see if the following link will help you out.
https://simonhearne.com/2022/caching-header-best-practices/
