### ISSUE TITLE
Attributes can't be added to items using CSV import

### ISSUE THREAD

**Issue by JTaal** [opensourcepos/opensourcepos#3516]
Currently I'm using version 3.3.6
Attributes aren't imported whenever I do so. After adding the attributes and configuring them to accept text, the CSV import file was nicely updated with three extra columns. I've added all the necessary information into the cells, however the importer simply ignores the added columns. It leaves the items with an unchecked attribute box and no additional info. On the latest test build it did seem to partially work, however still one column is simply ignored.

Can't we just use the custom columns that worked fine in previous versions?

Additionally with CSV import in general, it is hard to determine what is the cause of failure, because there is no reason stated for said errors.

**Comment by jekkos** [comment]
Can you describe a bit more in detail what type of attribute you are trying to import and how your data looks ?

Can't tell from the top of my head but I suppose there is some limitations depending on the definition types that the import will accept. Ofc it might have been more helpful to have this in a clear error message instead.

**Comment by vishal262** [comment]
> been

Can you please let me know, How can I update items with import csv function?

**Comment by vishal262** [comment]
> Can you describe a bit more in detail what type of attribute you are trying to import and how your data looks ?
> 
> Can't tell from the top of my head but I suppose there is some limitations depending on the definition types that the import will accept. Ofc it might have been more helpful to have this in a clear error message instead.

**Can you please let me know, How can I update items with import csv function?**

**Comment by JTaal** [comment]
> > Can you describe a bit more in detail what type of attribute you are trying to import and how your data looks ?
> > Can't tell from the top of my head but I suppose there is some limitations depending on the definition types that the import will accept. Ofc it might have been more helpful to have this in a clear error message instead.
> 
> **Can you please let me know, How can I update items with import csv function?**

I believe items are updated based on ID number. So, if the ID number remains the same in your .csv, then you should be able to update the items by changing the other columns.

**Comment by vishal262** [comment]
> > > Can you describe a bit more in detail what type of attribute you are trying to import and how your data looks ?
> > > Can't tell from the top of my head but I suppose there is some limitations depending on the definition types that the import will accept. Ofc it might have been more helpful to have this in a clear error message instead.
> > 
> > 
> > **Can you please let me know, How can I update items with import csv function?**
> 
> I believe items are updated based on ID number. So, if the ID number remains the same in your .csv, then you should be able to update the items by changing the other columns.

it doesn't works properly . I have changes in script in items controller. Now it's working fine for me

**Comment by jekkos** [comment]
> > > > Can you describe a bit more in detail what type of attribute you are trying to import and how your data looks ?
> > > > Can't tell from the top of my head but I suppose there is some limitations depending on the definition types that the import will accept. Ofc it might have been more helpful to have this in a clear error message instead.
> > > 
> > > 
> > > **Can you please let me know, How can I update items with import csv function?**
> > 
> > 
> > I believe items are updated based on ID number. So, if the ID number remains the same in your .csv, then you should be able to update the items by changing the other columns.
> 
> it doesn't works properly . I have changes in script in items controller. Now it's working fine for me

Hi could you elaborate which changes you did to make it work?

**Comment by objecttothis** [comment]
There hasn't been activity on this for some time.  This is working on the demo site (3.3.9) now.
