### ISSUE TITLE
database migration issue after first login: An uncaught Exception was encountered Type: Error

### ISSUE THREAD

**Issue by davidporemba** [opensourcepos/opensourcepos#3518]
### Installation information

- OSPOS version is: 3.3.7
- OSPOS git commit hash is: 3.3.7
- PHP version is: 7.2
- MySQL or MariaDB version is:  MySQL 5.7.38
- OS and version is:  Ubuntu 18.04 LTS
- WebServer is:  Apache 2
- Selected language is: 
- (If applicable) Docker installation: n/a
- (If applicable) Installation package for the LAMP/LEMP stack is: n/a

### Issue / Bug  / Question / New Feature

After first login:

An uncaught Exception was encountered
Type: Error

Message: Call to a member function result_array() on boolean

Filename: /var/www/html/nwms/application/migrations/20210422000000_database_optimizations.php

Line Number: 85

Backtrace:

File: /var/www/html/nwms/application/migrations/20210422000000_database_optimizations.php
Line: 17
Function: migrate_duplicate_attribute_values

File: /var/www/html/nwms/application/controllers/Login.php
Line: 43
Function: latest

File: /var/www/html/nwms/application/controllers/Login.php
Line: 19
Function: run

File: /var/www/html/nwms/public/index.php
Line: 315
Function: require_once

**Comment by davidporemba** [comment]
Clean install

**Comment by hoststatic** [comment]
Why not try version 3.6 of ospos?

**Comment by jekkos** [comment]
I expect it to bea php version issue as the db upgrade does work with php7.4 and mariadb. Could you try php 7.3?

**Comment by jekkos** [comment]
Sorry after some thought I think it's probably MySQL. Some query returns false instead of a result. Can you try run https://stackoverflow.com/questions/23921117/disable-only-full-group-by?

Maybe we should execute this ourselves when we detect MySQL to make it transparant

**Comment by WebShells** [comment]
@jekkos was this solved ?
