### ISSUE TITLE
opensourcepos 3.3.7 does not contain the opensourcepos.master.zip file.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3519]
![2022-06-01 16_30_58-Window](https://user-images.githubusercontent.com/10962177/171512621-bb911f90-843f-492e-ada4-dd89e799d1b1.png)

**Comment by jekkos** [comment]
Indeed I switched to tarballs some time ago, might not be so convenient for most users. I'll try to tweak the build config such that at least the release is a zipfile again.

**Comment by WebShells** [comment]
Solved...
