### ISSUE TITLE
Not showing any images

### ISSUE THREAD

**Issue by mrtechive** [opensourcepos/opensourcepos#3520]
OSPOS Installation Info: 3.3.6 - f3e41a
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: LiteSpeed
.PHP Version: 7.4.29
.DB Version: 5.7.38
.Server Port: 443
.OS: Linux 3.10.0-962.3.2.lve1.5.38.el7.x86_64

File Permissions:
» [application/logs:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads/item_pics:] - 0750 | Writable ✓ | Security Check Passed ✓
» [import_customers.csv:] - 0660 | Readable ✓ | Security Check Passed ✓

No security/vulnerability risks.

Asia/Dhaka

I am changing the logo with the same name but the logo is not showing.

**Comment by jekkos** [comment]
Can you check if the uploaded file on your server is the correct one?
