### ISSUE TITLE
Install error, and I know it is my fault...

### ISSUE THREAD

**Issue by viragni** [opensourcepos/opensourcepos#3521]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.7
- OSPOS git commit hash is: no idea
- PHP version is: 7.4
- MySQL or MariaDB version is: 10.3.34
- OS and version is: Ubuntu 20

- WebServer is: Apache2
- Selected language is: English
- (If applicable) Docker installation: no
- (If applicable) Installation package for the LAMP/LEMP stack is: from APT

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I followed these steps in my install:

**Start with vanilla Ubuntu Image**

1. Install MariaDB with apt and related packages 
2. Run secure install script
3. root PW : ***********
4. Install Apache2
5. Install 
php7.4-curl
php7.4-mysql
php7.4-gd
php7.4-intl
php7.4-bcmath

6. a2enmod rewrite
7. systemctl restart apache2
8. sudo apt install libapache2-mod-php
9. sudo a2enmod php 

10. CD  /var/www/html
11. Downloaded https://github.com/opensourcepos/opensourcepos/releases/download/3.3.7/opensourcepos.3.3.7.4f3226.tgz
12. Extracted all files to /var/www/html
13. executed sudo mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
14. Executed sudo mysql -u admin -ppointofsale -D ospos < /var/www/html/database/database.sql

I am able to run PHP, as I ran a test file for PHP info in public directory. This is included as OPOSPHPTest.pdf. The page I see when I browse to public is attached as OPOSPAgeAsSeen.pdf.

**Comment by viragni** [comment]
[OPOSPHPTest.pdf](https://github.com/opensourcepos/opensourcepos/files/8862663/OPOSPHPTest.pdf)
[OPOSPAgeAsSeen.pdf](https://github.com/opensourcepos/opensourcepos/files/8862670/OPOSPAgeAsSeen.pdf)

**Comment by hoststatic** [comment]
what's your issue?
maybe you should check the issue https://github.com/opensourcepos/opensourcepos/issues/920

**Comment by viragni** [comment]
@hoststatic I believe you are correct. I had an initial issue with having set up the virtual directory incorrectly, but now this seems to be it. I will play around with this, and try to get it resolved. This was very helpful as a direction to "chase"!

I know this isn't the best forum for this, but the solutions are around using .htdocs in the public or www directory. It seems this is no longer supported in the most recent version of Apache2 on Ubuntu. 

Where should I place:
RewriteRule ^(.*)$ /<OSPOS path>/public/index.php?/$1
in Apache2? 
Thanks!

**Comment by viragni** [comment]
When I try to login, I receive an error:
"The installation is not correct, check your php.ini file."

I think I might have made and error that I can't account for in my build doc, so I am going to retry with a fresh build. I will close this issue, and try the new information I have gotten here. Thanks!

**Comment by hoststatic** [comment]
Try to install and enable following php extensions php-intl php-openssl php-bcmath php-curl

**Comment by Vinaycmrit** [comment]
> ### Background information
> **IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.**
> 
> Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:
> 
> * [x]  Reporting an issue of an unmodified OSPOS installation
> * [x]  Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
> * [x]  Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
> * [x]  Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
> * [x]  Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
> * [x]  Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
> * [x]  Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.
> 
> ### Installation information
> * OSPOS version is: 3.3.7
> * OSPOS git commit hash is: no idea
> * PHP version is: 7.4
> * MySQL or MariaDB version is: 10.3.34
> * OS and version is: Ubuntu 20
> * WebServer is: Apache2
> * Selected language is: English
> * (If applicable) Docker installation: no
> * (If applicable) Installation package for the LAMP/LEMP stack is: from APT
> 
> ### Issue / Bug / Question / New Feature
> Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.
> 
> I followed these steps in my install:
> 
> **Start with vanilla Ubuntu Image**
> 
> 1. Install MariaDB with apt and related packages
> 2. Run secure install script
> 3. root PW : ***********
> 4. Install Apache2
> 5. Install
>    php7.4-curl
>    php7.4-mysql
>    php7.4-gd
>    php7.4-intl
>    php7.4-bcmath
> 6. a2enmod rewrite
> 7. systemctl restart apache2
> 8. sudo apt install libapache2-mod-php
> 9. sudo a2enmod php
> 10. CD  /var/www/html
> 11. Downloaded https://github.com/opensourcepos/opensourcepos/releases/download/3.3.7/opensourcepos.3.3.7.4f3226.tgz
> 12. Extracted all files to /var/www/html
> 13. executed sudo mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
> 14. Executed sudo mysql -u admin -ppointofsale -D ospos < /var/www/html/database/database.sql
> 
> I am able to run PHP, as I ran a test file for PHP info in public directory. This is included as OPOSPHPTest.pdf. The page I see when I browse to public is attached as OPOSPAgeAsSeen.pdf.

hi can you please help me on the installation . was this method working for you ?

**Comment by viragni** [comment]
@Vinaycmrit I cleaned up the instructions after a lot of help from the community. Check them out here:
https://github.com/opensourcepos/opensourcepos/wiki/Ubuntu-20.04.4-LTS-Install

**Comment by Vinaycmrit** [comment]
Can i please have your email id - viragni? Im little stuck in installation. Could you please help me? . My email- vinay7527@gmail.com

> @Vinaycmrit I cleaned up the instructions after a lot of help from the community. Check them out here: https://github.com/opensourcepos/opensourcepos/wiki/Ubuntu-20.04.4-LTS-Install

**Comment by viragni** [comment]
https://github.com/opensourcepos/opensourcepos/wiki/Ubuntu-20.04.4-LTS-Install

**Comment by viragni** [comment]
If it doesn't work, open a ticket and we can get you a solution!
