### ISSUE TITLE
question for mailchimp and smtp

### ISSUE THREAD

**Issue by dennistsc** [opensourcepos/opensourcepos#3522]
question:
i use free smtp from google (smtp.gmail.com)
and 
i sign up for free MailChimp API Key

may i know where the software or how to use smtp and mailchimp API in ospos?

1. smtp is sending out email but when i click a customer (then click email) and my window 10 the mail pop up. so can't use the smtp??
2. i add a contact to mailchimp and the ospos didn't sync the email to customers section. 

may i know do something wrong? or the feature is not using this way. hope that i ask a clear question.  thanks for your time.

### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is: 
- PHP version is: 7.4.3
- MySQL or MariaDB version is: 8.0.29-0ubuntu0.20.04.3
- OS and version is: 
- WebServer is: Apache/2.4.41 (Ubuntu)
- Selected language is: eng
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by daN4cat** [comment]
There is only push from OSPOS to Mailchimp no synchronisation the other way round.

For SMPT send you need to make sure your PHP configuration on your Apache server has the SMPT library available and enabled.

**Comment by dennistsc** [comment]
> There is only push from OSPOS to Mailchimp no synchronisation the other way round.
> 
> For SMPT send, you need to make sure your PHP configuration on your Apache server has the SMPT library available and enabled.

could you send me more info for the "push from OSPOS to Mailchimp" and "PHP configuration on your Apache server has the SMPT library available and enabled"

thanks for your reply

**Comment by emushene** [comment]
I would rather install Sendmail and hook it up to Gmail SMTP. So far has been the easiest installation I have done on a Linux server.

**Comment by dennistsc** [comment]
> I would rather install Sendmail and hook it up to Gmail SMTP. So far has been the easiest installation I have done on a Linux server.

thanks for letting me know 
would you mind share more? 
i have a business and i would like to use that

**Comment by emushene** [comment]
follow your regular sudo apt/yum/dnf install Sendmail mailutils
configure send mail by following this link [here](https://tecadmin.net/sendmail-to-relay-emails-through-gmail-stmp/). 

Note
/etc/mail/authinfo/smtp-auth
**AuthInfo: "U:root" "I:user@gmail.com" "P:PASSWORD"** the password here will have to come from Gmail/security app password. to do that, go to your account settings security and create it... note, you must have 2 step authentication on. 

let me know if it works for you, will take 20 minutes to complete.

**Comment by daN4cat** [comment]
I can see that there is a wiki post explaining how to: https://github.com/opensourcepos/opensourcepos/wiki/Setting-Up-OSPOS-with-Postfix-and-Gmail-SMTP-Server
