### ISSUE TITLE
Estado Cotizacion

### ISSUE THREAD

**Issue by Yankids7** [opensourcepos/opensourcepos#3524]
Deberia permitir guardar cotización y una vez confirmado por el cliente permitir cambiar de estado a facturado o nota de venta para poder agregarlo a nuestras ventas o servicios, ya que actualmente no se puede ni visualizar ese estado.

**Comment by ekardian** [comment]
> Deberia permitir guardar cotización y una vez confirmado por el cliente permitir cambiar de estado a facturado o nota de venta para poder agregarlo a nuestras ventas o servicios, ya que actualmente no se puede ni visualizar ese estado.

Sí se puede, cuando generas la cotización se guarda automáticamente en suspendidas, cuando lo restauras puedes cambiar el estado a facturado o lo que quieras, la lógica en la que fue desarrollada esta web app te permite evitarte algunas cosas que no requieres, lo adaptas a tus requerimientos, puedes ver algunos ejemplos [aquí](http://pc.biosxtreme.net/puntos-de-venta-inventarios-stock-con-open-source-point-of-sale-ospos/)
