### ISSUE TITLE
Install blues... php.ini configuration challenges

### ISSUE THREAD

**Issue by viragni** [opensourcepos/opensourcepos#3528]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.7
- OSPOS git commit hash is: no idea
- PHP version is: 7.4
- MySQL or MariaDB version is: 10.3.34
- OS and version is: Ubuntu 20.04.4 LTS
- WebServer is: Apache
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I have reviewed the issue logs, and I was able to get closer to success! However, I am also having the zombie php.ini issue. When we get this working, am more than happy to write up my server build doc to share on install page if that is helpful. I appreciate the assistance with this noob issue. As of now, I am receiving the php.ini error. I have included my build doc and errors, both resolved and current.

OPOS Build

    1. Start with Vanilla build Ubuntu 20.04.4 LTS
    2. sudo apt update
    3. sudo apt install mariadb-server
    4. sudo mysql_secure_installation
    5. root PW : ***************
    6. Install Apache2
    7. Install
php7.4-curl
php7.4-mysql
php7.4-gd
php7.4-intl
php7.4-bcmath
    8. sudo a2enmod rewrite
    9. systemctl restart apache2
    10. ## PHP not working in www
    11. sudo apt install libapache2-mod-php
    12. sudo a2enmod php7.4
    13. ## PHP working in www
    14. CD /var/www/html
    15. Downloaded https://github.com/opensourcepos/opensourcepos/releases/download/3.3.7/opensourcepos.3.3.7.4f3226.tgz
    16. Extracted all files to /var/www/html
    17. Executed mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY 'pointofsale' WITH GRANT OPTION;FLUSH PRIVILEGES;"
    18. Executed sudo mysql -u admin -ppointofsale -D ospos < /var/www/html/database/database.sql
    19. I receive the login screen, but upon entry of credetials, I receive a 404
    20. Edited .htaccess in \public to reflect: RewriteRule ^(.*)$ /var/www/html/public/index.php?/$1 [L]
    21. systemctl restart apache2
    22. Unable to login, 404 error
    23. Edited /etc/apache2/apache2.conf to include AllowOverride All
       Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
    24. systemctl restart apache2
    25. I am able to attempt a login, but I receive the php.ini error
    26. sudo nano /etc/php/7.4/apache2/php.ini
    27. enabled or added the following:
extension=intl
extension=gd
extension=openssl
extension=bcmath
extension=curl
extension=mysql
    28. systemctl restart apache2
    29. I am still receiving the php.ini error

Thanks!

**Comment by viragni** [comment]
I ran php -m:
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

**Comment by odiea** [comment]
array('bcmath', 'intl', 'gd', 'openssl', 'mbstring', 'curl'); It appears that mbstring is missing.

**Comment by viragni** [comment]
@odiea YOU ARE AMAZING!!! It works! 
I really appreciate all the help from the people on the board, and if it would be seen as helpful, I am more than happy to clean up my install doc, run it from vanilla to ensure accuracy, and post it on the "Other probably outdated install guides".:tm:
