### ISSUE TITLE
Opensourcepos.org SSL Cert expired

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3530]
I get a server error when navigating to the site. Is anyone aware of the cause? @WebShells @jekkos

**Comment by objecttothis** [comment]
Correction. The site is up but the SSL Cert expired on 5/29. @jekkos are you able to reissue the cert?

**Comment by jekkos** [comment]
No the site is not under my control. @WebShells can you have a look?

**Comment by jekkos** [comment]
I checked the website today and the certificate seems valid. Will close.
