### ISSUE TITLE
Mutli store support

### ISSUE THREAD

**Issue by MalinrRuwan** [opensourcepos/opensourcepos#3531]
How to add a different address to the same company in a different user account because another useraccount is used in the other branch

**Comment by odiea** [comment]
No this is really a single location program.

**Comment by arielszy** [comment]
You can use the location feature to do that

**Comment by WebShells** [comment]
You can try to play around with the setup of multi stock locations and assigning every cashier to a specific stock. 
Multi store feature isn't supported yet.
