### ISSUE TITLE
Merchant Account Integration

### ISSUE THREAD

**Issue by viragni** [opensourcepos/opensourcepos#3532]
I have been looking into integrating with National Processing or Helcim, and my business is based in the USA. Has anyone tried this, and are there larger issues from the OpenPOS side with doing this? I spoke with both tech teams, and they have lead me to believe the integration is not that complex (hahahahahahahahaha) but I wanted to reach out and see if anyone has tried this. More that happy to share if I get it to work.

**Comment by viragni** [comment]
And, to clarify, I am interested in if anybody has integrated with a merchant account. It need not be the ones I am looking to use.

**Comment by daN4cat** [comment]
What is the use case exactly?

**Comment by viragni** [comment]
The goal of the integration would be to allow the credit card portion of a sale to be run via the card reader. OPOS would send the request to the machine, and the machine would return a token. The token would be saved by OPOS. If there was a refund, the token would be used to generate the refund without the card being needed. 
I am looking to create the communication between OPOS and the merchant processor. My big question is had anyone tried this? Am I going to have to make big DB changes to save new fields (I know this is dumb, but I have no idea what I will run into)? If someone tried and failed, why?
More than happy to share if I get this to work.

**Comment by daN4cat** [comment]
There are security implications and PCI compliancy in the picture. Not sure if that's clear.

**Comment by viragni** [comment]
I have spoken to both development teams about the PCI issues, and that is why a token is passed back. No user identifiable information about the credit card will be kept onsite, nor will the account numbers. This is the token that is passed back. It allows for the transaction to be maintained, but the information is only kept by the processor (merchant account). 

If this has not had issues in the past, at least from US based users (I am not familiar with GDPR regulations, nor general European laws), I am more than happy to give it a swing. If it works, I will submit the code to you all. If it doesn't, it just means a bit more paperwork!

**Comment by daN4cat** [comment]
Sure thing, contributions are also welcomed.
