### ISSUE TITLE
Remove Logo/image is not working 🐛 

### ISSUE THREAD

**Issue by bhojkamal** [opensourcepos/opensourcepos#3533]
### Background information
In the latest release 3.3.7, in configuration, to remove the logo. Remove image is not working. If we click the remove image, it will remove the image of logo from the frontend but after submit and refresh the page, the logo is there again. I checked on web dev console, there is no error or warning but when I checked on network - `remove_logo` response is `Method not allowed`. This is shown on clicking the remove image. 
On web dev network - 
![image](https://user-images.githubusercontent.com/14083299/175535974-82418df5-45aa-42ed-b1ca-fecf11fa40fd.png)

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is:  3.3.7
- OSPOS git commit hash is:  dev
- PHP version is:  7.4
- MySQL or MariaDB version is: 
- OS and version is:  Linux
- WebServer is: apache
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:

**Comment by jekkos** [comment]
Thanks for the report. I think this bug might have been introduced recently. Will have a look this week.

**Comment by jekkos** [comment]
Tested this on dev, seems fine now.
