### ISSUE TITLE
Barcodes

### ISSUE THREAD

**Issue by jonnyfrm1977** [opensourcepos/opensourcepos#3534]
Hello.
First of all say that OSPOS is great. But I need a little help with the barcodes. I want to implement in a shoe store where each pair has a barcode.
How can I customize the barcodes? The format is not quite right for me. Since the article name looks small.
How can I print the necessary quantity of the pairs of shoes that enter the warehouse? If you enter 400 different pairs, how do I print 400 labels?

Excuse my English, and thank you very much for your help.
All the best.

**Comment by WebShells** [comment]
@jonnyfrm1977 just select the needed pair and click generate barcode, a new page will open -> Ctrl + P to print -> Set the Quantity to 400 in the browser printing window. 
To edit the barcode font size this requires some changes in Application -> Views -> Barcodes -> barcode_sheet.php 
Will close.

**Comment by jonnyfrm1977** [comment]
Thanks for the answers.
But the problem I have is that, for example, in a shoe transport they enter:

15 white shoes, size x
10 white shoes, size xx
7 white shoes, size xy
14 white shoes, size yy
.....

It becomes very inconvenient to print labels, could it not be done from "Inventory to add/subtract."? To automatically print the number of stickers needed. It's an idea ;)

Thanks.
