### ISSUE TITLE
Customer Reward Point Bug

### ISSUE THREAD

**Issue by surprised-potato** [opensourcepos/opensourcepos#3536]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: WIndows !0
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Good Day devs!
I have encountered a customer reward point bug where the earned points are computed based on amount paid instead of amount due.

for example, 
in the case where a customer pays the exact amount or close to the exact amount, the correct number of points are rewarded but in this example the bug appears:

I have a reward tier that rewards 2% as points, when the customer makes a purchase 100 but pays 500, the points rewarded is 10 points. How can I fix this? Thanks!

**Comment by surprised-potato** [comment]
I fixed it. I dont know if this will lead to bugs down the line though, so i would appreciate feedback if this solution is good.
i went to the /application/models/sale.php and changed line 651 to 

$total_amount = floatval($total_amount) + floatval($payment['payment_amount']) - floatval($payment['cash_refund']);

**Comment by jekkos** [comment]
Thanks for the solution! I made a PR for this change, let's build it and see if it fixes the problem.

**Comment by daN4cat** [comment]
3.3.8 release coming?

Despite the long time the software is out, there is always a bug somewhere.
