### ISSUE TITLE
Decimal stock

### ISSUE THREAD

**Issue by arielszy** [opensourcepos/opensourcepos#3538]
Is there a way to edit the system in order to buy/sell items with decimal stock such as meat cheese fruits or anything sell by weight?

**Comment by arielszy** [comment]
Selling I get an error.
Modifying stock sets automatically to 0

**Comment by arielszy** [comment]
Anyone can please tell me how to fix it? Thank

**Comment by odiea** [comment]
Have you tried setting Quantity Decimals in Configuration??

 ![2022-07-05 05_49_06-](https://user-images.githubusercontent.com/10962177/177320892-b0be2790-3188-4f8f-9bae-5a59df51e295.png)

**Comment by odiea** [comment]
https://github.com/opensourcepos/opensourcepos/wiki/Weighted-Barcodes

**Comment by arielszy** [comment]
Thanks! A lot!
