### ISSUE TITLE
SAVE ACCOUNT NUMBER ON SALE

### ISSUE THREAD

**Issue by Castros** [opensourcepos/opensourcepos#3540]
We are using OSPOS for a school cafeteria. 
We are searching students/staff by their account number/Matricula and we give them credit for the cafeteria.
Everything has been working fine.

We would like for the account number to show up on reports. So when we go to reports>Detailed_reports>Transactions and generate the daily, weekly report we can see the account number. I was able to to add the column but I am not able to get the account number that corresponds to the customer to show up.

Is this something difficult to add?

<img width="1244" alt="Screen Shot 2022-07-02 at 14 42 18" src="https://user-images.githubusercontent.com/17105508/177014319-1ac268cc-0c2f-4fb2-ac79-88bfbeb9632f.png">

**Comment by nukerj** [comment]
@Castros This is easy to do. contact me by **telegram** my user **jvilchez**  I can gladly help you
