### ISSUE TITLE
Api rest

### ISSUE THREAD

**Issue by arielszy** [opensourcepos/opensourcepos#3542]
It would be great to have an api rest for example, to make an app

**Comment by jekkos** [comment]
Duplicate of #2463

**Comment by jekkos** [comment]
The other day I found this great tool that would allow to reverse engineer a swagger spec from sniffing the communication between frontend and backend. Actually we should run this for Ospos and then we can generate a client in about any language.

https://github.com/alufers/mitmproxy2swagger

**Comment by jekkos** [comment]
@arielszy perhaps something you could try?
