### ISSUE TITLE
Fatal Error CodeIgniter.php

### ISSUE THREAD

**Issue by PGTech85** [opensourcepos/opensourcepos#3548]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.7
- OSPOS git commit hash is: 
- PHP version is: 7.4.29
- MySQL or MariaDB version is: 10.4.24-MariaDB
- OS and version is: Windows 10
- WebServer is: XAMPP
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Trying to setup OSPOS. I am getting an error
`Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\codeigniter\system\core/CodeIgniter.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\public\index.php on line 315`
I've changed /public/index.php `$system_path = '../codeigniter/system';`
The file path 'C:\xampp\htdocs\codeigniter\system\ is correct but not sure what the \core is. CodeIgniter.php is in the \system folder.

**Comment by PGTech85** [comment]
Haha.....ok so I see where in index.php it had `require_once BASEPATH.'core/CodeIgniter.php';` so I changed it to `require_once BASEPATH.'CodeIgniter.php';`  but now I just get a blank page with nothing.

**Comment by daN4cat** [comment]
Have you downloaded the official release zio file or cloned GitHub?

**Comment by PGTech85** [comment]
> Have you downloaded the official release zio file or cloned GitHub?

I downloaded the official release .zip file

**Comment by odiea** [comment]
You will need to download this one. The other .zip files are not compiled for use. &zip will extract .tgz files.
https://github.com/opensourcepos/opensourcepos/releases/download/3.3.7/opensourcepos.3.3.7.4f3226.tgz
