### ISSUE TITLE
It does not close the session neither in demo nor installed.

### ISSUE THREAD

**Issue by wolarte** [opensourcepos/opensourcepos#3549]
- OSPOS version is: 3.3.7
- OSPOS git commit hash is: don't close the session.
- PHP version is: 7.4
- MySQL or MariaDB version is: 5.7
- OS and version is: hosting
- WebServer is: cerberus
- Selected language is: 
- (If applicable) Docker installation: no
- (If applicable) Installation package for the LAMP/LEMP stack is: no

in demo mode or installed software the system cannot log out. It simply stays open and you can re-enter without having to re-register the username and password.

**Comment by wolarte** [comment]
Is it possible to tell me how I can make the logout work,

**Comment by ekardian** [comment]
> Is it possible to tell me how I can make the logout work,

welp i am clicking in the logo, then i wait like 5~8 seconds and then close session, in the begining is not working in that way, so i deactivated the adblok and the duckduckgo privacy, but now again its not closing after 8 seconds. i am with firefox

**Comment by jekkos** [comment]
I have just tested the logout on our demo server with FF and that seems to work ok?

**Comment by ekardian** [comment]
> I have just tested the logout on our demo server with FF and that seems to work ok?

nop, is not disconecting sometimes in the first attemp i can, i said like 1 of 4 i can logout, but after i clicked like 5 times logout butom or other else,,, i can logout

**Comment by jekkos** [comment]
Can you check what happens in the browser console when you click the button?

**Comment by wolarte** [comment]
@ekardian is correct but i try open with Chrome and work fine. Thanks alls.

**Comment by ekardian** [comment]
> Can you check what happens in the browser console when you click the button?

in the demo from ospos and on my hosting the same issue, maybe the firefox thing

no errors, just this
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.

**Comment by ekardian** [comment]
> @ekardian is correct but i try open with Chrome and work fine. Thanks alls.

Replicated issue on firefox:
- if i have 2 tabs open, you cannot logout, in other case
- if you opened only ospos in 1 tab you need back to the site.com/public for logout, so
- if you are in any place and you press logout ospos take you to the main page, then you can logout now, so you need press 2 time logout if you are in 1 tab for logout XD
