### ISSUE TITLE
Multiple prices for same item

### ISSUE THREAD

**Issue by viragni** [opensourcepos/opensourcepos#3551]
I have seen a few requests similar to this:
https://github.com/opensourcepos/opensourcepos/issues/1271
https://github.com/opensourcepos/opensourcepos/issues/1017
https://github.com/opensourcepos/opensourcepos/issues/642

But I have a slightly different use case. If I was selling cut flowers as an item, and cut flowers would be priced at sale time. I could buy (3) roses for $5, and (2) tulips for $6. They are all cut flowers. Think of almost a miscellaneous sales item, but one that was specific to a category.  

Is there a way to do this now? Or, would this be an enhancement?

**Comment by nukerj** [comment]
@viragni Making it multi-priced would be a better option, you can place up to 6 prices on the same product and change from a selector to Price1, Price2 or Price 3

**Comment by viragni** [comment]
@nukerj I like the idea, but we have too wide of a range of prices on flower arrangements. They can go from $25 to $250. I would need greater flexibility. But, thanks!

**Comment by nukerj** [comment]
@viragni  no le queda de otra que utilizar los Kits para los arreglos. Es la opción más viable por el momento y ya existe en OSPOS

**Comment by emushene** [comment]
> @viragni Making it multi-priced would be a better option, you can place up to 6 prices on the same product and change from a selector to Price1, Price2 or Price 3

How do I do this on the 3.3.7, also I need to automate supplier reports to be sent every night via sendmail. Send mail already works, just to automate this. I got Amazon giftcards

**Comment by nukerj** [comment]
> > @viragni Making it multi-priced would be a better option, you can place up to 6 prices on the same product and change from a selector to Price1, Price2 or Price 3
> 
> How do I do this on the 3.3.7, also I need to automate supplier reports to be sent every night via sendmail. Send mail already works, just to automate this. I got Amazon giftcards

@emushene hello. Sendme to telegram it's my profile @jvilchez
