### ISSUE TITLE
Impresión fiscal

### ISSUE THREAD

**Issue by juneiker24** [opensourcepos/opensourcepos#3552]
Impresión fiscal

Algunos países necesitan algunas comunicaciones especiales con chip interno en las impresoras, esta función solo se realiza localmente y no es posible a menos que se pueda realizar un ad-hoc específico o con un dispositivo especial que recibe la impresión sin procesar y la envía desde el navegador a la impresora.

Puede solicitar aquí algunos servicios por unos pocos dólares, las adaptaciones se hacen fáciles para algunos países. Abra un problema, [un problema de ticket de soporte (haciendo clic aquí)](https://github.com/opensourcepos/opensourcepos/issues/new) ¡solo unas pocas palabras antes de su solución!

quisiera mas informacion para saber como asociar impresoras fiscales

**Comment by ekardian** [comment]
hice una pregunta parecida para crear un módulo de facturación electrónico en línea para Bolivia, según los requerimientos de encriptación que propone el Sistema De Facturación de Bolivia, aún para todo Bolivia está retrasado el proceso tras la pandemia por el Covid, donde todos pasamos a dejar el papel y hacerlo todo en línea, la pregunta fue muy compleja, la respuesta fue la siguiente en este hilo [Question about registering OSPOS to national taxes of my country Bolivia](https://github.com/opensourcepos/opensourcepos/issues/2418#issue-427309160)

**Comment by nukerj** [comment]
@juneiker24 

To synchronize with fiscal printers, a **fiscal spooler** can be used. In some countries, such as Venezuela, the use of a fiscal spooler is not allowed, but I have used this type of application for other systems. With OSPOS I have not yet had the need to do it but it is possible

Para comunicarse con impresoras fiscales se pueden usar un spooler fiscal. En algunos paises como en Venezuela no esta permitido el uso de spooler fiscal pero si he utilizado para otros sistemas este tipo de aplicacion. Con OSPOS no se me ha presentado aun la necesidad de hacerlo pero si es pocible
