### ISSUE TITLE
OSPOS becomes unresponsive when trying to export many rows to CSV or any format on brave browser.

### ISSUE THREAD

**Issue by surprised-potato** [opensourcepos/opensourcepos#3553]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
Bug OSPOS becomes unresponsive from brave browser when trying to export csv file from reports that is more than >1500 rows. The browser provides an error message asking if id like to wait for the page or kill the process. it doesn't download an exported copy of the report.

**Comment by surprised-potato** [comment]
![image](https://user-images.githubusercontent.com/89435318/181468399-3b1dbd35-ad9e-46e9-9526-f91f7405b0f7.png)
I managed to export 5500 rows on google chrome but if i try to export more, it crashes with the following error.
![image](https://user-images.githubusercontent.com/89435318/181468569-b1891037-65da-4735-8b22-abfc38e355d5.png)

**Comment by viragni** [comment]
Have you tried connecting to the DB directly (https://dev.mysql.com/downloads/workbench/ is an easy solution) to see if you can export the data directly? I realize this isn't a solution, but it might help to get you the data you need.

**Comment by surprised-potato** [comment]
Hi. Yes. That is my current workaround. I hope this can get fixed soon. for now, I also just try to limit the number of rows being exported at a time.

**Comment by jekkos** [comment]
The with the current design is that you need to load all data in the browser first. This is not efficient and it will have its limits.

The browser hangs because the export blocks the ui event thread.

A more scalable solution would be a http stream from the server directly. But that would be a reimplementation

**Comment by hoststatic** [comment]
Facing some issue, downloading data from all pages (bootstrap table 20k records) and it fails.
Would try jekkos recommendation
