### ISSUE TITLE
Sales commissions.

### ISSUE THREAD

**Issue by LuisPadilla** [opensourcepos/opensourcepos#3554]
First of all, I apologize for my English.
My knowledge of the software is basic, so I need you to please tell me how to calculate the commission per sale of an item.
The idea is to calculate the final value of the item by a number that equals the percentage (item value * commission percentage).
Thank you very much in advance, any information will be very valuable to me.

**Comment by nukerj** [comment]
@LuisPadilla tengo esto que necesitas funcionando de la siguiente forma. cuando ingresas un producto desde articulos luego de agregar el costo te pide el porcentaje de venta del producto y podemos hacer que calcule el precio de venta. 

tambien desde el modulo recepcion le coloque cambiar el porcentaje de venta y el precio de venta del producto.

tambien tengo en uso el pago por multimonedas, es decir, recibir pagos en dolares y en moneda local a la vez y colcoar a los productos costo y precio en dolares y en moneda local. luego al agregar la tasa de cambio tus productos pueden tener los precios y costos actualizados segun la tasa de cambio.

I have this you need working as follows. When you enter a product from articles, after adding the cost, it asks you for the sales percentage of the product and we can make it calculate the sale price.

Also from the reception module, you can change the percentage of sale and the sale price of the product.

I also have multi-currency payment in use, that is, receive payments in dollars and in local currency at the same time and assign cost and price to products in dollars and in local currency. then by adding the exchange rate your products can have updated prices and costs according to the exchange rate.

mi usuario **telegram** es **jvilchez** contactame para darte acceso a una version de prueba.

my username **telegram** is **jvilchez** contact me to give you access to a trial version.

**Comment by hoststatic** [comment]
You'd like to create another field, datatype for calculating the commision for sale ?
Add new column on Sales table (it depends where you making changes) 
Make the changes on the sales module (the calculations), add it also on controller and also the view (and reports).
Hope this helps

**Comment by LuisPadilla** [comment]
Hello @nukerj @hoststatic , your help is very valuable.
I want to show what I have done so far, I need you to please guide me.
I really don't know very well what to do.
1. Create a field in the table `ospos_items`.
![image](https://user-images.githubusercontent.com/5678654/190023100-68a3dfe0-dad0-45a3-9217-63e37bf0e480.png)
2. I would like to calculate the commission for each item sold. 
3. I would like the commission to be shown in the place where the profit is being shown. 
![image](https://user-images.githubusercontent.com/5678654/190023901-7df27942-f22c-43e9-bc89-019e5755eedb.png)

Any guidance to help me achieve my goal would be greatly appreciated. 

PS. Too bad about the English level.

**Comment by nukerj** [comment]
> Hello @nukerj @hoststatic , your help is very valuable. I want to show what I have done so far, I need you to please guide me. I really don't know very well what to do.
> 
> 1. Create a field in the table `ospos_items`.
>    ![image](https://user-images.githubusercontent.com/5678654/190023100-68a3dfe0-dad0-45a3-9217-63e37bf0e480.png)
> 2. I would like to calculate the commission for each item sold.
> 3. I would like the commission to be shown in the place where the profit is being shown.
>    ![image](https://user-images.githubusercontent.com/5678654/190023901-7df27942-f22c-43e9-bc89-019e5755eedb.png)
> 
> Any guidance to help me achieve my goal would be greatly appreciated.
> 
> PS. Too bad about the English level.

Hola Luis. Ya tienes mi número telefónico. Escríbeme directamente a WhatsApp o telegram y con gusto puedo seguirte asesorando dándote indicaciones o ideas de que hacer ya solo te falta agregar en la tabla sales_items un atributo invariable que se llame tot_comision y aplicas la fórmula en el  digo fuente creo que en la librería sale_lib 

tot_cimision=((quantity_purchased*item_unit_price)*comision)/100 

Está fórmula es una idea se podría mejorar y no recuerdo bien si las variables de llaman así exactamente
