### ISSUE TITLE
Paid Feature request

### ISSUE THREAD

**Issue by viragni** [opensourcepos/opensourcepos#3555]
This is referencing https://github.com/opensourcepos/opensourcepos/issues/3551

I am looking for added functionality to the sales page. If a customer is purchasing an item, such as fresh cut flowers, currently all fresh cut flowers must have the same price. I would like to have the ability to change the price on the screen and have it show as a separate line item.
Below, the item must be a different item to have a different price. 

![OPOSScreen](https://user-images.githubusercontent.com/15070250/181787547-8ff4a601-3f78-4b89-8c77-e53fbbbbcb62.png)

The user would be able to change the price of an item, in this case Cut Flowers. When another Cut Flowers is added, it will add it as a separate line. If it is the same price, it will increment the value.
If I have 1 Cut Flower, and I change the price from $15 (the default price) to $35, and I add another Cut Flower from the Find or Scan Item, it will add another line because the existing line item is $35. I will now have 2 lines. If I add another Cut Flowers, it will increment the one at $15, and show 2 lines. One line will have 2 items at $15, and the other line will have one item at $35.

I am willing to pay $200 USD for this. For payment to occur, it must do what is outlined here, and be accepted into the code base. When this is successfully tested and accepted by OPOS, I will transfer funds via PayPal, Venmo, etc.

**Comment by viragni** [comment]
Is this something other people see as valuable? Is the bounty for this on par?

**Comment by odiea** [comment]
What version number are you using. I can suggest a quick edit for you to try on a test machine to see if is what you want. PS I am not a programmer.

**Comment by viragni** [comment]
I am on 3.3.7. Can't wait to hear a idea! Thanks!

**Comment by odiea** [comment]
This is is assuming that you do not use the Serialized function in Items.
In application/libraries/sale.lib around line 827 remove the exclamation mark. if($item_info->is_serialized) then around line 
879 add an exclamation mark as follows. if(!$itemalreadyinsale || !$item_info->is_serialized). I tried this multiple times and it worked for me. Check your reports to be sure that you are getting the correct info after a Sale. Hope this helps.

**Comment by nukerj** [comment]
@viragni I have something similar working for the use of restaurants, I think something similar can be done with this using the Serialized function in Articles and conditioning according to your requirements. my **telegram** user is **jvilchez** contact me and we analyze this to start the development of what you request

**Comment by viragni** [comment]
@odiea Winner, winner, chicken dinner! Thanks, that is perfect! I will reach out to you privately for figuring out how to send you the bounty.

**Comment by viragni** [comment]
@odiea It looks like I can't reach out in a direct message. Is there a better way to contact you? Or, should I post a BS email, you email it, and then I email you back. I hate spam....

**Comment by odiea** [comment]
On the front page you will see a place to donate money to Jekkos. That would be where I would like it to go. What ever amount you can afford.

**Comment by jekkos** [comment]
Thanks for the donation!

**Comment by viragni** [comment]
@jekkos Thanks for the amazing software! I hope to be able to add more value as we move to adopt this in-house.
