### ISSUE TITLE
Demo POS - error at login

### ISSUE THREAD

**Issue by froger-me** [opensourcepos/opensourcepos#3556]
https://demo.opensourcepos.org/login

"Unable to load the requested language file: language/malay/form_validation_lang.php"

<img width="585" alt="Screen Shot 2022-08-02 at 6 39 21 AM" src="https://user-images.githubusercontent.com/3622456/182257378-6e6980e1-2479-4ef3-963e-49bc853df04b.png">

**Comment by jekkos** [comment]
I have reset the demo instance. I think there might be a missing language file in malay language.
