### ISSUE TITLE
CSV import issues

### ISSUE THREAD

**Issue by joshbudu** [opensourcepos/opensourcepos#3559]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I have being reading wikis and old conversations for about a week now but i am not getting anywhere. CSV import works when i import only one item. I mean only one row. I am using 3.3.8 and it is a fresh install. will be glad if someone can help.

**Comment by ekardian** [comment]
### it's working
just you need follow a tips, like when you are filling and in the export option, i am using a libreoofice for this (in my personal and demo working good):

- you need write the ID of your supplier instead his name supplier:
-- in the demo there are a supplier with id 45, so...
![How_write](https://user-images.githubusercontent.com/6296036/185760534-2da4280a-ddfe-4b5e-b7fd-cd45efdfae54.png)

- In LibreOffice Calc, when you are exporting you need change the options like, on microsoft windows i dont know how, but, maybe you can find in guugle:
![how_export1](https://user-images.githubusercontent.com/6296036/185760628-16f6bf1f-819a-42f3-9f42-2bd8cab38a51.png)

and


![How_export2](https://user-images.githubusercontent.com/6296036/185760650-e11de721-86aa-4e40-991d-7898ee68b368.png)

### A view of my csv exported and openned with a text editor and how was exported on OSPOS

![how_u_see_exported](https://user-images.githubusercontent.com/6296036/185760726-9d59acf8-1a42-40f9-a747-5de3c37d6d7f.png)

**Comment by joshbudu** [comment]
Thank you for reaching out. Will download office libre office and follow your steps. @ekardian

**Comment by joshbudu** [comment]
Thank you so much buddy. After a month of pain it finally worked. Really appreciate it. @ekardian
