### ISSUE TITLE
500 error after trying loging

### ISSUE THREAD

**Issue by kilian099** [opensourcepos/opensourcepos#3560]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

####Symptoms####

It seems when I tried to access after installation ospos, once it appears the page to login:

![image](https://user-images.githubusercontent.com/106171763/184913396-09ee889a-ce57-4917-bf93-5f8f6e9b8d53.png)

500 internal server error comes...

![image](https://user-images.githubusercontent.com/106171763/184913519-b23e3a4e-2b6c-4431-af9c-f0f03f0b5225.png)

I am pretty sure needs to be rewrite module rule is entirely configure as apache's default config on my system. Is there any ospos contributor expert to guide me with may be some issues I have this is my current configuration for now:
OS: Ubuntu 18.06 minimalist server version
Environment Local Virtual Machine with Virtualbox
/etc/apache2/apache.conf
<Directory />
        Options FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

<Directory /usr/share>
        AllowOverride All
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

/var/www/html/opensource/public/.htaccess

RewriteEngine On

# To redirect a subdomain to a subdir because of https not supporting wildcards
# replace values between <> with your ones
# RewriteCond %{HTTP_HOST} ^<OSPOS subdomain>\.<my web domain>\.com$ [OR]
# RewriteCond %{HTTP_HOST} ^www\.<OSPOS subdomain>\.<my web domain>\.com$
# RewriteRule ^/?$ "https\:\/\/www\.<my web domain>\.com\/<OSPOS path>" [R=301,L]

# To rewrite "domain.com -> www.domain.com" uncomment the following lines.
# RewriteCond %{HTTPS} !=on
# RewriteCond %{HTTP_HOST} !^www\..+$ [NC]
# RewriteCond %{HTTP_HOST} (.+)$ [NC]
# RewriteRule ^(.*)$ http://www.%1/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path

RewriteRule ^(.*)$ /opensourcepos/public/index.php?/$1 [L]

# disable directory browsing
# For security reasons, Option all cannot be overridden.
#Options All -Indexes
Options +ExecCGI +Includes +IncludesNOEXEC +SymLinksIfOwnerMatch -Indexes

version apache : 

Server version: Apache/2.4.29 (Ubuntu)
Server built:   2022-06-23T12:51:37

php7.4 installed

#2730 

[core:error] [pid 2620] [client 192.168.1.121:38912] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://192.168.1.142/login

php -m 
[PHP Modules]
calendar
Core
ctype
date
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

**Comment by kilian099** [comment]
Please, only people who has been developed or contribute on this project can be helpful to have resolve this issue. Avoid suggestions as I already suggest most of the things on the issues of this project. Thanks.

**Comment by odiea** [comment]
PHP 'bcmath', 'intl', 'gd', 'openssl', 'mbstring', 'curl' are required. First enable these then try again.

**Comment by kilian099** [comment]
> PHP 'bcmath', 'intl', 'gd', 'openssl', 'mbstring', 'curl' are required. First enable these then try again.

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

Already installed and enabled them, restart apache and same situation.

**Comment by odiea** [comment]
try changing public/index.php from production to development
application/config/config.php  change $config['log_threshold'] = 0; to 1
Then inspect the error log to see if anything there shows up.

**Comment by kilian099** [comment]
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '/var/www/html/opensourcepos/application/logs/errors'

I tested as normal without change the path did not output any errors and then I tried to redirect the specific logs for errors in the path errors and did not output any errors either. 
I checked the GLOBAL settings of mysql to check if 'only_full_group_by' I removed it
my mod_rewrite is enabled.
and also my login page is working the only differences is when I provide the default user admin:pointofsale or leave it blank and press log in; the page where suppose to be is log on to is an internal server 500

Anymore suggestions?

**Comment by kilian099** [comment]
> $config['log_threshold'] = 1;
> 
> /*
> Error Logging Directory Path
> --------------------------------------------------------------------------
> | | Leave this BLANK unless you would like to set something other than the default | application/logs/ directory. Use a full server path with trailing slash. | */ $config['log_path'] = '/var/www/html/opensourcepos/application/logs/errors'
> 
> I tested as normal without change the path did not output any errors and then I tried to redirect the specific logs for errors in the path errors and did not output any errors either. I checked the GLOBAL settings of mysql to check if 'only_full_group_by' I removed it my mod_rewrite is enabled. and also my login page is working the only differences is when I provide the default user admin:pointofsale or leave it blank and press log in; the page where suppose to be is log on to is an internal server 500
> 
> Anymore suggestions?

<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">$config['log_threshold'] = 1;</p>

/*
--
Error Logging Directory Path
--------------------------------------------------------------------------

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">|<br style="box-sizing: border-box;">| Leave this BLANK unless you would like to set something other than the default<br style="box-sizing: border-box;">| application/logs/ directory. Use a full server path with trailing slash.<br style="box-sizing: border-box;">|<br style="box-sizing: border-box;">*/<br style="box-sizing: border-box;">$config['log_path'] = '/var/www/html/opensourcepos/application/logs/errors'</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I tested as normal without change the path did not output any errors and then I tried to redirect the specific logs for errors in the path errors and did not output any errors either.<br style="box-sizing: border-box;">I checked the GLOBAL settings of mysql to check if 'only_full_group_by' I removed it<br style="box-sizing: border-box;">my mod_rewrite is enabled.<br style="box-sizing: border-box;">and also my login page is working the only differences is when I provide the default user admin:pointofsale or leave it blank and press log in; the page where suppose to be is log on to is an internal server 500</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Anymore suggestions?</p>

**Comment by kilian099** [comment]
This ticket can be resolved it seems in the current latest 3.3.8 .htaccess in the web root is missing to let rewrite working.
I downloaded the previous version 3.3.7 and whole installation went through with the same steps follow at INSTALL.md
