### ISSUE TITLE
3.3.8 is not the same with demo, that has the time selection in reports

### ISSUE THREAD

**Issue by Masturzi** [opensourcepos/opensourcepos#3561]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: ffe492
- PHP version is: 7.2
- MySQL or MariaDB version is: 5.5.5-10.4.11
- OS and version is: Windows NT 6.3
- WebServer is: XAMPP
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

In the demo, it has time selection when extracting a report but after 3.3.8 installation there is none.

**Comment by odiea** [comment]
Will you show an image of what you are referring to?

**Comment by Masturzi** [comment]
> Will you show an image of what you are referring to?

Hi, here is a screenshot https://imgur.com/A51Ru6s.png of the demo page that has the time selection under the date selection. I have upgraded mine from 3.3.7 to 3.3.8 and I do not have that.

**Comment by odiea** [comment]
Did you enable the Date Time filter in configuration Localization?
