### ISSUE TITLE
How to apply the the changes after editing .htaccess? 

### ISSUE THREAD

**Issue by bhojkamal** [opensourcepos/opensourcepos#3562]
### Background information

Suppose I want to redirect to another website for temporarily, So I edit and write the rewriteCond and Rule, But it does not do anything. Still it apply the old rule even I removed or commented it. 

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is:  3.3.4 - 3.3.7
- OSPOS git commit hash is:  392d92, dev 
- PHP version is: 7.4
- MySQL or MariaDB version is:  10.5.16
- OS and version is: Linux and window
- WebServer is: apache
- Selected language is:  en-GB
- (If applicable) Docker installation: no
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue  / Question 

I want to redirect to another website for temporarily, So to do it. I edit and write the rewriteCond and Rule on .htaccess, But it does not do anything. Still it apply the old rule even I removed or commented it. 

I even tried the redirect from cpanel domain redirect, but it still does not do any effect to the original. 
To my understanding, once the whatever is set on .htaccess is set permanently. Then if we change to it it does not affect anything to the application. So, it is save in such way permanently. how can I remove it.

**Comment by hoststatic** [comment]
Please explain more in detail what you want to achieve?
If you do changes in .htaccess make sure you nginx/apache are configured properly. 
I am running on a custom .htaccess and it works flawlessly

**Comment by ekardian** [comment]
more details like share your config .htaccess or install a clean ospos demo in a subdomain for testing, remember you have like 2 .htaccess redirecting in source/.htaccess and source/public/.htacess

**Comment by bhojkamal** [comment]
I comment the original rewriteCond and Rule and put this
```
  RewriteCond %{HTTP_HOST} ^example.com$ [OR]
  RewriteCond %{HTTP_HOST} ^www.example.com$
  RewriteRule (.*)$ https://www.anothersite.com/$1 [R=301,L]
```
This does not work at all, I don't why but the below worked.
`Redirect 301 / https://anothersite.com/`

**Comment by bhojkamal** [comment]
Redirect 301 / https://anothersite.com/ 
worked
