### ISSUE TITLE
How to Remove ,000 in quantity 

### ISSUE THREAD

**Issue by zidnyyasrah** [opensourcepos/opensourcepos#3566]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: 
- PHP version is: 7.2.34
- MySQL or MariaDB version is: .DB Version: 5.5.5-10.3.35-MariaDB-log-cll-lve
- OS and version is: Windows 10
- WebServer is: Apache
- Selected language is: id-ID
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
hello, so i need to use the decimals number for something like half quantity of an item (i've enabled the quantity decimals), but when the quantity of the item is not decimal, the extra zero for decimal is still remain. Is there any way to remove the extra .000 in the quantity 

![Screenshot (54)](https://user-images.githubusercontent.com/69409101/190834931-8122ca79-7c5c-40a3-b112-95c7cdd10038.png)

**Comment by nukerj** [comment]
Hello.  To be able to change whether an item has a decimal quantity or is sold by weight or by whole unit, you must do the following.  First, from the Articles register, add an option that allows you to select if the article is loaned when it is sold.  then from the sales module make a condition with this variable that was added to verify if the variable $peso==1 then number_format($quality,3) else number_format($quantity)
![IMG_20220922_030121](https://user-images.githubusercontent.com/47283494/191682005-a6a14a6a-29e5-4aaf-9eb2-140e014b2721.jpg)
![Screenshot_2022-09-22-02-58-51-672_com android chrome](https://user-images.githubusercontent.com/47283494/191682009-b412f9da-b7db-444b-98ea-1a0ccc2591cd.jpg)

**Comment by nukerj** [comment]
@zidnyyasrah Hello.  To be able to change whether an item has a decimal quantity or is sold by weight or by whole unit, you must do the following.  First, from the Articles register, add an option that allows you to select if the article is loaned when it is sold.  then from the sales module make a condition with this variable that was added to verify if the variable $peso==1 then number_format($quality,3) else number_format($quantity)

![IMG_20220922_030121](https://user-images.githubusercontent.com/47283494/191682410-0356ea48-4651-4e48-9ee9-14ac5bf9aaa9.jpg)
![IMG_20220922_030100](https://user-images.githubusercontent.com/47283494/191682412-ab8c7049-94f3-41c1-b3d4-509f08b212a6.jpg)

**Comment by zidnyyasrah** [comment]
Hi, thank you for your replies, but unfortunately on the articles register you just mentioned, i can't find the option that allows me to "select if the article is loaned when it is sold". 

![Screenshot (59)](https://user-images.githubusercontent.com/69409101/192075626-603edfa7-4014-4865-b690-5482be51ac40.png)

or do i need to add the new option through editing "items\form" code? 

![Screenshot (57)](https://user-images.githubusercontent.com/69409101/192075365-4e834b1a-f86a-45d2-975c-4318bb9d3c41.jpg)

thanks before :D

**Comment by zidnyyasrah** [comment]
Hi, @nukerj
Just wondering, what is your ospos version, it's looks a little bit different from mine

**Comment by nukerj** [comment]
> @nukerjHola, gracias por sus respuestas, pero lamentablemente en el registro de artículos que acaba de mencionar, no encuentro la opción que me permita "seleccionar si el artículo se presta cuando se vende".
> 
> ![Captura de pantalla (59)](https://user-images.githubusercontent.com/69409101/192075626-603edfa7-4014-4865-b690-5482be51ac40.png)
> 
> ¿O necesito agregar la nueva opción editando el código "items\form"?
> 
> ![Captura de pantalla (57)](https://user-images.githubusercontent.com/69409101/192075365-4e834b1a-f86a-45d2-975c-4318bb9d3c41.jpg)
> 
> gracias antes :D

Debes desarrollarla

**Comment by nukerj** [comment]
> Hola,@nukerj Me preguntaba cuál es tu versión ospos, se ve un poco diferente a la mía

No lo recuerdo en este momento pero la versión que uso le he hecho muchas modificaciones a medida que se van necesitando. Por ejemplo, yo le agregué pago Multimoneda para poder recibir pagos en divisas USD y moneda local.
