### ISSUE TITLE
amount received to zero on invoice

### ISSUE THREAD

**Issue by blutme** [opensourcepos/opensourcepos#3568]
### Issue / Bug  / Question / New Feature

Hello Friends, on /application/views/sales/registe.php
I suggest that in the condition:

`
					if(!$pos_mode && isset($customer))
					{
					?>
						<div class='btn btn-sm btn-success' id='finish_invoice_quote_button'><span class="glyphicon glyphicon-ok">&nbsp</span><?php echo $mode_label; ?></div>
					<?php
					}
					?>`

 add

`$amount_due <= 0`

like this:

`
					if(!$pos_mode && isset($customer) && $amount_due <= 0)
					{
					?>
						<div class='btn btn-sm btn-success' id='finish_invoice_quote_button'><span class="glyphicon glyphicon-ok">&nbsp</span><?php echo $mode_label; ?></div>
					<?php
					}
					?>
`

Because without adding that other condition, the enabling of the payment button invoice only depends on the selected client and if someone changes the amount received to zero, and click on the invoice button the payment invoice will also be zero.

**Comment by jekkos** [comment]
But should you have an amount due to create an invoice? You can perfectly pay for the sale and then request an invoice for the amount that is already fullfilled no?

**Comment by blutme** [comment]
Yes, of course, that's why I say that it is an optional suggestion... Because there may be stores where the cashier does not know the system well and if he uses the keyboard shortcuts, the bill will go to zero... and that goes to generate an error in the report. Maybe... I will work on a javascript warning before processing the payment.

Thanks.
