### ISSUE TITLE
Any plans to add a shipping costs at the receiving's module? 

### ISSUE THREAD

**Issue by EgliTafa** [opensourcepos/opensourcepos#3570]
Just installed OSPOS and added all my products but I have noticed that the sales and receiving's sections lack 'add shipping cost'. Is there any way to add this feature?

**Comment by nukerj** [comment]
@EgliTafa  hay que hacerle una adaptación para eso.  Con gusto puedo ayudarle si es una adaptación mínima así de simple yo puedo hacerla y contribuye con apoyo directo 
A los desarrolladores de OSPOS  no para mí. Es la forma en que me gustaría contribuir de forma externa al proyecto
