### ISSUE TITLE
Quick search

### ISSUE THREAD

**Issue by Snake-Host** [opensourcepos/opensourcepos#3572]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: ffe492
- PHP version is: 7.4.30
- MySQL or MariaDB version is: 10.5.15
- OS and version is: Debian 11 linux 5.10.0-18-amd64
- WebServer is: Apache/2.4.54
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hello,
First of all excuse me if I'm asking in the wrong place, but is there a quick method to search an item without typing it's full name.

Supposing I have an item called "Hp Laptop i5-1035G1" and I would like to search for it by typing only few letters separated by a special character like an * or % or even a space like the following "hp%lap%i5%35G" without the double quotes.

If someone can help, it would be a great feature to implement in this great project.

**Comment by nukerj** [comment]
@Snake-Host Hello. If it can be done with a FullText query type, it is something that @andriux1990  and I already use in a modified version of ospos. I don't know if the Ospos development team is willing to implement it. but if you wish I can customize this function for advanced search. my telegram user is @jvilchez

**Comment by nukerj** [comment]
Hello. If it can be done with a FullText query type, it is something that @andriux1990  and I already use in a modified version of ospos. I don't know if the Ospos development team is willing to implement it. but if you wish I can customize this function for advanced search. my telegram user is @jvilchez

**Comment by jekkos** [comment]
Sure this could be useful, how was it implemented exactly?

**Comment by Snake-Host** [comment]
@nukerj I would be really pleased to get your help on it.

**Comment by nukerj** [comment]
> Claro que esto podría ser útil, ¿cómo se implementó exactamente?

Usamos el tipo de consulta fulltext que puede reslizar la busqueda con comodines como se hace en google ejemplo +item name

tambien lo hicimos que que use los dos tipos de busqueda la nativa de OSPOS y la tipo FullText esto activando desde configuracion la busqueda avanzada

**Comment by Snake-Host** [comment]
@nukerj any code?

**Comment by nukerj** [comment]
> @nukerj any code?
  Contact me at https://t.me/jvilchez
