### ISSUE TITLE
Docker install on WSL Ubuntu-20.04 not running after following the instrcutions

### ISSUE THREAD

**Issue by tichaonax** [opensourcepos/opensourcepos#3574]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: Ubuntu 20.04 on windows 11
- WebServer is: WSL on Windows 11
- Selected language is: English
- (If applicable) Docker installation:  Docker Installation latest GitHub code-base
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I have followed the instruction to install using docker. cloned the repo and ran docker-compose build followed by docker-compose up. I am running WSL. Everything appears to work except there is no response from the browser on localhost. I see activity on the console when accessing the webpage. 

Is there an initial webpage I need to go to first time or it should automatically redirect me. This is default install to test nothing configured prior to running the build and run commands as directed.

![image](https://user-images.githubusercontent.com/1031407/194434013-54658ac0-b3df-4db6-b081-7dd85b2e73ff.png)

**Comment by tichaonax** [comment]
FYI!, I also followed same instruction on a MAC and its the same result the page does not load

**Comment by jekkos** [comment]
Can you try to set in dev mode to see what the issue is?

Use the following command

`docker exec "opensourcepos-ospos-1" /bin/sed -i 's/production/development/g' /app/public/index.php`

**Comment by tichaonax** [comment]
Thanks for the response, It is complaining of database access or something related, I do not know if I need to do that outside the docker container itself. I thought its a self contained system. Here is the error on the browser.
![image](https://user-images.githubusercontent.com/1031407/194715337-336478f3-3b73-4e88-b654-de8848d9e46a.png)

**Comment by jekkos** [comment]
It looks like some database table is missing. Maybe you can remove the containers and restart the stack, so the db is reinitialized?

**Comment by tichaonax** [comment]
I will try again but this occurred on two different systems, macbookpro and ubuntu under windows 11.

**Comment by tichaonax** [comment]
Still get the same error unfortunately. I really wanted to use the docker version, its supposed to work seamlessly but may be needs more details on the steps than what is currently available.
