### ISSUE TITLE
Message: array_multisort(): Argument #1 is expected to be an array or a sort flag

### ISSUE THREAD

**Issue by khaolek** [opensourcepos/opensourcepos#3577]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [/] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [/] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [/] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [/] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [/] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [/] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.6
- OSPOS git commit hash is: f3e41a
- PHP version is: 7.4.29
- MySQL or MariaDB version is:  10.8.3-MariaDB
- OS and version is:  Windows 11 Home Single Language
- WebServer is: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29 
- Selected language is:  Thai
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

add goods to cart and summit sale then bill receive can't display sale item and php display msg this 

A PHP Error was encountered

Severity: Warning

Message: array_multisort(): Argument #1 is expected to be an array or a sort flag

Filename: libraries/Sale_lib.php

Line Number: 99

Backtrace:

File: D:\xampp\htdocs\application\libraries\Sale_lib.php
Line: 99
Function: array_multisort

File: D:\xampp\htdocs\application\controllers\Sales.php
Line: 771
Function: sort_and_filter_cart

File: D:\xampp\htdocs\public\index.php
Line: 315
Function: require_once

![ospos_error](https://user-images.githubusercontent.com/4671237/195582908-693776af-5be0-433d-9112-68fd7b6c3278.png)

**Comment by jekkos** [comment]
sort and filter cart, that is not a standard function I think

**Comment by khaolek** [comment]
> sort and filter cart, that is not a standard function I think. Did you modify the code?

i'm add sales_debit and sales_check in thai on file application\language\th\sales_lang.php only.

**Comment by khaolek** [comment]
step a problem is
1. add goods in  item (on picture 1)

barcode: 8850267112624
Item name: Lactasoy soymilk 125ml.
cost Price: ฿0.00
Sell Price: ฿5.00
Item group: นมและนมถั่วเหลือง

2. add code in item kit (on picture 2)
	
barcode: 8850267117629
Item name: Lactasoy 125ml pack 6 box
cost Price: ฿0.00
Sell Price: ฿30.00
Item : 8850267112624 Lactasoy soymilk 125ml.

3. sale barcode barcode: 8850267117629  (on picture 3)
4. commit order
5. print bill order (this error) (on picture 4)

mark:
im sale in barcode: 8850267112624 not has a problem.



![1  Update item Powered by OSPOS 3 3 6](https://user-images.githubusercontent.com/4671237/195763986-606101fc-3557-4c43-9ec7-7063fa0ec988.png)

![2  Update item kit Powered by OSPOS 3 3 6](https://user-images.githubusercontent.com/4671237/195763992-7636f9b5-d540-4a3d-84ca-0a5e85e3c180.png)

![3  addpayment Powered by OSPOS 3 3 6](https://user-images.githubusercontent.com/4671237/195763994-56907854-0b1e-4abe-8111-cb17b903d198.png)

![4  close order Powered by OSPOS 3 3 6](https://user-images.githubusercontent.com/4671237/195764805-16116033-a02e-4ccc-b805-d205a7c08a1f.png)

**Comment by nukerj** [comment]
@khaolek did you make any condition for the quantities from sale_lib?

**Comment by khaolek** [comment]
> @khaolek did you make any condition for the quantities from sale_lib?

i'm not make condition for the quantities from sale_lib.
