### ISSUE TITLE
Calculate wholesale price in summary data differently

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3583]
What I would like to achieve is to calculate total wholesale (cost_price) differently on reports
The total summary data query is done in /models/reports/Summary_report

For the wholesale summary calculations is done on line 30
		`$sale_cost = 'SUM(sales_items.item_cost_price * sales_items.quantity_purchased)';`

So what I would like to achieve is to get the AVG of cost_price (all receivings for a product) if there is data if not calculate with the default formula.
so it would be like this

`(select item_id, item_cost_price, quantity_purchased, SUM(item_cost_price)/count(receiving_id) as avg_recv_price from ospos_receivings_items GROUP BY item_id) * sale_items.quantity_purchased`  
if there is no data for a certain item.
`SUM(sales_items.item_cost_price * sales_items.quantity_purchased)`

Some items would have data on receivings_items and some not.

How could I apply this?

**Comment by hoststatic** [comment]
The moment I make a receiving for an item it could be different cost_price may change, so to calculate with a fixed price it shows profit and wholesale price not correctly/real value.

**Comment by hoststatic** [comment]
The only solution is to start with 0 stock in stock_location and then use the Receivings->receive to populate data to use the 
$sale_cost = 'SUM(receivings_items.item_cost_price * sales_items.quantity_purchased)';

**Comment by nukerj** [comment]
I think that the ideal would be to add up to 3 different sale prices for a product, then we would have price 1 which would be the main price that OSPOS has by default, price 2 which would be the wholesale price and price 3 as another wholesale price and thus have a selector that allows us to choose between price one price 1, 2 and 3 .  Permissions can then be set for users, where or who can use these additional prices.  This is something that I have already done and it works perfectly for me, I have up to 6 different sale prices and I can choose between the 6 according to the permission that my user has.

![IMG_20221101_040727](https://user-images.githubusercontent.com/47283494/199187662-d6ede337-e426-4491-86d5-6e3d2cb04e67.jpg)
![IMG_20221101_040704](https://user-images.githubusercontent.com/47283494/199187667-5c26654c-1ea7-4ee0-ab12-1dffea56bf46.jpg)

**Comment by hoststatic** [comment]
When you receive a product, price may change (unit_price). If price changes then for the product you should calculate the avarage of changeable unit_price if does not change calculate with default unit_price. So in end of reports when you calculate profit that should be taken in consideration. That is what I mean, not in sales but receivings, in this is for the reports

**Comment by hoststatic** [comment]
![osp_3](https://user-images.githubusercontent.com/99489665/199840603-95a4b1c3-791f-4674-a259-f87f11833427.png)
![1](https://user-images.githubusercontent.com/99489665/199840605-18c77672-ec15-458f-bf3d-cff0afc21054.PNG)

**Comment by hoststatic** [comment]
The default calculations does not show the real wholesale total and the profit because we could receive an item with different (unit_price). So basically you should calculate avarage unit_price of that item from ospos_receivings_items and if there is the item has been receivied with same unit_price calculate from ospos_items (unit_price). I hope you understand my point

**Comment by hoststatic** [comment]
> I think that the ideal would be to add up to 3 different sale prices for a product, then we would have price 1 which would be the main price that OSPOS has by default, price 2 which would be the wholesale price and price 3 as another wholesale price and thus have a selector that allows us to choose between price one price 1, 2 and 3 . Permissions can then be set for users, where or who can use these additional prices. This is something that I have already done and it works perfectly for me, I have up to 6 different sale prices and I can choose between the 6 according to the permission that my user has.
> 
> ![IMG_20221101_040727](https://user-images.githubusercontent.com/47283494/199187662-d6ede337-e426-4491-86d5-6e3d2cb04e67.jpg) ![IMG_20221101_040704](https://user-images.githubusercontent.com/47283494/199187667-5c26654c-1ea7-4ee0-ab12-1dffea56bf46.jpg)

Could you share the changes you've made, maybe reading the code would understand better your point. My english is not that good. 

Thanks in advance

**Comment by odiea** [comment]
In configuration/general did you enable calculate average price in Receivings?

**Comment by nukerj** [comment]
@hoststatic 
![IMG_20221103_185944](https://user-images.githubusercontent.com/47283494/199851720-456cfd50-3a32-4d27-9d74-1a8417ab537a.jpg)
Do you want to see something like this but in the reports?  I have it but in the reception module.  where have I done but as a reference for reception and to know the average

**Comment by nukerj** [comment]
@hoststatic si claro puedo compartir el código, al sentarme en el computador lo remito a tu usuario github

**Comment by hoststatic** [comment]
@nukerj it would be great

**Comment by hoststatic** [comment]
> 

Yes, I used avarage price in receivings, but in reports of sales (summary employees, summary_items, detailed_transactions etc) I would like to calculate wholesale and profit using avarage unit_price from ospos_receivings_items if an item has been received with different price, if not use unit_price from ospos_items.
So basically I think wholesale and profit are calculated 'not correctly', if you receive an item in certain time with different prices.
