### ISSUE TITLE
CI4: Merge changes from the Master into #3271

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3585]
#3271 was opened in August of 2021. We need to bring in changes that have been merged into the master since the branch was created.  This will need to be curated because CI4 has many changes to formats and syntax. Some CI3 functions also do not exist or exist in the same way in CI4.

**Comment by jekkos** [comment]
This won't be easy, but I can give it a try.. I might try to squash all commits in the branch first, it might make the sync easier

**Comment by objecttothis** [comment]
If it were me, I would go back to each of the commits or branches that were merged into the master, look at what changes were made and then go make the corollary changes on #3271.  If we try to merge Master onto CodeIgniter_4_upgrade then go through the conflicts one at a time, it's probably just going to say everything has changed so it's indistinguishable from what is CI4 related and what is changes that are made into the master.

I think this is a good argument for freezing direct merges to the master and asking changes to be a branch of CodeIgniter_4_upgrade so they get merged into that and we don't end up with a rats nest.  The more people pitching in, the faster this upgrade will be done and out the door and we won't have the crazy. At minimum, my vote is to freeze merging new branches directly into the master. I'm over my head in terms of most of the stuff regarding devops, so I've been primarily focused on the code changes to get that up to snuff.

CI4 added a lot of built in CRUD functions to the Model class, but we don't have to port our current CRUD methods to them at this point since what we have will work fine.  So, I'm holding off on all that for now.

**Comment by jekkos** [comment]
I think that if we squash all changes it will be easier to move changes from master into the branch, as it will only generate merge conflicts once we do the rebase. Also the history will be a lot cleaner as it will look like we started from latest master and we just amend everything that was added since the branch to the squashed commit.

**Comment by objecttothis** [comment]
That's fine with me.

**Comment by jekkos** [comment]
So the advantage of this approach is that if git detects whether a file is moved, and it sees that the original was changed in the meantime in master, it will try to apply those changes to the file in the new location. This seems to work for some of the files, but not for all of them currently (list below). I suppose for some reason it can't detect that it changed place. I'll check later on if there is a way to overcome this.

```
Auto-merging .gitignore                                                                                                                                                                                                                                                                                                       
CONFLICT (content): Merge conflict in .gitignore                                                                                                                                                                                                                                                                              
Auto-merging .travis.yml                                                                                                                                                                                                                                                                                                      
CONFLICT (content): Merge conflict in .travis.yml                                                                                                                                                                                                                                                                             
Auto-merging Dockerfile                                                                                                                                                                                                                                                                                                       
CONFLICT (content): Merge conflict in Dockerfile                                                                                                                                                                                                                                                                              
Auto-merging app/Helpers/locale_helper.php                                                                                                                                                                                                                                                                                    
Auto-merging app/Libraries/Token_lib.php                                                                                                                                                                                                                                                                                      
CONFLICT (content): Merge conflict in app/Libraries/Token_lib.php                                                                                                                                                                                                                                                             
Auto-merging app/Models/Reports/Summary_taxes.php                                                                                                                                                                                                                                                                             
CONFLICT (content): Merge conflict in app/Models/Reports/Summary_taxes.php                                                                                                                                                                                                                                                    
Auto-merging app/Views/configs/info_config.php                                                                                                                                                                                                                                                                                
CONFLICT (content): Merge conflict in app/Views/configs/info_config.php                                                                                                                                                                                                                                                       
Auto-merging app/Views/expenses/manage.php                                                                                                                                                                                                                                                                                    
Auto-merging app/Views/login.php                                                                                                                                                                                                                                                                                              
CONFLICT (content): Merge conflict in app/Views/login.php                                                                                                                                                                                                                                                                     
Auto-merging app/Views/partial/header_js.php                                                                                                                                                                                                                                                                                  
Auto-merging app/Views/reports/tabular.php                                                                                                                                                                                                                                                                                    
Auto-merging app/Views/reports/tabular_details.php                                                                                                                                                                                                                                                                            
CONFLICT (file location): application/views/sales/help.php added in HEAD inside a directory that was renamed in ca94e3ea8 (Composer Changes), suggesting it should perhaps be moved to app/Views/sales/help.php.                                                                                                              
Auto-merging app/Views/sales/manage.php                                                                                                                                                                                                                                                                                       
CONFLICT (modify/delete): application/config/config.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/config/config.php left in tree.                                                                                                                                            
CONFLICT (modify/delete): application/config/hooks.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/config/hooks.php left in tree.                                                                                                                                              
CONFLICT (modify/delete): application/controllers/Items.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/controllers/Items.php left in tree.
CONFLICT (modify/delete): application/controllers/Login.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/controllers/Login.php left in tree.
CONFLICT (modify/delete): application/controllers/Messages.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/controllers/Messages.php left in tree.
CONFLICT (modify/delete): application/controllers/Reports.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/controllers/Reports.php left in tree.
CONFLICT (modify/delete): application/controllers/Sales.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/controllers/Sales.php left in tree.
CONFLICT (modify/delete): application/helpers/tabular_helper.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/helpers/tabular_helper.php left in tree.
CONFLICT (modify/delete): application/language/en-US/common_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/en-US/common_lang.php left in tree.
CONFLICT (modify/delete): application/language/en-US/config_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/en-US/config_lang.php left in tree.
CONFLICT (modify/delete): application/language/en-US/customers_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/en-US/customers_lang.php left in tree.
CONFLICT (modify/delete): application/language/en-US/employees_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/en-US/employees_lang.php left in tree.
CONFLICT (modify/delete): application/language/en-US/expenses_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/en-US/expenses_lang.php left in tree.
CONFLICT (modify/delete): application/language/en-US/items_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/en-US/items_lang.php left in tree.
CONFLICT (modify/delete): application/language/en-US/sales_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/en-US/sales_lang.php left in tree.
CONFLICT (modify/delete): application/language/en-US/taxes_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/en-US/taxes_lang.php left in tree.
CONFLICT (modify/delete): application/language/ta/cashups_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/ta/cashups_lang.php left in tree.
CONFLICT (modify/delete): application/language/ta/item_kits_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/ta/item_kits_lang.php left in tree.
CONFLICT (modify/delete): application/language/ta/module_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/ta/module_lang.php left in tree.
CONFLICT (modify/delete): application/language/tl-PH/receivings_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/tl-PH/receivings_lang.php left in tree.
CONFLICT (modify/delete): application/language/tl-PH/reports_lang.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/language/tl-PH/reports_lang.php left in tree.
CONFLICT (modify/delete): application/libraries/Sale_lib.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/libraries/Sale_lib.php left in tree.
CONFLICT (modify/delete): application/models/Appconfig.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/Appconfig.php left in tree.
CONFLICT (modify/delete): application/models/Employee.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/Employee.php left in tree.
CONFLICT (modify/delete): application/models/Sale.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/Sale.php left in tree.
CONFLICT (modify/delete): application/models/reports/Detailed_receivings.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/reports/Detailed_receivings.php left in tree.
CONFLICT (modify/delete): application/models/reports/Detailed_sales.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/reports/Detailed_sales.php left in tree.
CONFLICT (modify/delete): application/models/reports/Specific_customer.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/reports/Specific_customer.php left in tree.
CONFLICT (modify/delete): application/models/reports/Specific_discount.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/reports/Specific_discount.php left in tree.
CONFLICT (modify/delete): application/models/reports/Specific_employee.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/reports/Specific_employee.php left in tree.
CONFLICT (modify/delete): application/models/reports/Specific_supplier.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/reports/Specific_supplier.php left in tree.
CONFLICT (modify/delete): application/models/reports/Summary_items.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/reports/Summary_items.php left in tree.
CONFLICT (modify/delete): application/models/tokens/Token_invoice_sequence.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/tokens/Token_invoice_sequence.php left in tree.
CONFLICT (modify/delete): application/models/tokens/Token_quote_sequence.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/tokens/Token_quote_sequence.php left in tree.
CONFLICT (modify/delete): application/models/tokens/Token_work_order_sequence.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/models/tokens/Token_work_order_sequence.php left in tree.
CONFLICT (modify/delete): application/views/partial/footer.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/views/partial/footer.php left in tree.
CONFLICT (modify/delete): application/views/partial/header.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/views/partial/header.php left in tree.
CONFLICT (modify/delete): application/views/receivings/receiving.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/views/receivings/receiving.php left in tree.
CONFLICT (modify/delete): application/views/sales/form.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/views/sales/form.php left in tree.
CONFLICT (modify/delete): application/views/sales/register.php deleted in ca94e3ea8 (Composer Changes) and modified in HEAD.  Version HEAD of application/views/sales/register.php left in tree.
Auto-merging composer.json
CONFLICT (content): Merge conflict in composer.json
Auto-merging composer.lock
CONFLICT (content): Merge conflict in composer.lock
Auto-merging package.json
CONFLICT (content): Merge conflict in package.json
CONFLICT (file location): application/hooks/method_hook.php added in HEAD inside a directory that was renamed in ca94e3ea8 (Composer Changes), suggesting it should perhaps be moved to writable/cache/method_hook.php.
error: could not apply ca94e3ea8... Composer Changes
```

**Comment by objecttothis** [comment]
Good work.  
application is now app
hooks is now Events
subfolders of application now begin with a capital letter.
application/config/hooks.php is now app/Config/Events.php, though they are different files almost entirely.

There are two things I'm mildly concerned about.
1- In many cases, the changes made to the master, when brought over, will not work.  This is usually because of differences between CI3 and CI4.  For example, we may have a change that adds the line `$this->input->get_post()` but in CI4 this would be $this->request->getPost()`.
2- Where it does find the file and automatically port over the changes, will it be smart enough not to just give this giant amalgamation of the CI4 and CI3 files?

Good work.  Thanks for helping with this.

**Comment by jekkos** [comment]
Ok cfr my question in the other thread on hook.php, you answered it here. It seems that git does not consider a files as moved once the content has changed too much. To avoid losing commit history I have now first moved those files in my local master manually to the new folder structure, and made a separate commit with only that.

Now I have reran the rebase on top of this new master. This time git does detect that the files were moved and generates a proper merge conflict. This makes merging the upstream changes a bit easier.

**Comment by jekkos** [comment]
To make language file migration easier, I will just ignore the current merge conflicts. I will copy them again from the master branch and will try to use a tool, or build one myself, to convert them to the new format all at once.

**Comment by jekkos** [comment]
@objecttothis I think I'm done with the version control work. I have pushed this in a new branch called ci4-upgrade. It has three commits on top of master

* First commit contains the file moves to the new folder directory
* Second commit has all your changes on top of it
* Last commit applies the changes in master applied on top of the upgraded code

I have reverted all language files to the old structure for now. You converted one file already but it needed to be updated as well as probably the strings and translations were changed. I copied all the files from master to the new structure nad will rename and reformat them in one go in the weblate ticket.

I did not do any testrun yet so that might be a next thing. Do you have anything runtime tested already on your side, or an overview on what works and what does not?

**Comment by objecttothis** [comment]
I just started runtime testing and fixing bugs. Now I'm working on fixing the problems with hooks being converted to events and figuring out why the env file isn't properly overriding the config files.

**Comment by jekkos** [comment]
The env file was something custom we added if I remember well. I can apply any further changes from the initial branch to the new one if you prefer not to switch yet

**Comment by objecttothis** [comment]
The env file is used by CI4 natively so I think we should use it. It makes sense to configure all of the OSPOS specific settings in the various settings files and then use the env file for users to enter the per instance settings such as db connection settings and encryption key.

**Comment by objecttothis** [comment]
> The env file was something custom we added if I remember well. I think it read the env file and filled the config object with the parsed object properties.
> 
>  I can apply any further changes from the initial branch to the new one if you prefer not to switch yet

I'm mildly confused now which branch I should be working on to get OSPOS converted to CI4. I would assume that it should be whichever one contains the changes from the current master, but I'm not sure which that is. Can you clarify?

**Comment by jekkos** [comment]
I made a first PR here. Maybe wait before you switch to it as I still see a couple of things I would like to fix. I see that the zh-hans language was renamed to zh-hant. I guess I'll need to use the latter? Also a couple of files are not properly tracked (they are still removed and added instead of replaced) and some others were accidentally committed.

**Comment by jekkos** [comment]
Have reviewed the PR a bit further
* Both zh-Hans and zh-Hant are back in the tree
* Properly moved db_log, load_config and save hooks now to events (so their history is preserved)
* Also fixed the displacement of the test files

I still see two files that are in first sight not present in the new branch, MY_Lang and MY_Security. The first one is probably not needed anymore, but not sure on the second, I think it does some extension to how the cookie is generated and adds sameSite attribute to prevent a class of CSRF attacks

**Comment by objecttothis** [comment]
> Have reviewed the PR a bit further
> 
>     * Both zh-Hans and zh-Hant are back in the tree
> 
>     * Properly moved db_log, load_config and save hooks now to events (so their history is preserved)
> 
>     * Also fixed the displacement of the test files
> 
> 
> I still see two files that are in first sight not present in the new branch, MY_Lang and MY_Security. The first one is probably not needed anymore, but not sure on the second, I think it does some extension to how the cookie is generated and adds SameSite attribute to prevent a class of CSRF attacks. I see that SameSite is now natively supported so indeed we might be able to get rid of it.

zh-Hans is Chinese simplified and zh-Hant is Chinese Traditional.  They are two separate languages for our purposes and I think we need to keep both.

**Comment by objecttothis** [comment]
> Have reviewed the PR a bit further
> 
>     * Both zh-Hans and zh-Hant are back in the tree
> 
>     * Properly moved db_log, load_config and save hooks now to events (so their history is preserved)
> 
>     * Also fixed the displacement of the test files
> 
> 
> I still see two files that are in first sight not present in the new branch, MY_Lang and MY_Security. The first one is probably not needed anymore, but not sure on the second, I think it does some extension to how the cookie is generated and adds SameSite attribute to prevent a class of CSRF attacks. I see that SameSite is now natively supported so indeed we might be able to get rid of it.

I don't know for sure but I don't think either are needed any longer.  I believe CSRF is handled natively in CI4 but we need to make sure https://codeigniter.com/user_guide/libraries/security.html.  As for Language localization we may need to port over MY_Lang if that is what is allowing a database driven language selection https://codeigniter.com/user_guide/outgoing/localization.html?highlight=lang#language-localization

**Comment by objecttothis** [comment]
> I made a [first PR](https://github.com/opensourcepos/opensourcepos/pull/3592) here. Maybe wait before you switch to it as I still see a couple of things I would like to fix.

@jekkos am I good to begin using this branch? I'd like to have just one branch to use rather than make more changes to codeigniter_4_upgrade and later have to bring them into this branch.  IMO we also either need to freeze merges into the master until this branch is merged or try to get this branch merged before anyone else wants to merge something into master... but maybe that's just me wanting to avoid "merge hell".

**Comment by objecttothis** [comment]
Yeah, the changes from the master are not in this branch.
For example, this is one of @jekkos fixes to prevent Blind SQL injection
![image](https://user-images.githubusercontent.com/17935339/202391924-ec0bd9bb-ba7b-4a29-9364-ea0399cd3478.png)

The code in CI4 has a different syntax and function name, so if we were to just do a straight merge it doesn't work.
![image](https://user-images.githubusercontent.com/17935339/202391984-e02929bc-6f77-44dc-8a3c-378cff33550b.png)

Instead, I think we likely need to go through each of the commits in the master between 10 August 2021 and manually port them over.  According to the Codeigniter_4_upgrade branch, that's 310 commits.  The good news is that many of these commits are weblate translation changes (https://github.com/opensourcepos/opensourcepos/compare/CodeIgniter_4_upgrade...master) so we can either just copy over what's in the current master (as long as it's before we switch to CI4 formatting) or we can let weblate overwrite the new location with the new format and all the translation changes.
![image](https://user-images.githubusercontent.com/17935339/202392973-8124a805-ab83-4289-b6a5-cee7695dfd1d.png)

Here is the list of commits in the master since I started. @jekkos how do you want to proceed?
https://github.com/opensourcepos/opensourcepos/compare/CodeIgniter_4_upgrade...master

**Comment by objecttothis** [comment]
Here is a list of the 76 commits in the master that is not in ci4_upgrade, which need to be ported over in CI4 format and are not related to weblate.  We could just have people take ownership of porting over each one.  @jekkos thoughts?
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/objec/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/objec/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>
<body link="#0563C1" vlink="#954F72">

Commit Message | Link | Owner
-- | -- | --
Fix logout race condition (#3578) | https://github.com/opensourcepos/opensourcepos/commit/b44993f2fa7a7c916ccb1f8ad3ffac108ebb4ce3 |  
Fix closing parenthesis, otherwise   ENVIRONMENT always resulted true & path added as tests/ | https://github.com/opensourcepos/opensourcepos/commit/a501dc9b9938e578f6b302c7bbccb276d12fa01e |  
Update DO offer | https://github.com/opensourcepos/opensourcepos/commit/06ca9e9f746563675a65399a172e1d23a9df3f22 |  
Bump to 3.3.8 | https://github.com/opensourcepos/opensourcepos/commit/ffe49278fcbd936f34a9644debd0b7ff9bd83e31 |  
Substract refund from total rewards   (#3536) | https://github.com/opensourcepos/opensourcepos/commit/f061a83317be81ce8591bb010d481a4df95ab586 |  
Bump grunt from 1.5.2 to 1.5.3 | https://github.com/opensourcepos/opensourcepos/commit/7e3d048bfc6b9e517555db0ddc0a1a7d23e08c5e |  
Add item_pic to escape ignore list   (#3379) | https://github.com/opensourcepos/opensourcepos/commit/4f3226b1ba7db529f4d40e93825fa7b77794a974 |  
Enable search in detailed reports (#3495) | https://github.com/opensourcepos/opensourcepos/commit/82ae2e093176413d01f1dde729cc49c56804c2d3 |  
Add cost price column to item summary   report (#3495) | https://github.com/opensourcepos/opensourcepos/commit/e4ca111977cbb8512b8e9b391d4175becc6d41e8 |  
Enable search in reports (#3491) | https://github.com/opensourcepos/opensourcepos/commit/31944f491c1d724f95c0234ba5eadc8424571731 |  
Bump simple-get from 3.1.0 to 3.1.1 | https://github.com/opensourcepos/opensourcepos/commit/19342e4d6f3184e846024c0f9fab7680ff45c9e5 |  
Update unstable build URL | https://github.com/opensourcepos/opensourcepos/commit/c8a83fbb577251f8bf4b038fd2627c3c616aa4d7 |  
Remove markup last row expenses (#3779) | https://github.com/opensourcepos/opensourcepos/commit/c3d06fc6f51439c666eabeb96c31120f21203c39 |  
Add version string echo | https://github.com/opensourcepos/opensourcepos/commit/553eae19a3c9189785dd9167dd05d0bafabdb5ae |  
3.3.7-master-564465 | https://github.com/opensourcepos/opensourcepos/commit/63f282a8b58bbc76331827a7132949f2bbabf315 |  
Add npm version --from-git Rotate npm   token | https://github.com/opensourcepos/opensourcepos/commit/cfd5973f0e1828b8c3e53479f425d592d0cdc33e |  
Bump grunt from 1.4.1 to 1.5.2 | https://github.com/opensourcepos/opensourcepos/commit/e44bc3e6740664b1dc1eb056abd90ea2fcb4c760 |  
Update changelog | https://github.com/opensourcepos/opensourcepos/commit/a6b4f826c539544431d2a8506262ec4f961c903c |  
Do not escape email and phone_numbers   (#3379) | https://github.com/opensourcepos/opensourcepos/commit/d26498d1adc89105a78efc3d4a29f0aceb8715d8 |  
Fix sales last row style (#3379) | https://github.com/opensourcepos/opensourcepos/commit/5897130e0acf8ddd4670383dd61ef6f48a4da48a |  
Add escape flag for XSS mitigation   (#3379) | https://github.com/opensourcepos/opensourcepos/commit/9331d823132c268c38d77690223e5b75cb498fe9 |  
Mount database.sql from docker volume   (#3352) | https://github.com/opensourcepos/opensourcepos/commit/4a591e89b6efd6e9bd2538c68511bd59ce211054 |  
Fix transaction summary for serialized   items (#3445) | https://github.com/opensourcepos/opensourcepos/commit/8c1977b1ec44dbb13055e5b20839d91938e8e9bf |  
Run build if git tag is added | https://github.com/opensourcepos/opensourcepos/commit/6028bc408d215f563bd8a4a5d9a296cc2da739e8 |  
Change register to show anticipated   invoice number. (#3408) | https://github.com/opensourcepos/opensourcepos/commit/96c59245e3b608e61a2b9bebef54fe8d05bba26d |  
Bump to 3.3.7 | https://github.com/opensourcepos/opensourcepos/commit/669a5b33f34e7df2aa2c5b444efffec65b005fc0 |  
Use anchor in supplier regex (#3402) | https://github.com/opensourcepos/opensourcepos/commit/730ec1292dbc18fd3dea3b7bcf6b2ed761e90964 |  
Rotate npm token (#2834) | https://github.com/opensourcepos/opensourcepos/commit/6e1db1458ba57baab8376abb9831dd1323b10859 |  
Use https for git-script-link-tags | https://github.com/opensourcepos/opensourcepos/commit/5c425febfb276c5f77e9639f1b874ae3f5c9906d |  
Update link to unstable builds (#2834) | https://github.com/opensourcepos/opensourcepos/commit/81087fc093478573fa37c38bfbe209aa33cae075 |  
Use git tag in case of release (#2834) | https://github.com/opensourcepos/opensourcepos/commit/0231c0bc4fa1b0b8a105fd41382a21e508ebe318 |  
Enable npm package uploads for unstable   (#2834) | https://github.com/opensourcepos/opensourcepos/commit/bece3b5fea0e933260f6f1e3da9ab5e978c9af3b |  
Update CHANGELOG.md | https://github.com/opensourcepos/opensourcepos/commit/b309b631f253fde9a5e2cf1136c058d71f75422e |  
Add default user/password in testing   (#3374) | https://github.com/opensourcepos/opensourcepos/commit/40565ea8113457e27aece54c780ec351b99e9ad5 |  
Fix logout csrf | https://github.com/opensourcepos/opensourcepos/commit/9332d16ec403bdc696c2543d837fbd4566c59d97 |  
Update ISSUE_TEMPLATE.md | https://github.com/opensourcepos/opensourcepos/commit/0618ff47fd3f5bc0df4ee3ff605fdb20e0fc37d6 |  
Combine dependencies info, update npm   packages | https://github.com/opensourcepos/opensourcepos/commit/b936306b50e5b19ce7193b87e369275c7da7455d |  
Text improvements | https://github.com/opensourcepos/opensourcepos/commit/33cb3fa3f932931f6f68ac1b0fda235707fc431c |  
Bump to 3.3.6 | https://github.com/opensourcepos/opensourcepos/commit/caaa26f9ba4ee4954a1395c4db7ae9eaebe63fc9 |  
Sync language files (#2554) | https://github.com/opensourcepos/opensourcepos/commit/bbac91f421b69f2ed65b418df998e6de2948e36a |  
Keyboard Shortcuts/Hotkeys (#2618) | https://github.com/opensourcepos/opensourcepos/commit/6f8b877bd964f0733b6ba9eae9ff51fd2904327f |  
Fix payment summary refresh after edit   (#3329) | https://github.com/opensourcepos/opensourcepos/commit/c5bf78fcbd5676f4a887109e825e9cee35b80752 |  
Use POST for delete supplier &   customer (#3336) | https://github.com/opensourcepos/opensourcepos/commit/3ac43c2d26e016ea776a68ba82dce9b7949487bb |  
Leave cURL default for SSL because more   secure | https://github.com/opensourcepos/opensourcepos/commit/2e33f32630fd60553153ff1cd26bce7e02f6967f |  
Make footer revision clickable (#3306) | https://github.com/opensourcepos/opensourcepos/commit/986ab7e86c98596bbb872f5f7bc87d37c886c3ce |  
Fix reCaptcha issue with wrong keys   (#3207) | https://github.com/opensourcepos/opensourcepos/commit/8d87f35fd8e29daf4a733efc7a3a0994052c6cf2 |  
Add dev docker-compose with phpmyadmin | https://github.com/opensourcepos/opensourcepos/commit/b2d187a349ba58736d67bd98bb173f4b6dd46e25 |  
Fix dev docker-compose | https://github.com/opensourcepos/opensourcepos/commit/d821c69e6c8376a939314e7963ccf0969004bd75 |  
Fix CSP, it needs to be one line +   ReCaptcha | https://github.com/opensourcepos/opensourcepos/commit/e36a74ded2f17ff37fcf4d8c3e7392aa85ffbb5c |  
Fix CSP rules (and tested) | https://github.com/opensourcepos/opensourcepos/commit/ee5e06cd0cd7454f465113a8de1bce692a6a9e2f |  
Try unsafe-inline for script-src, add   font-src | https://github.com/opensourcepos/opensourcepos/commit/d04f1e434c2c1860eddc97a6f757cf6077d89549 |  
Add CSP directive for javascript (#3217) | https://github.com/opensourcepos/opensourcepos/commit/38ebf9e8198d23cf93d572ce3ff2498915111e66 |  
Update composer.lock | https://github.com/opensourcepos/opensourcepos/commit/05de93cb68c609541c83c3521a82fe66036a6e35 |  
Update docker-compose.dev.yml | https://github.com/opensourcepos/opensourcepos/commit/970744d8fc3e85888269fd7fecba2f64d277e2f9 |  
Remove deprecated MAINTAINER from   Dockerfile | https://github.com/opensourcepos/opensourcepos/commit/a5f063b382248a9daa328c2627d917b83e4eb05e |  
Amend the fix to include delete_supplier   (#3332) | https://github.com/opensourcepos/opensourcepos/commit/6b3aa876ed60eb9a36254b75b271e069fd314161 |  
Prevent type juggling for password hash   comparison (#3324) | https://github.com/opensourcepos/opensourcepos/commit/f1672d9701c895e51444f206d11b3b5ed5ffe824 |  
Update Items.php | https://github.com/opensourcepos/opensourcepos/commit/2f69841c95869c26d4413186dd0078e3a98dc461 |  
Extend method hook validation for deletes | https://github.com/opensourcepos/opensourcepos/commit/e8f27f547b061b88ed78232e75e859bdf7ebcd6b |  
Fix reflected XSS vulnerability | https://github.com/opensourcepos/opensourcepos/commit/2b031e646693eac8687de8e90835fc1af4201f7f |  
Typo | https://github.com/opensourcepos/opensourcepos/commit/6ef764d9b2e689ed9573be34d55102d2ea18c6a1 |  
Tax name | https://github.com/opensourcepos/opensourcepos/commit/d2d9c9c5327e3c93fa9103c6a27f4eabe0071a80 |  
Time in Reports | https://github.com/opensourcepos/opensourcepos/commit/b15d0b046ea3c968adfee5e3bdf74612dcce24fd |  
Revert "Time in Reports" | https://github.com/opensourcepos/opensourcepos/commit/e51a3e698a07104ba18e3df26aa0e72802ef09e3 |  
Time in Reports | https://github.com/opensourcepos/opensourcepos/commit/a33f29b713364265ed5a96273dae9ea8c3717ef7 |  
Correct bug preventing new item creation | https://github.com/opensourcepos/opensourcepos/commit/ad7ae23f2cc8dde04971e7bd3d7cd5a82ef20025 |  
Revert SQLi fixes (#3284) | https://github.com/opensourcepos/opensourcepos/commit/a2e7c0a74bbdaed6a33fd80549d6e6117a32ecb3 |  
Enable mode_headers for docker | https://github.com/opensourcepos/opensourcepos/commit/136448444d5375adcaf1545dbe4449b30e5beae3 |  
Add X-Frame-Options header (prevent   clickjacking) | https://github.com/opensourcepos/opensourcepos/commit/2c9355e8b86f4ecf8875a5f872b638af09469f4c |  
Use bootstrap 5.0.2 (#3281) | https://github.com/opensourcepos/opensourcepos/commit/77c30b7f904ffc9a7fd52b34e5d48782f1af187b |  
Merge all unstable builds in one draft   release (#3110) | https://github.com/opensourcepos/opensourcepos/commit/fe727674a518374a9c97e61b57aa3edd056a981b |  
Blind sql injection fixes (#3284) | https://github.com/opensourcepos/opensourcepos/commit/b4c48e5141fd04857def6cd141f96d27a5986a45 |  
Update changelist (#3218) | https://github.com/opensourcepos/opensourcepos/commit/b925155ba55b7d6ae2a79693c3892a48f12fc805 |  
Try to upgrade docker version (#3281) | https://github.com/opensourcepos/opensourcepos/commit/d07b9349e38e94c087ac4b70d13d0552bc62d7b6 |  
Bump to 3.3.5 (#3281) | https://github.com/opensourcepos/opensourcepos/commit/51a8cffc9eb09939692b5db1a054f7e5a1ee3d3a |  
Add sorting for quantity and sales   (#3262) | https://github.com/opensourcepos/opensourcepos/commit/5669dff7da6e651708f8934f1813193dd7cd7450 |  



</body>

</html>

**Comment by objecttothis** [comment]
As I'm looking through these commits, it appears to be only changes related to folders/files that have been moved which have not applied from the current master.

**Comment by objecttothis** [comment]
OK, I've checked the ones already applied and a few others that I ported over.  We are down to 35 commits that need to be ported over to CI4 format.  This is much more manageable.

**Comment by jekkos** [comment]
I still have a set of stashed changes that contain some of the things that still need to be applied, apparantly. I also made a script to convert the language files to the new format, so I can do that in go. Then after I can try to import in weblate.

**Comment by jekkos** [comment]
> 

On the CSRF, I don't think it will be solved in CI4. I would like to know how the input sanitization works in CI4. Tackling CSRF this way is no good as it might filter out valid character sequences. As I said before this needs to be solved on the output side of things, by properly escaping html entities. not on the input.

**Comment by objecttothis** [comment]
> > 
> 
> On the CSRF, I might need to read up, and I don't know if it can be solved by CI itself. I think it's better to solve this on the output side of things, by properly escaping html entities and script tags before render. not on the input.

OK, that's fine.  If it ends up being needed then we can bring it over from the current master and port it to CI4.  My only thought on the customization is that if there is a native solution that works as well, I think we should use the native solution since it makes it more resilient to upgrading the framework in the future.

**Comment by objecttothis** [comment]
> I still have a set of stashed changes that contain some of the things that still need to be applied, apparantly. I also made a script to convert the language files to the new format, so I can do that in go. Then after I can try to import in weblate.

Super. The weblate in this branch is very far behind, so you may want to apply changes from weblate to it before running your conversion script and uploading.

**Comment by jekkos** [comment]
I have moved the master versions of the translations to the new folder structure already, last thing to do is the format conversion

**Comment by objecttothis** [comment]
OK, I've gotten it down to 5 commits that need to be ported over to CI4 format.  I'll be on vacation until the 28th.  Anyone can feel free to port them over, but make sure that the changes are using CI4-specific syntax and functions.  I'll be back on the 28th.

**Comment by objecttothis** [comment]
The newest commits are on top in the list above, so they should be ported over bottom to top.

**Comment by jekkos** [comment]
@objecttothis I thought you were on vacation? I think we should rebase and squash again at some point. I think we can squash most commits except for the file move / renames

**Comment by objecttothis** [comment]
> @objecttothis I thought you were on vacation? I think we should rebase and squash again at some point. I think we can squash most commits except for the file move / renames. Otherwise let's continue testing and fixing stuff.

I am... I was being naughty.  Squash away.  See you on the 28th. Feel free to work on the runtime issues. I added a couple of todo's where I thought we needed to fix something, but I think it will be obvious when you load the application.

**Comment by objecttothis** [comment]
I'm going to close this for now.  If there are any other changes from the master that we need to merge in we can do so when it comes time to merge the PR into the master.
