### ISSUE TITLE
CI4: Load_config class not found

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3586]
In the CI4 branch, we are needing to replace hooks with events.  Currently loading the page renders:
![image](https://user-images.githubusercontent.com/17935339/199249686-95767d8f-b4df-499e-b9e5-62e565bb51cd.png)

The Load_config class now exists in app/Events/Load_config.php and seems to be namespaced properly.  The CI3 method of doing this allowed you to specify the director that the class was in but CI4 doesn't have this. 
Load_config is now called in an event in the app/Config/Events.php file.

**Comment by jekkos** [comment]
So does this mean we can get rid of the hooks.php? Currently git considers it removed, so I can just keep it that way?

**Comment by objecttothis** [comment]
> So does this mean we can get rid of the hooks.php? Currently git considers it removed, so I can just keep it that way?

Correct, hooks become Events in CI4. I have moved the hooks in hooks.php to Events.php for now.  We may need to adjust them later.

**Comment by objecttothis** [comment]
This is working now with the update to CI 4.3.1.  Either a bug was fixed or possibly a previous install of CI4 did not fully merge all the files properly.
