### ISSUE TITLE
Freezes when saving changes to items

### ISSUE THREAD

**Issue by LarsGMortensen** [opensourcepos/opensourcepos#3590]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: ffe492 and f8d798 (the latter being your own demo-server)
- PHP version is: 7.4 + whatever version your own demo-server is running.
- MySQL or MariaDB version is: MySQL + whatever version your own demo-server is running.
- OS and version is: whatever version your own demo-server is running.
- WebServer is: whatever version your own demo-server is running.
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

In 'items' (/public/items) when I update an item, the system often just freezes/hangs after pressing the 'Submit' button.
I can then exit the dialog box, open it again, make the changes again, and press the submit button again to save it - and sometimes it will save it on later tries.
I have noticed the error on both my own installation AND on your demo-server (https://dev.opensourcepos.org/items).
Also, I noted that both my own installation and your demo-server had multiple stock locations - so I dont know if the problem only appears if the system is set up with multiple stock locations?

Steps to reproduce:

1: Go to 'items' (/public/items)
2: Click the icon to update a given item
3: Make some changes to that item and try to save the item
4: Repeat this process a few times, until the system just hangs/freezes when clicking the submit-button

I have made the attached screen-recording to demonstrate the problem (please watch the video to the end, as the problem didn't appear until I had tried a few times - but on my own installation, I have often experienced the problem on the first attempt to update an item, so it doesn't only happen when updating multiple times in a row):

![w01riJUnNA](https://user-images.githubusercontent.com/26773745/200118173-a36a9128-cb71-4d43-a6df-5baf3bae0847.gif)

NOTE: In my attached video, I just updated the stock-quantities to trigger the issue - but on my own installation, I have also experienced the problem when editing other values for a given item (i.e. the barcode-value).

**Comment by hoststatic** [comment]
clear browser cache

**Comment by hoststatic** [comment]
> > clear browser cache
> 
> So, you want me to clear browser cache each and every time this issue occurs? ...first of all; what is that going to help? ...and secondly; the problem really occurs OFTEN, so that will be a ton of cache-clearing. ...and lastly; why does the issue occur? 

Have you tried on other browers, is you browser up to date?

**Comment by jekkos** [comment]
Can you open the developer tools / console (F12 on chrome I think) and check if there is any error message in there? Perhaps also open the network tab, keep it open and attach a screencap of this when the issues happens?

**Comment by LarsGMortensen** [comment]
> Can you open the developer tools / console (F12 on chrome I think) and check if there is any error message in there? Perhaps also open the network tab, keep it open and attach a screencap of this when the issues happens?

Sure, here's the console:

![ospos-wont-save-console-log-2022-11-07](https://user-images.githubusercontent.com/26773745/200310535-2c19606d-5419-4403-97ab-bf220701421f.png)

And here's the network tab:

![ospos-wont-save-network-tab-2022-11-07](https://user-images.githubusercontent.com/26773745/200310615-2df688bc-d08f-4dec-93a5-ca8c03ed4039.png)

**Comment by jekkos** [comment]
Can you try to disable csrf protection in config.php? The reason might be that the token is not correctly added to the form after some time

**Comment by LarsGMortensen** [comment]
> Can you try to disable csrf protection in config.php? The reason might be that the token is not correctly added to the form after some time

It has now been a couple of days sine I disabled CSRF protection as instructed - and it seems to have solved the issue (although I can’t be entirely sure, as it was a sporadic - but frequent - issue).
Anyway, it’s been a couple of days and I haven’t experienced the freezing-issue since I disabled CSRF protection - so I think your assumption was correct.

...but now the site doesn't have CSRF protection.

Is there a way to just disable CSRF protection for this specific function (saving/updating items)?

**Comment by hoststatic** [comment]
I have CSRF option enabled in config and no issue. I wonder if you tried on other device and the problem persisted.

**Comment by LarsGMortensen** [comment]
> I have CSRF option enabled in config and no issue. I wonder if you tried on other device and the problem persisted.

Yes, I have tried it on 2 different computers (each with Chrome and Firefox) and in Safari on my iPhone. The problem occured on them all - on my own OSPOS installation AND on your demo installation.

**Comment by SteveIreland** [comment]
I believe I may have stumbled across this issue in the 3.3.8 version.  I'll do more testing sometime this week to confirm.  But it sure did look similar to your video when I was doing some maintenance on several item records while testing another issue around the 6th or 7th item all of the sudden I couldn't change anything.  Had to reload to continue.

**Comment by jekkos** [comment]
Could you keep an eye on the js console in this case? It will reattach the token to the form after every ajax call. Perhaps if there's a call that fails it does not attach the token and then this might break the update mechanism.

**Comment by SteveIreland** [comment]
Haven't been able to recreate it yet, but I'm keeping an eye out for it.

**Comment by LarsGMortensen** [comment]
I still experience the issue in 3.3.9

**Comment by odiea** [comment]
When the issue shows it appears that the item pic is giving you issues. Click on that line for further info then post that.
