### ISSUE TITLE
Cashup summary -  Notes column missing icon

### ISSUE THREAD

**Issue by hasyrein** [opensourcepos/opensourcepos#3593]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: OSPOS Installation Info: 3.3.8 - ffe492
- OSPOS git commit hash is: ffe492
- PHP version is: 7.2.24-0ubuntu0.18.04.15
- MySQL or MariaDB version is: MySQL 5.7.40-0ubuntu0.18.04.1
- OS and version is: Ubuntu 18.04.6 LTS
- WebServer is:  Apache/2.4.29 (Ubuntu)
- Selected language is: en-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

![cashup](https://user-images.githubusercontent.com/26219611/201897372-b772b839-d2f0-457c-beae-cac099c78b2c.png)

At "Notes" column, it show `<span class="glyphicon glyphicon-remove"></span>`

**Comment by odiea** [comment]
It appears that note needs to be added to the escape clause in tabular_details.

**Comment by meierrom** [comment]
> It appears that note needs to be added to the escape clause in tabular_details.

@odiea : Can't say that I understand what you mean by that? Can you elaborate? Kind regards, Roman

**Comment by odiea** [comment]
In application/helpers/tabular_helper line 45 after item_pic" |note" needs to be added
 ``` 'escape' => !preg_match("/(edit|phone_number|email|messages|item_pic|note)/", key($element)) && !(isset($element['escape']) && !$element['escape']),```

**Comment by meierrom** [comment]
Thanks @odiea,

I was able to fix it as follows:

File: application/helpers/tabular_helper.php
Function: get_cashups_manage_table_headers

//array('note' => $CI->lang->line('cashups_note')),
array('note' => $CI->lang->line('cashups_note'), 'escape' => FALSE),

Kind regards,
Roman

**Comment by jekkos** [comment]
Tested in dev and checked in code, seems to be fixed.
