### ISSUE TITLE
Help with installation on RPI

### ISSUE THREAD

**Issue by BramWerbrouck** [opensourcepos/opensourcepos#3598]
Where can I find the proper installation instructions to install the opensourcepos on a raspberry pi 4 and raspbian?

Is there no complete image-file available?

I want to try the opensourcepos but I am a noob for installing on the RPI

**Comment by printgeek** [comment]
These are my notes. There are a few things you should do to make it more secure, but this will get you up and going. I did it yesterday on a Rpi 3b so I know its up to date.

sudo apt-get update && sudo apt install apache2 mariadb-server php libapache2-mod-php php-gd php-mysql php-bcmath php-intl php-mbstring php-curl nano -y
sudo a2enmod rewrite
sudo nano /etc/apache2/mods-enabled/dir.conf

update in bold:
<IfModule mod_dir.c>
    DirectoryIndex **index.php** index.html index.cgi index.pl index.xhtml index.htm
</IfModule>

sudo nano /etc/apache2/apache2.conf

update in bold:
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride **All**
        Require all granted
</Directory>

systemctl restart apache2

cd /var/www/html
sudo rm index.html
sudo wget https://github.com/opensourcepos/opensourcepos/releases/download/3.3.8/opensourcepos.3.3.8.ffe492.zip
sudo unzip opensourcepos*.zip
sudo rm opensourcepos*.zip
sudo chown -R www-data:www-data *
sudo chmod -R 755 *
sudo nano /etc/apache2/sites-available/000-default.conf

Change the DocumentRoot from /var/www/html to /var/www/html/public

sudo service apache2 restart
sudo mysql -u root -p
CREATE DATABASE ospos;
CREATE USER ‘admin’@‘localhost' IDENTIFIED BY ‘pointofsale’;
GRANT ALL PRIVILEGES ON ospos.* TO ‘admin’@‘localhost';
FLUSH PRIVILEGES;
quit;
cd /var/www/html/database
sudo mysql -uadmin -p ospos < database.sql

sudo nano ../application/config/config.php

Add encryption key (Go to https://randomkeygen.com/ to generate)

**Comment by BramWerbrouck** [comment]
HI,
thanks for the quick response. I just have a problem:
when entering the following command: `sudo mysql -u root -p` he ask for a pasword, so I use "1234" (without the quotes)

then creating the database, I assume this is ok

creating the uyser give me another problem:
```
CREATE USER 'admin'@'localhost' IDENTIFIED BY 'pointofsale';
ERROR 1396 (HY000): Operation CREATE USER failed for 'admin'@'localhost'
```

```
MariaDB [(none)]> GRANT ALL PRIVILEGES ON ospos.* TO 'admin'@'localhost';
Query OK, 0 rows affected (0.006 sec)
```
```
MariaDB [(none)]> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.002 sec)
```

after adding the encrypten key (forget one moment the user 'admin' is failed to create) How do I start the opensourcepos application?

**Comment by printgeek** [comment]
The only password that `sudo mysql -u root -p` should have prompted you for was your user password if you are running a recent version of raspbian, since you are running mysql as sudo. That password would be 'raspberry' unless you changed it from the default.
Run `sudo mysql -u root -p` from the command line again, use password 'raspberry' to run as sudo, and then type `SHOW DATABASES;` at the `mysql>' prompt. If you don't see a database called ospos then you weren't successful in creating the database and you need redo that whole block of commands.

**Comment by BramWerbrouck** [comment]
I checked with `SHOW DATABASES` and this is the result:

<img src="https://i.ibb.co/3dbfyKr/Screenshot-20221123-065618-Gallery.jpg">

so the database ospos is created.. but stil no luck to create the user admin

**Comment by BramWerbrouck** [comment]
I typed the ' myself (it wasn't copy paste) but I will have another look this evening. Can you tell me - if everything is well installed - how do I start this ?

**Comment by printgeek** [comment]
Oh, apache is installed and running, and you changed the document root, so all you have to do is point your browser to the ip address of the rpi, or if your router is configured for it you can just use the hostname. So if you are using the default hostname http://raspberrypi.local will take you to it
