### ISSUE TITLE
Understanding weighted barcodes

### ISSUE THREAD

**Issue by 33284** [opensourcepos/opensourcepos#3599]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.8.8
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Question 

i've been trying to understand how to get barcodes with weights or prices in them to scan on OSPOS, and found quite a number of (rather questionably helpful) answers. they all basically just sum up to what can be found here: 

https://github.com/opensourcepos/opensourcepos/wiki/Weighted-Barcodes

Could someone perhaps assist me in understanding how these dynamic barcodes work, so that i may perhaps assist in improving the wiki on this topic for new developers/users?

Thanks

**Comment by jekkos** [comment]
The idee is to write a regex expression that parses The barcode. It might Be a bit technical for regular users.                     Can you post an example you want to actieve?

**Comment by 33284** [comment]
Thanks for the reply @jekkos, your time is appreciated.

while i understand i need to write a regex expression, i'm not sure how to parse it as information into OSPOS. my scale prints an EAN13 barcode in the following sequence: 

"20", a 5 digit PLU code, 5 digits for the price, and 1 check digit 
which can be expressed like this as per the wiki from what i understand: 20{\d:5}{\d:5}{\d:1}
(Kindly correct me if i'm wrong)

i would then put this into the "Input Formats" field under configuration > barcode. 

my issue is that i don't know where to go from here.

what i've tried so far (unsuccessfully) is:
under configuration>barcode>barcode layout: set row 1 to "Category" or "Item name", row 2 to retail price, row 3 to none (Barcode content set to "Barcode"
when creating an item, set the barcode to 2000021{\d:5}{\d:1} (example) and select a field as "price entry"

Kindly advise? attached are examples of the barcodes my scale prints
![Image](https://user-images.githubusercontent.com/62174701/203045236-139ec585-37cf-4ad5-bd34-ba0f77da1e0a.jpeg)

**Comment by jekkos** [comment]
Maybe the wiki needs to be updated, I think this format was changed some time ago. The formatter is using the `token` variables now as also used in the invoices numbering. In this case `2000026{W:5}` would parse weight as 5 decimals there. It does divide by 1000. So if you generate barcodes yourself, you should take this into account.

**Comment by 33284** [comment]
Thanks Jekkos, however I still don't understand how or where to implement
the regex code, or how to set what data gets put in where. Could we perhaps
work together to improve the wiki on this issue?

**Comment by jekkos** [comment]
So the barcode format is what you need to configure here.

**Comment by 33284** [comment]
Sorry @jekkos if this comes off as offensive, but it feels as though you're being intentionally unhelpful.

nevertheless, i've managed to figure it out by going through the PHP files. moreover, the Price variable doesn't account for cents, and there is no option to parse the data as cents. in my case, i edited the Token_lib.php file (./Application/libraries/Token_lib.php, line 94) to divide the $parsed_results['P'] value by 100, which suits my purposes fine. 

here is my suggestion as to what the wiki should be updated to include, so that it might mitigate this sort of interaction in future, i will add it and leave it to you to edit/update/remove as you see fit:

Barcodes embedded with data, such as weight or price or item ID can be parsed with a regex code (this is simpler than it sounds).

let's assume your barcode is an EAN13 barcode (in theory, this should work for any type of barcode), and your barcode looks like this:

2000021019409

we can break this barcode up into the following segments:

20 (company or country code)
0002 (item ID)
1 (random digit for barcode uniqueness)
01940 (price)
9 (checksum digit)

in order to write out regex code for this barcode (assuming all other barcodes are generated the same) you would need to use the following:
20{I:4}\d{P:5}\d 
(worth noting, the last "\d" can be left out)

let's understand the components of this, and see what our options are:
20 is the company code, as mentioned above. this is an unchanging component.
{:} is to indicate that whatever is within these curly braces specifies a range of data that matches what is in the brackets.
I = item ID, and will always separate out whatever is within the specified range as the ID
W = weight/quantity of the item specified. this value is divided by 1000 by default.
P = price. by default, price does not consider cents. 
\d = digit placeholder. this digit will be ignored by default.

for more information about regex codes, please refer to this link: https://www.w3schools.com/php/php_regex.asp


the regex code you build ought to be placed into the "Barcode Formats" field, found in Configuration > Barcode

the item ID for the item you are scanning should be placed into the "Barcode" segment of the item you are wishing to add by scanning.

Should the price be embedded into the barcode, be sure to check the "amount entry" radio button on the item config screen.


WARNING: The following section is only recommended if you are technically inclined

should you wish to accomodate cents into your barcodes price, you will need to edit the following file accordingly:

File: Application/libraries/Token_lib.php
find line number 94
edit this line by adding " / 100" after "(double) $parsed_results['P']"

**Comment by jekkos** [comment]
Thanks for updating the wiki! I guess I was typing from a mobile phone so a bit short in my answer, sorry for this.
