### ISSUE TITLE
Error 500 or blank page after installing using install.md or wiki

### ISSUE THREAD

**Issue by FuseBarTV** [opensourcepos/opensourcepos#3600]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8 
- OSPOS git commit hash is: ffe49278fcbd936f34a9644debd0b7ff9bd83e31
- PHP version is: 7.4
- MySQL or MariaDB version is: MDB 10.3
- OS and version is: Ubuntu 20.04
- WebServer is: Apache
- Selected language is: English
- (If applicable) Docker installation: N/A
- (If applicable) Installation package for the LAMP/LEMP stack is: N/A

### Issue / Bug  / Question / New Feature

I have been working to get an instance running on my local Proxmox server, I'm specifically using LXC containers for the web server as it uses less resources and is better for my configuration. I have followed the Wiki and install.md, gone through heaps of containers uninstalling and reinstalling but I get the same error over and over, I've been working on this for about 4 days now and starting to think this is a bug... I would also like to state that php7.4-openssl doesn't exist as openssl comes pre-enabled on PHP. I have also tried on XAMPP on my other windows server but to no avail... get the same issue without fail.

If someone would be so generous to help me with my endeavor of installing this brilliant looking software that would be great! I would like to know how to do this efficiently without fail as I have an idea of how I will put this into a production environment and need it to be reliable, Thanks!

**Comment by jekkos** [comment]
HI, can you try to enable debug on your container? We need to know what is causing the 500 to understand what is wrong. It could be that eg your database is not reachable or the docker network is not setup correctly?
```docker exec "opensourcepos-ospos-1" /bin/sed -i 's/production/development/g' /app/public/index.php```

this enables debug for the container and will print an error message then instead of a blank page.

**Comment by FuseBarTV** [comment]
Oh, sorry. I think you may have misunderstood. I'm using LXC Containers to run it, so its a containerized Ubuntu instance, not Docker. Is there a way to output debug logs from there?

**Comment by jekkos** [comment]
Ok I saw you mentioned containers in your first post so I probably thought you were using docker. If you have a regular ubuntu then can you edit the index.php file and change the `production` with `development`. Then you should be able to see error logging

**Comment by FuseBarTV** [comment]
![image](https://user-images.githubusercontent.com/70828143/204167606-2743bbdb-ab6b-465d-b466-4c37ad4f9224.png)

Sorry, I'm uploading this from work. Does this say anything in specific?
