### ISSUE TITLE
Error sending email (gmail)

### ISSUE THREAD

**Issue by BramWerbrouck** [opensourcepos/opensourcepos#3601]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8 - ffe492
- OSPOS git commit hash is: 
- PHP version is: 7.4.33
- MySQL or MariaDB version is: 5.5.5-10.5.15-MariaDB-0+deb11u1
- OS and version is: Raspbian 
- WebServer is: Apache/2.4.54
- Selected language is: Dutch
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Question

If I want to email the ticket to a customer, I got the message “error sending the email”
This is what the settings are in settings and configuration - email:
Protocol: smtp
SMTP Server: smtp.gmail.com
SMTP Port: 587
SMTP Encryption: TLS
SMTP Time-out (s): 15
SMTP Username: myuser@gmail.com
SMTP Password: ******

What do I do wrong? Or do I have to install something else? Some general settings on Raspbian?

**Comment by jekkos** [comment]
Do you have 2fa setup for your gmail account? Perhaps try to send a mail fitst with another smtp client first to see if it works

**Comment by BramWerbrouck** [comment]
> You should add 2fa protection for google and enable less secure apps/app passwords, it would generate password for such case that you could use in ospos or other places

It isn’t possible anymore to change the gmail settings to “enable for less secure apps”

**Comment by daN4cat** [comment]
I can see that there is a wiki post explaining how to: https://github.com/opensourcepos/opensourcepos/wiki/Setting-Up-OSPOS-with-Postfix-and-Gmail-SMTP-Server
