### ISSUE TITLE
Can't complete a sale with due payment

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3606]
I would like to have dues as a payment method, but for some reason it does not show the complete button.
How the does a sale work with due payment in ospos? 
Am I missing something?

![image](https://user-images.githubusercontent.com/99489665/205894173-95e9b7ed-dff9-491c-8ebf-222fa9f6032b.png)

**Comment by odiea** [comment]
No Customer no Complete Button.

**Comment by hoststatic** [comment]
thanks @odiea,
