### ISSUE TITLE
Access forbidden! Error 403

### ISSUE THREAD

**Issue by maulanadiki** [opensourcepos/opensourcepos#3608]
please help, i have some issue , when i want to access localhost/ospos/application, i have some trouble like that, what i must to do ?
![image](https://user-images.githubusercontent.com/90600303/206067362-239ee646-f4e4-4aaf-9a89-d87eb88e3757.png)

**Comment by im-machakata** [comment]
That is a 'system' folder, try the **public** folder.
Do note that it's based on a framework

**Comment by eozalp** [comment]
> please help, i have some issue , when i want to access localhost/ospos/application, i have some trouble like that, what i must to do ?
> ![image](https://user-images.githubusercontent.com/90600303/206067362-239ee646-f4e4-4aaf-9a89-d87eb88e3757.png)
> 

Try localhost/ospos/public

Or if you need to access here you need to change .htaccess file.

**Comment by im-machakata** [comment]
> Or if you need to access here you need to change .htaccess file.
Here's a working htaccess file contents:

```
RewriteEngine on

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d [OR]
RewriteCond %{REQUEST_URI} ^/$
RewriteRule ^(.*)$ /public/$1 [L,QSA]

php_flag display_errors 1
```

**Comment by ekardian** [comment]
dude `localhost/public/` things for acces
