### ISSUE TITLE
Could not add payments on a due invoice sale

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3609]
Hi guys,
I would like to add more payments to an invoice sale for paying a due with parts.
In the older release version I think it allowed you to do that 
Am I missing something?
![image](https://user-images.githubusercontent.com/99489665/206497450-b3cad277-01d0-46e0-bcf9-e771060533d5.png)

**Comment by hoststatic** [comment]
Tried also in daily sales but could not find the option for finding add new payment, last time I remember it allowed you to have 2 payments for a sale (a due and a sale)

**Comment by odiea** [comment]
Look in helpers/locale_helper

**Comment by hoststatic** [comment]
which function?

**Comment by odiea** [comment]
function get_payment_options()
