### ISSUE TITLE
CI4: PHPUnit Testing composer package for CI4

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3610]
composer.json is currently using `"kenjis/ci-phpunit-test"` but this package is made for CI3 https://github.com/kenjis/ci-phpunit-test. We need to replace it with a CI4 compatible PHPUnit package.  @jekkos do you want to take this one?

**Comment by jekkos** [comment]
Yes I removed it locally but did not push yet.

**Comment by objecttothis** [comment]
Looks like this has been done.
