### ISSUE TITLE
CI4: Rework file permission and package checker for CI4

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3611]
CI4 requires PHP 7.4 or newer, mbstring, intl, php-json, php-mysqlnd, php-xml, libcurl, MySQL 5.1 or newer and 
/writable/ as well as it's subdirectories to be writable by apache.  We need to rework the checker code to make sure it's looking in the right places for the right permissions and packages to match the requirements. @WebShells I think you did the original work on this.  You interested?

#3592

**Comment by jekkos** [comment]
I asked @WebShells if he could have a look at this one.

**Comment by WebShells** [comment]
Hello everyone!
Will do, when is the due for CI4 ? 
@objecttothis just saw this issue am not receiving repos emails anymore... Thanks @jekkos!

**Comment by objecttothis** [comment]
@WebShells sorry you're not getting the notifications.  I'm not sure why, but it isn't anything we've intentionally done.  The CI4 upgrade is moving along at a little quicker pace now that we have a few people working on it as they have time and are healthy, but the more people working on it, the faster we will be able to release 3.4.0.  You should probably try to subscribe to notifications on #3858 since that is the PR for the CI4 branch.  the branch to check out is called `ci4-branch`

**Comment by WebShells** [comment]
@objecttothis am already subscribed to it and to the repo yet receiving nothing. Anyway i'll check that... Thanks

**Comment by objecttothis** [comment]
This is a screenshot of the GitHub app on Android when you click notifications. I only get them when I have participated in an issue or if I am mentioned. Maybe you could look at what is enabled for you.

![Screenshot_2023-11-10-14-50-46-66_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/opensourcepos/opensourcepos/assets/17935339/a064f067-67d1-48c5-9a60-ee1d0c5dc20b)

**Comment by objecttothis** [comment]
@WebShells do you still plan on working on this?

**Comment by WebShells** [comment]
@objecttothis Even if am mentioned nothing received.

**Comment by objecttothis** [comment]
> @objecttothis Even if am mentioned nothing received. 

Potentially we could remove all your permissions and readd them. Do you get notifications for other GitHub repos you are participating in? If not, I doubt that will help.
