### ISSUE TITLE
Multiple checkouts

### ISSUE THREAD

**Issue by BramWerbrouck** [opensourcepos/opensourcepos#3612]
IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

  Reporting an issue of an unmodified OSPOS installation
  Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
  Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
  Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
  Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
[] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
  Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.
Installation information

OSPOS version is: 3.3.8 - ffe492
OSPOS git commit hash is:
PHP version is: 7.4.33
MySQL or MariaDB version is: 5.5.5-10.5.15-MariaDB-0+deb11u1
OS and version is: Raspbian
WebServer is: Apache/2.4.54
Selected language is: Dutch
(If applicable) Docker installation:
(If applicable) Installation package for the LAMP/LEMP stack is:
Issue / Question

How can I connect multiple raspberry pi’s to one ‘master with the database installed’ so imagine you have more than one checkout…

**Comment by hoststatic** [comment]
What do you mean?

**Comment by BramWerbrouck** [comment]
I mean: what if I have more than one checkout in my store. Each time a screen connected to a raspberry pi and a barcodescanner. The whole system should use only one database. So just one RPI is the master.. how can I achieve such a setup?

**Comment by hoststatic** [comment]
You could create multiple users and have multiple checkouts?
I don't understand you well

**Comment by BramWerbrouck** [comment]
I can create multiple users, this is not the issue, But physical I have more than one checkout point in my store, see picture <img src="https://www.kassahuur.nl/wp-content/uploads/2019/09/slide_mechandis_verkoop_3.jpg">

But I don't want to have different databases. I mean: If checkout No°1 sells item X, the stock you see in checkout No°3 should be changed..

**Comment by hoststatic** [comment]
No problem, create multiple users and have same stock location.

**Comment by hoststatic** [comment]
deploying ospos with all those checkout, what do you want to do ? Explain please
Does ospos fit your your needs?

**Comment by BramWerbrouck** [comment]
> No problem, create multiple users and have same stock location.

This does not work. the opensourcePOS is installed several times on different RPI's. even if I set the same stock location. There is no connection between the different checkout's. Do I have to install the opensourcePOS "in the cloud"? If so, I want to use one of the existing RPI's as master (where the opensourcePOS runs on it) but I don't have an id how.

**Comment by chunter2** [comment]
I think you may be misunderstanding the design of ospos.  It's a client/server type model.  So the server is your ospos install and the client is a web browser.  So in your case you only need to install ospos on one RPI and the rest of the check-outs would just point their browsers to the first one.  I'd suggest not using the RPI that you installed ospos on as a check-out.  I'd leave that one in a back room somewhere.  Hope this makes sense.

**Comment by BramWerbrouck** [comment]
> I think you may be misunderstanding the design of ospos. It's a client/server type model. So the server is your ospos install and the client is a web browser. So in your case you only need to install ospos on one RPI and the rest of the check-outs would just point their browsers to the first one. I'd suggest not using the RPI that you installed ospos on as a check-out. I'd leave that one in a back room somewhere. Hope this makes sense.

OK, so if I could browse (with an explorer) from any other device to the RPI (where the ospos) is installed, this should work? Any changes I need to make on my RPI to make this accessible from other devices?

**Comment by hoststatic** [comment]
You install in one device and use other device browser (chromium firefox) to access web interface. You could create multiple users for identifying the checkout. Please explain better

**Comment by BramWerbrouck** [comment]
Oh, I feel so stupid.. I installed ospos on every RPI. But ok, everything works fine now
