### ISSUE TITLE
500 error only on Sale Module 

### ISSUE THREAD

**Issue by w002qaa** [opensourcepos/opensourcepos#3613]
Hello,

I am using OSPOS on online host. It was working fine. Suddenly, when I try to do sale give me HTTP ERROR 500. If I try to check all old sale, no data is showing.

I think the host made some changes in PHP configurations, but I could figure it out.

Is any way to know reason that cause the error?

**Comment by odiea** [comment]
go to config setup and see what version the php is

**Comment by w002qaa** [comment]
It is now PHP 7.2, however I tried to change to PHP 5.5, PHP 5.6, PHP 7.0, PHP 7.1, PHP 7.2, PHP 7.3, and PHP 7.4 and not helping

Here OSPOS version --> $config['application_version'] = '3.2.3';

**Comment by odiea** [comment]
Jekkos recommends the following. Can you open the developer tools / console (F12 on chrome I think) and check if there is any error message in there? Perhaps also open the network tab, keep it open and attach a screencap of this when the issues happens?

**Comment by w002qaa** [comment]
Here the error

![error](https://user-images.githubusercontent.com/6653267/208239779-bb30be95-3a33-4f49-93f8-947a179d02b2.png)

**Comment by odiea** [comment]
Check your Customer module for any errors?

**Comment by w002qaa** [comment]
How can I check it? 

FYI: I copied the system to different hosting account with same the company, and it is working fine. Only in this account

**Comment by odiea** [comment]
Has the database version changed?

**Comment by w002qaa** [comment]
I am trying to find if the database change or not. It is still not working in the main account. I have to fix it to work in the main account

**Comment by odiea** [comment]
You can double click and expand the customer error for further info

**Comment by w002qaa** [comment]
![error1](https://user-images.githubusercontent.com/6653267/208242620-9321284f-1694-4b99-8f4d-e82fbfbd967d.png)

![error2](https://user-images.githubusercontent.com/6653267/208242629-9a601798-760e-4a2d-9cda-e379cd4fe854.png)

**Comment by odiea** [comment]
It looks like something with the customers is giving you issues Have you recently added a new customer?

**Comment by w002qaa** [comment]
Not only in customers, daily sale has same issue. There are no data showing 

![error3](https://user-images.githubusercontent.com/6653267/208244384-7ade3d82-2150-486a-aef0-a0a26fffa736.png)

**Comment by odiea** [comment]
If all of your Sales are customer based it still may be an issue

**Comment by w002qaa** [comment]
Okay any suggestion to solve this issue

**Comment by odiea** [comment]
Are any Customers showing in the Table?

**Comment by w002qaa** [comment]
Yes, there are four customers

**Comment by odiea** [comment]
When you got it working did you use a backed up Database or the original?

**Comment by w002qaa** [comment]
Hi @odiea 
I used a backed up database

**Comment by hoststatic** [comment]
Do you have "'" or special characters in first_name, last_name ospos_people table?

**Comment by hoststatic** [comment]
> Hi @odiea I used a backed up database

You could restore db by parts of querries and see where it hangs

**Comment by hoststatic** [comment]
how is configured your .htaccess file?
Have you made any modifications in Customers or Sales
You have problems with post request

**Comment by odiea** [comment]
Try going into application/config/config and change the error level from 0 to 1 and then see if any info is displayed in application/logs

**Comment by w002qaa** [comment]
> how is configured your .htaccess file? Have you made any modifications in Customers or Sales You have problems with post request

I have not change anything at all

**Comment by w002qaa** [comment]
> Try going into application/config/config and change the error level from 0 to 1 and then see if any info is displayed in application/logs

`
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-12-25 15:22:46 --> 404 Page Not Found: Images/favicon.ico
ERROR - 2022-12-25 18:23:27 --> Query error: Too many active concurrent transactions - Invalid query: CREATE TEMPORARY TABLE IF NOT EXISTS ospos_sales_items_temp (INDEX(sale_id))
			(
				SELECT
					sales.sale_id AS sale_id,
					AVG(sales_items.discount_percent) AS avg_discount,
					SUM(sales_items.quantity_purchased) AS quantity
				FROM ospos_sales AS sales
				INNER JOIN ospos_sales_items AS sales_items
					ON sales_items.sale_id = sales.sale_id
				WHERE sales.customer_id = '2'
				GROUP BY sale_id
			)
ERROR - 2022-12-25 18:23:27 --> Query error: Table 'u60131_hadithah.ospos_sales_items_temp' doesn't exist - Invalid query: SELECT SUM(sales_payments.payment_amount) AS total, MIN(sales_payments.payment_amount) AS min, MAX(sales_payments.payment_amount) AS max, AVG(sales_payments.payment_amount) AS average, ROUND(AVG(sales_items_temp.avg_discount), 2) AS avg_discount, ROUND(SUM(sales_items_temp.quantity), 0) AS quantity
FROM `ospos_sales`
JOIN `ospos_sales_payments` AS `sales_payments` ON `ospos_sales`.`sale_id` = `sales_payments`.`sale_id`
JOIN `ospos_sales_items_temp` AS `sales_items_temp` ON `ospos_sales`.`sale_id` = `sales_items_temp`.`sale_id`
WHERE `ospos_sales`.`customer_id` = '2'
AND `ospos_sales`.`sale_status` = 0
GROUP BY `ospos_sales`.`customer_id`
ERROR - 2022-12-25 18:23:27 --> Severity: error --> Exception: Call to a member function row() on boolean /home/u60131/domains/alksest.com/public_html/hadithah/application/models/Customer.php 136
ERROR - 2022-12-25 18:26:00 --> Severity: Warning --> count(): Parameter must be an array or an object that implements Countable /home/u60131/domains/alksest.com/public_html/hadithah/application/models/Customer.php 352
ERROR - 2022-12-25 18:26:03 --> Query error: Too many active concurrent transactions - Invalid query: CREATE TEMPORARY TABLE IF NOT EXISTS ospos_sales_items_temp (INDEX(sale_id))
			(
				SELECT
					sales.sale_id AS sale_id,
					AVG(sales_items.discount_percent) AS avg_discount,
					SUM(sales_items.quantity_purchased) AS quantity
				FROM ospos_sales AS sales
				INNER JOIN ospos_sales_items AS sales_items
					ON sales_items.sale_id = sales.sale_id
				WHERE sales.customer_id = '5'
				GROUP BY sale_id
			)
ERROR - 2022-12-25 18:26:03 --> Query error: Table 'u60131_hadithah.ospos_sales_items_temp' doesn't exist - Invalid query: SELECT SUM(sales_payments.payment_amount) AS total, MIN(sales_payments.payment_amount) AS min, MAX(sales_payments.payment_amount) AS max, AVG(sales_payments.payment_amount) AS average, ROUND(AVG(sales_items_temp.avg_discount), 2) AS avg_discount, ROUND(SUM(sales_items_temp.quantity), 0) AS quantity
FROM `ospos_sales`
JOIN `ospos_sales_payments` AS `sales_payments` ON `ospos_sales`.`sale_id` = `sales_payments`.`sale_id`
JOIN `ospos_sales_items_temp` AS `sales_items_temp` ON `ospos_sales`.`sale_id` = `sales_items_temp`.`sale_id`
WHERE `ospos_sales`.`customer_id` = '5'
AND `ospos_sales`.`sale_status` = 0
GROUP BY `ospos_sales`.`customer_id`
ERROR - 2022-12-25 18:26:03 --> Severity: error --> Exception: Call to a member function row() on boolean /home/u60131/domains/alksest.com/public_html/hadithah/application/models/Customer.php 136

`

**Comment by w002qaa** [comment]
@odiea Any ide to solve the this problem

**Comment by odiea** [comment]
All I can suggest is to use your current backup db to see if that changes the issue.

**Comment by nukerj** [comment]
También pude ser que se haya eliminado algún atributo en la tabla Customes o people como también pudieron haber agregado uno nuevo y es necesario agregarlo al código

**Comment by ekardian** [comment]
oooh i saw that problem, its about bad characters in your comment field, or sometimes i give that error on my firefox with a lot of advice blockers, i sugest, manually clear the comments or delete your last sells and try, U KNOW U CAN BACKUP ALL... GG GOOD 2023

**Comment by w002qaa** [comment]
![image](https://user-images.githubusercontent.com/6653267/214826232-b9c50a80-2b4f-41ac-b020-58354d59b743.png)

If I comment this function "get_stats($customer_id)" and return 0; it working but no the daily sales return nothing.

**Comment by w002qaa** [comment]
Finally, I solved the issue by changing the server location in Hostinger account 

https://support.hostinger.com/en/articles/5577027-how-to-transfer-your-hosting-account-to-a-different-server
