### ISSUE TITLE
store payment history inside the invoice for the new payments 

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3614]
Hello guys,
I would like to track all the payments in a logging receipt or inside invoice itself.
Let say I make a due sale with type invoice,
I check out with no payment and later add payments,
when the client do a partial payment I would like to print a receipt that shows he payed x amount of money.
It could be done but what about storing all payments history that a client does for in a invoice sale. 

How you guys deal with that?
 I am thinking of  generating a payment mandate when a new payment is added or saving the history of payments in the invoice itself it does the job

**Comment by nukerj** [comment]
Greetings, friend, this can be done with two new modules that I developed to keep track of debts, the modules if accounts receivable and account statements.  an amount is added or paid to the client's debt and in the accounts receivable and account statements module you will see payments received and pending debt.  Also in the customer information you can see payments made and outstanding balance or outstanding debt.  If you wish, I can sell you this development, contact me via WhatsApp at +584126447407 or telegram @jvilchez

**Comment by nukerj** [comment]
Hi @hoststatic it's other change whaching the vídeo 

News Payments Method from BD and multi Currency 💲💵
It's NioPos by Andriux990 and me, powered by OSPOS
If you need it contact me to

telegram. @JVilchez
WhatsApp. +584126447407
Email vilchezjohnny82@gmail.com

https://user-images.githubusercontent.com/47283494/224935950-41761344-d5c0-4285-884f-7f771fff7478.mp4
