### ISSUE TITLE
Ability to edit current receiving/sale by adding/removing new items

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3617]
Ability to edit a sale or receiving for example if the aim is to add/remove items to an existing sale/receipt

**Comment by SteveIreland** [comment]
Meant to comment that it's my understanding that in some countries its against regulations to change a sale after it's closed.  It would need to be cancelled and recreated.   That is why, as a policy, OSPOS doesn't allow changes to sales/invoices after they are issued.
