### ISSUE TITLE
Feature request: A Total line at the end of Summary Reports

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3623]
I'd like to see a Total line at the end of the Summary Reports like there is on the Daily Sales Report that would update when search criteria is entered, also like the Daily Sales Report.  This would be the total of the columns that are visible.  This would save having to export the report and sum the columns in a spreadsheet application.  

Thanks

**Comment by nukerj** [comment]
Contact to telegram @jvilchez or vilchezjohnny82@gmail.com i can do it

**Comment by ekardian** [comment]
try #2293
try https://github.com/reportico-web/reportico

**Comment by chunter2** [comment]
What I'm looking for is just this
![image](https://user-images.githubusercontent.com/531129/211557621-fe6384cc-222b-4e4d-883f-6212c83621c5.png)
but in Summary Reports like this
![image](https://user-images.githubusercontent.com/531129/211558220-c179ed59-7393-4a11-b3c4-6c44360f735d.png)
This would be the total for the page (what's showing), not the full report.
