### ISSUE TITLE
Warning: PHP Startup: Unable to load dynamic library 'libmcrypt' (tried: c:/wamp64/bin/php/php8.2.0/ext/libmcrypt (The specified module could not be found), c:/wamp64/bin/php/php8.2.0/ext/php_libmcrypt.dll (The specified module could not be found)) in Unknown on line 0

### ISSUE THREAD

**Issue by chrissasare** [opensourcepos/opensourcepos#3630]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is:3.2.3 
- OSPOS git commit hash is:3.2.3 
- PHP version is: 8.2.0
- MySQL or MariaDB version is:8.0 
- OS and version is: 3.3.0
- WebServer is: 
- Selected language is: english
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by odiea** [comment]
Php 8 is not supported. Maybe in the future

**Comment by SteveIreland** [comment]
Agreed ... after the CI4 upgrade we should go for PHP8 ASAP.   My ISP is strongly encouraging it. :-)   Maybe as soon as we get it building and somewhat functional we can throw in PHP8 just to get it out of the way.

**Comment by o-data** [comment]
Some of the package I use minimum requirement is PHP 8, which is unfortunately. I wanted to use Open POS but I guess have to compromise or wait for PHP 8 support.
