### ISSUE TITLE
CI4: Possible duplicate import of PSR LoggerInterface

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3633]
PHPStorm is complaining about two different instances of PSR\Log\LoggerInterface classes.

One is in `\vendor\psr\log\PSR\log` and the other is in `\vendor\codeigniter4\framework\system\ThirdParty\PSR\log`

![image](https://user-images.githubusercontent.com/17935339/215047869-aa10558a-3cb1-4e42-90a6-e7b49706c169.png)

![image](https://user-images.githubusercontent.com/17935339/215047805-befe5298-443f-48a8-a1b3-41fc0f6010e6.png)

It seems like since PSR\log is now included in CI4, we should remove the duplicate.  This happens during the npm install and I'm seeing the psr/log reference in the composer.lock file as a CodeIgniter dependency. I'm not sure the best way to remedy this because I believe the composer.lock file is automatically generated.

**Comment by jekkos** [comment]
Could be handled as follows: https://stackoverflow.com/questions/34637657/is-it-possible-to-ignore-child-dependencies-in-composer-config

**Comment by objecttothis** [comment]
#4091 fixes this issue.
