### ISSUE TITLE
RuntimeException --Class Attribute already exists and doesn't extend CI_Model

### ISSUE THREAD

**Issue by MambJose** [opensourcepos/opensourcepos#3636]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

_______________________________________________________________________________________________________________________________

Ospos version 3.3.8
-PHP 7.4.33
Installed on server (bluehost)
Installation by 3 modes
1.downloading(github) and uploading to server--Same failure
  note: the latest version does not come with the vendor folder*discarded

2. Same as the first option but with a previous version (3.3.7)*discarded
same fault

3.The one that I have installed from the Softaculus repertoire that has bluehost

![openpos](https://user-images.githubusercontent.com/123847730/215300072-c5bc263e-e04a-4d0a-92fa-e8fb0ed4d8ce.png)

The installation presented me with basic problems that have already been solved, the developer mode is on

The problem in question is this:

![problema](https://user-images.githubusercontent.com/123847730/215300207-2db4ed2a-7dbe-40d1-85cc-76683aa5b465.png)

Honestly I was lost

I understand more or less the problem, but I don't know how to solve it
The only thing modified is the database.php in configuration and the public index for developer mode

I will load the files of the error in question

[index.txt](https://github.com/opensourcepos/opensourcepos/files/10528787/index.txt)

[database.txt](https://github.com/opensourcepos/opensourcepos/files/10528788/database.txt)

[Loader.txt](https://github.com/opensourcepos/opensourcepos/files/10528789/Loader.txt)

If more information is required I will be attentive

**Comment by odiea** [comment]
Did you download the prebuilt file listed under the Install.md section of this page?

**Comment by MambJose** [comment]
download this for one of the mentioned tests opensourcepos.3.3.8.ffe492.zip

**Comment by MambJose** [comment]
download this for one of the mentioned tests opensourcepos.3.3.8.ffe492.zip

(I pressed the close button by mistake)

**Comment by SteveIreland** [comment]
That looks like the zip file I'm currently using in a production environment - unfortunately (or fortunately?) I'm not yet using the Attributes feature.  Waiting for a use case to pop-up.

**Comment by jekkos** [comment]
Not sure what could cause this, the zip might be incomplete? Perhaps check with softaculous support as you are probably using their paid service?

**Comment by saadismail** [comment]
https://github.com/opensourcepos/opensourcepos/issues/3913 might be relevant.
