### ISSUE TITLE
new customer modal not work

### ISSUE THREAD

**Issue by frog-waha** [opensourcepos/opensourcepos#3637]
- OSPOS version is: 3.3.8 - [ffe492]
- PHP version is: 7.4.8
- Selected language is:  English

add new customer modal not work , when i open only pop up with blank (no data field)
and all others modal works well
![Capture](https://user-images.githubusercontent.com/115638886/215460881-948dd2de-48eb-4beb-936d-05425344d2b6.PNG)

**Comment by jekkos** [comment]
Perhaps check you javascript console, or enable php error logging to see if you find any error message

**Comment by frog-waha** [comment]
sorry to ask , how to enable php error logging ?

**Comment by odiea** [comment]
Go into application/config/config about half way down line 261 and change it 2 1.
$config['log_threshold'] = 1;

**Comment by ahmzus** [comment]
log file , Table ospos_sales_items_temp not exist in my data base and I made sure that the user has all permissions
![Capture](https://user-images.githubusercontent.com/69791889/215881171-58eb195c-aace-49f3-a32f-1e43d3ea9075.PNG)
and js error in /htdocs/public/dist/
![Capture1](https://user-images.githubusercontent.com/69791889/215881926-ecd18810-ad9f-4344-8122-e41a1abc5bbe.PNG)
