### ISSUE TITLE
Product and attribute.

### ISSUE THREAD

**Issue by jonnyfrm1977** [opensourcepos/opensourcepos#3638]
Hello. And thanks for the help.
I have a question regarding product introduction.
I have products that have all the identical fields, only the one attribute changes, the size.
Is there the possibility of creating the product and selecting several options from the attribute at the same time? 
And that the program automatically generates the rows of products.

**Example:**
Name: AAA
Category: Shoes
Attribute: size(25,26,27,39)

**Result:**
Item:
AAA 25
AAA 26
AAA 27
AAA 39

Something along the lines of "Woocommerce attributes and variations".

Thanks.

**Comment by objecttothis** [comment]
This feature is not currently implemented.  I think what you are suggesting would be sort of a product generator.  A similar feature would be to have an attribute with a multi-select dropdown, but that would allow you to select multiple dropdown items in a single attribute on an item, not generate other items.

**Comment by jekkos** [comment]
I would always mode one attribute value at a time, you can easily create variations of the same product by using the 'new' button in the product modal dialog. It will keep your dialog open and remove only the barcode field if I'm not mistaken. Then you can just select that one field that is different and scan your product, which will then automatically allow you to create a next item. 

The default action on the modal is still the new if I'm not mistaken.
