### ISSUE TITLE
customer modal not work

### ISSUE THREAD

**Issue by frog-waha** [opensourcepos/opensourcepos#3644]
OSPOS version is: 3.3.8 - [ffe492]
PHP version is: 7.4.8
Selected language is: English
add new customer modal not work , when i open only pop up with blank (no data field)
and gearte repots not works with same log errro
and all others modal works well 
log file , Table ospos_sales_items_temp not exist in my data base and I made sure that the user has all permissions
and js error in /htdocs/public/dist/
![215881926-ecd18810-ad9f-4344-8122-e41a1abc5bbe](https://user-images.githubusercontent.com/115638886/216286986-8d3b00c9-9f69-40f2-801c-27afef3f4291.png)
![215881171-58eb195c-aace-49f3-a32f-1e43d3ea9075](https://user-images.githubusercontent.com/115638886/216287055-cafb0012-a072-44dc-b8a4-44c1799d5c2e.png)

**Comment by jekkos** [comment]
I think you do not have the database permissions setup correctly, at leas that is what the error message is saying?
