### ISSUE TITLE
Adding image file name that already exists in the folder does not overwrite the file

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3652]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 78c8c2
- PHP version is: 7.4
- MySQL or MariaDB version is: 8.0
- OS and version is: FreeBSD 13
- WebServer is: Apache 2.4
- Selected language is: en-US
- (If applicable) Docker installation: N/A
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

If a file by the same name exists when you try to overwrite the image for an item, it submits but then the file is not overwritten.  This is likely an issue with configuration in the code to not overwrite.  We also have a similar issue where the if we have two ISBNs that are the same but are a different book, we can't have a picture by the same name.  For security, we probably shouldn't be storing the images with the original name anyway, but instead assigning a UID and perhaps keeping them in a database table.

I'll assign this to myself for now, but if anyone wants to take it, feel free.  I may not get around to resolving it for a bit since we have the CI4 conversion.

**Comment by jekkos** [comment]
filenames are assigned a hash now, so overwriting should not be an issue anymore
