### ISSUE TITLE
Refused Content-Security-Policy Error

### ISSUE THREAD

**Issue by fu4dfauzi** [opensourcepos/opensourcepos#3655]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: ffe492
- PHP version is: 7.4
- MySQL or MariaDB version is: 5.7.40
- OS and version is: Ubuntu 20.04
- WebServer is: Apache 2.4.53
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: LAMP

### Issue / Bug  / Question / New Feature

Hello, I got this error message. Please help me to solve it.

![image](https://user-images.githubusercontent.com/11000913/218244764-823e9ed9-7286-42b3-bf35-6fc3f1e6dc6b.png)

**Comment by jekkos** [comment]
Do you have a  rewrite  rule enabled for your domain? IT should not block the request of both js and backend live on the same domain

**Comment by fu4dfauzi** [comment]
Hi, Jekkos.

I don't change the rewrite rule.

How do I suggest IT to unblock it? Any advice is appreciated.

Warm regards,
Fuad

Pada tanggal Sen, 13 Feb 2023 pukul 15.11 jekkos ***@***.***>
menulis:

**Comment by jekkos** [comment]
For some reason your browser might be making this request to a different domain then the one you are browsing on. Can you compare what is in the url bar with what is removed in red in your picture? Is it the same domain name?

The self directive allows you to only load javascript from the domain the site is running on. I also see that the request goes to http/ Do you use https or plain http?

**Comment by fu4dfauzi** [comment]
Yes, it is the same domain. I also provided an SSL Certificate for
the domain and no issue(s) with other websites on the server. That's why I
am confused.

Pada tanggal Sel, 14 Feb 2023 pukul 03.41 jekkos ***@***.***>
menulis:
