### ISSUE TITLE
CI4: bootstrap3-dialog

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3658]
We currently have bower.json referring to bootstrap-3 and other bootstrap version 3 stuff.  But the project file is acquiring bootstrap 5 stuff. 

It seems to me that bower needs to pull in bootstrap 5.   I'm also curious as to what the plans are for https://github.com/nakupanda/bootstrap3-dialog.  Is this no longer a dependency?

**Comment by SteveIreland** [comment]
@objecttothis  Okay.  No one has responded. So, more often than not, that means I'm confusing everyone with my question.

In package.json we are installing bootstrap@^5.2.3.   In bower.json we are still referring to version 3 stuff.  I'm assuming that my task is to remap those to their version 5 equivalent if I can find an equivalent.  

The github project that provides the bootstrap3-dialog appears to be abandoned and I don't know if there is a good way to determine if any of the forks picked it up and upgraded it to the current level of version 5. 

Does ANYONE know if there a way to do that without going through each of the forks one by one to check to see if they are trying to keep that project alive?  I tried doing that on another abandoned project with 40 forks and that was painful enough.

**Comment by objecttothis** [comment]
Sorry @SteveIreland. I simply didn't see it for some reason. In the future it might help to reference @opensourcepos/org so it notifies the team. So, my thought would be the fewest changes needed to get the CI4 version working is best. Then we can upgrade bootstrap in a separate featureset.  That said, I think some of this is my fault. In an effort to fix build issues I started that ball rolling. So one approach we could make is to roll back the changes to packages.json and all the other build related files. Then only bump up or change what is needed specifically for CI4 or production security vulnerabilities. Let me know what you think.

**Comment by objecttothis** [comment]
If you do go that route then probably look at the composer.json that comes with codeigniter 4... There are a few dependency changes there... I don't know enough to know how many of those differences are required... Perhaps @jekkos can weigh in.

**Comment by SteveIreland** [comment]
Ah, okay ... so we are staying with bootstrap 3 for now.  That will certainly make life simpler.  :-) 

@opensourcepos/org

**Comment by objecttothis** [comment]
That way we can separate featuresets as much as possible.

**Comment by jekkos** [comment]
Yes we are only using bs5 in the login page for now. Upgrading bootstrap will be one of the next projects, after finishing the CI4. @BudsieBuds did try out a couple of things already on that front.

**Comment by jekkos** [comment]
So the bootstrap5 dependency is only used in the login page for now. It should not leak into the actual header as it might create conflicts.
