### ISSUE TITLE
CI4: Changes to be aware of

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3689]
@opensourcepos/org This issue is here because Github discussions is not working properly. I'll try to list things here to be aware of when contributing to the repo as I run into them.  I'm sure I'll forget stuff because I'm starting this mid-way through the conversion to CI4

### System Requirements
- PHP 7.4 is now the minimum version to run OSPOS due to CI4. All the way up to PHP 8.2 should work properly.

### Models
- There is now a allowedfields array for each model that needs to have all the column names which are allowed to be modified during save, insert or update function calls.  If you add a column in a migration, you need to also add it to this array if it should be allowed.  This is a security feature, so we need to use it. Do not put primary keys in the allowedfields array.

**Comment by SteveIreland** [comment]
damned frameworks

**Comment by SteveIreland** [comment]
With the introduction of typehints the field must not be null and must be of the requested type.  The value passed cannot be any other type..

Changing a typehint to conditional by preceding it with a question mark allows us to pass in either a null or a value of the same type.  To resolve this issue I initially changed the initialization of an empty object's properties from an empty string to a null.

It also appears that the checkbox form control must be evaluated as either true or false  I was having a problem with the boolean values (actually tinyint values) being initialized to nulls.  It was complicating things.  So I changed the initialization of empty object properties to a value appropriate to the data type of the property.  Numeric fields will be initialized as 0 and string values will be initialized to null.   I'm also setting the value of the key field for the object to the new constant NEW_ENTRY which translates to our originally overused -1.

**Comment by objecttothis** [comment]
> It also appears that the checkbox form control must be evaluated as either true or false I was having a problem with the boolean values (actually tinyint values) being initialized to nulls. It was complicating things. So I changed the initialization of empty object properties to a value appropriate to the data type of the property. Numeric fields will be initialized as 0 and string values will be initialized to null. I'm also setting the value of the key field for the object to the new constant NEW_ENTRY which translates to our originally overused -1.

@SteveIreland you may or may not run into this but the optional feature to force "category" as a dropdown to prevent users from misspelling categories when they entered items has an attribute definition ID of -1. This is because an ID can't be 0 in the attribute definition table, so I had to make 0 represent a new_attribute in the code. It's really the exception to the rule on -1 meaning a new entry.
