### ISSUE TITLE
ERROR 500

### ISSUE THREAD

**Issue by Dilsh93** [opensourcepos/opensourcepos#3696]
I have getting this error after login The localhost page isn’t working localhost is currently unable to handle this request. **HTTP ERROR 500** **I am using OpensourcePos V3.3.8  mamp server latest version and windows 11 Pro Google Chrome Browser.** **_Please help me...._**

**Comment by SteveIreland** [comment]
Help us help you.   Provide more info.  What version of PHP is mamp configured to use.  3.3.8 does not support PHP 8. 

Did you read the installation requirements?   Did you set up the credentials to the database correctly   Etc.

Review the INSTALL.MD to see if there is some configuration requirement that is missing.

**Comment by Dilsh93** [comment]
Please tell me which is the most suitable **PHP** Version for **OSPOS 3.3.8** Also, explain to me the points that should be paid attention to while preparing the database.  It worked after reading **Install.md**.  But **HTTP Error 500** came when trying to login.

**Comment by SteveIreland** [comment]
From INSTALL.md:

Server Requirements
**PHP version 7.2 to 7.4 are supported, PHP version ≤5.6 and 8.0 are NOT supported.** 

Please note that PHP needs to have the extensions php-gd, php-bcmath, php-intl, php-openssl, php-mbstring and php-curl installed and enabled.

MySQL 5.5, 5.6 and 5.7 are supported, also MariaDB replacement 10.x is supported and might offer better performance.

Apache 2.2 and 2.4 are supported. Nginx should work fine too, see [wiki page here](https://github.com/opensourcepos/opensourcepos/wiki/Local-Deployment-using-LEMP).

Raspberry PI based installations proved to work, see [wiki page here](https://github.com/opensourcepos/opensourcepos/wiki/Installing-on-Raspberry-PI---Orange-PI-(Headless-OSPOS)).

For Windows based installations please read [the wiki](https://github.com/opensourcepos/opensourcepos/wiki). There are closed issues about this subject, as this topic has been covered a lot.
