### ISSUE TITLE
CI4: Customer data isn't being displayed.

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3701]
I'm not sure if this is recorded elsewhere under another task, but I thought I might spend a little time this weekend trying to determine why the customer data table isn't being rendered and fix it.

**Comment by objecttothis** [comment]
Finding out why it's not being displayed will likely fix all the other tables too because none of them are being displayed.

**Comment by odiea** [comment]
In Controller/Sales I commented out line 54 email lib and now the Register view shows.
In Controller/Cashups I commented out line 24 summary payments and now Cashups shows.
Hope this helps someone.

**Comment by objecttothis** [comment]
Thanks @odiea . I'm working on the sales controller stuff so I'll take a look at that line.

**Comment by odiea** [comment]
This also appears to load ok using php 8

**Comment by SteveIreland** [comment]
Yep, so far I've only had to tweak one thing due to PHP 8.

**Comment by SteveIreland** [comment]
I pushed a fix this morning that resolves the JavaScript crash that was occurring when tables are rendered.  I'm not sure this is the final fix for this issue.  I'm reading the CI4 documentation and it's suggesting that it MIGHT no longer be necessary.

But at least now the table headers are being displayed.

**Comment by odiea** [comment]
Modals are at least showing signs of life now. Table headers are working like you said.

**Comment by SteveIreland** [comment]
Just found the documentation for the esc function.  It says it still supports arrays.  So I think the issue must be in the area of character encoding - because it was spitting out some real garbage.

**Comment by objecttothis** [comment]
Yeah, I think the esc() function may need to be applied to form data coming from the user rather than data from the db displayed to the user.

**Comment by SteveIreland** [comment]
If it's not automagically happening, the reason for using the esc() functions on the table header data would be to convert non-html friendly characters to html friendly versions.  Tonight I'm going to try to add the UTF-8 character encoding to the esc requests and specify "html" as the purpose (which should be the default) just to see if it makes a difference.

**Comment by SteveIreland** [comment]
Well, I tried the "fully fleshed out" version of esc($table_headers, 'html', 'UTF-8')

The result was quite a bit different, but totally unusable.  It escaped just about every character in the field - resulting in a different JavaScript error but one that again breaks the display.

**Comment by SteveIreland** [comment]
I just now pushed a batch of changes that addressed numerous issues that I encountered.  

@odiea I also changed the getGet() instances to getVar().  That seems to be the "safer" version to use when one doesn't know if the request is GET or POST.   I wasn't sure about the getSearch() since I couldn't find the source of that nor could I find any documentation for it.  BecauseI haven't reached the point where I can add customers or items, I haven't been able to see the results of that particular change, so if you can check it out I'd appreciate it.   Most of my changes deal with building the linkages correctly.

Now I'm getting into issues that seem related to configuration and I see I still have some learning to do about the internal wiring of CI4.

**Comment by SteveIreland** [comment]
The issues I'm now getting in the modal forms (now that I'm past the linkages issue) is related to initializing the data with stuff from the config files and I'm guessing it's because CI4 is now a little more anal about how things need to be set up, or just decided it wanted to do things differently because it could.

But at least now I'm crashing at the point where it's trying to load the view data.

@objecttothis Please ignore my change on one of the functions where I dropped the :void   I will be putting it back.  I was a rabbit hole I temporarily went down while trying to get the view to display - and I was using the approach documented by CI4.

**Comment by SteveIreland** [comment]
An interesting issue cropped up  On the search functions, types have been added to the parameters.  That's good, but then the value passed in has to match the assigned type.  But null isn't a valid type.  So, I reworked them so that the type was optional (thereby allowing nulls to be passed in) and I ran another test.  But then I realized that the default values were no longer being passed through - or so it seems.  I'm out of time to work on it today.   But that seems to be where I'm stuck for now. The documentation isn't very helpful to me.  I'm thinking that the default doesn't work for typed parameters and that the fields will be tested for a null value and the default value assigned within the function.

**Comment by odiea** [comment]
Me not being a programmer took the easy way out and just changed some lines of code in controller and Model. All tables are now showing except Attributes. The tables search function works but the tables do not sort and of course there is still no view working other than the manage view.

**Comment by SteveIreland** [comment]
Yep, that's a path to take - used it many times myself.  :-)  My approach has changed- but right now it seems to have devolved into chasing down and fixing all critical errors that appear in the log file.  Priority is given to those that seem to be standing in my way of achieving my goal of being able to add either an item or a customer.

When I identify an error and then, through trial and error, I seem to have found the technically correct solution, then I apply that change to all places in the app where that error is also likely to occur.

If you took a snapshot after I push my changes then I'm glad I didn't make things worse.

**Comment by odiea** [comment]
Thanks. No I did not merge any of your newest changes but will set up a new location and try them out.

**Comment by odiea** [comment]
I got the current version and the table headers show but no data. Must still be a work in progress.

**Comment by odiea** [comment]
Here is what the error log displays when loading the customers table.

CRITICAL - 2023-03-13 08:06:45 --> Call to undefined method App\Models\Customer::getSearch
in SYSTEMPATH\Model.php on line 841.
 1 APPPATH\Controllers\Customers.php(102): CodeIgniter\Model->__call('getSearch', [...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Customers->getSearch()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Customers))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-13 08:06:49 --> Argument 5 passed to App\Models\Item::getSearch() must be of the type string, null given, called in C:\wamp64\www\ireland\app\Controllers\Items.php on line 119
in APPPATH\Models\Item.php on line 123.
 1 APPPATH\Controllers\Items.php(119): App\Models\Item->getSearch('ROOTPATH\\public', [...], 15, 0, null, null)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Items->getSearch()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Items))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()

**Comment by SteveIreland** [comment]
The second critical issue is where I left it.  That's the new behavior with the type hint applied.

The first one is my mistake.  CI4 led us to naming the default functions to "getView" or "getIndex" instead of simply "view" or "index".  I see I got a little over aggressive with my bulk renaming.  I'll back that out tonight.  It's only the controllers that need to change - not the models.   Sorry.

**Comment by objecttothis** [comment]
Correct, the only reason for adding get, put, post, etc is for auto routing which only applies to controllers.

**Comment by objecttothis** [comment]
> An interesting issue cropped up  On the search functions, types have been added to the parameters.  That's good, but then the value passed in has to match the assigned type.  But null isn't a valid type.  So, I reworked them so that the type was optional (thereby allowing nulls to be passed in) and I ran another test.  But then I realized that the default values were no longer being passed through - or so it seems.  I'm out of time to work on it today.   But that seems to be where I'm stuck for now. The documentation isn't very helpful to me.  I'm thinking that the default doesn't work for typed parameters and that the fields will be tested for a null value and the default value assigned within the function.

@SteveIreland the solution here is to make the parameter or return type nullable if it's not overriding a parent function. So if you have `public function has_fun(string $foo): string` and null is an acceptable input for $foo then your signature becomes `public function has_fun(?string $foo): string` same can be done for the return type.

**Comment by odiea** [comment]
I don't know what I did for sure but I got the items form to show.
![2023-03-13 19_19_26-](https://user-images.githubusercontent.com/10962177/224867787-83a38400-c800-4734-a759-6ccf77f07333.png)

**Comment by SteveIreland** [comment]
@odiea I'm jealous.  I'd like to know what magic you applied.  I'm still getting a "not found" message in the console when trying to call the search method and the view method.

**Comment by odiea** [comment]
@SteveIreland each form appears to have it's own rabbit hole to follow. On the forms I have had to change the sources like we did in manage. I had to remove all instances of ResultInterface in Models including any other Model that's being called. The forms show errors with to_currency_no_money  so I removed that.

**Comment by objecttothis** [comment]
> @odiea I'm jealous.  I'd like to know what magic you applied.  I'm still getting a "not found" message in the console when trying to call the search method and the view method.
> 

@odiea most IDEs have an ability to show a diff of what has changed from original. Perhaps you can look at the diff to get a clue as to what changed?

**Comment by odiea** [comment]
Her are the current files I have changed to get Customer tables to show.
[Customers.zip](https://github.com/opensourcepos/opensourcepos/files/10969532/Customers.zip)
[Customer.zip](https://github.com/opensourcepos/opensourcepos/files/10969535/Customer.zip)
These should sow the customer table?

**Comment by odiea** [comment]
I commented out stuff that was showing errors instead of trying to fix them. LOL

**Comment by odiea** [comment]
To get the customer update view to show I also changed the following. To get the forms to show I also edited out 'attr'.
```
'edit' => anchor(
			"Customers/view/$person->person_id",	//TODO: String interpolation
			'<span class="glyphicon glyphicon-edit"></span>',
			[
				'class' => 'modal-dlg',
				'data-btn-submit' => lang('Common.submit'),
				'title'=>lang('Customers.update')	//TODO: String interpolation
			]
```

**Comment by odiea** [comment]
I am still testing but it appears the this new build may have eliminated the  to_currency_no_money problem I had earlier.

**Comment by odiea** [comment]
This is the error displayed when using to currency  "message": "Argument 1 passed to to_currency_no_money() must be of the type float, string given, called in C:\\wamp64\\www\\ireland\\app\\Views\\items\\form.php on line 202",
    "file": "C:\\wamp64\\www\\ireland\\app\\Helpers\\locale_helper.php",

**Comment by SteveIreland** [comment]
@objecttothis   I need some insight.  I'm a pattern programmer.  I work best when I can clone approaches that have been proven by my predecessors.  Because I hadn't explored as deep as I needed to, I made some assumptions that now don't seem to be correct.  So, I need some clarification.  I saw that the "index" function had been changed to "getIndex".  Based on that I assumed that was because of a CodeIgniter requirement.   So, I concluded that getSearch and getView was a requirement.

However, after reading the CodeIgniter manual it seems like "get" being prepended to it might not be in sync with CodeIgniter's expectations.   (Still studying on that.) However, the fact that it mostly works (but not always) is confusing the heck out of me.

The SecureController seems to complicate things since the method names assigned there don't, necessarily, have anything to do with CodeIgniter.

I'm going to keep exploring, but you're far ahead of me on this, so if you can enlighten me, I'd appreciate it.

I'm beginning to think that I need to back out a lot of changes (although many seemed to resolve issues I had).

**Comment by SteveIreland** [comment]
Okay, progress is finally being made (at least for me).  "getView" seems to be correct vs simply "view", and once I removed the "esc" function the URL that was generated was acceptable (no more "not found" message).  The next message I got when clicking on "new customer" was ... "App\Models\Tax_code::get_info() must be of the type int, string given, called in C:\vroots\osposci4\app\Controllers\Customers.php on line 170"

Now I'm back in familiar territory.

**Comment by SteveIreland** [comment]
For the record, here is what I found from the CI4 documentation:

"A controller method needs HTTP verb prefix like getIndex(), postCreate()."

"Developers always know the HTTP method, so requests by an unexpected HTTP method does not pass."

I think it's rather presumptuous of the CI4 team that developers always know, but I'm sure I can figure it out as soon as it crashes.  :-)

**Comment by objecttothis** [comment]
> @objecttothis I need some insight. I'm a pattern programmer. I work best when I can clone approaches that have been proven by my predecessors. Because I hadn't explored as deep as I needed to, I made some assumptions that now don't seem to be correct. So, I need some clarification. I saw that the "index" function had been changed to "getIndex". Based on that I assumed that was because of a CodeIgniter requirement. So, I concluded that getSearch and getView was a requirement.
> 
> However, after reading the CodeIgniter manual it seems like "get" being prepended to it might not be in sync with CodeIgniter's expectations. (Still studying on that.) However, the fact that it mostly works (but not always) is confusing the heck out of me.
> 
> The SecureController seems to complicate things since the method names assigned there don't, necessarily, have anything to do with CodeIgniter.
> 
> I'm going to keep exploring, but you're far ahead of me on this, so if you can enlighten me, I'd appreciate it.
> 
> I'm beginning to think that I need to back out a lot of changes (although many seemed to resolve issues I had).

@SteveIreland Pattern programming is likely my favorite way to master a skill, so no shame in clone code from another part of the project and adapting it as you figure out how it works.  Unfortunately a lot of the CI4 changes don't have an existing patter in this project.  If we were not using autorouting, then we would not need to change the name of these functions.  It's only required because that's what CI4 is expecting when it tries to autoroute to a controller.  For example, the reports controller methods are not auto routed, so we don't need to make any of those changes there.

You mentioned this but several controllers inherit Secure Controller which means if the function index() in the Items controller needs to be changed to getIndex(), then it's parent in Secure Controller needs to be changed to match and then subsequently any controller inheriting secure controller.  In most cases, this will be fine.

There are only a finite number of routes, and this is why CI4 says that the dev should know permutations.  Let me know if you need more clarification on something.

**Comment by SteveIreland** [comment]
Made another batch of commits, and can now to get the New Customer panel (but can't actually add a customer yet).
Next target is to be able to get to the New Item panel.

**Comment by SteveIreland** [comment]
The new item panel now displays (with a couple of issues).  I think my next task will be to resolve all of the issues with adding a new customer.  Trying to do my best to confirm to the new standards.  I'm finding that the "get_info" functions that currently initialize a new record object with empty strings are causing havoc with the data-typing requirement.  So I'm changing those to initialize the new object fields to null, and then on the functions that were passed one or more of those "now null" fields, I am prepending the typehint with a question mark so that the function can digest a null.  So far I haven't had much of a problem with making those changes, and hopefully that trend continues.

**Comment by SteveIreland** [comment]
Progress.  I was able to add a new customer and it revealed itself in the table.

A commit was made with necessary changes.

My next target is new item add.

**Comment by odiea** [comment]
@SteveIreland  That works. I had to add post to the ajax checks then I could do an update but had to refresh the table to see the changes. Good work

**Comment by SteveIreland** [comment]
Thanks, yes.  I forgot to redo that.  I had to do the same when I was adding values to those fields in my tests. After failing 20 times in a row I started just adding the first and last name to run a test.

**Comment by SteveIreland** [comment]
I changed my mind (based on your feedback).  I'm going to focus on customer maintenance and chase it down until I've resolved all of the issues.   I just committed a few more changes.  It's still not functional but it's a bit of progress.   I corrected the escape behavior on the forms so it doesn't introduce garbage on the display and I corrected an issue with the update link so that it picks up the correct name for the controller.

**Comment by SteveIreland** [comment]
I made some bulk changes to reflect the changes that I made to customer maintenance to get it working.  There were some changes I wanted to make to the use of site_url(), which is used a lot, but my confidence level on those changes isn't yet to the point where I feel comfortable making the changes in bulk.

I'll do some more feature by feature testing and debugging.  Maybe next weekend my confidence level will be higher.

**Comment by SteveIreland** [comment]
Customer maintenance seems to be working for the most part, so I'm going to focus on item maintenance for the rest of this weekend.

**Comment by SteveIreland** [comment]
I can now add, change and delete both customers and items.

I haven't touched inventory maintenance and I haven't fully tested the CSV import (only that the panels pop up).

Nor have I tested the item attributes feature. 

But I think I will go ahead and close this issue.  I'm past 98% of the customer maintenance issues and probably 80% of the item maintenance issues.
