### ISSUE TITLE
CI4: Create build script to generate .env if it doesn't exist

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3702]
Currently the .env is being tracked in the repo. The problem is that this poses the risk of someone committing a .env with their sensitive credentials. The way to resolve this is
- [ ] check if .env exists during build and generate from a template if it doesn't.
- [ ] force push a delete of the .env in the repo.
- [ ] add .env to the .gitignore in the root directory 

@SteveIreland do you want this one?

**Comment by SteveIreland** [comment]
Sure.

**Comment by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [comment]
Save some overhead with .env-example and remove .env entirely.  Maybe a bit safer?

**Comment by objecttothis** [comment]
OK tracking the template as .env-example and putting .env in .gitignore is a simpler solution. We likely need to add a check at the beginning of the Login controller to throw an error if the .env isn't there. The login controller is currently generating a key in the .env, so if the file doesn't exist, it will puke.

**Comment by SteveIreland** [comment]
That certainly makes it simply than trying to do something with the build.  :-)

**Comment by SteveIreland** [comment]
A commit was made to create the `.env-example`.  However, .env was already included in the `.gitignore`.   So that wasn't changed.
