### ISSUE TITLE
First login - 405 Not allowed

### ISSUE THREAD

**Issue by pari** [opensourcepos/opensourcepos#3703]
Fresh install of opensourcespos - this is my first time
ubuntu 20.04 on Ec2 ,
I am getting at `405 Not Allowed` page while attempting my first login.
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/226929/222913389-0afcba50-55f2-4187-a408-610f8535bec9.png">

**Comment by nukerj** [comment]
Can you do it?

Johnny Vilchez
Telegram @jvilchez
WhatsApp +584126447407
Email vilchezjohnny82@gmail.com
