### ISSUE TITLE
Sales section 

### ISSUE THREAD

**Issue by fix24networks** [opensourcepos/opensourcepos#3712]
Hi, 
I noticed that where the amount is entered in sales, if the amount is given with one decimal places, it switches to a single digit.

**Comment by SteveIreland** [comment]
You need to go to Configuration > Localization >  and change the quantity decimals from 0 to 1 if you want to be able to enter decimal positions

**Comment by fix24networks** [comment]
Thanks for your information.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
