### ISSUE TITLE
Can I change default discount method from percentage to cash?

### ISSUE THREAD

**Issue by fix24networks** [opensourcepos/opensourcepos#3713]
Hi,
01. I noticed that where the amount is entered in sales, if the amount is given with one decimal places, it switches to a single digit.

02. Can change default discount method from percentage to cash.

**Comment by SteveIreland** [comment]
Question 1 was answered on your other ticket.

The answer to your second question is also Yes.  Go to Configuration -> General, and then drag the discount toggle from % to $ and click on save.  discounts in dollar amounts will be the default from that point forward

**Comment by fix24networks** [comment]
Thanks for your information

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fix24networks** [comment]
Thanks for your information

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
