### ISSUE TITLE
This is a request not an issue, thanks.

### ISSUE THREAD

**Issue by 2mhzbrain** [opensourcepos/opensourcepos#3722]
Can someone help me add Item Name column on Daily Sales?

**Comment by WebShells** [comment]
It's doable but not suggested. The Daily sales table lists each sale as 1 line, applying what you need is only capable if you want to divide it into several lines ( So sale with ID 1 for example has 3 items in it will be showing as 3 lines in place of 1 )

**Comment by 2mhzbrain** [comment]
I am using OSPOS for listing the sold items on FB live selling, I want to view their items when I search their name then screenshot (using snipping tool) and paste it directly on their FB messenger when they ask how much their total items.
![image](https://user-images.githubusercontent.com/7908759/226342334-18bc7d49-fbe2-4f41-a215-062785c1af1a.png)

**Comment by 2mhzbrain** [comment]
> It will be more messy if you are going to seperate each item in the invoice on a separate line. I can help you out anyway figure out what is the best report to display it.

can you make a report under Customer Summary report that includes full address with contact number all grouped by Address2 as header

like this excel format
Address2
State, City, Address2, Address1, Name, Contact
State, City, Address2, Address1, Name, Contact
State, City, Address2, Address1, Name, Contact
State, City, Address2, Address1, Name, Contact

I will be using it for delivery.
