### ISSUE TITLE
How to disable sales if the Quantity is insufficient.

### ISSUE THREAD

**Issue by rigzintsh** [opensourcepos/opensourcepos#3723]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Please help me to disable sales when desired quantity is insufficient. By default we get a warning 
![image](https://user-images.githubusercontent.com/80269899/226527654-3818dab3-e68b-4b62-bbcb-d77ee9e19e13.png)

**Comment by WebShells** [comment]
Hello @rigzintsh, your answer can be found in the below branch, the code might need some updates.

[Do not allow negative stock sales](https://github.com/opensourcepos/opensourcepos/compare/master...no-negative-stock)

**Comment by blutme** [comment]
Just add in: `.../application/views/sales/register.php`

line 18 `?>` << NOT ERASE!
below, add in line 19. Like this:
`if(isset($error_os))`
`{`
`	echo '<script>alert("¡Producto Sin Inventario Disponible!  Recepcione para poder Vender!")</script>';`
`}`

-------

line 	292		`<?php echo form_close(); ?>` << NOT ERASE!
below  add in line 293:
`<?php `
`      if ($item['in_stock'] < $item['quantity']){ `
`	redirect($controller_name.'/delete_item_os/'. $line);`
`	} `
`?>`

-----

********
and create a function called `delete_item_os ` on: `.../application/controllers/Sales.php`

line 	515		`}` << NOT ERASE!
below, add in line 516. Like this:

`	public function delete_item_os($item_number) 
	{`
`		$data = array();`
`		$this->sale_lib->delete_item($item_number);`

`		$this->sale_lib->empty_payments();`
		
`		$data['error_os'] = "cualquier cosa";`

`		$this->_reload($data);`
`	}`

This change allows you to delete the product if the quantity entered is greater than the quantity in inventory.
If there is any suggestion that you can give me I am not very good at handling github
