### ISSUE TITLE
Barcode 

### ISSUE THREAD

**Issue by fix24networks** [opensourcepos/opensourcepos#3726]
Can we off barcode in invoice

**Comment by WebShells** [comment]
You mean remove barcode column from the invoice form ?

**Comment by WebShells** [comment]
Ok you can remove the lines below from the receipt:

`<div id="barcode">
		<img src='data:image/png;base64,<?php echo $barcode; ?>' /><br>
		<?php echo $sale_id; ?>
	</div>`

and from invoice:

`<div id='barcode'>
			<img style='padding-top:4%;' src='data:image/png;base64,<?php echo $barcode; ?>' /><br>
			<?php echo $sale_id; ?>
		</div>`

This will remove the barcode displayed at the bottom.
