### ISSUE TITLE
OSPOS reports module issue while using Date filter

### ISSUE THREAD

**Issue by kizitox2** [opensourcepos/opensourcepos#3728]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: ffe492
- PHP version is: 7.4.33
- MySQL or MariaDB version is: 5.7.23-23
- OS and version is: 
- WebServer is: Linux 4.19.150-76.ELK.el7.x86_64
- Selected language is: En/US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
This seem to be a Bug;
When I am running a Report I get an error where a page is redirected to a non existent link.If I check the page via inspection I come find the error message as bellow:
Mixed Content:Page was loaded over https but requested an insecure script http://cdn.jsinit.directfwd.com/sk-jspark_init.php.This request has been blocked the content must be saved on https.Failed to load resource Responded with error status 403()

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by jeetdebnath** [comment]
Same problem I am getting
https://public/reports/detailed_sales/2023-04-06%2000:00:00/2023-04-06%2023:59:59/complete/all/0

**Comment by odiea** [comment]
https://stackoverflow.com/questions/66496320/one-malicious-link-that-is-still-reflecting-on-the-website. This  appears to be your webservers problem

**Comment by WebShells** [comment]
It's not related to any malicious files. 
@odiea you can replicate the issue by setting date and time filter on. On some web servers that had an update around 2 weeks ago started giving permission denied error. I disabled date and time filter and reports works again, i thought it was a local update; Seems not!

**Comment by jeetdebnath** [comment]
Dear @ Webshells you are right my webserver got updated and i am getting the problem... please kindly elaborate how to disable date and time filter... thanks in advance

**Comment by jeetdebnath** [comment]
Dear @Webshells   Thanks a lot i found it..... Office-config-localization.... Untick date and time picker...
thanks a lot... you saved my day

**Comment by kizitox2** [comment]
Thanks,I have also done the change,unticking the date and time filter in office-config-localization.Thanks Should this remain as a Bug to be checked and fixed?

**Comment by WebShells** [comment]
Hello @jeetdebnath & @kizitox2, excuse my late reply... 
Glad you found it, yes it's under the configuration module, localization tab at the bottom of the page (Date and Time).
Before the webserver update the link of date and time filter was submitted including spacing, in the updated version it's replacing spaces by % that's where the forbidden page error appears. 
@opensourcepos/org any one can have a look ?

**Comment by SteveIreland** [comment]
I'll fix it in the CI4 branch.  There are a lot of url calls that are now being escaped that weren't in the CI3 release.

"Webserver update" is pretty generic.  Is this a Linux or Windows thing?  Or is an Apache thing?  I'm trying to grasp what could have triggered this behavior in the CI3 release.

It sounds like the change I need to make is to make sure that the search function unescapes the date string before using it.  Is that what you believe is needed?

**Comment by WebShells** [comment]
@SteveIreland the setup/environment is as submitted in the issue.

OSPOS version is: 3.3.8
OSPOS git commit hash is: ffe492
PHP version is: 7.4.33
MySQL or MariaDB version is: 5.7.23-23
OS and version is:
WebServer is: Linux 4.19.150-76.ELK.el7.x86_64
Selected language is: En/US

It sounds like the change I need to make is to make sure that the search function unescapes the date string before using it. Is that what you believe is needed? **I think so**

**Comment by SteveIreland** [comment]
LOL.   Sorry, I'm getting so accustomed to no one filling those out that I didn't even think to look there.  My bad.  I need to retrain myself.

So a Linux upgrade triggered the issue, which is probably why I haven't seen it and can't recreate it, but I'll go ahead fix it.  Maybe I'll use this as an excuse to set up a Linux platform.

**Comment by nukerj** [comment]
@kizitox2 It's a bug in the server configuration that doesn't accept spaces in the url.  When you activate the date and time format in the query, a space is left between the date and the time.  that's why the error.
