### ISSUE TITLE
CI4: Missing keys in configuration 

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3730]
I'm going to start working on the configuration piece of this puzzle.  I need something to write the missing configuration values before I can continue work on the sales register.

**Comment by odiea** [comment]
If it is not there then login_form need to be added to appconfig

**Comment by SteveIreland** [comment]
I found a "solution/hack" for the missing config value errors that I'm using for configuration maintenance.   Preceding the $config['xxx'] with an @ symbol tells PHP to ignore the error and I believe a null is returned instead.  It also flags those that we need include in a migration step to add the missing values.

**Comment by odiea** [comment]
@SteveIreland App/views/ Items /form line 227` what is that at the end? Otherwise all is working much better now.
```
<?php endif; ?>`
```

**Comment by odiea** [comment]
@SteveIreland   ) ?>s  views/configs/general line 43. I did not see this earlier.

**Comment by SteveIreland** [comment]
So today's goal was to get Attribute maintenance working again, and to successfully add an Attribute to Item maintenance.

The is working for me now, and the second was successful with a TEXT attribute.  The commits were pushed.

**Comment by SteveIreland** [comment]
Finally got around to adding a migration script to add the config values that didn't exist that were creating issues with loading panels.  Removed the @ hack so that if the config values are missing the panel will resume crashing.  An odd one though was the barcode_content config value.  The issue with that was not that the config value was missing, because it was there.  However, it was being evaluated using the === comparison operator    As soon as I changed it to ==, it started working.  Doesn't make sense to me, I only know that it works.   It should be comparing two string data values.

**Comment by SteveIreland** [comment]
I take back my comment about the barcode_content fix.

I rebuilt my test environment, upgraded the PHP version again, and then retested it.  Shocked to find it, again, fails for the same reason.

**Comment by odiea** [comment]
I finally found it. Line 96 of views barcode_config is missing a bracket. Should look like this. 'checked' =>$config['barcode_content'] == 'id'] missing bracket at end of barcode_content.

**Comment by SteveIreland** [comment]
@odiea Thank you!

**Comment by jekkos** [comment]
@objecttothis do you know if this issue is stil present for other screens? Otherwise I would make a small migration that diffs the config table and adds key entries for missing entries, so that those things don't need to be fixed in the code.

**Comment by objecttothis** [comment]
I'm not sure. I suppose a migration would settle the issue for both new and existing installs unless the issue pops back up in the event of removing a value then adding it back in.

**Comment by objecttothis** [comment]
@SteveIreland can this issue be closed as resolved?

**Comment by SteveIreland** [comment]
I haven't been following closely.  It looks like I did what I was able almost a year ago, and it appears that others have finished the work.   So, if I'm the only one you're waiting on, I'll go and and close it.
