### ISSUE TITLE
CI4_update

### ISSUE THREAD

**Issue by DEV-byoos** [opensourcepos/opensourcepos#3732]
hello dev's

I installed the last commit opensourceospos upgrade ci4
some modifications are needed:
PROPOSALS:
IN /root/app/Views/Login.php
FIX <link href="" rel="stylesheet" type="text/css">
TO

i am move to /bootstrap@3.4.1/bootstrap.min.css and testing version [bootstrap@5.3.0-alpha1.css](mailto:bootstrap@5.3.0-alpha1.css) it'ok

also for the header.php
AND IN /root/app/Views/partial/Header.php

AND added
added the 2023/04/07
	
	<script type="text/javascript" src="dist/opensourcepos.min.js?rel=64a537c419"></script>
	<script type="text/javascript" src="js/jquery-ui@1.11.3/jquery-ui.js"></script>
	

I'm stuck on internationalization
the template does not follow the local code, I'm working on it

config CI4.3.3 and php8.2  OSPOS   CI4_upgrade  from ospos v3.4.0
I FIX bugs as they arise

best regars
Gabriel
the 2023/04/07

I'm currently using bootstrap_3.4.1 ho, I made a little test for fun ho.
in the previous post i wanted to point out a small typo in script ../Views/Loging.php on the line href="<?php echo 'dist/bootswatch-5/'
to be replaced by
href="<?php echo 'dist/bootswatch/' 
Sincerely 

By the way I found the error

 of displaying languages, see the files ../app/Language/... in CI4 the format is filename.message in the views or others and here we are rather  
return [
	"login.gcaptcha" => "I'm not a robot",
..... other lines

FIX
return [
	"gcaptcha" => "I'm not a robot",
..... other lines
it works well,  I hope this helps
Gabriel

**Comment by SteveIreland** [comment]
I'm not clear on what you're proposing, but my understanding is that an earlier decision was made for the first release of CI4 to keep bootstrap5 for the login, and continue to use bootstrap 3 for the rest of the app.

Migration to boostrap 5 is supposed to be a later project.

**Comment by SteveIreland** [comment]
header.php is updated via the build.  You should not be manually adding links to JavaScript or CSS.

Also, at this point I'm only testing and developing targeting the development mode.  Once, we have it working in development mode then I'll refocus on production mode.  (That is technically a build issue.)  If someone is impatient then they can focus on production mode.

@objecttothis is in the middle of migrating the language stuff over.   I noticed that he renamed a ton of language elements and I'm sure, at some point, he (or someone else) will continue with that effort.  It looks like the only renamed elements are in the EN-usa files.  The same changes will need to be propagated to the other files.

**Comment by objecttothis** [comment]
> header.php is updated via the build.  You should not be manually adding links to JavaScript or CSS.
> 
> Also, at this point I'm only testing and developing targeting the development mode.  Once, we have it working in development mode then I'll refocus on production mode.  (That is technically a build issue.)  If someone is impatient then they can focus on production mode.
> 
> @objecttothis is in the middle of migrating the language stuff over.   I noticed that he renamed a ton of language elements and I'm sure, at some point, he (or someone else) will continue with that effort.  It looks like the only renamed elements are in the EN-usa files.  The same changes will need to be propagated to the other files. 

The en-US is the main language. @jekkos, when he has time, will need to pull those into weblate, pair the old language strings in other languages to them then push a commit to the branch with the updated formatting of those files. I think he has been pretty busy recently, so not sure when he will have time. Until then only the en-US translation works.

**Comment by objecttothis** [comment]
@jekkos it's possible that it may be easier to find/replace in the code to change the other language files to match en-US formatting then create a new instance of weblate and import all the languages from the latest. Otherwise I'm not sure how easy it will be to pair old index names in other languages to their translations that have been done.

**Comment by DEV-byoos** [comment]
good evening, here it is23:40 but wanted to finish the translation with the FIX

Thank you very much for the information, I take it into account in my work, this day I have fixed the language FR and EN-GB in fact I manage for the moment two language English and franchise.
I wrote a php script fix_language_multi_ospos_v3.4_ci4.php that I will attach to my answer./.

For the links that are downloaded at the BUILD node I have not seen anything like that except that the pages are displayed without CSS or JS...
bye les dev's

Gabriel
[fix_language_multi_ospos_v3.4_ci4.zip](https://github.com/opensourcepos/opensourcepos/files/11184391/fix_language_multi_ospos_v3.4_ci4.zip)

PS PS correct by hand the first line of Attributes.php
then the double header on Bootstarp_tables.php // special case

**Comment by DEV-byoos** [comment]
good evening dev's
it's 7pm French time here
I'm not only looking for bugs but also fixing them!!! that's not nice: now that the translation is working perfectly since last night, I'm tackling the other problems I had already noticed 

proposal for today's corrections
IN /root/App/Libraries/Token_lib.php at line 158   Token::get_tokens()
FIX  line 5  use App\Models\Tokens\Token;

IN all  /root/app/Controllers/*.*
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated since php8.1
replace to:
FILTER_SANITIZE_FULL_SPECIAL_CHARS

IN  /root/app/Views/partial/header.js

move line one  whith line two
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo base_url('image/') ?>favicon.ico">
	<link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">
********** END debug *************
best regard
Gabriel

**Comment by SteveIreland** [comment]
Yes, the FILTER_SANITIZE_STRING has been a headache for me during my tests - specifically with JSON encoded arrays.  The PHP manual was recommending a function to replace that, but I'll give the FILTER_SANITIZE_FULL_SPECIAL_CHARS a try.  Hopefully it won't screw up JSON encoded arrays too.

**Comment by SteveIreland** [comment]
Just for yuks, I replaced FILTER_SANITIZE_STRING with FILTER_SANITIZE_FULL_SPECIAL_CHARS and pushed that commit.

I haven't been testing with special characters, so I haven't noticed any issues with all of the sanitizing going on.

So, I thought I'd pay a little more attention to the sanitize/escape flow discussed in an earlier closed thread, and then try my hand at at doing something like inserting a double quote into the item description to see how that was absorbed by what we had in place.

It didn't go well.  I believe we are over encoding.   For example most, if not all, of the CI4 form elements will automatically escape a field.  But most of the CI4 form elements also have their data explicitly escaped with the esc( ) function.  The result of that is not what the user would like to see.

When time permits, I'm will modify item maintenance so that it accomplishes what it needs to.  But tax season is upon me so I'll be preoccupied most of this week.

**Comment by SteveIreland** [comment]
I played around with item maintenance.  I removed all of the SANITIZE stuff because it was essentially encoding special characters like double quotes, single quotes and the less than and greater than sign and the encoded values are not useful.

Most of our numeric value input filtering is accomplished by internal parsing functions developed for that purpose.  So garbage coming in that way is mostly cleaned up.   We don't report errors with bad data, we just strip out the bad data.

I'm 95% sure that CI4 already escapes data sent to MySQL/MariaDB so SQL injection isn't a problem.  Everything I'm sending is being written correctly to the database. 

As I expand my debugging I'm going to propagate these changes.  There isn't really a bulk way to make these changes.

**Comment by objecttothis** [comment]
> I played around with item maintenance.  I removed all of the SANITIZE stuff because it was essentially encoding special characters like double quotes, single quotes and the less than and greater than sign and the encoded values are not useful.
> 
> Most of our numeric value input filtering is accomplished by internal parsing functions developed for that purpose.  So garbage coming in that way is mostly cleaned up.   We don't report errors with bad data, we just strip out the bad data.
> 
> I'm 95% sure that CI4 already escapes data sent to MySQL/MariaDB so SQL injection isn't a problem.  Everything I'm sending is being written correctly to the database. 
> 
> As I expand my debugging I'm going to propagate these changes.  There isn't really a bulk way to make these changes.
> 

@SteveIreland I think we should test that CI4 is indeed sanitizing without the esc() functions in place. This is easy to do by pasting in something like `malicious'ex` to a text field then looking at it in the database. If the apostrophe isn't escaped then sanitizing isnt happening correctly.

**Comment by DEV-byoos** [comment]
@SteveIreland and  @objecttothis

Thank you for your quick responses and I am glad that many of us are improving the OSPOS ci4_update which will take over from OSPOS_ci3, this is great for me as I am in the process of moving my ci3 apps to CI4.
I test, I analyze the possible bugs then I propose a patch...

PS I have several (bug's) waiting for solution(s):

1)
IN  /root/app/Views/partial/header.js

move line one  whith line two
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo base_url('image/') ?>favicon.ico">
	<link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">

IN /root/app/Events/load_config.php

added into  class Load_config
{
	
	
	public $session;
	....
2)
IN database.ospos_app_config  several keys missing from the table
key   login_form
key  category_dropdown	

3)
ErrorException
Undefined property: CodeIgniter\View\View::$barcode_lib search →
APPPATH/Views/configs/barcode_config.php at line 55

NOTA: I'm not sure, because the Baercode_lis lib is present in app/config/autoload.php

see you leater
Gabriel

**Comment by SteveIreland** [comment]
**Regarding item 1**.  I'm not clear on what you're asking.  Here are the first few lines of header.js.  What exactly is it that you believe needs to be changed?

`1 <script type="text/javascript">

2 	// live clock	

3 	var clock_tick = function clock_tick() {

4 	setInterval('update_clock();', 1000);

5 }
`

**Regarding item 2.**  I've been working on identifying all of the missing config values.  It's coming soon.

**Regarding item 3.**  I believe I fixed that over the weekend.   I just now went to the barcode config page and pressed the save button and didn't crash.  Obviously that's not a full test.  If the latest commit isn't working for you, if can you tell me what value you entered on what field, then I'll replicate and fix the issue. 

I've been nibbling away at the issues myself.  I was working on the register when I finally gave up and decided I had to work on the configuration pages first.   I'm now able to save all of the configuration pages.

Then I decided I had to get Attribute maintenance working so that I could make progress on the Item Maintenance page.

I would have made more progress over the weekend, but I had to take Saturday off in order to pass a couple of kidney stones.

**Comment by DEV-byoos** [comment]
@SteveIreland
OK, thanks for your answer,
1)
OK, thanks for your answer,
In the ../app/Views/partial/header.php file I updated the favico.ico display

<link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">
the old line doesn't work, this one is from ../app/View/Login.php

2)
OK, FIX

3)
I'm working on it but I'm going to load the last commit ci4_update

good day
<link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">
the old line doesn't work, this one is from ../app/View/Login.php

**Comment by DEV-byoos** [comment]
PS  two patches on the en and fr language files
Expenses_categories.php apparently my PHP script has a problem with underscore filenames, sorry,

I'm attaching some screenshots from my last install
![ospos_login _with_css](https://user-images.githubusercontent.com/18718552/231007837-0a4500e9-3020-41b0-a71d-a36ac62ba526.png)
![ospos_screen_login_wihout_css](https://user-images.githubusercontent.com/18718552/231007870-b30ab4dc-c900-44ea-a8e0-527aaef1e7eb.png)
![ospos_screen_menu_home_with_css](https://user-images.githubusercontent.com/18718552/231007921-632af561-7ef2-44ac-9dc8-8cd66af69c29.png)
![ospos_screen_login_with_css](https://user-images.githubusercontent.com/18718552/231008272-33dbf745-da44-48cb-b665-0261104ad129.png)

bye

**Comment by SteveIreland** [comment]
After you download the files and drop them into your folder, what project build steps are you using?

It looks like your header.php file isn't being injected with the correct stylesheet.

**Comment by DEV-byoos** [comment]
good evening, it is now 22:00

the method to follow is described in the file migration_ospos340_ci4_update_php8-2.txt in attachment.
OK for the script .../app/Wiews.Loging.php this .css link is missing

' <link rel="stylesheet" type="text/css" href="css/login.min.css"/>'

for the rest everything works fine in CI4 version 4.3.3
Thanks a lot for this update from ci2 to ci4 
bye
Gabriel
![ospos_screen_login_fuul_css](https://user-images.githubusercontent.com/18718552/231289527-0147adf2-1eac-490d-aa55-98ae2b4340bf.png)

**Comment by jekkos** [comment]
@objecttothis @SteveIreland regarding escape, I think we should save input unmodified, so validated only and escape in the view. Reason is that sometimes we want to uwe bstables escape,  which means that data should be fed unmodified. This gpt link search thinks the Same thing

https://www.phind.com/search?cache=601a651f-2ea7-4686-aba7-d010bec575b8

**Comment by objecttothis** [comment]
> @objecttothis @SteveIreland regarding escape, I think we should save input unmodified, so validated only and escape in the view. Reason is that sometimes we want to uwe bstables escape,  which means that data should be fed unmodified. This gpt link search thinks the Same thing
> 
> https://www.phind.com/search?cache=601a651f-2ea7-4686-aba7-d010bec575b8

@jekkos OK sounds good. @SteveIreland you should be able to see a working version of CI4 validation with the Login. Use that as a template. It even has a custom rule.

**Comment by jekkos** [comment]
Will try to free some time to sort translations when Im back home

**Comment by DEV-byoos** [comment]
@SteveIreland
here it is 1:00 PM
Thanks for appreciating my participation in the OSPOS project, I must say that OSPOS ci3 is my flagship solution for business management.

I have completed the correction of:
# [DEPRECATED] Creation of dynamic property App\Events\Load_config::$session is deprecated
IN /root/app/Controllers/...    /root/app/Models/...
Load_config.php, Suppliers.php, Persons.php, Models::Employee.php, Employees.php, ...
added public $session;
or protected $module;
or protected $employee; 

.... all Controllers and many Libraries and Models

I integrate an Analitycs module to monitor server access.

if you posted a new commit, i'll run a fromscratchhoo install again
from logs  ci4
CRITICAL - 2023-04-13 07:29:49 --> Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause
in SYSTEMPATH/Database/MySQLi/Connection.php on line 295.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(295): mysqli->query()
 2 SYSTEMPATH/Database/BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute()
 3 SYSTEMPATH/Database/BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery()
 4 SYSTEMPATH/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
 5 APPPATH/Models/Cashup.php(149): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH/Models/Cashup.php(76): App\Models\Cashup->search()
 7 APPPATH/Controllers/Cashups.php(65): App\Models\Cashup->get_found_rows()
 8 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Cashups->getSearch()
 9 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
WARNING - 2023-04-13 07:30:04 --> [DEPRECATED] file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated in APPPATH/Controllers/Config.php on line 105.
 1 APPPATH/Controllers/Config.php(105): file_get_contents('license/LICENSE', null, null, 0, 2000)
 2 APPPATH/Controllers/Config.php(291): App\Controllers\Config->_licenses()
 3 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Config->getIndex()
 4 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Config))
 5 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
WARNING - 2023-04-13 07:30:04 --> [DEPRECATED] file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated in APPPATH/Controllers/Config.php on line 125.
 1 APPPATH/Controllers/Config.php(125): file_get_contents('license/bootswatch.version', null, null, 0, 100)
 2 APPPATH/Controllers/Config.php(291): App\Controllers\Config->_licenses()
 3 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Config->getIndex()
 4 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Config))
 5 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()

good day
Gabriel

one other bug

**Comment by SteveIreland** [comment]
@jekkos @objecttothis 

I'm still not clear on what you're asking me to change.   I read your link and the topic is certainly valid - but I don't believe it changes what I'm doing.

For the search to work, I  need single quotes, double quotes, brackets, and other characters stored in the database as themselves.  Hopefully you agree ... if not, then we need a decision on how broken we want the search to be.

CI4 $builder escapes those characters before they are written to the database.  So currently I don't need to do any specific escaping to get them properly written to the database.

Also, when retrieved from the database and before it is sent to the browser, the CI4 controls will escape special characters.  If we present the data via a non CI4 Form control , then we need to manually escape the displayed data (in order to avoid the XSS issues discussed in the link you provided).

That's where my head currently is.  What am I missing?

**Comment by SteveIreland** [comment]
@objecttothis 

Earlier, I entertained myself a bit with the validation logic that you used in the Login controller.   And I would like to revisit what we're doing.  But my priority suddenly became getting the CRUD functionality working.  Also, we generally only display one error message at a time and I wasn't sure how the new CI4 validation logic would behave in our current one message feedback mechanism.  I had it, at one time, displaying multiple error messages .... but the formatting was ugly and didn't have time to hack around with it, so I unplugged that.

**Comment by objecttothis** [comment]
> @jekkos @objecttothis
> 
> I'm still not clear on what you're asking me to change. I read your link and the topic is certainly valid - but I don't believe it changes what I'm doing.
> 
> For the search to work, I need single quotes, double quotes, brackets, and other characters stored in the database as themselves. Hopefully you agree ... if not, then we need a decision on how broken we want the search to be.
> 
> CI4 $builder escapes those characters before they are written to the database. So currently I don't need to do any specific escaping to get them properly written to the database.
> 
> Also, when retrieved from the database and before it is sent to the browser, the CI4 controls will escape special characters. If we present the data via a non CI4 Form control , then we need to manually escape the displayed data (in order to avoid the XSS issues discussed in the link you provided).
> 
> That's where my head currently is. What am I missing?

One change would be all those entries to `esc()` that I added to the views can be removed it seems.  They are causing problems and the consensus is that we need to be doing it through what CI4 does automatically and validation.

**Comment by objecttothis** [comment]
> @objecttothis
> 
> Earlier, I entertained myself a bit with the validation logic that you used in the Login controller. And I would like to revisit what we're doing. But my priority suddenly became getting the CRUD functionality working. Also, we generally only display one error message at a time and I wasn't sure how the new CI4 validation logic would behave in our current one message feedback mechanism. I had it, at one time, displaying multiple error messages .... but the formatting was ugly and didn't have time to hack around with it, so I unplugged that.

Validation gave me fits. It took me a long time to port what we had in CI3 for the login.  I really like the built-in nature of the validation that CI4 provides, but I'm not sure that it will play nicely with the AJAX calls. I do think we need to put our heads together and come to an agreement on how we are going to do the validation/error handling/presentation.

**Comment by jekkos** [comment]
> I'm still not clear on what you're asking me to change. I read your link and the topic is certainly valid - but I don't believe it changes what I'm doing.
> 
> For the search to work, I need single quotes, double quotes, brackets, and other characters stored in the database as themselves. Hopefully you agree ... if not, then we need a decision on how broken we want the search to be.

This sounds good, so you save the chars as they are provided by the user.
 
We basically validate the input (eg check if an email is in the correct format, or if a field is numeric, etc), and save that to the db. I would not use any CI4 `xss->clean()` equivalent to escape and we save it knowing the input could contain a potential malicious payload. The idea is that it will be rendered harmless by escaping it at render time.

In the past we had these funky combinations of characters for which the CI3 `xss->clean` was just removing the characters or replacing them with something that broke the view. In the end CI also gave up on the xss cleaning as they could not foresee all possible inputs we would want to accept

> 
> CI4 $builder escapes those characters before they are written to the database. So currently I don't need to do any specific escaping to get them properly written to the database.

Is this the query builder you are describing? My guess is that it's used to avoid SQL injection, so which is different from XSS. In case a user inserts a quote, it should be escaped in the SQL query first, so the resulting database record from that query will just contain the quote as user entered it.

**Comment by objecttothis** [comment]
> > > @objecttothis
> > > Earlier, I entertained myself a bit with the validation logic that you used in the Login controller. And I would like to revisit what we're doing. But my priority suddenly became getting the CRUD functionality working. Also, we generally only display one error message at a time and I wasn't sure how the new CI4 validation logic would behave in our current one message feedback mechanism. I had it, at one time, displaying multiple error messages .... but the formatting was ugly and didn't have time to hack around with it, so I unplugged that.
> > 
> > Validation gave me fits. It took me a long time to port what we had in CI3 for the login. I really like the built-in nature of the validation that CI4 provides, but I'm not sure that it will play nicely with the AJAX calls. I do think we need to put our heads together and come to an agreement on how we are going to do the validation/error handling/presentation.
> 
> Reason for this was that CI4 got rid of the custom validation callback handlers?

There is still the ability for custom callback validation functions but they look different and passing data to them looks different. In short, the custom validation rules were part of what took me so long.

**Comment by jekkos** [comment]
> Validation gave me fits. It took me a long time to port what we had in CI3 for the login. I really like the built-in nature of the validation that CI4 provides, but I'm not sure that it will play nicely with the AJAX calls. I do think we need to put our heads together and come to an agreement on how we are going to do the validation/error handling/presentation.

If I remember well we were using a combination of jQuery frontend validation and server side checks. The advantage of the jQuery validation was that it's instant, so when you type, the validation is triggered and it shows the backend response in case you use a 'custom' jQuery validator.

We could choose to keep this validation in the frontend only , so in this case jQuery would call the CI4 validator class using Ajax  ? In this case indeed not all errors are shown at the same time, but the ajax validation message only comes up when you are editing  the field with specific validation itself which I think is acceptable. 

When you have a required field that also has a custom jQuery validator, you can also set it required in the backend and you will all error messages back if you submit an empty form. It's only when you touch the field itself and you fill it wrongly, that you will see an error message specific to that field, produced by the frontend, as other backend validations are not triggered.

Hope that makes sense

**Comment by objecttothis** [comment]
> > Validation gave me fits. It took me a long time to port what we had in CI3 for the login. I really like the built-in nature of the validation that CI4 provides, but I'm not sure that it will play nicely with the AJAX calls. I do think we need to put our heads together and come to an agreement on how we are going to do the validation/error handling/presentation.
> 
> If I remember well we were using a combination of jQuery frontend validation and server side checks. The advantage of the jQuery validation was that it's instant, so when you type, the validation is triggered and it shows the backend response in case you use a 'custom' jQuery validator.
> 
> We could choose to keep this validation in the frontend only , so in this case jQuery would call the CI4 validator class using Ajax ? In this case indeed not all errors are shown at the same time, but the ajax validation message only comes up when you are editing the field with specific validation itself which I think is acceptable.
> 
> When you have a required field that also has a custom jQuery validator, you can also set it required in the backend and you will get all error messages back if you submit an empty form. It's only when you touch the field with custom validator (account number, item number) and you fill it wrongly, that you will see an error message specific to that field, as other backend validations are not triggered.
> 
> Was that the issue you were facing or am I missing things? Hope this makes sense.

Most of the issues I was facing were not necessarily incompatibility but 1. familiarizing myself with what we were currently doing and 2. Figuring out how to port that to CI4. I may be mistaken but I don't think we were using the CI3 validation everywhere and I've only ported the login validation to CI4. I'm OK with however you want to do it.  Earlier I ported it as close to apples-to-apples as I could.  You weren't available at the time to sort through any design decisions on it, so I left further work on validation until you were more available.

**Comment by DEV-byoos** [comment]
@SteveIreland
here it is 12:30 pm
config environment
OSPOS version is: update-ci4
    OSPOS git commit hash is: ac8ff71
    PHP version is: php8.2
    MySQL or MariaDB version is: 10.5
    OS and version is:  GNU/LINUX debian 11.6
    WebServer is: apache 2.4
    Selected language is: fr
    (If applicable) Docker installation: yes  and bower
    (If applicable) Installation package for the LAMP/LEMP stack is:

two final bugs on my unit test phase
# IN ..App\Controllers\Config.php
WARNING - 2023-04-14 04:23:04 --> [DEPRECATED] file_get_contents(): Passing null to parameter #2 ($use_include_path) of type bool is deprecated in APPPATH/Controllers/Config.php on line 105.
 1 APPPATH/Controllers/Config.php(105): file_get_contents('license/LICENSE', null, null, 0, 2000)
 2 APPPATH/Controllers/Config.php(291): App\Controllers\Config->_licenses()
 
# FIX repmlace  			$license[$i]['text'] = file_get_contents('license/LICENSE', false, NULL, 0, 2000);
# line 105, 125, 131
file_get_contents use_include_path parameter #2  set from null to false null is deprecated

one last one for the road...  :-)
# IN App\Controllers\Config
ERROR - 2023-04-14 04:47:40 --> mysqli_sql_exception: Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause in /root/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /root/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(295): mysqli->query()
# trace  6 APPPATH/Models/Cashup.php(76): App\Models\Cashup->search()

FIX
show sql_mode,
SELECT @@sql_mode;

disable ONLY_FULL_GROUP_BY
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

zero ERROR, zero CRITICAL  it'OK

good day
Gabriel
