### ISSUE TITLE
Error when importing customer with same account # as previously deleted customer. 

### ISSUE THREAD

**Issue by LibertyHomesteads** [opensourcepos/opensourcepos#3734]
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8 
- OSPOS git commit hash is: 
- PHP version is: 7.4.30
- MySQL or MariaDB version is: MariaDB 10.5.19
- OS and version is: Linux 6.1.23-1-lts
- WebServer is: Apache/2.4.54 (Debian)
- Selected language is: 
- (If applicable) Docker installation: Yes
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug

1) I added some customers using the web interface, with a certain value in the Account # field. Just playing around. 

2) Later I deleted the customers that I manually added. I was now ready to import the full customer list as a CSV file. 

3) I then imported a CSV file with a customer list, including a few that had the same account # value as they did before when I manually added them. 

4) It doesn't let me add the customers that had the same account # as before, giving unspecified error. When I tried to add them manually, it gave me a more detailed error message, saying that the account number is "already present in the database." 

5) Normally I wouldn't add a new customer who had the same account number as a previously deleted customer. But in this case, I am doing it because I already have set account numbers for each customer, and I added a few to start just to figure out how it all works, figuring I can just delete them and import the CSV when I am ready. Now I am stuck because I cannot add any of these account numbers that were added previously and then deleted. 

Is this a feature or a bug? A failsafe to prevent confusion of past account #s from being used again? Or a bug because for some reason it is not deleting those past account number fields from the database despite me manually deleting them with the interface in the Customers menu... 

It's weird because I deleted the customer entries from before, so those account numbers should have been wiped, it shouldn't say that they are "already present in the database." 

I wonder if this error in file permissions is the cause of the problem: 

```
File Permissions:
» [application/logs:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads:] - 0750 | Writable ✓ | Security Check Passed ✓
» [public/uploads/item_pics:] - 0750 | Writable ✓ | Security Check Passed ✓
» [import_customers.csv:] - 0664 | Readable ✓ | Vulnerable or Incorrect Permissions ✗	

Security Vulnerability Warning
Incorrect permissions leaves this software at risk.

» [import_customers.csv:] is readable, but the permissions are incorrectly set. Please set it to 640 or 660 and refresh.
```
But somehow I feel this can't be related because why would the file permissions selectively let some fields stay in the database when all the other fields were deleted... 

Any help would be much appreciated.

**Comment by straumer** [comment]
Confirmed that the "Vulnerable or Incorrect Permissions" for the import_customers.csv file happens also on a quick local setup with [docker-compose](https://github.com/opensourcepos/opensourcepos/blob/master/docker-compose.yml) (`docker-compose up -d`). I think it's unrelated with the issue specified here, but it definitely should not happen on a default docker-compose setup for people just installing via the info in the readme.

**Comment by jekkos** [comment]
It might just be better to get rid of the unique constraint? As we otherwise invalidate history If we clear it before removal. I think at the time we did a similar thing for item number

**Comment by SteveIreland** [comment]
Fixed in the CI4 branch.

**Comment by jekkos** [comment]
Thanks for the fix @SteveIreland
