### ISSUE TITLE
Additional Barcodes 

### ISSUE THREAD

**Issue by joshbudu** [opensourcepos/opensourcepos#3735]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

I believe it will be very difficult managing a product that has several variations hence different barcodes if additional Barcodes Field is not created. For example Ceres drink is currently having over 20 different flavours but the same price and different barcodes. In other to sell with barcodes, you have to add the flavours as unique items which will not help in future. A field for additional Barcodes where the barcodes can be seperated with a , or ; can make stock management earlier. I am willing to support this feature if someone can integrate.

**Comment by jekkos** [comment]
I don't fully understand the problem, do the items have their own barcodes already? If yes then why not use them as they are? You might want to know how many of what flavor you have in stock? Or is this not something of interest?
You can also generate barcodes yourself for these items, it will be based on the item id and then you have the freedom to determine how to do the inputs.

**Comment by joshbudu** [comment]
Hi Jekkos, 
In most cases, the managers are not interested in the flavours they have in stock. The reason is manufacturers are always changing flavours and you might have about 10 flavours you previously added discontinued and making stock management messy. However, if the additional Barcodes Field is there, you just add the new barcodes to the previous ones and if you are interested in managing seperate flavours, you add them uniquely. @jekkos

**Comment by DEV-byoos** [comment]
@joshbudu

I agree with the notification, indeed it will help to simplify the search and response to users:
I fully agree

    OSPOS version is: update-ci4
    OSPOS git commit hash is: ac8ff71
    PHP version is: php8.2
    MySQL or MariaDB version is: 10.5
    OS and version is: GNU/LINUX debian 11.6
    WebServer is: apache 2.4
    Selected language is: fr
    (If applicable) Docker installation: yes and bower
    (If applicable) Installation package for the LAMP/LEMP stack is:

at the moment I am working on upgrade-ci4 with SteveIreland which is ok for me
my install is fixed and fully working, I would like a beta tester before going to production.

best regards
Gabriel

**Comment by DEV-byoos** [comment]
> I don't fully understand the problem, do the items have their own barcodes already? If yes then why not use them as they are? You might want to know how many of what flavor you have in stock? Or is this not something of interest? You can also generate barcodes yourself for these items, it will be based on the item id and then you have the freedom to determine how to do the inputs and stock management, as you decide which barcode maps to which items
@jekkos
So I thought it was a general theme orpssss ???

**Comment by jekkos** [comment]
@joshbudu if you want to reuse an existing item, then you just add the quantities to that one and use the item barcode instead of the one on the product itself? This way you work around the problem, you override the barcode of the product with one you generate that maps to the same item.

**Comment by joshbudu** [comment]
@DEV-byoos will be happy to test it.
