### ISSUE TITLE
Help adding new buttons to the sales module

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3736]
Just looking for some coding help.  I'd like to add two buttons to the sales module.  One for Debit and one for Credit.  Clicking on them would be the same as selecting Debit Card or Credit Card from the Payment Type dropdown and clicking add payment.  Just trying to simplify things for our cashiers.  Here's an example screenshot I mocked up.  This would be for the current release, not the CI4 upgrade.  

Thanks

![image](https://user-images.githubusercontent.com/531129/232070038-e1cedc3b-ef17-4a2d-b60b-cf4ba5ff7b46.png)

**Comment by nukerj** [comment]
@chunter2  Hello, if you like, write me via WhatsApp at +584126447407 or  by telegram at @jvilchez

**Comment by chunter2** [comment]
So I figured out how to add the buttons in application/views/sales/register.php at line 517 like this.  
```
				<?php
				}
				else
				{
				?>
					<?php echo form_open($controller_name."/add_payment", array('id'=>'add_payment_form', 'class'=>'form-horizontal')); ?>
						<table class="sales_table_100">
							<tr>
								<td><?php echo $this->lang->line('sales_payment'); ?></td>
								<td>
									<?php echo form_dropdown('payment_type', $payment_options,  $selected_payment_type, array('id'=>'payment_types', 'class'=>'selectpicker show-menu-arrow', 'data-style'=>'btn-default btn-sm', 'data-width'=>'fit')); ?>
								</td>
							<td><div class='btn btn-sm btn-success pull-right' id='debit_payment_button' tabindex="<?php echo ++$tabindex; ?>"><span class="glyphicon glyphicon-credit-card">&nbsp</span>Debit</div></td>
							<td><div class='btn btn-sm btn-success pull-right' id='credi_payment_button' tabindex="<?php echo ++$tabindex; ?>"><span class="glyphicon glyphicon-credit-card">&nbsp</span>Crebit</div></td>
							</tr>
							<tr>
								<td><span id="amount_tendered_label"><?php echo $this->lang->line('sales_amount_tendered'); ?></span></td>
								<td>
									<?php echo form_input(array('name'=>'amount_tendered', 'id'=>'amount_tendered', 'class'=>'form-control input-sm non-giftcard-input', 'value'=>to_currency_no_money($amount_due), 'size'=>'5', 'tabindex'=>++$tabindex, 'onClick'=>'this.select();')); ?>
									<?php echo form_input(array('name'=>'amount_tendered', 'id'=>'amount_tendered', 'class'=>'form-control input-sm giftcard-input', 'disabled' => true, 'value'=>to_currency_no_money($amount_due), 'size'=>'5', 'tabindex'=>++$tabindex)); ?>
								</td>
							</tr>
						</table>
					<?php echo form_close(); ?>

					<div class='btn btn-sm btn-success pull-right' id='add_payment_button' tabindex="<?php echo ++$tabindex; ?>"><span class="glyphicon glyphicon-credit-card">&nbsp</span><?php echo $this->lang->line('sales_add_payment'); ?></div>
				<?php
				}
				?>
```
I can't quite figure out where the code is that gets run when the button is clicked.  Any ideas?  

Thanks

**Comment by nukerj** [comment]
@chunter2  in  register.php add

$(document).on("click","#payment_cash",function()
    {
        $("#payment_types").val("<?php echo $this->lang->line('sales_cash'); ?>") ;
        $('#add_payment_form').submit();
    });

Change the name button payment_cash for your button  name id

**Comment by chunter2** [comment]
Thanks @nukerj. The first line of your function is what I was missing.  Here's the code I ended up adding to register.php along with the two button lines from my post above.  
```
        $('#debit_payment_button').click(function() {
                $("#payment_types").val("<?php echo $this->lang->line('sales_debit'); ?>");
                $('#add_payment_form').submit();
        });

        $('#credit_payment_button').click(function() {
                $("#payment_types").val("<?php echo $this->lang->line('sales_credit'); ?>");
                $('#add_payment_form').submit();
        });
```
And the sales module now looks like this.  
![image](https://user-images.githubusercontent.com/531129/236357193-5b29886c-49b7-472d-af07-97cfc3d760be.png)

**Comment by nukerj** [comment]
@chunter2 excellent.  any questions we are to order here.
