### ISSUE TITLE
Error adding/updating Expense

### ISSUE THREAD

**Issue by nlarga19** [opensourcepos/opensourcepos#3737]
### Background information

<img width="1377" alt="Screen Shot 2023-04-15 at 11 45 23 AM" src="https://user-images.githubusercontent.com/130638737/232181866-c6873d4a-0b5e-44b1-83ad-24194816277b.png">

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8 
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 5.5 
- OS and version is: ubunto 18.04 
- WebServer is: local
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Cant add New expense

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by nlarga19** [comment]
Need to create expenses category first before you can use the expenses menu.

**Comment by meierrom** [comment]
Hi folks,

The above is a workaround rather and not a fix. This issue is still there.

Kind regards,
Roman
