### ISSUE TITLE
CI4: Remove unnecessary html escaping.

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3739]
There was a tentative agreement the user of the esc() function was unnecessary form CI4 generated form elements.  So those should be removed.  Also, on input the application of html escaping was causing the data to be difficult to use.  So FILTER_SANITIZE of received text is being dropped.

**Comment by SteveIreland** [comment]
Today I reverted some of the changes I pushed yesterday, related to the form_dropdown box.

I originally made the changes because the documentation for what's automatically escaped was unclear and I thought I was taking the safe route by changing the use of form_dropdown to an associative array.   However, that caused problems because the "extra" attribute isn't supported as part of the associative array that is passed in - at least not for the form_dropdown function.  So, since I was forced to look at the CI4 code I found that the escaping takes place regardless of whether or not the info is passed in as an associative array.  So, now I understand why the original developers didn't use associative arrays for the form_dropdown, but did for most other form elements.  I always have to learn the hard way.

At least that's my interpretation of the travels I was just on.

**Comment by jekkos** [comment]
A good test might be to see if we now support special chars and if they are rendered correctly. I guess this will work differently for controls like dropdowns then for tables. For bstables we can just leverage builtin escaping from their library.
If CI4 controls offer built in escaping then we should use that. So in this case it's better to rely on the context specific logic (escaping in dropdown might be different then for tables) offered by the components instead.

**Comment by SteveIreland** [comment]
Yes, I've been using the characters  < > ' " &  in the text fields to make sure that they were saved, written to disk, and retrieved without any issues.
