### ISSUE TITLE
CI4: Update CI4 Branch with commits made in master branch

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3741]
I've started manually migrating the commits from master branch into the CI4 branch.

Hopefully we've disabled future weblate udates.   This is an unpleasant activity.  :-)

**Comment by jekkos** [comment]
Thanks for the work @SteveIreland . Ill set weblate in maintenance mode.

**Comment by SteveIreland** [comment]
Only 8 more master commits left to transfer over to CI4 branch.   If time allows I should be able to finish up on Thursday.

**Comment by SteveIreland** [comment]
I completed the merge of the commits and then rebased CI4 onto master.

For some reason it decided to rebase onto a commit point that didn't include the last couple of master changes.

But those two commits have been incorporated into CI4, so I suppose this battle will be fought at a future date.
