### ISSUE TITLE
HTTP 500 Error for Fresh installation

### ISSUE THREAD

**Issue by saurabh261187** [opensourcepos/opensourcepos#3744]
### Installation information

- OSPOS version is:  3.3.8
- OSPOS git commit hash is: 
- PHP version is: 7.2.24
- MySQL or MariaDB version is: 5.7.41-0ubuntu0.18.04.1 
- OS and version is: Ubuntu Linux 18.04.6
- WebServer is: Apache version 2.4.29
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Fresh install at www.nextechsolutions.in . Not under a sub directory. All php extensions are installed and enabled. Followed all steps. When I tried to login gives me HTTP 500 error. Am I missing something ?

**Comment by saurabh261187** [comment]
Also, I checked most Issues regarding this, but am not able to figure things out on exactly what may be the problem here. I am already running an OLD version of OSPOS on the server and it is working fine. Any help will be highly appreciated.

**Comment by odiea** [comment]
Try this and see if it changes anything for you. #3560

**Comment by VonHirsch** [comment]
Here's my cheatsheet for installing release 3.3.7 on a Digital Ocean "LAMP on Ubuntu 18.04" droplet:

```
	COMMANDS
		ln -s /var/www/html
		apt-get update
		wget https://github.com/opensourcepos/opensourcepos/releases/download/3.3.7/opensourcepos.3.3.7.4f3226.tgz			
		cp opensourcepos.3.3.7.4f3226.tgz html
		cd html
		tar xvf opensourcepos.3.3.7.4f3226.tgz
		rm opensourcepos.3.3.7.4f3226.tgz
		chown -R www-data:www-data *
		a2enmod rewrite
		systemctl restart apache2
		mysql
		CREATE SCHEMA ospos;
		CREATE USER 'admin'@'%' IDENTIFIED BY 'pointofsale';
		GRANT ALL PRIVILEGES ON ospos.* TO 'admin'@'%' WITH GRANT OPTION;		
		SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
		FLUSH PRIVILEGES;
		exit		
		mysql -u admin -ppointofsale -D ospos < /var/www/html/database/database.sql			
		apt install -y php7.2-intl php7.2-bcmath php7.2-curl php7.2-mbstring
		ln -s html/application/logs/
		ln -s html/application/config/config.php
				
	FURTHUR CONFIG
	
		Change ENVIRONMENT in public/index.php to "development" to see errors on screen
		
		Changes to html/application/config/config.php:
			$config['base_url'] .= '://' . ((isset($_SERVER['HTTP_HOST'])) ? $_SERVER['HTTP_HOST'] : 'localhost') ;  <-- change localhost to the ipaddress of the VM
			$config['log_threshold'] = 1;
			$config['log_path'] = '/var/www/html/application/logs/';
			$config['db_log_enabled'] = TRUE;

		systemctl restart apache2		
		login
			admin
			pointofsale
```

Overall issues found:

1. mysql ONLY_FULL_GROUP_BY config needed
2. php version issues aren't mentioned
3. mbstring isn't mentioned

Good luck

**Comment by jekkos** [comment]
Do you use latest docker compose file from master @hahayusuf ? I tried that locally and it seemed to init the db fine.

**Comment by hahayusuf** [comment]
I did not use the latest docker compose. I used the docker compose from in the release 3.3.8.

Manually initializing the database fixed it. You may ignore this if this was fixed in the latest docker compose.

Thanks.

**Comment by hahayusuf** [comment]
Hi @jekkos 

I come back with an update. Using the latest docker compose does not fix it unfortunately.

Peeking into the sqlscript image revealed that database.sql is just a blank folder. Not sure why that is the case. Might explain why the import is not running as expected.

![image](https://github.com/opensourcepos/opensourcepos/assets/101795434/33217cff-8c54-40b2-97fa-194ca4d8adb0)

**Comment by jekkos** [comment]
Hi,

You should check in docker init folder under root.

**Comment by jekkos** [comment]
Can you remove all containers fitst? Weird as I Fried locally and it worked

**Comment by hahayusuf** [comment]
Just tried removing everything and trying again. Still no luck. Even tried on Linux, still same issue.

**Comment by jekkos** [comment]
Did you also remove the images? I have now cleared images and containers on my machine, and pulled latest versions again from docker hub. Can you see this in the image list

```
jekkos/opensourcepos                   sqlscript                   4273e2e35083   5 days ago      5.64MB
```
