### ISSUE TITLE
dompdf not prodcucing PDF's for invoice sending

### ISSUE THREAD

**Issue by titusito** [opensourcepos/opensourcepos#3745]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

-  [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: OpensourcePos 3.3.8
- OSPOS git commit hash is: 
- PHP version is: 7.4
- MySQL or MariaDB version is: --
- OS and version is: ubuntu 22.04
- WebServer is: nginx
- Selected language is: en_US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

After failing to send invoices for a couple of days with a new "local" install, I found that dompdf for pdf Invoice sending,  does not work unless php-xml is installed, the docker image does have php-xml, but the local install might not have it and the installaation does not check.
 
Checking for php-xml would be trivial and would make it easier than chasing dompdf not working.

Hope it helps, thank you.

**Comment by SteveIreland** [comment]
I've added the check for php-xml to the CI4 branch.

Thanks for the suggestion.
