### ISSUE TITLE
CI4_update  and redirect()->to('login');

### ISSUE THREAD

**Issue by DEV-byoos** [opensourcepos/opensourcepos#3749]
hello dev's
OSPOS version is: update-ci4 based on OSPOS 3.4.0-dev
OSPOS git commit hash is: ac8ff71
PHP version is: php8.2
MySQL or MariaDB version is: 10.5
OS and version is: GNU/LINUX debian 11.6
WebServer is: apache 2.4
Selected language is: fr
(If applicable) Docker installation: yes and bower
(If applicable) Installation package for the LAMP/LEMP stack is:No

See the Important note: [[https://codeigniter4.github.io/CodeIgnit...onstructor](https://codeigniter4.github.io/CodeIgniter4/incoming/controllers.html#constructor)](https://codeigniter4.github.io/CodeIgniter4/incoming/controllers.html#constructor)

1)
class Secure_Controller....

	public function __construct(....

		if(!$this->employee->is_logged_in())
		{
			//return redirect()->to('login');// No work
			header("Location:".base_url('login'));//BYOOS_tag  it's work fine
			exit();
		}

2)
Controller Employees  no work  return object is NULL
$person_info = $this->employee->get_info($employee_id);

MODELS Employee object  work
	public function get_info(int $person_id): object
	{
		$builder = $this->db->table('employees');
		$builder->join('people', 'people.person_id = employees.person_id');
		$builder->where('employees.person_id', $person_id);
		$query = $builder->get();

		if($query->getNumRows() == 1)	//TODO: ===
		{
			$return =$query->getRow();
echo ' MODELS Employee   ';var_dump($query->getNumRows(), $person_id, $return);die;//BYOOS_tag

			return $return;
		}
courage
Gabriel

**Comment by SteveIreland** [comment]
Part 1 (and one or two other Employee maintenance related fixes) have been incorporated into CI4.

I'm working on resolve the employee maintenance issues and there seems to be more than one.  I'm sure I'll catch the Part 2 issue as part of that effort.

**Comment by DEV-byoos** [comment]
SteveIrland,

thanks for all the updates, #3749 it is useful to place an exit() following the header("location:"...

the language tables are not yet up to date, sorry.
courage my dev's
Gabriel byoosdigital.com

**Comment by SteveIreland** [comment]
Interesting, it works without it in my testing without the exit, but recognizing that there are things that are still mysterious to me, I'll go ahead and add the exit()

**Comment by SteveIreland** [comment]
Actually while making the change, the need for the exit() is obvious.   Duh.

**Comment by DEV-byoos** [comment]
@SteveIreland
several coders have advised against exit(); after a header( location...
See as well:
https://www.php.net/manual/en/function.header.php
Best regards
Gabriel
