### ISSUE TITLE
CI4: Migrate Build to Gulp (instead of Webpack)

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3750]
Since Bower is dead and Grunt requires playing games with software versions, in order to accomplish a build, I'm working on a Webpack flavored version of the build for CI4.  I spent this weekend working on crafting the Webpack build.  Since I need to evaluate every component of the system, I figure I might as well swap out some obsolete components with "not so dead" equivalents.

**Comment by jekkos** [comment]
Nice to hear you are taking this one! I was looking at the travis build and would like to have the branch deployed on dev server..

**Comment by SteveIreland** [comment]
@jekkos I've spent quite a bit of time learning Webpack and attempting to build a configuration that works for us.

After learning what Webpack is all about, I don't see the value for the ospos project - unless, of course, you are about to introduce a vue front end to OSPOS.   Then it makes sense.  Otherwise, it doesn't appear to be a good fit since there are no acceptable adaptors for PHP.   I've found a few play projects but nothing that seems to add much value.

In my frustration with Webpack I decided to play around with Gulp.  In about 3-4 hours I was able to develop a Gulp migration that builds the project similar to the way we are currently doing it using Bower and Grunt.  So, I'm thinking Gulp would be a good build tool - even if it's temporary until we transition to something better.

One complication that you might have some thoughts on, is that the structure we target is a combined dev and production so that we can easily toggle between development mode and production mode using Code Igniter.  Webpack isn't friendly to this target structure - instead wanting to build for either development or production.

I guess my question is there some current or future value to Webpack that you see that I'm missing that would make it worth the effort.   I'm almost at the point where I believe the solution is to build my own Webpack plugin.

**Comment by jekkos** [comment]
That sounds a bit disappointing. In which way do we need specific php support from the webpack? Perhaps it's more focused on fullstack javascript apps?

I'm  fine with gulp but curious to know what was the exact blocker. From a build tool we'd ,eed

* install javascript (node) dependencies
* minify those dependencies by concatting into a compact version
* minify the css sheets by concatting them
* inject the resolved javascript dependencies into the php header file, indeed one for development and one for production (which has two minified files)
* some kind of cachebreaker that injects a new hash into the header once an input changes so the browser reloads
* something that zips the build output together

**Comment by SteveIreland** [comment]
Yes, Webpack is definitely focused on javascript only apps (with plugin support for CSS, SCSS, images, and other resource stuff.  Since we aren't a "javascript" project, Webpack can't navigate it's way through the php files to identify "imports" and "requires" as it is intended to do.   I fabricated a "root" js file that pretended to require the handfull of javascrpt files we have in the public folder and that worked pretty well.  It concatenated them and minimized them into an opensourcepos.min.js file, as we would expect.  However, that was all it did since it didn't seem possible (at least to me) to tell webpack how to parse the php files to identify JS dependencies.

I tried to find some php-loaders that hopefully attempted to do that, but none of them seemed like they invested the effort it would actually take to do a thorough job.  If I do another google search on another day then my results might be different - frequently is.

I used npm to pull all of the JS and CSS files we needed into node_modules and then used the copy-webpack-plugin to import all of the JS and css files we needed from node_modules into a resources folder with cachebreaking feature..  That was time consuming, but simple enough.  I took the research from this effort to do something similar for the gulp effort.

Unfortunately for me, I could not find a nice way to inject stylesheet and JS links into our header.php file the way we currently do it (i.e. including links for running the app in development mode and running the same set of code in production mode).

In fact, in development mode it seems to only want to inject links in the DOM running on their built in development server.  It would only do the actual file updates when building for production mode. 

Very confusing to me, but if one is a vue or react developer then I'm sure it makes total sense.

If you're okay with gulp (at least temporarily, until you've determined that I am missing something) then I'll go ahead and finish out the gulp effort and include it in the CI4 project so that we can identify issues are being introduced.

There were one or two projects that apparently were still available through bower, but aren't available through NPM.  I selected replacements that I felt were most likely to work.

**Comment by jekkos** [comment]
Ok in this case gulp might be less opnionated on how we need to build this js code. What we need from npm is a list of import files and pass those to gulp. In bower there used to be a file listing the exported files, but this was not used consistently by the dependencies or sometimes not used at all. Hopefully node does a better job here, so that we can easily distinguish source files from already minified ones.

**Comment by SteveIreland** [comment]
The rework is finally starting to look good.  I should have the first push for this effort to the CI4 branch this weekend.

**Comment by jekkos** [comment]
We will need to adapt some documentation and instructions as well. Nice to hear you are making progress, would like to help out a bit but that might be in June as Im enjoying a bit the rainy scottish weather now

**Comment by SteveIreland** [comment]
I doubt if  the rainy Virginia east coast weather that I'm NOT enjoying is as nice as what you're enjoying, but at least I'm prevented from spending the day mowing lawns.  :-)

**Comment by jekkos** [comment]
I wonder how you know which files need to go in wiredep as bower main file is  gone now. In some examples I saw they list the dependenciy files manually in a config file. Does node module have some kind of file hierarchy convention that we can use to pick up those entries? Eg you coupe just scan for min.js files in the installed modules and inject those as a first step. Then concat them into a opensourepos.min.js

I know that for bower a lot of tweaking was needed to make this approach work, so it might be better in the end to tackle this ourself.

**Comment by SteveIreland** [comment]
Okay, so the build is now done using gulp and this has been committed to the CI4 branch.  All of this is documented in the BUILD read me.

The new build steps are:

- composer install
- npm install
- npm run build

There is additional work to be done, but the primary goal of this commit is to be able to build a functional dev mode and a functional production mode.  This is working for me, so since so much work has been put into it, I felt it best to push now so that others can check to see if it works for them.  (Lint, licensing, and zipping up is NOT yet included in this commit).

**Comment by jekkos** [comment]
I have now reverted the changes I did to the grunt buildbox, as this broke master. I think in this case it's best for me to design a gulp buildbox that can then be used in travis on the CI4 branch , this way we don"t interfere with master for the time being

**Comment by jekkos** [comment]
So currently demo is back on 3.3.8 and dev is at latest master. There were a couple of translations added. I suggest to squash those commits and port them to CI4 branch in one go.

**Comment by SteveIreland** [comment]
I made significant progress on some customizations, so I should have some time to return to work on the gulp build.  I totally forgot about the need to build the database.php so that will be my primary focus this week.  That seems like it should be trivial.

**Comment by jekkos** [comment]
I pulled your changes yesterday, will check tonight if I can build the gulp using node and composer

**Comment by SteveIreland** [comment]
I committed a change that builds the database.sql file.  Tested it by rebuilding the project from scratch (including the database) and it appears to work.

When doing that I noticed that at least one of the config values required for SMTP wasn't initialized.  I'll add that to my "to-do" list

**Comment by jekkos** [comment]
The datavase.sql it was just a concat I believe. The reason it was split was because of the initial phppos migration

**Comment by SteveIreland** [comment]
That's true, but don't forget the complexity of it.  :-)   I had to install another gulp plugin so that I could add a comment to the database.sql telling users to "don't touch!"   lol

That's why gulp-header is now part of the build.

**Comment by SteveIreland** [comment]
Also @jekkos, did you want me to carry forward the phppos migration script build?  Or is that now obsolete?

**Comment by daN4cat** [comment]
Migration scripts were build to work incrementally. Unless there is a path problem they shouldn't be touched and just any SQL change should be part of a new script.

**Comment by daN4cat** [comment]
Or at least it used to be like that. Maybe the world changed since I put my nose into this...

**Comment by SteveIreland** [comment]
Nope.  It's still the same way.  Nothing has changed.  The gulp build creates the database.php file using the untouched tables.sql and the untouched constraints.sql.   The migration scripts still kick off when logging in for the first time into ospos with a virgin (or partially defiled) database.

**Comment by SteveIreland** [comment]
And where have you been?!?!   I've been running amuck, with no one to keep me in check.

**Comment by objecttothis** [comment]
During `npm install` I get the following deprecation errors.  Are these anything we should do something about?
```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
```

I also get the vulnerability audit results.
```
audited 963 packages in 3m

123 packages are looking for funding
  run `npm fund` for details

20 vulnerabilities (4 moderate, 16 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by objecttothis** [comment]
IMO we can close this ticket as the build works in CI4 now.  @SteveIreland thoughts?

**Comment by jekkos** [comment]
Job was done thanks all!
