### ISSUE TITLE
ci4-upgrade,   Fresh install

### ISSUE THREAD

**Issue by DEV-byoos** [opensourcepos/opensourcepos#3754]
Good evening,
CONFIG:
OSPOS version is: upgrade-ci4 based on OSPOS 4.0.0-dev
OSPOS git commit hash is: [a312434]
PHP version is: php8.2
MySQL or MariaDB version is: 10.5
OS and version is: GNU/LINUX debian 11.6
WebServer is: apache 2.4
Selected language is: en-US
(If applicable) Docker installation: yes and bower
(If applicable) Installation package for the LAMP/LEMP stack is:LINUX

I launched into a new installation as an experiment...
Result:
"compose" is complete
npm and nodejs is complete
# populate your database with phpMyAdmin
/root/app/Database/database.sql

# install docker mode root... su -
apt-get install docker.io
docker-compose build
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.mysql: 'volumes_from'

here i am stuck

After connecting my working database
first START
message: Attempt to read property "version" on null

location: APPPATH/Libraries/MY_Migration.php at line 37
re-blocked

**Comment by odiea** [comment]
Not ready for prime time. Try again in about 6 months.

**Comment by DEV-byoos** [comment]
Good evening,
Well, my goal is to move the ci4-upgrade branch forward and in this direction I have already reported anomalies and proposed ten fixes.
on my build:
-- the FR, en-GB languages are migrated on my compilation
-- I also reordered the login view with bootstrap5.3 it works fine
I am in progress on the header.php ditto css and non-functional js
And many more, in six months where will we be :)
bye

**Comment by jekkos** [comment]
the `volumes_from` is deprecated in compose 3. I might just try to set compose file version back to 2 instead.

**Comment by jekkos** [comment]
there is no container yet for 3.4, so I have temporarily set version in ci4 branch to 3.3.8. First I need to get the CI build working and had some issues with this last week, now npm container is complaining it can't find bower, while the dependency was installed.

**Comment by DEV-byoos** [comment]
good evening dev's

I worked on the login views and the header
RESULT:
the login script embeds the incomplete css, add the following line:
		<link /Viewzrel="stylesheet" type="text/css" href="css/login.min.css"/>

OK for /root/app/Views/login.php
... next for header.php

**Comment by SteveIreland** [comment]
That looks like a build issue.  Since I was primarily focused on building for development I can imagine that I missed something on the production side.  However, now I'm focused on the Webpack build and I'm making slow, but steady, progress.  I'll make sure it doesn't get overlooked.

**Comment by DEV-byoos** [comment]
@steveIrland
thank you for taking into account the feedback of my experimental coding, as I already told you the goal is to improve the ci4-update branch.
I don't have the opensourcepos.js script to test the code ho I only have min.js
by plugging the opensource.min.js script of the version ospos 3.3.4 I can work on the module read, create, delete, it's good to know...
PS a question about DOCKER, what is its use on OSPOS?
there is already compose then npm, then bower???
bye
Gabriel

**Comment by DEV-byoos** [comment]
hello devs,
I made myself rare last week because I tried to install the CI3 version osposv3.3.8 ho without success.
I return to ci4-upgrade for some suggestions like improving the OSPOS root .htaccess file and the /OSPOS/public/ .htaccess file.

# .htaccess patch
# IN /root/.htaccess force the http://localhost/public

# FIX
     RewriteRule ^(.*)$ %{REQUEST_URI}public/ [R=301,L]

# FIX IN /root/public/.htaccess
# if in web root Do not forget the? behind index.php
RewriteRule ^([\s\S]*)$ index.php?/$1 [L,NC,QSA]

https://www.drupal.org/forum/support/post-installation/2016-09-19/how-to-remove-indexphp-from-urls

follow me

**Comment by DEV-byoos** [comment]
Hello devs

the OSPOS site is hacked on May 26, 2023
https://opensourcepos.org/

moreover, I have been a bit rare lately but I continue to reflect on the improvement of ci4-upgrade
my only problem is the opensource pos.min.js script which sends me a dependency error.. I do not have the opensource pos.js source which was present on the install of versin 3.3.4...
Who can help me?
bye

**Comment by jekkos** [comment]
Checking with @WebShells . I recently changed DNS records to point to a new cname record.

**Comment by DEV-byoos** [comment]
Hello SteveIreland

This cancels and replaces the POST of yesterday May 29, 2023

May 30 in the morning here 5:00 am, I launched into the "FRESH INSTALL of OSPOS git commit hash is: 1cdefef

Super installed the first time almost without modification, I test all this ho! finally we got there, THANK YOU for you SteveIreland and jekkos, it works after some small corrections:
IN /root/app/Views/partial/header.php no see favicon added images/
<link rel="shortcut icon" type="image/x-icon" href="<?php echo base_url() ?>favicon.ico">

# IN /root/App/Libraries/Token_lib.php at line 158 Token::get_tokens()
# FIX line 5 use App\Models\Tokens\Token; // T of Tokens upper case

# update language for en-GB and fr IN /root/app/Language

zero ERROR, zero CRITICAL it'OK
thank you again for this great work
Gabriel

**Comment by SteveIreland** [comment]
Thanks for the feedback.  Since it was trivial, I just added a commit that fixes the favicon issue.  I'll take a look at the others later this evening.

**Comment by DEV-byoos** [comment]
SteveIreland hello

if you're in shape a little last for the road :)

TypeError
NumberFormatter::setAttribute(): Argument #2 ($value) must be of type int|float, string given
# IN /root/app/Helpers/local_helper.php line 387 replace '' by 0
$fmt->setAttribute(NumberFormatter::GROUPING_SEPARATOR_SYMBOL, 0);
bye
Gabriel

**Comment by DEV-byoos** [comment]
hello dev's

two FIX this morning
# IN  /root/app/controllers/Sales.php
App\Models\Item_kit::is_valid_item_kit(): 
Argument #1 ($item_kit_id) must be of type int, string given, called 
in /var/www/html/ci4_opensourcepos_latest/app/Controllers/Sales.php on line 494 

FIX  line 484  (int)
$item_id_or_number_or_item_kit_or_receipt = (int)$this->request->getPost('item', FILTER_SANITIZE_FULL_SPECIAL_CHARS);

404 error Controller or its method is not found: \App\Controllers\Receivings::postAdd
# IN  /root/app/controllers/Receivings.php  replace  add   by  postAdd
#FIX	public function postAdd(): void
	{...
good use
Gabriel

**Comment by DEV-byoos** [comment]
hello dev's
At the moment I test  the Reports

404error Controller method is not found: "index"  IN  /root/app/controllers/Reports.php
# IN  /root/app/Helpers/report_helper.php

function show_report(string $report_prefix, string $report_name, string $lang_key = ''): void
{...
	$report_prefix = empty($report_prefix) ? '' : $report_prefix . '_';// replace (dot)  .   by(underscore) _
...
At the moment I test  the Reports
follow me
Gabriel

**Comment by odiea** [comment]
It appears that this will be the next issue for Reports not showing. 404error Controller method is not found: "index" IN /root/app/controllers/Reports.php
