### ISSUE TITLE
Customer debt control or sales due

### ISSUE THREAD

**Issue by nukerj** [opensourcepos/opensourcepos#3758]
Greetings, I show the functionality of a new module developed at the request of a client. The modules are Accounts Receivable and account statements; They serve to keep track of a debt sales or due sale.

Contact +58412-644-74-07 via whatsapp or telegram @jvilchez

https://github.com/opensourcepos/opensourcepos/assets/47283494/805a9260-9eee-438a-b0d1-d0079e37875f

**Comment by nukerj** [comment]
https://github.com/opensourcepos/opensourcepos/assets/47283494/0d4290f4-3ac6-4404-9192-f537c69b3a5f

**Comment by adityaharist** [comment]
Hi! 
Can you tell me how do you make those new modules (statements of accounts, account receivable)?

**Comment by nukerj** [comment]
greetings.  I already reply to WhatsApp

**Comment by nukerj** [comment]
> Hi! Can you tell me how do you make those new modules (statements of accounts, account receivable)?

Write me to WhatsApp
