### ISSUE TITLE
Access forbidden! 

### ISSUE THREAD

**Issue by jsyl80** [opensourcepos/opensourcepos#3759]
i have installed  xampp 7.4.16.0 and ospos opensourcepos.20210101114640.3.3.3.8e52bd

i have install successfully but i got this error,   is there anybody can help me?

Access forbidden!
You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.

If you think this is a server error, please contact the [webmaster](mailto:you@example.com).

Error 403
[localhost](http://localhost/)
Apache/2.4.46 (Unix) OpenSSL/1.1.1j PHP/7.4.16 mod_perl/2.0.11 Perl/v5.32.1

**Comment by SteveIreland** [comment]
You might find some helpful info here: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-using-Xampp-(recommended-for-testing-or-local-use-only).

But, why would anyone install 3.3.3 when they can enjoy the massive benefits of 3.3.8?

**Comment by jsyl80** [comment]
Hi, 
Due to respect, 
I installed  ospos v 3.3.8. and And  xampp 7.4.16.0.    for your suggestion and I overcome one step and I got now another prob


When I try to log in this error is coming ——>.  The installation is not correct, check your php.ini file.

Now what have to do? Pls let me know 
Thanks

**Comment by odiea** [comment]
You did not read the readme to use the correct version. Try the following https://github.com/opensourcepos/opensourcepos/releases/download/3.3.8/opensourcepos.3.3.8.ffe492.zip

**Comment by jsyl80** [comment]
hi i installed on MacOS  xampp v  xampp 7.4.16.0 and OSPOS 3.3.8
the error is 
**The installation is not correct, check your php.ini file.**
is there anybody can help me?
