### ISSUE TITLE
New Feature?  Daily Sales for Selected Customer

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3765]
I just finished up the following requested change for a client.  When processing a quote, work order, or invoice they wanted Daily Sales to filter on the currently selected customer.   I did this by adding a new filtering option named "Selected Customer" and when selected it will filter on the customer that is selected.   When going to daily sales, I will automatically select that option if there is a currently selected customer.  The option can be deselected.

If there is any interest, I can add this to the base system.

**Comment by odiea** [comment]
What would be the difference between that and the Customer report?

**Comment by SteveIreland** [comment]
Well, to be honest ... I hadn't visited the customer report until you mentioned it.  But I wish you hadn't mentioned it, because it's not working in the 3.3.8 release that we're using - so now I have another issue to fix.  :-)

The reason for their request is that in the sales register it is easy to identify and select a specific customer, and they can make sure that they have selected the correct customer.  Then when they click on daily sales they do not need to, again, search for a specific customer.  In fact, if they have two customers that have the same name (a frequent occurrence) then they won't be accidentally look at the wrong sales history.

They work in a very chaotic environment with customers, service personnel, and even the owner bombarding them with requests and distracting them from their immediate task.  So, anything the software can do to reduce opportunity for errors is a good thing.

**Comment by jekkos** [comment]
Was thinking that enabling the daily view for a customer might then be done by adding their id in the query string for the daily view? This way you could make the name clickable in register so it opens their history in a new tab or so? I wouldnt rely on the session state to get selected one as that is less portable as you can only enter the screen through register

**Comment by SteveIreland** [comment]
Since this wasn't a stellar idea, I'll cancel this.  For my client's purposes they are currently only using the Daily Sales from the register, so it works well for them.  But I can see the value of having it as an option from the customer list.  I might come back to this later, but "I have promises to keep and miles to go before I sleep". 

Thanks for the feedback.
