### ISSUE TITLE
Feature request: Custom Payment Type

### ISSUE THREAD

**Issue by erikdemarco** [opensourcepos/opensourcepos#3767]
Please implement feature to add custom payment method. mutliple countries have different payment methods. And multiple business have multiple way of payment.

For example a restaurant business have Grubhub, UberEats, Doordash. To know which platform this sales assigned to, we can use custom payment type. So we can view the detailed report for each payment.

**Comment by nukerj** [comment]
@erikdemarco Greetings, I have done it from the database, through a module I manage the new payment methods that I want to have and then I can see them in the payment method options.  If you are interested, contact me Telegram @jvilchez WhatsApp +58412-6447407

**Comment by jekkos** [comment]
#2508 #371
