### ISSUE TITLE
Question for Linux Testing

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3770]
I'm a Windows guy, but I want to be able to test the build components targeting a Linux Platform.

So I've upgraded to Windows 11 Pro, installed Docker, and I'm going to use WSL instead of Hyper-V.

So, the final question is which flavor of Linux should I use?  Apparently I have a plethora of choices, but since I know nothing, I'm open to suggestions (if anyone wishes to share their preference).  Thanks in advance.

- [Ubuntu 18.04 LTS](https://www.microsoft.com/store/apps/9N9TNGVNDL3Q)
- [Ubuntu 20.04 LTS](https://www.microsoft.com/store/apps/9n6svws3rx71)
- [Ubuntu 22.04 LTS](https://www.microsoft.com/store/apps/9PN20MSR04DW)
- [openSUSE Leap 15.1](https://www.microsoft.com/store/apps/9NJFZK00FGKV)
- [SUSE Linux Enterprise Server 12 SP5](https://www.microsoft.com/store/apps/9MZ3D1TRP8T1)
- [SUSE Linux Enterprise Server 15 SP1](https://www.microsoft.com/store/apps/9PN498VPMF3Z)
- [Kali Linux](https://www.microsoft.com/store/apps/9PKR34TNCV07)
- [Debian GNU/Linux](https://www.microsoft.com/store/apps/9MSVKQC78PK6)
- [Fedora Remix for WSL](https://www.microsoft.com/store/apps/9n6gdm4k2hnc)
- [Pengwin](https://www.microsoft.com/store/apps/9NV1GV1PXZ6P)
- [Pengwin Enterprise](https://www.microsoft.com/store/apps/9N8LP0X93VCP)
- [Alpine WSL](https://www.microsoft.com/store/apps/9p804crf0395)
- [Raft(Free Trial)](https://www.microsoft.com/store/apps/9msmjqd017x7)

**Comment by SteveIreland** [comment]
I'm leaning toward Debian since it's smaller and tighter.  And presumably since it includes less "fluff", which suggests that it might be better for identifying what needs to be added in order to support OSPOS.

**Comment by odiea** [comment]
I installed Ubuntu 18 on an old laptop I had and it works good. I let it update to 20 and have not had any issues with it. I also installed webmin and phpmyadmin to make it easier for me.

**Comment by jekkos** [comment]
I also tried Debian on WSL, but I think it does matter how you install it. I used `wsl --install` but that gave me a real old version of debian. Currently the package manager is broken and it cannot resolve some package sources due to deprecation, so you might need to google around on how to have a more recent version installed (eg buster or bullseye).

**Comment by SteveIreland** [comment]
Okay based on Jekkos's  negative experience with Debian and Odiea's positive experience with Ubuntu and since I like positive experiences, I'll start with Ubuntu and see what happens.

Thanks for the feedback.
