### ISSUE TITLE
CI4: Reports

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3773]
Modify the Reports infrastructure to be compatible with CI4.

**Comment by SteveIreland** [comment]
Over this weekend I made some changes to the reports feature so that it would work, for at least what I wanted to see (the labels working and the reports appearing to work somewhat)

Since I didn't yet have any data to test with I just wanted it to "not crash".

However, I stumbled across something that I coded up a work-around for, but it might not be suitable for a permanent fix.

Reports is heavy with JavaScript and the way it works seems to fail to go through CI4 infrastucture to do its thing.  The result is that "getIndex()" is required to get to the filter panel, but after that, it insists on calling the pre-CI4 "index()" method.  I think it's because Reports does a windows.location replacement to go to the data after submitting the filter.  But I'm not a JavaScript wizard - just a journeyman.

So what you will find is that I added to Reports.php is the function index() that calls getIndex().  That seems to be working.

On a different topic.  I did work through the issues with Item Kit maintenance and that seems to be working now.

**Comment by odiea** [comment]
The Reports show with their correct names but after the Input there is no Report. Thanks for all the work.

**Comment by SteveIreland** [comment]
@odiea I'm guessing you tested with data so there there should have been a report.  Thanks for checking it out and letting me know I have more work to do on it.  👍

**Comment by odiea** [comment]
@SteveIreland  The other issue in Reports listing is the Inventory grants are not working so Inventory Reports are not showing in the listing..

**Comment by SteveIreland** [comment]
Yeah, that was weird.  I went ahead and did the commit because they were showing when I last tested, but when I went back to retest after you pointed out your issue I also noticed that the inventory reports were not appearing.  It seems I have a stability issue in my test environment.

**Comment by DEV-byoos** [comment]
@SteveIreland
OK, well received I had been working on the subject for a few days and I persuaded my time to test the routes regex, well I had seen this javascript problem, BRAVO SteveIreland
I try a "FRSH install with the last commit
see you soon

**Comment by odiea** [comment]
Anyone making any headway on the Reports to show correctly?

**Comment by jekkos** [comment]
This week I briefly tried to get things running again, but have to find more time to make progress.

**Comment by objecttothis** [comment]
@SteveIreland is this still an issue that you plan to take on?

**Comment by odiea** [comment]
@objecttothis Great bunch of commits. Thanks It's nice to see the Detailed, Specific and Inventory Reports finally working.

**Comment by objecttothis** [comment]
Summary reports are working now.

**Comment by objecttothis** [comment]
For graphical reports we are getting a problem related to chartist
```
Uncaught TypeError: can't assign to property "top" on 5: not an object
    extend http://localhost/opensourcepos/public/resources/js/chartist-8a7ecb4445.js:94
    extend http://localhost/opensourcepos/public/resources/js/chartist-8a7ecb4445.js:92
    Pie http://localhost/opensourcepos/public/resources/js/chartist-8a7ecb4445.js:4501
    constr http://localhost/opensourcepos/public/resources/js/chartist-8a7ecb4445.js:1762
    <anonymous> http://localhost/opensourcepos/public/reports/graphical_summary_categories/2010-01-01/2024-04-29/complete/all/0:355
chartist-8a7ecb4445.js:94:11
    extend http://localhost/opensourcepos/public/resources/js/chartist-8a7ecb4445.js:94
    extend http://localhost/opensourcepos/public/resources/js/chartist-8a7ecb4445.js:92
    Pie http://localhost/opensourcepos/public/resources/js/chartist-8a7ecb4445.js:4501
    constr http://localhost/opensourcepos/public/resources/js/chartist-8a7ecb4445.js:1762
    <anonymous> http://localhost/opensourcepos/public/reports/graphical_summary_categories/2010-01-01/2024-04-29/complete/all/0:355
```
![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/faa51394-9169-4229-bee1-ce0bb4f939bf)

**Comment by jekkos** [comment]
one plugin dependency was installed using npm but not copied. Some reports do work now but I do still get the error you post here above in at least one of them.

**Comment by jekkos** [comment]
@objecttothis the error you posted occurred only in pages with a pie chart. For some reason, a config object with padding for top and bottom was set on a chartPadding property that was just a number.

Maybe something changed in chartist in a backwards incompatible way, as I have the impression this `chartPadding` setting should have been a dict before. I simply changed the type of this config option and now it seems to work.

**Comment by objecttothis** [comment]
This is all working now.
