### ISSUE TITLE
Remove/Hide some Payment types

### ISSUE THREAD

**Issue by TheCoderZA** [opensourcepos/opensourcepos#3775]
Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I am looking to remove or even hide some of the payment types from the Sales Drop Down Selector, I would only like to keep Cash and Debit Card (would like to change this to just say Card)

I am abit new to editing so have tried to find the array that contains these details but no luck.

I appreciate the assistance

**Comment by SteveIreland** [comment]
Also, I'd suggest that you download a free copy of a PHP editor.  The search features they provide are simply amazing.  :-)

**Comment by TheCoderZA** [comment]
> The payment options are set in two places:
> 
> First: `app/Helpers/locale_helper.php` in the function `get_payment_options(...)`
> 
> Then it is revised again in: `app/Models/Sale.php` in the function `get_payment_options(...)` for sales specific purposes.
> 
> You don't want to mess with the Cash payment because that's used to control program logic.
> 
> But I believe the others are open to dropping. I'd comment out the ones you want to drop (just in case you need to add them back for some reason). I haven't looked at payment dependencies in a couple of years.

Thank you will check that

**Comment by TheCoderZA** [comment]
> The payment options are set in two places:
> 
> First: `app/Helpers/locale_helper.php` in the function `get_payment_options(...)`
> 
> Then it is revised again in: `app/Models/Sale.php` in the function `get_payment_options(...)` for sales specific purposes.
> 
> You don't want to mess with the Cash payment because that's used to control program logic.
> 
> But I believe the others are open to dropping. I'd comment out the ones you want to drop (just in case you need to add them back for some reason). I haven't looked at payment dependencies in a couple of years.

I found the gift card option and was able to remove it but cannot find the Check or Due option to remove. I dont mind leaving the Cards and Cash option

**Comment by jekkos** [comment]
cfr recent request from @odiea on the payment types, it wouldn't be too much work to make it configurable in settings. I'd use the multiselect widget that is in use for the barcode formats and load the payment types array in that one. Then reference it from the config instead.
