### ISSUE TITLE
login credentials for demo is not working

### ISSUE THREAD

**Issue by dilawer** [opensourcepos/opensourcepos#3779]
In readme, there is mentioned that this demo will work with following credentials
https://demo.opensourcepos.org/login 

username: admin
password: pointofsale

but its not working, can someone help on this. Thanks

**Comment by jekkos** [comment]
Ok I think I see what happened, while trying to setup the CI4 branch, I broke the last command of the redeploy script which is setting the CI_ENV for the dev and demo containers. Setting it to testing disables the password change functionality. I fixed this now.

**Comment by odiea** [comment]
@jekkos Is the Dev Demo set to the new CI4 branch?

**Comment by jekkos** [comment]
Ah ok that tip could be useful, currently the build fails for a weird reason, while the container builds fine locally. I need to look into this further, but at least I'm already able to get to the login screen.

**Comment by odiea** [comment]
Also until others get involved to help @SteveIreland out it really is not usable for deployment

**Comment by jekkos** [comment]
@odiea you mean there are too many bugs currently? If I can spin it up it would already be a step forward, at least we can try to make a list of the issues we have now currently, but it seems then there are plenty
