### ISSUE TITLE
cash adjustment  | Enable | Disable |

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#3780]
Please explain me about the cash adjustment features.

Is cash adjustment really needs? I enable the Allow Derived Sale Quantity (for example in a Gas Station: PRICE=59.21; Amount Entry:500; Quantity: 8.44 liters) but instead of 500 it cost 499.73 only and there is a cash adjustment of : 0.27

**Comment by izeblood** [comment]
i understand this already..but my concerned now is the receipt...I prefer not to display the cash adjustment in the receipt and instead in the given example of 499.73 to make it 500.00 in the receipt

**Comment by SteveIreland** [comment]
Are you asking to have a new receipt configuration option that would turn off displaying the payment type "Cash Adjustment"?

I don't live in a world that allows cash rounding, so I don't know what's customarily expected.   But that change wouldn't be too hard.  The gift card processing logic makes it a tiny bit more complex because we wouldn't want this change breaking that.

**Comment by izeblood** [comment]
> Are you asking to have a new receipt configuration option that would turn off displaying the payment type "Cash Adjustment"?
> 
> I don't live in a world that allows cash rounding, so I don't know what's customarily expected. But that change wouldn't be too hard. The gift card processing logic makes it a tiny bit more complex because we wouldn't want this change breaking that.
------------------------------------------------------------------------------------------------------------------------------------

Thank you for your response. I appreciate your willingness to consider adding a new receipt configuration option to turn off the display of the payment type "Cash Adjustment."

Considering that cash rounding is not customary in our region, it would be beneficial for our business to have the ability to exclude the cash adjustment from the receipt. This customization would align with our preferred receipt format and ensure a better customer experience.
I understand the importance of ensuring the gift card processing logic remains intact. It would be great if you could take that into consideration while implementing this change, to prevent any potential issues.
I look forward to hearing from you and appreciate your efforts to meet our specific requirements.

**Comment by nukerj** [comment]
@izeblood You can easily do it from configuration, check to activate and deactivate this type of payment.  then it goes to locale helper and in get payment types it conditions the visualization with the configuration variable that it has created.  It's not that hard to do.

**Comment by izeblood** [comment]
can you make it more specific?
