### ISSUE TITLE
Request for all -For adding a Credit/ Customer Account management 

### ISSUE THREAD

**Issue by jeetdebnath** [opensourcepos/opensourcepos#3784]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by WebShells** [comment]
Yeah the issue/request details are super exciting... lol!

**Comment by nukerj** [comment]
@jeetdebnath I have something that maybe you can use (It is paid).  It is called accounts or receivable, which is used to keep track of credits and receive payments or installments of that debt.  For example, if the question is 200, you can pay 50 today in a few days, filter the client or invoice again and there 100 more and so on as necessary.  and another Account Statements module where the details of credits received and a payment or credit receipt for each operation can be observed.  I contacted Telegram @jvilchez WhatsApp +58412-6447407

**Comment by WebShells** [comment]
@nukerj try finding another way than spamming every issue being opened... I deleted your previous comment.

**Comment by nukerj** [comment]
Disculpe pero Ningún spam . Respondo personalmente los comentarios uno a uno  de forma directa he ayudado a varias personas y la mayoría me contacta vía Telegram algunos me colaboran con algo de dinero de forma voluntaria, otros los hago totalmente gratis . Lo hago de este modo ya que que la mayoría de las solicitudes no son respondidas o tomadas en cuenta. Pero esta bien dejo de brindar soporte a OSPOS que cada quien se resuelva el problema
