### ISSUE TITLE
how to add stock location in the receipt?

### ISSUE THREAD

**Issue by izeblood** [opensourcepos/opensourcepos#3786]
![Screenshot_17](https://github.com/opensourcepos/opensourcepos/assets/32444665/ddc85e20-c1f1-49d2-a70d-2f1c687f770e)

I want to add the stock location as the header of the receipt since I had 3 different stock locations and every stock location can make a sale base on the availability of the stocks

**Comment by odiea** [comment]
You can try the following and see if it works for you. In the proper location in the receipt.
```
                <?php
		if($config['receipt_show_company_name'])
		{
		?>
		
		<?php	
		foreach($cart as $line => $item)
		{
		?>
			<div id="company_name"><?php echo $item['stock_name'] ?></div>
		<?php
		}
		?>
		<?php
		}
		?>
```

**Comment by izeblood** [comment]
Kindly give more specific files and line where to put this code? Thanks @odiea

**Comment by odiea** [comment]
application/views/sales/receipt_default.php

**Comment by izeblood** [comment]
> application/views/sales/receipt_default.php



> @izeblood You can try the following and see if it works for you. In the proper location in the receipt.
> 
> ```
>                 <?php
> 		if($config['receipt_show_company_name'])
> 		{
> 		?>
> 		
> 		<?php	
> 		foreach($cart as $line => $item)
> 		{
> 		?>
> 			<div id="company_name"><?php echo $item['stock_name'] ?></div>
> 		<?php
> 		}
> 		?>
> 		<?php
> 		}
> 		?>
> ```

This code doesn't work .. I display nothing...

**Comment by odiea** [comment]
Replace the following line. Was doing this in the ci4 branch
```
if($this->config->item('receipt_show_company_name'))
```

**Comment by izeblood** [comment]
<div id="receipt_wrapper" style="font-size:<?php echo $this->config->item('receipt_font_size');?>px">
	<div id="receipt_header">
		<?php
		if($this->config->item('company_logo') != '')
		{
		?>
			<div id="company_name">
				<img id="image" src="<?php echo base_url('uploads/' . $this->config->item('company_logo')); ?>" alt="company_logo" />
			</div>
		<?php
		}
		?>

		<?php
		if($this->config->item('receipt_show_company_name'))
		{
		?>
			<div id="company_name"><?php echo $this->config->item('company'); ?></div>
		<?php
		}
		?>
		
		<?php
		$stock_location = ""; // Initialize the stock location variable
		foreach($cart as $line => $item)
		{
			if($item['print_option'] == PRINT_YES)
			{
				$stock_location = $item['stock_name']; // Get the stock location value
				break; // Exit the loop after getting the first valid stock location
			}
		}
		?>

		<?php if (!empty($stock_location)) : ?>
			<div id="stock_location">Stock Location: <?php echo $stock_location; ?></div>
		<?php endif; ?>

		<div id="company_address"><?php echo nl2br($this->config->item('address')); ?></div>
		<div id="company_phone"><?php echo $this->config->item('phone'); ?></div>
		<div id="sale_receipt"><?php echo $this->lang->line('sales_receipt'); ?></div>
		<div id="sale_time"><?php echo $transaction_time ?></div>
	</div>
	
this code works to me

**Comment by izeblood** [comment]
It's nice to include this to next update in stock location module and adding more data fields like:
ex. Stock Location:  Name, Address, Contact No:
* with separate series numbers of receipt for each Stock Locations.

**Comment by odiea** [comment]
I believe the hardest part would be saving it under Configuration. It was easy adding address and phone number to the stock location db but it needs to be edited in the database.
