### ISSUE TITLE
Cant access to the localhost/ospos/public

### ISSUE THREAD

**Issue by domo536** [opensourcepos/opensourcepos#3794]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: 5ad6097 //not sure whether is this or not
- PHP version is: 7.4.33
- MySQL or MariaDB version is: MariaDB 10.4.27
- OS and version is: Windows 11
- WebServer is: Apache 2.4.54
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Hi there, I keep facing the issue "Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php". 

I am using XAMPP for this and followed along INSTALL.md until step 7, localhost/public/ospos/ was unable to access the login page I have tried changing the .htaccess as below:

![image](https://github.com/opensourcepos/opensourcepos/assets/85671043/337b6a11-90a1-4766-a9f8-098a3754f5d0)

and also I downloaded this project from here
![image](https://github.com/opensourcepos/opensourcepos/assets/85671043/f373004d-d5cc-4d1b-af42-8e7739189361)

Also, I followed this too "https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-using-Xampp-(recommended-for-testing-or-local-use-only)".

**Comment by odiea** [comment]
Source code has to be built. Download the zip then try it.

**Comment by domo536** [comment]
Fixed, thanks!

![image](https://github.com/opensourcepos/opensourcepos/assets/85671043/646ac67b-5b76-4c1e-809f-a8accab206dd)

**Comment by nguyenkhanhdaniel** [comment]
> Fixed, thanks!
> 
> ![image](https://private-user-images.githubusercontent.com/85671043/260409782-646ac67b-5b76-4c1e-809f-a8accab206dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjg2ODQsIm5iZiI6MTczMzM2ODM4NCwicGF0aCI6Ii84NTY3MTA0My8yNjA0MDk3ODItNjQ2YWM2N2ItNWI3Ni00YzFlLTgwOWYtYThhY2NhYjIwNmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDAzMTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NjAzYzliYjU4ZWU0ZGI5ODU4MjY5ZDM0YTU3YTkyNTQxNDk1M2M5NmQxNjgwNzEzNmQyMTVjNzlmNTBmM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AP5-9qYkEE_OXp44gQJ1Xl2GGj6GsSvX-T7VtsytEoo)

I have met the same issue. Could you share me the detail solution!? Thank you very much!
