### ISSUE TITLE
Ship pack in receiving section 

### ISSUE THREAD

**Issue by fix24networks** [opensourcepos/opensourcepos#3797]
How can I retain the default value x1 in the 'ship pack' section within the receiving section?

**Comment by fix24networks** [comment]
Please help

**Comment by odiea** [comment]
My only suggestion would be to disable Multiple Packages per Item under General Config.

**Comment by fix24networks** [comment]
Not working

Thank you for reading and looking forward to your response.

Good day and be safe,
Administration Department,
[cid:15eb2f41-511b-4f35-9775-3e2b46f50da8]
Fix 24 Networks (Pvt) Ltd. | Your BPO Partner (PV00270662)
24/7: +94772022281 (https://wa.me/94772022281)
100/1, Ambathalagama, Mihintale,Sri Lanka.
Web: www.fix24.lk<http://www.fix24.lk/> | Email: ***@***.***, ***@***.***
Think before printing, we're not against printing. We're against wasting resources.

________________________________

**Comment by odiea** [comment]
The other option would be to edit item receiving to 1 for each item in the Items form.
