### ISSUE TITLE
asking if some one tested with like 50.000+ items?

### ISSUE THREAD

**Issue by ekardian** [opensourcepos/opensourcepos#3799]
i had a nigthmare last nigth, so..... i was thinking about

**Comment by WebShells** [comment]
Depends on the environment running the software, reached 37k before on Xeon 64GB.

**Comment by ekardian** [comment]
so, more money for more hardware, thx @WebShells

**Comment by ekardian** [comment]
With a rule of tree kkkkk  :) :) very RUSTIC
WITH 64GB i can GIVE UP 37k, so with 8GB how much?

64/8=37/?
?=(8*37)/64 = 4625 ITEMS

nasa here we go

**Comment by WebShells** [comment]
![Oh I See](https://github.com/opensourcepos/opensourcepos/assets/26513147/f324be61-8965-43ce-b054-890016bf3d20)
But no, that's not how many items it can hold... It depends on how many transactions the setup can handle with 50k+ of items.
