### ISSUE TITLE
Request: Daily sales invoice generation in bulk

### ISSUE THREAD

**Issue by Edcarfer** [opensourcepos/opensourcepos#3802]
Request: Option in daily sales to select all sales receipts where invoice is null and generating invoices to 1 client (or no client)

Background:
Hi!

Here in Spain is mandatory for taxes to make an invoice for every sale, usually we use the type of "simplified invoice" as is an invoice with no client data as we are a retail shop and clients dont want to give all their personal data for making an invoice. Also, the simplified invoice has the format of a sales receipt, but it includes the invoice number on it.

Could be great if at the end of the day we are able to select all sales receipts and generate invoices for them in "bulk style".

Thanks for your great work!!

Offtopic: I'm trying to get around the code, but Im mainly in python, maybe I can make a pull request sometime in the near future

**Comment by jekkos** [comment]
Yes that is doable. Create a controller method that accepts json array. Then loop over it and call invoice numbering logic. Add a button in the overview that calls the controller methode.
