### ISSUE TITLE
How to enter item data for newly created attribute?

### ISSUE THREAD

**Issue by meierrom** [opensourcepos/opensourcepos#3803]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: ffe492
- PHP version is: 7.4
- MySQL or MariaDB version is: 10.3.22-MariaDB
- OS and version is: Debian 10
- WebServer is: 2.4.38
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 
Hi folks,

I have added the new attribute "Size" for my store items using Office> Attributes. This new item now shows in my list of "Items". How can I enter data?

When I click the "Update Item" form the new attribute is not showing.

Kind regards,
Roman

**Comment by meierrom** [comment]
Oh, I missed the dropdown menu "Add Attribute" where I can select the attribute to edit.

**Comment by meierrom** [comment]
Hi,

This is a follow-up question.

When adding a new attribute for my store items using Office> Attributes, a field called "Group" is shown with a single dropdown menu entry "[Select]".

What's its purpose?

Kind regards,
Roman

**Comment by kral5151** [comment]
I am wondering too..

**Comment by meierrom** [comment]
Hi folks,

There are different ways:

1) Items> New Item> Add Attribute and fill them
2) Items> Update Item> Add Attribute and fill them
3) Items> CSV Import> Download the template file which contains all
attributes, fill them, and import the file to create or update items

Kind regards,
Roman
