### ISSUE TITLE
Automatic logout after 1 to 30 seconds in ospos

### ISSUE THREAD

**Issue by sislinigeria** [opensourcepos/opensourcepos#3807]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: N/A
- PHP version is: 7.4.33
- MySQL or MariaDB version is: 10.5.20-MariaDB-cll-lve-log
- OS and version is: Linux 2.6.32-954.3.5.lve1.4.89.el6.x86_64
- WebServer is: LiteSpeed
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

##Issue
Good day All, I have OSPOS installed for multiple businesses, and all of them are having the same issue of automatic logout after 1 to 30 seconds.

**My Observation:**

This happens whenever they are using MTN Mobile Network Company (https://www.mtn.ng/) this is the most popular and used Internet provider in my country. The company has the most coverage area making them the preferred provider for individuals and businesses.

I suspect the MTN network provider uses dynamic IP, therefore anytime the Network IP changes, the OSPOS software logs out. And this happens in seconds.

**My Request:**
I believe there is something that can be done on the ospos software to stop the software from logging out anytime a network IP changes. You can effect this on subsequent updates and also **list out a step-by-step process** to resolve this for my clients who are currently facing this challenge.

I hope to hear from someone soon.

**Sixtus Nnamdi**
Email: sixtus.nnamdi@gmail.com

**Comment by WebShells** [comment]
Hello @sislinigeria, glad to hear that OSPOS is covering the business needs in Nigeria region. As for the problem you are facing, allocate line 419 in application/config/config.php:

$config['sess_match_ip'] = TRUE; and set it to false
Doing this will stop forcing logout on ip change.

**Comment by sislinigeria** [comment]
Thank you for this solution. It worked. You guys are doing great with this software.

**Comment by WebShells** [comment]
> Thank you for this solution. It worked. You guys are doing great with this software.

Anytime! Thank you
