### ISSUE TITLE
Object not found!

### ISSUE THREAD

**Issue by AlfiFazulul** [opensourcepos/opensourcepos#3813]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information
- OSPOS version is: 3.3.8
- OSPOS git commit hash is: 
- PHP version is: 7.4.6
- MySQL or MariaDB version is:  10.4.11
- OS and version is: windows
- WebServer is: localhost /apache
- Selected language is: indonesia
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Object not found!
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the [webmaster](mailto:postmaster@localhost).

Error 404
[localhost](http://localhost/)
Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.6

<img width="419" alt="image" src="https://github.com/opensourcepos/opensourcepos/assets/141599623/55493596-5a3e-4251-ad2a-f323fe714e76">

**Comment by AlfiFazulul** [comment]
<img width="419" alt="image" src="https://github.com/opensourcepos/opensourcepos/assets/141599623/f8fb1487-33d1-482c-84f1-8079680552f5">

**Comment by odiea** [comment]
localhost/websitename/public

**Comment by AlfiFazulul** [comment]
> localhost/websitename/public
I've followed your way still the same error, see my screenshot 
![Uploading 266500935-55493596-5a3e-4251-ad2a-f323fe714e76.png…]()

**Comment by AlfiFazulul** [comment]
> localhost/nama situs web/publik

I've followed your way still the same error, see my screenshot 

<img width="419" alt="266500935-55493596-5a3e-4251-ad2a-f323fe714e76" src="https://github.com/opensourcepos/opensourcepos/assets/141599623/d3d888b2-b8f5-47e4-9109-22407f953733">

**Comment by odiea** [comment]
Replace websitename with the name of the website that you are using.

**Comment by AlfiFazulul** [comment]
> Ganti nama website dengan nama website yang 

> Ganti nama website dengan nama website yang Anda gunakan.

masalah selesai, saya mempunyai ide  menjalankannya di hosting ternyata bekerja thanks, saya nyerah dengan local host
