### ISSUE TITLE
Sales & Receivings does not have date pick function

### ISSUE THREAD

**Issue by rana4u** [opensourcepos/opensourcepos#3814]
There is no date picker function in the sales and receiving of this project. How to resolve this?

**Comment by odiea** [comment]
Use the Reports.

**Comment by rana4u** [comment]
I mean the date pick function during sales and receiving

**Comment by odiea** [comment]
Not there. It defaults to the current date and time.

**Comment by odiea** [comment]
If you need to change the date of the Sale or Receiving in Sale go to transactions then update the Sale. Receivings you will need to go into Receivings Report and do the same there.
