### ISSUE TITLE
How to use the debug cookie?

### ISSUE THREAD

**Issue by meierrom** [opensourcepos/opensourcepos#3820]
Hi folks!

I came across file application/views/partial/header.php. There, a cookie with the name debug is used.

Where and how can I set the debug cookie? What is the best practice?

Kind regards,
Roman

**Comment by jekkos** [comment]
I don't remember exactly if the cookie is in use now, but if you append the query string param `?debug=true` then you will load all original javascript source files.

**Comment by meierrom** [comment]
Yeah, I know. This is exactly what I'm trying to avoid. Using the
cookie I don't have to edit the url anytime I change to another page.

2023-09-16 21:06 GMT, jekkos ***@***.***>:
