### ISSUE TITLE
CSV Importing Issue.

### ISSUE THREAD

**Issue by duchuynh** [opensourcepos/opensourcepos#3823]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Receiving Error when attempting to Import this CSV File. Please let me know how you would go about fixing this. I checked the cells to see if there were any stray spaces, and the data seems to be clean.
It just delivers an error when I am attempting to simply import this Excel CSV into OSPOS. This CSV is just one row of the dataset I am attempting to import.
![image](https://github.com/opensourcepos/opensourcepos/assets/1304489/6303c03b-1fa6-4fe8-99cb-7461408e951a)

![image](https://github.com/opensourcepos/opensourcepos/assets/1304489/5b542b6e-f96f-4b16-ba18-4dfc3c4eb975)

**Comment by duchuynh** [comment]
It should be a straight-forward importation, but I am struggling with an import failure on this.

**Comment by jekkos** [comment]
Can you check if the barcode already exists? Try to tick the deleted flag in the items search filter to check if it's there?

**Comment by duchuynh** [comment]
Hi @jekkos the import worked once but I deleted the item from OSPOS to replicate the import. Would this return the error if I try to import it again?

Also having error importing a very large file with 7000+ rows

**Comment by jekkos** [comment]
It's a soft delete of the item, you cannot import it again so that works by design .

**Comment by jekkos** [comment]
I'm not sure but perhaps there is a flag that allows to have duplicate barcodes, you could try to check if that is enabled, if you want the import to work regardless of what barcode exists.

**Comment by duchuynh** [comment]
Hi @jekkos,

Thank you so much for that. That seemed to be the issue for my previous problem. Is there a way to delete the "soft deleted" items so I can import an entire spreadsheet without the spreadsheet importing the same barcode of the deleted items, returning an error?

In addition, if you look at the import template, where is the column that can be used to import quantities of each line item?

**Comment by duchuynh** [comment]
The column seems to be location_store.

Is there a way to update quantity for every sale, or using CSV import to update the quantity? Or do we have to go in and manually update every line item?

**Comment by jekkos** [comment]
You can use SQL to fix this.

**Comment by jekkos** [comment]
I believe that updating quantities should also be possible

**Comment by duchuynh** [comment]
> You can use SQL to fix this.

Hi @jekkos thanks so much for helping with this...

What would be the use case of SQL that will fix my inquiry? Is there no way to hard delete line items?

 I believe SQL is used to query data, but I am just wondering if quantities can be updated with each sale. 

For example, for one of my business items, if a customer were to make a purchase, will it -1 from the quantity column of that item in real-time? Or would we have to keep track of quantities sold per day and update the database EOD?

**Comment by duchuynh** [comment]
Closing this thread, as it was solved with discussions with jekkos
