### ISSUE TITLE
Table refresh not working upon deleting expense entry

### ISSUE THREAD

**Issue by meierrom** [opensourcepos/opensourcepos#3840]
Hi folks,

When I use the form to delete or undelete an expense and then click the submit button, the table does not update and remains unchanged.

When I use the delete button to delete an entry then the table refreshes nicely.

Kind regards,
Roman

**Comment by meierrom** [comment]
Hi folks,

This bug occurs in items and cashups as well.

Kind regards,
Roman

**Comment by jekkos** [comment]
I briefly checked the code and this logic is reused across screens indeed. Is it reproducable on demo?

**Comment by viragni** [comment]
On the demo, I used the form to delete an item, and the table didn't update. When I reload the page, the item is gone.

I was not able to create and expense on the demo to test. The form page just hangs.

**Comment by objecttothis** [comment]
Before reproducing this issue, press F12 which should open up developer tools in your browser.  Go to the console tab, then recreate the issue.  Please report any errors that appear in the console.  Those will give clues as to what is causing the problem.

**Comment by objecttothis** [comment]
On 3.4.0-dev I am able to delete an item using the check box and delete button in the form and it refreshes properly, but produces an error when I highlight the row and press delete. I'm assigning this issue to be fixed in 3.4.0

![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/5b8074d8-2bfb-4b02-a59c-1c3aa6894b0d)

**Comment by odiea** [comment]
In Views /forms another thing to fix. The following code did not previously include the table refresh. Works fine with it included.
```
$('#expenses_edit_form').validate($.extend({
		submitHandler: function(form) {
			$(form).ajaxSubmit({
				success: function(response)
				{
					dialog_support.hide();
					table_support.handle_submit("<?php echo esc($controller_name) ?>", response);
				},
				dataType: 'json'
			});
			table_support.refresh();
		},
```

**Comment by jekkos** [comment]
Tried locally and seems to work. WIll close.
