### ISSUE TITLE
Can't create New Expense on Demo Server

### ISSUE THREAD

**Issue by viragni** [opensourcepos/opensourcepos#3844]
Demo Server:

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

On the demo server, I am not able to create a new expense using the form. I submit the form, and it hangs.

**Comment by odiea** [comment]
You have to create an Expense Category first.
