### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by jabad9999** [opensourcepos/opensourcepos#3848]
hi, is there any body can help me about logout issue. i uploaded ospos files as sub-domain -> ospos.mysite.com and everything working perfectly except logout, when i click logout its goes to home page why??? its suppose to go to login page but not!

**Comment by jekkos** [comment]
which version  of the app?

**Comment by jabad9999** [comment]
© 2010 - 2023 ·opensourcepos.org· 3.3.8 - [ffe492]

**Comment by nibblersghost** [comment]
This happened to me too.

I'm using OsPOS 3.3.8-ffe492.

One thing I've found is that sometimes the browser cache can mess around with navigation while logged in, have you tried clearing the cache? If you're using a chrome based browser: Inspect element->right click on the reload button->select: Empty cache and hard reload--that did it for me, it does happen a few times a week though. Just keep "logging out", it will log you out eventually.

The cache issue has been discussed before, I just can't find the link to it now, sorry. It might have been a reference to something else, but it had to do with the browser cache and having to clear it.

**Comment by jekkos** [comment]
This is fixed in master, perhaps I can release a 3.3.9 as some fixes + translation updates were done in the meantime.

**Comment by jekkos** [comment]
related to  #3578
