### ISSUE TITLE
CI4: .htaccess and POST   -  GET

### ISSUE THREAD

**Issue by DEV-byoos** [opensourcepos/opensourcepos#3849]
added my config
OSPOS version is: upgrade-ci4 based on OSPOS 4.0.0-dev  CI 4.4.1
OSPOS git commit hash is: 5ef2608
PHP version is: php8.2
MySQL or MariaDB version is: 10.11
OS and version is: GNU/LINUX debian 12.1
WebServer is: apache 2.4
Selected language is: en-US
(If applicable) Docker installation: no use
(If applicable) Installation package for the :LINUX/ DeBIAN 12.1
Good evening,
I carefully read the #steveIrland thread
  CI4: Form is being redirected from POST (which is how it is generated) to a GET #3721

and I must admit that I didn't understand everything...
indeed some methods like getIndex() work if the URL ends with "index" but for other cases it doesn't work???
Error in source links: Error: request failed with status 404
Resource URL: http://localhost/ci4_opensourceospos_latest/public/resources/js/html2canvas-e1d3a8d7cd.js
Source link URL: html2canvas.js.map

XHRGET
http://localhost/ci4_opensourceospos_latest/public/items/checkNumeric?cost_price=0.00
[HTTP/1.1 404 Not Found 18ms]

XHRGET
http://localhost/ci4_opensourceospos_latest/public/items/checkNumeric?unit_price=0.00
[HTTP/1.1 404 Not Found 26ms]

XHRGET
http://localhost/ci4_opensourceospos_latest/public/items/checkNumeric?quantity_1=0
[HTTP/1.1 404 Not Found 18ms]

XHRGET
http://localhost/ci4_opensourceospos_latest/public/items/checkNumeric?receiving_quantity=1
[HTTP/1.1 404 Not Found 16ms]

XHRGET
http://localhost/ci4_opensourceospos_latest/public/items/checkNumeric?reorder_level=1
I don't see where the problem comes from....
Thanks for your help

**Comment by DEV-byoos** [comment]
Good evening devs
myConfig
OSPOS version is: upgrade-ci4 based on OSPOS 4.0.0-dev  CI 4.4.3
OSPOS git commit hash is: 5ef2608
PHP version is: php8.2
MySQL or MariaDB version is: 10.11
OS and version is: GNU/LINUX debian 12.1
WebServer is: apache 2.4
Selected language is: en-US
(If applicable) Docker installation: no use
(If applicable) Installation package for the :LINUX/ DeBIAN 12.1

********** START debug *************
[ci4_upgrade_osposv4-0-0-dev_php8-2.txt](https://github.com/opensourcepos/opensourcepos/files/13219641/ci4_upgrade_osposv4-0-0-dev_php8-2.txt)


Finally I solved the PB with checkNumeric... following the advice of #steveIreland, OK solved.
I was then able to work on the "company_logo" which was only displayed in the config when I manually copied it to the /root/public/.... directory.
I try to change the logo but nothing works.
I started the modifications: PS there are some updates on the Config.php controller methods postSaveInfo AND upload_logo() AND postRemove_logo

**Comment by DEV-byoos** [comment]
code fixes to be updated in order to come to a stable version of ci4-upgrade dear to our friend Gabriel. 
[Uploading ci4_upgrade_osposv4-0-0-dev_php8-2.zip…]()

**Comment by objecttothis** [comment]
@DEV-byoos please check out a branch from ci4-upgrade and then submit a pull request of that branch to merge into ci4-upgrade.  I can't compare this against the current code, so I don't know what has changed and I would hate to have any of your hard work not get implemented.

**Comment by jekkos** [comment]
@DEV-byoos you can even create a pull request by editing the source directly in the github browser.
Please give that a try. It should be very straightforward.
