### ISSUE TITLE
CI4: Views/attributes/item.php not loading values in dropdown nor current attributes in New/Edit Item form view

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3855]
View > items > form is the popup modal that allows creation of new items and editing existing items.

Starting on line 83 the getAttributes() function in the Items controller is called
```
		<div id="attributes">
			<script type="text/javascript">
				$('#attributes').load('<?php echo "items/attributes/$item_info->item_id" ?>');
			</script>
		</div>
``` 

The problem is that `$this->request->getGet()` returns null
```
	public function getAttributes(int $item_id = NEW_ENTRY): void
	{
		$data['item_id'] = $item_id;

		if($this->request->getGet('definition_ids') != null)
		{
			$definition_ids = json_decode($this->request->getGet('definition_ids'), TRUE);
			$data['definition_values'] = $this->attribute->get_attributes_by_item($item_id) + $this->attribute->get_values_by_definitions($definition_ids);
			$data['definition_names'] = $this->attribute->get_definition_names();
		}
```

getAttributes() then calls the views/attributes/item.php view to display the dropdown and the existing attributes, but since those are all empty, a blank dropdown and no attributes are displayed.

Expected behavior:
- definition_ids in the get request would not be null
- on new items a complete dropdown of the available attributes would be output in the view
- on existing items a dropdown with undefined attributes would be displayed along with existing attributes.

Next Steps:
We need to research why definition_ids in the request is null. It's possible that the problem is in the form view or sooner, so they are never getting populated.

**Comment by jekkos** [comment]
I wonder how it worked before, were the definition ids coming from the frontend? Perhaps this was just the contents of the dropdown list sent back (as you need to add an attribute to an item in a first step).

Also I wonder if all of this just came in through query string parameter, encoded in json? I would need to check the master version to understand.

**Comment by odiea** [comment]
The following function also creates errors. It does not like the  & symbol.
```
public function get_definitions_by_flags(int $definition_flags): array
	{
		$builder = $this->db->table('attribute_definitions');
		$builder->where('definition_flags &', $definition_flags);
		$builder->where('deleted', 0);
		$builder->where('definition_type <>', GROUP);
		$builder->orderBy('definition_id');
		$results = $builder->get()->getResultArray();

		return $this->to_array($results, 'definition_id', 'definition_name');
	}
```

**Comment by jekkos** [comment]
Thanks for pointing that out @odiea . The `&=  was used as a bit field operator. Maybe the query builder does not support this notation anymore.

**Comment by objecttothis** [comment]
@jekkos I think we are talking about this line `$builder->where('definition_flags &', $definition_flags);`. 
I think that means we want it to produce `WHERE 'ospos_definition_flags' &= [definition_flags]` where [definition_flags] is the value passed into the function. In PHP the function is defining this as an int, but in the database it's a tinyint(1), so I think this is part of why that was in there.  I'll try to debug this tomorrow to see what SQL is actually being produced.

**Comment by objecttothis** [comment]
According to the documentation (https://codeigniter.com/user_guide/database/query_builder.html#custom-key-value-method) we may need to include the whole operator `&=` rather than just part of it.

**Comment by objecttothis** [comment]
`$builder->where('definition_flags &', $definition_flags);` produces `WHERE `definition_flags` `&` = 1`

Adding the `escape` parameter `$builder->where('definition_flags &', $definition_flags, false);` gets rid of the escaping issue, but it still fails. `WHERE definition_flags & = 1`

After doing a bit of research, this is because `&=` is valid SQL, but not valid MySQL. Changing the code to `$builder->where(new RawSql("definition_flags & $definition_flags"));` will produce `WHERE definition_flags & 1` so that is what we may need to do, but doing so unfortunately doesn't resolve this issue.

**Comment by objecttothis** [comment]
Something to be noted about `RawSql()`, which is new as of CI4.2.0, is that their documentation gives strong warning to escape values and protect identifiers manually. How should we go about doing this? I'm more gun-shy about using `esc()` since we needed to rip out a bunch of them for having messed up the data.

**Comment by objecttothis** [comment]
@SteveIreland in the Items controller you reworked the beginning of the `getAttributes()` function from this
```
		$data['item_id'] = $item_id;
		$definition_ids = json_decode($this->request->getPost('definition_ids'), TRUE);
		$data['definition_values'] = $this->attribute->get_attributes_by_item($item_id) + $this->attribute->get_values_by_definitions($definition_ids);
		$data['definition_names'] = $this->attribute->get_definition_names();
```

to this
```
		if($this->request->getGet('definition_ids') != null)
		{
			$definition_ids = json_decode($this->request->getGet('definition_ids'), TRUE);
			$data['definition_values'] = $this->attribute->get_attributes_by_item($item_id) + $this->attribute->get_values_by_definitions($definition_ids);
			$data['definition_names'] = $this->attribute->get_definition_names();
		}
		else
		{
			$data['definition_values'] = [];
			$data['definition_names'] = [];
		}
```

`getAttributes()` is called from views\items\form.php
```
		<div id="attributes">
			<script type="text/javascript">
				$('#attributes').load('<?php echo "items/attributes/$item_info->item_id" ?>');
			</script>
		</div>
```

and from views\attributes\items.php
```
		var refresh = function() {
			var definition_id = $("#definition_name option:selected").val();
			var attribute_values = definition_values();
			attribute_values[definition_id] = '';
			$('#attributes').load('<?= "items/attributes/$item_id" ?>', {
				'definition_ids': JSON.stringify(attribute_values)
			}, enable_delete);
		};
```

The first does not send definition_ids and breaks it so that no attribute values are sent to the views/attributes/item.php view. Is there any reason why I can't change your code to a hybrid of the two?
```
		$data['item_id'] = $item_id;
		$definition_ids = json_decode($this->request->getGet('definition_ids'), TRUE);
		$data['definition_values'] = $this->attribute->get_attributes_by_item($item_id) + $this->attribute->get_values_by_definitions($definition_ids);
		$data['definition_names'] = $this->attribute->get_definition_names();
```

**Comment by objecttothis** [comment]
After further testing, I think the reason you added the if statement is because passing null in the first parameter of json_decode() is deprecated.  I think this can be resolved by using the null coalescing operator `??`, so 
`$definition_ids = json_decode($this->request->getGet('definition_ids') ?? '', TRUE);`

**Comment by objecttothis** [comment]
That resolved the problem and I fixed a few other issues.  Now onto the next one. updating the attribute_links is failing.

**Comment by jekkos** [comment]
great work @objecttothis

**Comment by objecttothis** [comment]
I've been troubleshooting that error most of the day today. I posted on the code igniter forum. There are problems with the attributes save functions. I suspect that the stack trace is masking another problem.

**Comment by objecttothis** [comment]
Here is the forum post. I am working on another project today so if anyone has any ideas, feel free to offer them. https://forum.codeigniter.com/showthread.php?tid=88789

**Comment by odiea** [comment]
I found the issue. In items form I commented out rules and have not had this problem. It appears that checkNumeric is creating this problem.

**Comment by objecttothis** [comment]
> I found the issue. In items form I commented out rules and have not had this problem. It appears that checkNumeric is creating this problem.

Validation rules?  Can you post what code you had to comment out?

**Comment by objecttothis** [comment]
OK, I'll play around with checkNumeric. Can you post specifically what you commented out?

**Comment by odiea** [comment]
App/views/items/form starting at line 576 on my version. Checkitemnumber gave me no issues.
```
/*rules:
			{
				name: 'required',
				category: 'required',
				item_number:
				{
					required: false,
					remote:
					{
						url: "<?php echo esc("$controller_name/checkItemNumber") ?>",
						type: 'POST',
						data: {
							'item_id' : "<?php echo $item_info->item_id ?>"
							// item_number should be passed into the function by default
						}
					}
				},
				cost_price:
				{
					required: true,
					remote: "<?php echo esc("$controller_name/checkNumeric") ?>"
				},
				unit_price:
				{
					required: true,
					remote: "<?php echo esc("$controller_name/checkNumeric") ?>"
				},
				<?php
				foreach($stock_locations as $key=>$location_detail)
				{
				?>
				<?php echo 'quantity_' . $key ?>:
					{
						required: true,
						remote: "<?php echo esc("$controller_name/checkNumeric") ?>"
					},
				<?php
				}
				?>
				receiving_quantity:
				{
					required: true,
					remote: "<?php echo esc("$controller_name/checkNumeric") ?>"
				},
				reorder_level:
				{
					required: true,
					remote: "<?php echo esc("$controller_name/checkNumeric") ?>"
				},
				tax_percent:
				{
					required: false,
					remote: "<?php echo esc("$controller_name/checkNumeric") ?>"
				}
			},*/
```

**Comment by objecttothis** [comment]
Hmmm. I commented out the rules section, but had the same errors in the log `Error connecting to the database: ErrorException: Trying to access array offset on value of type bool`.  I get those errors when I edit an item and change the value of an attribute.  Let's make sure that we are both running the same code though.  I can't remember, do you know how to pull down the latest version of a branch using github desktop or another tool?  If you need, I can show you how to build a project to make it easier.

**Comment by odiea** [comment]
Yes I noticed that this issue was still there but it was not preventing the model from doing the update. I use github to download the current versions and work from that.
