### ISSUE TITLE
CI4: branch Form Datepicker issues.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3864]
The following issue is showing on most forms that have a Date selector.
![2023-11-11 14_40_10-Odies Test _ Powered by OSPOS 3 4 0-dev](https://github.com/opensourcepos/opensourcepos/assets/10962177/f1d7c7ce-cfee-4257-87ad-a548d364b88c)

**Comment by jekkos** [comment]
Thanks for logging this @odiea

**Comment by odiea** [comment]
I had to change line 28 to <?php echo isset($config) ? $config : '{}' ?>); and this is now showing current date but the time is not correct.. When I click on Today it now shows the current time. How do I set the picker default as today?

**Comment by objecttothis** [comment]
@odiea when I change `<?= '{}' ?>` to `	}, <?php echo isset($config) ? $config : '{}' ?>);` I get 'array to string conversion error'.  I see that this is the way the code is in the current master, so I'm a little stumped on why that is working.  The issues with datepicker go even further than  you reported. in the current master we are calling `$this->lang->load('calendar');` at the top of the view, which I assume is giving us access to all those language lines.  This calendar file does not appear in any of the OSPOS code, so it must have been built into CI3. Our current problem with the localization is that it's not finding the array, so it's just giving us the keys that we requested.
![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/0e8ab741-5eb3-4e6b-9d88-dc5debe746f4)

**Comment by odiea** [comment]
I got it working by creating a Cal language. Would you like me to submit a pull request on this? Currently it is only in the en_US lang. Yes I Fixed the November issue.
![2023-12-16 06_22_42-Odies Test _ Powered by OSPOS 3 4 0-dev](https://github.com/opensourcepos/opensourcepos/assets/10962177/26896bce-c222-48f9-a974-4a2924b14374)

**Comment by objecttothis** [comment]
If we cannot find a solution that allows us to use the same built-in translations that CI3 versions were using then we will likely need to create a Cal language and store the translations ourselves. I will be back in the office on January 8th, but if someone wants to investigate why what we were doing in 3.3.9 and prior was working and see if there is a solution in CI4 that uses that, then we will have our answer.

**Comment by odiea** [comment]
It was built into the CI3 Framework using the system helper and loader library. I found  where it was located under \ vendor \codeigniter\framework\system\language\english.

**Comment by objecttothis** [comment]
I suppose if they didn't bring this over to CI4 then we need to treat it like any other language file. @jekkos do you have thoughts on this? If we create a Calendar language file the only downside is that we then need to get all those translations. I wonder if intl has any build in translations for things like calendar names that are standardized.

**Comment by jekkos** [comment]
can we maybe just copy the ci3 file in our branch and then maintain it? all the translations should be there, we just need to convert them.

**Comment by jekkos** [comment]
the only annoyance is that the folder structure for language names in ci3 is different so the files need to be moved one by one. Or I steal the mapping table from the code and move them using that one

**Comment by jekkos** [comment]
I quickly built this mapping table in zsh from the code

```
typeset -A hash
hash[arabic]="ar-EG"
hash[arabic]="ar-LB"
hash[azerbaijani]="az-AZ"
hash[bulgarian]="bg"
hash[bosnian]="bs-BA"
hash[czech]="cs"
hash[danish]="da"
hash[german]="de"
hash[german]="de-CH"
hash[greek]="el"
hash[english]="en-GB"
hash[english]="en-US"
hash[spanish]="es"
hash[spanish]="es-MX"
hash[french]="fr"
hash[persian]="fa-IR"
hash[english]="he"
hash[croatian]="hr-HR"
hash[hungarian]="hu-HU"
hash[armenian]="hy"
hash[indonesian]="id"
hash[italian]="it"
hash[khmer]="km"
hash[lao]="lo"
hash[malay]="ml"
hash[norwegian]="nb"
hash[dutch]="nl"
hash[dutch]="nl-BE"
hash[polish]="pl"
hash[portuguese]="pt-BR"
hash[romanian]="ro"
hash[russian]="ru"
hash[swedish]="sv"
hash[tamil]="ta"
hash[thai]="th"
hash[talong]="tl-PH"
hash[turkish]="tr"
hash[ukrainian]="uk-UA"
hash[urdu]="ur-PK"
hash[vietnamese]="vi"
hash[simplified-chinese]="zh-Hans"
hash[traditional-chinese]="zh-Hant"
```

it can then be used in a script that copies the file to the correct location

**Comment by jekkos** [comment]
Pushed the calendar language files now in ci4-branch.

**Comment by objecttothis** [comment]
> Pushed the calendar language files now in ci4-branch. I will need to reconfigure weblate so translators can also work on these files.

Thanks for doing that.  Did you create a PR for those files already?  I'm not seeing them in `/app/Language/xx-YY/`

**Comment by jekkos** [comment]
https://github.com/opensourcepos/opensourcepos/commit/6843443a1f89cae203334a32d1d841038cb11b85

**Comment by jekkos** [comment]
I don't see the english file in there indeed. It's also not in the t[ranslation repository](https://github.com/bcit-ci/codeigniter3-translations/tree/develop/language).

**Comment by jekkos** [comment]
Added the english files now as well.

**Comment by objecttothis** [comment]
I see them now.  The only thing I see that we could change is that in the other language files we dropped the prefixes in the keys because they were redundant. In this case, it would mean dropping `cal_`.  Do you think we can do that here too for consistency? The way it is currently, the call will be `lang('Calendar.cal_su')`, but dropping the prefix would allow us to go with `lang('Calendar.su')`

**Comment by jekkos** [comment]
Alright I think the autodeploy now also works again, I checked dev server and see that we have Cal.su in use, so even Calendar is abbreviated? Maybe we should change that in code as well then?

**Comment by jekkos** [comment]
Pushed a change now that strips the prefix

**Comment by objecttothis** [comment]
> Alright I think the autodeploy now also works again, I checked dev server and see that we have Cal.su in use, so even Calendar is abbreviated? Maybe we should change that in code as well then?

We can do one of two things
1- Change the code to read `Calendar.su`
2- Change the name of the language file to `Cal`

option 1 is in line with the rest of the language files which are not abbreviated.  Option 2 is shorter to write in the code.  I prefer option 1 so that it's consistent with the rest of the language files.  What do you think?

**Comment by jekkos** [comment]
I would go for the first option then. Will do the change later today.

**Comment by odiea** [comment]
@objecttothis I am now testing with php 8 and can see this error. So i changed the following from ```<?php echo isset($config) ? $config : '{}' ?>); to <?php echo isset($config)  ?>); ```and now I am not getting this error.

**Comment by objecttothis** [comment]
> @objecttothis I am now testing with php 8 and can see this error. So i changed the following from `<?php echo isset($config) ? $config : '{}' ?>); to <?php echo isset($config) ?>); `and now I am not getting this error.

OK, I made a commit for this.

**Comment by objecttothis** [comment]
@odiea I just pushed some changes to fix the datepicker.  One change that I made was to remove `config[timeformat]` from the pickerconfig.  I'm not sure if there are cases where we want the time in the datepicker though, so this might not be what we want.  The change was because in OSPOS <= 3.3.9 attribute datepicker was just selecting the date even with timeformat in there, but in the current codebase it's having you walk through picking hour, minute and second. I'm not sure why though, because that set of code in datepicker_locale.php hasn't changed.

**Comment by jekkos** [comment]
I believe in sale or receiving edit we allow to pick a time as well

**Comment by jekkos** [comment]
thanks for going the extra mile here

**Comment by jekkos** [comment]
date picker for attributes seems to work fine in dev version, will close.
