### ISSUE TITLE
CI4 branch items checkNumeric issue

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3872]
In Items form there is checkNumeric. I found that checkNumeric is located in the secure controller. To fix this issue I had to change the line from ```remote: "<?= esc("$controller_name/checkNumeric") ?>" to remote: "<?php echo site_url($controller_name . '/checkNumeric')?>"``` and now I have no issues with check numeric when adding or updating an Item form.

**Comment by objecttothis** [comment]
Some of the calls to checkNumeric are using esc and some are not using it.  Namely calls in views\items\form.php are using esc. What was the issue coming up with checkNumeric? Right now the only issue I'm experiencing with saving in the items/form.php is saving attributes.

**Comment by jekkos** [comment]
The validation also passes even if you do not fill any number, so this should be double checked

**Comment by jekkos** [comment]
Tested locally and works now.
