### ISSUE TITLE
CI4: branch is no longer showing the toast notifications.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3873]
Something else to learn is how to show toast notifications. But the tables are showing that fine green bar.

**Comment by odiea** [comment]
app/controller/config lines 413  'notify_horizontal_position' => $this->request->getPost('notify_horizontal_position'),
			414 'notify_vertical_position' => $this->request->getPost('notify_vertical_position'), had filter_sanitized and I removed that. Apparently the FILTER_SANITIZE for numeric was stripping out the text and placeing empty variables into the app_config table. Now toast notifications are showing.

**Comment by jekkos** [comment]
Seems to work now on dev, will close.
