### ISSUE TITLE
Ci4 branch Sale_lib issue

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3874]
In Sale_lib the following has been commented out. $this->sale = model('Sale');	//TODO: This is causing an infinite loop because the constructor calls the sale library . To eliminate this problem I went thru the different functions containing  $this->sale  and pasted 
$this->sale = model('Sale'); into the offending function. I am no longer getting the loop and Sale_lib appears to be working properly.

**Comment by jekkos** [comment]
Seems to be resolved already, will close.
