### ISSUE TITLE
Fix docker-compose dev mount permissions

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#3875]
When setting up a dev environment using compose, the mounted files have the permissions of the logged in user on the host filesystem. These do not match with the permissions for files that are created in a container. This leads to annoying situations in which files that were built by a tool inside the container are then owned by root on the host.

Solution: Create the host user inside the docker container and run the php / apache process as this user. This way there should be no more permission issues when a container is stopped.

**Comment by jekkos** [comment]
Also add back the base layer that used to be in the Dockerfile, as currently there are no more debian updates pulled in as the layer was fixed at some point as a workaround to a travis build issue

**Comment by objecttothis** [comment]
@jekkos should this still go in 3.4.0 or do we move it to after 3.4.0?

**Comment by jekkos** [comment]
Let's keep it in 3.4, I'll take care of this

**Comment by jekkos** [comment]
This works now locally. I had one issue while logging in which is that the backup file could not be created. After I added the folder things were fine though. Not sure if the code also takes care of creating the folder when it's not there @owlbrudder

**Comment by jekkos** [comment]
Also added some big folders in .dockerignore so they are not copied into the container anymore, the image was at 1.7GB size already locally. I guess that is because my git history folder has grown a bit over the years. By adding some folder the size was reduced to 700MB. node_modules is also something we do not need at runtime. So this does not need to be copied either.
