### ISSUE TITLE
CI4: Branch Receivings validation issue.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3878]
The following code in Controller/Receivings postEditItem returns this issue if any number is changed. Currently I have it edited out to complete a Receivings.

                //$this->validator->setRule('price', 'lang:items_price', 'required|numeric');
		//$this->validator->setRule('quantity', 'lang:items_quantity', 'required|numeric');		
		//$this->validator->setRule('discount', 'lang:items_discount', 'required|numeric');

CRITICAL - 2023-11-21 12:57:17 --> Call to a member function setRule() on null
in APPPATH\Controllers\Receivings.php on line 176.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Receivings->postEditItem('1')
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Receivings))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

I replaced it with the following code and it appears to work.
$validation_rule = [
			'price' => 'trim|required|numeric',
			'quantity' => 'trim|required|numeric',
			'discount' => 'trim|required|numeric',
		];
And changed the following and removed the ! mark.
if ($this->validate($validation_rule))

**Comment by odiea** [comment]
Works in the version I am using.

**Comment by jekkos** [comment]
It's on dev server, could you check if it works there as well, then I'll merge. Thanks!

**Comment by jekkos** [comment]
when I complete receivings I get this message ` Controller or its method is not found: \App\Controllers\Receivings::postComplete `

**Comment by jekkos** [comment]
I guess the function name needs to be renamed, there are quite some others in the controller, I think it's best that I test it through locally.
