### ISSUE TITLE
CI$ Branch Expenses Date issue

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3879]
After trying to save an Expense the following error occurs.

CRITICAL - 2023-11-22 13:42:48 --> Call to a member function format() on bool
in APPPATH\Controllers\Expenses.php on line 144.
 1 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Expenses->postSave(-1)
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Expenses))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

Also In app/Models/Cashup Line 100 the following code prevents the Table from loading properly. Only the Dates will be displayed.

if(!$count_only)
		{
			$builder->select('
			cash_up.cashup_id,
			');
		}

**Comment by jekkos** [comment]
Ah so it was not really a bug then? Thanks for the update
