### ISSUE TITLE
CI4: nominatim issue . People form basic info.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3885]
When entering a zip or country code the following error was returned.
message
: 
"Structured query parameters(amenity, street, city, county, state, postalcode, country) cannot be used together with 'q' parameter."

**Comment by objecttothis** [comment]
What country code are you entering? I take it you are referring to /public/config under the Localization tab?

**Comment by odiea** [comment]
Customer, Employee, Supplier  application/views/people/form_basic_info.

**Comment by jekkos** [comment]
Also got this error ```Content-Security-Policy: The page’s settings blocked the loading of a resource at https://nominatim.openstreetmap.org/search?q=2200&format=json&limit=5&addressdetails=1&countrycodes=us&accept-language=en-US&city=2200 (“connect-src”).```

**Comment by jekkos** [comment]
but at least it seems that @odiea browser is able to make the API call and perhaps something has changed in nominatim itself. Quite impressive that it kept working all these years btw

**Comment by jekkos** [comment]
Indeed according to their docs, either you use unstructured query, or we search using fields only

**Comment by jekkos** [comment]
Fixed now on dev server. I might want to backport this one in case we also tackle #3913
