### ISSUE TITLE
CI4 Branch commit issue?

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3887]
Yes I checked my permissions. This showed up today after merging with ci4-branch. Any Ideas?

![2023-12-04 13_33_04-Odies Test _ Powered by OSPOS 3 4 0-dev](https://github.com/opensourcepos/opensourcepos/assets/10962177/0fa74579-ba10-403c-8127-41699fe32251)

**Comment by objecttothis** [comment]
Yeah, I think I broke that.  I need to troubleshoot it.
