### ISSUE TITLE
CI4: Export of Customer Data to JSON format does not respect numberformat local

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3888]
numberformat
thousands separator: period `.`
decimal separator: comma `,`

In the customer view, if you click the export icon and choose JSON, the resulting JSON for the amount spent strips the comma (decimal separator) and treats the period (thousands separator) like a decimal.

The functionality is implemented by Bootstrap Table https://bootstrap-table.com/versions/1.15.5/.  I wonder if a newer version is needed?

**Comment by objecttothis** [comment]
I updated the bootstrap-table dependency in npm to 1.22.1 (latest) but no immediate effect.  I probably need to log the data that gets sent to it to see if it's the json-encoded data that is a problem.  I suspect it might be.

**Comment by jekkos** [comment]
@objecttothis if the export is JSON then the format might depend on whether the field is a number or a string. If the datatype is the first, then no locale formatting will be applied.

**Comment by jekkos** [comment]
I have tested this one and in my case, this field is exported in the configured locale. It's a string so it should literally be a 1-to-1 coy of what is in the table

**Comment by objecttothis** [comment]
> I have tested this one and in my case, this field is exported in the configured locale. It's a string so it should literally be a 1-to-1 coy of what is in the table

Did you test with a locale that uses a comma as a decimal separator such as az-az? It doesn't happen when period decimal separators are used. I haven't tested in a while. Maybe it's fixed now.

**Comment by jekkos** [comment]
This is a json export for nl_BE which uses comma as decimal separator
![image](https://github.com/user-attachments/assets/1b11dca3-890b-4013-8a58-980a11592e45)
