### ISSUE TITLE
CI4: table load elipsis repeated

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3891]
Currently the language line for the table loading message includes an elipsis `...`.  Bootstrap also has an animated elipsis (see below), so they are redundant.
![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/f80e3761-ae80-482b-81ae-e3a26861d999)

There are two possible ways to resolve this:
1- Remove the elipsis `...` from all weblate strings in all languages AND format the bootstrap animation to match the font size of the loading message.
2- Disable the bootstrap animation and keep the elipsis in the language lines in the various languages.

I am in favor of option 1, but option 2 is slightly less work.

**Comment by jekkos** [comment]
Or option 3, we remove the loading string and keep the animation only?

**Comment by objecttothis** [comment]
> Or option 3, we remove the loading string and keep the animation only? 

That is a pretty good option, actually.
- It's clean without losing meaning
- One less language string to maintain
