### ISSUE TITLE
CI4: Stats data need top margin in customer form view

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3892]
In the stats tab of the form, the data needs to be centered vertically and horizontally in the modal with a minimum top margin value that matches other modals.

![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/eda09aa7-76a4-4e47-a54f-4d40a14c4b42)

**Comment by odiea** [comment]
Is this what you are hoping to see?
![2024-03-08 05_50_44-Open Source Point of Sale _ Powered by OSPOS 3 4 0-dev](https://github.com/opensourcepos/opensourcepos/assets/10962177/8f1379f7-d10f-4774-aeb6-3c5013cadc82)

**Comment by objecttothis** [comment]
That does look better, but this is what I was referring to directly. See how the block is left-justified?  The block should be centered with the left column right justified like it is now.  Basically shift the whole thing to the middle.
![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/4e9c8847-02ce-418b-8557-cdf6d5ee5413)

**Comment by odiea** [comment]
I thought that most of the forms are left justified. Here is setting the columns to 4
![2024-03-08 14_02_25-Open Source Point of Sale _ Powered by OSPOS 3 4 0-dev](https://github.com/opensourcepos/opensourcepos/assets/10962177/a47d8df0-ee9b-468f-b73d-e1ebba84a5f9)

**Comment by odiea** [comment]
Here is a different col setting.

![2024-03-08 14_17_02-Open Source Point of Sale _ Powered by OSPOS 3 4 0-dev](https://github.com/opensourcepos/opensourcepos/assets/10962177/c450739c-1955-42b0-a0ac-19ed9b880984)

**Comment by objecttothis** [comment]
> I thought that most of the forms are left justified.

Maybe. It just looked really funny to me all the way to the left.

**Comment by objecttothis** [comment]
> Here is a different col setting and this is what I changed.
> 
> ```
> if(!empty($stats))
> 		{
> 		?>
> 			<br>
> 			<div class="tab-pane" id="customer_stats_info">
> 				<fieldset>
> 					<div class="form-group form-group-sm">
> 						<?= form_label(lang('Customers.total'), 'total', ['class' => 'control-label col-xs-5']) ?>
> 						<div class="col-xs-4">
> ```

This looks fantastic.  Did you know you can go to the ci4-update branch and edit it right in github? It will allow you to create a pull request to merge into the ci4-update branch. It's not a huge risk if you mess it up because we can always roll the commit back or push another commit to fix something if need be. @owlbrudder, @jekkos or myself can do it too, but it saves us a little time if you're willing to give it a shot.

**Comment by odiea** [comment]
I gave it a shot then merged to my versions with no issues.
