### ISSUE TITLE
Move chat from Matrix (formerly gitter)

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3898]
Gitter used to be used for general discussions and dev conversations. Gitter shifted to the Matrix platform which is client agnostic (though Element is the most common).  The problem is that how this all works is convoluted and most people did not shift over to this.  I'm proposing that we move to using another platform for these conversations.  Here are the options as I understand them (there may be others):

- Github Discussions
Pros: People don't need to leave the platform and login to another service.
Cons: There are no Private rooms, therefore conversations surrounding direction or otherwise non-public conversation about the work cannot happen there. Github discussions is a post/thread format rather than live chat format. It isn't the end of the world, but can sometimes make conversations about multiple topics more difficult.

- Slack
Pros: Similar chat functionality. Conducive to room format rather than post/thread format.
Cons: External platform that people need to login to.

I think I prefer Github Discussions even though I use Slack all the time for other projects. If the goal is to increase engagement, IMO Github discussions is the way to go.  We can possibly work around the issue of not having private discussions by enabling discussions for the opensourcepos organization and assigning it to a dummy repository, so they don't appear in opensourcepos... or if our account allows us to make that dummy repo private, then we can limit visibility to the repo, therefore those conversations.

@jekkos what do you think?

**Comment by jekkos** [comment]
The link in the README.MD was broken so maybe visitors did not find their way to the chatroom.

The nice thing about it is that the chat can still be accessed by a browser, so no apps needed. users should just be able to login with their github account. Let's see if the link refresh brings in more users to the chatrooms. It's not in master yet but it will be after we merge.

**Comment by jekkos** [comment]
So conclusion, let's stick to gitter for now?
