### ISSUE TITLE
CI4: Generate Barcodes Errors

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3899]
It doesn't like $this->request.  It's probably an easy fix. Once resolved we need to make sure the barcodes are being generated properly and fix any issues along the way.
![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/b71df34a-39a2-43f0-8786-b9ce8ffa40e7)

**Comment by odiea** [comment]
Why is this even in there. It is not in the original barcode sheet?  It works without it.
lang="<?= $this->request->getLocale() ?>

**Comment by objecttothis** [comment]
Does the language line properly generate without it?  If so, then we can just remove it.

**Comment by odiea** [comment]
If you are concerned about the lang line I replaced this with the one from the header. This does not show an error. It appears the only lang file in this is on the title which I have never seen shown. Yes it works just fine without it.

use Config\Services;

$request = Services::request();
```
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?= $request->getLocale() ?>">
```
![2023-12-20 05_24_03-Generate Barcodes](https://github.com/opensourcepos/opensourcepos/assets/10962177/ba2ba74b-b5bc-44b0-9636-45b2d1e22cb9)

**Comment by objecttothis** [comment]
If the lang line in the title tag works OK without `lang="<?= $request->getLocale() ?>` then I agree that we should remove it from the code. It may have been added in to appease the IDE linters.

**Comment by objecttothis** [comment]
I've pushed several changes which fix some problems, but I believe there are more problems to resolve.  For example the config for "Input Formats" is wrong.
![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/2451f05a-f10a-4693-8c96-975107df2cc1)

**Comment by odiea** [comment]
Here is the code I used. Hope it helps 
```
<div class="form-group form-group-sm">
				<?php echo form_label(lang('Config.barcode_formats'), 'barcode_formats', ['class' => 'control-label col-xs-2']) ?>
				<div class='col-xs-4'>
					<?php
					$barcode_formats = json_decode(config('OSPOS')->settings['barcode_formats']);
					echo form_dropdown ([
						'name' => 'barcode_formats[]',
						'id' => 'barcode_formats',
						'options' => !empty($barcode_formats) ? esc(array_combine($barcode_formats, $barcode_formats), 'attr') : [],
						'multiple' => 'multiple',
						'data-role' => 'tagsinput']) ?>
				</div>
			</div>```

**Comment by objecttothis** [comment]
> Here is the code I used. Hope it helps 
> ```
> <div class="form-group form-group-sm">
> 				<?php echo form_label(lang('Config.barcode_formats'), 'barcode_formats', ['class' => 'control-label col-xs-2']) ?>
> 				<div class='col-xs-4'>
> 					<?php
> 					$barcode_formats = json_decode(config('OSPOS')->settings['barcode_formats']);
> 					echo form_dropdown ([
> 						'name' => 'barcode_formats[]',
> 						'id' => 'barcode_formats',
> 						'options' => !empty($barcode_formats) ? esc(array_combine($barcode_formats, $barcode_formats), 'attr') : [],
> 						'multiple' => 'multiple',
> 						'data-role' => 'tagsinput']) ?>
> 				</div>
> 			</div>```

Epic. Thanks. I'm hoping that's what is causing the null reference exception when the line 2 is the item id and the barcode type is EAN-13.

**Comment by objecttothis** [comment]
@odiea your code change resolves the issue with the configuration.  Thank you for posting that. Our bug with getting an `undefined array key ""` error when EAN-13 is the barcode type, barcode is an ISBN-13 number, barcode content is set to Item Id/Name and Barcode Layout set to Item Name/Barcode/Retail Price  is still present.
![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/f1474fb5-b426-4123-827e-9b8b350389d9)

When I check "Generate if Empty" the problem goes away. @odiea do you get the same behavior with the settings I listed?

**Comment by odiea** [comment]
What's a good ean-13 number to try. No i have not tested this yet.

**Comment by objecttothis** [comment]
I'm using 9780230766518 for the value of item_number (the barcode) on an item that isn't generating but throwing the exception. The thing I find interesting is that the barcode content is set to Item Id/Name, so it shouldn't matter what the Barcode value is.

**Comment by objecttothis** [comment]
Here's the exact error and stack trace
Caught exception: Undefined array key ""
Stack trace: 
#0 \app\Libraries\Barcodes\Ean13.php(277): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\Users\\objec\\...', 277) 
#1 \app\Libraries\Barcode_lib.php(157): App\Libraries\Barcodes\Ean13->draw() 
#2 \app\Libraries\Barcode_lib.php(214): App\Libraries\Barcode_lib->generate_barcode(Array, Array) 
#3 \app\Views\barcodes\barcode_sheet.php(34): App\Libraries\Barcode_lib->display_barcode(Array, Array) 
#4 \vendor\codeigniter4\framework\system\View\View.php(228): include('C:\\Users\\objec\\...') 
#5 \vendor\codeigniter4\framework\system\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}() 
#6 \vendor\codeigniter4\framework\system\Common.php(1178): CodeIgniter\View\View->render('barcodes/barcod...', Array, true) 
#7 \app\Controllers\Items.php(521): view('barcodes/barcod...', Array) 
#8 \vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Items->getGenerateBarcodes(Array) 
#9 \vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Items)) 
#10 \vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false) 
#11 \public\index.php(79): CodeIgniter\CodeIgniter->run() 
#12 {main}

**Comment by odiea** [comment]
Yes I also have that issue with this barcode
ISBN 9780230766518 [EDIT PRODUCT ](https://www.barcodelookup.com/9780230766518#edit-product)
The $100 Startup: Fire Your Boss, Do What You Love and Work Better to Live More
(Write a Review)
Barcode Formats: ISBN-10 023076651X, ISBN-13 9780230766518
Category: Media > Books
Author: Guillebeau, Chris

**Comment by odiea** [comment]
It doesn't show the issue when I change it to  EAN 8

**Comment by objecttothis** [comment]
The place that it's dying is in this for loop
```
		for ($idx = 1; $idx < 7; ++$idx)
		{
			$value = substr($this->data, $idx, 1);

			if(isset($this->_codingmap[$value][$set_array[$idx - 1]]))
			{
    			foreach($this->_codingmap[$value][$set_array[$idx - 1]] as $bar)
				{
        			if($bar)
					{
						imagefilledrectangle(
							$this->img,
							$xpos,
							0,
							$xpos + $pxPerBar - 1,
							$this->y,
							$black
						);
					}
        			$xpos += $pxPerBar;
    			}
			}
			else
			{
    			throw new \Exception("Invalid index in _codingmap array. Value: $value, Set: {$set_array[$idx - 1]}");
			}
		}
```
It's trying to access an array element 5 but the item id 13228 only has 0-4

**Comment by objecttothis** [comment]
The frustrating thing is that this is working in 3.3.9.

**Comment by odiea** [comment]
I understand your pain. Sendmail also does not work depending on the php version or Apache version.

**Comment by objecttothis** [comment]
> I understand your pain. Sendmail also does not work depending on the php version or Apache version.

That reminds me. The `mixed` type hint for function parameters wasn't introduced until PHP 8.0 so we need to find any instances of it in the code and remove them because they will break PHP 7.4 user's applications.

**Comment by odiea** [comment]
CRITICAL - 2024-02-27 15:46:47 --> Argument 1 passed to App\Libraries\Barcodes\Ean13::setData() must be an instance of App\Libraries\Barcodes\mixed, string given, called in C:\newwamp\www\ospos\app\Libraries\Barcode_lib.php on line 80
in APPPATH\Libraries\Barcodes\Ean13.php on line 125.
 1 APPPATH\Libraries\Barcode_lib.php(80): App\Libraries\Barcodes\Ean13->setData('2')
 2 APPPATH\Libraries\Barcode_lib.php(149): App\Libraries\Barcode_lib::barcode_instance([...], [...])
 3 APPPATH\Libraries\Barcode_lib.php(205): App\Libraries\Barcode_lib->generate_barcode([...], [...])
 4 APPPATH\Views\barcodes\barcode_sheet.php(34): App\Libraries\Barcode_lib->display_barcode([...], [...])
 5 SYSTEMPATH\View\View.php(228): include('C:\\newwamp\\www\\ospos\\app\\Views\\barcodes\\barcode_sheet.php')
 6 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 7 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('barcodes/barcode_sheet', [], true)
 8 APPPATH\Controllers\Items.php(520): view('barcodes/barcode_sheet', [...])
 9 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Items->getGenerateBarcodes([...])
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Items))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

**Comment by objecttothis** [comment]
Exactly. Just take the mixed type hint out and it will work.  We need to do a code search for other places with mixed in there.

**Comment by odiea** [comment]
I changed the location of the $value and it is not givng me the error now. But does it give a correct ean13 for you
```
$value = substr($this->data, $idx, 1);
		for ($idx = 1; $idx < 7; ++$idx)
		{
			//$value = substr($this->data, $idx, 1);
			foreach ($this->_codingmap[$value][$set_array[$idx - 1]] as $bar)
			{
				if ($bar)
				{
					imagefilledrectangle(
						$this->img,
						$xpos,
						0,
						$xpos + $pxPerBar - 1,
						$this->y,
						$black
					);
				}

				$xpos += $pxPerBar;
			}
		}

**Comment by objecttothis** [comment]
> I changed the location of the $value and it is not givng me the error now. But does it give a correct ean13 for you
> 
> ```
> $value = substr($this->data, $idx, 1);
> 		for ($idx = 1; $idx < 7; ++$idx)
> 		{
> 			//$value = substr($this->data, $idx, 1);

I don't see how this worked.  `$idx` isn't defined until the for loop. It throws an 'undefined variable' exception when I try it.

**Comment by odiea** [comment]
This is why I question stuff I try out. LOL

**Comment by objecttothis** [comment]
Yeah, I'm sick of trying to make this abandonware work in the new code.  Per #3455 I'm stripping out the emberlabs code and adding in Picquer/php-barcode-generator

**Comment by objecttothis** [comment]
OK, this all should be working.  If anyone finds any bugs, let me know and I'll fix them.
