### ISSUE TITLE
CI4 Item attributes not working properly

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3900]
The partial/datepicker_locale is now showing a starting date of 1899. It is also showing minutes. 
 view('partial/datepicker_locale', ['config' => '{ minView: 2, format: "'.($config['dateformat'] . '"}')])  Appears not to be working any longer as it did in Ci3. It shows the following error when trying to save a Date in the date format only.
CRITICAL - 2023-12-17 17:25:33 --> Call to a member function format() on null
in APPPATH\Models\Attribute.php on line 892.
 1 APPPATH\Controllers\Items.php(766): App\Models\Attribute->save_value('12/17/2023', 31, 63, '214', 'DATE')
 2 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Items->postSave(63)
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Items))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

**Comment by jekkos** [comment]
Seems to work fine in dev version
