### ISSUE TITLE
Request to remove the showing of the word 'Category' or 'Item name' above and below the Barcode

### ISSUE THREAD

**Issue by JZafarr** [opensourcepos/opensourcepos#3901]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.9
- OSPOS git commit hash is: NA
- PHP version is: NA
- MySQL or MariaDB version is: NA
- OS and version is: NA
- WebServer is: NA
- Selected language is: English
- (If applicable) Docker installation: YES
- (If applicable) Installation package for the LAMP/LEMP stack is: NA

### Question / New Feature / Enhancement

Request to remove the showing of the word 'Category' or 'Item name' next to the name chosen when showing above and below the barcode. We already know what we are selecting when we are going into the settings option. Also add the ability to not cut the last part of a long item name or category above or below the barcode. Please see screenshot.
![Screenshot 2023-12-19 215724](https://github.com/opensourcepos/opensourcepos/assets/62207359/27c4e0e3-2507-4adb-ad13-9459416d9481)

**Comment by odiea** [comment]
Go to application/libraries/barcode_lib . Scroll to the bottom of the page and locate manage_display_layout. Remove the lang name like this shows. Hope this helps you out.

if($layout_type == 'name')
		{
			$result = lang('') . " " . $item['name'];

**Comment by JZafarr** [comment]
Okay it worked and how to stop the truncating of a long name, some of our product names are long and we also have to define Pallets and their numbers next to them. After a certain length it cuts and adds .... at the end

**Comment by JZafarr** [comment]
Nevermind, i just changed the character limit from 40 to 100
