### ISSUE TITLE
Upgrade jsPDF to 2.5

### ISSUE THREAD

**Issue by owlbrudder** [opensourcepos/opensourcepos#3909]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.4.0-dev
- OSPOS git commit hash is: ceea0fec697c95e026aca916b9f7755eee46654b
- PHP version is: 8.2.14
- MySQL or MariaDB version is: 10.5.23-MariaDB
- OS and version is: Linux 6.6.7-100.fc38.x86_64
- WebServer is: Apache/2.4.58 (Fedora Linux) mod_wsgi/4.9.4 Python/3.11 mod_perl/2.0.12 Perl/v5.36.3
- Selected language is: en-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I have just moved from PHP 7.4.x to PHP 8.2.x and this required new copies of composer and npm. When I ran `npm install`, it complained about an old version of uuid. To correct this, I ran `npm install uuid@latest`. As this it finished, the automatic audit reported 2 critical vulnerabilities (20 vulnerabilities in total). I mentioned this on the devroom thread and jekkos asked me to raise an issue which he would look at sometime.

**Comment by jekkos** [comment]
We do have a couple of dependabot alerts open
 https://github.com/opensourcepos/opensourcepos/security/dependabot

**Comment by jekkos** [comment]
Tried to run `npm audit fix --force` and strangely enough it suggested to downgrade gulp and pdf export library. Also one of the alerts is about a library we use and a potential XSS vulnerability it has. I don't think we are affected by that.

**Comment by jekkos** [comment]
Reduced the critiical warnings by one. Fixing the other issue would require a jspdt upgrade to 2.5.x .Currently bootstrap table depends on 1.x so that will be a breaking change. Will need to investigate further if this is really the only way and if that upgrade would potentially break something in our functionality.

**Comment by jekkos** [comment]
jspdf might need an upgrade if I understand #3894 correctly

**Comment by objecttothis** [comment]
> jspdf might need an upgrade if I understand #3894 correctly

Yes, the current version of jspdf does not work properly.
