### ISSUE TITLE
Adding Serial Number prevents us from chaning the quantity of that item 

### ISSUE THREAD

**Issue by ElveHultqvist** [opensourcepos/opensourcepos#3922]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [X] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.8
- OSPOS git commit hash is: 
- PHP version is: 7.4.33
- MySQL or MariaDB version is:  5.5.5-10.5.21, MariaDB-0+deb11u1
- OS and version is: Linux 5.10.0-25-amd64
- WebServer is: nginx/1.18.0
- Selected language is: en-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

When we check the box for "Item has Serial Number", we can't change the quantity for that item. 

![image](https://github.com/opensourcepos/opensourcepos/assets/93058718/5ea4c4ee-bc9a-491e-bc0b-fd3c0f9d5a85)

**Comment by odiea** [comment]
That is correct. Are you selling multiple electronics  or stereos with the same Serial number?
