### ISSUE TITLE
Windows 11 HTTP ERROR 500

### ISSUE THREAD

**Issue by NXT44** [opensourcepos/opensourcepos#3925]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 3.3.9
- OSPOS git commit hash is: 
- PHP version is: 8.0.1
- MySQL or MariaDB version is: MySQL
- OS and version is: Windows 11
- WebServer is: Apache
- Selected language is: en-US
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

OSPOS Version 3.2.3 is working fine.
If a do a new installation of version 3.3.9 I'm getting "HTTP ERROR 500".
I followed the installation Wiki for Windows with MAMP.
I'm using MAMP for the PHP and the MySQL server.

Thanks!

**Comment by odiea** [comment]
PHP version is: 8.0.1 is too high. Should be 7.4

**Comment by NXT44** [comment]
Yes found it.
Now I get the error "The installation is not correct, check your php.ini file."
Any idea how to solve this?

**Comment by odiea** [comment]
Search the issues. That should be there.

**Comment by ANTOINE1128** [comment]
how can i find the php-7.4?
