### ISSUE TITLE
Feature: Rename Company Logo on upload and housekeeping of company_logo files

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3930]
Current OSPOS 3.3.9 behavior for company logo in OSPOS > Configuration > Information is
- Upload the file as is given by the user and not rename.
- When removing the company logo to not remove the file but just replace the value for the filename with an empty string.
- Changing the company_logo does not remove any old company logo.

Proposed changes
- ~~save the default logo as default_company_logo.jpg.  This is the OpensourcePOS logo.~~ (The default logo is embedded as an SVG and is visible if a custom company logo is not present so this change is not needed)
- Clicking "Remove Image" causes the current image to be deleted on disk and the value of the company_logo in the database be set to default_company_logo.jpg. Clicking "Remove Image" would retain it's current behavior of causing the button on the view to read "Select Image" even though technically it has the default company logo file that it displays.
- Adding or changing company logo causes the uploaded file to be renamed to company_logo.[ext] where [ext] is the result of `file->guessExtension();`

These changes would result in
- ~~Always having some image on the login landing page rather than the blank company logo section that looks sort of awkward when "Remove Image" has been clicked.~~ (already present behavior)
- Keeping /public/uploads/ free from clutter.

Thoughts?

**Comment by jekkos** [comment]
So we always have a max of two files for the logo active at the same time

* company_logo
* default_company_logo
* 
the first one is renamed and overwritten from any file that is uploaded. If it does not exist, due to it being deleted or not uploaded yet, then we fallback to the second default one/

**Comment by objecttothis** [comment]
> So we always have a max of two files for the logo active at the same time
> 
> * company_logo
> * default_company_logo
> * 
> the first one is renamed and overwritten from any file that is uploaded. If it does not exist, due to it being deleted or not uploaded yet, then we fallback to the second default one/

That was my original thought but then I realized that the default logo is an embedded SVG, no no need to keep it on disk. Someone did ask for the possibility to have a custom logo AND receipt logo though. I think due to poor print quality on thermal printers people asked for the ability to do a b/w version.

**Comment by jekkos** [comment]
@objecttothis perhaps we can just use md5 hash of filename + date to have a unique filename for each upload. I would apply this consistently for item pics and company logo.

**Comment by objecttothis** [comment]
> @objecttothis perhaps we can just use md5 hash of filename + date to have a unique filename for each upload. I would apply this consistently for item pics and company logo.

This is not a bad idea.  The only drawback I can see for it is in the case that a user wants multiple items to use the same image.  We do this with books.  Even then, that's problematic because some books are given the same barcode (ISBN) number by the publisher but would need completely different images.  

I assume that we would not migrate existing images, but just all images after the code change?  It seems like it would be potentially problematic to change existing images.

As for the company logo, we could apply the same logic as long as we are doing proper cleanup when the logo is changed.  Someone made a feature request to implement a separate receipt logo for thermal printers that don't render color logos well, so we should keep that in mind regarding our implementation.

**Comment by jekkos** [comment]
Currently we do not really allow to reuse existing uploaded images.. it might be a handy feature, as now you always need to upload again a new file if you want to add an avatar. But every uploaded file will get a unique name.
