### ISSUE TITLE
delete button for suspended sales direct from menu

### ISSUE THREAD

**Issue by hoststatic** [opensourcepos/opensourcepos#3933]
I am loading suspended sale on new page, and struggling to delete suspended sales from a url instead of going to unsuspend and then delete there.

Unsuspend url is like localhost/ospos/public/sales/unsuspend  with payload
csrf_ospos_v3=cecxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&suspended_sale_id=57242&submit=Unsuspend.

Is there any short around more like calling an url delete/....sale_id=57242

It can be done with a url redirect and then loading the url /cancel but is there a simpler way

thanks

**Comment by odiea** [comment]
What version are you using.

**Comment by hoststatic** [comment]
sorry have been away for some days. I have version 3.3.6 
I got suspeded sales in a custom page (not the form) and would like to build something like delete button for each suspended sale, suspended sales are in rows and would like to have for each row a button for deleting @odiea

**Comment by hoststatic** [comment]
dear @odiea would you consider providing a button function for completing sale directly. Thanks

**Comment by odiea** [comment]
That is beyond my ability.
