### ISSUE TITLE
Nuestra pagina web es inestable y se cae constantemente

### ISSUE THREAD

**Issue by Entrepaginas** [opensourcepos/opensourcepos#3939]
### Installation information
Información de la Instalación OSPOS: 3.3.1 - c786d4
Language Code: es

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache
.PHP Version: 7.3.33
.DB Version: 5.5.5-10.6.16-MariaDB-cll-lve
.Server Port: 443
.OS: Linux pyme109.pymedns.net 3.10.0-962.3.2.lve1.5.83.el7.x86_64 #1 SMP Thu Nov 23 15:58:18 UTC 2023 x86_64

File Permissions:
» [application/logs:] - 0755 | Writable ✓
» [public/uploads:] - 0755 | Writable ✓
» [public/uploads/item_pics:] - 0755 | Writable ✓
» [import_customers.csv:] - 0644 | Writable ✓

### Issue / Bug  / Question / New Feature

Tenemos nuestra pagina web  y abre pero no podemos hacer porque esta en un constante cargar y luesto la pagina se cae, hay algo que podemos hacer?

**Comment by jplrts** [comment]
¿¿

**Comment by ekardian** [comment]
estás en hosting de pago? o es tu servidor personal? llevas dominio propio? 
y sugiero que descargas la versión [ospos 3.3.9](https://github.com/opensourcepos/opensourcepos/releases/tag/3.3.9) estable y lee el [manual de instalacion](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) por si saltaste algunos requerimientos

**Comment by ingmarioalberto** [comment]
Yo te puedo apoyar a determinar si es culpa del software o bien de tu hosting, sin fines de lucro, saludos.
