### ISSUE TITLE
[Bug]: Disappearing Item Image

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3954]
### Bug Description?

Add Item pic to Item form. Save open then save Item form. Item pic disappears.

### Steps to Reproduce?

Same as above

### Expected Behavior?

Item pic should stay.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Wamp Server

### Database Management System and version

Mysql 8.2.0

### Web Server and version

Wamp Server

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by odiea** [comment]
controller/Items line 685 I changed  $item_data['pic_filename'] = !empty($upload_data['orig_name']) && $upload_data['raw_name']? $upload_data['raw_name'] . '.' . $upload_data['file_ext']: null
to. 
if(!empty($upload_data['orig_name']))
	{		
	if($upload_data['raw_name'])
		{
		$item_data['pic_filename'] = $upload_data['raw_name'];
		}
	}
And now the previous avatar is not removed.

**Comment by jekkos** [comment]
Is this still an issue? Tried on my local setup and the item pic does not disappear

**Comment by jekkos** [comment]
Will close, can be reopened if needed.
