### ISSUE TITLE
[Bug]: CI4 Suspend Sale fails

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3964]
### Bug Description?

![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/dd77faeb-7ddb-464f-8c28-cd5cb30fd050)

### Steps to Reproduce?

1. Navigate to Sale Register
2. Add an item.
3. Click "Suspend" button

### Expected Behavior?

The sale would be properly suspended.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

Windows 11

### Database Management System and version

MySQL 8.2.0

### Web Server and version

Apache 2.4.58

### System Information Report (optional)

OSPOS Installation Info: 3.4.0-dev - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓
» Xml: Enabled ✓

User Configuration:
.Browser: Firefox
.Server Software: Apache/2.4.58 (Win64) OpenSSL/3.1.3 mod_fcgid/2.3.10-dev
.PHP Version: 8.2.12
.DB Version: 8.2.0
.Server Port: 80
.OS: Windows NT 10.0

File Permissions:
» [writeable/logs:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗	
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗	
» [writable/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗	
» [import_customers.csv:] - 0666 | Readable ✓ | Vulnerable or Incorrect Permissions ✗	

Security Vulnerability Warning
Incorrect permissions leaves this software at risk.

» [writeable/logs:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [writable/uploads:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [writable/uploads/item_pics:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [import_customers.csv:] is readable, but the permissions are incorrectly set. Please set it to 640 or 660 and refresh.	
[REDACTED LOCALE]

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Resolved now in dev vresion
