### ISSUE TITLE
CodeIgniter 4.5.0 drops support for PHP versions before 8.1.0

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3966]
### OpensourcePOS Version

opensourcepos 3.4.0-dev

### Description

Looks like we will need to officially end support for php 7.4.x and 8.0.x in OSPOS 3.4.0.  This is because CI4 does not support them as of 4.5.0 (https://codeigniter4.github.io/CodeIgniter4/intro/requirements.html).  Possibly another option would be to release 3.4.0 on CI 4.4.8, then the next minor release after 3.4.0 we bump to CI 4.5.0 and drop support for PHP 7.4 and 8.0 flavors. @jekkos et. al., can you weigh in on this?  It's kind of a big decision.

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by objecttothis** [comment]
both 7.4 and 8.0 are EOL

**Comment by objecttothis** [comment]
For now I've bumped CodeIgniter to 4.4.8 which is the last version with PHP 7.4.x and 8.0.x support.

**Comment by jekkos** [comment]
I would move forward with this. Ospos is currently the only PHP app that is holding me back to remove PHP7.4 from my server.

**Comment by andriux1990** [comment]
I downloaded ci4-branch (https://github.com/opensourcepos/opensourcepos/tree/ci4-branch). Since php7.4 is left behind, as I mentioned before I want to fully support the migration to codeigniter 4.5.
I ran the code, noticed that there are three connections to the database. I tried to configure it and I think I did it correctly, but I got a blank screen.

**Comment by andriux1990** [comment]
I downloaded all the code and just configured it. If there's anything else I need to do, please let me know.

**Comment by objecttothis** [comment]
Take a look at README.md. the commands to install packages and build are there.

**Comment by andriux1990** [comment]
> Take a look at README.md. the commands to install packages and build are there.

Thank you, I'm already reading the instructions. One question, is this version still compatible with PHP 7.4 or is it only for PHP 8.1 onwards?

**Comment by objecttothis** [comment]
The ci-branch currently is on CI 4.8 which is the last branch to support 7.4 and 8.0. Based on @jekkos feedback, it's probably best for us to move it to CI 4.5.0 which drops support for those versions.  There are two reasons for this being a good thing:
- Neither of those PHP versions are receiving security patches any longer, so the more time that goes by, the more likely a vulnerability will cause problems for OSPOS deployments.
- There are not a lot of people able to help finish getting the conversion to CI4 done. Not needing to develop for compatibility with 7.4 and 8.0 will reduce the amount of time needed for me to finish this.

If anyone has good reason not to drop support for 7.4 and 8.0 I'm all ears, but they need to speak up soon.

**Comment by SteveIreland** [comment]
I vote for the motion to upgrade to CI 4.5.0.

**Comment by andriux1990** [comment]
I think migrating OSPOS to CodeIgniter 4 can be done very quickly. The issue lies in sales and purchases; that's where the real complexity lies. I also suggest not relying so much on Bootstrap and finding a way to call tables more dynamically, using foreach. I have it set up like this in OSPOS, and it allows for much more customization.

**Comment by andriux1990** [comment]
We need to use jQuery, but not rely on opensourcepos.min.js. Relying on it limits us to having an updated version of jQuery. We should find another way to call modals, using the frontend more.

![Screenshot_20240412_063907](https://github.com/opensourcepos/opensourcepos/assets/29256343/cfb1109a-6c6a-4063-8e75-536a92c3c1c3)
![Screenshot_20240412_064110](https://github.com/opensourcepos/opensourcepos/assets/29256343/fa043a01-756c-445c-b551-3b3a3adb26ce)
I customized the view to use a different type of modal window, one that allows for more customization.

And this is done using foreach to display the products in the items module
![WhatsApp Image 2024-04-12 at 6 45 57 AM](https://github.com/opensourcepos/opensourcepos/assets/29256343/46648063-eef5-4c6d-bdc7-b1fc8b240a4e)
![WhatsApp Image 2024-04-12 at 6 45 58 AM](https://github.com/opensourcepos/opensourcepos/assets/29256343/67402514-34ed-43ba-814f-49c40fc30cb3)

**Comment by objecttothis** [comment]
> I think migrating OSPOS to CodeIgniter 4 can be done very quickly. The issue lies in sales and purchases; that's where the real complexity lies. I also suggest not relying so much on Bootstrap and finding a way to call tables more dynamically, using foreach. I have it set up like this in OSPOS, and it allows for much more customization.

Feel free to help contribute code to fix the changes, but we are doing one thing at a time.  the ci4-branch is just focused on the existing functionality migrating to CI4. After that's done when we make UI changes and the like, that will be a part of a different branch. The more people contributing, the faster this will go.

**Comment by objecttothis** [comment]
> I vote for the motion to upgrade to CI 4.5.0.

OK, sounds like enough people are on board.  On Monday I will bump the ci4-branch to CI 4.5.0 and make whatever code changes need to happen for it to build properly.
