### ISSUE TITLE
[Bug]: New development error

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3968]
### Bug Description?

![2024-04-16 04_44_32-Window](https://github.com/opensourcepos/opensourcepos/assets/10962177/5e07fc5e-09e6-4d1c-8014-ce18472c369b)

### Steps to Reproduce?

try to open ci4 branch after last commits

### Expected Behavior?

It to work as usual

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Wamp Server

### Database Management System and version

Wamp Server

### Web Server and version

wamp Server

### System Information Report (optional)

Syst
![2024-04-16 04_44_32-Window](https://github.com/opensourcepos/opensourcepos/assets/10962177/9d456da3-6d61-40f8-8cfd-3ad36ec0c779)
em Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by odiea** [comment]
After rebuilding this branch the following error shows.
![2024-04-16 05_28_55-Window](https://github.com/opensourcepos/opensourcepos/assets/10962177/876374f8-6f56-4716-8b10-e3f492401c51)

**Comment by odiea** [comment]
To get this part to work I had to change \www\\ospos4\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php', 193
to just $config.

**Comment by odiea** [comment]
I am now showing the following error when trying to display a receipt from the takings view.
The param count in the URI are greater than the controller method params. Handler:\App\Controllers\Sales::getIndex, URI:sales/receipt/76 and now it is too buggy for me to test any longer trying to create a sale in the register..

**Comment by WebShells** [comment]
@odiea timezone fix was committed by jekkos earlier today, setting the timezone in .env file to UTC fixes the issue... I'll try to have a look on receipt display.

**Comment by WebShells** [comment]
@odiea if you can test reaching the receipt and invoice through daily sales from your side, i committed the fix now ...Please ignore the barcode error on invoice ...Thanks

**Comment by odiea** [comment]
I was having no issue showing the Receipts until the routes was changed now I get an error 404

**Comment by WebShells** [comment]
> The param count in the URI are greater than the controller method params. Handler:\App\Controllers\Sales::getIndex, URI:sales/receipt/76 and now it is too buggy for me to test any longer trying to create a sale in the register..

How can i reproduce the issue you are getting ?

**Comment by odiea** [comment]
Once I rebuilt it this issue went away. Thanks for looking into it.

**Comment by WebShells** [comment]
Glad to hear that, thanks for reporting it...
