### ISSUE TITLE
Report Export Date and Time

### ISSUE THREAD

**Issue by SidSkiba** [opensourcepos/opensourcepos#3970]
### Type of Feature

✨ New Feature

### OpensourcePOS Version

opensourcepos 3.3.9

### Description

When exporting a report file to say excel it would be nice if the file name would have a date and time identifier. They are all called the same thing at present.

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by SidSkiba** [comment]
After some digging I found that Chrome has an extension called Timestampeder that does this perfectly for my case.  Would still be nice to have OSPOS do it as the extension above does it for all downloads.

**Comment by hoststatic** [comment]
nice thanks for sharing the extension, I guess you have to change some bootstrap settings for the export button

**Comment by jekkos** [comment]
I don't think this should be too hard to do this. It might need a bit of javascript in the filename generation

**Comment by jekkos** [comment]
Hi as I touched this part of the code yesterday, I spent 10 more minutes to implement this feature request, especially for you @SidSkiba .

**Comment by hoststatic** [comment]
will apply this, thanks @jekkos

**Comment by SidSkiba** [comment]
Thank you guys for the amazing work. I look forward to release 3.40.
