### ISSUE TITLE
Installation ospos ci4

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#3971]
I feel silly asking this, I downloaded the ospos 4 ci4 version, then ran the 'composer install' command. Then it gives me the CodeIgniter 4 view. It doesn't show me the ospos login. I'm using Linux, and in the directory, I looked at the .env file used in composer. Please help if I did something wrong. Thanks.

**Comment by WebShells** [comment]
Please check if $baseurl in App.php and htaccess are pointing to OSPOS directory, i didnt face CI4 view page during installation although some issues popped up and they are already fixed.
After running composer you should run npm install & npm run build to link css files not to have broken layout.  
If you have additional info related to the issue you are facing will be helpfull.

**Comment by andriux1990** [comment]
@WebShells thanks. 
Baseurl ready created: public string $baseURL = 'http://localhost/ci4/public/'; 

and .htaccess as well:
       RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	# if in web root
	RewriteRule ^(.*)$ index.php?/$1 [L]

But I'm getting this message when running npm run:
Scripts available in opensourcepos@3.4.0 via `npm run-script`:
  build
    gulp default
  gulp
    gulp

**Comment by andriux1990** [comment]
"php spark serve" starts a local development server and provides you with a URL. It works for CodeIgniter 4, but with OSPOS CI4, I get the error message:

Whoops!

We seem to have hit a snag. Please try again later...

**Comment by andriux1990** [comment]
Done, I got it working. You also need to put the credentials in .env at the root directory.

**Comment by WebShells** [comment]
> Done, I got it working. You also need to put the credentials in .env at the root directory.

I thought you've set it already, great it worked!
