### ISSUE TITLE
Support multiple printers for multiple restaurant kitchens [Feature]:  

### ISSUE THREAD

**Issue by DrXtreme** [opensourcepos/opensourcepos#3972]
### Type of Feature

✨ New Feature

### OpensourcePOS Version

opensourcepos 3.3.9

### Description

Hello, I have a restaurant that has more than one kitchen, I setup all the kitchens printers to print with the main POS printer, but we want to print only what we make at that kitchen to that printer.

For Example: you order from the bbq menu and you get a receipt and the bbq kitchen gets a receipt but the other kitchens dont.

### Additional Information

I actually want to develop this feature myself but I need a replacement for JSPrintSetup as it is not available anymore (I use firefox ESR).

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by odiea** [comment]
JSPrint still works on Pale Moon. Hope this helps.

**Comment by andriux1990** [comment]
@odiea. I didn't know about that browser, another thing that can be done since the browsers no longer have this function available is to use a webview with Electron and configure the printer there.

**Comment by mnasruul** [comment]
Hi, I'm waiting for this feature 🙏

**Comment by mnasruul** [comment]
> JSPrint

@odiea  Hi, I have installed the pale moon browser, what next? I checked the add-on, there is no jsPrint https://addons.palemoon.org/search/?terms=print
![image](https://github.com/user-attachments/assets/ad409188-08c5-4028-9342-5b2f8d88b79c)

**Comment by odiea** [comment]
I installed it years ago so that is why it is still working. It appears to have been removed from addons.
