### ISSUE TITLE
Focus on OSPOS 3.4.0

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#3973]
I have been using the 2020 version of OSPOS, and the bugs are repairable, nothing serious. So, now with version 3.3.9, it is quite stable. I think we should move on from CodeIgniter 3 and focus on 3.4.0 with CI4. Looking at it, there is much work to be done. It practically only shows the interface, which is a significant step forward. I will start with the clients, making sure they are displayed and can be saved. The code needs to be migrated. Then, we can tackle inventory. It's quite a big task, especially regarding CSV imports.

As I've said before, I believe the challenging part will be sales and purchases, as they involve many processes that require a lot of work.

**Comment by objecttothis** [comment]
@andriux1990 3.4.0 is limited to keeping current functionality but with CodeIgniter 4.5.1. There is a good deal to be done still with working out kinks in 3.4.0, but I'm not sure I understand what you mean when you say the code needs to be migrated.  Most of that work is done already, it's now fixing the bugs of things that don't work after the migration.  That and making sure the validation, filtering and escaping is working as expected.

It's helpful to have multiple people contributing now on this, but let's make sure we communicate clearly about what we are working on so that we don't duplicate work. The opensourcepos/devroom in gitter.im has been the main space for the devs to communicate. You already have an invite to that room, so just install a matrix compatible client like element and change your server to gitter.im to get it up and running.

I don't remember what isn't working with CSV imports, but someone should take a look.  It's probably a good idea to make sure there are github issues created for things and assign yourself so that people know you are working on it.

**Comment by WebShells** [comment]
@andriux1990 all forms are now displaying and submitting/updating data as expected. Whether it's a new record like new item, customer, supplier, expense, gift card etc... Or updating previous data for the mentioned modules. Please fetch the latest changes from CI4 branch in order not to spend your time on things already fixed. Thanks

**Comment by odiea** [comment]
That is not quite correct. Testing Receiving update The following error displays. You all are doing great.
404
The param count in the URI are greater than the controller method params. Handler:\App\Controllers\Receivings::getIndex, URI:receivings/edit/1

**Comment by jekkos** [comment]
For the devroom you can also just use a browser, I mainly check it from my laptop as I don't like typing on a phone keyboard.

**Comment by WebShells** [comment]
@odiea thanks for testing this, can you check it again ? i committed a fix for the modal display. Still not submitting/updating data but now it's showing, will check further for data update.

**Comment by WebShells** [comment]
@odiea test also displaying the receiving receipt, please fetch the latest commits.

**Comment by odiea** [comment]
In Receivings Post needs to be added to save but there are issues when saving the form and the supplier search is not working.
In Sales when saving the form there is an issue with unknown column payments in list. Receipts and Modals are working good.  In my earlier version I had to change back save to the ci3 payments code then the payments issue went away

**Comment by odiea** [comment]
@jekkos  How do we get to the dev room. Clicking on gitter displays bad stuff.

**Comment by WebShells** [comment]
Yeah thats why i mentioned still not submitting, for the receivings supplier search not working and for sale edit the check_invoice_number isn't working as needed which keeping form from submitting data. 
I think CI4 branch have corrected gitter link.

**Comment by jekkos** [comment]
I have updated the README.md in master, the link should be fixed now Hopefully more devs can find their way to the chatroom now

**Comment by andriux1990** [comment]
Could someone please tell me which version of the Bootstrap theme I should use for the correct interface of OSPOS? Since the modal and the table are not working for me. If I don't have the correct interface, I won't be able to know what the real problems are.
Thanks

**Comment by objecttothis** [comment]
After you check out ci4-branch you need to build the application. The instructions to build are in readme.MD. The css will function correctly then.

**Comment by andriux1990** [comment]
@objecttothis thanks for answering. If you're referring to these instructions: https://github.com/opensourcepos/opensourcepos/blob/ci4-branch/INSTALL.md or https://github.com/opensourcepos/opensourcepos/blob/ci4-branch/README.md . It doesn't specify the version of the CSS.

In the partial/header.php file, there's this link: <link rel="stylesheet" type="text/css" href="<?= 'resources/bootswatch/' . (empty($config['theme']) ? 'flatly' : esc($config['theme'])) . '/bootstrap.min.css' ?>"/>, where the CDN should be placed. I've tried all versions, using both version 4 and version 5, and even directly inserting the CDN. But I think it's giving me the incorrect interface.

**Comment by objecttothis** [comment]
> Another problem I've had is that when migrating my existing database from the previous version of OSPOS, I can't log in afterward. I don't know if this is just happening to me because I have some additional tables, or if it has also happened to you all?

You need to change the ci environment variables in the env file. Set it to development and increase the log level. Look at the logs after trying to login to see exactly what error you're getting. The migration from CI3 to CI4 is complex and while it has been tested thoroughly, we need to spot all the edge cases, so create an issue of you spot something.

**Comment by andriux1990** [comment]
> After you check out ci4-branch you need to build the application. The instructions to build are in readme.MD. The css will function correctly then.

Thanks, regarding the interface issue. version 3.4.0 works best but it still looks like this.
![WhatsApp Image 2024-04-26 at 11 51 18 AM](https://github.com/opensourcepos/opensourcepos/assets/29256343/e47c20a7-ff47-49c4-99ed-934daccf6e1e)

**Comment by objecttothis** [comment]
> @objecttothis thanks for answering. If you're referring to these instructions: https://github.com/opensourcepos/opensourcepos/blob/ci4-branch/INSTALL.md or https://github.com/opensourcepos/opensourcepos/blob/ci4-branch/README.md . It doesn't specify the version of the CSS.
> 
> In the partial/header.php file, there's this link: <link rel="stylesheet" type="text/css" href="<?= 'resources/bootswatch/' . (empty($config['theme']) ? 'flatly' : esc($config['theme'])) . '/bootstrap.min.css' ?>"/>, where the CDN should be placed. I've tried all versions, using both version 4 and version 5, and even directly inserting the CDN. But I think it's giving me the incorrect interface.

Sorry, look at  https://github.com/opensourcepos/opensourcepos/blob/ci4-branch/BUILD.md

Use the build instructions in that file.

**Comment by andriux1990** [comment]
@objecttothis @odiea @jekkos @WebShells Ready, Thank you.
Everything I've tried is working now, from the clients, items, and sales. I'll continue running tests.
