### ISSUE TITLE
[Bug]: Sales delete payment needs a Route

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3983]
### Bug Description?

Try deleting a payment from the Register.
404
The param count in the URI are greater than the controller method params. Handler:\App\Controllers\Sales::getIndex, URI:sales/delete_payment/Credit Card. I 

### Steps to Reproduce?

Try deleting a payment from the Register.

### Expected Behavior?

Delete a payment

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Wamp server and Demo

### Database Management System and version

Wamp Server

### Web Server and version

Wamp Server

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Seems the method is get and not post. I did find some javascript that uses a post, but it seems that it is not in use.

**Comment by odiea** [comment]
Yes it is a get and now works.

**Comment by jekkos** [comment]
Pushed the fix works now, thanks for the bug report!
