### ISSUE TITLE
[Bug]: The route for "no_access/office/" cannot be found. 

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3984]
### Bug Description?

In the address bar and you don't have permission for office change the current http://localhost/ci4branch/public/sales to office and this is the error reported.

### Steps to Reproduce?

In the address bar and you don't have permission for office change the current http://localhost/ci4branch/public/sales to office and this is the error reported.

### Expected Behavior?

Should to return to home or current controller.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Wamp server

### Database Management System and version

wamp server

### Web Server and version

wamp server

### System Information Report (optional)

Not required?

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Pushed a commit for this one. The url you mention should give the access denied now. But the redirect is still not working

**Comment by jekkos** [comment]
Fix this now in the ci4-branch.

**Comment by odiea** [comment]
@jekkos in Secure_controller I changed lines 52 and 53 to the following and now it brings me back to Home instead of No_access.  

header("Location:".base_url('login'));
			exit();

**Comment by jekkos** [comment]
that is an option as well, but then the behavior would be different as it was before. Would you consider that an improvement

**Comment by odiea** [comment]
I would. Todays employees may not know how to use the back arrow on Chrome or Firefox Browsers

**Comment by jekkos** [comment]
I do believe that in normal circumstances an employee should not end up in a section where she does not have access. The link to the module is hidden and can only be accessed by going to the URL directly. In that case it might still be useful to give a proper message on why the page is not accessible. Any thoughts on this @objecttothis ?

**Comment by objecttothis** [comment]
I think in the current PR we should replicate the functionally of 3.3.9 and assign changes to the 3.4.1 or later milestone. I think it's reasonable to give the employee a message showing they don't have access to that module rather than a URL not found error which might lead to GitHub issues being created because people think something in the app is broken.

**Comment by jekkos** [comment]
Lets stick with 3.3.9 behavior for now then
