### ISSUE TITLE
[Bug]: Gulp does not properly copy fonts for some reason.

### ISSUE THREAD

**Issue by SpookedByRoaches** [opensourcepos/opensourcepos#3987]
### Bug Description?

In the past week or so, the gulp task that is supposed to copy the fonts from the bootswatch dist directory in node_modules, copies a wrong file or does something else I don't know. After running `npm run build` everything is ok except the fonts and I don't know why. The other files seem to be OK. The diff command is supposed to show that the files are different and even the sizes are wildly different.

```
$ diff public/resources/bootswatch/superhero/bootstrap.min.css ./node_modules/bootswatch/superhero/bootstrap.min.css
$ diff node_modules/bootswatch/fonts/glyphicons-halflings-regular.woff ./public/resources/bootswatch/fonts/glyphicons-halflings-regular.woff
Binary files node_modules/bootswatch/fonts/glyphicons-halflings-regular.woff and ./public/resources/bootswatch/fonts/glyphicons-halflings-regular.woff differ
```

The resulting files are binary garbage and aren't even fonts. They make the browsers throw errors regarding the decoding of the fonts.

### Steps to Reproduce?

run `npm run build`

### Expected Behavior?

The files should be exactly the same

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.4

### What browsers are you seeing the problem on?

Firefox, Chrome

### Server Operating System and version

Linux: 6.8.7-zen1-2-zen  

### Database Management System and version

mariadb 11.3.2

### Web Server and version

apache 2.4.59-1

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by objecttothis** [comment]
@jekkos I suspect when you bumped dependencies to get jspdf and other stuff working it may have had this effect.  Do you want to investigate this? If not, that's OK, but I think you might have more experience with the build stuff than I do.

**Comment by objecttothis** [comment]
Here is one of the PR's https://github.com/opensourcepos/opensourcepos/pull/3981/files

**Comment by SpookedByRoaches** [comment]
You're right @objecttothis when I revert back to commit `e870697`, it's fine. But when going to the `42a54bb` commit it copies wrong again. Although I can't say why it does that.

**Comment by jekkos** [comment]
Indeed wel spotted @SpookedByRoaches, I might have removed something by accident. Gulp was giving me some errors on non-existant folders, which led me to remove the offending copy.

**Comment by jekkos** [comment]
This issue is due to the gulp [bump to 5.0](https://github.com/gulpjs/gulp/issues/2797). Will apply the fix mentioned there.

**Comment by jekkos** [comment]
Fixed now in ci4-branch.
