### ISSUE TITLE
[Bug]: Loop issue in Detailed and Specific Reports

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3990]
### Bug Description?

Tables appear properly but the following error shows in debug.
CRITICAL - 2024-05-10 11:34:29 --> Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames
[Method: GET, Route: /]
in SYSTEMPATH\Debug\Toolbar.php on line 313.
SYSTEMPATH\Debug\Toolbar.php(331): CodeIgniter\Debug\Toolbar->structureTimelineData([...]) 256 lines
248 SYSTEMPATH\Debug\Toolbar\Views\toolbar.tpl.php(102): CodeIgniter\Debug\Toolbar->renderTimeline([...], 1715340866.502661, 7, 90, [])
249 SYSTEMPATH\Debug\Toolbar.php(534): include('C:\\newwamp\\www\\ospos5\\vendor\\codeigniter4\\framework\\system\\Debug\\Toolbar\\Views\\toolbar.tpl.php')
250 SYSTEMPATH\Debug\Toolbar.php(497): CodeIgniter\Debug\Toolbar->format([...], 'html')
251 APPPATH\Config\Events.php(50): CodeIgniter\Debug\Toolbar->respond()
252 SYSTEMPATH\Events\Events.php(155): CodeIgniter\Events\Events::Config\{closure}()
253 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\Events\Events::trigger('pre_system')
254 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
255 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
256 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))

### Steps to Reproduce?

Do a Report with a date of  weeks or months

### Expected Behavior?

Tables do show properly

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.3

### Server Operating System and version

Wamp

### Database Management System and version

mysql

### Web Server and version

Wamp

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Tried to run a couple of reports with month or custom intervals. Currently a table is shown in all cases.

**Comment by odiea** [comment]
Yes this appears to be an old bug that was fixed after the reports started working again.
