### ISSUE TITLE
[Bug]: No Nominatim geocoding service. in any person form

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3992]
### Bug Description?

Try adding a zip code to any person form.
Access blocked
You have been blocked because you have violated the usage policy of OSM's Nominatim geocoding service. Please be aware that OSM's resources are limited and shared between many users. The usage policy is there to ensure that the service remains usable for everybody.

Please review the terms and make sure that your software adheres to the terms. You should in particular verify that you have set a custom HTTP referrer or HTTP user agent that identifies your application, and that you are not overusing the service with massive bulk requests.

If you feel that this block is unjustified or remains after you have adopted your usage, you may contact the Nominatim system administrator at nominatim@openstreetmap.org to have this block lifted.

### Steps to Reproduce?

Same as above

### Expected Behavior?

Zip should show Info.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### Server Operating System and version

Wamp Server

### Database Management System and version

Mysql

### Web Server and version

Wamp Server

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Their rate limit is 1 request per second. Maybe they also require to add a referral header now.

**Comment by jekkos** [comment]
I tried this now on dev and the form works as expected. Maybe they just temporarily block you because you make too many requrests at a time. I can increase the delay to abide their usage policy, one request per second max.

**Comment by jekkos** [comment]
It seems that the rate limitation is already set to 1s. Another recommendation is to set the referrer or user agent in the request. Alas this cannot be done if the call is made from a browser. So this means that it might need to be done from the backend instead, this way we also have more control over the rate at which the calls go out to this exernal API

@odiea are you able to reproduce this issue ?

**Comment by odiea** [comment]
This is the second time in the last year that I have tested this feature.

Access blocked
You have been blocked because you have violated the [usage policy](https://operations.osmfoundation.org/policies/nominatim/) of OSM's Nominatim geocoding service. Please be aware that OSM's resources are limited and shared between many users. The usage policy is there to ensure that the service remains usable for everybody.

Please review the terms and make sure that your software adheres to the terms. You should in particular verify that you have set a custom HTTP referrer or HTTP user agent that identifies your application, and that you are not overusing the service with massive bulk requests.

If you feel that this block is unjustified or remains after you have adopted your usage, you may contact the Nominatim system administrator at nominatim@openstreetmap.org to have this block lifted.

**Comment by odiea** [comment]
I just tried the dev demo and get the same access blocked.

**Comment by odiea** [comment]
I am not worried about this. I just test to see if is still working.

**Comment by jekkos** [comment]
I tested again and still working for me on dev. Does it work for you now as well?

**Comment by odiea** [comment]
Yes it is working for me now.
