### ISSUE TITLE
[CI4][Bug]: Language fallback

### ISSUE THREAD

**Issue by BudsieBuds** [opensourcepos/opensourcepos#3994]
### Bug Description?

Language fallback doesn't work as it did in the CI3 version. Empty strings in the translation files are returned as an empty string instead of falling back to English. If the string is removed from the language file, the fallback kicks in as it should.

### Steps to Reproduce?

Change the language on a `ci4-branch` build to an incomplete language. For example, Dutch translates `Welcome to OSPOS!` to `Welkom bij !` on the login screen because there's no translation for `OSPOS`. German gives an error on the login screen because of the nested translation and missing translations for both `Login.welcome` and `Common.software_short`.

### Expected Behavior?

This is the expected behavior for CI4, but a fallback to English should be coded. The same happened [here](f43a620bf400514639628c745c4a2ef5149db15f) for the CI3 version by @jekkos. Changing the language from `en-US` to `en` is also important for it to work correctly, as done here #3995.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Firefox, Chrome

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
@BudsieBuds to avoid a tricky migration I would just drop the language config in the db for 3.4 upgrade. Its only a small annoyance and a user can quickly restore language. so then we do not need to write a lengthy migration that mirrors the renaming you did in the file tree.
