### ISSUE TITLE
How to exempt only one tax type?

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#3998]
In Canada certain people can present a card and they don't have to pay one of two taxes.  I know there's a tax exempt checkbox for customers but that removes both taxes.  How would I go about removing just one.  My taxes are set up per item.  

Thanks

**Comment by jekkos** [comment]
So either tax exemption should be modelled per tax instead, Eg by creating config keys dynamically that represent the tax to exempt a customer for.

**Comment by chunter2** [comment]
Are you suggesting a code change or is this something done in the configuration of the software?

**Comment by SteveIreland** [comment]
This seems like it would be a small code change.   May I ask what the card represents?  Does it indicate local tax exemption due to a particular type of business, or is it a personal situation that qualifies for a local exemption?

**Comment by chunter2** [comment]
It's a Certificate of Indian Status card that they can present.  We have HST which is a provincial tax.  This can be removed when the card is presented.  We also have GST which is a country tax.  This one cannot be removed.  

https://www.ontario.ca/document/harmonized-sales-tax-hst/hst-ontario-first-nations-rebate

**Comment by SteveIreland** [comment]
Have you considered the destination based tax instead of the default tax system?  Each customer can use a different tax code configuration.  Or if it's a walk in customer, you can set up to house accounts, one for if they have a card and the other for if they don't have a card.   Changing tax methods is always a pain, so it might easier for you to just customize your installation.  But the destination based tax system was intended for the purpose of making things more flexible.

**Comment by chunter2** [comment]
I think the destination based tax system is what I need, I'm just not quite sure how it works.  Currently we have a customer called Tax Exempt that we've been using but we didn't realize we weren't supposed to be removing both taxes.  We only use customers for generic things like a 15% discount for example.  How would I go about setting the destination based tax system up?

**Comment by SteveIreland** [comment]
The documentation for setting up taxes is found in the OSPOS wiki on page https://github.com/opensourcepos/opensourcepos/wiki/Taxes.   I'll be happy to add any additional information you need if you can tell me what's missing.
