### ISSUE TITLE
[Bug]: Tick marks need removed for sales table to show after changing locale date and time filter

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3999]
### Bug Description?

$where .= empty($config['date_or_time_format'])
			? 'DATE(`' . $db_prefix . 'sales`.`sale_time`) BETWEEN ' . $this->db->escape($filters['start_date']) . ' AND ' . $this->db->escape($filters['end_date'])
			: '`sales`.`sale_time` BETWEEN ' . $this->db->escape(rawurldecode($filters['start_date'])) . ' AND ' . $this->db->escape(rawurldecode($filters['end_date']));

### Steps to Reproduce?

Changing date and time filter causes Sales table rows not to show

### Expected Behavior?

Table rows should show whether date and time filter is selected or not.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.3

### Server Operating System and version

Wamp Server

### Database Management System and version

Wamp Server

### Web Server and version

Wamp Server

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Thanks for the report @odiea . Tried this locally and indeed, the filter works again
