### ISSUE TITLE
[Bug]: CI: Creation of dynamic property xxx is deprecated

### ISSUE THREAD

**Issue by PieterWessels** [opensourcepos/opensourcepos#4013]
### Bug Description?

http://localhost/ospos/public/index.php is not working as expected.  It returns multiple errors, and associated follow-on errors.
The intial/principle errors appear to be in Code Ignite (CI) and take the general form of:

```
A PHP Error was encountered
Severity: 8192
Message: Creation of dynamic property CI_URI::$config is deprecated
Filename: core/URI.php
Line Number: 101

Backtrace:
File: C:\xampp\htdocs\ospos\public\index.php
Line: 317
Function: require_once
```
The dynamic properties include:
 - CI_URI::$config
 - CI_Router::$uri
 - Login::$benchmark
 - Login::$hooks
 - Login::$config
 - Login::$log
 - Login::$utf8
 - etc

Indications are that the XAMPP 8.2.12 (with PHP 8.2.12) and the version of CI used in OSPOS are incompatable.  However - I do not know what the highest version of PHP is that still remains compatable with CI 3 (or which ever version underpins OSPOS 3.3.9)

### Steps to Reproduce?

Run OSPOS 3.3.9 in XAMPP 8.2.12

### Expected Behavior?

I expected OSPOS to display the opening login screen.

### OpensourcePOS Version

opensourcepos 3.3.9

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

Windows 10

### Database Management System and version

MariaDB 10.4.32

### Web Server and version

Apache 2.4.58

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by SteveIreland** [comment]
PHP version 8.2 is not supported for version 3.3.9 of OSPOS.

![image](https://github.com/opensourcepos/opensourcepos/assets/23066623/34a3dae5-ca9c-437f-be9f-34baa495920e)
