### ISSUE TITLE
[Feature]: Filter Daily Sales by Selected Customer

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#4017]
### Type of Feature

✨ New Feature

### OpensourcePOS Version

opensourcepos 3.4.0

### Description

Is there any interest in adding a new filter for the Daily Sales  panel that filters on the currently selected customer?  I have that feature installed for my  existing client, but would like to add it to the core system since it's a really nice enhancement and isn't specific to my client's business.

### Additional Information

When you're in the Sales Register, adding a sale to an existing customer, it's often helpful to quickly review the customer's past sales by clicking on the sales button.   This feature would default the initial sales display to only include sales for the selected customer.  The user can then change the filter if they're going to daily sales for another purpose.

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by SteveIreland** [comment]
I'll code it up as a pull request and if it makes it to OSPOS then that's a good thing.  :-)  If not, then I'll just install it in my fork.

**Comment by odiea** [comment]
Sounds to me like a great option. Thanks

**Comment by odiea** [comment]
Works as described.

**Comment by SteveIreland** [comment]
Thanks for checking it out @odiea !
