### ISSUE TITLE
[Bug]: Item add to Sale failed

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#4025]
### Bug Description?

Try adding an Item kit or Return on the Register.
Item add to Sale failed

### Steps to Reproduce?

Same as above

### Expected Behavior?

Item add to Sale failed should not fail

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.4

### What browsers are you seeing the problem on?

Firefox, Chrome

### Server Operating System and version

Wamp Server

### Database Management System and version

Mysql

### Web Server and version

Wamp Server

### System Information Report (optional)

This also shows on the Dev Demo

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Do you get this error `Amount Tendered must be a number. `?

**Comment by odiea** [comment]
CRITICAL - 2024-07-18 04:59:39 --> TypeError: App\Models\Sale::is_valid_receipt(): Argument #1 ($receipt_sale_id) must be of type string, null given, called in C:\newwamp\www\mymaster2\app\Controllers\Sales.php on line 153
[Method: GET, Route: sales/search]
in APPPATH\Models\Sale.php on line 427.
 1 APPPATH\Controllers\Sales.php(153): App\Models\Sale->is_valid_receipt(null)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Sales->getSearch()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sales))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))

or with a kit

CRITICAL - 2024-07-19 03:47:37 --> TypeError: App\Models\Item_kit::is_valid_item_kit(): Argument #1 ($item_kit_id) must be of type int, string given, called in C:\newwamp\www\master\app\Controllers\Sales.php on line 560
[Method: POST, Route: sales/add]
in APPPATH\Models\Item_kit.php on line 43.
 1 APPPATH\Controllers\Sales.php(560): App\Models\Item_kit->is_valid_item_kit('KIT 30')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Sales->postAdd()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sales))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))

**Comment by SteveIreland** [comment]
Based on my testing, it appears that the new "model()" function to create an empty class no longer has support for initializing individual fields the way that we were doing it.  I'm looking into it this morning.  I'm hopeful that the initialization is no longer required because that was always a nasty hack.

WARNING - 2024-07-21 08:51:46 --> [DEPRECATED] Creation of dynamic property App\Models\Item_quantity::$location_id is deprecated in APPPATH\Models\Item_quantity.php on line 76.
 1 APPPATH\Controllers\Items.php(756): App\Models\Item_quantity->get_item_quantity(3, 1)

**Comment by SteveIreland** [comment]
I made a handful of code changes that allowed me to add an item kit to a sale.  My test resulted in zero pricing, but I'm assuming for the moment that it was user error on kit setup.  I submitted the changes as a draft until I can do a little more testing this evening.

**Comment by SteveIreland** [comment]
The pull request is ready for review.
