### ISSUE TITLE
[Question] about input field borders.

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#4028]
On the main branch, the latest styling introduces an extremely light border around input capable fields.  For me, I cannot see them unless I squint and move my nose 2 inches from the screen.

Was this intentional?  Does everyone like this except me?  I personally fell it makes the screens difficult to use because before I can know what fields can be entered I have to start tabbing until I can see which fields are actually editable.

I'll be changing it on my fork, but I'll correct ospos instead if @jekkos wants that to happen.

**Comment by jekkos** [comment]
I wonder when that was introduced and in which file. Don't think this was intentional unless @objecttothis knows?

**Comment by objecttothis** [comment]
I didn't intentionally add it. Feel free to revert it to 3.3.9. Without before/after screenshots I can't say for sure which I prefer. You may be able to look at the blame to see introduced the change and ask them if it was intentional.

**Comment by odiea** [comment]
If you are asking about Register changes then this was the commit. https://github.com/opensourcepos/opensourcepos/commit/17908b55ef7e29bf070370f4a0dd6b856bade5db

**Comment by SteveIreland** [comment]
Okay, thanks.   I'll revert it back within the next few days.

**Comment by SteveIreland** [comment]
@odiea That commit overrode a few background colors, but it didn't affect the color of the borders.  The issue is that the default value for the border-color is coming from the current bootstrap theme.

I've noticed this misguided trend of "clean UI" by hiding stuff until the user focuses on it, but giving style over substance priority ain't what my clients want.

Someone may want to weigh in on this.  The choices are that I just darken up the default border to something usable, or I change the theme.   I would just prefer to darken up the border.  I'll look at what we had in 339 and if that doesn't clash with our new bootstrap theme then I'll use that.

**Comment by objecttothis** [comment]
I believe most of the app is running bootstrap 3 and that needs to be updated once this release is completed. In the meantime I recommend we change as little as possible to resolve the problem. Best in this case is using a different theme that isn't so annoying. If all the themes are affected then that is a different issue and increasing the contrast slightly may be needed.

**Comment by objecttothis** [comment]
I'll close for now, unless more discussion is needed.
