### ISSUE TITLE
[Bug]: Gift card search appears broken

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#4030]
### Bug Description?

Enter a gift card as payment in Sales. Card 101 only displays card 1.

### Steps to Reproduce?

Enter a gift card as payment in Sales. Card 101 only displays card 1.

### Expected Behavior?

Card search should display card 101 not 1.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.4

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

wamp Server

### Database Management System and version

mysql

### Web Server and version

Wamp Server

### System Information Report (optional)

 No error log displays. In network search does show it has issues.

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by objecttothis** [comment]
@odiea I can't replicate this on the development branch I'm working on now.  I wonder if this is specific to MySQL 8.4.  If it is, then my vote is to just get this release out with MySQL <= 8.3 support and then work on MySQL 8.4 support in a different release.  Any chance you can test it in 8.3 or lower to see if the error persists?

**Comment by objecttothis** [comment]
OK, it must have been introduced recently because I just changed to a new branch which has been rebased on the master and I can now replicate it.  I'll have to investigate it more after fixing the attributes problems.

**Comment by jekkos** [comment]
Fix is in master now.

**Comment by objecttothis** [comment]
odiea please tell me if you get this.  We are trying to troubleshoot why @WebShells isn't getting notifications to his email so I changed your repo permissions to the same as his (temporarily).  I want to see if you stop getting notifications.

**Comment by odiea** [comment]
Yes I did get this notification.

**Comment by jekkos** [comment]
Tested in master, works so will close.
