### ISSUE TITLE
[Bug]: Customer search in Register no longer works.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#4031]
### Bug Description?

Type a name into customer. The suggested name should show. Only suggested names in the limit now show

### Steps to Reproduce?

Type a name into customer. The suggested name should show. Only suggested names in the limit now show

### Expected Behavior?

Customer name should show in suggestions

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.4

### Server Operating System and version

Windows 10

### Database Management System and version

mysql

### Web Server and version

Wamp Server

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Fix in master now. Thanks @odiea !

**Comment by odiea** [comment]
It appears that getGet has been updated back to getPost

**Comment by jekkos** [comment]
so should it be reverted here?

**Comment by odiea** [comment]
That was what I used to get it to work for me.

**Comment by jekkos** [comment]
Fix pushed to master, verified working locally.
