### ISSUE TITLE
[Bug]: 20210422000000_database_optimizations.php migration fails on clean database

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#4033]
### Bug Description?

![image](https://github.com/user-attachments/assets/f4400e55-a434-4aed-8238-7eade186edf9)

I think getResultArray() is returning false on an empty result set rather than an empty array.

### Steps to Reproduce?

1. Create clean database using 3.4.0 database.sql
2. Login to run migration

### Expected Behavior?

Migration completes

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

Windows 11

### Database Management System and version

MySQL 8.2.0

### Web Server and version

Apache 2.4.58

### System Information Report (optional)

N/A

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by objecttothis** [comment]
It turns out that our only_full_group_by friend has struck again and it isn't an empty result set causing the problem.

![image](https://github.com/user-attachments/assets/29a321b3-3470-4dfc-8395-2e0959c22788)

The solution here is to separate the queries so that attribute_id doesn't appear in the first query.  Then in the foreach loop to write a sub query to get the attribute_id of the offending duplicate values.

**Comment by dch90** [comment]
I am attempting to build the project from scratch, and this particular migration fails when attempting to drop `person_id` indices.
Also fails when creating primary_key for `person_id`

**Comment by objecttothis** [comment]
> I am attempting to build the project from scratch, and this particular migration fails when attempting to drop `person_id` indices. Also fails when creating primary_key for `person_id`

This is resolved with [#4034](https://github.com/opensourcepos/opensourcepos/pull/4034/files) where I have created a delete_index() function which first checks to see if the index exists before trying to drop it.  

@SteveIreland I noticed earlier in your changes one of the inconsistencies that I'm seeing is that index name in some places is PRIMARY but in other places it's expecting the index name to be person_id.  On my current dev install, they are all called PRIMARY rather than person_id but in scripts it's looking to manipulate person_id.  It might be something to look into.

**Comment by objecttothis** [comment]
I think standard practice is PRIMARY

**Comment by objecttothis** [comment]
@SteveIreland I know you've been working on migration scripts so I'm hesitant to dive into it.  Let me know if you need any assistance/testing and what the status is on it.

**Comment by jekkos** [comment]
I have done some changes and testing on this. Still need to push those as a last diff between upgrade and clean install is still to be made.

**Comment by jekkos** [comment]
Could you explain why the drop index was needed in this script? I would only add changes in new scripts if they are required as this one is already included in older versions, which creates then different outcomes depending on the migration path.

**Comment by jekkos** [comment]
So my solution drops the index if it exists and creates a pk for person_id but it does this from a new script instead

**Comment by objecttothis** [comment]
The database.sql script creates these primary indexes and names them `person_id`
![image](https://github.com/user-attachments/assets/7d4b2745-547f-4512-bd3a-f77dbb7cd438)

There are two problems with that.  One is that standard practice is for the primary index to be named `PRIMARY`. There are descrepancies between some of the tables having this naming pattern (see below) and other's using the name of the column.

![image](https://github.com/user-attachments/assets/be484a6c-0e12-469c-ba90-3f68911f8561)

The second, I can't find the specific example, but I vaguely recall finding this out because I was getting errors where an index `PRIMARY` was expected but didn't exist because it was called person_id. Like I said, I can't find the example, so I may just be making it up too.

**Comment by objecttothis** [comment]
> So my solution drops the index if it exists and creates a pk for person_id but it does this from a new script instead. We should not edit any old migration scripts unless they prevent us from doing a clean install. Let me know if you guys agree on this.

Meaning the pk is called person_id?  Doesn't this undo the optimization script's renaming and reintroduce the inconsistency?

**Comment by jekkos** [comment]
So in case an existing migration crashes a clean install I would do minimal changes to make the upgrade work. In this case the drop statement can ve removed and any other modification goes into a new script

**Comment by objecttothis** [comment]
Sorry, I'm just catching up on all this.  Is the existing migration script crashing on a clean database? @dch90 posted that it crashes when trying to drop the index if it doesn't exist.  Is this what you're talking about?

**Comment by jekkos** [comment]
Correct now I can double check the primary key naming as you suggest. But this is handled in a new script. We should really freeze old scripts as much as possible as it will give us headache otherwise

**Comment by objecttothis** [comment]
agreed on freezing old scripts as much as possible.  You'll need to also remove the adding of the PK if you're removing the drop of the original PK.  The solution in the new script can be handled in the up() function by just doing a check to see if the PK called person_id on those tables exists and if so drop them and recreate them as `PRIMARY` rather than person_id.

**Comment by jekkos** [comment]
that seems to work fine as far as I can see now.

**Comment by jekkos** [comment]
All good for now, let's merge the open PR and be done with this.
One last remaining difference is that the upgraded version has two keys for company_name. Perhaps I can add a drop logic in the last script to get rid of the second one.
