### ISSUE TITLE
Slow invoice sending 

### ISSUE THREAD

**Issue by AHMEDabdamine** [opensourcepos/opensourcepos#4039]
When sending an invoice to an email it taaakes a loooots of time tondo it , it will be great if you can make it faster or make a queue system for sending emails

**Comment by jekkos** [comment]
I never experienced any slowness here.. The email is sent using ajax I believe, so it should not block the UI, only show a popup once the request is handled?

**Comment by AHMEDabdamine** [comment]
> I never experienced any slowness here.. The email is sent using ajax I believe, so it should not block the UI, only show a popup once the request is handled?

I don't know i think its my issue i run a weird configuration using the send mail service implemented on laragon portable web server , i dont know to how to make the sendmail function work properly without thr laragon server

**Comment by jekkos** [comment]
Not sure what sendmail has to do with laragon. Typically this is something that is setup by the PHP config . It's not really related to Ospos. Will close.

**Comment by AHMEDabdamine** [comment]
> Not sure what sendmail has to do with laragon. Typically this is something that is setup by the PHP config . It's not really related to Ospos. Will close.
It would be greate and helpful if you guys add the instruction for the mail conf  i mean there are but they are outdated and most of people cannot understand it or make it work , rather than this thanks guys for your work .

**Comment by jekkos** [comment]
I believe it uses standard CI email configuration.
