### ISSUE TITLE
[Feature]: Jetbrains license

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#4044]
### Type of Feature

✨ New Feature

### OpensourcePOS Version

opensourcepos 3.3.9

### Description

@jekkos I sent you an email and Element message about this, but you may not have seen it.  The Jetbrains OSS licenses expired.  I've submitted a renewal request to them for 3 licenses (@SteveIreland, @jekkos and @objecttothis).  I'm not aware of anyone else actively committing code to the repository.  Since I think you submitted the original request, I don't know if they will accept my renewal request.

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by objecttothis** [comment]
I got an email back saying that they would review the request within 2 weeks (ugh). I sent them an email per instructions to see if they could expedite.

**Comment by SteveIreland** [comment]
I don't need it.  Please give it to someone else.  I also use their IntelliJ product as part of my income producing job. So, for that reason I subscribe to the "All Products Pack" - it's also nice that I can use their tools to dabble in other languages in addition to Java and PHP.

**Comment by jekkos** [comment]
Ah great thanks for the renewal request @objecttothis . I just got back home from a couple of days off. Usuually they do reply in about a week or something. I planned to do it earlier but did not get to it yet.

I'll try to look into this db issue I have on the dev server this weekend.

**Comment by objecttothis** [comment]
I realized after that they do have a fallback version that can be used.
