### ISSUE TITLE
[Feature]: Multiple Branch 

### ISSUE THREAD

**Issue by 8521454900** [opensourcepos/opensourcepos#4046]
### Type of Feature

✨ New Feature

### OpensourcePOS Version

opensourcepos 3.3.9

### Description

Multiple Branch from main admin where inventory is same .One outlet option from where user can create their new branch and able to see all the sales and employee from admin login 

### Additional Information

UI is not good in sales 

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by jekkos** [comment]
Not very clear what the question is here.
