### ISSUE TITLE
Stock Quantity going in Minus

### ISSUE THREAD

**Issue by maazbinrizwan** [opensourcepos/opensourcepos#4052]
### Discussed in https://github.com/opensourcepos/opensourcepos/discussions/4051

<div type='discussions-op-text'>

<sup>Originally posted by **maazbinrizwan** August 30, 2024</sup>
In the sales view where  we scan any item and it is added to the card. When the stock is 0 it still adds it to the cart and from the inventory the item goes from 0 to -1. I want the functionality that when the item is 0 it cant be added to the cart with the message that stock is empty or something. I need this to implement in a project. Please help i have timeline.

![Screenshot 2024-08-30 114101](https://github.com/user-attachments/assets/7aac9f68-e7b5-4b70-aa92-591e78da5c84)
</div>

**Comment by nukerj** [comment]
En Sale_lib puedes adecuar la función de  agregar y editar para condicionar que no se ingresen items al carro de compras sino es mayor o igual a 1

**Comment by jekkos** [comment]
I believe there is a config that disallows negative stock values, you can enable that one.
