### ISSUE TITLE
[Bug]: Suppliers Detail Report 500 error with MySQL 5.7 - vs 3.3.9

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#4055]
### Bug Description?

HTTP Error 500 when using Suppliers Detail Report

ERROR - 2024-09-14 17:05:05 --> Query error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column '<removed>.ospos_sales_items_temp.sale_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by - Invalid query: SELECT `sale_id`, MAX(CASE
                        WHEN sale_type = 0 && sale_status = 0 THEN 'POS'
                        WHEN sale_type = 1 && sale_status = 0 THEN 'INV'
                        WHEN sale_type = 2 && sale_status = 1 THEN 'W/O'
                        WHEN sale_type = 3 && sale_status = 1 THEN 'Q'
                        WHEN sale_type = 4 && sale_status = 0 THEN 'RET'
                        WHEN sale_status = 2 THEN 'CNL'
                        ELSE ''
                        END) AS type_code, MAX(sale_status) as sale_status, MAX(sale_time) AS sale_time, MAX(name) AS name, MAX(category) AS category, MAX(item_number) AS item_number, SUM(quantity_purchased) AS items_purchased, SUM(subtotal) AS subtotal, SUM(tax) AS tax, SUM(total) AS total, SUM(cost) AS cost, SUM(profit) AS profit, MAX(discount_type) AS discount_type, MAX(discount) AS discount
FROM `ospos_sales_items_temp`
WHERE `supplier_id` = '1234'
AND `sale_status` = 0
AND   (
`sale_type` = 0
OR `sale_type` = 1
OR `sale_type` = 4
 )
GROUP BY `item_id`
ORDER BY `sale_id`
ERROR - 2024-09-14 17:05:05 --> Severity: error --> Exception: Call to a member function result_array() on bool /<removed>/ospos/application/models/reports/Specific_supplier.php 101

### Steps to Reproduce?

vs 3.3.9, but I see that current master (future 3.4) has the same issue but can't test
Set MySQL 5.7 with no backward compatibility
Reports -> Detailed Reports -> Suppliers; select any supplier and time range;  click Submit

### Expected Behavior?

Normal report like with the rest of Detail reports.

Lines

		$this->db->group_by('item_id');
		$this->db->order_by('sale_id');

Should be changed to

		$this->db->group_by('sale_id');
		$this->db->order_by('MAX(sale_time)');

That will fix the error.

### OpensourcePOS Version

opensourcepos 3.3.9

### Php version

Php 7.2

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Linux debain

### Database Management System and version

GCP SQLCloud MySQL 5.7

### Web Server and version

Apache 2.4

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Is this the specific_supplier report?

**Comment by jekkos** [comment]
@daN4cat we should probably search for other occurences of this issue also.
