### ISSUE TITLE
[Feature]: Having multiple outlet and inventory is same but other outlet have different stock and different employee and admin is able to see all the transaction from his login for other outlet     

### ISSUE THREAD

**Issue by 8521454900** [opensourcepos/opensourcepos#4062]
### Type of Feature

✨ New Feature

### OpensourcePOS Version

opensourcepos 3.3.9

### Description

Having multiple outlet and inventory is same but other outlet have different stock and different employee and admin is able to see all the transaction from his login for other outlet  

### Additional Information

One owner have more outlet and from one login owner wants to manage all the other outlet information 

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by jekkos** [comment]
#150 #1113
