### ISSUE TITLE
[Bug]: models/reports/Detailed_sales 500 Error

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#4064]
### Bug Description?

In the function getDataBySaleId, the query (select) where it's `sale_time as sale_time,`, should be `MAX(sale_time) as sale_time,`.

Throws an exception with MySQL 5.7.

### Steps to Reproduce?

Detailed_sales

### Expected Behavior?

No 500 error

### OpensourcePOS Version

opensourcepos 3.3.9

### Php version

Php 7.2

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Linux

### Database Management System and version

GCP CloudSQL MySQL 5.7

### Web Server and version

Apache 2.4

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Thanks for the report, fix in master.
