### ISSUE TITLE
[Bug]: Sale edit failure

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#4068]
### Bug Description?

Sales can currently not be edited in daily sales overview

### Steps to Reproduce?

Go to a sale, edit it and try to save

### Expected Behavior?

The modal disappears and changes are picked up correctly

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

Arch Linux 6.6 LTS

### Database Management System and version

MariaDB 10.5

### Web Server and version

Apache 2.4

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by odiea** [comment]
It appears that it needs post before the Save function and look for other issues after that

**Comment by odiea** [comment]
This is the next error.
CRITICAL - 2024-10-02 14:44:36 --> TypeError: prepare_decimal(): Argument #1 ($decimal) must be of type string, null given, called in C:\newwamp\www\master\app\Controllers\Sales.php on line 1593
[Method: POST, Route: sales/save/103]
in APPPATH\Helpers\locale_helper.php on line 713.
 1 APPPATH\Controllers\Sales.php(1593): prepare_decimal(null)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Sales->postSave(103)
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sales))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))

**Comment by odiea** [comment]
I also get the following but I think it was someone debug testing to see how this function works?

ERROR - 2024-10-02 15:03:19 --> SELECT `payments`.`sale_id`, SUM(CASE WHEN `payments`.`cash_adjustment` = 0 THEN `payments`.`payment_amount` ELSE 0 END) AS sale_payment_amount, SUM(CASE WHEN `payments`.`cash_adjustment` = 1 THEN `payments`.`payment_amount` ELSE 0 END) AS sale_cash_adjustment, GROUP_CONCAT(CONCAT(`payments`.`payment_type`, " ", (`payments`.`payment_amount` - `payments`.`cash_refund`)) SEPARATOR ", ") AS payment_type
FROM `ospos_sales_payments` AS `payments`
INNER JOIN `ospos_sales` ON `ospos_sales`.`sale_id` = `payments`.`sale_id`
WHERE `ospos_sales`.`sale_status` =0 AND `ospos_sales`.`sale_time` BETWEEN '2024-10-02 00:00:00' AND '2024-10-02 23:59:59'
GROUP BY `payments`.`sale_id`
ERROR - 2024-10-02 15:03:19 --> SELECT `payments`.`sale_id`, SUM(CASE WHEN `payments`.`cash_adjustment` = 0 THEN `payments`.`payment_amount` ELSE 0 END) AS sale_payment_amount, SUM(CASE WHEN `payments`.`cash_adjustment` = 1 THEN `payments`.`payment_amount` ELSE 0 END) AS sale_cash_adjustment, GROUP_CONCAT(CONCAT(`payments`.`payment_type`, " ", (`payments`.`payment_amount` - `payments`.`cash_refund`)) SEPARATOR ", ") AS payment_type
FROM `ospos_sales_payments` AS `payments`
INNER JOIN `ospos_sales` ON `ospos_sales`.`sale_id` = `payments`.`sale_id`
WHERE `ospos_sales`.`sale_status` =0 AND `ospos_sales`.`sale_time` BETWEEN '2024-10-02 00:00:00' AND '2024-10-02 23:59:59'
GROUP BY `payments`.`sale_id`

**Comment by jekkos** [comment]
Fix in master
