### ISSUE TITLE
[Bug]: Tax issue in Expenses when Creating new or updating old.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#4075]
### Bug Description?

Create a new Expense. Tax amount is not working until it is removed. Try updating a form and the same issue shows. 

### Steps to Reproduce?

Create a new Expense. Tax amount is not working until it is removed. Try updating a form and the same issue shows.  Checknumeric tax displays false.

### Expected Behavior?

Tax amount should not be required and displays false when an amount is added.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.3

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Wamp Server

### Database Management System and version

Mysql 8.2.0

### Web Server and version

Wamp Server

### System Information Report (optional)

Not Available. This is not  optional anymore?

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Its a problem with checkNumeric I believe. I have also experienced it in other forms.

**Comment by jekkos** [comment]
Did some small improvements for supplier selection in master
