### ISSUE TITLE
[Bug]: Attribute Visibility Column in Attributes view not accurate

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#4081]
### Bug Description?

When the attribute "Attribute Visibility" multi-select has all options removed it successfully saves the values
![image](https://github.com/user-attachments/assets/38f53fd7-c476-4032-adea-d4c87bf2aef8)

But even after refreshing the table column for attribute table visibility still shows it displaying in all three locations.
![image](https://github.com/user-attachments/assets/937e64b9-3760-46c5-892d-c9f99c572a80)

### Steps to Reproduce?

1. Fresh database
2. Add an attribute
3. Modify the "Attribute Visibility"
4. Click "Submit"

### Expected Behavior?

The table would show the accurate information related to the attribute

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

Windows 11

### Database Management System and version

MySQL 8.2.12

### Web Server and version

Apache 2.4.58

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Did a fix for this, seems fine locallty. Pushed it to master

**Comment by odiea** [comment]
Works great. Thanks
