### ISSUE TITLE
[Bug]: Validation is broken in item creation

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#4082]
### Bug Description?

If you create a new item but forget required fields the submit button does not allow clicking even when the fields are corrected.
![image](https://github.com/user-attachments/assets/7de4148a-5886-4775-922d-df8758c29991)

### Steps to Reproduce?

1. Create new item
2. Omit Wholesale Price, Retail price and quantity stock.
3. Click Submit

After getting the errors if you update the values, only the quantity stock validation message disappears, but the price validation messages do not.

### Expected Behavior?

This is also a secondary problem, but 0.00 price wholesale and retail values should be allowed.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

Windows 11

### Database Management System and version

MySQL 8.2.12

### Web Server and version

Apache 2.4.58

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Thanks for the report, this is due to my changes in checkNumeric
