### ISSUE TITLE
[Bug]:  FILE  database/database.sql  is MISSING

### ISSUE THREAD

**Issue by Giuliano69** [opensourcepos/opensourcepos#4083]
### Bug Description?

For a NEW INSTALL o master version:
the install.md file states to run the database.sql file.
BUT The FILE  (nowadays) does NOT EXIST  in the directory structure. Maybe it is an OLD name ?

Which file/files  are we supposed to use ?

1- I found two files:    opensourcepos/app/Database/tables.sql and constrains.sql
Do we need BOTH ?
Are the install.md instructions supposed to be updated?

2- in the same directory above, it is found the bash script resetdatabase.sh.
The last line of the script is calling a mysql command from root:
mysql -u root -p"$mypassword" -e "USE ospos; source $script.sql;"

Here the $script bash variable should be evaluated as  “migrate_phppos” or (again) “database”, BUT both of them are NOT present in the directory.

### Steps to Reproduce?

Check 
https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md
app/Database directory 

### Expected Behavior?

the database.sql file should be provied,
OR the install.md and bash script be updated with new name/names.

### OpensourcePOS Version

opensourcepos 3.3.9

### Php version

Php 8.3

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

Ubuntu 22.04

### Database Management System and version

Mysql

### Web Server and version

Apache

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by odiea** [comment]
It will show up after you build this version. Otherwise download an earlier version.

**Comment by Giuliano69** [comment]
thanks Odie.
AT first I Downloaded 3.3.9: here , the database  folder exist in the zip...
 BUT as it does not work with PHP 8.3 I  downloaded master branch (3.4) in the hope it will work with PHP 8.3

Problem with database.sql:
 AFTER having unzipped and copied the master and  run from  the  folder  var/www/html the following commands:
sudo -u www-data composer install
sudo -u www-data npm install
sudo -u www-data  npm run build 

the /database directory is  NOT created.

The folder from which the command is run seem right. The command "composer install" will create the "vendor"  folder aside to the app directory, as  expected as in the 3.3.9 version. 

BUT the npm run build is NOT creating  any database.sql file.

I'm following build.md.
Is there another file to follow ?

BR

**Comment by odiea** [comment]
3.3.9 is php 7.3 or 7.4
Master for the current version that uses php 8.3
composer install
npm ci
npm run build

**Comment by Giuliano69** [comment]
Thanks
tested with
npm ci
BUT same result: database directory&database.sql not created  (ci== code igniter??)

PLEASE confirm that the database file is expected to be created from npm run build.

PS
the command su - www-data npm ci
is intended to be run directly from var/www/html, that normally is owned only by www-data (in Ubuntu). So the user change is necessary in running the command.

PPS
the new directory structure in 3.4  seems different in many dir from 3.3.9:
application (old name) -> app (new 3.4)
sub dir in lower case (old name) -> subdir in Camel case (new)
...
and of course ...
non database directory and database.sql... .-))

**Comment by odiea** [comment]
It should be in app/database if it is not there after you build it then use this one.
[database.zip](https://github.com/user-attachments/files/17217720/database.zip)

**Comment by jekkos** [comment]
you need to run gulp after npm

**Comment by Giuliano69** [comment]
from  the CLI...
 the command "gulp" get the exact same result as  "npm run build".
