### ISSUE TITLE
[Feature]: Detailed Reports of Receiving

### ISSUE THREAD

**Issue by jeetdebnath** [opensourcepos/opensourcepos#4084]
### Type of Feature

✨ New Feature

### OpensourcePOS Version

opensourcepos 3.3.9

### Description

Is there any way to get reports of RECEIVED items in details, Like item wise,  category wise, etc

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by jeetdebnath** [comment]
Kindly help with some codes or ways to get the reports

**Comment by jekkos** [comment]
I believe there is a detailed receivings report already, no?

**Comment by jeetdebnath** [comment]
Yes there is detailed report there is only one option of showing total of receiving with date range. is it possible to get item wise, category wise, just like sale summary section has ITEM option.
