### ISSUE TITLE
[Bug]: No customer,supplier or employee tables display

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#4086]
### Bug Description?

Go to Customers, Suppliers or Employees. Tables should show info. None shown.

### Steps to Reproduce?

Same as above

### Expected Behavior?

Tables to show names.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.4

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

win 10

### Database Management System and version

mysql

### Web Server and version

Wamp Server

### System Information Report (optional)

$sort = $this->sanitizeSortColumn(CUSTOMER_HEADERS, $this->request->getGet('sort', FILTER_SANITIZE_FULL_SPECIAL_CHARS), 'person_id');
		Reverting this the tables now show.
ERROR - 2024-10-02 17:50:10 --> mysqli_sql_exception: Column 'person_id' in order clause is ambiguous in 

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by odiea** [comment]
I added people to people.person_id and now the tables show

**Comment by jekkos** [comment]
Ouch ok did not test this thoroughly, thanks for the effort here!

**Comment by jekkos** [comment]
Pushed a fix to master
