### ISSUE TITLE
[Bug]: File not found 

### ISSUE THREAD

**Issue by UbuntuEvangelist** [opensourcepos/opensourcepos#4098]
### Bug Description?

I am using LEMP Stack. After setup i see File not found

### Steps to Reproduce?

check php and update composer and restart NGINX

### Expected Behavior?

 File not found 
![Screenshot from 2024-10-27 03-50-56](https://github.com/user-attachments/assets/c703338f-899b-466a-aa13-01fde835ac98)

### OpensourcePOS Version

opensourcepos 3.3.9

### Php version

Php 8.3

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Ubuntu 20

### Database Management System and version

MariaDB

### Web Server and version

NGINX

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
3.3.9 does not work with php8.3 . you should try latest master, but it needs to be built from scratch.

**Comment by UbuntuEvangelist** [comment]
> 3.3.9 does not work with php8.3 . you should try latest master, but it needs to be built from scratch.

now i am using PHP 8.2.25 and master branch but now i see Whoops!
We seem to have hit a snag. Please try again later...
![Screenshot from 2024-11-02 22-48-36](https://github.com/user-attachments/assets/c086d2f5-ec08-41c4-bc27-7d5f6b7ffb8c)

**Comment by jekkos** [comment]
php 8 build is available now in release section. Mind that this is not final 3.4 yet, there's still at least one bug to be fixed.
