### ISSUE TITLE
[Bug]: Class Attribute already exists and doesn't extend CI_Model

### ISSUE THREAD

**Issue by letitiakayw** [opensourcepos/opensourcepos#4100]
### Bug Description?

Using: 
PHP 8.1
MariaDB 10.11 Standard
Version: opensourcepos.3.3.9.c00ff2 (not the development version)

I am getting this error below on loading, which I have seen on a closed issue from back in December. This version INSTALL file says it **won't** run on PHP 8, but the development page for this version says it will run on 8.1. Is there a difference between the development version and the latest non-development version and can I get something to work if there is? I apologize if I am wasting your time.

```
An uncaught Exception was encountered
Type: RuntimeException
Message: Class Attribute already exists and doesn't extend CI_Model
Filename: /homepages/2/d184897015/htdocs/apl-wordpress/rereads_point_of_sale/vendor/codeigniter/framework/system/core/Loader.php
Line Number: 353
Backtrace:
File: /homepages/2/d184897015/htdocs/apl-wordpress/rereads_point_of_sale/public/index.php
Line: 315
Function: require_once
```

### Steps to Reproduce?

I have set up the database and altered all the database and config files as needed. 

### Expected Behavior?

Load the login page at mysite/public/

### OpensourcePOS Version

opensourcepos 3.3.9

### Php version

Php 8.1

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

Linux shl-buildd-bs02 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC 

### Database Management System and version

MariaDB 10.11

### Web Server and version

Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux 

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Hi, current master should be in a decent state and working with php8. There is currently however no build available with all files in it. Ill try to fix that perhaps this weekend.

**Comment by jekkos** [comment]
You can try to build from the repo directly but you will need some tools.

**Comment by odiea** [comment]
Does not support php 8 versions.

**Comment by letitiakayw** [comment]
Thank you for your replies!
