### ISSUE TITLE
[Feature]: Support for Variable Weight Products (e.g., kg)

### ISSUE THREAD

**Issue by eltan148** [opensourcepos/opensourcepos#4105]
### Type of Feature

✨ New Feature

### OpensourcePOS Version

opensourcepos 3.3.9

### Description

Feature Request Description

We would like to request a new feature to support products sold by weight in the OSPOS system. Specifically, it would be ideal if the system could allow entry of the price per kilogram or other weight unit (e.g., grams, pounds) and automatically calculate the total price based on the specific weight sold.

Details and Example:

Suppose 1 kilogram of apples costs 2500 pesos.
A customer buys 1.2 kg of apples. The system should allow entry of the specific weight (1.2 kg) and calculate the total price as 3000 pesos (2500 x 1.2).
Desired Functionality:

Add an option in product settings to mark an item as "sold by weight."
Allow entry of a variable weight at the point of sale (e.g., 1.2 kg).
Calculate the total price based on the unit weight price and the entered weight.
Display the weight and calculated price on the customer's receipt.
Motivation This feature would benefit businesses that sell products by weight, such as produce markets and butcher shops, improving both accuracy in sales and customer experience.

Thank you for considering this enhancement request.

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by odiea** [comment]
I believe that has already been added in configuration/barcode input formats. You will have to search on how to set that up.

**Comment by jekkos** [comment]
This is the actual wiki page: https://github.com/opensourcepos/opensourcepos/wiki/Weighted-Barcodes
