### ISSUE TITLE
[Bug]: remove customer button on register

### ISSUE THREAD

**Issue by tmn14** [opensourcepos/opensourcepos#4113]
### Bug Description?

When you are at the checkout and add a customer , the remove customer button does not remove the customer . sometimes after a few clicks on the button it removes the customer and sometimes dosent

### Steps to Reproduce?

enter sales
select customer or add new
click the remove client button

### Expected Behavior?

remove the customer on first click

### OpensourcePOS Version

opensourcepos 3.3.9

### Php version

Php 7.4

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

linux rocky 9

### Database Management System and version

mariadb 10

### Web Server and version

apach 2

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by objecttothis** [comment]
This is working properly in the current master, so it will be fixed in 3.4.0 assuming it is indeed a bug and not a configuration issue.
