### ISSUE TITLE
[Bug]: Error "HTTP ERROR 500" when installing Opensourcepos version 3.4

### ISSUE THREAD

**Issue by hiendd89** [opensourcepos/opensourcepos#4114]
### Bug Description?

I am using MAM Pro to install the latest Opensourcepos version 3.4 and I get the error "HTTP ERROR 500". Can anyone show me how to configure this version?

Thanks a lot!!!

### Steps to Reproduce?

- Installation directory: Mac/Users/mac/Sites/opensourcepos
- PHP Version: 8.1.13

### Expected Behavior?

Fix error 500

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.1

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

MAM Pro

### Database Management System and version

5.2.0

### Web Server and version

8.1

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by odiea** [comment]
You have to build 3.4 before it will work. Read the readme.
