### ISSUE TITLE
[Bug]: Error Editing Item when changing quantity

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#4115]
### Bug Description?

![image](https://github.com/user-attachments/assets/173ce763-20e7-4145-8569-e7029e2a4503)

### Steps to Reproduce?

1. Go to sales register.
2. Add an item.
3. Change quantity.
4. Tab.

### Expected Behavior?

Quantity to change without error.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.2

### What browsers are you seeing the problem on?

Firefox

### Server Operating System and version

Windows 11

### Database Management System and version

MySQL 8.2.12

### Web Server and version

Apache 2.4.58

### System Information Report (optional)

OSPOS Installation Info: 3.4.0-dev - dev
Language Code: en

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓
» Xml: Enabled ✓

User Configuration:
.Browser: Firefox 133.0
.Server Software: Apache/2.4.58 (Win64) OpenSSL/3.1.3 mod_fcgid/2.3.10-dev
.PHP Version: 8.2.12
.DB Version: 8.2.0
.Server Port: 80
.OS: Windows NT 10.0

.OS Time Zone: Asia/Baku
.OSPOS Time Zone: Asia/Baku

File Permissions:
» [writeable/logs:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [writable/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable or Incorrect Permissions ✗
» [importCustomers.csv:] - 0666 | Readable ✓ | Vulnerable or Incorrect Permissions ✗

Security Vulnerability Warning
Incorrect permissions leaves this software at risk.

» [writeable/logs:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [writable/uploads:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [writable/uploads/item_pics:] is writable, but the permissions are incorrectly set. Please set it to 750 and refresh.
» [importCustomers.csv:] is readable, but the permissions are incorrectly set. Please set it to 640 or 660 and refresh. 

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by objecttothis** [comment]
No logs are made with this error.  We might need to add that.  This happens in the Sales Controller's postEditItem() function when validation fails.

**Comment by objecttothis** [comment]
OK, so this issues is caused by the locale using commas as the decimal separator for price, quantity and discount percent.  This is the reason that the rules fail.  The solution to this is custom rules.  In app/Config/Validation/OSPOSRules.php we have a decimal_locale custom rule and it needs to be used any place we would normally use the `numeric` rule during validation.  This is because `numeric` will fail if the locale uses a comma for decimal separator.  @jekkos I suspect you might run into this as you are looking at validation issues.

**Comment by objecttothis** [comment]
![image](https://github.com/user-attachments/assets/5df736fe-ec43-47bb-957f-bd0fa3e32527)

**Comment by jekkos** [comment]
I have applied this fix also to receivings

**Comment by objecttothis** [comment]
> I have applied this fix also to receivings

Thanks.  I did a search of the code at the time but for some reason it didn't show up in my searches. This will also be useful to keep in mind for adding validation in the future.
