### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by ohitsgian** [opensourcepos/opensourcepos#4123]
Hi! Im trying to install and use this pos system but i have windows. Im trying to use Visual Studio and VS code but i am not getting any luck and I'm an entry level software developer. Any help would be greatly appreciated.

**Comment by andriux1990** [comment]
Use Linux

**Comment by objecttothis** [comment]
> Hi! Im trying to install and use this pos system but i have windows. Im trying to use Visual Studio and VS code but i am not getting any luck and I'm an entry level software developer. Any help would be greatly appreciated.

@ohitsgian you need to run a webserver and PHP stack.  I use Windows in development and find Laragon to be my favorite for managing Apache, PHP and MySQL (or MariaDB).  https://laragon.org/download/

You'll need to download the latest release (3.3.9) and follow the installation instructions.  If you get stuck, you'll need to submit an issue and include more information about exactly where you are stuck.

> Use Linux

@andriux1990 if Windows is a supported OS, then that's not going to help @ohitsgian
