### ISSUE TITLE
[Bug]: Total Payment is sometimes multiplied by 2 from the total transaction price

### ISSUE THREAD

**Issue by mnasruul-xxi** [opensourcepos/opensourcepos#4124]
### Bug Description?

Hi, I have added payment option in get_payment_options function in helpers/locale_helper.php file, `$payments['QRIS'] = 'QRIS';`, lately there is a problem, total payment is doubled from total transaction, is there any suggestion to add this payment option?

### Steps to Reproduce?

I updated the manual into the ospos_sales_Payments table

### Expected Behavior?

it shouldn't have happened like this

### OpensourcePOS Version

opensourcepos 3.3.9

### Php version

Php 7.4

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

docker base image php:7.4-apache

### Database Management System and version

docker base image mariadb:10.5

### Web Server and version

i dont kno

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Thjs is an issue report for something that is not in our codebase. Will close.
