### ISSUE TITLE
[Bug]: Takings or Daily Sales in Register 

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#4125]
### Bug Description?

![2024-11-26 04_23_43-Window](https://github.com/user-attachments/assets/cb79e51d-fac1-4c1c-bc22-5af55b064301)

### Steps to Reproduce?

Complete a Sale then go to Takings

### Expected Behavior?

Table headers should not show &nbsp.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.3

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Windows

### Database Management System and version

Mysql

### Web Server and version

Wamp Server

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Fix in master now.

**Comment by odiea** [comment]
Works great. Thanks
