### ISSUE TITLE
[Bug]: Issue generating a Quote

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#4126]
### Bug Description?

![2024-11-27 09_11_00-Window](https://github.com/user-attachments/assets/df7522be-d60a-4462-bf76-7565825d05f9)

### Steps to Reproduce?

Create a Quote .

### Expected Behavior?

Quote number should appear on the quote not the date as shown

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.4

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Windoes 10

### Database Management System and version

Wamp Server

### Web Server and version

Wamp Server

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Fix in master now.
