### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [opensourcepos/opensourcepos#4127]
### Bug Description?

Dear @opensourcepos team, @jekkos,

Can you remove old tabs:
- https://sourceforge.net/p/opensourcepos/discussion/
- https://sourceforge.net/p/opensourcepos/_list/tickets
- https://sourceforge.net/p/opensourcepos/wiki/
- Donate link

Update the links to have the good place: https://github.com/opensourcepos/opensourcepos
- "Open Source Point of Sale Web Site"
- https://sourceforge.net/projects/opensourcepos/support

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/opensourcepos/

To disable/delete tabs, go here: https://sourceforge.net/projects/opensourcepos/
To add a new tab, go here: https://sourceforge.net/projects/opensourcepos/
To change informations, go here: https://sourceforge.net/p/opensourcepos/admin/overview
To export, go here: https://sourceforge.net/p/opensourcepos/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/opensourcepos/admin/overview
- A new tab, go here: https://sourceforge.net/projects/opensourcepos/

Thanks in advance.

### Steps to Reproduce?

Read before.

### Expected Behavior?

Read before.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.4

### What browsers are you seeing the problem on?

Other

### Server Operating System and version

*

### Database Management System and version

*

### Web Server and version

*

### System Information Report (optional)

Read before.

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by objecttothis** [comment]
@jekkos I don't have access to the sourceforge profile, so I can't really do any of this.  I don't know if we want to keep maintaining that but probably should update it if we do.

**Comment by jekkos** [comment]
Will need to reset my access to this, I used this with a hotmail account that I did not open for a while

**Comment by jekkos** [comment]
I have reset my access and marked the project as inactive. There should be a direct link to this repo now.

**Comment by Neustradamus** [comment]
@jekkos: Thanks! :)

Can you remove last old parts here:
- https://sourceforge.net/p/opensourcepos/_list/tickets

You can export before.

Thanks in advance.

**Comment by Neustradamus** [comment]
@jekkos: I wish you a Happy New Year 2025!

Have you seen my previous comment?
