### ISSUE TITLE
[Bug]: Disappearing Avatar in Items 

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#4128]
### Bug Description?

Edit a form in Items. Add an Avatar. Save form. Go back to edit form then save. Avatar is somehow removed.

### Steps to Reproduce?

Same as above

### Expected Behavior?

Avatar should remain in form and Table views

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.3

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Windows 10

### Database Management System and version

Mysql

### Web Server and version

Wamp Server and online Dev demo

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Tested this locally, fix in master now
