### ISSUE TITLE
[Feature]: hide the cost price and profit in reports by default at least on that browsers like in items as store in localStorage.

### ISSUE THREAD

**Issue by bhojkamal** [opensourcepos/opensourcepos#4130]
### Type of Feature

✨ New Feature

### OpensourcePOS Version

opensourcepos 3.3.9

### Description

**Problem Statement**
When clients or customers (even friends) view reports, they can see the exact cost price and profit. For business reasons, it is not ideal to show this information to customers, as it might affect the relationship, even if the customer is a friend.

**Proposed Solution**
By default, hide the cost price and profit columns in reports. This way, we can view the report in front of the customer and even print it for them without showing sensitive financial details.

Currently, we can untick the cost and profit columns using the dropdown header, but these settings reset upon refresh.

Implement a feature to store the visibility settings of these columns in the browser's localStorage, similar to how items are managed. This way, the columns will remain hidden even after a page refresh, unless localStorage is cleared via web browser dev tools—a step most users won't perform.

**Request for Assistance**
If this feature can be added, it would greatly enhance user experience and business confidentiality. If there are suggestions on where to modify the code to achieve this, I am willing to implement it myself.
Thank you.

### Additional Information

![profit hiding option required-unckeck by default](https://github.com/user-attachments/assets/f07dd318-ccaf-482e-86fc-81bd7b4e426b)
![profit hiding option required](https://github.com/user-attachments/assets/f5694e35-38bd-456c-960b-8e3aeee7ae24)

### Verify you searched open requests in OpensourcePOS

- [X] I agree I have searched Open Requests

**Comment by jekkos** [comment]
Hi this should not be very hard as there is already an example in manage_tables.js. You can check the `onColumnSwitch` function in the bstables configuration in that file. This is what needs to go into the table init for the reports. Also the `toggle_column_visibility` function can then be reused to set the correct table state after init.

**Comment by jekkos** [comment]
If you do this improvement then please submit it also as a PR, contributions are welcomed!

**Comment by bhojkamal** [comment]
Okay, I got it. I have changed on on ci3 or version 3. when version 4 releases, I will add it to the live too.
