### ISSUE TITLE
[Bug]: Config/General will not save Category as a dropdown.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#4134]
### Bug Description?

CRITICAL - 2024-12-16 03:35:28 --> TypeError: CodeIgniter\Database\MySQLi\Connection::insertID(): Return value must be of type int, string returned
[Method: POST, Route: config/saveGeneral/]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 594.
 1 APPPATH\Models\Attribute.php(550): CodeIgniter\Database\MySQLi\Connection->insertID()
 2 APPPATH\Controllers\Config.php(404): App\Models\Attribute->save_definition([...], '-1')
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Config->postSaveGeneral()
 4 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Config))
 5 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))

### Steps to Reproduce?

Enable Dropdown as a Category

### Expected Behavior?

Enable Dropdown as a Category should be saved.

### OpensourcePOS Version

development (unreleased)

### Php version

Php 8.4

### What browsers are you seeing the problem on?

Chrome

### Server Operating System and version

Windows 10

### Database Management System and version

Mysql

### Web Server and version

Wamp Server

### System Information Report (optional)

System Information Report

### Unmodified copy of OpensourcePOS

- [X] I agree this copy has not been modified

**Comment by jekkos** [comment]
Should be fixed in master now. For some reason the CI crashed on retrieving the last inserted ID, which can be an int or string. In this case it was a string but it expected an int. I use a method now that checks the type of the variable behind this function first before returning it. Changed this in all the models as the issue might have been elsewhere as well.
