### ISSUE TITLE
Beginning of day Cash entry.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#440]
When the Sales register is first opened it would be nice to have a form to add the beginning of day cash that's in the register.

**Comment by daN4cat** [comment]
Yep, that's what my wife told me as well. She asked me if I could add.
Maybe suggest at the beginning of the day what was at closing time than previous day.

**Comment by odiea** [comment]
Yes. That is what my wife did at her Thrift Store. A like amount was added to the Beginning of Day.

**Comment by odiea** [comment]
We were not terrible concerned about how many coins or bills were entered just the total amount in the till that morning.

**Comment by daN4cat** [comment]
Yes, the same here.

I'll check what is coming from this cash up feature and branch.

**Comment by daN4cat** [comment]
As reference, https://github.com/KotieSmit/opensourcepos/commits/features has a cashup feature that is implementing this one most likely.

**Comment by jekkos** [comment]
will source that repo now and check it out

**Comment by alvin101** [comment]
Where I come from we call this till reconciliation.  I have yet to see a POS do a good job of this.

**1.  Opening Balance** You come in the morning open the till and count the money, you have 3 tills with dual currency.  Is the count the same as closing of last night, was money missing in the night, was there human error?

**2. Cash Movement** You make sales, you buy toilet paper and pay the window cleaning boy (petty cash expense) expenses must be added to your accounting system as well as calculated in till reconciliation.

**3. Closing** you count the money and do the till reconciliation, do the sales and expense add up? Was a clerk dishonest or make mistakes? 

This can be quit complicated with multi currency multi location business.

**Comment by daN4cat** [comment]
It's the same in my wife's shop. The problem with OSPOS would be to add the notes or justification for the difference. It has to become a journal to log things.

**Comment by alvin101** [comment]
I think the (journal to log things) belongs in back office, most accounting systems have a Memo column.

**Comment by ishtiaquesarwar** [comment]
what's the progress here?

**Comment by daN4cat** [comment]
@ishtiaquesarwar no progress as it needs somebody to take and implement it.

**Comment by HamidCh** [comment]
How Does KotieSmit's Cashup Module Work? I have Downloaded his Source But Can't find a way to use cashups

**Comment by daN4cat** [comment]
My mind went blank, what's KotieSmith?

**Comment by odiea** [comment]
6th comment down from top .You referred to it but apparently he never finished or submitted it.

**Comment by daN4cat** [comment]
Ha ha and it was even a comment I posted.... most likely that code works on an old version of OSPOS, maybe even 2.4. We never checked that code and migrated to 3.x. We need a brave developer to take it and upgrade it to the latest and contribute it back

**Comment by odiea** [comment]
I downloaded it and tried it but it appears nothing works as far as the cashup feature is concerned. You even need to add the module into modules and setup permissions and grants.

**Comment by daN4cat** [comment]
#1235 is part of this work.

**Comment by odiea** [comment]
When I looked at this it appeared to be more of an Invoice or sale reconciliation.

**Comment by daN4cat** [comment]
I guess that setting the start of the day cash at till position, take the sale transaction and the expenses we should be good to give an end of the day report.

It's a journal / log thing. It probably needs one database table and a means to record start of the day and end of the day. Something like that....

@SteveIreland any view on this story?

**Comment by odiea** [comment]
I think what we need first would have the ability to have employees be able to log in or out without closing the program.
Admin logs in to open the program then an Employee logs in as a user. That way if a Sale has issues a manager or admin can log in without losing the Sale. Any thoughts?

**Comment by daN4cat** [comment]
#2131 is the other part of this discussion.

**Comment by daN4cat** [comment]
As described in #2131:

The idea of cashup module is to mainly keep track of the cash in your drawer at opening and closing time.
So the entry needs to be created first thing in the morning, stating the opening cash position.
If during the day cash is added/removed out of the sales it should be added to the in/out field in the form, and it's better to add a note in the description to say what was that about.

At closing time the closed cash line needs to be added and adding the other payments should give a total matching the total of the day taken the expenses.

The checkbox notes is to say whether the cash has banknotes, just a memory note.

**Comment by daN4cat** [comment]
Probably we are good with this feature after the expenses and cashup.

**Comment by nathanzky** [comment]
Due is deducted twice from the transfer cash it display in correct data compare to daily sales.
I modified some codes to add Dues into the Cashup module in order to have correct cash on drawer. 

![cashup_update](https://user-images.githubusercontent.com/26484936/46076412-87139080-c19e-11e8-9d83-d8ad2ce1dcb9.JPG)

**Comment by HamidCh** [comment]
Is Day opening cash is added to the OSPOS?

**Comment by nathanzky** [comment]
@daN4cat  I have submitted the fixes on #2131

**Comment by nathanzky** [comment]
@daN4cat  I  forgot the closed amount due to be added on the cashup table... I am grateful to contribute on this project.. :-)

**Comment by daN4cat** [comment]
Ok, I'll check that.

**Comment by daN4cat** [comment]
@nathanzky I checked and everything looks fine. not sure if there was some more problem but my fix to the ajax solved the totals in the form. Probably it's what you meant and I misread.

**Comment by nathanzky** [comment]
@daN4cat I mean I forget to mention additional database field for cashup table. I check the master and works well..

**Comment by daN4cat** [comment]
Good

**Comment by HamidCh** [comment]
Is Day Beginning Cash Module is added to the OSPOS or not? If any help is needed I am available.

**Comment by daN4cat** [comment]
@HamidCh the Cashup module is part of the vs 3.3.0. Current code in master.
If there is any addition you would like to see, you are welcome to contribute! Thanks :-)
