### ISSUE TITLE
Cost Price and Unit Price

### ISSUE THREAD

**Issue by bkrajendra** [opensourcepos/opensourcepos#547]
As i understand cost_price is purchase price and unit_price is selling price.
Then why in receiving process we are doing it wrong. check line no - 87 in Receiving model

``` php
'item_cost_price' => $cur_item_info->cost_price,
'item_unit_price'=>$item['price'],
```

here $item['price'], is obtained from receiving cart which is basically cost_price. And its being assigned to unit price. Is this a bug or I'm missing something.

**Comment by tanakornp** [comment]
As I understand,
'item_cost_price' and 'item_unit_price' is temp table using in receiving process.
Coincidentally, item_cost_price is use data from opos_items.cost_price so it is the same thing
however, 'item_unit_price' is not using any data from opos_items. It is the cost of item in current receiving.

**Comment by bkrajendra** [comment]
@tanakornp why we need these two fld in this receivings_items and why the confusing names.
item_cost_price gets the old cost from items table and item_unit_price gets the new entered cost.
Whats the purpose?

**Comment by tanakornp** [comment]
'item_unit_price'=>$item['price']  is clearly essential as the item cost may change each receiving. 
We do need both those to field to calculate the average cost.

```
			// update cost price, if changed AND is set in config as wanted
			if($cur_item_info->cost_price != $item['price']
					AND	$this->config->item('receiving_calculate_average_price') != FALSE)
			{
				$this->Item->change_cost_price($item['item_id'],
												$items_received,
												$item['price'],
												$cur_item_info->cost_price);
			}
```

**Comment by bkrajendra** [comment]
@tanakornp 
Sorry for this but can u clarify!
1) Do u mean here item_cost_price is old cost from item table and 
item_unit_price is new cost got through receiving.?
2) Why r we maintaining 2 cost. As I can see both in receive receipt and sale receipt they get the cost and selling price data from item table. so in which case receivings_items table cost r used?

3) If I have 2 item in stock with price MRP 30 and then I add another 2 with MRP 40. how things work.? 
4) Same thing with purchase cost. how to deal with changed purchase cost. I dont want averaging as i dnt understand it. purchase costs are mostly fixed by  vendors and you can not change it unless they change it.

**Comment by daN4cat** [comment]
Is this a bug in the end?

**Comment by odiea** [comment]
An easy way to change the cost price is place a check into calc average price. Then go into models/receiving and change the function so it looks like this. It works for me. Dont forget to refresh Receivings after you do this.
$this->Item->change_cost_price($item['item_id'],
												$items_received,
												$item['price'],
												$item['price']);
