### ISSUE TITLE
Shipping Enhancement Feature (Contribution)

### ISSUE THREAD

**Issue by MiiCode2** [opensourcepos/opensourcepos#592]
I have downloaded the OSPOS system and I am currently adding the ability for shipping products.

I have added the icon for this and I have been working on some code.
![screen shot 2016-05-24 at 3 09 06 pm](https://cloud.githubusercontent.com/assets/6429840/15519971/343d8bba-21c1-11e6-9244-c99e96ec111c.png)

I think it's best to have a delivery checkbox beside each sales item (that requires delivery) and then when the sale is complete have a delivery ticket produced under the shippings icon that can be edited to add shipping information and then print the delivery ticket or should we have a separate tab for shipping information for the customers?

I am also thinking that delivery charges could be a separate item in the inventory.

I need to be able to supply shipping address, shipper instructions, date and delivery time requested by customer, contact information if different.

I guess some of this could be put in a notes field for the shipper to keep the database simple.

Also in my case I sometimes need to sell a delivery service.  For example item is picked up at AddressA and delivered to AddressB.  But the item never comes to my business address.

If you have any strong direction I should follow to implement this, please let me know.  Otherwise I will add it and submit a pull request at a later time.

I should note that I have never programmed in PHP before, so I spent a good part of a week going through the code and figuring out the inner workings.

**Comment by jekkos** [comment]
Ok thanks for bringing this up here. Which changes to the data model did you foresee to accomodate this change? I suppose that there should be at least one new table containing the shipping info linked to a sale and customer. I would also add a new address table to store multiple customer addresses (for invoices / shipping) and adapt the customer form to add / edit those details.

From a usability view I would stick with max one extra module to consolidates the different ways to view this shipping information. On the other hand you could also add extra info to takings or customers  by adding a new tab in the form.

**Comment by MiiCode2** [comment]
Yes, I definitely need to implement a shipping info table linked to the sale and customer.

It appears that most of the shipped items will go to the same address as the customers address, but I do like the idea of having multiple addresses to select from when necessary, so a shipping address table would be a good fit.

I want to keep the view as simple as possible.  So I will have to think about it some more, but I also want to maintain the same appearance and simplicity as the rest of the ospos system.

I am currently working on another project, so I plan to fit this in where I can.

**Comment by engehab87** [comment]
is there any updates on this feature ?

**Comment by MiiCode2** [comment]
Sorry, I should have probably closed this.  I was implementing this for a friend and he decided to go a different direction.  Somebody else will have to pick up the ball on this if they so choose.

**Comment by mckaygerhard** [comment]
so @MiiCode2 if you dont work anymore on this, please where are the code that you worked? of only bloffing?
