### ISSUE TITLE
Responsive Support and Android Support

### ISSUE THREAD

**Issue by palomita15binaria** [opensourcepos/opensourcepos#593]
Hi guys! :3
I was looking for Point Of Sales that support Responsive or Android Support, this can be possible?

Peace :3

**Comment by daN4cat** [comment]
With version 3.0 we support responsiveness but we did manage to test everything and more test work is required under #437 . Maybe you can help?

With regards to Android support, what do you exactly mean with that?
Have a dedicated app on Android to interact with OSPOS or use a web interface?
The former would require RESTful API support and of course an Android app.
The latter should be there but we need help with testing. Of course barcode scanning and printer support are something of a question mark.

If you could help with anything of the above that will be great. There is far more work we can digest in the two of us that are pulling the story at the moment.

**Comment by palomita15binaria** [comment]
@daN4cat Yeah maybe I can do that but I'm not a professional programmer, I'm going to try something with web app view

**Comment by daN4cat** [comment]
Helping with the testing would do as well.

**Comment by daN4cat** [comment]
@palomita15binaria any feedback on the testing?

**Comment by likozhang** [comment]
@daN4cat work for android now ?

**Comment by pedrojsaba** [comment]
Add this tag in partial/header
<meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by pedrojsaba** [comment]
Add this tag in partial/header
`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by daN4cat** [comment]
@pedrojsaba what's that supposed to do?

**Comment by pedrojsaba** [comment]
When you use a mobile browser, you get this view.
![image](https://user-images.githubusercontent.com/1163827/29638519-1b07cc64-881d-11e7-9034-5a420e99f9c5.png)

**Comment by jekkos** [comment]
Look nice indeed

**Comment by daN4cat** [comment]
Almost... tested sale register and looks awful. No way to resize it or else.

**Comment by daN4cat** [comment]
@pedrojsaba have you checked all the views?

**Comment by pedrojsaba** [comment]
I have tried it from a tablet and embedded in a android view. This according to my need, in my case nobody will make sales from a cell phone.

**Comment by daN4cat** [comment]
The problem is that I cannot commit this change to everybody as not everything works fine.

**Comment by pedrojsaba** [comment]
Ok, no problem.

2017-08-23 16:59 GMT-05:00 FrancescoUK <notifications@github.com>:

**Comment by mckaygerhard** [comment]
hi , the codeigniter framework has a detection tool for browsers, maybe by trying detecting the client browwer, can aded the meta `<meta name="viewport" content="width=device-width, initial-scale=1">` via php code.. 

its a good "hack" and by this way will can make that commit @daN4cat? any opinion ?

**Comment by ashkaps** [comment]
Hi! If testing with mobile/tablet devices is left, this is something I can assist with. I do not have real devices but chrome emulator provides a good option to virtualise most devices.
Is there a list of devices ospos is tested on?
Is there a desirable list of standard devices (I really mean screen size) for which ospos should be supported?
Do we have something on what has been tested so far for mobile devices?

**Comment by mckaygerhard** [comment]
@ashkaps i have some devices where tested and some xperience are not same as emulator for detection, but you can force it and override the identification send by the emulator browser.. and also for testing purposes set on command line of the linux the identification solve it! of couse only works with linux.. on rest are not same that's why its no so easy this thing, real devices must be need for some cases, so the solution must be force the browsing in the proyect as i pointed with codeigniter

**Comment by haicoi311** [comment]
@mckaygerhard I am using version 3.2.3. But I do not see any difference between the desktop web interface and mobile web interface?

**Comment by mckaygerhard** [comment]
@haicoi311 seems do you not used my androit client! that's the main reason, also my mobile changes are not uploaded in the official demo neither in my others demos..

if do you want a demo with those changes must waith i finish the generation documentation and i currently busy in some things! please waith some weeks and i upload those features

**Comment by haicoi311** [comment]
> @haicoi311 seems do you not used my androit client! that's the main reason, also my mobile changes are not uploaded in the official demo neither in my others demos..
> 
> if do you want a demo with those changes must waith i finish the generation documentation and i currently busy in some things! please waith some weeks and i upload those features

Could you show me your mobile version? I have accessed to the osposweb, but I saw some version there but it seem not a mobile version as well as mobile app.

**Comment by mckaygerhard** [comment]
hi @haicoi311 i fixed my demo page and now i have a client prepared for you, and for all, demo1 with 12345678 the client are at https://wetransfer.com/downloads/fc091a7527b1f25b83be5e3406763afa20181204143549/255483c72d07ee2c25f0f63269675ff720181204143549/d019e8

**Comment by mckaygerhard** [comment]
hi @haicoi311 i fixed my demo page and now are mobile compatible, also i have a client prepared for you, and for all, demo1 with 12345678 the client are at https://wetransfer.com/downloads/fc091a7527b1f25b83be5e3406763afa20181204143549/255483c72d07ee2c25f0f63269675ff720181204143549/d019e8

**Comment by haicoi311** [comment]
> mo page and now are mobile compatible, also i have a client prepared for you, and for all, demo1 with 12345678 the client are at

Is this simmilar with the version of @nerv55 ?

**Comment by daN4cat** [comment]
@haicoi311 I would be careful picking up stuff from that guy, you don't know what's inside that app. In any case it's not endorsed by us.
