### ISSUE TITLE
Is deleted in Sales

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#682]
So I am playing with adding the is_deleted function to sales. I added a deleted column to ospos sales and also have the Inventory being updated. Is there anything else I should be aware of?

**Comment by daN4cat** [comment]
Reports would need to consider the is_deleted or not as well as Takings with an additional filter.

**Comment by odiea** [comment]
I am not capable of going any farther with this idea. I am having no luck with filters.

**Comment by daN4cat** [comment]
I would reopen because this is what requested in #677 and #686.

**Comment by odiea** [comment]
Sorry I forgot about this thread. Here is the updated sale.txt
[Sale.txt](https://github.com/jekkos/opensourcepos/files/345272/Sale.txt)

**Comment by jekkos** [comment]
Adding soft delete to sales might have some implications for reporting parts. Will we take these 'deleted' sales into account or not? 
If we really want this feature then I think it just comes down to whether we want to see some of these sales or not. Also the code that corrects inventory based on this should be reviewed.. not an easy task to get this all right

**Comment by odiea** [comment]
I submitted a text copy of the deleted model Sale.txt. I do have the Inventory being updated and also have uncommented out this line. // $this->Item_quantity->reset_quantity($item_id);
It appears to be working on my setup. As far as reports go I just am showing the Undeleted sales. Controller needs the filter added to it and the Sales needs the column added to it. Please check out the coding because I am not as programmer. I also am not deleting any of the items from the Sales so when viewed in takings the full receipt does show.

**Comment by daN4cat** [comment]
I set this to 3.1 because the change will require going through several scenarios and agree what if this or that, I already see that commenting one line we need to agree what to do with the items in the deleted sale.

**Comment by odiea** [comment]
And the table does not update the way it should.

**Comment by odiea** [comment]
Uncommenting this gave me nothing but a headache. I removed it and the tables are updating properly
 // $this->Item_quantity->reset_quantity($item_id); This should not have been there .

**Comment by daN4cat** [comment]
I would need to check but you should say which function is that in.

**Comment by odiea** [comment]
That was a copy and paste from Item.php delete to sale.php delete .

**Comment by daN4cat** [comment]
OK, so the purpose of that is to reset the quantity of items that get deleted.
You shouldn't have to deal with deleting items when you delete a sale, right?
I can't see the connection between the two...

**Comment by odiea** [comment]
It was a copy and paste mistake. Yes when you delete a sale the items need to go back into inventory

**Comment by daN4cat** [comment]
And if the items where deleted you need to undelete them

**Comment by daN4cat** [comment]
And if you undelete a sale you need to restore the items quantity, in case you want to delete/undelete.

Also everytime the inventory is touched a message needs to be logged (deleted sale, undeleted sale POS...)

**Comment by odiea** [comment]
So here is my current code. It is updating the tables just fine. The only issue so far is the Items will also update again from the deleted table. Any ideas for a filter or anything. The following $this->db->where('deleted', 0); has been working fine for Reports showing the proper amounts of Sales not deleted.
public function delete($sale_id, $employee_id, $update_inventory = TRUE) 
	{
		// start a transaction to assure data integrity
		$this->db->trans_start();
                $this->db->where('sale_id', $sale_id);
		if($update_inventory)
		{
			// defect, not all item deletions will be undone??
			// get array with all the items involved in the sale to update the inventory tracking
			$items = $this->get_sale_items($sale_id)->result_array();
			foreach($items as $item)
			{
				// create query to update inventory tracking
				$inv_data = array(
					'trans_date'      => date('Y-m-d H:i:s'),
					'trans_items'     => $item['item_id'],
					'trans_user'      => $employee_id,
					'trans_comment'   => 'Deleting sale ' . $sale_id,
					'trans_location'  => $item['item_location'],
					'trans_inventory'=>$item['quantity_purchased']
				);
				// update inventory
				$this->Inventory->insert($inv_data);

				// update quantities
				$this->Item_quantity->change_quantity($item['item_id'], $item['item_location'], $item['quantity_purchased']);
			}
		}
		 
		// execute transaction*/
		$this->db->update('sales', array('deleted'=>1));
               $this->db->trans_complete();
	     return $this->db->trans_status();
		
	
	}

**Comment by onyema3** [comment]
Any update on this?

**Comment by odiea** [comment]
No there is not.

**Comment by daN4cat** [comment]
@SteveIreland in you new status of Sales, the delete or cancellation should cover this, correct?

**Comment by SteveIreland** [comment]
Yes.  The new canceled status should be updating the tables correctly.  I'll retest to confirm that I didn't overlook anything.  I also want to add the ability to "undelete" a sale.  In this scenario I actually expect to handle it by "Suspending" the canceled sale and that way we can adjust the sale before completing it again.

**Comment by SteveIreland** [comment]
And the ability to cancel or deactivate a sale will be restricted by permission grants

**Comment by daN4cat** [comment]
sounds great @SteveIreland. Thanks!

**Comment by daN4cat** [comment]
@SteveIreland do you think you can work on this?

**Comment by daN4cat** [comment]
@SteveIreland is the sale undelete an implemented feature?

**Comment by SteveIreland** [comment]
Yes, a cancelled sale can be reactivated.  I think I must have run out of time because I didn't change the label of the button  to "Reactivated" and I vaguely recall that I looked at it but I would have had to learn how to work it since it was a bit more complicated than simply conditioning the label. However I'll take another look at it tomorrow.

As it is right now, if you are looking at sales reports and select "Cancelled" as the filter and you edit the cancelled order and click on the Delete button it will actually Reactivate it.  The confirmation will ask you if you want to delete "or reactivate" the sale.

Admittedly it's not very intuitive and I would like to take another shot at it to do it right.

**Comment by SteveIreland** [comment]
The pull request has been resubmitted for this.  Lipstick and rouge has been added where needed.
