### ISSUE TITLE
Add inventory vs sales report

### ISSUE THREAD

**Issue by leominojr** [opensourcepos/opensourcepos#761]
Hello Good Day,

I would like to request if it's okay to have an inventory report vs sales report. Which shows the total deducted quantity vs the sales w/ ref no.? When i click the ref no. it goes to sales report where is the transaction.
![data](https://cloud.githubusercontent.com/assets/9472129/17089806/dbe3f3e2-525c-11e6-9840-f60230d165e0.JPG)

**Comment by jekkos** [comment]
Feel free to add a new report (see how in the wiki) and make pull request for any changes you do.
