### ISSUE TITLE
Deleted stock locations can not be used

### ISSUE THREAD

**Issue by aelhofy** [opensourcepos/opensourcepos#828]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.
### Installation information

ubuntu server 14.04.05 , php 5.5 and mysql

OSPOS 3.0.0 - 4f5ad57 [without JS update files because of login issue]
### Expected behaviour

when stock location is deleted same deleted name could be reused
### Actual behaviour

when stock location is deleted same deleted name could not be reused

Also, why stock locations is tracked and kept in the DB?
### Steps to reproduce the issue

1- add stock location name loc1 and submit 
2- delete stock location  loc1 and submit 
3- try to add a stock location called loc1

**Comment by jekkos** [comment]
This is as designed. You cannot delete a stock location as otherwise you will need to delete sales and receivings as well.

**Comment by jekkos** [comment]
So in this case it's only logical delete.

**Comment by daN4cat** [comment]
Maybe there should be a mean to resume the location if deleted.

**Comment by jekkos** [comment]
This can currently be done by clearing the deleted flag in the db..
