### ISSUE TITLE
Negative Balances can't be tendered & Date in inventory reports

### ISSUE THREAD

**Issue by leominojr** [opensourcepos/opensourcepos#835]
Hello Good Day,

// Negative Balances can't be tendered
I would like to ask if its possible to have an option we choose to allow negative inventory or strictly allowed only positive inventory in tendering a sale?

// Date in inventory reports
I would like to request if its possible to add date filter in inventory reports for us to know what are the items being sold within the desired date.

Thank you so much for this amazing program. God Bless you All

**Comment by daN4cat** [comment]
All is possible it just requires time and people to do the work.
Contributions are always welcome as we cannot do all the work in the two of us and we need help.

**Comment by daN4cat** [comment]
For the first point see also #698

**Comment by leominojr** [comment]
Thank you for understanding and consideration dan. However, i'm still figuring out how to create my own custom reports so that I can publish it here. Thank you so much

**Comment by daN4cat** [comment]
For advance reporting I suggest considering Reportico. Install it as separate application and then query OSPOS database in read only mode, and build the reports you want.
