### ISSUE TITLE
export all records 

### ISSUE THREAD

**Issue by dayano** [opensourcepos/opensourcepos#868]
Hi

in the  reports when i click export to excel
exports only 25 or 100   indicating the combobox

This should show all records in the query.

**Comment by freemail624** [comment]
There is an extension in Bootstrap table to export basic , selected or all data
[Export](http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html)
How to activate it ?

**Comment by waynebr76** [comment]
Thanks how do I add this I cannot find a file called export.html and am not sure how to add this

**Comment by nvk1990** [comment]
@dayano @freemail624 Hi, I was looking at a similar requirement and mine is simple. I always wanted to export all the records irrespective of the records displayed on the page or selected records. 

I was able to achieve it by modifying the code below in **public\dist\opensourcepos.min.js**
From
`exportDataType: "basic"`
To
`exportDataType: "all",`

Not sure if anyone has a simple requirement as I have. If you do, I hope the above one helps!

I'm currently trying to add the functionality of exporting selected, displayed & full set of records. Will keep you posted.

Cheers!

**Comment by daN4cat** [comment]
If you are all OK I can change that value to all by default.

**Comment by SteveIreland** [comment]
Defaulting to all  sounds good to me.

**Comment by sanubari97** [comment]
@nvk1990 I have it edited but still only exporting the current displaying sales.. why ?

**Comment by daN4cat** [comment]
Fixed and in master, but you need to take the code from bintray once the build is completed (15-30 min)

**Comment by daN4cat** [comment]
Still an issue, reopening.

> I've enabled the option to export all in bootstrap-table, however it doesn't look to be right indeed.
> I have even updated bootstrap-table code to the latest in my test environment but it doesn't seem right.
> However I can read that other people face the same issue: wenzhixin/bootstrap-table#2508
> Not sure what else can be done.

**Comment by daN4cat** [comment]
Comment from @jekkos 

> Probably debug the javascript to see what it's doing. If I'm not mistaken it should just call the server endpoint without any query string parameters... should dig into the bstables code and check then I guess

**Comment by AhsenKh** [comment]
How I bypass this issue is, go to **Store Config** section and change **Lines Per Page** to desired lines. Then go to **Items** section and download as *.csv* or any other file.

I had 200+ items, so I changed it to 300 Lines Per Page, temporarily.

**Comment by daN4cat** [comment]
This is now fixed and in master, part of 3.2.0

**Comment by daN4cat** [comment]
Has anyone counter tested this? @AhsenKh can you please check and confirm? Thanks

**Comment by mckaygerhard** [comment]
seems work but in my install, for more thant 8000+ records browser hangs.. i'll test later at night better in non-production env

**Comment by mckaygerhard** [comment]
sorry seems dont work! seems need had to use " tbodySelector" too?

**Comment by jekkos** [comment]
probably browser stops working cause the export happens in the main thread, but that'll be an issue on bootstrap-tables side then

**Comment by mckaygerhard** [comment]
@jekkos have right in part, and the other fault comes from w-gu-indows poor OS to manager memory in the browser.. let's see with a low end machine with 4G ram and 2Ghz cpu:

-   using any OS but in chromium browser version 38 works perfectly
-   using poor OS like guindows but lasted google-chrome browser hangs if records are more than 1000+
-   using debian with LXDE and firefox 28 browser works but if have 8G ram
-   using debian with other desktop like gnomepuach and lasted browser, hangs if are more that 1000

in others hangs mayor export work happened at the cliient side, at the server side, never hangs for me due i used a very older debian lenny with tuned php and hiawatta, apache2 its terrible slower and the sorks web server of the world.. only used to tested the ospos due its the server that used here..

so i cant said any conclusions here due the export of all records depends in many terms of the browser and of the management of the os..

**Comment by jekkos** [comment]
ideally it should use a webworker to do the export, but I'm not sure whether the DOM will be accessible, at least in read only mode

**Comment by mckaygerhard** [comment]
no will not be accesible... export hundred of files with so many stupid eye candy things using a modern webbroser are imposiblle.. 

but using "vanilla-datatables" and purgin that stupid jquery implementation i exported 8000 lines with 7 columns "lorem ipsum"

**Comment by daN4cat** [comment]
What about using Reportico as external tool accessing OSPOS database and you can create all the reports and export the results as you like?

**Comment by mckaygerhard** [comment]
jaja a friend of mine send me that result will happened only if used the fantastic "apache2":

`Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 9 bytes`

when try to use a report that data has 8000+ sales in a simple bad day of sales in a store..

nginx seems have better performance and some users (google searching for a while) reports hiawatta and lighty performed much very much better..

**Comment by mckaygerhard** [comment]
a extra help note: If you aren't sure what your PHP memory limit is set to, it's helpfully included in the error message. The size is reported in bytes, though, in my previous case i setup php for 1G but reported incorrectly the amount.. its suppost that if message said:
"size of 134217728 bytes" means that php memory are setup for 128M but all the php.ini files revised was setup for 1G (based on information of my friend)
seems memory management in guindows are very different if some other process are in use.. (yes he used guindows 10) its a very rare problem due the message does not correspond to the reported.. 
due for 1G of ram setup the report must support almost 8000+ rows.. 

so i think that due both browser and server are running in same host and guindows memory management are very stupid, some cross problem was happened.. 

well but in other hand that guy setup a hacked nginx in cywing and install very hard and got almost 2000 rows.. so well conclusion are obvious about performance and some possibilites..
