### ISSUE TITLE
Pick customers via Barcode scanner?

### ISSUE THREAD

**Issue by sebzan** [opensourcepos/opensourcepos#871]
### Issue, Question or Bug
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

QUESTION:
Have you guys considered using the barcode scanner to pick "existing" customer? In that way you don´t have to search for an existing customer. :)

Best Regards Sebastian Zander - using version 2.4.0 in his association

**Comment by daN4cat** [comment]
Please note that we don't develop features on old versions, so this can happen only from 3.0.0 onward.

With regards picking up customer with barcode, you just need to create a barcode with the customer name and then the scanner will pick it up if you point to the customer input.

What you probably would like to have is a generation of barcodes out of your customer list using OSPOS. That's not supported yet.

Alternative you could associate a barcode to the customer adding a field, I can see cases like loyalty cards fetching customer and applying automatically a discount (already supported).

**Comment by tanakornp** [comment]
If you use Motolora Symbol you can program your scanner to send a command like f1 f2.. etc (check out 123scan Advanced Data Formatting rule) combine with http://www.openjs.com/scripts/events/keyboard_shortcuts/

**Comment by daN4cat** [comment]
@kosimoff see if the change I committed to master works fine now.
