### ISSUE TITLE
Receipt Template

### ISSUE THREAD

**Issue by Modding** [opensourcepos/opensourcepos#908]
I know it is a enhancement, or a feature Request. 

I want to use an Reciept printer that print normal Reciept and i want to change some things in the Reciept. So i need a Template or a File that i can alter for the Reciept.

Like in Germany it is by the Law that you Print the Tax (UST) for each artickle and the price without Tax and With Tax and the Tax Prices of each Tax Rate.

We have two taxes in Germany The normal Tax is 19% and the Tax on food and Bocks is 7%. So we must take the two Tax rates in the Reciept.

**Comment by daN4cat** [comment]
At the moment you can select two receipt layouts, default and short version.

Check `application/views/sales/receipt_default.php` & `receipt_short.php`, create your one and we can add it to the list and selection from Store Config.

**Comment by martadinata666** [comment]
![layout](https://cloud.githubusercontent.com/assets/2433562/19418931/3f044ff8-93f8-11e6-8577-1a079bb4282f.png)

sorry for bumping another your thread @Modding , because i had the same. i need to add the ISBN number in receipt, because my shop item is "one type product, many serials". The receipt indeed can print serial but the serial entered when selling product and many times forgotten that things. thanks

**Comment by daN4cat** [comment]
@martadinata666 there is a means to serialise an item and add at sale and print it in the receipt.

**Comment by daN4cat** [comment]
@Modding any chance you want to contribute something here? I'm under the impression you created a new one based on another issue comment.

**Comment by xtruthx** [comment]
my i am willed to help here. cause without printing taxes in a receipt als in the other statistics it is not really usable in germany due too the law.
As i can see you have a part to show taxes or do i missunderstood something wrong there:
`<?php
                if ($this->Appconfig->get('receipt_show_taxes'))
                {
                ?>
                        <tr>
                                <td colspan="3" style='text-align:right;border-top:2px solid #000000;'><?php echo $this->lang->line('sales_sub_total'); ?></td>
                                <td style='text-align:right;border-top:2px solid #000000;'><?php echo to_currency($this->config->item('tax_included') ? $tax_exclusive_subtotal : $discounted_subtotal); ?></td>
                        </tr>
                        <?php
                        foreach($taxes as $name=>$value)
                        {
                        ?>
                                <tr>
                                        <td colspan="3" class="total-value"><?php echo $name; ?>:</td>
                                        <td class="total-value"><?php echo to_currency($value); ?></td>
                                </tr>
                        <?php
                        }
                        ?>
                <?php
                }
                ?>`

**Comment by odiea** [comment]
Store Config - Receipt  Make sure Show taxes is checked. It shows if you check that.

**Comment by xtruthx** [comment]
yeh got it now.  And it visible on the receipt.

**Comment by jekkos** [comment]
you can add / select a template at will now in config screen. Will close this one now.
