### ISSUE TITLE
Find a stock value for a point in time

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#938]
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.
### Installation information

N/A
### Expected behaviour

Get a sensible stock value for a certain point in time
### Actual behaviour

I would like to post two queries here to find a value for a certain point in time. This query takes followig into account
- Will add/substract inventory quantities to the current quantity value for each value to get a current quantity at a defined point in time (in this case 2016-01-01)
- Will filter out a set of items that was last purchased after a certain date (in this case 01-01-2015)
- Can anyone spot an error in the second query and perhaps also explain what is wrong?

-- GOOD

``` sql

select 
    max(trans_date), 
    cost_price as price, 
    corr.correctie, 
    IF(corr.correctie IS NULL,quantity,quantity-corr.correctie) as hoeveelheid, name, ospos_items.item_id
from ospos_inventory
join ospos_items on ospos_items.item_id = ospos_inventory.trans_items

left join 
    (select 
        trans_items,
        sum(trans_inventory) as correctie 
    from ospos_inventory
    where trans_date between date('2016-01-01') and now()
    group by trans_items) 
as corr on corr.trans_items = ospos_items.item_id

join 
    (select 
        max(trans_date) as last_date, 
        trans_items, 
        trans_inventory 
     from ospos_inventory 
     group by trans_items 
     having last_date > date('2015-01-01') and trans_inventory > 0) 
as lastbuy on lastbuy.trans_items = ospos_items.item_id

join ospos_item_quantities on ospos_item_quantities.item_id = ospos_items.item_id
group by ospos_inventory.trans_items having hoeveelheid > 0 order by max(trans_date) asc

```

-- BAD

``` sql
select 
    max(trans_date), 
    cost_price as price, 
    corr.correctie, 
    IF(corr.correctie IS NULL,quantity,quantity-corr.correctie) as hoeveelheid, name, ospos_items.item_id
from ospos_inventory
join ospos_items on ospos_items.item_id = ospos_inventory.trans_items

left join 
    (select 
        trans_items, 
        sum(trans_inventory) as correctie
    from ospos_inventory
    where trans_date between date('2016-01-01') and now()
    group by trans_items) 
as corr on corr.trans_items = ospos_items.item_id

join 
    (select 
        max(trans_date) as last_date, 
        trans_items, 
        trans_inventory 
    from ospos_inventory 
    where trans_inventory > 0 
    group by trans_items ) 
as lastbuy on lastbuy.trans_items = ospos_items.item_id and last_date > date('2015-01-01')
join ospos_item_quantities on ospos_item_quantities.item_id = ospos_items.item_id
group by ospos_inventory.trans_items having hoeveelheid > 0 order by max(trans_date) asc
```

**Comment by odiea** [comment]
The only difference I can see is the last_date is included in the first select but not the second select.
~~~
(select 
        max(trans_date) as last_date, 
        trans_items, 
        trans_inventory 
     from ospos_inventory 
     group by trans_items 
     having last_date > date('2015-01-01') and trans_inventory > 0) 

(select 
        max(trans_date) as last_date, 
        trans_items, 
        trans_inventory 
    from ospos_inventory 
    where trans_inventory > 0 
    group by trans_items )

**Comment by jekkos** [comment]
Main difference between the two is indeed that one statement in where or having. I might want to retest it on Mysql 5.7 toi see whether both work with full_group_by enabled.

**Comment by data2base** [comment]
Hi! Im looking to get my stock balance on 28/02/2019 will this work for me as i`m not getting all my stock items? Please assist with any adjustments required?

**Comment by jekkos** [comment]
How do you mean, you're not getting all your stock items? Indeed the items with a zero quantity at that date are filtered out.

**Comment by data2base** [comment]
Yes not all stock items are listed. Should i send you my db?
