### ISSUE TITLE
From Bower to npm v3.0 package.json, from grunt to gulp

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#975]
I read that Bower is somehow not necessary anymore given npm v3.0 is out.

Should we switch to npm v3.0 once forever?

**Comment by jekkos** [comment]
Funny I looked at exactly the same thing today. If we switch to npm I guess we'll need to adapt the build pipeline as there's quite some bower specific stuff in there? Also grunt is being abandoned for gulp these days

**Comment by SteveIreland** [comment]
Gulp is an awesome bait for flounders here on the East cost of the USA. I use it almost exclusively!   Wait ... am I on the wrong Web site again?

**Comment by daN4cat** [comment]
OK, it sounds like we need to two changes to make on the scripting side.
I will read about gulp as I'm not familiar with it. This is not the type of stuff I'm in touch normally outside here.

**Comment by jekkos** [comment]
Yes I spend a lot of time to refine the grunt build as it is now. Think this is not of the highest priority currently and will probably focus on other stuff first. But it's good to have it in the tracker once somebody feels up to it.

**Comment by jekkos** [comment]
I mean that current milestone might even be a bit too ambitious..

**Comment by daN4cat** [comment]
Set 4.0.0, not urgent indeed.

**Comment by jekkos** [comment]
Duplicate issue, will close
