### ISSUE TITLE
Adding a New Module

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#991]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
localhost
WAMP 2.5
PHP 5.5
MySQL 5.6
Apache 2.4

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
How can i add a new module for extra functionality such as promotions...

**Comment by gentlesolo** [comment]
Am also interested in adding An expense module... I will to understand the coding format or structure

**Comment by jekkos** [comment]
I guess this is something that could use some explanation on the wiki.

**Comment by vimkaf** [comment]
@jekkos @gentlesolo @daN4cat @bill-goldberg What is the proper way of doing this without breaking the app, I am currently adding an accounts module but I am having problem displaying the module name correctly, Instead of displaying Accounts on the homepage I am getting module_accounts(TBD)

**Comment by daN4cat** [comment]
I assume this is sorted, right?
